### ISSUE TITLE
Requesting: realmd, freeipa-client, oddjob

### ISSUE THREAD

**Issue by ABotelho23** [chaotic-aur/packages#1001]
- Link to the package(s) in AUR:
https://aur.archlinux.org/packages/freeipa-client/
https://aur.archlinux.org/packages/realmd/
https://aur.archlinux.org/packages/oddjob/

- Utility this package has for you:
This package is pretty fundamental to anything that approaches a more enterprise-y setup. Homelab users in particular would benefit tremendously. Arch users that need to join a machine to FreeIPA/Active Directory would be using these packages.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [X] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [X] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [X] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [X] NO

- Does the package's license allows us to redistribute it?:

  - [X] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [X] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [X] YES

**Comment by ABotelho23** [comment]
Was freeipa-* removed from the repo? I've noticed it's not showing up when I install it.

**Comment by Technetium1** [comment]
No, they're just not building for some reason.

**Comment by Technetium1** [comment]
@ABotelho23 They're back.

**Comment by ABotelho23** [comment]
Should the dependencies be building as well? I think more have been added since before. Unless I setup the "normal" AUR, I can't seem to install it.

**Comment by Technetium1** [comment]
`python-yubico` has been [orphaned since `2019-10-02`](https://aur.archlinux.org/packages/python-yubico), but is new enough.
`certmonger` is [Flagged out-of-date (2022-02-21)](https://aur.archlinux.org/pkgbase/certmonger/flag-comment), but is also new enough.

**Comment by Technetium1** [comment]
[python-ipaclient](https://aur.archlinux.org/packages/python-ipaclient) fails (?)

**Comment by ABotelho23** [comment]
> [python-ipaclient](https://aur.archlinux.org/packages/python-ipaclient) fails (?)

Fails, as in it doesn't build?

**Comment by Technetium1** [comment]
I suspect so, I need more help to know for certain..

**Comment by Technetium1** [comment]
Fine now as far as I can tell, please comment again if that's not the case.

**Comment by xiota** [comment]
`realmd` not building because missing makedep.  Maintainer hasn't responded to comment and flag.  May drop if not fixed "soon".  Metrics 26.

**Comment by xiota** [comment]
Month is long enough to wait... How important is `realmd`?  Is it worth interfere and orphan request?  Or drop?

**Comment by Technetium1** [comment]
@xiota For some _enterprise_ users, it is considered a critical nessecity, but outside of that, it is useless. I think we can safely remove it until requested again [after being fixed].

**Comment by BPplays** [comment]
@xiota is there a reason why freeipa-client was removed too?

**Comment by xiota** [comment]
From the description in the request, they didn't appeat useful independently of each other.

**Comment by BPplays** [comment]
@xiota i assume you mean 'appear'. i use freeipa-client but i've never used realmd

**Comment by xiota** [comment]
@BPplays Please open a new request for `freeipa` with a description that is specific to it.
