### ISSUE TITLE
[Request] webex-bin

### ISSUE THREAD

**Issue by nandgator** [chaotic-aur/packages#1004]
## 👶 For requesting new packages

- https://aur.archlinux.org/packages/webex-bin

- Used to attend virtual meetings, all over the world. 

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [X] No, but yes for a great amount
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [X] YES
  - [ ] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [X] YES

- Have you tested if this package builds in a clean chroot?:

  - [X] YES
  - [ ] NO

- Does the package's license allows us to redistribute it?:

  - [ ] YES
  - [X] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [X] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [X] YES

**Comment by papadakospan** [comment]
`warning: webex-bin: local (41.12.0.20899-1) is newer than chaotic-aur (41.10.0.20371-1)`
