### ISSUE TITLE
[Request] firefly-iii

### ISSUE THREAD

**Issue by joe733** [chaotic-aur/packages#1008]
## 👶 Requesting new package

- https://aur.archlinux.org/packages/firefly-iii/

- Personal finance management

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [X] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [X] YES
  - [ ] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [X] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [X] NO

- Does the package's license allows us to redistribute it?:

  - [X] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [X] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [X] YES

**Comment by Technetium1** [comment]
@dr460nf1r3 you've gotten a reply:
angelsl commented on [2021-10-25 15:34 (UTC)](https://aur.archlinux.org/packages/firefly-iii#comment-832800)
> @dr460nf1r3
It doesn't require root; the warning from Composer is because it's running in fakeroot.
If you find a way to silence that warning, let me know.

**Comment by joe733** [comment]
I guess this can be closed as it's available @ `chaotic-aur/firefly-iii`

![image](https://user-images.githubusercontent.com/38415384/166153895-07e5c3ae-deb4-4cc7-aeaf-ce9742fe1ffc.png)

**Comment by dr460nf1r3** [comment]
Agreed! :)

**Comment by JC5** [comment]
@dr460nf1r3 see this page on how to suppress the root warning from composer:

https://getcomposer.org/doc/03-cli.md#composer-allow-superuser
