### ISSUE TITLE
jamesdsp did not update in chaotic-aur

### ISSUE THREAD

**Issue by coxackie** [chaotic-aur/packages#1009]
## 👴 For reporting outdated packages

- (If available) Link to latest build ([find it here](https://aur.archlinux.org/packages/jamesdsp/))

- Package name: `jamesdsp`

- Latest build: `v2.2-1`

- Latest version available: `v2.1-1`

- Have you tested if the latest version of the package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

(but I did build it locally and there was no issue.)

**Comment by coxackie** [comment]
sorry to come back to this, but `jamesdsp` PKGBUILD got updates two days ago (https://aur.archlinux.org/packages/jamesdsp/), but the version in chaotic is still the previous one...

**Comment by dr460nf1r3** [comment]
No need to say sorry, its nice that you report things as it helps keeping things going 😌 The package got updated!

**Comment by coxackie** [comment]
@dr460nf1r3 many thanks for such prompt response. Just for future reference: is there something not allowing this to be updated automatically? I am just asking to know whether I should be making requests in the future soon as I see the update (I am subscribed on github). It is not updated so often, so it is not a big deal to do so.

**Comment by dr460nf1r3** [comment]
Usually they get rebuilt every hour, I'm not sure why it didn't do it in this case. There wasn't even an error log. Anyways, if something is wrong feel free to just create an issue, they exist for this reason 🙂

**Comment by coxackie** [comment]
and, once again, unfortunately, this did not update. It is not 2.4-1 in the AUR, 2.3-5 still in chaotic.

**Comment by dr460nf1r3** [comment]
Just built it manually! :)
