### ISSUE TITLE
[Remove] stacer, stacer-git

### ISSUE THREAD

**Issue by ghost** [chaotic-aur/packages#1013]
## 👶 For requesting new packages

https://github.com/oguzhaninan/Stacer
- Link to the package(s) in AUR: https://aur.archlinux.org/packages/stacer-git
- Utility this package has for you:
  Describe it here, why you use this package, how it can be helpful.
^-"System Optimizer and Monitoring"
- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [x] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by xiota** [comment]
Dropping because last release was May 2019.  Upstream repo has notice: This project has been abandoned. There will be no further releases.
