### ISSUE TITLE
[Request] spotify-adblock-git

### ISSUE THREAD

**Issue by coxackie** [chaotic-aur/packages#1014]
- Link to the package(s) in AUR: [https://aur.archlinux.org/packages/spotify-adblock-git/](https://aur.archlinux.org/packages/spotify-adblock-git/)

- Utility this package has for you:

  It blocks annoying ads for the spotify official client (free accounts). I understand this may be a bit controversial, but I can attest that it makes a huge difference in listening experience.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by coxackie** [comment]
@dr460nf1r3 All of a sudden I do not see `spotify-adblock-git` in the chaotic repo. Was it removed?

**Comment by dr460nf1r3** [comment]
Sorry, I forgot answering here! I was getting rid of packages I had in my personal list, those I didn't use anymore to save processing power for other packages. Added it back tho, since there was demand ;)

**Comment by coxackie** [comment]
There is and will always be demand for this. Thank you very much.
