### ISSUE TITLE
[Request] ProtonUP-QT Added To Chaotic-aur

### ISSUE THREAD

**Issue by Kandelai** [chaotic-aur/packages#1020]
Requesting [ProtonUP-QT](https://github.com/DavidoTek/ProtonUp-Qt/releases) to be added to Chaotic-AUR

- Link to the package(s) in AUR: 
Package is not currently in AUR, but is partly based on [ProtonUP](https://github.com/AUNaseef/protonup) which is in AUR and Chaotic-aur

ProtonUP-QT is located; [Here](https://github.com/DavidoTek/ProtonUp-Qt)

- Utility this package has for you:

  This package does more than ProtonUP which really on supports adding Proton versions to Lutris and proton-ge-custom and proton-ge-custom-bin which only adds the latest Proton-GE to Steam. 

ProtonUP-QT shows all installed versions and allows you to easily remove or install new ones from both Lutris and Steam. Supports Proton-GE for Steam and Wine-GE, Lutris-Wine and Kron4ek's Vanilla Wine-Builds for Lutris.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ x] YES
  - [ ] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ x] YES
  - [ ] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x ] YES

- Have you tested if this package builds in a clean chroot?:

  - [x ] YES
  - [ ] NO

- Does the package's license allows us to redistribute it?:

  - [ x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [ x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x ] YES

**Comment by dr460nf1r3** [comment]
Update: I added the application using the testing PKGBUILD from here https://github.com/DavidoTek/ProtonUp-Qt/issues/1#issuecomment-954136696, now waiting for it to be published to AUR.

**Comment by Kandelai** [comment]
Thank you. Yes they do need a .desktop app, had to make mine manually. You are the best!
