### ISSUE TITLE
[Remove] fzf-tab-bin-git

### ISSUE THREAD

**Issue by brendenhoffman** [chaotic-aur/packages#1021]
- Link to the package(s) in AUR: https://aur.archlinux.org/packages/fzf-tab-bin-git/

- Utility this package has for you: 

fzf tab completion utility for zsh. Very fast and interactive. Optional binary module is compiled for extra speed.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [X] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [X] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [X] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [X] NO - I am a little unsure how that should be done, but I would give it no reason that it shouldn't build

- Does the package's license allows us to redistribute it?:

  - [X] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - I just created this package as an upgrade to fzf-tab-git, which was added to chaotic-aur several months ago.

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [X] YES

**Comment by xiota** [comment]
Dropped because broken and maintainer MIA.
