### ISSUE TITLE
[Request] Protonvpn-cli

### ISSUE THREAD

**Issue by brendenhoffman** [chaotic-aur/packages#1022]
- Link to the package(s) in AUR: https://aur.archlinux.org/packages/protonvpn-cli/

- Utility this package has for you:

  Official Protonvpn cli tool. Currently the protonvpn-gui has a massive memory leak and the cli is not obsolete. This is how I use Protonvpn until the gui does not have performance issues and can be autostarted.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [X] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [X] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [X] YES - the gui and unofficial cli tool are in the chaotic-aur

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [X] NO

- Does the package's license allows us to redistribute it?:

  - [X] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [X] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [X] YES

**Comment by Technetium1** [comment]
Upstream has been archived, and Arch is no longer a target.
