### ISSUE TITLE
[Request] zenmap

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#1027]
## 👶 For requesting new packages

- Link to the package(s) in AUR: [zenmap](https://aur.archlinux.org/packages/zenmap/)

- Utility this package has for you:

  Zenmap is the official GUI for nmap: https://nmap.org/zenmap

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES, as long as there are not modifications made: https://nmap.org/npsl/npsl-annotated.html
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by Technetium1** [comment]
@Stunkymonkey I would really like to add this back, can you please update `zenmap`? Python3 migration is complete upstream, and many things are fixed.

**Comment by Stunkymonkey** [comment]
nice to know, that it got merged. Based on the package naming guidelines `zenmap-git` would be the appropriate name for the current software state. the `zenmap` package will be updated if the package is released.
at the moment please use [`zenmap-python3-git`](https://aur.archlinux.org/packages/zenmap-python3-git)

**Comment by xiota** [comment]
Dropping because moved to extra.  Metrics 311.
