### ISSUE TITLE
[request] Atomic Wallet

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#1031]
- Link to the package(s) in AUR: [Atomic Wallet](https://aur.archlinux.org/packages/atomicwallet/)

- Utility this package has for you:

Having a secure and efficient digital wallet in my system was really necessary, especially despite my many purchases through tron currency.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [x] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

- Does the package's license allows us to redistribute it?:

  - [X] YES 
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by xiota** [comment]
Dropping because EOL Electron/22.3.14.  Metrics 42.
