### ISSUE TITLE
[Request] pfetch-git, freshfetch-git, novafetch-git, rufetch, ufetch-git, bitfetch-git, aurafetch-git

### ISSUE THREAD

**Issue by maklamj** [chaotic-aur/packages#1034]
## 👶 For requesting new packages

- Link to the package(s) in AUR: https://aur.archlinux.org/packages/pfetch-git/	https://aur.archlinux.org/packages/freshfetch-git/	https://aur.archlinux.org/packages/novafetch-git/	https://aur.archlinux.org/packages/rufetch/	https://aur.archlinux.org/packages/ufetch-git/	https://aur.archlinux.org/packages/aurafetch-git/	https://aur.archlinux.org/packages/bitfetch-git/

- Utility this package has for you:
    Shows various info about OS/hardware and also it's fun.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by xiota** [comment]
Dropping freshfetch for poor maintenance.  Last release 2021.  Last commit 2022.

**Comment by xiota** [comment]
Dropped ufetch-git because AUR package is orphaned and there are too many fetch clones.  Metrics 25.
