### ISSUE TITLE
Request snap-pac-grub

### ISSUE THREAD

**Issue by adoldrol** [chaotic-aur/packages#1036]
## 👶 For requesting new packages

- Link to the package(s) in AUR: https://aur.archlinux.org/packages/snap-pac-grub

- Utility this package has for you:
I used with snapper is a Pacman hook to update GRUB entries for grub-btrfs after snap-pac made snapshots

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [X] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [X] YES
  - [ ] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [X] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

- Does the package's license allows us to redistribute it?:

  - [X] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [X] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [X] YES

**Comment by xiota** [comment]
Dropping because AUR package is orphaned.  Metrics 48.
