### ISSUE TITLE
[Outdated] tok-git

### ISSUE THREAD

**Issue by userofryzen** [chaotic-aur/packages#1037]
Note:

- We will delete issues not following this template!
- You can add new information besides the ones required here.
- You can delete the subsections that are not related to your issue.

## 👴 For reporting outdated packages

- (If available) Link to latest build ([find it here](https://builds.garudalinux.org/repos/chaotic-aur/logs/)): [some-package.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/some-package.log)

- Package name: tok-git`

- Latest build: three days ago for example

- Latest version available: any

- Have you tested if the latest version of the package builds in a clean chroot?:

  - [ ] YES
  - [X] NO

**Comment by dr460nf1r3** [comment]
This one misses a new dependency we don't have in repo yet 👀 adding it and rebuilding afterwards

**Comment by userofryzen** [comment]
> This one misses a new dependency we don't have in repo yet eyes adding it and rebuilding afterwards Cmake is also missing in makedepends, reporting to AUR. Edit: even with proper makedeps build is failing, reported and waiting for a fix now :)

where is reported? to see the issue, the error and so on if its possible. 

Thanks!

**Comment by dr460nf1r3** [comment]
I reported the issue at the respective AUR page.

**Comment by userofryzen** [comment]
I see no movement on aur website what a weird thing.

**Comment by dr460nf1r3** [comment]
Maintainers do have lifes as well 😉

**Comment by userofryzen** [comment]
Oh yeah i know. It s simple an observation

**Comment by userofryzen** [comment]
there is an updated, I think it can be compiled now! 
@dr460nf1r3 when you can give it a try pls

**Comment by dr460nf1r3** [comment]
I tried building it as I got a notification about the update, there is still a blocker left sadly. But I reported it at the AUR page, hoping for the best :)

**Comment by userofryzen** [comment]
I have been able to compile it right now, test if you can pls!

In addition when is the routine  executed?

**Comment by dr460nf1r3** [comment]
Eeeh, I got good news 😋  It did in fact build after adding 3 new dependencies to Chaotic and adding a last missing dep to the PKGBUILD. Glad to see it happen finally 🥳

**Comment by userofryzen** [comment]
> Eeeh, I got good news yum It did in fact build after adding 3 new dependencies to Chaotic and adding a last missing dep to the PKGBUILD. Glad to see it happen finally partying_face About the routines: that depends on the routine it is in, in this case its every 2. hour :)

i mean for chromium-wayland-vaapi ones, may be this ones is on other routine

Thanks for the news!

**Comment by dr460nf1r3** [comment]
Posted an update on that in the corresponding issue :)

**Comment by userofryzen** [comment]
seen, thanks!
