### ISSUE TITLE
[Request]  Add obs-studio-tytan652 and obs-studio-rc

### ISSUE THREAD

**Issue by tytan652** [chaotic-aur/packages#1038]
## 👶 For requesting new packages

- Link to the package(s) in AUR: 
  - [obs-studio-tytan652](https://aur.archlinux.org/packages/obs-studio-tytan652/)
  - [obs-studio-rc](https://aur.archlinux.org/packages/obs-studio-rc/)

- Utility this package has for you:
  - obs-studio-tytan652 is a OBS Studio package with almost all feature with some QOL PR added and sometimes backported fix. It is also build with the CEF version that OBS vendored on Linux. You can ask on their discord this is also the one who is recommended when someone with a Arch base have issue with dependencies or ask for missing features.
  - obs-studio-rc is a OBS Studio package for OBS Studio that follow the beta (release candidates) version branch. Allow user to try OBS Studio RCs. Will may need cef-minimal-obs-rc-bin in the future.

Since I'm the maintainer of those two package and many OBS related package on AUR, you can consider me biased because these are my packages. But when I read messages about people appreciating my packages on OBS discord, I seriously think that I should ask you to add it for the ones that may use your repository.

I have also many OBS plugins packages but I let other users request them.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [x] No, but yes for a great amount for obs-studio-tytan652.
  - [x] No, but yes for a few for obs-studio-rc.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [x] YES for obs-studio-rc
  - [ ] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by dr460nf1r3** [comment]
Is adding the `-rc` really beneficial when we have `-git` already? :eyes:

**Comment by tytan652** [comment]
RC is the beta cycle of OBS Studio which allow users to test the RC when the OBS Project release it (with the right CEF unlike the `-git` one).

Also some people don't want to the git packages but could use beta version package.

If you don't see it beneficial you can close the PR without adding it.

**Comment by dr460nf1r3** [comment]
I added it nevertheless :)

**Comment by xiota** [comment]
Dropping `obs-studio-rc` and `obs-studio-browser` (#886).  Doesn't really make sense to have five slightly different versions of `obs-studio`.  The following will remain:

* `extra/obs-studio`
* `chaotic-aur/obs-studio-git`
* `chaotic-aur/obs-studio-tytan652` (more popular than -browser or -rc)

**Comment by novadragonDOTspace** [comment]
vlc-plugin-luajit needs an update, or obs-studio-tytan652 and the system install of vlc wont cooperate, cause vlc now demands a version higher than provided.
