### ISSUE TITLE
[Request] thunar-devel

### ISSUE THREAD

**Issue by lynoxy** [chaotic-aur/packages#1039]
## 👶 For requesting new packages

- Link to the package(s) in AUR: [https://aur.archlinux.org/packages/thunar-devel/](https://aur.archlinux.org/packages/thunar-devel/)

- Utility this package has for you:

  Development version of thunar has important new features like split view and recently used files.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by Technetium1** [comment]
[Here's the build log](https://builds.garudalinux.org/repos/chaotic-aur/logs/thunar-devel.log). It wants versions of packages that are obviously [not yet released as stable](https://www.xfce.org/download/changelogs), as of 20 hours ago when it was updated.

[This comment](https://aur.archlinux.org/packages/thunar-devel#comment-826700) said:
> I didn't need any custom PKGBUILD for thunar-devel, upon installing it with pikaur it asked me for the 3 devel packages to be installed -one at a time-, then it was built flawlessly.
exo-devel, libxfce4ui-devel, libxfce4util-devel.
Unless the PKGBUILD is changed, this will not build without it's dependencies.

- [exo-devel](https://aur.archlinux.org/packages/exo-devel) = `4.17.1-1` -> `>=4.17.0` is required.
- [libxfce4ui-devel](https://aur.archlinux.org/packages/libxfce4ui-devel) = `4.17.6-1` -> `>=4.17.6` is required.
- [libxfce4util-devel](https://aur.archlinux.org/packages/libxfce4util-devel) = `4.17.2-1` -> `>=4.17.2` is required

**Comment by lynoxy** [comment]
Sorry, i don't use xfce anymore, at that time i was able to use thunar-devel without any problem.
