### ISSUE TITLE
[Request] linux-xanmod-tt

### ISSUE THREAD

**Issue by ojaksch** [chaotic-aur/packages#1042]
- Link to the package(s) in AUR: [linux-xanmod-tt](https://aur.archlinux.org/packages/linux-xanmod-tt/)

- Utility this package has for you:

 The Linux kernel and modules with Xanmod and "tt" patches, the successor to the CacULE patchset.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [X] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [X] YES
  - [ ] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [X] YES

- Have you tested if this package builds in a clean chroot?:

  - [X] YES
  - [ ] NO

- Does the package's license allows us to redistribute it?:

  - [X] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [X] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [X] YES

**Comment by federicotorrielli** [comment]
+1

Also, the removal of the *now* old linux-xanmod-cacule and linux-xanmod-cacule-headers

**Comment by ojaksch** [comment]
Great, thank you!
