### ISSUE TITLE
[Outdated] Flutter

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#1043]
- (If available) Link to latest build ([flutter](https://aur.archlinux.org/packages/flutter/))

- Package name: `Flutter`

- Latest build: `v2.2.3-1`

- Latest version available: `v2.5.3-1`

- Have you tested if the latest version of the package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

**Comment by simondvt** [comment]
If I run `flutter --version` I see I have the latest flutter 2.5.3, but the package itself has version 2.2.3-1 and pacman wants to update it, but if I try I get [these errors](https://pastebin.com/tZhDdKN8).

What should I do?

**Comment by dr460nf1r3** [comment]
I would assume that the files have been put there by flutter without being installed by pacman itself, in this case you could `--overwrite "*"`.

**Comment by simondvt** [comment]
> I would assume that the files have been put there by flutter without being installed by pacman itself, in this case you could `--overwrite "*"`.

It worked! Thanks.

**Comment by dr460nf1r3** [comment]
The package itself got updated by me, but I couldn't check for flutter actually being in the list of packages yet so I left the issue open for now 👀

**Comment by PedroHLC** [comment]
It is in `dragon-cluster/hourly.txt`
