### ISSUE TITLE
what are the packages that are outside the aur ??

### ISSUE THREAD

**Issue by D0nnieD4rk0** [chaotic-aur/packages#1047]

**Comment by dr460nf1r3** [comment]
Could you be more precise with that question please? 👀

**Comment by D0nnieD4rk0** [comment]
> Could you be more precise with that question please? eyes

like the linux-tkg kernels for example

**Comment by PedroHLC** [comment]
Clone this repository, run `grep ':' **.txt`, everything you see there is the packages we're not getting from AUR. (Note that there will be a few from AUR, it's because we force them to hourly build)

**Comment by D0nnieD4rk0** [comment]
im asking cuz i thought the repo was entirely just precompiled aur packages and it seemed a little strange how can i rly trust these if they dont even come from the aur

**Comment by D0nnieD4rk0** [comment]
a few secs too late damn

**Comment by PedroHLC** [comment]
> a few secs too late damn

:sweat_smile: don't worry, if you need to discuss security details, feel free to keep using this issue.
