### ISSUE TITLE
[Request] nvidia-utils-nvlax

### ISSUE THREAD

**Issue by Smart123s** [chaotic-aur/packages#1048]
## 👶 For requesting new packages

- Link to the package(s) in AUR: https://aur.archlinux.org/packages/nvidia-utils-nvlax/

- Utility this package has for you:

  Does the same thing as [nvidia-utils-keylase](https://aur.archlinux.org/packages/nvidia-utils-keylase/), but that package will be [deleted](https://aur.archlinux.org/packages/nvidia-utils-keylase/#comment-833261) soon.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

- Does the package's license allows us to redistribute it?:

  - [ ] YES
  - [x] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by zany130** [comment]
wouldn't this one be better as it does not depend on a specific version of the Nvidia driver? https://aur.archlinux.org/packages/nvlax-git

**Comment by Smart123s** [comment]
I don't think that we can say that one of them would be better than the other. They just work differently.

nvidia-utils-nvlax patches the driver, while building the package. This has the advantage, that no post installation steps (ex. pacman hooks) are required. Furthermore, the maintainer of the package (hopefully) tests the patched driver, before updating, so it's less likely to break. However, this has the disadvantage of slower updates.

On the other hand, nvlax-git doesn't need its maintainers attention to work with a newer version of the driver.

I prefer not having to work with pacman hooks, but that's just my opinion. Maybes we could have both packages? nvlax-git is not a small package after all.

Also, nvidia-tweaks does the same things as nvidia-keylase-patch-git, but the former one actually works.
