### ISSUE TITLE
[Request] GMenu

### ISSUE THREAD

**Issue by Krutonium** [chaotic-aur/packages#1049]
Note:

- We will delete issues not following this template!
- You can add new information besides the ones required here.
- You can delete the subsections that are not related to your issue.

## 👶 For requesting new packages

- Link to the package(s) in AUR: [gmenu](https://aur.archlinux.org/packages/gmenu/)

- Utility this package has for you:
It's required for some gnome extensions to work.

  Describe it here, why you use this package, how it can be helpful.
Extensions like [Arc Menu](https://extensions.gnome.org/extension/3628/arcmenu/) Require this to be installed to function.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

- Does the package's license allows us to redistribute it?:

  - [x] [YES](https://code.rocketnine.space/tslocum/gmenu/src/branch/master/LICENSE)
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by Krutonium** [comment]
Thanks :)

**Comment by dr460nf1r3** [comment]
Always welcome 😊

**Comment by xiota** [comment]
Dropping because AUR package is orphaned.  Metrics 55.
