### ISSUE TITLE
[Request] liblnk

### ISSUE THREAD

**Issue by ghost** [chaotic-aur/packages#1063]
## 👶 For requesting new packages

- Link to the package(s) in AUR:
https://aur.archlinux.org/packages/liblnk-git/
https://aur.archlinux.org/packages/liblnk-tools-git/

- Utility this package has for you:
Optional dependency for exe-thumbnailer which provides .lnk thumbnails.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [x] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by Technetium1** [comment]
This depends on python2, so it will be removed. See #1958
