### ISSUE TITLE
request google-messages

### ISSUE THREAD

**Issue by robson-66** [chaotic-aur/packages#1067]
## 👶 For requesting new packages

- Link to the package(s) in AUR: [google-messages](https://aur.archlinux.org/packages/google-messages/)

- Utility this package has for you:

  Describe it here, why you use this package, how it can be helpful.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [x] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [x] YES
  - [ ] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by Technetium1** [comment]
* This package seems fantastic, I love it.
* Package is not useful for feature testing/preview
* Does not seem to build in a clean chroot
```
==> Making package: google-messages 1.3.0-1 (Tue 16 Nov 2021 10:57:22 PM EST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Installing missing dependencies...
error: target not found: nodejs-nativefier
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
-> nodejs-nativefier
==> ERROR: Could not resolve all dependencies.
```

**Comment by robson-66** [comment]
Because this package needs `nodejs-nativefier` dependencies to build. And what command did you issue to build the package? It should be `makepkg -sirc` and the `nodejs-nativefier` package will be downloaded from the chaotic-aur repo.

**Comment by PedroHLC** [comment]
> package will be downloaded from the chaotic-aur repo.

This was probably some confusion in my part, I should make clear that by "clean chroot" it would be: `base` + `base-devel` + chaotic

**Comment by robson-66** [comment]
Thanks Nico.

**Comment by xiota** [comment]
Dropping because uses EOL Electron/19.0.14.  Metrics 32.
