### ISSUE TITLE
Cannot install chaotic-mirrorlist, "package invalid or corrupted"

### ISSUE THREAD

**Issue by ayesse** [chaotic-aur/packages#1069]
Note:

- We will delete issues not following this template!
- You can add new information besides the ones required here.
- You can delete the subsections that are not related to your issue.

## 🐛 For reporting bugs

- What happens?

  I cannot install the chaotic-mirrorlist because "error: '/var/cache/pacman/pkg/chaotic-mirrorlist.pkg.tar.zst': the package is invalid or corrupted (PGP signature)"

- What is expected to happen?

  Describe it here

- If possible, please attach logs.

**Comment by PedroHLC** [comment]
Hi, we updated this package, can you try again?
If this is your first time installing the package, you may need to import the keys as seen in the "How to use it?" [here](https://aur.chaotic.cx/)

**Comment by ayesse** [comment]
I have installed for the first time 20 minutes ago and yes, I imported the keys as stated in the website. It's not the first time I install the chaotic-mirrorlist, but today I encountered that error for the first time

**Comment by PedroHLC** [comment]
```
╰─λ sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
:: Retrieving packages...
 chaotic-mirrorlist                                                                                   2,9 KiB  1642   B/s 00:02 [##############################################################################] 100%
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) chaotic-mirrorlist-20211118-2

Total Installed Size:  0,00 MiB
Net Upgrade Size:      0,00 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                                                                                                  [##############################################################################] 100%
(1/1) checking package integrity                                                                                                [##############################################################################] 100%
(1/1) loading package files                                                                                                     [##############################################################################] 100%
(1/1) checking for file conflicts                                                                                               [##############################################################################] 100%
(1/1) checking available disk space                                                                                             [##############################################################################] 100%
:: Processing package changes...
(1/1) upgrading chaotic-mirrorlist                                                                                              [##############################################################################] 100%
warning: /etc/pacman.d/chaotic-mirrorlist installed as /etc/pacman.d/chaotic-mirrorlist.pacnew
```

It worked like a charm here, what's the first "Server" entry in your current `/etc/pacman.d/chaotic-mirrorlist`?

**Comment by ayesse** [comment]
I don't have that file. The first two steps on the website work, but as soon as I launch the third it gives me that error

**Comment by dr460nf1r3** [comment]
I have a suspection - the mirrorlist was signed with my key rather than @PedroHLC's for the first time when it got updated yesterday. Could you try the first two steps again please, this time using `FBA220DFC880C036` as key?

**Comment by ayesse** [comment]
> I have a suspection - the mirrorlist was signed with my key rather than @PedroHLC's for the first time when it got updated yesterday. Could you try the first two steps again please, this time using `FBA220DFC880C036` as key?

I tried with the key you provided and everything worked perfectly

**Comment by dr460nf1r3** [comment]
Thanks for letting us know! We will update the installation instructions accordingly soon :)
