### ISSUE TITLE
chaotic-keyring: invalid or corrupted package (PGP signature)

### ISSUE THREAD

**Issue by CygnusTerminal** [chaotic-aur/packages#1071]
Note:

- We will delete issues not following this template!
- You can add new information besides the ones required here.
- You can delete the subsections that are not related to your issue.

## 🐛 For reporting bugs

- What happens?

Fresh Arch install, when trying to pull the keyring package, it asks for PGP key 8A9E14A07010F7E3, importing the key makes the operation fail:

`error: '/var/cache/pacman/pkg/chaotic-keyring.pkg.tar.zst': invalid or corrupted package (PGP signature)`

- What is expected to happen?

The keyring should install.

`[root@outerisolation vektor]# pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'
loading packages...
:: Import PGP key 8A9E14A07010F7E3, "Pedro Henrique Lara Campos <root@pedrohlc.com>"? Y
error: '/var/cache/pacman/pkg/chaotic-keyring.pkg.tar.zst': invalid or corrupted package (PGP signature)
`

**Comment by dr460nf1r3** [comment]
Hey there! :)
The signing key for keyring got changed today and the CDN mirror takes some time to sync.  Try [this](https://builds.garudalinux.org/repos/chaotic-aur/x86_64/chaotic-keyring-20210617-2-any.pkg.tar.zst) link instead for the keyring, it's the current version of the keyring package.

**Comment by CygnusTerminal** [comment]
> Hey there! :) The signing key for the keyring got changed today and the CDN mirror takes some time to sync. Try [this](https://builds.garudalinux.org/repos/chaotic-aur/x86_64/chaotic-keyring-20210617-2-any.pkg.tar.zst) link instead for the keyring, it's the current version of the keyring package.

Hey man! It worked, thanks a lot!
