### ISSUE TITLE
[Request] Guarda Wallet

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#1076]
- Link to the package(s) in AUR: [Guarda Wallet](https://aur.archlinux.org/packages/guarda-appimage/)

- Utility this package has for you:

  **Secure Crypto Wallet** : Stake, exchange, earn and buy Bitcoin, Ethereum and thousands of other assets.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [x] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by xiota** [comment]
Dropping because [project](https://github.com/guardaco/guarda-android-wallets) was discontinued in 2021.  Also, uses EOL Electron 8.0.0.
```
$ strings guarda | grep -Eom1 'Electron/[0-9\.]+'
Electron/8.0.0
```

Metrics 14.
