### ISSUE TITLE
Chaotic-aur.db broken

### ISSUE THREAD

**Issue by LukeDotDev** [chaotic-aur/packages#1082]
## 🐛 For reporting bugs

- What happens? 

 Unable to do anything with the chaotic aur & update.

- What is expected to happen?

  The expected thing is to that it works normally, and you're able to use / update normally

- What have I tried to fix the issue?

 First off I started googling, which came up with clearing the pacman cache with pacman -Scc, which doesn't work. Then I tried reinstalling the chaotic mirrorlist and keyring, which doesn't work either, I also manually tried sorting the chaotic mirrors.

- If possible, please attach logs.

![unknown (1)](https://user-images.githubusercontent.com/71151094/143035916-2917bd74-267f-4a38-8a32-b7578462120a.png)
![unknown (2)](https://user-images.githubusercontent.com/71151094/143035878-7023a906-33ed-462b-a292-e307d53a3ecb.png)

In the first screenshot you can see what the .db file contains, as you can see it says 301 Moved permanently
In the second screenshot you can see the error doing a update.

**Comment by PedroHLC** [comment]
Hi @LukeDotDev

I'm curious, what is the content of yours `/etc/pacman.d/chaotic-mirrorlist`? Is that what yours `[chaotic-aur]` is using in `pacman.conf`?

**Comment by LukeDotDev** [comment]
Here's the content of my chaotic-mirrorlist, this isn't changed since its on my home server. (this issue happens on both my Laptop and Desktop)
![image](https://user-images.githubusercontent.com/71151094/143037767-6ef3e6c6-e4d4-41a5-a465-f7863acde6be.png)

Here's my pacman.conf, chaotic is currently disabled due to me wanting to upgrade.
![image](https://user-images.githubusercontent.com/71151094/143037996-1f6dc1f9-b542-4f77-82f3-59fc51c272c6.png)

**Comment by PedroHLC** [comment]
Thanks. @LukeDotDev, what do you see when you enter this link?: `https://status.chaotic.cx/geo` (you can curl it)

Also, did you change your pacman's `XferCommand`?

**Comment by LukeDotDev** [comment]
The curl returns **de-mirror 1637676318 Healthy**
And I'm not quite sure what you refer to with **XferCommand**?

**Comment by 3k2** [comment]
I have same Issue as @LukeDotDev 

`error: could not open file /var/lib/pacman/sync/chaotic-aur.db: Unrecognized archive format`


my list looks like this from /etc/pacman.d/chaotic-mirrorlist I have commented some of the countries off. 



```
# Automatic per-country routing of the mirrors below.
Server = https://geo-mirror.chaotic.cx/$repo/$arch

# CDN (delayed syncing)
# By: Fosshost
Server = https://cdn-mirror.chaotic.cx/$repo/$arch

# USA
# * Utah, By: ash (@the_ashh on telegram)
Server = https://us-ut-mirror.chaotic.cx/$repo/$arch
# * Los Angeles - CA, By: IRC-Nerds
#Server = https://us-ca-mirror.chaotic.cx/$repo/$arch

# Spain
# * By: JKANetwork
Server = https://es-mirror.chaotic.cx/$repo/$arch
# * By: Ícar
Server = https://es-2-mirror.chaotic.cx/$repo/$arch

# Germany
# * By: Nico
Server = https://de-mirror.chaotic.cx/$repo/$arch
# * By: ParanoidBangL
Server = https://de-2-mirror.chaotic.cx/$repo/$arch
# * By: itsTyrion
Server = https://de-3-mirror.chaotic.cx/$repo/$arch
# * By: redgloboli
Server = https://de-4-mirror.chaotic.cx/$repo/$arch

# Brussels, Belgium
# * By: Belnet, the Belgian Education and Research Network
Server = https://be-bru-mirror.chaotic.cx/$repo/$arch

# São Carlos, Brazil
# * By: Universidade Federal de São Carlos
#Server = https://br-mirror.chaotic.cx/$repo/$arch

# Seoul, Korea
# * By: Ryoichi <t.me/maakpain>
#Server = https://kr-mirror.chaotic.cx/$repo/$arch

# Bulgaria
# * By: Sudo Man <github.com/sakrayaami>
Server = https://bg-mirror.chaotic.cx/$repo/$arch

# Toronto, Canada
# * By freebird54
#Server = https://ca-mirror.chaotic.cx/$repo/$arch

# Mumbai, India
# * By WebWerks
#Server = https://in-mirror.chaotic.cx/$repo/$arch
```

```
➜ curl https://status.chaotic.cx/geo
de-mirror 1637676498 Healthy
```

**Comment by fmjaeschke** [comment]
![image](https://user-images.githubusercontent.com/15345365/143051539-c6c6792e-b059-4223-be8b-7033850ba063.png)

**Comment by dr460nf1r3** [comment]
This was my mirror being faulty. Syncthing was quite out of sync but it should be fixed now. Please let us know if things are working again for you! 😊

**Comment by PedroHLC** [comment]
@LukeDotDev  @3k2 @fmjaeschke
Please, any of you, confirm if the issue was fixed.

**Comment by 3k2** [comment]
> @LukeDotDev @3k2 @fmjaeschke Please, any of you, confirm if it fixed the issue.

It seems to be working for me now

**Comment by fmjaeschke** [comment]
It works for me now. Dickes Dankeschön an @dr460nf1r3
