### ISSUE TITLE
[Request] rstudio-desktop

### ISSUE THREAD

**Issue by caniko** [chaotic-aur/packages#1083]
## 👶 For requesting new packages

- Link to the package(s) in AUR: [rstudio-desktop](https://aur.archlinux.org/packages/rstudio-desktop), [rstudio-desktop-bin](http://aur.archlinux.org/packages/rstudio-desktop-bin)

- Utility this package has for you: Develop programs using R.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few. (I don't know the demographic of chaotic-aur users, but for those doing statistics: YES)
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by xiota** [comment]
This package and related deps will likely be dropped soon because it still uses Qt5 and 2024 releases are not building successfully.  See #3157
