### ISSUE TITLE
[Request] gtksourceview-git

### ISSUE THREAD

**Issue by realmazharhussain** [chaotic-aur/packages#1085]
## 👶 requesting new package: `gtksourceview-git`

- Link to the package(s) in AUR (**_git_**): [gtksourceview-git](https://aur.archlinux.org/gtksourceview-git.git)

- Link to the package(s) in AUR (**_webpage_**): [gtksourceview-git](https://aur.archlinux.org/packages/gtksourceview-git)

- Utility this package has for you:

  Provides the latest development version of gtksourceview and in result, makes other bleeding edge versions of GNOME apps buildable/usable (most notably gnome-text-editor-git)

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [ ] NO
  - [x] IDK. Kinda

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by xiota** [comment]
Dropping because no longer useful for stated purpose.  Many "bleeding-edge" GNOME apps have been dropped because trying to keep them working was futile.
