### ISSUE TITLE
[Requerst] Wine lol and Wine lol glibc

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#1086]
- Link to the package(s) in AUR: [Wine-lol](https://aur.archlinux.org/packages/wine-lol/PKGBUILD), [Wine-lol-Glibc](https://aur.archlinux.org/packages/wine-lol-glibc/)

- Utility this package has for you:
 
  **These packages are mandatory to install League of Legend on Linux :** (A compatibility layer for running Windows programs - Wine Tk-Glitch with League Of Legends fixes.)
 

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [x] YES
  - [ ] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [x] YES
  - [ ] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by dr460nf1r3** [comment]
Why exactly do you want this in repo when Lutris does a really good job handling LoL already?

**Comment by ALipAkrohk** [comment]
> Hey there :) Why exactly do you want this in repo when Lutris does a really good job handling LoL already?

Currently the suggested version of Lutris does not work for me and I have to install Standard v2.0 (Launch Helper) version which unfortunately works very unstable, but the snap and wine-lol versions show better performance for me , Especially since I make most of the config myself.

**Forgive me for poor English.**

**Comment by dr460nf1r3** [comment]
This package is not building in clean chroot.
