### ISSUE TITLE
[Outdated] sweet-kde-git

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#1089]
## 👴 For reporting outdated packages

- Link to latest build: [sweet-kde-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/sweet-kde-git.log)
  - Build seems to have failed

- Package name: `some-package`

- Latest build: `r215.e9bb8e5-1`

- Latest version available: `r216.123dd8b-1`

- Have you tested if the latest version of the package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

**Comment by dr460nf1r3** [comment]
Seems like the folder structure changed once again :eyes:
