### ISSUE TITLE
[Outdated] kvantum-theme-sweet-git

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#1090]
## 👴 For reporting outdated packages

- (If available) Link to latest build: `There is none`

- Package name: `kvantum-theme-sweet-git`

- Latest build: `r215.e9bb8e5-1`

- Latest version available: `r216.123dd8b-1`

- Have you tested if the latest version of the package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

**Comment by dr460nf1r3** [comment]
Part of #1089
