### ISSUE TITLE
[Request] Anita (distribution) packages

### ISSUE THREAD

**Issue by PedroHLC** [chaotic-aur/packages#1092]
- Link to the package(s) in AUR: https://gitlab.com/a6209/chaotic-aur-builds

- Utility this package has for you:

  Grows chaotic beyond pure-arch and Garuda setups. Helping smaller distros maintainers like Anita's.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [X] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [X] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [X] YES

- Have you tested if this package builds in a clean chroot?:

  - [X] The author said it does

- Does the package's license allows us to redistribute it?:

  - [X] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [X] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [X] YES

**Comment by dr460nf1r3** [comment]
The `calamares-configuration` package should be prefixed with `anita-` like the other 2 packages :eyes:

**Comment by mdhishamsayed** [comment]
@dr460nf1r3 done sir
