### ISSUE TITLE
[Request] gnome-shell-git and other git versions of gnome packages

### ISSUE THREAD

**Issue by Titaniumtown** [chaotic-aur/packages#1093]
- Link to the package(s) in AUR: [mutter-git](https://aur.archlinux.org/packages/mutter-git/) (note, missing `wayland-protocols` dependency), [gnome-shell-git](https://aur.archlinux.org/packages/gnome-shell-git)

- Utility this package has for you:
Allows me (and other people) to experience bleeding edge gnome and to see latest changes.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [X] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [X] YES
  - [ ] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [X] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [X] NO

- Does the package's license allows us to redistribute it?:

  - [ ] YES
  - [X] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [X] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [X] YES

**Comment by theblobscp** [comment]
Can we get a status update on this? I also would like an updated GNOME Shell.
