### ISSUE TITLE
[Request] pcloudcc-git

### ISSUE THREAD

**Issue by coxackie** [chaotic-aur/packages#1104]
- Link to the package(s) in AUR: [https://aur.archlinux.org/packages/pcloudcc-git/](https://aur.archlinux.org/packages/pcloudcc-git/)

- Utility this package has for you:
"Official" console client for storage and syncing solution pCloud. Much more lightweight than their electron app.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by xiota** [comment]
Planning to drop.  Fails to build with GCC 14 because many warnings were changed to errors.  Upstream essentially unmaintained.  Last update about three years ago.  Metrics 8.

**Comment by coxackie** [comment]
@xiota yeah, that makes sense. By the way, there is a fork that solves building, and other things. I have created a ticket to create an AUR package, as anyway the dev wanted to do so: https://github.com/lneely/pcloudcc-lneely/issues/26. Maybe a bit of extra nudge from your side would be good.

**Comment by xiota** [comment]
@coxackie You could switch the package to the new fork and add the dev as comaintainer.

**Comment by lneely** [comment]
@xiota @coxackie Between "life happening" and wanting to get a few tasks done on the code first, it hasn't been as fast as I wanted. Now those things are dealt with, so I expect to have my fork published on AUR tomorrow. :beers:

**Comment by xiota** [comment]
Dropping this package.  If someone wants the lneely fork added, please open a new request.
