### ISSUE TITLE
[Outdated] etcher-bin

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#1109]
## 👴 For reporting outdated packages

- (If available) Link to latest build: [etcher-bin.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/etcher-bin.log)

- Package name: `balena-etcher`

- Latest build: `1.7.0-1`

- Latest version available: `1.7.1-1`

- Have you tested if the latest version of the package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

Note: there are no breaking changes so this is probably low priority.

**Comment by dr460nf1r3** [comment]
The package is currently not building due to a packaging issue which already has been reported at its AUR page. :eyes:
