### ISSUE TITLE
[Request] dosbox-x & dosbox-x-git

### ISSUE THREAD

**Issue by realmazharhussain** [chaotic-aur/packages#1110]
## 👶 Requesting new package

- Link to the packages in AUR: [dosbox-x](https://aur.archlinux.org/packages/dosbox-x) & [dosbox-x-git](https://aur.archlinux.org/packages/dosbox-x-git)

- Utility this package has for me:

  Running legacy DOS games/apps more easily than regular dosbox

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by dr460nf1r3** [comment]
Which one of those are you actually using?

**Comment by realmazharhussain** [comment]
I am using dosbox-x
