### ISSUE TITLE
[Request] Sticky-git, Bulky, Thingy, Pix

### ISSUE THREAD

**Issue by blank-space-maker** [chaotic-aur/packages#1114]
## 👶 For requesting new packages

- Link to the package(s) in AUR: [Sticky-git](https://aur.archlinux.org/packages/sticky-git/), [Bulky](https://aur.archlinux.org/packages/bulky/), [Thingy](https://aur.archlinux.org/packages/thingy/), [Pix](https://aur.archlinux.org/packages/pix/)

- Utility this package has for you:

  Describe it here, why you use this package, how it can be helpful.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [x] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by xiota** [comment]
`bulky` and `thingy` were moved to extra.

Metrics:

* bulky # 21
* pix # 131
* sticky-git # 164
* thingy # 8

**Comment by xiota** [comment]
Dropping `sticky-git` because `extra/sticky` is available.

Metrics:

* pix # 223
* sticky-git # 71
