### ISSUE TITLE
missing defendency for superslicer

### ISSUE THREAD

**Issue by Lukas1818** [chaotic-aur/packages#1117]
While checking [repology](https://repology.org/project/superslicer/versions) I notify that the chaotic-aur superslicer version is heavily outdated. So I have check the chaotic-aur logs and notfily that, the build dose fail because of a missing dependency ([wxgtk-dev-314-opt](https://aur.archlinux.org/pkgbase/wxgtk-dev-314-opt/)).

Superslicer have change from ([wxgtk-dev-opt](https://aur.archlinux.org/pkgbase/wxgtk-dev-opt/)) to wxgtk-dev-314-opt, because the current version of wxgtk-dev-opt is not compatible with superslicer. see https://github.com/supermerill/SuperSlicer/issues/1093

Because of this the maintainer of wxgtk-dev-opt had create the wxgtk-dev-314-opt package.

Furthermore wxgtk-dev-opt is also outdated. But it can be removed from the chaotic-aur, because even at the official aur, superslicer was the only package, which does depend on it.

https://builds.garudalinux.org/repos/chaotic-aur/logs/superslicer.log
```
Building package "superslicer"
INFO:    Starting build...
INFO:    Verifying bootstrap image /home/u726578/chaotic/cache/lower/20211211132002.sif
WARNING: integrity: signature not found for object group 1
WARNING: Bootstrap image could not be verified, but build will continue.
INFO:    Creating sandbox directory...
INFO:    Build complete: /scratch/chaotic/sandbox/pkg284347624cc
:: Synchronizing package databases...
 core downloading...
 extra downloading...
 community downloading...
 multilib downloading...
 chaotic-aur downloading...
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (1) pacman-mirrorlist-20211212-1

Total Installed Size:  0.04 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] 
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
upgrading pacman-mirrorlist...
warning: /etc/pacman.d/mirrorlist installed as /etc/pacman.d/mirrorlist.pacnew
error: target not found: wxgtk3-dev-314-opt
error: target not found: wxgtk2-dev-314-opt
```

**Comment by dr460nf1r3** [comment]
Thanks for finding this! :)
