### ISSUE TITLE
[Request] mcpelauncher-linux-git & mcpelauncher-ui-git

### ISSUE THREAD

**Issue by JadenJSJ** [chaotic-aur/packages#1118]
## 👶 For requesting new packages

- Link to the package(s) in AUR: 
https://aur.archlinux.org/packages/mcpelauncher-linux-git/
https://aur.archlinux.org/packages/mcpelauncher-ui-git/

- Utility this package has for you:

  To Play Minecraft Bedrock Edition on Linux, so I don't need to switch back to Windows to do so.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ O ] No, but yes for a great amount. (Minecraft Bedrock Edititon Players(
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [ O ] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [ O ] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [ O ] NO

- Does the package's license allows us to redistribute it?:

  - [ ] YES
  - [ O ] No clue. (Not listed anywhere on the Github & Documentation) 
  I think its fine? I have seen a few forks
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [ O ] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [ O ] YES

**Comment by xiota** [comment]
Fails to build.  Most likely missing headers.  Reported upstream on 2024-08-02.  May drop if not fixed.
```
src/mcpelauncher-manifest/libc-shim/src/cstdio.cpp:140:10: error: no matching member function for call to 'insert'
```

**Comment by xiota** [comment]
Earlier issue was likely resolved some time ago.  For anyone interested, metrics:

* mcpelauncher-linux-git # 387
* mcpelauncher-ui-git # 189
