### ISSUE TITLE
[Outdated] [Bug] powerpill outdated and missing

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#1119]
## 👴 For reporting outdated packages

- Link to latest build: [powerpill.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/powerpill.log)

- Package name: `powerpill`

- Latest build: `Can't tell since I upgraded and forgot to make note`

- Latest version available: `2021.11-2`

- Have you tested if the latest version of the package builds in a clean chroot?:

  - [x] YES

I manually built it with paru and it went fine. Unfortunately I didn't save those logs, but it also complained about `pm2ml` in some capacity.

## 🐛 For reporting bugs

- What happens?

  Search for powerpill and it does not show up.

- What is expected to happen?

  It should show up

- If possible, please attach logs.
```
[tech@mango ~]$ pacman -Ss powerpill
[tech@mango ~]$ pacman -Qi powerpill
Name            : powerpill
Version         : 2021.11-2
Description     : Pacman wrapper for faster downloads.
Architecture    : any
URL             : https://xyne.dev/projects/powerpill
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : aria2  pm2ml>2012.12.12  pyalpm  python3  python3-xcgf  python3-xcpf
Optional Deps   : python3-threaded_servers: internal Pacserve support
reflector: Reflector and Rsync support [installed]
rsync: Rsync download support [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 99.66 KiB
Packager        : Unknown Packager
Build Date      : Tue 14 Dec 2021 02:36:46 AM EST
Install Date    : Tue 14 Dec 2021 02:36:50 AM EST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

**Comment by Technetium1** [comment]
Related: https://github.com/chaotic-aur/packages/blob/388f046a2eec1bb827b2a59bd29da0c480e1dee8/ufscar-hpc/hourly.1.txt#L61-L66

**Comment by dr460nf1r3** [comment]
I'm pretty sure this was due to the mass rebuild of Python packages :eyes: thanks for reporting!
