### ISSUE TITLE
Licensing Issue: multimc-git

### ISSUE THREAD

**Issue by patrick96** [chaotic-aur/packages#1120]
Sorry for not using the template, this didn't match any of the subsections.

Builds of the package [`multimc-git`](https://aur.archlinux.org/packages/multimc-git) cannot be redistributed. The package maintainer also says so in a [pinned comment](https://aur.archlinux.org/packages/multimc-git#pinned-840987):

> Please note that it is illegal to distribute the binaries created with this script due to MultiMC's licensing. You're still fine using/distributing the PKGBUILD itself to build a local package that you won't redistribute. If you would like a freely redistributable version without the extra stuff that this package adds please go to https://aur.archlinux.org/packages/devlauncher-git

The reason is that it is an unofficial package, but uses the official branding which is prohibited by the Apache2 license. The MultiMC maintainers also state as much on their [website](https://multimc.org/#Branding):

> MultiMC is released under the Apache 2 license, which gives you the full access to the source code. What it doesn't give you is the right to use the name (MultiMC) or logo (infinity symbol on the side view of a block of grass) in any custom builds or forks of the project.

**Comment by dr460nf1r3** [comment]
Hey there, thanks for the notice! We will of course remove and blacklist the package :)
