### ISSUE TITLE
[Request] rum

### ISSUE THREAD

**Issue by coolio321** [chaotic-aur/packages#1121]
Note:

- Link to the package(s) in AUR: https://aur.archlinux.org/packages/rum/

- Utility this package has for you: Helps game pirates play cracked games easier due to its simple GUI and setup.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [X] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [ X] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [ ] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [ X] NO

- Does the package's license allows us to redistribute it?:

  - [ X] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [ X] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [X ] YES

**Comment by Technetium1** [comment]
I would like to second this request and add `rum-git` for identical reasons.
