### ISSUE TITLE
[outdated] Lbry Desktop Bin

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#1124]
- Package name: `lbry-desktop-bin`

- Latest build: `0.51.1-1`

- Latest version available: `0.51.2-1`

- Have you tested if the latest version of the package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

**Comment by dr460nf1r3** [comment]
It seems the package was removed from AUR :eyes:

**Comment by dr460nf1r3** [comment]
Is there a difference be tween `lbry-app-bin` and `lbry-desktop-bin`? If there is none, I'd suggest adding the former instead 🤔

**Comment by ALipAkrohk** [comment]
Exactly I saw the message "Please update me" in the software, and after checking in aur, I saw the new version and announced it.
But I did not pay attention to its exact name, sorry.

![image](https://media.discordapp.net/attachments/911658462889525268/922217371886841927/Screenshot_20211219_232823.png)

**Comment by dr460nf1r3** [comment]
Alright that's great, we will replace the package then! :)
