### ISSUE TITLE
[Outdated] librewolf

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#1126]
## 👴 For reporting outdated packages

- (If available) Link to latest build : [librewolf.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/librewolf.log)

- Package name: `librewolf`

- Latest build: `94.0.2-2`

- Latest version available: `95.0-1`

- Have you tested if the latest version of the package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

**Comment by dr460nf1r3** [comment]
This happened due a missing patch which is required to build the package currently. I already notified the maintainer about it so it might be fixed soon :)
