### ISSUE TITLE
[request] vscodium-marketplace (updated issue)

### ISSUE THREAD

**Issue by Daviteusz** [chaotic-aur/packages#1127]
- Link to the package(s) in AUR: 
  
  - [vscodium-marketplace](https://aur.archlinux.org/packages/vscodium-marketplace/) 

- Utility this package has for you:

  vscodium-marketplace has extensions that the vscodium marketplace doesn't have (like microsoft extensions)

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by dr460nf1r3** [comment]
Hey there! We do have `vscodium` available already, wouldn't [this](https://aur.archlinux.org/packages/vscodium-marketplace/) be more appropriate?

**Comment by Daviteusz** [comment]
oh, i did not search for "vscodium" when entering "pacman -Ss" but I search vscodium with "-bin" sorry about that. I'll make test with vscodium-marketplace. If it's working, I'll edit this pr if it's working for vscodium-marketplace support. Regards
