### ISSUE TITLE
[Broken] ungoogled-chromium-96.0.4664.110-1-x86_64 fails to start

### ISSUE THREAD

**Issue by avbobylev** [chaotic-aur/packages#1130]
- What happens?

Package ```ungoogled-chromium-96.0.4664.110-1-x86_64``` fails to start with an error:

```bash
/usr/lib/chromium/chromium: symbol lookup error: /usr/lib/chromium/chromium: undefined symbol: wl_proxy_marshal_flags
```

Previous version of the package ```ungoogled-chromium-96.0.4664.93-1-x86_64``` runs as expected.

- What is expected to happen?

Package starts without an error.

**Comment by dr460nf1r3** [comment]
Hey there! Do you have `wayland-protocols` installed? If that doesn't help, the issue should be reported at Ungoogled Chromiums repo :eyes:

**Comment by avbobylev** [comment]
I do have ```wayland-protocols``` installed:

```bash
local/wayland-protocols 1.24-1
    Specifications of extended Wayland protocols
```

but I use regular x11 session.

**Comment by dr460nf1r3** [comment]
Alright, I would suggest reporting the issue [here](https://github.com/ungoogled-software/ungoogled-chromium-archlinux) then as that is the repo we use to build the package :)

**Comment by dr460nf1r3** [comment]
I had a look at the issue at the Ungoogled Chromium repo - there was an important information: Chaotic-AUR + Manjaro can be quiet problematic because of package versions being released some time after Arch pushes their versions.
