### ISSUE TITLE
[Outdated] anaconda

### ISSUE THREAD

**Issue by blank-space-maker** [chaotic-aur/packages#1132]
## 👴 Reporting outdated packages

- If available: link to latest build ([find it here](https://builds.garudalinux.org/repos/chaotic-aur/logs/)): [some-package.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/some-package.log)

- Package name: `anaconda`

- Latest build: `2021.05`

- Latest version available: `2021.11`

- Have you tested if the latest version of the package builds in a clean chroot?

  - [ ] Yes
  - [x] No

**Comment by dr460nf1r3** [comment]
Hey there, the AUR PKGBUILD needs to be updated in order to update this package here as well :)

**Comment by blank-space-maker** [comment]
AUR package has been flagged out of date for over 60 days.

**Comment by xiota** [comment]
@dr460nf1r3 @Technetium1 `anaconda` package sizes:
```
Download Size   : 2.50 GiB
Installed Size  : 6.57 GiB
```

Metrics: 638

Keep / Remove?

**Comment by Technetium1** [comment]
@xiota while it is large, it's greatly beneficial to developers.

**Comment by dr460nf1r3** [comment]
I agree, I've come across it numerous times already. One of the fewer things to justify its size.
