### ISSUE TITLE
[Request] leagueoflegends-git and wine-lol

### ISSUE THREAD

**Issue by federicotorrielli** [chaotic-aur/packages#1133]
##  👶 New package requests

- Link to the package(s) in AUR: [leagueoflegends-git](https://aur.archlinux.org/packages/leagueoflegends-git) and [wine-lol](https://aur.archlinux.org/packages/wine-lol)

- **Utility** this package has for you

  While I know that wine-lol-glibc is already in chaotic-aur, wine-lol is mandatory to install for leagueoflegends-git to work.
  Plus, there is a LOT of people I know that would have an use of these packages pre-compiled.

- Do you consider the package(s) to be useful for **every** Chaotic-AUR user?

  - [ ] YES!
  - [x] No, but for a great amount.
  - [ ] No, but for a few.
  - [ ] No, it's useful only for me.

- Do you consider the package to be **useful for feature testing**/preview (e.g: mesa-aco, wine-wayland)?

  - [ ] Yes
  - [x] No

- Are you sure the package **isn't available already** (test with `pacman -Ss <pkgname>`) ?

  - [x] Yes

- Have you tested if the package builds in a [**clean chroot**](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot)?

  - [x] Yes, after the latest patch and with the latest glibc version.
  - [ ] No

- Does the package's **license** allow redistributing it?

  - [x] YES!
  - [ ] No clue.
  - [ ] No, but the author doesn't really care anyways. It's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request **is unique**?

  - [x] Well, I just reposted because it was updated and works again...

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is **not banned**?

  - [x] YES!

**Comment by dr460nf1r3** [comment]
Is there a real reason to using this over the Lutris installer? 👀

**Comment by federicotorrielli** [comment]
@dr460nf1r3 yes, it includes game-specific patches for wine that corrects frequent crashes that I (and many) have...
