### ISSUE TITLE
[Bug] [bear] 3.0.17-1 is broken

### ISSUE THREAD

**Issue by AulonSal** [chaotic-aur/packages#1134]
## 🐛 Reporting bugs

- What happens?
  [chaotic-aur/bear] v3.0.17-1's `/usr/bin/intercept` links against `libprotobuf.so.28`
  [extra/protobuf] from the official repos only provides `libprotobuf.so=30-64`
```fish
~> intercept
intercept: error while loading shared libraries: libprotobuf.so.28: cannot open shared object file: No such file or directory
~> ldd /usr/bin/intercept | grep protobuf
libprotobuf.so.30 => /usr/lib/libprotobuf.so.30 (0x00007f984a6ca000)
```
- What is expected to happen?
  `/usr/bin/intercept` links against `libprotobuf.so.30`
```fish
~> intercept
Parameter is required, but not given: "--"
Usage: intercept [--output <arg>] [--verbose] -- ...
~> ldd /usr/bin/intercept | grep protobuf
libprotobuf.so.30 => /usr/lib/libprotobuf.so.30 (0x00007f984a6ca000)
```
- How to fix?
Rebuilding the package should work (The "What is expected to happen" section is from a fresh build of [aur/bear] on my system

**Comment by dr460nf1r3** [comment]
Make sure to reinstall the package in order to profit from the rebuild :)
