### ISSUE TITLE
Quick question: why's there no linux-xanmod

### ISSUE THREAD

**Issue by D0nnieD4rk0** [chaotic-aur/packages#1135]
or is the anbox thing just harmless patch that doesn't rly affect anything

**Comment by federicotorrielli** [comment]
There are many linux-xanmod-* packages on chaotic-aur: the latest part of the package describes the CPU scheduler used for that Kernel. I would recommend the latest `linux-xanmod-tt`and `linux-xanmod-tt-headers` to install right now because it is the most active of them all.

**Comment by dr460nf1r3** [comment]
Well its just `linux-xanmod` with Anbox support added (`ashmem` and `binder` modules enabled in its config). Personally, I didn't see any benefit in building both `linux-xanmod` and `linux-xanmod-anbox` since they are the same package apart from this.
