### ISSUE TITLE
Build lib32-libffmpeg without lib32-x265 or provide lib32-x265

### ISSUE THREAD

**Issue by CobaltSpace** [chaotic-aur/packages#1137]
## 🐛 Reporting bugs

- What happens?

  lib32-libffmpeg depends on lib32-x265, which is not provided

- What is expected to happen?

  lib32-libffmpeg should not depend on lib32-x265, and should not enable libx265 in the pkgbuild, or lib32-x265 should be added.

- If possible, please attach logs.

**Comment by dr460nf1r3** [comment]
Solved via https://github.com/chaotic-aur/interfere/commit/a395e04e05cc64a4aa3fa395b5cb5bbd7a71be81, this disables the dependency / disables building support for `lib32-x265`. Thanks for the report :)
