### ISSUE TITLE
[Request] jamesdsp-pulse

### ISSUE THREAD

**Issue by BachoSeven** [chaotic-aur/packages#1141]
- Link to the package(s) in AUR: [](https://aur.archlinux.org/packages/jamesdsp)

- **Utility** this package has for you

  *This is the place to describe how you use the package and how it can be helpful.*

- Do you consider the package(s) to be useful for **every** Chaotic-AUR user?

  - [ ] YES!
  - [x] No, but for a great amount.
  - [ ] No, but for a few.
  - [ ] No, it's useful only for me.

- Do you consider the package to be **useful for feature testing**/preview (e.g: mesa-aco, wine-wayland)?

  - [ ] Yes
  - [x] No

- Are you sure the package **isn't available already** (test with `pacman -Ss <pkgname>`) ?

  - [x] Yes

- Have you tested if the package builds in a [**clean chroot**](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot)?

  - [x] Yes
  - [ ] No

- Does the package's **license** allow redistributing it?

  - [x] YES!
  - [ ] No clue.
  - [ ] No, but the author doesn't really care anyways. It's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request **is unique**?

  - [x] YES!

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is **not banned**?

  - [x] YES!

## Notes
Related to #982, for folks like me who are still on Pulseaudio and will be for a while...

**Comment by BachoSeven** [comment]
Thanks!

**Comment by dr460nf1r3** [comment]
You are welcome! :)
