### ISSUE TITLE
[Outdated] obs-studio-tytan652

### ISSUE THREAD

**Issue by WitherCubes** [chaotic-aur/packages#1142]
## 👴 Reporting outdated packages

- Package name: `obs-studio-tytan652`

- Latest build: `27.1.3-8`

- Latest version available: `27.1.3-10`

- Have you tested if the latest version of the package builds in a clean chroot?

  - [ ] Yes
  - [X] No

**Comment by dr460nf1r3** [comment]
There were some new dependencies which didn't exist in our repo yet :eyes:

**Comment by WitherCubes** [comment]
Currently this version of OBS does not open/work because the python version in the main repos has updated to python 3.10 but this version of OBS looks for a python 3.9 library.

**Comment by dr460nf1r3** [comment]
This will be no problem once the package gets rebuild. I was just adding the deps and the new build is in progress :)

**Comment by dr460nf1r3** [comment]
Fixed in https://github.com/chaotic-aur/packages/commit/ac338721d58ba1ed28d2fd55d89a618145bc88d4, the referenced issue was supposed to be this one.
