### ISSUE TITLE
[Request] play-emu-git

### ISSUE THREAD

**Issue by heroku-miraheze** [chaotic-aur/packages#1145]
**Notes:**

- **We will delete issues not following this template!**
- **You can add new information besides the ones required here.**
- **You should delete the subsections that are not related to your issue.**

##  👶 New package requests

- Link to the package(s) in AUR: https://aur.archlinux.org/packages/play-emu-git/

- **Utility** this package has for you

  An PlayStation 2 emulator (BIOS not required).

- Do you consider the package(s) to be useful for **every** Chaotic-AUR user?

  - [x] YES!
  - [ ] No, but for a great amount.
  - [ ] No, but for a few.
  - [ ] No, it's useful only for me.

- Do you consider the package to be **useful for feature testing**/preview (e.g: mesa-aco, wine-wayland)?

  - [x] Yes
  - [ ] No

- Are you sure the package **isn't available already** (test with `pacman -Ss <pkgname>`) ?

  - [x] Yes

- Have you tested if the package builds in a [**clean chroot**](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot)?

  - [x] Yes
  - [ ] No

- Does the package's **license** allow redistributing it?

  - [x] YES!
  - [ ] No clue.
  - [ ] No, but the author doesn't really care anyways. It's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request **is unique**?

  - [x] YES!

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is **not banned**?

  - [x] YES!

**Comment by dr460nf1r3** [comment]
The package is in repo since a long time already. If you ever request a package again make sure to not lie in the template and waste my time, its not the first time you do this.
