### ISSUE TITLE
[Request] kget-integrator, kget-integrator-chromium

### ISSUE THREAD

**Issue by mdhishamsayed** [chaotic-aur/packages#1150]
##  👶 New package requests

- Link to the package(s) in AUR: (https://aur.archlinux.org/packages/kget-integrator/) (https://aur.archlinux.org/packages/kget-integrator-chromium/)

- **Utility** this package has for you

Integrate KGet Download Manager with Google Chrome, Chromium, Vivaldi, Opera and Firefox

- Do you consider the package(s) to be useful for **every** Chaotic-AUR user?

  - [ ] YES!
  - [ ] No, but for a great amount.
  - [x] No, but for a few.
  - [ ] No, it's useful only for me.

- Do you consider the package to be **useful for feature testing**/preview (e.g: mesa-aco, wine-wayland)?

  - [ ] Yes
  - [x] No

- Are you sure the package **isn't available already** (test with `pacman -Ss <pkgname>`) ?

  - [x] Yes

- Have you tested if the package builds in a [**clean chroot**](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot)?

  - [x] Yes
  - [ ] No

- Does the package's **license** allow redistributing it?

  - [x] YES! Its GPL v3
  - [ ] No clue.
  - [ ] No, but the author doesn't really care anyways. It's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request **is unique**?

  - [x] YES!

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is **not banned**?

  - [x] YES!

**Comment by xiota** [comment]
Upstream project discontinued since 2020.  https://github.com/NicolasGuilloux/KGet-Integrator

**Comment by Technetium1** [comment]
This can be reconsidered if the upstream project comes back to life.
