### ISSUE TITLE
[Request] mutter-rounded, kde-rounded-corner

### ISSUE THREAD

**Issue by Evan-aja** [chaotic-aur/packages#1151]
##  👶 New package requests

- Link to the package(s) in AUR: [mutter-rounded](https://aur.archlinux.org/packages/mutter-rounded), [kde-rounded-corner](https://aur.archlinux.org/packages/kde-rounded-corners/)

- **Utility** these packages has for you

  These packages (Gnome with mutter-rounded, and Plasma with kde-rounded-corner) gives the ability to have rounded corners on all window. even ones that aren'r supported by themes (like xdman's downloads floating widget)

- Do you consider the package(s) to be useful for **every** Chaotic-AUR user?

  - [ ] YES!
  - [ ] No, but for a great amount.
  - [X] No, but for a few.
  - [ ] No, it's useful only for me.

- Do you consider the package to be **useful for feature testing**/preview (e.g: mesa-aco, wine-wayland)?

  - [ ] Yes
  - [X] No

- Are you sure the package **isn't available already** (test with `pacman -Ss <pkgname>`) ?

  - [X] Yes

- Have you tested if the package builds in a [**clean chroot**](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot)?

  - [ ] Yes
  - [X] No

- Does the package's **license** allow redistributing it?

  - [X] YES!
  - [ ] No clue.
  - [ ] No, but the author doesn't really care anyways. It's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request **is unique**?

  - [X] YES!

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is **not banned**?

  - [X] YES

**Comment by xiota** [comment]
Metrics after recent X11 split.

* kwin-effect-rounded-corners-git # 18991
* kwin-effect-rounded-corners-x11-git # 69
