### ISSUE TITLE
[Request] exaile & amarok

### ISSUE THREAD

**Issue by mdhishamsayed** [chaotic-aur/packages#1152]
- Link to the package(s) in AUR: https://aur.archlinux.org/packages/exaile/ & https://aur.archlinux.org/packages/amarok/ & https://gitlab.com/a6209/chaotic-aur-builds/pkgbuild-anita-cinnamon-configuration

- **Utility** this package has for you
A full-featured Amarok-style media player for GTK+'
The powerful music player for KDE
Custom
- Do you consider the package(s) to be useful for **every** Chaotic-AUR user?

  - [ ] YES!
  - [ ] No, but for a great amount.
  - [x] No, but for a few.
  - [ ] No, it's useful only for me.

- Do you consider the package to be **useful for feature testing**/preview (e.g: mesa-aco, wine-wayland)?

  - [ ] Yes
  - [x] No

- Are you sure the package **isn't available already** (test with `pacman -Ss <pkgname>`) ?

  - [x] Yes

- Have you tested if the package builds in a [**clean chroot**](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot)?

  - [x] Yes
  - [ ] No

- Does the package's **license** allow redistributing it?

  - [x] YES!
  - [ ] No clue.
  - [ ] No, but the author doesn't really care anyways. It's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request **is unique**?

  - [x] YES!

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is **not banned**?

  - [x] YES!

**Comment by xiota** [comment]
For anyone interested, `exaile` fails check because of Python 3.13 update.  `amarok` still uses Qt5.  Metrics:

* exaile # 24
* amarok # 298

**Comment by FabioLolix** [comment]
`amarok` have an experimental Qt6 port but it is failing to build on Arch https://bugs.kde.org/show_bug.cgi?id=498058, the pkgbuilds are already ready I'm just waiting for the fixes, very likely will upload as `amarok-qt6` until Qt6 will be preferred over Qt5

**Comment by FabioLolix** [comment]
`amarok-qt6` is uploaded but https://aur.archlinux.org isn't working now

**Comment by xiota** [comment]
@FabioLolix Re: amarok-qt6 merge request...  aur/amarok still uses Qt5.

**Comment by FabioLolix** [comment]
Made the update 3 days ago (https://github.com/FabioLolix/PKGBUILD-AUR_fix/commit/c56a601c3b73ad76b971aba6c2aae6e7196ee432) but forgot to sync, though I already done it

**Comment by xiota** [comment]
Thank you.  Will switch chaotic-aur back to amarok.

For future consideration, might be easier to switch package `xyz` to Qt6 and create `xyz-qt5`, since `xyz` would eventually be switched to Qt6.

**Comment by FabioLolix** [comment]
>  might be easier to switch package xyz to Qt6 and create xyz-qt5, since xyz would eventually be switched to Qt6.

wasn't pratical with amarok for various reason IMO but I generally to that

**Comment by xiota** [comment]
Dropping amarok because moved to extra.  Metrics 364.
