### ISSUE TITLE
[bug] qimgv-git

### ISSUE THREAD

**Issue by bipox** [chaotic-aur/packages#1153]
# What happens?

qimgv won't launch. Error message:   
`qimgv: error while loading shared libraries: libopencv_imgproc.so.4.5: cannot open shared object file: No such file or directory
`

The bug has been reported on qimgv's github: https://github.com/easymodo/qimgv/issues/381

This is what a user had to say: 
>qimgv-git after rebuild (do not use cache) works. I use git version now and it was build with new lib.

I installed it directly from the AUR and it does work.

Possibly rebuilding without using cache could fix it.

(Thank you for chaotic-aur, it's very handy!)

**Comment by dr460nf1r3** [comment]
Thanks for reporting, the package has been rebuilt 🙂
