### ISSUE TITLE
[Request] libadwaita-git-pkgs (libadwaita-docs-git & libadwaita-demos-git)

### ISSUE THREAD

**Issue by realmazharhussain** [chaotic-aur/packages#1159]
##  👶 New package request

- Link to the package(s) in AUR: [libadwaita-git-pkgs](https://aur.archlinux.org/pkgbase/libadwaita-git-pkgs)

- Clone URL: [libadwaita-git-pkgs](https://aur.archlinux.org/libadwaita-git-pkgs.git)

- **Utility** this package has for you

  *Latest version of LibAdwaita Docs and Demos. Latest Docs are much better than older docs available in repos. I need newer Docs to work on my app.*

- Do you consider the package(s) to be useful for **every** Chaotic-AUR user?

  - [ ] YES!
  - [ ] No, but for a great amount.
  - [x] No, but for a few.
  - [ ] No, it's useful only for me.

- Do you consider the package to be **useful for feature testing**/preview (e.g: mesa-aco, wine-wayland)?

  - [x] Yes, Maybe? IDK.
  - [ ] Yes
  - [ ] No

- Are you sure the package **isn't available already** (test with `pacman -Ss <pkgname>`) ?

  - [x] Yes

- Have you tested if the package builds in a [**clean chroot**](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot)?

  - [ ] Yes
  - [x] No

- Does the package's **license** allow redistributing it?

  - [x] YES!
  - [ ] No clue.
  - [ ] No, but the author doesn't really care anyways. It's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request **is unique**?

  - [x] YES!

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is **not banned**?

  - [x] YES!

**Comment by dr460nf1r3** [comment]
Seems to be broken here still.. 
`==> Starting package_libadwaita-docs-git()...
mv: cannot stat 'docs/*': No such file or directory` 
I notified the maintainer about this.

**Comment by realmazharhussain** [comment]
It has been fixed now

**Comment by dr460nf1r3** [comment]
Yeah, I did in fact add this yesterday 😬
