### ISSUE TITLE
[Outdated] pcsx2-git

### ISSUE THREAD

**Issue by NerosTie** [chaotic-aur/packages#1161]
## 👴 Reporting outdated packages

- If available: link to latest build: [pcsx2-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/pcsx2-git.log)

- Package name: `pcsx2-git`

- Latest build: `1.7.2141`

- Latest version available: `1.7.2225`

- Have you tested if the latest version of the package builds in a clean chroot?

  - [ ] Yes
  - [x] No

**Comment by dr460nf1r3** [comment]
Ah, a new dependency which isn't in the repo yet 👀

**Comment by NerosTie** [comment]
Fixed, thanks :)
