### ISSUE TITLE
Request qbittorrent-enhanced-qt5

### ISSUE THREAD

**Issue by robson-66** [chaotic-aur/packages#1164]
##  👶 New package requests

- Link to the package(s) in AUR: [qbittorrent-enhanced-qt5](https://aur.archlinux.org/packages/qbittorrent-enhanced-qt5/)

- **Utility** this package has for you

  *This is the place to describe how you use the package and how it can be helpful.*

- Do you consider the package(s) to be useful for **every** Chaotic-AUR user?

  - [ ] YES!
  - [ ] No, but for a great amount.
  - [x] No, but for a few.
  - [ ] No, it's useful only for me.

- Do you consider the package to be **useful for feature testing**/preview (e.g: mesa-aco, wine-wayland)?

  - [ ] Yes
  - [x] No

- Are you sure the package **isn't available already** (test with `pacman -Ss <pkgname>`) ?

  - [x] Yes

- Have you tested if the package builds in a [**clean chroot**](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot)?

  - [ ] Yes
  - [x] No

- Does the package's **license** allow redistributing it?

  - [x] YES!
  - [ ] No clue.
  - [ ] No, but the author doesn't really care anyways. It's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request **is unique**?

  - [x] YES!

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is **not banned**?

  - [x] YES!

**Comment by dr460nf1r3** [comment]
Hey there :) what exactly is the purpose of this? I'm assuming qbittorrent is now built using Qt6 ?

**Comment by ObserverOfTime** [comment]
Yes, qBittorrent is built with Qt6 now which doesn't have proper theming support yet.

Personally, I'd prefer `qbittorrent-qt5` instead since `qbittorrent-enhanced-git` is still built with Qt5.

**Comment by robson-66** [comment]
Exactly yes, it's about the theme which is using `qt5ct` to make it dark. Unfortunately `qbittorrent` built on `qt6` does not offer any theme.

![ScreenShot](https://i.postimg.cc/dVtQfJFG/screen.png)

**Comment by robson-66** [comment]
Thanks Nico.
