### ISSUE TITLE
Fluent & Fluent round Icon theme

### ISSUE THREAD

**Issue by soumyatheman** [chaotic-aur/packages#1166]
##  👶 New package requests

- Link to the package(s) in AUR: https://aur.archlinux.org/fluent-icon-theme-git.git

- **Utility** this package has for you
- Icon Pack
  *This is the place to describe how you use the package and how it can be helpful.*
Icon Pack mainly for gnome, Also thinking to make a merge request in the Garuda Gnome Edition and make this icon pack the default one and to do so it's necessary that this is in the repository.

- Do you consider the package(s) to be useful for **every** Chaotic-AUR user?
    
     YES!
- Do you consider the package to be **useful for feature testing**/preview (e.g: mesa-aco, wine-wayland)?
     
     No

- Are you sure the package **isn't available already** (test with `pacman -Ss <pkgname>`) ?
    
    Yes

- Have you tested if the package builds in a [**clean chroot**](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot)?
    
   Yes

- Does the package's **license** allow redistributing it?

   YES!

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request **is unique**?

   YES!

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is **not banned**?

   YES!

**Comment by dr460nf1r3** [comment]
Hey, which package is meant here exactly? The linked one does not exist and there are a few ones with the name `fluent` :eyes:

**Comment by soumyatheman** [comment]
Sorry, made a mistake taking the links :( 
Giving the new links
[Fluent Icon theme](https://aur.archlinux.org/pkgbase/fluent-icon-theme-git/)
[Fluent GTK theme](https://aur.archlinux.org/pkgbase/fluent-icon-theme-git/)

**Comment by soumyatheman** [comment]
That's too fast😁😁😁Sent using Zoho Mail ---- On Sun, 16 Jan 2022 02:14:26 +0530  ***@***.***  wrote ----
Closed #1166 via 178e758.
