### ISSUE TITLE
[Request] sddm-theme-astronaut

### ISSUE THREAD

**Issue by joe733** [chaotic-aur/packages#1168]
##  👶 Requesting new package

- <https://aur.archlinux.org/packages/sddm-theme-astronaut/>

- A theme for the login screen

- Do you consider the package(s) to be useful for **every** Chaotic-AUR user?

  - [ ] YES!
  - [X] No, but for a great amount, who use SDDM.
  - [ ] No, but for a few.
  - [ ] No, it's useful only for me.

- Do you consider the package to be **useful for feature testing**/preview (e.g: mesa-aco, wine-wayland)?

  - [X] Yes
  - [ ] No

- Are you sure the package **isn't available already** (test with `pacman -Ss <pkgname>`) ?

  - [X] Yes

- Have you tested if the package builds in a [**clean chroot**](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot)?

  - [ ] Yes
  - [X] No

- Does the package's **license** allow redistributing it?

  - [X] YES!
  - [ ] No clue.
  - [ ] No, but the author doesn't really care anyways. It's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request **is unique**?

  - [X] YES!

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is **not banned**?

  - [X] YES!

**Comment by xiota** [comment]
Dropping because fails to build and not updated to Qt6.  AUR package is orphaned.  Metrics 148.

**Comment by D3vil0p3r** [comment]
I can adopt the package and fix the build

**Comment by xiota** [comment]
Looks like upstream still hasn't updated to Qt6.

**Comment by D3vil0p3r** [comment]
@xiota what if I adopt that package and I replace it by this: https://github.com/Keyitdev/sddm-astronaut-theme ? And I change the name accordingly

**Comment by xiota** [comment]
I'd suggest opening deletion request (not merge) against the qt5 package.

**Comment by D3vil0p3r** [comment]
> I'd suggest opening deletion request (not merge) against the qt5 package.

I'll do deletion req
