### ISSUE TITLE
[Request] Dbus-X11 Package 

### ISSUE THREAD

**Issue by soumyatheman** [chaotic-aur/packages#1170]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/dbus-x11/

### Utility this package has for you

This package allows using dconf and dbus-launch automatically even in x11, which is primarily not there. Every Gnome user under xorg will need this.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by dr460nf1r3** [comment]
I was quicker. lol 
https://github.com/chaotic-aur/packages/commit/ee553b688f761e029a8090091c9339c9c7a1f47a
