### ISSUE TITLE
[Request]  Gnome Shell Extension X11 gestures

### ISSUE THREAD

**Issue by soumyatheman** [chaotic-aur/packages#1172]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/gnome-shell-extension-x11gestures

### Utility this package has for you

This package enables gnome 4x's awesome touchpad gestures in the Xorg, which is currently only supported in Wayland.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because AUR package is orphaned and GNOME is now Wayland only.  Metrics 7.
