### ISSUE TITLE
[Request] qbittorrent-qt5

### ISSUE THREAD

**Issue by Drommer** [chaotic-aur/packages#1178]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/qbittorrent-qt5

### Utility this package has for you

Since version 4.4.0 in the official repository the application is built on Qt 6. The appearance of the application is terrible (the Breeze theme for Qt 6 is missing).

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [x] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by robson-66** [comment]
Why do you need `qbittorrent-qt5` if there is a `qbittorrent-enhanced-qt5` added to the chaotic-aur repo.

**Comment by ObserverOfTime** [comment]
Why do you need qBittorrent Enhanced in particular?

**Comment by dr460nf1r3** [comment]
Well, everyone got preferences I guess. lol
