### ISSUE TITLE
[Request] gnome-shell-extension-dash-to-panel-git

### ISSUE THREAD

**Issue by arun54321** [chaotic-aur/packages#1179]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/gnome-shell-extension-dash-to-panel-git/

### Utility this package has for you

Enables traditional desktop on gnome shell.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by evansan** [comment]
I can't find this package in the repo, was it removed? Can we add it to the repo again?

**Comment by Technetium1** [comment]
It was never added, they closed the issue.

**Comment by xiota** [comment]
Dropping because `extra/gnome-shell-extension-dash-to-panel` is available.  Currently one commit difference between stable and git versions.  Metrics 3.
