### ISSUE TITLE
[Bug] tauon-music-box

### ISSUE THREAD

**Issue by bipox** [chaotic-aur/packages#1180]
### What happens?

Program won't start.

### What is expected to happen?

Start. (has github changed recently? sorry about dumb answer, not a dev and not sure what is expected here)

### If possible, please attach logs

```
tauon
Traceback (most recent call last):
  File "/opt/tauon-music-box/tauon.py", line 8, in <module>
    from sdl2 import *
ModuleNotFoundError: No module named 'sdl2'
```

### More information

It works when installed from AUR.

Rebuild python-pysdl2 ?

Cheers!

**Comment by dr460nf1r3** [comment]
Hey there! I'm sorry, but I'm afraid I do not understand the problem.. Neither tauon-music-box nor python-pysdl2 is present in Chaotic-AUR :eyes: Can you provide some more information please?

**Comment by bipox** [comment]
oh woops... it's in the arcolinux 3rd party repo, indeed not in Chaotic-AUR.

Sorry about that!
