### ISSUE TITLE
[Bug] signalbackup-tools-git build failed

### ISSUE THREAD

**Issue by Smart123s** [chaotic-aur/packages#1182]
### What happens?

From https://builds.garudalinux.org/repos/chaotic-aur/logs/signalbackup-tools-git.log

> ==> Starting build()...
/bin/sh: /BUILDSCRIPT.sh: No such file or directory
==> ERROR: A failure occurred in build().
    Aborting...

### What is expected to happen?

Successful build. A package update was pushed to the AUR which *should* fix the issue. It fixed it for me.

### If possible, please attach logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/signalbackup-tools-git.log

### More information

Successful build package version: 20210128.r0.g563fe38-1
Current version in Chaotic AUR: 20220107.r0.g35b0f4c-1

**Comment by dr460nf1r3** [comment]
That looks rather like a PKGBUILD issue, I just triggered a rebuild and its still happening. To confirm, you build the package on your personal device successfully?

**Comment by Smart123s** [comment]
> To confirm, you build the package on your personal device successfully?

Yes, I did. I used Arch WSL2. I don't use it often, so I didn't have too many packages installed. I think I had Wine (on Windows... ikr...), base-devel, git and yay installed.

I used `yay -S signalbackup-tools-git` to build the package.

**Comment by dr460nf1r3** [comment]
Thanks for the report, then its a toolbox bug most likely :eyes:

**Comment by Smart123s** [comment]
Thanks for your fast response, I'll post here if I find out anything new.

**Comment by Smart123s** [comment]
I have created a clean Arch VM & installed https://builds.garudalinux.org/repos/chaotic-aur/x86_64/signalbackup-tools-git-20220107.r0.g35b0f4c-1-x86_64.pkg.tar.zst in it with pacman, and `signalbackup-tools` works.

**Comment by dr460nf1r3** [comment]
Thanks, glad you got it working :)
