### ISSUE TITLE
[Request] ros-noetic-desktop-full (& its dependencies)

### ISSUE THREAD

**Issue by fcolecumberri** [chaotic-aur/packages#1183]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/ros-noetic-desktop-full/

### Utility this package has for you

This is the Robot Operating System (ROS https://www.ros.org/ https://en.wikipedia.org/wiki/Robot_Operating_System ) main metapackage (it doesn't include every ros-noetic package as dependency nor is an operating system despite the name). Having ROS as a binary should improve the prospects of arch (and arch-based OS) as a viable operating systems for robots. Specially considering that some robots have low power consumption systems and compile everything from the AUR might not be the best of ideas.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Despite ROS having multiple currently supported versions (Noetic, Melodic & Kinetic) Noetic is the only ROS version that doesn't require python2, therefore while I request *ros-noetic-desktop-full*, I advice to not add any older versions.

There also exists ROS2 which is still on an early stage of development and therefore I am not requesting it.

**Comment by dr460nf1r3** [comment]
Now that I had a closer look, this package literally pulls around 100+ dependencies.. Given that you are the first one to request this (I never heard of it before myself), I'm declining this request unless another Chaotic-AUR maintainer is motivated to maintain this properly.

**Comment by 123-123-nil** [comment]
@dr460nf1r3 If possible, can chaotic AUR provide gazebo?. It is one of ros dependency and needs huge amount of ram to compile (a single threaded compile without -pipe fails on my machine with 16 GB of ram). This software sadly does not provide binaries for non-ubuntu machines. Thanks!

**Comment by dr460nf1r3** [comment]
I'll think about it. Would you be so kind to create a different issue, so we can track progress? Thanks :)
