### ISSUE TITLE
[Bug] pcsx2-git

### ISSUE THREAD

**Issue by NerosTie** [chaotic-aur/packages#1188]
### What happens?

When launching `pcsx2` from the terminal, it crashes and we have this error:

```
[1]    295449 illegal hardware instruction (core dumped)  pcsx2
```

Tested with pcsx2-git 1.7.2249-1.

No issue with pcsx2 1.7.2250 from the repo "aur".
No issue with pcsx2 1.7.2243-3 from the repo "community".

### What is expected to happen?

It shouldn't crash.

**Comment by dr460nf1r3** [comment]
Could you try building pcsx2-git from AUR to see if it also happens? There were cases of AUR packages built with specific CPU instructions which weren't available on users CPUs, although I'm not sure if that's the case here.

**Comment by NerosTie** [comment]
@dr460nf1r3 There is no issue with pcsx2-git from AUR. The one on Chaotic has been updated to 1.7.2250 and the issue is still here.

**Comment by dr460nf1r3** [comment]
Thanks for reporting back, we will look into this then :)

**Comment by NerosTie** [comment]
It looks like it's fixed (v1.7.2277)

**Comment by xiota** [comment]
Error when trying to run:

```
$ pcsx2-qt
pcsx2-qt: error while loading shared libraries: libryml.so.0.4.1: cannot open shared object file: No such file or directory
```

¿Needs to be rebuilt?

**Comment by xiota** [comment]
This can be closed again.  The library loading problem is resolved now.  The AUR package was updated with:
```
    -DUSE_SYSTEM_FMT=OFF \
    -DUSE_SYSTEM_LIBZIP=OFF \
    -DUSE_SYSTEM_RYML=OFF \
    -DUSE_SYSTEM_SDL2=ON \
    -DUSE_SYSTEM_ZSTD=OFF \
```

**Comment by dr460nf1r3** [comment]
Very nice :)
