### ISSUE TITLE
[Bug] urlgrabber package completely broken.

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#1190]
### What happens?

The package as it stands is built against python2, despite upstream and the package in aur supporting python3.
It also has a dependency `python2-pycurl` which is missing in chaotic-aur.

### What is expected to happen?

The package in AUR is renamed to [python-urlgrabber](https://aur.archlinux.org/packages/python-urlgrabber/).
It builds successfully against python3. It does sadly have 2 missing check dependencies also - `python-pip` and `python-wheel`.
Please build this new package instead.

**Comment by dr460nf1r3** [comment]
Will do, thanks for reporting! 😊
