### ISSUE TITLE
[Request] prospect-mail-bin

### ISSUE THREAD

**Issue by pixtolero** [chaotic-aur/packages#1192]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/prospect-mail-bin/

### Utility this package has for you

Outlook mail client for professional purpose

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

MIT license

**Comment by xiota** [comment]
Dropping because uses EOL Electron/27.0.2.  Metrics 14.
