### ISSUE TITLE
[Request] stumpwm & stumpwm-contrib

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#1196]
### Link to the package(s) in the AUR

[stumpwm](https://aur.archlinux.org/packages/stumpwm/)
[stumpwm-git](https://aur.archlinux.org/packages/stumpwm-git/)
[stumpwm-contrib-git](https://aur.archlinux.org/packages/stumpwm-contrib-git/)

### Utility this package has for you

StumpWM is a tiling window manager that was created when developer Shawn Betts found ratpoison growing increasingly large and "lispy". Intended as a successor to ratpoison, StumpWM is released under the terms of the GNU General Public License, version 2 (GPLv2)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

**Prerequisites** :
-   SBCL
-   quicklisp (for obtaining the following dependencies; not needed if you use your distribution's package manager.)
-   clx
-   cl-ppcre
-   alexandria

**stumpwm-contrib** : Extension Modules for StumpWM.
Modules are the canonical way to extend StumpWM using Lisp code.
Being implemented in Lisp, you have all the facilities of a Lisp system in your hands to write your own module.
StumpWM searches for modules in the *data-dir*/modules directory. By default this is ~/.stumpwm.d/modules.

**Comment by dr460nf1r3** [comment]
Are you using stable or -git? I would like to add the one you actually use only :)

**Comment by ALipAkrohk** [comment]
> Are you using stable or -git? I would like to add the one you actually use only :)

I use the git and stumpwm-contrib-git versions (simultaneously), but you can add whichever you think is more useful to the repository.
stabled or Git.

**Comment by dr460nf1r3** [comment]
Is this PKGBUILD supposed to be used with user input? Build stalls sadly.. 
```
(SB-KERNEL::%FILE-ERROR #P"/home/main-builder/.cache/common-lisp/sbcl-2.2.1-linux-x64/usr/share/common-lisp/source/alexandria/alexandria-1/package.fasl" "Can't create directory ~A~:[~;,~%a file with ~
the same name already exists.~]" "/home/main-builder/.cache/common-lisp/sbcl-2.2.1-linux-x64/usr/share/common-lisp/source/alexandria" NIL)
```
