### ISSUE TITLE
[Bug] Freetube Crashes on Wayland

### ISSUE THREAD

**Issue by MetalNeo** [chaotic-aur/packages#1202]
### What happens?

The `freetube` package crashes after being installed on KDE Wayland. The crash error is noted below.

### What is expected to happen?

The app should launch and not display an error.

### If possible, please attach logs

Error when launching:
[98350:0100/000000.014964:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is egl, ANGLE is

### More information

I am forcing Electron to use Wayland as outlined here: https://wiki.archlinux.org/title/wayland#Electron

The `freetube` package from the AUR appears to have the same issue as the Chaotic-AUR's package.
However, the `freetube-bin` package from the AUR doesn't appear to crash when launching.

**Comment by dr460nf1r3** [comment]
Hey :) What is the actual request here? Since it seems to happen for the AUR version as well it's obviously nothing we would fix on our side 👀

**Comment by MetalNeo** [comment]
My apologies! I seem to have forgotten what makes `freetube` and `freetube-bin` different from each other. 😅

I'll go ahead and mark this as resolved.

**Comment by dr460nf1r3** [comment]
Absolutely no problem! :)
