### ISSUE TITLE
[Request] PolyMC

### ISSUE THREAD

**Issue by FireMasterK** [chaotic-aur/packages#1205]
### Link to the package(s) in the AUR

[polymc](https://aur.archlinux.org/packages/polymc/)
[polymc-bin](https://aur.archlinux.org/packages/polymc-bin/)
[polymc-git](https://aur.archlinux.org/packages/polymc-git/)

### Utility this package has for you

It's a fork of MultiMC, licensed under GPL.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by dr460nf1r3** [comment]
Hello 🙂 which of these are you actually using?

**Comment by FireMasterK** [comment]
I use the first one personally.
