### ISSUE TITLE
[Bug] PGP Keys again

### ISSUE THREAD

**Issue by EAJGlobal** [chaotic-aur/packages#1207]
### What happens?

Trying to setup on my fresh Arch Linux with KDE install and PGP keys for the repo are erroring out again.

### What is expected to happen?

Mirrorlist to download and sync

### If possible, please attach logs

pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
loading packages...
error: '/var/cache/pacman/pkg/chaotic-keyring.pkg.tar.zst': invalid or corrupted package (PGP signature)
error: '/var/cache/pacman/pkg/chaotic-mirrorlist.pkg.tar.zst': invalid or corrupted package (PGP signature)

**Comment by JustTNE** [comment]
Please follow the instructions on https://aur.chaotic.cx/ carefully and don't skip any steps. When following all steps, I fail to reproduce this issue.

**Comment by EAJGlobal** [comment]
Strange, still fails on my machine, Ive found the firedragon package in the arch aur now so switching to use that.
