### ISSUE TITLE
[Request] ffmpeg-vulkan

### ISSUE THREAD

**Issue by matteoturini** [chaotic-aur/packages#1209]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/ffmpeg-vulkan/

### Utility this package has for you

Dependency for ALVR. Allows converting Vulkan frames directly in GPU without copying.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

I marked "No clue" on licensing because I don't know if FFmpeg's license allows redistribution.

**Comment by xiota** [comment]
Request remove `ffmpeg-vulkan`.

1. It is not building or has other issues preventing it from appearing in the repository:
    ```
    $ pacman -Ss ffmpeg-vulkan
    
    $
    ```
2. `alvr` no longer requires this as a dependency.
    ```
    $ pacman -Ss alvr
    chaotic-aur/alvr 19.1.0.r0.g969899c7-1
        Experimental Linux version of ALVR. Stream VR games from your PC to your headset via Wi-Fi.

    $ pacman -Si alvr
    Repository      : chaotic-aur
    Name            : alvr
    Version         : 19.1.0.r0.g969899c7-1
    Description     : Experimental Linux version of ALVR. Stream VR games from your PC to your headset via Wi-Fi.
    Architecture    : x86_64
    URL             : https://github.com/alvr-org/ALVR
    Licenses        : MIT
    Groups          : None
    Provides        : alvr
    Depends On      : vulkan-driver  libunwind  ffmpeg
    Optional Deps   : None
    Conflicts With  : alvr
    Replaces        : None
    Download Size   : 9.53 MiB
    Installed Size  : 23.75 MiB
    Packager        : Eduard Tolosa <edu4rdshl@protonmail.com>
    Build Date      : Sun Feb 19 10:13:02 2023
    Validated By    : MD5 Sum  SHA-256 Sum  Signature
    ```
