### ISSUE TITLE
[Request] ALVR

### ISSUE THREAD

**Issue by matteoturini** [chaotic-aur/packages#1210]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/alvr/
https://aur.archlinux.org/packages/alvr-git/

### Utility this package has for you

Oculus Quest VR on Linux

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [x] YES!

**Comment by Edu4rdSHL** [comment]
I have added `alvr` but not `alvr-git`, I wonder if it makes sense to add the -git package since it's a experimental software.
