### ISSUE TITLE
[Remove] nvlax-git

### ISSUE THREAD

**Issue by Weirdo1312** [chaotic-aur/packages#1212]
### Package

https://aur.archlinux.org/packages/nvlax-git

Upstream:
https://github.com/illnyang/nvlax

### Purpose

with the patch, nvenc can encode more than 3 videos at once
and with nvfbc you can capture the framebuffer of the gpu when recording your screen in obs, with this method you'll have **VERY** little performance loss when recording or streaming

### License

GPL 3.0

**Comment by Edu4rdSHL** [comment]
Done!

**Comment by xiota** [comment]
Fails to build.  Don't know how to fix.  Metrics 0.

Update: Dropped.  Use nvidia-patch-git instead..

**Comment by Edu4rdSHL** [comment]
Feel free to drop it
