### ISSUE TITLE
[Request] Logseq

### ISSUE THREAD

**Issue by theCode-Breaker** [chaotic-aur/packages#1213]
### Link to the package(s) in the AUR

~~https://aur.archlinux.org/packages/logseq-desktop-bin~~
Added: https://aur.archlinux.org/packages/logseq-desktop

### Utility this package has for you

A privacy-first, open-source knowledge base
Logseq is a joyful, open-source outliner that works on top of local plain-text Markdown and Org-mode files. Use it to write, organize and share your thoughts, keep your to-do list, and build your own digital garden.
Open source alternative to Obsidian

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Edu4rdSHL** [comment]
Done!
