### ISSUE TITLE
[Outdated] librewolf-extension-bitwarden

### ISSUE THREAD

**Issue by MetalNeo** [chaotic-aur/packages#1217]
### Package name

librewolf-extension-bitwarden

### Latest build

1.54.0

### Latest version available

1.55.0

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

Addon will no longer allow for sign-in. Latest version from official page at addons.mozilla.org allows for sign-in without issue.

**Comment by dr460nf1r3** [comment]
Hey there! This shouldve been reported at the corresponding AUR page instead of this repo. Luckily I maintain the package though, so its updated nevertheless 😋
