### ISSUE TITLE
[Outdated] visual-studio-code-bin

### ISSUE THREAD

**Issue by coxackie** [chaotic-aur/packages#1218]
### Package name

visual-studio-code-bin

### Latest build

1.64.0

### Latest version available

1.63.2

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### More information

Package was updated more than 12 hours now.

**Comment by coxackie** [comment]
and again, 1.64.1 has been out for some hours, but there is no update.

**Comment by coxackie** [comment]
again, 1.65.2 is available on the AUR since yesterday, while chaotic is stuck at 1.65.1...

**Comment by dr460nf1r3** [comment]
Thanks for your reports, we really need to investigate why this keeps happening.. the fact that there aren't logfiles about failed builds doesn't help 😅 I built it manually (again).

**Comment by dr460nf1r3** [comment]
I'm quite confident the issue is solved by now - `joplin` was blocking the routine as a patch didn't apply cleanly.

**Comment by coxackie** [comment]
@dr460nf1r3  it indeed updated automatically this time. Many thanks!
