### ISSUE TITLE
[Bug] Wayfire

### ISSUE THREAD

**Issue by mdhishamsayed** [chaotic-aur/packages#1222]
### What happens?

it needs wlroots<0.15 but the current version is 0.15.0-4

### What is expected to happen?

we need to update the pkgbuild

### If possible, please attach logs

चेतावनी :"wlroots<0.15" हेतु आश्रित पैकेज "wayfire" का समन्वय विफल
:: असमन्वयित आश्रित पैकेज होने के कारण निम्नलिखित पैकेज अपग्रेड करना संभव नहीं है :
      wayfire

:: इस अपग्रेड हेतु, क्या आप ऊपर दिए पैकेज को निरस्त करना चाहते हैं? [y/N] n
त्रुटि :संचालन तैयार करना विफल (आश्रित पैकेज समन्वयन विफल)
:: wlroots<0.15 हेतु आवश्यक आश्रित पैकेज 'wayfire' समन्वयन विफल

**Comment by dr460nf1r3** [comment]
Usually we don't update packages ourselves unless its a package we control. Did you check if the blocker is in place for a reason?

**Comment by mdhishamsayed** [comment]
@dr460nf1r3 no blocker is in place

**Comment by dr460nf1r3** [comment]
You could try to install wlroots-git?
