### ISSUE TITLE
[Request] Sioyek pdf reader

### ISSUE THREAD

**Issue by okarin69** [chaotic-aur/packages#1226]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/sioyek-git

### Utility this package has for you

PDF viewer for research papers and technical books. Supports customized shortcuts and more features that make things easier.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information
https://github.com/ahrm/sioyek

**Comment by Edu4rdSHL** [comment]
The package doesn't build in a clean chroot:

```
pdf_viewer/sqlite3.c:128008:10: note: declared here
128008 |   Select standin;
       |          ^~~~~~~
g++ -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Wl,-rpath-link,/usr/lib -fPIC -o sioyek book.o config.o database.o document.o document_view.o input.o main.o main_widget.o pdf_renderer.o pdf_view_opengl_widget.o checksum.o sqlite3.o ui.o path.o utils.o synctex_parser.o synctex_parser_utils.o RunGuard.o moc_pdf_renderer.o moc_RunGuard.o   -ldl -Lmupdf/build/release -lmupdf -lmupdf-third -lmupdf-threads -lharfbuzz -lz /usr/lib/libQt5OpenGL.so /usr/lib/libQt5QuickWidgets.so /usr/lib/libQt5Widgets.so /usr/lib/libQt5Quick.so /usr/lib/libQt53DAnimation.so /usr/lib/libQt53DExtras.so /usr/lib/libQt53DRender.so /usr/lib/libQt53DInput.so /usr/lib/libQt53DLogic.so /usr/lib/libQt53DCore.so /usr/lib/libQt5OpenGLExtensions.a /usr/lib/libQt5Gui.so /usr/lib/libQt5Sql.so /usr/lib/libQt5QmlModels.so /usr/lib/libQt5Qml.so /usr/lib/libQt5Network.so /usr/lib/libQt5Core.so -lGL -lpthread   
/usr/sbin/ld: cannot find -lmupdf
/usr/sbin/ld: cannot find -lmupdf-third
/usr/sbin/ld: cannot find -lmupdf-threads
collect2: error: ld returned 1 exit status
make: *** [Makefile:263: sioyek] Error 1
cp: cannot stat 'sioyek': No such file or directory
==> Entering fakeroot environment...
==> Starting package()...
install: cannot stat './build/sioyek': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
Container pkg1a80fc7c13c failed with error code 4.
```

**Comment by dr460nf1r3** [comment]
Oops.

**Comment by okarin69** [comment]
My request did not get a response from the head developer, I have put another request for the AUR maintainer. Lets hope we see a fix soon :smile: 

https://aur.archlinux.org/packages/sioyek-git#comment-852113

**Comment by okarin69** [comment]
@dr460nf1r3 @Edu4rdSHL the maintainer has fixed the issue and it should work as expected now.

https://github.com/ahrm/sioyek/issues/125#issuecomment-1042811429

**Comment by dr460nf1r3** [comment]
Sounds great, thanks for the notice! I'll add it by the weekend if @Edu4rdSHL doesn't add it by then 😊

**Comment by okarin69** [comment]
Thank you so much @dr460nf1r3 @Edu4rdSHL

**Comment by dr460nf1r3** [comment]
Np, I'm sorry I forgot about it last weekend :/

**Comment by okarin69** [comment]
Hey @dr460nf1r3 can we change the package base to https://aur.archlinux.org/pkgbase/sioyek from this one, the developers changed this package to be the development version and the stable version was added later. Please let me know if I should open a new issue or this could be done otherwise. Thanks :D

**Comment by okarin69** [comment]
Wow thank you so much @dr460nf1r3 @Technetium1 :smile:

**Comment by okarin69** [comment]
@dr460nf1r3 it's been long since this package has been updated and it does not work on qt6 environments anymore. I request you to shift to [sioyek-git](https://aur.archlinux.org/sioyek-git.git), as it is more regularly updated and works in modern environments. Thanks!

**Comment by dr460nf1r3** [comment]
Sounds like a good idea to me 👍

**Comment by okarin69** [comment]
@dr460nf1r3 I was under the assumption that the sioyek aur package is so old that it does not launch on plasma 6 because of the Qt5 dependencies. But now after shifting to sioyek-git I think there is some issue in building the package. 

I am saying this because both the packages work fine when built and installed from the aur, but when installed from chaotic-aur they do not launch at all. Hope we can resolve this issue.

**Comment by xiota** [comment]
@okarin69 `chaotic-aur/sioyek-git` is also not working?

**Comment by okarin69** [comment]
Yes, it is working now. Thanks @xiota @dr460nf1r3. Much appreciated.
