### ISSUE TITLE
[Request] python-poetry-git

### ISSUE THREAD

**Issue by caniko** [chaotic-aur/packages#1227]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/python-poetry-git

### Utility this package has for you

Package manager for my python packages

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by dr460nf1r3** [comment]
Package is still failing to build as of now, reported the issue at the AUR page.

**Comment by caniko** [comment]
> Package is still failing to build as of now, reported the issue at the AUR page.

Did you try with `python-cleo-git` installed?

**Comment by Technetium1** [comment]
Thanks for the update @caniko, it's no longer failing.

**Comment by xiota** [comment]
@caniko Recently removed `python-poetry-git` because of dependency issues, but might be easier to fix than I had previously thought.  I believe it hadn't been building successfully for at least several months.  Do you still have a need for `python-poetry-git`?  If so, would you explain the benefit over `community/python-poetry`?

**Comment by caniko** [comment]
It has the newest features. There are times when minor bugfixes that I needed were not on the latest release, but on the git version.

**Comment by xiota** [comment]
Okay.  I'll try to put it back later.  Some of the blockers are related to the 3.11 upgrade, so may take a while.

**Comment by caniko** [comment]
@xiota, thanks for the heads up! No rush from my side

**Comment by xiota** [comment]
Dropped because rebuild failed for Python 3.14.  Users advised to use `extra/python-poetry`.  Metrics 58.
