### ISSUE TITLE
[Outdated] tenacity-git still depends on jack2 instead of jack

### ISSUE THREAD

**Issue by Beuscher** [chaotic-aur/packages#1228]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/tenacity-git.log

### Package name

tenacity-git

### Latest build

1:r13926.g0665614b8-1 (So 05 Dez 2021 11:52:31 CET)

### Latest version available

1:r13926.g0665614b8-1 

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### More information

The build available on the AUR still has jack2 as a dependency, however it was recently ([aur commit](https://aur.archlinux.org/cgit/aur.git/commit/?h=tenacity-git&id=e9cb077e2862143a00f8028a44e1c3854f209a07)) changed into jack to ensure compatibility with pipewire-jack.

**Comment by dr460nf1r3** [comment]
Rebuild done! I'll leave this issue open as the source of the error in the logs still needs to be fixed :)
