### ISSUE TITLE
[Outdated] plymouth-git

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#1241]
### If available, link to the latest build

[plymouth-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/plymouth-git.log)

### Package name

`plymouth-git`

### Latest build

`0.9.5.r110.g5b91b9e-1`

### Latest version available

`22.02.122.r2.g716b5bd-1`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

I'm not for certain this name is broken or if it's outdated, but I suspect outdated. Something definitely looks wrong at the end of the build log.

**Comment by dr460nf1r3** [comment]
The PKGBUILD needs to be fixed, inputs don't work in automatic builds. You're right about that :)

**Comment by dr460nf1r3** [comment]
Seems like it built successfully! :eyes:
