### ISSUE TITLE
[Request] chromium wayland vaapi

### ISSUE THREAD

**Issue by userofryzen** [chaotic-aur/packages#1243]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/chromium-wayland-vaapi

### Utility this package has for you

enable vaapi on wayland ozone systems without having to go Xwayland chromium way( apart, its buggy)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

BSD license at least from the aur package, it takes so long to compile it's why i have not tested but there are no fails on comments since last updated I think.

**Comment by dr460nf1r3** [comment]
The package is added to the routine and will built the next time it runs :)

**Comment by dr460nf1r3** [comment]
The build sadly never finished, it ran yesterday. Just reported this to the AUR page and added the [logs](https://builds.garudalinux.org/repos/chaotic-aur/logs/chromium-wayland-vaapi.log) in case the maintainer can help with that :)

**Comment by RubenKelevra** [comment]
I'm also interested, but there seems to be no update by the developer 🤔

**Comment by emanuelserpa** [comment]
https://aur.archlinux.org/packages/ungoogled-chromium-wayland is an alternative package.

**Comment by userofryzen** [comment]
> https://aur.archlinux.org/packages/ungoogled-chromium-wayland is an alternative package.

i dont think is an alternative.. it haas vaapi working on ozone wayland?

While I'm using the official from arch/manjaro repos that has ozone X11 vaapi working out of the box almost

**Comment by dr460nf1r3** [comment]
The package has been disowned, so I guess there will be no more updates to this one. If there are alternatives just shoot a message so we can have a look at them :)

**Comment by RubenKelevra** [comment]
> The package has been disowned

I've asked for this.

> so I guess there will be no more updates to this one.

That's pretty unlikely. Usually there will be someone who's willing to take over the maintenance/development. :)

I had a thought about doing this, but as I don't use Chromium, I really don't want to invest that amount of time into that.

**Comment by coxackie** [comment]
chromium-wayland-vaapi is on 104.0.5112.79-1 on AUR for some days now; chaotic-aur still has 103.0.5060.134-1

**Comment by dr460nf1r3** [comment]
`==> ERROR: A package has already been built. (use -f to overwrite)`, as of today 🤔 very weird. I'll try to trigger a manual build soonish.

**Comment by dr460nf1r3** [comment]
I see why, in fact it got deployed a few moments before I had a look at the log file 😂

![Screenshot_20220805-165459~2.png](https://user-images.githubusercontent.com/12834713/183103679-83c769b0-877d-439b-80b3-46cfdf546c68.png)

**Comment by xiota** [comment]
No longer needed according to Arch Wiki [Chromium#Hardware_video_acceleration](https://wiki.archlinux.org/title/Chromium#Hardware_video_acceleration).

> Since Chromium version 122, the `chromium-wayland-vaapi` package is no longer needed. VA-API works when using the native Wayland backend with the `chromium` package from official repositories.
