### ISSUE TITLE
[Bug]  Replace leagueoflegends-git with chaotic-aur/leagueoflegends-ge-git?

### ISSUE THREAD

**Issue by InvisibleRasta** [chaotic-aur/packages#1248]
### What happens?

When running pacman -Syu i keep getting this prompt. And no, I do not want to replace.

### What is expected to happen?

It should not prompt me to replace  leagueoflegends-git with chaotic-aur/leagueoflegends-ge-git

**Comment by dr460nf1r3** [comment]
Seems like the package introduced this lately, I'm gonna have a look soon.

**Comment by dr460nf1r3** [comment]
I had a look at the PKGBUILD - both the regular and ge versions are getting built by the same pkgbase and have `replaces()` set. Seems unncessary to me, I asked the maintainer to remove that.

**Comment by dr460nf1r3** [comment]
This should no longer be an issue as the maintainer removed the` replaces()` part of the PKGBUILD :)
