### ISSUE TITLE
[Outdated] natron packages and ffmpeg5

### ISSUE THREAD

**Issue by a61kt** [chaotic-aur/packages#1250]
### If available, link to the latest build

some natron packages depends on ffmpeg and they might give problems coz arch updated ffmpeg to 5.0  
https://aur.archlinux.org/packages/openfx-io

### Package name

openfx-io,natron

### Latest build

2.4.2

### Latest version available

2.4.2

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

_It might be necessary  cos ffmpeg5've changed-replaced their apis   https://ffmpeg.org/_

**Comment by dr460nf1r3** [comment]
I notified the `openfx-io` maintainer, hopefully he can do something about it :)

**Comment by dr460nf1r3** [comment]
We decided to not add the natron packages anymore due to the lack of maintenance: https://github.com/chaotic-aur/packages/issues/1084#issuecomment-1164749099
