### ISSUE TITLE
[Request] blender-git

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#1253]
### Package:

https://aur.archlinux.org/packages/blender-git

GitHub Project: https://github.com/blender/blender

### Purpose:

Blender is a free and open-source 3D computer graphics software tool set used for creating animated films, visual effects, art, 3D-printed models, motion graphics, interactive 3D applications, virtual reality, and, formerly, video games. Blender's features include 3D modelling, UV mapping, texturing, digital drawing, raster graphics editing, rigging and skinning, fluid and smoke simulation, particle simulation, soft body simulation, sculpting, animation, match moving, rendering, motion graphics, video editing, and compositing. 

### Copyright:

GPL2

### Expected Interest:

Some; metrics currently show 19 downloads

### Already available?

Yes; needs rebuild

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
`0002-embree.patch` is broken.  Tried to apply fix from [comment](https://aur.archlinux.org/packages/blender-git?all_deps=1#comment-930244), but have error:
```
==> Starting build()...
==> python version detected: 3.11
which: no gcc-11 in (/opt/lib:/opt/bin:/nix/store/pm4gxdsl1jjn3yr063si78b6636vvda7-systemd-253.6/bin/:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
==> ERROR: A failure occurred in build().
```

**Comment by xiota** [comment]
Closing because still fails to build.  Based on AUR comments, there are many problems, both old and new.  Too complicated to fix.  `extra/blender` is available.
