### ISSUE TITLE
[Outdated] fastgame-git

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#1255]
### If available, link to the latest build

[fastgame-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/fastgame-git.log)

### Package name

`fastgame-git`

### Latest build

`0.1.3.r9.g0e17f2c-1`

### Latest version available

`0.2.0.r0.g6a53b7c-1`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

This from end of log, though `adwaita-icon-theme` seems to get installed...
```
Run-time dependency libadwaita-1 found: NO (tried pkgconfig)
fastgame/src/meson.build:29:0: ERROR: Dependency "libadwaita-1" not found, tried pkgconfig
```

**Comment by dr460nf1r3** [comment]
In fact, it was `libadwaita` (and `cmake`) 😄
