### ISSUE TITLE
[Bug] Packages have disappeared from chaotic-aur

### ISSUE THREAD

**Issue by coxackie** [chaotic-aur/packages#1258]
### What happens?

At least three packages I have previously installed from `chaotic-aur` have disappeared (`opencl-amd`, `jamesdsp` and `spotify-adblock-git`). Most probably there must be more missing. For example, when I `pacman -Qi opencl-amd` I get `Packager: Chaotic-AUR Wild Bear Node <wildbear.node@chaotic.cx>` but `pacman -Si opencl-amd` gives `error: package 'opencl-amd' was not found`. Same with the other two packages.

### What is expected to happen?

Packages that we use and love not disappearing from `chaotic-aur`.  :(

**Comment by dr460nf1r3** [comment]
Thanks for the report, we were on it already :)

**Comment by coxackie** [comment]
@dr460nf1r3 Great. You are truly awesome!

**Comment by joe733** [comment]
Looks like quite some of them have disappeared... `grub-silent` #598, `choosenim` #419, `iota-firefly-wallet` #1112, `motrix-bin` #586, `teams` #679, `zoom` #939... searching for these packages returns nothing for Chaotic AUR (as of 20 Feb 2022, 11:37 UTC)

![image](https://user-images.githubusercontent.com/38415384/154840485-63440569-cc66-4be9-aea8-3194bd2fdd81.png)

**Comment by dr460nf1r3** [comment]
Yep, you are right. We started a full rebuild of the repo and stopped syncing changes to mirrors - eventually some of the removed packages still got synced by accident which resulted in this situation. We are working hard to get everything back as quickly as possible though :)

**Comment by joe733** [comment]
Hey, no pressure, thanks a lot!

**Comment by coxackie** [comment]
ok, sorry to get back at this, but `spotify-adblock-git` has once again disappeared from the repos. Could you please check what happened?

**Comment by dr460nf1r3** [comment]
There is an issue with building Spotify, therefore this package failed to build as well after our openssl3 rebuilds. I'll try to fix it soonish.

**Comment by coxackie** [comment]
hmmmm... still?

**Comment by Technetium1** [comment]
### Spotify failures:
- [ ] [spotify](https://builds.garudalinux.org/repos/chaotic-aur/logs/spotify.log)
- [ ] [spotify-adblock-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/spotify-adblock-git.log)
- [ ] [spotify-qt](https://builds.garudalinux.org/repos/chaotic-aur/logs/spotify-qt.log)
- [ ] [spotify-tui](https://builds.garudalinux.org/repos/chaotic-aur/logs/spotify-tui.log)
- [ ] [spotify-tray-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/spotify-tray-git.log)

**Comment by dr460nf1r3** [comment]
Not anymore! There are things like work days, you know ;)
