### ISSUE TITLE
[Bug] Zoom: move ibus from depends to optdepends

### ISSUE THREAD

**Issue by heavysink** [chaotic-aur/packages#1260]
### What happens?

ibus is unnecessary for zoom and may brought conflict when using other input method, e.g. fcitx. Tested on my machine and it will work. There are discussion about it already at AUR https://aur.archlinux.org/packages/zoom. It seems that the maintainer at AUR do not want to remove the dependency. I was wondering if ibus can be moved to optdepends at Chaotic-AUR.

### What is expected to happen?

Removing an unneeded dependency.

**Comment by dr460nf1r3** [comment]
Sure, sounds reasonable to me. Fixed in https://github.com/chaotic-aur/interfere/commit/87c4e1952cad1fa8d974acf741468fd6e04715bb
