### ISSUE TITLE
[Request] yandex-disk

### ISSUE THREAD

**Issue by BlitDev** [chaotic-aur/packages#1262]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/yandex-disk

### Utility this package has for you

This package provides **synchronization** of a local folder with a **remote Yandex Disk cloud storage** (**Russian** cloud)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
[Section 4 of the license](https://yandex.com/legal/browser_agreement/) forbids redistribution, especially where there are any modifications done.
Related: #2031
