### ISSUE TITLE
[Request] libxcrypt-compat and lib32-libxcrypt-compat

### ISSUE THREAD

**Issue by Evan-aja** [chaotic-aur/packages#1263]
### Link to the package(s) in the AUR

[libxcrypt-compat](https://aur.archlinux.org/packages/libxcrypt-compat)
[lib32-libxcrypt-compat](https://aur.archlinux.org/packages/lib32-libxcrypt-compat)

### Utility this package has for you

gives compatibility to legacy dependencies, like xampp which needs the libcrypt.so.1 library

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by dr460nf1r3** [comment]
The `libxcrypt-compat` package seems to no longer exist :eyes: I still added the other :)

**Comment by Evan-aja** [comment]
ohh yeah, it was added to official arch repository 5 days ago
