### ISSUE TITLE
[Request] pygtk

### ISSUE THREAD

**Issue by Evan-aja** [chaotic-aur/packages#1264]
### Link to the package(s) in the AUR

[pygtk](https://aur.archlinux.org/packages/pygtk)

### Utility this package has for you

this package is used as dependency for Python bindings of GTK apps widget set.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by dr460nf1r3** [comment]
This was in fact present already 🤔

**Comment by Evan-aja** [comment]
huh, weird, a few days ago it was missing from the repository, just like the chaotic keyring and mirrorlist, it suddenly vanished, but now present again in the repository

**Comment by dr460nf1r3** [comment]
That was because of a full rebuild we executed. Things are good again :)

**Comment by Evan-aja** [comment]
ahh, got it. a bit of update on the readme could be helpful in the future (like a schedule or short notice announcement)
thank you for the hard work on the repo :clinking_glasses:

**Comment by dr460nf1r3** [comment]
The initial plan was to do things behind the scenes but there were some issues we encountered. Otherwise an announcement would've been posted in https://t.me/chaotic_aur (I did in fact post about it after things took longer than expected), I'd recommend joining it to receive updates as we usually don't post about things here. Thanks for your feedback! 🥂
