### ISSUE TITLE
[Request] syncthingtray, syncthingtray-qt6

### ISSUE THREAD

**Issue by maltejur** [chaotic-aur/packages#1267]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/syncthingtray
https://aur.archlinux.org/packages/syncthingtray-qt6

### Utility this package has for you

This package is a very nice system integration for the headless [syncthing](https://archlinux.org/packages/community/x86_64/syncthing/), including a pretty good KDE integration.

![image](https://user-images.githubusercontent.com/48161361/154854937-a8dd06bb-4d3b-41db-957c-0f5ec350113c.png)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by maltejur** [comment]
❤️

**Comment by zany130** [comment]
There a new package for plasma 6 support https://aur.archlinux.org/packages/syncthingtray-qt6

**Comment by aik2mlj** [comment]
+1 for the plasma 6 package `syncthingtray-qt6`

**Comment by xiota** [comment]
That's interesting... Manjaro is still on KF5.
