### ISSUE TITLE
[Bug] megasync-bin breaks dependency 'megasync-bin' required by thunar-megasync-bin     

### ISSUE THREAD

**Issue by InvisibleRasta** [chaotic-aur/packages#1268]
### What happens?

:: Synchronizing package databases...
 core                                                   133.3 KiB   901 KiB/s 00:00 [------------------------------------------------] 100%
 extra                                                 1539.1 KiB  8.12 MiB/s 00:00 [------------------------------------------------] 100%
 community                                                6.1 MiB  21.7 MiB/s 00:00 [------------------------------------------------] 100%
 multilib                                               149.6 KiB  1076 KiB/s 00:00 [------------------------------------------------] 100%
 chaotic-aur is up to date
:: Starting full system upgrade...
:: Replace megasync-bin with chaotic-aur/megasync? [Y/n] y
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: removing megasync-bin breaks dependency 'megasync-bin' required by thunar-megasync-bin     

### What is expected to happen?

There is something wrong with some PKGBUILD

**Comment by dr460nf1r3** [comment]
Hey :) this is a packaging issue - thunar-megasync just wants megasync-bin in dependencies. We can fix this though by just adding provides=megasync-bin to the package 👀

**Comment by dr460nf1r3** [comment]
So the fix was committed to the interfere repo, the package doesn't build currently though. 
```
control/UpdateTask.cpp:555:65: warning: â€˜static QString QString::fromAscii(const char*, int)â€™ is deprecated [-Wdeprecated-declarations]
  555 |         MegaApi::log(MegaApi::LOG_LEVEL_INFO, QString::fromAscii("File already downloaded: %1").arg(localPaths[currentFile]).toUtf8().constData());
      |                                               ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/qt/QtCore/qcoreapplication.h:44,
                 from /usr/include/qt/QtCore/QCoreApplication:1,
                 from control/UpdateTask.h:4,
                 from control/UpdateTask.cpp:1:
/usr/include/qt/QtCore/qstring.h:730:41: note: declared here
  730 |     QT_DEPRECATED static inline QString fromAscii(const char *str, int size = -1)
      |                                         ^~~~~~~~~
make[1]: Leaving directory '/home/main-builder/pkgwork/src/MEGAsync/src/MEGASync'
make: *** [Makefile:47: sub-MEGASync-make_first] Error 2
```

**Comment by dr460nf1r3** [comment]
Megasync finally built so the issue should be fixed :)
