### ISSUE TITLE
[Request] webcamoid

### ISSUE THREAD

**Issue by joe733** [chaotic-aur/packages#1269]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/webcamoid

### Utility this package has for you

As camera and screen recording.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Done, but ominous errors in the log: [webcamoid.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/webcamoid.log)
