### ISSUE TITLE
[Outdated] opencl-amd

### ISSUE THREAD

**Issue by coxackie** [chaotic-aur/packages#1270]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/opencl-amd.log

### Package name

opencl-amd

### Latest build

21.40.1.1337803-1

### Latest version available

21.50.50000.1376259-3

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by coxackie** [comment]
So, not sure if this is again outdated, or has also just disappeared from the chaotic servers, thought it seems it is the latter. Can you please check?

**Comment by dr460nf1r3** [comment]
```
λ pacman -Ss opencl-amd
chaotic-aur/opencl-amd 22.40.0.50302-1
ROCr OpenCL stack, supports Vega 10 and later products - Legacy OpenCL stack
(Proprietary), supports legacy products older than Vega 10 - This package is intended to
work along with the free amdgpu stack.
```
