### ISSUE TITLE
[Request] labwc[-git]

### ISSUE THREAD

**Issue by logan2611** [chaotic-aur/packages#1283]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/labwc
https://aur.archlinux.org/packages/labwc-git

### Utility this package has for you

Stacking Wayland compositor inspired by [Openbox](http://openbox.org/wiki/Main_Page). Since `wayfire` has fallen out of date with wlroots, there are no longer any good wlroots based stacking Wayland compositors in the Chaotic-AUR (to my knowledge).

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
`labwc` and `libsfdo` dropped because moved to extra.  Metrics:

* libsfdo # 112
* labwc # 215
* labwc-git # 68
