### ISSUE TITLE
[Outdated] google-messages

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#1285]
### If available, link to the latest build

[google-messages.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/google-messages.log)

### Package name

`google-messages`

### Latest build

`1.3.0-1`

### Latest version available

`1.3.0-1`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

It probably just needs rebuilt as there's apparently a new version of Nativifier since the last build. If that doesn't fix it I can open another issue 
![image](https://user-images.githubusercontent.com/9877150/155430174-f25589bc-151c-4edf-bb14-46a176fc99d0.png)

**Comment by Technetium1** [comment]
The package is not actually out of date, but will need to be rebuilt. `nodejs-nativefier` released a new version and the maintainer has not yet bumped the pkgver. I built it myself then updated my [comment in the AUR](https://aur.archlinux.org/packages/nodejs-nativefier#comment-847132) to mention the new version also working with no changes required. It seems to just be simple [dependency bumps](https://github.com/nativefier/nativefier/compare/v46.0.4...v46.1.1) so nothing should break.

Packages requiring `nodejs-nativefier` will need to be rebuilt, though I'm not sure if that will happen automatically?
In the meantime this should probably have `waiting:upstream-fix` applied until it's updated.

**Comment by robson-66** [comment]
I had the same warning when running `google-messages`, but just rebuilt, and now this message is not displayed.

**Comment by dr460nf1r3** [comment]
The package has been rebuilt, please let us know if the issue is fixed :)

**Comment by Technetium1** [comment]
It was fixed! Should there be a separate issue for `nodejs-nativefier`? Are other related packages rebuilt as well? Did you use `46.1.0-1` in Chaotic or `46.1.1-1`?
