### ISSUE TITLE
[Bug] Firedragon PGP key error

### ISSUE THREAD

**Issue by Me-At-The-Age-Of-Git** [chaotic-aur/packages#1286]
### What happens?

![image](https://user-images.githubusercontent.com/96075551/155520215-2a76bbc4-dd4c-4e5e-b9c8-71ca01345c91.png)
when i tried to update my packages it prompted up a new key for the chaotic-aur, now after accepting it i can no longer download the Firedragon package since it says the keys are invalid or corrupted

### What is expected to happen?

package sync working without pgp key errors

**Comment by Me-At-The-Age-Of-Git** [comment]
as a mean time solution i'm ignoring the package using **--ignore=firedragon**

**Comment by sergen213** [comment]
I think its not package related, somethings wrong with their server. I'm getting error for updating chaotic keyring and it just says it can't be downloaded from remote server.

**Comment by Me-At-The-Age-Of-Git** [comment]
I think they fixed it, i tried updating again and it worked, i guess i'll close the issue then

**Comment by dr460nf1r3** [comment]
Must likely you didn't have SGS key added to your keyring yet. Since it is provided by chaotic-keyring, it would've been added to your system after a system update. This also explains why it worked when you tried again :)
