### ISSUE TITLE
[Request] ntfsprogs-ntfs3

### ISSUE THREAD

**Issue by StarterX4** [chaotic-aur/packages#1289]
### Link to the package(s) in the AUR

[https://aur.archlinux.org/packages/ntfsprogs-ntfs3](https://aur.archlinux.org/packages/ntfsprogs-ntfs3)

### Utility this package has for you

Since Linux 5.15 (and newer) comes with a new `ntfs3` driver, the legacy FUSE-based `ntfs-3g` is not necessary.
The package provides just the utilities, without that driver.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because no longer in AUR.  Metrics 92.
