### ISSUE TITLE
[Outdated] skypeforlinux-stable-bin

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#1300]
### If available, link to the latest build

[skypeforlinux-stable-bin.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/skypeforlinux-stable-bin.log)

### Package name

`skypeforlinux-stable-bin`

### Latest build

`8.80.0.143-1`

### Latest version available

`8.81.0.268-1`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by xiota** [comment]
Planning to drop.  EOL Electron/19.1.8.  Metrics 657.
