### ISSUE TITLE
[Request] Aqemu

### ISSUE THREAD

**Issue by mdhishamsayed** [chaotic-aur/packages#1304]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/aqemu

### Utility this package has for you

QEMU GUI written in Qt5

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by ALipAkrohk** [comment]
I was going to request the addition of this package, but it seems that you had already added it, but now it is not in your repositories, what is the reason?

**Comment by dr460nf1r3** [comment]
I see what happened here. I was interested in this personally a while back and removed it from my packages when I cleaned them up. Its added back now!

**Comment by xiota** [comment]
Switched to aqemu-qt6-git because aqemu failed to build and is still based on Qt5.  Metrics 35.
