### ISSUE TITLE
[Outdated] gitkraken

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#1305]
### If available, link to the latest build

[gitkraken.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/gitkraken.log)

### Package name

`gitkraken`

### Latest build

`8.3.0-1`

### Latest version available

`8.3.1-1`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by Technetium1** [comment]
The rebuild happened automatically as it should have. I was just a bit too quick.

**Comment by dr460nf1r3** [comment]
I did in fact just rebuild it :P thanks for your ongoing efforts, they are very appreciated! 😊
