### ISSUE TITLE
[Request] linux-bore

### ISSUE THREAD

**Issue by grimy192837465** [chaotic-aur/packages#1307]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/linux-bore

### Utility this package has for you

It's a kernel from the developer of the Linux cacule kernel that many people know and love through the Garuda forums. It's the kernel he personally uses and it has many great features and runs amazingly for workloads and gaming. Definitely worth adding some more of his kernel's I feel than just the basic cacule kernel currently added.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by sgse** [comment]
```
==> Validating source files with sha256sums...
    linux-5.16.11.tar.xz ... Passed
    config ... Passed
    0001-bore-sched.patch ... FAILED
    0001-cachy.patch ... Passed
    0001-arch-patches-v3.patch ... Passed
    0001-amdpstate.patch ... Passed
    0001-anbox.patch ... Passed
    0001-bbr2-patches.patch ... Passed
    0001-cfi.patch ... Passed
    0001-cpu.patch ... Passed
    0001-clearlinux.patch ... Passed
    0001-misc-new.patch ... FAILED
    0001-fs-patches.patch ... Passed
    0001-lrng.patch ... Passed
    0001-MG-LRU-v7.patch ... Passed
    0001-hwmon-patches.patch ... Passed
    0001-net-patches.patch ... Passed
    0001-pf-patches.patch ... Passed
    0001-zstd-patches.patch ... Passed
    0001-v4l2loopback.patch ... Passed
    0001-xanmod-patches.patch ... Passed
    auto-cpu-optimization.sh ... Passed
==> ERROR: One or more files did not pass the validity check!
```

**Comment by grimy192837465** [comment]
Huh, well that sucks. Thanks for trying though
