### ISSUE TITLE
[Request] rum, rum-bin, rum-git

### ISSUE THREAD

**Issue by agent255** [chaotic-aur/packages#1310]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/rum-bin
https://aur.archlinux.org/packages/rum
https://aur.archlinux.org/packages/rum-git

### Utility this package has for you

It is a game launcher for linux by johncena141

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by dr460nf1r3** [comment]
Hey :) Which of those packages do you actually use? Adding both `rum` and `rum-bin` doesn't make sense, hence I'm wondering :)

**Comment by agent255** [comment]
sorry my mind just filled all of the variations in. only rum and rum-git are used by me
