### ISSUE TITLE
[Bug] ungoogled chromium and systemd 

### ISSUE THREAD

**Issue by Wastelander72** [chaotic-aur/packages#1311]
### What happens?

It's not really a bug, but I'm using an Arch-based distro without systemd. The problem is that if I try to install Ungoogled Chromium from chaotic-AUR it fails because systemd and systemd—libs are required dependancies. So I should download the package and manually remove the dependancy (it's not really required, I have no idea why the the source code has it). 

### What is expected to happen?

The systemd dependency should be optional and pacman be able to install Ungoogled Chromium directly from the repo.

**Comment by dr460nf1r3** [comment]
Hey :) This is something you should report to the [upstream repo](https://github.com/ungoogled-software/ungoogled-chromium-archlinux.git), we build straight from there.

**Comment by Wastelander72** [comment]
Hey @dr460nf1r3 thanks a bunch! Yes, I had already thought about reporting upstream soon after submitting here :)
