### ISSUE TITLE
[Request] Guilded

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#1312]
### Link to the package(s) in the AUR

[Guillded](https://aur.archlinux.org/packages/guilded)

### Utility this package has for you

Used to communicate with my friends by voice while playing computer games (this software is a free discord competitor)
Unfortunately, in a racist decision, Discord intends to restrict the people of several countries (never all the people of one country are criminals or terrorists).
Due to new Discord decisions, my friends and I left Discord and moved to Guilded.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

No, but the author doesn't really care anyways. It's just for bureaucracy.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Pakrohk** [comment]
https://aur.archlinux.org/packages/guilded

This version of the deb package is built in aur and no longer requires electron.

**Comment by Technetium1** [comment]
Now ships its own Electron. Also uses https://github.com/electron-userland/electron-builder for automatic updates, and doesn't seem to have a way to programmatically opt out of this default behavior (not good):
```js
    constructor(options, app) {
        super();
        /**
         * Whether to automatically download an update when it is found.
         * @default true
         */
        this.autoDownload = true;
        /**
         * Whether to automatically install a downloaded update on app quit (if `quitAndInstall` was not called before).
         * @default true
         */
        this.autoInstallOnAppQuit = true;
        /**
```

**Comment by Pakrohk** [comment]
The Guilded platform will end its service on December 19, 2025. All access to the Guilded website, desktop, and mobile apps will be suspended, and all content on the platform will no longer be accessible.
Thank you for being a part of the Guilded community. We deeply appreciate all that you have built here together.
--------------------------------------------------------------
Well, I guess I should either go back to Discord or go install stoat, if it's even usable.
