### ISSUE TITLE
[Request] lightlyshaders-git

### ISSUE THREAD

**Issue by mdhishamsayed** [chaotic-aur/packages#1317]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/lightlyshaders-git

### Utility this package has for you

Round corners and outline effect for Kwin

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
See #1521
