### ISSUE TITLE
[Request] ausweisapp2

### ISSUE THREAD

**Issue by Orko79** [chaotic-aur/packages#1318]
### Link to the package(s) in the AUR

[https://aur.archlinux.org/packages/ausweisapp2](url)

### Utility this package has for you

online identification in EU, use for logins, age verification or to fill formulars
[https://www.ausweisapp.bund.de/en/home](url)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because moved to extra.  Metrics 34.
