### ISSUE TITLE
[Outdated] Firedragon

### ISSUE THREAD

**Issue by D0nnieD4rk0** [chaotic-aur/packages#1319]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/firedragon.log

### Package name

firedragon

### Latest build

97.0.2-1

### Latest version available

98.0-1

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by dr460nf1r3** [comment]
That timing - I fixed the build blocker just about half an hour ago :D
