### ISSUE TITLE
[Request] nushell-git

### ISSUE THREAD

**Issue by baba99j** [chaotic-aur/packages#1323]
### Link to the package(s) in the AUR

[nushell-git](https://aur.archlinux.org/packages/nushell-git)

### Utility this package has for you

The lastest commit of [nushell](https://archlinux.org/packages/community/x86_64/nushell/) — Nu draws inspiration from functional programming languages, and modern CLI tools. Rather than thinking of files and services as raw streams of text, Nu looks at each input as something with structure.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping.  Fails to build.  Use `extra/nushell`.
