### ISSUE TITLE
[Request] qt-virt-manager

### ISSUE THREAD

**Issue by SoftwareRat** [chaotic-aur/packages#1324]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/qt-virt-manager

### Utility this package has for you

QT-based GUI application for managing virtual machines.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because fails to build and not updated for Qt6

**Comment by Technetium1** [comment]
Source seems abandoned https://github.com/F1ash/qt-virt-manager/issues/50
