### ISSUE TITLE
[Bug] libtorrent-rasterbar-1_2-git

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#1326]
### What happens?

Shared library is not found for `qbittorrent-enhanced-git` (and maybe Tribler - which I forgot to check).

### What is expected to happen?

qBittorrent should find the library and launch.

### If possible, please attach logs

`qbittorrent: error while loading shared libraries: libtorrent-rasterbar.so.2.0: cannot open shared object file: No such file or directory`

### More information

Provided by `libtorrent-rasterbar`, [or assumably](https://aur.archlinux.org/packages/qbittorrent-enhanced-git#comment-845383) libtorrent-rasterbar-git / libtorrent-rasterbar-2_0-git

**Comment by dr460nf1r3** [comment]
Shared libraries not being found most likely always hint towards the package needing a rebuild :) it should be fixed now, let me know if that's the case 😊

**Comment by Technetium1** [comment]
@dr460nf1r3 Nope, still broken sadly.

**Comment by dr460nf1r3** [comment]
Just to verify - did you reinstall the new `qbittorrent-enhanced-git` package?

**Comment by Technetium1** [comment]
Yes I did.

**Comment by dr460nf1r3** [comment]
Its working well over here :thinking:

**Comment by Technetium1** [comment]
It seems this may be an issue with qBittorrent. This [AUR comment](https://aur.archlinux.org/packages/qbittorrent-enhanced-git#comment-857284) is correct that the [minimum version](https://github.com/c0re100/qBittorrent-Enhanced-Edition/blob/1cb261407b0deca0586f182f465f95486b2dc053/INSTALL#L8) is `1.2.14` - but when running `ldd /usr/bin/qbittorrent | grep libtorrent-rasterbar` these are the outputs..

with `libtorrent-rasterbar-1_2-git`:
```bash
libtorrent-rasterbar.so.2.0 => not found
```
without 1.2.x available it chooses 2.0.x:
```bash
libtorrent-rasterbar.so.2.0 => /usr/lib/libtorrent-rasterbar.so.2.0 (0x00007fe5f61ca000)
```
Since it prefers to install the 2.0.x version in the first place, why go out of the way to use an older version? It doesn't seem anything else requires it.

**Comment by dr460nf1r3** [comment]
You are right - this seems to be a reminiscent of an older version of the PKGBUILD. Since I installed it locally as well, I can confirm that it uses the regular `libtorrent-rasterbar` of the Arch repos. Guess we can remove the 1_2 one then.

**Comment by Technetium1** [comment]
Fixed in https://github.com/chaotic-aur/packages/commit/d4c86bb084ff76e4696e4c28fb82c9ca13be0dda
