### ISSUE TITLE
[Request] linux-tt

### ISSUE THREAD

**Issue by guiodic** [chaotic-aur/packages#1330]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/linux-tt

### Utility this package has for you

This package sums a lot of useful patches from xanmod, clearlinux, cachyos, etc

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because tracking EOL kernel 6.5.  Patch is no longer maintained.
