### ISSUE TITLE
[Request] Maui Shell 

### ISSUE THREAD

**Issue by mrquantumoff** [chaotic-aur/packages#1336]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/maui-shell-git

### Utility this package has for you

This is a desktop shell built on KDE frameworks

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because AUR packages are not well maintained.
