### ISSUE TITLE
[Bug] `pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com` fails in Docker

### ISSUE THREAD

**Issue by caniko** [chaotic-aur/packages#1337]
I am aware of the fact that `pacman-key` is unaffiliated with `chaotic-aur`; moreover, I thought that the issue might be relevant for others that might get the same problem.

### What happens?

I am trying to add `chaotic-aur` in my ArchLinux docker container. However, I am having a really hard time troubleshooting:
```shell
pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com
```
Which times out:
```
gpg: keyserver receive failed: Connection timed out
==> ERROR: Remote key not fetched correctly from keyserver.
```
I tried through port 80:
```shell
pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com:80
```
Output:
```
gpg: keyserver receive failed: General error
==> ERROR: Remote key not fetched correctly from keyserver.
```

### What is expected to happen?

This shouldn't timeout, I should receive the keys. I am running the container on top of Garuda, and have no issue running the same command on Garuda.

### If possible, please attach logs

Not sure what logs are of interest here.

### More information

Dockerfile:
```dockerfile
FROM archlinux:latest

RUN pacman-key --init && \
    pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com && \
    pacman-key --lsign-key FBA220DFC880C036 && \
    pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst' && \
    echo "[chaotic-aur]" >> /etc/pacman.conf && \
    echo "Include = /etc/pacman.d/chaotic-mirrorlist" >> /etc/pacman.conf

RUN pacman -Syu --noconfirm
```
I am also behind a proxy, but this hasn't been a problem on the Garuda side.

**Comment by dr460nf1r3** [comment]
This seems to be a rather setup specific issue - we are building Docker containers [like that](https://gitlab.com/garuda-linux/tools/buildiso-docker/-/blob/master/Dockerfile#L2=) since quite some time 👀

**Comment by Rojikku** [comment]
@caniko That dockerfile builds for me.
I might note that like 6 of your dockerfile is missing a --noconfirm.

I'm going to assume the issue is related to your proxy setup. 
https://docs.docker.com/network/proxy/
Have you confirmed if docker can reach the internet at all? I like to use the `nicolaka/netshoot` for this sort of thing, but a straight `ubuntu` or `archlinux` image could work as well.

**Comment by caniko** [comment]
Yes @Rojikku you were right! Apologies for being so late to my own party!

I arrived at the same conclusion the day after posting this, solution:
```Dockerfile
RUN mkdir app && \
    mkdir /etc/gnupg && \
    echo "honor-http-proxy" > /etc/gnupg/dirmngr.conf && \
    echo "honor-http-proxy" > /etc/pacman.d/gnupg/dirmngr.conf && \
    ...
```
