### ISSUE TITLE
[Request] wayfire-plugins-extra

### ISSUE THREAD

**Issue by scruffidog** [chaotic-aur/packages#1338]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/wayfire-plugins-extra

### Utility this package has for you

this includes plugins for focus follows mouse and window zooming.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

this was available before as it was added by my request last year. ;) 
I know that the release for wayfire has been inexplicably delayed but hopefully this can still be provided for a new rebuild of my client ?

**Comment by Technetium1** [comment]
I added git in https://github.com/chaotic-aur/interfere/commit/2c9cdf7956fd2a4864f93e1d67b788991df39cde and managed to fail further into the build https://builds.garudalinux.org/repos/chaotic-aur/logs/wayfire-plugins-extra.log

**Comment by Technetium1** [comment]
Related issue upstream: https://github.com/WayfireWM/wayfire-plugins-extra/issues/126

**Comment by dr460nf1r3** [comment]
Interfere magic time! https://github.com/chaotic-aur/interfere/commit/db6d0f6df343e9ed1b48e438b97e4331818c72d8
