### ISSUE TITLE
[Request] libunity

### ISSUE THREAD

**Issue by Syndrizzle** [chaotic-aur/packages#1339]
### Link to the package(s) in the AUR

[libunity 7.1.4-13](https://aur.archlinux.org/packages/libunity)

### Utility this package has for you

Libunity is one of the packages that some electron based applications depend upon to show badges on the taskbar, this is very useful for some people like me.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Compiling this package takes hours and hours trust me, it would be a great help if this one gets in chaotic AUR!

**Comment by dr460nf1r3** [comment]
The actual package wasn't that heavy actually, the dependencies took longest to build 😄

**Comment by Syndrizzle** [comment]
Thank you so much for this! This package was the reason that kept me away from using arch, since it is available as a binary package in the official repositories of almost every linux distribution...
Also, this is a one time process, this package has been abandoned. No idea why electron still uses it, but you don't have to bother to compile it again :)
Now I can finally use arch without any pain, thank you again!
