### ISSUE TITLE
[Request] Darling-git

### ISSUE THREAD

**Issue by MANICX100** [chaotic-aur/packages#1344]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/darling-git

### Utility this package has for you

Translation layer for me to test basic macOS binaries without needing a VM and superior performance.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
It's doing tests that will fail: https://builds.garudalinux.org/repos/chaotic-aur/logs/darling-git.log

**Comment by MANICX100** [comment]
It appears to be balking at xrandr.

Will try and fix upstream.
