### ISSUE TITLE
[Request] discord-rpc-cli

### ISSUE THREAD

**Issue by coxackie** [chaotic-aur/packages#1346]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/discord-rpc-cli-git

### Utility this package has for you

Lighter discord client (made in Rust) than the electron one

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

The package is named as "-git", but it does not really pull from latest git, just last release. Should not be burden on the chaotic servers.

**Comment by Technetium1** [comment]
To be clear, this is not actually a separate client for Discord, it's only a utility to manage your rich presence status. Do you still want to request it?

**Comment by coxackie** [comment]
@Technetium1 no, I did not know that, apologies, it is then not important. @dr460nf1r3 I will close this, no need to worry about it.
