### ISSUE TITLE
[Request] Provide texlive-full as a package

### ISSUE THREAD

**Issue by innerout** [chaotic-aur/packages#1347]
### Link to the package(s) in the AUR

[texlive-full](https://aur.archlinux.org/packages/texlive-full)

### Utility this package has for you

It provides all the latex packages usually someone needs. The download time for each package is slow. If it is prebuilt as other packages in chaotic AUR the installation will be faster.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Takes a very long time indeed, around 30 mins total.

**Comment by dr460nf1r3** [comment]
I fixed the OOM situation & built the package afterwards - it should be available. It still needs to be added to the routine though, therefore I left the issue open.
Cheers 😊

**Comment by innerout** [comment]
Thanks, I appreciate it!

**Comment by innerout** [comment]
It is added in the routine and works as expected! Thanks again, for the immediate response!

**Comment by Technetium1** [comment]
Not yet added to the routine for automatic builds

**Comment by caniko** [comment]
I am using it too, sad to see it go :cry:
