### ISSUE TITLE
[Remove] marktext

### ISSUE THREAD

**Issue by Evan-aja** [chaotic-aur/packages#1349]
### Link to the package(s) in the AUR

[marktext](https://aur.archlinux.org/packages/marktext)
[marktext-bin](https://aur.archlinux.org/packages/marktext-bin)

### Utility this package has for you

Rich graphical Markdown text editor

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
`marktext` fails to compile: https://builds.garudalinux.org/repos/chaotic-aur/logs/marktext.log
`marktext-bin` did not.

**Comment by xiota** [comment]
Electron 18... time to drop?

**Comment by Technetium1** [comment]
Yes, long overdue.

**Comment by D3vil0p3r** [comment]
Is there an alternative of marktext?

**Comment by xiota** [comment]
Depends on features you want.  Search repos for markdown and markup.
