### ISSUE TITLE
[Request] hardinfo-git 

### ISSUE THREAD

**Issue by evansan** [chaotic-aur/packages#1350]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/hardinfo-git

### Utility this package has for you

a good hardware overview tool

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Added in https://github.com/chaotic-aur/packages/commit/6c2f1f9a7bb5c99a3e1943509379e9128af701aa I forgot the `#` for the issue number.

**Comment by xiota** [comment]
Dropping because build fails and hasn't been migrated to Qt6 yet.  Will keep stable package a little longer.  Metrics:

* hardinfo2 # 1081
* hardinfo2-git # 176
