### ISSUE TITLE
adw-gtk3-git

### ISSUE THREAD

**Issue by coxackie** [chaotic-aur/packages#1352]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/adw-gtk3-git

### Utility this package has for you

With Gnome 42 out, there is a bit of inconsistency between gtk3 and gtk4 themes. This theme aims at making gtk3 styling look very close to gtk4.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because `extra/adw-gtk-theme` is available.

Metrics 13.
