### ISSUE TITLE
the package group "amdgpu-pro-installer"

### ISSUE THREAD

**Issue by CosmicFusion** [chaotic-aur/packages#1354]
### Link to the package(s) in the AUR

https://aur.archlinux.org/pkgbase/amdgpu-pro-installer

### Utility this package has for you

I Use it to enable Raytracing in support Games , Encode Videos with the AMF Encoder (Works With OBS when using streamfx) , and fix davinci resolve proprietary OpenGL Requirements (On Some Builds) .

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No, but the author doesn't really care anyways. It's just for bureaucracy.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Ashark has finally Updated his AUR package to upstream , Deprecating the "amdgpu-pro-installer-cfe" package group (
https://aur.archlinux.org/pkgbase/amdgpu-pro-installer-cfe
https://builds.garudalinux.org/repos/chaotic-aur/logs/amdgpu-pro-installer-cfe.log)
So remove those .

**Comment by Technetium1** [comment]
Related removal request for old package https://github.com/chaotic-aur/packages/issues/1355

**Comment by Technetium1** [comment]
This is already being built here: https://github.com/chaotic-aur/packages/blob/a116d7db6b390fad9f81f513da000f54c64e1837/ufscar-hpc/hourly.1.txt#L393-L394
The new version is up now.
