### ISSUE TITLE
[Outdated] [Removal-Request] Remove the package group "amdgpu-pro-installer-cfe"

### ISSUE THREAD

**Issue by CosmicFusion** [chaotic-aur/packages#1355]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/amdgpu-pro-installer-cfe.log

### Package name

amdgpu-pro-installer-cfe

### Latest build

21.50-1373477

### Latest version available

22.10-1395274 (here : https://aur.archlinux.org/pkgbase/amdgpu-pro-installer)

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

Ashark has finally Updated his AUR package to upstream , Deprecating this package , please remove this package and include that one.

**Comment by Technetium1** [comment]
Added in https://github.com/chaotic-aur/packages/issues/1309
