### ISSUE TITLE
[Request] ffsend

### ISSUE THREAD

**Issue by FireMasterK** [chaotic-aur/packages#1356]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/ffsend

### Utility this package has for you

It's a CLI for Firefox Send.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
I don't see a reason to not use the version from CI, `ffsend-bin`.
