### ISSUE TITLE
[Outdated] dxvk-mingw-git

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#1357]
### If available, link to the latest build

[dxvk-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/dxvk-git.log)

### Package name

`dxvk-mingw-git`

### Latest build

`1.10.1.r8.g95a34139-1`

### Latest version available

`42c66c410e213f7504903744a5684a4e453f71f2`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

Hasn't updated for like a week. 4 new commits got added 3 days ago, one of which fixes Call of Duty games I play. Was told in telegram to submit this bug report.

**Comment by Technetium1** [comment]
`Finished making: dxvk-git 1.10.1.r13.g3672375b-1 (Sat 09 Apr 2022 07:20:13 PM CEST)`
