### ISSUE TITLE
[Request] x2goclient and x2goserver

### ISSUE THREAD

**Issue by creeper123123321** [chaotic-aur/packages#1358]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/x2goclient
https://aur.archlinux.org/packages/x2goserver

### Utility this package has for you

remote desktop connection

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

it isn't on official repo anymore

**Comment by Technetium1** [comment]
[x2goclient](https://builds.garudalinux.org/repos/chaotic-aur/logs/x2goclient.log) is missing `nxproxy` from `nx`
[x2goserver](https://builds.garudalinux.org/repos/chaotic-aur/logs/x2goserver.log) is missing `nxagent` from `nx`
