### ISSUE TITLE
[Request] deltachat-desktop

### ISSUE THREAD

**Issue by maltejur** [chaotic-aur/packages#1359]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/deltachat-desktop

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Stable available as `extra/deltachat-desktop`
