### ISSUE TITLE
[Request] davfs2

### ISSUE THREAD

**Issue by airend** [chaotic-aur/packages#1360]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/davfs2

### Utility this package has for you

File system driver that allows you to mount a WebDAV folder

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Package was moved from `community` to AUR.

**Comment by xiota** [comment]
Dropping because moved to extra.  Metrics 1030.
