### ISSUE TITLE
[Outdated] all Firefox(s) with appmenu are outdated; FF extensions possibly need manual intervention

### ISSUE THREAD

**Issue by jeois** [chaotic-aur/packages#1361]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/firefox-appmenu-bin.log
https://builds.garudalinux.org/repos/chaotic-aur/logs/firefox-extension-plasma-integration.log
https://builds.garudalinux.org/repos/chaotic-aur/logs/firefox-extension-flagfox.log
https://builds.garudalinux.org/repos/chaotic-aur/logs/firefox-kde-opensuse-rpm.log

### Package name

firefox-appmenu-bin

### Latest build

98.0.2-1

### Latest version available

99.0-1

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

Thanks for maintaining these Firefox packages.  However, I noticed a few issues:

1) Firefox 99 has been released for about a week, and most variants have already been updated.  However, the binary versions with the global app menu patch have not been updated on the repo.

According to the build server logs, it did complete the `firefox-appmenu-bin` build or at least attempted it.  But, there is an error:
`==> ERROR: A package has already been built. (use -f to overwrite)`
I'm guessing this is because _chaotic-aur_ is fetching the binary versions from the AUR's _"-bin"_ packages rather than building them from source.  Therefore, it's only a link to AUR binaries, and if those maintainers don't update, then nothing gets built because the previous version already exists?  In that case, I'm mistaken, and it isn't technically outdated but still a bit disappointing since it's only a mirror rather than a "build" available from `firefox-appmenu`'s updated sources and patches.

2) Upon reviewing build logs, I've come across recent firefox extension builds which also ended with this error and therefore haven't been updated to the repo.  This issue appears to have only come up recently, as older packages seem to be unaffected (i.e. `plasma-integration` is up-to-date even with this error, but `flagfox` is _outdated_).   I haven't checked all the extensions, but I posted links to the two builds with errors I found.  It's probably a similar issue with retrieving whatever the AUR has linked without downloading the newest version from Mozilla servers.  If that's the case, it's more AUR mirroring with no scripted download, which seems redundant and not very useful since we can get the same outdated extension directly from AUR.
```
[?25h==> ERROR: A package has already been built. (use -f to overwrite)
Container pkg5f237c1a8d3 failed with error code 13.
```

3) `firefox-kde-opensuse` also contains the appmenu patch and `firefox-kde-opensuse-rpm` is the binary built by OpenSUSE.  I'm not sure why _chaotic-aur_ also tries to build this, but it's failing due to what looks like a dependency error:
`error: target not found: kmozillahelper`
I don't know the difference between this package and the one OpenSUSE builds, and if it is the same, then this is redundant and possibly a waste of resources.  Therefore, it may be best if someone removed this, especially if we're not willing to also keep up its dependent helper.  

https://aur.archlinux.org/packages/firefox-kde-opensuse-rpm
Unfortunately, the AUR maintainer hasn't updated the PKGBUILD, and its RPM download URL fails, so I haven't tested this either.  Moreover, this particular binary package **doesn't include the global app menu patch like the source version does**, so I'm confused about what it offers as opposed to just using baseline `firefox` releases with `firefox-extension-plasma-integration` since my reason for using these is for the appmenu support.

4)  Also of interest to this issue is `firefox-ubuntu-bin` as all these global menu Firefox variants seem to rely on `unity-menubar.patch` which comes from Ubuntu.  It would be great if we consolidated these packages, which basically do the same thing, without having to rely on Ubuntu's slow build servers.  In addition, this version doesn't respect `/usr/lib/firefox/browser/extensions` (Arch's default global extensions directory), overwrites it with a new empty folder, and renames the existing folder to `extensions.old` thereby making installing extensions with pacman and AUR useless and forces the user to reinstall them to their profile directory instead.

If AUR maintainers aren't willing to rebuild these binaries in a timely manner, please consider using chaotic-aur to automate builds of Firefox with the relevant patches enabled.  The **_source versions_** (e.g. `firefox-appmenu` not `...-bin`) on the AUR are more up-to-date and probably do work, and I would really appreciate if at least one binary of Firefox with appmenu support gets built.   

Thanks again to everyone maintaining these packages.  I hope the automated builds work again.

**Comment by jeois** [comment]
Thank you for adding the `firefox-appmenu` source build and updating the extensions.  I think this is mostly resolved for now.  

`flagfox` still gives a warning about being outdated.  We're getting `6.1.37` even though you just updated the AUR version to `6.1.49`.  PKGBUILD is looking in the old directory.  The correct address is [https://addons.mozilla.org/firefox/downloads/file/**3929226**/flagfox-6.1.49-fx.xpi](https://addons.mozilla.org/firefox/downloads/file/3929226/flagfox-6.1.49-fx.xpi) 
`md5sum: b17e92ae5c388552bb3528d4f04fc81f`
The same issue applies for `localCDN`:
[2.6.25](https://addons.mozilla.org/firefox/downloads/file/3930632/localcdn-2.6.25-an+fx.xpi) vs 2.6.4 from _chaotic-aur_
`md5sum: b3d3d3fcfb79434b045894b6175ac49d`
Although I should comment to AUR instead, but this makes the browser not auto-update to profile, but it's actually using old versions.  So, you might want to check other extension updates too.  There should be a less tedious way to get the new address and checksum, but I'm not sure how besides checking the website.

If anyone wants to discuss whether to remove `firefox-kde-opensuse-rpm` from the build list or how to automate extension updates, please give your suggestions/comments.  Otherwise, I'll close this issue soon since my main request was implemented.

**Comment by dr460nf1r3** [comment]
Thanks man, I fixed the extensions. Why remove the opensuse one though? :eyes:

**Comment by jeois** [comment]
Thanks for updating and maintaining those packages.  You're very fast! :) :+1: 

The binary RPM version from AUR/OpenSUSE doesn't include the appmenu `unity-menubar.patch`, and it's failing to install because the maintainer has to manually update its RPM build numbers or the URL breaks whenever openSUSE rebuilds.  
https://builds.garudalinux.org/repos/chaotic-aur/logs/firefox-kde-opensuse-rpm.log
`curl: (22) The requested URL returned error: 404
==> ERROR: Failure while downloading https://download.opensuse.org/repositories/mozilla:/Factory/openSUSE_Factory/x86_64/MozillaFirefox-99.0-976.1.x86_64.rpm
    Aborting...`

The frequent update breaks is no reason to remove it, but I'm very confused as to what it offers over vanilla Firefox.  Although it's also older, AUR `firefox-kde-opensuse` _does_ include that patch, and it's sourcing OpenSUSE's `firefox-maintenance`, so it **doesn't match** this RPM binary.  Therefore, users like me install the RPM thinking they'll get the same functionality, but no...

There's probably other differences from vanilla I'm unaware of, but to the best of my knowledge, it works the same as Firefox with plasma-integration extension (i.e. plasma media player applet and notifications work regardless) and doesn't apply any of the other AUR patches either.

**Comment by jeois** [comment]
I just thought _chaotic-aur_ is wasting effort at trying to package the RPM, which isn't particularly useful IMO, and it hasn't been available on the repo anyway due to failed downloads... but I guess it isn't that important.

Since my requests were implemented and updated, I'll close this thread.  Thanks again.
