### ISSUE TITLE
[Request] libplacebo-git

### ISSUE THREAD

**Issue by jkcdarunday** [chaotic-aur/packages#1362]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/libplacebo-git

### Utility this package has for you

Having this package installed while building mpv-full-git enables the gpu-next video output as per [this comment](https://github.com/mpv-player/mpv/issues/9506#issuecomment-976123285).

In my machine, the gpu-next video output has less lags compared to the default output so it might be useful to other users as well to have it as an option.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because of ffmpeg stable/git incompatibility.
