### ISSUE TITLE
[Remove] asusctl

### ISSUE THREAD

**Issue by d-513** [chaotic-aur/packages#1363]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/asusctl

### Utility this package has for you

controls aspects of asus laptops

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

asus-linux have their own repo, but its not even signed with PGP key and I would prefer to not add too many repos

**Comment by Pakrohk** [comment]
You have already added this package, now it is not available in the list of repositories for installation.
Please check to see where the problem is.

**Comment by xiota** [comment]
AUR last updated 2023-07-07.  Package last build 2023-09-15.

**Comment by xiota** [comment]
Switching to stable package.  Better maintained.

`-git` package fails to build, missing depends.  Current maintainer has never pushed a commit.  Metrics 142.

**Comment by xiota** [comment]
Dropping because moved to extra.

Metrics:

* asusctl # 142
* rog-control-center # 97
