### ISSUE TITLE
[Request] Send Anywhere

### ISSUE THREAD

**Issue by Bhooty** [chaotic-aur/packages#1367]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/sendanywhere

### Utility this package has for you

This app can be used to get files from mobile to desktop and vice versa without connecting via cable

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
The build failed with `error: target not found: electron8`. https://builds.garudalinux.org/repos/chaotic-aur/logs/sendanywhere.log

**Comment by dr460nf1r3** [comment]
Did you try to build electron8 before building the package? 🤔

**Comment by Technetium1** [comment]
Nope, did not get that far yet.

**Comment by Technetium1** [comment]
It's satisfied with `electron8-bin`.
