### ISSUE TITLE
[Request] joplin-desktop

### ISSUE THREAD

**Issue by DenjixPochita** [chaotic-aur/packages#1368]
### Link to the package(s) in the AUR

[joplin-desktop](https://aur.archlinux.org/packages/joplin-desktop)

### Utility this package has for you

Notes taking

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
The build is failing https://builds.garudalinux.org/repos/chaotic-aur/logs/joplin-desktop.log

**Comment by dr460nf1r3** [comment]
Building from ArchlinuxCN's working PKGBUILD now.

**Comment by tio-trom** [comment]
Cannot find this package in your repo...

**Comment by dr460nf1r3** [comment]
https://github.com/chaotic-aur/packages/issues/2086

**Comment by Technetium1** [comment]
@tio-trom This was removed in https://github.com/chaotic-aur/packages/commit/eda5ade30bc15862f88d37049270a586485b7bca due to #1958 :(

**Comment by Zahrun** [comment]
Does joplin-desktop still depend on python2 today?

**Comment by dr460nf1r3** [comment]
No, it seems to accept generic `python`  now.
