### ISSUE TITLE
[Outdated] librewolf

### ISSUE THREAD

**Issue by maltejur** [chaotic-aur/packages#1369]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/librewolf.log

### Package name

librewolf

### Latest build

98.0.2-1

### Latest version available

99.0-2

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by coxackie** [comment]
there could be an issue again, 99.0.1-4 is out for a day or so, but chaoric still has 99.0.1-1.

**Comment by Technetium1** [comment]
It rebuilds [every afternoon](https://github.com/chaotic-aur/packages/search?q=librewolf); looks like you were really [on the ball](https://aur.archlinux.org/cgit/aur.git/log/?h=librewolf). Feel free to open new issues to request rebuilds, even if it's the same package as previously reported and closed. Thanks for helping :)
