### ISSUE TITLE
[Request] iriunwebcam-bin

### ISSUE THREAD

**Issue by joe733** [chaotic-aur/packages#1371]
### Link to the package(s) in the AUR

[iriunwebcam-bin](https://aur.archlinux.org/packages/iriunwebcam-bin)

### Utility this package has for you

Use phone camera as source for video conferencing 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Official Site: https://iriun.com/

**Comment by xiota** [comment]
Considering to drop.  Package has not been updated to Qt6 yet.  Also, comment on aurweb indicates program may not be working.  Metrics 180.
