### ISSUE TITLE
[Outdated] gstreamer-git 1.20.1

### ISSUE THREAD

**Issue by ERLindeman** [chaotic-aur/packages#1375]
### If available, link to the latest build

[1.20.1 release on GitHub](https://github.com/GStreamer/gstreamer/releases/tag/1.20.1)

[1.20.0 build log](https://builds.garudalinux.org/repos/chaotic-aur/logs/gstreamer-git.log)

### Package name

gstreamer

### Latest build

v1.20.0

### Latest version available

v1.20.1

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### More information

Mainline development appears to have moved from "master" to "main" branch several months ago, though a 1.20.0 standalone branch does exist, and is presumably why this has failed to move to the new version after a month. 

'extra' repo updated to the new version a while ago and thus trying to move to the 'chaotic-aur' version is made difficult by dependency conflicts.

(Probably showing how green I am with that statement, but I'm here to help and learn)

Note: I read the wiki about certain issues with gstreamer and gst plugins, but from my understanding, this package (and maybe 'gst-plugins-base' and 'gst-plugins-good'?) are supported. Sorry for the inconvenience if I misinterpreted that disclaimer.

**Comment by Technetium1** [comment]
I opened [an issue upstream](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/1158), because that's very stupid on their part. 
Thank you for contributing :)

**Comment by Technetium1** [comment]
@SolarAquarion need to specify the branch per [this issue](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/1158).

**Comment by Technetium1** [comment]
> [takaomag](https://aur.archlinux.org/account/takaomag) commented on [2022-11-06 04:00 (EST)](https://aur.archlinux.org/packages/gstreamer-git?all_reqs=1#comment-888325)

This package is based on `git+https://gitlab.freedesktop.org/gstreamer/gst-plugins-ugly.git` which is too old. gstreamer itself and all plugins supported by the project has been moved to `git+https://gitlab.freedesktop.org/gstreamer/gstreamer.git`.

So, don't install this Aur package until fixed.

- Current gstreamer and plugins mono repository
https://gitlab.freedesktop.org/gstreamer/gstreamer

- PKGBUILD of default (non-Aur) gst-plugins-ugly (and others) package
https://github.com/archlinux/svntogit-packages/blob/packages/gstreamer/trunk/PKGBUILD

**Comment by dr460nf1r3** [comment]
Not in repo anymore.
