### ISSUE TITLE
[Outdated] poppler-git

### ISSUE THREAD

**Issue by qumaciel** [chaotic-aur/packages#1377]
### If available, link to the latest build

[poppler-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/poppler-git.log)

### Package name

poppler-git

### Latest build

22.04.0.r40.g7ff9c784

### Latest version available

22.04.0.r40.g7ff9c784

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### More information

The PKGBUILD in chaotic-aur is not in pair with [upstream poppler](https://github.com/archlinux/svntogit-packages/blob/packages/poppler/trunk/PKGBUILD). For instance, it doesn't have `poppler-qt6` bindings.

Another issue is that, with current poppler-git build, it is not possible to run inkscape in KDE plasma, it returns:
```
inkscape: error while loading shared libraries: libpoppler.so.119: cannot open shared object file: No such file or directory
```

**Comment by Technetium1** [comment]
Out of date https://aur.archlinux.org/pkgbase/poppler-git/flag-comment

**Comment by Technetium1** [comment]
Done! https://github.com/chaotic-aur/interfere/commit/6614256cf5fdbf65ef7e153408160c3f9ea5158d
