### ISSUE TITLE
[Outdated] xorg-server-git

### ISSUE THREAD

**Issue by qumaciel** [chaotic-aur/packages#1378]
### If available, link to the latest build

[xorg-server-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/xorg-server-git.log)

### Package name

xorg-server-git

### Latest build

21.1.99.1.r177.g9e5a37961

### Latest version available

21.1.99.1.r190.g6d468c68d

### Have you tested if the package builds in a clean chroot?

- [X] Yes

**Comment by Edu4rdSHL** [comment]
We need to remove `check()` from the PKGBUILD using our interfere repo.
