### ISSUE TITLE
[Request] webstorm

### ISSUE THREAD

**Issue by dada513** [chaotic-aur/packages#1382]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/webstorm

### Utility this package has for you

coding websites and stuff

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Not sure about license, it's proprietary, but you are distributing ther jetbrains products (like `clion`) so I assume it's fine

**Comment by Technetium1** [comment]
We should also be sure to add this dependency https://aur.archlinux.org/packages/webstorm-jre

**Comment by dada513** [comment]
Agreed. Again, I’m not sure about the licensing, but since you package Clion and others I think it’s fair to say this is fine to be distributed
