### ISSUE TITLE
[Remove] heimdall-grimler-git

### ISSUE THREAD

**Issue by Smart123s** [chaotic-aur/packages#1384]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/heimdall-grimler-git

### Utility this package has for you

Flash Samsung phones' firmware.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because no longer in AUR.  `extra/heimdall` is based on the same fork.  Metrics 16.
