### ISSUE TITLE
[Request] QMPlay2

### ISSUE THREAD

**Issue by ghost** [chaotic-aur/packages#1387]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/qmplay2

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Does [qmplay2-git](https://aur.archlinux.org/packages/qmplay2-git) fill the same need effectively? Seems there are not frequent releases at https://github.com/zaps166/QMPlay2/releases

**Comment by Technetium1** [comment]
Ghost account now, but it could be added anyway
