### ISSUE TITLE
[Request] Dedicated ZFS modules prebuild for the custom kernels

### ISSUE THREAD

**Issue by RubenKelevra** [chaotic-aur/packages#1388]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/zfs-linux

### Utility this package has for you

An awesome file system

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Archzfs.com offers a repo with custom build kernel modules for each individual (official) kernel.

It would be neat if chaotic-aur could provide such modules as well for the kernels this repo provides.

This would avoid being dependent on dkms - and have some automatic testing (if possible), to make sure that the zfs module loads and works fine.

Like with the archzfs-repo a zfs module would then need to be coupled to exactly the right version of the kernel, and if the testing/build of the zfs module fails the older matching kernel version would need to be retained until the issue is resolved.

The archzfs repo solves this by having the matching official kernels on a dedicated mirror, to have pacman able to receive the older versions if necessary (without using `downgrade`).

**Comment by mdhishamsayed** [comment]
@RubenKelevra Hi Sir/Maam,
i know that ZFS is an "awesome" file system, i have used it. But,but,
may i know the reason when "archzfs-repo" already provides the kernel modules,
please do not consider it to be offensive but that question popped up in my mind and i asked

**Comment by SolarAquarion** [comment]
We can do PKGBUILD.append in the interfere github

**Comment by Edu4rdSHL** [comment]
I don't see any point in this issue, `-dkms` is the way to avoid any kind of issues, it has been working that way for a long time. Pre-building out of tree modules for all the kernel variants would just be a headache.

**Comment by PedroHLC** [comment]
> I'm also not sure whether it would make sense to build the modules separately thinking DKMS has been the preferred way to handle kernel modules for a long time for me eyes

Laptops suffer a lot with DKMS while updating.



> We can do PKGBUILD.append in the interfere github

Since this depends more on the kernel version than the ZFS version. I would make it part of the kernel's PKGBUILD, adding to it with PKGBUILD.append. But chaotic builds a lot of kernels from different PKGBUILDs it would be too complicated to implement for them all.
