### ISSUE TITLE
[Request] swayr

### ISSUE THREAD

**Issue by cornerot** [chaotic-aur/packages#1390]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/swayr

### Utility this package has for you

Window switcher for Sway.
More functional and flexible window switch replacement (old python script) for Garuda Sway edition

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [x] Yes

### Have you tested if the package builds in a clean chroot?

- [x] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Need to remove `check()` with interfere.
