### ISSUE TITLE
[Request] Termius

### ISSUE THREAD

**Issue by dlsf** [chaotic-aur/packages#1391]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/termius-app

### Utility this package has for you

SSH client with FTP and synchronization support

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Unfortunately, I can't find any licensing information

**Comment by Technetium1** [comment]
https://builds.garudalinux.org/repos/chaotic-aur/logs/termius-app.log
`chmod: cannot access '/opt/Termius/chrome-sandbox': No such file or directory`

**Comment by xiota** [comment]
For anyone interested.  Metrics 274.
