### ISSUE TITLE
[Request] wallpapers-qt gtk-wallpapers

### ISSUE THREAD

**Issue by mdhishamsayed** [chaotic-aur/packages#1392]
### Link to the package(s) in the AUR

https://gitlab.com/avahi_daemon/pkgbuild-gtk-wallpapers
https://gitlab.com/avahi_daemon/pkgbuild-wallpapers-qt

### Utility this package has for you

OTHER DISTRIBUTION,
ANITA

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Changed your mind @mdhishamsayed?
