### ISSUE TITLE
[Request] add libxcvt 

### ISSUE THREAD

**Issue by kassindornelles** [chaotic-aur/packages#1393]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/libxcvt-git

### Utility this package has for you

It's useful to get the git version when you are a wayland user that relies on xwayland, for me the git package always fixes something related to my screen resolution on wayland and other issues, etc

last night it fixed xrandr reporting the wrong resolution for me (kinda of)
see https://gitlab.freedesktop.org/xorg/xserver/-/issues/1337

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

:frog:

**Comment by Technetium1** [comment]
`check()` needs to be removed via interfere

**Comment by dr460nf1r3** [comment]
Here we go :)

**Comment by kassindornelles** [comment]
Thank you so much! :D
