### ISSUE TITLE
[Request] citra-git / citra-qt-git

### ISSUE THREAD

**Issue by fwookerton** [chaotic-aur/packages#1394]
### Link to the package(s) in the AUR

https://aur.archlinux.org/pkgbase/citra-git
provides `citra-git` and `citra-qt-git`

### Utility this package has for you

An experimental open-source Nintendo 3DS emulator and debugger

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
`check()` needs to be removed via interfere

**Comment by Technetium1** [comment]
@dr460nf1r3 can/should this go underneath https://github.com/chaotic-aur/packages/blob/03dcbc6a209a2623360f0724480e272d5b4ae596/ufscar-hpc/hourly.2.txt#L223

**Comment by dr460nf1r3** [comment]
Yeah, this sounds good to me 👍

**Comment by xiota** [comment]
Request to remove citra-qt-git.  Currently, it appears that citra-qt-git may not be building correctly because it doesn't appear in pacman searches.  However, examination of the upstream git repositories of citra-canary-git tracks the development repository.  Since citra-canary-git is already included in chaotic-aur and building correctly, it seems that also having citra-qt-git is redundant.

**Comment by xiota** [comment]
`citra-nightly-git` is easily modified by setting variables in interferes.  It is being used to make `citra-nightly-git`, `citra-nightly-avx-git`, and `citra-canary-git`.

Reasons for switching away from the other packages:

* `aur/citra-git`
    * frequently breaks with slow fixes
    * split packages are annoying to work with
* `aur/citra-canary-git`
    * currently broken, segfaults

**Comment by fluffeon** [comment]
should this package be dropped now

**Comment by Technetium1** [comment]
@fluffeon when it no longer works

**Comment by fluffeon** [comment]
Citra frontend is now incompatible with latest Qt core.
![image](https://github.com/chaotic-aur/packages/assets/69437909/81d4747f-7baf-41ea-877b-b24d8dc39b86)

**Comment by fluffeon** [comment]
now this package is returning once again

**Comment by xiota** [comment]
Different name... different issue.
