### ISSUE TITLE
[Request] grub-improved-luks2-git

### ISSUE THREAD

**Issue by xAffan** [chaotic-aur/packages#1397]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/grub-improved-luks2-git

### Utility this package has for you

This package has proper support for luks2 in grub supporting latest hashing algorithms like argon2, which are not supported by grub yet. In order to boot from an encrypted /boot partition, this package is a godsend.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

I hope this can be added. By the way, this package is mentioned here https://wiki.archlinux.org/title/GRUB#LUKS2

**Comment by Technetium1** [comment]
Requires [bdf-unifont](https://aur.archlinux.org/packages/bdf-unifont)

**Comment by xiota** [comment]
Failing to build.  Patches need to be updated.  Maintainer has been notified.  Metrics 15.

**Comment by xiota** [comment]
Planning to drop this Soon℠ because relying on difficult to maintain patches is a Bad Idea℠.
