### ISSUE TITLE
[Request] JDK

### ISSUE THREAD

**Issue by arthurflor23** [chaotic-aur/packages#1399]
### Link to the package(s) in the AUR

https://aur.archlinux.org/pkgbase/jdk

### Utility this package has for you

Includes tools for developing and testing programs written in the Java programming language.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by dr460nf1r3** [comment]
@Technetium1 about the license I'm actually not sure. I'd say we add this, if there is any issue and someone notifies us we simply take it down and put it on the ban list :)
