### ISSUE TITLE
[Request] tinygo-git

### ISSUE THREAD

**Issue by Elara6331** [chaotic-aur/packages#1401]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/tinygo-git

### Utility this package has for you

I use this package to run the latest version of Go on microcontrollers and to compile Go programs written in the latest version of Go to WASI. The version of TinyGo in the community repo often lags behind the latest version of Go and the latest TinyGo improvements.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
`'llvm<11.0.0'` is not satisfied.

**Comment by Technetium1** [comment]
I don't know where to source that version of `llvm`, the oldest I see is `11.1.0-6`.

**Comment by dr460nf1r3** [comment]
Well, we are rolling so packages like that can be problematic. I guess a workaround using a fixed, older version of `llvm` would work. If someone wants to provide a working PKGBUILD we will build it of course :)

**Comment by Technetium1** [comment]
https://github.com/tinygo-org/tinygo/issues/1435 LLVM 11 support was added here. Maybe @Depau will update the package to build with a newer LLVM. It was added into community so we at least have a known working copy here: https://github.com/archlinux/svntogit-community/blob/packages/tinygo/trunk/PKGBUILD

**Comment by Depau** [comment]
@Technetium1 I disowned the package since I no longer have time to maintain it. Feel free to adopt it and make the required changes.

**Comment by xiota** [comment]
I adopted this to fix.  Will be disowning.  This package is *not* a good use of chaotic-aur resources.

* Currently requires rebuilding LLVM from scratch.
* Upstream makes reasonably frequent releases.  Current git head = latest release.
* Based on `extra/tinygo`, package download size will be ~1250 MiB.
