### ISSUE TITLE
[Request] intel-hybrid-codec-driver

### ISSUE THREAD

**Issue by joe733** [chaotic-aur/packages#1403]
### Link to the package(s) in the AUR

[intel-hybrid-codec-driver](https://aur.archlinux.org/packages/intel-hybrid-codec-driver)

### Utility this package has for you

Video decoding drivers

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Failed with `error: target not found: libcmrt` because it needs [libcmrt](https://aur.archlinux.org/packages/libcmrt)
