### ISSUE TITLE
[Request] keybase-bin

### ISSUE THREAD

**Issue by DenjixPochita** [chaotic-aur/packages#1406]
### Link to the package(s) in the AUR

[keybase-bin](https://aur.archlinux.org/packages/keybase-bin)

### Utility this package has for you

Secure messaging and file-sharing.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

It's official keybase client for arch : https://keybase.io/docs/the_app/install_linux

**Comment by Technetium1** [comment]
@DenjixPochita Why not use the same [packages in community](https://archlinux.org/packages/community/x86_64/keybase/)?

**Comment by DenjixPochita** [comment]
> @DenjixPochita Why not use the same [packages in community](https://archlinux.org/packages/community/x86_64/keybase/)?

Because of this https://github.com/keybase/client/issues/24800#issue-1107203567 it has Unnecessary systemd dependency + the aur one is officially maintained.
