### ISSUE TITLE
[Request] jellyfin-git

### ISSUE THREAD

**Issue by Bhooty** [chaotic-aur/packages#1407]
### Link to the package(s) in the AUR

https://aur.archlinux.org/pkgbase/jellyfin-git

### Utility this package has for you

It's a  is a web server for media like movies series etc

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

After building there will be 3 files jellyfin-git, jellyfin-server-git, jellyfin-web-git.
The jellyfin-git have to installed after the other two.

**Comment by Technetium1** [comment]
Builds successfully
