### ISSUE TITLE
[Request] adguardhome

### ISSUE THREAD

**Issue by joe733** [chaotic-aur/packages#1408]
### Link to the package(s) in the AUR

[adguardhome](https://aur.archlinux.org/packages/adguardhome)

### Utility this package has for you

Blocks network-wide ads and trackers

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
> Done in 101.00s.

Not sure where to add this, but it's built successfully :smiley:

**Comment by dr460nf1r3** [comment]
Add it to dragon-cluster hourly :)
