### ISSUE TITLE
[Request] amberol and amberol-git

### ISSUE THREAD

**Issue by alissonlauffer** [chaotic-aur/packages#1409]
### Link to the package(s) in the AUR

[amberol](https://aur.archlinux.org/packages/amberol)
[amberol-git](https://aur.archlinux.org/packages/amberol-git)

### Utility this package has for you

It's a new music player for GNOME and is gaining attention of most of the GNOME community in the last days.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

The `amberol` package will probably get into community soon, but `amberol-git` is still useful for testing future releases.

**Comment by Technetium1** [comment]
They each take ~6 minutes to successfully compile.

**Comment by bbhtt** [comment]
The packages [1](https://archlinux.pkgs.org/rolling/chaotic-aur-x86_64/amberol-0.5.0-1-x86_64.pkg.tar.zst.html), [2](https://archlinux.pkgs.org/rolling/chaotic-aur-x86_64/amberol-git-0.5.0.r16.g2f0b111-1-x86_64.pkg.tar.zst.html) should probably include `gst-plugins-good` as a dependency otherwise there is an error:

```

(amberol:4165): GStreamer-Play-WARNING **: 12:06:14.966: GstPlay: scaletempo element not available. Audio pitch will not be preserved during trick modes

```

Installing that package fixes the issue.

**Comment by dr460nf1r3** [comment]
I left a comment on both AUR pages so the maintainer can fix it :)

**Comment by Technetium1** [comment]
They were added very quickly

**Comment by Technetium1** [comment]
It compiles successfully now but has a warning that's interesting to make note of for both builds.
```
==> WARNING: Package contains reference to $srcdir
```

**Comment by dr460nf1r3** [comment]
This apparently happens at times when debug information reference $srcdir and didn't get stripped and can be disregarded most of the times :eyes:

**Comment by xiota** [comment]
`amberol-git` no longer builds because of pervasive `libadwaita` issue.  Dropping.
