### ISSUE TITLE
[Bug] simple-mtpfs missing from repo

### ISSUE THREAD

**Issue by tnxz** [chaotic-aur/packages#1410]
### What happens?

package 'simple-mtpfs' missing from the packages chaotic-aur repo

package does exist in ufscar-hpc/hourly.2.txt [Issue 976]

### What is expected to happen?

package to be available for install via pacman

**Comment by xiota** [comment]
The cause is that the package name is incorrect in [ufscar-hpc/hourly.2.txt](https://github.com/chaotic-aur/packages/blob/main/ufscar-hpc/hourly.2.txt#L1190).  The first letter is an `ś` (note the accent mark), while it should be a normal `s`.

**Comment by dr460nf1r3** [comment]
Btw - feel free to PR such changes! While we don't like PRs for new packages, this is a perfectly valid case to go for it :)

**Comment by xiota** [comment]
> Btw - feel free to PR such changes! While we don't like PRs for new packages, this is a perfectly valid case to go for it :)

Thanks.  Will keep this option in mind.  I just test built in a clean chroot.  Anything else I should do before opening a PR?

**Comment by dr460nf1r3** [comment]
Thanks! :) Testing the build in a clean chroot should be sufficient for now. If there is something else to do in a specific case, I'd let you know!
