### ISSUE TITLE
[Remove] tiemu

### ISSUE THREAD

**Issue by HimDek** [chaotic-aur/packages#1412]
### Packages

https://aur.archlinux.org/packages/tiemu

### Purpose

An emuator for TI-89/92/V200 calculators

### License

GPL-2.0-or-later

**Comment by Technetium1** [comment]
Something is going wrong when building `tiemu`
Log: https://builds.garudalinux.org/repos/chaotic-aur/logs/tiemu.log
Headstart on commit if someone beats me to fix:
```
# Issue 1412
libticonv # (dep libtifiles)
libtifiles # (dep libticalcs)
libticables # (dep libticalcs)
libticalcs # (dep tiemu)
tiemu
```

**Comment by Technetium1** [comment]
An AUR comment claims the makefile is apparently using the wrong flag to build, and thereby the compiler is treating formatting errors as actual errors: https://aur.archlinux.org/packages/tiemu#comment-840189

**Comment by Technetium1** [comment]
This depends on `python2` so it will not be added. See #1958

**Comment by xiota** [comment]
Dropped because depends on EOL GTK2.

Metrics:

* tiemu # 8
* libtifiles # 22
* libticonv # 21
* libticalcs # 18
* libticables # 19
