### ISSUE TITLE
[Request] openlitespeed

### ISSUE THREAD

**Issue by joe733** [chaotic-aur/packages#1414]
### Link to the package(s) in the AUR

[openlitespeed](https://aur.archlinux.org/packages/openlitespeed)

### Utility this package has for you

Setup a web server

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
I would like to drop this package for the following reasons:
* PKGBUILD is out of date for five months and counting.
* Checksum error and source changes that require nontrivial updates to patches.
* Incomplete build, errors, missing files.  [openlitespeed.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/openlitespeed.log)  Part of the build stops at 37%, followed by several errors and missing files.  Yet the package is still created.

**Comment by dr460nf1r3** [comment]
Fine by me!
