### ISSUE TITLE
[Bug] python-torchvision not building due to CUDA_HOME

### ISSUE THREAD

**Issue by flipflop97** [chaotic-aur/packages#1417]
### What happens?

The package `python-torchvision` build fails. It does so because `CUDA_HOME environment variable is not set.` This has probably been the case for as long as the package is included in the builds.

### What is expected to happen?

The package compiles successfully locally in a clean chroot as well as on the ArchLinuxCN repo. So I expected the package to also compile on Chaotic-AUR.

### If possible, please attach logs

[Chaotic-AUR](https://builds.garudalinux.org/repos/chaotic-aur/logs/python-torchvision.log)  
[ArchLinuxCN](https://build.archlinuxcn.org/imlonghao-api/pkg/python-torchvision/log/1651639506)

**Comment by hubutui** [comment]
As the build log shows, ArchLinuxCN repo builds this pkg with:
```bash
extra-x86_64-build -- -I /home/lilydjwg/archgitrepo/archlinuxcn/python-av/python-av-9.2.0-1-x86_64.pkg.tar.zst -I /home/lilydjwg/archgitrepo/archlinuxcn/python-pycocotools/python-pycocotools-2.0.4-1-x86_64.pkg.tar.zst
```
We simply follow the [wiki](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot#Passing_arguments_to_makepkg) to build this pkg with [devtools](https://archlinux.org/packages/?name=devtools).

**Comment by Technetium1** [comment]
Fixed via interfere with https://github.com/chaotic-aur/interfere/blob/master/python-torchvision/prepare

**Comment by dr460nf1r3** [comment]
Well done!
