### ISSUE TITLE
[Request] app-outlet

### ISSUE THREAD

**Issue by HiDe-Techno-Tips** [chaotic-aur/packages#1419]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/app-outlet-bin

### Utility this package has for you

A universal linux app store that supports snaps, flatpaks, appimages and native packages.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping.  Metrics 5.

* EOL Electron/11.5.0
* Upstream discontinued in 2023.
* Files dumped directly in `/opt` instead of dedicated subdirectory.
