### ISSUE TITLE
[Request] MyPy

### ISSUE THREAD

**Issue by caniko** [chaotic-aur/packages#1420]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/mypy-git

### Utility this package has for you

Python development, static typing.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because `extra/mypy` should be sufficient.  Metrics 17.
