### ISSUE TITLE
[Request] responsively

### ISSUE THREAD

**Issue by DenjixPochita** [chaotic-aur/packages#1425]
### Link to the package(s) in the AUR

[responsively](https://aur.archlinux.org/packages/responsively)

### Utility this package has for you

Helps in creating, helps in responsive web apps.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Network issues are currently affecting many downloads from https://registry.yarnpkg.com

**Comment by Technetium1** [comment]
I was also confused with the network issues, but when I tried on my own machine I got the same issue. Forgot to come back to this sooner. It's building now!
