### ISSUE TITLE
[Request] mangohud split into mangohud-x11 and mangohud-wayland

### ISSUE THREAD

**Issue by FireMasterK** [chaotic-aur/packages#1426]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/mangohud-wayland

https://aur.archlinux.org/packages/mangohud-x11

### Utility this package has for you

It already exists in chaotic-aur.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Maintainer's reasoning for the split: https://www.reddit.com/r/linux_gaming/comments/unal0s/comment/i8742if/

**Comment by Technetium1** [comment]
Only `mangohud-wayland` needs to be added. `mangohud-x11` comes from `mangohud`.
