### ISSUE TITLE
[Request] colorway

### ISSUE THREAD

**Issue by arthurflor23** [chaotic-aur/packages#1427]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/colorway

### Utility this package has for you

Tool with color picker and color pair generator.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
It is missing git, let's see if the author adds it quickly. https://aur.archlinux.org/packages/colorway#comment-864749

**Comment by xiota** [comment]
Dropping instead of adding new deps.  Last release was over two years ago.  Why does it need new deps without new release?  While the dev makes nice looking programs, the code is convoluted.  Repo is in unbuildable state.  Metrics is 1.
