### ISSUE TITLE
[Request] nvidia-open-beta-*

### ISSUE THREAD

**Issue by mobin-2008** [chaotic-aur/packages#1428]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/nvidia-open-git
https://aur.archlinux.org/packages/nvidia-open-beta-dkms

### Utility this package has for you

This driver is currently being tested and is currently only available via AUR.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Finally, NVIDIA has released open source modules for its graphics cards!

**Comment by xiota** [comment]
Dropping because `extra/nvidia-open` and `extra/nvidia-open` are available.  There is currently no difference across packages.  Metrics:

* nvidia-open-git # 9
* nvidia-open-dkms-git # 19
* nvidia-open-beta # 8
* nvidia-open-beta-dkms # 10
