### ISSUE TITLE
[Bug] rocm-opencl-runtime fails to build because of opencl-amd

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#1429]
### What happens?

It seems `rocm-opencl-runtime` fails to build because it conflicts with `opencl-amd`. The former is the open-source OpenCL driver from AMD, the latter is the proprietary one.

### What is expected to happen?

The `rocm-opencl-runtime` should build.

### If possible, please attach logs

[rocm-opencl-runtime.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/rocm-opencl-runtime.log)

**Comment by acxz** [comment]
@niobium93 if you want to use `rocm-opencl-runtime`, the rocm-arch group recommends the [arch4edu](https://github.com/arch4edu/arch4edu) repository as stated in the [README](https://github.com/rocm-arch/rocm-arch/#installation)

**Comment by niobium93** [comment]
@acxz I already am using `arch4edu` by now. Back when I reported this the packages on `arch4edu` were severely outdated and it wasn't getting any attention for months and months. Now it looks like they updated everything and are maintaining it. We'll see.

**Comment by dr460nf1r3** [comment]
Might be worth looking at their PKGBUILD versions and look for eventual fixes we can apply to the AUR PKGBUILDs.

https://github.com/arch4edu/arch4edu/tree/master/x86_64/rocm

**Comment by niobium93** [comment]
Are there any differences compared to [upstream](https://github.com/rocm-arch/rocm-arch)? I looked at a few and they look the same.

**Comment by acxz** [comment]
arch4edu packages rocm-arch packages, so they copy over the pkgbuilds from the rocm packages in the AUR and build it on their servers. There should be no difference between some pkgrel bumps to rebuild.

**Comment by acxz** [comment]
I believe the proper solution is to send a patch over to opencl-amd that lists those conflicting packages from rocm-arch in its conflicts field. They have a conflict with rocm-opencl-runtime, but not the others mentioned in the log file above: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=opencl-amd

**Comment by niobium93** [comment]
`rocm-opencl-runtime` is in Arch Linux community repo now.
