### ISSUE TITLE
[Request] rocm-hip-runtime

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#1430]
### Link to the package(s) in the AUR

[rocm-hip-runtime](https://aur.archlinux.org/packages/rocm-hip-runtime)

### Utility this package has for you

HIP is the AMD equivalent of Nvidia's CUDA. The 'blender-git' package now supports using HIP for rendering. I would like to use it for rendering in Blender.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Just like `rocm-opencl-runtime`, this will probably conflict with `opencl-amd`, so that should be fixed first. See #1429
Once that's done, both these ROCm packages will share lots of dependencies, including notably `rocm-llvm`, which Chaotic already builds, so building this shouldn't be _that_ much of an extra burden, hopefully.

**Comment by Technetium1** [comment]
There is indeed a conflict. Here's [the log](https://builds.garudalinux.org/repos/chaotic-aur/logs/rocm-hip-runtime.log).

**Comment by niobium93** [comment]
I think maybe the `opencl-amd` package should be modified to not `provide` all the `rocm` stuff, but conflict with it instead? I have no idea why it's like that.

**Comment by acxz** [comment]
@niobium93 if you are on a time crunch and need these packages, see: https://github.com/chaotic-aur/packages/issues/1429#issuecomment-1193342455

**Comment by niobium93** [comment]
`rocm-hip-runtime` is in Arch Linux community repo now.
