### ISSUE TITLE
[Bug] blender-git doesn't include denoising support

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#1431]
### What happens?

`blender-git` has `openimagedenoise` listed only as an optional dependency, unlike the upstream Arch `blender` package where it's a regular dependency. This probably results in it being unavailable at build time in the chaotic chroot. If it isn't available at build time, blender gets built without de-noising support.

### What is expected to happen?

Blender should be built with `openimagedenoise` present, as de-noising is a feature many blender users use.

### If possible, please attach logs

[blender-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/blender-git.log)

**Comment by dr460nf1r3** [comment]
While we can add it easily, this should also be reported at the AUR page so it can be fixed for everyone :)

**Comment by niobium93** [comment]
Looking at the pinned comment on the AUR page, it seems like it is the way it is on purpose. I guess they want people to be able to build with minimal dependencies if they want. IMO Chaotic should build with all the same dependencies as the regular non-git Arch package has, however.

**Comment by dr460nf1r3** [comment]
I agree. Let's do it like this then!

**Comment by dr460nf1r3** [comment]
Fixed in https://github.com/chaotic-aur/interfere/commit/032e64fbde4fb4dd2716218e46ec058098c5e022

**Comment by niobium93** [comment]
Awesome, thanks! <3
