### ISSUE TITLE
[Remove] planify

### ISSUE THREAD

**Issue by raul-lezameta** [chaotic-aur/packages#1432]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/planify

### Utility this package has for you

Task management

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Package is currently broken, and the maintainer has no intention to fix it.  The upstream project is planning to rename soon, so this package can be added again when the new renamed version is created.

**Comment by xiota** [comment]
Renamed project `planify` is in AUR.  I've updated the title and AUR link in this issue.  Test build in clean chroot, but did no other testing.

**Comment by xiota** [comment]
Package is drop candidate because `gxml` depends is unbuildable with MIA maintainer.

**Comment by xiota** [comment]
Dropped because moved to extra.

Metrics:

* gxml # 4
* planify # 3
