### ISSUE TITLE
[Request] python2-cairo and python2-numpy

### ISSUE THREAD

**Issue by robson-66** [chaotic-aur/packages#1436]
### Link to the package(s) in the AUR

[python2-cairo](https://aur.archlinux.org/packages/python2-cairo)
[python2-numpy](https://aur.archlinux.org/packages/python2-numpy)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

I would very much like to ask you to add these packages as they are dependencies of `pygtk`.

**Comment by dr460nf1r3** [comment]
Just had a look, apart from being in the package lists it's also available in our database 👀

**Comment by robson-66** [comment]
But `python2-cairo` is required when installing` pygtk`.

**Comment by dr460nf1r3** [comment]
You were actually right. My apologies, they are added now! :)
