### ISSUE TITLE
[Request] joystickwake and xone-dkms

### ISSUE THREAD

**Issue by dankcuddlybear** [chaotic-aur/packages#1437]
### Link to the package(s) in the AUR
https://aur.archlinux.org/packages/joystickwake
https://aur.archlinux.org/packages/xone-dkms
https://aur.archlinux.org/packages/beignet

### Utility this package has for you

joystickwake: Keep the screensaver alive while controller input is detected
xone-dkms: Xbox One controller driver with wireless dongle support
beignet: An open source OpenCL implementation for Intel IvyBridge & Haswell iGPUs

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
beignet was [flagged](https://aur.archlinux.org/pkgbase/beignet/flag-comment) out of date:
> [pedrogabriel](https://aur.archlinux.org/account/pedrogabriel) flagged beignet out-of-date on 2021-04-04 (EDT) for the following reason:
> Not building with lvm 11, do as said in the comments

This is a problem.

**Comment by Technetium1** [comment]
Please open another seperate issue for beignet if you're still interested in it.

**Comment by xiota** [comment]
Dropped `xone-dkms` and `xone-dkms-git` because the upstream project reported to be unmaintained.  Dropped `xone-dongle-firmware`.  Added custom package with firmware included: `xone-dlundqvist-dkms-git`.

Metrics:

* joystickwake # 57
* xone-dkms # 425
* xone-dkms-git # 96
* xone-dongle-firmware # 489

**Comment by xiota** [comment]
Switched back to `aur/xone-dkms-git` because it's been switched to the dlundqvist fork.

Metrics:

* joystickwake # 21
* xone-dlundqvist-dkms-git # 344
