### ISSUE TITLE
[Request] deluge-git

### ISSUE THREAD

**Issue by mdhishamsayed** [chaotic-aur/packages#1438]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/deluge-git

### Utility this package has for you

A BitTorrent client with multiple user interfaces in a client/server model (git version, 'develop' branch)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Good torrenting client GTK+

**Comment by Technetium1** [comment]
```
WARNING: The wheel package is not available.
/usr/sbin/python: No module named pip
```

**Comment by Technetium1** [comment]
Added `python-pip` in https://github.com/chaotic-aur/interfere/commit/8f14e26f0520fa8c5072f1b84ec7b03db4825cd9

**Comment by Technetium1** [comment]
I left a [comment](https://aur.archlinux.org/packages/deluge-git#comment-865310), hopefully the package maintainer notices.

**Comment by xiota** [comment]
Dropping because `extra/deluge` is available and no new commits since 2022-07-10, same day as latest release. Metrics 24.
