### ISSUE TITLE
[Request] strawberry-qt5

### ISSUE THREAD

**Issue by userofryzen** [chaotic-aur/packages#1441]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/strawberry-qt5

### Utility this package has for you

globalmenu doesn't work on QT6 yet
close to tray has problems on qt6 with strawberry
both of them are fixed with QT5 so..

in addition the look and feel is more comfortable on QT5 because KDE not being Qt6 yet

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

my build is not done on a clean chroot I think( idk what is it) but It compiles correct( i have just done it)
compiles in a good time to be honest( my cpu is weak so no bother to you)

**Comment by xiota** [comment]
Dropping for following reasons:

* Not updated for Qt6 (see [#3157](https://github.com/chaotic-aur/packages/issues/3157))
* Not rebuilding for `icu` 75.

Note: Package does not list `icu` in depends, and has needed special intervention for previous updates.
