### ISSUE TITLE
[Bug] subtitlecomposer need rebuild

### ISSUE THREAD

**Issue by lynoxy** [chaotic-aur/packages#1442]
### What happens?

subtitlecomposer won't launch error message:

`subtitlecomposer: error while loading shared libraries: libicui18n.so.70: cannot open shared object file: No such file or directory`

### What is expected to happen?

no error

### More information

current icu version 71.1

subtitlecomposer need rebuild

**Comment by Technetium1** [comment]
From the log:
```
-- Found ICU: 
	includes: /usr/include
	libs: /usr/lib/libicui18n.so;/usr/lib/libicuuc.so;/usr/lib/libicudata.so
	 (found version "70.1") 
-- Subtitle Composer plugin path: /usr/lib/subtitlecomposer
-- ICU Library will be used for charset detection.
```

**Comment by Technetium1** [comment]
Bumped and rebuilt: https://github.com/chaotic-aur/interfere/commit/08375e2f3a13c49e5e9edb1a652815f351c44f0e. Please comment if the issue persists.
