### ISSUE TITLE
[Outdated] osu-lazer 2022.515.0

### ISSUE THREAD

**Issue by stormzyyyy** [chaotic-aur/packages#1443]
### If available, link to the latest build

[osu-lazer.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/osu-lazer.log)

### Package name

osu-lazer

### Latest build

v2022.509.0-1

### Latest version available

2022.515.0

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

osu! release version 2022.515.0 was released 5 days ago and has not been updated. The build available in the chaotic-aur is version 2022.509.0-1.

**Comment by Technetium1** [comment]
The package is [flagged](https://aur.archlinux.org/pkgbase/osu-lazer/flag-comment):
> [ZhangHua](https://aur.archlinux.org/account/ZhangHua) flagged osu-lazer out-of-date on 2022-05-15 (EDT) for the following reason:
Version 2022.515.0 has been released

**Comment by stormzyyyy** [comment]
osu!lazer version 2022.523.0-1 was realeased in the AUR and is now available in the chaotic-aur.
