### ISSUE TITLE
[Outdated] firefox-appmenu

### ISSUE THREAD

**Issue by efeflorez** [chaotic-aur/packages#1444]
### If available, link to the latest build

[firefox-appmenu-log](https://builds.garudalinux.org/repos/chaotic-aur/logs/firefox-appmenu.log)

### Package name

`firefox-appmenu`

### Latest build

`100.0-1`

### Latest version available

`99.0.1-1`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

it seems that there are errors in the building of the package in firefox-appmenu.log that ended up leaving version 99.0.1-1

**Comment by Technetium1** [comment]
`OSError: [Errno 28] No space left on device`

**Comment by Technetium1** [comment]
Build failed again :confused:

**Comment by dr460nf1r3** [comment]
Actually quite the same thing:
`LLVM ERROR: IO failure on output stream: No space left on device`

Gotta look into it tomorrow, quite a few packages failing due to no space lately 🧐

**Comment by dr460nf1r3** [comment]
Funny thing, the build still fails due to something else now 🤔

**Comment by mandanguero** [comment]
I really appreciate you keeping an eye on all the problems!
wish I could contribute in some other way :neutral_face:

**Comment by Technetium1** [comment]
@mandanguero You're contributing just by opening accurate issues, thanks for your effort :smiley:

**Comment by dr460nf1r3** [comment]
"fixed" by disabling PGO in the PKGBUILD for now. It's a known issue with Firefox based browsers atm, something yet unknown in our toolbox makes the build fail after the profiling phase. Personally, I'd say security patches > PGO build, hope its an acceptable solution for the time being.

**Comment by Technetium1** [comment]
Apparently there are issues browsing YouTube with PGO removed.

**Comment by lowne** [comment]
Might wanna reopen this as v103 has been [failing to build](https://builds.garudalinux.org/repos/chaotic-aur/logs/firefox-appmenu.log) for more than a week now.

**Comment by dr460nf1r3** [comment]
It's apparently due to the glibc update that happened. No Firefox builds as of now :/

**Comment by Technetium1** [comment]
The latest rebuild (just now) reproduced the failure as referenced above, instead of the failure downloading sources that was shown in #1636.

**Comment by jothi-prasath** [comment]
firefox-appmenu 103.0.2-1 was out now

**Comment by Technetium1** [comment]
Still failing the same way.

**Comment by dr460nf1r3** [comment]
Well, its also suffering from the recent Rust 1.63 update as every other Firefox right now. [Left a comment about its fix](https://aur.archlinux.org/packages/firefox-appmenu#comment-877824), which already got merged upstream but still needs to arrive.

**Comment by jothi-prasath** [comment]
firefox-appmenu 104.0.1-1 is out and i can successfully build it in my local machine

**Comment by Technetium1** [comment]
Just failed to rebuild again due to some pip compatibility issues.

**Comment by jothi-prasath** [comment]
it can be fixed by changing   `export MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE=pip` to `export MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE=system`in PKGBUILD

**Comment by dr460nf1r3** [comment]
The package builds alright nowadays! Its still version 104.0.2 as the AUR package hasn't been updated in a while, which is the maintainers task to solve though :)
