### ISSUE TITLE
[Outdated] linux-xanmod-edge

### ISSUE THREAD

**Issue by Inetol** [chaotic-aur/packages#1445]
### If available, link to the latest build

[linux-xanmod-edge.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-xanmod-edge.log)

### Package name

`linux-xanmod-edge`

### Latest build

`5.17.9-1`

### Latest version available

`5.17.5-1.2`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

The logs about last build show that version `5.17.8-1` was not compiled due to lack of space.

**Comment by Technetium1** [comment]
From the log: 
> ==> Making package: linux-xanmod-edge 5.17.8-1 (Tue 17 May 2022 12:22:26 PM UTC)

**Comment by dr460nf1r3** [comment]
I issued a build before starting to work this morning :)
