### ISSUE TITLE
[Outdated] protonup-qt

### ISSUE THREAD

**Issue by ChaoticSi1ence** [chaotic-aur/packages#1446]
### If available, link to the latest build

[protonup-qt.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/protonup-qt.log)

### Package name

`protonup-qt`

### Latest build

`v2.6.0`

### Latest version available

`v2.6.2`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by Technetium1** [comment]
?!
