### ISSUE TITLE
[Request] shutter-git

### ISSUE THREAD

**Issue by robson-66** [chaotic-aur/packages#1447]
### Link to the package(s) in the AUR

[shutter-git](https://aur.archlinux.org/packages/shutter-git)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by dr460nf1r3** [comment]
This package has no use for you? 🤔

**Comment by Technetium1** [comment]
Why is that dependency not required in the [-git version](https://aur.archlinux.org/packages/shutter-git)? Is it actually necessary? Maybe @muflone has something to say about it. https://github.com/muflone/pkgbuilds/blob/70c9256b37ffd2f49d2bd58c5ed003eb7f314327/shutter/PKGBUILD#L40

**Comment by robson-66** [comment]
But then do not add this package to the chaotic-aur repo, because I rebuilt `shutter` from the community myself by removing the dependency` xdg-desktop-portal`

**Comment by muflone** [comment]
> Why is that dependency not required in the [-git version](https://aur.archlinux.org/packages/shutter-git)? Is it actually necessary? Maybe @muflone has something to say about it. https://github.com/muflone/pkgbuilds/blob/70c9256b37ffd2f49d2bd58c5ed003eb7f314327/shutter/PKGBUILD#L40

Please see https://github.com/shutter-project/shutter/issues/416

**Comment by Photon89** [comment]
@muflone @robson-66 

Hi guys, I'm a bit late to the party, but I just got some spare time and wanted to update the shutter-git package by adding the xdg-desktop-portal dependency. However, if there are people who explicitly don't want it, what about splitting it into shutter-xorg-git and shutter-wayland-git (the only difference being the xdg-desktop-portal dependency)?
