### ISSUE TITLE
[Request] freetube-bin

### ISSUE THREAD

**Issue by mdhishamsayed** [chaotic-aur/packages#1448]
### Link to the package(s) in the AUR

https://aur.archlinux.org/freetube-bin.git

### Utility this package has for you

An open source desktop YouTube player built with privacy in mind.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Is this related issue still applicable?
https://github.com/chaotic-aur/packages/issues/1376

AUR comment says Electron 17 works, but the [release notes](https://github.com/FreeTubeApp/FreeTube/releases/tag/v0.16.0-beta) say:

> Electron has been updated to v16.0.8, fixing an issue with video playback on older versions of Windows

**Comment by mdhishamsayed** [comment]
@Technetium1 This App Works

**Comment by xiota** [comment]
Package in repo is based on `aur/freetube` (not freetube-bin).  It's been flagged for a week.  Maintainers are usually allowed at least two weeks to update.
