### ISSUE TITLE
[Outdated] proton-ge-custom failed to build

### ISSUE THREAD

**Issue by RubenKelevra** [chaotic-aur/packages#1449]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/proton-ge-custom.log

### Package name

proton-ge-custom

### Latest build

`2:GE.Proton7.18-1`

### Latest version available

`2:GE.Proton7.16-1`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

That's the end of the logfile:

```
==> Making package: proton-ge-custom 2:GE.Proton7.18-1 (Mon 23 May 2022 03:06:59 PM -03)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating proton-ge-custom git repo...
Fetching origin
  -> Updating wine-valve git repo...
Fetching origin
  -> Updating dxvk git repo...
Fetching origin
  -> Updating openvr git repo...
Fetching origin
==> ERROR: /home/main-builder/pkgsrc/liberation-fonts is not a clone of https://github.com/liberationfonts/liberation-fonts.git
    Aborting...
```

**Comment by dr460nf1r3** [comment]
The package is in fact building right in this moment (since like an hour) 🚀

**Comment by dr460nf1r3** [comment]
@thotypous ufscar needs its source cleared :)

**Comment by dr460nf1r3** [comment]
The package got built, leaving this open tho since the actual builder still needs to be fixed.
