### ISSUE TITLE
[Request] vlang

### ISSUE THREAD

**Issue by tuhanayim** [chaotic-aur/packages#1452]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/vlang

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
[Flagged out-of-date (2022-01-03)](https://aur.archlinux.org/pkgbase/vlang/flag-comment). Maybe we should use [vlang-git](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vlang-git)?

**Comment by tuhanayim** [comment]
It isn't outdated. It has weekly builds. Latest stable version is `0.2.4`.

**Comment by Technetium1** [comment]
Fails in clean chroot, see: https://builds.garudalinux.org/repos/chaotic-aur/logs/vlang.log

**Comment by tuhanayim** [comment]
This is weird because my friend was using this package with no build issues. Can you try `-git` version?

**Comment by Technetium1** [comment]
Built successfully: https://builds.garudalinux.org/repos/chaotic-aur/logs/vlang-git.log
Either we can wait for upstream to fix, figure the problem ourselves and use interfere to fix, or just use the `-git` version.

**Comment by tuhanayim** [comment]
`-git` version is ok in my opinion.

**Comment by dr460nf1r3** [comment]
Nice! :)
