### ISSUE TITLE
[Request] stockfish

### ISSUE THREAD

**Issue by theblobscp** [chaotic-aur/packages#1456]
### Link to the package(s) in the AUR

[Stockfish](https://aur.archlinux.org/packages/stockfish)

### Utility this package has for you

Stockfish is a chess engine that works with several chess clients. I have tested it with GNOME Chess and it does work as an engine.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Stockfish is one of if not the best-known chess engines. As a chess enjoyer myself, I thought that other stockfish users would like to have it prebuilt.

**Comment by Technetium1** [comment]
No difference to us, just a matter of which one is more frequently updated :smiley:

**Comment by theblobscp** [comment]
Tysm

**Comment by xiota** [comment]
The AUR packages and upstream makefile detect and force cpu features, causing the resulting package to be unusable on some computers.  Replaced with interfere that bypasses cpu detection.  The interfere also autoupdates the standard version and fixes pkgver of the git version.
