### ISSUE TITLE
[Bug] 404 Not Found error after attempting to install brave-nightly-bin

### ISSUE THREAD

**Issue by stormzyyyy** [chaotic-aur/packages#1462]
### What happens?

Attempting to install `brave-nightly-bin` from the repository will fail due to a 404 error. This is because it attempts to retrieve `brave-nightly-bin-1.41.30-1-x86_64.pkg.tar.zst` when it should really be trying to get `brave-nightly-bin-1.41.31-1-x86_64.pkg.tar.zst`
![image](https://user-images.githubusercontent.com/84043891/171525849-d9c39fa5-4472-4e7d-8a41-cf7cfa91d96f.png)

### What is expected to happen?

The package is expected to install normally, like its stable counterpart, `brave-bin`

**Comment by dr460nf1r3** [comment]
> Attempting to install `brave-beta-bin`
This is probably a typo? 

How did you try to install `brave-nightly-bin`? I'm assuming you missed doing syncing the database as I can download it correctly here. As this is one of the more frequently changing packages, installing using `pacman -Syu` is always a good idea.

**Comment by stormzyyyy** [comment]
Yes, that part is a typo.

I attempted to install it by running `pacman -S brave-nightly-bin`. I'm pretty sure I hadn't updated the database in a while, because running it as `pacman -Sy brave-nightly-bin` now works. And thank you for that suggestion!
