### ISSUE TITLE
[Outdated] plasma5-wallpapers-wallpaper-engine-git

### ISSUE THREAD

**Issue by zany130** [chaotic-aur/packages#1463]
### Package name

plasma5-wallpapers-wallpaper-engine-git

### Latest build

r398.5bbb4d8-1 

### Latest version available

plasma5-wallpapers-wallpaper-engine-without-mpv-git r441.791240d-2

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information
[wallpaper-engine-git](https://aur.archlinux.org/packages/plasma5-wallpapers-wallpaper-engine-git) seems to be depricated in favor of [wallpaper-engine-without-mpv-git](https://aur.archlinux.org/packages/plasma5-wallpapers-wallpaper-engine-without-mpv-git)

also maybe worthy of note that there is a stable version also on the aur https://aur.archlinux.org/packages/plasma5-wallpapers-wallpaper-engine

**Comment by dr460nf1r3** [comment]
Removed the old package and added both of the new ones.
