### ISSUE TITLE
[Request] Noisetorch

### ISSUE THREAD

**Issue by Pistrie** [chaotic-aur/packages#1464]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/noisetorch

### Utility this package has for you

It filters out background noise so you don't irritate the other people will in a call with them.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
I would like to see a couple more things finished before adding it, but it will be back soon! 
https://github.com/noisetorch/NoiseTorch/issues/310, 
https://github.com/noisetorch/NoiseTorch/issues/298, 
https://github.com/noisetorch/NoiseTorch/issues/311, 
as well as https://github.com/noisetorch/NoiseTorch/issues/290 and the related discussion https://github.com/noisetorch/NoiseTorch/discussions/284.

**Comment by Technetium1** [comment]
`#335` seems to be specific to Feren OS, and has not been reproduced. `#311` will probably not be done for a while, so I'm okay adding this in again.
