### ISSUE TITLE
[Remove] mullvad-vpn, mullvad-vpn-cli

### ISSUE THREAD

**Issue by edgarjustus** [chaotic-aur/packages#1465]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/mullvad-vpn
https://aur.archlinux.org/packages/mullvad-vpn-cli

### Utility this package has for you

This is the Mullvad vpn client

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
We currently build `mullvad-vpn-beta`, that's my preferred choice since it gets [updated much more frequently](https://github.com/mullvad/mullvadvpn-app/releases), does that effectively solve the GUI request?

**Comment by Technetium1** [comment]
The cli built fine.

**Comment by HansAmPfaall** [comment]
I want the cli to comfortable split tunnel certain Apps and I'm not sure if the cli works with the beta build

**Comment by HansAmPfaall** [comment]
I just found out that both packages are not compatible so just the cli would be awesome

**Comment by dr460nf1r3** [comment]
Sure thing! :)

**Comment by Technetium1** [comment]
> I want the cli to comfortable split tunnel certain Apps and I'm not sure if the cli works with the beta build

The split tunnel is possible via GUI.

**Comment by xiota** [comment]
Dropping because moved to extra.

Metrics:

* mullvad-vpn # 2250
* mullvad-vpn-cli # 125
