### ISSUE TITLE
[Bug] pamac-classic: signature is invalid

### ISSUE THREAD

**Issue by jtfen86** [chaotic-aur/packages#1468]
### What happens?

error: pamac-classic: signature from "Pedro Henrique Lara Campos <root@pedrohlc.com>" is invalid.

### What is expected to happen?

Install without error obviously! :V

### More information

I tried reinstalling chaotic-keyring and repopulating keys, no dice.

**Comment by jtfen86** [comment]
This is happening again! :(

**Comment by xiota** [comment]
@dr460nf1r3 Is it enough to just rebuild these or does something more need to be done?

**Comment by dr460nf1r3** [comment]
Bumping + building is sufficient.

**Comment by jtfen86** [comment]
> Bumping + building is sufficient. Or just rebuilding, since nobody's installed it anyways yet 😬

I installed it through AUR since this was broken but it just upgraded from the repo without error. I like classic because it's just.. simple. The search history on the sidebar is great too to help keep track of what stuff I just installed. I do have pkgstats installed as a dependency so maybe you just saw one install? :D

**Comment by xiota** [comment]
> maybe you just saw one install?

Maybe was referring to the signature issue?  No one should install packages with broken signature.
