### ISSUE TITLE
[Outdated] wine-tkg-staging-fsync-git

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#1473]
### If available, link to the latest build

[wine-tkg-staging.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/wine-tkg-staging.log)

### Package name

`wine-tkg-staging-fsync-git`

### Latest build

`7.7.r15.gcd7567fd-327`

### Latest version available

`7.10`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

`0002-proton_LFH.mypatch` community patch fails to apply.
It would also probably be affected by the [binutils 2.38 issue](https://github.com/Frogging-Family/wine-tkg-git/issues/764).

**Comment by dr460nf1r3** [comment]
This would require updating either toolbox or wine-tkg repo. We build from the `chaotic-*` profiles of the official repo: https://github.com/Frogging-Family/wine-tkg-git/tree/master/wine-tkg-git/wine-tkg-profiles
I pulled the builds for now since they are severely outdated.

**Comment by niobium93** [comment]
According to that issue, this is fixed now? Could you retry the build?
