### ISSUE TITLE
[Request] conserve(-git)

### ISSUE THREAD

**Issue by road2react** [chaotic-aur/packages#1482]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/conserve

https://aur.archlinux.org/packages/conserve-git

### Utility this package has for you

This package is a backup program that "conserves" data :)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
I think [conserve-git](https://aur.archlinux.org/packages/conserve-git) might be the most useful version here since new releases are *VERY* scarcely tagged: https://github.com/sourcefrog/conserve/compare/v0.6.15...main

**Comment by Technetium1** [comment]
This was intended to be closed with https://github.com/chaotic-aur/packages/commit/deff6ba8bb3ce14c613f2c7c3fd4dde909589079 but I fat-fingered the issue number. Please let us know if `conserve-git` is not enough.
