### ISSUE TITLE
[Request] yin-yang-git

### ISSUE THREAD

**Issue by dankcuddlybear** [chaotic-aur/packages#1483]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/yin-yang-git

### Utility this package has for you

Automatically switch to dark theme at night for KDE, Gnome, Budgie, VSCode, Atom and more

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Not building: [log](https://builds.garudalinux.org/repos/chaotic-aur/logs/yin-yang-git.log).

```
install: cannot stat 'src/yin-yang': No such file or directory
```

**Comment by xiota** [comment]
Does this need to be bumped?  AUR is updated, but log date is from 2023-05-03.

**Comment by Technetium1** [comment]
@xiota nope seems that it was bad cache causing it at least to some extent. Also it [updated since then](https://aur.archlinux.org/cgit/aur.git/log/?h=yin-yang-git).
`Finished making: yin-yang-git 3.2.4.r11.g0cd2fb2-1 (Thu 11 May 2023 09:23:26 AM CEST)`
