### ISSUE TITLE
[Outdated] 

### ISSUE THREAD

**Issue by hunabku94** [chaotic-aur/packages#1484]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-clear.log

### Package name

linux-clear

### Latest build

5.17.12

### Latest version available

5.17.13

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

The linux-clear-headers package is up to date but not the linux-clear.
That cause DKMS modules can't build!
I builded it if you want to gain time : 
https://mega.nz/folder/fQgQWa4R#OrIAeweYt-dArXCNiYfAsQ

**Comment by dr460nf1r3** [comment]
Building and offering is a nice thing to do but we sadly can't add packages built by users to our repo because of security reasons. I just started the build on one of our builders though, so it should be available soon :)

**Comment by hunabku94** [comment]
I understand, thanks a lot for your work and your reactivity !
