### ISSUE TITLE
[Bug] Inner conflicts trying to install Compiz 0.8 plugins (compiz-core)

### ISSUE THREAD

**Issue by Viktini** [chaotic-aur/packages#1485]
### What happens?

When trying to install any of the Compiz Fusion plugins (for Compiz 0.8/`compiz-core`) from the AUR, `yay` complains about inner conflicts due to `compiz-bcop` from the AUR trying to pull `compiz` (Compiz 0.9) from Chaotic-AUR, even when `compiz-core` is already installed beforehand.

This also happens with `libcompizconfig` and `compizconfig-python`.

### What is expected to happen?

`compiz-bcop`'s dependency should pull `compiz-core` from Chaotic-AUR, rather than `compiz`, if `compiz-core` is already installed.

### If possible, please attach logs

```
:: Checking for conflicts...
:: Checking for inner conflicts...
 -> Inner conflicts found:
 -> compiz-core: compiz
 -> compiz: compiz-core, compiz-fusion-plugins-main
 -> Conflicting packages will have to be confirmed manually
```

### More information
For Compiz 0.8, the plugins are _required_ in order to get a basic window management setup going. `compiz-gtk` may help with window decorations, but some may want to use `emerald` as well.

This might be remedied by adding all of the Compiz-related required packages into Chaotic-AUR, or removing 0.8 from the repository and letting those who want it compile it themselves... or adding a Provides option on `compiz-core`.

For what it's worth, here's [the AUR page for `compiz-core`](https://aur.archlinux.org/packages/compiz-core).

**Comment by dr460nf1r3** [comment]
That looks like a packaging issue on `compiz` to me. If you look at its `provides()` you can see it already includes `compiz-bcop`. Since it is available in Chaotic-AUR already it is also the preferred package. To solve this particular issue you can tell yay to explicitly install from AUR: 
`yay -S aur/compiz-bcop`
