### ISSUE TITLE
[Request] kwallet-secrets

### ISSUE THREAD

**Issue by sylviiu** [chaotic-aur/packages#1486]
### Link to the package(s) in the AUR

[AUR](https://aur.archlinux.org/packages/kwallet-secrets)

### Utility this package has for you

KWallet has lacked the capabilities for FreeDesktop secrets -- this package is built with necessary patches to enable said capabilities / support.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

As a sidenote, I don't fully understand licensing -- it's listed as `LGPL` on the AUR, which I believe permits redistributing binaries? (only note I've seen with it is that it must be explicit what's changed / modified, if any)

**Comment by Technetium1** [comment]
Fine to redistribute: https://opensource.stackexchange.com/a/4328
