### ISSUE TITLE
[Outdated] strawberry-qt5

### ISSUE THREAD

**Issue by r0ckhopper** [chaotic-aur/packages#1487]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/strawberry-qt5.log

### Package name

strawberry-qt5

### Latest build

1.0.4

### Latest version available

1.0.5

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

New release of Strawberry that has been updated to v1.0.5 in the AUR https://aur.archlinux.org/packages/strawberry-qt5

**Comment by Technetium1** [comment]
Done :smiley:
