### ISSUE TITLE
[Request] handbrake-nvenc

### ISSUE THREAD

**Issue by cleanerspam** [chaotic-aur/packages#1489]
### Link to the package(s) in the AUR

http://aur.archlinux.org/packages/handbrake-nvenc

### Utility this package has for you

Allows fast video encoding by utilizing nvidia GPU power 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

please add --enable-qsv flag also , so that it supports x265 , x265(qsv) , x265(NVENC)

**Comment by dr460nf1r3** [comment]
Required build flag added in https://github.com/chaotic-aur/interfere/commit/d88ef92dedf2821a29f8c5ab8a79161f8c469816

**Comment by xiota** [comment]
Switching to `handbrake-full` because it is better maintained.

**Comment by xiota** [comment]
Dropping for confluence of factors.  Should not be re-added.  Metrics 447.

**Comment by FabioLolix** [comment]
You could switch to `handbrake-semifull` which have all the features except for the offending one (fkd-aac) https://aur.archlinux.org/packages/handbrake-semifull

btw which other pkgbuilds of mine do you have in chaotic-aur?

**Comment by xiota** [comment]
@FabioLolix I don't think can add semi-full either.  IMO, merely linking GPL2 with "incompatible" open-source libraries is a factitious problem.  But suppose it is a real problem, linking with closed-source libraries would be even worse, which makes the original request (nvenc) impossible to satisfy.

There are currently 41 packages that you maintain (fewer pkgbase, depending on splits).  (I've sent you a list elsewhere.)

**Comment by FabioLolix** [comment]
> linking with closed-source libraries would be even worse, which makes the original request (nvenc) impossible to satisfy.

nvenc in ffmpeg which handbrake bundle is enabled by MIT licensed `ffnvcodec-headers` which also Arch's package enable https://archlinux.org/packages/extra/any/ffnvcodec-headers/ and don't taint ffmpeg, nvidia-utils and cuda are not present at build time, it call the binary when it need it guess; you could always inquiry upstream

**Comment by xiota** [comment]
If linking were actually problematic, that type of workaround wouldn't hold up. If anything, it increases legal exposure because it demonstrates intent.  If linking works as FSF claims, it is transitive.  Link the shim, becomes part of the whole.  Shim links something else, that also becomes part of the whole.  And so on.  It's obviously absurd.
