### ISSUE TITLE
[Bug]  strawberry-qt5 libprotobuf error - package needs rebuilding

### ISSUE THREAD

**Issue by r0ckhopper** [chaotic-aur/packages#1490]
### What happens?

After the update of protobuf today in the Arch repos [https://archlinux.org/packages/extra/x86_64/protobuf/](url) attempting to launch the qt5 build of strawberry results in the following error:
`strawberry: error while loading shared libraries: libprotobuf.so.31: cannot open shared object file: No such file or directory`

### What is expected to happen?

Strawberry launches as normal.

### More information

Rebuilding the strawberry-qt5 package myself from the AUR builds against this latest version of protobuf. Therefore a rebuild of the Chaotic AUR package should resolve this issue.

The qt6 build of strawberry in the Arch community repo has also been rebuilt today - [https://github.com/archlinux/svntogit-community/commits/packages/strawberry/trunk](url)

**Comment by Technetium1** [comment]
@r0ckhopper should be good now https://github.com/chaotic-aur/interfere/commit/a484680ba9edf76ae046ee5861ede71ecfbafd97

**Comment by r0ckhopper** [comment]
Yes, all good now - thank you.
