### ISSUE TITLE
[Request] gyroflow

### ISSUE THREAD

**Issue by ni-ka** [chaotic-aur/packages#1491]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/gyroflow-git

### Utility this package has for you

Used to stabilize video footage.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
This software looks great!

**Comment by Technetium1** [comment]
It does not build in clean chroot as it's missing some things in makedepends, so I found out what broke [left a comment with a solution](https://aur.archlinux.org/packages/gyroflow-git#comment-869685). I'll add an entry in the meantime ( https://github.com/chaotic-aur/interfere/commit/58097fe44079143ded2b3d004597cf386d152786 ), but the package maintainer seems active so it should be fixed for everyone else soon.

**Comment by Technetium1** [comment]
Compilation takes ~10min
