### ISSUE TITLE
[Request] ms-office-electron-bin

### ISSUE THREAD

**Issue by arthurflor23** [chaotic-aur/packages#1493]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/ms-office-electron-bin

### Utility this package has for you

MS Office Electron is the app in which the web free version of Microsoft Office is wrapped into a cross-platform app with Electron.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
I use `ms-office-online` and `teams` if I need to interact with 365, and it's been perfect. Will that suffice or is there a benefit to this particular version?

**Comment by arthurflor23** [comment]
I think it's only the base toolkit.
The ``ms-office-online`` uses jade-application-kit, which brings qt5 stuffs; and ``ms-office-electron-bin`` uses electron, which brings gtk stuffs

However, I'm not sure actually in the application itself.
I can try ``ms-office-online`` with no problem here

**Comment by Technetium1** [comment]
This is an 82MB file to mirror, as opposed to a tiny 17KB for `ms-office-online` and 43KB for `jade-application-kit`, it does not make a ton of sense to have both given the giant difference in size. If that is an alright outcome could the issue be closed?

**Comment by arthurflor23** [comment]
You have a good point. I completely agree.
