### ISSUE TITLE
[Outdated] Heroic-games-launcher-bin

### ISSUE THREAD

**Issue by mrnetlex** [chaotic-aur/packages#1495]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/heroic-games-launcher-bin.log

### Package name

heroic-games-launcher-bin

### Latest build

2.3.7-2

### Latest version available

2.3.9-2

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### More information

Version 2.3.9-2 is available in AUR - https://aur.archlinux.org/packages/heroic-games-launcher-bin.

**Comment by Technetium1** [comment]
Done!

**Comment by mrnetlex** [comment]
Thanks!!!
