### ISSUE TITLE
[Request] Include what you use

### ISSUE THREAD

**Issue by innerout** [chaotic-aur/packages#1496]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/include-what-you-use

### Utility this package has for you

Linting for C/C++ file. Extremely useful to maintain high quality when coding.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
This has been flagged out of date for a while now... https://aur.archlinux.org/pkgbase/include-what-you-use/flag-comment

**Comment by innerout** [comment]
Hi, it is flagged as outdated but builds successfully with the clang provided in the Arch repositories. This has happened because clang has not been updated to the latest version in the Arch repositories for more than four months. So I believe it is safe to build the package. So the transition to v0.18 cannot happen, but that is not a problem in building the package.
