### ISSUE TITLE
[Request] playonlinux & phoenicis-playonlinux

### ISSUE THREAD

**Issue by Bhooty** [chaotic-aur/packages#1500]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/playonlinux

### Utility this package has for you

an app to install windows app

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No, but the author doesn't really care anyways. It's just for bureaucracy.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
This is being superseded by [Phoenicis](https://phoenicisorg.github.io/phoenicis/) which also has [an AUR package](https://aur.archlinux.org/packages/phoenicis-playonlinux). Let's add both while it's in a transitional state.
