### ISSUE TITLE
[Request] python-qt-material-git

### ISSUE THREAD

**Issue by Bhooty** [chaotic-aur/packages#1501]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/python-qt-material-git

### Utility this package has for you

Opensnitch application needs this

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because `extra/opensnitch` and `extra/python-qt-material` are available.  Metrics 13.
