### ISSUE TITLE
[Request] Ferdium

### ISSUE THREAD

**Issue by csolisr** [chaotic-aur/packages#1503]
### Link to the package(s) in the AUR

[https://aur.archlinux.org/packages/ferdium](https://aur.archlinux.org/packages/ferdium)

### Utility this package has for you

Since Ferdi, the original fork of Franz, has been officially discontinued, Ferdium comes out as a near drop-in replacement of functionality.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
That took a REALLY long time to build, let's use `ferdium-bin` since it's built from CI.
