### ISSUE TITLE
[Outdated] wine-tkg

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#1506]
### If available, link to the latest build

[wine-tkg-staging.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/wine-tkg-staging.log)

### Package name

`wine-tkg-staging-fsync-git` and `wine-tkg-fsync-git`

### Latest build

`7.10.r0.g94f00cd9-327`

### Latest version available

`7.11`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

Nothing wrong in the log, because it's just the last build from 2022-06-05. It hasn't tried to build since.

**Comment by Technetium1** [comment]
@dr460nf1r3 I can't find where these are built (if they still are right now)? maybe relation to https://github.com/chaotic-aur/packages/issues/1473?
