### ISSUE TITLE
[Bug] kvantum-qt5-git fails to install

### ISSUE THREAD

**Issue by stormzyyyy** [chaotic-aur/packages#1511]
### What happens?

`kvantum-qt5-git` is unable to be upgraded/installed due to a 404 error. As seen in the picture, it fails to install even after redownloading the package database.

![pic](https://user-images.githubusercontent.com/84043891/175385418-88c20741-232c-44df-a3cc-5964627a06ec.png)

### What is expected to happen?

`kvantum-qt5-git` is upgraded/installed.

**Comment by dr460nf1r3** [comment]
This package got superceded by `kvantum-git` :)

**Comment by stormzyyyy** [comment]
Oh, alright. Thank you!

**Comment by dr460nf1r3** [comment]
The package has now been removed from the database and upgrading *should* ask to replace it with `kvantum-git`
