### ISSUE TITLE
[Outdated] linux-xanmod-tt

### ISSUE THREAD

**Issue by D0nnieD4rk0** [chaotic-aur/packages#1512]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-xanmod-tt.log

### Package name

linux-xanmod-tt

### Latest build

5.15.47-1

### Latest version available

5.15.49-1

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by Technetium1** [comment]
`5.15.49-1` is built!
