### ISSUE TITLE
[Request] pika-backup

### ISSUE THREAD

**Issue by timocapa** [chaotic-aur/packages#1514]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/pika-backup

### Utility this package has for you

selective system backups

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Took a long time:
```
real    14m0.651s
user    27m59.056s
sys     1m25.209s
```
