### ISSUE TITLE
[Remove] lokinet

### ISSUE THREAD

**Issue by FireMasterK** [chaotic-aur/packages#1515]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/lokinet

### Utility this package has for you

It is an LLARP, similar to Tor's onion routing.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Build fails:
```
-- Checking for module 'libsystemd'
--   Package 'libsystemd', required by 'virtual:world', not found
CMake Error at CMakeLists.txt:315 (message):
libsystemd not found
```
---

`/var/lib/aurbuild/x86_64/tech/build/lokinet/src/lokinet-v0.9.9/CMakeLists.txt`:

```
313 if(WITH_SYSTEMD AND (NOT ANDROID))
314   if(NOT SD_FOUND)
315     message(FATAL_ERROR "libsystemd not found")
316   endif()
317   target_link_libraries(base_libs INTERFACE PkgConfig::SD)
318   target_compile_definitions(base_libs INTERFACE WITH_SYSTEMD)
319 endif()
```

**Comment by Technetium1** [comment]
Added `python3` via interfere https://github.com/chaotic-aur/interfere/commit/e2ceb9adc86aa2f2ec62b741d64cc2feaf39b075

**Comment by Technetium1** [comment]
Link to build log: https://builds.garudalinux.org/repos/chaotic-aur/logs/lokinet.log

**Comment by majestrate** [comment]
the existing lokinet package on mainline aur is broken and will remain broken as long as the changeset we have in https://github.com/oxen-io/lokinet/tree/makepkg is not applied in full. the existing maintainer has not done this and continues to not do that as he seems to have strong opinions that make packaging a (self inflicted) nightmare for him. we have been trying to get ownership of the aur package so that it can work and arch linux users stop complaining about an issue we didn't make and can't fix (because the trust model of the aur is idiotic).

**Comment by Technetium1** [comment]
@majestrate I just tried your PKGBUILD and it failed very quickly, [the log](https://builds.garudalinux.org/repos/chaotic-aur/logs/lokinet.log) has been updated.

**Comment by majestrate** [comment]
>[?25hContainer pkg2a006bd1401 failed with error code 6.
i have no idea what this means or how your ci works.

**Comment by dr460nf1r3** [comment]
This usually indicates an issue with the PKGBUILD itself.

**Comment by dr460nf1r3** [comment]
> [https://github.com/oxen-io/lokinet/tree/makepkg](https://github.com/oxen-io/lokinet/tree/makepkg?rgh-link-date=2022-06-27T23%3A41%3A00Z) is not applied in full

What exactly do you mean by this? Building off that branch? Should be easy enough for us :) Otherwise, if there is a working PKGBUILD we might as well take it instead of using the AUR version as long as it compiles. Thanks for helping out!


> but because of me not cleaning up what I was testing with in interfere

Happened to me often enough as well :P From my personal experience its often worth checking interfere before doing further analysis 😆

**Comment by majestrate** [comment]
> > [https://github.com/oxen-io/lokinet/tree/makepkg](https://github.com/oxen-io/lokinet/tree/makepkg?rgh-link-date=2022-06-27T23%3A41%3A00Z) is not applied in full
> 
> What exactly do you mean by this? Building off that branch? Should be easy enough for us :) Otherwise, if there is a working PKGBUILD we might as well take it instead of using the AUR version as long as it compiles. Thanks for helping out!
> 
> > but because of me not cleaning up what I was testing with in interfere
> 
> Happened to me often enough as well :P From my personal experience its often worth checking interfere before doing further analysis laughing

that branch has a working pkgbuild.

**Comment by Technetium1** [comment]
https://github.com/chaotic-aur/pkgbuild-lokinet it did build!

**Comment by Technetium1** [comment]
Confirming [lokinet on AUR](https://aur.archlinux.org/packages/lokinet) builds in clean chroot now. Noticed this comment: https://github.com/oxen-io/lokinet/discussions/1823#discussioncomment-3108437.
Which one do we want to use?

**Comment by dr460nf1r3** [comment]
I'd say we should use the AUR PKGBUILD for now, as (if I understood the conversation correctly) it is written out of an Arch users perspective rather than the Lokinet team's ones. I gotta say, things got heated over there and I don't get why.

**Comment by xiota** [comment]
Dropped because AUR package is potentially compromised.  If re-added, needs to be a custom package.

Metrics 15.
