### ISSUE TITLE
[Request] zecwallet-lite

### ISSUE THREAD

**Issue by BlitDev** [chaotic-aur/packages#1516]
### Link to the package(s) in the AUR

[AUR Link](https://aur.archlinux.org/packages/zecwallet-lite)

### Utility this package has for you

This is a lightweight wallet for the anonymous cryptocurrency **ZCash**.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Build fails:
```
⨯ cannot execute  cause=exit status 127
errorOut=/home/main-builder/.cache/electron-builder/fpm/fpm-1.9.3-2.3.1-linux-x86_64/lib/ruby/bin.real/ruby: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
```
I tried to add `libxcrypt` in https://github.com/chaotic-aur/interfere/commit/608c7db7062f83ab9f083d83d7b23d3af14ed0d4 to no avail.

**Comment by BlitDev** [comment]
I will write about this error to the maintainer of the package, maybe he will do something.
In case he doesn't respond, I'll make zecwallet-lite-bin.

**Comment by Technetium1** [comment]
Here's the full build log: https://builds.garudalinux.org/repos/chaotic-aur/logs/zecwallet-lite.log

**Comment by Technetium1** [comment]
We got further this time!

**Comment by xiota** [comment]
Commented on AUR page to notify maintainer of issues:

* Fails to build ([log](https://builds.garudalinux.org/repos/chaotic-aur/logs/zecwallet-lite.log))
* Out of date.  Package version is 1.7.13.  Current upstream version is 1.8.8.
