### ISSUE TITLE
[Bug] themix-icons-papirus-git-20220606.r61.g971ddc90a3-1 is corrupted

### ISSUE THREAD

**Issue by cgcgcgcgcg** [chaotic-aur/packages#1517]
### What happens?

```
:: File /var/cache/pacman/pkg/themix-icons-papirus-git-20220606.r61.g971ddc90a3-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (checksum)).
Do you want to delete it? [Y/n] 
```

### What is expected to happen?

Work?

**Comment by cgcgcgcgcg** [comment]
Disabled chaotic-aur temporarily, installed themix-icons-papirus-git package from Aur, enabled chaotic-aur again, and other packages updated normally.

**Comment by Technetium1** [comment]
It's [bumped](https://github.com/chaotic-aur/interfere/commit/610321e8b009caa83d7d7d41ad5b875314376d48#diff-acda3a66e1f15a258e2d7c66274a579f3e77ce846d9358b43f611ab39f0ae9f2R98)!
