### ISSUE TITLE
[Bug] the package linux-xanmod-anbox does not contain anbox modules

### ISSUE THREAD

**Issue by mdhishamsayed** [chaotic-aur/packages#1518]
### What happens?

so, first things first, how can you build the anbox modules when they are not working??
the current modules by @choff are not working on 5.18 kernel..
so first i request you to add this package to the interface and correct
https://gitlab.com/liyalinux/anbox-modules-dkms
this is fixed version for v5.18 kernel
even in 5.17 kernel it did not have the modules installed by default, had to install them manually

### What is expected to happen?

the anbox modules should be present in the linux-xanmod-anbox packag, but they are not present and have to be added ashmem and binder modules with the package anbox-modules-dkms which only builds on few kernels..

**Comment by dr460nf1r3** [comment]
Might help? https://forum.garudalinux.org/t/failed-to-load-anbox-required-ashmem-binder-modules-with-zen-kernel/20117/8?u=dr460nf1r3

**Comment by mdhishamsayed** [comment]
@dr460nf1r3 waydroid is different than anbox and anbox did not have any commits since 2021 october..

**Comment by dr460nf1r3** [comment]
Well, it was just a suggestion. This sounds more like a PKGBUILD issue rather than one with our build tools. After all, we build the package straight from AUR - might be very worth reporting this to the package maintainer instead :)

**Comment by mdhishamsayed** [comment]
The Issue is closed, Anbox reached EOS, that package has been removed, ashmem and binder modules are now unusable
