### ISSUE TITLE
[Request] lightlyshaders-git

### ISSUE THREAD

**Issue by Smart123s** [chaotic-aur/packages#1521]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/lightlyshaders-git

### Utility this package has for you

Round corners and outline effect for KWin

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Build failed, and I don't know what dependency is missing. https://builds.garudalinux.org/repos/chaotic-aur/logs/lightlyshaders-git.log

**Comment by Technetium1** [comment]
I left [a comment](https://aur.archlinux.org/packages/lightlyshaders-git#comment-872029) on the AUR page.

**Comment by xiota** [comment]
Dropping because not updated for KF6.
