### ISSUE TITLE
[Request] linux-nitrous

### ISSUE THREAD

**Issue by D0nnieD4rk0** [chaotic-aur/packages#1522]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/linux-nitrous

### Utility this package has for you

I've been using xanmod for a while now but lately its been a little faulty. so far from all the custom kernels none are as good as xanmod in terms of performance so i went looking for alternatives and found linux-nitrous which looks interesting.
the dev does have his own repo ... but he only compiles x86_64 V3 which my hardware doesnt support :(

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by mdhishamsayed** [comment]
@D0nnieD4rk0 does this perform better than xanmod or same??
and what are the issues did u face with xanmod??

**Comment by D0nnieD4rk0** [comment]
> @D0nnieD4rk0 does this perform better than xanmod or same?? and what are the issues did u face with xanmod??

when i boot up xanmod sometimes it just reboots itself right after and the most annoying issue is that sound for some reason just doesnt work
i use xanmod-tt and no i dont have this issue with other kernels
