### ISSUE TITLE
[Outdated] neovide-bin

### ISSUE THREAD

**Issue by Mine-Ranger** [chaotic-aur/packages#1523]
### Package name

neovide-bin

### Latest build

0.7.0-3

### Latest version available

0.8.0-1

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

This package is marked out of date in the aur but can be replaced by the "neovide" package in the (aur) instead

**Comment by Technetium1** [comment]
@PR454D do you mind me switching this package over to [neovide](https://aur.archlinux.org/packages/neovide)?

**Comment by PR454D** [comment]
@Technetium1 no, go ahead
