### ISSUE TITLE
[Outdated] latte-dock-git

### ISSUE THREAD

**Issue by rejedai** [chaotic-aur/packages#1524]
### Package name

latte-dock-git

### Latest build

0.10.6.r260.g899c0155-1

### Latest version available

0.10.77.r5953.899c0155-1

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by dr460nf1r3** [comment]
The commit hash at the end of the pkgver is the same, so it's using the same commit to build Latte dock from. So it's not a problem, it's probably just using another method to set the version.

**Comment by xiota** [comment]
Request to modify the latte-dock-git interfere [PKGBUILD.append](https://github.com/chaotic-aur/interfere/blob/master/latte-dock-git/PKGBUILD.append) to realign the version string.

Right now, aur/latte-dock-git is 0.10.6.r331.g7564e0ee-1, while community/latte-dock is at 0.10.9.  The last official release was 0.10.8, but there seems to have been a silent release in Nov 2022.  The following change will produce the version string 0.10.9.r33.g7564e0ee.
````
pkgver() {
  cd "latte-dock"

  local _release_version="0.10.9"
  local _release_commit="1d468a94e931d684f1ec180584eaa1d25765f100"

  printf "$_release_version.r%s.g%s" \
    "$(git rev-list --count $_release_commit..HEAD)" \
    "$(git rev-parse --short HEAD)"
}
````
Manual intervention will be needed to keep the versions aligned, but releases are not too frequent.  Even if not updated, the string would still be less out of sync than now.

**Comment by dr460nf1r3** [comment]
https://github.com/chaotic-aur/interfere/commit/4c32eeec62222ba31493a3152501e1c3fbed6c0a

**Comment by Pakrohk** [comment]
failed to prepare transaction (could not satisfy dependencies)
:: installing plasma-framework5 (5.111.0-1) breaks dependency 'plasma-framework' required by latte-dock-git
:: installing knewstuff5 (5.111.0-1) breaks dependency 'knewstuff' required by latte-dock-git
 -> error installing repo packages

**Comment by xiota** [comment]
@Pakrohk A lot of packages will be affected by the name changes.  Nothing to do on this side until after the AUR package is updated.  If you still don't see the package in the repo about a day after the AUR package is updated, you can comment again here.
