### ISSUE TITLE
[Remove] superproductivity-bin

### ISSUE THREAD

**Issue by nandgator** [chaotic-aur/packages#1526]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/superproductivity-bin

### Utility this package has for you

Task management

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Fails to build because source 404.  Upstream dev is also aur package maintainer.

**Comment by Technetium1** [comment]
> [alosarjos](https://aur.archlinux.org/account/alosarjos) commented on [2026-08-30 16:37 (EDT)](https://aur.archlinux.org/packages/superproductivity-bin#comment-1083522):
This package wont be any longer maintained by the App creator.
This decision comes after the creation of a version maintained by Arch Official Maintainers: https://archlinux.org/packages/extra/x86_64/super-productivity/
