### ISSUE TITLE
[Outdated] ffmpeg-full

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#1527]
### If available, link to the latest build

[ffmpeg-full.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/ffmpeg-full.log)

### Package name

`ffmpeg-full`

### Latest build

`None`

### Latest version available

`5.0.1-2`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

Adding missing deps in https://github.com/chaotic-aur/packages/commit/e2072dd61dca0b0b8c9732e76803278bba06ee27 but `python-pocketsphinx-git` still won't build: [python-pocketsphinx-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/python-pocketsphinx-git.log)

**Comment by Technetium1** [comment]
Build fails in a clean chroot on my machine with the same error. Where is `autogen.sh` supposed to be?

**Comment by SolarAquarion** [comment]
It's fixed via my dropping of python-pocketsphinx-git

**Comment by Technetium1** [comment]
`opt/cuda/bin/nvcc` is provided by `cuda`, which is installed.
