### ISSUE TITLE
[Request] freenet

### ISSUE THREAD

**Issue by BlitDev** [chaotic-aur/packages#1528]
### Link to the package(s) in the AUR

[Freenet AUR Package](https://aur.archlinux.org/packages/freenet)

### Utility this package has for you

**Freenet** allows you to surf Javascript-**free** sites, distribute **files**. **E-mail** and other plugins are also **supported**.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

**Freenet** is a quite **popular** anonymous network. Now the package has **181 votes**.

**Comment by xiota** [comment]
Dropping because fails to build (inappropriate git commands in prepare).  Also, package is misnamed.  Should be hyphanet.

**Comment by Technetium1** [comment]
Wow, I never knew they changed the name! https://news.ycombinator.com/item?id=36561663
