### ISSUE TITLE
[Request] paru-bin

### ISSUE THREAD

**Issue by alimirrajei** [chaotic-aur/packages#1529]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/paru-bin

### Utility this package has for you

Feature packed AUR helper

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by dr460nf1r3** [comment]
We do have `paru` and `paru-git` available already.
