### ISSUE TITLE
[Request] tenacity-git

### ISSUE THREAD

**Issue by AriaMoradi** [chaotic-aur/packages#1533]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/tenacity-git/

### Utility this package has for you

Audacity is one of the most popular audio editing tools, it's late fork tenacity provides the same features but without the telemetry.
The original Audacity on Arch repos is too old, and building tenacity requires building `wxWidgets` as well which results in big downloads of source and big build time.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

It seems that the package used to be in the repo but was removed at some point.

**Comment by Technetium1** [comment]
Needs a specific version of `wxgtk3`:
```error: target not found: wxgtk3-3.1.5```
[tenacity-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/tenacity-git.log)
Note about compatibility with latest version on package: https://aur.archlinux.org/packages/tenacity-git#comment-861523

**Comment by Technetium1** [comment]
Added `python` in https://github.com/chaotic-aur/interfere/commit/c9facb53eba51049f5c9f41699ff1dc92be42fa4 for documentation generation. Commented on AUR [here](https://aur.archlinux.org/packages/tenacity-git#comment-873457).

**Comment by xiota** [comment]
Dropping because fails to build.  When requested, there was no stable release.  Now `extra/tenacity` is available.

**Comment by FabioLolix** [comment]
> Dropping because fails to build

I guess you are refferring to 

```
Your package tenacity-git [1] has been flagged out-of-date by xiota
[2]:

Fails to build.
```
/home/builder/build/PKGBUILD: line 47: cd: images/icons: No such file
or directory
```

[1] https://aur.archlinux.org/pkgbase/tenacity-git/
[2] https://aur.archlinux.org/account/xiota/
```

Which was an issue on your end

https://aur.archlinux.org/packages/tenacity-git#comment-989036

images/icons is there upstream and untouched since 7 months

https://github.com/FabioLolix/buildlogs/commit/a60a45d4bf4124405a809b7a1f795e73379109a6

**Comment by xiota** [comment]
That looks like an old flag.  Tenacity had [pipeline failure](https://ci.codeberg.org/repos/10751/pipeline/1693/1) two weeks ago, with subsequent sporadic failures.

Regardless, users are advised to switch to `extra/tenacity`.

**Comment by FabioLolix** [comment]
> That looks like an old flag

That was on 02/09/24 which is about 2 weeks ago, made by you

Also that problem is not happening with devtools

> [pipeline failure](https://ci.codeberg.org/repos/10751/pipeline/1693/1) two weeks ago, with subsequent sporadic failures.

Quite normal with VCS pkgbuilds, Anyway is fine

**Comment by xiota** [comment]
Lately, my threshold to drop packages has been lower to prepare for transition to v4 builder.  Unfortunately, logs on v4 builder aren't retained very long, so cannot check what actually happened.  @dr460nf1r3 Possible to save logs longer?

But it doesn't matter much in this case.  When the package was initially added, there was no stable version.  Now there is.

Will eventually screen for other packages that are no longer needed to fill an availability gap.  (Package count inflation must be brought down to manageable levels.)

**Comment by Technetium1** [comment]
@FabioLolix I don't understand why you did your PKGBUILD so different from `tenacity`. Why not [keep prepare clean](https://gitlab.archlinux.org/archlinux/packaging/packages/tenacity/-/blob/main/PKGBUILD?ref_type=heads) and move it to build? Does it have to be there in the first place? Why is your submodule init different?

**Comment by FabioLolix** [comment]
> Lately, my threshold to drop packages has been lower to prepare for transition to v4 builder.

Understandable

> I don't understand why you did your PKGBUILD so different from tenacity

>Why is your submodule init different?

tenacity-git exist since well before before tenacity stable was on AUR or Arch, no one reached to make it different 

Submodules can be configured in several ways, I'm aware other commands exist since I have seen them on other pkgbuild but don't remember which so I use what I know

> Why not [keep prepare clean](https://gitlab.archlinux.org/archlinux/packaging/packages/tenacity/-/blob/main/PKGBUILD?ref_type=heads) and move it to build?

IMO fixing the png icons in prepare() is fitting, this was added by one of the former co-maintainers and I don't a compelling reason to move it

> Does it have to be there in the first place?

Seems it it still relevant
