### ISSUE TITLE
[Bug] spotify-tray-git

### ISSUE THREAD

**Issue by Zbysiu3cytryny** [chaotic-aur/packages#1534]
### What happens?

Pacman aborts with an error, while installing spotify-tray-git

### What is expected to happen?

Pacman downloads installs package without issue.

### If possible, please attach logs

[zbysiu@komp ~]$ sudo pacman -S spotify-tray-git
[sudo] hasło użytkownika zbysiu: 
rozwiązywanie zależności…
szukanie sprzecznych pakietów...

Pakiety (1) spotify-tray-git-1.3.2.r3.g989e9a1-1

Do pobrania:        0,01 MiB
Do zainstalowania:  0,03 MiB

:: Kontynuować instalację? [T/n] t
:: Pobieranie pakietów…
 spotify-tray-git-1.3.2.r3.g989e9a1-1-x86_64.pkg.tar.zst failed to download
błąd:  nie udało się pobrać pliku 'spotify-tray-git-1.3.2.r3.g989e9a1-1-x86_64.pkg.tar.zst' z geo-mirror.chaotic.cx : Maximum file size exceeded
błąd:  nie udało się pobrać pliku 'spotify-tray-git-1.3.2.r3.g989e9a1-1-x86_64.pkg.tar.zst' z cdn-mirror.chaotic.cx : Maximum file size exceeded
błąd:  nie udało się pobrać pliku 'spotify-tray-git-1.3.2.r3.g989e9a1-1-x86_64.pkg.tar.zst' z us-ut-mirror.chaotic.cx : Maximum file size exceeded
błąd:  nie udało się pobrać pliku 'spotify-tray-git-1.3.2.r3.g989e9a1-1-x86_64.pkg.tar.zst' z es-mirror.chaotic.cx : Maximum file size exceeded
błąd:  nie udało się pobrać pliku 'spotify-tray-git-1.3.2.r3.g989e9a1-1-x86_64.pkg.tar.zst' z es-2-mirror.chaotic.cx : Maximum file size exceeded
błąd:  nie udało się pobrać pliku 'spotify-tray-git-1.3.2.r3.g989e9a1-1-x86_64.pkg.tar.zst' z de-mirror.chaotic.cx : Maximum file size exceeded
błąd:  nie udało się pobrać pliku 'spotify-tray-git-1.3.2.r3.g989e9a1-1-x86_64.pkg.tar.zst' z de-2-mirror.chaotic.cx : Maximum file size exceeded
błąd:  nie udało się pobrać pliku 'spotify-tray-git-1.3.2.r3.g989e9a1-1-x86_64.pkg.tar.zst' z de-3-mirror.chaotic.cx : Maximum file size exceeded
błąd:  nie udało się pobrać pliku 'spotify-tray-git-1.3.2.r3.g989e9a1-1-x86_64.pkg.tar.zst' z de-4-mirror.chaotic.cx : Maximum file size exceeded
błąd:  nie udało się pobrać pliku 'spotify-tray-git-1.3.2.r3.g989e9a1-1-x86_64.pkg.tar.zst' z fr-mirror.chaotic.cx : Maximum file size exceeded
błąd:  nie udało się pobrać pliku 'spotify-tray-git-1.3.2.r3.g989e9a1-1-x86_64.pkg.tar.zst' z br-mirror.chaotic.cx : Maximum file size exceeded
błąd:  nie udało się pobrać pliku 'spotify-tray-git-1.3.2.r3.g989e9a1-1-x86_64.pkg.tar.zst' z kr-mirror.chaotic.cx : Maximum file size exceeded
błąd:  nie udało się pobrać pliku 'spotify-tray-git-1.3.2.r3.g989e9a1-1-x86_64.pkg.tar.zst' z bg-mirror.chaotic.cx : Maximum file size exceeded
błąd:  nie udało się pobrać pliku 'spotify-tray-git-1.3.2.r3.g989e9a1-1-x86_64.pkg.tar.zst' z ca-mirror.chaotic.cx : Maximum file size exceeded
błąd:  nie udało się pobrać pliku 'spotify-tray-git-1.3.2.r3.g989e9a1-1-x86_64.pkg.tar.zst' z in-mirror.chaotic.cx : Maximum file size exceeded
błąd:  nie udało się pobrać pliku 'spotify-tray-git-1.3.2.r3.g989e9a1-1-x86_64.pkg.tar.zst' z in-2-mirror.chaotic.cx : Maximum file size exceeded
błąd:  nie udało się pobrać pliku 'spotify-tray-git-1.3.2.r3.g989e9a1-1-x86_64.pkg.tar.zst' z sg-mirror.chaotic.cx : Maximum file size exceeded
ostrzeżenie: nie udało się pobrać niektórych plików
błąd:  nie udało się dokonać transakcji (błąd pobierania biblioteki)
Wystąpiły błędy, nie zaktualizowano żadnego pakietu.
[zbysiu@komp ~]$ 

### More information

sorry for using Polish language

**Comment by Zbysiu3cytryny** [comment]
fixed?

**Comment by Technetium1** [comment]
@Zbysiu3cytryny yes, it should be!

**Comment by Zbysiu3cytryny** [comment]
> @Zbysiu3cytryny yes, it should be!

I am not sure,because pacman show me a error 403

**Comment by Zbysiu3cytryny** [comment]
`[zbysiu@komp ~]$ sudo pacman -S spotify-tray-git
[sudo] hasło użytkownika zbysiu: 
rozwiązywanie zależności…
szukanie sprzecznych pakietów...

Pakiety (1) spotify-tray-git-1.3.2.r3.g989e9a1-1

Do zainstalowania:  0,03 MiB

:: Kontynuować instalację? [T/n] t
:: Pobieranie pakietów…
 spotify-tray-git-1.3.2.r3.g989e9a1-1-x86_64 is up to date
błąd:  nie udało się pobrać pliku 'spotify-tray-git-1.3.2.r3.g989e9a1-1-x86_64.pkg.tar.zst' z geo-mirror.chaotic.cx : The requested URL returned error: 404
błąd:  nie udało się pobrać pliku 'spotify-tray-git-1.3.2.r3.g989e9a1-1-x86_64.pkg.tar.zst' z cdn-mirror.chaotic.cx : The requested URL returned error: 404
błąd:  nie udało się pobrać pliku 'spotify-tray-git-1.3.2.r3.g989e9a1-1-x86_64.pkg.tar.zst.sig' z mirror.theash.xyz : The requested URL returned error: 404
ostrzeżenie: nie udało się pobrać niektórych plików
błąd:  nie udało się dokonać transakcji (nie udało się odzyskać niektórych plików)
Wystąpiły błędy, nie zaktualizowano żadnego pakietu.`

**Comment by Zbysiu3cytryny** [comment]
Sorry, with sudo pacman -Syu spotify-tray-git
is working fine!
Thanks!

**Comment by dr460nf1r3** [comment]
Always update the database before trying to install a package :) the version changed as I bumped it 😊

**Comment by Zbysiu3cytryny** [comment]
Simple thing, but i forgot about it :)
