### ISSUE TITLE
[Request] yt-dlg

### ISSUE THREAD

**Issue by Zbysiu3cytryny** [chaotic-aur/packages#1538]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/yt-dlg

### Utility this package has for you

easy to use, gui version of yt-dl

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Zbysiu3cytryny** [comment]
Thanks for add to repo :smile:

**Comment by Technetium1** [comment]
Thanks for requesting!
