### ISSUE TITLE
[Request] reactgame

### ISSUE THREAD

**Issue by BlitDev** [chaotic-aur/packages#1540]
### Link to the package(s) in the AUR

[Link to AUR](https://aur.archlinux.org/packages/reactgame)

### Utility this package has for you

Sources: https://codeberg.org/BlitDev/ReactGame
I made PKGBUILD for my simple game, maybe it will help someone to spend time.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, it's useful only for me.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

**Size after build**: 40 KiB.

**Comment by xiota** [comment]
Dropping because has wrong deps, AUR package unmaintained, and metrics show no usage.
