### ISSUE TITLE
[Request] zulucrypt

### ISSUE THREAD

**Issue by BlitDev** [chaotic-aur/packages#1541]
### Link to the package(s) in the AUR

[AUR Package](https://aur.archlinux.org/packages/zulucrypt)

### Utility this package has for you

I think zuluCrypt can be considered an alternative to VeraCrypt. It allows you to create encrypted volumes and encrypt files.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

**Size after build**: 1.8 MiB

**Comment by xiota** [comment]
Added custom package `zulucrypt-qt6`.

`aur/zulucrypt` is still using Qt5.  Metrics 92.

**Comment by xiota** [comment]
Dropping Qt5 variant.

Metrics:

* zulucrypt # 58
* zulucrypt-qt6 # 7
