### ISSUE TITLE
[Request] salad-git

### ISSUE THREAD

**Issue by fwookerton** [chaotic-aur/packages#1546]
### Link to the package(s) in the AUR

[https://aur.archlinux.org/packages/salad-git](https://aur.archlinux.org/packages/salad-git)

### Utility this package has for you

Allows gamers to mine crypto in their downtime, to obtain rewards from it.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

MIT License

**Comment by xiota** [comment]
According to this [comment](https://aur.archlinux.org/packages/salad#comment-868345), Salad ≥ 1.0 does not support Linux.

**Comment by fwookerton** [comment]
Would there be a mention of this in the rejected packages section?

**Comment by xiota** [comment]
The reason for rejecting is documented here, and anyone making package requests is supposed to check for existing requests.  If the developers wish to support Linux in the future, the package could be reconsidered.

**Comment by fluffeon** [comment]
> The reason for rejecting is documented here, and anyone making package requests is supposed to check for existing requests.  If the developers wish to support Linux in the future, the package could be reconsidered.

This package was updated to 1.0.

**Comment by fluffeon** [comment]
@xiota

**Comment by fluffeon** [comment]
nvm i read it wrong ignore the ping
