### ISSUE TITLE
[Outdated] wine-tkg-staging-fsync-git

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#1547]
### If available, link to the latest build

[wine-tkg-staging.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/wine-tkg-staging.log)

### Package name

`wine-tkg-staging-fsync-git`

### Latest build

`7.11.r2.ga51c679f-327`

### Latest version available

`7.12`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

There's some hotfixer errors in the last log, but I think those have been resolved by now. Sure hope I'm not wrong.

**Comment by dr460nf1r3** [comment]
For some reason the wine-tkg routine stalls right after the beginning, no matter on what builder. Looks like a toolbox issue that has to be investigated.

**Comment by niobium93** [comment]
Any progress on this? We're up to `7.13` now.

**Comment by Technetium1** [comment]
Maybe related to #1574?

**Comment by niobium93** [comment]
I don't think so? [Looks like the script doesn't even run.](https://builds.garudalinux.org/repos/chaotic-aur/logs/wine-tkg-staging.log)

**Comment by Technetium1** [comment]
@niobium93 The routine hangs and fails. Marked relation because I'm suspecting a toolbox issue.

**Comment by VexfulNiko** [comment]
Any updates?

**Comment by Technetium1** [comment]
The toolbox issue has since been fixed by disabling bcachefs temporarily, and the upstream issue about bcachefs leading 0s was fixed too, leading to a revert of the temporary toolbox patch. I just manually triggered the routine and it fails like this:
```
$ chaotic routine tkg-wine
3932642 (process ID) old priority 0, new priority 19
[!] Deleting:

[!] Total: 0
Skipping config file that was not found
Syncing interfere...
HEAD is now at cc95508 glaxnimate-git missing clang
Cleaning pre-existent routine directory.
Invalid package directory.
Invalid package directory.
grep: ./*.log: No such file or directory
grep: ./*.log: No such file or directory
grep: ./*.log: No such file or directory
Cloning into '_repo'...
remote: Enumerating objects: 15655, done.
remote: Counting objects: 100% (228/228), done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 15655 (delta 144), reused 185 (delta 129), pack-reused 15427
Receiving objects: 100% (15655/15655), 13.00 MiB | 16.16 MiB/s, done.
Resolving deltas: 100% (11922/11922), done.
Building: ./chaotic-staging.cfg ./chaotic-upstream.cfg
mkdir: cannot create directory 'wine-tkg-git.0001': File exists
```

**Comment by dr460nf1r3** [comment]
> mkdir: cannot create directory 'wine-tkg-git.0001': File exists

This can be solved by clearing the routine directory, however after that the build still stalls. Its still unclear why this happens exactly.

**Comment by Technetium1** [comment]
> This can be solved by clearing the routine directory

Why does the [routine](https://github.com/chaotic-aur/toolbox/blob/main/src/lib/routines-tkg-wine.sh) not do that if it's required? Just noticed that the [service](https://github.com/chaotic-aur/toolbox/blob/main/services/chaotic-tkg-wine.service) sets the working dir to `/tmp`… and I did not.

**Comment by Technetium1** [comment]
https://github.com/chaotic-aur/interfere/blob/master/wine-tkg/prepare :eyes:

**Comment by dr460nf1r3** [comment]
> Why does the [routine](https://github.com/chaotic-aur/toolbox/blob/main/src/lib/routines-tkg-wine.sh?rgh-link-date=2022-08-29T13%3A04%3A31Z) not do that if it's required? Just noticed that the [service](https://github.com/chaotic-aur/toolbox/blob/main/services/chaotic-tkg-wine.service?rgh-link-date=2022-08-29T13%3A04%3A31Z) sets the working dir to `/tmp`… and I did not.

In this case the routine would lock up indefinitely, so it can't clean the directory afterwards.



> [chaotic-aur/interfere@`master`/wine-tkg/prepare](https://github.com/chaotic-aur/interfere/blob/master/wine-tkg/prepare?rgh-link-date=2022-10-08T06%3A13%3A15Z) 

Interesting find! Sadly it doesn't have any influence on whether our bug occurs or not, I just verified that 🤔

**Comment by niobium93** [comment]
It built! `7.20.r3.g49ed7ae4-327` is now in the repo. Guess I'll close this then.
