### ISSUE TITLE
[Request] budgie-control-center, budgie-screenshot-applet and budgie-network-applet

### ISSUE THREAD

**Issue by Heus-Sueh** [chaotic-aur/packages#1548]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/budgie-control-center
https://aur.archlinux.org/packages/budgie-screenshot-applet
https://aur.archlinux.org/packages/budgie-network-applet

### Utility this package has for you

to make arch linux with budgie desktop

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
`budgie-control-center` was added from #1553
