### ISSUE TITLE
[Request] dwarfs

### ISSUE THREAD

**Issue by Rrauros** [chaotic-aur/packages#1549]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/dwarfs
https://aur.archlinux.org/packages/dwarfs-git
https://aur.archlinux.org/packages/dwarfs-bin

### Utility this package has for you

It is one of the high compress/fast file system. It is actually very useful and looks better than squasfs and zpaq. 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropped `dwarfs-git` because broken and stable `dwarfs` has reasonably frequent releases.

**Comment by xiota** [comment]
Re-added `dwarfs-git` because package was updated.

Metrics for dwarfs, 486.
