### ISSUE TITLE
[Request] session-desktop-bin

### ISSUE THREAD

**Issue by BlitDev** [chaotic-aur/packages#1551]
### Link to the package(s) in the AUR

[AUR Package](https://aur.archlinux.org/packages/session-desktop-bin)

### Utility this package has for you

[Official site](https://getsession.org/)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

**Size after build**: 96.4 MiB

**Comment by xiota** [comment]
Dropping because uses EOL Electron/25.8.4.  Metrics 53.
