### ISSUE TITLE
[Request] lazydocker

### ISSUE THREAD

**Issue by BlitDev** [chaotic-aur/packages#1556]
### Link to the package(s) in the AUR

[AUR Package](https://aur.archlinux.org/packages/lazydocker)

### Utility this package has for you

Simple Docker management tui
![image](https://user-images.githubusercontent.com/79034202/178207405-c3b5bc3b-a17c-4df0-8f76-b4a1e04b081d.png)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

**Size after build:** 3.9 MiB

**Comment by xiota** [comment]
Dropped because moved to extra.  Metrics 287.
