### ISSUE TITLE
[Request] pfetch

### ISSUE THREAD

**Issue by BlitDev** [chaotic-aur/packages#1562]
### Package

https://aur.archlinux.org/packages/pfetch

### Purpose

Fastfetch for those who want to save 2 nanoseconds and 7 kilobytes of RAM (stable release)
![image](https://user-images.githubusercontent.com/79034202/178210643-6d35174f-f265-44d6-a70d-64760931d960.png)

Size after build: 20 KiB

### License

MIT

**Comment by xiota** [comment]
Dropped because unmaintained.

Metrics:

* pfetch # 992
* pfetch-git # 6

**Comment by FabioLolix** [comment]
> Dropped because unmaintained.

Last commit was 2 months ago with no unresolved issues or PR  https://github.com/Un1q32/pfetch

**Comment by xiota** [comment]
Will re-add.  I missed that `pfetch` had switched to different repo.
