### ISSUE TITLE
[Request] openoffice-bin

### ISSUE THREAD

**Issue by BlitDev** [chaotic-aur/packages#1564]
### Link to the package(s) in the AUR

[AUR Package](https://aur.archlinux.org/packages/openoffice-bin)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

**Size after build:** 150.0 MiB

**Comment by Technetium1** [comment]
Are you sure you wish to request this even though `libreoffice-fresh` is available? https://www.libreoffice.org/discover/libreoffice-vs-openoffice/

**Comment by BlitDev** [comment]
> 

Sorry, I've been going through all my AUR packages looking for ones to upload to chaotic and didn't notice that LibreOffice is already in the Arch Linux repositories.
