### ISSUE TITLE
[Request] kotatogram-desktop-bin

### ISSUE THREAD

**Issue by BlitDev** [chaotic-aur/packages#1565]
### Link to the package(s) in the AUR

[AUR Package](https://aur.archlinux.org/packages/kotatogram-desktop-bin)

### Utility this package has for you

There are already unstable versions of Kotatogram, but the most popular package is missing.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

**Size after build:** 78.5 MiB

![image](https://user-images.githubusercontent.com/79034202/178213098-5087fd56-d4ce-4bac-a144-2c87b54a29d3.png)
It seems like there is an issue for this package, but the package itself is not in the repositories, so I created it again.

**Comment by Technetium1** [comment]
I would recommend `kotatogram-desktop-beta-dynamic-bin` since it's always on the latest release on GitHub built by their CI. I've not experienced any stability issues with it whatsoever. Do you still want the stable version?

**Comment by BlitDev** [comment]
> I would recommend `kotatogram-desktop-beta-dynamic-bin` since it's always on the latest release on GitHub built by their CI. I've not experienced any stability issues with it whatsoever. Do you still want the stable version?

I'm not sure, but I'm using the stable version and it definitely works fine.
