### ISSUE TITLE
[Request] plasma5-applets-virtual-desktop-bar-git

### ISSUE THREAD

**Issue by ZingyTomato** [chaotic-aur/packages#1569]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/plasma5-applets-virtual-desktop-bar-git

### Utility this package has for you

A plasma 5 applet to create virtual desktops.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because does not support KF6.
