### ISSUE TITLE
[Request] zramswap

### ISSUE THREAD

**Issue by ZingyTomato** [chaotic-aur/packages#1571]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/zramswap

### Utility this package has for you

Sets up zram-based swap devices on boot

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by dr460nf1r3** [comment]
Hey :) We do have `zram-generator` available in Arch repos already, it pretty much does the same thing and is a better application for this purpose as it integrates well with Systemd.
https://github.com/systemd/zram-generator

**Comment by ZingyTomato** [comment]
Yeah but this one is much easier to setup then that imo. Just need to enable the service and that's all.

**Comment by Technetium1** [comment]
Is [this comment](https://aur.archlinux.org/packages/zramswap#comment-773153) implying something has been wrong for almost 3 years?

**Comment by ZingyTomato** [comment]
> Is [this comment](https://aur.archlinux.org/packages/zramswap#comment-773153) implying something has been wrong for almost 3 years?

I don't know, it works fine for me...

Anyways feel free to close this issue if you don't wanna add it. I'll try requesting another pkg.

**Comment by Technetium1** [comment]
Thanks for requesting, just wanted to be sure it was working as expected. Don't want to add a broken package!
