### ISSUE TITLE
[Request] ff2mpv-native-messaging-host-git

### ISSUE THREAD

**Issue by ZingyTomato** [chaotic-aur/packages#1573]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/ff2mpv-native-messaging-host-git

### Utility this package has for you

Basically allows you to play any link in mpv using the firefox context menu. Requires this addon https://addons.mozilla.org/en-US/firefox/addon/ff2mpv/ + the aur pkg to work.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Hopefully my last package request :sweat_smile: Just trying to request all the aur packages that I use here.

**Comment by Technetium1** [comment]
Keep them coming if you've got more :)
