### ISSUE TITLE
[Outdated] linux-tkg* kernel packages family

### ISSUE THREAD

**Issue by AlexKurisu** [chaotic-aur/packages#1574]
### If available, link to the latest build

[linux-tkg-cfs-generic_v3](https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-tkg-cfs-generic_v3.log)
[linux-tkg-bmq](https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-tkg-bmq.log)

### Package name

`linux-tkg-cfs-generic_v3`

### Latest build

`5.18.9-263`

### Latest version available

`5.18.11`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by dr460nf1r3** [comment]
There are ongoing investigations about an issue with recent kernel builds. [here](https://github.com/Frogging-Family/linux-tkg/issues/550) the corresponding issue at TKG's repo 😊

**Comment by qumaciel** [comment]
linux-tkg* was updated yesterday or the day before.
The wrong format for /proc/meminfo was fixed?

**Comment by Technetium1** [comment]
https://github.com/chaotic-aur/toolbox/pull/53 related

**Comment by dr460nf1r3** [comment]
It turned out, bcachefs was responsible for the wrong meminfo values. Thanks to @ptr1337 for finding out! 

https://github.com/chaotic-aur/toolbox/pull/55

**Comment by logan2611** [comment]
This seems to have been fixed a while ago, could this get reenabled please?

**Comment by dr460nf1r3** [comment]
Any source for this claim? I'd rather be very sure about this before rolling out bcachfs again :)

**Comment by logan2611** [comment]
https://github.com/Frogging-Family/linux-tkg/issues/550#issuecomment-1214451246

**Comment by dr460nf1r3** [comment]
Re-enabling it in https://github.com/chaotic-aur/toolbox/pull/56.
