### ISSUE TITLE
[Bug] gamescope-git compiled against glibc 2.34

### ISSUE THREAD

**Issue by ZombieBear** [chaotic-aur/packages#1578]
### What happens?

The gamescope-git package is compiled against glibc 2.34 which is newer than 2.33-5, the latest  available verions in  the repos, including AUR and chaotic AUR

### What is expected to happen?

Update build package to compile against a supported version of glibc

### If possible, please attach logs

gamescope: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by gamescope)
gamescope: /usr/lib/libc.so.6: version `GLIBC_2.34' not found (required by gamescope)

**Comment by Technetium1** [comment]
Should be fine now https://github.com/chaotic-aur/interfere/commit/3a93b3067d1c64567763abc8e563f071bffc1ac6

**Comment by ZombieBear** [comment]
Unfortunately the issue appears to persist; I just reupdated to the version on the package and am receiving the exact same messages

**Comment by Technetium1** [comment]
@ZombieBear https://github.com/chaotic-aur/interfere/commit/a901e077c6f9ddf9d28df5e614c1b29b15b6ec5d It's now built against `glibc 2.35-6`. Please comment if this issue persists.
