### ISSUE TITLE
[Outdated] natron-compositor

### ISSUE THREAD

**Issue by a61kt** [chaotic-aur/packages#1580]
### If available, link to the latest build

https://aur.archlinux.org/packages/natron-compositor

### Package name

natron-compositor

### Latest build

`2.4.2-1.1`

### Latest version available

`2.4.3`

### Have you tested if the package builds in a clean chroot?

- [X] Yes

**Comment by Technetium1** [comment]
I'm still missing something: https://builds.garudalinux.org/repos/chaotic-aur/logs/natron-compositor.log

**Comment by Technetium1** [comment]
Tried adding `shiboken` to makedepends to fix this since it provides `shiboken.h`, but no change:
```
../../Engine/NatronEngine/animatedparam_wrapper.cpp:10:10: fatal error: shiboken.h: No such file or directory
   10 | #include <shiboken.h> // produces many warnings
      |          ^~~~~~~~~~~~

```

**Comment by Technetium1** [comment]
I guess one of the optional dependencies wasn't so optional, because it builds now? :eyes:
