### ISSUE TITLE
[Request] system76-power

### ISSUE THREAD

**Issue by timescam** [chaotic-aur/packages#1585]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/system76-power

### Utility this package has for you

managing graphics and power profiles

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropped optional dkms modules.  They have low usage and at least one fails to build with maintenance issues on AUR.

Leaving `system76-power` alone, but may drop in future.  Users should consider switching to `extra/power-profiles-daemon`.

Metrics:

* system76-acpi-dkms # 12
* system76-dkms-git # 9
* system76-io-dkms # 5
* system76-power # 143
