### ISSUE TITLE
[Remove] lbry-desktop-git

### ISSUE THREAD

**Issue by jopejoe1** [chaotic-aur/packages#1586]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/lbry-desktop-git

### Utility this package has for you

Used for watching lbry/Odyssey 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

git version of lbry-desktop and lbry-app-bin

**Comment by xiota** [comment]
Dropping because uses electron 17.
