### ISSUE TITLE
[Bug] vkd3d Maximum file size exceeded

### ISSUE THREAD

**Issue by nPHYN1T3** [chaotic-aur/packages#1587]
### What happens?

error: failed retrieving file 'vkd3d-tkg-git-1.4.r24.g3b579f6f-1-x86_64.pkg.tar.zst' from br-mirror.chaotic.cx : Maximum file size exceeded

### What is expected to happen?

Updates complete

### If possible, please attach logs

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 vkd3d-tkg-git-1.4.r24.g3b579f6f-1-x86_64.pkg.tar.zst failed terror: failed retrieving file 'vkd3d-tkg-git-1.4.r24.g3b579f6f-1-x86_64.pkg.tar.zst' from geo-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'vkd3d-tkg-git-1.4.r24.g3b579f6f-1-x86_64.pkg.tar.zst' from cdn-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'vkd3d-tkg-git-1.4.r24.g3b579f6f-1-x86_64.pkg.tar.zst' from us-mi-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'vkd3d-tkg-git-1.4.r24.g3b579f6f-1-x86_64.pkg.tar.zst' from us-ut-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'vkd3d-tkg-git-1.4.r24.g3b579f6f-1-x86_64.pkg.tar.zst' from us-va-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'vkd3d-tkg-git-1.4.r24.g3b579f6f-1-x86_64.pkg.tar.zst' from es-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'vkd3d-tkg-git-1.4.r24.g3b579f6f-1-x86_64.pkg.tar.zst' from es-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'vkd3d-tkg-git-1.4.r24.g3b579f6f-1-x86_64.pkg.tar.zst' from de-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'vkd3d-tkg-git-1.4.r24.g3b579f6f-1-x86_64.pkg.tar.zst' from de-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'vkd3d-tkg-git-1.4.r24.g3b579f6f-1-x86_64.pkg.tar.zst' from de-3-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'vkd3d-tkg-git-1.4.r24.g3b579f6f-1-x86_64.pkg.tar.zst' from de-4-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'vkd3d-tkg-git-1.4.r24.g3b579f6f-1-x86_64.pkg.tar.zst' from fr-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'vkd3d-tkg-git-1.4.r24.g3b579f6f-1-x86_64.pkg.tar.zst' from br-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'vkd3d-tkg-git-1.4.r24.g3b579f6f-1-x86_64.pkg.tar.zst' from br-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'vkd3d-tkg-git-1.4.r24.g3b579f6f-1-x86_64.pkg.tar.zst' from kr-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'vkd3d-tkg-git-1.4.r24.g3b579f6f-1-x86_64.pkg.tar.zst' from bg-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'vkd3d-tkg-git-1.4.r24.g3b579f6f-1-x86_64.pkg.tar.zst' from ca-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'vkd3d-tkg-git-1.4.r24.g3b579f6f-1-x86_64.pkg.tar.zst' from in-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'vkd3d-tkg-git-1.4.r24.g3b579f6f-1-x86_64.pkg.tar.zst' from in-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'vkd3d-tkg-git-1.4.r24.g3b579f6f-1-x86_64.pkg.tar.zst' from sg-mirror.chaotic.cx : Maximum file size exceeded
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.

**Comment by Technetium1** [comment]
@nPHYN1T3 It's been rebuilt. Please reopen the issue if it persists. https://builds.garudalinux.org/repos/chaotic-aur/logs/vkd3d-tkg-git.log

**Comment by nPHYN1T3** [comment]
All seems 'Awesome Possum' now, thanks!
