### ISSUE TITLE
[Bug] Both garuda-assistant and garuda-assistant-git have disappeared from the repos despite being in the package list

### ISSUE THREAD

**Issue by gardotd426** [chaotic-aur/packages#1589]
### What happens?

Checking the package database manually by using `yay -Syy; yay -Fyy; yay garuda assistant` shows that both `garuda-assistant` and `garuda-assistant-git` have disappeared. Going to PKGS.org and checking for either package confirms that indeed,  both garuda-assistant packages have stopped being carried by the mirrors. 

I checked the [latest logs](https://builds.garudalinux.org/repos/chaotic-aur/logs/) link, and checked the last log for both [`garuda-assistant`](https://builds.garudalinux.org/repos/chaotic-aur/logs/garuda-assistant.log) and [`garuda-assistant-git`](https://builds.garudalinux.org/repos/chaotic-aur/logs/garuda-assistant-git.log). Neither package has had a build attempted (at least going by the log file dates) since June 23, and both fail because `makepkg` detects that a package has already been built. 

Relevant sections of the log files:

`garuda-assistant.log`:

```
(10/18) Warn about old perl modules
(11/18) Updating fontconfig cache...
(12/18) Probing GDK-Pixbuf loader modules...
(13/18) Updating GIO module cache...
(14/18) Compiling GSettings XML schema files...
(15/18) Probing GTK3 input method modules...
(16/18) Updating icon theme caches...
(17/18) Updating the info directory file...
(18/18) Updating the desktop file MIME type cache...
[?25h==> ERROR: A package has already been built. (use -f to overwrite)
Container pkgdb25895aac4 failed with error code 13.
umount: /var/cache/chaotic/routines/morning/garuda-assistant/machine/root/home/main-builder/pkgwork unmounted
umount: /var/cache/chaotic/routines/morning/garuda-assistant/machine/root/home/main-builder/.ccache unmounted
umount: /var/cache/chaotic/routines/morning/garuda-assistant/machine/root/home/main-builder/pkgsrc unmounted
umount: /var/cache/chaotic/routines/morning/garuda-assistant/machine/root/var/cache/pacman/pkg unmounted
umount: /var/cache/chaotic/routines/morning/garuda-assistant/machine/root/var/pkgdest unmounted
umount: /var/cache/chaotic/routines/morning/garuda-assistant/machine/root (overlay) unmounted
```

`garuda-assistant-git.log`:

```
(10/18) Warn about old perl modules
(11/18) Updating fontconfig cache...
(12/18) Probing GDK-Pixbuf loader modules...
(13/18) Updating GIO module cache...
(14/18) Compiling GSettings XML schema files...
(15/18) Probing GTK3 input method modules...
(16/18) Updating icon theme caches...
(17/18) Updating the info directory file...
(18/18) Updating the desktop file MIME type cache...
[?25h==> Making package: garuda-assistant-git 2.3.5.r6.gaf84e83-1 (Thu 23 Jun 2022 06:58:48 AM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating garuda-assistant git repo...
Fetching origin
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with md5sums...
    garuda-assistant ... Skipped
==> Extracting sources...
  -> Creating working copy of garuda-assistant git repo...
Cloning into 'garuda-assistant'...
done.
==> Starting pkgver()...
==> Updated version: garuda-assistant-git 2.6.2.r1.g4d498d3-1
==> ERROR: A package has already been built. (use -f to overwrite)
Container pkgbb712e65d32 failed with error code 13.
umount: /var/cache/chaotic/routines/morning/garuda-assistant-git/machine/root/home/main-builder/pkgwork unmounted
umount: /var/cache/chaotic/routines/morning/garuda-assistant-git/machine/root/home/main-builder/.ccache unmounted
umount: /var/cache/chaotic/routines/morning/garuda-assistant-git/machine/root/home/main-builder/pkgsrc unmounted
umount: /var/cache/chaotic/routines/morning/garuda-assistant-git/machine/root/var/cache/pacman/pkg unmounted
umount: /var/cache/chaotic/routines/morning/garuda-assistant-git/machine/root/var/pkgdest unmounted
umount: /var/cache/chaotic/routines/morning/garuda-assistant-git/machine/root (overlay) unmounted
```

I haven't dove into the way you guys are setting up and automating your build system, but it at least seems odd that the `A package has already been built (use -f to override)` error is showing up on the `garuda-assistant-git` log because that log shows that the pkgrel version number was actually changed, which means that error should be impossible. But, the non `-git` assistant package didn't have that message, so I have no idea. 

But yeah, as of right now there are at least two phantom packages, and I don't use Garuda itself (I just think Assistant is a real good tool), but I *think* it's one of the more important system utilities on a Garuda installation, and I believe you folks are the official source for the package on Garuda installs, which might mean that anyone who has installed Garuda Linux from scratch since June 23 either doesn't have Garuda Assistant installed, or they do and it's just really old.  Either way, I knew this one was a definite bug so I figured I'd hop over and report it. 

### What is expected to happen?

The two Garuda Assistant packages are able to be found, queried, and installed, rather than just not existing. 

### If possible, please attach logs

There y'all's logs, but still:

https://builds.garudalinux.org/repos/chaotic-aur/logs/garuda-assistant.log

https://builds.garudalinux.org/repos/chaotic-aur/logs/garuda-assistant-git.log

**Comment by dr460nf1r3** [comment]
That's in fact no bug rather than an intended change. Since these applications were Garuda specific and the inclusion of Garuda packages led to the removal from the Arch wiki's custom repository list, we decided to move them to a dedicated Garuda repo in order to make Chaotic-AUR a more compelling choice for Arch and other Arch-based distributions. 
This dedicated Garuda repo still uses our infrastructure (hence being listed in the package list and logs), however using it requires adding 
```
[garuda]
Include = /etc/pacman.d/chaotic-mirrorlist
```
to `/etc/pacman.conf`.
