### ISSUE TITLE
[Remove] plots

### ISSUE THREAD

**Issue by ZingyTomato** [chaotic-aur/packages#1594]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/plots

### Utility this package has for you

A graph plotting app for GNOME.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
https://aur.archlinux.org/packages/plots#comment-875190 left a comment about the broken check process when there's no display attached. Skipping check() for that reason.

**Comment by xiota** [comment]
Dropping because depends on `python-pyglm`, which fails to build.
```
fatal: Fetched in submodule path 'glm', but it did not contain fbc534be62f8c785db989f8ae7526edf6d0dc306. Direct fetching of that commit failed.
```

Metrics:
* plots 13
* python-freetype-py 21
* python-pyglm 11
