### ISSUE TITLE
[Bug] river-git crashes

### ISSUE THREAD

**Issue by jeLee6gi** [chaotic-aur/packages#1597]
### Package

https://aur.archlinux.org/packages/river-git

### What happens?

river `0.1.0.r109.g7443e13` crashes on startup/ when trying to start any program, downgrading to `0.1.0.r107.gbc610c8` fixes the issue.

### What is expected to happen?

river does not crash

### If possible, please attach logs

```
Illegal instruction at address 0x29312b
???:?:?: 0x29312b in ??? (???)
???:?:?: 0x27b30e in ??? (???)
???:?:?: 0x27b60b in ??? (???)
error: failed to dispatch wayland events
Gdk-Message: 13:38:44.522: Error reading events from display: Broken pipe
(EE) failed to read Wayland events: Broken pipe
```

### More information

There is a discussion about this over at the river issue tracker
https://github.com/riverwm/river/issues/657

There was a discussion about compiler flags for river-git on the chaotic-aur issue tracker
https://github.com/chaotic-aur/packages/issues/937

For me the issue goes away when I compile river-git from AUR

**Comment by drishal** [comment]
My guess is probably it needs wlroots 0.16 but official repos have 0.15 and git has 0.17
So you might need to package that as well
