### ISSUE TITLE
[Request] blackbox-terminal-git

### ISSUE THREAD

**Issue by ZingyTomato** [chaotic-aur/packages#1599]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/blackbox-terminal-git

### Utility this package has for you

A beautiful GTK 4 terminal.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
It built okay, but this error pops out at me:
```
installing graphviz...
Warning: Could not load "/usr/lib/graphviz/libgvplugin_gdk.so.6" - It was found, so perhaps one of its dependents was not.  Try ldd.
Warning: Could not load "/usr/lib/graphviz/libgvplugin_gtk.so.6" - It was found, so perhaps one of its dependents was not.  Try ldd.
Warning: Could not load "/usr/lib/graphviz/libgvplugin_gdk.so.6" - It was found, so perhaps one of its dependents was not.  Try ldd.
Warning: Could not load "/usr/lib/graphviz/libgvplugin_gtk.so.6" - It was found, so perhaps one of its dependents was not.  Try ldd.
```
I checked to see what provides that, and it's `graphviz`, which is required by `vala`:
```
pacman -F libgvplugin_gdk.so.6
extra/graphviz 5.0.0-1 [installed]
usr/lib/graphviz/libgvplugin_gdk.so.6
```
If there are *any* issues with the package, please reopen this issue and mention me so I can add `graphviz` to makedepends via interfere.
