### ISSUE TITLE
Git/Bzr packages which "replace" their stable counterparts

### ISSUE THREAD

**Issue by kode54** [chaotic-aur/packages#16]
There is at least one package which chaotic-aur builds, which are Git/Bzr or other source tip packages, which declares itself to be a replacement for its stable counterpart, and therefore always cause package management to offer it as a replacement on every system update pass.

Thus far, the following have been reported:

~~kdisplay-git - replaces: kscreen~~ - fixed
libappindicator-bzr - replaces: libappindicator-gtk3

There may be other such packages in the repository, it may be worth sweeping all the PKGBUILDs for replaces declarations, and listing them here.

Worth telling these packages' maintainers, too, since this declaration really only becomes a problem if anyone is building to custom repositories and doesn't want the bleeding edge replacements.

-- Migrated issue to new infra tracker

**Comment by PedroHLC** [comment]
`libappindicator-bzr` didn't update
:shark:

**Comment by dr460nf1r3** [comment]
This package is not part of Chaotic-AUR so the issue can be closed.
