### ISSUE TITLE
[Request] bat-cat-git

### ISSUE THREAD

**Issue by roythearsonist** [chaotic-aur/packages#1600]
### Link to the package(s) in the AUR

[Bat-cat-git](https://aur.archlinux.org/packages/bat-cat-git)

### Utility this package has for you

As the title implies, this is a cat clone. However, it does things better than cat, such as having color. 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
This package isn't building.  [log](https://builds.garudalinux.org/repos/chaotic-aur/logs/bat-cat-git.log).  Is `community/bat` not sufficient?

**Comment by dr460nf1r3** [comment]
I would be fine with dropping it, how about @roythearsonist ?

**Comment by roythearsonist** [comment]
Sorry for the wait. I'll do the honors and close it myself.
