### ISSUE TITLE
[Request] koodo-reader-bin

### ISSUE THREAD

**Issue by Azanul** [chaotic-aur/packages#1601]
### Link to the package(s) in the AUR

[Koodo Reader](https://aur.archlinux.org/packages/koodo-reader-bin)

### Utility this package has for you

It's an ebook reader

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because uses EOL Electron/14.1.1.  Metrics 37.
