### ISSUE TITLE
[Request]  whatsie-git

### ISSUE THREAD

**Issue by RohitSingh107** [chaotic-aur/packages#1606]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/whatsie-git

### Utility this package has for you

It's a WhatsApp client written in Qt. It's helpful in accessing WhatsApp on desktop.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

https://github.com/keshavbhatt/whatsie

**Comment by xiota** [comment]
Related #3157

**Comment by xiota** [comment]
Dropping because not updated for Qt6 yet.  Will be dropping packages still using Qt5 more rapidly.   Metrics 474.
