### ISSUE TITLE
[Outdated] find-the-command-git fails building (chown main-builder)

### ISSUE THREAD

**Issue by pkasemir** [chaotic-aur/packages#1607]
### If available, link to the latest build

[find-the-command-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/find-the-command-git.log)

### Package name

`find-the-command-git`

### Latest build

`1.4.3.r0.g5a59306-2`

### Latest version available

`2.0.r0.g05157f6-1`

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### More information

Installs just fine on fresh arch install using `yay -S aur/find-the-command-git` 
* https://aur.archlinux.org/packages/find-the-command-git

There seems to be something wrong with the build container/script, the log shows:
```
chown: invalid user: 'main-builder:main-builder'
Container pkg505960d04c6 failed with error code 1.
```

**Comment by pkasemir** [comment]
Seems like it built now, but I sometimes get an install error on archlinux...

```
paul@archlinux ~> sudo pacman -S find-the-command-git
resolving dependencies...
looking for conflicting packages...

Packages (1) find-the-command-git-2.0.r0.g05157f6-1

Total Download Size:   0.01 MiB
Total Installed Size:  0.02 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 find-the-command...     9.5 KiB  17.4 KiB/s 00:01 [######################] 100%
(1/1) checking keys in keyring                     [######################] 100%
(1/1) checking package integrity                   [######################] 100%
error: find-the-command-git: signature from "Nico Jensch (Chaotic-AUR) <dr460nf1r3@garudalinux.org>" is invalid
:: File /var/cache/pacman/pkg/find-the-command-git-2.0.r0.g05157f6-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
```

The strange thing is that if I run the same command again, it will sometimes succeed without the PGP failure.

**Comment by Technetium1** [comment]
Rebuilt and available now, I was able to download and install it.

**Comment by pkasemir** [comment]
Hmm, must have been a temporary issue, I was able to install 150 times in a row successfully, re-downloading the package.

So all LGTM now.

:+1:

**Comment by dr460nf1r3** [comment]
The issue has been identified to be caused by a recent `arch-install-scripts` update, that is used to build our chroots - downgrading fixed the issue for now.
