### ISSUE TITLE
[Request] sqlcl

### ISSUE THREAD

**Issue by SunnyRaj84348** [chaotic-aur/packages#1609]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/sqlcl

### Utility this package has for you

Sqlcl is a command-line utility for Oracle, it is used for remotely connecting to oracle db.
I use it to manage Oracle DB which reside in docker container.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because AUR package is orphaned.  Metrics 4.
