### ISSUE TITLE
[Request] Windscribe Git

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#1611]
### Link to the package(s) in the AUR

[Windscribe-Git](https://aur.archlinux.org/packages/windscribe-git)

### Utility this package has for you

This VPN will be very useful for the security of users who are in Iran (Persia) and China.
Users from other countries can also use it to remain hidden on the Internet.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
```
# Issue 1611
icu67-bin # (dep windscribe-git)
windscribe-git
```
Build fails patching, maybe missing an unspecified qt dep :eyes:...
https://builds.garudalinux.org/repos/chaotic-aur/logs/windscribe-git.log

**Comment by Technetium1** [comment]
I messaged @topik0 on Matrix, but the message was never delivered.

**Comment by Technetium1** [comment]
Made contact with maintainer on another platform, it may be a couple of weeks before the package is debugged.

**Comment by Technetium1** [comment]
This will continue to depend on python2 for a while, so it is rejected for that reason. See #1958
