### ISSUE TITLE
[Request] firefox-userchromejs

### ISSUE THREAD

**Issue by demostanis** [chaotic-aur/packages#1613]
### Link to the package(s) in the AUR

[link](https://aur.archlinux.org/packages/firefox-userchromejs)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by dr460nf1r3** [comment]
No utility provided? :eyes:

**Comment by demostanis** [comment]
Sorry, it's useful to me because it allows me to use old Firefox extensions such as vimfx which are far superior from the new WebExtension ones.
