### ISSUE TITLE
[Request] `zandronum` and `q-zandronum`

### ISSUE THREAD

**Issue by yum13241** [chaotic-aur/packages#1615]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/zandronum

https://aur.archlinux.org/packages/q-zandronum

### Utility this package has for you

Some people like me play Classic Doom multiplayer on Linux. Precompiling these for us would make it take less time to jump in.

Also `zandronum-bin` and the `zandronum-hg` packages are flagged out of date, so that's why they wont work in this case.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

The `zandronum-bin` package is flagged out of date, so we can't just use that.

Same with the `zandronum-hg`.

`q-zandronum` seems to be only in source form.

**Comment by Technetium1** [comment]
I'm choosing [wxgtk2-dev](https://aur.archlinux.org/packages/wxgtk2-dev) instead of [wxwidgets-gtk2](https://aur.archlinux.org/packages/wxwidgets-gtk2) for the [odamex](https://aur.archlinux.org/packages/odamex) dep because `wxwidget-gtk2` does **_NOT_** actually provide what we want.

**Comment by Technetium1** [comment]
odamex partial fail:
```
-- Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES wxWidgets_INCLUDE_DIRS)
CMake Warning at odalaunch/CMakeLists.txt:40 (message):
wxWidgets not found, odalaunch target not generated.
```
I reported the issue: https://aur.archlinux.org/packages/odamex#comment-876350

It still builds the important part of odamex, so it should not actually cause any issue. *PLEASE* report back here if there is a problem because of it!

**Comment by yum13241** [comment]
https://bin.garudalinux.org/?6d80e25df8cfbab1#3XEhtPTRMPPWPA33D3hiC5sUoAbp77wJXX9j4CxbXm4U


fyi i requested zandronum and q-zandronum, odamex is nice to have lol

**Comment by Technetium1** [comment]
`doomseeker` is missing `python` https://aur.archlinux.org/packages/doomseeker#comment-876356

**Comment by Technetium1** [comment]
@yum13241 I need to seperately grab all packages that are in AUR and have them built in order, so I got `odamex` because it is an optdepend from AUR for `doomseeker`.

**Comment by yum13241** [comment]
Oh that makes more sense.



Thank you all chaotic-aur maintainers for all your hard work. It must cost losts to keep this thing alive! I'd donate if I had a bank card lol.


Thanks 4 the explanation. I look forward to playing Doom multiplayer now that I don't have to spend years compiling (my laptop sucks)

**Comment by Technetium1** [comment]
Almost got it, just need to sort out why `doomseeker` is failing. It builds in clean chroot on my machine after adding the required python dep.
```
# Issue 1615
deutex # (dep freedoom)
freedoom # (dep zandronum q-zandronum chocolate-doom)
chocolate-doom # (dep doomseeker)
wxgtk-dev:https://aur.archlinux.org/wxgtk-dev.git # (dep odamex doomseeker)
odamex # (dep doomseeker)
srb2-data # (dep srb2 doomseeker)
srb2 # (dep doomseeker)
doomseeker # (dep zandronum q-zandronum)
q-zandronum
zandronum
```

```
Add zandronum / q-zandronum and all deps: doomseeker, srb2, srb2-data, odamex, wxgtk-dev, chocolate-doom, freedoom, deutex
```

**Comment by Technetium1** [comment]
> Thank you all chaotic-aur maintainers for all your hard work. It must cost losts to keep this thing alive! I'd donate if I had a bank card lol.

No problem! If you want to contribute but don't have spare bandwidth to mirror it's good to keep up on issues here! If something breaks it's good to have people to report the problems so they can be quickly fixed for everyone.

> Thanks 4 the explanation. I look forward to playing Doom multiplayer now that I don't have to spend years compiling (my laptop sucks)

:smiley: Glad to help! I'm sure you won't be the only one enjoying it. Feel free to open issues to have other useful things added.

**Comment by yum13241** [comment]
Well at least I can rest assured knowing one of my favorite projects is still being helped by me asking for stuff lol.


> smiley Glad to help! I'm sure you won't be the only one enjoying it. Feel free to open issues to have other useful things added.


You are welcome.


I *technically* could mirror since I have a fiber optic connection but im just a 13 y/o teen, my dad would postpone pressing the pay button so long lol. So i wouldn't be a reliable one. and my isp doesnt let me port fwd.

**Comment by Technetium1** [comment]
Actually you can do a mirror without port forwarding at all; that's how I run the Michigan USA mirror! The only real requirement is not having a data cap (LOTS of data is used per month) and having 75+GB storage. Certainly no obligation what-so-ever to mirror, but don't be scared to consider it in the future, [especially if you fill in one of the 'blank' areas](https://status.chaotic.cx/map).

The docker scripts used to run a mirror are here: https://github.com/chaotic-aur/docker-mirror/

**Comment by yum13241** [comment]
OK, ll consider it when im independent and financially stable.

**Comment by Technetium1** [comment]
> I'm choosing [wxgtk2-dev](https://aur.archlinux.org/packages/wxgtk2-dev) instead of [wxwidgets-gtk2](https://aur.archlinux.org/packages/wxwidgets-gtk2) for the [odamex](https://aur.archlinux.org/packages/odamex) dep because `wxwidget-gtk2` does **_NOT_** actually provide what we want.

[wxwidgets-gtk2 has been updated](https://aur.archlinux.org/packages/wxwidgets-gtk2#comment-876396), I'll try again...

**Comment by yum13241** [comment]
It seems that this one is a real stumper...

**Comment by Technetium1** [comment]
Maintainer of doomseeker said they will fix soon: https://aur.archlinux.org/packages/doomseeker#comment-876362

**Comment by yum13241** [comment]
OK, I guess i'll need more patience. I can wait for my doom dm fix.

**Comment by yum13241** [comment]
Does the package build now?

**Comment by Technetium1** [comment]
Not yet, the author of Doomseeker in AUR has not updated anything. I tried building again just to be certain. :disappointed:

**Comment by yum13241** [comment]
That's sad.



what's also sad is that at on linux, you can't add bots in gzdoom to deathmatch.



Even with mods like TDBots.

**Comment by yum13241** [comment]
It seems as if `odamex` has now been built.

**Comment by Technetium1** [comment]
@yum13241 Yes! Everything builds but `doomseeker` right now. The maintainer has still not updated it.

**Comment by yum13241** [comment]
On my machine (not in a clean chroot) it builds fine.



![image](https://user-images.githubusercontent.com/91150826/185079464-7a9b3739-988c-4002-a5d5-1e8e15a744df.png)

**Comment by yum13241** [comment]
what the AUR package *should* do IMO is add the user to the audio group so after you get gm.dls and put it in a directory and set snd_midipatchset to that path it should work.

**Comment by Technetium1** [comment]
@yum13241 I'm not sure if we should modify groups, someone more knowledgeable than me can confirm or deny that. We don't have a way to build other than clean chroot, as all packages should be. I still have no idea why the build fails.

**Comment by yum13241** [comment]
Maybe something to report upstream?

**Comment by Technetium1** [comment]
@yum13241 yeah that's probably a good idea, feel free to link this issue to one there!

**Comment by Technetium1** [comment]
New version of odamex is out, so it's been [flagged](https://aur.archlinux.org/pkgbase/odamex/flag-comment).

**Comment by Technetium1** [comment]
`odamex-git` actually works!

**Comment by xiota** [comment]
Switched `doomseeker` to custom package `doomseeker-qt6-git` to build with Qt6.

Switched `odamex-git` to custom package because AUR package fails to build with error stating "In-source builds are not supported."

Metrics:

* doomseeker # 11
* odamex-git # 26
* q-zandronum # 7
* zandronum # 17
