### ISSUE TITLE
[Bug] FYI bottles

### ISSUE THREAD

**Issue by RubenKelevra** [chaotic-aur/packages#1616]
### What happens?

There are currently packaging issues with the [bottles](https://aur.archlinux.org/packages/bottles) main package. The version number shows "2022.6.14-9" at the time of writing, but if you look at the sources, the maintainers actually fetch "2022.5.28-trento-3.tar.gz".

I've created a temporary fix for this (and other issues) and updated it to the latest version under [bottles-fixed](https://aur.archlinux.org/packages/bottles-fixed) until this is sorted out 🤷🏼 

### What is expected to happen?

I guess I would recommend deleting the original package bottles until the version number is corrected, because that's just misleading.

**Comment by dr460nf1r3** [comment]
Let me guess, the pending request on that package is a deletion request? 🤣 
If things don't work out, we can still kind of "fix" the PKGBUILD using our [interfere repo](https://github.com/chaotic-aur/notes#our-interfere-repo).

**Comment by Technetium1** [comment]
:eyes: https://aur.archlinux.org/cgit/aur.git/commit/?h=bottles&id=8387308bf6ea644e87024b90d3ae2a9eef1c5b27

**Comment by Technetium1** [comment]
https://aur.archlinux.org/pkgbase/bottles/flag-comment
> D3SOX flagged bottles out-of-date on 2022-08-05 (EDT) for the following reason:
> libadwaita 1.1.4 is now available in the repos, can this be updated to the latest version now?

**Comment by Technetium1** [comment]
This has been fixed.
