### ISSUE TITLE
[Request] flatseal

### ISSUE THREAD

**Issue by bentuhana** [chaotic-aur/packages#1618]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/flatseal

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
That's pretty cool.

**Comment by Technetium1** [comment]
That commit on interfere says missing GJS and it was not, just forgot to delete that from description...

**Comment by Technetium1** [comment]
I left a comment for the maintainer about the missing deps: https://aur.archlinux.org/packages/flatseal#comment-876499

**Comment by xiota** [comment]
Dropped because moved to extra.  Metrics 407.
