### ISSUE TITLE
[Outdated] Firefox-esr

### ISSUE THREAD

**Issue by Gontier-Julien** [chaotic-aur/packages#1620]
### If available, link to the latest build

[firefox-esr](https://builds.garudalinux.org/repos/chaotic-aur/logs/firefox-esr.log)

### Package name

firefox-esr

### Latest build

91.11.0-2

### Latest version available

102.1.0-1

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

I think it _"could"_ be a `ccache` issue from older version of firefox-esr.
I couldn't test it on my machine and/or my server, since i don't have enough ram.

**Comment by Gontier-Julien** [comment]
Any news?

**Comment by Technetium1** [comment]
This still fails the same way :confused:

**Comment by Gontier-Julien** [comment]
oh :(
Hope it can be fixed quickly, but i've seen on the aur page of [firefox-esr](https://aur.archlinux.org/packages/firefox-esr) that it could be related to the `libevent` version

**Comment by dr460nf1r3** [comment]
Errors are actually different now.. this time it's an issue concerning Rust 1.63, which needs the source to be patched. 
![image](https://user-images.githubusercontent.com/12834713/184531340-22d4598b-0491-4a59-902a-a6e0e5fe725a.png)

**Comment by Gontier-Julien** [comment]
Yeaahh...
Now the new co-maintainer don't seem to even check if the PKGBUILD is passing or not.
`ERROR: Integrity checks (sha512) differ in size from the source array.`

**Comment by Gontier-Julien** [comment]
Firefox-esr should finally build again!
Let see tomorrow and cross fingers!

**Comment by Technetium1** [comment]
Rebuild triggered now.

**Comment by Gontier-Julien** [comment]
> Rebuild triggered now.

Nice but the build failed, but with
`TIER: configure pre-export export compile misc libs tools48:20.47 [0m[0;1;31mfatal error: [0m[1merror in backend: IO failure on output stream: No space left on device[0m`

Not enough memory allocated to build Firefox-esr?

**Comment by dr460nf1r3** [comment]
If it was built on chaotic-dragon, there was indeed a low space situation. I cleared it :)

**Comment by Gontier-Julien** [comment]
> If it was built on chaotic-dragon, there was indeed a low space situation. I cleared it :)

Awesome!!

**Comment by Technetium1** [comment]
@dr460nf1r3 indeed it was! Restarting the build now.

**Comment by Gontier-Julien** [comment]
Well it finally finished building, but it still failing (again sigh)

It seem to complain about some file missing or something missing at least, i didn't really understood what going on. ^^"

**Comment by dr460nf1r3** [comment]
This might actually be a known issue with Firefox-based browsers on Chaotic-AUR, trying to fix it in https://github.com/chaotic-aur/interfere/commit/49caa77c53788c078aa7123ffcb1cabab5874ca5

**Comment by Gontier-Julien** [comment]
> This might actually be a known issue with Firefox-based browsers on Chaotic-AUR, trying to fix it in [chaotic-aur/interfere@49caa77](https://github.com/chaotic-aur/interfere/commit/49caa77c53788c078aa7123ffcb1cabab5874ca5)

Alright how it build not ^^

**Comment by Gontier-Julien** [comment]
It was going to build the package, and then:
`ERROR: You do not have write permission for the directory $SRCDEST (/home/main-builder/pkgsrc).
    Aborting...
Container pkge8db17507cf failed with error code 11.`

We are so close XD

**Comment by dr460nf1r3** [comment]
Affer another build cycle it finally happened 😂

**Comment by Gontier-Julien** [comment]
Thank you very much for the help and patient, i can finally update firefox-esr!

**Comment by Gontier-Julien** [comment]
Quick question, when the package while hit the repo?

**Comment by Technetium1** [comment]
@Gontier-Julien within 30 seconds of the build completing.

**Comment by Gontier-Julien** [comment]
Just seen that it was rebuild today, maybe it while hit the repo in a few

**Comment by Gontier-Julien** [comment]
Hey @Technetium1 could you see why the firefox-esr packages isn't showing in the repo please?

**Comment by Technetium1** [comment]
Oh… This is a problem again.

**Comment by Technetium1** [comment]
https://t.me/chaotic_aur_deploy_log/262119 It was deployed correctly :confused:

**Comment by Technetium1** [comment]
The successful build notification didn't happen, though.

**Comment by Gontier-Julien** [comment]
> 

Welp, something broken again, but elsewhere this time 😂

**Comment by Technetium1** [comment]
@dr460nf1r3 noticed there that there were not signatures deployed.
I'm going to remove `firefox-esr` to clean any leftovers, and rebuild.

**Comment by Technetium1** [comment]
Upon removal, there are 96 language pack files left over, as well as their signatures :eyes:

**Comment by Technetium1** [comment]
It's still refusing to generate signatures and deploy.

**Comment by Technetium1** [comment]
https://t.me/chaotic_aur_deploy_log/262478
So it's deployed with signatures, but *ONLY* when triggered via routine, not as a one-off, and only after removing the previous one. It also did not show a file addition in the deploy log.

**Comment by Gontier-Julien** [comment]
> https://t.me/chaotic_aur_deploy_log/262478 So it's deployed with signatures, but _ONLY_ when triggered via routine, not as a one-off, and only after removing the previous one. It also did not show a file addition in the deploy log.

Firefox-esr is shy that why it doesn't want to deploy 😂
All jokes aside, at least the new version in on the repo now, maybe i could help figure out what could be wrong?

**Comment by dr460nf1r3** [comment]
> All jokes aside, at least the new version in on the repo now, maybe i could help figure out what could be wrong?

I just installed it successfully :eyes:

**Comment by Gontier-Julien** [comment]
> > All jokes aside, at least the new version in on the repo now, maybe i could help figure out what could be wrong?
> 
> I just installed it successfully eyes

Same here successful install on here too :3

**Comment by dr460nf1r3** [comment]
We shall put it to build on garuda-builder in order to avoid issues with uploaded signatures for now 👀

**Comment by Gontier-Julien** [comment]
Btw i know it out of the blues and maybe not the place asking it, but is there a way i could help/participate with the chaotic-aur project?
I'd love too because y'all guys are doing such amazing jobs and i'll be happy to help and/or participate ^^

**Comment by Technetium1** [comment]
We could always use more mirrors https://github.com/chaotic-aur/docker-mirror

**Comment by dr460nf1r3** [comment]
> Btw i know it out of the blues and maybe not the place asking it, but is there a way i could help/participate with the chaotic-aur project?
> I'd love too because y'all guys are doing such amazing jobs and i'll be happy to help and/or participate ^^

Help is always welcome! :) As @Technetium1 pointed out already, mirroring is a great way to participate, it's actually pretty easy to do thanks to our scripted Docker setup. Apart from that, it really depends on what you want to be doing - general package maintenance (like adding new packages, fixing not building packages, and working on issues) or code contributions for the toolbox are also common tasks :)

**Comment by Gontier-Julien** [comment]
> > Btw i know it out of the blues and maybe not the place asking it, but is there a way i could help/participate with the chaotic-aur project?
> > I'd love too because y'all guys are doing such amazing jobs and i'll be happy to help and/or participate ^^
> 
> Help is always welcome! :) As @Technetium1 pointed out already, mirroring is a great way to participate, it's actually pretty easy to do thanks to our scripted Docker setup. Apart from that, it really depends on what you want to be doing - general package maintenance (like adding new packages, fixing not building packages, and working on issues) or code contributions for the toolbox are also common tasks :)

Alright! I'll see what i'm going to do, since i also have a unused vps right now, i'll probably will setup as a mirror then, and see next what can i help more! ^^

Thank you again so much for you're help @Technetium1 and @dr460nf1r3 you're awesome!! ^^

**Comment by Technetium1** [comment]
@Gontier-Julien if you haven't already, please feel free to join the Telegram group. If you only use Matrix, there's a bridge for that too! [Chat links are here](https://aur.chaotic.cx/#:~:text=AUR%20package%20maintainers.-,Links,-%3A). A mirror should have ~100GB available, but it can be a bit less, at least for the moment. Currently we use approx 82.5 GB, but it's always growing a bit at a time.

**Comment by Gontier-Julien** [comment]
> @Gontier-Julien if you haven't already, please feel free to join the Telegram group. If you only use Matrix, there's a bridge for that too! [Chat links are here](https://aur.chaotic.cx/#:~:text=AUR%20package%20maintainers.-,Links,-%3A). A mirror should have ~100GB available, but it can be a bit less, at least for the moment. Currently we use approx 82.5 GB, but it's always growing a bit at a time.

I gess 160G would be plenty then hahaha ^^
I've already join the telegram group, but i'm shy to talk when there a lots of peoples haha ^^"
But i'm going to say hi (I while be under the name of Snowy ^^)! ^^
