### ISSUE TITLE
[Request] orchis-theme

### ISSUE THREAD

**Issue by joe733** [chaotic-aur/packages#1621]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/orchis-theme

### Utility this package has for you

Theming

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
A long time goes by between releases that contain fixes, it makes more sense to add [orchis-theme-git](https://aur.archlinux.org/packages/orchis-theme-git)

**Comment by xiota** [comment]
Dropping because `extra/orchis-theme` is available and reasonably up to date (new release yesterday).
