### ISSUE TITLE
[Bug] duckstation-git cubeb audio doesn't work

### ISSUE THREAD

**Issue by Latrolage** [chaotic-aur/packages#1622]
### What happens?

audio doesn't work when starting game

It gives these 2 errors:

Failed to create or configure audio stream, falling back to null output.

Could not initialize cubeb context: -1

### What is expected to happen?

Audio works

### If possible, please attach logs

```
[    2.2088] I/CDROMAsyncReader: Read thread started with readahead of 8 sectors
[    2.2088] I/SPU: Creating 'Cubeb' audio stream, sample rate = 44100, channels = 2, buffer = 50, latency = 20, stretching = TimeStretch
[    2.2089] E(ReportErrorAsync): ReportErrorAsync: Error: Could not initialize cubeb context: -1
[    2.2102] E(ReportErrorAsync): ReportErrorAsync: Error: Failed to create or configure audio stream, falling back to null output.
[    2.2105] I/MemoryCard: Loaded memory card from /home/firecatmon/.config/duckstation/memcards/Xenogears (Japan) (Disc 1)_1.mcd
[    2.2591] I/CDROM: Inserting new media, disc region: NTSC-J, console region: NTSC-J
[    2.2592] E(SetScreensaverInhibit): Unknown type: 4
[    2.2592] E(SuspendScreensaver): Failed to suspend screensaver.
[    2.2596] E(SetScreensaverInhibit): Unknown type: 4
[    2.2596] E(SuspendScreensaver): Failed to suspend screensaver.
[    2.2596] I/System: Target speed: 100.000000%
[    2.2596] I/System: Syncing to audio
[    2.2596] I/System: Max display fps: 0.000000 (skipping displaying frames when needed)
[    5.6701] I/System: Saving state to '/home/user/.config/duckstation/savestates/SLPS-01160_resume.sav'...
[    5.6701] E(RenderScreenshot): Unhandled swap chain pixel format 58
Panic triggered: 'Unhandled pixel format' in function GetTexelSize (/home/main-builder/pkgwork/src/duckstation/src/common/vulkan/util.cpp:100)
Aborting application. # I closed the application here, it didn't crash
```

### More information

It works when compiling from git or from aur package

**Comment by dr460nf1r3** [comment]
Are you sure that the pkgname is correct? https://aur.archlinux.org/packages/duckstation-qt-git gives 404 :eyes:

**Comment by Latrolage** [comment]
Oops, i definitlly meant duckstation-git

**Comment by Technetium1** [comment]
@Latrolage can you confirm this is fixed now? There's a new maintainer and there's been changes.
https://aur.archlinux.org/packages/duckstation-git#comment-877565

**Comment by Latrolage** [comment]
Installing from the AUR PKGBUILD works properly. the chaotic-aur package does not have working cubeb audio

**Comment by Technetium1** [comment]
New maintainer is missing at least one dependency. I left [a comment](https://aur.archlinux.org/packages/duckstation-git#comment-878157).

**Comment by Latrolage** [comment]
works now :+1:

**Comment by Technetium1** [comment]
Awesome! Thanks for the update @Latrolage!

**Comment by Technetium1** [comment]
It turns out it was in fact missing deps! 
1. https://aur.archlinux.org/cgit/aur.git/commit/?h=duckstation-git&id=ebc4f191a890329a92b9e7e2d78752ea7fa8c3b8
2. https://aur.archlinux.org/cgit/aur.git/commit/?h=duckstation-git&id=6b973f870c14c4653c7b01ea5ab3cfbb4ffcf9a6
