### ISSUE TITLE
[Remove] moodle-dl-git

### ISSUE THREAD

**Issue by jopejoe1** [chaotic-aur/packages#1623]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/moodle-dl-git

### Utility this package has for you

Download content from moodle server for offline reading.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because package and depends aren't in good shape.

Possible to fix by taking over package, but current comaintainer is upstream developer.

Metrics 9.
