### ISSUE TITLE
[Remove] datagrip

### ISSUE THREAD

**Issue by jopejoe1** [chaotic-aur/packages#1624]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/datagrip

### Utility this package has for you

Write database queries with SQL.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Not sure about the license, but other JetBrains products were already packaged.

Also, should include [datagrip-jre](https://aur.archlinux.org/packages/datagrip-jre) as dependency.
Which is also in the same [package base](https://aur.archlinux.org/pkgbase/datagrip).

**Comment by Technetium1** [comment]
We can only add package bases anyway :upside_down_face:
