### ISSUE TITLE
[Request] jdk-temurin

### ISSUE THREAD

**Issue by jopejoe1** [chaotic-aur/packages#1625]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/jdk-temurin

### Utility this package has for you

Using it in development in java and playing Minecraft.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Also has the following LTS versions which would be nice to have.
[jdk17-temurin](https://aur.archlinux.org/packages/jdk17-temurin)
[jdk11-temurin](https://aur.archlinux.org/packages/jdk11-temurin)

**Comment by xiota** [comment]
Dropping this as a duplicate of `extra/jdk-openjdk`.
```
extra/jdk-openjdk 20.0.2.u9-3
chaotic-aur/jdk-temurin 20.0.2.u9-1
```
