### ISSUE TITLE
[Request]  libva-intel-driver-hybrid

### ISSUE THREAD

**Issue by userofryzen** [chaotic-aur/packages#1627]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/libva-intel-driver-hybrid

### Utility this package has for you

complements https://aur.archlinux.org/packages/intel-hybrid-codec-driver aur package
 I think it's very important to have both because unless this the another ones loss its function

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by userofryzen** [comment]
vainfo 
/usr/lib/dri/hybrid_drv_video.so has no function __vaDriverInit_0_32
Not using hybrid_drv_video.so
vainfo: VA-API version: 1.15 (libva 2.15.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Desktop - 2.4.1
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      : VAEntrypointVLD
      VAProfileH264MultiviewHigh      : VAEntrypointEncSlice
      VAProfileH264StereoHigh         : VAEntrypointVLD
      VAProfileH264StereoHigh         : VAEntrypointEncSlice
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileJPEGBaseline           : VAEntrypointVLD


someone can test this package with the another ones that is on the repo on them PC's? for me is not working but if I rebuild the things on my own from AUR it works.. Maybe its because i'm using manjaro or maybe because the another package needs a rebuild.. idk

**Comment by userofryzen** [comment]
@Technetium1 for you is not working either?

**Comment by Technetium1** [comment]
@userofryzen I don't actually use this package so I can't really help debug :\

**Comment by xiota** [comment]
What's the difference between libva-intel-driver-hybrid and intel-hybrid-driver-codec?  The upstream website and project name is the same for both.

**Comment by userofryzen** [comment]
> What's the difference between libva-intel-driver-hybrid and intel-hybrid-driver-codec? ~The upstream website and project name is the same for both.~
> 
> Nevermind, looked more carefully. Looks like one project (driver) may use the other for functionality (codec)?

yeah

**Comment by xiota** [comment]
After installing libva-intel-driver-hybrid and intel-hybrid-driver-codec:
```
$ vainfo
/usr/lib/dri/hybrid_drv_video.so has no function __vaDriverInit_0_32
Not using hybrid_drv_video.so
vainfo: VA-API version: 1.15 (libva 2.15.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Skylake - 2.4.1
vainfo: Supported profile and entrypoints
         ...
```

**Comment by xiota** [comment]
What's the difference among these packages?
```
chaotic-aur/libva-intel-driver-g45-h264
chaotic-aur/libva-intel-driver-hybrid
extra/libva-intel-driver
```

**Comment by userofryzen** [comment]
Libva g45 IS for older devices
Libva Hybrid uses intel hybrid driver along with the normal liba drivers that way gets the acceleration not only with vp9 provided by hybrid but the another codecs too. 
Apart from it, building that locally gives me a package that is working but installing from this repository gives me a package that is not working. When I can I'll send how it looks like on my pc when building locally

**Comment by userofryzen** [comment]
@xiota when I make the package locally on my systemd it gives me this output:
vainfo: VA-API version: 1.15 (libva 2.15.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Desktop - 2.4.1
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      : VAEntrypointVLD
      VAProfileH264MultiviewHigh      : VAEntrypointEncSlice
      VAProfileH264StereoHigh         : VAEntrypointVLD
      VAProfileH264StereoHigh         : VAEntrypointEncSlice
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD

That is the mix of libva normal driver and the hybrid ones
But when I install the packages from this repo it gives one error for the hybrid so no vp9 accel.

**Comment by xiota** [comment]
I think `intel-hybrid-codec-driver` needs to be rebuilt on chaotic-aur because it is the package that provides `hybrid_drv_video.so`.  When I rebuilt it locally, it seems to load properly:
```
$ vainfo
vainfo: VA-API version: 1.15 (libva 2.15.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Skylake - 2.4.1
vainfo: Supported profile and entrypoints
      ...
```

The version on chaotic aur is 2.0.0.r169.edead0c-4.  When I built it from aur, the version is 2.0.0.r170.7961945-1.  (Is it necessary to open an outdated issue for this?)

**Comment by userofryzen** [comment]
> I think `intel-hybrid-codec-driver` needs to be rebuilt on chaotic-aur because it is the package that provides `hybrid_drv_video.so`. When I rebuilt it locally, it seems to load properly:
> 
> ```
> $ vainfo
> vainfo: VA-API version: 1.15 (libva 2.15.0)
> vainfo: Driver version: Intel i965 driver for Intel(R) Skylake - 2.4.1
> vainfo: Supported profile and entrypoints
>       ...
> ```
> 
> The version on chaotic aur is 2.0.0.r169.edead0c-4. When I built it from aur, the version is 2.0.0.r170.7961945-1. (Is it necessary to open an outdated issue for this?)
I have said this.. the need to rebuilt the another package is on first comment. @Technetium1 has it been done?

**Comment by xiota** [comment]
> I have said this.. the need to rebuilt the another package is on first comment.

@userofryzen Since you didn't specify the packages that need to be rebuilt, I thought you were rebuilding `libva-intel-driver-hybrid`.  Perhaps others thought the same.

**Comment by userofryzen** [comment]
When I said the another package I meant the intel-hybrid ones that is a dependency for that. Sorry for the confusion. 
I hope those can be rebuilt and I'll test again

**Comment by Technetium1** [comment]
@userofryzen `libva-intel-driver-hybrid` is being rebuilt hourly if any change happens: https://github.com/chaotic-aur/packages/commit/4d35bc47d61f8e70375e9fa03a2a0ce3b0747c10. I will start a manual build in case something weird happened, though. 

> Is it necessary to open an outdated issue for this?

Not when this issue is already open, but normally yes!

**Comment by Technetium1** [comment]
The latest version is already built: https://builds.garudalinux.org/repos/chaotic-aur/logs/libva-intel-driver-hybrid.log

**Comment by userofryzen** [comment]
> The latest version is already built: https://builds.garudalinux.org/repos/chaotic-aur/logs/libva-intel-driver-hybrid.log

The package that needs a rebuilt it's not that. It's https://aur.archlinux.org/packages/intel-hybrid-codec-driver
And may be after making the rebuilt of this one it is good to rebuilt this too but always after the another one because it's a dependency for this. 
Try to rebuild the another ones that is on this repo too and after this I'm gonna testing

**Comment by userofryzen** [comment]
It's needed to say that from the logs the package is not even been rebuilt at least it's what I see at the end because it says that there is another built and finish

**Comment by Technetium1** [comment]
> The package that needs a rebuilt it's not that. It's [aur.archlinux.org/packages/intel-hybrid-codec-driver](https://aur.archlinux.org/packages/intel-hybrid-codec-driver)

That was added in this issue https://github.com/chaotic-aur/packages/issues/1403 and this commit https://github.com/chaotic-aur/packages/commit/81a2876bb4f954496e7287b8acb6dd462fa69369

I will bump both packages to force a simultaneous rebuild.

**Comment by Technetium1** [comment]
> ==> Finished making: libva-intel-driver-hybrid 2.4.1-2.1 (Tue 30 Aug 2022 05:50:42 PM CEST)
==> Finished making: intel-hybrid-codec-driver 2.0.0.r170.7961945-1 (Tue 30 Aug 2022 05:50:06 PM CEST)

**Comment by userofryzen** [comment]
@xiota test it you too by the way

**Comment by Technetium1** [comment]
> Now it's working :) May be it's good to recompile the intel-hybrid-codec-driver too each time libva-intel-driver-hybrid gets recompiled

I don't think we have a way to do that aside from manually bumping when needed.

**Comment by Technetium1** [comment]
I'll gladly close this issue if someone else can also confirm it's working as expected now!

**Comment by xiota** [comment]
I just reinstalled both packages from the repository, and it appears to work as expected.  How do I check whether mpv or some other program is really using it?
```
# pacman -S libva-intel-driver-hybrid intel-hybrid-codec-driver
   ...
$ vainfo
vainfo: VA-API version: 1.15 (libva 2.15.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Skylake - 2.4.1
vainfo: Supported profile and entrypoints
   ...
```

**Comment by userofryzen** [comment]
> I just reinstalled both packages from the repository, and it appears to work as expected. How do I check whether mpv or some other program is really using it?
> 
> ```
> # pacman -S libva-intel-driver-hybrid intel-hybrid-codec-driver
>    ...
> $ vainfo
> vainfo: VA-API version: 1.15 (libva 2.15.0)
> vainfo: Driver version: Intel i965 driver for Intel(R) Skylake - 2.4.1
> vainfo: Supported profile and entrypoints
>    ...
> ```

sudo intel_gpu_top says when it's used the video block EXCEPT for VP9( I think it's because it's emulated at all and not " official")
You can also put in smplayer with mpv and see if there is hadware accel on logs
in chromium you can check( but first you have to configure it and it's a little bit complicated) if there is VDA or GPU accel in chrome://media-internals tab you have gpu decode

**Comment by userofryzen** [comment]
anyways you can close @Technetium1 
confirmed that the package is working well now

**Comment by xiota** [comment]
`intel_gpu_top` shows `mpv -vo=gpu -hwdec=vaapi` using the video pipeline.  But it's only around 4-5%, while the render pipeline is around 40%.  Without vaapi, the render pipeline shows  45-60%.

**Comment by Technetium1** [comment]
@dr460nf1r3 is there a way we can force these to build together?

Anyone is welcome to open an issue to report this package outdated, it'd be helpful to link to this issue in it.

**Comment by userofryzen** [comment]
> `intel_gpu_top` shows `mpv -vo=gpu -hwdec=vaapi` using the video pipeline. But it's only around 4-5%, while the render pipeline is around 40%. Without vaapi, the render pipeline shows 45-60%.

it's normal and it's working so dont worry about

**Comment by xiota** [comment]
When trying to install `libva-intel-driver-hybrid`, I get the following error:
```
error: libva-intel-driver-hybrid: signature from "Pedro Henrique Lara Campos <root@pedrohlc.com>" is invalid
:: File /var/cache/pacman/pkg/libva-intel-driver-hybrid-2.4.1-2.2-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n]
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.
```

I have tried editing `/etc/pacman.d/chaotic-mirrorlist` to change mirrors.

**Comment by dr460nf1r3** [comment]
It just got rebuilt!
