### ISSUE TITLE
[Request] Required Packages

### ISSUE THREAD

**Issue by Bhooty** [chaotic-aur/packages#1631]
### Link to the package(s) in the AUR

https://archlinux.org/packages/core/x86_64/libxcrypt-compat/
https://archlinux.org/packages/core/x86_64/inetutils/
https://archlinux.org/packages/core/x86_64/net-tools/

### Utility this package has for you

Xampp application needs these packages

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
None of these packages are in the AUR, so therefore this issue is invalid.

**Comment by dr460nf1r3** [comment]
Aren't these available in official mirrors already? I'm not seeing the point 👀

**Comment by Bhooty** [comment]
> Aren't these available in official mirrors already? I'm not seeing the point 👀

Yes
At the time for some reason they were not showing up
That’s why added them here

Later found them but forgot to close the issue
Sorry 😞
