### ISSUE TITLE
[Request] kodi-git

### ISSUE THREAD

**Issue by cg00001** [chaotic-aur/packages#1632]
### Link to the package(s) in the AUR

https://aur.archlinux.org/pkgbase/kodi-git

### Utility this package has for you

Installs latest Kodi Nexus.
Building it takes countless hours.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
I have never yet seem something with so many dependencies. This will take a while.

**Comment by Technetium1** [comment]
Luckily all the dependencies are available in core/community... but this takes a long time to build.
```
real    37m51.903s
user    187m7.347s
sys     22m2.128s
```
@dr460nf1r3 `chaotic-dragon` consistently fails to upload with rsync. I'll put it into the ufscar until that's sorted.

**Comment by cg00001** [comment]
Thank you.

**Comment by cg00001** [comment]
@Technetium1 kodi-git points to master, and that now builds Kodi 21 alpha version, leaving the Kodi 20 (Nexus) behind with no binary.
A new PKGBUILD was just created for Kodi Nexus, it's here if you can make a binary out of it:
https://aur.archlinux.org/packages/kodi-nexus-git

**Comment by Technetium1** [comment]
@cg00001 let's wait until someone explicitly requests this. There are less than 100 users of `kodi-git`

**Comment by cg00001** [comment]
> @cg00001 let's wait until someone explicitly requests this. There are less than 100 users of `kodi-git`

Maybe because master now gives Kodi 21 alpha instead of Kodi 20?
If opening a new request helps I can do it.

**Comment by Technetium1** [comment]
@cg00001 there are 88 downloads over the last 30 days combined for `kodi-git` from the entire Chaotic-AUR. If you are requesting it for your use, it will be added, but let's check on this later to make sure it actually gets used! I'll attempt to compile it, and if it works, I'll add it to this issue, else it should get it's own.

**Comment by cg00001** [comment]
> @cg00001 there are 88 downloads over the last 30 days combined for `kodi-git` from the entire Chaotic-AUR. If you are requesting it for your use, it will be added, but let's check on this later to make sure it actually gets used! I'll attempt to compile it, and if it works, I'll add it to this issue, else it should get its own.
> 
> EDIT: Build fails, please open a separate issue.

I opened an issue:
https://github.com/chaotic-aur/packages/issues/2175

**Comment by xiota** [comment]
Dropping kodi-git because  failing to build since Feb 2025.  Too complicated to fix with interfere.

Last build of kodi-stable-git was last week.

Metrics:

* kodi-git # 10
* kodi-git-dev # 3
* kodi-git-eventclients # 2
* kodi-git-tools-texturepacker # 2
* kodi-stable-git # 15
* kodi-stable-git-dev # 2
* kodi-stable-git-eventclients # 2
* kodi-stable-git-tools-texturepacker # 2
