### ISSUE TITLE
[Outdated] firefox with appmenu is outdated

### ISSUE THREAD

**Issue by jothi-prasath** [chaotic-aur/packages#1636]
### If available, link to the latest build

[firefox-appmenu](https://builds.garudalinux.org/repos/chaotic-aur/logs/firefox-appmenu.log)

### Package name

firefox-appmenu

### Latest build

103.0.1-1

### Latest version available

103.0.1-1

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by Technetium1** [comment]
Started rebuilding it now, so at least if it fails we will have an accurate log.

**Comment by Technetium1** [comment]
Oops! Duplicate of #1444, please subscribe to that issue for updates.

**Comment by jothi-prasath** [comment]
firefox-appmenu 104.0.1-1 is out and i can successfully build it in my local machine
