### ISSUE TITLE
[Request] intel-ucode-clear

### ISSUE THREAD

**Issue by evansan** [chaotic-aur/packages#1637]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/intel-ucode-clear

### Utility this package has for you

This is the microcode for INTEL CPUs that you can find in Clear Linux
regular intel-ucode microcode found in official arch repos is often a few months behind intel-ucode-clear and might not have the same perks and optimizations as it follows a different release pipeline.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because package is unmaintained and now years behind `extra/intel-ucode`.
