### ISSUE TITLE
[Request] amdguid-glow-bin

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#1641]
### Link to the package(s) in the AUR

[amdguid-glow-bin](https://aur.archlinux.org/packages/amdguid-glow-bin)

### Utility this package has for you

AMDGPU temperature and fan speed monitoring tool

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropped because orphaned on AUR and depends tree looks like a mess.  Utilities should have been combined in a single package (they all share the same repo) instead of split across multiple packages.  Metrics 11.
