### ISSUE TITLE
[Request] glibc-eac

### ISSUE THREAD

**Issue by matteoturini** [chaotic-aur/packages#1643]
### Link to the package(s) in the AUR

[glibc-eac (github.com)](https://github.com/Frogging-Family/glibc-eac)

This package is outside of the AUR, but it's from a trusted developer that has a history of creating arch packages related to gaming.

### Utility this package has for you

Fixes EAC (EasyAntiCheat) in many games.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by JustTNE** [comment]
Arch's gibc is already patched, so I don't see why we should have this.

**Comment by PedroHLC** [comment]
> Arch's gibc is already patched, so I don't see why we should have this.

Be more polite, we're not Arch's TUs.

---

@matteoturini the patch "glib-eac" adds, was recently (yesterday) added to arch's official glibc, as seen in: https://github.com/archlinux/svntogit-packages/commit/e1d69d80d07494e3c086ee2c5458594d5261d2e4

Which means you don't need to install "glib-eac" anymore.

But thanks for the contribution anyway. :smile_cat:

**Comment by matteoturini** [comment]
> Update: As of https://github.com/archlinux/svntogit-packages/commit/e1d69d80d07494e3c086ee2c5458594d5261d2e4, Arch glibc will work again with eos-eac games, except for Rogue Company which needs additional reverts. The approach used by Arch's glibc maintainer is the same as this (reverting the offending change), so updating to the 2.36-2 package will be totally seemless. Rogue Company players, I fear you'll have to keep using this package.
Except for Rogue Company.

**Comment by matteoturini** [comment]
Is it going to get added?

**Comment by Technetium1** [comment]
I'm going to probably say no, because there is no differentiation that this is patched. It does build, but I immediately removed it after seeing this:
```
[tech@mango ~]$ pacman -Ss glibc
core/glibc 2.36-2 [installed]
GNU C Library
core/lib32-glibc 2.36-2 [installed]
GNU C Library (32-bit)
extra/libnss_nis 3.1-3
NSS NIS plugin for glibc
extra/nss-mdns 0.15.1-1 [installed]
glibc plugin providing host name resolution via mDNS
extra/rpcsvc-proto 1.4.3-1
rpcsvc protocol definitions from glibc
community/aarch64-linux-gnu-glibc 2.36-1
GNU C Library ARM64 target
community/riscv64-linux-gnu-glibc 2.36-1 (risc-v)
GNU C Library RISCV target
chaotic-aur/glibc 2.36-2 [installed]
GNU C Library
chaotic-aur/lib32-glibc 2.36-2 [installed]
GNU C Library (32-bit)
chaotic-aur/lib32-nss-mdns 0.15.1-1
glibc plugin providing host name resolution via mDNS
chaotic-aur/wine-lol-glibc 2.35-1
GNU C Library patched for wine-lol
```

**Comment by dr460nf1r3** [comment]
We would need to modify it's pkgname and add proper provides in order to add this package 👀

**Comment by dr460nf1r3** [comment]
Completed via https://github.com/chaotic-aur/interfere/blob/master/glibc-eac/interfere.patch

**Comment by matteoturini** [comment]
Thank you

**Comment by xiota** [comment]
Earlier this month, Arch dropped the patch that enabled DT_HASH.  To restore functionality, I have added packages that auto-sync with `core/glibc`.

* `glibc-dthash`: Enables DT_HASH by modifying `LDFLAGS` (instead of patching).
    * Functionally equivalent to the patched `core/glibc` and `aur/glibc-eac`.

* `glibc-eac`: Enables DT_HASH and applies `rogue_company_reverts.patch`.
    * Functionally equivalent to `Frogging-Family/glibc-eac`
