### ISSUE TITLE
[Request] burpsuite

### ISSUE THREAD

**Issue by fukeromar** [chaotic-aur/packages#1644]
### Link to the package(s) in the AUR

[burpsuite aur ](https://aur.archlinux.org/packages/burpsuite)

### Utility this package has for you

for penetration testing 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

i searched in pull request it was there but it's not exist in  `yay`

**Comment by xiota** [comment]
Dropping because fails to build and license states:

> Restrictions on use
>
> (i) Unless expressly permitted by the terms of Your Order, **You shall not copy the Software or the Documentation** except where such copying is incidental to normal use of the Software, or necessary for the purpose of back-up or operational security. You further agree to include Our copyright notice on all entire and partial copies that You make of the Software or Documentation on any medium.

Metrics 2406.
