### ISSUE TITLE
[Outdated] ryujinx-git

### ISSUE THREAD

**Issue by NerosTie** [chaotic-aur/packages#1646]
### If available, link to the latest build

[ryujinx-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/ryujinx-git.log)

### Package name

ryujinx-git

### Latest build

r2186.c8f9292b

### Latest version available

r2100.9827dc35e

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

Git package not updated since the end of May.

**Comment by Technetium1** [comment]
This builds in a clean chroot for me.

**Comment by Technetium1** [comment]
Building successfully for a while now at `r2385.af0110005-1`
