### ISSUE TITLE
[Request] podman-desktop

### ISSUE THREAD

**Issue by timescam** [chaotic-aur/packages#1647]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/podman-desktop

### Utility this package has for you

Manage Podman and other container engines from a single UI and tray

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
I was wondering when this would get requested :)

**Comment by xiota** [comment]
Planning to drop, pending move to extra repo.  Metrics 769.
