### ISSUE TITLE
[Outdated] mongodb-compass

### ISSUE THREAD

**Issue by KatsuroKurosaki** [chaotic-aur/packages#1648]
### If available, link to the latest build

[mongodb-compass.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/mongodb-compass.log)

### Package name

mongodb-compass

### Latest build

1.30.1

### Latest version available

1.32.6

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### More information

Package builds sucessfully in arch docker image with base, base-devel, git and sudo installed, using `makepkg -s` as unprivileged user and the "ALL:ALL (NO PASSWD)" thingie in sudoers

**Comment by Technetium1** [comment]
[Bumping](https://github.com/chaotic-aur/interfere/commit/e7f35019b5bfc8156372cbd0998ffe1e71090879?diff=unified#diff-acda3a66e1f15a258e2d7c66274a579f3e77ce846d9358b43f611ab39f0ae9f2R87) fixed it.

**Comment by Technetium1** [comment]
Sidenote for later if this happens again, something weird was going on with a cached `.deb` file from the old build...

**Comment by KatsuroKurosaki** [comment]
Thanks for reviewing it, Technetium1.

As a heads up, check if there are no other dangling *.deb packages out there preventing further builds to succeed. Not for mongoDB compass but other packages-

**Comment by Technetium1** [comment]
@KatsuroKurosaki We do take a look around for failing builds occasionally. To make it easier the are filtered by the type of failures: https://builds.garudalinux.org/repos/chaotic-aur/logs/filtered/
