### ISSUE TITLE
[Request] FSearch

### ISSUE THREAD

**Issue by ProfP30** [chaotic-aur/packages#1649]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/fsearch

### Utility this package has for you

Implements program FSearch; FSearch is a fast file search utility, inspired by Everything Search Engine. It’s written in C and based on GTK3.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

See also 
https://cboxdoerfer.github.io/fsearch/

Requirements

    GTK 3.18
    GLib 2.44
    glibc 2.19 or musl 1.1.15 (other C standard libraries might work too, those are just the ones I verified)
    PCRE (libpcre)
    ICU 3.8

**Comment by Technetium1** [comment]
That's pretty cool
