### ISSUE TITLE
[Request]  liquorix kernel

### ISSUE THREAD

**Issue by Pandademic** [chaotic-aur/packages#1652]
### Link to the package(s) in the AUR

- [linux-lqx](https://aur.archlinux.org/packages/linux-lqx)
- [linux-lqx-headers](https://aur.archlinux.org/packages/linux-lqx-headers)
- [related? linux-lqx-docs](https://aur.archlinux.org/packages/linux-lqx-docs)

### Utility this package has for you

It's a very nice custom kernel.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview

No, I do not.

### Have you tested if the package builds in a clean chroot?

No , I have not.

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

- [kernel homepage](https://liquorix.net/)

liqourix is another custom kernel, like xanmod(which is already here).]

**Comment by Technetium1** [comment]
We only build pkgbases, so those will all be included: https://aur.archlinux.org/pkgbase/linux-lqx

**Comment by Technetium1** [comment]
:sweat_smile: 
```
real    57m56.809s
user    323m15.156s
sys     59m52.477s
```

**Comment by Pandademic** [comment]
@Technetium1 thanks.
