### ISSUE TITLE
[Outdated] blender-git

### ISSUE THREAD

**Issue by qumaciel** [chaotic-aur/packages#1653]
### If available, link to the latest build

[blender-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/blender-git.log)

### Package name

`blender-git`

### Latest build

`3.4.r117161.g90be364ca9b`

### Latest version available

master

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

`blender-git` has `cuda` and `optix` listed only as an optional dependency, unlike the upstream Arch `blender` package where it's a regular dependency. This probably results in it being unavailable at build time in the chaotic chroot. If it isn't available at build time, blender gets built without cuda and optix.

As discussed before regarding `openimagedenoise`, it seems like it is the way it is on purpose. I guess the maintainer wants people to be able to build with minimal dependencies if they want. IMO Chaotic should try to build with the same dependencies as the regular non-git Arch package.

For `cuda` is simple, we could just add `cuda` to [blender-git/PKGBUILD.append](https://github.com/chaotic-aur/interfere/blob/master/blender-git/PKGBUILD.append)

On the other hand, to solve the `optix` issue, the `PKGBUILD` needs to be patched to something like this:

<details>
<summary>optix.patch</summary>

```
From 84a5b2dda4c619966427c35469d0ca00f5fcac8f Mon Sep 17 00:00:00 2001
From: qumaciel <maciel@tutanota.com>
Date: Wed, 17 Aug 2022 17:18:31 -0300
Subject: optix support

---
 PKGBUILD | 15 +++++++++------
 1 file changed, 9 insertions(+), 6 deletions(-)

diff --git a/PKGBUILD b/PKGBUILD
index 255e8f7..68c8ff1 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -48,6 +48,7 @@ source=("git://git.blender.org/blender.git${_fragment}"
         'blender-dev-tools.git::git://git.blender.org/blender-dev-tools.git'
         usd_python.patch #add missing python headers when building against python enabled usd.
         embree.patch #add missing embree link.
+        https://developer.download.nvidia.com/redist/optix/v7.3/OptiX-7.3.0-Include.zip
         )
 sha256sums=('SKIP'
             'SKIP'
@@ -55,7 +56,8 @@ sha256sums=('SKIP'
             'SKIP'
             'SKIP'
             '333b6fd864d55da2077bc85c55af1a27d4aee9764a1a839df26873a9f19b8703'
-            'd587135fd9b815d60e8b7f48976aa835472922fc8f64c256dc397bfcd3c2642a')
+            'd587135fd9b815d60e8b7f48976aa835472922fc8f64c256dc397bfcd3c2642a'
+            '0d6cb22f4f7e5f8723ab48b5f94c09c0e0d20e8f8b792909530fac2ee1325272')
 
 pkgver() {
   blender_version=$(grep -Po "BLENDER_VERSION \K[0-9]{3}" "$srcdir"/blender/source/blender/blenkernel/BKE_blender_version.h)
@@ -85,11 +87,11 @@ build() {
   fi
 
   # check for optix
-  _OPTIX_PKG=$(pacman -Qq optix 2>/dev/null) || true
-  if [ "$_OPTIX_PKG" != "" ]; then
-      _CMAKE_FLAGS+=( -DWITH_CYCLES_DEVICE_OPTIX=ON
-                      -DOPTIX_ROOT_DIR=/opt/optix )
-  fi
+  #_OPTIX_PKG=$(pacman -Qq optix 2>/dev/null) || true
+  #if [ "$_OPTIX_PKG" != "" ]; then
+  #    _CMAKE_FLAGS+=( -DWITH_CYCLES_DEVICE_OPTIX=ON
+  #                    -DOPTIX_ROOT_DIR=/opt/optix )
+  #fi
 
   # check for open image denoise
   _OIDN_PKG=$(pacman -Qq openimagedenoise 2>/dev/null) || true
@@ -106,6 +108,7 @@ build() {
 
   cmake -G Ninja -S "$srcdir/blender" -B build \
         -C "${srcdir}/blender/build_files/cmake/config/blender_release.cmake" \
+        -DOPTIX_ROOT_DIR="$srcdir"/include \
         -DCMAKE_INSTALL_PREFIX=/usr \
         -DCMAKE_BUILD_TYPE=Release \
         -DWITH_INSTALL_PORTABLE=OFF \
-- 
2.37.2
```
</details>

But I don't know how chaotic patches PKGBUILDs.

In addition to all of that, checking the .log, looks like `libepoxy` is missing.
I've reported in [AUR-blender-git repo](https://github.com/bartoszek/AUR-blender-git/issues/12).

**Comment by Technetium1** [comment]
I think we should also include `usd20` too then, even though it's slightly outdated at the moment.

**Comment by qumaciel** [comment]
> ~I think we should also include `usd21` too, even though it's slightly outdated at the moment.~ EDIT: build of `usd21` dependency fails, skipping that one for now.

I´d be a nice addition! I'm experimenting locally with the latest [usd22](https://github.com/PixarAnimationStudios/USD/blob/release/CHANGELOG.md#change-log), trying to drop `python2` dependencies, upgrade deps to `PySide6`, and the latest `tbb`, but I'm not quite there yet.

**Comment by Technetium1** [comment]
@qumaciel I was just writing an issue for the Pixar repo to create an AUR package! Are you going to create it instead, or should I post this?

---

### Description of Issue
The [latest version](https://aur.archlinux.org/packages/usd21) of USD on the [Arch User Repository](https://wiki.archlinux.org/title/Arch_User_Repository) is an outdated version of 21.XX that doesn't build anymore. The developer previously created and maintained versions 19 and 20, but is unlikely to make a new package for 22 because they are helping out at the border of Ukraine and have no access to their machine.

To follow the naming scheme, `usd22` could be for version 22.XX, or just `usd` if it will always be at the latest version.

### System Information (OS, Hardware)
Arch Linux

### Package Versions
22.XX

**Comment by qumaciel** [comment]
> @qumaciel I was just writing an issue for the Pixar repo to create an AUR package! Are you going to create it instead, or should I post this?

Since, unfortunately, we're unlikely to see the maintainer anytime soon, I think you should post it anyway.

I'm just figuring whether it will be an easy update without much headache. 
I'll keep you posted in case I have success here.

**Comment by Technetium1** [comment]
I opened https://github.com/PixarAnimationStudios/USD/issues/2001

**Comment by qumaciel** [comment]
It turns out that [USD is built against tbb 2019 update 6](https://github.com/PixarAnimationStudios/USD/issues/2000#issuecomment-1220141712) and it is broken with current `2021.6.0`.

The only solution I see is to create a legacy tbb repo and build with it. :(

**Comment by qumaciel** [comment]
Created AUR [tbb2019](https://aur.archlinux.org/packages/tbb2019).

**Comment by Technetium1** [comment]
`tbb2019` deployed successfully; if it needs to be built again in the meantime, just say so, since it's not yet in a routine.

**Comment by adro79** [comment]
@qumaciel packages like `embree` needs dependency `intel-tbb` and can't be replaced with your **tbb2019** package. Maybe changing provides=("intel-tbb=$pkgver") in the PKGBUILD can fix the issue?

**Comment by qumaciel** [comment]
Sure, I'll fix in the next update. I'm still polishing this old piece of code to the two-digits gcc era.  :S

Upstream Arch [changed the name](https://github.com/archlinux/svntogit-packages/commit/ccf4c488c380817bdf58e152f8254e3245f3edbe) from `intel-tbb` to `tbb` in v2020.
I wasn't sure whether keep it or not.

**Comment by qumaciel** [comment]
Packaging `usd` is proven to be more challenging than I anticipated. So, I think we should settle for `blender-git` in pair with the features in Arch's `blender`. I can open another issue whenever I get a working `usd`.

Back to`optix`, we need to patch the current PKGBUILD to include the redistributable headers to build instead of looking for `optix`. 

Arch blender uses [OptiX-7.3.0](https://developer.download.nvidia.com/redist/optix/v7.3/OptiX-7.3.0-Include.zip), but we can try the latest  redist headers [OptiX-7.4.0](https://developer.download.nvidia.com/redist/optix/v7.4/OptiX-7.4.0-Include.zip)

@Technetium1 , do you think it is possible with chaotic toolboxes, or shall we contact the repo maintainer?


I fail to see a scenario where we want to build with `cuda` but not `optix`.

**Comment by Technetium1** [comment]
> Packaging `usd` is proven to be more challenging than I anticipated. So, I think we should settle for `blender-git` in pair with the features in Arch's `blender`. I can open another issue whenever I get a working `usd`.

Sounds good to me, probably the most appropriate answer


> Back to`optix`, we need to patch the current PKGBUILD to include the redistributable headers to build instead of looking for `optix`. 
> 
> Arch blender uses [OptiX-7.3.0](https://developer.download.nvidia.com/redist/optix/v7.3/OptiX-7.3.0-Include.zip), but we can try the latest  redist headers [OptiX-7.4.0](https://developer.download.nvidia.com/redist/optix/v7.4/OptiX-7.4.0-Include.zip)

> @Technetium1 , do you think it is possible with chaotic toolboxes, or shall we contact the repo maintainer?

It should be possible, but away from home until Monday afternoon, so I cannot confirm anything for sure yet. Probably requires interfere to specify


> I fail to see a scenario where we want to build with `cuda` but not `optix`.

I agree with that!

**Comment by Technetium1** [comment]
@qumaciel Should be able to add this to the [PKGBUILD.append](https://github.com/chaotic-aur/interfere/blob/master/blender-git/PKGBUILD.append), but seems the flags will need to be altered as well, since right now it's checking to see if Optix is installed with pacman. Does it need anything more than [-DOPTIX_ROOT_DIR="$srcdir"/include](https://github.com/archlinux/svntogit-community/blob/2291ee7af8e8e6a3d09b1dd847e411c4950bb95a/trunk/PKGBUILD#L67)?

```
source+=(https://developer.download.nvidia.com/redist/optix/v7.4/OptiX-7.4.0-Include.zip)
sha512sums+=(c7ebb2ceb8bd12730f7ab6e33b204daf22beda56b0c903de22386d6effd919a90e2b232bac6f5d4542ff25c741b148ce67115bef0d39fd59cc24632da1586b65)
```

**Comment by Technetium1** [comment]
`tbb2019` is missing `git` in makedepends.

**Comment by qumaciel** [comment]
> seems the flags will need to be altered as well, since right now it's checking to see if Optix is installed with pacman. Does it need anything more than [-DOPTIX_ROOT_DIR="$srcdir"/include](https://github.com/archlinux/svntogit-community/blob/2291ee7af8e8e6a3d09b1dd847e411c4950bb95a/trunk/PKGBUILD#L67)?

I think we need exactly what you mentioned: remove `optix` check, include this flag, and add source with checksum.


> `tbb2019` is missing `git` in makedepends.

Thank you!

**Comment by qumaciel** [comment]
I've just followed your link to Arch's `blender` I and noticed that, comparing with AUR, there are also extra things happening on `package()`:

```
  install -Dm755 release/bin/blender-softwaregl "${pkgdir}/usr/bin/blender-softwaregl"
  python -m compileall "${pkgdir}/usr/share/blender"
  python -O -m compileall "${pkgdir}/usr/share/blender"

  install -Dm644 release/freedesktop/org.blender.Blender.appdata.xml "${pkgdir}/usr/share/metainfo/org.blender.Blender.appdata.xml"

  # Manually install additional scripts (See FS#69351)
  cp -r release/scripts/addons_contrib/* "${pkgdir}"/usr/share/blender/3*/scripts/addons_contrib/

  # Manually install draco bindings (See FS#73415)
  mkdir -p "${pkgdir}"/usr/lib/python3.10/
  mv "${pkgdir}"/usr/share/blender/3*/python/lib/* "${pkgdir}"/usr/lib/
  rm -r "${pkgdir}"/usr/share/blender/3*/python
```

I don't know if I'll have time this week to follow FS#69351 and FS#73415 to see what happened there, but let me point it out for future reference.

**Comment by Technetium1** [comment]
@qumaciel we got an official update from Pixar about USD in the linked issue.

**Comment by adro79** [comment]
I uploaded an updated `usd` package based on the PKGBUILD that @qumaciel [provided on my issue.](https://github.com/PixarAnimationStudios/USD/issues/2000#issuecomment-1221549490)
Since I don't need USD for building blender, you can create a `usd-blender` based on my package and edit the necessary build options.

**Comment by dr460nf1r3** [comment]
Let's just inject the option via interfere, that is likely the easiest solution. Does the build() function change frequently @adro79 ?

**Comment by adro79** [comment]
> Let's just inject the option via interfere, that is likely the easiest solution. Does the build() function change frequently @adro79 ?

No afaik. But it will possibly change next year due to USD moving to CY2022.

I made the package without third-party plugins, everybody is free to add the build vars they need.

**Comment by dr460nf1r3** [comment]
https://github.com/chaotic-aur/interfere/commit/a8d4a9c6d5ed66c61894bebcebc48b558571853a

**Comment by qumaciel** [comment]
I was AFK for quite some time. I will close this, since we managed to address almost everything. 

Let us wait until we have `usd` working with more recent `tbb`. I've tried but I didn't manage to integrate it with blender as it is right now.
