### ISSUE TITLE
[Request] hardcode-tray

### ISSUE THREAD

**Issue by joe733** [chaotic-aur/packages#1654]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/hardcode-tray

### Utility this package has for you

> "The script will automatically detect your default theme, the correct icon size, the hard-coded applications, the correct icons for each indicator and fix them. All that with the possibility to revert to the original icons."

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
That's... unique.

**Comment by xiota** [comment]
```
error: hardcode-tray: signature from "Pedro Henrique Lara Campos <...>" is invalid
:: File ./hardcode-tray-4.3-3.1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
```

**Comment by Technetium1** [comment]
`Finished making: hardcode-tray 4.3-3.3 (Sun 07 May 2023 08:57:17 PM CEST)`
