### ISSUE TITLE
[Request] Dracula themes

### ISSUE THREAD

**Issue by jopejoe1** [chaotic-aur/packages#1655]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/dracula-gtk-theme-git
https://aur.archlinux.org/packages/dracula-xresources-git
https://aur.archlinux.org/packages/dracula-cursors-git
https://aur.archlinux.org/packages/dracula-icons-git
https://aur.archlinux.org/packages/dracula-grub-theme-git
https://aur.archlinux.org/packages/konsole-dracula-git

### Utility this package has for you

Uniform theming in my system.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping `dracula-gtk-theme-git` because orphaned and not clear if packaged correctly.

Metrics:

* dracula-grub-theme-git # 20
* dracula-gtk-theme-git # 302
* dracula-icons-git # 229
* dracula-xresources-git # 11
* konsole-dracula-git # 11
