### ISSUE TITLE
[Request] yacy-git

### ISSUE THREAD

**Issue by jopejoe1** [chaotic-aur/packages#1656]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/yacy-git

### Utility this package has for you

local and peer to peer search engine

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Build failed, needs investigated: https://builds.garudalinux.org/repos/chaotic-aur/logs/yacy-git.log

**Comment by Technetium1** [comment]
Also fails the same way in a clean chroot on my machine.

**Comment by Technetium1** [comment]
https://aur.archlinux.org/pkgbase/yacy-git/flag-comment I flagged the package.
`installonlinux` is no longer a valid target for `ant` in https://github.com/yacy/yacy_search_server/blob/master/build.xml

**Comment by VexfulNiko** [comment]
@Technetium1 pkgbuild been updated since yesterday, October 13th
