### ISSUE TITLE
[Request] battop

### ISSUE THREAD

**Issue by RohitSingh107** [chaotic-aur/packages#1657]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/battop

### Utility this package has for you

battop is an interactive viewer, similar to top, htop and other *top utilities, but about the batteries installed.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

https://github.com/svartalf/rust-battop

**Comment by Technetium1** [comment]
Great request!

**Comment by RohitSingh107** [comment]
We all love rust!
