### ISSUE TITLE
[Outdated] linux-xanmod-edge-headers

### ISSUE THREAD

**Issue by Inetol** [chaotic-aur/packages#1661]
### If available, link to the latest build

[linux-xanmod-edge & -headers](https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-xanmod-edge.log)

### Package name

`linux-xanmod-edge-headers`

### Latest build

`5.19.0-2`

### Latest version available

`5.19.2-1`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

idk if it should be published as a bug because in the logs it doesn't show any error but the version differs with "linux-xanmod-edge" making that if you have some package like "nvidia-dkms" (obviously) the environment breaks and you have to recover it from another Kernel or LiveCD.

**Comment by Technetium1** [comment]
Rebuild has completed
