### ISSUE TITLE
[Request] linux-xanmod & linux-xanmod-headers

### ISSUE THREAD

**Issue by EvoXCX** [chaotic-aur/packages#1662]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/linux-xanmod
https://aur.archlinux.org/packages/linux-xanmod-headers

### Utility this package has for you

Daily Kernel 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

All version of xanmod is here except stable

**Comment by xiota** [comment]
xanmod kernels are being reorganized:

* linux-xanmod-edge-x64v3
* linux-xanmod-x86v2
* linux-xanmod-lts
* linux-xanmod-rt

See [Wikipedia x86-64](https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels) for more info about microarchitecture levels.
