### ISSUE TITLE
[Request] uutils-coreutils-git

### ISSUE THREAD

**Issue by VexfulNiko** [chaotic-aur/packages#1664]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/uutils-coreutils-git

### Utility this package has for you

Coreutils but in faster and safer rust, pretty useful.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

It would be this PKGBUILD + a few modifications to only download and build uutils-coreutils. (Plus the vanilla package is already in chaotic aur, just requesting a version without GNU coreutils and just uutils.)

**Comment by Technetium1** [comment]
I was going to ask which package you wanted until I noticed we already have the one you linked. Sorry about the label spam, GitHub interface was being a bit buggy.

**Comment by Technetium1** [comment]
One of the tests will _always_ fail, since the package is not allowed to change group ownership outside chroot. Stupid test.
```
failures:

---- test_chgrp::test_reference stdout ----
current_directory_resolved:
run: /home/main-builder/pkgwork/src/coreutils/target/debug/coreutils chgrp -v --reference=/etc/passwd /etc
thread 'test_chgrp::test_reference' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
chgrp: changing group of '/etc': Operation not permitted (os error 1)
<failed to change group of '/etc' from 1002 to root
>failed to change group of '/etc' from root to root

', tests/common/util.rs:328:9

---- test_ls::test_ls_styles stdout ----
current_directory_resolved:
touch: /tmp/.tmphJXfEY/test
run: /home/main-builder/pkgwork/src/coreutils/target/debug/coreutils ls -l --time-style=full-iso
thread 'test_ls::test_ls_styles' panicked at 'assertion failed: re_full.is_match(result.stdout_str())', /home/main-builder/pkgwork/src/coreutils/tests/by-util/test_ls.rs:1660:5


failures:
test_chgrp::test_reference
test_ls::test_ls_styles

test result: FAILED. 1855 passed; 2 failed; 36 ignored; 0 measured; 5 filtered out; finished in 30.00s

error: test failed, to rerun pass '--test tests'
make: *** [GNUmakefile:286: test] Error 101
==> ERROR: A failure occurred in check().
Aborting...
```

**Comment by Technetium1** [comment]
@VexfulNiko No problem at all! That's what these issues are here for :)

**Comment by xiota** [comment]
Dropping because fails to build.  Maintainer ignored comment from 2024-03-02.  Metrics 2.

Use `extra/uutils-coreutils`.
