### ISSUE TITLE
[Request] wl-clipboard-rs

### ISSUE THREAD

**Issue by nyabinary** [chaotic-aur/packages#1667]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/wl-clipboard-rs
~~https://aur.archlinux.org/packages/wl-clipboard-rs-git~~

### Utility this package has for you

Clipboard, in Wayland with a Rust implementation.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Maybe get wl-clipboard-git as well seeing as wl-clipboard-x11 is already available in the repo.

**Comment by Technetium1** [comment]
Build fails https://builds.garudalinux.org/repos/chaotic-aur/logs/wl-clipboard-rs-git.log

**Comment by VexfulNiko** [comment]
It seems like the maintainer made another package called wl-clipboard-rs (non-git) that works, and even though it isn't marked as git, it appears to download and build directly from the git version from a glance at the PKGBUILD.
https://aur.archlinux.org/packages/wl-clipboard-rs

**Comment by VexfulNiko** [comment]
[PKGBUILD.txt](https://github.com/chaotic-aur/packages/files/9411058/PKGBUILD.txt)
I tried making a PKGBUILD of the git ver (modified the outdated/flagged build n fixed it). Tell me if I made any mistakes since this is my first time making/fixing a PKGBUILD.

**Comment by Technetium1** [comment]
```diff
@@ -1,37 +1,47 @@
-# Maintainer: Ivan Molodetskikh <yalterz@gmail.com>
+# Maintainer: Vextium <Discord: Vextium!#0001>
pkgname=wl-clipboard-rs-git
-pkgver=0.2.r0.gee298eb5
+pkgver=v0.6.0.r1.g78a6f3ec
pkgrel=1
+epoch=
pkgdesc="A safe Rust reimplementation of the Wayland command-line copy/paste utilities"
arch=('x86_64')
-url="https://github.com/YaLTeR/wl-clipboard-rs"
+url='https://github.com/YaLTeR/wl-clipboard-rs'
+source=("${pkgname}::git+https://github.com/YaLTeR/wl-clipboard-rs")
license=('MIT' 'APACHE')
-depends=('gcc-libs')
makedepends=('git' 'cargo')
+depends=('gcc-libs')
provides=('wl-clipboard')
conflicts=('wl-clipboard')
-source=("$pkgname::git+https://github.com/YaLTeR/wl-clipboard-rs")
-sha1sums=('SKIP')
-
-pkgver() {
-  cd "$pkgname"
-  git describe --long | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'
-}
+sha256sums=('SKIP')

build() {
-  cd "$pkgname"
+       cd "$pkgname/wl-clipboard-rs-tools"
+       CARGO_INCREMENTAL=0 cargo build --release
+}

-  cargo build --release
+check() {
+       cd "$pkgname/wl-clipboard-rs-tools"
+       CARGO_INCREMENTAL=0 cargo test --release
}

package() {
-  cd "$pkgname"
+       if [ ! -d "$pkgdir/usr/bin" ]; then
+               mkdir -p "$pkgdir/usr"
+       fi
+       CARGO_INCREMENTAL=0 cargo install --path "$pkgname/wl-clipboard-rs-tools" --root "$pkgdir/usr" --bins --frozen --offline
+
+       local _f
+       for _f in "$pkgdir"/usr/{.crates.toml,.crates2.json}; do
+               [ ! -e "$_f" ] || rm "$_f"
+       done

```
- You don't need epoch unless you're going to change it
- There are mixed single and double quotes now
- Should pkgver have `v` in front?

**Comment by VexfulNiko** [comment]
Created variables for easier management
Also used double quotes for things involving variables since they require double quotes
Removed the v problem (thanks for mentioning all of this btw
[PKGBUILD.txt](https://github.com/chaotic-aur/packages/files/9411905/PKGBUILD.txt)
)

**Comment by Technetium1** [comment]
```diff
diff --git a/PKGBUILD b/PKGBUILD
index 21a1f8a..ba11315 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -1,37 +1,50 @@
# Maintainer: Ivan Molodetskikh <yalterz@gmail.com>
-pkgname=wl-clipboard-rs-git
-pkgver=0.2.r0.gee298eb5
+# Contributor: Vextium <Discord: Vextium!#0001>
+
+_pkgname='wl-clipboard-rs'
+pkgname="${_pkgname}-git"
+pkgver=0.6.0.r1.g78a6f3ec
pkgrel=1
-pkgdesc="A safe Rust reimplementation of the Wayland command-line copy/paste utilities"
+pkgdesc='A safe Rust reimplementation of the Wayland command-line copy/paste utilities'
arch=('x86_64')
-url="https://github.com/YaLTeR/wl-clipboard-rs"
+url='https://github.com/YaLTeR/wl-clipboard-rs'
+source=("${_pkgname}::git+https://github.com/YaLTeR/wl-clipboard-rs")
license=('MIT' 'APACHE')
+makedepends=('git' 'rustup')
depends=('gcc-libs')
-makedepends=('git' 'cargo')
provides=('wl-clipboard')
conflicts=('wl-clipboard')
-source=("$pkgname::git+https://github.com/YaLTeR/wl-clipboard-rs")
-sha1sums=('SKIP')
-
-pkgver() {
-  cd "$pkgname"
-  git describe --long | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'
-}
+sha256sums=('SKIP')

build() {
-  cd "$pkgname"
+       cd "${_pkgname}/wl-clipboard-rs-tools"
+       CARGO_INCREMENTAL=0 cargo build --release
+}

-  cargo build --release
+check() {
+       cd "${_pkgname}/wl-clipboard-rs-tools"
+       CARGO_INCREMENTAL=0 cargo test --release
}

package() {
-  cd "$pkgname"
+       if [ ! -d "${pkgdir}/usr/bin" ]; then
+               mkdir -p "${pkgdir}/usr"
+       fi
+       CARGO_INCREMENTAL=0 cargo +nightly install --path "${_pkgname}/wl-clipboard-rs-tools" --root "${pkgdir}/usr" --bins

-  install -Dm755 "target/release/wl-copy" "$pkgdir/usr/bin/wl-copy"
-  install -Dm755 "target/release/wl-paste" "$pkgdir/usr/bin/wl-paste"
-  install -Dm755 "target/release/wl-clip" "$pkgdir/usr/bin/wl-clip"
+       local _f
+       for _f in "${pkgdir}"/usr/{.crates.toml,.crates2.json}; do
+               [ ! -e "$_f" ] || rm "$_f"
+       done

-  install -Dm644 "README.md" "$pkgdir/usr/share/doc/${pkgname}/README.md"
-  install -Dm644 "LICENSE-APACHE" "$pkgdir/usr/share/licenses/${pkgname}/LICENSE-APACHE"
-  install -Dm644 "LICENSE-MIT" "$pkgdir/usr/share/licenses/${pkgname}/LICENSE-MIT"
+       cd "${_pkgname}"
+
+       install -Dm644 "README.md" "${pkgdir}/usr/share/doc/${_pkgname}/README.md"
+       install -Dm644 -t "${pkgdir}/usr/share/licenses/${_pkgname}" LICENSE-APACHE LICENSE-MIT
+}
+
+pkgver() {
+       cd "${_pkgname}"
+       # removing v prefix that present in tags
+       git describe --long | sed "s/^v//;s/\([^-]*-g\)/r\1/;s/-/./g"
}
```
Here's the diff again, if you clone the AUR package and edit that PKGBUILD, you can run `git diff` and enclose the results in triple accents with `diff` at the end, then you get syntax highlighting too!

@YaLTeR you maintain this package, and it's been flagged since March. Do you possibly want to update the package according to this diff or add @VexfulNiko as a co-maintainer / contributor?

**Comment by YaLTeR** [comment]
Hey, I'd love for someone else to take the package over. How do I do that?

**Comment by Technetium1** [comment]
I have no idea on the specifics for sure, but I do know @VexfulNiko would need an AUR account setup. `Contributor` with contact info has already been added in the diff above.
