### ISSUE TITLE
[Request] waybar-experimental-git

### ISSUE THREAD

**Issue by VexfulNiko** [chaotic-aur/packages#1668]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/waybar-experimental-git

### Utility this package has for you

Highly customizable Wayland bar for Sway and Wlroots-based compositors, with experimental features enabled (GIT version)

--Required for Hyprland to have support

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Since hyprland-git was recently added to the repo, I suggest including waybar-experimental-git since the hyprland team recommends it and suggests it for use with Hyprland.

**Comment by xiota** [comment]
Dropping in favor of `waybar-git`, which also enables experimental features.
