### ISSUE TITLE
[Outdated] linux-next-git, linux-next-git-docs, linux-next-git-headers

### ISSUE THREAD

**Issue by VexfulNiko** [chaotic-aur/packages#1670]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-next-git.log

### Package name

linux-next-git, linux-next-git-docs, linux-next-git-headers

### Latest build

20220819

### Latest version available

20220823 (master)

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

AUR PKGBUILD (upstream) has been updated and is updated quite frequently.
https://aur.archlinux.org/pkgbase/linux-next-git

**Comment by Technetium1** [comment]
`Finished making: linux-next-git 20220823.r0.g05477f3653b8-1 (Tue 23 Aug 2022 05:39:58 PM UTC)`
