### ISSUE TITLE
[Outdated] linux-next-git (yes, again)

### ISSUE THREAD

**Issue by VexfulNiko** [chaotic-aur/packages#1675]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-next-git.log

### Package name

linux-next-git, linux-next-git-headers, linux-next-git-docs

### Latest build

20220823

### Latest version available

master (20220825)

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

Something is wrong with the PKGBUILD, it tries to run a signature check but fails, perhaps try putting 'SKIP' instead on the PKGBUILD.

**Comment by Technetium1** [comment]
It was due to a connection issue at build time, we don't want to skip the signature for that one. If source changes, it _should_ fail.

`Finished making: linux-next-git 20220825.r0.gb5d939c95186-1 (Thu 25 Aug 2022 04:42:43 PM UTC)`
