### ISSUE TITLE
[Request] nerd-fonts-hack

### ISSUE THREAD

**Issue by ConnorJC3** [chaotic-aur/packages#1677]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/nerd-fonts-hack

### Utility this package has for you

I like the [Hack font](https://sourcefoundry.org/hack/), this includes a [nerd-fonts](https://github.com/ryanoasis/nerd-fonts) patched version of the font. It will be useful to any users who also like the Hack font and want symbols in their terminal.

Chaotic-AUR already packages a few other variants (`nerd-fonts-fantasque-sans-mono`, `nerd-fonts-fira-code`, and `nerd-fonts-jetbrains-mono`), and Hack is the most popular of the remaining fonts not packaged.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
This is now provided by https://archlinux.org/packages/community/any/ttf-hack-nerd/
