### ISSUE TITLE
[Request]  broadcom-bt-firmware-git

### ISSUE THREAD

**Issue by xiota** [chaotic-aur/packages#1678]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/broadcom-bt-firmware

### Utility this package has for you

Needed for bluetooth on my computer to work.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
@Technetium1  Could you remove broadcom-bt-firmware and add broadcom-bt-firmware-git?  Upstream release version is v12.0.1.1105_p4, but the maintainer of broadcom-bt-firmware refuses to update from 10.1.0.1115.  (She unmarks the out-of-date flag without making any changes.)

**Comment by dr460nf1r3** [comment]
![image](https://user-images.githubusercontent.com/12834713/195896013-e835726a-bb11-4b59-bc09-59899c6aa27e.png)

Just for fun 😆
