### ISSUE TITLE
[Request] KCM modules

### ISSUE THREAD

**Issue by jopejoe1** [chaotic-aur/packages#1682]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/systemd-kcm
https://aur.archlinux.org/packages/kcm-polkit-kde-git
https://aur.archlinux.org/packages/fancontrol-kcm
https://aur.archlinux.org/packages/kcm-uefi
https://aur.archlinux.org/packages/kcm-grub2-git
https://aur.archlinux.org/packages/kcm-colorful-git
https://aur.archlinux.org/packages/fancontrol-kcm-git
https://aur.archlinux.org/packages/jackman-kcm-git

### Utility this package has for you

Managing more setting at the same place.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Guess I may as well add in the other few remaining KCM modules too, as they have a lot of votes. This will take a little bit.

**Comment by Technetium1** [comment]
- [ ] fancontrol-kcm
- [ ] fancontrol-kcm-git
- [ ] garuda-settings-manager-kcm-git
- [ ] jackman-kcm-git
- [ ] kcm-colorful-git
- [ ] kcm-grub2-git
- [ ] kcm-imchooser-frameworks
- [ ] kcm-lookandfeel-standalone-git
- [ ] kcm-polkit-kde-git
- [ ] kcm-tablet-git
- [ ] kcm-uefi
- [ ] kcm-wacomtablet-git
- [ ] kcm_webcam
- [ ] kcmutils-git
- [ ] kde1-kcmlaptop-git
- [ ] lxqt-kcm-integration-extra-git
- [ ] nx-firewall-git
- [ ] plymouth-kcm
- [ ] sddm-kcm-git
- [ ] systemd-kcm
- [ ] telepathy-kde-accounts-kcm-git
- [ ] deepin-kcm-integration-git - **orphan**
- [ ] polkit-kde-kcmodules-frameworks - **orphan**
- [ ] lxqt-kcm-integration-git - **orphan**
- [ ] nomad-firewall-git - **orphan**

**Comment by jopejoe1** [comment]
> kcm-grub2-git - Impossible, no old enough imagemagick6

imagemagick6 can be replaced with regular imagemagick and it compiles fine also the prepare section should be removed as a .desktop file is no longer included.

> kcm-imchooser-frameworks [broken](https://builds.garudalinux.org/repos/chaotic-aur/logs/kcm-imchooser-frameworks.log)

Missing dependency kdesignerplugin and kdelibs4support

**Comment by Technetium1** [comment]
Fixed `fancontrol-kcm-git` source URL in: https://github.com/chaotic-aur/interfere/commit/0c3a988d04ffc8c089a83cc547593cd56d2d6bb6 & marked package outdated.

**Comment by Technetium1** [comment]
@jopejoe1 it still fails: [kcm-imchooser-frameworks.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/kcm-imchooser-frameworks.log)

**Comment by jopejoe1** [comment]
> @jopejoe1 it still fails: [kcm-imchooser-frameworks.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/kcm-imchooser-frameworks.log) Other logs are also updated

Also missing 'kinit' as dependency

> kcm-lookandfeel-standalone-git [broken](https://builds.garudalinux.org/repos/chaotic-aur/logs/kcm-lookandfeel-standalone-git.log)

Missing dependencies `plasma-framework kcmutils kdoctools krunner kdelibs4support kdesignerplugin knewstuff knotifyconfig libxcursor`

> kcm-tablet-git [broken](https://builds.garudalinux.org/repos/chaotic-aur/logs/kcm-tablet-git.log)

Missing dependencies `plasma-framework kcmutils git`

> kcm_webcam

Source URL should be changed to `https://web.archive.org/web/20150923064016if_/http://kde-apps.org/CONTENT/content-files/119405-kcm.tar.gz` but that doesn't really help as I can't get `kdelibs` to build even with it missing dependency to `'pcre'` being added.

> sddm-kcm-git

This build perfectly fine in a clean chroot for me, so no idea what the issue is.

**Comment by Samisafool** [comment]
Guys, plymouth-kcm is borked.
```
(1/1) checking keys in keyring                                                                   [--------------------------------------------------------] 100%
(1/1) checking package integrity                                                                 [--------------------------------------------------------] 100%
(1/1) loading package files                                                                      [--------------------------------------------------------] 100%
(1/1) checking for file conflicts                                                                [--------------------------------------------------------] 100%
error: failed to commit transaction (conflicting files)
plymouth-kcm: /bin exists in filesystem (owned by filesystem)
plymouth-kcm: /lib exists in filesystem (owned by filesystem)
Errors occurred, no packages were upgraded.
```

**Comment by xiota** [comment]
Dropping rest of these packages because they have not been updated for KF6.
