### ISSUE TITLE
[Request] webcord & webcord-git

### ISSUE THREAD

**Issue by BowDown097** [chaotic-aur/packages#1683]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/webcord

### Utility this package has for you

Has features and fixes not present in the normal Discord client, such as built-in theming, extensions, and screensharing with audio, with many more planned. Also has many security and privacy improvements.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Edited because I also want to add `webcord-git` for myself :upside_down_face:
