### ISSUE TITLE
[Request] linux-git

### ISSUE THREAD

**Issue by jopejoe1** [chaotic-aur/packages#1684]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/linux-git

### Utility this package has for you

I like my system to break

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because:

* Linux kernels are resource intensive to build.
* I prefer to direct resources and effort into keeping other kernels working.
* `linux-mainline` release candidates should be sufficient for end-user testing.
    * git kernels are prone to bugs that can lead to data loss.
    * kernel devs should build their own branches.
