### ISSUE TITLE
[Request] anime4k & anime4k-git

### ISSUE THREAD

**Issue by xiota** [chaotic-aur/packages#1685]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/anime4k

### Utility this package has for you

This package provides glsl up-scalers trained on anime.  Can be used with mpv and other video players.  Useful for viewing animated HD content in 4k.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
I also want [`anime4k-git`](https://aur.archlinux.org/packages/anime4k-git)

**Comment by Technetium1** [comment]
Should have been closed by https://github.com/chaotic-aur/packages/commit/a71976a9cb24c1ac8b72984b189168ab12089833, I fat-fingered the number :man_facepalming:

**Comment by xiota** [comment]
Dropping `anime4k` (last release 4.0.1 in Sep 2021) because shaders are included in `extra/mpv-shim-default-shaders`.  Metrics 14.

Keeping `anime4k-git` because there are significant post-release commits. Metrics 8.
