### ISSUE TITLE
[Request] AMD FidelityFX Super Resolution and NVIDIA Image Scaling

### ISSUE THREAD

**Issue by xiota** [chaotic-aur/packages#1688]
### Link to the package(s) in the AUR

No AUR package exists at the moment.  Source is available in a [github gist](https://gist.github.com/agyild/).  I am interested in adding it to the AUR, but don't know what the package should be named or how to pull sources from a gist.

### Utility this package has for you

FSR and NIS are super scaling algorithms that are useful for viewing general HD content in 4k.  These are glsl shaders that can be used with mpv and other video players.  This should be of interest to anyone who is interested in the anime4k package.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by SolarAquarion** [comment]
You need to package it first, for example look at the mpv hierarchy

**Comment by xiota** [comment]
Yes, I know I need to package it first.  But gists don't have project names, so I'm asking here if there's any preference about how it should be named.

**Comment by Technetium1** [comment]
Well, if it's going to be for example a patched version of MPV, maybe it would be good to call it something like `mpv-fxr`, but it should still provide `mpv`.

**Comment by xiota** [comment]
I'm thinking of naming the package `glsl-fsr-nis`, and installing the files to `/usr/share/glsl-fsr-nis`.  They're glsl shaders, like anime4k, so they work with unmodified mpv by adding to `mpv.conf`:

    scale=filter
    glsl-shader=/path/to/file.glsl

Or `input.conf`:

    CTRL+0 no-osd change-list glsl-shaders clr ""; show-text "GLSL shaders cleared"
    CTRL+1 no-osd change-list glsl-shaders set "/path/to/file.glsl"; show-text "name of shader"

**Comment by SolarAquarion** [comment]
It won't be a patched version of mpv. It's just a shader that exists in a
system directory.  MPV doesn't have any shaders by default, instead you add
them to ~/.config/mpv/shaders

**Comment by xiota** [comment]
Closing because... Someone else made a package... Available at `extra/mpv-shim-default-shaders`.
