### ISSUE TITLE
[Request] Glaxnimate

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1691]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/glaxnimate
https://aur.archlinux.org/packages/glaxnimate-git

### Utility this package has for you

I am a video editor and recently Kdenlive added support for glaxnimate animations which is a game changer in my view. Shortcut also has such a feature. So glaxnimate not only it is a great animation app on its own, but integrates well with the most well-known video editors in Linux.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
I left [a comment](https://aur.archlinux.org/packages/glaxnimate-git#comment-879427) about the missing dependency.

**Comment by xiota** [comment]
@tio-trom `glaxnimate` was dropped last month because of build issues.  Those issues have now been resolved.  Please let me know whether the stable package is still wanted and should be added back.

**Comment by tio-trom** [comment]
Yes would be nice to have the stable package if possible. Thank you!

**Comment by xiota** [comment]
Dropping `glaxnimate` because moved to extra.

Metrics:

* glaxnimate # 99
* glaxnimate-git # 41
