### ISSUE TITLE
[Request] noto-fonts-emoji-flag-git

### ISSUE THREAD

**Issue by jopejoe1** [chaotic-aur/packages#1692]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/noto-fonts-emoji-flag-git

### Utility this package has for you

More region flags than the standard noto emoji package

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
```
# Issue 1692
python-pyclipper
python-booleanoperations
python-defcon
python-nototools
noto-fonts-emoji-flag-git
```

**Comment by xiota** [comment]
Request to remove the following because they are in the community repository:

* `python-pyclipper`
* `python-booleanoperations`
* `python-defcon`

**Comment by dr460nf1r3** [comment]
Closing this one then! Thanks for taking care :)

**Comment by xiota** [comment]
Dropping because AUR package is orphaned.  Metrics 36.
