### ISSUE TITLE
[Request] qt-jdenticon

### ISSUE THREAD

**Issue by bbhtt** [chaotic-aur/packages#1694]
### Link to the package(s) in the AUR

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=qt-jdenticon

### Utility this package has for you

Nheko is already in the Chaotic AUR but not one of its optional dependencies. qt-jdenticon is optionally needed by Nheko to generate Github-like avatars for users (identicons)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

N/A

**Comment by xiota** [comment]
Switched to Qt6 version.  Metrics 3.
