### ISSUE TITLE
[Request] Alephone-Marathon

### ISSUE THREAD

**Issue by coolio321** [chaotic-aur/packages#1695]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/alephone-marathon

### Utility this package has for you

It is an AUR package for a free and open source game, I find it very fun to play from time to time, however it takes ages for me to compile on my computer.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Should we compile *all* of https://aur.archlinux.org/packages/alephone ?

---

[alephone-eternalx ](https://aur.archlinux.org/packages/alephone-eternalx)(optional) – community-made scenario
[alephone-evil ](https://aur.archlinux.org/packages/alephone-evil)(optional) – community-made scenario
[alephone-infinity ](https://aur.archlinux.org/packages/alephone-infinity)(optional) – original data for Marathon Infinity
[alephone-marathon ](https://aur.archlinux.org/packages/alephone-marathon)(optional) – M1A1 data converted for AlephOne
[alephone-marathon2 ](https://aur.archlinux.org/packages/alephone-marathon2)(optional) – original data for Marathon 2: Durandal

**Comment by Technetium1** [comment]
@coolio321 is there still interest in getting this added?

**Comment by Technetium1** [comment]
Please reopen if there is interest in this in the future
