### ISSUE TITLE
[Request] ruffle-git

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#1697]
### Link to the package(s) in the AUR

[ruffle-git](https://aur.archlinux.org/packages/ruffle-git)

### Utility this package has for you

It's an open source Flash player written in Rust. It's actively developed and constantly improving. The only viable alternative to the increasingly outdated proprietary Flash player. I use it to play old flash games and view old flash animations.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
@FabioLolix please let us know when you update it :)

**Comment by niobium93** [comment]
He promised an update a month ago and still nothing...

**Comment by FabioLolix** [comment]
pkgbuild is update now, I've made the update some days ago https://github.com/FabioLolix/PKGBUILD-AUR_fix/commit/b061c5bbbb094a1b9e0d13b0fea8798d92b9c217 but forgot to push it
