### ISSUE TITLE
[Request] czkawka-gui

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1699]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/czkawka-gui-bin
https://aur.archlinux.org/packages/czkawka-gui

### Utility this package has for you

It is a great tool to find  duplicates, empty folders, similar images etc. We use it for our TROMjaro distro. tested, works great.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
[czkawka pkgbase](https://aur.archlinux.org/pkgbase/czkawka) has [czkawka-gui](https://aur.archlinux.org/packages/czkawka-gui) included, so let's skip [czkawka-gui-bin](https://aur.archlinux.org/packages/czkawka-gui-bin)?

**Comment by tio-trom** [comment]
Yup sounds good!

**Comment by xiota** [comment]
`aur/czkawka` currently fails to build.  If not fixed "soon", may switch to `aur/czkawka-git`.
