### ISSUE TITLE
[Request] easystroke

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1700]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/easystroke
~~https://aur.archlinux.org/packages/easystroke-git~~ build broken

### Utility this package has for you

I think this is the best mouse gesture application. Used it for the past several years. Works like a charm.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
`easystroke` works, but `easystroke-git` does not, maybe missing a library that it expects? Error is not very descriptive to me: https://builds.garudalinux.org/repos/chaotic-aur/logs/easystroke-git.log

**Comment by tio-trom** [comment]
Ah yes I think I remember failing with the git. Let's leave the non-git only. Is that ok?
