### ISSUE TITLE
[Request] libadwaita-without-adwaita, libadwaita-without-adwaita-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1701]
### Package

https://aur.archlinux.org/packages/libadwaita-without-adwaita-git
https://github.com/chaotic-aur/packages/tree/main/libadwaita-without-adwaita (custom)

Reference:
https://aur.archlinux.org/packages/libadwaita-without-adwaita

### Purpose

For those who want a consistent theming experience, this package allows for the automatic theming of libadwaita apps. We use it for TROMjaro and packaged it for our repo. All works great.

### License

LGPL-2.1-or-later

**Comment by tio-trom** [comment]
This package is very important and can break many other apps. They updated from 1.1 to 1.2 and already a bunch of apps do not work. The maintainer of the AUR seems to not respond very quickly but the fix is super simple, to bump the version to 1.2 in the pkgfile. Tested and works. Can you push a fix for the chaotic aur perhaps?

**Comment by Technetium1** [comment]
@tio-trom manually built now as a one-off (not using interfere). Let me know when the package maintainer updates, in case they do something of a bigger change, or if something fails to patch correctly.

**Comment by Technetium1** [comment]
`Finished making: libadwaita-without-adwaita-git 1.2.0-1 (Wed 28 Sep 2022 06:25:48 PM CEST)`

**Comment by tio-trom** [comment]
Thank you. I keep a close eye on this package since we also package it for our repo.

**Comment by tio-trom** [comment]
Main package got updated https://aur.archlinux.org/packages/libadwaita-without-adwaita-git

**Comment by Technetium1** [comment]
Built the new version, we match exactly again.

**Comment by xiota** [comment]
I'm considering adding the stable package, possibly custom package with updater, because -git package doesn't build with extra/gtk4.  Then, may drop the -git package later.

Another option is to rebuild the -git package only on new stable releases.  Then it wouldn't "really" be a -git package anymore, but would stop the repeated failed rebuild attempts.
