### ISSUE TITLE
[Request] riseup-vpn-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1703]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/riseup-vpn-git

### Utility this package has for you

Perhaps the only purely free VPN out there. No subscriptions or freemiums or data collection. We use it for our distro and have tested it for over a year now. The git package is the one that works.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because depends on nonexistent package.
