### ISSUE TITLE
[Request] vala-panel-appmenu

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1705]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/vala-panel
https://aur.archlinux.org/packages/vala-panel-appmenu-xfce-git
https://aur.archlinux.org/packages/vala-panel-appmenu-xfce
https://aur.archlinux.org/packages/vala-panel-appmenu-valapanel-git
https://aur.archlinux.org/packages/vala-panel-appmenu-valapanel
https://aur.archlinux.org/packages/vala-panel-appmenu-mate-git
https://aur.archlinux.org/packages/vala-panel-appmenu-mate
https://aur.archlinux.org/packages/vala-panel-appmenu-common-git
https://aur.archlinux.org/packages/vala-panel-appmenu-budgie-git
https://aur.archlinux.org/packages/vala-panel-appmenu-budgie
https://aur.archlinux.org/packages/vala-panel-appmenu-jayatana-git

### Utility this package has for you

It provides an global menu for many desktop environments. I think global menus are really useful!

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

I only tested a few of these for the past 2 or so years.

**Comment by Technetium1** [comment]
`vala-panel-*` is all done by 2 maintainers, which means they're probably all updated, so let's add them all!

**Comment by Technetium1** [comment]
- [ ] vala-panel-applets-icontasks-git
- [ ] vala-panel-applets-xembed-git
- [ ] vala-panel-appmenu-budgie
- [ ] vala-panel-appmenu-budgie-git
- [ ] vala-panel-appmenu-common
- [ ] vala-panel-appmenu-common-git
- [ ] vala-panel-appmenu-jayatana-git
- [ ] vala-panel-appmenu-mate
- [ ] vala-panel-appmenu-mate-git
- [ ] vala-panel-appmenu-registrar
- [ ] vala-panel-appmenu-registrar-git
- [ ] vala-panel-appmenu-valapanel
- [ ] vala-panel-appmenu-valapanel-git
- [ ] vala-panel-appmenu-xfce
- [ ] vala-panel-appmenu-xfce-git
- [ ] vala-panel-extras-battery-git
- [ ] vala-panel-extras-common-git
- [ ] vala-panel-extras-gtop-git
- [ ] vala-panel-extras-volume-git
- [ ] vala-panel-extras-weather-git
- [ ] vala-panel-extras-xkb-flags-git
- [ ] vala-panel-extras-xkb-git
- [ ] vala-panel-genmon-git
- [ ] vala-panel-git
- [ ] vala-panel-sntray-git

**Comment by Technetium1** [comment]
Skipping `vala-panel-appmenu-xfce-git` and `vala-panel-extras-git` due to the errors. I'm not sure how to fix them, and it looks like a bigger problem with them than I know how to fix. Open another issue for either independently if you want them!

**Comment by tio-trom** [comment]
Did we forget to add "vala-panel-appmenu-registrar" https://aur.archlinux.org/packages/vala-panel-appmenu-registrar ? Or was it not added for a particular reason? (https://aur.archlinux.org/packages/vala-panel-appmenu-registrar#comment-879787) ?

**Comment by Technetium1** [comment]
Oops

**Comment by Technetium1** [comment]
I missed that one before. `vala-panel-appmenu-registrar-git` was already added in #469

**Comment by tio-trom** [comment]
I see https://aur.archlinux.org/packages/vala-panel-appmenu-xfce and  https://aur.archlinux.org/packages/vala-panel-appmenu-common have been dropped.

**Comment by tio-trom** [comment]
I see you have labeled it as a request to remove it. Would you not want to include this in chaotic?

**Comment by Hayao0819** [comment]
Sorry. I have no time to mentain such a complex PKGBUILD.

**Comment by tio-trom** [comment]
I understand. I see that all of the vala panel packages are already in chaotic's repos, only the mentioned two are not, despite their git versions behind in the repo. Is it that difficult to add those 2 non-git ones again?

Also, these packages are so unique to the linux community since they provide global menus, something only these packages can provide independently from my knowledge.

**Comment by Technetium1** [comment]
@tio-trom I've rebuilt packages, everything here is back now, at least for as long as the AUR packages exist in working order.

**Comment by xiota** [comment]
Dropping stable packages for poor maintenance.

**Comment by tio-trom** [comment]
Ok. I wanted to mention that in fact I was referring to the git packages conflicting with each other.

**Comment by xiota** [comment]
The non-git packages are no longer building successfully.  If the git packages are also broken, they should also be dropped.

I understand the utility of global menu, but there is no point keeping broken packages that the maintainer has quit updating.

**Comment by tio-trom** [comment]
But the vala panel package is maintained https://gitlab.com/vala-panel-project/vala-panel-appmenu - last update a week ago. And vala-panel-appmenu-xfce-git is also maintained (updated a few days ago) https://aur.archlinux.org/pkgbase/vala-panel-appmenu-xfce-git

**Comment by xiota** [comment]
Doesn't matter that the upstream project is maintained.  The updates are not making it downstream because the AUR package is not maintained.  Last updated 2022-09-16.  https://aur.archlinux.org/pkgbase/vala-panel-appmenu

**Comment by tio-trom** [comment]
Maybe I am a bit confused by these packages, but how is the https://aur.archlinux.org/pkgbase/vala-panel-appmenu use for say https://aur.archlinux.org/pkgbase/vala-panel-appmenu-xfce-git? Looking at the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vala-panel-appmenu-xfce-git) file it seems to pull from the main: https://gitlab.com/vala-panel-project/vala-panel-appmenu

**Comment by xiota** [comment]
There are stable and git sets of packages on AUR.  The stable packages (https://aur.archlinux.org/pkgbase/vala-panel-appmenu) are currently in unmaintained state and have already been dropped from chaotic aur.

The git packages (https://aur.archlinux.org/pkgbase/vala-panel-appmenu-xfce-git) were last updated a few months ago.  However, there is currently a file conflict across the subpackages.

The git packages have been rebuilt, and I am unable to reproduce the issue described at https://gitlab.com/vala-panel-project/vala-panel-appmenu/-/issues/387#note_1892946705.  However, the vala-panel version of the applet does not seem to be working.

**Comment by xiota** [comment]
Dropping the genmon packages.  They regularly show up in my screenings for problem packages, and metrics show low single-digit usage.  Not worth the effort to keep them working.

**Comment by xiota** [comment]
I'm reorganizing packages so git packages are listed under https://github.com/chaotic-aur/packages/issues/1944 and stable packages will be listed under https://github.com/chaotic-aur/packages/issues/1705.
