### ISSUE TITLE
[Request] warp

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1707]
### Link to the package(s) in the AUR

~~https://aur.archlinux.org/packages/warp-git~~ broken build
https://aur.archlinux.org/packages/warp

### Utility this package has for you

One of the easiest and fastest ways of sending files to anyone in the world. No limitations. We use it for our distro as the main send-app. Tested for a few months now.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
We also build one of my favorites: `croc-git` https://github.com/schollz/croc

**Comment by tio-trom** [comment]
> We also build one of my favorites: `croc-git` https://github.com/schollz/croc

Yup heard of it. I personally am not that used to using CLI applications but it does look like a good and simple one.

**Comment by Technetium1** [comment]
[`warp-git`](https://builds.garudalinux.org/repos/chaotic-aur/logs/warp-git.log) fails with code 4.
> error: could not find system library 'libadwaita-1' required by the 'libadwaita-sys' crate

**Comment by tio-trom** [comment]
Ok interesting. I tested warp and that works. So perhaps we can, again, leave the non-git one please.
