### ISSUE TITLE
[Remove] zafiro-icon-theme

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1709]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/zafiro-icon-theme

### Utility this package has for you

It is a very well maintained icon theme. We too create hundreds of icons for it.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

The git package is broken...

**Comment by xiota** [comment]
Dropping because orphaned and cannot fix.  Metrics 78.

Package was flagged years ago because upstream versions don't match: 

* https://www.opendesktop.org/s/Cinnamon/p/1209330
* https://github.com/zayronxio/Zafiro-icons

Cannot fix because upstream hasn't been tagging.
