### ISSUE TITLE
[Request] micropad

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1711]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/micropad

### Utility this package has for you

Quite a unique notes taking app. You can even paste videos, audio files and such into it.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
```
==> Creating package "micropad"...
-> Generating .PKGINFO file...
-> Generating .BUILDINFO file...
-> Adding install file...
-> Generating .MTREE file...
-> Compressing package...
: Can't translate pathname 'opt/µPad/' to UTF-8: Can't translate pathname 'opt/µPad/micropad' to UTF-8: Can't translate pathname 'opt/µPad/resources/' to UTF-8: Can't translate pathname 'opt/µPad/resources/app.asar' to UTF-8: Can't translate pathname 'opt/µPad/resources/app.asar.unpacked/' to UTF-8: Can't translate pathname 'opt/µPad/resources/app.asar.unpacked/preload.js' to UTF-8: Can't translate linkname '/opt/µPad/micropad' to UTF-8==> Leaving fakeroot environment.
==> Finished making: micropad 3.30.6-1 (Tue 30 Aug 2022 03:01:25 PM UTC)
```

**Comment by Technetium1** [comment]
If this doesn't work as expected, please comment here.

**Comment by xiota** [comment]
Dropping because uses EOL Electron/28.1.0.  There is a more recent upstream release, but it uses EOL Electron 31.7.0.  Metrics 4.
