### ISSUE TITLE
[Request] gnome-multi-writer-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1713]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/gnome-multi-writer-git

### Utility this package has for you

Write an ISO file to multiple USB devices at once

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
@tio-trom Etcher has support for multiwriting already: https://www.balena.io/blog/etcher-now-with-multi-write-and-compute-module-support/, are you sure you want to request this even though it's not being frequently updated?

**Comment by tio-trom** [comment]
> @tio-trom Etcher has support for multiwriting already: https://www.balena.io/blog/etcher-now-with-multi-write-and-compute-module-support/, are you sure you want to request this even though it's not being frequently updated?

Etcher is what we will not consider as trade-free since it inserts ads into the app itself, and promotional content. At least the latter. That's what I remember from our tests.

**Comment by Technetium1** [comment]
It does in fact have a Balena related 'ad' type thing in the flash screen, fair point.

**Comment by xiota** [comment]
Dropping because `extra/gnome-multi-writer` is available.
