### ISSUE TITLE
[Remove] popcorntime-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1717]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/popcorntime-git

### Utility this package has for you

Stream videos from torrents. Skip the downloads. Launch, click, watch.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
@tio-trom we do not have `popcorntime-git`, you can still request that if you want.

**Comment by tio-trom** [comment]
Ok reopening. Thanks!

**Comment by Technetium1** [comment]
Missing NPM https://builds.garudalinux.org/repos/chaotic-aur/logs/popcorntime-git.log

**Comment by Technetium1** [comment]
I left [a comment](https://aur.archlinux.org/packages/popcorntime-git#comment-879753) for the maintainer.

**Comment by xiota** [comment]
`popcorntime-git` builds without `npm`, but produces an error message.  I dropped the interfere before noticing the message.  However, the package has other issues and is dysfunctional, even with `npm`.  Maintainer never responded to Aug 2022 comment.

Considering dropping this package.  Fixing via interfere would probably require override.  Metrics is 7.  3-4 of those are my test builds.  Doesn't seem worthwhile.  `popcorntime` (#733) is available and functional.

**Comment by xiota** [comment]
Dropping.  Still has packaging issues and produces error on run.
```
popcorntime: error while loading shared libraries: libnw.so: cannot open shared object file: No such file or directory
```
