### ISSUE TITLE
[Request] akira + akira-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1719]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/akira
https://aur.archlinux.org/packages/akira-git

### Utility this package has for you

Native Linux App for UI and UX Design built in Vala and Gtk

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping akira-git because it was orphaned and adopted by a malicious maintainer.  Compromised commit was not built.

Stable version is still maintained and available.

Metrics:

* akira # 7
* akira-git # 4
