### ISSUE TITLE
[Request] alphaplot-git 

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1720]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/alphaplot-git

### Utility this package has for you

Application for Scientific Data Analysis and Visualization

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

The non-git version is no updated in months.

**Comment by Technetium1** [comment]
Build fails: [alphaplot-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/alphaplot-git.log)

**Comment by Technetium1** [comment]
@dr460nf1r3 maybe running out of memory is causing it to be killed prematurely?

**Comment by dr460nf1r3** [comment]
Mhm I doubt it, though we could of course try building on another machine 🤔

**Comment by Technetium1** [comment]
Tested on another builder and got further with a very similar error. Not sure how to make progression for this.

**Comment by tio-trom** [comment]
What if we try the non git version https://aur.archlinux.org/packages/alphaplot-bin - more specifically the bin.

**Comment by xiota** [comment]
`alphaplot-git` has several issues.  Correcting them allows it to build.  Have flagged package.

* unnecessary depends on `qt5-xmlpatterns`
* missing depends on `glu`
* extraneous `-j` that apparently causes build to fail by running out of memory
