### ISSUE TITLE
[Request] amule-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1722]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/amule-git

### Utility this package has for you

Client for the eD2k and Kad networks

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Build fails: https://builds.garudalinux.org/repos/chaotic-aur/logs/amule-git.log
```
checking for wx-config... no
configure: error: 
		wxWidgets must be installed on your system but wx-config
		script couldn't be found. Please check that wx-config is
		in path or specified by --with-wx-config=path flag, the
		directory where wxWidgets libraries are installed (returned
		by 'wx-config --libs' command) is in LD_LIBRARY_PATH or
		equivalent variable and wxWidgets version is 2.8.12 or above.
```

**Comment by Technetium1** [comment]
It installed `wxwidgets-gtk2-3.2.0-4` & `wxwidgets-common-3.2.0-5`

**Comment by tio-trom** [comment]
> It installed `wxwidgets-gtk2-3.2.0-4` & `wxwidgets-common-3.2.0-5`

From my knowledge it takes a long time to build those. If amule-git is not playing well, you can drop it from my perspective.

**Comment by Technetium1** [comment]
we already build wxwidgets, so it's no extra burden.

**Comment by FabioLolix** [comment]
amule-git no longer require wxgtk2
