### ISSUE TITLE
[Request] app-icon-preview + app-icon-preview-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1723]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/app-icon-preview
https://aur.archlinux.org/packages/app-icon-preview-git

### Utility this package has for you

Tool for designing applications icons

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
`-git` variant dropped last year because of libadwaita issues.  Dropping stable package now because moved to extra repo.
