### ISSUE TITLE
[Request] xfce4-appfinder-devel + xfce4-appfinder-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1724]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/xfce4-appfinder-devel
https://aur.archlinux.org/packages/xfce4-appfinder-git

### Utility this package has for you

An application finder for Xfce. The main one for our TROMjaro. Works like a charm.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Is there any need for these packages?  What benefit do they provide over `extra/xfce4-appfinder`?  Packages have defects, and maintainer ignores comments.  Metrics are devel 16, git 9.

**Comment by tio-trom** [comment]
hm yes true. no need for them. thanks for checking you can drop them
