### ISSUE TITLE
[Request] astrofox

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1726]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/astrofox

### Utility this package has for you

A motion graphics program that lets turn audio into amazing videos

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
This one's super cool

**Comment by xiota** [comment]
Dropping because electron19.
