### ISSUE TITLE
[Request] notion-app-enhanced

### ISSUE THREAD

**Issue by DenjixPochita** [chaotic-aur/packages#1731]
### Link to the package(s) in the AUR

[notion-app-enhanced](https://aur.archlinux.org/packages/notion-app-enhanced)

### Utility this package has for you

Enhances the Notion experience.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because uses EOL Electron/11.5.0.  Metrics 110.
