### ISSUE TITLE
[Request] A few nice fonts

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1732]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/ttf-aller
https://aur.archlinux.org/packages/audiowide-font
https://aur.archlinux.org/packages/ttf-bangers
https://aur.archlinux.org/packages/ttf-djb-zora-prints-fonts
https://aur.archlinux.org/packages/xorg-font-utils - dep ttf-geosans-light ttf-iskpota
https://aur.archlinux.org/packages/ttf-geosans-light
https://aur.archlinux.org/packages/ttf-iskpota
https://aur.archlinux.org/packages/fonts-kalam
https://aur.archlinux.org/packages/ttf-pacifico

### Utility this package has for you

These are some of the fonts we use for TROMjaro. I hope you accept fonts too. Could be useful. If you think not, is ok. You can close this issue :).

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping `ttf-pacifico` because source 404 and maintainer MIA.
