### ISSUE TITLE
[Request] backintime + backintime-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1733]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/backintime-git
https://aur.archlinux.org/packages/backintime

### Utility this package has for you

Simple backup system inspired from the Flyback Project and TimeVault. QT5 GUI version.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Tests fail on both, need to find out why before I just skip doing the tests:
[backintime-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/backintime-git.log)
[backintime.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/backintime.log)

```
-m unittest  -b test/test_tools.py
WARNING: import keyring failed
.....s..F.Fs.s..s......s................s..s.s...ss.s.s.............
======================================================================
FAIL: test_device (test.test_tools.TestTools)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/main-builder/pkgwork/src/backintime-1.3.2/common/test/test_tools.py", line 447, in test_device
self.assertRegex(tools.device('/nonExistingFolder/foo/bar'),
AssertionError: Regex didn't match: '(:?/dev/.*|tmpfs)' not found in 'overlay'

======================================================================
FAIL: test_filesystem (test.test_tools.TestTools)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/main-builder/pkgwork/src/backintime-1.3.2/common/test/test_tools.py", line 453, in test_filesystem
self.assertRegex(tools.filesystem('/nonExistingFolder/foo/bar').lower(),
AssertionError: Regex didn't match: '(:?ext[2-4]|xfs|zfs|jfs|raiserfs|btrfs|tmpfs)' not found in 'overlay'

----------------------------------------------------------------------
```

**Comment by Technetium1** [comment]
We found the issue! The maintainer is responsive, and it's an upstream issue, so we will wait a short while before I bother adding to interfere to fix these.

**Comment by Technetium1** [comment]
This will fix the problem with tests: https://github.com/bit-team/backintime/pull/1390

**Comment by Technetium1** [comment]
Waiting on `backintime` to bump to next version.
