### ISSUE TITLE
[Request] bookworm-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1739]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/bookworm-git

### Utility this package has for you

A simple user centric eBook reader which displays multiple eBooks formats uniformly

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
For future reference, current stable release 1.1.2 was tagged in 2019.

**Comment by xiota** [comment]
Dropping because of low usage and depends on deprecated `webkit2gtk`.  Metrics 4.
