### ISSUE TITLE
[Request] csound-blue

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1740]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/csound-blue

### Utility this package has for you

A music composition environment for Csound

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping.  Crashes on startup.  Metrics 0.
