### ISSUE TITLE
[Request] canta themes

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1741]
### Link to the package(s) in the AUR

https://aur.archlinux.org/pkgbase/canta-theme
https://aur.archlinux.org/pkgbase/canta-theme-git
https://aur.archlinux.org/packages/canta-kde-git

### Utility this package has for you

Flat Material Design theme

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
`canta-kde-git` was deleted from AUR.  These packages haven't been updated since 2021.  Are the GTK themes still working/wanted?

**Comment by tio-trom** [comment]
I agree drop them. Thank you for checking!
