### ISSUE TITLE
[Remove] copypastegrab-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1745]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/copypastegrab-git

### Utility this package has for you

A shell wrapper for youtube-dl that downloads videos from websites. 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Planning to drop.

* This package depends on `youtube-dl`.  Does not work with `yt-dlp` (but does with `youtube-dl-git`).
* `pkgver()` and `depends`/`makedepends` need to be updated.
* Upstream project has no commits since 2018.
