### ISSUE TITLE
[Request] corepad

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1747]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/corepad

### Utility this package has for you

A document editor from the C Suite

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Marking dependency relation to https://github.com/chaotic-aur/packages/issues/1693

**Comment by Technetium1** [comment]
@tio-trom I'm declining `corepad-git` because `libcprime-git` is an orphan.
