### ISSUE TITLE
[Request] curlew

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1749]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/curlew

### Utility this package has for you

This video/audio converted is super easy to use and works quite well. I am using it for the past few years.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Orphaned deps, may not be possible.

**Comment by tio-trom** [comment]
Worked well to build on my system.
