### ISSUE TITLE
[Request] wireproxy

### ISSUE THREAD

**Issue by artemklevtsov** [chaotic-aur/packages#1750]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/wireproxy

### Utility this package has for you

Wireguard client that exposes itself as a socks5 proxy. I'm use it for the Cloudflare Warp connection.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Now package builds only with Go 1.18.

**Comment by Technetium1** [comment]
Build failed: https://builds.garudalinux.org/repos/chaotic-aur/logs/wireproxy.log

**Comment by Technetium1** [comment]
I flagged it https://aur.archlinux.org/pkgbase/wireproxy/flag-comment
Go 1.19 support was just added 44 min ago in https://github.com/octeep/wireproxy/commit/0e6333194a23a0d98b2ad2543083fb79478e2292

**Comment by artemklevtsov** [comment]
Build success now with 1.0.5-2.
