### ISSUE TITLE
[Request] deskreen

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1752]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/deskreen

### Utility this package has for you

This is one of the most useful apps I've seen recently. Quickly make another monitor out of any device: tablet, laptop, mobile...I love it!

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Inetol** [comment]
@tio-trom This is the current deskreen* maintainer for the AUR.
There is already a package containing the official precompiled binaries called [deskreen-bin](https://aur.archlinux.org/packages/deskreen-bin), you could use that package directly.

Regards.

**Comment by tio-trom** [comment]
Yes thank you I understand. I thought that could be useful to also have it in the chaotic-aur :)

**Comment by Technetium1** [comment]
Hmm let's not use the `-bin` for this one https://github.com/pavlobu/deskreen/blob/9126c891b3ac6b93fca433a9a494530353c1a265/.github/workflows/release.yml#L33

**Comment by Technetium1** [comment]
It's not _usually_ a problem, but if it can be built against Arch instead of Ubuntu, it's preferred. Sometimes they're added as `-bin` anyway, since the difference in compile time can be insane on some things, as well as the occasional difficulty of Arch having bleeding edge versions of everything and a package needing an old version explicitly.

**Comment by dr460nf1r3** [comment]
https://github.com/chaotic-aur/packages/issues/2086

**Comment by Inetol** [comment]
I will look into it if I can do smth about it.

**Comment by Inetol** [comment]
> I will look into it if I can do smth about it.

deskreen builds "correctly" again in clean chroot 🎉
[rel 2.0.3-7](https://aur.archlinux.org/cgit/aur.git/commit/?h=deskreen&id=0d115606a0e18dbfc6d67c3fec17b7b8eb6ae341)

**Comment by Technetium1** [comment]
`Finished making: deskreen 2.0.3-7 (Tue 08 Nov 2022 04:32:06 AM CET)`

**Comment by xiota** [comment]
`descreen` uses EOL Electron/18.2.4.  Metrics 87.
