### ISSUE TITLE
[Request] detwinner

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1753]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/detwinner-git
https://aur.archlinux.org/packages/detwinner

### Utility this package has for you

Duplicate file finder for the Linux desktop

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Both fail testing: 
https://builds.garudalinux.org/repos/chaotic-aur/logs/detwinner-git.log
https://builds.garudalinux.org/repos/chaotic-aur/logs/detwinner.log

**Comment by tio-trom** [comment]
Damn. Works to build on my Arch system but I have the Manjaro repos too so idk. I will submit these to the AUR maintainer.

**Comment by Technetium1** [comment]
@tio-trom Please open another issue in the future for `detwinner-git` if there are major changes to the pkgbuild. `detwinner` is now passing tests!

**Comment by tio-trom** [comment]
I cannot find any of those in your repo anymore.

**Comment by dr460nf1r3** [comment]
https://github.com/chaotic-aur/packages/issues/2086

**Comment by Technetium1** [comment]
Done

**Comment by xiota** [comment]
Dropping because orphaned package.  No upstream commits since 2023.  Metrics 9.
