### ISSUE TITLE
[Request] dupeguru

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1756]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/dupeguru

### Utility this package has for you

Find duplicate files with various contents, using perceptual diff for pictures

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropped because fails to build and still depends on Qt5.  Metrics 45.

**Comment by Technetium1** [comment]
To anyone looking for a replacement, consider https://github.com/qarmin/czkawka

**Comment by tio-trom** [comment]
By the way AUR is working fine to build on my system. Just saying....

**Comment by Technetium1** [comment]
@tio-trom I have no problem adding it back when upstream moves to Qt6. See #3157
