### ISSUE TITLE
[Request] feedreader

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1761]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/feedreader

### Utility this package has for you

Modern desktop application designed to complement existing web-based RSS accounts

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
This has not been actively maintained for a long time, please find another similar app to replace it, like NewsFlash:
https://github.com/jangernert/FeedReader/#this-project-is-no-longer-activily-maintained

**Comment by tio-trom** [comment]
Ah ok thank you. I will check from now on the main repo to see if it is actively developed still.

**Comment by Technetium1** [comment]
@tio-trom there are always exceptions. If in doubt, just ask!
