### ISSUE TITLE
[Request] Fityk

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1762]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/fityk

### Utility this package has for you

A program for nonlinear fitting of analytical functions to data.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
`fityk-git` fails: https://builds.garudalinux.org/repos/chaotic-aur/logs/fityk-git.log

**Comment by tio-trom** [comment]
> `fityk-git` fails: https://builds.garudalinux.org/repos/chaotic-aur/logs/fityk-git.log

We can leave the non git if that's ok with you.

**Comment by Technetium1** [comment]
Accidentally closed the wrong issue, this was added in https://github.com/chaotic-aur/packages/commit/5ac06a337f4794bab1a3b0e01a7bbe2d2ce83c6e

**Comment by tio-trom** [comment]
https://builds.garudalinux.org/repos/chaotic-aur/logs/filtered/dep-not-in-repo/fityk.log Seems like it fails now because of the xylib>=1.4 dependency? Can it be fixed?

**Comment by dr460nf1r3** [comment]
https://github.com/chaotic-aur/packages/issues/2086

**Comment by Technetium1** [comment]
Done
