### ISSUE TITLE
[Request] friture + friture-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1763]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/friture
https://aur.archlinux.org/packages/friture-git

### Utility this package has for you

An application to visualize and analyze live audio data in real-time.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping both packages because they fail to run from numpy compatibility issue.  Packages also need updates to build, but maintainer has been unresponsive to comments since late 2023.

Metrics:

* friture - 5
* friture-git - 3
