### ISSUE TITLE
[Request] Friendiqa

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1764]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/friendiqa

### Utility this package has for you

Client for social network Friendica

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Drop candidate because low usage and unable to rebuild.   Server error 504 (gateway timeout).  Upstream notified.  Metrics 2.
