### ISSUE TITLE
[Request] mcstatus

### ISSUE THREAD

**Issue by jopejoe1** [chaotic-aur/packages#1768]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/mcstatus

### Utility this package has for you

Check status of minecraft server from the terminal

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
It's outdated, I flagged it.

**Comment by jopejoe1** [comment]
Looks like they updated it.
