### ISSUE TITLE
[Request] gifcurry

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1771]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/gifcurry

### Utility this package has for you

The open-source, Haskell-built video editor for GIF makers.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
This package has come to my attention as the result of a signature error.

Dropping it because it is a misnamed binary package with unusual version string.  I am not going to bother trying to convince maintainer to fix the package because others already complained years ago.
