### ISSUE TITLE
[Bug] rustdesk-git contains a symlink to a file that was supposed to be copied in

### ISSUE THREAD

**Issue by kode54** [chaotic-aur/packages#1774]
### What happens?

The RustDesk Git package symlinks to a library that it depends on, from the build folders on the build bot machine. It should probably be dealt with somehow. Meanwhile, the RustDesk Git package is not buildable right now, so it won't be fixable quite yet anyway.

### What is expected to happen?

The library in question should be copied into the build folder so it actually gets bundled in the package.

### More information

The library in question:

```
lrwxrwxrwx root/root         0 2022-05-28 11:06 usr/share/rustdesk/libsciter-gtk.so -> /home/main-builder/pkgsrc/libsciter-gtk.so
```

**Comment by Technetium1** [comment]
This is something that should certainly be reported to the AUR page, I don't think we can do much about it here :frowning_face:. We have fixed that issue in the non-git version though.

Looks like an issue compiling gstreamer is causing the new builds to fail: https://builds.garudalinux.org/repos/chaotic-aur/logs/rustdesk-git.log
