### ISSUE TITLE
[Request] IDJC

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1777]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/idjc

### Utility this package has for you

Powerful client for individuals interested in streaming live radio shows

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Needed `libshout-idjc`, but still failed once it got it: https://builds.garudalinux.org/repos/chaotic-aur/logs/idjc.log

**Comment by tio-trom** [comment]
> Needed `libshout-idjc`, but still failed once it got it: https://builds.garudalinux.org/repos/chaotic-aur/logs/idjc.log

Maybe the maintainer can help. I asked.

**Comment by tio-trom** [comment]
Tested this today and builds fine, if you can test again please.

**Comment by Technetium1** [comment]
@tio-trom Still failing, the log has been regenerated.

**Comment by tio-trom** [comment]
hmm....ok...interesting...

**Comment by Inetol** [comment]
Also for me, both `idjc` and `idjc-git` fails to build 😵

**Comment by xiota** [comment]
Rejecting because has recurrent issues building, missing depends, depends on custom library forks, other minor packaging issues.
