### ISSUE TITLE
[Request] imageburner

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1778]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/imageburner

### Utility this package has for you

Image burner

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

It has not been updated in about 2 years, but it works fine. So up to you guys.

**Comment by Technetium1** [comment]
This is an older app with next to no potential to receive an upgrade in the future, and it seems we already have many others in repo which are very similar, are you sure you want to request this? Does it provide anything unique?

Excerpt of `pacman -Ss iso`:
```
chaotic-aur/bootiso 4.2.0-1 [installed]
A bash script to securely create a bootable USB device from one ISO file.
chaotic-aur/furiusisomount 0.11.3.1-2 [installed]
A PyGTK interface for managing ISO/IMG/BIN/MDF/NRG image files
chaotic-aur/gnome-multi-writer-git 3.35.90.r324.469c911-1
Write an ISO file to multiple USB devices at once
chaotic-aur/imagewriter 1.10.1432200249.1d253d9.2.13-1
A graphical utility for writing raw disk images & hybrid isos to USB keys
chaotic-aur/iso-flag-png 1.0.2-1
ISO country flags in PNG format
chaotic-aur/isoimagewriter 0.9-1
Tool to write a .iso file to a USB disk
chaotic-aur/isomaster 1.3.16-1.1 [installed]
CD image editor written in GTK2
chaotic-aur/lib32-faad2 2.10.0-1
ISO AAC audio decoder (32 bit)
chaotic-aur/mintstick 1.5.0-2
A GUI to write .img or .iso files to a USB Key. It can also format them
```

**Comment by tio-trom** [comment]
I agree. Can be skipped!

**Comment by xiota** [comment]
Dropping because 404 error and not yet updated for Qt6.  Metrics 168.
