### ISSUE TITLE
[Request] imagine-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1779]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/imagine-git

### Utility this package has for you

I am using this for the past 3 years or so. The best image compression software out there. Easy to use and cuts down the size by a huge amount while keeping a great quality.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because uses EOL Electron/12.2.3.  Metrics 4.
