### ISSUE TITLE
[Request] krop

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1782]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/krop

### Utility this package has for you

A tool to crop PDF files, with an eye towards eReaders.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Not updated in 2 years but I remember talking to the developer and him saying that if it works why update it.

**Comment by Technetium1** [comment]
Fantastic!
