### ISSUE TITLE
[Bug] Mangohud searches for /usr/lib/libfmt.so.8, it doesn't exist anymore

### ISSUE THREAD

**Issue by Andy3153** [chaotic-aur/packages#1790]
### What happens?

Mangohud errors out while launching any program:

```bash
$ mangohud echo
echo: error while loading shared libraries: libfmt.so.8: cannot open shared object file: No such file or directory
```

### What is expected to happen?

No error shows up, and Mangohud launches together with the program

### More information

Trying to create a symlink (yes, even though it is really really bad to do so, I still tried) doesn't work either, for a different reason:

```bash
$ sudo ln -s /usr/lib/libfmt.so /usr/lib/libfmt.so.8

$ mangohud echo
echo: symbol lookup error: /usr/lib/libMangoHud.so: undefined symbol: _ZN3fmt2v86detail9dragonbox10to_decimalIfEENS2_10decimal_fpIT_EES5_
```

By the way, the AUR version works normally, with no system modifications. Maybe a recompile is required?

**Comment by niobium93** [comment]
It seems to have been rebuilt, try again.

**Comment by niobium93** [comment]
Though the `*-git` version needs to be rebuilt too probably.

**Comment by Andy3153** [comment]
Yes. Now it works.
