### ISSUE TITLE
[Request] autokey

### ISSUE THREAD

**Issue by bbkjbbkj** [chaotic-aur/packages#1792]
### Link to the package(s) in the AUR

https://aur.archlinux.org/pkgbase/autokey

### Utility this package has for you

AutoKey is a scripting application for Linux. It lets you automate repetitive and trivial operations on your computer so you can perform them quickly and efficiently.  Here is a few examples how i use it:

1. Quick responses in Social Media

@mpo  <- When commenting I highlight the person's ID and press [Meta-']  and it looks up their real name and types it in

Marcelo <-  I then press one of many custom greetings, for example [Meta+]] it then builds additional text around the name 

Hi Marcelo and a good morning to you my friend. hope you have a blessed Friday!

The opening greeting is semi-random between Hi, Hello, Greetings, etc and the ending day is derived by looking at the system date/time.

2. I use it in coding html tags with asciidoctor. For example:

[Meta-g] = [lime-background]#
[Meta-y] =[yellow-background]#
[Shift-Meta-g] = +++<span class="backspace"></span>+++[lime-background]#
[Shift-Meta-y] = +++<span class="backspace"></span>+++[yellow-background]#
and so on.

It is a great time saver.  Here is a 2021 review of the package:

How to Use AutoKey to Automate Repetitive Tasks on Linux
https://www.makeuseof.com/use-autokey-to-automate-repetitive-tasks-on-linux/

Thanks for your consideration! (see more information note below)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

It was requested once before as https://github.com/chaotic-aur/packages/issues/953

But was set with a low priority, then closed.

I am hoping you might reconsider.

**Comment by xiota** [comment]
#953 was closed as completed.
