### ISSUE TITLE
[Request] nasc

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1793]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/nasc

### Utility this package has for you

Do maths like a normal person.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because fails to build.  Fix would ideally involve new upstream commit and release.  However, last release was Aug 2021.
```
/usr/include/unicode/localpointer.h:561:26: error: parameter declared ‘auto’
  561 | template <typename Type, auto closeFunction>
```

AUR package also has other issues, like broken url.
