### ISSUE TITLE
[Request] nightpdf

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1794]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/nightpdf

### Utility this package has for you

Dark mode PDF reader

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
The source no longer exists :frowning:

**Comment by Technetium1** [comment]
I've submitted a deletion request: https://lists.archlinux.org/pipermail/aur-requests/2022-September/076961.html
