### ISSUE TITLE
[Request] notejot

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1795]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/notejot

### Utility this package has for you

A stupidly-simple sticky notes application for any type of short term notes or ideas

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Not building.  Potential [patch](https://github.com/lainsce/notejot/issues/395#issuecomment-1509402727) to fix (did not test).

**Comment by xiota** [comment]
AUR maintainer added the patch, so this package is now building.  However, the issue was [reported four months ago](https://aur.archlinux.org/packages/notejot?O=10#comment-918589), and the source has QA issues.  So if this breaks again, I would prefer to drop it.

**Comment by xiota** [comment]
Dropping.  Upstream code is an unbuildable mess.  Metrics is 10.
```
malloc(): unaligned fastbin chunk detected
Aborted (core dumped)
```
