### ISSUE TITLE
[Request] oxygen-cursors

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1798]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/oxygen-cursors

### Utility this package has for you

Beautiful Cursors themes

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Switched to `oxygen-cursors-extra` because it is better maintained and `oxygen-cursors` has unnecessary dependencies.

**Comment by xiota** [comment]
Switching back to `oxygen-cursors` because `oxygen-cursors-extra` fails to build and don't know how to fix with interfere.

Metrics: oxygen-cursors-extra 27.

**Comment by xiota** [comment]
Changed mind...  Dropping oxygen-cursors-extra because fails to build and don't know how to fix with interfere. Metrics 27.

Basic oxygen cursor in `extra/oxygen`.
