### ISSUE TITLE
linux-tkg-bmq missing

### ISSUE THREAD

**Issue by timescam** [chaotic-aur/packages#18]
linux-tkg-bmq-headers is still in the repo, but linux-tkg-bmq is missing.

**Comment by PedroHLC** [comment]
:thinking: They were there, I just bumped them in database to be sure

**Comment by timescam** [comment]
Thank you,
I can't check now as I'm not with my machine, but it should not be a me problem as it was also missing on [pkgs.org](https://pkgs.org/search/?q=linux-tkg-bmq)

**Comment by timescam** [comment]
fixed
