### ISSUE TITLE
[Request] passbook + passbook-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1800]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/passbook
https://aur.archlinux.org/packages/passbook-git

### Utility this package has for you

A password manager for GNOME

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because upstream development appears to have halted.  Last commit was 2022, and readme has notice:

> Passbook is looking for a new maintainer. (and need to be ported to GTK4)

Metrics:

* passbook # 2
* passbook-git # 0
