### ISSUE TITLE
[Request] pebbles-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1802]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/pebbles-git

### Utility this package has for you

Pebbles is an advanced calculator application

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Left comment for maintainer to fix it.

**Comment by xiota** [comment]
Dropping -git package in favor of stable.  Metrics 4.
