### ISSUE TITLE
[Request] pencil

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1803]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/pencil

### Utility this package has for you

Sketching and GUI prototyping/wireframing tool

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
This is super awesome!

**Comment by xiota** [comment]
Dropping because electron21.  (Upstream git repo still on electron 16.)
Metrics 16.
