### ISSUE TITLE
[Request] photoqt

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1804]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/photoqt

### Utility this package has for you

Fast and highly configurable image viewer with a simple and nice interface.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by dr460nf1r3** [comment]
https://github.com/chaotic-aur/packages/issues/2086

**Comment by Technetium1** [comment]
Done
