### ISSUE TITLE
[Bug] yuzu-mainline-git fails to install because of conflicting files

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#1808]
### What happens?

`yuzu-mainline-git` seems to include files that conflict with the `robin-map` package, even though `-DDYNARMIC_NO_BUNDLED_ROBIN_MAP=ON` is set in the PKGBUILD.

### What is expected to happen?

`yuzu-mainline-git` shouldn't contain files that conflict with other packages.

### If possible, please attach logs

```
(26/26) checking for file conflicts                                                                                [#####################################################################] 100%
error: failed to commit transaction (conflicting files)
yuzu-mainline-git: /usr/include/tsl/robin_growth_policy.h exists in filesystem (owned by robin-map)
yuzu-mainline-git: /usr/include/tsl/robin_hash.h exists in filesystem (owned by robin-map)
yuzu-mainline-git: /usr/include/tsl/robin_map.h exists in filesystem (owned by robin-map)
yuzu-mainline-git: /usr/include/tsl/robin_set.h exists in filesystem (owned by robin-map)
yuzu-mainline-git: /usr/share/cmake/tsl-robin-map/tsl-robin-mapConfig.cmake exists in filesystem (owned by robin-map)
yuzu-mainline-git: /usr/share/cmake/tsl-robin-map/tsl-robin-mapConfigVersion.cmake exists in filesystem (owned by robin-map)
yuzu-mainline-git: /usr/share/cmake/tsl-robin-map/tsl-robin-mapTargets.cmake exists in filesystem (owned by robin-map)
Errors occurred, no packages were upgraded.
```

**Comment by Edu4rdSHL** [comment]
Please report this to the AUR maintainers.

**Comment by niobium93** [comment]
[Isn't it because of this?](https://github.com/chaotic-aur/interfere/blob/master/yuzu-mainline-git/PKGBUILD.append)
`-DDYNARMIC_NO_BUNDLED_ROBIN_MAP=ON` is missing there. Probably a lot of stuff is missing there, it hasn't been updated in a year. Maybe just drop it and build the stock PKGBUILD from AUR?

**Comment by Technetium1** [comment]
`pkgver=r21802.68148cf4e` on AUR now matches our format of `r21928.8dc328634-1`, `glslang` is now in depends instead of makedepends, `boost` is now in makedepends, so we can probably just remove this from interfere entirely.

`boost-libs` is no longer (or maybe never was) in makedepends, so if it fails after doing this - that's probably why.

**Comment by Technetium1** [comment]
@niobium93 if the [new build](https://github.com/chaotic-aur/interfere/commit/fbb50e173cb691d8eaf5929dde1d0a68d12d07a9#diff-acda3a66e1f15a258e2d7c66274a579f3e77ce846d9358b43f611ab39f0ae9f2R89) doesn't fix this, it's a problem upstream.

**Comment by niobium93** [comment]
Everything seems fine now. Thanks <3
