### ISSUE TITLE
[Request] qnapi-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1809]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/qnapi-git

### Utility this package has for you

Qt5 client for downloading movie subtitles

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Fantastic!

**Comment by xiota** [comment]
Dropping for following reasons:

* Not updated for Qt6 (see [#3157](https://github.com/chaotic-aur/packages/issues/3157))
* Uses deprecated/disabled API
