### ISSUE TITLE
[Request] qoob-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1810]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/qoob-git

### Utility this package has for you

foobar-like music player for Linux

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
@tio-trom I flagged `qoob` out of date, because it doesn't have a valid key. Instead, let's add `qoob-git`.

**Comment by tio-trom** [comment]
> @tio-trom I flagged `qoob` out of date, because it doesn't have a valid key. Instead, let's add `qoob-git`.

Sounds good! Thanks!
