### ISSUE TITLE
[Remove] qrab

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1812]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/qrab

### Utility this package has for you

Simply grabs QR code from screen and copies decoded text into clipboard

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
I flagged [liri-cmake-shared-git](https://aur.archlinux.org/packages/liri-cmake-shared-git) out of date because it's blocking the build of [fluid-git](https://aur.archlinux.org/packages/fluid-git) which is blocking this build: [qrab.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/qrab.log)

**Comment by xiota** [comment]
@Technetium1 We can switch to stable `liri-cmake-shared`.  I adopted because it was orphaned.  Can add `provides=(liri-cmake-shared-git)` to satisfy deps.

However, `fluid-git` still fails to build.

**Comment by xiota** [comment]
Dropping for following reasons:

* Hasn't been updated for Qt6 (see [#3157](https://github.com/chaotic-aur/packages/issues/3157))
    * Upstream hasn't been updated since Feb 2017.
* Depends on broken packages, that also haven't been updated for Qt6.
