### ISSUE TITLE
[Request] quilter + quilter-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1815]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/quilter-git
https://aur.archlinux.org/packages/quilter

### Utility this package has for you

Focus on your writing and write beautiful solid stories with the Focus Mode in tow in this Markdown editor.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

The non-git version may not build.

**Comment by Technetium1** [comment]
This has been deprecated :frowning_face:

**Comment by tio-trom** [comment]
> This has been deprecated frowning_face

Oh bummer...thanks for checking!
