### ISSUE TITLE
[Request] qwertone-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1816]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/qwertone-git
https://aur.archlinux.org/packages/qwertone

### Utility this package has for you

Simple music synthesizer app based on usual qwerty-keyboard for input

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
While this software looks alright, the upstream repo is explicitly marked stale, so I don't expect any changes, therefore don't see a reason to add the non `-git` version.
