### ISSUE TITLE
[Request] recapp + recapp-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1817]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/recapp
https://aur.archlinux.org/packages/recapp-git

### Utility this package has for you

Simple screen recorder for Linux written in GTK, using only GStreamer.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
> This project is archived, it's no longer under development. If you would like to continue development, please feel free to fork the project according to the GPL license

R.I.P.
