### ISSUE TITLE
[Request] remarkable + remarkable-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1818]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/remarkable-git
https://aur.archlinux.org/packages/remarkable

### Utility this package has for you

A free fully featured markdown editor for Linux.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
This is no longer actively developed :frowning_face:

**Comment by tio-trom** [comment]
Ok. I see that they didn't archive the project https://github.com/jamiemcg/remarkable or anything like that. From my tests works well, but up to you. I understand your point.
