### ISSUE TITLE
[Request] remotely + remotely-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1819]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/remotely
https://aur.archlinux.org/packages/remotely-git

### Utility this package has for you

simple VNC viewer for the GNOME desktop environment

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
> Remotely is no longer being developed. As an alternative, GNOME Connections can be used

R.I.P.
