### ISSUE TITLE
[Request] Ricochet

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1820]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/ricochet

### Utility this package has for you

Anonymous peer-to-peer instant messaging.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Unsure if it is still developed....but from my tests it works.

**Comment by Technetium1** [comment]
[I flagged it](https://aur.archlinux.org/pkgbase/ricochet/flag-comment) since it's not pointing to GitHub and it really should be.

**Comment by Technetium1** [comment]
This package was deleted :skull:
