### ISSUE TITLE
[Request] siril-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1823]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/siril-git
https://aur.archlinux.org/packages/siril

### Utility this package has for you

An astronomical image processing software for Linux. (IRIS clone)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
I left a comment for the [siril-git](https://aur.archlinux.org/packages/siril-git#comment-881645) fix.

**Comment by xiota** [comment]
`extra/exiv2` 0.28.0-1 introduced some breaking changes.  `siril` is affected.

**Comment by xiota** [comment]
Dropping `siril` because it has been broken for far too long.  Not enough users to be worth fixing via interfere.
