### ISSUE TITLE
[Request] sk1 + sk1-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1824]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/sk1-git
https://aur.archlinux.org/packages/sk1

### Utility this package has for you

Open source vector graphics editor for prepress

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
This project no longer has any active development :cry: 
> Ihor Novikov, the founder and the lead developer of open-source sK1 vector graphics editor and UniConvertor, passed away at the age of 49 in March 2021, due to COVID-19. It has been a tragic loss for his family and friends, and a very unexpected one. Ihor was full of life and energy.

**Comment by tio-trom** [comment]
Oh that's a sad news.
