### ISSUE TITLE
[Request] Sleek

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1825]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/sleek

### Utility this package has for you

Todo manager based on the todo.txt syntax for Linux, free and open-source (FOSS)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Package is missing depends, but maintainer appears to be ignoring comments.  Plan to drop if package isn't fixed the next time it comes to my attention.

**Comment by xiota** [comment]
Dropping because fails to build and maintainer still appears to be absent.
