### ISSUE TITLE
[Request] sonobus

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1826]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/sonobus-git
https://aur.archlinux.org/packages/sonobus

### Utility this package has for you

An easy to use application for streaming high-quality, low-latency peer-to-peer audio

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
I never knew there was an AUR package for it, awesome!

**Comment by Technetium1** [comment]
`sonobus-git` fails: https://builds.garudalinux.org/repos/chaotic-aur/logs/sonobus-git.log

**Comment by Technetium1** [comment]
Please open a different issue for [sonobus-git](https://aur.archlinux.org/packages/sonobus-git) if it gets updated in the future.
