### ISSUE TITLE
[Request] spice-up-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1827]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/spice-up-git

### Utility this package has for you

Create simple and beautiful presentations on the Linux desktop

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
I flagged the package. Fails with `CMake Error: The source directory does not appear to contain CMakeLists.txt`. This probably won't be fixed for a long time.

@tio-trom Feel free to reopen if it is ever updated?
