### ISSUE TITLE
[Request] Subsurface + Subsurface-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1829]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/subsurface-git
https://aur.archlinux.org/packages/subsurface

### Utility this package has for you

For someone who dives, this is a unique app honestly. I could not find a good alternative. I think Linus himself made it or contributed to it since he also dives. 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

The non-git may not work to build.

**Comment by Technetium1** [comment]
I never knew about the diving, that's cool!

**Comment by xiota** [comment]
Going ahead with drop.  Can re-add when upstream properly supports Qt6.
