### ISSUE TITLE
python2-xcb-proto fails to build (dependency of chromium-ozone package)

### ISSUE THREAD

**Issue by vincentvanvugt** [chaotic-aur/packages#183]
Currently `chromium-ozone` fails to build because `python2-xcb-proto` doesn't build. According to [python2-xcb-proto AUR](https://aur.archlinux.org/packages/python2-xcb-proto/#comment-753404) their key needs to be added with a different keyserver. Not sure if this is the correct way/place to mention issues with packages. If not, my apologies.

**Comment by PedroHLC** [comment]
Sorry, as I'm transitioning to a new infra, I wasn't watching this repo yet.
Thanks for the instructions, I'll be fixing this as soon as possible!

**Comment by PedroHLC** [comment]
Well, we have `chromium-ozone`, so I think this was fixed :sweat_smile: 
Sorry for the late reply!
