### ISSUE TITLE
[Request] subtitlecomposer + subtitlecomposer-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1830]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/subtitlecomposer-git
https://aur.archlinux.org/packages/subtitlecomposer

### Utility this package has for you

Video subtitle editor

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
This is a fantastic addition

**Comment by xiota** [comment]
`aur/subtitlecomposer-git` has multiple issues that maintainers are ignoring/refusing to fix.  Switching to PKGBASE from `subtitlecomposer-nopocketsphinx-git` (#2686).  The package retain the old name (`chaotic-aur/subtitlecomposer-git`).

**Comment by xiota** [comment]
Switched to -qt6 versions.  Related #3157.

**Comment by xiota** [comment]
Planning to drop -qt6-git package because low usage.  Metrics 10.  Compared with stable package metrics 456.

**Comment by xiota** [comment]
Dropping because moved to extra.  Metrics 158.
