### ISSUE TITLE
[Request] synkron

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1831]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/synkron

### Utility this package has for you

A folder synchronization tool

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

It is quite old....but still works. Up to you guys.

**Comment by Technetium1** [comment]
@tio-trom it's been 11 years since that site updated, is this still maintained at all?

**Comment by tio-trom** [comment]
7 years

![2022-09-04_16-08](https://user-images.githubusercontent.com/38043315/188317759-e4788355-dbc1-4926-8c1d-2ea93d3d3af7.png)

 - but still yes I understand. I mean it works well from my tests. But feel free to reject it I totally understand. The reason I added it to our library was because is quite unique: allows the easy synchronization between folders.

**Comment by Technetium1** [comment]
> 7 years

I meant this site, oops: http://synkron.sourceforge.net

If it was tested and still works then no harm at all, it's only 1KB. There are other things that do this too, like https://github.com/syncthing/syncthing

**Comment by tio-trom** [comment]
> > 7 years
> 
> I meant this site, oops: http://synkron.sourceforge.net
> 
> If it was tested and still works then no harm at all, it's only 1KB. There are other things that do this too, like https://github.com/syncthing/syncthing

Yes I use Syncthing too but that's for over-the-internet synchronization, not local :P

**Comment by Technetium1** [comment]
syncthing relays are only used when needed, it's LAN by default https://forum.syncthing.net/t/syncthing-in-lan/6538

**Comment by tio-trom** [comment]
> syncthing relays are only used when needed, it's LAN by default https://forum.syncthing.net/t/syncthing-in-lan/6538

Yes but Synkro allows you to sync local files, withing the same computer. Very useful when you have multiple drives and want the same content synced across them and such.

**Comment by Technetium1** [comment]
OH I understand what you mean exactly now. In that case I withdraw the recommendation of rclone gui in favor of https://github.com/bcpierce00/unison

**Comment by tio-trom** [comment]
Oh beautiful! I am testing it now!

**Comment by Technetium1** [comment]
I remembered one more while we brought this up: https://github.com/tillberg/gut

**Comment by tio-trom** [comment]
One think Synkron has that is very useful is the ability to easily schedule syncs. Also multisync, restore, and more. I think for now at least is worth adding it too.

**Comment by Technetium1** [comment]
It already is added :)

**Comment by tio-trom** [comment]
qt4 dependency not met anymore https://builds.garudalinux.org/repos/chaotic-aur/logs/filtered/dep-not-in-repo/synkron.log

**Comment by dr460nf1r3** [comment]
Mhm, qt4 was a quite heavy package iirc I was happy to be able to drop it 👀
Thinking about wanting to reduce repository size, this would be a good candidate 🤔

**Comment by tio-trom** [comment]
So it means that every package that depends on qt4 will be removed from the chaotic aur? If so, aren't many packages still reliant on it?

**Comment by Technetium1** [comment]
There are probably a few still... They've had many years to update at this point https://lists.archlinux.org/pipermail/arch-dev-public/2019-April/029560.html

**Comment by Technetium1** [comment]
Update: we are going to build qt4 once again.

**Comment by Technetium1** [comment]
Done in https://github.com/chaotic-aur/packages/commit/7162209a5f3c3faa6d9689d781fd934e0405f58f
