### ISSUE TITLE
[Request] Taigo

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1832]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/taigo

### Utility this package has for you

A virtual pet for your desktop built with GTK+, Vala, and love

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

AUR flagged out of date but the app works fine.

**Comment by Technetium1** [comment]
Flagged out of date for more than a year, and upstream activity is dead :(
