### ISSUE TITLE
[Request] tiddlydesktop + tiddlywiki

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1834]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/tiddlydesktop

### Utility this package has for you

With this you can create wonderful websites into 1 single HTML file. I use it for a few websites. It is great!

TiddlyDesktop is a special purpose web browser for working with locally stored TiddlyWikis.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
`tiddlydesktop` is a disguised `-bin` package with incorrect depends.  Haven't decided what to do with it (drop, rename, or build from source).  Metrics 8.
