### ISSUE TITLE
[Request] trimage-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1837]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/trimage-git

### Utility this package has for you

A GUI based lossless image compressor.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Releases are very infrequent and missing patches for extended periods. Switching to `trimage-git` for that reason.

**Comment by tio-trom** [comment]
Another dropped package? :D

**Comment by dr460nf1r3** [comment]
https://github.com/chaotic-aur/packages/issues/2086

**Comment by Technetium1** [comment]
Done
