### ISSUE TITLE
[Request] trojita

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1839]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/trojita

### Utility this package has for you

A Qt IMAP email client

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
There are a [LOT of bugs](https://bugs.kde.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=CONFIRMED&bug_status=ASSIGNED&bug_status=REOPENED&order=changeddate%20DESC%2Cbug_status%2Cpriority%2Cassigned_to%2Cbug_id&product=trojita&query_format=advanced), many that haven't recieved attention in years. They are inactive enough to let their SSL cert expire too.. I'm not comfortable adding an email client with such lax development around it. It feels like too much potential for things to go wrong.
