### ISSUE TITLE
[Request] Venom

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1841]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/venom

### Utility this package has for you

a modern Tox client for the Linux desktop

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
This seems dead @tio-trom :frowning_face: https://github.com/naxuroqa/Venom/issues/506

**Comment by tio-trom** [comment]
> This seems dead @tio-trom frowning_face [naxuroqa/Venom#506](https://github.com/naxuroqa/Venom/issues/506)

Unfortunately....
