### ISSUE TITLE
[Request] video-downloader

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1842]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/video-downloader

### Utility this package has for you

GTK application to download videos from websites like YouTube and many others (based on yt-dlp)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Very good!

**Comment by xiota** [comment]
Dropping because moved to extra.  Metrics 48.
