### ISSUE TITLE
[Request] vpaint-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1844]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/vpaint
https://aur.archlinux.org/packages/vpaint-git

### Utility this package has for you

VPaint is an experimental vector graphics editor based on the Vector Animation Complex technology.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Last stable release was 2 years ago, let's do `vpaint-git` for that reason.

**Comment by tio-trom** [comment]
Maybe the releases are slow but the last activity is in June this year https://github.com/dalboris/vpaint https://github.com/dalboris/vpaint/commit/5e7eb3afea98b4ae1f381cd4a565b9124f148bbd

**Comment by Technetium1** [comment]
@tio-trom Both PKGBUILDs are broken, and I don't know why. Can you fix / report them?

[vpaint-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/vpaint-git.log)
[vpaint.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/vpaint.log)

**Comment by tio-trom** [comment]
Now that I looked closely at the AUR packages they do not seem maintained. I have reported the error with the pkgbuild some time ago and got to reply...it is unfortunate because VPaint is really promising. I do not know how to fix their pkgbuilds...If you decline this one I understand.

**Comment by Technetium1** [comment]
@simonrepp please help fix these, so they can be added here.

**Comment by simonrepp** [comment]
@tio-trom I already have a written on paper todo note right here on my desk to look into the issue you reported (thanks), please grant me some time to get to it, I'm having very stressful weeks right now.

@tio-trom @Technetium1 Also note that vpaint is not going to get **any** feature releases anymore as the author (Boris Dalstein) has been (literally and figuratively) kickstarting and working on its successor, VGC Illustration (https://www.vgc.io/), which builds on the research done in VPaint, but unlike VPaint, is going to be a (also FLOSS btw.) production-grade tool (not a research demo, which VPaint basically is). It's precisely for that reason too that I didn't immediately jump to fix the AUR build errors for VPaint - Boris and his colleague are currently intensively working towards VGC Illustration v1, so while I'm happy to help keep VPaint running for a good while still (and I think Boris also does not want to drop it just yet), the immediate pressing focus and the promising developments around this technology are currently happening elsewhere. Note that there is also an AppImage offered on vpaint.org so nothing's stopping anyone from still using VPaint while the AUR builds are not working. All that said, I'll look into this as soon as I find time, thanks for your patience folks.

**Comment by tio-trom** [comment]
I highly appreciate that you wrote all of these details and I am very excited about VGC!

**Comment by simonrepp** [comment]
@Technetium1 @tio-trom Submitted a possible upstream fix at https://github.com/dalboris/vpaint/pull/134 today, will post an update when there's news. :)

**Comment by Technetium1** [comment]
I'll rebuild it now!

**Comment by Technetium1** [comment]
Success! [vpaint-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/vpaint-git.log)
