### ISSUE TITLE
issue: polybar-git recompile needed

### ISSUE THREAD

**Issue by timescam** [chaotic-aur/packages#185]
polybar: error while loading shared libraries: libjsoncpp.so.22: cannot open shared object file: No such file or directory

**Comment by PedroHLC** [comment]
This was done, please let me know if the problem persists.

**Comment by timescam** [comment]
same error, clean rebuild needed?
polybar: error while loading shared libraries: libjsoncpp.so.22: cannot open shared object file: No such file or directory

**Comment by PedroHLC** [comment]
Every build here is clean: freshly cloned and a new container every time.
It could've been I dreamed about rebuilding it cause I couldn't find its log.
Well, it's built now. Remembering it doesn't bump pkgrel, so you need to force it to reinstall.

Please let me know if it works, and if it does, feel free to close this issue.
Thanks for your contribution!

**Comment by timescam** [comment]
fixed
