### ISSUE TITLE
[Request] youplay

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1853]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/youplay

### Utility this package has for you

Search, download and play music from YouTube.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
v4 builder will switch to custom package because the way the aur package is constructed causes some problems.  package on v3 will stay as-is.  Metrics unknown because everything was reset to zero.
