### ISSUE TITLE
[Request] zrythm + zrythm-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1854]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/zrythm-git
https://aur.archlinux.org/packages/zrythm

### Utility this package has for you

a highly automated and intuitive digital audio workstation

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Left the maintainer [a comment](https://aur.archlinux.org/packages/zrythm-git#comment-893414) about missing dependency on `zrythm-git`.
