### ISSUE TITLE
[Outdated] mutter-x11-scaling

### ISSUE THREAD

**Issue by raul-lezameta** [chaotic-aur/packages#1855]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/mutter-x11-scaling.log

### Package name

mutter-x11-scaling

### Latest build

42.3-1

### Latest version available

42.4-1

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by Technetium1** [comment]
I think the patch might need updated?

**Comment by Technetium1** [comment]
`==> Finished making: mutter-x11-scaling 42.4-1 (Sun 04 Sep 2022 03:30:19 PM UTC)`
