### ISSUE TITLE
[Request] catppuccin themes

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1856]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/catppuccin-gtk-theme

### Utility this package has for you

GTK theme for catppuccin. Warm dark theme for the masses!

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

It is flagged as out of date but granted this is quite a new package so I am sure it will be updated

**Comment by Technetium1** [comment]
This has been [flagged](https://aur.archlinux.org/pkgbase/catppuccin-gtk-theme/flag-comment) since 2 days before it was requested… Now we wait a while to see if it's actively maintained.

**Comment by tio-trom** [comment]
The package was removed from AUR but now we have them in different variations as:
https://aur.archlinux.org/packages/catppuccin-mocha-grub-theme-git
https://aur.archlinux.org/packages/catppuccin-macchiato-grub-theme-git
https://aur.archlinux.org/packages/catppuccin-latte-grub-theme-git
https://aur.archlinux.org/packages/catppuccin-frappe-grub-theme-git
https://aur.archlinux.org/packages/catppuccin-gtk-theme-frappe
https://aur.archlinux.org/packages/catppuccin-gtk-theme-mocha
https://aur.archlinux.org/packages/catppuccin-gtk-theme-macchiato
https://aur.archlinux.org/packages/catppuccin-gtk-theme-latte

Can we add them?

**Comment by xiota** [comment]
Dropped the GTK themes because upstream no longer supports them. Will keep the cursors and grub themes.

Metrics:

* catppuccin-cursors-mocha # 120
* catppuccin-frappe-grub-theme-git # 14
* catppuccin-gtk-theme-frappe # 41
* catppuccin-gtk-theme-latte # 42
* catppuccin-gtk-theme-macchiato # 89
* catppuccin-latte-grub-theme-git # 9
* catppuccin-macchiato-grub-theme-git # 10
* catppuccin-mocha-grub-theme-git # 30
