### ISSUE TITLE
[Request] popsicle-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1862]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/popsicle-git

### Utility this package has for you

Linux utility for flashing multiple USB devices in parallel, written in Rust

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
We already have `popsicle`

**Comment by tio-trom** [comment]
> We already have `popsicle`

Yup but git builds can also be useful. Thanks for adding!
