### ISSUE TITLE
[Request] nheko

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1865]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/nheko

### Utility this package has for you

Desktop client for the Matrix protocol

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

You only have the git version.

**Comment by Technetium1** [comment]
> You only have the git version.

Probably because the other one lags behind official releases, which don't happen _nearly_ often enough for this. Like right now, it is outdated. If they tagged more regularly, and the maintainer was a bit faster to update, maybe then it would be a good idea to revisit this one.

**Comment by tio-trom** [comment]
So the git one was also dropped recently?

**Comment by dr460nf1r3** [comment]
https://github.com/chaotic-aur/packages/issues/2086

**Comment by tio-trom** [comment]
> @tio-trom Can you please open a rebuild request for the `-git` version

Ok https://github.com/chaotic-aur/packages/issues/2087 :)
