### ISSUE TITLE
[Request] gmsh-bin

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1868]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/gmsh-bin

### Utility this package has for you

An automatic 3D finite element mesh generator with pre and post-processing facilities.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
@tio-trom since they seem to be the same version, is just `gmsh-bin` okay?

**Comment by tio-trom** [comment]
Sounds good yes
