### ISSUE TITLE
[Request] gdevelop-bin

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1871]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/gdevelop-bin
https://aur.archlinux.org/packages/gdevelop-git

### Utility this package has for you

A full featured, open source game development software, allowing to create HTML5 and native games without knowing a programming language. All the game logic is made thanks to an intuitive and powerful event based system.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
I flagged [gdevelop-git](https://aur.archlinux.org/pkgbase/gdevelop-git/flag-comment).

**Comment by Technetium1** [comment]
@tio-trom Feel free open another issue for `gdevelop-git` if it ever gets updated.

**Comment by xiota** [comment]
Dropping because still uses electron18.  Metrics 9.
