### ISSUE TITLE
[Request] sweet-gtk-theme

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1873]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/sweet-gtk-theme

### Utility this package has for you

Light and dark colorful Gtk3.20+ theme

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Already in Garuda repo from: https://github.com/chaotic-aur/packages/commit/41b4d4dad08f109f4e903d715652f673eab57306

**Comment by Technetium1** [comment]
I'll match that commit and add `sweet-gtk-theme-dark`, just because.
