### ISSUE TITLE
[Request] sayonara-player

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1880]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/sayonara-player

### Utility this package has for you

Small, clear and fast audio player for Linux written in C++, supported by the Qt framework. It uses Gstreamer as audio backend.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

You only have the git, at you know git may not always be stable.

**Comment by Technetium1** [comment]
Tests fail: [sayonara-player.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/sayonara-player.log)

**Comment by tio-trom** [comment]
Can we try the git https://aur.archlinux.org/packages/sayonara-player-git ?

**Comment by Technetium1** [comment]
@tio-trom already added by #1101

**Comment by tio-trom** [comment]
Ahh I see. Ok
