### ISSUE TITLE
[Request] cecilia + cecilia-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1882]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/cecilia-git
https://aur.archlinux.org/packages/cecilia

### Utility this package has for you

Audio signal processing environment aimed at sound designers

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
bug was a temporary network error

**Comment by xiota** [comment]
Dropping cecilia-git because depends on python-pyo which is orphaned and fails to build.

Metrics:

* cecilia-git # 7
* python-pyo # 4
