### ISSUE TITLE
[Request] cabbage-bin

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1883]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/cabbage-bin

### Utility this package has for you

Framework for developing audio plugins with the Csound programming language.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Planning to drop.  Metric 1.  Also, has been potentially broken for 6 months with no complaint.
