### ISSUE TITLE
[Request] giada

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1884]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/giada
https://aur.archlinux.org/packages/giada-git

### Utility this package has for you

A free, minimal, hardcore audio tool for DJs, live performers and electronic musicians

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
`giada-git` is failing due to missing `steinberg-vst`: [giada-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/giada-git.log)

**Comment by Technetium1** [comment]
Please open an issue in the future if `steinberg-vst` is ever able to be satisfied for the `-git`.

**Comment by xiota** [comment]
Added `giada-git`.  Builds, but not tested for functionality.

Metrics for `giada`, 41.

**Comment by xiota** [comment]
Dropping giada because needs rebuild for fmt update, but fails to build because submodule errors and missing depends.

Metrics:

* giada # 15
* giada-git # 15

**Comment by xiota** [comment]
Note: `giada` was dropped, but `giada-git` was retained.  Metrics 12.
