### ISSUE TITLE
[Request] gnome-documents-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1886]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/gnome-documents-git

### Utility this package has for you

A document manager application for GNOME

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Build fails: [gnome-documents-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/gnome-documents-git.log)

**Comment by tio-trom** [comment]
I see this comment https://aur.archlinux.org/packages/gnome-documents-git#comment-828331 - maybe a a PKGBUILD patch can fix it?

**Comment by Inetol** [comment]
It seems that the project was [archived](https://gitlab.gnome.org/Archive/gnome-documents) about 1 year ago (nor in FlatHub exists). Not to be picky but the utility I see in this package is non-existent rn.

**Comment by Technetium1** [comment]
Thanks @Inetol
