### ISSUE TITLE
[Remove] nuclear-player-bin

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1893]
### Link to the package(s) in the AUR

~~https://aur.archlinux.org/packages/nuclear-player-git~~
https://aur.archlinux.org/packages/nuclear-player-bin

### Utility this package has for you

This is the best music player I came across :D   -  listen to any music for free. Streams from many "free" sources.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
makedepends for `nuclear-player-git` requires `nodejs-lts-erbium`, which no longer exists.

**Comment by Technetium1** [comment]
I gave it git and now it fails differently: [nuclear-player-bin.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/nuclear-player-bin.log)

**Comment by tio-trom** [comment]
I have used the bin package for a while now, maybe we can only use that for now.

**Comment by Technetium1** [comment]
@tio-trom the `-bin` is failing too :eyes:

**Comment by tio-trom** [comment]
That's odd but the developer maintains that AUR package so maybe we can contact them directly. I don't understand anything out of the log tho. There is nothing specific....

**Comment by Technetium1** [comment]
Actually, this builds in a clean chroot for me, so I think it's a toolbox bug…

**Comment by Technetium1** [comment]
@nukeop any ideas?

**Comment by nukeop** [comment]
Bin should be ok, it uses whatever .deb is in the latest release, and installs that. I'll boot my arch derivative later and see if I can install it.

**Comment by dr460nf1r3** [comment]
`-bin` is indeed okay without having added `git` as makedepend. Fine by me, at some point, the maintainer will likely add it himself (hopefully lol)

**Comment by nukeop** [comment]
Sure, I can do it.

**Comment by dr460nf1r3** [comment]
Thanks! :)

**Comment by tio-trom** [comment]
I do not see this package in your repos anymore.

**Comment by nukeop** [comment]
I'm gonna switch to using regular semantic versioning soon, then I'll sort it out.

**Comment by dr460nf1r3** [comment]
https://github.com/chaotic-aur/packages/issues/2086

**Comment by Technetium1** [comment]
I thought to just add `git` via interfere, but it fails with error code 6... However when I just clone the package and manually add makedepends=(git) it works fine. This is a toolbox issue, but should be fixed by the addition of `git` upstream.

**Comment by dr460nf1r3** [comment]
Oh yes, I remember that issue. I think I did exactly the same which yielded the same result, I'm yet clueless about why it happens. Sematic versioning will be a big help here!

**Comment by Technetium1** [comment]
I've manually added git to makedepends again and we have a build:
`Finished making: nuclear-player-bin 1667906953281:2022118_2aafe80b9a7a18d4b506b4f8b92005cc-2 (Sun 20 Nov 2022 12:02:57 AM CET)`

**Comment by xiota** [comment]
`nuclear-player-bin` no longer needs interfere to build.

<details><summary>However, <code>PKGBUILD</code> does not end with a newline, which causes toolbox to quit before doing anything useful.</summary>

```
Downloading: nuclear-player-bin
Trying to make directory...
Finished preparing nuclear-player-bin.
Starting making nuclear-player-bin at Tue Sep 19 07:07:52 CEST 2023
Building package "nuclear-player-bin"
:: Synchronizing package databases...
 core downloading...
 extra downloading...
 community downloading...
 multilib downloading...
 chaotic-aur downloading...
:: Starting full system upgrade...
 there is nothing to do
umount: /home/xiota/nuclear-player-bin/machine/root/home/main-builder/pkgwork unmounted
umount: /home/xiota/nuclear-player-bin/machine/root/home/main-builder/.ccache unmounted
umount: /home/xiota/nuclear-player-bin/machine/root/home/main-builder/pkgsrc unmounted
umount: /home/xiota/nuclear-player-bin/machine/root/var/cache/pacman/pkg unmounted
umount: /home/xiota/nuclear-player-bin/machine/root/var/pkgdest unmounted
umount: /home/xiota/nuclear-player-bin/machine/root (overlay) unmounted

real    0m1.432s
user    0m0.216s
sys     0m0.362s
Trying to deploy log file...
'/home/xiota/nuclear-player-bin.log' -> '/srv/http/repos//chaotic-aur/logs/nuclear-player-bin.log'
Invalid package, last build did not succeed, or already deployed.
Cleaning "nuclear-player-bin"...
Waiting all jobs to finish
```
</details>

**Comment by xiota** [comment]
@Technetium1 Drop candidate?  This package uses [electron 12](https://github.com/nukeop/nuclear/blob/b1533c5ee2ec69c8f2ec9d92728cea8a1f6ed1d7/package.json#L42).
