### ISSUE TITLE
[Request] keeweb-desktop-bin

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1895]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/keeweb-desktop-bin
~~https://aur.archlinux.org/packages/keeweb-git~~
~~https://aur.archlinux.org/packages/keeweb~~

### Utility this package has for you

Desktop password manager compatible with KeePass databases

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
`keeweb` depends on Electron 12, so that one is declined.

**Comment by xiota** [comment]
Dropping because Electron 13.  Also, fails to build on v4.  Metrics 6.
