### ISSUE TITLE
[Request] patchbay + patchbay-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1897]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/patchbay-git
https://aur.archlinux.org/packages/patchbay

### Utility this package has for you

An alternative Secure Scuttlebutt client interface that is fully compatible with Patchwork

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
I'm going to reject this one for now, unless there's more interest in it from others. It seems to be 'barely afloat'.
https://github.com/ssbc/patchbay/issues/393#issuecomment-1077690207

**Comment by tio-trom** [comment]
Hm ok that's sad to hear about the development...it was promising. I understand your decision.
