### ISSUE TITLE
[Request] geometrize-bin

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1898]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/geometrize-bin

### Utility this package has for you

A desktop app that geometrizes images into geometric primitives

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because AUR package is orphaned.  Also, it is a Qt5 app, so #3157 may be relevant.  Metrics 3.
