### ISSUE TITLE
[Request] knowte

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1900]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/knowte

### Utility this package has for you

A note taking application that allows you to quickly and easily organize and find your notes

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Last release was more than a year ago, there is no -git version :(

**Comment by tio-trom** [comment]
> Last release was more than a year ago, there is no -git version :(

I've been in contact with the developer some time ago and the development was slow but still in working-phase. This note taking app is quite good and works fine from my tests. Up to you if you want to include it, but it does not seem like an abandoned project. https://github.com/digimezzo/knowte

**Comment by Technetium1** [comment]
https://github.com/digimezzo/knowte/commit/52fe424a9a395540f592ff65b5ea2dcc6e148d6c
> Dec 13, 2021

This was the last commit, and that's what leads me to assume it was abandoned. Please do reopen this issue when (if?) the next update happens.

**Comment by tio-trom** [comment]
knowte-bin is up to date now https://aur.archlinux.org/packages/knowte-bin

**Comment by Technetium1** [comment]
@xiota my only issue with adding this is `electron17`, but it's suddenly apparent we are providing this and other EOL versions still!
Do you think we should consider dropping the older ones? How many packages would be affected, does it maybe deserve a new issue?

**Comment by xiota** [comment]
I just built `knowte` from source.  Will update `aur/knowte` "soon".  Had to use `nvm` to build because it requires old nodejs/etc, but after that, seems to run with `extra/electron` (25).

**Comment by xiota** [comment]
@tio-trom `knowte` 3.0.0 and `knowte-git` 3.0.0.r12.gb86ef565 are in repo for testing.  Please let me know whether they work.

**Comment by tio-trom** [comment]
Both are working. Thank you very much!

**Comment by xiota** [comment]
In the last couple years, I've learned that using mismatched electron is prone to problems.  This package can be left alone for now because it still seems to work.  However, usage is very low, pkgstats zero since early 2022.  Metrics 2.
