### ISSUE TITLE
[Request] spectrum

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1901]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/spectrum

### Utility this package has for you

The community platform for the future.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Spectrum is going read-only in favor of GitHub discussions :pensive:
https://spectrum.chat/spectrum/general/join-us-on-our-new-journey~e4ca0386-f15c-4ba8-8184-21cf5fa39cf5

**Comment by tio-trom** [comment]
Oh damn....ok. Good to know. Thanks for spotting this! We can remove it.
