### ISSUE TITLE
[Request] xcursor-chameleon

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1903]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/xcursor-chameleon-anthracite
https://aur.archlinux.org/packages/xcursor-chameleon-darkskyblue
https://aur.archlinux.org/packages/xcursor-chameleon-skyblue
https://aur.archlinux.org/packages/xcursor-chameleon-white

### Utility this package has for you

Chameleon X Cursor Theme 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
White is the only one that's not an orphan :eyes:

**Comment by tio-trom** [comment]
> White is the only one that's not an orphan eyes

I understand but these are cursor themes should work well. Up to you, you can remove it if you think is not ok. Usually orphans get adopted.

**Comment by xiota** [comment]
Dropping because upstream source is gone.
