### ISSUE TITLE
[Request] xcursor-lliurex

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1904]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/xcursor-lliurex

### Utility this package has for you

A cursor theme inspirated on oxygen theme, but drawn from the scratch.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Download URL is invalid:
```
ERROR: Failure while downloading https://dl.opendesktop.org/api/files/downloadfile/id/1460735232/s//t//153068-lliurex-cursors.tar.xz
```

**Comment by Technetium1** [comment]
[I flagged it](https://aur.archlinux.org/pkgbase/xcursor-lliurex/flag-comment)

**Comment by Inetol** [comment]
This package no longer exists in the AUR, the issue should be closed.
