### ISSUE TITLE
[Request] gtk-theme-shades-of-gray

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1906]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/gtk-theme-shades-of-gray

### Utility this package has for you

A dark GTK-theme (GNOME, Cinnamon, Xfce, Openbox) in 8 color variants with themes for Firefox and Thunderbird.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Upstream archived:
> Note: I archived the repository on 02/15/2021 because I can't give it the attention it needs right now.
