### ISSUE TITLE
[Request] moka-icon-theme-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1907]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/moka-icon-theme-git

### Utility this package has for you

An icon theme designed with a minimal, flat style, using simple geometry & colours.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
[Upstream is dead](https://github.com/snwh/moka-icon-theme) and the [URL](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=moka-icon-theme-git#n9) is incorrect. R.I.P. to this theme.
