### ISSUE TITLE
[Request] flat-remix-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1908]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/flat-remix
https://aur.archlinux.org/packages/flat-remix-git

### Utility this package has for you

Flat Remix is an icon theme inspired by material design. It is mostly flat using a colorful palette with some shadows, highlights, and gradients for some depth.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
`flat-remix` is not updated.
