### ISSUE TITLE
[Request] raven-reader-bin

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1909]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/raven-reader-bin

### Utility this package has for you

Simple Desktop RSS Reader made using VueJS

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Very cool! I added it to my own list here: https://github.com/Technetium1/ChocolateyUpdate/commit/0805f94c2006844c079bf2d537ad73a8cd85ace8

**Comment by xiota** [comment]
Dropping because uses EOL Electron/19.1.9.  Metrics 6.
