### ISSUE TITLE
[Request] stellarium

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1912]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/stellarium

### Utility this package has for you

This is am amazing one please add :D - Software which renders realistic skies in real time with OpenGL

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by tio-trom** [comment]
Fails to build because of dependency issue `error: target not found: calcmysky` https://builds.garudalinux.org/repos/chaotic-aur/logs/filtered/dep-not-in-repo/stellarium.log

**Comment by dr460nf1r3** [comment]
https://github.com/chaotic-aur/packages/issues/2086

**Comment by xiota** [comment]
Dropped because moved to extra.  Metrics 75.
