### ISSUE TITLE
[Remove] celestia & addons / plugins

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1913]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/celestia

### Utility this package has for you

Another amazing app for those interested in space - Real-time space simulation

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
I'll also add `celestia-addon-*` / [`celestia-m42-plugin`](https://aur.archlinux.org/packages/celestia-m42-plugin)

**Comment by Technetium1** [comment]
- [ ] celestia-addon-2009_exoplanets
- [ ] celestia-addon-2010_exoplanets
- [ ] celestia-addon-2010_exoplanets_ii
- [ ] celestia-addon-apollo_soyuz
- [ ] celestia-addon-atlantis_2
- [ ] celestia-addon-deep_impact
- [ ] celestia-addon-deep_impact_spacecraft
- [ ] celestia-addon-earth_without_water_2
- [ ] celestia-addon-global_water_volume
- [ ] celestia-addon-hubble_space_telescope
- [ ] celestia-addon-international_space_station
- [ ] celestia-addon-millenium_falcon
- [ ] celestia-addon-spaceman_spiff
- [ ] celestia-addon-spitzer_space_telescope
- [ ] celestia-addon-star_destroyer
- [ ] celestia-addon-sun
- [ ] celestia-addon-tatooine_endor_deathstar
- [ ] celestia-addon-ulysses
- [ ] celestia-addon-vaders_tie_fighter
- [ ] celestia-addon-voyagers
- [ ] celestia-addon-xwing

**Comment by dr460nf1r3** [comment]
> Celestia addons failing to build because bad https certificate.  http would probably work.  Metrics unavailable.  Drop or add interferes?

If metrics unavailable that likely means it hasn't been downloaded. Would personally drop in that case.

**Comment by xiota** [comment]
@dr460nf1r3 All metrics apparently reset to zero.  Also, v4 buiders having issues.  Immortalis is running, but garuda isn't.  Don't know if related to metrics issue.

**Comment by dr460nf1r3** [comment]
> Immortalis is running, but garuda isn't.

Just fixed that. Wasn't able to connect to the Redis instance. 

> Don't know whether problems with builder and metrics could be related.

No, that's impossible. Both build tools and router have no connection to each other whatsoever. But yes, I agree something is up, looking at the website:

> Total users over the last months: 650

I don't think metrics have been wiped, but am checking database rn.

**Comment by Technetium1** [comment]
Celestia Motherlode admins have just been notified of the expired cert. When I checked previously there were around 20 users, varying greatly based on addon.

**Comment by xiota** [comment]
Added interferes: https://github.com/chaotic-aur/interfere/commit/533deb4ff81364474facfd344b1ca38ac8a99cec

**Comment by Technetium1** [comment]
These are to be dropped since upstream has abandoned addons and no longer controls the site: https://github.com/CelestiaProject/Celestia/issues/2228#issuecomment-2294929000

**Comment by Technetium1** [comment]
https://github.com/chaotic-aur/interfere/commit/59c171735d52d76f0c9210cca3fba6386bd8165a

**Comment by xiota** [comment]
Is the main `celestia` package to be kept?

**Comment by Technetium1** [comment]
Not unless multiple people _really_ want it back.
There is an appimage available as well: https://github.com/CelestiaProject/Celestia/issues/333

**Comment by tio-trom** [comment]
Is it possible to keep the main Celestia package in the chaotic repo? It works perfectly fine from AUR.
