### ISSUE TITLE
[Bug] linux-tkg-* linux-lts-tkg-* package name, description, and urls uninformative

### ISSUE THREAD

**Issue by xiota** [chaotic-aur/packages#1915]
### What happens?

The linux-tkg package name, description, and url are uninformative.  How are they different from mainline? How are bmq, cfs, pds different? What is different in the generic package? What is lto?

### What is expected to happen?

The description should state what the major difference is between the modified kernel package and standard/mainline.

The url should point to https://github.com/Frogging-Family/linux-tkg

**Comment by xiota** [comment]
I guess it's not as bad as I thought.  Looks like mainly the linux-tkg packages are problematic.  How are they different from mainline?  How are bmq, cfs, pds different?  What is different in the generic package?  What is lto?  I'll update the title and description of this issue.
```
chaotic-aur/linux-tkg-bmq 5.19.6-269
The Linux-tkg kernel and modules
chaotic-aur/linux-tkg-bmq-generic_v3 5.19.6-269
The Linux-tkg kernel and modules
chaotic-aur/linux-tkg-cfs 5.19.6-269
The Linux-tkg kernel and modules
chaotic-aur/linux-tkg-cfs-generic_v3 5.19.6-269
The Linux-tkg kernel and modules
chaotic-aur/linux-tkg-cfs-lto_v3 5.19.6-269
The Linux-tkg kernel and modules
chaotic-aur/linux-tkg-pds 5.19.6-269
The Linux-tkg kernel and modules
chaotic-aur/linux-tkg-pds-generic_v3 5.19.6-269
The Linux-tkg kernel and modules
chaotic-aur/linux-vfio 5.17.1.arch1-1
The Linux kernel and modules
```

**Comment by Technetium1** [comment]
If this is the case, I think reporting upstream would make the most sense: https://github.com/Frogging-Family/linux-tkg

**Comment by dr460nf1r3** [comment]
I agree with @Technetium1. The `pkgname` is quite informative already - it contains the scheduler as well as eventual extra modifications we provide. Further information can be obtained by reading the TKG kernels repo README, eg. in the [customization](https://github.com/Frogging-Family/linux-tkg#customization-options) section. 

Putting information like `generic_v3 variant` or `LTO variant` in `pkgdesc` won't actually help to understand the package's purpose. To understand those terms, it is on you to do some research on your own :) most of those, eg. `vfio` are specialized kernels that serve no purpose beyond their intended use case.

**Comment by xiota** [comment]
I'll report upstream to request that the url be changed to the source of the patches instead of kernel.org.
