### ISSUE TITLE
[Outdated] visual-studio-code-insiders-bin

### ISSUE THREAD

**Issue by hmnd** [chaotic-aur/packages#1916]
### If available, link to the latest build

[visual-studio-code-insiders-bin.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/visual-studio-code-insiders-bin.log)

### Package name

visual-studio-code-insiders-bin

### Latest build

1661146970-1

### Latest version available

1662529402-1

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

No new builds in chaotic-aur since Aug. 23.

**Comment by Technetium1** [comment]
`Finished making: visual-studio-code-insiders-bin 1662529402-1 (Wed 07 Sep 2022 09:52:14 PM UTC)`
