### ISSUE TITLE
[Bug] [Request] linux-tkg-* include CONFIG_X86_AMD_PSTATE=m in .config

### ISSUE THREAD

**Issue by pkejval** [chaotic-aur/packages#1918]
### What happens?

Trying to use "new" amd-pstate scaling driver https://docs.kernel.org/admin-guide/pm/amd-pstate.html
Found out that linux-tkg-* from ChaoticAUR doesn't have it included in .config file with this command
`cat /usr/lib/modules/5.19.7-269-tkg-pds/build/.config  | grep  CONFIG_X86_AMD_PSTATE=m`

```
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_driver
acpi-cpufreq
```

### What is expected to happen?

```
cat /usr/lib/modules/5.19.7-269-tkg-pds/build/.config  | grep  CONFIG_X86_AMD_PSTATE=m
CONFIG_X86_AMD_PSTATE=m
```

```
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_driver
amd-pstate
```

**Comment by dr460nf1r3** [comment]
I'm on `linux-tkg-cfs-llvm`, which does in fact have pstate enabled. 

![image](https://user-images.githubusercontent.com/12834713/190856451-32ba1c17-08a0-4471-9856-cbaa5874af99.png)

```
λ cat /usr/lib/modules/5.19.9-269-tkg-cfs-llvm/build/.config | grep AMD_P
CONFIG_X86_AMD_PLATFORM_DEVICE=y
CONFIG_PERF_EVENTS_AMD_POWER=m
CONFIG_X86_AMD_PSTATE=y
CONFIG_AMD_PHY=m
CONFIG_AMD_PTDMA=m
CONFIG_AMD_PMC=m

**Comment by dr460nf1r3** [comment]
If this is still an issue, just drop a message here. It works over here, hence I'm closing this issue.
