### ISSUE TITLE
[Outdated] xorg-xwayland-git

### ISSUE THREAD

**Issue by VexfulNiko** [chaotic-aur/packages#1919]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/xorg-xwayland-git.log

### Package name

xorg-xwayland-git

### Latest build

21.1.4.r443.g399cf1272-1

### Latest version available

master

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

Version numbering seems to be broken, seeing by the ending of the log.

**Comment by Technetium1** [comment]
@VexfulNiko seems this has built automatically since this was opened, please reopen if it's still an issue!

> ==> Making package: xorg-xwayland-git 21.1.2.901.r270.gccffe90c3-1 (Sat 10 Sep 2022 03:32:17 PM -03)

**Comment by Technetium1** [comment]
Seems I misread, the versioning is indeed wrong :eyes:

**Comment by dr460nf1r3** [comment]
Seems to be working by now! 
`
==> Updated version: xorg-xwayland-git 21.1.4.r450.ge37f18ee9-1`
