### ISSUE TITLE
[Request] Syncterm

### ISSUE THREAD

**Issue by Paulie420** [chaotic-aur/packages#1922]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/syncterm

### Utility this package has for you

SyncTERM is a terminal software for connecting to ANSI based BBSes. Its a bit tricky to compile, but there is a how-to for Ubuntu-based distros that I use to find the appropriate Arch pre-requisites: https://www.erb.pw/how-to-install-syncterm-for-linux-from-source/  
I would love having this as an AppImage for portability, and offering to my BBS users.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

I think supporting old tech is important, and love that Syncterm is a up to date developed software. Hope you think its worthy.

**Comment by Technetium1** [comment]
There are a discomforting amount of warnings in the logs, but everything seems fine.
https://builds.garudalinux.org/repos/chaotic-aur/logs/syncterm.log

**Comment by xiota** [comment]
This package is failing to build because missing depends.  However, from request description, this may not satisfy OP's needs because it is not an AppImage.  Metrics 4.
