### ISSUE TITLE
[Request] thorium-reader, thorium-reader-git

### ISSUE THREAD

**Issue by evansan** [chaotic-aur/packages#1924]
### Link to the package(s) in the AUR

~~thorium-bin~~
https://aur.archlinux.org/packages/thorium-reader
https://aur.archlinux.org/packages/thorium-reader-git

### Utility this package has for you

ebook reader

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
This looks fantastic!

**Comment by xiota** [comment]
`thorium-reader-bin` and `thorium-reader` are in the repo.  Not added to list yet because of upstream issues.
