### ISSUE TITLE
[Outdated] nvidia-zen is still built for 5.19.5 when latest zen kernel is 5.19.7

### ISSUE THREAD

**Issue by jkcdarunday** [chaotic-aur/packages#1926]
### If available, link to the latest build

[nvidia-zen.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/nvidia-zen.log)

### Package name

nvidia-zen

### Latest build

515.65.01.2+5.19.7.zen2.1-1

### Latest version available

515.65.01.2+5.19.5.zen1.1-1

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by Technetium1** [comment]
https://github.com/chaotic-aur/packages/blob/0f774ba4a487a06da810397ee7cf4cfce73f470d/garuda-cluster/hourly.2.txt#L154

**Comment by Technetium1** [comment]
Done!
```==> Finished making: nvidia-zen 515.65.01.2+5.19.7.zen2.1-1 (Sun 11 Sep 2022 03:46:29 PM UTC)```
