### ISSUE TITLE
[Request] mozillavpn, mozillavpn-git

### ISSUE THREAD

**Issue by braveatnight** [chaotic-aur/packages#1927]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/mozillavpn
https://aur.archlinux.org/packages/mozillavpn-git

### Utility this package has for you

This package is a tool to make your internet connection more private and bypass network filtering. 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
I recommend you consider [Mullvad](https://mullvad.net/) as well, to support the upstream provider. [It's who Mozilla resells service from](https://mullvad.net/en/help/partnerships-and-resellers/).

**Comment by braveatnight** [comment]
Okay but that's completely besides the point, it's a piece of software that's generally well known and could be useful to a great deal of people. It seems kinda arbitrary to set it to a low priority just because you don't agree with their business model

**Comment by xiota** [comment]
Pausing `mozillavpn` because it is currently broken with multiple issues.  Rebuild required extensive changes to pkgbuild.  Metrics 64.

`mozillavpn-git` is in repo for testing.

If `mozillavpn` is not fixed "soon", should an interfere be added?  Or switch to `mozillavpn-git`?  Or both?

**Comment by Technetium1** [comment]
@xiota both :)

**Comment by xiota** [comment]
Interfere uses same pkgbuild for both mozillavpn and mozillavpn-git... Cached sources are reused.
