### ISSUE TITLE
[Request] icaclient

### ISSUE THREAD

**Issue by evansan** [chaotic-aur/packages#1928]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/icaclient

### Utility this package has for you

access remote virtual desktop and applications

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

/opt/Citrix/ICAClient❯ gdb /opt/Citrix/ICAClient/selfservice
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /opt/Citrix/ICAClient/selfservice...
(No debugging symbols found in /opt/Citrix/ICAClient/selfservice)

**Comment by xiota** [comment]
Dropped because depends on EOL GTK2.  Metrics 287.

**Comment by xiota** [comment]
License is also problematic: https://github.com/chaotic-aur/packages/issues/4323#issuecomment-4733558770
