### ISSUE TITLE
rebuild qt6gtk2

### ISSUE THREAD

**Issue by DioEgizio** [chaotic-aur/packages#1929]
### What happens?

Qt 6.3.2 is in arch repos, so using it right now provided by chaotic aur causes a segfault

### What is expected to happen?

Work lol

### More information

Rebuild it and it'd work

**Comment by Technetium1** [comment]
```==> Finished making: qt6gtk2 0.2-1.1 (Tue 13 Sep 2022 05:56:40 PM CEST)```
