### ISSUE TITLE
[Request] nchat-git

### ISSUE THREAD

**Issue by maydeafmute** [chaotic-aur/packages#1930]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/nchat-git

### Utility this package has for you

Using my telegram account from ssh.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Console telegram client.

**Comment by Technetium1** [comment]
This is a cool program

**Comment by xiota** [comment]
This package installs to `/usr/local`.  Flagged two months ago with no response from maintainer.

@Technetium1 Drop or interfere?

**Comment by Technetium1** [comment]
@xiota should be reasonable to interfere, the only alternative we provide is https://github.com/paul-nameless/tg which isn't **nearly** as active at this point.
