### ISSUE TITLE
[Request] r8152-dkms

### ISSUE THREAD

**Issue by DonRichie** [chaotic-aur/packages#1931]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/r8152-dkms

### Utility this package has for you

Needed to make USB-C to RJ45 Ethernet Adapters work, which use Realtek RTL8152/RTL8153/RTL8154/RTL8156 chips

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because no longer needed since kernel 6.3.
