### ISSUE TITLE
[Outdated] ananicy-cpp no longer runs with the latest libfmt

### ISSUE THREAD

**Issue by skeithc** [chaotic-aur/packages#1932]
### If available, link to the latest build

[ananicy-cpp.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/ananicy-cpp.log)

### Package name

ananicy-cpp

### Latest build

1.0.0.rc6-1.1

### Latest version available

1.0.0.rc6-1.2

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

ananicy-cpp no longer runs with an up to date Arch Linux installation as the last build dynamically loads libfmt 8 but the package in community is now libfmt 9.1.0

The following error occurs when running it:
```
ananicy-cpp: error while loading shared libraries: libfmt.so.8: cannot open shared object file: No such file or directory
```

Building directly from the AUR works so I believe this simply needs a rebuild with the latest libfmt package installed.

**Comment by dr460nf1r3** [comment]
Should be fixed, I bumped the package. :)

**Comment by skeithc** [comment]
Thanks! It works fine now.
