### ISSUE TITLE
[Request] gtuber-git

### ISSUE THREAD

**Issue by bbhtt** [chaotic-aur/packages#1934]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/gtuber-git

### Utility this package has for you

Clapper is already included in Chaotic AUR. Clapper 0.5.0 https://github.com/Rafostar/clapper/releases/tag/0.5.0 removed inbuilt support for playing videos from Youtube etc. and separated it to [gtuber ](https://github.com/Rafostar/gtuber). It was also added as an optdepends for the AUR Clapper package recently https://aur.archlinux.org/cgit/aur.git/commit/?h=clapper&id=8da672aa980d5a7d9b8e3c9a66f8da1db6a910e3. So it'd be great to have gtuber in Chaotic AUR.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Added in #750
