### ISSUE TITLE
themix-icons-archdroid-git doesn't download freezes updates until Ignored [Bug] 

### ISSUE THREAD

**Issue by cg00001** [chaotic-aur/packages#1937]
### What happens?

I had to put this in my pacman.conf to update.
`IgnorePkg = themix-icons-archdroid-git`
![k223249](https://user-images.githubusercontent.com/38960370/190873759-e487d36b-f092-4e3c-b8b9-f98e99c42c91.png)

### What is expected to happen?

Download and install.

**Comment by Technetium1** [comment]
@cg00001 Why can't you download it? We need more details. Do you have the latest mirrorlist? Have you made any adjustments to it? What about `chaotic-keyring`?

**Comment by cg00001** [comment]
> @cg00001 Why can't you download it? We need more details. Do you have the latest mirrorlist? Have you made any adjustments to it? What about `chaotic-keyring`?

Everything is in order as per https://aur.chaotic.cx/
The problem is that package was a dependency of another while I freshly installed EndevourOS (due to the minimal Bash bug I couldn't install pure Arch, don't ask).
I disabled Chaotic-Aur repo, installed it from AUR, then Ignored it and enabled Chaotic-Aur again to make updates work.

**Comment by Technetium1** [comment]
You are using `pacman -Syu` to update, right? Are there any network errors?

**Comment by cg00001** [comment]
I reinstalled chaotic-mirrorlist, and tried to update the system.
This is what happens:
https://zerobin.net/?3fa2d19955d7eca5#ZIEuJ4qO83WBUtzugyli7Rue6FthTY/pFxiAMCRwaLQ=

**Comment by Technetium1** [comment]
Bumped and rebuilt https://github.com/chaotic-aur/interfere/commit/eaf98c564c274aa1b1647fe5d451f30846899aa2, try now.

**Comment by cg00001** [comment]
> Bumped and rebuilt [chaotic-aur/interfere@eaf98c5](https://github.com/chaotic-aur/interfere/commit/eaf98c564c274aa1b1647fe5d451f30846899aa2), try now.

Thank you, works fine now.
