### ISSUE TITLE
[Bug] Chromium-wayland-vaapi doesn't launch

### ISSUE THREAD

**Issue by userofryzen** [chaotic-aur/packages#1938]
### What happens?

When trying to launch from a manjaro computer there are errors on libs, may be is a thing of manjaro only and there is need to wait to an update from manjaro but.. Someone on arch can update the system and tell us pls?

### What is expected to happen?

/usr/lib/chromium/chromium: error while loading shared libraries: libFLAC.so.12: cannot open shared object file: No such file or directory

### If possible, please attach logs

there are no more

### More information

Manjaro stable. I have not tried to build from arch because of the huge time needed and I have not now...

**Comment by Technetium1** [comment]
@userofryzen [it looks like someone else is having issues on Manjaro as well](https://aur.archlinux.org/packages/chromium-wayland-vaapi#comment-882086). Ensure you have `flac` installed?

**Comment by userofryzen** [comment]
> @userofryzen [it looks like someone else is having issues on Manjaro as well](https://aur.archlinux.org/packages/chromium-wayland-vaapi#comment-882086). Ensure you have `flac` installed?

This comment is mine too jaja and yes I have it installed. 
Nevermind I think the problem is that the package on manjaro repos is old and needs to be updated, actually in testing the package is updated so.. a week or so to get it in stable to test it if nobody says nothing here

**Comment by Technetium1** [comment]
The package is most definitely up to date, at least as far as matching the AUR.

**Comment by userofryzen** [comment]
> The package is most definitely up to date, at least as far as matching the AUR.

No, no, I meant the flac package, not this one

**Comment by dr460nf1r3** [comment]
Most likely it needs a rebuild. Just bumped the package's `pkgver`, it'll be built with the next daily `ufscar-hpc` routine.

**Comment by userofryzen** [comment]
I'll test it when I have time but I think that the problem here is a lib that in manajro is older than in arch, so at time compilation it links the new and there is no back compability. It's not the only time that it happens to me, with mega with arch official repo from mega happens to sometimes. It's why I said that le'ts wait. And for me at least this package is not "high priority" ones

**Comment by Technetium1** [comment]
Actually now that you mention it, this technically is high priority due to the amount of users of this package.

**Comment by dr460nf1r3** [comment]
Yep. I just tried launching `ungoogled-chromium`, which works fine over here. If it still doesn't work, its a Manjaro issue we can't fix sadly.

**Comment by dr460nf1r3** [comment]
Considering it done, thus closing. If it still occurs, feel free to reopen the issue! :)
