### ISSUE TITLE
[Outdated]: epiphany-git

### ISSUE THREAD

**Issue by 0xMRTT** [chaotic-aur/packages#1939]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/epiphany-git.log

### Package name

`epiphany-git`

### Latest build

`43.alpha-1`

### Latest version available

` 42.beta+really+294+gf8a4ef7cb-1`

### Have you tested if the package builds in a clean chroot?

- [x] Yes

**Comment by Technetium1** [comment]
> Run-time dependency libportal-gtk3 found: NO (tried pkgconfig and cmake)

**Comment by Technetium1** [comment]
Great.
```
Run-time dependency gcr-3 found: NO (tried pkgconfig and cmake)

meson.build:85:0: ERROR: Dependency "gcr-3" not found, tried pkgconfig and cmake```

**Comment by Technetium1** [comment]
Apparently we're replacing depends, not adding to…

**Comment by Technetium1** [comment]
```
Finished making: epiphany-git 43.0+7+g10d6ea022-1 (Sun 18 Sep 2022 08:20:22 PM UTC)
```

**Comment by Technetium1** [comment]
I flagged the package: https://aur.archlinux.org/pkgbase/epiphany-git/flag-comment

**Comment by xiota** [comment]
Is this a problem with the build server?  Build [log] has this error:
```
:: Proceed with installation? [Y/n] 
checking keyring...
checking package integrity...
:: File /var/cache/pacman/pkg/libhandy-git-1.8.0.r21.g691fa96-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (checksum)).
Do you want to delete it? [Y/n] error: failed to commit transaction (invalid or corrupted package)
```

**Comment by dr460nf1r3** [comment]
```
Run-time dependency gcr-4 found: NO (tried pkgconfig and cmake)

meson.build:88:0: ERROR: Dependency "gcr-4" not found, tried pkgconfig and cmake

```

**Comment by Technetium1** [comment]
[Dependency requested for orphan!](https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/message/ZTUUXRQYIDIREANS4JYP5QQXSTLXHSQV/) Hopefully someone will adopt [`libadwaita-git`](https://aur.archlinux.org/pkgbase/libadwaita-git) because we're stuck building `1.3.rc+60+g24f9bbe0`. Thus we have this error:

```py
ERROR: Dependency lookup for libadwaita-1 with method 'pkgconfig' failelibadwaita-1' ['>= 1.4.alpha'] found '1.3.1'.
```
