### ISSUE TITLE
[Request] pokete-git

### ISSUE THREAD

**Issue by VexfulNiko** [chaotic-aur/packages#1940]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/pokete-git

### Utility this package has for you

Pretty fun as a game (Pokémon like terminal based game)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
```
# Issue 1940
scrap_engine-git:https://aur.archlinux.org/scrap_engine-git.git # (dep pokete-git)
pokete-git
```

**Comment by Technetium1** [comment]
I've commented about the missing `python-pip` for `scrap_engine-git`, and about the latest failure:
https://aur.archlinux.org/packages/pokete-git#comment-882097

```
# pkg-config --cflags  -- alsa
Package alsa was not found in the pkg-config search path.
Perhaps you should add the directory containing `alsa.pc'
to the PKG_CONFIG_PATH environment variable
Package 'alsa', required by 'virtual:world', not found
pkg-config: exit status 1
```
[Log here](https://builds.garudalinux.org/repos/chaotic-aur/logs/pokete-git.log)
