### ISSUE TITLE
[Request] endeavour & endeavour-git

### ISSUE THREAD

**Issue by 0xMRTT** [chaotic-aur/packages#1943]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/endeavour
https://aur.archlinux.org/packages/endeavour-git

### Utility this package has for you

Todo list for GNOME

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping `endeavour-git` because of libadwaita dependency issues.
