### ISSUE TITLE
[Request] vala-panel-appmenu-xfce-git

### ISSUE THREAD

**Issue by erenfro** [chaotic-aur/packages#1944]
### Link to the package(s) in the AUR

[vala-panel-appmenu-xfce-git](https://aur.archlinux.org/pkgbase/vala-panel-appmenu-xfce-git)

### Utility this package has for you

This adds appmenu menu support for GTK+ Applications. Helpful addition to packages like WhiteSur that adds macOS style themes to Linux in various distros. This one is for Xfce specifically, but there's more for budgie and mate as well.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

This requires vala-panel which chaotic-aur already has a fix for the missing git makedepends.

**Comment by Technetium1** [comment]
Ah, one of the previously requested failed builds.
https://github.com/chaotic-aur/packages/issues/1705#issuecomment-1232139322
[vala-panel-appmenu-xfce-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/vala-panel-appmenu-xfce-git.log)

**Comment by erenfro** [comment]
Seems to be somehow not installing vala, which has the valac compiler. Yet it's in this package's makedepends. So that's unusual.

**Comment by erenfro** [comment]
Yeah, my aurto build has it building fine, on my own server.

**Comment by Technetium1** [comment]
https://github.com/chaotic-aur/interfere/commit/14adcf58e81b746505c94f4357f940494871c055 an old interfere strikes again :eyes:

**Comment by erenfro** [comment]
Haha, wow. So that needs vala and I think vala-panal as well, but the rest looks fine.

**Comment by Technetium1** [comment]
Let's see what happens without any interference. I'd rather not disable things unless they're breaking something. Even if we don't use the entirety of what the pkgbase provides, someone else might.

**Comment by erenfro** [comment]
True enough!

**Comment by tio-trom** [comment]
Hey so there are some conflicts with this package. 

`- /usr/share/applets/org.valapanel.appmenu.plugin exists in both vala-panel-appmenu-common-git and vala-panel-appmenu-xfce-git`

It was fixed recently and the vala panel packages need a rebuild I suppose. See the last comments here please https://aur.archlinux.org/pkgbase/vala-panel-appmenu-xfce-git

The AUR packages work well but not the chaotic AUR ones.

**Comment by tio-trom** [comment]
> chaotic-aur should rebuild vala-panel-appmenu with latest vala-panel. Or rebuild it yourself. If you build vala-panel-appmenu with outdated vala-panel, and then update, you will still suffer from the bug.

Fro AUR's maintainer https://aur.archlinux.org/pkgbase/vala-panel-appmenu-xfce-git

**Comment by Technetium1** [comment]
@tio-trom Thank you!
`Finished making: appmenu-glib-translator-git 24.02.r32.gbada552-1 (Sun 05 May 2024 08:11:57 PM CEST)`
`Finished making: vala-panel-appmenu-xfce-git 24.02.r32.gbada552-1 (Sun 05 May 2024 08:13:26 PM CEST)`
Please reinstall the packages.

**Comment by tio-trom** [comment]
Unfortunately I got the same conflict errors with these:

![2024-05-05_23-01](https://github.com/chaotic-aur/packages/assets/38043315/965ff55f-8d7c-498b-be87-2f65e57fe3a6)

They all work fine from our repos:
```
vala-panel-appmenu-xfce-git-24.02.r31.gfdf2821-1-x86_64.pkg.tar
vala-panel-appmenu-common-git-24.02.r31.gfdf2821-1-any.pkg.tar
```
Did you first rebuilt the vala-panel-git package and after that rebuilt the above ones?

**Comment by Technetium1** [comment]
@tio-trom I've rebuilt them again. The first time was during a routine, which may have caused an issue. I've also cleared the cache. Please confirm it's working.

**Comment by tio-trom** [comment]
Can you please tell me what's the versioning of these packages? So that I can properly check them.

```
appmenu-glib-translator-git
vala-panel-appmenu-xfce-git
vala-panel-appmenu-registrar-git
```

**Comment by Technetium1** [comment]
```
appmenu-glib-translator-git-24.02.r32.gbada552-1
vala-panel-appmenu-xfce-git-24.02.r32.gbada552-1
vala-panel-appmenu-registrar-git-24.02.r32.gbada552-1
```

**Comment by tio-trom** [comment]
hm I tried several times still no luck....same conflicts. I don't know what's up. It works all fine with the packages I built for our repo... https://www.drive.tromsite.com/s/BcfHfNWizskkTg8

Just to be clear - so these packages need to be built only after you have the latest vala-panel-git package already built since they need to be built against it. Now chaotic-aur has both vala-panel and vala-panel-git in the repo, so how is this working? How do you rebuild these packages against the proper vala-panel package?

**Comment by Technetium1** [comment]
I'm just noticing #1705 again, and @xiota has a good point. We should probably drop this until it's fixed.

**Comment by xiota** [comment]
> these packages need to be built only after you have the latest vala-panel-git package already built since they need to be built against it.

`vala-panel`/`vala-panel-git` is not listed in depends or makedepends of any of the `*-appmenu-*` packages.

**Comment by xiota** [comment]
I rebuilt the appmenu packages with `vala-panel-git` in makedepends.  It should work now.  Have notified maintainer of issue via comment.  Will give maintainer time to update before considering whether to add an interfere.

**Comment by xiota** [comment]
`vala-panel-appmenu-registrar-git` was rebuilt two days ago.  Is it working now?  If not, there is a problem with the pkgbuild.

**Comment by tio-trom** [comment]
hmm no same issue. Crashing all the time. All works fine with the packages I built for our TROMrepo...so there must be an issue with the way your are building them for the chaotic-aur.

**Comment by xiota** [comment]
Packages are built in clean chroot.  These packages do not have interfere, so problem is most likely in the pkgbuild.  I'll look at it later.

**Comment by xiota** [comment]
I have adopted and updated `vala-panel-appmenu`.  The stable packages (`vala-panel`, `-appmenu-`, and `-registrar`) appear to be tightly coupled and incompatible with the git packages.

I am adding back the stable packages, which have updated conflicts to avoid co-installation with the git packages.  I am also asking the maintainer of the git packages to make similar changes.
