### ISSUE TITLE
[Request] appmenu-gtk-module-git

### ISSUE THREAD

**Issue by erenfro** [chaotic-aur/packages#1946]
### Link to the package(s) in the AUR

[appmenu-gtk-module-git](https://aur.archlinux.org/pkgbase/appmenu-gtk-module-git)

### Utility this package has for you

This provides appmenu support to gtk2 and gtk3 applications, along the lines with the appmenu support modules.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because `extra/appmenu-gtk-module` is available and low usage.  Metrics 3.
