### ISSUE TITLE
[Request] minetest-git

### ISSUE THREAD

**Issue by VexfulNiko** [chaotic-aur/packages#1948]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/minetest-git

### Utility this package has for you

Pretty fun game, also useful for game development and experimental development.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Pretty funky game :3

**Comment by Technetium1** [comment]
Build fails: [minetest-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/minetest-git.log)
```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
Call Stack (most recent call first):
/usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
/usr/share/cmake/Modules/FindJPEG.cmake:106 (find_package_handle_standard_args)
lib/irrlichtmt/source/Irrlicht/CMakeLists.txt:62 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/main-builder/pkgwork/src/build-client/CMakeFiles/CMakeOutput.log".
==> ERROR: A failure occurred in build().
```

**Comment by VexfulNiko** [comment]
@Technetium1 upstream fix has been implemented as of 09/30/2022. The AUR pkg maintainer has added the missing dependencies.

**Comment by xiota** [comment]
Switching packages because upstream rebranded to Luanti.

Metrics:

* minetest-common-git # 1404
* minetest-git # 1597
* minetest-server-git # 1371
