### ISSUE TITLE
[Request] hplip-lite

### ISSUE THREAD

**Issue by epic0421** [chaotic-aur/packages#1949]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/hplip-lite

### Utility this package has for you

This AUR package is useful for me since the default hplip app installs the hp printing app and this application only provides the printer drivers, which is useful for me since I don't need the application.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Build failed: [hplip-lite.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/hplip-lite.log)

```
configure: error: "cannot find libjpeg support"
==> ERROR: A failure occurred in build().
```
