### ISSUE TITLE
[Request] linux-steam-integration

### ISSUE THREAD

**Issue by jopejoe1** [chaotic-aur/packages#1950]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/linux-steam-integration

### Utility this package has for you

Better integration for steam

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because...

* Recent Arch changes related to Steam may affect program function.
* No upstream changes since Mar 2024.
* AUR package orphaned.

Metrics 122.
