### ISSUE TITLE
[Outdated] linux-next-git, linux-next-git-docs, linux-next-git-headers

### ISSUE THREAD

**Issue by VexfulNiko** [chaotic-aur/packages#1951]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-next-git.log

### Package name

linux-next-git* pkgs

### Latest build

20220916

### Latest version available

master

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

Also semi request for linux-next-firmware-git

**Comment by Technetium1** [comment]
That firmware doesn't exist on the AUR, open a request when it does. Rebuilt successfully.
