### ISSUE TITLE
[Request] ultimate-doom-builder-git

### ISSUE THREAD

**Issue by yum13241** [chaotic-aur/packages#1952]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/ultimate-doom-builder-git

### Utility this package has for you

This app lets me make Doom maps without dealing with SLADE (slade's map editor pales in comparison)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

I couldn't find a non git version.

**Comment by Technetium1** [comment]
Build fails: [ultimate-doom-builder-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/ultimate-doom-builder-git.log)
