### ISSUE TITLE
[Request] wxwidgets-light + wxwidgets3.0

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1954]
### Link to the package(s) in the AUR

[wxwidgets-light](https://aur.archlinux.org/pkgbase/wxwidgets-light)
[wxwidgets3.0](https://aur.archlinux.org/packages/wxwidgets3.0)

### Utility this package has for you

wxWidgets is a C++ library that lets developers create applications for Windows, macOS, Linux and other platforms with a single code base. It has popular language bindings for Python, Perl, Ruby and many other languages, and unlike other cross-platform toolkits, wxWidgets gives applications a truly native look and feel because it uses the platform's native API rather than emulating the GUI. It's also extensive, free, open-source and mature. 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Link package bases, not packages.

**Comment by Technetium1** [comment]
```
wxwidgets-light:https://aur.archlinux.org/wxwidgets-light.git
```
Build fails: [wxwidgets-light.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/wxwidgets-light.log)

**Comment by tio-trom** [comment]
I reported it https://aur.archlinux.org/pkgbase/wxwidgets-light#comment-882921

**Comment by Technetium1** [comment]
Maintainer has updated it multiple times since the comment, rebuilding now.

**Comment by tio-trom** [comment]
Awesome! Thank you for adding this. Usually it takes a while to build them so it saves everyone a lot of time. Much appreciated!

**Comment by xiota** [comment]
What is the point of these packages?  Extra already has `wxwidgets-common`, `wxwidgets-gtk3` and `wxwidgets-qt5`.  There isn't really any disk savings from the "light" versions:
```
wxwidgets-common: 15.44 MiB
wxwidgets-common-light: 13.54 MiB

wxwidgets-gtk3: 17.61 MiB
wxwidgets-gtk3-light: 20.17 MiB

wxwidgets-qt5: 17.50 MiB
wxwidgets-qt5-light: 19.89 MiB
```

**Comment by FabioLolix** [comment]
The 'light' build are GStreamer free, they are pkgbuilds by sl1pkn07 but never used them

**Comment by xiota** [comment]
I plan to drop `wxwidgets-light` and `wxwidgets3.0` unless someone provides a compelling reason to keep them.  I can find no package that requires them.

How important is being gstreamer free?  The original request doesn't mention it at all.
```
$ pactree -su wxwidgets-gtk3 | grep str
libunistring
gstreamer=1.22.5

$ pactree -su wxwidgets-gtk3-light | grep str
libunistring
```

**Comment by tio-trom** [comment]
All fine with me. You can remove if you think that's fine.
