### ISSUE TITLE
[Request] bisq

### ISSUE THREAD

**Issue by LeSnake04** [chaotic-aur/packages#1955]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/bisq/

### Utility this package has for you

Open source monero exchange

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

AGPL license

Has a long build time, therefore I am requesting it.

**Comment by xiota** [comment]
Dropped because conversion to split packaging had some difficult to characterize problem.  Not sure whether worth effort to update given level of usage.   Metrics 22.
