### ISSUE TITLE
[Request] Rebuild nvidia-390xx-dkms with kernel patches from herecura

### ISSUE THREAD

**Issue by norz3n** [chaotic-aur/packages#1956]
### Link to the package(s) in the AUR

[nvidia-390xx-dkms](https://aur.archlinux.org/packages/nvidia-390xx-dkms)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

This is not a request for a new package, but rather a request to build this package in a slightly different way.
What am I saying? It would be nice if this package would be built with these patches:
[Gitlab with patches](https://gitlab.com/herecura/packages/nvidia-390xx-dkms/-/tree/herecura)
They allow the driver to be built via dkms on any kernel, it would be nice to have these patches in the repository

**Comment by Inetol** [comment]
You should discuss this with the current package maintainer.

<details><summary>Also...</summary>They are seeking a substitute to maintain this package, so if you are interested you should let the maintainer know 😁</details>

**Comment by dr460nf1r3** [comment]
It would be best if the patch is applied upstream. Let's ask @jonathonf :eyes:

**Comment by Technetium1** [comment]
Project is archived.
