### ISSUE TITLE
[Outdated] librewolf

### ISSUE THREAD

**Issue by ilovethecmdprompt** [chaotic-aur/packages#1957]
### If available, link to the latest build

[librewolf.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/librewolf.log)

### Package name

librewolf

### Latest build

104.0.2-1

### Latest version available

105.0.1-1

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

librewolf v105.0.1-1 was released yesterday. release information [here](https://gitlab.com/librewolf-community/browser/arch/-/releases/v105.0.1-1)

**Comment by dr460nf1r3** [comment]
Already rebuilt by itself 😄
