### ISSUE TITLE
[Remove] python2 (banished)

### ISSUE THREAD

**Issue by micwoj92** [chaotic-aur/packages#1958]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/python2

### Utility this package has for you

There are still some tools that require python2 as dependency.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

There are quite a few python2 packages in chaotic aur already.

**Comment by Technetium1** [comment]
We have come to the conclusion that we shouldn't go out of our way to fix this, and that it's time to remove related packages from Chaotic. I'll link them all in a commit that closes this issue later so that people are notified of the removal. I'm also adding it to the list of rejected packages.

**Comment by somebody1234** [comment]
it'd be nice if python2 *is* added, since things like renpy (unfortunately) still use python2 quite widely

**Comment by somebody1234** [comment]
... but i guess python2-bin is a thing and that's good enough

**Comment by micwoj92** [comment]
python2-bin is just a repackage of manually built python on some random dude's machine, so do what you want with it, but it would be much better to have something more trustworthy.

**Comment by Technetium1** [comment]
Well it won't be updated, so best to build it on your own machine as a one-off then.

**Comment by SolarAquarion** [comment]
https://github.com/archlinuxcn/repo/commit/a136f3e38ad3a2f489a9ac45d1d0ff10e519b726 python2 is in archlinuxcn

**Comment by dr460nf1r3** [comment]
Found yet another one, **https://builds.garudalinux.org/repos/chaotic-aur/logs/filtered/dep-not-in-repo/joplin.log**

**Comment by Technetium1** [comment]
@dr460nf1r3 https://github.com/chaotic-aur/pkgbuild-joplin can be deleted now, I don't have such power :)

**Comment by dr460nf1r3** [comment]
> @dr460nf1r3 [chaotic-aur/pkgbuild-joplin](https://github.com/chaotic-aur/pkgbuild-joplin) can be deleted now, I don't have such power :)

Done! :)

**Comment by VexfulNiko** [comment]
Should this be an issue? Since it's not going be added for a valid reason.

**Comment by dr460nf1r3** [comment]
Issues are for all kind of requests or things that need to be done. In this case we decided to not support any kind of packages depending on Python 2 since it's no longer getting updates, therefore we need to track the progress somehow :)

**Comment by Technetium1** [comment]
I'll unpin and close it once I'm certain everything related to Python 2 is gone.

**Comment by a51kot** [comment]
@Technetium1 i-ve actually found a way to  _play_  with python2

- i-ve removed the check rocess (it demanads internet)
- - im compiling on obs (de iure its a clean cheroot env) ... but obs AINT has internet...  
- if u-ve internet u could run the _check_  step  / if not.. it _WORKS_  without it  

https://build.opensuse.org/package/show/home:Area51Kacz:branches:home:ungoogled_chromium:testing/python2

**Comment by Technetium1** [comment]
@a51kot it's not just a matter of it not compiling for Chaotic, it's a matter of it being fully deprecated. I definitely *do* recommend compiling it yourself instead of using the `-bin` version, which is compiled by a random person here: https://github.com/VanillaBase1lb/python2-bin-aur

In my case, I do unfortunately still have to use it for a couple programs. I built it in a clean chroot, and it's working fine, and passing *all* the tests as well, with internet access.

**Comment by juxuanu** [comment]
It doesn't pass all the tests if you have `zlib-ng` instead of `zlib`.

**Comment by xiota** [comment]
Reasonably sure there are no remaining `python2` packages.

Created a `python2` metapackage and `pactree -rs python2` listed no other packages.

**Comment by dr460nf1r3** [comment]
That explains the things I saw in the deploy log. I was like "wtf, python2 back?" at first 😂 good idea to verify if like that.
