### ISSUE TITLE
[Request] seadrive

### ISSUE THREAD

**Issue by lowne** [chaotic-aur/packages#1960]
### Link to the package(s) in the AUR

[seadrive-gui](https://aur.archlinux.org/packages/seadrive-gui)

needs [seadrive-daemon](https://aur.archlinux.org/packages/seadrive-daemon)

### Utility this package has for you

Its sibling `seafile-client` is already in (thanks!) and seadrive is even more of a PITA (as in, very fussy) to compile.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
`libevent-compat` fails and I don't see why: [libevent-compat.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/libevent-compat.log
)
```
# Issue 1960
libevent-compat # (dep seadrive-daemon)
seadrive-daemon # (dep seadrive-gui)
seadrive-gui
```

**Comment by dr460nf1r3** [comment]
`/usr/bin/ld: ../.libs/libevent.so: undefined reference to `arc4random_addrandom'`

If I remember correctly I had this happen to FireDragon before, basically it needed a source code fix to compile.

**Comment by lowne** [comment]
FWIW the [new PKGBUILD](https://aur.archlinux.org/packages/seadrive-daemon#comment-894633) for the daemon now builds fine (and so does `seadrive-gui`)

**Comment by Technetium1** [comment]
Ready to add this now, but the checksum is wrong, so [I flagged it out of date](https://aur.archlinux.org/pkgbase/seadrive-gui/flag-comment).

**Comment by xiota** [comment]
Dropped seadrive-gui because it requires EOL Qt5.  In particular, qt5-webengine was dropped from extra.

Metrics:

* seadrive-daemon # 12
* seadrive-gui # 11

**Comment by lowne** [comment]
Fair enough; but there's already a patch for porting to qt6, and I expect the PKGBUILD to be updated relatively soon (judging by maintainer activity) - hopefully it can be reinstated then?

**Comment by Technetium1** [comment]
Yes

**Comment by xiota** [comment]
Please comment when the aur package is updated.  If not done, say in two weeks, since upstream already has Qt6 support, comment here to remind me to look into a -git package.

**Comment by lowne** [comment]
@xiota  AUR PKGBUILD has been ported to qt6 (although I can only see the commit history - the website seems prone to 502 atm)

**Comment by xiota** [comment]
Re-added with interfere to fix build and some annoyances.
