### ISSUE TITLE
[Outdated] firefox-extension-flagfox

### ISSUE THREAD

**Issue by adi-g15** [chaotic-aur/packages#1963]
### If available, link to the latest build

[log.8august22](https://builds.garudalinux.org/repos/chaotic-aur/logs/firefox-extension-flagfox.log)

### Package name

`firefox-extension-flagfox`

### Latest build

6.1.52-1

### Latest version available

6.1.54-1

### Have you tested if the package builds in a clean chroot?

- [x] Yes

**Comment by Technetium1** [comment]
@dr460nf1r3 it broke :thinking:

**Comment by dr460nf1r3** [comment]
This was actually an issue with the cached `extension.xpi` and not a broken PKGBUILD. Fixed :)
