### ISSUE TITLE
[Request] Across

### ISSUE THREAD

**Issue by Pakrohk** [chaotic-aur/packages#1964]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/across

https://wiki.arktoria.org

### Utility this package has for you

ACross is a simple and modern GUI client for v2ray, written in Qt6 & QML. It is one of the main projects of the Arktoria community.

Focusing on users' experience, we stick to the principle of simplicity and practicality. Thus, we do not provide many redundant functions but design a few flexible ones. To keep the project pure and clean, there's no build-in core, but you can easily set the core and even customize the interface.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Fantastic

**Comment by xiota** [comment]
`across` is broken and failing to build because of missing cstdint headers in third-party source tree.  Looks troublesome to fix.  Maintainers appear to be inactive.  They did not respond to dependency request from 2022-10-01 (11 months).  Metrics show 4 downloads.  Is this a candidate for removal?
