### ISSUE TITLE
[Outdated] visual-studio-code-insiders-bin

### ISSUE THREAD

**Issue by hmnd** [chaotic-aur/packages#1966]
### If available, link to the latest build

[visual-studio-code-insiders-bin.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/visual-studio-code-insiders-bin.log)

### Package name

`visual-studio-code-insiders-bin`

### Latest build

`1662529402-1`

### Latest version available

`1664343731`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

The package on aur itself is not updated, however the aur package builds the latest possible version every time. Is there a way to automate rebuilding daily, regardless of whether the package has been updated?

**Comment by dr460nf1r3** [comment]
That's an issue I noticed myself as well. A possibility would be to set a timer bumping the package using the `chaotic bump` command, I guess. At least that's what I did in the past to have the package updated.

**Comment by dr460nf1r3** [comment]
I'm leaving this open for further events / until a good solution has been implemented.

**Comment by xiota** [comment]
Looks like this was fixed in e58a3d6155d6971cdb64fd8d5d541b7e98d13d45.  Last rebuild was today.
