### ISSUE TITLE
[Request] volantes-cursors

### ISSUE THREAD

**Issue by joe733** [chaotic-aur/packages#1967]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/volantes-cursors

### Utility this package has for you

Change cursor theme

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Build fails: [volantes-cursors.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/volantes-cursors.log)
```
build.sh: line 34: [: : integer expression expected
inkscape: error while loading shared libraries: libsoup-2.4.so.1: cannot open shared object file: No such file or directory
make: *** [Makefile:7: build] Error 123
```

**Comment by joe733** [comment]
Oh, let me try.

**Comment by Technetium1** [comment]
Make sure you test in a clean chroot.

**Comment by joe733** [comment]
> Make sure you test in a clean chroot.

I'm trying build in a fresh docker container (`archlinux:base-devel`), but I'm not able to get internet inside the container. I'm reading, looking for the solution. 

> EDIT: tested, and it fails, it's an issue with the pkgbuild.

Mm.. okay

**Comment by Technetium1** [comment]
Probably missing `libsoup` in makedepends, if so I'll fix via interfere and report to maintainer a bit later.

**Comment by joe733** [comment]
Hi, I was able to build it on docker. Yes `libsoup` is required to make. I've notified both author (https://github.com/varlesh/volantes-cursors/issues/6) and the AUR maintainer (https://aur.archlinux.org/packages/volantes-cursors#comment-883619)

**Comment by joe733** [comment]
**Update:** Fixed. It has been addressed on AUR. https://aur.archlinux.org/packages/volantes-cursors#comment-883630
