### ISSUE TITLE
[Bug]  Across : QQmlApplicationEngine failed to load component

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#1972]
### What happens?

The software cannot display its GUI environment and only opens in the background, this problem is not seen on the package inside the AUR.

### What is expected to happen?

The software is expected to open and look for V2ray Core and try to launch it.

### If possible, please attach logs

```zsh
QQmlApplicationEngine failed to load component
qrc:/Arktoria/ACross/src/views/main.qml:56:5: Type PopNotify unavailable
qrc:/Arktoria/ACross/src/views/main/PopNotify.qml:33:19: Type PopMessageBox unavailable
qrc:/Arktoria/ACross/src/views/main/PopMessageBox.qml:6:1: Type CardBox unavailable
qrc:/Arktoria/ACross/src/views/components/CardBox.qml:27:23: Type DropShadow unavailable
qrc:/qt-project.org/imports/Qt5Compat/GraphicalEffects/DropShadow.qml:6:1: Cannot load library /usr/lib/qt6/qml/Qt5Compat/GraphicalEffects/private/libqtgraphicaleffectsprivateplugin.so: (libQt6ShaderTools.so.6: cannot open shared object file: No such file or directory)
```

### More information

The problem that I felt in the packages in your repository (in long-term use) is that you should request the prerequisites from the users or, if possible, check aur or source to see what each software needs to work properly.

**Comment by Technetium1** [comment]
I added [a comment](https://aur.archlinux.org/packages/across#comment-883704) so the maintainer knows they're missing a dependency.

**Comment by Technetium1** [comment]
Bumped and rebuilt, please update and try again @ALipAkrohk

**Comment by ALipAkrohk** [comment]
The problem of running the software in the background has been completely solved. 
Thanks for the support 👍🏻

**Comment by Technetium1** [comment]
@dctxmei
