### ISSUE TITLE
[Bug] linux-next-git keeps failing to build because of validity/signature check

### ISSUE THREAD

**Issue by VexfulNiko** [chaotic-aur/packages#1973]
### What happens?

/usr/lib/modules/'linux-next-folder-here' is missing multiple files therefore booster (or any other initramfs builder) to fail, causing an unbootable linux-next img.

### What is expected to happen?

To include the files that are necessary to create a bootable img.

### More information

Not sure if it is a Linux-next upstream issue or an AUR pkg issue, or just an issue on my end (probably not, as I tried to do the same process on another system to no avail)

**Comment by Technetium1** [comment]
Report this to the AUR maintainer

**Comment by VexfulNiko** [comment]
@Technetium1 did you ever rebuild the Linux next pkg? Maybe that could be the problem.

**Comment by Technetium1** [comment]
It took about 5 hours of real world time, and about 46 mins of cpu time, but yes in #1951

**Comment by dr460nf1r3** [comment]
I noticed UFSCar currently has a blocker in place (the wrong cached checksum file, which apparently isn't easy to clear), so let's build this on `chaotic-dragon`. Once the next update of the package happens, please let us know whether the issue is still present.

**Comment by dr460nf1r3** [comment]
The package cache on UFSCar *should* be cleared by now, lets see whether automated builds succeed :)

**Comment by VexfulNiko** [comment]
`:: Running post-transaction hooks...
(1/3) Arming ConditionNeedsUpdate...
(2/3) Updating module dependencies...
depmod: ERROR: Cycle detected: nf_conntrack -> nf_nat -> nf_conntrack
depmod: ERROR: Found 2 modules in dependency cycles!
error: command failed to execute correctly
(3/3) Updating linux booster images...
2022/10/03 10:41:22 open /usr/lib/modules/6.0.0-rc7-next-20220930-1-next-git/modules.alias: no such file or directory`

Still dead sadly.

**Comment by VexfulNiko** [comment]
Suggest adding the linux-next-git (base) group as well:
https://aur.archlinux.org/pkgbase/linux-next-git

From gamezelda in the comments of the AUR pkg, it seems like an upstream issue:


"PSA: If you get an error about a circular dependency with nf_nat and nf_conntrack (then a lot of errors from mkinitcpio), this is the patch to apply: https://lore.kernel.org/netdev/633655f64ff90_233df20817@john.notmuch/T/

I guess it'll be merged upstream soon."

**Comment by Technetium1** [comment]
@VexfulNiko added in #318

**Comment by VexfulNiko** [comment]
@Technetium1 @dr460nf1r3 Upstream PKG from the Aur has been updated, should rebase it to that, also the linux-next-git is outdated (again)

**Comment by Technetium1** [comment]
Build failed, so I cleared sources. Rebuilding now.

**Comment by VexfulNiko** [comment]
Seems like it works now , safe to close this issue if you rebuild the pkg today or yesterday since that when the pkg in the AUR was last updated.

**Comment by Technetium1** [comment]
Great, I started the build from my phone before I went to sleep :smile:

@dr460nf1r3 I did still have to clear the cache, so the interfere seems to not take effect. Is this https://github.com/chaotic-aur/interfere/commit/317c99e20a899c03d9e736ffc916d34738744901 okay to do to every kernel?

**Comment by dr460nf1r3** [comment]
So basically this package builds successfully and fails due to signatures the next build still?

**Comment by VexfulNiko** [comment]
@dr460nf1r3 Yep, it builds successfully, then when the next build comes, it fails. For example, I'm using Linux-next, but it is outdated; it's at 10/05 currently, but versions 10/06 and 10/07 already came out, and in the logs (https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-next-git.log) it showed it failed because of a validity check.

**Comment by dr460nf1r3** [comment]
We could setup cache clearing as on success interfere 👀

**Comment by dr460nf1r3** [comment]
Taking a look at the commit history of our file, it might in fact be the frequency of changes concerning this file while not changing the filename: https://gitlab.com/sirlucjan/kernel-patches/-/commits/master/6.0/arch-patches-sep/0001-ZEN-Add-sysctl-and-CONFIG-to-disallow-unprivileged-C.patch :eyes: Since we cache all the things if possible, the cached (old) file would be used to build the package, resulting in a wrong checksum. I had this happen before with @ptr1337's kernels 😆 
If it is indeed the same problem, skipping checksum might be the best option here.

**Comment by VexfulNiko** [comment]
Yeah it probably is in this case.

**Comment by ptr1337** [comment]
> Taking a look at the commit history of our file, it might in fact be the frequency of changes concerning this file while not changing the filename: https://gitlab.com/sirlucjan/kernel-patches/-/commits/master/6.0/arch-patches-sep/0001-ZEN-Add-sysctl-and-CONFIG-to-disallow-unprivileged-C.patch eyes Since we cache all the things if possible, the cached (old) file would be used to build the package, resulting in a wrong checksum. I had this happen before with @ptr1337's kernels laughing If it is indeed the same problem, skipping checksum might be the best option here.

Actually, you should maybe implement clearing "patches" from the source frequently. Also this patch, at linux-next-git has not changed since a long time.
Maybe this patch was pulled time ago from another source, which has a different checksum.

Skipping the checksums is in my eyes not a good. 
At linux-next-git it is fine, but at other kernels, as you know the patches does change with every kernel version and gets fixes, other patches and then you would basically patch the old, maybe bugged  kernel patch again

**Comment by VexfulNiko** [comment]
Any ETA for this to get implemented? @Technetium1 @dr460nf1r3

**Comment by dr460nf1r3** [comment]
Well.. I'm absolutely unsure whether it works but I thought its worth a try :eyes:
https://github.com/chaotic-aur/interfere/commit/685cbf9463970eb33d1671ad8c653a65402ef862
https://github.com/chaotic-aur/interfere/commit/b62c57f71de2cafa0bab2b634ef49e5f44dc1069

**Comment by VexfulNiko** [comment]
@dr460nf1r3 Sadly it seems like it hasn't worked...
    0001-ZEN-Add-sysctl-and-CONFIG-to-disallow-unprivileged-C.patch ... FAILED
    https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-next-git.log

**Comment by VexfulNiko** [comment]
@dr460nf1r3 
https://gitlab.com/sirlucjan/kernel-patches/-/tree/master/6.0/arch-patches-sep
https://gitlab.com/sirlucjan/kernel-patches/-/tree/master/6.0/arch-patches
These are the upstream links for the patches. Any ideas to fix the issue?

**Comment by ptr1337** [comment]
> @dr460nf1r3 Sadly it seems like it hasn't worked... 0001-ZEN-Add-sysctl-and-CONFIG-to-disallow-unprivileged-C.patch ... FAILED https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-next-git.log

If you test it yourself, on your rig with:
```
git clone https://aur.archlinux.org/linux-next-git.git
cd linux-next-git
makepkg -si 
```

You wont face this issue, also if you do this in a chroot. So it is actually a issue at the builder.
You could simply also patch the PKGBUILD and simply skip the checksums

**Comment by sirlucjan** [comment]
```lucjan at archlinux ~/Download 21:27:32    
❯ export LANG=C
lucjan at archlinux ~/Download 21:27:33    
❯ git clone https://aur.archlinux.org/linux-next-git.git
Found existing git alias for "clone". You should use: "git cl"
Cloning into 'linux-next-git'...
remote: Enumerating objects: 1073, done.
remote: Counting objects: 100% (1073/1073), done.
remote: Compressing objects: 100% (743/743), done.
remote: Total 1073 (delta 565), reused 817 (delta 330), pack-reused 0
Receiving objects: 100% (1073/1073), 925.83 KiB | 2.69 MiB/s, done.
Resolving deltas: 100% (565/565), done.
lucjan at archlinux ~/Download 21:27:36    
❯ cd linux-next-git
lucjan at archlinux ~/Download/linux-next-git 21:27:37 6b782af9 master    
❯ makepkg -srd --sign
==> Making package: linux-next-git 20221005.r0.g67ae4f7434ce-1 (wto, 11 paź 2022, 21:27:46)
==> WARNING: Skipping dependency checks.
==> Retrieving sources...
  -> Updating linux-next git repo...
From git://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next
 - [deleted]                   (none)     -> next-20220708
 - [deleted]                   (none)     -> next-20220711
remote: Enumerating objects: 4543, done.
remote: Counting objects: 100% (4543/4543), done.
remote: Compressing objects: 100% (1016/1016), done.
remote: Total 5057 (delta 3752), reused 4305 (delta 3523), pack-reused 514
Receiving objects: 100% (5057/5057), 2.35 MiB | 771.00 KiB/s, done.
Resolving deltas: 100% (4010/4010), completed with 727 local objects.
 + 082fce125e57...b9f85101cad3 master        -> master  (forced update)
 + 1af0c6a154d3...565da9e84d8f pending-fixes -> pending-fixes  (forced update)
   ffb39098bf87..aa512c115a09  stable        -> stable
 * [new tag]                   next-20221010 -> next-20221010
 * [new tag]                   next-20221011 -> next-20221011
  -> Downloading 0001-ZEN-Add-sysctl-and-CONFIG-to-disallow-unprivileged-C.patch...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4434  100  4434    0     0   7870      0 --:--:-- --:--:-- --:--:--  7875
  -> Found config
==> Validating source files with sha512sums...
    linux-next ... Skipped
    0001-ZEN-Add-sysctl-and-CONFIG-to-disallow-unprivileged-C.patch ... Passed
    config ... Passed
==> Extracting sources...```

Hi. I am the maintainer of this package. I change the Arch Linux patch every two months, along with the release of a new kernel - synchronizing with the upstream. As you can see, I can not reproduce this error you are facing. The only thing I can think of is to suggest I have a regular cleaning of the working directory.

**Comment by dr460nf1r3** [comment]
Thanks for chiming in @sirlucjan :) when trying it for the first time locally, this won't happen.

I guess the only solution will be putting it to build on another builder and adding a timer that regularly deletes the source cache (ufscar is special due to being a hpc). I'll take care of that at the weekend.

**Comment by VexfulNiko** [comment]
@dr460nf1r3 That's great still stuck in linux next oct 5 over here lmao

**Comment by Technetium1** [comment]
@VexfulNiko I'll manually build it now, it'll be a while.

**Comment by VexfulNiko** [comment]
@Technetium1 seems like it worked im on October 14th now : )

**Comment by dr460nf1r3** [comment]
Revisiting this - it seems to no longer fail :eyes: Latest build successful build happened yesterday.

**Comment by VexfulNiko** [comment]
I'm assuming it also grabs the newest patches as well, to maintain the same kernel config upstream (core) linux kernel has.
