### ISSUE TITLE
[Request] raider-file-shredder

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1980]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/raider-file-shredder

### Utility this package has for you

Securely delete your files

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Build fails: [raider-file-shredder.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/raider-file-shredder.log)

**Comment by Technetium1** [comment]
[Updated 10 days ago](https://aur.archlinux.org/cgit/aur.git/commit/?h=raider-file-shredder&id=59bbdc7f4ac899b346977ad064827bc6516d8873).

**Comment by xiota** [comment]
Available as `extra/raider`
