### ISSUE TITLE
[Request] tokodon-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#1986]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/tokodon-git

### Utility this package has for you

A native Mastodon client

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because `extra/tokodon` is available.  Metrics 16.

@alexjp Would this be worth considering for kde-git repo?

**Comment by alexjp** [comment]
@xiota I haven't checked the status of the package (if it is working/updated, seems last update was in april) but, yeah, it could be.

Anyway feel free to remove it, since if it does go into kde-git, it will be changed.
