### ISSUE TITLE
[Request] evdi-git, displaylink, micro-git

### ISSUE THREAD

**Issue by VexfulNiko** [chaotic-aur/packages#1988]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/evdi-git
https://aur.archlinux.org/packages/displaylink
https://aur.archlinux.org/packages/micro-git

### Utility this package has for you

Displaylink support + bleeding-edge micro (a terminal editor)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Metrics:

* evdi-git # 87
* displaylink # 75
* micro-git # 14

**Comment by Technetium1** [comment]
Much lower than expected for `micro-git`... @nyabinary do you still have a desire for it?

**Comment by nyabinary** [comment]
> Much lower than expected for `micro-git`... @nyabinary do you still have a desire for it?

Nah, I use NixOS anyways now :P

**Comment by xiota** [comment]
There are currently 88 commits difference between stable and git packages.  After recent rebuild, metrics went to 17.  So looks like at least 3 users.

**Comment by xiota** [comment]
Switched `evdi-git` to custom packages, `evdi-dkms` and `evdi-dkms-git`.  Current metrics:

* evdi-git # 85
* displaylink # 64
* micro-git # 33
