### ISSUE TITLE
[Bug] pipewire*-git package(s) get corrupted after a few updates

### ISSUE THREAD

**Issue by Nyabinary** [chaotic-aur/packages#1989]
### What happens?

Every once in a while, the pipewire*-git packages return an invalid or corrupted package (PGP signature), no idea why happens in all systems I run to have this problem it usually isn't a big problem since I can delete it, and it works again but it still an annoyance. 

### What is expected to happen?

Packages to not be corrupted.

**Comment by Technetium1** [comment]
Is your keyring up to date?

**Comment by VexfulNiko** [comment]
Yes it is

**Comment by PedroHLC** [comment]
What is the mirror you're using? (check in `/etc/pacman.d/chaotic-mirrorlist`)
If the response is "geo-mirror", what does this page `https://status.chaotic.cx/geo` shows you?

**Comment by VexfulNiko** [comment]
It shows me the Florida mirror

**Comment by VexfulNiko** [comment]
us-fl-mirror 1665062428 specifically

**Comment by PedroHLC** [comment]
> us-fl-mirror 1665062428 specifically

Thanks, the mirror owner seems to be aware of the issue.

**Comment by alissonlauffer** [comment]
Hello, I am the maintainer of us-fl and br-2 mirrors. This is most likely being caused when the mirror is still syncing files but has already synced the database, and this is a rare case, but happens sometimes (apparently) because of sync concurrency.

I made some internal changes to the mirror to avoid such issues. Please comment on this thread if the issue reoccurs.

**Comment by PedroHLC** [comment]
** re-open the issue in case it re-occurs.

**Comment by VexfulNiko** [comment]
Will do!

**Comment by VexfulNiko** [comment]
![1665191094](https://user-images.githubusercontent.com/97130632/194679881-a5750e12-bbff-4594-85a3-2c7a8e3a0afe.png)
Got the same problem again sadly.

**Comment by alissonlauffer** [comment]
Alright, I will temporarily disable Cloudflare proxy in the mirror and you tell me if it happens again.

**Comment by VexfulNiko** [comment]
Will do

**Comment by PedroHLC** [comment]
@VexfulNiko any update?

**Comment by VexfulNiko** [comment]
@PedroHLC still corrupts in some packages kitty and pipewire are the usually ones that are corrupted. Also for some packages versioning seems to be wrong requiring using pacman -Syyuu to fix

**Comment by VexfulNiko** [comment]
Yeah, it seems like a mirror problem, @alissonlauffer , happened to me again, also happens with wayland-git.

**Comment by JustTNE** [comment]
Please post your full /etc/pacman.conf, /etc/pacman.d/chaotic-mirrorlist, full terminal log of when this happens along with the output of `curl https://status.chaotic.cx/geo`.

**Comment by xiota** [comment]
Closing because it's been almost a year with no response from OP.
