### ISSUE TITLE
[Request] mold-git

### ISSUE THREAD

**Issue by Nyabinary** [chaotic-aur/packages#1990]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/mold-git
~~systemd-git~~

### Utility this package has for you

Bleeding-edge packages for mold (a modern linker) and systemd.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

systemd-libs-git is a dependency of systemd-git so probably a good idea to build that first out of the two if you end up adding this.

**Comment by Technetium1** [comment]
We build the dep at the same time we build the rest of the base.

**Comment by yurikoles** [comment]
Test often fail in a clean chroot, so `--nocheck` is needed.

**Comment by VexfulNiko** [comment]
@Technetium1

**Comment by Technetium1** [comment]
@yurikoles if tests fail on a `-git` package, isn't that a good sign that you'd be getting a broken version? Can you link me anything that confirms it's okay to skip tests? It still tries to rebuild on the hour, and will only deploy a successful package. This isn't the kind of package you really want to have break on you…

**Comment by VexfulNiko** [comment]
Yeah I feel like no check is need I have systemd git in my system and it's just got updated today to the newest commit version and ran fine with no breakage.

**Comment by dr460nf1r3** [comment]
Added the skip to both `systemd-git` and `lib32-systemd-git` - I guess its quite clear breakage can occur when using these packages.

**Comment by xiota** [comment]
`systemd-git` not building because of missing dependencies.  Maintainer was already notified ~2 months ago.  Flagged to remind.  If not fixed "soon", will drop.  (Metrics currently show 10.)

**Comment by yurikoles** [comment]
I'm sorry for the delay, fixed by https://github.com/yurikoles-aur/systemd-git/commit/22d76052f49305f62b836ae28b31fd3a2fc7e0df

**Comment by xiota** [comment]
If anyone wants `systemd-git` added back, please open a new package request.

**Comment by xiota** [comment]
Planning to drop `mold-git` because `mold` hasn't been useful after Arch enabled LTO by default.  As far as I can tell, mold uses `ld` or `lld` for LTO.   Metrics 37.
