### ISSUE TITLE
[Request] oblige-obsidian-stable-git

### ISSUE THREAD

**Issue by yum13241** [chaotic-aur/packages#1992]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/oblige-obsidian-stable-git

### Utility this package has for you

Random DOOM maps. Why not?

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Github: https://github.com/dashodanger/Obsidian

**Comment by Technetium1** [comment]
Build fails, no idea why for sure: [oblige-obsidian-stable-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/oblige-obsidian-stable-git.log)
