### ISSUE TITLE
[Outdated] linux-mainline

### ISSUE THREAD

**Issue by completelygenericusername** [chaotic-aur/packages#1993]
### If available, link to the latest build

[linux-mainline.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-mainline.log)

### Package name

linux-mainline

### Latest build

6.0rc7-1

### Latest version available

6.0-1

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

linux 6.0 was released 2 days ago, shown by the [release on github](https://github.com/torvalds/linux/releases/tag/v6.0)

**Comment by completelygenericusername** [comment]
package has updated to version 6.0-1 in the repository

**Comment by Technetium1** [comment]
Rebuilt, thank you!
