### ISSUE TITLE
[Outdated] Openrazer

### ISSUE THREAD

**Issue by dreigon2474** [chaotic-aur/packages#1994]
### If available, link to the latest build

[openrazer.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/openrazer.log)

### Package name

`openrazer`

### Latest build

`3.4.0-1` 

### Latest version available

`3.3.0-1`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by Technetium1** [comment]
Looks like `openrazer` either merged or deleted. We'll have to replace it.

**Comment by Technetium1** [comment]
I'm thinking [openrazer-git](https://aur.archlinux.org/pkgbase/openrazer-git)
