### ISSUE TITLE
[Outdated] linux-xanmod-edge

### ISSUE THREAD

**Issue by Inetol** [chaotic-aur/packages#1995]
### If available, link to the latest build

[linux-xanmod-edge](https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-xanmod-edge.log)

### Package name

`linux-xanmod-edge`, `linux-xanmod-edge-headers`

### Latest build

`5.19.12-1`

### Latest version available

`6.0.0-1`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

We are eager to check out this new version as it includes significant changes 🙌🏽

**Comment by completelygenericusername** [comment]
seems like it was updated, you should close your issue now
![image](https://user-images.githubusercontent.com/109995907/194108000-6d070233-8f1c-486a-a060-9cf80b0da804.png)

**Comment by Technetium1** [comment]
Rebuilt, thank you! I fell asleep while it was compiling :upside_down_face:
