### ISSUE TITLE
[Outdated] deezer

### ISSUE THREAD

**Issue by jopejoe1** [chaotic-aur/packages#1997]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/deezer.log

### Package name

deezer

### Latest build

5.30.310-1

### Latest version available

5.30.340-1

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

Missing dependency electron13

**Comment by dr460nf1r3** [comment]
We should think about whether we want to build those, since they are a security risk just by being outdated :eyes: I just had a look, we have one package using electron8, even worse 😦 I'd like to drop it for this reason actually. What do you think @Technetium1 ?

**Comment by Technetium1** [comment]
@dr460nf1r3 my opinion is to drop both then. Pretty sure deezer is in setup assistant, so that's something you'd have to remove. To mark relation: `sendanywhere` from #1367 requires `electron8`

**Comment by dr460nf1r3** [comment]
Let's do it then! I'm taking care of the setup assistant part :)

**Comment by dr460nf1r3** [comment]
It turned out to be not on the setup assistant lists. :D
