### ISSUE TITLE
[Outdated] firefox-wayland-hg

### ISSUE THREAD

**Issue by VexfulNiko** [chaotic-aur/packages#1999]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/firefox-nightly.log
https://builds.garudalinux.org/repos/chaotic-aur/logs/firefox-wayland-hg.log

### Package name

firefox-nightly & firefox-wayland-hg

### Latest build

10-01 for nightly and an commit ver for HG

### Latest version available

master

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by Technetium1** [comment]
`firefox-nightly` seems to have compiled successfully.

**Comment by VexfulNiko** [comment]
They both did, should rebuild pkg just in case tho, just to be on the safe side, if you didn't already.

**Comment by Technetium1** [comment]
Rebuilding now.

**Comment by dr460nf1r3** [comment]
`firefox-wayland-hg` fails with `Exception: No jar log data for omni.ja` on `package()` :eyes: while `firefox-nightly` finishes successfully.

**Comment by dr460nf1r3** [comment]
An update on this: the build no longer fails at the build phase rather than during moving debug symbols. 
```
{"upload": {"id": 407288, "size": 133537193, "filename": "firefox-108.0a1.en-US.linux-x86_64.crashreporter-symbols.zip", "bucket": "org.mozilla.crash-stats.symbols-public", "region": "us-west-2", "download_url": null, "try_symbols": true, "redirect_urls": [], "completed_at": null, "created_at": "2022-10-29T13:35:40.405Z", "user": "matias@ufscar.br", "skipped_keys": []}}
mv: cannot move './pkgwork/firefox-108.0a1.en-US.linux-x86_64.crashreporter-symbols.zip' to './pkgwork/firefox-108.0a1.en-US.linux-x86_64.crashreporter-symbols.zip.uploaded': Permission denied
```
Does this need any adaption @thotypous ?

**Comment by VexfulNiko** [comment]
Also I feel like firefox-wayland-hg should target Nightly instead of release branding, since it's more aligned with nightly than the release channel.

**Comment by dr460nf1r3** [comment]
@thotypous thoughts?
