### ISSUE TITLE
[Request] Rebuild paru-git with rust nightly & pacman-git

### ISSUE THREAD

**Issue by VexfulNiko** [chaotic-aur/packages#2004]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/paru-git

### Utility this package has for you

Bleeding edge paru + additional features with rust nightly and pacman-git

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

The PKGBUILD should also be changed to adhere to [Rust packaging guidelines](https://wiki.archlinux.org/title/Rust_package_guidelines), as pointed out by a [commenter in the AUR pkgbuild](https://aur.archlinux.org/packages/paru-git#comment-878253)

**Comment by Technetium1** [comment]
Rebuild sure, but it's not really our responsibility to maintain the pkgbuild :eyes: 
It was already rebuilt, but I did it again just in case.

**Comment by VexfulNiko** [comment]
@Technetium1 I created a PKGBUILD (+ added generate as a feature, it requires clang as a make dependency, though.)
[PKGBUILD.txt](https://github.com/chaotic-aur/packages/files/9738457/PKGBUILD.txt)

**Comment by Technetium1** [comment]
@VexfulNiko submit the diff to the AUR in comments!

**Comment by VexfulNiko** [comment]
@Technetium1 Most likely won't accept the diffs since their pretty specific (I mean the author likely wont incorporate the change)

**Comment by Technetium1** [comment]
@VexfulNiko Actually I revise that, post the diff to the issues here. The maintainer of the package is the same Morganamilo: https://github.com/Morganamilo/paru

**Comment by VexfulNiko** [comment]
`--- PKGBUILD	2022-10-08 00:35:20.517253709 -0400
+++ /home/vextium/Downloads/paru/PKGBUILD.txt	2022-10-08 01:22:18.823692696 -0400
@@ -1,23 +1,36 @@
-# Maintainer: Morgan <morganamilo@archlinux.org>
-pkgname=paru
-pkgver=1.11.1
+# Maintainer: Vextium <Vextium#0001>
+# Contributor: Morgan <morganamilo@archlinux.org>
+
+pkgname=paru-git
+_pkgname=paru
+pkgver=1.11.1.r64.g4a34ae9
 pkgrel=1
 pkgdesc='Feature packed AUR helper'
 url='https://github.com/morganamilo/paru'
-source=("$pkgname-$pkgver.tar.gz::https://github.com/Morganamilo/paru/archive/v$pkgver.tar.gz")
+source=("git+https://github.com/morganamilo/paru")
 backup=("etc/paru.conf")
 arch=('i686' 'pentium4' 'x86_64' 'arm' 'armv7h' 'armv6h' 'aarch64')
 license=('GPL3')
-makedepends=('cargo')
-depends=('git' 'pacman')
+makedepends=('cargo-nightly')
+depends=('glibc' 'git' 'pacman-git' 'clang')
 optdepends=('asp: downloading repo pkgbuilds' 'bat: colored pkgbuild printing' 'devtools: build in chroot')
-sha256sums=('42cefa8cdf48e3aec3f9922235f1e1126a9fe3262f1644494e1be51980e520d8')
+conflicts=("${_pkgname}")
+provides=("${_pkgname}")
+sha256sums=(SKIP)
+
+# Rustup install is the same as rustup update if nightly is installed
+prepare() {
+    cd "${srcdir}/${_pkgname}"
+    rustup install nightly
+    cargo +nightly update -Z sparse-registry
+    cargo +nightly fetch --locked -Z sparse-registry --target "$CARCH-unknown-linux-gnu"
+}
 
 build () {
-  cd "$srcdir/$pkgname-$pkgver"
+  cd "${srcdir}/${_pkgname}"
 
   if pacman -T pacman-git > /dev/null; then
-    _features+="git,"
+    _features+="git,generate,"
   fi
 
   if [[ $(rustc -V) == *"nightly"* ]]; then
@@ -28,23 +41,28 @@
     export CARGO_PROFILE_RELEASE_LTO=off
   fi
 
-  cargo build --locked --features "${_features:-}" --release --target-dir target
-  ./scripts/mkmo locale/
+  PARU_VERSION=${pkgver} cargo +nightly build --frozen --features "${_features:-}" --release --target-dir target -Z sparse-registry
+./scripts/mkmo locale/
 }
 
 package() {
-  cd "$srcdir/$pkgname-$pkgver"
+  cd "${srcdir}/${_pkgname}"
 
-  install -Dm755 target/release/paru "${pkgdir}/usr/bin/paru"
-  install -Dm644 paru.conf "${pkgdir}/etc/paru.conf"
+  install -Dm755 target/release/${_pkgname} "${pkgdir}/usr/bin/${_pkgname}"
+  install -Dm644 ${_pkgname}.conf "${pkgdir}/etc/${_pkgname}.conf"
 
-  install -Dm644 man/paru.8 "$pkgdir/usr/share/man/man8/paru.8"
-  install -Dm644 man/paru.conf.5 "$pkgdir/usr/share/man/man5/paru.conf.5"
+  install -Dm644 man/${_pkgname}.8 "${pkgdir}/usr/share/man/man8/${_pkgname}.8"
+  install -Dm644 man/${_pkgname}.conf.5 "${pkgdir}/usr/share/man/man5/${_pkgname}.conf.5"
 
-  install -Dm644 completions/bash "${pkgdir}/usr/share/bash-completion/completions/paru.bash"
-  install -Dm644 completions/fish "${pkgdir}/usr/share/fish/vendor_completions.d/paru.fish"
-  install -Dm644 completions/zsh "${pkgdir}/usr/share/zsh/site-functions/_paru"
+  install -Dm644 completions/bash "${pkgdir}/usr/share/bash-completion/completions/${_pkgname}.bash"
+  install -Dm644 completions/fish "${pkgdir}/usr/share/fish/vendor_completions.d/${_pkgname}.fish"
+  install -Dm644 completions/zsh "${pkgdir}/usr/share/zsh/site-functions/_${_pkgname}"
+
+  install -d "${pkgdir}/usr/share/"
+  cp -r locale "${pkgdir}/usr/share/"
+}
 
-  install -d "$pkgdir/usr/share/"
-  cp -r locale "$pkgdir/usr/share/"
+pkgver() {
+  cd "${srcdir}/${_pkgname}"
+  git describe --long --tags | sed 's/^v//;s/\([^-]*-g\)/r\1/;s/-/./g'
 }`

**Comment by dr460nf1r3** [comment]
Preferably we create a repo for this PKGBUILD so things don't break if the AUR PKGBUILD gets updated and @VexfulNiko can PR changes.

**Comment by VexfulNiko** [comment]
Yeah seems like a good solution

**Comment by Technetium1** [comment]
@VexfulNiko build fails: [paru-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/paru-git.log).
As soon as it works I'll change path in: https://github.com/chaotic-aur/packages/blob/main/dragon-cluster/hourly.txt#L56

**Comment by VexfulNiko** [comment]
@Technetium1 hmm what's the issue because just from a quick glance it seems like it shows that a package is already built (therefore needing -f)
==> Starting pkgver()...
==> Updated version: paru-git 1.11.1.r64.g4a34ae9-1
==> ERROR: A package has already been built. (use -f to overwrite)
(Unless this is the normal pkgbuild ver)

**Comment by dr460nf1r3** [comment]
Ah, it's another one. Need to force install pacman-git via interfere as it tries to install this, resulting in a package conflict.

**Comment by VexfulNiko** [comment]
@Technetium1 @dr460nf1r3 https://builds.garudalinux.org/repos/chaotic-aur/logs/paru-git.log Something weird going on with the build.

**Comment by dr460nf1r3** [comment]
Well that's to be expected given the PKGBUILD wants `pacman-git` while `pacman` is already installed 👀

**Comment by dr460nf1r3** [comment]
Sorry for the delay! Just had this fixed. https://github.com/chaotic-aur/interfere/commit/2d1dee40ba3f66018a3b896ad64fd2cc41274b9a

**Comment by xiota** [comment]
`paru-git` has been failing to link with `pacman-git` for the last month (last successful build 2025-10-08).  Local build succeeds with plain `pacman`.  Not sure how much longer to wait before dropping or revising (switch to `pacman`).

Metrics are interesting.

* paru # 4247
* paru-git # 855
* pacman-git # 20
