### ISSUE TITLE
[Request] networkmanager-git

### ISSUE THREAD

**Issue by nyabinary** [chaotic-aur/packages#2005]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/networkmanager-git

~~pacman-auto-update~~ # No longer in AUR
~~electron-nightly-npm~~ # No longer in AUR

Rebuild: https://aur.archlinux.org/packages/webcord-git
Big PKGBUILD update that address security concerns is out ^

### Utility this package has for you

Bleeding edge git updates and convience.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
`==> Finished making: webcord-git 3.8.6.r712.c1ba49c-1 (Sat 08 Oct 2022 08:15:25 AM CEST)`

**Comment by Technetium1** [comment]
@SolarAquarion [`networkmanager-git` is flagged](https://aur.archlinux.org/pkgbase/networkmanager-git/flag-comment)

**Comment by xiota** [comment]
`pacman-auto-update` was dropped from AUR in Apr 2023. (PRQ#40650)

Dropped `electron-nightly-npm` because it appears to be a "bogus package".  There is a deletion request pending.  (PRQ#44376)

**Comment by xiota** [comment]
Closing because I think this is part of the kde-git repo.  @alexjp

**Comment by alexjp** [comment]
> Closing because I think this is part of the kde-git repo. @alexjp

Not quite, what is a package of kde-git (which is closed for porting for now) is networkmanager-qt.
