### ISSUE TITLE
[Outdated] Linux-Xanmod 

### ISSUE THREAD

**Issue by EvoXCX** [chaotic-aur/packages#2006]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-xanmod.log

### Package name

linux-xanmod

### Latest build

5.19.12

### Latest version available

5.19.14

### Have you tested if the package builds in a clean chroot?

- [X] Yes

**Comment by dr460nf1r3** [comment]
This doesn't even seem to be present in the package list, interesting. Adding it and rebuilding, 5.19.12 hasn't been a nice version with all those Intel display issues!
