### ISSUE TITLE
[Request] cpu-x

### ISSUE THREAD

**Issue by epic0421** [chaotic-aur/packages#2011]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/cpu-x

### Utility this package has for you

This package is helpful for viewing system information such as CPU, GPU & Memory

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

The git version of this application (cpu-x-git) is already available in the chaotic-aur but the main version is not which I would find more useful since git versions tend to be more unstable.

**Comment by VexfulNiko** [comment]
Cpu-x git version is in the repo currently but needs to be rebuilt because it's outdated.

**Comment by VexfulNiko** [comment]
@Technetium1 Btw cpu-x doesn't need to be in hourly IMO. Could be daily or bidaily for the binary/stable option for the git ver it could be daily.

**Comment by Technetium1** [comment]
It's a light package, no worries. If it doesn't actually have an update, it's not really much of any load, which also means the very heavy afternoon/nightly routines finish a bit faster.

**Comment by xiota** [comment]
Dropping because moved to `extra`.  Metrics 1035.
