### ISSUE TITLE
[Request] grub-themes-git

### ISSUE THREAD

**Issue by joe733** [chaotic-aur/packages#2013]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages?O=0&SeB=nd&K=grub-theme-tela&outdated=&SB=p&SO=d&PP=50&submit=Go

**grub-theme-tela-color**

1. https://aur.archlinux.org/packages/grub-theme-tela-color-1080p-git
2. https://aur.archlinux.org/packages/grub-theme-tela-color-2k-git
3. https://aur.archlinux.org/packages/grub-theme-tela-color-4k-git
4. https://aur.archlinux.org/packages/grub-theme-tela-color-ultrawide-git
5. https://aur.archlinux.org/packages/grub-theme-tela-color-ultrawide2k-git

**grub-theme-tela-white**

1. https://aur.archlinux.org/packages/grub-theme-tela-white-1080p-git
2. https://aur.archlinux.org/packages/grub-theme-tela-white-2k-git
3. https://aur.archlinux.org/packages/grub-theme-tela-white-4k-git
4. https://aur.archlinux.org/packages/grub-theme-tela-white-ultrawide-git
5. https://aur.archlinux.org/packages/grub-theme-tela-white-ultrawide2k-git

**grub-theme-tela-whitesur**

1. https://aur.archlinux.org/packages/grub-theme-tela-whitesur-1080p-git
2. https://aur.archlinux.org/packages/grub-theme-tela-whitesur-2k-git
3. https://aur.archlinux.org/packages/grub-theme-tela-whitesur-4k-git
4. https://aur.archlinux.org/packages/grub-theme-tela-whitesur-ultrawide-git
5. https://aur.archlinux.org/packages/grub-theme-tela-whitesur-ultrawide2k-git

### Utility this package has for you

Theme for grub

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
All contained within the pkgbase [grub-themes-git](https://aur.archlinux.org/pkgbase/grub-themes-git)
