### ISSUE TITLE
[Outdated] godot-git 

### ISSUE THREAD

**Issue by VexfulNiko** [chaotic-aur/packages#2015]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/godot-git.log

### Package name

godot-git

### Latest build

4.0.r47426.67961d875d51-1

### Latest version available

master

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

PKGBuild got updated: https://aur.archlinux.org/packages/godot-git (+ fixed versioning in the update)

**Comment by Technetium1** [comment]
Build is still failing the same way :confused:

**Comment by VexfulNiko** [comment]
@Technetium1 what's the error?

**Comment by Technetium1** [comment]
@VexfulNiko [godot-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/godot-git.log)
```
==> Starting build()...
scons: Reading SConscript files ...

scons: *** Invalid value for option target: release_debug.  Valid values are: ('editor', 'template_release', 'template_debug')
File "/home/main-builder/pkgwork/src/godot/SConstruct", line 249, in <module>
==> ERROR: A failure occurred in build().
```

**Comment by VexfulNiko** [comment]
@Technetium1 could this be fixed with a interference? It seems to be a simple value change.

**Comment by VexfulNiko** [comment]
@Technetium1 https://github.com/godotengine/godot/pull/66242 this is the breaking commit/pr. It simplifies the options.

**Comment by dr460nf1r3** [comment]
We could technically `sed` the PKGBUILD, however it would be preferable to have it fixed on the AUR side as everyone benefits by this. So yeah, waiting for upstream fix it is :yum:

**Comment by VexfulNiko** [comment]
@dr460nf1r3 I created a pkgbuild that contains a fix

**Comment by VexfulNiko** [comment]
Godot updates a lot, so I think it should be put to build and compile hourly.

**Comment by VexfulNiko** [comment]
@Technetium1 is there any changes I need to make to the pkg? Or is it good to go?

**Comment by VexfulNiko** [comment]
@dr460nf1r3 Maybe this can be a separate repo as well, so I can fix it in any updates upstream that requires changing the build process.

**Comment by dr460nf1r3** [comment]
Well, lets see how it goes. Feel free to submit a PR containing the PKGBUILD here: https://github.com/chaotic-aur/pkgbuild-godot-git

**Comment by VexfulNiko** [comment]
@dr460nf1r3 I added the PKGBUILD(s). Thank you :)
