### ISSUE TITLE
gcc10, gcc11, etc

### ISSUE THREAD

**Issue by PistachioGuy** [chaotic-aur/packages#2016]
### Link to the package(s) in the AUR

~~gcc9~~
https://aur.archlinux.org/pkgbase/gcc10
https://aur.archlinux.org/pkgbase/gcc11

### Utility this package has for you

It's useful to have multiple versions of gcc for apps that depend on older versions.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
For both
```
real    104m54.883s
user    795m46.277s
sys     177m31.470s
```

**Comment by PistachioGuy** [comment]
Thank you so much!

**Comment by xiota** [comment]
@Technetium1 @dr460nf1r3 Based on declared makedepends, no packages currently in chaotic-aur requires `gcc9` to build.  Okay to drop?

**Comment by Technetium1** [comment]
@xiota `gcc9` can be removed, but not yet `gcc10` [for a while]: https://gcc.gnu.org/develop.html#timeline

**Comment by xiota** [comment]
What about `gcc11`?

**Comment by Technetium1** [comment]
@xiota `gcc11` is still active as well, and is a dep for many, we should keep it too.

**Comment by xiota** [comment]
Dropping `gcc10` and `gcc11`.  No package in chaotic-aur is using them to build.  `gcc11` is also not well maintained.
