### ISSUE TITLE
[Remove] imagemagick-full-git

### ISSUE THREAD

**Issue by jopejoe1** [chaotic-aur/packages#2023]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/imagemagick-full-git

### Utility this package has for you

Imagemagick with all features enabled git version

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
@jopejoe1 Please describe extra functionality `imagemagick-full-git` provides over `imagemagick`.  Thank you.
