### ISSUE TITLE
[Outdated/Other] PSA for GNU packages - GNU is moving from sourceware.org to kernel.org

### ISSUE THREAD

**Issue by nyabinary** [chaotic-aur/packages#2024]
### If available, link to the latest build

Source:
https://www.phoronix.com/news/GNU-Toolchain-Infrastructure
https://sourceware.org/pipermail/overseers/2022q3/018896.html

### Package name

misc

### Latest build

misc

### Latest version available

misc

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

Also btw glibc is hosted on chaotic-aur for some reason, it should be removed as well as glibc-eac since the EAC patch is now included in the core repo glibc.

**Comment by dr460nf1r3** [comment]
Removed all `glibc` variants, the regular ones were in fact not meant to be included :eyes:
