### ISSUE TITLE
[Outdated] webstorm

### ISSUE THREAD

**Issue by jopejoe1** [chaotic-aur/packages#2025]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/webstorm.log

### Package name

webstorm

### Latest build

2022.2.2b222.4167.31-1

### Latest version available

2022.2.3b222.4345.14-1

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by Technetium1** [comment]
Rebuilt!
