### ISSUE TITLE
[Remove] dataspell, goland, phpstorm, rubymine

### ISSUE THREAD

**Issue by jopejoe1** [chaotic-aur/packages#2026]
### Packages

https://aur.archlinux.org/packages/dataspell
https://aur.archlinux.org/packages/phpstorm
https://aur.archlinux.org/packages/goland
https://aur.archlinux.org/packages/rubymine

### Purpose

Having similar IDE for different languages.

### License

Proprietary

**Comment by Technetium1** [comment]
- [ ] webstorm-eap
- [ ] rubymine-eap
- [ ] rubymine
- [ ] rider-eap
- [ ] phpstorm
- [ ] goland-eap
- [ ] goland
- [ ] dataspell-eap
- [ ] dataspell
- [ ] datagrip-eap

---

```
# Issue 2026
webstorm-eap
rubymine-eap
rubymine
rider-eap
phpstorm
goland-eap
goland
dataspell-eap
dataspell
datagrip-eap
```
Add webstorm-eap rubymine-eap rubymine rider-eap phpstorm goland-eap goland dataspell-eap dataspell datagrip-eap

**Comment by dr460nf1r3** [comment]
Hey! We are currently trying to reduze repo size since we are at 92GB right now, which causes mirrors to have issues. With this in mind I would like to drop one of the 2 versions of rubymine and dataspell as they are quite big. Which ones would you like to keep?

**Comment by jopejoe1** [comment]
Remove the eap versions i think the regular versions are more important
