### ISSUE TITLE
[Request/Outdated/Fix] glibc-git & gcc-git

### ISSUE THREAD

**Issue by Nyabinary** [chaotic-aur/packages#2027]
### Link to the package(s) in the AUR

https://aur.archlinux.org/pkgbase/glibc-git
https://aur.archlinux.org/pkgbase/gcc-git#comment-883479

### Utility this package has for you

Bleeding edge glibc and gcc

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

According to https://aur.archlinux.org/packages/gcc-git#comment-883479
gcc had a breaking change that needs either A. glibc patched or B. glibc-git (since it is fixed upstream). I updated the glibc-git package, so it should compile again. Once that is done, you need to do an interference in the gcc-git package so it uses glibc-git instead of the default gcc.

**Comment by Technetium1** [comment]
`gcc-git` first added in #1672.

**Comment by Technetium1** [comment]
Build failed: [glibc-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/glibc-git.log)
Log will take a while to load, it's 68 MB.

**Comment by VexfulNiko** [comment]
@Technetium1 try now

**Comment by Technetium1** [comment]
@VexfulNiko it failed again, but in what looks to be a slightly different way.

**Comment by xiota** [comment]
Dropped `glibc-git` and `gcc-git` because they've been broken for a long time with no fix in site.  They can be re-added someday when they're working.
