### ISSUE TITLE
[Request] libnvidia-container libnvidia-container-tools

### ISSUE THREAD

**Issue by crestfalln** [chaotic-aur/packages#2028]
### Link to the package(s) in the AUR

[libnvidia-container](https://aur.archlinux.org/pkgbase/libnvidia-container)

### Utility this package has for you

Used to enable nvidia GPU capabilities in docker. An example usecase would be self hosted containerized media servers(like jellyfin) that benefit from hardware assisted transcode.  

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Title changed to match pkgbase

**Comment by crestfalln** [comment]
@Technetium1 libnvidia-container does not provide the runtime and the nvidia-ctk binary which is required for the mentioned use case. [This package](https://aur.archlinux.org/packages/nvidia-container-toolkit) is required.

**Comment by Technetium1** [comment]
[libnvidia-container-tools.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/libnvidia-container-tools.log)

**Comment by dr460nf1r3** [comment]
Those were building successfully already:
```
==> ERROR: The package group has already been built. (use -f to overwrite)
Container pkg3d933bac96d failed with error code 13.
```
Added the toolkit one as well.
