### ISSUE TITLE
[Request] Delete astronciaiptv

### ISSUE THREAD

**Issue by lineuper2029** [chaotic-aur/packages#2030]
### Link to the package(s) in the AUR

[AUR (deleted)](https://aur.archlinux.org/packages/astronciaiptv/)

### More information

astronciaiptv is deleted from AUR and its repo [GitLab (deleted)](https://gitlab.com/astroncia/iptv)  
its development stopped  
maybe we should delete it too?  
It's doesn't build anyway (try it in clean chroot for example) :)  
  
Please set the label to ``request:remove-pkg``.

**Comment by dr460nf1r3** [comment]
I agree, since updates won't be happening anyways.
