### ISSUE TITLE
[Outdated] grapejuice

### ISSUE THREAD

**Issue by theblobscp** [chaotic-aur/packages#2032]
### If available, link to the latest build

[Grapejuice log](https://builds.garudalinux.org/repos/chaotic-aur/logs/grapejuice.log)

### Package name

grapejuice

### Latest build

5.5.7-1

### Latest version available

6.0.0-1

### Have you tested if the package builds in a clean chroot?

- [X] Yes

**Comment by Technetium1** [comment]
`Finished making: grapejuice 6.0.0-1 (Sun 16 Oct 2022 03:51:20 PM -03)`

**Comment by theblobscp** [comment]
Sorry for the late response, thank you.
