### ISSUE TITLE
[Request] blender-wayland-git

### ISSUE THREAD

**Issue by TheSunCat** [chaotic-aur/packages#2033]
### Link to the package(s) in the AUR

[blender-wayland-git](https://aur.archlinux.org/packages/blender-wayland-git)

### Utility this package has for you

This package allows usage of Blender in Wayland, which is disabled in the default build.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
This will be deleted soon, so this is declined. Please see https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/message/A6HJYMJNRV33I7GDAJ73KZMYQUV5XSCZ/

**Comment by TheSunCat** [comment]
That's great news! Thanks for the heads-up.
