### ISSUE TITLE
[Request] mutter-dynamic-buffering

### ISSUE THREAD

**Issue by FireMasterK** [chaotic-aur/packages#2034]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/mutter-dynamic-buffering

### Utility this package has for you

Gnome's mutter with https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1441 merged in.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because the MR was merged and AUR package deleted.  Metrics 480.
