### ISSUE TITLE
[Request] prismlauncher prismlauncher-qt5 prismlauncher-qt5-git

### ISSUE THREAD

**Issue by ConnorJC3** [chaotic-aur/packages#2037]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/prismlauncher
https://aur.archlinux.org/packages/prismlauncher-qt5
https://aur.archlinux.org/packages/prismlauncher-qt5-git

### Utility this package has for you

Minecraft launcher (fork of PolyMC, which is a fork of MultiMC) with significantly upgraded support over the Mojang-provided launcher for modding, better profile management, etc

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

This launcher is a fork of PolyMC, which has been previously requested and accepted into chaotic-aur (https://github.com/chaotic-aur/packages/issues/1205, https://github.com/chaotic-aur/packages/issues/1497).

Recently, the head dev with ownership of the PolyMC website was hacked and/or exposed themselves as a bigot (publicly available details are unclear), kicked most (all?) of the other maintainers, and the other maintainers forked the project to create PrismLauncher. Development on PolyMC has effectively halted and I expect PrismLauncher will be the de-facto replacement, and already has traction on the AUR.

**Comment by DioEgizio** [comment]
i agree with this, having prismlauncher-qt5-git and prismlauncher-qt5 would be cool too

**Comment by jopejoe1** [comment]
`prismlauncher-git` was already add in https://github.com/chaotic-aur/packages/commit/17e1b7e9bd2d368e57c20c082f23f01e0455e2b0

**Comment by Technetium1** [comment]
Linking to #2036, thanks @jopejoe1.

@DioEgizio can do.

**Comment by Technetium1** [comment]
These are actually somewhat heavy builds, so if one ends up unused in the next couple of months, one or more may be pruned (looking especially at qt5 variants).
