### ISSUE TITLE
[Bug] mutter-dynamic-buffering and mutter-performance package conflict

### ISSUE THREAD

**Issue by phantomic12** [chaotic-aur/packages#2038]
### What happens?

whenever I try to build an arch image with mutter, there is an unresolvable package conflict betwen mutter-dynamic-buffering and mutter-performance

### What is expected to happen?

generic mutter packages from the official repos install

### If possible, please attach logs

Pre mutter-dynamic-buffering
https://github.com/phantomic12/phantomsarch/actions/runs/3269273120/jobs/5376591450

Post mutter-dynamic-buffering
https://github.com/phantomic12/phantomsarch/actions/runs/3285090214

**Comment by dr460nf1r3** [comment]
This will be resolved once the commit gets merged. The problem with this package is that it has `groups` in individual packages rather than a global `groups` - this caused `grep` to not find it.

**Comment by dr460nf1r3** [comment]
Should be resolved now!
