### ISSUE TITLE
[Request] java-jbr-xdg

### ISSUE THREAD

**Issue by jopejoe1** [chaotic-aur/packages#2039]
### Link to the package(s) in the AUR

https://aur.archlinux.org/pkgbase/java-jbr-xdg

### Utility this package has for you

One jdk/jre for all jetbrains tools, also includes some improvement to comply better with XDG Base Directory Specification

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by dr460nf1r3** [comment]
Left a comment at the AUR page.

**Comment by Technetium1** [comment]
@dr460nf1r3 new failure, any idea?

**Comment by dr460nf1r3** [comment]
Need to explicitly install `jdk17-openjdk` as makedepends.

**Comment by Technetium1** [comment]
Package no longer exists.
