### ISSUE TITLE
[Request] firefox-kde-opensuse

### ISSUE THREAD

**Issue by DroidFreak32** [chaotic-aur/packages#2040]
### Link to the package(s) in the AUR

[AUR firefox-kde-opensuse](https://aur.archlinux.org/packages/firefox-kde-opensuse)

### Utility this package has for you

Better integration with KDE

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Let's wait until it's updated to add it

**Comment by DroidFreak32** [comment]
Hey! The package has been updated. Just a heads up :)

**Comment by Technetium1** [comment]
This should be added to https://github.com/chaotic-aur/packages/blob/main/dragon-cluster/afternoon.txt once fixed, but for now we have an error:
[firefox-kde-opensuse.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/firefox-kde-opensuse.log)

```
# Issue 2040
kmozillahelper
firefox-kde-opensuse
```

**Comment by DroidFreak32** [comment]
Hi All,

When I try to build this package in a container environment, I get an error too.
I was able to fix this by changing line 215 in the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=firefox-kde-opensuse#n215):
Before
```
  export MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE=system
```
After
```
  export MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE=pip
```
[Reference AUR Comment](https://aur.archlinux.org/packages/firefox-kde-opensuse#comment-872633)

**Comment by DroidFreak32** [comment]
@Technetium1, I don't recommend this anymore the package is not frequently updated by the author and can cause security issues down the line.
I will revisit this in the future if needed
