### ISSUE TITLE
[Remove] Persepolis-git

### ISSUE THREAD

**Issue by Pakrohk** [chaotic-aur/packages#2041]
### Link to the package(s) in the AUR

[persepolis-git](https://aur.archlinux.org/packages/persepolis-git)

### Utility this package has for you

Qt front-end for aria2 download manager (Github version).

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

This software has not been updated for a long time in the official Arch repositories, but its git version is still being developed, I think adding it to the list of chaotic packages is a good idea.

**Comment by xiota** [comment]
Planning to drop because depends on defunct `youtube-dl` and upstream git repo hasn't been updated since Aug 2021.

**Comment by Technetium1** [comment]
We should be able to interfere and change depends. I wonder if this hook a valid solution, because it sure seems like it: https://aur.archlinux.org/packages/yt-dlp-drop-in

I'll mention a related issue, maybe someone else will chime in: https://github.com/persepolisdm/persepolis/issues/930

**Comment by xiota** [comment]
Asking maintainer to patch to use yt-dlp, according to https://github.com/persepolisdm/persepolis/issues/930#issuecomment-1746877113.  If package is not updated "soon", will drop.

**Comment by xiota** [comment]
`yt-dlp-drop-in` will not work because it is only a shell script.  It does not cover python imports.

**Comment by xiota** [comment]
Dropping now.

* "Fetch Media List" doesn't work with `youtube-dl`, `youtube-dl-git`, or `ytdl-shim`.
* AUR maintainer didn't reply to comment, even if only to decline to patch.
* OP did not object to plans to drop "soon" for over a month.
