### ISSUE TITLE
[Request] jetbrains-fleet

### ISSUE THREAD

**Issue by FireMasterK** [chaotic-aur/packages#2043]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/jetbrains-fleet

### Utility this package has for you

It's JetBrain's new fancy polyglot IDE.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Sorry this is too big, so it's declined.

**Comment by joe733** [comment]
Hi @Technetium1, ChaoticAUR is already building Android Studio which has a download size of `~ 1113M`,

```console
$ pacman -Ss android-studio
chaotic-aur/android-studio 2022.3.1.19-1
    The official Android IDE (Stable branch)
chaotic-aur/android-studio-canary 2023.2.1.1-1
    The Official Android IDE (Canary branch)
chaotic-aur/android-studio-launcher 1:1.0.3-1
    Wrap android-sdk directory in UnionFS to be "writeable" for Android Studio
```

whereas JetBrains Fleet only has a download size of `~ 206M`. Currently it does not have any dependencies. I've built it successfully in chroot.

I'm not aware of the state of ChaoticAUR or JetBrains Fleet package a year ago, but today given the available information I'm positive that it can build this package.

Please let me know if anything else is a showstopper to build this package. May I open a new package request for re-considerations?

**Comment by xiota** [comment]
> Android Studio which has a download size of ~ 1113M

Perhaps Android Studio should be dropped?  (I jest... unless it can... metrics show 0 downloads.)

> May I open a new package request... ?

Don't open a new request.  Commenting on the old request is sufficient.

> Please let me know if anything else is a showstopper...

JetBrains [license](https://aur.archlinux.org/cgit/aur.git/tree/LICENSE?h=jetbrains-fleet) is known to prohibit distribution:

> (C) You must not:
>
> (i) rent, lease, reproduce, modify, adapt, create derivative works of, distribute, sell or transfer the Product;

**Comment by Technetium1** [comment]
@joe733 `android-studio` belongs to a maintainer, Paulo. It will stay around until there's a major issue with it or Paulo decides to remove it. We would also like to avoid displeasing JetBrains.

@xiota I don't believe metrics are entirely repopulated right now, and as such can't be trusted yet. Moreso since it hasn't had a [need to rebuild](https://aur.archlinux.org/cgit/aur.git/log/?h=android-studio) recently.
