### ISSUE TITLE
[Request] IPFS-Desktop

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#2045]
### Link to the package(s) in the AUR

[AUR](https://aur.archlinux.org/packages/ipfs-desktop)

### Utility this package has for you

Desktop client for the InterPlanetary File System

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

The InterPlanetary File System is a protocol, hypermedia and file sharing peer-to-peer network for storing and sharing data in a distributed file system. IPFS uses content-addressing to uniquely identify each file in a global namespace connecting IPFS hosts. IPFS can among others replace the location based hypermedia server protocols http and https to distribute the World Wide Web.

**Comment by xiota** [comment]
Switched to custom package using system electron and autoupdate because aur package...

* has unnecessary depends causing build failure
* reverted to previous version, with gratuitous epoch bump
* has questionable install script
* has "interesting" packaging (builds a pacman package that is repacked into another pacman package)

Metrics 79.

**Comment by RubenKelevra** [comment]
@xiota I would have appreciated a notification and fixed any of the issues you posted here, if you reached out to me. Kinda weird that you didn't.

**Comment by xiota** [comment]
@RubenKelevra Will try to contact you about issues in the future.  I get tired of notifying maintainers of problems.

**Comment by RubenKelevra** [comment]
@xiota thanks!

How do we move forward with this?

1) Since you removed the zero license your proposed solution has the wrong license for the AUR. So I can't use it and would need to start from scratch with your explanations. 

2) the version push is inenvertenly now, as otherwise it would require a manual intervention by the users

3) Do you remember what you meant by "has unnecessary depends causing build failure"? I mean I use it and and it builds fine for me. I'm curious!

**Comment by xiota** [comment]
1. Are you referring to copyright on the PKGBUILD itself?  Use what you want from it.  Packaging scripts are almost entirely boilerplate – package name, description, depends, makedeps, make/cmake/meson, etc – not truly copyrightable.

    * Do not add me to the contributor list on AUR.  Whoever commits is responsible for the package.  Whoever commits may add themselves.  Adding other people to lists is like signing them up for junk mail.

2. What's done is done.  But generally, doesn't make sense to bump epoch for a temporary version slide.

3. Try building in clean chroot: `error: target not found: http-parser`

**Comment by RubenKelevra** [comment]
> 1. Are you referring to copyright on the PKGBUILD itself?

Yep. Just wanted to make sure we're on the same page here, as the repo has GPL licensing. Thanks!



> 2\. What's done is done.  But generally, doesn't make sense to bump epoch for a temporary version slide.

Yeah, I get the sentiment, thanks for your input :)



> 3\. Try building in clean chroot: `error: target not found: http-parser`

Thanks again, will have a look when I'm home!

**Comment by xiota** [comment]
> the repo has GPL licensing

I'd forgotten, but licenses generally don't apply to uncopyrightable stuff.

**Comment by RubenKelevra** [comment]
> 3\. Try building in clean chroot: `error: target not found: http-parser`

Ah, I found the issue:

CachyOS packages the AUR-Package http-parser as Pacman package:

```
❯ paru -Ss http-parser
cachyos/http-parser 2.9.4-2 [0 B 57.70 KiB] [Installed]
    Parser for HTTP Request/Response written in C
extra/ruby-http_parser.rb 0.8.1-1 [119.92 KiB 385.72 KiB]
    Ruby bindings to https://github.com/ry/http-parser and https://github.com/a2800276/http-parser.java
aur/http-parser 2.9.4-2 [+24 ~5.02] [Installed]
    Parser for HTTP Request/Response written in C
aur/perl-http-parser-xs 0.17-3 [+5 ~0.00]
    a fast, primitive HTTP request parser
```

But usually AUR-Packages should be also able to draw other AUR packages as dependencies. Maybe that's a limitation in your build process?

Anyway, I'll gave your PKGBUILD a look and I think it's a better build process. I'll integrate it/switch over to it and not list you as contributor, as you requested. So I like to thank you here personally for your contribution instead! :)

**Comment by xiota** [comment]
> usually AUR-Packages should be also able to draw other AUR packages as dependencies

Deps that aren't in official Arch repos have to be reviewed and added separately.  As far as I can tell, `http-parser` isn't needed by this package.  From the AUR page, it looks like it may have been dropped from official repos Sep 2025.

> I'll integrate it/switch over to it

I'll review the package for potential switch back after I see the update.

> I like to thank you here personally for your contribution

No problem.

**Comment by RubenKelevra** [comment]
I've already pushed the requested changes before you wrote your last comment :)
