### ISSUE TITLE
[Outdated] 

### ISSUE THREAD

**Issue by phantomic12** [chaotic-aur/packages#2047]
### Package name

discord-electron-bin

### Latest build

0.0.21-1

### Latest version available

0.0.20-1

### Have you tested if the package builds in a clean chroot?

- [X] Yes

**Comment by completelygenericusername** [comment]
there's no `discord-electron-bin` in the repository. maybe you meant `discord-canary-electron-bin`? also, could you update your title to include the package name? (example title: `[Outdated] discord-canary-electron-bin`)

**Comment by Technetium1** [comment]
Both of the `-bin` packages we have match the versions available in the AUR. Please add more details.
