### ISSUE TITLE
[Bug] gnome-text-editor needs rebuild

### ISSUE THREAD

**Issue by Piroro-hs** [chaotic-aur/packages#2048]
### What happens?

```
gnome-text-editor: error while loading shared libraries: libicuuc.so.71: cannot open shared object file: No such file or directory
```

### What is expected to happen?

Launch gnome-text-editor.

### If possible, please attach logs

```
$ ldd `which gnome-text-editor` | grep icu
        libicuuc.so.71 => not found
        libicuuc.so.72 => /usr/lib/libicuuc.so.72 (0x00007f5f0d01c000)
        libicui18n.so.72 => /usr/lib/libicui18n.so.72 (0x00007f5f0ccab000)
        libicudata.so.72 => /usr/lib/libicudata.so.72 (0x00007f5f0ab80000)
```

### More information

Latest `icu` package version on arch repository is 72.1-1.

**Comment by SolarAquarion** [comment]
The automatic rebuild interfere should be added in interfere

**Comment by Technetium1** [comment]
#1619 is getting dropped because it's been moved to main repos, see [this AUR request](https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/thread/JIT4LGUJ2DWWKXUFSR76QBFVUG2PDHMS/#JIT4LGUJ2DWWKXUFSR76QBFVUG2PDHMS).
