### ISSUE TITLE
[Outdated] Linux-tkg-pds

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#2062]
### If available, link to the latest build

[linux-pds](https://aur.archlinux.org/packages/linux-pds)

### Package name

`Linux-pds`

### Latest build

`6.0.1-270`

### Latest version available

`v6.0.6-arch1`

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### More information

Strange, why don't you use the aur version?!
  Did I get it wrong? Because you don't get this kernel version from aur, you get it directly from the project's official git repository.

**Comment by ALipAkrohk** [comment]
> I don't know if you noticed but for linux 6.0 bmq and pds have been disabled.
https://github.com/Frogging-Family/linux-tkg/commit/d60046d9fb565bb70992c821905aff18a18d43f9

Yes, and that's why I opened this issue.
The project in aur is still updating, I was wondering why !?
https://aur.archlinux.org/packages/linux-pds

**Comment by dr460nf1r3** [comment]
That's likely because it is another maintainer compared to TKG. I don't know what reasons TKG had for disabling it, it might be worth asking at their repository since they know best :)
