### ISSUE TITLE
[Request] hd

### ISSUE THREAD

**Issue by Noah-Arcouette** [chaotic-aur/packages#2063]
### Link to the package(s) in the AUR

[hd](https://aur.archlinux.org/packages/hd)

### Utility this package has for you

HD is a C makefile generator that uses source file to generate dependencies. HD requires a one time configuration per-project 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because upstream repo has been deleted.
