### ISSUE TITLE
[Request] megasync-bin

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#2065]
### Package:

https://aur.archlinux.org/packages/megasync-bin

### Purpose:

Easy automated syncing between your computers and your MEGA cloud drive

### Benefits:

This needs to be added as a temporary alternative to `megasync` from #335 while it's severely outdated due to pkgbuild issues.

### Building:

clean chroot

### Copyright:

https://github.com/meganz/MEGAsync/blob/master/LICENCE.md

> * “non-commercial distribution” means distribution of the code or any compilation of the code, or of any other application or program containing the code or any compilation of the code, where such distribution is not intended for or directed towards commercial advantage or monetary compensation.
>
> 2\. You may provide the code to anyone else and publish excerpts of it for the purposes of review, compilation and non-commercial distribution, provided that when you do so you make any recipient of the code aware of the terms of this licence, they must agree to be bound by the terms of this licence and you must attribute the code to Mega.
>
> 3\. Other than in respect of those parts of the code that were developed by other parties and as specified strictly in accordance with the open source and other licences under which those parts of the code have been made available, as set out on our website or in those items of code, you are not entitled to use or do anything with the code for any commercial or other purpose, other than review, compilation and non-commercial distribution in accordance with the terms of this licence.

### Expected Interest:

Many

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
Depends on Qt5 and will not be readded until upstream moves to Qt6. See #3157

**Comment by EyBmY** [comment]
Can we add this to Chaotic AUR again?

**Comment by xiota** [comment]
The package still uses EOL Qt5, and upstream project doesn't appear to have been updated for Qt6.  https://github.com/meganz/MEGAsync

Feel free to comment for reconsideration when it no longer uses EOL libraries.
