### ISSUE TITLE
[Meta/Outdated] Rebuild all packages in chaotic-aur with openssl 3.x

### ISSUE THREAD

**Issue by VexfulNiko** [chaotic-aur/packages#2069]
### Package name

N/A

### Latest build

N/A

### Latest version available

N/A

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

Arch is in the process of updating all packages to use OpenSSL3.x instead of OpenSSL1.x, It's currently in the testing repo and is most likely to move to the stable repos relatively soon.

**Comment by Technetium1** [comment]
https://lists.archlinux.org/archives/list/arch-dev-public@lists.archlinux.org/thread/IZT6ADWS5YUUNC7IFBUVYIB7O4QIJGZV/

https://md.archlinux.org/s/t8HOyhNOi

**Comment by niobium93** [comment]
`ruffle-git` needs to be rebuilt because of this.

**Comment by dr460nf1r3** [comment]
This is currently in progress while mirrors are frozen.

**Comment by Technetium1** [comment]
Things that were missed are being tracked in: #2086
