### ISSUE TITLE
[Request] palemoon-gtk3

### ISSUE THREAD

**Issue by RubenKelevra** [chaotic-aur/packages#2071]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/palemoon-gtk3

https://aur.archlinux.org/packages/palemoon-gtk3-bin

### Utility this package has for you

You're currently creating `palemoon-gtk3-bin` (linked above). Not sure why you package a binary, I mean it has no benefits.

Could you please include `palemoon-gtk3` instead? This would make sure the package will be built with the latest build tools arch provides, instead of the build server the project is using. :)

### Related requests

https://github.com/chaotic-aur/packages/issues/573

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Hi @RubenKelevra, thanks for noticing this! I would very much like to switch too, but we cannot. The non `-bin` requires python2 still (see #1958). Once they eventually update to python3, please reopen this issue, and we'll be more than happy to add it!
