### ISSUE TITLE
[Outdated] 

### ISSUE THREAD

**Issue by Bhooty** [chaotic-aur/packages#2073]
### If available, link to the latest build

https://aur.archlinux.org/packages/rtl88x2bu-dkms-git

### Package name

rtl88x2bu-dkms-git

### Latest build

5.13.1.r166.3d25a90-1

### Latest version available

5.13.1.r166.3d25a90-1

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### More information

This packages requires kernel headers for it to work and is backdated in the repo.

Warning: rtl88x2bu-dkms-git: local (5.13.1.r173.88f80f7-1) is newer than chaotic-aur (5.13.1.r171.bfcf676-1)

**Comment by Technetium1** [comment]
`rtl88x2bu-dkms-git 5.13.1.r176.0c8f2cf-1` now available, sorry I forgot to close this!
