### ISSUE TITLE
[Request] gnome-git meta

### ISSUE THREAD

**Issue by nyabinary** [chaotic-aur/packages#2075]
### Link to the package(s) in the AUR

N/A
*Gnome Git Packages

### Utility this package has for you

Bleeding edge gnome-desktop.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

There is a KDE -git meta-package, so it makes sense to offer a gnome -git meta package as well.

**Comment by VexfulNiko** [comment]
@PedroHLC I saw that in the repo, you had made a PKGBUILD for gnome-git-meta but haven't updated it from the placeholder PKGBUILD: https://github.com/chaotic-aur/pkgbuild-gnome-git-meta
What's blocking you from doing a gnome git meta package, if anything?

**Comment by PedroHLC** [comment]
> @PedroHLC I saw that in the repo, you had made a PKGBUILD for gnome-git-meta but haven't updated it from the placeholder PKGBUILD: https://github.com/chaotic-aur/pkgbuild-gnome-git-meta What's blocking you from doing a gnome git meta package, if anything?

That repo is an indirect fork of our "template-repo", made by someone else.

**Comment by VexfulNiko** [comment]
How hard would it be to make something like this? Considering yall have kde-git.

**Comment by PedroHLC** [comment]
> How hard would it be to make something like this? Considering yall have kde-git.

Open a PR :smile:

**Comment by Technetium1** [comment]
@VexfulNiko about as hard as https://github.com/chaotic-aur/pkgbuild-kde-git-meta/blob/main/PKGBUILD

**Comment by xiota** [comment]
Rejecting as too hard.  Would need someone who is interested in actively maintaining all gnome-git packages.  Would also need to be in a separate repo (like kde-git) to prevent library conflicts.
