### ISSUE TITLE
[Request] openssl-git

### ISSUE THREAD

**Issue by xiota** [chaotic-aur/packages#2076]
### Link to the package(s) in the AUR

openssl3-git installs the openssl 3.x branch alongside the 1.x branch.  Now that 3.x is in the official repo, side-by-side installation is no longer needed.  So the package can either be removed or replaced with [openssl-git](https://aur.archlinux.org/packages/openssl-git).

### Utility this package has for you

None, now that the Arch repo is using openssl 3.x.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No.

### Do you consider the package to be useful for feature testing/preview?

No.

### Have you tested if the package builds in a clean chroot?

No.

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

N/A

**Comment by xiota** [comment]
Note: `openssl3-git` has been removed from the AUR with reason: Now a duplicate of openssl-git. [\[1\]](https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/message/C4CEVFRC7R5HNJSNPKCTMLHE4DEE6CHA/) [\[2\]](https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/message/DAWCRSXIWS5UI6BOQNB744MI7PL27YXA/) [\[3\]](https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/message/KI2N6JKVV2BXD73VCS7ETPZFDLJTXKXC/)

**Comment by Technetium1** [comment]
I think based on this, the patching process may need to be updated? Based on the last few changes here: https://github.com/archlinux/svntogit-packages/commits/master/openssl. This one is maybe the most relevant: https://github.com/archlinux/svntogit-packages/commit/eef05b437f55c4d9403668ebdc27973c6a6c2134
[openssl-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/openssl-git.log)

**Comment by xiota** [comment]
Since `openssl-git` isn't building, why not just remove `openssl3-git` entirely?   The main reason to install `openssl3-git` was to have the 3.x branch available for binaries that require it.  Since `openssl` has been switched to the 3.x branch, it's not needed anymore.

**Comment by dr460nf1r3** [comment]
Sure thing!

**Comment by Technetium1** [comment]
@xiota that was just done in the commit above my last comment :)

**Comment by xiota** [comment]
@Technetium1 Sorry, missed that.

**Comment by Technetium1** [comment]
Patching process updated, let's try again.. https://aur.archlinux.org/cgit/aur.git/commit/?h=openssl-git&id=180f8c7ae477eae70b74a326595f17c05d2b9ca4

**Comment by xiota** [comment]
Dropping.  No longer needed.
```
$ comm <(pactree -usrd1 openssl-git | sort -u) <(pactree -usrd1 openssl | sort -u) -3
        openssl
openssl-git
```
