### ISSUE TITLE
[Request] cura-bin

### ISSUE THREAD

**Issue by Gontier-Julien** [chaotic-aur/packages#2077]
### Link to the package(s) in the AUR

[cura-bin](https://aur.archlinux.org/packages/cura-bin)

### Utility this package has for you

This packages was previously on the official repos of archlinux, but it was dropped not so long ago.
It an awesome slicer for 3D printing!

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
> Does the package's license allow redistributing it?

Yes.  Cura is licensed LGPL-3.0.  Source and binaries are available at https://github.com/Ultimaker/Cura

**Comment by Gontier-Julien** [comment]
> > Does the package's license allow redistributing it?
> 
> Yes. Cura is licensed LGPL-3.0. Source and binaries are available at https://github.com/Ultimaker/Cura
> 
> Unfortunately, `cura` package is out of date, won't build, and I couldn't figure out how to fix it frowning_face

That why it was dropped from the archlinux repo, but cura-bin work just fine, so it okay
