### ISSUE TITLE
[Request] thunderbird-beta-i18n

### ISSUE THREAD

**Issue by yurikoles** [chaotic-aur/packages#2078]
### Link to the package(s) in the AUR

[thunderbird-beta-i18n](https://aur.archlinux.org/pkgbase/thunderbird-beta-i18n).

### Utility this package has for you

Language packs split package for [thunderbird-beta](https://github.com/chaotic-aur/packages/issues/1536).

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

I'm a maintainer of this package on AUR. `thunderbird-beta` should be installed in a chroot before building.

**Comment by xiota** [comment]
@yurikoles Does this package work properly when the version is out of sync from `thunderbird-beta`?

You might want to consider adding autoupdate capability to the packages to reduce the need for frequent version bumps.  You can see the changes needed at [interfere/thunderbird-beta-i18n](https://github.com/chaotic-aur/interfere/tree/6d8b6f1b11ecfbe580ab2173a865c6bfa072ab60/thunderbird-beta-i18n).
