### ISSUE TITLE
[Request] asus-fan-dkms-git

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#2083]
### Link to the package(s) in the AUR

[aur](https://aur.archlinux.org/packages/asus-fan-dkms-git)

### Utility this package has for you

Kernel module allowing to control (both) fan inside various ASUS laptops

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Sorry this took so long
