### ISSUE TITLE
[Request] prboom-plus + prboom-plus-um-git

### ISSUE THREAD

**Issue by yum13241** [chaotic-aur/packages#2085]
### Link to the package(s) in the AUR

PR+: https://aur.archlinux.org/packages/prboom-plus
PR+_UM_GIT: https://aur.archlinux.org/packages/prboom-plus-um-git
PR+_SVN: https://aur.archlinux.org/packages/prboom-plus-svn

### Utility this package has for you

This is a Doom port that is compatible with many others, it can also be faster than GZDoom. Sometimes I want to test or play maps in this port to see how it works in it.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

AFAIK `prboom-plus` recent releases are all UM releases (**UM**APINFO), but some people like to live on the edge.

**Comment by Technetium1** [comment]
Not sure why `prboom-plus-svn` is failing, but here's the log: [prboom-plus-svn.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/prboom-plus-svn.log)

**Comment by Technetium1** [comment]
`prboom-plus-svn` is superseded by the other 2 packages!

**Comment by xiota** [comment]
As of Jun 2023, development on [prboom-plus](https://github.com/coelckers/prboom-plus) has ceased.

Dropping `prboom-plus-um-git` because it is now effectively the same as `prboom-plus`.

`prboom-plus` can remain because the final release is still fairly recent.
