### ISSUE TITLE
[Rebuild] Missing packages

### ISSUE THREAD

**Issue by dr460nf1r3** [chaotic-aur/packages#2086]
### What is happening?

After our latest repository rebuild that was needed due to the OpenSSL 3 update in Arch repos, a few packages couldn't be built due to various build errors. This issue tracks the progress.

### More information

Most of the packages are present here: [https://builds.garudalinux.org/repos/chaotic-aur/logs/filtered/dep-not-in-repo/](https://builds.garudalinux.org/repos/chaotic-aur/logs/filtered/dep-not-in-repo/)

**Comment by Technetium1** [comment]
[cryptomator](https://aur.archlinux.org/packages/cryptomator) is failing again: [cryptomator.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/cryptomator.log)
* I updated deps here: https://github.com/chaotic-aur/packages/commit/89dec945a756c5f2c80eb5b515df254ced2e8fad
* I removed @dr460nf1r3's previous interfere changes here: https://github.com/chaotic-aur/interfere/commit/0ac9955f21139f637dd6f802390d94959bfa73f2
* Now at the point of being able to at least see a failure in the build

**Comment by Technetium1** [comment]
[github-desktop](https://aur.archlinux.org/packages/github-desktop) is failing: [github-desktop.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/github-desktop.log)
Probably due to something with submodules.

**Comment by Technetium1** [comment]
[replay-sorcery-git](https://aur.archlinux.org/packages/replay-sorcery-git) is failing: [replay-sorcery-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/replay-sorcery-git.log)
Probably due to something with submodules.

**Comment by Technetium1** [comment]
[tuner](https://aur.archlinux.org/packages/tuner#comment-888696) is missing a dependency upstream. I reported it.
[tuner.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/tuner.log)

**Comment by dr460nf1r3** [comment]
> [cryptomator](https://aur.archlinux.org/packages/cryptomator) is failing: [cryptomator.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/cryptomator.log)
> * I updated deps here: https://github.com/chaotic-aur/packages/commit/89dec945a756c5f2c80eb5b515df254ced2e8fad
> * I removed @dr460nf1r3's previous interfere changes here: https://github.com/chaotic-aur/interfere/commit/0ac9955f21139f637dd6f802390d94959bfa73f2
> * Now at the point of being able to at least see a failure in the build

It seems we need to force an older version of Java to be able to build it. Ideally the maintainer fixes it, otherwise we could do the interfere way.

**Comment by Technetium1** [comment]
[health](https://aur.archlinux.org/packages/health) from #1693 is failing: [health.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/health.log)
Python problem: `ModuleNotFoundError: No module named 'gi'`

**Comment by FireMasterK** [comment]
`balena-etcher` seems to missing too and `stremio` is failing (it fails locally too, due to a git security update disabling the file protocol :/ )

**Comment by Technetium1** [comment]
### Spotify failures:
- [ ] [spotify](https://builds.garudalinux.org/repos/chaotic-aur/logs/spotify.log)
- [ ] [spotify-adblock-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/spotify-adblock-git.log)
- [ ] [spotify-qt](https://builds.garudalinux.org/repos/chaotic-aur/logs/spotify-qt.log)
- [ ] [spotify-tui](https://builds.garudalinux.org/repos/chaotic-aur/logs/spotify-tui.log)
- [ ] [spotify-tray-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/spotify-tray-git.log)

**Comment by Technetium1** [comment]
`ttf-malayalam-fonts-meta` missing lots of deps

**Comment by dr460nf1r3** [comment]
> [health](https://aur.archlinux.org/packages/health) from #1693 is failing: [health.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/health.log) Python problem: `ModuleNotFoundError: No module named 'gi'`
Fixed in https://github.com/chaotic-aur/interfere/commit/c139a0220c1794f336f4c83c547204fcf65b13aa

**Comment by dr460nf1r3** [comment]
> `balena-etcher` seems to missing too and `stremio` is failing (it fails locally too, due to a git security update disabling the file protocol :/ )

`balena-etcher` was actually dropped due to using an unsupported version of Electron. I'd recommend `ventoy-bin` as handy alternative.

**Comment by FireMasterK** [comment]
> `balena-etcher` was actually dropped due to using an unsupported version of Electron. I'd recommend `ventoy-bin` as handy alternative.

Why not ship `etcher-bin` instead then? It seems to be bundled with its own Electron build

**Comment by dr460nf1r3** [comment]
A valid point! However there was also another reason for this decision as `etcher-bin` is an extremely heavy package for what it actually does (300+mb iirc), while the mirror's space is something to look after these days. Luckily we have better alternatives available - building `etcher-bin` yourself also shouldn't take as long as it is a binary anyways if prefer using it :)

**Comment by dr460nf1r3** [comment]
> ### Spotify failures:
> 
>     * [x]  [spotify](https://builds.garudalinux.org/repos/chaotic-aur/logs/spotify.log)
> 
>     * [x]  [spotify-adblock-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/spotify-adblock-git.log)
> 
>     * [x]  [spotify-qt](https://builds.garudalinux.org/repos/chaotic-aur/logs/spotify-qt.log)
> 
>     * [ ]  [spotify-tui](https://builds.garudalinux.org/repos/chaotic-aur/logs/spotify-tui.log)
> 
>     * [x]  [spotify-tray-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/spotify-tray-git.log)
 
`spotify-tui` seems to be failing due to Rust related issues, the rest were built successfully after removing the build-breaking `prepare` function of Spotify.

**Comment by Technetium1** [comment]
[`extension-manager-git`](https://aur.archlinux.org/packages/extension-manager-git) is failing: [extension-manager-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/extension-manager-git.log)

**Comment by tablet0ps** [comment]
`citra-canary-git` is also failing to build: [citra-canary-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/citra-canary-git.log)

**Comment by Technetium1** [comment]
@tablet0ps This is likely to stay broken until it updates, as [it's flagged on the AUR](https://aur.archlinux.org/packages/[). It also has a [pending request to orphan here](https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/thread/AZ7V3FZF5AI7JBUEHMR2KN6EKB4X6BOY/#AZ7V3FZF5AI7JBUEHMR2KN6EKB4X6BOY).

**Comment by Technetium1** [comment]
[`plasmatube-git`](https://aur.archlinux.org/packages/plasmatube-git) is failing: [plasmatube-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/plasmatube-git.log)
```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find KF5 (missing: Config) (found suitable version "5.99.0",
minimum required is "5.81.0")
```

**Comment by Technetium1** [comment]
[`responsively`](https://aur.archlinux.org/packages/responsively) is failing: [responsively.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/responsively.log)
`code: 'ERR_OSSL_EVP_UNSUPPORTED'`

**Comment by erenfro** [comment]
> [`extension-manager-git`](https://aur.archlinux.org/packages/extension-manager-git) is failing: [extension-manager-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/extension-manager-git.log)

Reached out to Igor for this. It's missing python-gobject makedepend which is on the non-git package maintained by the same guy.

**Comment by erenfro** [comment]
> > [`extension-manager-git`](https://aur.archlinux.org/packages/extension-manager-git) is failing: [extension-manager-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/extension-manager-git.log)
> 
> Reached out to Igor for this. It's missing python-gobject makedepend which is on the non-git package maintained by the same guy.

And this has been fixed, upstream at least. I tested in my own aurto server, and it built a package fine, so we should be golden on this -git version of this.

**Comment by Technetium1** [comment]
@erenfro It's back! `Finished making: extension-manager-git 0.4.0.r34.g5b1fa91-1 (Wed 16 Nov 2022 11:39:50 PM CET)`

**Comment by VexfulNiko** [comment]
sddm-kcm-git missing.

**Comment by Technetium1** [comment]
cryptomator should build as soon as the maintainer updates, a new release is out using the new Java version, so I [flagged the package](https://aur.archlinux.org/pkgbase/cryptomator/flag-comment).

**Comment by Technetium1** [comment]
I left [a comment](https://aur.archlinux.org/packages/cryptomator#comment-892826) for the maintainer, so they can fix cryptomator. In the meantime there is https://github.com/chaotic-aur/interfere/commit/c8987b8b2bde5d401a227f98dc81a9e3a2b5f745.

**Comment by Technetium1** [comment]
I can't find `jpackage`, but `jlink` is in `/usr/lib/jvm/default/bin/jlink`.
[cryptomator.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/cryptomator.log)

**Comment by sgse** [comment]
![grafik](https://user-images.githubusercontent.com/17575778/206527982-67c9ad08-691b-452e-800c-7c19840c0d92.png)

**Comment by dr460nf1r3** [comment]
Since all the still occuring issues are tracked and longer-term build failures, I'm closing this issue.
