### ISSUE TITLE
[Request] nheko-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#2087]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/nheko-git

### Utility this package has for you

Desktop client for the Matrix protocol

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Linked to #2086

**Comment by Technetium1** [comment]
It was just missing `re2` in makedepends per [this comment](https://aur.archlinux.org/packages/nheko-git#comment-885526).

**Comment by Technetium1** [comment]
`Finished making: nheko-git 0.10.2.r139.g0cc1c6ed-1 (Wed 09 Nov 2022 04:18:46 AM CET)`
