### ISSUE TITLE
[Request] discord-screenaudio

### ISSUE THREAD

**Issue by sylviiu** [chaotic-aur/packages#2090]
### Link to the package(s) in the AUR

[AUR](https://aur.archlinux.org/packages/discord-screenaudio)

### Utility this package has for you

a discord client that allows the user to screenshare with audio via pipewire

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Very cool!!

**Comment by xiota** [comment]
Dropped because upstream discontinued Jun 2024.  AUR package flagged since Apr 2025.  Metrics 29.
