### ISSUE TITLE
[Request] pleroma-bin

### ISSUE THREAD

**Issue by Ty3r0X** [chaotic-aur/packages#2091]
### Link to the package(s) in the AUR

[https://aur.archlinux.org/packages/pleroma-bin](https://aur.archlinux.org/packages/pleroma-bin)

### Utility this package has for you

Ability to run a federated microblogging platform in Arch / Garuda

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Unfortunately pleroma AUR packages have become unmaintained.
