### ISSUE TITLE
[Bug] psautohint: signature from "Pedro Henrique Lara Campos <root@pedrohlc.com>" is invalid

### ISSUE THREAD

**Issue by latin-1** [chaotic-aur/packages#2094]
### What happens?

error: psautohint: signature from "Pedro Henrique Lara Campos <root@pedrohlc.com>" is invalid

### What is expected to happen?

Installed successfully.

**Comment by Technetium1** [comment]
Related #2086

**Comment by Technetium1** [comment]
`Finished making: psautohint 3:2.4.0-1.2 (Wed 09 Nov 2022 04:40:40 AM CET)`
Should be fine now.
