### ISSUE TITLE
[Bug] proton-ge-custom is missing

### ISSUE THREAD

**Issue by latin-1** [chaotic-aur/packages#2095]
### What happens?

.

### What is expected to happen?

.

**Comment by Technetium1** [comment]
Related #2086

**Comment by Technetium1** [comment]
The deps for it should really be organized in this process

**Comment by Technetium1** [comment]
- [ ] python-pyclipper
- [ ] python-booleanoperations
- [ ] python-defcon
- [ ] python-fontmath
- [ ] python-fontparts
- [ ] python-fontpens
- [ ] python-mutatormath
- [ ] python-ufonormalizer
- [ ] python-ufoprocessor
- [ ] psautohint
- [ ] lib32-lzo
- [ ] mingw-w64-tools
- [ ] afdko
- [ ] lib32-gsm
- [ ] proton-ge-custom

**Comment by Technetium1** [comment]
`python-fontpens` & `python-fontparts` have a circular dependency issue. This is the problem. Need to manually build one without tests.

**Comment by Technetium1** [comment]
:tada: `Finished making: proton-ge-custom 2:GE.Proton7.41-1 (Sat 12 Nov 2022 02:36:01 AM CET)`

**Comment by dr460nf1r3** [comment]
Very nice, well done!

**Comment by Technetium1** [comment]
I feel like it should ideally error out on insatiable cyclic dependencies instead of just hanging mysteriously.
