### ISSUE TITLE
[Request] linux-tkg-tt

### ISSUE THREAD

**Issue by drishal** [chaotic-aur/packages#2096]
### Link to the package(s) in the AUR

linux-tt and linux-tkg-tt (i.e linux with tt/task type scheduler, and also linux-tkg with it as well)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by yum13241** [comment]
I'd also like to request the `cacule` line as well.

**Comment by Technetium1** [comment]
@drishal we already have `linux-tt` available, and I can't find `linux-tkg-tt`. We already have other various tkg kernels. Please explain what exactly you want.

**Comment by dr460nf1r3** [comment]
We would need to modify the toolbox in order to process this request.

**Comment by drishal** [comment]
> @drishal we already have `linux-tt` available, and I can't find `linux-tkg-tt`. We already have other various tkg kernels. Please explain what exactly you want.

Basically Linux tkg kernel but with tt scheduler

**Comment by dr460nf1r3** [comment]
This will be available the next time our kernels are built! :)

**Comment by drishal** [comment]
Yes just installed tkg-tt from chaotic aur :)
