### ISSUE TITLE
[Rebuild] mangohud

### ISSUE THREAD

**Issue by epic0421** [chaotic-aur/packages#2098]
### If available, link to the latest build

Whenever I try to run `mangohud` with Steam I get this error:

```
/bin/sh: error while loading shared libraries: libspdlog.so.1: cannot open shared object file: No such file or directory
```

I ended up tracing it back to `mangohud` yet `mangohud-git` doesn't have this issue.

### Package name

mangohud

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by Technetium1** [comment]
There's a new `spdlog`, bumping and rebuilding now

**Comment by Technetium1** [comment]
`Finished making: mangohud 0.6.8-2.2 (Wed 09 Nov 2022 06:21:45 PM CET)`
Please reopen if it persists :)
