### ISSUE TITLE
plasma5-applets-latte-separator

### ISSUE THREAD

**Issue by Kandelai** [chaotic-aur/packages#2100]
### If available, link to the latest build

In updating AUR via yay -Syu, I noticed it flagged this package as a newer version available in AUR, so wondering if you can update it also in Chaotic-aur. thanks.

### Package name

plasma5-applets-latte-separator

### Latest build

0.1.1-1

### Latest version available

0.1.2-1

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by Technetium1** [comment]
This isn't actually in a routine or seen when searching via pacman... :eyes:
