### ISSUE TITLE
[Bug] natron-bin

### ISSUE THREAD

**Issue by a51kot** [chaotic-aur/packages#2101]
### What happens?

Natron its broken

```
 Natron
Natron: error while loading shared libraries: libboost_serialization.so.1.79.0: cannot open shared object file: No such file or directory

```

### What is expected to happen?

Running it >)

### If possible, please attach logs

 Natron
Natron: error while loading shared libraries: libboost_serialization.so.1.79.0: cannot open shared object file: No such file or directory

### More information

Could u please  _force/trigger_  a rebuild  (natron / openfx-arena / openfx-io / openfx-misc / openfx-gmic)

thanks

**Comment by a51kot** [comment]
And natron its slightly annoying   (it needs some   aur packs)  si i CANT  play with my obs instance

**Comment by Technetium1** [comment]
Unfortunately, Natron is going to have to be dropped due to Python 2 :frowning_face: 
See #1958

**Comment by Technetium1** [comment]
My mistake, I forgot I'd already removed that entire metapackage for that reason. We only have `natron-bin`.

**Comment by Technetium1** [comment]
This might be missing `boost` in depends. It's the only x64 package providing that shared library. I left [a comment](https://aur.archlinux.org/packages/natron-bin#comment-889101) for the maintainer.

**Comment by Technetium1** [comment]
Bumped here: https://github.com/chaotic-aur/interfere/commit/4b4d7d5f29b0d0e00a63622f0fac4f4ad92a1a34#diff-acda3a66e1f15a258e2d7c66274a579f3e77ce846d9358b43f611ab39f0ae9f2R1102

**Comment by Technetium1** [comment]
`natron-git` is being added in #2103
