### ISSUE TITLE
[Remove] natron-git

### ISSUE THREAD

**Issue by a51kot** [chaotic-aur/packages#2103]
### Link to the package(s) in the AUR

https://aur.archlinux.org/packages/natron-git
https://aur.archlinux.org/packages/natron-compositor-git
https://aur.archlinux.org/packages/openfx-arena-git
https://aur.archlinux.org/packages/openfx-gmic-git
https://aur.archlinux.org/packages/openfx-misc-git
https://aur.archlinux.org/packages/natron-plugins-git

### Utility this package has for you

Its Natron but its free from  abandonware-related dramas **(python2** + opencolorio1) 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
```
# Issue 2103
opencolorio1 # (dep openfx-arena-git)
libseexpr2 # (dep openfx-io-git) 
openfx-arena-git # (dep natron-git)
openfx-gmic-git # (dep natron-git)
openfx-io-git # (dep natron-git)
openfx-misc-git # (dep natron-git)
natron-compositor-git # (dep natron-git)
natron-git
```

**Comment by Technetium1** [comment]
## Failures:
- [ ] [openfx-arena-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/openfx-arena-git.log)
- [ ] [openfx-gmic-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/openfx-gmic-git.log)
- [ ] [openfx-io-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/openfx-io-git.log)
- [ ] [openfx-misc-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/openfx-misc-git.log)
- [ ] [natron-compositor-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/natron-compositor-git.log)

**Comment by xiota** [comment]
Planning to drop, various issues. Also not updated to Qt6.
