### ISSUE TITLE
[Request] Workbench

### ISSUE THREAD

**Issue by realmazharhussain** [chaotic-aur/packages#2108]
### Link to the package base(s) in the AUR

[workbench](https://aur.archlinux.org/packages/workbench)

### Utility this package has for you

Lets me try out different UI ideas without directly implementing in my app

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Build fails: [workbench.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/workbench.log)

**Comment by realmazharhussain** [comment]
Sorry, I didn't read [packaging](https://github.com/sonnyp/Workbench/tree/a02f8742f9365708e14039bc31cc9c07e2830c5c#packaging) note before. Project's build scripts only support Flatpak builds and non-Flatpak packages are forbidden by the developer.

**Comment by Technetium1** [comment]
@realmazharhussain thank you for the update! That project is `GPLv3`, so frankly that notice has no bearing on what we do. If it builds and functions, we could package and redistribute without concern, as long as it's building from AUR correctly. Never hurts to be considerate though.

**Comment by realmazharhussain** [comment]
The problem is that it doesn't even build. Whoever packaged it for the AUR, wrote some scripts to modify the code which must have allowed it to build initially. But since the upstream developers assume the build environment to be Flatpak and modify the upstream code accordingly, the scripts no longer work and the build fails.

The only way it will work is if someone is willing to check and rewrite scripts/patches on every single release.

**Comment by FabioLolix** [comment]
The pkgbuild have been deleted from the AUR
https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/message/VMAHHCQ6GN66CVLSHUOVMJPCUSMSV2KF/

by the way inxi have been re-imported in the Arch repo https://archlinux.org/packages/community/any/inxi/
