### ISSUE TITLE
[Request] GNOME-related packages.

### ISSUE THREAD

**Issue by erenfro** [chaotic-aur/packages#2109]
### Link to the package base(s) in the AUR

[gnome-shell-extension-arch-update](https://aur.archlinux.org/packages/gnome-shell-extension-arch-update)
[gnome-shell-extension-tiling-assistant-git](https://aur.archlinux.org/packages/gnome-shell-extension-tiling-assistant-git)
[extension-manager](https://aur.archlinux.org/packages/extension-manager)

### Utility this package has for you

arch-update is for checking and reporting, and being able to run garuda-update and a package manager (I use pacseek).
tiling-assistant-git is an extension to improve the already existing tiling in GNOME to incorporate more points to tile to, and keybindings for them as well.
extension-manager is an extension manager that can also download extensions and can be more reliable than using the browser extension in pretty much every way.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

extension-manager-git had previously been requested, but does not seem to be in now. https://github.com/chaotic-aur/packages/issues/1200
I've worked with Igor, the current maintainer of both non-git and git aur packages to fix little problems (dependancy missing that causes chroot build to fail), and he's responded within 24 hours each time to fix it, when emailed directly. Does not always seem to pay attention to comments on packages. So, decent communication and response to fix. 
arch-update and extension-manager I am intending to include in the GNOME edition of Garuda, with a possible optional add-in of tiling-assistant at post-install.

**Comment by Technetium1** [comment]
`extension-manager-git` is broken, will track that in #2086

**Comment by xiota** [comment]
Metrics for anyone interested:

* gnome-shell-extension-arch-update # 27
* gnome-shell-extension-tiling-assistant # 18
* extension-manager # 1119
