### ISSUE TITLE
[Bug] Nekoray

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#2110]
### What happens?

The software is installed correctly.
But the software launcher is not in the list of software and it cannot be run through the terminal.

### What is expected to happen?

The software should have a launcher in the Internet category and display the graphical interface after clicking on it.

### If possible, please attach logs

➜ nekoray
/usr/bin/nekoray: line 3: /home/ali/.local/opt/nekoray/launcher: No such file or directory

**Comment by Technetium1** [comment]
I left a comment for the maintainer to fix here: https://aur.archlinux.org/packages/nekoray#comment-889458

**Comment by ALipAkrohk** [comment]
The launcher problem has not been solved yet, please remove it from your repositories so that its updates can be installed from aur.
