### ISSUE TITLE
[Request] xsudo-git

### ISSUE THREAD

**Issue by robson-66** [chaotic-aur/packages#2115]
### Link to the package base(s) in the AUR

[xsudo-git](https://aur.archlinux.org/packages/xsudo-git)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, it's useful only for me.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by robson-66** [comment]
Thanks

**Comment by xiota** [comment]
Dropping because of minor packaging issues and low usage.  Metrics 10.

Can be replaced with `alias`.
```bash
alias xsudo='pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY'
```
