### ISSUE TITLE
[Request] blackbox-terminal

### ISSUE THREAD

**Issue by ansarimohammed422** [chaotic-aur/packages#2116]
### Link to the package base(s) in the AUR

[com.raggesilver.BlackBox][https://aur.archlinux.org/packages/blackbox-terminal]

### Utility this package has for you

This package is not updated and has been dropped by its maintainer from aur due to removal of a dependency on which it lies on [ vte4-copy-patch-git ] but chaotic aur have this dependency so can you re-maintain it on chaotic aur with more updated version

it is a great gtk terminal and i dont wanno use flatpak version of this
this was my go to terminal-emulator befor the removal of [ vte4-copy-patch-git ]

please can you bring this package back
through chaotic-aur

Thanks in Advance.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Added in https://github.com/chaotic-aur/packages/commit/6705a26156d63574b3ccb8a756bba4bfa306ae24
