### ISSUE TITLE
[Outdated] Bottles last build failed

### ISSUE THREAD

**Issue by EvoXCX** [chaotic-aur/packages#2117]
### If available, link to the latest build

[bottles.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/bottles.log)

### Package name

bottles

### Latest build

2022.11.14

### Latest version available

2022.11.14

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### More information

Maybe vkbasalt-cli need to be in chaotic repository.

**Comment by Technetium1** [comment]
We do indeed have `vkbasalt-cli` already, but it's not building… This is now related to #2086

**Comment by Technetium1** [comment]
`Finished making: vkbasalt-cli 3.0-2 (Fri 18 Nov 2022 05:08:05 AM CET)`

**Comment by Technetium1** [comment]
Thanks for opening this issue!
`Finished making: bottles 2022.11.14-1 (Fri 18 Nov 2022 05:17:10 AM CET)`
