### ISSUE TITLE
[Bug] jellyfin-media-player-git needs a clean build

### ISSUE THREAD

**Issue by bipox** [chaotic-aur/packages#2120]
### What happens?

Hi,

When I launch jellyfinmediaplayer I get this error:  

`jellyfinmediaplayer: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory
`

### What is expected to happen?

I suppose a clean build would fix it?

Thanks for your work!! It is much appreciated

**Comment by Technetium1** [comment]
@bipox Done!
`Finished making: jellyfin-media-player-git r1631.aaa82f1-1.2 (Fri 18 Nov 2022 05:16:38 PM CET)`
