### ISSUE TITLE
[Outdated] firefox-nightly

### ISSUE THREAD

**Issue by VexfulNiko** [chaotic-aur/packages#2123]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/firefox-nightly.log

### Package name

firefox-nightly

### Latest build

109 (master)

### Latest version available

108

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

The PKGBUILD provided by the AUR has been updated multiple times. Please update the PKGBUILD to the latest version, Thank you. https://aur.archlinux.org/packages/firefox-nightly

**Comment by Technetium1** [comment]
We don't actually update PKGBUILD, as we don't use our own copy. It simply needs to be rebuilt. There are currently connection issues causing problems with the final stage of package deployment.

**Comment by Technetium1** [comment]
Log has been updated, it hits an error.

**Comment by VexfulNiko** [comment]
@Technetium1 Are you sure? Heftig (pkgbuild maintainer) has an unofficial repo as well using their PKGBUILD, and it worked fine and it gets updated.

**Comment by Technetium1** [comment]
@VexfulNiko I'm quite sure, the log is right there :P I have no idea how the maintainer builds their packages. All I know is it's a server for Arch TUs: https://pkgbuild.com

**Comment by dr460nf1r3** [comment]
This is actually a known issue with Firefox builds, it can be built by using the following interfere: https://github.com/chaotic-aur/interfere/commit/a823c7733cfd9a4ca1c786d334fcc07e93c93a5f 
I don't know why this happens though.

**Comment by Technetium1** [comment]
I suppose this is complete now, I wonder why that interfere is required :thinking:…
`Finished making: firefox-nightly 109.0a1+20221120.1+h46dae1c56dad-1 (Sun 20 Nov 2022 05:41:21 PM CET)`

**Comment by xiota** [comment]
When I run `pacman -Syu`, I'm getting the following warning:
````
warning: firefox-nightly: local (109.0a1+20221118.1+h859b32ad9584-1) is newer than chaotic-aur (108.0a1+20221125.1+h76c244536f60-1)
````

Anyone know why the version went from 109.0a1 to 108.0a1?  Is it an upstream issue or something else?

**Comment by dr460nf1r3** [comment]
It got updated and shows the correct version now. That being said, the timestamp in your output was valid anyways.
