### ISSUE TITLE
[Question] What is the process for removing packages?

### ISSUE THREAD

**Issue by xiota** [chaotic-aur/packages#2125]
Take nm-tray for instance:

* `network-manager-applet` provides same functionality (though based on GNOME instead of Qt)
* errors when I tried to use it to connect to a network
* marked out of date *and* orphaned
* zero votes on AUR
* no issue here to request it – grandfathered in?

Since there is another package providing the same functionality, it's potentially broken, out of date, orphaned, and has no visible indication of use, would it be a candidate for removal?  But what if there are users who rely on it?  What would the process be for removing it?  Is there any way to find out whether anyone is using it?

Notes:

* I've taken ownership of nm-tray to at least update it for now, but I don't really want to maintain it because nm-applet works better for me.
* After removal, if someone wants it back, they could comment here to complain.
* nm-tray is actively maintained, and someone did mark it out of date.  But don't know if that person uses this repository, or if other users of this repository have any interest in the package.

**Comment by Technetium1** [comment]
- Doesn't really matter if it is from Gnome or something else, the deps it pulls are more relevant.
- If it's not working and nobody is trying to make it work, why provide something known to fail?
- Out of date packages are not usually removed _just because_ they're outdated, we continue to provide the last version that built.
- Orphans can typically be removed, esp if they have been orphaned for a long time.
- Votes don't really matter much, the popularity does. Not everyone votes (though they should imo).
- Not all packages were added by a linked issue, so it can be tricky to find older things sometimes. I use `grep -r pkgname` in the dir that has this repo cloned, works better than GitHub search.
- `would it be a candidate for removal` — Yes, most definitely, given that context
- The removal process consists of removing the pkg from the routine it's in, running `chaotic rm pkgname`, then the Chaotic toolbox archives the last version built, and removes it from the database. It then shows as an orphan when you next use pacman.

---

[network-manager-applet-git](https://aur.archlinux.org/pkgbase/network-manager-applet-git) is maintained by SolarAquarion [Chaotic staff], and it seems actively updated. I can add it to Chaotic if you'd like, we already have the deps in routine.

> Is there any way to find out whether anyone is using it?

Yes… sort of… `nm-tray` is a moderately popular package, thank you for fixing it!
You can see some very basic stats here. Only accurate as of this moment:
![image](https://user-images.githubusercontent.com/9877150/202867610-4e3ff9aa-def8-4b88-93ab-8502acffe8a9.png)

> But don't know if that person uses this repository, or if other users of this repository have any interest in the package

According to those stats, there is indeed interest, around 400 people!


[network-manager-applet-nolibappindicator](https://aur.archlinux.org/packages/network-manager-applet-nolibappindicator) seems popular, might be of interest for you?
![image](https://user-images.githubusercontent.com/9877150/202867629-a543ac82-2cf2-48ad-9645-e07c816e9a15.png)

> After removal, if someone wants it back, they could comment here to complain.

That's generally how it goes :)

Is there anything you would like added?

**Comment by xiota** [comment]
> nm-tray is a moderately popular package, thank you for fixing it!
> According to those stats, there is indeed interest, around 400 people!

You're welcome.  I'll go ahead and maintain it until someone else wants it.

Is there a way to see the stats like that, besides asking here?

> network-manager-applet-nolibappindicator

What's the difference between network-manager-applet-nolibappindicator and network-manager-applet ?

> network-manager-applet-git

I don't need the -git version.  I tend to use -git versions only when there are bug fixes or features I need.

**Comment by Technetium1** [comment]
Glad it has a maintainer now. If you want help, consider pinning a comment that says as much! I forgot to mention that those stats above are for the last 30 days.

> Is there a way to see the stats like that, besides asking here?

We do have metrics, but it's better to ask here if you want to know. There are sometimes reasons that it isn't accurate, and it can't be blindly trusted. It helps to have context of builds and rebuilds that happen, because that can greatly inflate things.

> What's the difference between `network-manager-applet-nolibappindicator` and `network-manager-applet` ?

I think `libappindicator` is Ubuntu/Unity stuff, I don't fully know. I do have [this](https://bugs.archlinux.org/task/51740), [this](https://src.fedoraproject.org/rpms/network-manager-applet/pull-request/1), and most importantly [this active bug](https://bugs.launchpad.net/ubuntu/+source/libappindicator/+bug/1910521).

> I don't need the -git version. I tend to use -git versions only when there are bug fixes or features I need.

Consider that some projects don't release bugfixes or bump their versions in a timely manner. It really depends on the project for me. I like to use `-git` versions of a lot of things because I have the capability/skill to report bugs upstream as they happen without much hassle.
