### ISSUE TITLE
[Request] retrofe

### ISSUE THREAD

**Issue by DrGrizzPHD** [chaotic-aur/packages#2126]
### Link to the package base(s) in the AUR

[retrofe](https://aur.archlinux.org/packages/retrofe)

### Utility this package has for you

emulator frontend

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Sorry, but this depends on `python2` :(
