### ISSUE TITLE
[Bug] Pipewire Packages (FL Mirror)

### ISSUE THREAD

**Issue by VexfulNiko** [chaotic-aur/packages#2127]
### What happens?

Pipewire*-git packages are throwing an error that its file size is too big for the mirror to handle.

### What is expected to happen?

It's expected to download and install.

**Comment by Technetium1** [comment]
It's just `pipewire-common-git`, but that's invalid on all mirrors. Bumping and rebuilding now.

**Comment by Technetium1** [comment]
Done now: `Finished making: pipewire-common-git 0.3.60.r33.gbb558b7d-1.1 (Sat 19 Nov 2022 11:26:19 PM CET)`

![image](https://user-images.githubusercontent.com/9877150/202874022-32e1ee2a-03b0-47fb-83f9-e1141d9f66bb.png)
