### ISSUE TITLE
[Request] cassowary

### ISSUE THREAD

**Issue by zany130** [chaotic-aur/packages#2128]
### Link to the package base(s) in the AUR

[cassowary](https://aur.archlinux.org/packages/cassowary)

### Utility this package has for you

run windows apps in a vm directly from app menu or filemanager

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because AUR package is orphaned.  It is also flagged for functional issues.  Last upstream commit was Dec 2022.  Metrics 8.
