### ISSUE TITLE
[Bug]  eclipse-java  automated build broken getting exceeds size error

### ISSUE THREAD

**Issue by snostormjp** [chaotic-aur/packages#2130]
### What happens?

from all online mirrors:

error: failed retrieving file 'eclipse-java-2:4.25-1.1-x86_64.pkg.tar.zst' from geo-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'eclipse-java-2:4.25-1.1-x86_64.pkg.tar.zst' from cdn-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'eclipse-java-2:4.25-1.1-x86_64.pkg.tar.zst' from cdn-cn-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'eclipse-java-2:4.25-1.1-x86_64.pkg.tar.zst' from au-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'eclipse-java-2:4.25-1.1-x86_64.pkg.tar.zst' from au-2-mirror.chaotic.cx : Maximum file size exceeded

### What is expected to happen?

download and install pkg

### If possible, please attach logs

NA

### More information

previously for other packages it just required a bump to have the pkg rebuild again, manual build and install from aur worked fine for current version.

**Comment by Technetium1** [comment]
Done :)
