### ISSUE TITLE
[Request] tahoma2d

### ISSUE THREAD

**Issue by justaordinaryman** [chaotic-aur/packages#2132]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/tahoma2d

### Utility this package has for you

very little software to create animations on linux this package will be useful for users who want to make animations on linux for free

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping this package because it currently doesn't build, neither does the -git version.
