### ISSUE TITLE
[Request] Sol Client 

### ISSUE THREAD

**Issue by RaptaG** [chaotic-aur/packages#2135]
### Link to the package base(s) in the AUR

[sol-client](https://aur.archlinux.org/packages/sol-client)

### Utility this package has for you

I play Minecraft

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because has packaging issues and upstream project has been discontinued.
