### ISSUE TITLE
[Request] gpick-git

### ISSUE THREAD

**Issue by paperbenni** [chaotic-aur/packages#2136]
### Link to the package base(s) in the AUR

[gpick-git](https://aur.archlinux.org/packages/gpick-git)

### Utility this package has for you

Hands down the best color picker period. 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

The arch build of lua seems incompatible with the build process, there is a comment describing how to fix it but it's tedious and it would really help to have gpick easily available again

**Comment by Technetium1** [comment]
A possible solution was found and posted, the package has been flagged.

**Comment by xiota** [comment]
Closing... Package was last updated 2021.  Maintainer hasn't responded to comments from 2022, 2024.

`extra/gpick` is available.
