### ISSUE TITLE
[Request] profile-sync-daemon-brave

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2138]
### Link to the package base(s) in the AUR

[profile-sync-daemon-brave](https://aur.archlinux.org/packages/profile-sync-daemon-brave)

### Utility this package has for you

It allows to use in PSD (Profile Sync Daemon) also the support for Brave, that currently is used as browser by a lot of users. This package allows to manage the profile folder of Brave in RAM in order to improve the performance of the browser.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because brave support is included in `extra/profile-sync-daemon` in `contrib` folder.
```
$ pacman -Fl profile-sync-daemon | grep brave
profile-sync-daemon usr/share/psd/contrib/brave
```

Metrics 342.
