### ISSUE TITLE
[Request] myman

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2140]
### Link to the package base(s) in the AUR

[myman](https://aur.archlinux.org/packages/myman)

### Utility this package has for you

MyMan is a text-mode videogame inspired by [Namco](http://www.namco.co.jp/)'s Pac-Man. It has been ported to a variety of operating systems using the following for user interaction: ncurses, PDcurses, XCurses, sysV-curses, old BSD curses, old VMS curses, S/Lang slcurses, Win32 console, VMS console, raw stdio and termios, GGI, Allegro, aalib, libcaca, TWin, and Carbon. It produces [plain-text](https://myman.sourceforge.io/snap0000.txt) and [HTML](https://myman.sourceforge.io/snap0000.html) screenshots which may give a reasonable approximation of how it will look in a text terminal.

It is a funny minimal game to have in our Linux environment.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Can't add this as it's severely outdated and not touched in many years. Please get the package to build in clean chroot to re-request.

**Comment by D3vil0p3r** [comment]
> Can't add this as it's severely outdated and not touched in many years. Please get the package to build in clean chroot to re-request.

Hello @Technetium1 Thank you for the answer. I built the package in a clean chroot environment as described [here](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot) and the process ended successfully and I got the package:
![image](https://user-images.githubusercontent.com/83867734/205464211-05d3f4bf-a9d2-4858-bd84-dad4ea496494.png)

I also tested it by installing on an Arch Linux environment and it works.

For re-requesting, I need to open a new Issue Request?

**Comment by Technetium1** [comment]
I will re-confirm in a clean chroot on my end :thinking:

**Comment by Technetium1** [comment]
This fails in a clean chroot for me with the same result as on a builder: [myman.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/myman.log)
```c
installing sprite file /build/myman/pkg/myman/usr/share/myman-0.7.0/spr/ott10.txt
/bin/sh: line 1: makewhatis: command not found
update-whatis: failed to update whatis database
**  you should update the whatis database for /build/myman/pkg/myman/usr/share/man
**  if you would like the `apropos' and `whatis' programs to
**  find myman; if you have the `mandb' and/or `makewhatis'
**  programs, add their directories to your PATH and re-run this command
make[1]: [makefile.cp:3976: update-whatis] Error 1 (ignored)
rm: cannot remove '/build/myman/pkg/myman/usr/share/man/cat6': No such file or directory
==> ERROR: A failure occurred in package().
Aborting...
==> ERROR: Build failed, check /var/lib/aurbuild/x86_64/tech/build
```

**Comment by D3vil0p3r** [comment]
> This fails in a clean chroot for me with the same result as on a builder: [myman.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/myman.log)
> 
> ```c
> installing sprite file /build/myman/pkg/myman/usr/share/myman-0.7.0/spr/ott10.txt
> /bin/sh: line 1: makewhatis: command not found
> update-whatis: failed to update whatis database
> **  you should update the whatis database for /build/myman/pkg/myman/usr/share/man
> **  if you would like the `apropos' and `whatis' programs to
> **  find myman; if you have the `mandb' and/or `makewhatis'
> **  programs, add their directories to your PATH and re-run this command
> make[1]: [makefile.cp:3976: update-whatis] Error 1 (ignored)
> rm: cannot remove '/build/myman/pkg/myman/usr/share/man/cat6': No such file or directory
> ==> ERROR: A failure occurred in package().
> Aborting...
> ==> ERROR: Build failed, check /var/lib/aurbuild/x86_64/tech/build
> ```
`makewhatis: command not found`. It is part of `man` package. You need to install `man` package.

**Comment by Technetium1** [comment]
Yup, that does it @D3vil0p3r, thanks!

```diff
diff --git a/PKGBUILD b/PKGBUILD
index ae9a8f1..03d9683 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -10,7 +10,7 @@ arch=('i686' 'x86_64')
url='http://myman.sourceforge.net/'
license=('BSD')
depends=('ncurses')
-makedepends=('make>=3.80')
+makedepends=('make>=3.80' 'man')
optdepends=('xterm: Launch game with xmyman wrapper'
'rxvt-unicode: Launch game with xmyman2 wrapper'
'kterm: Launch game with xmyman4 wrapper')
```

**Comment by Technetium1** [comment]
I left [a comment on the package](https://aur.archlinux.org/packages/myman#comment-892293) about the missing dep.
