### ISSUE TITLE
[Request] superbfetch-git

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2142]
### Link to the package base(s) in the AUR

[superbfetch-git](https://aur.archlinux.org/packages/superbfetch-git)

### Utility this package has for you

General-purpose fetch displayer that takes user commands output and dynamically changes how it displays output based on the terminal size.
Unlike Neofetch and Pfetch and similar, where on tiled window manager, the terminal is often too small leading to the fetch getting cropped off, by SuperBFetch is possible to solve this issue because it behaves as a dynamic fetching tool. Link: https://github.com/NNBnh/bfetch

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because orphaned.  Last upstream commit was over two years ago.  Metrics 14.
