### ISSUE TITLE
[Request] gnome-shell-extension-appindicator-git

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2143]
### Link to the package base(s) in the AUR

[gnome-shell-extension-appindicator-git](https://aur.archlinux.org/packages/gnome-shell-extension-appindicator-git)

### Utility this package has for you

GNOME extension used for showing indicator icons in the top panel, revealing indicator menus upon click, interacting with the tray icon, compatibility with legacy tray icons. Details: https://github.com/ubuntu/gnome-shell-extension-appindicator

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because `extra/gnome-shell-extension-appindicator` is available.  Currently two commits difference between stable and git versions.  Metrics 45.
