### ISSUE TITLE
[Request] gnome-shell-extension-pop-shell-git

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2146]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/gnome-shell-extension-pop-shell-git

Depends:
https://aur.archlinux.org/pkgbase/pop-launcher-git
https://aur.archlinux.org/packages/pop-shell-shortcuts-git

### Utility this package has for you

Keyboard-driven layer for GNOME Shell which allows for quick and sensible navigation and management of windows.
Details: https://github.com/pop-os/shell

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
This already exists in https://github.com/chaotic-aur/packages/blob/71b0fd2dcdbcfc334c43f62a93017f29d78d75a7/garuda-cluster/hourly.1.txt#L156

**Comment by xiota** [comment]
Switching to this issue for tracking because the request form is filled out.
