### ISSUE TITLE
[Request] g4music, g4music-git

### ISSUE THREAD

**Issue by coxackie** [chaotic-aur/packages#2150]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/g4music
https://aur.archlinux.org/packages/g4music-git

### Utility this package has for you

Neat, lightweight new gtk4 music player

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by coxackie** [comment]
I evidently did not notice that this was already included... many apologies.

**Comment by xiota** [comment]
Dropping `g4music` because AUR package deleted.  The project is rebranding.  However, the new package `aur/gapless` is not properly constructed.  It has a new maintainer who has not yet responded to request for correction.

**Comment by xiota** [comment]
`aur/gapless` has been updated.  Planning to add back under a new request when the rename is reflected across the project (not just the readme).

Metrics:
* g4music 161
* g4music-git 21

**Comment by tio-trom** [comment]
I think the name changed into gapless https://gitlab.gnome.org/neithern/g4music - So I recommend it to be readded as such please https://aur.archlinux.org/packages/gapless

**Comment by xiota** [comment]
The repo is currently down, so cannot check status.  However, last I checked, repo and executable name still referenced "g4music", despite rebranding.  Doesn't make sense to add back under the new name until rebrand is complete (and repo is back in service).
