### ISSUE TITLE
[Bug] chromium-wayland-vaapi needs to be rebuilt against new re2 version

### ISSUE THREAD

**Issue by emanuelserpa** [chaotic-aur/packages#2151]
### What happens?

I get the `/usr/lib/chromium/chromium: error while loading shared libraries: libre2.so.9: cannot open shared object file: No such file or directory` error and Chromium doesn't run.

### What is expected to happen?

Chromium running.

### More information

https://forum.artixlinux.org/index.php/topic,2237.0.html

**Comment by dr460nf1r3** [comment]
The package has been bumped in https://github.com/chaotic-aur/interfere/commit/e7ebe553c3205c9d010af625bc070be7631a97eb and will be built the next time the routine runs.

**Comment by Technetium1** [comment]
`Finished making: chromium-wayland-vaapi 108.0.5359.98-2 (Fri 09 Dec 2022 08:37:43 AM CET)`
