### ISSUE TITLE
[Outdated]  noto-fonts-emoji-flag-git

### ISSUE THREAD

**Issue by jopejoe1** [chaotic-aur/packages#2152]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/noto-fonts-emoji-flag-git.log

### Package name

noto-fonts-emoji-flag-git

### Latest build

2.038.r9.g412b9edf8+1.2.1.r5.g8aa5413-1

### Latest version available

2.038.r9.g412b9edf8+1.2.1.r1.g0f2ae1a-1

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

Changed the git link submodule, and it complains about the current one in use not being a clone of the new one

**Comment by Technetium1** [comment]
`Finished making: noto-fonts-emoji-flag-git 2.038.r9.g412b9edf8+1.2.1.r5.g8aa5413-1 (Fri 09 Dec 2022 02:25:10 AM CET)`
