### ISSUE TITLE
[Request] Add Natron 2.5  coz it builds with python3 

### ISSUE THREAD

**Issue by anomalocaris452** [chaotic-aur/packages#2153]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/natron-compositor 
https://aur.archlinux.org/packages/openfx-arena
https://aur.archlinux.org/packages/openfx-gmic
https://aur.archlinux.org/packages/openfx-io
https://aur.archlinux.org/packages/openfx-misc

### Utility this package has for you

Being literally the best VFX  software (linux(

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Natron 2.5 builds WITH python3  (no python2 drama kek)  

But the OP aint updated it  

BUT  i've updated it on my OBS instances  
https://build.opensuse.org/package/show/home:Area51Kacz:branches:home:ungoogled_chromium:testing/natron-compositor
https://build.opensuse.org/package/show/home:Area51Kacz:branches:home:ungoogled_chromium:testing/openfx-arena
https://build.opensuse.org/package/show/home:Area51Kacz:branches:home:ungoogled_chromium:testing/openfx-gmic
https://build.opensuse.org/package/show/home:Area51Kacz:branches:home:ungoogled_chromium:testing/openfx-io
https://build.opensuse.org/package/show/home:Area51Kacz:branches:home:ungoogled_chromium:testing/openfx-misc

So i beg u  to just clone MY pkgbuilds  and   add natron 2.5   to chaotic aur

**Comment by Technetium1** [comment]
This still requires `python2-pyside` though?

**Comment by anomalocaris452** [comment]
@Technetium1 natron 2.5 now works against https://archlinux.org/packages/extra/x86_64/pyside2/

https://build.opensuse.org/package/view_file/home:Area51Kacz:branches:home:ungoogled_chromium:testing/natron-compositor/PKGBUILD?expand=1

**Comment by anomalocaris452** [comment]
@Technetium1 so we-re (finally) free from python2-related drama

**Comment by Technetium1** [comment]
@anomalocaris452 Is the only change required `pyside2` replacing `python2-pyside` in `depends`?

**Comment by anomalocaris452** [comment]
@Technetium1 literally YES     

thats what i-ve done  (natron-compositor-git  uses this)

And MY pkgbuild added  opencolorio profiles  


So u will only neeeeed to
- change pkgrel to 1 (hehe clean build)
- - remove this from makepends ('gzip' 'p7zip' 'xz' 'zip' 'unzip)  
>it only exists cz obs turns stupid if  u aint install these utilities / but a clean chroot aint gives this drama

**Comment by Technetium1** [comment]
@anomalocaris452 I will make these changes via interfere, thank you! If you have a properly fixed pkgbuild in the future, `git diff` output always helps. The build server you linked above seemed to require account creation to take more than a superficial look at files / changes.

**Comment by Technetium1** [comment]
Related #1084, #1925, #2101, and #2103

**Comment by Technetium1** [comment]
```
# Issue 2153
openfx-arena # (dep natron-compositor)
openfx-gmic # (dep natron-compositor)
openfx-io # (dep natron-compositor)
openfx-misc # (dep natron-compositor)
natron-compositor
```

Existing `dragon-cluster/hourly.txt:`
```
libseexpr2 # (dep openfx-io openfx-io-git)
```

**Comment by Technetium1** [comment]
missing dep `qt4`
```
==> Starting build()...
/home/main-builder/pkgwork/PKGBUILD: line 77: qmake-qt4: command not found
==> ERROR: A failure occurred in build().
Aborting...
```

**Comment by Technetium1** [comment]
`interfere.patch`
```diff
diff --git a/PKGBUILD b/PKGBUILD
index 902ffcd..348b812 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -10,14 +10,15 @@ _SequenceParsing_commit=3c93fcc488632b0bdfeee3181586809932357598
_tinydir_commit=64fb1d4376d7580aa1013fdbacddbbeba67bb085

pkgname=natron-compositor
-pkgver=2.4.4
-pkgrel=1
+pkgver=2.5.0
+pkgrel=4
pkgdesc="Open source compositing software"
arch=('x86_64')
url="https://natrongithub.github.io/"
license=('GPL')
-depends=('boost-libs' 'cairo' 'glfw-x11' 'python2-pyside')
-makedepends=('boost' 'expat' 'openmp')
+depends=('boost-libs' 'cairo' 'glfw' 'pyside2' 'python-qtpy' 'shiboken2')
+makedepends=('boost' 'glfw-x11' 'extra-cmake-modules' 'expat' 'git' 'openmp' 'ninja' 'icu' 'fontconfig' 'gzip' 'p7zip' 'xz' 'zip' 'unzip'
+             'bzip2' 'minizip' 'zlib')
optdepends=('openfx-arena: Extra OpenFX plugins for Natron'
'openfx-gmic: OpenFX wrapper for the GMIC framework'
'openfx-io: Readers/Writers plugins'
@@ -36,9 +37,9 @@ source=("${_pkgname}.tar.gz::${_url}/${_pkgname%-*}/archive/refs/tags/v${pkgver}
"google-test-${_google_test_commit}.tar.gz::${_url}/google-test/archive/${_google_test_commit}.tar.gz"
"SequenceParsing-${_SequenceParsing_commit}.tar.gz::${_url}/SequenceParsing/archive/${_SequenceParsing_commit}.tar.gz"
"tinydir-${_tinydir_commit}.tar.gz::${_url}/tinydir/archive/${_tinydir_commit}.tar.gz")
-sha512sums=('a703f36c01e0a980d53d1e12bf51fc1c819437261319f9a24cfd48e6ec810238c8907ba9a1460455572bbc5a182a343d31d4fb4d5d5658a87e285e1cde541e6f'
-            '39983f693798121342bf6509c819f9243c176c8123e4e2665309270ba3709f686592f9f29b3b938d2c7ce87c756b0ce9ef0ea36c0c96e4d3ba3379bd7f5976be'
-            '1e2c20a2ccc597aec8c69352f2b0533f75afcceda427247346b64752ce0de82631ab89f47ff182c326e12d3fce2efda8ee846d6768cb8cfcb27e3da6e2399e78'
+sha512sums=('SKIP'
+            'SKIP'
+            'SKIP'
'SKIP'
'SKIP'
'SKIP'
@@ -62,40 +63,41 @@ prepare() {

tar -xzf "openfx-${_pkgname}.tar.gz" --strip 1 \
-C   "${_pkgname}/libs/OpenFX/"
+tar -xzf "OpenColorIO-Configs-${_pkgname%-*}-v${pkgver%.*}.tar.gz"

-#  mv "config.pri" \
-#     "${_pkgname}/config.pri"
-  mv "${_pkgname}/build-configs/arch-linux/config.pri" \
-     "${_pkgname}"
}

-build() {
-  cd "${_pkgname}"

-  [[ -d build ]] && rm -r build; mkdir build; cd build
+build() {
+  cd $_pkgname

-  qmake-qt4 -r ../Project.pro \
-               PREFIX=/usr \
-               BUILD_USER_NAME="Arch_Linux" \
-               CONFIG+=custombuild \
-               CONFIG+=openmp \
-               DEFINES+=QT_NO_DEBUG_OUTPUT \
-               QMAKE_CFLAGS_RELEASE="${CFLAGS}" \
-               QMAKE_CXXFLAGS_RELEASE="${CXXFLAGS}" \
-               QMAKE_LFLAGS_RELEASE="${LDFLAGS}"
+  cmake -G Ninja \
+        -B build \
+        -DCMAKE_BUILD_TYPE=Release \
+        -DCMAKE_INSTALL_PREFIX=/usr \
+        -DNATRON_BUILD_TESTS=OFF

-  make
+  ninja -C build/
}

package() {
-  cd "${_pkgname}/build"
-  make INSTALL_ROOT="${pkgdir}" install
-
-  install -d "${pkgdir}/usr/share/Natron/Plugins/"
-  cp -r "../Gui/Resources/PyPlugs" \
-        "${pkgdir}/usr/share/Natron/Plugins/"
-
-  install -d "${pkgdir}/etc/profile.d"
-  echo -e "export FONTCONFIG_PATH=/etc/fonts\n" > "${pkgdir}/etc/profile.d/${pkgname%-*}.sh"
-  echo -e "setenv FONTCONFIG_PATH /etc/fonts\n" > "${pkgdir}/etc/profile.d/${pkgname%-*}.csh"
+  cd $_pkgname
+
+  DESTDIR="$pkgdir" ninja -C build/ install
+
+  install -d "$pkgdir/usr/share/Natron/Plugins/"
+  cp -r "Gui/Resources/PyPlugs" \
+        "$pkgdir/usr/share/Natron/Plugins/"
+
+  install -d "$pkgdir/usr/share/mime/application/"
+  mv "$pkgdir/usr/share/mime/x-natron.xml" \
+     "$pkgdir/usr/share/mime/application/"
+
+     #tar  –xzf "$srcdir/OpenColorIO-Configs-Natron-v2.5.tar.gz"
+     cp -R "$srcdir/OpenColorIO-Configs-Natron-v2.5/" "$pkgdir/usr/share/OpenColorIO-Configs/"
+
+
+  install -d "$pkgdir/etc/profile.d"
+  echo -e "export FONTCONFIG_PATH=/etc/fonts\n" > "$pkgdir/etc/profile.d/$_pkgname.sh"
+  echo -e "setenv FONTCONFIG_PATH /etc/fonts\n" > "$pkgdir/etc/profile.d/$_pkgname.csh"
}
```

**Comment by Technetium1** [comment]
My patch is malformed, and I'm not sure why yet...

**Comment by anomalocaris452** [comment]
@Technetium1 does my  pkgbuild give problems?

it works well even under obs conditions  (NO internet access  +  add gzip+friends as makedepends to avoid errors)

**Comment by Technetium1** [comment]
@anomalocaris452 it does yes. I can't apply the patch for unknown reasons. It seems the maintainer finally got around to updating, let's try that... https://aur.archlinux.org/cgit/aur.git/commit/?h=natron-compositor&id=ff4a0aae9b8f0165df21c23e61e79d9d6bb2a502

**Comment by Technetium1** [comment]
`Finished making: natron-compositor 2.5.0-1 (Sat 17 Dec 2022 11:06:48 PM CET)`

**Comment by dr460nf1r3** [comment]
Very cool! :)

**Comment by xiota** [comment]
Dropping `natron-compositor` and associated packages because they're not building.  Adding `natron-git`, et al, instead. (#2103)
