### ISSUE TITLE
[Outdated]  Nheko-git 0.10.2

### ISSUE THREAD

**Issue by Sazu-bit** [chaotic-aur/packages#2154]
### If available, link to the latest build

Needs to be rebuilt. Shared dependency was unceremoniously downgraded.

https://github.com/Nheko-Reborn/nheko
nheko-git 0.10.2.r155.g40a7d58c-1

### Package name

nheko-git

### Latest build

Unknown

### Latest version available

Unknown

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by dr460nf1r3** [comment]
Done!
