### ISSUE TITLE
[Remove] cinelerra-gg-git

### ISSUE THREAD

**Issue by anomalocaris452** [chaotic-aur/packages#2156]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/cinelerra-gg
https://aur.archlinux.org/packages/cinelerra-gg-git

### Utility this package has for you

The best linux video editor >)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

'm building it without any drama on my obs instance https://build.opensuse.org/package/show/home:Area51Kacz:branches:home:ungoogled_chromium:testing/cinelerra

i-ve even enabled  cinelerra  opencv plugins 

[ANd it workson a clean chroot](https://build.opensuse.org/package/show/home:Area51Kacz:branches:home:ungoogled_chromium:testing/cinelerra)

**Comment by xiota** [comment]
Hasn't been buildable because the upstream repo is offline.  Will wait a while to see if it returns.

Normally not recommended, but can get program to run by editing the binary:

```
_libs=(
  libIex-3_3.so.32::libIex.so
  libIlmThread-3_3.so.32::libIlmThread.so
  libImath-3_1.so.29::libImath.so
  libvpx.so.9::libvpx.so
)

for i in "${_libs[@]}"; do
  sudo patchelf --replace-needed "${i%%::*}" "${i##*::}" /usr/bin/cinelerra-gg
done
```

Metrics 11.

**Comment by xiota** [comment]
Dropped because depends on EOL GTK2.  Metrics 19.

Note: Upstream sources are still unavailable.
