### ISSUE TITLE
[Request]  Lightzone

### ISSUE THREAD

**Issue by anomalocaris452** [chaotic-aur/packages#2157]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/lightzone
https://aur.archlinux.org/packages/lightzone-git

### Utility this package has for you

Open-source professional-level digital darkroom software
--

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by anomalocaris452** [comment]
their  only aur dependency its
https://aur.archlinux.org/packages/javahelp2

**Comment by Technetium1** [comment]
[lightzone-git](https://aur.archlinux.org/packages/lightzone-git) is severely outdated and seems to be only updated due to the work done at https://github.com/ktgw0316/LightZone.

**Comment by xiota** [comment]
Dropped because broken for a long time.  Have tried to fix multiple times.  Giving up.
