### ISSUE TITLE
[Request] disneyplus

### ISSUE THREAD

**Issue by RaptaG** [chaotic-aur/packages#2158]
### Link to the package base(s) in the AUR

[disneyplus](https://aur.archlinux.org/packages/disneyplus)

### Utility this package has for you

I have a Disney+ subscription and I wanna use an application for it, not the website.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
This application is quite literally loading the website in a browser… :thinking:
https://gitlab.com/disneyplusdesktop/application/-/blob/main/main.js#L34
We can of course add it anyway

**Comment by xiota** [comment]
Dropping because:

* Depends on custom electron package with some defects, including using `pkgrel` in download link. Cannot be built without modification after bump for `icu` update.
* Not significantly different from running `electron https://www.disneyplus.com/identity/login`
