### ISSUE TITLE
[Request] synfigstudio-dev

### ISSUE THREAD

**Issue by anomalocaris452** [chaotic-aur/packages#2161]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/synfig-dev
https://aur.archlinux.org/packages/etl-dev
https://aur.archlinux.org/packages/synfigstudio-dev

### Utility this package has for you

The best linux animation software

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

arch has synfig 1.4
this is synfig 1.5

**Comment by Technetium1** [comment]
`etl-dev` failed due to a missing dep, left [a comment](https://aur.archlinux.org/packages/etl-dev#comment-893409) for the maintainer to fix.
[etl-dev.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/etl-dev.log)

**Comment by Technetium1** [comment]
`synfig-dev` fails to build due to missing dep: [synfig-dev.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/synfig-dev.log)

```
*** No intltoolize found, please install the intltool package ***```

**Comment by xiota** [comment]
Dropping because `synfig-dev` fails to build.  (Consequently, cannot build `synfigstudio-dev`.)  Metrics 2, for both.
```
./configure: line 22499: syntax error near unexpected token `;;'
./configure: line 22499: `               ;;'
==> ERROR: A failure occurred in build().
```
