### ISSUE TITLE
[Bug] code-marketplace maximum file size exceeded

### ISSUE THREAD

**Issue by Thadah** [chaotic-aur/packages#2163]
### What happens?

error: failed retrieving file 'code-marketplace-1.73.0-1.1-any.pkg.tar.zst' from es-mirror.chaotic.cx : Maximum file size exceeded

### What is expected to happen?

Update completes successfully

### If possible, please attach logs

:: Instalazioarekin jarraitu? [B/e] 
:: Paketeak eskuratzen...
 no se pudo descargar code-marketplace-1.73.0-1.1-any.pkg.tar.zst
errorea:huts egin du 'code-marketplace-1.73.0-1.1-any.pkg.tar.zst' fitxategia 'es-mirror.chaotic.cx'-tik erauzteak: Maximum file size exceeded
errorea:huts egin du 'code-marketplace-1.73.0-1.1-any.pkg.tar.zst' fitxategia 'es-2-mirror.chaotic.cx'-tik erauzteak: Maximum file size exceeded
errorea:huts egin du 'code-marketplace-1.73.0-1.1-any.pkg.tar.zst' fitxategia 'de-mirror.chaotic.cx'-tik erauzteak: Maximum file size exceeded
errorea:huts egin du 'code-marketplace-1.73.0-1.1-any.pkg.tar.zst' fitxategia 'de-2-mirror.chaotic.cx'-tik erauzteak: Maximum file size exceeded
errorea:huts egin du 'code-marketplace-1.73.0-1.1-any.pkg.tar.zst' fitxategia 'de-3-mirror.chaotic.cx'-tik erauzteak: Maximum file size exceeded
errorea:huts egin du 'code-marketplace-1.73.0-1.1-any.pkg.tar.zst' fitxategia 'de-4-mirror.chaotic.cx'-tik erauzteak: Maximum file size exceeded
errorea:huts egin du 'code-marketplace-1.73.0-1.1-any.pkg.tar.zst' fitxategia 'fr-mirror.chaotic.cx'-tik erauzteak: Maximum file size exceeded
oharra:fitxategi batzuk eskuratzeak huts egin du
errorea:transakzioa burutzean huts egin du (errorea liburutegia deskargatzean)
Erroreak gertatu dira, ez da paketerik bertsio berritu.
 -> errorea biltegitako paketeak instalatzerakoan

**Comment by Technetium1** [comment]
`Finished making: code-marketplace 1.73.0-1.2 (Tue 13 Dec 2022 03:11:53 PM CET)`
