### ISSUE TITLE
[Request] whatever

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2164]
### Link to the package base(s) in the AUR

[whatever](https://aur.archlinux.org/packages/whatever)

### Utility this package has for you

Whatever is a lightweight unofficial Evernote© client for Linux desktop.

Whereas Evernote Corporation still doesn't support Linux platform, there's a need to piece it out. Using a web version can not always be comfortable, therefore there's nothing that can be more useful than a desktop client.

Source: https://github.com/sbrshk/whatever

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
This appears to no longer work? https://github.com/sbrshk/whatever/issues/36

**Comment by D3vil0p3r** [comment]
> This appears to no longer work? [sbrshk/whatever#36](https://github.com/sbrshk/whatever/issues/36) & [sbrshk/whatever#34](https://github.com/sbrshk/whatever/issues/34) & [sbrshk/whatever#33](https://github.com/sbrshk/whatever/issues/33)

Ok... At this point I close it as unplanned, because it seems that GitHub repo is dead.
