### ISSUE TITLE
[Request] raze - a Build Engine source port.

### ISSUE THREAD

**Issue by yum13241** [chaotic-aur/packages#2166]
### Link to the package base(s) in the AUR

[Raze](https://aur.archlinux.org/pkgbase/raze)

### Utility this package has for you

Raze is a Build engine source port that allows you to play basically every Build engine game in existence.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Raze uses ZMusic.

**Comment by Technetium1** [comment]
Please avoid `code` in titles, it makes GitHub's search behave badly, even though it shouldn't.
