### ISSUE TITLE
[Request] joplin-appimage

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2167]
### Link to the package base(s) in the AUR

[joplin-appimage](https://aur.archlinux.org/packages/joplin-appimage)

### Utility this package has for you

Joplin is a free, open source note-taking and to-do application, which can handle a large number of notes organised into notebooks. The notes are searchable, can be copied, tagged and modified either from the applications directly or from your own text editor.
It is one of the most used note-taking apps.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Source: https://github.com/laurent22/joplin

In AUR, joplin has several different packages. The declared stable package is this one on this request as stated in the comment in its AUR page:
```
thynkon commented on https://aur.archlinux.org/packages/joplin-appimage#comment-813169
Attention

From now, this package will only track https://github.com/laurent22/joplin/releases/latest of Joplin.
```
Tested in Arch Linux. It worked as expected:
![image](https://user-images.githubusercontent.com/83867734/207637884-12e6c7e1-947a-49e4-9a7f-44f8af30ef07.png)

**Comment by Technetium1** [comment]
This is already satisfied by https://github.com/chaotic-aur/packages/issues/2160. It's only an appimage while the other packages are outdated and/or requiring python2.

The non-beta will not be added, since important security updates don't beget a new stable release, even for more than a month! https://github.com/laurent22/joplin/releases

**Comment by D3vil0p3r** [comment]
> This is already satisfied by #2160. It's only an appimage while the other packages are outdated and/or requiring python2.
> 
> The non-beta will not be added, since important security updates don't beget a new stable release, even for more than a month! https://github.com/laurent22/joplin/releases

Since joplin-beta-appimage was considered a temporary package, what will be the "stable" pkg that will replace it?

**Comment by Technetium1** [comment]
> Since joplin-beta-appimage was considered a temporary package, what will be the "stable" pkg that will replace it?

That will be decided as packages are updated, but the hope is to get a native build rather than Appimage. We ***cannot*** add any of them that still require Python2.

> joplin-appimage is not a "pre-release" version. It is 2.8.8 that has been released on May 2022.

This is exactly the problem! Look at how many releases happen between stable tags! For example, this XSS fix has been in prereleases for a whole month https://github.com/laurent22/joplin/commit/762b4e88f888ce104584293c10ac5d9ea21ad6de

**Comment by D3vil0p3r** [comment]
> > Is joplin-beta-appimage requiring Python2?
> 
> Unfortunately [eda5ade](https://github.com/chaotic-aur/packages/commit/eda5ade30bc15862f88d37049270a586485b7bca)

I just installed `joplin-beta-appimage` and uninstalled Python2 and its dependencies from my system by `sudo pacman -Rcns python2` and running Joplin seems to work correctly.

**Comment by D3vil0p3r** [comment]
> @D3vil0p3r sorry I misread that quote above! All the **_non-appimage_** versions require python2 to compile, but **_not_** the appimages!

So the best scenario is to have a native build not more dependent on Python2... <3 Let's hope
