### ISSUE TITLE
[Outdated] heroic-games-launcher-bin

### ISSUE THREAD

**Issue by RokkuCode** [chaotic-aur/packages#2168]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/heroic-games-launcher-bin.log

### Package name

heroic-games-launcher-bin

### Latest build

2.5.1-2

### Latest version available

2.5.2 HOTFIX #2

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases

**Comment by Technetium1** [comment]
`Finished making: heroic-games-launcher-bin 2.5.2-1 (Wed 14 Dec 2022 06:12:40 PM CET)`
