### ISSUE TITLE
[Request] woof-doom, woof-git, & dsda-doom.

### ISSUE THREAD

**Issue by yum13241** [chaotic-aur/packages#2172]
### Link to the package base(s) in the AUR

[Woof!](https://aur.archlinux.org/pkgbase/woof-doom)
[Woof! Git.](https://aur.archlinux.org/pkgbase/woof-git)
[DSDA-Doom](https://aur.archlinux.org/pkgbase/dsda-doom)

### Utility this package has for you

Woof is a continuation of Lee Killough's MBF port.

DSDA-Doom is a fork of PrBoom+ for speedrunning. PrBoom+ is in maintenance mode.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

First checkbox only applies to `woof-git`.

I know I've been requesting a lot of Doom stuff lately, someone that isn't me will appreciate this too.

**Comment by Technetium1** [comment]
`woof-git` is failing due to missing python: [woof-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/woof-git.log)
I left [a comment](https://aur.archlinux.org/packages/woof-git#comment-893923) for the maintainer.
