### ISSUE TITLE
[Remove] shattered-pixel-dungeon-git

### ISSUE THREAD

**Issue by magnus-ISU** [chaotic-aur/packages#2174]
### Link to the package base(s) in the AUR

[shattered-pixel-dungeon-git](https://aur.archlinux.org/packages/shattered-pixel-dungeon-git)

### Utility this package has for you

This is one of the best roguelike games and it is free and open source!

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

[Here is github repo, as AUR upstream repo is a couple steps removed](https://github.com/00-Evan/shattered-pixel-dungeon)

**Comment by xiota** [comment]
Needs interfere to downgrade jdk version.

**Comment by xiota** [comment]
Dropping because maintainer opened deletion request.  Upstream development process doesn't seem to work well for `-git` packages.
