### ISSUE TITLE
[Request] kodi-nexus-git

### ISSUE THREAD

**Issue by cg00001** [chaotic-aur/packages#2175]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/kodi-nexus-git

### Utility this package has for you

Takes too long to build  from sources and binaries are big help for both slow and fast PCs.
kodi-git used to provide Kodi Nexus but changes in master git made it build Kodi 21 -which might be useful in a year or so.
Kodi-nexus-git will also provide stable Kodi Nexus once it's out in January.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Build failing: [kodi-nexus-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/kodi-nexus-git.log)

**Comment by Technetium1** [comment]
Looks like it was temporary. Such is the nature of `-git` packages :)

**Comment by cg00001** [comment]
Thank you.
