### ISSUE TITLE
[Request] fancytasks

### ISSUE THREAD

**Issue by zany130** [chaotic-aur/packages#2176]
### Link to the package base(s) in the AUR

[Fancy Tasks](https://aur.archlinux.org/packages/fancytasks)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

[build log](https://gist.github.com/zany130/043e0302b9fb733c301e43fddaa49a52)

**Comment by xiota** [comment]
Dropping because disguised -git package.  Also, not updated for Qt6.  Metrics 41.
