### ISSUE TITLE
[Request] lokinet

### ISSUE THREAD

**Issue by anomalocaris452** [chaotic-aur/packages#2178]
### Link to the package base(s) in the AUR

[lokinet](https://aur.archlinux.org/packages/lokinet)

### Utility this package has for you

darknet service as freenet/i2p

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
#2086

**Comment by Technetium1** [comment]
Build failing: [lokinet.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/lokinet.log)
Working in a clean chroot on my machine though :thinking:
