### ISSUE TITLE
[Request] xmind

### ISSUE THREAD

**Issue by anomalocaris452** [chaotic-aur/packages#2182]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/xmind/

### Utility this package has for you

Brainstorming and mind mapping application. It provides a rich set of different visualization styles, and allows sharing of created mind maps via their website

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by FabioLolix** [comment]
```
Does the package's license allow redistributing it?

YES!
```

Where do you see that is redestributable? The package don't have a license for xmind code, only the standard electron and chromium licenses are included

**Comment by Technetium1** [comment]
https://xmind.app/terms
> You agree not to distribute in any medium any part of the Site without Xmind’s prior written authorization.

This is a proprietary paid software with no free usecase, and it also seems to be an electron app which suggests a large size. I'm not sure that this fits here. If it turns out this is a small binary, and you can get permission to redistribute, we can come back to this.
