### ISSUE TITLE
[Request] yed

### ISSUE THREAD

**Issue by anomalocaris452** [chaotic-aur/packages#2183]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/yed/

### Utility this package has for you

Very powerful graph editor written in java

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by FabioLolix** [comment]
```
Does the package's license allow redistributing it?

YES!
```

The package license explicity forbid redistribution


```
6. DISTRIBUTION

No distribution is to be made of the Software by the Licensee.
```

**Comment by Technetium1** [comment]
So says the license https://www.yworks.com/company/legal/terms-of-use
