### ISSUE TITLE
[Request] ffdiaporama

### ISSUE THREAD

**Issue by anomalocaris452** [chaotic-aur/packages#2184]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/ffdiaporama

https://aur.archlinux.org/packages/ffdiaporama-texturemate
https://aur.archlinux.org/packages/ffdiaporama-openclipart

### Utility this package has for you

a cute movie-maker like program

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by FabioLolix** [comment]
ffdiaporama use ffmpeg 2.1

**Comment by Technetium1** [comment]
Source is now unavailable and it also depends on Qt5, so this will not be added. See #3157
