### ISSUE TITLE
[Request] meowsql

### ISSUE THREAD

**Issue by ProfP30** [chaotic-aur/packages#2188]
### Link to the package base(s) in the AUR

[meowsql](https://aur.archlinux.org/packages/meowsql)

### Utility this package has for you

meosql is an attempt to port a very useful GUI database client HeidiSQL to C++/Qt

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Considering drop for maintenance practice and low usage.  Metrics 7.

Package clones to folder using pkgver and pkgrel, which results in unnecessary recloning and breaks build on chaotic servers.  Maintainer was asked to fix about a year ago, but ignored message.
