### ISSUE TITLE
[Request] linux-nitrous-fire

### ISSUE THREAD

**Issue by abdurehman4** [chaotic-aur/packages#2189]
### Link to the package base(s) in the AUR

[linux-nitrous-fire](https://aur.archlinux.org/packages/linux-nitrous-fire)

### Utility this package has for you

Linux Nitrous Fire is a fork Kernel of Linux Nitrous focused on performance than security and patches from the Clear Linux.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Lzop is required for building this kernel.

**Comment by xiota** [comment]
Dropping because tracking EOL kernel 6.2.
