### ISSUE TITLE
[Request] Remove flycast-git

### ISSUE THREAD

**Issue by xiota** [chaotic-aur/packages#2190]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/flycast-git
https://aur.archlinux.org/packages/flycast

### Utility this package has for you

reicast is no longer developed/maintained.  flycast is a fork of reicast that is still developed/maintained.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few. (whoever is using reicast)

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
In case it helps, here is a link to the [reicast github](https://github.com/reicast/reicast-emulator).  The readme now states:

> **Project EOL**
>
> Hey there,
>
> This project is no longer active.
>
> Please, use another Dreamcast Emulator that is activelly developed :)
>
> Cheers, ~skmp

**Comment by xiota** [comment]
I just created a `flycast` package, in case people would prefer a non-git version.  https://aur.archlinux.org/packages/flycast

**Comment by dr460nf1r3** [comment]
Oh that's even better for people not seeking for development builds! Adding soonish :)

**Comment by xiota** [comment]
I requested the -git version earlier only because a normal release package didn't exist before.

**Comment by xiota** [comment]
Request to remove `flycast-git`.  The normal version is sufficient.  Also, the package needs to be updated, but the maintainer appears to be unresponsive.

**Comment by xiota** [comment]
Just to clarify... please keep `flycast`.

**Comment by dr460nf1r3** [comment]
Yeah, I understood it this way as well. Np!

**Comment by xiota** [comment]
Adding back `flycast-git` with interfere because there have been 420 commits since the last release.
