### ISSUE TITLE
[Outdated] mesa-tkg-git and lib32-mesa-tkg-git

### ISSUE THREAD

**Issue by raziel100** [chaotic-aur/packages#2192]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/mesa-tkg-git.log

### Package name

mesa-tkg-git and lib32-mesa-tkg-git

### Latest build

mesa-tkg-git-23.0.0_devel.164253.e4e4ba23047-1-x86_64.pkg.tar.zst

### Latest version available

Latest from git

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### More information

Mesa-tkg is too old, and is failing do build, the least successful one was day 14

**Comment by dr460nf1r3** [comment]
Am I missing something? I don't see the failure in the logfile :eyes:

```

==> Updated version: mesa-tkg-git 23.0.0_devel.164253.e4e4ba23047-1
==> ERROR: The package group has already been built. (use -f to overwrite)
```

**Comment by raziel100** [comment]
> Am I missing something? I don't see the failure in the logfile 👀
> 
> ```
> ==> Updated version: mesa-tkg-git 23.0.0_devel.164253.e4e4ba23047-1
> ==> ERROR: The package group has already been built. (use -f to overwrite)
> ```

He is trying to build the same build from day 14 every day, so something is wrong

**Comment by Technetium1** [comment]
I'm not sure what I'm missing here. We're not changing the version that should be building at all... https://github.com/chaotic-aur/interfere/tree/master/mesa-tkg-git

**Comment by dr460nf1r3** [comment]
Looking at this, it might be better to post this to the PKGBUILDS repository. As @Technetium1 there is nothing we change concerning package versions 🤔 though we might keep this open and link the corresponding issue.

**Comment by raziel100** [comment]
Well. I have opened here because @PedroHLC have asked me to do here

**Comment by PedroHLC** [comment]
@raziel100 @Technetium1 @dr460nf1r3 so, there is something wrong with Mesa's mirroring here in GitHub, it's 10 days behind the GitLab counterpart.

**Comment by dr460nf1r3** [comment]
I have started the build, so it should be available soon. Thanks @PedroHLC ! :)
