### ISSUE TITLE
[Request] looking-glass-git

### ISSUE THREAD

**Issue by sylviiu** [chaotic-aur/packages#2195]
### Link to the package base(s) in the AUR

[looking-glass-git](https://aur.archlinux.org/packages/looking-glass-git)

### Utility this package has for you

Tool that provides low-latency KVM FrameRelay (essentially allowing users who run virtual machines with gpu passthrough to control & play games through virtual machine through the linux host without an actual kvm switch)

![image](https://user-images.githubusercontent.com/95180094/209316145-eb6bfea7-3ddd-4be6-9360-927c82d629a0.png)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

There is a [non-git version](https://aur.archlinux.org/packages/looking-glass) of looking-glass, but [it currently has issues with mesa 22.3+](https://gitlab.freedesktop.org/mesa/mesa/-/issues/7929) and has yet to be updated in the AUR. If possible could both be added?

**Comment by xiota** [comment]
Interfere added to build with `-march=x86-64-v2` instead of `-march=native`.  Metrics 42.

**Comment by xiota** [comment]
Fails to build because of outdated patch.  AUR maintainer notified.  Metrics 66.
