### ISSUE TITLE
[Request] jpeg-recompress-git

### ISSUE THREAD

**Issue by xiota** [chaotic-aur/packages#2198]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/jpeg-recompress-git
https://aur.archlinux.org/packages/libsmallfry-git
https://aur.archlinux.org/packages/libiqa-git

### Utility this package has for you

Reduces JPEG file size while retaining high-quality appearance.  Useful to reduce bandwidth when transferring images.  This is a fork of jpeg-archive with fixes and webp support.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

For `libiqa-git` and `libsmallfry-git`: `extra-x86_64-build`.

For `jpeg-recompress-git`:
````
extra-x86_64-build -- -I libiqa-git-1.1.2.1.r1.g5441721-1-x86_64.pkg.tar.zst -I libsmallfry-git-0.1.2.r0.ge6d4939-1-x86_64.pkg.tar.zst
````

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Also need to add dependencies: libsmallfry-git and libiqa-git.

**Comment by dr460nf1r3** [comment]
The package itself seems to depend on the non-git parts,

**Comment by xiota** [comment]
Non-git versions of the packages don't exist.  The git packages provide them.

**Comment by dr460nf1r3** [comment]
Fair enough, thanks!

**Comment by xiota** [comment]
Since jpeg-recompress-git is currently the only package that depends on libsmallfry and libiqa, I suppose it could be modified to build/include them.

**Comment by Technetium1** [comment]
@xiota I guess they should be built separately if they have an application outside of `jpeg-recompress-git`, otherwise the only reason to have them separated would be to make maintaining them easier.

**Comment by xiota** [comment]
I would like to keep the packages separate.  As you note, maintaining them separately would be easier.  They appear to be updated independently of each other, and combining them would making keeping track of versions and rebuilds more complicated.

**Comment by Technetium1** [comment]
@xiota `jpeg-recompress-git` is failing: [jpeg-recompress-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/jpeg-recompress-git.log)

**Comment by xiota** [comment]
Thanks for letting me know.  There was a missing dependency.  It's fixed now.
