### ISSUE TITLE
[Request] anki-official-binary-bundle

### ISSUE THREAD

**Issue by AriaMoradi** [chaotic-aur/packages#2201]
### Link to the package base(s) in the AUR

[anki-official-binary-bundle](https://aur.archlinux.org/packages/anki-official-binary-bundle)

### Utility this package has for you

This package, re-packages the official binary from anki. The aur [anki](https://aur.archlinux.org/packages/anki) packages has build issues every other anki release. Using this package removes the need to compile anki. 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Anki was originally added in #960

**Comment by Technetium1** [comment]
These seem to be built by the people at the GitHub repository, not by CI? Not sure how I feel about that.
