### ISSUE TITLE
[Request] Godot Export Templates

### ISSUE THREAD

**Issue by Pakrohk** [chaotic-aur/packages#2202]
### Link to the package base(s) in the AUR

[AUR](https://aur.archlinux.org/packages/godot-export-templates-git)

### Utility this package has for you

Godot export templates

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by dr460nf1r3** [comment]
Welp, too early. The git repo apparently times out while cloning.

**Comment by Technetium1** [comment]
That fixes the timeout issue, but it still fails to build: [godot-export-templates-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/godot-export-templates-git.log)

**Comment by Technetium1** [comment]
AUR maintainer needs to fix build target, or else someone needs to say how to do it, so it can be altered via interfere.

**Comment by xiota** [comment]
Dropping because export templates are now included with `aur/godot-git`.  Metrics 116.
