### ISSUE TITLE
[Bug] qbittorrent-git

### ISSUE THREAD

**Issue by SimPilotAdamT** [chaotic-aur/packages#2205]
### What happens?

QBitTorrent as installed from the Chaotic AUR Pacman repo fails to launch, returnign the following error to the SystemD journal:
```bash
qbittorrent: symbol lookup error: qbittorrent: undefined symbol:_ZN11QBasicMutex15destroyInternalEP13QMutexPrivate, version Qt_6
```

### What is expected to happen?

QBitTorrent is supposed to actually launch, as it does when locally built (at least on my own system)

**Comment by dr460nf1r3** [comment]
The package has been rebuilt, please check if it works now :)

**Comment by SimPilotAdamT** [comment]
Nope, same issue. Still gets fixed if I rebuild it locally, though...

**Comment by SimPilotAdamT** [comment]
Nope, same issue. Still gets fixed if I rebuild it locally, though...

**Comment by dr460nf1r3** [comment]
Now that's really strange. Thanks for the feedback :eyes:

**Comment by Technetium1** [comment]
Nobody has complained about this, so I'm assuming it's solved.
