### ISSUE TITLE
[Request] pacman-static

### ISSUE THREAD

**Issue by Samisafool** [chaotic-aur/packages#2207]
### Link to the package base(s) in the AUR

[pacman-static](https://aur.archlinux.org/packages/pacman-static)

### Utility this package has for you

It has saved my ass a few times.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

The guy maintaining it runs his own repo, 
![image](https://user-images.githubusercontent.com/59611020/209751369-c61804a0-a906-47e9-b334-22f929985748.png)

And he's an Arch dev so he's trustworthy.

**Comment by xiota** [comment]
Is this package still needed?

v4 build (`shfmt`) chokes on PKGBUILD:
```
PKGBUILD:59:65: invalid UTF-8 encoding
```
