### ISSUE TITLE
[Request] nessus

### ISSUE THREAD

**Issue by DF001** [chaotic-aur/packages#2210]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/nessus

### Utility this package has for you

important tool for pentesters 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by DF001** [comment]
please close it here. Going to request blackarch to add nessus

**Comment by dr460nf1r3** [comment]
As you wish! :)
