### ISSUE TITLE
[Request] fatrat-git

### ISSUE THREAD

**Issue by anomalocaris452** [chaotic-aur/packages#2215]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/fatrat-git/

### Utility this package has for you

a good download manager

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

FatRat — Qt based download manager with support for HTTP, FTP, SFTP, BitTorrent and Metalink.

**Comment by Technetium1** [comment]
Build fails: [fatrat-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/fatrat-git.log)

**Comment by xiota** [comment]
@anomalocaris452 How did you build this?  I'm unable to build in a clean chroot and unable to figure out how to fix the PKGBUILD.

@Technetium1 I'm getting a 404 on fatrat-git.log

**Comment by dr460nf1r3** [comment]
This does indeed seem like a source code issue.

**Comment by xiota** [comment]
Dropping because not updated for Qt6.  PR to add Qt6 support was ignored for two years. Metrics 7.
