### ISSUE TITLE
[Remove] remarkable

### ISSUE THREAD

**Issue by anomalocaris452** [chaotic-aur/packages#2221]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/remarkable

### Utility this package has for you

Description: | A free fully featured markdown editor for Linux.
-- | --

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping this because it depends on a cluster of broken packages that I'm not interested in fixing.

Related #3157.
