### ISSUE TITLE
[Request] vscodium-electron

### ISSUE THREAD

**Issue by coxackie** [chaotic-aur/packages#2223]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/vscodium-electron

### Utility this package has for you

VSCodium build using already existing electron package. Follows the Arch philosophy.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by dr460nf1r3** [comment]
Now that's an interesting one!

**Comment by Technetium1** [comment]
Build failing: [vscodium-electron.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/vscodium-electron.log)

**Comment by REmerald** [comment]
@Technetium1 , build fine on my system, didn't try in the clean chroot though...

Btw, the log is no longer accessible, maybe try again?

**Comment by dr460nf1r3** [comment]
```
error An unexpected error occurred: "/home/main-builder/pkgwork/src/vscode/package.json: Unexpected end of JSO
N input".
```

**Comment by REmerald** [comment]
I figured it out, the problem is missing `jq` package in the `makedepends`. Gives the same error if I `pacman -Rdd jq`.

[I asked the package maintainer to fix it.](https://aur.archlinux.org/packages/vscodium-electron#comment-902648)  
Ones he does it, we can try again.

**Comment by coxackie** [comment]
@Technetium1 could you in the meantime alter the PKGBUILD to include `jq` to see if everything works ok?

**Comment by dr460nf1r3** [comment]
On it already. Build is in progress!

**Comment by dr460nf1r3** [comment]
It succeeded btw :) gotta add to the routine still.

**Comment by coxackie** [comment]
Should we close this then? I already see the package in `chaotic-aur` repo.

**Comment by dr460nf1r3** [comment]
Now we can ;)
