### ISSUE TITLE
[Request] agg-2.6-git

### ISSUE THREAD

**Issue by caniko** [chaotic-aur/packages#2224]
### Link to the package base(s) in the AUR

[agg-2.6-git](https://aur.archlinux.org/packages/agg-2.6-git)

### Utility this package has for you

I use it for matplotlib backend on Python

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

The source is BSD licensed

**Comment by xiota** [comment]
@caniko Do you still need this package for matplotlib?  It is failing to build, and I would rather drop than fix if it's not needed.

**Comment by caniko** [comment]
I don't use chaotic aur anymore

**Comment by xiota** [comment]
@caniko Thanks for letting me know.  Will drop package because failing to build and no longer needed.
