### ISSUE TITLE
[Request] mozc-ut ibus-mozc

### ISSUE THREAD

**Issue by Grafcube** [chaotic-aur/packages#2225]
### Link to the package base(s) in the AUR

[mozc-ut](https://aur.archlinux.org/pkgbase/mozc-ut)

[ibus-mozc](https://aur.archlinux.org/pkgbase/ibus-mozc)

### Utility this package has for you

I use it for Japanese input.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by dr460nf1r3** [comment]
Actually, this should be [rebuilding automatically already](https://github.com/chaotic-aur/interfere/blob/master/qt5-styleplugins/PKGBUILD.append#L1) 🤔 I removed & rebuilt the package manually now, so a reinstallation will get you the updated package.
