### ISSUE TITLE
[Bug] qt5-styleplugins its broken

### ISSUE THREAD

**Issue by anomalocaris452** [chaotic-aur/packages#2226]
### What happens?

qt5-styleplugins its broken

so u cant configure gtk applications and get some crashes

### What is expected to happen?

qt5-styleplugins to work well

### If possible, please attach logs

the solution its force a rebuild  (trigger a rebuild for qtr5-styleplugins)  + update its pkgrel

**Comment by dr460nf1r3** [comment]
Actually we do have automatic rebuilds for this one, though I now removed & rebuilt it manually. Reinstall the package and you should be good to go :)
