### ISSUE TITLE
[Outdated] firefox-esr

### ISSUE THREAD

**Issue by anomalocaris452** [chaotic-aur/packages#2227]
### Package name

firefox-esr
https://aur.archlinux.org/packages/firefox-esr

### Latest build

102.6.0esr

### Latest version available

~~105.5.0esr~~
115.2.0

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### More information

just update its pkgrel

thats all

**Comment by anomalocaris452** [comment]
@dr460nf1r3 the problem its that the mantainer its dead
https://archlinux.org/news/in-memory-of-jonathon-fernyhough/

**Comment by dr460nf1r3** [comment]
Oh, I didn't notice it was him being the maintainer. I got to know this very sad news already, in fact, he was also part of the Chaotic staff. Missing him already 🥲 

Guess we will need to wait for someone to step in then as I'm not particularly interested in maintaining the package myself atm.

**Comment by xiota** [comment]
Removed broken interfere: https://github.com/chaotic-aur/interfere/commit/6228677b03d499c2900a89a4240be7588da01664

Looks like there's a maintainer now.  Updated to 115.2.0.  Will see what happens at the next build attempt.

**Comment by Technetium1** [comment]
Successful build [firefox-esr.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/firefox-esr.log)

RIP Jonathon
