### ISSUE TITLE
[Outdated] thunderbird-beta

### ISSUE THREAD

**Issue by anomalocaris452** [chaotic-aur/packages#2228]
### If available, link to the latest build

https://ftp.mozilla.org/pub/thunderbird/releases/109.0b4/source/

### Package name

thunderbird-beta

### Latest build

109.0b4

### Latest version available

109.0b3

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### More information

just update the pkgrel
thats all

**Comment by dr460nf1r3** [comment]
The package needs to be updated in AUR in order to let our builders build it.

**Comment by dr460nf1r3** [comment]
I went ahead and flagged the package - it got updated and is building now
