### ISSUE TITLE
[Request] gimp-plugin-resynthesizer-git

### ISSUE THREAD

**Issue by anomalocaris452** [chaotic-aur/packages#2231]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/gimp-plugin-resynthesizer-git

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by dr460nf1r3** [comment]
This sadly depends on `python2-gimp`, which is why we can't add it (we got rid of Python 2 dependant packages a while ago).
