### ISSUE TITLE
[Request] gimp-extras

### ISSUE THREAD

**Issue by anomalocaris452** [chaotic-aur/packages#2232]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/gimp-extras

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by anomalocaris452** [comment]
dont worry
its _orphan_

but ubuntu aint pdated it
https://pkgs.org/search/?q=gimp-data-extras

**Comment by Technetium1** [comment]
This is already in routine :)

**Comment by dr460nf1r3** [comment]
Oops, is it in a routine twice now?

**Comment by Technetium1** [comment]
@dr460nf1r3 Oh no! Sorry, I didn't see your commit as closed for some reason. I went here as an open issue from notifications, did recursive grep on package dir, saw it in hourly, and closed as duplicate. Fixing!

**Comment by xiota** [comment]
Dropped because not compatible with GIMP 3.0.  Metrics 102.
