### ISSUE TITLE
[Request] chatgpt-desktop-bin

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2234]
### Link to the package base(s) in the AUR

[chatgpt-desktop-bin](https://aur.archlinux.org/packages/chatgpt-desktop-bin)

### Utility this package has for you

This package is a ChatGPT desktop client that is useful for all users to answer questions and, mainly, for solving issues.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because flagged out of date six months without maintainer response.  There are also reports of functional issues.  Metrics 212.
