### ISSUE TITLE
[Bug] wine-tkg stopped building again

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#2235]
### What happens?

```
==> ERROR: /home/main-builder/pkgsrc/wine-staging-git is not a clone of https://gitlab.winehq.org/wine/wine-staging.git
```

### What is expected to happen?

`wine-staging` moved from GitHub to WineHQs GitLab. `/home/main-builder/pkgsrc/wine-staging-git` should be deleted so it can be re-downloaded from the new repo.

### If possible, please attach logs

[https://builds.garudalinux.org/repos/chaotic-aur/logs/wine-tkg-staging.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/wine-tkg-staging.log)

**Comment by dr460nf1r3** [comment]
The issue has been identified and fixed :)
