### ISSUE TITLE
[Request] floorp

### ISSUE THREAD

**Issue by Jin-Asanami** [chaotic-aur/packages#2236]
### Link to the package base(s) in the AUR

[floorp](https://aur.archlinux.org/pkgbase/floorp)

### Utility this package has for you

This package is a Firefox-based web browser focused on balancing openness, anonymity, security and functionality of the web.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

I'm not a Floorp developer, but I think this package is very useful.

**Comment by FabioLolix** [comment]
Floorp is a disguised -bin pkgbuild and need a little revision (about use of source=() mainly), otherwise seems ok at first sight

**Comment by dr460nf1r3** [comment]
Indeed, thats a good hint. I remember checking this browser a while ago, though there hasn't been a release in months iirc :eyes:

**Comment by Ryonez** [comment]
@xiota 
I am unsure how, but the changes here broke the floorp build in a way that the `about:config` setting `xpinstall.signatures.required`  is no longer respected. 

Switching to the floorp-bin fixed it, but it seems odd, and prompted me to look into things and notice the bin changes.

**Comment by xiota** [comment]
The current `chaotic-aur/floorp` was built from source using a PKGBUILD related to `aur/firefox-hg` with the same default settings.  Any settings users change should be respected.

`aur/floorp-bin` uses upstream binaries, along with their defaults, except for auto update, which is disabled.

**Comment by Ryonez** [comment]
That's what I imagined, the default for `xpinstall.signatures.required ` for floorp was `false`.
 
For whatever reason though, that flag isn't respected in `chaotic-aur/floorp` now. I can't say for sure it is because of the PKGBUILD changes, but it becoming ignored happened in the last two days.

**Comment by xiota** [comment]
What are the steps to reproduce the problem?

**Comment by Ryonez** [comment]
I was using `chaotic-aur/floorp` before the bin changes, some time during the last two days.

upgraded floorp (11.7.1-2 -> 11.7.1-2.1)
Extension was disabled.

Switched to floorp-bin (11.7.1-1) after removing floorp (11.7.1-2.1)
Extension was usable.

Just had a look, looks like just install floorp (11.7.1-2.1), use an unsigned extension, and watch the browser mark it as disabled. Though I will note it seems to run despite the warning in addons and a browser restart. If you toggle it off though, it can't be re-enabled.

**Comment by xiota** [comment]
I need an example of an extension that is definitely not signed to test with.

**Comment by Ryonez** [comment]
The one I'm working with: [hydrus-companion](https://gitgud.io/prkc/hydrus-companion)

> Also, why are you installing unsigned extensions if you want floorp to keep them disabled?

I do not, I reached out as Floorp disabled it by itself after the update, which I noticed as I use the extension. The problem is it disabled it when it wasn't meant to.

**Comment by xiota** [comment]
The default for `xpinstall.signatures.required` in `chaotic-aur/floorp` seems to be false.  The default in `chaotic-aur/firefox-wayland-hg` and `chaotic-aur/firefox-nightly` is true.  I just looked through the diffs of the pkgbuilds, and do not see anything that explains the difference.  Going to look through upstream files.  If you want to look, here are the floorp repos:

* https://github.com/Floorp-Projects/Floorp
* https://github.com/Floorp-Projects/Floorp-core
* https://github.com/Floorp-Projects/Unified-l10n-central

**Comment by xiota** [comment]
I think the difference in default setting is here: [Floorp-Projects/Floop-core](https://github.com/search?q=repo%3AFloorp-Projects%2FFloorp-core+xpinstall&type=code)

But I cannot install the extension you linked regardless of how `xpinstall.signatures.required` is set.  So that is related to what you were describing earlier?

`firefox-nightly` allows the extension to be installed, but `firefox-wayland-hg` behaves the same as `floorp`.  I see references online indicating this behavior is intentional by Mozilla.  I will search for how to fix it.

**Comment by Ryonez** [comment]
> But I cannot install the extension you linked regardless of how `xpinstall.signatures.required` is set. So that is related to what you were describing earlier?

I already had the extension installed, so for me it was disabled once signing was enforced. But if the signing is already being enforced it will also prevent it from being installed.



> `firefox-nightly` allows the extension to be installed, but `firefox-wayland-hg` behaves the same as `floorp`. I see references online indicating this behavior is intentional by Mozilla. I will search for how to fix it.

Yes, only certain versions will respect the flag, otherwise it's forced disabled. [Info Here](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox).

Floorp's binaries are built on Firefox's ESR build, which does support this flag. If it's somehow getting another base that doesn't support it, it would force it to be disabled.

**Comment by Ryonez** [comment]
Where is the PKGBUILD file Chaotic is using to make this?
The AUR still seems to be using the binaries, but I'm not finding an interfere folder for it in  https://github.com/chaotic-aur/interfere

**Comment by xiota** [comment]
It's not uploaded anywhere yet.  Depending on what happens with `aur/floorp`, it could eventually be uploaded to aur, into the interfere repo, or dropped if it's decided chaotic-aur should stick with `floorp-bin`.  It could also be uploaded to aur under a different name if a good suffix can be found.

**Comment by xiota** [comment]
@Ryonez Seems unlikely that `aur/floorp` can be switched to build from source soon, so uploaded to the interfere repo: [intefere/floorp](https://github.com/chaotic-aur/interfere/tree/master/floorp).  It's not active yet.
