### ISSUE TITLE
[Request] otf-unifont

### ISSUE THREAD

**Issue by REmerald** [chaotic-aur/packages#2237]
### Package

https://aur.archlinux.org/pkgbase/otf-unifont

### Purpose

To make grub text bigger without reducing the resolution; to use the grub font in the desktop environment.

### License

OFL-1.1
GPL-2.0-or-later with font exception

### More information

We already have `bdf-unifont` in the repo, so why don't we include the other unifont variants?

They are extremely helpful and useful for the reasons above.

**Comment by xiota** [comment]
Some of unifont packages are being reorganized, so time to review which to keep / replace / drop.

What is the purpose of each file format – pcf, psf, otb, bdf?  Would it be worthwhile to replace the ttf with otf?

**Comment by xiota** [comment]
AUR dropped some related packages, so easier to drop all now and add back later after figuring it out.  Based on metrics, an otf or ttf package will be brought back.  Others are less likely.

* bdf-unifont 22
* bdf-unifont-extra 26
* otb-unifont 2
* pcf-unifont 11
* pcf-unifont-extra 11
* psf-unifont 13
* ttf-unifont 141
* ttf-unifont-csur 14
* unifont 0

There are multiple unifont packages all downloading and repackaging parts of the same source tarball.  So this might be worth making a custom pkgbuild.

**Comment by xiota** [comment]
Current metrics:

* bdf-unifont 8
* bdf-unifont-extra 4
* otb-unifont 3
* pcf-unifont-extra 4
* ttf-unifont 76
* ttf-unifont-csur 8

**Comment by knvzzz** [comment]
I think otf-unifont is the best option now:
- Pango 1.44 dropped support for the bdf and pcf format;
- The font in otf format is available from the official site; 
- The otf-unifont package includes Unifont.otf, Unifont_jp.otf, Unifont_Upper.otf and Unifont_CSUR.otf.

**Comment by xiota** [comment]
Dropping most unifont packages because of low usage and waning utility.  Keeping following (for now):

* `bdf-unifont` – makedep for `grub-improved-luks2-git` ([#1397](https://github.com/chaotic-aur/packages/issues/1397)).
* `otf-unifont` for general desktop use.

**Comment by xiota** [comment]
Current metrics:

* otf-unifont # 16
* bdf-unifont # 24
