### ISSUE TITLE
[Request] glrnvim

### ISSUE THREAD

**Issue by REmerald** [chaotic-aur/packages#2238]
### Link to the package base(s) in the AUR

[glrnvim](https://aur.archlinux.org/pkgbase/glrnvim)

### Utility this package has for you

(https://github.com/beeender/glrnvim)  
The best alternative to the other neovim frontends (at least in the repos/chaotic):

- Wraps neovim in your favourite terminal (supports alacritty, kitty and a few more), thus supports your terminal's features: keybinds, gpu acceleration, etc.
- Has its own config file which lets you easily change the font, neovim binary path (e.g. to lunarvim's `.local/bin/lvim`), etc. without messing up your terminal/neovim configuration and adding extra scripts/desktop files to launch e.g. `lvim`.
- Had [a recent release](https://github.com/beeender/glrnvim/releases/tag/v1.3.2): actively developed/maintained.
- The develover is also [the package's maintainer](https://aur.archlinux.org/packages/glrnvim): unlikelihood for the package to be orphan/outdated.
- Fully relies on the terminal for the UI, thus doesn't have to be developed too actively to fix bugs.
- So, it won't be too big of a deal (at least for a relatively long time) even if the project will be partially/fully abandoned.
- Works flawlessly.
- neovide is currently [broken on most wayland sessions](https://github.com/neovide/neovide/issues/1356).
- `neovim-qt` prints a weird annoying message about monospace family fonts.
- `goneovim-bin` (at least from chaotic) is broken too: needs an old missing outdated library; even if satisfied, prints warnings.
- This leaves with almost no other good alternatives: `gnvim` and `neovim-gtk` have annoying useless decorations; other similar projects are abandoned.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
@REmerald Just to be clear, `goneovim-bin` is nonfunctional [AUR-side problem], and should be removed?

**Comment by REmerald** [comment]
> `goneovim-bin` is nonfunctional [AUR-side problem]

I meant if you install the missing library `chaotic-aur/libtiff5` (not present in the `goneovim-bin` package dependencies), it will launch and "work", but with some issues:
```
goneovim: /usr/lib/libtiff.so.5: no version information available (required by goneovim)
/usr/bin/goneovim: /usr/lib/libtiff.so.5: no version information available (required by /usr/bin/goneovim)
open /home/remorin/.goneovim/setting.toml: no such file or directory
qt.qpa.wayland: Failed to load client buffer integration: "wayland-egl"
qt.qpa.wayland: Available client buffer integrations: ()
```
And I also noticed it displays some of the glyphs wrong. Maybe it has more, I didn't test it, just lauched it with a custom neovim config.

> should be removed?
I am not an expert, so I don't really know what's the right decision.

If you ask my opinion, I agree that this package is broken/unfunctional. It should at least be updated to use `libtiff.so.6` from `libtiff` instead of `libtiff.so.5` from `libtiff5`. [The project seems to relatively active though.](https://github.com/akiyosi/goneovim)  
Btw, if you will decide to not remove it, it'll be a good idea to rename it from `goneovim-bin` to just `goneovim`, to make the packages less confusing, because this's not AUR anymore, everything here is a binary.

> Just to be clear
So, everything else ok, especially `glrnvim`?
