### ISSUE TITLE
[Bug] Rebuild packages that depend on llvm

### ISSUE THREAD

**Issue by xiota** [chaotic-aur/packages#2241]
Arch updated `llvm` from 14.x to 15.x.  Consequently, packages depending on `llvm` cannot find `libLLVM-14.so`.  Rebuilding will make them use `libLLVM-15.so`.

Packages likely to have this issue:
 - [x]  clang-git
 - [x]  clasp-cl-git
 - [x]  compiler-rt-git
 - [x]  lib32-mesa-tkg-git
 - [x]  lld-git
 - [x]  lldb-git
 - [x]  llvm-git
 - [x]  mesa-tkg-git
 - [x]  polly-git
- [ ] ... others... ?

Above packages have a direct dependency on `llvm`.  They were found by running:

    pacman -Si | grep -E 'Depends On|Repository|Name' \
       | grep -B 2 -E 'Depends On.*\bllvm\b.*' \
       | grep -A 1 -E 'chaotic-aur' \
       | grep 'Name' | awk -F ':' '{ print $2 }'

Packages with indirect dependencies may also be affected.

**Comment by dr460nf1r3** [comment]
Both packages just got rebuilt, leaving this open in case other packages need to be bumped too.

**Comment by xiota** [comment]
@dr460nf1r3 Thank you.  I've updated the list with more packages that may be affected.

**Comment by dr460nf1r3** [comment]
Those are bumped as well and shall be rebuilt once the routine runs. https://github.com/chaotic-aur/interfere/commit/6f338774d2727d524695e05fbf5105a2ba102e51

**Comment by xiota** [comment]
I just did a search for second-order dependencies.  After they're rebuilt, would that be good enough to close this?  Or would there be a need to recursively search further?
````
 across
 anydesk-bin
 armorpaint-git
 art-rawconverter
 bcachefs-tools-git
 cef-minimal-obs-bin
 celestia
 codelite
 codelite-unstable
 corrosion-git
 darktable-git
 dosbox-x
 dosbox-x-git
 gallium-nine-git
 godot-git
 grapejuice
 include-what-you-use
 kodi-git
 kodi-nexus-git
 leagueoflegends-git
 lib32-gallium-nine-git
 lib32-gtk3-classic
 lib32-libglvnd-git
 libglvnd-git
 lldb-git
 lutris-git
 lutris-wine-git
 meowsql
 microsoft-edge-beta-bin
 microsoft-edge-dev-bin
 microsoft-edge-stable-bin
 minecraft-launcher
 minetest-git
 minetest-server-git
 paru-git
 php80-pgsql
 php82-pgsql
 playonlinux
 proftpd
 pspp
 qemu-git
 river
 river-git
 rocm-opencl-runtime
 rstudio-desktop
 servo-git
 spot-client-git
 steam-boilr-gui
 vim-coc-clangd-git
 vim-coc-rust-analyzer-git
 vkcube-git
 wasi-sdk-git
 waypipe-git
 xorg-server-devel-git
 yuzu-early-access
 zoom
````

**Comment by xiota** [comment]
@dr460nf1r3 When you get a chance, would you mind checking whether the packages in my previous post have been rebuilt so this issue can be closed?  Thank you.

**Comment by xiota** [comment]
@dr460nf1r3 I checked the build dates.  After the following packages are rebuilt, I believe this can be closed.  Thank you.
````
across
celestia
codelite
dosbox-x
lib32-gtk3-classic
minecraft-launcher
php80-pgsql
playonlinux
proftpd
pspp
steam-boilr-gui
gallium-nine-git
lib32-gallium-nine-git
lib32-libglvnd-git
spot-client-git
vkcube-git
````

**Comment by dr460nf1r3** [comment]
Alright, all of them are bumped now. A few caveats: 
- `lib32-gtk3-classic` has no PKGBUILD to build from, therefore it couldn't be bumped
- `{lib32-}gallium-nine-git is missing makedeps, therefore it didn't build
- the same goes for `vkcube-git`

**Comment by xiota** [comment]
How was `lib32-gtk3-classic` created without a PKGBUILD?

**Comment by dr460nf1r3** [comment]
I was baffled at first too but checked the non-32bit PKGBUILD: it used to get built by this package until this commit:
https://aur.archlinux.org/cgit/aur.git/commit/?h=gtk3-classic&id=e0d28569d8fbd8d01b40dbf21d6ec5a157f2ca07

**Comment by xiota** [comment]
What are the usage stats for `lib32-gtk3-classic`?  Would it be a candidate for removal?

**Comment by dr460nf1r3** [comment]
I already dropped it. There is no point in keeping it without proper updates imo.

**Comment by xiota** [comment]
Would `vkcube-git` also be a candidate for removal?  It's just a demo app that's included in `vulkan-tools`.

**Comment by dr460nf1r3** [comment]
Gotta ask @thotypous, he added it.

**Comment by thotypous** [comment]
Please remove :D

**Comment by dr460nf1r3** [comment]
I think we can close this by now. Both gallium-nine packages are stalled due to a missing dep for a longer time (I notified the maintainer some time back).
