### ISSUE TITLE
[Request] linux-xanmod-v2/3, linux-xanmod-lts-v2/3

### ISSUE THREAD

**Issue by EvoXCX** [chaotic-aur/packages#2242]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/linux-xanmod
https://aur.archlinux.org/packages/linux-xanmod-lts

https://www.xanmod.org/

Already in repo but need to be build with different flags in "More information" section to be x64-v2 and v3
Maybe create 2 different package but with different build flags could be nice features

### Utility this package has for you

Better support for recent CPU

x86-64 baseline ⇲  linux-xanmod-x64v1 | x86-64-v2 ⇲  linux-xanmod-x64v2 | x86-64-v3 ⇲  linux-xanmod-x64v3 | x86-64-v4 (AVX-512) ⇲  linux-xanmod-x64v3
-- | -- | -- | --
AMD K8-family AMD K10-family AMD Family 10h (Barcelona) AMD Family 14h (Bobcat) Intel low-power Silvermont Intel Goldmont (Apollo Lake and Denverton) Intel Goldmont Plus (Gemini Lake) All x86-64 CPUs | AMD Family 16h (Jaguar) AMD Family 15h (Bulldozer) AMD Family 15h (Piledriver) AMD Family 15h (Steamroller) Intel 1st Gen Core (Nehalem) Intel 1.5 Gen Core (Westmere) Intel 2nd Gen Core (Sandybridge) Intel 3rd Gen Core (Ivybridge) | AMD Family 15h (Excavator) AMD Family 17h (Zen) AMD Family 17h (Zen+) AMD Family 17h (Zen2) AMD Family 19h (Zen3) Intel 4th Gen Core (Haswell) Intel 5th Gen Core (Broadwell) Intel 6th Gen Core (Skylake) Intel 12th Gen (Alder Lake) | AMD Family 19h (Zen4) Intel 6th Gen Core (Skylake X) Intel 8th Gen Core (Cannon Lake) Intel 10th Gen Core (Ice Lake) Intel Xeon (Cascade Lake) Intel Xeon (Cooper Lake) Intel 3rd Gen 10nm++ (Tiger Lake) Intel 3rd Gen 10nm++ Xeon (Sapphire Rapids) Intel 11th Gen (Rocket Lake) Intel 13th Gen (Raptor Lake) Intel 14th Gen (Meteor Lake)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [x] Yes (Depend on x64 version)

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

```
##
## The following variables can be customized at build time. Use env or export to change at your wish
##
##   Example: env _microarchitecture=98 use_numa=n use_tracers=n makepkg -sc
##
## Look inside 'choose-gcc-optimization.sh' to choose your microarchitecture
## Valid numbers between: 0 to 99
## Default is: 0 => generic
## Good option if your package is for one machine: 98 (Intel native) or 99 (AMD native)
if [ -z ${_microarchitecture+x} ]; then
  _microarchitecture=0
fi

## Disable NUMA since most users do not have multiple processors. Breaks CUDA/NvEnc.
## Archlinux and Xanmod enable it by default.
## Set variable "use_numa" to: n to disable (possibly increase performance)
##                             y to enable  (stock default)
if [ -z ${use_numa+x} ]; then
  use_numa=y
fi

## For performance you can disable FUNCTION_TRACER/GRAPH_TRACER. Limits debugging and analyzing of the kernel.
## Stock Archlinux and Xanmod have this enabled. 
## Set variable "use_tracers" to: n to disable (possibly increase performance)
##                                y to enable  (stock default)
if [ -z ${use_tracers+x} ]; then
  use_tracers=y
fi

# Unique compiler supported upstream is GCC
## Choose between GCC and CLANG config (default is GCC)
## Use the environment variable "_compiler=clang"
if [ "${_compiler}" = "clang" ]; then
  _compiler_flags="CC=clang HOSTCC=clang LLVM=1 LLVM_IAS=1"
fi

# Choose between the 4 main configs for stable branch. Default x86-64-v1 which use CONFIG_GENERIC_CPU2:
# Possible values: config_x86-64-v1 (default) / config_x86-64-v2 / config_x86-64-v3 / config_x86-64-v4
# This will be overwritten by selecting any option in microarchitecture script
# Source files: https://github.com/xanmod/linux/tree/5.17/CONFIGS/xanmod/gcc
if [ -z ${_config+x} ]; then
  _config=config_x86-64-v1
fi

# Compress modules with ZSTD (to save disk space)
if [ -z ${_compress_modules+x} ]; then
  _compress_modules=n
fi

# Compile ONLY used modules to VASTLY reduce the number of modules built
# and the build time.
#
# To keep track of which modules are needed for your specific system/hardware,
# give module_db script a try: https://aur.archlinux.org/packages/modprobed-db
# This PKGBUILD read the database kept if it exists
#
# More at this wiki page ---> https://wiki.archlinux.org/index.php/Modprobed-db
if [ -z ${_localmodcfg} ]; then
  _localmodcfg=n
fi

# Tweak kernel options prior to a build via nconfig
if [ -z ${_makenconfig} ]; then
  _makenconfig=n
fi
```

**Comment by dr460nf1r3** [comment]
Most likely needs either separate PKGBUILDs or some code in the toolbox like the TKG kernels.

**Comment by EvoXCX** [comment]
Why closing the issue ?

**Comment by xiota** [comment]
Looks like typo...

**Comment by EvoXCX** [comment]
How I can help to close this issue ?

**Comment by xiota** [comment]
There are already 30+ kernels in chaotic-aur.  What do the xanmod kernels provide that the others don't?  (In particular, how do they compare with the tkg kernels?)

If you want only a few variations, this could be added with interfere.  Otherwise, it would require toolbox change, and may not be worth the effort.

**Comment by EvoXCX** [comment]
You're right, I close the issue.

**Comment by xiota** [comment]
My earlier comment was requesting more info.  I don't know how the kernel variations compare.  Since you closed the issue, does that mean you feel the xanmod kernels duplicate functionality from some others?

**Comment by EvoXCX** [comment]
> My earlier comment was requesting more info. I don't know how the kernel variations compare. Since you closed the issue, does that mean you feel the xanmod kernels duplicate functionality from some others?

On they website : 
Third-party patchset available: [patches](https://gitlab.com/xanmod/linux-patches)

- AMD's P-state CPPC driver for Zen2/3/4 processors [default].
- Intel's SMT task migration scheduler rework.
- Futex waitv and legacy WAIT_MULTIPLE implementation for Wine / Proton Fsync support.
- Cloudflare's TCP collapse processing for high throughput and low latency [[info](https://blog.cloudflare.com/optimizing-tcp-for-high-throughput-and-low-latency)].
- Google's Multigenerational LRU framework [default].
- Google's BBRv3 TCP congestion control [built-in: tcp_bbr] [default].
- Netfilter nf_tables RFC3489 full-cone NAT support.
- Netfilter FLOWOFFLOAD target to speed up processing of packets.
- WineSync driver for fast kernel-backed Wine [as module: winesync].
- PCIe ACS Override for bypassing IOMMU groups support.
- Graysky's additional GCC and Clang CPU options.
- Clear Linux patchset [partial].
- Android Binder IPC driver as module for Waydroid.

Plus a kernel compiled for the good arch psABI level reference can take more instructions set and have more "functionality".

**Comment by xiota** [comment]
Dropped v2 package because of low usage.

Switched to gcc to build v3 because kernels recently failing to build with clang.
