### ISSUE TITLE
[Request] gksu

### ISSUE THREAD

**Issue by joe733** [chaotic-aur/packages#2244]
### Link to the package base(s) in the AUR

[gksu](https://aur.archlinux.org/packages/gksu)

### Utility this package has for you

Run GUI applications as admin

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
@joe733 Added as dep for #2243 :smiley:
