### ISSUE TITLE
[Outdated] gamescope-git

### ISSUE THREAD

**Issue by CobaltSpace** [chaotic-aur/packages#2245]
### If available, link to the latest build

[gamescope-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/gamescope-git.log)

### Package name

`gamescope-git`

### Latest build

`3.11.51.r97.gf2a4533`

### Latest version available

`3.11.51.r120.gd6c1df4`

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### More information

It looks like the repo mirror used by `UFSCar HPC Builder` is broken.

**Comment by Technetium1** [comment]
Rebuilt, got a new error... :eyes:

**Comment by dr460nf1r3** [comment]
Gotta add pipewire to (make)depends

**Comment by dr460nf1r3** [comment]
Fixed in https://github.com/Frogging-Family/gamescope-git/pull/8 (built already, PR needs to be accepted for long term fix) :eyes:
