### ISSUE TITLE
[Request] balena-etcher

### ISSUE THREAD

**Issue by caniko** [chaotic-aur/packages#2246]
### Link to the package base(s) in the AUR

[balena-etcher](https://aur.archlinux.org/packages/balena-etcher)

### Utility this package has for you

Making ISO-USBs

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by caniko** [comment]
You must install `electron13` ahead of time, I used `electron13-bin` from the AUR.

**Comment by dr460nf1r3** [comment]
That's in fact one of the Electron versions we decided to get rid of - it's EOL and doesn't receive updates anymore. Apart from that, we seem to require Python 2, which we also don't provide anymore these days. (conflicts=('python<3'))

**Comment by asdfzxcvbn** [comment]
[balena-etcher](https://aur.archlinux.org/packages/balena-etcher) now depends on electron19 and python3, so could this be looked at again?

**Comment by xiota** [comment]
Please test: `balena-etcher-2:1.18.12-1-x86_64.pkg.tar.zst`

**Comment by asdfzxcvbn** [comment]
> Please test: `balena-etcher-2:1.18.12-1-x86_64.pkg.tar.zst`

it doesn't seem to be launching on my system

**Comment by xiota** [comment]
Launches on my computer.  Did not test flashing any drives.  Any error messages?

**Comment by caniko** [comment]
May I suggest `usbimager` instead? It doesn't have any adds, and gets the job done.

**Comment by asdfzxcvbn** [comment]
> Launches on my computer. Did not test flashing any drives. Any error messages (run in terminal)?

```
$ balena-etcher-electron
/usr/lib/electron19/electron: error while loading shared libraries: libicui18n.so.72: cannot open shared object file: No such file or directory
```

 something is probably just wrong on my system

**Comment by xiota** [comment]
What package are you using to provide electron?  I used `electron19-bin`.

**Comment by FabioLolix** [comment]
> error while loading shared libraries: libicui18n.so.72:

Need to be rebuilded after the `icu` update

> Making ISO-USBs

There aren't `popsicle` and `popsicle-git` already?

**Comment by dr460nf1r3** [comment]
The package has been rebuilt btw.

**Comment by xiota** [comment]
Package is not in lists.  Should it be added?

**Comment by dr460nf1r3** [comment]
I don't mind, as long as no outdated Electron is used (see at the beginning :D)
