### ISSUE TITLE
[Bug] nheko-git: Rebuild under cmark 0.30.3-1

### ISSUE THREAD

**Issue by Jocadbz** [chaotic-aur/packages#2249]
### What happens?

Running `nheko-git` installed from chaotic-aur results in a binary that raises an error while launching, complaining about a missing lib: `libcmark.so.0.30.2`

### What is expected to happen?

Nheko launches normally.

### If possible, please attach logs

[Logs:](https://github.com/chaotic-aur/packages/files/10484619/log.txt)

**Comment by Jocadbz** [comment]
Turns out nheko needs a rebuild. *Sigh*. Should've done my research first.

**Comment by Technetium1** [comment]
Should bump automatically now: https://github.com/chaotic-aur/interfere/commit/57046b8195f748ae7ac938b7b1c186ef61ee6e6b

**Comment by Jocadbz** [comment]
Thanks for looking at it.
