### ISSUE TITLE
[Bug] rstudio-desktop "error while loading ... : libboost_chrono.so.1.80.0" *Needs rebuild*

### ISSUE THREAD

**Issue by ThePoorPilot** [chaotic-aur/packages#2250]
### What happens?

With boost being updated to 1.81, rstudio-desktop is currently broken and does not open

### What is expected to happen?

rstudio would open without that error

### If possible, please attach logs

rstudio: error while loading shared libraries: libboost_chrono.so.1.80.0: cannot open shared object file: No such file or directory

### More information

All that is needed is a rebuild from what I can tell on AUR page.

I cannot get it to build on my machine, so there may be an issue further than that, but I'm just guessing it's probably just my machine

**Comment by dr460nf1r3** [comment]
Welp, I'm afraid we are having build issues 🥲

**Comment by Technetium1** [comment]
Everything goes wrong here: `[3/4] Linking dependencies...`, and further in it also fails due to 404 on a node dep's release, which seems to be caused by an incorrect URL. I don't think this is necessarily a problem on our end.
[rstudio-desktop.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/rstudio-desktop.log)

**Comment by ThePoorPilot** [comment]
Does the -git or -bin versions of the rstudio-desktop package have the same issues?

**Comment by dr460nf1r3** [comment]
`-bin` most likely won't have this issue as it is precompiled 🤔

**Comment by ThePoorPilot** [comment]
Yep, confirmed -bin works

Had to install openssl-1.1 and lib32-openssl-1.1, which are not listed as dependencies, but are most certainly needed

Would be nice to compile from source, but at least there's one avenue to make rstudio work

**Comment by xiota** [comment]
`rstudio-desktop` last built 2023-09-12.
