### ISSUE TITLE
[Request] micromamba

### ISSUE THREAD

**Issue by goingtosleep** [chaotic-aur/packages#2251]
### Link to the package base(s) in the AUR

[micromamba](https://aur.archlinux.org/packages/micromamba)

### Utility this package has for you

Mamba is a fast package manager for python, widely used in scientific fields in companion with conda. `micromamba` is a lightweight binary version of mamba.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Package failing to build and flagged out of date since 2024-09-10.

**Comment by xiota** [comment]
Switching to `aur/micromamba-bin`.  Metrics 26.
