### ISSUE TITLE
Need rebuild of ckb-next [Bug] 

### ISSUE THREAD

**Issue by mixalis1987** [chaotic-aur/packages#2254]
### What happens?

ckb-next will not start because it is requesting to be rebuilt on startup.

### What is expected to happen?

The GUI is expected to start and show keyboard lighting configurations.

### More information

I installed the AUR version and all is working great. So I think the program just needs rebuilding on your end?? Note, this happened after a big OS update and the programs GUI notified me on what needs to be done and that this may happen on big updates. Not sure if I can call this a bug or not, but the fix is simple.

**Comment by Technetium1** [comment]
`Finished making: ckb-next 0.5.0-2.3 (Fri 27 Jan 2023 07:21:00 AM CET)`
