### ISSUE TITLE
[Bug] qt5-styleplugins interfere not working

### ISSUE THREAD

**Issue by anomalocaris452** [chaotic-aur/packages#2255]
### What happens?

qt5-base wee updated so we'd need to reupdate qt5-styleplugins

### What is expected to happen?

update qt5-styleplugins from chaotic

### If possible, please attach logs

- force a rebuild for qt5-styleplugins
- - move the pkgrel to 36 (its 35  now its 36)

**Comment by Kandelai** [comment]
Came here to report the same thing. It is clearly outdated, switched to the more recent version in AUR. Thanks.

**Comment by dr460nf1r3** [comment]
Alright, it got bumped to pkgver `36` and I removed the interfere for now as it clearly does not work as intended. Keeping this issue open for this reason.

**Comment by xiota** [comment]
Is there still any need / desire to fix this interfere?

**Comment by Technetium1** [comment]
#3157
