### ISSUE TITLE
[Request] feishu

### ISSUE THREAD

**Issue by myeveryheart** [chaotic-aur/packages#2257]
### Link to the package base(s) in the AUR

[Feishu](https://aur.archlinux.org/packages/feishu-bin)

### Utility this package has for you

Feishu is an all-in-one collaboration suite. With features like Chat, Calendar, Meetings, Docs, Mail and Workplace all in one collective app, Feishu is dedicated to establishing an efficient working environment for organizations. 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

https://www.feishu.cn/en/

**Comment by FabioLolix** [comment]
The program don't have a license, the pkgbuild and .install where initially created with debtap and the .install need a big cleanup because as of now is questionable

**Comment by Technetium1** [comment]
This is not redistributable per ToS, and it's too large.

> 4.1 Subject to the terms and conditions agreed in the Terms, you are hereby granted a non-exclusive, limited, non-transferable, non-sublicensable and revocable license to access and use the Services, as well as access Feishu Contents (definition provided in Article9), and Feishu Content can only be accessed by using this Services. Feishu reserves all rights related to the Services and Feishu Contents. Without the prior written consent from us (or our authorized partners), you shall not, for any purpose, dispose of the Services and Feishu Contents in any manner, including but not limited to copy, adaptation, remake, distribution, transmission, broadcasting, display, sale, licensing, vertical search, mirroring or otherwise access or use without the authorization.
