### ISSUE TITLE
[Request] qqmusic

### ISSUE THREAD

**Issue by myeveryheart** [chaotic-aur/packages#2258]
### Link to the package base(s) in the AUR

[qqmusic](https://aur.archlinux.org/packages/qqmusic-bin)

### Utility this package has for you

It's a music player, many chinese love it.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by FabioLolix** [comment]
The package don't have a dedicated license, license=("CC0-1.0") is wrong, it is an electron program packaged with FPM and those pratically never have a license

**Comment by Technetium1** [comment]
I'm not sure if redistribution is allowed, but this would technically be against [their ToS](https://www.qq.com/contract.shtml) because it's [modifying the software](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=qqmusic-bin#n31).
