### ISSUE TITLE
[Request] hyprland-nvidia

### ISSUE THREAD

**Issue by georgewoodall82** [chaotic-aur/packages#2259]
### Link to the package base(s) in the AUR

[hyprland-nvidia](https://aur.archlinux.org/pkgbase/hyprland-nvidia)

### Utility this package has for you

an amazing wayland compositor that i use everyday for my gui programs.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

hyprland-git is already in chaotic-aur

**Comment by xiota** [comment]
Upstream `hyprland` has been reported to include fixes for the Nvidia issues this package was intended to address.

Would be nice if someone can confirm.

**Comment by xiota** [comment]
Dropped because functionality is now included in upstream hyprland.
