### ISSUE TITLE
[Request] remmina-plugin-teamviewer

### ISSUE THREAD

**Issue by mauriciodelima21** [chaotic-aur/packages#2264]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/remmina-plugin-teamviewer

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Will need to move teamviewer from Garuda repo

**Comment by xiota** [comment]
Dropping because depends on aur/teamviewer, which depends on qt5-webengine, which is no longer available (unbuildable).

Metrics 44.
