### ISSUE TITLE
[Outdated] Librewolf

### ISSUE THREAD

**Issue by Zacktamondo** [chaotic-aur/packages#2265]
### If available, link to the latest build

[librewolf.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/librewolf.log)

### Package name

`librewolf`

### Latest build

`108.0.1-1`

### Latest version available

`109.0-1`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by Technetium1** [comment]
Cache needed to be cleared. Thanks for the issue.
`Finished making: librewolf 109.0-1 (Sun 29 Jan 2023 07:48:23 PM CET)`
