### ISSUE TITLE
[Bug] prismlauncher and prismlauncher-qt5 need rebuilding

### ISSUE THREAD

**Issue by Godeps2891** [chaotic-aur/packages#2269]
### What happens?

prismlancher fails to launch

### What is expected to happen?

launch without issues

### If possible, please attach logs

prismlauncher: error while loading shared libraries: libtomlplusplus.so.3: cannot open shared object file: No such file or directory

**Comment by Technetium1** [comment]
`Finished making: prismlauncher-qt5 6.1-3 (Thu 02 Feb 2023 11:44:48 PM CET)`
`Finished making: prismlauncher 6.1-3 (Thu 02 Feb 2023 11:45:44 PM CET)`
