### ISSUE TITLE
[Bug] Logsec not installing correctly

### ISSUE THREAD

**Issue by zany130** [chaotic-aur/packages#2270]
### What happens?

```
logseq
fish: Unknown command. '/usr/bin/logseq' exists but is not an executable file.
```
Bash gives this

```
/usr/bin/logseq
bash: /usr/bin/logseq: Permission denied
```

Installing from the aur https://aur.archlinux.org/packages/logseq-desktop has the same issue 

https://aur.archlinux.org/packages/logseq-desktop-bin

does not have this issue

### What is expected to happen?

program launches with no errors

**Comment by Technetium1** [comment]
Since this is an upstream issue, would a valid fix be to use [logseq-desktop-bin](https://aur.archlinux.org/packages/logseq-desktop-bin) for the time being?

**Comment by Technetium1** [comment]
Looks like this has been resolved: https://aur.archlinux.org/cgit/aur.git/log/?h=logseq-desktop
