### ISSUE TITLE
[Outdated] schildichat-desktop

### ISSUE THREAD

**Issue by ProfP30** [chaotic-aur/packages#2274]
### Package name

schildichat-desktop

### Latest build

1.11.13.sc.1-1

### Latest version available

v1.11.22-sc.1

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by dr460nf1r3** [comment]
This is a case, in which flagging the AUR package would be the solution. The PKGBUILD is still at .13, which is why we build this version. I just did that :D

**Comment by ProfP30** [comment]
Fixed on 12.02.2023

**Comment by xiota** [comment]
Dropping because depends on electron25.  (Range in extra is 27-31.)
