### ISSUE TITLE
[Request] teams-for-linux

### ISSUE THREAD

**Issue by REmerald** [chaotic-aur/packages#2277]
### Link to the package base(s) in the AUR

[teams-for-linux](https://aur.archlinux.org/pkgbase/teams-for-linux)

### Utility this package has for you

Works better than the official app.  
See [its readme](https://github.com/IsmaelMartinez/teams-for-linux#teams-for-linux).

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by dr460nf1r3** [comment]
Wow, it is actually responsive and not buggy!
