### ISSUE TITLE
KDE-git moving to qt6 / repo split

### ISSUE THREAD

**Issue by dr460nf1r3** [chaotic-aur/packages#2279]
Here, we track the progress of moving our `kde-git` packages to Qt6 (necessary due to Plasma 6), as well as the move to a separate `kde-git` repo - removing the `-git` ending in each package's pkgname`. 

- [ ] Build packages against Qt6
- [ ] Create a new builder container for the `kde-git` repo
- [ ] Build all packages without `-git` ending

**Comment by dr460nf1r3** [comment]
Builder got set up in https://github.com/garuda-linux/infrastructure-nix/commit/ccd302d6c8ef6c99ae5aa88fe8702676b041c6e1, still needs 2 issues to be worked out to actually use it.

**Comment by dr460nf1r3** [comment]
The builder is set up and is ready to be used @alexjp !

**Comment by Technetium1** [comment]
NO! I was meant to close #2779

**Comment by alexjp** [comment]
> NO! I was meant to close #2779

no big issue ... THIS WILL BE CLOSED SOON :) ( hopefully )

**Comment by RyzenDew** [comment]
How goes the progress ?

**Comment by dr460nf1r3** [comment]
A working KDE 6 Desktop is up by now, some applications are still in need of being built against Qt6 though.

**Comment by alexjp** [comment]
unluckly.... seems today's build does not work (crash plasma-desktop).

last week it worked.

so far: 
 * all kf6 is built
 * all plasma-desktop is built (except discover)
 * some apps are built, some not

the server is [chaotic-aur-kde] ... but ... do not try it now, without doing a btrfs snapshot first.

also ... its necessary to `pacman -Rdd kirigami2 polkit-qt5` before (I will fix the pkgbuilds to add conflicts next step)

**Comment by alexjp** [comment]
well ... works now ( er ... meaning works is... you can open windows and most things don't crash :) :) :) )

**Comment by dr460nf1r3** [comment]
I'd call that success :yum: 🥳

**Comment by xiota** [comment]
Okay to close as completed?
