### ISSUE TITLE
[Remove] jellyfin-media-player

### ISSUE THREAD

**Issue by maltejur** [chaotic-aur/packages#2282]
### Link to the package base(s) in the AUR

[jellyfin-media-player](https://aur.archlinux.org/packages/jellyfin-media-player)

### Utility this package has for you

It allows me to seamlessly connect to my Jellyfin server and play media.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

[jellyfin-media-player-git](https://aur.archlinux.org/packages/jellyfin-media-player-git) already is in chaotic-aur, so why not the main package?

**Comment by xiota** [comment]
Dropped because depends on EOL Qt5.  In particular,  qt5-webengine was dropped from extra.  Metrics 1018.

There is evidence upstream is working on porting to Qt6.  Please comment to request re-add when it's updated.
