### ISSUE TITLE
[Request] binance

### ISSUE THREAD

**Issue by mauriciodelima21** [chaotic-aur/packages#2283]
### Link to the package base(s) in the AUR

[binance](https://aur.archlinux.org/pkgbase/binance)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
```
$ strings binance | grep -Eom1 'Electron/[0-9\.]+'
Electron/26.6.10
```

**Comment by xiota** [comment]
Package should have been dropped a lot sooner...
* [Binance and CEO Plead Guilty to Federal Charges in $4B Resolution](https://www.justice.gov/archives/opa/pr/binance-and-ceo-plead-guilty-federal-charges-4b-resolution)
* [Binance Founder Sentenced to 4 Months in Prison](https://www.nytimes.com/2024/04/30/technology/binance-founder-changpeng-zhao-sentenced.html)
