### ISSUE TITLE
[Bug] gconf produce "Maximum file size exceeded"

### ISSUE THREAD

**Issue by hunabku94** [chaotic-aur/packages#2284]
### What happens?

Can't install gconf via chaotic-aur but with aur works

### What is expected to happen?

When trying to install / update gconf via chaotic-aur, have "Maximum file size exceeded" on all mirrors.
Work build/install in aur.

### If possible, please attach logs

> gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst file could not be downloaded error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg .tar.zst" from geo-mirror.chaotic.cx: Maximum file size exceeded
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from cdn-mirror.chaotic.cx: Maximum file size exceeded
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from cdn-cn-mirror.chaotic.cx: Maximum file size exceeded
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from br-mirror.chaotic.cx: Maximum file size exceeded
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from br-2-mirror.chaotic.cx: Maximum file size exceeded
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from bg-mirror.chaotic.cx: Maximum file size exceeded
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from ca-mirror.chaotic.cx: Maximum file size exceeded
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from fr-1-mirror.chaotic.cx: The requested URL returned error: 404
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from fr-2-mirror.chaotic.cx: Maximum file size exceeded
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from de-mirror.chaotic.cx: Maximum file size exceeded
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from de-2-mirror.chaotic.cx: Maximum file size exceeded
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from de-3-mirror.chaotic.cx: Maximum file size exceeded
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from de-4-mirror.chaotic.cx: Maximum file size exceeded
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from in-mirror.chaotic.cx: Maximum file size exceeded
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from in-2-mirror.chaotic.cx: Maximum file size exceeded
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from in-3-mirror.chaotic.cx: Maximum file size exceeded
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from kr-mirror.chaotic.cx: Maximum file size exceeded
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from es-mirror.chaotic.cx: Maximum file size exceeded
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from es-2-mirror.chaotic.cx: Maximum file size exceeded
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from ae-mirror.chaotic.cx: The requested URL returned error: 404
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from ae-2-mirror.chaotic.cx: The requested URL returned error: 404
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from us-fl-mirror.chaotic.cx: Maximum file size exceeded
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from us-mi-mirror.chaotic.cx: Maximum file size exceeded
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from us-ny-mirror.chaotic.cx: The requested URL returned error: 404
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from us-tx-mirror.chaotic.cx: Maximum file size exceeded
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from us-ut-mirror.chaotic.cx: Maximum file size exceeded
> 
> error: Failed to retrieve file 'gconf-3.2.6+11+g07808097-10.1-x86_64.pkg.tar.zst' from us-va-mirror.chaotic.cx: Maximum file size exceeded
> 
> warning: error retrieving some files
> error: transaction validation failed (download library error)
> Errors occurred, no packages were updated.

**Comment by Technetium1** [comment]
Should be fine, thanks @hunabku94!
`Finished making: gconf 3.2.6+11+g07808097-10.2 (Fri 17 Feb 2023 06:53:54 PM CET)`
