### ISSUE TITLE
[Remove] gdm-plymouth-prime

### ISSUE THREAD

**Issue by norz3n** [chaotic-aur/packages#2286]
### Link to the package base(s) in the AUR

[gdm-plymouth-prime](https://aur.archlinux.org/pkgbase/gdm-plymouth-prime)

### Utility this package has for you

It is needed to run Plymouth splash screens in Gnome, using Nvidia hybrid graphics

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Is this still needed?

**Comment by xiota** [comment]
Metrics 467.  But fails to build.  Flagged since Aug 2023 (11 months).

How "important" is this package?

**Comment by xiota** [comment]
Dropping because:

* Maintainer is MIA
* Package out of date.
* Package fails to build.
* Patches same or similar to `aur/gdm-prime`.
* No response to my previous queries.
