### ISSUE TITLE
[Remove] xcursor-breeze

### ISSUE THREAD

**Issue by norz3n** [chaotic-aur/packages#2288]
### Link to the package base(s) in the AUR

[xcursor-breeze](https://aur.archlinux.org/pkgbase/xcursor-breeze)

### Utility this package has for you

This package will be useful for users who only want the standard KDE Plasma cursor, without the folder icons, etc.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropped because no longer in AUR.  Metrics 33.
