### ISSUE TITLE
[Request] sublime-merge

### ISSUE THREAD

**Issue by norz3n** [chaotic-aur/packages#2290]
### Link to the package base(s) in the AUR

[sublime-merge](https://aur.archlinux.org/pkgbase/sublime-merge)

### Utility this package has for you

This package is used to work with Git repositories in Sublime Text, with the corresponding plugin.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by FabioLolix** [comment]
```
Does the package's license allow redistributing it?

YES!
```

The license explicity prohibit distribution

**Comment by dr460nf1r3** [comment]
Lmao, it's astonishing how many people cross yes when it's actually no 👀

**Comment by norz3n** [comment]
Oh, I just didn't know it couldn't be distributed, I'll close the issue

**Comment by FabioLolix** [comment]
> Oh, I just didn't know it couldn't be distributed

If you don't know just say that you don't know
