### ISSUE TITLE
[Request] catt

### ISSUE THREAD

**Issue by xiota** [chaotic-aur/packages#2293]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/catt

### Utility this package has for you

Cast All The Things - Send videos from many, many online sources to your Chromecast.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

What is the meaning of this question?  Doesn't it apply mainly to -git packages?

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Dependencies python-pychromecast and python-casttube are already in chaotic-aur.

**Comment by Technetium1** [comment]
Awesome find!

**Comment by xiota** [comment]
@dr460nf1r3 `error: catt: signature from "Nico Jensch (Chaotic-AUR) <...>" is invalid`

**Comment by Technetium1** [comment]
`Finished making: catt 0.12.10-2.2 (Fri 05 May 2023 07:56:42 PM CEST)`
