### ISSUE TITLE
[Bug] DB sync problem on TKG routine

### ISSUE THREAD

**Issue by raziel100** [chaotic-aur/packages#2297]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-tkg-bmq-generic_v3.log

### Package name

Linux-tkg-*

### Latest build

Linux-tkg v6.1

### Latest version available

Linux-tkg v6.2

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### More information

All Linux-tkg build are failing because of a sync problem with chaotic db for a fell days now.

error: failed retrieving file 'chaotic-aur.db' from localhost:8080 : Failed to connect to localhost port 8080 after 0 ms: Couldn't connect to server
error: failed to synchronize all databases (unexpected error)

**Comment by Technetium1** [comment]
This is not an issue with Chaotic, it's an issue with your connection. Check your configs, it looks like it's failing to connect due to a proxy on port 8080 not being available.

**Comment by raziel100** [comment]
> This is not an issue with Chaotic, it's an issue with your connection. Check your configs, it looks like it's failing to connect due to a proxy on port 8080 not being available.

My connection? What do you mean? The log is from wherever this packages are being building, is not related with the client side, I just put the part of the log that is the root of the issue

**Comment by Technetium1** [comment]
OH! I thought you were having an issue downloading the package yourself before checking the build log.

**Comment by dr460nf1r3** [comment]
This looks like a builder configuration issue 👀

**Comment by dr460nf1r3** [comment]
This just got fixed and kernels are in progress of being built! :)

**Comment by Edu4rdSHL** [comment]
Yep, I have fixed the issue. Thx for reporting.
