### ISSUE TITLE
[Request] ASUS Keyboard BackLight

### ISSUE THREAD

**Issue by Pakrohk** [chaotic-aur/packages#2299]
### Link to the package base(s) in the AUR

[asus-kbd-backlight](https://aur.archlinux.org/packages/asus-kbd-backlight)

### Utility this package has for you

Helper for adjusting keyboard backlight brightness in Asus Zenbook UX31A and ASUS N551 XX and similar models

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

After installing the package, you need to activate its service.
and a module for the kernel to be called.

```
modprobe asus-nb-wmi

systemctl enable asus-kbd-backlight.service
```

**Comment by xiota** [comment]
Dropping because AUR package is orphaned.  Metrics 15.
