### ISSUE TITLE
[Bug] wine-tkg-staging is failing to build again

### ISSUE THREAD

**Issue by raziel100** [chaotic-aur/packages#2300]
### What happens?

i believe some patch when applied is breaking the build in chaotic, its being happening for a fell days now, and always stop in the same place, for what i can see in the log it appears to be 0002-proton_LFH-staging.mypatch the problem. But i didn't try to build it with this patch to confirm it.

### What is expected to happen?

the build should be successful.

### If possible, please attach logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/wine-tkg-staging.log

**Comment by raziel100** [comment]
i have tested locally the build, and the patches for wine-tkg-staging
- ntdll_Map_top-down_if_dll_characteristics_include_DYNAMIC_BASE.mypatch 
- mfplat_nv12_d3d11_buffers.mypatch"
is not building with that, it needs to be removed, the only patch that had worked just fine was "amdags.mypatch"

**Comment by dr460nf1r3** [comment]
Needs to be fixed here: 
https://github.com/Frogging-Family/wine-tkg-git/blob/master/wine-tkg-git/wine-tkg-profiles/chaotic-staging.cfg
