### ISSUE TITLE
[Reove] runescape-launcher

### ISSUE THREAD

**Issue by StarterWheel22** [chaotic-aur/packages#2302]
### Link to the package base(s) in the AUR

[runescape-launcher](https://aur.archlinux.org/packages/runescape-launcher)

### Utility this package has for you

Game launcher for the video game "Runescape".

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropped because depends on EOL GTK2.  Metrics 20.
