### ISSUE TITLE
[Request] pamac-cli

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2304]
### Link to the package base(s) in the AUR

[pamac-cli](https://aur.archlinux.org/packages/pamac-cli)

### Utility this package has for you

Pamac CLI frontend

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by yum13241** [comment]
What's the point of the package? If you're gonna use the command line you might as well use `pacman` or `pikaur`!

**Comment by D3vil0p3r** [comment]
> What's the point of the package? If you're gonna use the command line you might as well use `pacman` or `pikaur`!

Hey! pamac, over pacman and similar, has also support for snaps, flatpack, (and of course the AUR). It is massively used on distros as Manjaro Linux.

**Comment by yum13241** [comment]
> Manjaro Linux.


Whose devs aren't exactly trustworthy. They brought down the AUR twice due to lack of testing.


Also, `flatpak` has its own CLI tool, and `snapd` is horrible.

**Comment by D3vil0p3r** [comment]
> > Manjaro Linux.
> 
> Whose devs aren't exactly trustworthy. They brought down the AUR twice due to lack of testing.
> 
> Also, `flatpak` has its own CLI tool, and `snapd` is horrible.

About snapd, I would not like to judge in that way. They could have tools that other pkg managers cannot allow you to retrieve.

**Comment by yum13241** [comment]
> About snapd, I would not like to judge in that way. They could have tools that other pkg managers cannot allow you to retrieve.


Dev's fault for using an objectively bad packaging format.

**Comment by Technetium1** [comment]
Until Arch changes from pacman, it will always be preferred. That of course doesn't stop us from adding this tool.

**Comment by Technetium1** [comment]
Looks like this has been abandoned but not orphaned? Please revive this in the future if it comes back!
