### ISSUE TITLE
[Request] cage-git

### ISSUE THREAD

**Issue by REmerald** [chaotic-aur/packages#2305]
### Link to the package base(s) in the AUR

[cage-git](https://aur.archlinux.org/pkgbase/cage-git)

### Utility this package has for you

Git version of `community/cage`, uses newest wlroots 0.16, unlike the (quite old) release which requires separate `wlroots0.15`.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because `extra/cage` is available and low usage.  Metrics 3.

Currently only one commit difference between stable and git versions.
