### ISSUE TITLE
[Request] rmg

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#2306]
### Link to the package base(s) in the AUR

[rmg](https://aur.archlinux.org/pkgbase/rmg/)

### Utility this package has for you

Nintendo 64 emulator with a nice Qt6-based GUI.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Build failing: [rmg.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/rmg.log)
```
--   Package 'speexdsp', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:607 (message):
A required package was not found
Call Stack (most recent call first):
/usr/share/cmake/Modules/FindPkgConfig.cmake:829 (_pkg_check_modules_internal)
Source/RMG-Audio/CMakeLists.txt:14 (pkg_check_modules)
```

**Comment by Technetium1** [comment]
Left a comment for the maintainer to fix

**Comment by REmerald** [comment]
@Technetium1 [fixed](https://aur.archlinux.org/packages/rmg#comment-904748)
