### ISSUE TITLE
[Outdated] nvim-nightly

### ISSUE THREAD

**Issue by REmerald** [chaotic-aur/packages#2308]
### If available, link to the latest build

[nvim-nightly.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/nvim-nightly.log)

### Package name

`nvim-nightly`

### Latest build

`0.9.0.dev.1c47839-1`

### Latest version available

`0.9.0.dev.1dd2424-1`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

The package is outdated, it uses [the 4 months old version](https://github.com/neovim/neovim/commit/1c478391ca7754bf5ecb4b76c29acfa9b4978393) instead of [the latest one](https://github.com/neovim/neovim/releases/tag/nightly).

The AUR package is outdated too, flagged it out-of-date.

**Comment by REmerald** [comment]
@Technetium1 I think it would be better if we switched to `neovim-nightly-bin`, it's unmaintained too, but [is much better candidate that nvim-nightly](https://aur.archlinux.org/packages/neovim-git#comment-904675).

**Comment by REmerald** [comment]
@Technetium1 @dr460nf1r3  [neovim-nightly-bin is now fixed, updated and maintained.](https://aur.archlinux.org/packages/neovim-nightly-bin)

We can now 100% replace `nvim-nightly` with `neovim-nightly-bin`. Should I create separate issue(s)?

**Comment by dr460nf1r3** [comment]
Sounds good to me!

**Comment by dr460nf1r3** [comment]
Don't mind the wrong pkgname, I fixed it in the following commit :)

**Comment by REmerald** [comment]
@dr460nf1r3 I think the name should be `neovim-nighthly-bin` as other packages: `neovim`, `neovim-git`, etc.

`nvim-` is counter-intuitive.

**Comment by FabioLolix** [comment]
> The package is outdated, it uses [the 4 months old version](https://github.com/neovim/neovim/commit/1c478391ca7754bf5ecb4b76c29acfa9b4978393)

It download the latest nightly archive (https://github.com/neovim/neovim/archive/refs/tags/nightly.tar.gz), only pkgver= was static and manually updated
