### ISSUE TITLE
[Request] clash-for-windows-bin

### ISSUE THREAD

**Issue by myeveryheart** [chaotic-aur/packages#2311]
### Link to the package base(s) in the AUR

[clash-for-windows-bin](https://aur.archlinux.org/packages/clash-for-windows-bin)

### Utility this package has for you

A Windows/macOS/Linux GUI based on Clash and Electron.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

No, but the author doesn't really care anyways. It's just for bureaucracy.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
See #2106
