### ISSUE TITLE
[Bug] Incorrect info in ReadMe

### ISSUE THREAD

**Issue by lectrode** [chaotic-aur/packages#2314]
### Issue

> multimc-git: This application is licensed under the Apache 2 license, which prohibits distributing [custom binaries](https://multimc.org/#Branding) like the one built by us.

The Apache 2 license does not prohibit distributing custom binaries, as the above wording implies. The Apache 2 license is a permissive license that "allows users to use the software for any purpose, to distribute it, to modify it, and to distribute modified versions of the software under the terms of the license, without concern for royalties."([source](https://en.wikipedia.org/wiki/Apache_License))

### Solution

The original wording should be changed to indicate that the branding/custom binary restriction is imposed directly by the developers of that project, not the license. Something like the following:

> multimc-git: Redistribution of custom binaries that include their API keys and trademarked assets is [explicitly prohibited](https://multimc.org/#Branding).

**Comment by lectrode** [comment]
On a related note, the tlauncher snippet should not be "same as above"; it should list its own reasoning. For example:

> tlauncher: Legal gray area, as it potentially allows playing Minecraft in a reduced capacity without license

**Comment by dr460nf1r3** [comment]
Thanks for paying attention! :)
