### ISSUE TITLE
[Request] ares-emu-git

### ISSUE THREAD

**Issue by nilkonom** [chaotic-aur/packages#2315]
### Package

Custom package:
https://github.com/chaotic-aur/packages/tree/main/ares-emu-git

Reference:
https://aur.archlinux.org/packages/ares-emu-git

### Purpose

It's an actively developed multi-system emulator and has great compatibility and accuracy.

### License

ISC

**Comment by xiota** [comment]
To prevent illegal instructions, the following packages have been modified or created:

* ares-emu: targets x86-64 (sse2)
* ares-emu-git: targets x86-64 (sse2)
* ares-emu-avx-git: targets x86-64-v3 (avx/avx2)

**Comment by xiota** [comment]
For about a month, packages were in a state where they could attempt illegal instructions on some machines.  Should be fixed again.  Metrics:
 
* ares-emu # 126
* ares-emu-git # 40
* ares-emu-avx-git # 32

**Comment by xiota** [comment]
Dropped ares-emu because moved to extra.

Metrics:

* ares-emu # 37
* ares-emu-git # 56
