### ISSUE TITLE
[Outdated] chromium-wayland-vaapi needs rebuild

### ISSUE THREAD

**Issue by PolpOnline** [chaotic-aur/packages#2316]
### If available, link to the latest build

[chromium-wayland-vaapi](https://builds.garudalinux.org/repos/chaotic-aur/logs/chromium-wayland-vaapi.log)

### Package name

`chromium-wayland-vaapi`

### Latest build

not applicable since we need a rebuild just to relink a new lib

### Latest version available

-

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

We need a rebuild for this package, since it is still linked with an old FFmpeg library (`libavcodec.so.59`).

**Comment by dr460nf1r3** [comment]
The package is building currently.

**Comment by PolpOnline** [comment]
It works now
