### ISSUE TITLE
[Outdated] anbox-git

### ISSUE THREAD

**Issue by dagaz** [chaotic-aur/packages#2317]
### If available, link to the latest build

https://builds.garudalinux.org/repos/chaotic-aur/logs/anbox-git.log

### Package name

anbox-git

### Latest build

1:r1364.7a0bee7-11.1

### Latest version available

1:r1366.ddf4c57-1

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

I am not sure if a build is possible at all now.
The build exits with an error. It does the same on my machine if I try to build the AUR-package. But I am just too inexperienced to understand the latest comments on https://aur.archlinux.org/packages/anbox-git and so I really don't know what to do.

anbox-git was build with boost-libs 1.80.0, the current version of boost-libs is 1.81.0-3.

So libboost_log.so.1.80.0 (/usr/lib/libboost_log.so.1.80.0) is missing.

**Comment by dr460nf1r3** [comment]
I see, it is possible to build using the provided patch. We could in fact add this patch to the build process.

**Comment by xiota** [comment]
`anbox-git` is no longer included in chaotic-aur.  See #2402.
