### ISSUE TITLE
[Request] etcd

### ISSUE THREAD

**Issue by joe733** [chaotic-aur/packages#2318]
### Link to the package base(s) in the AUR

[etcd](https://aur.archlinux.org/packages/etcd)

### Utility this package has for you

A highly-available key value store for shared configuration and service discovery. For Kubernetes.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [x] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because moved to extra.  Metrics 47.
