### ISSUE TITLE
[Outdated] forkgram needs rebuild

### ISSUE THREAD

**Issue by poly000** [chaotic-aur/packages#2320]
### If available, link to the latest build

[forkgram.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/forkgram.log)

### Package name

forkgram

### Latest build

4.6.7-1

### Latest version available

4.6.7

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by dr460nf1r3** [comment]
Bumped and building.

**Comment by poly000** [comment]
need rebuild, again

**Comment by dr460nf1r3** [comment]
Building!
