### ISSUE TITLE
[Request] curl-http3

### ISSUE THREAD

**Issue by road2react** [chaotic-aur/packages#2322]
### Link to the package base(s) in the AUR

[curl-http3](https://aur.archlinux.org/packages/curl-http3)

### Utility this package has for you

This would provide help for HTTP development (web servers, etc), since it supports http3.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
The build fails due to missing `quiche`, which is not specified as a dep. To make matters worse, `quiche` seems to be [outdated for a month](https://aur.archlinux.org/packages/quiche).
Log: [curl-http3.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/curl-http3.log)

**Comment by xiota** [comment]
Dropping because previous maintainer left a comment stating that `extra/curl` supports http3.

**Comment by Technetium1** [comment]
Dropped twice in a row? 👀

**Comment by xiota** [comment]
v3 and v4 repos were out of sync prior to the transition.
