### ISSUE TITLE
[Request] myuzi

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#2324]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/myuzi

### Utility this package has for you

Spotify alternative with no ads, payments or accounts

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
@tio-trom Upstream is very suddenly gone... Entirely!?!

**Comment by tio-trom** [comment]
Oh whaaat!? That's odd. Maybe Youtube went after them who knows...damn. Maybe we can keep this issue open for a bit more and I'll check on them to see if this is a weird thing or they are gone for good, and I'll update the issue here.

**Comment by dr460nf1r3** [comment]
Sure, keep us updated :)

**Comment by xiota** [comment]
Upstream project has been discontinued with the repository taken offline.

**Comment by zehkira** [comment]
I realize that it's been almost a year, but I just found this issue by accident, so I thought I'd clarify some things.

Myuzi was not "discontinued". I rewrote the app from scratch and changed the name to "Monophony".

https://gitlab.com/zehkira/monophony

**Comment by xiota** [comment]
Deleting the repo is discontinuing it. The original package can no longer be built.

A new package would need to be made for the renamed/forked project.

**Comment by Technetium1** [comment]
If someone wants to request in the future, https://aur.archlinux.org/packages/monophony exists
