### ISSUE TITLE
[Request] dolphin-emu-git

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#2325]
### If available, link to the latest build

[dolphin-emu-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/dolphin-emu-git.log)

### Package name

`dolphin-emu-git`
https://aur.archlinux.org/pkgbase/dolphin-emu-git
https://aur.archlinux.org/packages/dolphin-emu-git

### Latest build

`5.0.r18714.g3c4a21315d`

### Latest version available

current commit is 019bde6

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by xiota** [comment]
If no one objects, I plan to drop this because `extra/dolphin-emu` uses select git commits.

`dolphin-emu-git` hasn't been building since Apr 2023.  It is now 165 commits behind extra.  The PKGBUILD looks like it needs an overhaul to at least update depends and git submodules.

**Comment by niobium93** [comment]
Yea I switched to the one in `extra` already, so fine by me.

**Comment by NerosTie** [comment]
I don't understand why it has been removed. The version in Extra is far behind (19433 vs 19793 for the exemple of today) and, worse, there is a segfault when launching a game. No issue when I compile the git version.

**Comment by niobium93** [comment]
Can confirm. The one in `extra` is broken. Games don't run. The `dolphin-emu-git` AUR package has been updated, so we should probably build it again. It also looks like the `dolphin-emu-nogui-git` package was never removed, so we are actually building the AUR package still, but only packaging the `nogui` variant...

**Comment by xiota** [comment]
Removed because it wasn't building in clean chroot.  Will recheck it later.

**Comment by niobium93** [comment]
@xiota Can you try again? The `PKGBUILD` has been updated and the one in `extra` still crashes when running a game for me.

**Comment by xiota** [comment]
Can you give instructions to reproduce the crashes/issues you're having?

**Comment by niobium93** [comment]
Just run dolphin, run a game, it freezes for a while then segfaults.

**Comment by xiota** [comment]
Based on AUR comments, looks like won't build because of `libfmt`.  Have to wait for upstream to fix it.

**Comment by niobium93** [comment]
[The package seems to have a patch to address that.](https://aur.archlinux.org/cgit/aur.git/commit/?h=dolphin-emu-git&id=e6c8d0c4271718051b58a0b57e661a46f736e321)

**Comment by xiota** [comment]
The PKGBUILD last updated yesterday.  Already tried building it today, and it failed.  No point to keep trying until the maintainer pushes another update or upstream releases an official fix.

**Comment by xiota** [comment]
From [FS#78628](https://bugs.archlinux.org/task/78628), the cause of the crashing may be LTO.  I've built `dolphin-emu` with LTO disabled.  Install with `pacman -S chaotic-aur/dolphin-emu`.

Note: `dolphin-emu` has not been added to the package lists and will not auto rebuild.  I have added it as a temporary workaround.

**Comment by xiota** [comment]
Built `dolphin-emu-git` with modified `PKGBUILD`.  Available for testing.  Still need to wait for maintainer to update.

**Comment by niobium93** [comment]
Can confirm both `chaotic-aur/dolphin-emu` and `chaotic-aur/dolphin-emu-git` are working fine. Thanks for your work!

**Comment by niobium93** [comment]
`chaotic-aur/dolphin-emu-git` needs to be rebuilt again.
```
dolphin-emu: error while loading shared libraries: libminizip-ng.so.4: cannot open shared object file: No such file or directory
```

**Comment by xiota** [comment]
Rebuilt `dolphin-emu-git`.  If the AUR package isn't updated/fixed during the next few weeks, I'll look into making an interfere.

**Comment by niobium93** [comment]
Looks like AUR package got updated.

**Comment by xiota** [comment]
Just test built and added `dolphin-emu-git` back to package lists.

`dolphin-emu-nolto` is also available.  It is a rebuild of `extra/dolphin-emu` with options to avoid the segfault.

Note: `dolphin-emu-git` *will* break again when upstream eventually updates for `fmt10`.  Please wait to request rebuild until a day after the maintainer updates to allow the build server to pick up the changes and rebuild automatically.

**Comment by xiota** [comment]
There are reports that `dolphin-emu-git` is failing to build again because of `fmt`.

`extra/dolphin-emu` was updated a few days ago, but still segfaults.

Added another test package, `dolphin-emu-clang`.  It is a rebuild of `extra/dolphin-emu` using `clang` instead of `gcc`.

**Comment by xiota** [comment]
`dolphin-emu-git` has been building with a custom pkgbuild for a few weeks.  It's available for examination at [dolphin-emu-debugfast-git](https://aur.archlinux.org/pkgbase/dolphin-emu-debugfast-git).  (I repurposed the package after the previous maintainer disowned it.)  This way, I can (try to) fix problems faster.

A moment ago, I made `dolphin-emu-avx-git`.  It's the same pkgbuild with different compiler flags. `-march x86-64-v3 -O3` instead of `-march x86-64 -O2`.  There's some info on Wikipedia about [Microarchitecture levels](https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels).

Is anyone willing to test and let me know if there's any noticeable difference?  If so, maybe having -avx- versions of other emulators would be worthwhile.  I'm also going to make an -avx- version of `yuzu`.

**Comment by niobium93** [comment]
@xiota I tried running Crash Tag Team Racing, which drops down to ~30 FPS when walking around the park on both `dolphin-emu-git` and 'dolphin-emu-avx-git` and didn't see any difference.

I also tried running the Red Dead Redemption Switch port with the framerate uncapped on both `yuzu-git` and `yuzu-avx-git` and I _think_ the framerate went from ~37 FPS to ~42 FPS right outside the first house you sleep in in the game.

This wasn't rigorous benchmarking or anything, just ran a couple games that run sub-par on my system with fps counters on and compared.

**Comment by xiota** [comment]
@niobium93 Thanks for testing.  Any other emulators you would like to try?  If -avx- builds were available, do you think you would use them?

**Comment by niobium93** [comment]
@xiota Most things I run in emulators already run at their fps cap so there isn't much of a need... If more optimized builds were available I'd install them though. I occasionally try out pretty much all the emulators for all the 3D systems, so I'll try to test whatever you build.
