### ISSUE TITLE
[Outdated] olive-git

### ISSUE THREAD

**Issue by anomalocaris452** [chaotic-aur/packages#2328]
### If available, link to the latest build

olive-git continuous.r2591.g2c2df9996-1

### Package name

olive-git

### Latest build

olive-git continuous.r2591.g2c2df9996-1

### Latest version available

continuous.r2518.g2d83beb2c-1

### Have you tested if the package
[PKGBUILD.txt](https://github.com/chaotic-aur/packages/files/10970524/PKGBUILD.txt)
 builds in a clean chroot?

- [X] Yes

### More information

Opentimelineio 0.15 gives problems  so   we'd disable it  
[PKGBUILD.txt](https://github.com/chaotic-aur/packages/files/10970523/PKGBUILD.txt)

**Comment by anomalocaris452** [comment]
so  wed just remove this line         -DOTIO_DEPS_INCLUDE_DIR=/usr/include/opentimelineio \

aka line 51

**Comment by dr460nf1r3** [comment]
Has the AUR maintainer been notified?

**Comment by dr460nf1r3** [comment]
Why don't you notify the AUR maintainer instead?
