### ISSUE TITLE
[Remove] clementine-git

### ISSUE THREAD

**Issue by themvl** [chaotic-aur/packages#2329]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/pkgbase/clementine-git

### Utility this package has for you

Playing music and maintaining music library. It has to be git version because of a bug of running on wayland on wlroots based systems.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
`clementine-git` no longer builds.  According to [comment](https://aur.archlinux.org/packages/clementine-git#comment-930484), Strawberry is a maintained fork of Clementine.  Since `strawberry-*` is in Chaotic, I plan to drop `clementine-git`.
