### ISSUE TITLE
[Bug] Broken package ananicy-rules

### ISSUE THREAD

**Issue by RubenKelevra** [chaotic-aur/packages#2332]
### What happens?

The package [ananicy-rules](https://aur.archlinux.org/packages/ananicy-rules) contains in line 15 the following dependency:

```
replaces=(ananicy-rules-git)
```

This is used, despite not beeing a replacement for ananicy-rules-git, as the git package does not have the same source:

Source for `ananicy-rules` is `https://github.com/CachyOS/ananicy-rules.git` and for `ananicy-rules-git` it is `https://github.com/kuche1/minq-ananicy`.

In addition the package `ananicy-rules` is a development package, but is not using the appropriate '-git' suffix, so the update process is broken.

I've noted both, and the misleading name, in the comment section of the package more than two weeks ago. There's no reaction by the maintainer.

Please remove `ananicy-rules` as it is blocking users from having `ananicy-rules-git` installed, as pacman will send on each update a replace-question to the users:

```
:: Replace ananicy-rules-git with chaotic-aur/ananicy-rules? [Y/n]
```

**Comment by dr460nf1r3** [comment]
Hey :) Sorry about missing the message on AUR. I removed the `replaces` for now, to have it renamed we need to file a request I guess.

**Comment by RubenKelevra** [comment]
Hey @dr460nf1r3,

thanks for the fast reaction!

>  to have it renamed we need to file a request I guess.

Well, you just create the package under the new name, and then file a rename request from the old to the new package.

In this case, the “replaces=" dependency should be placed in the new package, containing the old package name.

This will move everyone to the new package, if the new package is found by pacman in the database files. Just make sure to remove it after a while, as it would block other packages beeing published under the name “ananicy-rules”.

In any case, it would make sense to add a dependency to ananicy-cpp, as it is required to use your package.

**Comment by RubenKelevra** [comment]
Hey @dr460nf1r3,

[this is not enough](https://aur.archlinux.org/cgit/aur.git/commit/?h=ananicy-rules&id=7cde652b3b8742ba91b443a1ff1ac940e9297502) – you need to update the version to the last commit, and set `pkgrel` to 2, to push a new version to the repos of chaotic-aur.

**Comment by xiota** [comment]
`ananicy-rules` was dropped from AUR.  Replaced with `ananicy-rules-git`.  See #2513
