### ISSUE TITLE
[Outdated] obs-backgroundremoval

### ISSUE THREAD

**Issue by kenzer161** [chaotic-aur/packages#2333]
### If available, link to the latest build

[obs-backgroundremoval v0.5.14](https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.5.14)

### Package name

obs-backgroundremoval

### Latest build

0.4.0-1

### Latest version available

v0.5.14

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by dr460nf1r3** [comment]
The AUR package needs to be updated (and is flagged already).

**Comment by Technetium1** [comment]
I went to close this and realized it needed to be flagged again... [v0.5.19](https://github.com/royshil/obs-backgroundremoval/releases/tag/v0.5.19) is available
