### ISSUE TITLE
[Outdated] Rebuild the xfce4-docklike-plugin 

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#2334]
### If available, link to the latest build

https://aur.archlinux.org/packages/xfce4-docklike-plugin

### Package name

xfce4-docklike-plugin

### Latest build

0.4.1-1

### Latest version available

0.4.1-1

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### More information

The AUR maintainer pushed a buggy update and broke the plugin. He then quickly fixed it but in the meantime the chaotic-aur built the buggy version. The maintainer did not change the package version so the chaotic-aur does not know that the bugs have been fixed. So please rebuild it.

**Comment by dr460nf1r3** [comment]
Soon enough? :P Thanks for reporting!

**Comment by tio-trom** [comment]
Thanks for the update!
