### ISSUE TITLE
[Request] Emacs development master branch build with nativecomp and no-pgtk (and with xwidgets)

### ISSUE THREAD

**Issue by emacsomancer** [chaotic-aur/packages#2335]
### Link to the package base(s) in the AUR

[emacs-git-noway-widgets](https://aur.archlinux.org/packages/emacs-git-noway-widgets)

### Utility this package has for you

The current Emacs development master branch builds in the Chaotic AUR have either no nativecomp or nativecomp but with pgtk. I want nativecomp, but pgtk doesn't work for my setup. (Plus this build also has xwidget support which is useful for a number of things.)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by emacsomancer** [comment]
What is the Chaotic AUR (re)build cycle for `devel`/`git` packages? Or do they only get rebuilt when the AUR package itself/the PKGBUILD is changed?

**Comment by dr460nf1r3** [comment]
Usually, `-git` packages are getting rebuilt hourly (given they aren't too heavy and therefore daily). Is something off about the schedule?

**Comment by emacsomancer** [comment]
Ah, is the issue here that `-git-` is in the  middle the package name and not the end? (since it doesn't seem to have been rebuilt since 2023-03-27: https://builds.garudalinux.org/repos/chaotic-aur/logs/emacs-git-noway-widgets.log )

**Comment by dr460nf1r3** [comment]
Oh yes, that's exactly the issue! Non `-git` packages require a workaround, as repoctl would assume the package is up to date based on its PKGBUILD pkgver.

**Comment by emacsomancer** [comment]
Is there a way to manually mark this one as a `-git`/devel type, or would the package name need to change?

**Comment by dr460nf1r3** [comment]
Yes, in fact, there is! :)

**Comment by emacsomancer** [comment]
Cheers! That's excellent.
