### ISSUE TITLE
[Request] jameica - HBCI online banking for Germany

### ISSUE THREAD

**Issue by Orko79** [chaotic-aur/packages#2339]
### Link to the package base(s) in the AUR

[jameica AUR](https://aur.archlinux.org/packages/jameica)

[jameica website](https://www.willuhn.de/)

### Utility this package has for you

It's an easy to use and secure HBCI online banking tool for Germany. It is **way** easier to set up and use as for example GnuCash or KMyMoney. Not only that, but everything is protected with a master password. GnuCash and KMyMoney don't have any data protection! At least I couldn't figure out how to protect my data with these two. Jameica has its own plugin-repos. Plugins can be installed in the settings. 

I'm using it for about 2 years now as flatpak. It worked without any issues all the time. It gets regularly updates. It would be great to have it the repos :+1: 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Licenses: GPL2

**Comment by Technetium1** [comment]
Including: [java-jce_ustrength ](https://aur.archlinux.org/packages/java-jce_ustrength) – `Required for mashup plugin used as new scripting platform for non-HBCI accounts (credit cards etc)`
