### ISSUE TITLE
[Request] Switch to Python3.11/3.12 helper packages

### ISSUE THREAD

**Issue by RubenKelevra** [chaotic-aur/packages#2342]
### Link to the package base(s) in the AUR

[python311-as-default-interpreter](https://aur.archlinux.org/packages/python311-as-default-interpreter)

[python312-as-default-interpreter](https://aur.archlinux.org/packages/python312-as-default-interpreter)

### Utility this package has for you

I made those two helper packages, which actually just contain the necessary symbolic links and conflict the system-python version.

By installing these, the python3.10 version currently offered by archlinux will be removed and the python311/312 version from the AUR/Chaotic-AUR will be fetched.

As the Chaotic-AUR currently only offers python311, I think only this package makes sense to add.

Hope you guys find this an useful addition. :)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Why `python312-as-default-interpreter` if `python312` is not in chaotic-aur?

**Comment by Edu4rdSHL** [comment]
Having these packages on the repo somehow promotes system's breakages with something that's unneeded, these packages doesn't even need to be built or whatever, so it doesn't make any sense to have them in the repos.

If someone wants to use them, just install from AUR, knowing all the risk that making that change implies.
