### ISSUE TITLE
[Request] Remove python38, python39 

### ISSUE THREAD

**Issue by xiota** [chaotic-aur/packages#2344]
Request removal of `python38` and `python39`.  They were added as [dependencies](https://github.com/chaotic-aur/packages/blob/eee9e37ba44f0f26d1d3af5619d41b53cd608ed0/ufscar-hpc/hourly.2.txt#L399-L401) for `bombsquad` (#320).  Since `bombsquad` now works fine with `core/python`, the dependencies can be removed.

**Comment by Technetium1** [comment]
I use `python39` for https://github.com/Cog-Creators/Red-DiscordBot
