### ISSUE TITLE
[Request] adw-gtk3

### ISSUE THREAD

**Issue by Gontier-Julien** [chaotic-aur/packages#2351]
### Link to the package base(s) in the AUR

[adw-gtk3](https://aur.archlinux.org/packages/adw-gtk3)

### Utility this package has for you

Make gtk3 consistent with gt4 (libadwaita)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

I think it would be also great to replace `adw-gtk3-git` (which is on the repo) in favor of the stable version.

**Comment by xiota** [comment]
Dropping because duplicate of `extra/adw-gtk-theme`.
