### ISSUE TITLE
[Request] goldendict-webengine-git

### ISSUE THREAD

**Issue by asakura42** [chaotic-aur/packages#2352]
### Link to the package base(s) in the AUR

[goldendict-webengine-git](https://aur.archlinux.org/packages/goldendict-webengine-git)

### Utility this package has for you

goldendict-webengine-git is a nice fork of well-known goldendict dictionary program that adds many features like Anki support and so on.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Does not build in clean chroot:
```
==> Starting prepare()...
==> Starting pkgver()...
==> Updated version: goldendict-webengine-git 23.02.07.alpha.230402.8f1f630f.r3.g51b46ca0-1
==> Starting build()...
Info: creating stash file /build/goldendict-webengine-git/src/goldendict-webengine-git/.qmake.stash
v23.02.07-alpha.230402.8f1f630f-3-g51b46ca0-dirty
Project MESSAGE: generate version.txt....
Project MESSAGE: Install Prefix is: /usr
Project ERROR: Unknown module(s) in QT: texttospeech
==> ERROR: A failure occurred in build().
    Aborting...
```

Also, see [#1686](https://github.com/chaotic-aur/packages/issues/1686).  `goldendict-webengine-pr-git` is in chaotic-aur.

**Comment by tatsumoto-ren** [comment]
>Does not build in clean chroot:
>Unknown module(s) in QT: texttospeech

There are missing dependenices in the PKGBUILD. 

> `goldendict-webengine-pr-git` is in chaotic-aur

The main advantage of `goldendict-webengine-git` is that it has better Anki support. So it would be nice to have it in chaotic-aur as well.

**Comment by shenlebantongying** [comment]
@xiota I have fixed the PKGBUILD.

> goldendict-webengine-pr-git

Based on star/vote number. That one is not the right web engine port XD

**Comment by Technetium1** [comment]
Name will change soon, let's add it after:

> slbtty commented on [2023-04-17 05:42 (EDT)](https://aur.archlinux.org/packages/goldendict-webengine-git#comment-910701)
I have filed a request to change the name from `goldendict-webengine-git` to `goldendict-ng-git`
