### ISSUE TITLE
[Request] loupe-git

### ISSUE THREAD

**Issue by flipflop97** [chaotic-aur/packages#2363]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/pkgbase/loupe-git

### Utility this package has for you

This is the new image viewer for GNOME, which will soon replace the old one.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
`loupe` was dropped from AUR with recommendation to switch to `loupe-git`.  Unfortunately, the git package doesn't build because `libadwaita` dependency issue.
