### ISSUE TITLE
[Request] pcem

### ISSUE THREAD

**Issue by flookymonster** [chaotic-aur/packages#2369]
### Link to the package base(s) in the AUR

[https://aur.archlinux.org/packages/pcem](https://aur.archlinux.org/packages/pcem)

### Utility this package has for you

An emulator for classic IBM PC clones with lots of features, built in manager and ROMs

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

GPL2

**Comment by xiota** [comment]
Switching to `pcem-git` because stable package failing to build.  It was released 2.5 years ago.
