### ISSUE TITLE
[Request] o3de

### ISSUE THREAD

**Issue by bibliothec** [chaotic-aur/packages#2370]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/o3de-bin

### Utility this package has for you

Open 3D Engine - An open-source, real-time 3D development engine.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

MIT, Apache-2.0 License

**Comment by Technetium1** [comment]
Sorry, this is way too big for us at 4.7GB+
