### ISSUE TITLE
[Outdated] ryujinx-git

### ISSUE THREAD

**Issue by bayazidbh** [chaotic-aur/packages#2371]
### If available, link to the latest build

[ryujinx-git](https://builds.garudalinux.org/repos/chaotic-aur/logs/ryujinx-git.log)

### Package name

ryujinx-git

### Latest build

r2641.ecee34a50-1

### Latest version available

r2694.49be97758-1

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### More information

<details><summary>dotnet dependencies</summary><p>

aur/dotnet-host-preview-bin                      8.0.0.sdk100+preview.2-1 
aur/dotnet-runtime-bin                           7.0.4.sdk202-1
aur/netstandard-targeting-pack-bin               7.0.4.sdk202-1
aur/dotnet-targeting-pack-bin                    7.0.4.sdk202-1
aur/dotnet-sdk-bin                               7.0.4.sdk202-1
aur/ryujinx-git

</p></details>

Latest build process seems to have failed, based on the log. Looking at my log, built via distrobox, there is a newer dotnet version it depends on. It resulted in some manual intervention required due to dotnet version mismatch, but it did build correctly in the end.

Update is pretty relevant, since it seems they have recently [fixed Wayland issues](https://github.com/Ryujinx/Ryujinx/issues/2714#issuecomment-1482752923), and I've confirmed it's working on distrobox arch on Nobara 37 KDE Wayland.

**Comment by xiota** [comment]
Could this be fixed by removing the `ryujinx-git` interfere and adding (back) `dotnet-core-bin`?

**Comment by xiota** [comment]
According to `pacman -Sii ryujinx-git`, the last successful build was on yesterday (Wed May 3 08:11:00 2023).

**Comment by dr460nf1r3** [comment]
```
==> Updated version: ryujinx-git r2746.6279f5e43-1
==> ERROR: A package has already been built. (use -f to overwrite)
```
Logs are showing the same, very cool :)
