### ISSUE TITLE
[Outdated] python-spotdl

### ISSUE THREAD

**Issue by kamack38** [chaotic-aur/packages#2373]
### If available, link to the latest build

[python-spotdl](https://builds.garudalinux.org/repos/chaotic-aur/logs/python-spotdl.log)

### Package name

python-spotdl

### Latest build

`4.0.7-2`

### Latest version available

`4.1.3-1`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by dr460nf1r3** [comment]
```
error: target not found: python-pykakasi
error: target not found: python-syncedlyrics
```

**Comment by Evan-aja** [comment]
@dr460nf1r3 this package should be able to build now that both dependencies are in the chaotic repository

**Comment by kamack38** [comment]
I'm closing this issue since the problem has been resolved.

**Comment by Technetium1** [comment]
This was fixed by https://github.com/chaotic-aur/packages/commit/c26da518804654a04ee43cb83148990fb753a5fc
