### ISSUE TITLE
[Request]  asbru-cm-git

### ISSUE THREAD

**Issue by mauriciodelima21** [chaotic-aur/packages#2374]
### Link to the package base(s) in the AUR

[asbru-cm](https://aur.archlinux.org/asbru-cm.git)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
According to docs the master branch is kept as stable as possible. These are deps for `asbru-cm-git`:
```
uuid
perl-crypt-rijndael
perl-net-arp
perl-io-stty
perl-x11-guitest
perl-expect
```
