### ISSUE TITLE
[Request] ripcord

### ISSUE THREAD

**Issue by flookymonster** [chaotic-aur/packages#2375]
### Link to the package base(s) in the AUR

[https://aur.archlinux.org/packages/ripcord](https://aur.archlinux.org/packages/ripcord)

### Utility this package has for you

Qt-based Discord and Slack client.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

[Please read the redistribution terms.](https://cancel.fm/ripcord/shareware-redistribution/)

**Comment by xiota** [comment]
Tagged `library:eol` because uses EOL Qt5, but not dropping (for now) because the libraries are vendored.  Metrics 13.
