### ISSUE TITLE
[Remove] smtube

### ISSUE THREAD

**Issue by robson-66** [chaotic-aur/packages#2382]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/smtube

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Will only need to mark existing dep `qt5-webkit`

**Comment by xiota** [comment]
Dropping because #3157.  Also, `qt5-webkit` is broken.
