### ISSUE TITLE
[Request] obs-studio-amf

### ISSUE THREAD

**Issue by KryptoSynth** [chaotic-aur/packages#2384]
### Link to the package base(s) in the AUR

[obs-studio-amf](https://aur.archlinux.org/packages/obs-studio-amf)

### Utility this package has for you

It allows usage of the AMF hardware encoder in OBS Studio for AMDGPU users.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by FabioLolix** [comment]
This require pkgbase=amdgpu-pro-installer (amf-amdgpu-pro amdgpu-pro-oglp lib32-amdgpu-pro-oglp vulkan-amdgpu-pro lib32-vulkan-amdgpu-pro) which have been recently dropped https://github.com/chaotic-aur/packages/pull/2367

**Comment by dr460nf1r3** [comment]
Yup, I didn't have a closer look yet but that's pretty much a dealbreaker then. Thanks!
