### ISSUE TITLE
[Request] maestral, maestral-qt

### ISSUE THREAD

**Issue by mauriciodelima21** [chaotic-aur/packages#2387]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/maestral-qt
... https://aur.archlinux.org/packages/maestral

Depends:
https://aur.archlinux.org/packages/python-desktop-notifier
... https://aur.archlinux.org/pkgbase/python-sphinx_mdinclude

https://aur.archlinux.org/packages/python-pyro5

https://aur.archlinux.org/packages/python-survey
... https://aur.archlinux.org/packages/python-sphinx-paramlinks
... https://aur.archlinux.org/packages/python-wrapio

### Utility this package has for you

coxackie: The use case is having dropbox synced to filesystems outside ext4, which is the only one officially supported by official dropbox. As a side benefit, maestral (headless) takes up less than 1/3 of the memory that official dropbox does. It is, in general and many ways, much lighter.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by dr460nf1r3** [comment]
Whats the desired use case?

**Comment by Technetium1** [comment]
@dr460nf1r3 it should compile to a very small size, but deps I didn't check size of: 
```
maestral        python-survey
maestral        python-pyro5
python-desktop-notifier python-m2r2
python-survey   python-wrapio
maestral        python-desktop-notifier
python-m2r2     python-mistune1
```

@mauriciodelima21 What about https://aur.archlinux.org/packages/maestral-qt ? Is it required for a user interface?

**Comment by coxackie** [comment]
@Technetium1 let me chip in here. `maestral-qt` is required for the GUI, but `maestral` can be used without it, through CLI. I just built it - it was successful, and deps are also of small size, but it was a bit of a pain to biuld individually the AUR dependencies. When I tried to do it through `paru` it somehow failed, so I had to do everything manually. It would be *greatly* appreciated if you could include this is chaotic.

**Comment by coxackie** [comment]
Any updates here?

**Comment by xiota** [comment]
This issue predates me, but my problem would be that no one answered, "Whats the desired use case?"

I'll try building it while someone maybe works on describing what makes this program great.

**Comment by coxackie** [comment]
@xiota mainly, the use case is having dropbox synced to filesystems outside ext4, which is the only one officially supported by official `dropbox`. As a side benefit, `maestral` (headless) takes up less than 1/3 of the memory that official `dropbox` does. It is, in general and many ways, much lighter. Do the previous make this worthwhile?

**Comment by xiota** [comment]
@coxackie That's helpful.  Thank you.

I also see you built this previously.  When you request or build packages in the future, it helps to list the AUR-based dependencies.  I'm already done sorting through them, so not needed now.  (I know this is not your request.  It's just FYI.)

**Comment by xiota** [comment]
Packages have been built and available in repo, but not added to lists.

* `python-desktop-notifier`, is missing depends on `python-setuptools`.

```
python-sphinx_mdinclude:https://aur.archlinux.org/python-sphinx_mdinclude.git # (make python-desktop-notifier)
python-desktop-notifier # (dep maestral)
python-sphinx-paramlinks # (make python-survey)
python-wrapio # (dep python-survey)
python-pyro5 # (dep maestral)
python-survey # (dep maestral)
maestral # (dep maestral-qt)
maestral-qt # (opt maestral)
```
