### ISSUE TITLE
[Request] lemurs-git

### ISSUE THREAD

**Issue by IroAlexis** [chaotic-aur/packages#2388]
### Link to the package base(s) in the AUR

[lemurs-git](https://aur.archlinux.org/packages/lemurs-git)

### Utility this package has for you

A customizable terminal display manager in Rust

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Nice!
