### ISSUE TITLE
[Request] qlcplus

### ISSUE THREAD

**Issue by bibliothec** [chaotic-aur/packages#2392]
### Link to the package base(s) in the AUR

http://aur.archlinux.org/packages/qlcplus

### Utility this package has for you

Q Light Controller Plus - The open DMX lighting desk software for controlling professional lighting fixtures.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Switched to custom package to fix build failure and switch to Qt6.  Metrics 5.

**Comment by xiota** [comment]
Switching to `aur/qlcplus-git`.

Metrics of `qlcplus-qt6-git`, 45
