### ISSUE TITLE
[Bug] amd-ucode-git fails to update

### ISSUE THREAD

**Issue by toreopp** [chaotic-aur/packages#2395]
### What happens?

amd-ucode-git fails to update

### What is expected to happen?

amd-ucode-git gets updated

### If possible, please attach logs

:: Synkroniserer pakkedatabaser...
garuda er oppdatert
core er oppdatert
extra er oppdatert
community er oppdatert
multilib er oppdatert
chaotic-aur                             2,4 MiB  4,65 MiB/s 00:01 [------------------------------------] 100%
blackarch er oppdatert

--> Refreshing mirrorlists using rate-mirrors, please be patient..🍵
:: Synkroniserer pakkedatabaser...
laster ned garuda...
laster ned core...
laster ned extra...
laster ned community...
laster ned multilib...
laster ned chaotic-aur...
laster ned blackarch...
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (1) amd-ucode-git-20230418.8451c2b1-1

Total Download Size:   0.04 MiB
Total Installed Size:  0.05 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst failed to download
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from cdn-mirror.chaotic.cx :Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from geo-mirror.chaotic.cx :Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from au-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from au-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from br-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from br-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from br-3-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from br-4-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from bg-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from ca-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from ca-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from ca-3-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from ch-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from cl-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from cl-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from fr-1-mirror.chaotic.cx : The requested URL returned error: 404
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from fr-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from fr-3-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from de-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from de-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from de-3-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from de-4-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from de-5-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from de-6-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from gr-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from in-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from in-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from in-3-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from in-4-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from in-5-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from in-6-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from il-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from jp-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from jp-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from kr-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from kr-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from mx-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from nl-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from sa-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from za-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from es-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from es-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from es-3-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from se-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from ae-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from ae-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from ae-3-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from uk-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from uk-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from us-ca-mirror.chaotic.cx: Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from us-fl-mirror.chaotic.cx: Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from us-mi-mirror.chaotic.cx: Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from us-ny-mirror.chaotic.cx: The requested URL returned error: 404
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from us-tx-mirror.chaotic.cx: Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from us-tx-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from us-ut-mirror.chaotic.cx: Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from us-va-mirror.chaotic.cx: Maximum file size exceeded
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.

--> Some downloads failed. Retrying...

:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (1) amd-ucode-git-20230418.8451c2b1-1

Total Download Size:   0.04 MiB
Total Installed Size:  0.05 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst failed to download
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from cdn-mirror.chaotic.cx :Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from geo-mirror.chaotic.cx :Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from au-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from au-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from br-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from br-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from br-3-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from br-4-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from bg-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from ca-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from ca-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from ca-3-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from ch-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from cl-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from cl-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from fr-1-mirror.chaotic.cx : The requested URL returned error: 404
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from fr-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from fr-3-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from de-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from de-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from de-3-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from de-4-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from de-5-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from de-6-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from gr-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from in-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from in-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from in-3-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from in-4-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from in-5-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from in-6-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from il-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from jp-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from jp-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from kr-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from kr-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from mx-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from nl-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from sa-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from za-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from es-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from es-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from es-3-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from se-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from ae-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from ae-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from ae-3-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from uk-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from uk-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from us-ca-mirror.chaotic.cx: Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from us-fl-mirror.chaotic.cx: Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from us-mi-mirror.chaotic.cx: Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from us-ny-mirror.chaotic.cx: The requested URL returned error: 404
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from us-tx-mirror.chaotic.cx: Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from us-tx-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from us-ut-mirror.chaotic.cx: Maximum file size exceeded
error: failed retrieving file 'amd-ucode-git-20230418.8451c2b1-1-any.pkg.tar.zst' from us-va-mirror.chaotic.cx: Maximum file size exceeded
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.
Press enter to exit

### More information

Am i doing something wrong here?

**Comment by dr460nf1r3** [comment]
You did nothing wrong, the package needed to be rebuilt due to an error.
