### ISSUE TITLE
[Remove] cosmic-epoch-git

### ISSUE THREAD

**Issue by caniko** [chaotic-aur/packages#2397]
### Link to the package base(s) in the AUR

[cosmic-epoch-git](https://aur.archlinux.org/packages/cosmic-epoch-git)

### Utility this package has for you

It is a DE

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Problem building: [cosmic-epoch-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/cosmic-epoch-git.log)
```
==> Starting prepare()...
Falling back to direct application...
error: patch failed: cosmic-comp:1
error: cosmic-comp: patch does not apply
==> ERROR: A failure occurred in prepare().
```

**Comment by xiota** [comment]
@dr460nf1r3 @PedroHLC I noticed similar problem with some other packages.  [`cosmic-epoch-git.log`](https://github.com/chaotic-aur/packages/files/13723834/cosmic-epoch-git.log)

```
LLVM ERROR: IO failure on output stream: No space left on device
```

**Comment by Daktyl198** [comment]
I hate to post an "any progress?" comment, but I can't get the AUR package to build on my system and was looking to try out the latest changes.

The current version on chaotic-aur is quite old at this point. It may be better to remove it until it's fixed/updated, so that those trying to download the latest version don't have to manually use the -Sa flag on an AUR helper.

**Comment by xiota** [comment]
Rebuilt manually.  Requires ~65GB space.  tmpfs overlay has only 25GB.  Hence the disk space error.

This is pre-alpha software that isn't currently worth the effort required to keep builds up to date.

Dropping from package lists.  Leaving the current build in the repo for now.  Will eventually remove it entirely.

**Comment by PedroHLC** [comment]
@xiota maybe add it to ufscar's daily.

**Comment by Daktyl198** [comment]
According to their last posted roadmap, their "alpha" is meant to be feature locked and treated more like a beta. I don't know why they're doing it that way, but alpha might be a good time to look into it again.

**Comment by Technetium1** [comment]
@xiota what was the final size, excluding build env? This could go to ufscar daily if it's not too huge. This is about as 'beta' as it's ever going to get 🙃

**Comment by xiota** [comment]
@Daktyl198 Feel free to ping me here when you feel there is evidence that the program may be in a "usable" state.  For now, a build from earlier today is in the repo for testing.

**Comment by xiota** [comment]
```
$ pacman -Si cosmic-epoch-git | grep Date
Build Date      : Thu Feb 22 06:34:30 2024
```

**Comment by xiota** [comment]
I guess will have to wait for the update next month.
```
   Compiling cosmic-screenshot v0.1.0 (/home/main-builder/pkgwork/src/cosmic-epoch/cosmic-screenshot)
    Finished release [optimized] target(s) in 18.53s
/usr/bin/just cosmic-settings/build-release
cargo build --release
error: could not find `Cargo.toml` in `/home/main-builder/pkgwork/src/cosmic-epoch` or any parent directory
error: Recipe `build-debug` failed on line 32 with exit code 101
error: Recipe `build` failed on line 20 with exit code 101
==> ERROR: A failure occurred in build().
```

**Comment by xiota** [comment]
```
install: cannot stat '/home/main-builder/pkgwork/src/cosmic-epoch/target/release/cosmic-settings': No such file or directory
error: Recipe `install-cmd` failed on line 4 with exit code 1
error: Recipe `sysext` failed on line 44 with exit code 1
==> ERROR: A failure occurred in build().
```

**Comment by Technetium1** [comment]
`r137.7348756-1` now available

**Comment by xiota** [comment]
Some packages build okay on v3 but not v4... and vice versa.

**Comment by dr460nf1r3** [comment]
Key difference might be that we build in Docker containers and not systemd-nspawn. I'm not sure how this affects compilation however. If it's missing capabilities, we need to figure out which ones 🤔

**Comment by xiota** [comment]
v3 builder has been down a few days.  v4 builder should be ready "soon" and is able to build this package.

**Comment by dr460nf1r3** [comment]
This is due to the mentioned cache issue ("XYZ could not be found) ? I believe I just fixed this one 🤔

**Comment by xiota** [comment]
New issue for `cosmic-session-git` #3217
