### ISSUE TITLE
[Request] cyberchef-electron

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2398]
### Link to the package base(s) in the AUR

[cyberchef-electron](https://aur.archlinux.org/packages/cyberchef-electron)

### Utility this package has for you

This tool is the best tool for decoding used in a lot of activities (i.e., CTF, job purposes, decoding and encoding).

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
Absolutely, just as soon as it's updated!

**Comment by D3vil0p3r** [comment]
> Absolutely, just as soon as it's updated!

Hey @Technetium1 I managed the package and now it is updated on AUR.

**Comment by Technetium1** [comment]
GitHub has failed me once again, the commit didn't link correctly. This was just now added in: https://github.com/chaotic-aur/packages/commit/4b234e486d60efda292121dd72c2d4244e574a58
