### ISSUE TITLE
[Bug] pix

### ISSUE THREAD

**Issue by mdhishamsayed** [chaotic-aur/packages#2399]
### What happens?

Pix needs libtiff5
on starting after default installation, therein it displays a error
```
❯ administrator@Optiplex in ~ took 276ms
 ➜ pix

(pix:77660): Gtk-WARNING **: 12:32:22.511: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client

(pix:77660): GLib-GObject-CRITICAL **: 12:32:22.564: g_type_class_add_private() called multiple times for the same type

** (pix:77660): CRITICAL **: 12:32:22.576: Could not load the mandatory extension 'cairo_io': Could not open the module `cairo_io`: libtiff.so.5: cannot open shared object file: No such file or directory
zsh: IOT instruction (core dumped)  pix
```
the package "libtiff" needs to be installed, but it is not present in the dependencies section of pkguild
A workaround may be adding the package to interfere, appending libtiff to the pkgbuild
once installing that package, the app launches correctly

### What is expected to happen?

PIX must launch

### More information

Pix version 2.8.9-1

**Comment by FabioLolix** [comment]
> Pix needs libtiff5

It works fine with a rebuild, no libtiff5 package required

**Comment by Technetium1** [comment]
`Finished making: pix 2.8.9-1.2 (Fri 05 May 2023 01:09:22 AM CEST)`
