### ISSUE TITLE
[Request] PHP 7.3.33

### ISSUE THREAD

**Issue by Bhooty** [chaotic-aur/packages#2400]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/php73-cli

### Utility this package has for you

I need this package since I have some projects of Web running old version of php. Would be great if it can be included.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Would be great if u can compile the other packages of php73 if possible cause sometimes require modules.
https://aur.archlinux.org/packages?O=0&K=php73

**Comment by xiota** [comment]
@Bhooty Do you still need PHP 7.x?  Do you need specifically PHP 7.3.x (`aur/php73`)?  Or would PHP 7.4.x work (`aur/php74`)?

**Comment by gpodder770** [comment]
> @Bhooty Do you still need PHP 7.x? Do you need specifically PHP 7.3.x (`aur/php73`)? Or would PHP 7.4.x work (`aur/php74`)?

Specifically 7.3.* because of projects

**Comment by xiota** [comment]
Planning to drop because failing to build.  Also, PHP 7.3 was EOL in 2021 with new security advisories this year.
```
/home/main-builder/pkgwork/src/php-7.3.33/main/reentrancy.c:125:9: error: too few arguments to function readdir_r
  125 |         readdir_r(dirp, entry);
```

**Comment by dr460nf1r3** [comment]
Since the requesting person doesn't exist anymore anyways, it's a good candidate for dropping right away.

**Comment by xiota** [comment]
Will remove from lists.  Can leave the package in the repo if it's still working.

**Comment by Technetium1** [comment]
I removed it entirely.
