### ISSUE TITLE
[Outdated] yuzu-early-access

### ISSUE THREAD

**Issue by dnmodder** [chaotic-aur/packages#2405]
### If available, link to the latest build

[yuzu-early-access.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/yuzu-early-access.log)

### Package name

yuzu-early-access

### Latest build

3515-1

### Latest version available

3531-1

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by Technetium1** [comment]
```c
-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE)
```
I left a [comment for the maintainer](https://aur.archlinux.org/packages/yuzu-early-access#comment-911878). It somehow still built though 🤨

```
==> Finished making: yuzu-early-access 3531-1 (Thu 27 Apr 2023 02:39:17 AM CEST)
```
