### ISSUE TITLE
Confirming validity of current entries in interfere

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#2406]
<details><summary><b>Interferes</b> (checked)</summary>

- [x] ~~`afdko`~~
- [x] ~~`anbox-git`~~
- [x] ~~`ant-dracula-theme-git`~~
- [x] ~~`apparmor-git`~~
- [x] ~~`ark-git`~~
- [x] ~~`asusctl-git`~~
- [x] ~~`athenaeum-git`~~
- [x] `auracle-git`
- [x] ~~`ayatana-indicator-session`~~
- [x] ~~`blender-git`~~
- [x] `bluespec-bdw-git`
- [x] `bluespec-contrib-git`
- [x] `bluespec-git`
- [x] ~~`bluez-git`~~
- [x] ~~`btrfs-progs-git`~~
- [x] ~~`budgie-screenshot-applet`~~
- [x] ~~`cachyos-ananicy-rules`~~
- [x] `chaotic-keyring`
- [x] `chaotic-mirrorlist`
- [x] `cheese-git`
- [x] ~~`chrome-gnome-shell`~~
- [x] ~~`clifm-git`~~
- [x] ~~`coreutils-git`~~
- [x] ~~`cryptomator`~~
- [x] ~~`davinci-resolve-studio`~~
- [x] ~~`davinci-resolve`~~
- [x] ~~`dbus-x11`~~
- [x] ~~`decaf-emu-git`~~
- [x] ~~`deluge-git`~~
- [x] ~~`digital`~~
- [x] ~~`distrho-ports-lv2-git`~~
- [x] ~~`distrho-ports-vst-git`~~
- [x] ~~`doomseeker`~~
- [x] `element-desktop-git`
- [x] ~~`emacs-git`~~
- [x] ~~`emacs-ng-git`~~
- [x] ~~`emacs-pgtk-native-comp-git`~~
- [x] ~~`epiphany-git`~~
- [x] ~~`etl-dev`~~
- [x] ~~`exo-git`~~
- [x] ~~`extra-cmake-modules-git`~~
- [x] ~~`fancontrol-gui-git`~~
- [x] ~~`fancontrol-kcm-git`~~
- [x] ~~`fastgame-git`~~
- [x] `ffmpeg-full`
- [x] ~~`filelight-git`~~
- [x] ~~`firedragon-beta-znver2`~~
- [x] `firedragon`
- [x] ~~`firejail-git`~~
- [x] ~~`fish-git`~~
- [x] ~~`flatseal`~~
- [x] `fluffychat`
- [x] ~~`fondo`~~
- [x] ~~`freecad-git`~~
- [x] ~~`freetube`~~
- [x] ~~`freezer-git`~~
- [x] ~~`friture-git`~~
- [x] ~~`gala-git`~~
- [x] ~~`gamescope-git`~~
- [x] ~~`gcc-git`~~
- [x] ~~`gdm-plymouth`~~
- [x] `gdm-prime`
- [x] ~~`gdmap-gtk3`~~
- [x] ~~`gimp-elsamuko-git`~~
- [x] ~~`gis-weather-git`~~
- [x] ~~`gjs-git`~~
- [x] ~~`glaxnimate-git`~~
- [x] ~~`glibc-eac`~~
- [x] ~~`gnome-text-editor-git`~~
- [x] ~~`godot-export-templates-git`~~
- [x] ~~`godot-mono`~~
- [x] ~~`goodvibes-git`~~
- [x] ~~`goodvibes`~~
- [x] ~~`gtk4-git`~~
- [x] ~~`guestfs-tools`~~
- [x] ~~`gyroflow-git`~~
- [x] ~~`hal-git`~~
- [x] `handbrake-nvenc`
- [x] ~~`health`~~
- [x] ~~`helvum-git`~~
- [x] ~~`ialauncher-git`~~
- [x] ~~`icoextract`~~
- [x] ~~`imagemagick-git`~~
- [x] ~~`irpf`~~
- [x] ~~`java-jbr-xdg`~~
- [x] ~~`jellyfin-media-player-git`~~
- [x] ~~`jitsi-meet-desktop`~~
- [x] ~~`kawaii-player`~~
- [x] ~~`kid3-cli`~~
- [x] ~~`lbry-app-bin`~~
- [x] ~~`libadwaita-git-pkgs`~~
- [x] ~~`libelectron`~~
- [x] ~~`libfprint-git`~~
- [x] ~~`libquotient-git`~~
- [x] ~~`libretro-mame-git`~~
- [x] ~~`libshumate-git`~~
- [x] ~~`libxc`~~
- [x] ~~`libxvct-git`~~
- [x] ~~`lutris-git`~~
- [x] `matrix-registration`
- [x] ~~`matrix-synapse-git`~~
- [x] ~~`matrix-synapse-rest-auth`~~
- [x] ~~`mcomix-git`~~
- [x] ~~`megasync`~~
- [x] ~~`meteo-qt-git`~~
- [x] ~~`mingw-w64-gcc`~~
- [x] `monkeysphere`
- [x] `mpv-full-git`
- [x] ~~`msitools`~~
- [x] ~~`mutter-git`~~
- [x] ~~`natron-bin`~~
- [x] ~~`natron-plugins-git`~~
- [x] ~~`nautilus-git`~~
- [x] ~~`nautilus-typeahead`~~
- [x] `nestopia`
- [x] ~~`networkmanager-iwd`~~
- [x] ~~`nextcloud-client-git`~~
- [x] ~~`nheko-git`~~
- [x] `nspr-hg`
- [x] `nss-hg`
- [x] ~~`ntfs2btrfs-git`~~
- [x] ~~`nuclear-player-bin`~~
- [x] `nyrna`
- [x] ~~`obs-hevc-vaapi-git`~~
- [x] `obs-vkcapture-git`
- [x] ~~`onefetch-git`~~
- [x] ~~`onivim2-git`~~
- [x] `openal-git`
- [x] ~~`openvpn3`~~
- [x] ~~`optimus-manager-qt`~~
- [x] ~~`otter-browser-git`~~
- [x] ~~`p7zip-gui`~~
- [x] ~~`pacman-auto-update`~~
- [x] ~~`pamac-aur-git`~~
- [x] ~~`pamac-aur`~~
- [x] ~~`pantheon-mail`~~
- [x] ~~`papirus-folders-gui`~~
- [x] ~~`pdf-decrypt`~~
- [x] ~~`peazip-qt5`~~
- [x] ~~`pebbles-git`~~
- [x] ~~`perl-x11-guitest`~~
- [x] ~~`phosh-git`~~
- [x] ~~`phosh`~~
- [x] ~~`php80`~~
- [x] ~~`plasma5-theme-sweet-git`~~
- [x] ~~`plasma5-wallpapers-wallpaper-engine-without-mpv-git`~~
- [x] ~~`plasma5-wallpapers-wallpaper-engine`~~
- [x] ~~`play.it`~~
- [x] ~~`plots`~~
- [x] ~~`pokete-git`~~
- [x] ~~`polkit-qt5-git`~~
- [x] ~~`popcorntime-git`~~
- [x] ~~`power-profiles-daemon`~~
- [x] `powershell`
- [x] ~~`prjtrellis-git`~~
- [x] ~~`protontricks-git`~~
- [x] ~~`psautohint`~~
- [x] ~~`pulseeffects-git`~~
- [x] ~~`python-asttokens`~~
- [x] ~~`python-awesometkinter`~~
- [x] ~~`python-chess-git`~~
- [x] ~~`python-colorzero`~~
- [x] ~~`python-constraint`~~
- [x] ~~`python-fastdtw`~~
- [x] ~~`python-fontparts`~~
- [x] ~~`python-fonttools-git`~~
- [x] ~~`python-html-sanitizer`~~
- [x] ~~`python-murmurhash`~~
- [x] ~~`python-nbxmpp-git`~~
- [x] ~~`python-poetry-core-git`~~
- [x] ~~`python-pympv`~~
- [x] ~~`python-pyscf`~~
- [x] ~~`python-symdom-git`~~
- [x] ~~`python-torchvision`~~
- [x] ~~`python-urlgrabber`~~
- [x] ~~`qbittorrent-enhanced-git`~~
- [x] ~~`qogir-icon-theme-git`~~
- [x] ~~`qtile-extras-git`~~
- [x] `qtile-git`
- [x] ~~`quaternion-git`~~
- [x] ~~`quaternion`~~
- [x] ~~`radeon-profile-git`~~
- [x] ~~`redshift-minimal`~~
- [x] ~~`rofi-lbonn-wayland`~~
- [x] `rpcs3-git`
- [x] ~~`ruby-gettext-setup`~~
- [x] ~~`ruby-gettext`~~
- [x] ~~`rum-git`~~
- [x] ~~`rum`~~
- [x] ~~`samba-mounter-git`~~
- [x] ~~`sayonara-player-git`~~
- [x] ~~`scrap_engine-git`~~
- [x] ~~`sddm-config-editor-git`~~
- [x] ~~`shadowsocks-rust-git`~~
- [x] ~~`signalbackup-tools-git`~~
- [x] `siril-git`
- [x] ~~`spidermonkey-git`~~
- [x] ~~`spot-client-git`~~
- [x] ~~`spotify-qt`~~
- [x] `spotify`
- [x] ~~`starship-git`~~
- [x] `sudo-git` # custom prompt
- [x] ~~`swayfire-git`~~
- [x] `sweet-theme-full-git` → `plasma5-themes-sweet-full-git`
- [x] ~~`swiftshader-git`~~
- [x] ~~`synfig-dev`~~
- [x] ~~`systemd-git`~~
- [x] ~~`ta-lib`~~
- [x] ~~`telephant-git`~~
- [x] ~~`tenacity-git`~~
- [x] ~~`thonny-git`~~
- [x] ~~`thrift-0-10.0`~~
- [x] ~~`tok-git`~~
- [x] ~~`ufw-git`~~
- [x] ~~`usd`~~
- [x] `uutils-coreutils-git`
- [x] ~~`vala-panel-appmenu-jayatana-git`~~
- [x] ~~`vala-panel-appmenu-registrar`~~
- [x] `vala-panel-appmenu`
- [x] ~~`vala-panel`~~
- [x] ~~`vapoursynth-git`~~
- [x] ~~`veloren-git`~~
- [x] `velox-git`
- [x] ~~`virt-manager-meta`~~
- [x] ~~`waybar-experimental-git`~~
- [x] ~~`waybar-hyprland-git`~~
- [x] `wayfire-git`
- [x] ~~`wayfire-plugins-extra`~~
- [x] ~~`wayfire`~~
- [x] ~~`wcm`~~
- [x] ~~`webkit2gtk-unstable`~~
- [x] ~~`wf-config-git`~~
- [x] ~~`wf-shell`~~
- [x] ~~`whalebird`~~
- [x] ~~`wireplumber-git`~~
- [x] ~~`woof-git`~~
- [x] ~~`xcfun-git`~~
- [x] ~~`xdg-desktop-portal-wlr-git`~~
- [x] ~~`xf86-input-libinput-git`~~
- [x] ~~`xfce4-panel-profiles`~~
- [x] `xorg-server-git`
- [x] ~~`ytmdesktop`~~
- [x] ~~`zecwallet-lite`~~
- [x] ~~`zellij-git`~~
- [x] ~~`zrythm-git`~~
</details>

<details><summary><b>KDE-git related</b> (dropped)</summary>

- [x] ~~`across`~~
- [x] ~~`akonadi-calendar-git`~~
- [x] ~~`akonadi-calendar-tools-git`~~
- [x] ~~`akonadiconsole-git`~~
- [x] ~~`akregator-git`~~
- [x] ~~`bluedevil-git`~~
- [x] ~~`bluez-qt-git`~~
- [x] ~~`cantor-git`~~
- [x] ~~`discover-git`~~
- [x] ~~`dolphin-git`~~
- [x] ~~`frameworkintegration-git`~~
- [x] ~~`grantlee-git`~~
- [x] ~~`kactivities-git`~~
- [x] ~~`kactivities-stats-git`~~
- [x] ~~`kalendar-git`~~
- [x] ~~`kapidox-git`~~
- [x] ~~`karchive-git`~~
- [x] ~~`kauth-git`~~
- [x] ~~`kbookmarks-git`~~
- [x] ~~`kcalendarcore-git`~~
- [x] ~~`kcalutils-git`~~
- [x] ~~`kcmutils-git`~~
- [x] ~~`kcodecs-git`~~
- [x] ~~`kcompletion-git`~~
- [x] ~~`kconfig-git`~~
- [x] ~~`kconfigwidgets-git`~~
- [x] ~~`kcontacts-git`~~
- [x] ~~`kcoreaddons-git`~~
- [x] ~~`kcrash-git`~~
- [x] ~~`kdav-git`~~
- [x] ~~`kdbusaddons-git`~~
- [x] ~~`kdeclarative-git`~~
- [x] ~~`kded-git`~~
- [x] ~~`kdepim-addons-git`~~
- [x] ~~`kdepim-runtime-git`~~
- [x] ~~`kdesignerplugin-git`~~
- [x] ~~`kdesu-git`~~
- [x] ~~`kdnssd-git`~~
- [x] ~~`kdoctools-git`~~
- [x] ~~`kemoticons-git`~~
- [x] ~~`kfilemetadata-git`~~
- [x] ~~`kglobalaccel-git`~~
- [x] ~~`kguiaddons-git`~~
- [x] ~~`kholidays-git`~~
- [x] ~~`ki18n-git`~~
- [x] ~~`kiconthemes-git`~~
- [x] ~~`kidentitymanagement-git`~~
- [x] ~~`kidletime-git`~~
- [x] ~~`kimageannotator-git`~~
- [x] ~~`kimageformats-git`~~
- [x] ~~`kinit-git`~~
- [x] ~~`kio-git`~~
- [x] ~~`kirigami2-git`~~
- [x] ~~`kitemmodels-git`~~
- [x] ~~`kitemviews-git`~~
- [x] ~~`kjobwidgets-git`~~
- [x] ~~`kjs-git`~~
- [x] ~~`kldap-git`~~
- [x] ~~`kmail-account-wizard-git`~~
- [x] ~~`kmail-git`~~
- [x] ~~`kmailtransport-git`~~
- [x] ~~`knewstuff-git`~~
- [x] ~~`knotes-git`~~
- [x] ~~`knotifications-git`~~
- [x] ~~`knotifyconfig-git`~~
- [x] ~~`konsole-git`~~
- [x] ~~`kontact-git`~~
- [x] ~~`konversation-git`~~
- [x] ~~`korganizer-git`~~
- [x] ~~`kpackage-git`~~
- [x] ~~`kparts-git`~~
- [x] ~~`kpeople-git`~~
- [x] ~~`kpeoplevcard-git`~~
- [x] ~~`kplotting-git`~~
- [x] ~~`kpty-git`~~
- [x] ~~`kquickcharts-git`~~
- [x] ~~`krunner-git`~~
- [x] ~~`kscreenlocker-git`~~
- [x] ~~`kservice-git`~~
- [x] ~~`ktexteditor-git`~~
- [x] ~~`ktextwidgets-git`~~
- [x] ~~`ktorrent-git`~~
- [x] ~~`kunitconversion-git`~~
- [x] ~~`kwayland-git`~~
- [x] ~~`kwidgetsaddons-git`~~
- [x] ~~`kwindowsystem-git`~~
- [x] ~~`kwinft-git`~~
- [x] ~~`kxmlgui-git`~~
- [x] ~~`latte-dock-git`~~
- [x] ~~`libkexiv2-git`~~
- [x] ~~`libkscreen-git`~~
- [x] ~~`libksieve-git`~~
- [x] ~~`libqaccessibilityclient-git`~~
- [x] ~~`messagelib-git`~~
- [x] ~~`okular-git`~~
- [x] ~~`oxygen-git`~~
- [x] ~~`oxygen-icons-git`~~
- [x] ~~`partitionmanager-git`~~
- [x] ~~`pimcommon-git`~~
- [x] ~~`plasma-integration-git`~~
- [x] ~~`plasma-systemmonitor-git`~~
- [x] ~~`plasma-workspace-git`~~
- [x] ~~`purpose-git`~~
- [x] ~~`spectacle-git`~~
- [x] ~~`syndication-git`~~
- [x] ~~`syntax-highlighting-git`~~
- [x] ~~`xdg-desktop-portal-kde-git`~~
</details>

<details><summary><b>Firefox, forks, etc</b> (checked)</summary>

- [x] ~~`firefox-appmenu`~~
- [x] `firefox-esr`
- [x] `firefox-nightly`
- [x] `firefox-wayland-hg`
- [x] `librewolf`
- [x] ~~`thunderbird-beta`~~
</details>

<details><summary><b>Linux kernels</b> (checked)</summary>

- [x] `linux-cachyos-bore`
- [x] `linux-clear`
- [x] ~~`linux-mainline`~~
- [x] `linux-next-git`
- [x] ~~`linux-nitrous-fire`~~
- [x] ~~`linux-tt`~~
- [x] `linux-vfio`
- [x] ~~`linux-xanmod-anbox`~~
- [x] ~~`linux-xanmod-cacule`~~
- [x] `linux-xanmod-lts`
- [x] `linux-xanmod`
</details>

<details><summary><b>Video, Multimedia, Gaming</b> (dropped)</summary>

- [x] ~~`lib32-ffmpeg`~~
- [x] ~~`lib32-gamemode`~~
- [x] ~~`lib32-gst-plugins-bad`~~
- [x] ~~`lib32-gstreamer0.10-base`~~
- [x] ~~`lib32-gstreamer0.10`~~
- [x] ~~`lib32-lilv`~~
- [x] ~~`lib32-lzo`~~
- [x] ~~`lib32-mesa-git`~~
- [x] ~~`lib32-systemd-git`~~
- [x] ~~`mesa-git`~~
- [x] ~~`proton-ge-custom`~~
</details>

<details><summary><b>Other KDE/Qt</b> (checked)</summary>

- [x] ~~`kcm-imchooser-frameworks`~~
- [x] ~~`kcm-lookandfeel-standalone-git`~~
- [x] ~~`kcm-tablet-git`~~
- [x] ~~`kcm-wacomtablet-git`~~
- [x] `kde-service-menu-reimage`
- [x] ~~`material-kwin-decoration-git`~~
- [x] ~~`qt5-styleplugins`~~
- [x] `qt6gtk2`
</details>

<details><summary><b>tkg</b> (checked)</summary>

- [x] ~~`chaotic-nvidia-dev-tkg`~~
- [x] ~~`linux-tkg`~~
- [x] `mesa-tkg-git`
- [x] ~~`proton-tkg`~~
- [x] ~~`vkd3d-proton-tkg-git`~~
- [x] ~~`vulkan-icd-loader-tkg-git`~~
- [x] ~~`wine-tkg`~~
</details>

**Comment by xiota** [comment]
The following interferes aren't listed in the package lists, but some, like `linux-tkg`, are unlisted pkgbases that build multiple packages.

* btrfs-progs-git
* chaotic-nvidia-dev-tkg
* distrho-ports-lv2-git
* distrho-ports-vst-git
* element-desktop-git
* exo-git
* firedragon-beta-znver2
* freezer-git
* gdmap-gtk3
* glibc-eac
* gtk4-git
* imagemagick-git
* java-jbr-xdg
* kcm-wacomtablet-git
* kid3-cli
* lbry-app-bin
* lib32-gamemode
* lib32-gstreamer0.10
* lib32-gstreamer0.10-base
* lib32-systemd-git
* libadwaita-git-pkgs
* libretro-mame-git
* libxvct-git
* linux-tkg
* linux-xanmod-anbox
* linux-xanmod-cacule
* matrix-synapse-rest-auth
* mingw-w64-gcc
* msitools
* natron-plugins-git
* nautilus-git
* nautilus-typeahead
* obs-hevc-vaapi-git
* openvpn3
* pamac-aur-git
* plasma5-theme-sweet-git
* plasma5-wallpapers-wallpaper-engine-without-mpv-git
* power-profiles-daemon
* pulseeffects-git
* python-awesometkinter
* python-constraint
* python-fastdtw
* python-fontparts
* python-poetry-core-git
* python-pyscf
* python-symdom-git
* python-urlgrabber
* ruby-gettext
* ruby-gettext-setup
* rum-git
* samba-mounter-git
* spidermonkey-git
* starship-git
* thrift-0-10.0
* ufw-git
* usd
* vulkan-icd-loader-tkg-git
* wf-config-git
* wine-tkg
* xcfun-git
* ytmdesktop
* zellij-git

**Comment by dr460nf1r3** [comment]
`wine-tkg` and `linux-tkg` are a special case - these are built via dedicated builder routines (eg https://github.com/chaotic-aur/toolbox/blob/main/src/lib/routines-tkg.sh) from the TKG repository. This is required since one PKGBUILD serves many variants of the package. As for the other listed packages, if they aren't in the package lists anymore, it should be safe to drop them. I didn't spot any other special ones among them.

**Comment by Technetium1** [comment]
The following packages were dropped, but mysteriously not in https://github.com/chaotic-aur/interfere/pull/39
```
1. python-constraint
2. python-fastdtw
3. python-fontparts
4. python-poetry-core-git
5. python-pyscf
6. python-symdom-git
7. python-urlgrabber
```

**Comment by xiota** [comment]
They're in https://github.com/chaotic-aur/interfere/pull/38/files

**Comment by Technetium1** [comment]
@Chocobo1 please fix your deps for `coreutils-git`. `wget` is required to build in clean chroot according to https://github.com/coreutils/coreutils/blob/master/README-prereq. I would like to remove https://github.com/chaotic-aur/interfere/blob/master/coreutils-git/PKGBUILD.append

**Comment by xiota** [comment]
Interfere for `fish-git` disables `check()`.  This [comment](https://aur.archlinux.org/packages/fish-git?O=10#comment-795714) indicates check started working again, but it could break (or already broken) again.  Leave alone or try to drop interfere?

**Comment by Technetium1** [comment]
@xiota hopefully can be dropped if check works now. Part of the convenience of having check on a `-git` package is new commits failing to pass tests won't overwrite the last good version we made. If check fails every time or the dev doesn't care to adapt tests to work in our build env, then we should not test.

**Comment by xiota** [comment]
@Technetium1 @dr460nf1r3 `gimp-elsamuko-git` builds without [interfere](https://github.com/chaotic-aur/interfere/tree/master/gimp-elsamuko-git), but I don't understand the motivation for the changes in the interfere.  Would like someone to look at it to decide keep or drop.

**Comment by dr460nf1r3** [comment]
See this [commit](https://aur.archlinux.org/cgit/aur.git/commit/?h=gimp-elsamuko-git&id=a1ec4098102b1312dd03b2fca98a863d7e05460e), we had to supply this change in order to fix the build. Now that it has been added to the package itself it can of course be dropped.

**Comment by xiota** [comment]
Wanted a second opinion because they're slightly different and I couldn't definitely decide that they're equivalent.  I'll go ahead and drop it.

**Comment by dr460nf1r3** [comment]
It's very satisfying to see all of those gone ❤️

**Comment by xiota** [comment]
Can we just drop all packages that start with `k`?  They're all broken anyway. 🙃

**Comment by Technetium1** [comment]
@xiota you are in charge of [maybe fixing](https://github.com/chaotic-aur/interfere/blob/master/filelight-git/PKGBUILD.append) [`filelight-git`](https://aur.archlinux.org/packages/filelight-git).
@alexjp if you have anything to contribute to the `K` section, that'd be cool :)

**Comment by xiota** [comment]
Last I tested, `filelight-git` builds as-is.  However, the interfere adds `kdeclarative-git` to `makedepends`.  I was hesitant to drop the interfere because I don't know what's going on with the KDE/Plasma stuff.  Is `kdeclarative-git` being used to somehow try to unify all the kde git packages?

**Comment by FabioLolix** [comment]
For `gjs-git` cmake have been added to makedepends but tests still fails
For `mcomix-git`python-setuptools have been added to depends instead of makedepnds but git is missing from makedepends
`pantheon-mail` is in Arch repo now
For `sayonara-player-git` `|| true` is passed to the tests (almost found the culprit)
For `vala-panel` git have been added to makedepends but it still have the 4 missing optdepends
For `vala-panel-appmenu` git have been added to makedepends and budgie have been disabled by default

**Comment by xiota** [comment]
`partitionmanager-git` interfere adds depend on `kpmcore-git`.  AUR depends on `kpmcore`.  Is the git depend specifically desired, or should the interfere be dropped if it builds without?

Similar question for other packages that depend on `kdeclarative-git`, while AUR depends on `kdeclarative-git`.

**Comment by dr460nf1r3** [comment]
> `partitionmanager-git` interfere adds depend on `kpmcore-git`.  AUR depends on `kpmcore`.  Is the git depend specifically desired, or should the interfere be dropped if it builds without?
> 
> Similar question for other packages that depend on `kdeclarative-git`, while AUR depends on `kdeclarative`.  (But a lot of those packages are broken either way.)

We tried to maintain a full `-git` stack of KDE applications, so they also depended on each other. I'm sure either @IslandC0der or @alexjp can outline the exact plans for those packages though.

**Comment by IslandC0der** [comment]
Yes, KDE-git packages should always use KDE-git dependencies and stable non-KDE dependencies, with very few exceptions. Looking at that specific interfere, it looks like there was a mix-up between `kpmcore` and `kio`: the latter should be `kio-git`, but the former shouldn't (not everything that begins with "k" is KDE!)

**Comment by xiota** [comment]
Is `virt-manager-meta` interfere needed?  It's a `prepare` that runs `$CAUR_PUSH 'yes | pacman -S iptables-nft'`.

The package is a custom [`PKGBUILD`](https://gitlab.com/garuda-linux/packages/stable-pkgbuilds/virt-manager-meta/-/blob/master/PKGBUILD) that has `depends` inside `package()`.

Why not put `depends=('iptables-nft')` outside `package()` and `depends+=(...)` inside?

**Comment by xiota** [comment]
`ialauncher-git` ... adopted to update... and noticed https://github.com/rtts/ialauncher/issues/11 makes the package unusable.  Should it be dropped entirely?  Is it worth trying to patch to use `pyxdg` folders?

**Comment by dr460nf1r3** [comment]
> Is `virt-manager-meta` interfere needed?  It's a `prepare` that runs `$CAUR_PUSH 'yes | pacman -S iptables-nft'`.
> 
> The package is a custom [`PKGBUILD`](https://gitlab.com/garuda-linux/packages/stable-pkgbuilds/virt-manager-meta/-/blob/master/PKGBUILD) that has `depends` inside `package()`.
> 
> Why not put `depends=('iptables-nft')` outside `package()` and `depends+=(...)` inside?

I'm not entirely sure why `depends` was put inside `package`, but I can tell that the interfere was needed as iptables is preinstalled in the chroots and the build would fail due to a package conflict otherwise.

**Comment by xiota** [comment]
`qt5-styleplugins` [interfere](https://github.com/chaotic-aur/interfere/tree/master/qt5-styleplugins) is commented out.  Keep it / leave it alone?

Some packages have interferes that change `pkgrel`, like `qt6gtk2` [interfere](https://github.com/chaotic-aur/interfere/tree/master/qt6gtk2).  What is the purpose of "automatic bumping" is?  What's the difference between `eval pkgrel=...` and just `pkgrel=...`?

**Comment by dr460nf1r3** [comment]
These were implemented as a hack to automatically increase their pkgver whenever a dependency gets updated. It can be seen with a few packages requiring frequent rebuilds to not have shared library mismatches.

**Comment by xiota** [comment]
Thank you for explaining the auto bumps.

I've also wondered some interferes replace `check()` with a dummy function.  Some use a `prepare` script to use `--nocheck`.  Is there any functional difference between the two?

**Comment by dr460nf1r3** [comment]
There might be no functional differences, personally I've always used the substituted check() function.

**Comment by yaomtc** [comment]
kcm-utils should be using kf6 rather than kf5 now, right?

**Comment by alexjp** [comment]
> kcm-utils-git should be using kf6 rather than kf5 now, right?

yes!

**Comment by xiota** [comment]
@alexjp @dr460nf1r3   Theses are the packages with `kcm` in the name.  Which ones should be dropped/moved to the kde-git repo?

```
 fancontrol-gui # (dep fancontrol-kcm)
 fancontrol-gui-git # (dep fancontrol-kcm-git)
 fancontrol-kcm
 fancontrol-kcm-git
 garuda-settings-manager-kcm-git
 kcm-colorful-git
 kcm-grub2-git
 kcm-imchooser-frameworks
 kcm-lookandfeel-standalone-git
 kcm-polkit-kde-git
 kcm-tablet-git
 kcm-uefi
 kcmutils-git
 systemd-kcm
 telepathy-kde-accounts-kcm-git
 telepathy-qt # (dep telepathy-kde-accounts-kcm-git)
```

**Comment by alexjp** [comment]
@xiota will have to take a better look, but at least:
```
kcmutils
telepathy-kde-accounts-kcm
sddm-kcm
```

should be built in the chaotic-aur-kde server.
