### ISSUE TITLE
[Request] simplescreenrecorder

### ISSUE THREAD

**Issue by fwookerton** [chaotic-aur/packages#2407]
### Link to the package base(s) in the AUR

[https://aur.archlinux.org/packages/simplescreenrecorder](https://aur.archlinux.org/packages/simplescreenrecorder)

### Utility this package has for you

A simple and straight forward screen recorder for games, desktop and even has a RTMP streaming function. It's like bandicam for linux.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

GPL 3

**Comment by xiota** [comment]
Dropping because broken after recent ffmpeg update.  Also, uses Qt5 and upstream is unmaintained.

**Comment by drdaffey** [comment]
Can you consider re-adding this now that the ffmpeg issues have been resolved? Thank you.

**Comment by xiota** [comment]
I'll re-add, but it will eventually be dropped again if not ported to Qt6.  Since upstream dev seems responsive, someone should open an issue to request.

**Comment by xiota** [comment]
Failed to build because after CMake 4.0 update.  Metrics 696.

Switched to custom package `simplescreenrecorder-qt6-git` for Qt6 support.

**Comment by xiota** [comment]
Switching to `aur/simplescreenrecorder-git` because it's been updated to Qt6.

Metrics:

* simplescreenrecorder-qt6-git # 420
