### ISSUE TITLE
[Bug] elasticsearch: cannot resolve "jre19-openjdk-headless"

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2412]
### What happens?

When I try to install `elasticsearch` Chaotic package, I get the following error:
```
resolving dependencies...
warning: cannot resolve "jre19-openjdk-headless", a dependency of "elasticsearch"
:: The following package cannot be upgraded due to unresolvable dependencies:
      elasticsearch
```
Indeed, `jre19-openjdk-headless` does not exist.

### What is expected to happen?

Package installing with no dependency issue.

**Comment by dr460nf1r3** [comment]
Huh? Looking at the AUR, this package [does not exist at all](https://aur.archlinux.org/packages?O=0&K=jre19-openjdk-headless
)!

**Comment by Technetium1** [comment]
[`java19-openjdk` is back](https://aur.archlinux.org/packages/jre19-openjdk-headless), but fails to build: [java19-openjdk.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/java19-openjdk.log)

**Comment by xiota** [comment]
@D3vil0p3r `elasticsearch` last built on May 16.  Does it work now?

**Comment by D3vil0p3r** [comment]
> @D3vil0p3r `elasticsearch` last built on May 16. Does it work now?

I think it is needed to update elasticsearch to the latest version that works with java packages that are in the repositories.

**Comment by xiota** [comment]
> I think it is needed to update elasticsearch to the latest version that works with java packages that are in the repositories.

Arch has moved on to jre20, and elasticsearch 8.8.1 was built yesterday (2023-06-20).
