### ISSUE TITLE
[Request] mullvad-browser-bin

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2413]
### Link to the package base(s) in the AUR

[mullvad-browser-bin](https://aur.archlinux.org/packages/mullvad-browser-bin)

### Utility this package has for you

The Mullvad browser is a new browser focused mainly on Privacy and it is very worth for those users would like to surf Internet safely. It has been developed by Mullvad VPN and Tor Project devs.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Proprietary and binary packages are being dropped.  However, `mullvad-browser-bin` is a potential exception because correct packaging is required for fingerprint resistance.  The source-built package appears to be missing components and correct build process.
