### ISSUE TITLE
[Request] mullvad-vpn

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2414]
### Link to the package base(s) in the AUR

[mullvad-vpn](https://aur.archlinux.org/packages/mullvad-vpn)

### Utility this package has for you

It is an open-source VPN service, easy to use, that can be integrated with Mullvad VPN. It has also a dedicated page on Arch Linux Wiki: https://wiki.archlinux.org/title/Mullvad

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Already in chaotic.  Last built last week.  Duplicate #356 #1465.
