### ISSUE TITLE
[Request] telegram-bot-api-git

### ISSUE THREAD

**Issue by asdfzxcvbn** [chaotic-aur/packages#2415]
### Link to the package base(s) in the AUR

[telegram-bot-api-git](https://aur.archlinux.org/packages/telegram-bot-api-git)

### Utility this package has for you

used to host a local telegram bot api server. allows a bot to handle files over 25 megabytes, up to 2 gigabytes, for free.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by Technetium1** [comment]
submodule section needs updated

**Comment by Technetium1** [comment]
16 months of an inactive maintainer and many releases since, maybe this can be explored in the future if something changes.
