### ISSUE TITLE
[Outdated] pnpm

### ISSUE THREAD

**Issue by FireMasterK** [chaotic-aur/packages#2416]
### If available, link to the latest build

[pnpm.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/pnpm.log)

### Package name

pnpm

### Latest build

`8.0.0-1`

### Latest version available

`8.3.1-1`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by Technetium1** [comment]
Thank you!
