### ISSUE TITLE
[Request] microchip-mplabx-bin

### ISSUE THREAD

**Issue by bibliothec** [chaotic-aur/packages#2417]
### Link to the package base(s) in the AUR

http://aur.archlinux.org/packages/microchip-mplabx-bin
http://aur.archlinux.org/packages/microchip-mplabxc16-bin
http://aur.archlinux.org/packages/microchip-mplabxc32-bin
http://aur.archlinux.org/packages/microchip-mplabxc8-bin

### Utility this package has for you

IDE for Microchip PIC

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No, but the author doesn't really care anyways. It's just for bureaucracy.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

added some links for compiler tool chain in "Link to the package base(s) in the AUR"

**Comment by Technetium1** [comment]
Recursive deps need updated before this can happen. No obvious ETA...
> [MarsSeed](https://aur.archlinux.org/account/MarsSeed) flagged tclkit out-of-date on 2022-08-01 (EDT) for the following reason:

> Tcl & Tk 8.6.12 (2021-11-05)

**Comment by xiota** [comment]
```
$ pacman -Si microchip-mplabx-bin
...
Download Size   : 1089.13 MiB
Installed Size  : 11456.60 MiB
...
```

**Comment by Technetium1** [comment]
They are indeed large… It would still be good to add them for a while and see if they are used, then remove later if they are not. We can't know until they update again, but there are quite a few votes on the AUR there, and it seems quite difficult to build on a normal PC.
![image](https://github.com/chaotic-aur/packages/assets/9877150/ab241137-1c7f-42aa-be3c-42861d29c127)

**Comment by xiota** [comment]
The packages are built and in the repo.  I didn't add them to the package list after seeing the size.  Also need to look at the license specifics.

**Comment by xiota** [comment]
Fun fact:
```
$ namcap /var/cache/pacman/pkg/microchip-mplabxc8-bin-2.45-1-x86_64.pkg.tar.zst | grep python2
microchip-mplabxc8-bin W: Referenced library 'libpython2.7.so.1.0' is an uninstalled dependency (needed in files ['opt/microchip/xc8/v2.45/avr/bin/avr-gdb-py'])
```

**Comment by Technetium1** [comment]
This depends on [java8-openjfx](https://aur.archlinux.org/packages/java8-openjfx), which depends on both Python2.7 and Qt5. This won't be added per #1958 and #3157.
