### ISSUE TITLE
[Request] soundcloud-nativefier

### ISSUE THREAD

**Issue by Pakrohk** [chaotic-aur/packages#2422]
### Link to the package base(s) in the AUR

[aur](https://aur.archlinux.org/packages/soundcloud-nativefier)

### Utility this package has for you

SoundCloud desktop app built with nativefier (electron)

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
Dropping because Electron 22.  Metrics 3.
