### ISSUE TITLE
[Request] inochi-creator

### ISSUE THREAD

**Issue by bibliothec** [chaotic-aur/packages#2423]
### Link to the package base(s) in the AUR

http://aur.archlinux.org/packages/inochi-creator

### Utility this package has for you

Open source editor for rigging inochi 2D puppets

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

github : https://github.com/Inochi2D/inochi-creator

**Comment by Technetium1** [comment]
Hopefully fixed in next release: [inochi-creator.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/inochi-creator.log)
```
==> Starting build()...
Error Unresolvable dependencies to package bindbc-sdl:
  bindbc-imgui 0.7.0 depends on bindbc-sdl ~>0.21.4
  inochi-creator ~master depends on bindbc-sdl ~>1.1.2
```

**Comment by Technetium1** [comment]
Many changes have happened in the last year, and trying multiple times throughout the year, none have been successful. If anyone can build this in a clean chroot successfully, then we can try again.
