### ISSUE TITLE
[Bug] v4l2loopback-dc-dkms issue with PGP key

### ISSUE THREAD

**Issue by Zbysiu3cytryny** [chaotic-aur/packages#2427]
### What happens?

package v4l2loopback-dc-dkms has broken PGP key

### What is expected to happen?

To install a package

### If possible, please attach logs

:: Kontynuować instalację? [T/n] t
(144/144) sprawdzanie kluczy w bazie                                                                                         [----------------------------------------------------------------------------] 100%
(144/144) sprawdzanie spójności pakietów                                                                                     [----------------------------------------------------------------------------] 100%
błąd:  v4l2loopback-dc-dkms: podpis od "Nico Jensch (Chaotic-AUR) <dr460nf1r3@garudalinux.org>" jest nieprawidłowy
:: Plik /var/cache/pacman/pkg/v4l2loopback-dc-dkms-1:1.8.2-1.4-x86_64.pkg.tar.zst jest uszkodzony (Niepoprawny lub uszkodzony pakiet (podpis PGP)).
Czy chcesz go usunąć? [T/n]

**Comment by dr460nf1r3** [comment]
Should be fine now.

**Comment by Zbysiu3cytryny** [comment]
Update went off smoothly, thanks!
