### ISSUE TITLE
[Request] morewaita

### ISSUE THREAD

**Issue by raul-lezameta** [chaotic-aur/packages#2428]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/morewaita

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
For "reasons", this package will dropped if any problems develop.  It is being retained for now.  Metrics 17.
