### ISSUE TITLE
[Request] morewaita-git

### ISSUE THREAD

**Issue by raul-lezameta** [chaotic-aur/packages#2429]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/morewaita-git

### Utility this package has for you

An Adwaita style extra icons theme for Gnome Shell.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
For "reasons", this package will dropped if any problems develop.  It is being retained for now.  Metrics 13.

**Comment by coxackie** [comment]
FYI, the package was renamed to `morewaita-icon-theme-git`; see https://aur.archlinux.org/packages/morewaita-icon-theme-git. Same for the non-git version.

**Comment by xiota** [comment]
The old package had some minor issues that I was willing to overlook as long as they continued working.  Did not switch over to the new packages because they deviate somewhat from AUR submission guidelines.  Not worth trying to convince the maintainer to change anything.
