### ISSUE TITLE
[Outdated] shutter-encoder 

### ISSUE THREAD

**Issue by cleanerspam** [chaotic-aur/packages#2430]
### If available, link to the latest build

https://www.shutterencoder.com/en/
https://github.com/paulpacifico/shutter-encoder

### Package name

shutter-encoder

### Latest build

17.0.1

### Latest version available

17.1

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by dr460nf1r3** [comment]
Checksums are not correct on this one.

**Comment by Technetium1** [comment]
There's a new release. Flagged it out of date.

**Comment by Technetium1** [comment]
`Finished making: shutter-encoder 17.1-1 (Wed 10 May 2023 12:57:20 AM CEST)`
