### ISSUE TITLE
[Outdated] microsoft-edge-dev-bin

### ISSUE THREAD

**Issue by TheOceanBreeze** [chaotic-aur/packages#2431]
### If available, link to the latest build

https://aur.archlinux.org/packages/microsoft-edge-dev-bin

https://aur.archlinux.org/cgit/aur.git/snapshot/microsoft-edge-dev-bin.tar.gz

### Package name

microsoft-edge-dev-bin

### Latest build

114.0.1823.4-1

### Latest version available

114.0.1807.1-1

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by Technetium1** [comment]
`Finished making: microsoft-edge-dev-bin 114.0.1823.4-1 (Fri 05 May 2023 11:12:45 PM CEST)`
