### ISSUE TITLE
[Bug] poppler-git

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#2432]
### What happens?

Causes Okular to fail to launch with 
```
QWidget::setMinimumSize: (okular_sidebar/Sidebar) Negative sizes (0,-1) are not possible
org.kde.okular.core: Invalid plugin factory for "/usr/lib/qt/plugins/okular/generators/okularGenerator_poppler.so":"Cannot load library /usr/lib/qt/plugins/okular/generators/okularGenerator_poppler.so: (/usr/lib/libpoppler-qt5.so.1: undefined symbol: _ZN16SignatureHandlerC1EPKc9SECOidTag)"
```

### What is expected to happen?

No crash

### More information

Works fine with `extra/poppler` 
Package was already bumped and rebuilt once in https://github.com/chaotic-aur/interfere/commit/4032392ee2a6f770cf70bf5bcbd2bb477393367d#diff-acda3a66e1f15a258e2d7c66274a579f3e77ce846d9358b43f611ab39f0ae9f2R2593

**Comment by dr460nf1r3** [comment]
Might just be an incompatibility with newer poppler versions?

**Comment by Technetium1** [comment]
Meant to add that a temporary fix is to use `chaotic-aur/poppler-git`

**Comment by xiota** [comment]
I don't understand this bug.  Is it resolved?
```
$ pacman -Si poppler-git | grep -Ei "(repository|name|version|build date)"
Repository      : chaotic-aur
Name            : poppler-git
Version         : 23.08.0.r5.g2368e099-1
Build Date      : Sat Aug 26 15:50:57 2023
```
