### ISSUE TITLE
[Outdated] goland

### ISSUE THREAD

**Issue by balaios** [chaotic-aur/packages#2433]
### If available, link to the latest build

[goland.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/goland.log)

### Package name

goland

### Latest build

goland-2023.1.1-1

### Latest version available

goland-2023.1-1

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by Technetium1** [comment]
Thanks `Finished making: goland 2023.1.1-1 (Sat 06 May 2023 05:20:23 AM CEST)`
