### ISSUE TITLE
[Maintenance] Rebuild packages after Python upgrade

### ISSUE THREAD

**Issue by xiota** [chaotic-aur/packages#2434]
`extra/python` has been upgraded to 3.11.  This issue tracks rebuild progress.

Rebuilt, but have issues that require manual intervention...

* python-inputs # [aur](https://aur.archlinux.org/pkgbase/python-inputs)
* vkbasalt-cli # [aur](https://aur.archlinux.org/pkgbase/vkbasalt-cli)

<details><summary>Rebuild complete...</summary>

* amdgpu-fan
* anki
* autokey-common / autokey-gtk / autokey-qt
* bookletimposer
* compiz
* compiz-git
* dangerzone
* dee
* dockbarx
* f3d-git
* fotokilof
* friture
* frog-ocr
* fvs
* gajim-git
* gallery-dl
* gdcm
* gdm-settings
* gdm-settings-git
* getmail6
* git-cola
* gr-limesdr-git
* gradience
* gradience-git
* grass
* green-recorder
* green-recorder-git
* gtg
* guiscrcpy
* gwe
* ialauncher-git
* icoextract
* informant
* input-remapper-git
* jade-application-kit
* jdanimatedimageeditor
* joystickwake
* jupyter-metakernel
* kawaii-player
* kazam
* kicad-git
* kodi-git-eventclients
* krop
* legendary
* libsearpc
* libselinux
* llvm-git / lldb-git / clang-git # all built by [pkgbuild-llvm-git](https://github.com/chaotic-aur/pkgbuild-llvm-git)
* m64py
* mate-hud
* matrix-registration
* matrix-synapse-git
* mcomix
* mcomix-git
* mcstatus
* meteo-qt-git
* minigalaxy
* moodle-dl-git
* neovim-remote
* notorious-git
* ocrmypdf
* organize
* oversteer
* passbook
* passbook-git
* patool
* persepolis-git
* photocollage
* pip-tools
* podman-compose-git
* prjapicula
* protontricks-git
* protonup-git
* protonup-qt
* protonvpn-cli
* pyradio-git
* python-caldav
* python-codegen
* python-dlib
* python-imageio-ffmpeg
* python-ipaclient
* python-ipalib
* python-langcodes
* python-pa-ringbuffer
* python-pympv
* python-qiskit
* python-qiskit-aer
* python-qiskit-ibmq-provider
* python-rtmixer
* python-scrap_engine-git
* python-sip4
* python-spacy
* python-thinc
* python-vosk
* python-xdgenvpy
* pyzbar
* qoob-git
* qtile-extras-git
* qtile-git
* qutebrowser-git
* retrolink-git
* safeeyes
* safeeyes-git
* seafile
* searx-git
* setzer-git
* silos
* snapper-gui-git
* soapysdr-git
* sphinxbase
* subliminal-git
* swaystatus-git
* syncthing-gtk-python3
* targetcli-fb
* tartube
* tblock
* thonny
* thonny-git
* timetrack
* tlpui
* trackma-git
* trimage-git
* ubertooth
* ulauncher
* vapoursynth-git
* vimiv-qt
* vimiv-qt-git
* vorta
* wattman-gtk-git
* xcb-proto-git
* xen
* xkcdpass
* xpra-git
* youtube-search-python
* yt-dlg-git
* yt-dlp-git
* ytmdl
* zenmap-python3-git
</details>

**Comment by dr460nf1r3** [comment]
They are all bumped and building right now!

**Comment by Technetium1** [comment]
`Finished making: dangerzone 0.4.1-3 (Sun 07 May 2023 09:12:42 PM CEST)`

**Comment by xiota** [comment]
The python version change was around 4-May-2023.  Here are some packages missed in the previous list.  They have been checked for the presence of `usr/lib/python3.10`

* [ ] anki
* [ ] apparmor-git
* [ ] gradience-git
* [ ] kicad-git
* [ ] meteo-qt-git
* [ ] python-caldav
* [ ] thonny-git
* [ ] yt-dlp-git

As before, `-bin` and excessively large packages were not checked:

* crossover
* dataspell 
* dataspell-jre
* davinci-resolve-studio
* nteract-bin
* proton-ge-custom
* pycharm-community-eap

**Comment by xiota** [comment]
Does anyone object to dropping `python-dephell-*`?  Right now, no other packages depend on them, several key `dephell` packages are broken, and there is no upstream maintainer.

**Comment by dr460nf1r3** [comment]
Personally, given the outlined facts, I'd say it's a reasonable decision. 

I went through the list and checked the packages that succeeded in building. There were a few missing dependencies (fixable by adding those to the repo), a few missed runtime deps (also fixable by adding those to deps)  and others had build issues. I'm not sure yet what caused these.

**Comment by xiota** [comment]
Will add `python-dephell-*` to my next round of removals.  It won't be immediate, so there is time for someone to object (and volunteer to maintain the AUR packages 😝).

**Comment by RubenKelevra** [comment]
@xiota wrote:
> Method:
> 
>     * `pacman -Syu`
> 
>     * Search for packages that depend on python.
> 
>     * Exclude packages that were built in May 2023
> 
>     * Download `pkg.tar.zst` and check for `usr/lib/python3.10`

That's not efficient, and some packages don't have a direct `python` dependencies, but just a list of `python-*` packages they depend on.

You can however just download the file-database and let pacman search in it. This does not require you to download the packages itself, thus it's pretty fast (around 30 seconds on my system):

```console
# pacman -Fy --regex '^usr/lib/python3.10' | grep -v 'downloading...' | grep -F 'chaotic-aur' |  awk '{ print $(NF - 1) }' | cut -d'/' -f2 | sort -u
```

So currently that would be:

```
amdgpu-fan
apparmor-git
archinstall-git
autokey-common
autokey-gtk
autokey-qt
bookletimposer
clang-git
compiz
compiz-git
dee
f3d-git
friture
gajim-plugin-omemo-git
gdcm
gfeeds-git
giara
gradience-git
grass
gr-limesdr-git
guiscrcpy-git
kodi-git-eventclients
libselinux
lldb-git
llvm-git
moodle-dl-git
oversteer
python-aioxmpp
python-apprise
python-blist
python-booleanoperations
python-caldav
python-cleo-git
python-codegen
python-dataclasses
python-dephell-changelogs
python-dephell-markers
python-dephell-specifier
python-inputs
python-ipaclient
python-ipalib
python-langcodes
python-pa-ringbuffer
python-plaster-pastedeploy
python-pympv
python-pyramid
python-pyspark
python-rtmixer
python-sanic-routing
python-spacy
python-thinc
python-vosk
python-wxpython-dev
python-xdgenvpy
setzer-git
thonny-git
vkbasalt-cli
xcb-proto-git
xen
xpra-git
```

**Comment by dr460nf1r3** [comment]
Thanks for clearing this up @RubenKelevra :) 

I just bumped the missed ones in order to trigger a rebuild of them.

**Comment by xiota** [comment]
All but a few packages have now been rebuilt for Python 3.11.  Some were dropped as unnecessary dependencies or other issues.  Bumping version numbers didn't work with all packages, so they might have to be manually reinstalled or installed with `pacman -Syuu` (double `u`'s).  Use `check-broken-packages` to find them.

`clang-git`, `lldb-git`, `llvm-git`, `xen` have other issues preventing rebuild.  Some binary-based packages still use Python 3.10, but should continue to work because they package their own Python binary.  They would need to be updated upstream.

**Comment by dr460nf1r3** [comment]
> `clang-git`, `lldb-git`, `llvm-git`, `xen` have other issues preventing rebuild

Afaik it has been like this for quite a while - I'm not sure whether it makes sense keeping those around given we are having those build issues.

**Comment by xiota** [comment]
I would axe them, but ... will leave that to someone else.

**Comment by dr460nf1r3** [comment]
Mhm, `32, 10, 51, 14` downloads this month. So at least `clang-git` and `llvm-git` seem to be used by people.

**Comment by xiota** [comment]
`lldb-git`, `lld-git`, `polly-git`, `compiler-rt-git`, `clang-git`, `llvm-libs-git`, and `llvm-git` are built by [pkgbuild-llvm-git](https://github.com/chaotic-aur/pkgbuild-llvm-git), which currently isn't working.  I was unable to fix it.

**Comment by dr460nf1r3** [comment]
cc @SolarAquarion
