### ISSUE TITLE
[Request] sejda-desktop

### ISSUE THREAD

**Issue by hugo-drax** [chaotic-aur/packages#2436]
### Link to the package base(s) in the AUR

[sejda-desktop](https://aur.archlinux.org/packages/sejda-desktop)

### Utility this package has for you

I work a lot with PDF files and I tend to exclusively use Garuda Linux. Most rare packages I use are in the chaotic-aur. It would be nice to have this one included so when I do a fresh install using ansible pull, I can straemline and automate the entire install.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
From the Sejda Desktop [EULA](https://www.sejda.com/eula):

> **Transfer**
> 
> Licensee may not sell, assign, or transfer the Software or the License granted by this EULA without prior written consent of the Licensor.
>
> **Prohibited Uses**
>
> It is expressly forbidden to
>
> * ...
> * Redistribute the Software as part of a product, "appliance" or "virtual server";
> * ...

**Comment by Technetium1** [comment]
This is unfortunately way too large, licensing aside.
