### ISSUE TITLE
[Request] kate-root

### ISSUE THREAD

**Issue by dreirund** [chaotic-aur/packages#2440]
### Link to the package base(s) in the AUR

[kate-root](https://aur.archlinux.org/packages/kate-root)

### Utility this package has for you

My favourite text editor is `kate`. However, it refuses to run as root, without a possibility to override (but running via `kdesu` is supposed to work). The requested package patches `kate` to change the refusal into a warning.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a few.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

Since I don't know which type of users use Chaotic-AUR, and since I expect that every user installs only a small fraction of all available packages, I selected "*No, but for a few*" to the question "*Do you consider the package(s) to be useful for **every** Chaotic-AUR user?*"

**Comment by Technetium1** [comment]
Waiting until upstream is not flagged out of date.

**Comment by xiota** [comment]
Closing this as not planned because `kate-root` is no longer in AUR.

From [PRQ#44015](https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/thread/5MZB6VTSXG4YUCADEG2SOCAFMZPVN235/#5MZB6VTSXG4YUCADEG2SOCAFMZPVN235):

> Abandoned old mod from last year of kate text editor, available in repo.
>
> Custom-patched to allow running it as root.
>
> But this is not needed at all. Kate is able to request sudo credentials on-demand when needed, and it also supports the admin:// protocol.
