### ISSUE TITLE
[Request] rustdesk-bin

### ISSUE THREAD

**Issue by joe733** [chaotic-aur/packages#2444]
### Link to the package base(s) in the AUR

[rustdesk-bin](https://aur.archlinux.org/packages/rustdesk-bin)

### Utility this package has for you

Remote screen sharing.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [X] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

### More information

> Related issues: https://github.com/chaotic-aur/packages/issues/1774, https://github.com/chaotic-aur/packages/issues/928.

Built package:  [rustdesk-bin-1.1.9-3-x86_64.pkg.tar.zst.zip](https://github.com/chaotic-aur/packages/files/11417571/rustdesk-bin-1.1.9-3-x86_64.pkg.tar.zip)

**Dependencies**

- Arch packages: `gtk3`, `xdotool` ,`libxcb`, `libxfixes`, `alsa-lib`, `pulseaudio`, `hicolor-icon-theme`, `xdg-utils`
- AUR: [`python-pynput`](https://aur.archlinux.org/packages/python-pynput)

**Comment by Technetium1** [comment]
Unfortunately, this should be denied until the maintainer tags a new version. Too many things are broken, and the maintainer _actively refuses_ to tag new releases. I'll be aware when the change in releases happens, as I comaintain [`rustdesk`](https://aur.archlinux.org/packages/rustdesk). When there's a new release, we can definitely get this added!

**Comment by joe733** [comment]
> Too many things are broken, and the maintainer actively refuses to tag new releases.

Yes, that's unfortunate. The last release tag was one year ago. I created a task on their repository to track the next release, but they won't accept it from a non-contributor. 

Nevertheless, I've noticed that in this [`PKGBUILD`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rustdesk-bin),  `rustdesk-bin` is being created from an upstream builds for Manjaro.


```s
url="https://github.com/rustdesk/rustdesk"
...
source=("$url/releases/download/${pkgver}/rustdesk-${pkgver}-manjaro-arch.pkg.tar.zst")
...
```

So technically, this build is simply copy pasting stuff from an existing `zst` package. I've tested out the built package, it is working well. But certainly, adding it to Chaotic-AUR, is entirely up to your discernment.

**Comment by dr460nf1r3** [comment]
There won't be a package request of a maintainer added it 😁

**Comment by Technetium1** [comment]
@Rojikku and I are sick of waiting for a release, someone else has already adopted `anydesk` and I won't be bothered to watch for releases anymore. When [if] there is ever a new release, someone please post about it.

**Comment by zany130** [comment]
There was a new release a few days ago the nightly package is now out of date

**Comment by joe733** [comment]
Version [`1.2.2`](https://github.com/rustdesk/rustdesk/releases) was released two weeks ago. [AUR package](https://aur.archlinux.org/packages/rustdesk-bin) is also updated.

**Comment by crabvk** [comment]
Why the bin version of the package?
