### ISSUE TITLE
[Request] Mkchromecast 

### ISSUE THREAD

**Issue by Bhooty** [chaotic-aur/packages#2445]
### Link to the package base(s) in the AUR

https://aur.archlinux.org/packages/mkchromecast-git

### Utility this package has for you

Allows the user to mirror the screen to chromecast 

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

YES!

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### Does the package's license allow redistributing it?

No clue.

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by xiota** [comment]
`mkchromecast-git` wasn't working with devices earlier this year.  Have you tested that it works with your chromecast or tv?

**Comment by Technetium1** [comment]
Messaged on Telegram, `catt` provides expected functionality
