### ISSUE TITLE
[Outdated] gnome-shell-performance and mutter-performance

### ISSUE THREAD

**Issue by FireMasterK** [chaotic-aur/packages#2447]
### If available, link to the latest build

[gnome-shell-performance.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/gnome-shell-performance.log)
[mutter-performance.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/mutter-performance.log)

### Package name

`gnome-shell-performance` and `mutter-performance`

### Latest build

`43.4+r5+gc35e9f8c0-1`

### Latest version available

`44.1+r2+g82bd40dcb-1`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by FiestaLake** [comment]
[mutter-performance AUR log](https://aur.archlinux.org/cgit/aur.git/commit/?h=mutter-performance&id=9f14624b3684b10e438f01e9be9c4433b7302acc)
[gnome-shell-performance AUR log](https://aur.archlinux.org/cgit/aur.git/commit/?h=gnome-shell-performance&id=d5380511f6c2324963c2443ca611729c64e2c62a)

Tried to bump up pkgrel by AUR side. See if this triggers the rebuilding process. Thanks.

**Comment by xiota** [comment]
`gnome-shell-performance` was dropped because there is no difference from extra/gnome-shell. It was also flagged for nearly two months and had a new maintainer who hadn't pushed any changes.  Recent commit was after the drop.

**Comment by D3vil0p3r** [comment]
Oh ok. So also the performance improvements provided in that package are applied also in the vanilla `gnome-shell`?

**Comment by xiota** [comment]
The patches were either upstreamed or dropped for whatever reason.  I saw that there are no patches when I was checking on why it was flagged for so long.  I didn't check for details.
