### ISSUE TITLE
[Outdated] linux-nitrous

### ISSUE THREAD

**Issue by BowDown097** [chaotic-aur/packages#2448]
### If available, link to the latest build

[linux-nitrous.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-nitrous.log)

### Package name

`linux-nitrous`

### Latest build

`6.2.13`

### Latest version available

`6.3.1`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

Fails to build following the release of 6.3 seemingly due to a new build dependency on python3 which is not installed.

**Comment by Technetium1** [comment]
I flagged it: https://aur.archlinux.org/pkgbase/linux-nitrous
