### ISSUE TITLE
[Request] nerdfix

### ISSUE THREAD

**Issue by REmerald** [chaotic-aur/packages#2452]
### Link to the package base(s) in the AUR

[nerdfix](https://aur.archlinux.org/pkgbase/nerdfix)

### Utility this package has for you

Easily fix broken icons in files after nerd-fonts v3.0.0 update.

### Do you consider the package(s) to be useful for every Chaotic-AUR user?

No, but for a great amount.

### Do you consider the package to be useful for feature testing/preview?

- [ ] Yes

### Have you tested if the package builds in a clean chroot?

- [X] Yes

### Does the package's license allow redistributing it?

YES!

### Have you searched the issues to ensure this request is unique?

- [X] YES!

### Have you read the README to ensure this package is not banned?

- [X] YES!

**Comment by REmerald** [comment]
Can't create new issue to request `nomacs` package, github gives me error 500.

**Comment by xiota** [comment]
https://www.githubstatus.com/

**Comment by REmerald** [comment]
@xiota , thx for the link about the news.

Now it seems like everything is working and I successfully created a new package request.

**Comment by Technetium1** [comment]
Tests failing: [nerdfix.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/nerdfix.log)
