### ISSUE TITLE
[Outdated] wine-ge-custom

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#2453]
### If available, link to the latest build

[wine-ge-custom.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/wine-ge-custom.log)

### Package name

`wine-ge-custom`

### Latest build

`1:GE.Proton8.1-3`

### Latest version available

`1:GE.Proton8.4-1`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by Technetium1** [comment]
`Finished making: wine-ge-custom 1:GE.Proton8.4-1 (Tue 09 May 2023 06:28:09 PM -03)`
