### ISSUE TITLE
[Outdated] dxvk-async-git

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#2454]
### If available, link to the latest build

[dxvk-async-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/dxvk-async-git.log)

### Package name

`dxvk-async-git`

### Latest build

`2.1.r67.g5c8ed491-1`

### Latest version available

`2b09932`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by Technetium1** [comment]
`Finished making: dxvk-async-git 2.1.r85.g80f7d2ab-1 (Wed 10 May 2023 12:19:48 AM CEST)`
