### ISSUE TITLE
[Outdated] gnome-shell-extension-arch-update

### ISSUE THREAD

**Issue by abraham-sah** [chaotic-aur/packages#2456]
### If available, link to the latest build

[gnome-shell-extension-arch-update.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/gnome-shell-extension-arch-update.log)

### Package name

`gnome-shell-extension-arch-update`

### Latest build

`51`

### Latest version available

`52`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

https://aur.archlinux.org/packages/gnome-shell-extension-arch-update

**Comment by Technetium1** [comment]
`Finished making: gnome-shell-extension-arch-update 52-1 (Wed 10 May 2023 12:14:17 AM CEST)`
