### ISSUE TITLE
[Outdated] bottles

### ISSUE THREAD

**Issue by abraham-sah** [chaotic-aur/packages#2457]
### If available, link to the latest build

[bottles.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/bottles.log)

### Package name

`bottles`

### Latest build

`51.5`

### Latest version available

`51.6`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

### More information

https://aur.archlinux.org/packages/bottles

**Comment by Technetium1** [comment]
`Finished making: bottles 2:51.6-3 (Wed 10 May 2023 12:12:29 AM CEST)`
