### ISSUE TITLE
[Outdated] libadwaita-without-adwaita-git

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#2463]
### If available, link to the latest build

[libadwaita-without-adwaita-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/libadwaita-without-adwaita-git.log)

### Package name

`libadwaita-without-adwaita-git`

### Latest build

`1.2.3-4.2`

### Latest version available

`1.3.2-5`

### Have you tested if the package builds in a clean chroot?

- [ ] Yes

**Comment by dr460nf1r3** [comment]
`==> Finished making: libadwaita-without-adwaita-git 1.3.2-5 (Fri 12 May 2023 12:53:47 PM CEST)`
