### ISSUE TITLE
[Question] Feedback on New Issue Templates?

### ISSUE THREAD

**Issue by xiota** [chaotic-aur/packages#2466]
Issue templates have been modified (#2465, [Open New Issue](https://github.com/chaotic-aur/packages/issues/new/choose)).  The goal is to make maintenance decisions easier by improving the accuracy and relevance of responses.  Feel free to respond here with emojis, suggestions, or other feedback.

**Comment by xiota** [comment]
Should there be a separate template for download and key errors?

**Comment by Technetium1** [comment]
I don't think that's entirely necessary, but it wouldn't hurt.

**Comment by xiota** [comment]
I'm planning to update issue templates because of unexpected responses.  Anyone interested can [take a look](https://github.com/xiota/chaotic-packages/issues/new/choose).

**Comment by Technetium1** [comment]
@xiota `already available`: https://github.com/chaotic-aur/packages/commit/78666dbdaf664b3e587dbec0e9c017cdfe8476c8#diff-f721fa61cdfc2ed66db14f57693137ddc34ba0f68a57a5af8aebf240c45dbff3R59
Otherwise looks great!

**Comment by xiota** [comment]
Took me a moment too long to find the mistake.

**Comment by Technetium1** [comment]
No worries it's fantastic!

**Comment by xiota** [comment]
Will give it another once over and commit tomorrow... Then be surprised by the creative ways people find to answer questions.
