### ISSUE TITLE
[Outdated] linux-tkg-*

### ISSUE THREAD

**Issue by pkejval** [chaotic-aur/packages#2471]
### Outdated Package

All linux-tkg-* packages are in 6.2 kernel version. There is 6.3 released already for 3 weeks.
https://github.com/Frogging-Family/linux-tkg

### Latest chaotic version

6.2

### Latest upstream version

6.3

**Comment by dr460nf1r3** [comment]
(will take a while to build but it's on the way)

**Comment by njdom24** [comment]
Could this be reopened? Currently building 6.5, but 6.6 is stable.

**Comment by dr460nf1r3** [comment]
Hum, we need to automate this somehow. New versions currently need our toolbox code to be changed, which causes this whole situation.
