### ISSUE TITLE
[Request] an-anime-game-launcher-bin

### ISSUE THREAD

**Issue by TheFlomax** [chaotic-aur/packages#2472]
### Requested Package:

[an-anime-game-launcher-bin](https://aur.archlinux.org/packages/an-anime-game-launcher-bin)

### Purpose and Use?

This package is a custom launcher to apply a patch to play [an anime game] on Arch Linux. It also ensures the continuity of the updates of the game and allows the inequalities as the Discord RPC, MangoHud, etc...

### Benefits?

It is the only one in its category to be a "One-Click" solution for the installation and configuration of the game.

### Builds in clean chroot?

The following build procedure is provided on the GitHub project page :

git clone https://aur.archlinux.org/packages/an-anime-game-launcher-bin.git

cd an-anime-game-launcher-bin

makepkg -si

### Copyright License?

no

### Expected interest

Less than half.

### Prior availability?

I don't know

### Is this request unique?

I don't know

### Is the package banned?

No

### More information

About
An Anime Game launcher for Linux with automatic patching and telemetry disabling. Our discord server: https://discord.gg/ck37X6UWBp

**Comment by xiota** [comment]
I don't see any obvious packaging issues.  Dropping the other package in favor of this one.
