### ISSUE TITLE
[Bug] Mangoapp/Mangohud invalid or corrupted package (PGP signature) 

### ISSUE THREAD

**Issue by rejedai** [chaotic-aur/packages#2473]
### Affected Package

[mangoapp](https://aur.archlinux.org/packages/mangoapp)
[mangohud](https://aur.archlinux.org/packages/mangohud)
[mangohud-common](https://aur.archlinux.org/packages/mangohud-common)

### Latest chaotic version

0.6.9.1-2

### What happens?

When trying install got error: 
```
error: mangohud: signature from "Pedro Henrique Lara Campos <root@pedrohlc.com>" is invalid
:: File /var/cache/pacman/pkg/*-0.6.9.1-2-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
```

### What is expected to happen?

Package should be installed

**Comment by xiota** [comment]
Should be fixed now.
