### ISSUE TITLE
[Maintenance] Drop packages that require libadwaita newer than available

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#2478]
### Affected Package

[epiphany-git](https://aur.archlinux.org/packages/epiphany-git)

### Latest chaotic version

`Not building`

### What happens?

`found 1.3.2 but need: '>= 1.4.alpha'`

### What is expected to happen?

This is expected since `>=1.4.alpha` is not available.

### If possible, please attach logs

[epiphany-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/epiphany-git.log)

I've flagged the package out of date for missing `cmake` in `makedepends`.
Changes were just dropped from interfere because they should be unnecessary now, and to troubleshoot the failed build: https://github.com/chaotic-aur/packages/issues/2406 / https://github.com/chaotic-aur/interfere/commit/01575636ed3abbad638726b85ffb66ff30944cec

**Comment by xiota** [comment]
Also: `Dependency webkitgtk-6.0 found: NO found 2.40.1 but need: '>= 2.41.1'`

**Comment by xiota** [comment]
Looks like `libadwaita-git` is broken (for a while) and blocking lots of packages.  At what point should excising the dependency tree be considered?

**Comment by dr460nf1r3** [comment]
You mean as in removing packages depending on it?

**Comment by xiota** [comment]
Yes, I am suggesting to remove `libadwaita-git` and any dependent that cannot be built with `extra/libadwaita`.  The packages are very broken, mostly from the same maintainer.  For instance, `gnome-shell-git` now depends on a package that has never existed.

**Comment by xiota** [comment]
Dropped `libadwaita-git` and a bunch of broken related packages.

**Comment by xiota** [comment]
`gnome-calendar-git` and `gnome-contacts-git` may be salvageable.  Will look more closely at them later.

**Comment by xiota** [comment]
Closing as complete.
