### ISSUE TITLE
[Rebuild] numix-circle-icon-theme-git fails to install with "Maximum file size exceeded" error

### ISSUE THREAD

**Issue by sudoBash418** [chaotic-aur/packages#2481]
### Packages to rebuild

[numix-circle-icon-theme-git](https://aur.archlinux.org/packages/numix-circle-icon-theme-git)

### Latest chaotic version

23.04.28.r0.g6455f94-1

### Reason for rebuild

pacman fails to download the package with the following error message:
```
error: failed retrieving file 'numix-circle-icon-theme-git-23.04.28.r0.g6455f94-1-any.pkg.tar.zst' from cdn-mirror.chaotic.cx : Maximum file size exceeded
```

If I understand similar bug reports correctly, the package needs to be rebuilt to fix this issue.

**Comment by xiota** [comment]
Rebuilt `numix-circle-icon-theme-git` and `numix-icon-theme-git`.  But found some others with problems.

**Comment by xiota** [comment]
Closing this now.  Comment here if you find problems with similar/related packages.
