### ISSUE TITLE
[Rebuild] Prelockd

### ISSUE THREAD

**Issue by Boria138** [chaotic-aur/packages#2482]
### Packages to rebuild

[Prelockd](https://aur.archlinux.org/packages/prelockd)

### Latest chaotic version

0.9-2.3

### Reason for rebuild

Broken service

### More information

The service does not start fixed by adding ```sed -i '14d;25d' prelockd.service.in```  to the prepare section in pkgbuild

**Comment by xiota** [comment]
Does it work now?

**Comment by Boria138** [comment]
> Does it work now?

If you change the pkgbuild as I described, yes

**Comment by norz3n** [comment]
> Does it work now?

Yes, I've already checked that with myself.

**Comment by xiota** [comment]
To clarify.  Does the version in chaotic (0.9-3) work now?

**Comment by Boria138** [comment]
> 

Yes it`s worked now

**Comment by norz3n** [comment]
Yes, this daemon now works correctly
