### ISSUE TITLE
[Request]  Userspace KSM helper daemon. (uksmd)

### ISSUE THREAD

**Issue by Boria138** [chaotic-aur/packages#2483]
### Requested Package:

[uksmd](https://aur.archlinux.org/packages/uksmd)

### Purpose and Use?

The daemon goes through the list of userspace tasks (once per 5 seconds) and hints them to apply MADV_MERGEABLE to anonymous mappings for ksmd kthread to merge memory pages with the same content. Only long-living tasks are hinted (those that were launched more than 10 seconds ago).

### Copyright License?

GNU GPL v3 

### Expected interest

Some.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by xiota** [comment]
Dropped because no longer available on AUR.  Upstream reported to have ceased development.  Metrics 31.
