### ISSUE TITLE
[Request] uksmd-git

### ISSUE THREAD

**Issue by norz3n** [chaotic-aur/packages#2486]
### Requested Package:

[uksmd-git](https://aur.archlinux.org/pkgbase/uksmd-git)

### Purpose and Use?

This daemon will allow to merge similar memory pages in automatic mode if the kernel is known to support it

### Builds in clean chroot?

Yes

### Copyright License?

GPL3

### Expected interest

More than half.

### Prior availability?

No

### Is this request unique?

No

### Is the package banned?

No

**Comment by xiota** [comment]
Dropped because no longer available on AUR.  Upstream reported to have ceased development.  Metrics 2.
