### ISSUE TITLE
[Bug] zrythm-debug

### ISSUE THREAD

**Issue by R-a-l-f** [chaotic-aur/packages#2496]
### Affected Package

[zrythm](https://aur.archlinux.org/packages/zrythm)

### What happens?

Hi,

zrythm-debug isn't available by the chaotic-aur mirrors.
Building the package from [AUR](https://aur.archlinux.org/packages/zrythm) results in the packages zrythm and zrythm-debug.

pacman claims that it is available

$ pacman -Si zrythm-debug | head -3
Repository      : chaotic-aur
Name            : zrythm-debug
Version         : 1.0.0.beta.4.9.1-1

but it isn't, see

https://builds.garudalinux.org/repos/chaotic-aur/x86_64/

or try to install it.

Regards,
Ralf

**Comment by xiota** [comment]
rebuilt

**Comment by R-a-l-f** [comment]
Thank you for fixing the issue quickly.
