### ISSUE TITLE
[Remove] openvino-git

### ISSUE THREAD

**Issue by caniko** [chaotic-aur/packages#2497]
### Requested Package:

[openvino-git](https://aur.archlinux.org/packages/openvino-git)

### Purpose and Use?

https://docs.openvino.ai/latest/home.html

Me specifically: Running stable diffusion on my A770 with [this](https://github.com/bes-dev/stable_diffusion.openvino) with latest upstream commits

### Copyright License?

Apache License 2.0

### Expected interest

Some.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by Technetium1** [comment]
The build is failing: [openvino-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/openvino-git.log)

**Comment by xiota** [comment]
Rebuilt.

**Comment by xiota** [comment]
Fails to build.  Considering switching to stable `aur/openvino`.
```
error: inlining failed in call to ‘always_inline’ ‘_mm256_storeu_si256(long long __vector(4)*, long long __vector(4))’: target specific option mismatch
```

Metrics 491.
