### ISSUE TITLE
[Request] Mysql Workbench

### ISSUE THREAD

**Issue by Bhooty** [chaotic-aur/packages#2502]
### Requested Package:

https://archlinux.org/packages/extra/x86_64/mysql-workbench/

### Purpose and Use?

To write sql and procedures of mysql or mariadb for testing

### Copyright License?

N/A

### Expected interest

Many.

### Prior availability?

I don't know

### Is this request unique?

Yes

### Is the package banned?

No

### More information

For some reason, the aur package doesn’t seem to include gnome-keyring 
Without gnome-keyring, the app won’t start and throw the error
The name org.freedesktop.secrets was not provided by any .service files

**Comment by xiota** [comment]
Rejected because already in extra.

**Comment by dr460nf1r3** [comment]
@Bhooty did I understand it the right way, you wanted gnome-keyring added to the deps?

**Comment by Bhooty** [comment]
> @Bhooty did I understand it the right way, you wanted gnome-keyring added to the deps?

No I meant that the software needs gnome-keyring. So when installing include it.
I maybe wrong and it’s included but when I installed from the repo in endeavour os 
Had to search and found out the reason the app doesn’t start cause gnome-keyring is not working

**Comment by dr460nf1r3** [comment]
I deleted my comment right after I noticed the link you provided yourself went to the Arch repos (as xiota pointed out already) - sadly there is nothing we can do in this case. You'll notice the PKGBUILD contains `libsecret`, which pulls either `gnome-keyring` or `keepass-xc` :eyes:

**Comment by Bhooty** [comment]
> I deleted my comment right after I noticed the link you provided yourself went to the Arch repos (as xiota pointed out already) - sadly there is nothing we can do in this case. You'll notice the PKGBUILD contains `libsecret`, which pulls either `gnome-keyring` or `keepass-xc` though 👀

Oww okay sir
Thanks for the clarification
