### ISSUE TITLE
[Request] gnome-shell-extension-desktop-icons-ng-git

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2506]
### Requested Package:

[gnome-shell-extension-desktop-icons-ng-git](https://aur.archlinux.org/packages/gnome-shell-extension-desktop-icons-ng-git)

### Purpose and Use?

Desktop icons project, with several enhancements like Drag'n'Drop.

### Benefits?

This package offers desktop icons shown on the GNOME Desktop and enhanced drag and drop feature. The git package contains the most updated changes that are still not present in the normal package.

### Copyright License?

No source

### Expected interest

More than half.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by xiota** [comment]
`gnome-shell-extension-desktop-icons-ng` has been moved to `extra`.  Is the -git package still needed?

**Comment by Technetium1** [comment]
Releases seem _very_ infrequent, let's keep this for now.

**Comment by xiota** [comment]
Dropping because `extra/gnome-shell-extension-desktop-icons-ng` is available.  Currently five commits difference between stable and git versions.  Time between most recent releases is a few months.    Metrics 45.
