### ISSUE TITLE
[Request] gnome-shell-extension-vitals-git

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2511]
### Requested Package:

[gnome-shell-extension-vitals-git](https://aur.archlinux.org/packages/gnome-shell-extension-vitals-git)

### Purpose and Use?

Displays system vitals in a GNOME Shell top bar pop-down.

### Benefits?

Good tool for monitoring temperature, voltage, fan speed, memory usage and CPU load.

### Copyright License?

https://github.com/corecoding/Vitals/blob/main/LICENSE

### Expected interest

More than half.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by xiota** [comment]
Dropping because `extra/gnome-shell-extension-vitals` is available.  Currently no difference between stable and git versions.  Metrics 43.
