### ISSUE TITLE
[Request] gpt4all-chat-git

### ISSUE THREAD

**Issue by ShivamKumar2002** [chaotic-aur/packages#2514]
### Requested Package:

[gpt4all-chat-git](https://aur.archlinux.org/packages/gpt4all-chat-git)

### Purpose and Use?

It is very useful app for using open-source LLMs locally.

### Copyright License?

https://github.com/nomic-ai/gpt4all/blob/main/gpt4all-chat/LICENSE

### Expected interest

Many.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by Technetium1** [comment]
This is missing a dependency: [gpt4all-chat-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/gpt4all-chat-git.log)

**Comment by ShivamKumar2002** [comment]
> 

This is a new dependency. I guess we have to wait till aur package gets updated.

**Comment by xiota** [comment]
Fails to build.  Will watch.  Metrics 60.
```
CMake Error at deps/Jinja2Cpp/cmake_install.cmake:71 (file):
  file INSTALL cannot find
  "/home/builder/build/src/gpt4all/gpt4all-chat/deps/Jinja2Cpp/thirdparty/nonstd/expected-lite/include/nonstd/expected.hpp":
  No such file or directory.
Call Stack (most recent call first):
  deps/cmake_install.cmake:67 (include)
  cmake_install.cmake:47 (include)
```

**Comment by xiota** [comment]
Fails to build.  Looks like upstream mistake.  Taking as opportunity to note current metrics: 486.

**Comment by xiota** [comment]
Switching to a custom package.  The embedding model, used for the LocalDocs feature, will be in a separate package (`gpt4all-chat-data`) to improve bandwidth and storage usage.  Metrics 68.
