### ISSUE TITLE
[Request] archiso-git

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2517]
### Requested Package:

[archiso-git](https://aur.archlinux.org/packages/archiso-git)

### Purpose and Use?

Archiso is a very useful tool for creating Arch Linux-based ISO.

### Benefits?

The choice of using -git version is due to the current stable version has a bug on copying folders from /boot folder. This issue (and also other issues) has been solved on -git version.

### Copyright License?

https://gitlab.archlinux.org/archlinux/archiso/-/blob/master/LICENSE

### Expected interest

Many.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by xiota** [comment]
Dropping because `extra/archiso` is available and low usage.  Metrics 4.

There is currently no difference between stable and git packages.
