### ISSUE TITLE
[Rebuild] forkgram

### ISSUE THREAD

**Issue by Sad-Soul-Eater** [chaotic-aur/packages#2518]
### Packages to rebuild

[forkgram](https://aur.archlinux.org/packages/forkgram)

### Latest chaotic version

4.8.1-1.2

### Reason for rebuild

qt6 package update

### More information

```
# pacman -Q qt6-base
qt6-base 6.5.1-1
```

```
# telegram-desktop
Cannot mix incompatible Qt library (6.5.0) with this library (6.5.1)
zsh: IOT instruction (core dumped)  telegram-desktop
```

**Comment by xiota** [comment]
Build failed.  No idea why.  [forkgram.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/forkgram.log)
```
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
```

**Comment by dr460nf1r3** [comment]
```
> forkgram-4.8.1-1.3-x86_64.pkg.tar.zst
> forkgram-4.8.1-1.3-x86_64.pkg.tar.zst.sig
```

**Comment by Technetium1** [comment]
@xiota indeed they are, somewhat unfortunately. If they'd all have feature parity it wouldn't be such a fragmented mess. I'm guilty of using forks that randomly break and don't always have the best update frequency... but they just work well and feel nice[when they work]. It is a nice convenience to provide them.

**Comment by xiota** [comment]
I'll keep trying to fix them then.  But drops may be unavoidable when the methods stop working.

**Comment by xiota** [comment]
Last build: 4.14.3-1 on 2024-01-04.

**Comment by REmerald** [comment]
@xiota 
```
forkgram: error while loading shared libraries: libprotobuf-lite.so.28.2.0: cannot open shared object file: No such file or directory
```
