### ISSUE TITLE
[Request] spleeter-git

### ISSUE THREAD

**Issue by fwookerton** [chaotic-aur/packages#2519]
### Requested Package:

https://aur.archlinux.org/packages/spleeter-git

https://aur.archlinux.org/packages/spleeter
https://aur.archlinux.org/packages/spleeter2

### Purpose and Use?

Deezer source separation library and tool using pretrained models, so it basically allows you to separate stems from an audio file.

### Benefits?

- It allows you to split stems from an existing audio file.

### Builds in clean chroot?

No idea.

### Copyright License?

MIT

### Expected interest

Some.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by Technetium1** [comment]
[`Spleeter`](https://aur.archlinux.org/pkgbase/spleeter/flag-comment) is currently flagged out of date

**Comment by Technetium1** [comment]
@xiota it isn't just a library, it is a standalone application with access to already trained models. Fine to add after packages merge (if it builds): https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/message/253PC2AOYAWIQJVO3KVXGK4OVCIOZZ5K/

**Comment by xiota** [comment]
The package descriptions state that it is a library.  I've asked for the descriptions to be updated on the AUR pages.

The maintainer of `spleeter` removed the out-of-date flag without updating and posted a comment indicating resistance to updating to 2.x.  I've reflagged.

There have been 57 commits since 2.3.0 was released in 2021.  I am creating a package `spleeter-git`.  I am also tracking down the dependencies.

**Comment by Technetium1** [comment]
@xiota I think you made the best description so far [here](https://aur.archlinux.org/packages/spleeter#comment-917640)!

**Comment by xiota** [comment]
@fwookerton I'm going to consider this request fulfilled with `spleeter-git`.  I've edited the title of this request and the initial description to reflect this.

The main problem with `spleeter`/`spleeter2` is the dependency tree related to `python-librosa`.  The transitive dependencies have issues that complicate building.  Basically had enough with trying to get this working.
