### ISSUE TITLE
[Request] nuitka-git

### ISSUE THREAD

**Issue by xAffan** [chaotic-aur/packages#2524]
### Requested Package:

[nuitka-git](https://aur.archlinux.org/packages/nuitka-git)

### Purpose and Use?

Compile python programs into C++. The binary of nuitka can be easily installed but it does not support the latest python 3.11. So whenever python updates, it's needed to use nuitka-git package.

### Benefits?

This is a git package that can give latest changes, there are no other packages in aur for nuitka.

### Copyright License?

Apache 2.0
https://github.com/Nuitka/Nuitka/blob/develop/LICENSE.txt

### Expected interest

Some.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by xiota** [comment]
According to [Nuitka Release 1.5](https://nuitka.net/posts/nuitka-release-15.html), Nuitka 1.5 includes Python 3.11 support.

**Comment by xAffan** [comment]
I forgot to mention - there is experimental support in 1.5.
However quote from their blog reads 

> For the next release, full Python 3.11 support is planned. I believe it should be usable. Problems with 3.11 may get hotfixes, but ultimately the develop version is probably the one to recommend when using 3.11 with Nuitka, as there will be the whole set of fixes, since not everything will be ported back.

**Comment by xiota** [comment]
`extra/nuitka` is now at version 1.6.  Looks like there are new releases every couple weeks.

I'm still interested in use cases.

**Comment by xAffan** [comment]
The only use case would be to test development builds in order to submit bug reports and as such. other than that, i do not see a use case - at least for my self.

**Comment by xiota** [comment]
Fails to build in clean chroot.  Missing `python-setuptools` in `makedepends`.

> test development builds in order to submit bug reports

Why not build it yourself locally?  After fixing the missing dependency, it took less than two minutes to build in a clean chroot.  Then you'd could have up-to-the-minute builds, rather than wait hours to days for the build server.  You'd also need to build yourself to test fixes.

> i do not see a use case - at least for my self

I see... if no one would use it, then why (fix and) add it to chaotic?

**Comment by xAffan** [comment]
Hm, rather close the issue then since my original use case is gone
