### ISSUE TITLE
[Request] ttf-material-design-icons-extended

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2528]
### Requested Package:

[ttf-material-design-icons-extended](https://aur.archlinux.org/packages/ttf-material-design-icons-extended)

### Purpose and Use?

This package provides a lot of icons used in different tools like neofetch, ls-like and similar.

### Benefits?

It prevents that some tools show weird icons instead of the intended ones.

### Copyright License?

https://pictogrammers.com/docs/general/license/

### Expected interest

More than half.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by xiota** [comment]
Is special configuration required for these fonts to work with the apps you listed?  Isn't neofetch basically abandoned?

**Comment by D3vil0p3r** [comment]
> Is special configuration required for these fonts to work with the apps you listed? Isn't neofetch basically abandoned?

There are a lot of neofetch like programs, for example hyfetch, bfetch, screenfetch, fastfetch... There are a lot of them. Hyfetch is a direct clone of neofetch (only the binary filename changes).

**Comment by D3vil0p3r** [comment]
@xiota uhm I tested what you said some days ago. For this package, it automagically find and use icon fonts. The system detects automatically them by reading (if I'm not wrong) the folder `/usr/share/fonts`.

**Comment by xiota** [comment]
I see no difference in output from `hyfetch` with and without this font installed.

**Comment by D3vil0p3r** [comment]
> I see no difference in output from `hyfetch` with and without this font installed.

It depends on the HyFetch theme you are applying. For example, if you are using an HyFetch theme with already recognized icon fonts, of course they will be always the same. If you are using another HyFetch/Neofetch theme (there are a lot online) or you are using a theme u customized or created, and you don't see some icons, that derive from Material Design Icons, if you dont have this package installed, you will see only a "square" character". The Material Design Icons of the packages are from: https://pictogrammers.com/library/mdi/ and imho are better than Nerd Fonts.

Tell me if it is not clear please.

**Comment by Technetium1** [comment]
@xiota depends on app configuration, it does not override by default, only adds another TTF to fonts.

**Comment by xiota** [comment]
What makes this font "extended"?  I don't see it explained on AUR page or font homepage.

**Comment by Technetium1** [comment]
Package is currently flagged and needs to be updated.

@xiota extended by inclusion of converted Google symbols: https://github.com/google/material-design-icons#material-symbols--material-icons
