### ISSUE TITLE
[Request] tblock-gui

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#2529]
### Requested Package:

https://aur.archlinux.org/packages/tblock-gui

### Purpose and Use?

Official graphical user interface for the TBlock content blocker

### Copyright License?

https://www.gnu.org/licenses/gpl-3.0.en.html

### Expected interest

Everyone.

### Prior availability?

Yes

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by twann4** [comment]
I was going to open an issue to suggest this package but noticed there already was a request ;)
