### ISSUE TITLE
[Request] Nekoray 

### ISSUE THREAD

**Issue by barfin** [chaotic-aur/packages#2531]
### Requested Package:

[nekoray](https://aur.archlinux.org/packages/nekoray)

### Purpose and Use?

It helps users bypass the Great Firewall of Iran and China
compiling this package takes a very long time and has lots of dependencies for iranian users who struggle with data caps this can be a hard package to compile

### Benefits?

other solutions as gui don't exist

### Copyright License?

GPL-3.0 license

### Expected interest

Some.

### Prior availability?

No

### Is this request unique?

No

### Is the package banned?

No

### More information

this package was added before but cause [launching issues](https://github.com/chaotic-aur/packages/issues/2110) was removed, however it's been months since that bug report, please check if that bug still occurs.

**Comment by xiota** [comment]
Dropped because no longer in AUR. Metrics 350.
