### ISSUE TITLE
[Bug] python39 does NOT come included with tkinter

### ISSUE THREAD

**Issue by fwookerton** [chaotic-aur/packages#2532]
### Affected Package

[https://aur.archlinux.org/packages/python39](https://aur.archlinux.org/packages/python39)

### Latest chaotic version

3.9.16-2

### What happens?

When I try to run a program that depends on `tk`, it will not run due to it missing the aforementioned module.

### What is expected to happen?

The program should show up the GUI.

### If possible, please attach logs

```
$ python3.9 UVR.py
Traceback (most recent call last):
  File "/home/flookerton/Repos/ultimatevocalremovergui/UVR.py", line 26, in <module>
    import tkinter as tk
  File "/usr/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

```
$ python3.9 -m tkinter
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

```

### More information

In comparison to Chaotic's `python39`, running `python3.11 -m tkinter` (from the official Arch repos) and `python3.7 -m tkinter` (compiled by myself straight from the AUR) it does show up the test TK dialogue, so I don't know how could this have even happened. Also, installing `tk` from pacman does nothing to fix it.

**Comment by xiota** [comment]
`tk` is missing from `makedepends`.  I've commented on the AUR page to notify the maintainer.

I've bumped and temporarily added the dependency, so it should work for now.

**Comment by xiota** [comment]
Upstream updated the package.  Feel free to comment here if there are any other issues with this package.
