### ISSUE TITLE
[Request] waybar-hyprland

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2534]
### Requested Package:

[waybar-hyprland](https://aur.archlinux.org/packages/waybar-hyprland)

### Purpose and Use?

Highly customizable Wayland bar for Sway and Wlroots based compositors, with workspaces support for Hyprland. Very useful for Hyprland users.

### Copyright License?

MIT

### Expected interest

Many.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by Technetium1** [comment]
Deletion requested, see: https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/message/XJJXAZWYBRNJCTS6MUJZZJGULKBOK33Q/

**Comment by D3vil0p3r** [comment]
@Technetium1 according to the discussion here https://aur.archlinux.org/packages/waybar-hyprland#comment-919277 I think that the deletion request could be misleading because the original waybar package is still affected by some bugs that the requested package above will fix. According to the explanation of Waybar contributor in the comments, imho is worth to request `waybar-hyprland` and/or `waybar-hyprland-git` packages.

**Comment by D3vil0p3r** [comment]
About the upstream-fix label, in theory `waybar-hyprland` works correctly, so it can be deployed with no issue.

**Comment by Technetium1** [comment]
It may work as-is; but we make a habit to not add things to the repo when they're in an outdated state: https://github.com/Alexays/Waybar/releases/tag/0.9.18

**Comment by xiota** [comment]
No longer useful, based on [comment](https://aur.archlinux.org/packages/waybar-hyprland#comment-931819).

> ... you should no longer use this package, as upstream [hyprland] seems to have eliminated the direct usage of `hyprctl` CLI to manipulate and query hyprland workspaces. Instead, they have implemented direct support for workspaces and persistent workspaces on hyprland in `waybar 0.9.22`. The workaround utilized in this patched build should not be needed anymore.
