### ISSUE TITLE
[Remove] nwg-look-bin

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2535]
### Requested Package:

[nwg-look-bin](https://aur.archlinux.org/packages/nwg-look-bin)

### Purpose and Use?

GTK3 settings editor adapted to work in the wlroots environment. Very useful for Hyprland users.

### Copyright License?

MIT

### Expected interest

Many.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by xiota** [comment]
`nwg-look` is in chaotic with version parity to `nwg-look-bin`.  Is there reason to have both?  (Eg, does the normal package tend to have issues?)
