### ISSUE TITLE
[Request] ttf-icomoon-feather

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2537]
### Requested Package:

[ttf-icomoon-feather](https://aur.archlinux.org/packages/ttf-icomoon-feather)

### Purpose and Use?

Beautiful open source icons. Each icon is designed on a 24x24 grid with an emphasis on simplicity, consistency, and flexibility.

### Copyright License?

MIT

### Expected interest

Many.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by xiota** [comment]
Do you have a list of programs that use these?

**Comment by D3vil0p3r** [comment]
> Do you have a list of programs that use these?

Hyprland dotfiles, so unix porn users pretty much. An example of them is this: https://github.com/ChrisTitusTech/hyprland-titus
