### ISSUE TITLE
[Request] hyprpicker-git

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2538]
### Requested Package:

[hyprpicker-git](https://aur.archlinux.org/packages/hyprpicker-git)

### Purpose and Use?

A wlroots-compatible Wayland color picker. Useful for Hyprland users.

### Copyright License?

BSD

### Expected interest

Many.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by Technetium1** [comment]
[I flagged it out of date](https://aur.archlinux.org/pkgbase/hyprpicker-git/flag-comment) for not building in clean chroot.

**Comment by D3vil0p3r** [comment]
I flagged it as orphan. If AUR accepts my request, I will become the maintainer of the package.

**Comment by D3vil0p3r** [comment]
@Technetium1 the package has been updated.

**Comment by Technetium1** [comment]
Thanks, it's missing a dependency so I left [a comment](https://aur.archlinux.org/packages/hyprpicker-git#comment-922615).
