### ISSUE TITLE
[Request] cava

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2541]
### Requested Package:

[cava](https://aur.archlinux.org/packages/cava)

### Purpose and Use?

Famous console-based cross-platform Audio Visualizer for Alsa. Cava is a bar spectrum audio visualizer for terminal (ncurses) or desktop (SDL).

### Copyright License?

MIT

### Expected interest

More than half.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by xiota** [comment]
Metrics when dropped, 3194.
