### ISSUE TITLE
[Request] python-desktop-entry-lib

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2542]
### Requested Package:

[python-desktop-entry-lib](https://aur.archlinux.org/packages/python-desktop-entry-lib)

### Purpose and Use?

A library for working with .desktop files. It allows reading and writing .desktop files according to the [Desktop Entry Specification](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html)

### Copyright License?

BSD

### Expected interest

More than half.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by Technetium1** [comment]
[I flagged this out of date](https://aur.archlinux.org/pkgbase/python-desktop-entry-lib/flag-comment) for not building in a clean chroot.

**Comment by D3vil0p3r** [comment]
Thanks. I left a comment to the maintainer asking to add the missing dependency.

**Comment by D3vil0p3r** [comment]
The missing package has been added: https://aur.archlinux.org/packages/python-desktop-entry-lib

**Comment by D3vil0p3r** [comment]
@Technetium1 The missing package has been added: https://aur.archlinux.org/packages/python-desktop-entry-lib
