### ISSUE TITLE
[Request] geticons-git

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2544]
### Requested Package:

[geticons-git](https://aur.archlinux.org/packages/geticons-git)

### Purpose and Use?

CLI tool to get icons on Linux and other Freedesktop systems

### Copyright License?

GPL

### Expected interest

More than half.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by xiota** [comment]
For standard licenses (GPL, BSD, MIT, etc), it's sufficient to give the name of the license.  Links are only necessary for custom licenses and EULAs.

**Comment by D3vil0p3r** [comment]
> For standard licenses (GPL, BSD, MIT, etc), it's sufficient to give the name of the license. Links are only necessary for custom licenses and EULAs.

Gotcha. I will change them in all requests I opened. Thanks for the tip.

**Comment by Technetium1** [comment]
Invalid pkgver, must be fixed:
```
==> Starting pkgver()...
fatal: No tags can describe '322fba4d3641bfa0ccf72d051e56840508fc5b0d'.
Try --always, or create some tags.
==> ERROR: pkgver is not allowed to be empty.
==> ERROR: pkgver() generated an invalid version:
```

**Comment by D3vil0p3r** [comment]
Tagged as orphan. When AUR accepts, I will take control of it and fix it.

**Comment by D3vil0p3r** [comment]
@Technetium1 the package has been fixed by the maintainer.

**Comment by xiota** [comment]
> Tagged as orphan.

Don't open orphan requests for at least a month or so, after trying to contact the maintainer by other means.  The TUs will ignore or reject it.  Instead, leave a comment and wait a bit.  If there's no response to the comment within about a week, flag "out of date".  Some maintainers don't like the flag, but what else can be done when they disable or ignore notifications?  (Some say to email directly, but reality is those go straight to spam.)  Broken packages from missing dependencies and such are also technically out of date, just not reflected by the version number.

After that, if you still don't get a response from the maintainer, you can add the timeline info to the orphan request, which will make it slightly more likely to be accepted, at the whim of the TUs.

**Comment by D3vil0p3r** [comment]
It was outdated for 1 year. If you see the pkg is now updated is because I reached the maintainer directly today and he updated it.

**Comment by xiota** [comment]
> It was outdated for 1 year.

Was it *flagged* out of date for one year, or just last updated a year ago?  If it was flagged out of date for a year, your orphan request would have been accepted quickly.
