### ISSUE TITLE
[Request] linux-cachyos

### ISSUE THREAD

**Issue by goingtosleep** [chaotic-aur/packages#2548]
### Requested Package:

[linux-cachyos](https://aur.archlinux.org/pkgbase/linux-cachyos)

### Purpose and Use?

Currently there is `linux-cachyos-bore` in `chaotic-aur`. This one `linux-cachyos`, which is the default kernel in cachyos, uses a different scheduler, combination of EEVDF and BORE, could benefit people caring about performance.

### Benefits?

Mentioned above.

### Copyright License?

GPL2

### Expected interest

Some.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by goingtosleep** [comment]
Close as I see it's available in the repo. Many thanks!

![image](https://github.com/chaotic-aur/packages/assets/47395035/6744c67b-b9a9-4ff4-8d95-509afb58bedb)

**Comment by xiota** [comment]
Dropping `linux-cachyos-bore` because looks like default scheduler is now BORE. Metrics 1089.

**Comment by xiota** [comment]
Switched to upstream pkgbuild because aur sync lagging.  Metrics:
* linux-cachyos # 1393
* linux-cachyos-lts # 310

**Comment by D3vil0p3r** [comment]
Hey @xiota when you said above that "looks like default scheduler is now BORE", do you mean that `linux-cachyos` includes on it BORE scheduler? I talked with some CachyOS guys and told me that for a while BORE was in `linux-cachyos` but now no more. If it is ok for you, is it possible to have `linux-cachyos-bore` again in Chaotic AUR?

**Comment by Technetium1** [comment]
@D3vil0p3r Much has changed since the original comment, are you ***really** sure* that there is objective benefit to BORE now? [It's not the default anymore](https://github.com/CachyOS/linux-cachyos/blob/b91624f68ceaf5394ef1571f60290dca6ba22b45/linux-cachyos/config#L276). Can it be proven to be worth adding? https://wiki.cachyos.org/configuration/sched-ext/#testing-scheduler-latency-with-schbench

**Comment by D3vil0p3r** [comment]
Currently, for my personal use no. Btw BORE is not set on the config file. It is enabled inside [PKGBUILD](https://github.com/CachyOS/linux-cachyos/blob/master/linux-cachyos/PKGBUILD) during the process.

**Comment by Technetium1** [comment]
@D3vil0p3r BORE is not set there either, it defaults to `EEVDF`.

**Comment by D3vil0p3r** [comment]
Yes, default of the PKGBUILD is `EEVDF` but usually CachyOS team set the several variables inside it at CI/CD level if I remember well.

**Comment by xiota** [comment]
@D3vil0p3r If you don't use BORE, what would be the point of re-adding it?  What concrete use cases would it actually benefit?  My understanding is that EEVDF already "allows latency-sensitive tasks with shorter time slices to be prioritized, which helps with their responsiveness."

**Comment by D3vil0p3r** [comment]
Sorry @xiota , it was "now", I missed the last "w". If it is not feasible, don't worry.

**Comment by xiota** [comment]
I added linux-cachyos-bore and have been running it on a few machines with different core/thread counts.  There is no noticeable difference in latency.  Admittedly, I haven't run any benchmarks, but the point of switching schedulers is that there would be an appreciable difference.  To the extent that there isn't, there's no point switching.

I'll leave it in the repo in case others want to try, but it may be dropped if it develops problems that require manual intervention.  (Will leave alone as long as it auto-builds successfully.)
