### ISSUE TITLE
[Rebuild] nomacs

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#2554]
### Packages to rebuild

[nomacs](http://aur.archlinux.org/packages/nomacs)

### Latest chaotic version

`1:3.17.2206-13`

### Reason for rebuild

```
nomacs: error while loading shared libraries: libexiv2.so.27: cannot open shared object file: No such file or directory
```

### Logs for the latest build, if available

[nomacs.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/nomacs.log)

**Comment by xiota** [comment]
Failing to rebuild.  Haven't looked at specific reasons, but suspect breaking changes in `exiv2`.  Packages that appear to be affected:

- [ ] gwenview-git
- [ ] kfilemetadata-git
- [ ] libkexiv2-git
- [ ] nomacs
- [ ] photoqt
- [ ] siril

**Comment by niobium93** [comment]
Looks like it got updated and built.
