### ISSUE TITLE
[Rebuild] qimgv-git

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#2555]
### Packages to rebuild

[qimgv-git](http://aur.archlinux.org/packages/qimgv-git)

### Latest chaotic version

`v1.0.3.alpha.r85.g22a8f2e-1.2`

### Reason for rebuild

```
qimgv: error while loading shared libraries: libexiv2.so.27: cannot open shared object file: No such file or directory
```

### Logs for the latest build, if available

[qimgv-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/qimgv-git.log)

**Comment by xiota** [comment]
Already automatically rebuilt:
```
$ pacman -Ss qimg
chaotic-aur/qimgv-git v1.0.3.alpha.r87.g00b3a6c-1
    Qt image viewer. Fast, configurable, easy to use. Supports video playback.
```
