### ISSUE TITLE
[Request] envycontrol

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2556]
### Requested Package:

[envycontrol](https://aur.archlinux.org/packages/envycontrol)

### Purpose and Use?

envycontrol is a simple and useful tool used for switching GPUs (integrated and dedicated) in Dual GPU computers.

### Benefits?

envycontrol currently is the only tool that is able to switch GPUs both on Xorg and Wayland environment. Unlike Optimus Manager tool, envycontrol does not need additional patching on GDM.

### Copyright License?

MIT

### Expected interest

More than half.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by xiota** [comment]
> Expected interest
>
> More than half.

More than half of chaotic users have dual-GPU systems?  I don't, so can't test this, but does look useful.

**Comment by D3vil0p3r** [comment]
> > Expected interest
> > More than half.
> 
> More than half of chaotic users have dual-GPU systems? I don't, so can't test this, but does look useful.

In my Discord Arch community I see a lot of them, among Integrated Intel Graphic card + Dedicated NVIDIA (like me) and Integrated AMD Graphic card + Dedicated NVIDIA.

**Comment by xiota** [comment]
Vast majority of computers I see for sale don't have (or don't advertise) dual GPU.  So I would expect only a small percentage of users have them.  It's possible to see a lot of something without exceeding half of the population.  Before even reaching a third, you'd start seeing something "everywhere".

**Comment by D3vil0p3r** [comment]
I provide you some source. The integration of GPUs in CPU is not new and it started on the last 10 years for Intel and AMD. Of course, not all CPUs have an Integrated GPU but, for example, for Intel, only the F and KF series don't have an iGPU, while all the other series (K, KS, T, E, H, HK) yes.
About AMD, according to some articles, most AMD-powered laptops come with an iGPU. I think that one of the reasons we don't perceive these numbers is because the average of users are not technical, so they are not able to recognize if their machine has a iGPU or not.
Here one the source: https://10scopes.com/do-all-cpus-have-integrated-graphics-card/

**Comment by xiota** [comment]
I suppose it could be a hidden spec.  Next time I'm at a store, I'll look for an unlocked machine to see what device manager says.

**Comment by D3vil0p3r** [comment]
> I suppose it could be a hidden spec. Next time I'm at a store, I'll look for an unlocked machine to see what device manager says.

Let me know please ^^
