### ISSUE TITLE
[Request] hyprshot

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2560]
### Requested Package:

[hyprshot](https://aur.archlinux.org/packages/hyprshot)

### Purpose and Use?

A utility to easily take screenshots in Hyprland using your mouse.

### Copyright License?

GPL

### Expected interest

Many.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by xiota** [comment]
Dropped because moved to extra.  Metrics 1170.
