### ISSUE TITLE
[Request] wl-gammactl

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2561]
### Requested Package:

[wl-gammactl](https://aur.archlinux.org/packages/wl-gammactl)

### Purpose and Use?

Command-line / GUI utility for setting contrast, brightness and gamma on wlroots based compositors. It is very useful on Hyprland environment.

### Copyright License?

MIT

### Expected interest

Many.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by Technetium1** [comment]
[I flagged it out of date](https://aur.archlinux.org/pkgbase/wl-gammactl/flag-comment) because it's missing deps to build in clean chroot.

**Comment by D3vil0p3r** [comment]
Tagged as orphan. Missing dependencies: cmake (makedep) and wlroots (dep). I will take control of it if my request will be accepted by AUR. I keep you updated.

**Comment by D3vil0p3r** [comment]
@Technetium1 the package has been updated.

**Comment by xiota** [comment]
Fails to build.  Maintainer notified Nov 2024.  Fixed with interfere.  Metrics 24.

Difficult to package "properly".  Upstream project has no stable releases, but repo is flattened to a single commit, so not suitable for a -git package either.
