### ISSUE TITLE
[Request] virtualbox-unattended-templates

### ISSUE THREAD

**Issue by mdhishamsayed** [chaotic-aur/packages#2564]
### Requested Package:

https://aur.archlinux.org/packages/virtualbox-unattended-templates

### Purpose and Use?

Unattended Templates for Virtualbox

### Benefits?

Unattended templates

### Builds in clean chroot?

Yes

### Copyright License?

GPL3

### Expected interest

Some.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by Technetium1** [comment]
Currently flagged out of date.

**Comment by mdhishamsayed** [comment]
@Technetium1 Fixed...
