### ISSUE TITLE
[Request] penguins-eggs

### ISSUE THREAD

**Issue by pieroproietti** [chaotic-aur/packages#2565]
### Requested Package:

[penguins-eggs](https://aur.archlinux.org/packages/penguins-eggs)

### Purpose and Use?

penguins-eggs is a remastering tool that configures calamares to install the live system you create or uses your own TUI installer, a quick installer that tries, as much as possible to imitate, in form and function the much better known calamares.

With penguins-eggs you can create live systems on Arch, Debian, Devuan, Ubuntu, Manjaro and derivatives.

### Benefits?

I don't think there are any alternatives in arch, plus the tool being common to Debian/Devuan and Ubuntu might facilitate switching from one distribution to another.

### Builds in clean chroot?

`makepkg -srcCi`

### Copyright License?

https://github.com/pieroproietti/penguins-eggs/blob/master/LICENSE

### Expected interest

Many.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

### More information

* site: https://penguins-eggs.net
* repo: https://github.com/pieroproietti/penguins-eggs

**Comment by xiota** [comment]
To test building in clean chroot, try `extra-x86_64-build`.

**Comment by xiota** [comment]
@pieroproietti Fails to build.  Will drop if not fixed with next commit.  Missing makedep on `pnpm`.
```
/home/builder/build/PKGBUILD: line 60: pnpm: command not found
```

**Comment by pieroproietti** [comment]
Thanks  @xiota, fixed!

**Comment by xiota** [comment]
@pieroproietti Please enable aurweb notifications for the package, if not already enabled.  I had commented there about the issue, but two commits had been pushed without fixing it.

**Comment by xiota** [comment]
@pieroproietti The package was deleted from AUR at your request.  [PRQ#83439](https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/thread/NKXFNU23VCJFTV3KHMGDTM4APGTFEGNL)

Do you have ETA on when the replacement packages will be ready?  Do you need or want help?

Metrics 19.

**Comment by pieroproietti** [comment]
Hi @xiota thanks,

I can replace It with two new ones: penguins-eggs and penguins-eggs-legacy.

All must to be ok, but let me to take sane days off, and we will see that to do.

Actually they live in a mine custom native repository for all distros supported: https://penguins-eggs.net/repos/.
