### ISSUE TITLE
[Request] minq-ananicy-git

### ISSUE THREAD

**Issue by mdhishamsayed** [chaotic-aur/packages#2568]
### Requested Package:

https://aur.archlinux.org/packages/minq-ananicy-git

### Purpose and Use?

Ananicy-CPP does not run when BPF is disabled on xanmod kernel, so the way to run may be using ananicy or disable bpf.
so this version of ananicy does not depend on bpf and is updated more frequently

### Benefits?

Minq Ananicy - fork of Ananicy with support for cmdline and more frequently updated rules

### Builds in clean chroot?

Yes

### Copyright License?

GPL3

### Expected interest

Some.

### Prior availability?

No

### Is this request unique?

I don't know

### Is the package banned?

No

### More information

Both ananicy and minq-ananicy conflict, but not written in their respective pkgbuilds, so i request to append conflicts via interference

**Comment by xiota** [comment]
> Both ananicy and minq-ananicy conflict, but not written in their respective pkgbuilds, so i request to append conflicts via interference

@mdhishamsayed  Please comment on respective AUR pages to request maintainers add the conflicts directly to the packages.
