### ISSUE TITLE
[Rebuild] rofi-lbonn-wayland

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2569]
### Requested Package:

[rofi-lbonn-wayland](https://aur.archlinux.org/packages/rofi-lbonn-wayland)

### Purpose and Use?

A window switcher, application launcher and dmenu replacement.

### Benefits?

This package is the Wayland fork of Rofi (that works on Xorg). It means that this package could also work on window managers based only on Wayland as Hyprland (while `rofi` cannot).

### Copyright License?

MIT

### Expected interest

Many.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by Technetium1** [comment]
I already added this a long time ago in #1341, but seems we have issues with check since https://github.com/chaotic-aur/packages/issues/2358#issuecomment-1513435465

**Comment by D3vil0p3r** [comment]
> I already added this a long time ago in #1341, but seems we have issues with check since [#2358 (comment)](https://github.com/chaotic-aur/packages/issues/2358#issuecomment-1513435465)

The check should be fixed yesterday. My doubt is: why calling it with -git if the AUR package does not have -git in its name?

**Comment by xiota** [comment]
> why calling it with -git if the AUR package does not have -git in its name?

See commit 96297de7e2c90b2340a254e6794411e53e5fb44e.

When is the last time you synced the repositories?

```
$ sudo pacman -Sy
...

$ pacman -Ss rofi-lbonn
chaotic-aur/rofi-lbonn-wayland-git 1.7.5.wayland1.r48.gd06095b5-1
    A window switcher, application launcher and dmenu replacement (fork with Wayland support)
```

**Comment by D3vil0p3r** [comment]
> > why calling it with -git if the AUR package does not have -git in its name?
> 
> Sorry... was confused...
> 
> `-git` probably wasn't working when initially added. ([804e359](https://github.com/chaotic-aur/packages/commit/804e35999a2523cabe97cfdcf15c8483d28a01a4)) Then switched to `-git` when it was working ([96297de](https://github.com/chaotic-aur/packages/commit/96297de7e2c90b2340a254e6794411e53e5fb44e)).

Oh ok. At this point this request will be closed?

**Comment by xiota** [comment]
Confused again... non-git was added intentionally, but wasn't working, so switched to -git.

I'll test non-git version and add it if it works.

@Technetium1 Keep both or drop -git again?

**Comment by dr460nf1r3** [comment]
I think it makes sense to drop it again unless someone specifically requests it 🤔

**Comment by xiota** [comment]
Should [rofi-lbonn-wayland] temporarily include a "Replaces" directive?

**Comment by D3vil0p3r** [comment]
Thank you guys
