### ISSUE TITLE
[Request] rofi-greenclip

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2570]
### Requested Package:

[rofi-greenclip](https://aur.archlinux.org/packages/rofi-greenclip)

### Purpose and Use?

Simple [clipboard manager](https://wiki.archlinux.org/title/Clipboard_manager) designed to be integrated with [rofi](https://wiki.archlinux.org/title/Rofi)

### Benefits?

Make the management of clipboard easier on window manager environments.

### Copyright License?

GPL

### Expected interest

Many.

### Prior availability?

No

### Is this request unique?

Yes

### Is the package banned?

No

**Comment by xiota** [comment]
There is report of segfault on on aurweb.  Upon examination, looks like package is a disguised -bin package.  The github check-in uses a docker container.  Will look into whether package can be converted to build from source.  Otherwise, may drop.  Metrics 69.
