### ISSUE TITLE
[Remove] warpgui-bin

### ISSUE THREAD

**Issue by Pakrohk** [chaotic-aur/packages#2572]
### Package:

[AUR](https://aur.archlinux.org/packages/warpgui-bin)

### Purpose:

GUI for Cloudflare ™ WARP

### Benefits:

This package is the only GUI client for Warp on the AUR.

### Building:

I just installed the package with the help of TRIZEN, I didn't do anything else.

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

Yes

### Unique request?

Yes

### Banned package?

Yes

**Comment by xiota** [comment]
Dropped because depends on EOL GTK2.  Metrics 58.
