### ISSUE TITLE
[Bug] invalid PGP signature for pamac-tray-icon-plasma (Pedro Henrique Lara Campos <root@pedrohlc.com>)

### ISSUE THREAD

**Issue by Sad-Soul-Eater** [chaotic-aur/packages#2574]
### Packages:

[pamac-tray-icon-plasma](https://aur.archlinux.org/packages/pamac-tray-icon-plasma)

### Latest chaotic version

0.1.3-1.3

### What happens?

```
error: pamac-tray-icon-plasma: signature from "Pedro Henrique Lara Campos <root@pedrohlc.com>" is invalid
:: File /var/cache/pacman/pkg/pamac-tray-icon-plasma-0.1.3-1.3-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
```

### What is expected to happen?

Valid PGP signature

### More information

I tried to reinstall the `chaotic-keyring` package - it doesn`t help

**Comment by xiota** [comment]
Bumped and rebuilt.  Feel free to leave a comment if there are any other issues.
