### ISSUE TITLE
[Remove] chatbox-bin

### ISSUE THREAD

**Issue by raul-lezameta** [chaotic-aur/packages#2575]
### Package:

https://aur.archlinux.org/packages/chatbox-bin

### Purpose:

a cross-platform desktop client for OpenAI API, also a prompt debugging and management tool.

### Copyright:

GPL3

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
[Flagged out of date](https://aur.archlinux.org/pkgbase/chatbox-bin/flag-comment) now that there is actually a valid release for the maintainer to update to.

**Comment by xiota** [comment]
@Technetium1 Depends on `electron22`.  Drop?  Keep?

**Comment by Technetium1** [comment]
@xiota flagged for half a month and no update, also upstream just did a major refactor and decided not to bump Electron. It's time for it to go. Can be reconsidered in the future if it's running a reasonably current version.
https://github.com/Bin-Huang/chatbox/blob/f38b2c006c2a434e47fa78ad8de54a749be6fb1d/package.json#L74
