### ISSUE TITLE
[Request] etlegacy enemy-territory-data

### ISSUE THREAD

**Issue by REmerald** [chaotic-aur/packages#2577]
### Package:

[enemy-territory](https://aur.archlinux.org/pkgbase/enemy-territory)
[etlegacy](https://aur.archlinux.org/pkgbase/etlegacy)

### Purpose:

Free foss fps shooter, see [Wolfenstein: Enemy Territory](https://www.splashdamage.com/games/wolfenstein-enemy-territory) and [ET: Legacy](https://www.etlegacy.com/about) - its fork.

### Benefits:

Has a good amount of players.

### Building:

makepkg

### Copyright:

GPL3

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

enemy-territory and enemy-territory-data (etlegacy depends on it) can't be built by aur helpers, e.g. paru, (but works with makepkg) so it'll be a good idea to include them in the repo.

**Comment by xiota** [comment]
Why can't they be built by aur helpers?

**Comment by Technetium1** [comment]
Why does this person recommend ETLegacy? https://aur.archlinux.org/pkgbase/enemy-territory#comment-918611

**Comment by REmerald** [comment]
@xiota , idk seems like paru [rejects `depends_i686`] for some weird reason:
```
error: failed to parse srcinfo for 'enemy-territory-2.60b-14 (enemy-territory-data)': undeclared architecture 'i686' in key 'depends_i686': Line 26: depends_i686 = enemy-territory-data
```
makepkg is ok with it though.

**Comment by REmerald** [comment]
@Technetium1 , well, I haven't played it yet, but both versions/forks are launching fine.

Honestly, I included `enemy-territory`, because it also made it when I was making `enemy-territory-data`, so why not, especially if [it seems like some ppl still may use it](https://aur.archlinux.org/pkgbase/enemy-territory#comment-749478)?

**Comment by REmerald** [comment]
@Technetium1 , well, now I have thought about it a little bit more, I think it'll confuse ppl into downloading worse version of the game

**Comment by Technetium1** [comment]
@REmerald If data is required and part of pkgbase we must build it anyway 🙃

**Comment by xiota** [comment]
@REmerald Could you explain the relationship among `etlegacy`, `etlegacy-mod`, `etlegacy32`, `etlegacy32-mod`?

**Comment by REmerald** [comment]
@Technetium1 , well, now I think it wouldn't be a good idea, since it can cause new players (who don't know about etlegacy) to think that's the version they should install, which will cause them to rage and unistall the game because of the bugs/problems etlegacy fixed ([see the etlegacy page, at the middle](https://www.etlegacy.com/about)).

Also, including that package could practically be package hoarding / wasting mirrors space (if you want your packages to be somewhat useful; again few ppl that still use it, can build it themselves).  
But it's up to you whether to include `enemy-territory` or not.

**Comment by REmerald** [comment]
@xiota , umm, honestly, I haven't explored the game much yet, so I can't say for sure.  
`etlegacy-mod` is required by `etlegacy` anyway, so doesn't matter.

Judging by [the downloads page](https://www.etlegacy.com/download), [github faq wiki page](https://github.com/etlegacy/etlegacy/wiki/FAQ) and [github about wiki page](https://github.com/etlegacy/etlegacy/wiki/About), I think

`etlegacy32` and `etlegacy32-mod` are just a 32-bit version of the game; seems like ppl may still need to use it for some servers, but the packages are flagged outdated anyway.

It would be a good idea to also include `etlegacy-omnibot`, because it's bundled with the installer from the downloads, but the aur version is wrong, since the package just fetches the latest from [here](https://mirror.etlegacy.com/omnibot), which is regularly updated; that means we'll need to implement the versioning ourselves somehow, so I think it'll be easier for ppl just to rebuild it from aur every time, i guess.

**Comment by xiota** [comment]
I'd like an explanation of what the "mod" is referring to.  Does it mean "models"?  Looks like `etlegacy` depends on `etlegacy-mod`.  

Is `etlegacy-omnibot` a misnamed `-bin` package?

**Comment by REmerald** [comment]
[Arch Wiki prefers 32-bit version of etlegacy over 64-bit](https://wiki.archlinux.org/title/List_of_games#Shooters_(FPS,_third_person)).
![image](https://github.com/chaotic-aur/packages/assets/55359236/409c3cbe-c14b-4f9b-883e-046fdb5e61f7)

Honestly, I've lost interest in this game, so I'm closing this issue for now.  
If someone (or me in the future) wants this game in chaotic, they will need to find info and decide which version should be added (32, 64 or both).

**Comment by xiota** [comment]
@REmerald I think adding games to chaotic is good, but would like to sort out package relationships, especially when there may be compatibility issues among them.  Feel free to update your request and comment if you change your mind.
