### ISSUE TITLE
[Request] beeper

### ISSUE THREAD

**Issue by rgvxsthi** [chaotic-aur/packages#2578]
### Package:

[beeper](https://aur.archlinux.org/packages/beeper)

### Purpose:

all in one chat client for imessage, whatsapp, telegram, whatsapp and others - works across multiple OSes

### Benefits:

The developers are constantly updating this client everyday so would be great to have this automated to get the latest pre-built release via Chaotic.

### Building:

Regular installation of package with Yay aur manager, no special commands.

### Copyright:

https://www.beeper.com/terms

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by raul-lezameta** [comment]
:+1: on this request

**Comment by xiota** [comment]
Package is misnamed.  Should end in `-bin`.  Notified maintainer via comment on the AUR page.
