### ISSUE TITLE
[Bug] error: <pkg name>: signature from "Nico Jensch (Chaotic-AUR) <dr460nf1r3@garudalinux.org>" is unknown trust

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2580]
### Packages:

Several Chaotic packages

### Latest chaotic version

latest

### What happens?

When I upgrade the system, when it must upgrade a Chaotic package, I get:
```
error: <pkg name>: signature from "Nico Jensch (Chaotic-AUR) <dr460nf1r3@garudalinux.org>" is unknown trust
:: File /var/cache/pacman/pkg/armcord-git-r839.df0372b-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
```

### What is expected to happen?

Installing or upgrading the package with no key issue.

**Comment by LyonSyonII** [comment]
Same happens to me, have you found a solution?

**Comment by xiota** [comment]
This issue is currently being worked on.

**Comment by RAIACAD0564** [comment]
I am having the same issue. And in case any of this info is useful, my chaotic-keyring package is up to date and I already tried:
sudo pacman-key --populate chaotic
sudo pacman-key --refresh-keys
And then running sudo pacman -Syyu still couldn't update any of my packages from choatic-aur, same error.

**Comment by Technetium1** [comment]
**Probably** expect a fix tomorrow.

**Comment by dr460nf1r3** [comment]
This should be sorted now. Sorry everyone for the inconveniences.

**Comment by D3vil0p3r** [comment]
> This should be sorted now. Sorry everyone for the inconveniences.

It works. Thank you guys
