### ISSUE TITLE
[Request] go-mtpfs-git

### ISSUE THREAD

**Issue by jthvai** [chaotic-aur/packages#2581]
### Package:

[go-mtpfs-git](https://aur.archlinux.org/packages/go-mtpfs-git)

### Purpose:

From the [README](https://github.com/hanwen/go-mtpfs/blob/master/README.md),
> Go-mtpfs is a simple FUSE filesystem for mounting Android devices as a MTP device.
> 
> It will expose all storage areas of a device in the mount, and only reads file metadata as needed, making it mount quickly. It uses Android extensions to read/write partial data, so manipulating large files requires no extra space in /tmp.

### Benefits:

[`simple-mtpfs`](https://github.com/phatina/simple-mtpfs/) is a similar package that is currently available from Chaotic AUR.

However, Go-mtpfs "uses Android extensions to read/write partial data, so manipulating large files requires no extra space in /tmp", which is a benefit over `simple-mtpfs` (which does not do this, and therefore requires a caching directory).

### Copyright:

[BSD-3-Clause](https://github.com/hanwen/go-mtpfs/blob/master/LICENSE)

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by dr460nf1r3** [comment]
Added in https://github.com/chaotic-aur/packages/commit/3ebf08dd202374c392b135a7c1b7e9bd252a8aee (wrong #)
