### ISSUE TITLE
[Request] ueberzugpp

### ISSUE THREAD

**Issue by guiltiest-gear** [chaotic-aur/packages#2583]
### Package:

[ueberzugpp](https://aur.archlinux.org/packages/ueberzugpp)
AUR runtime dependency of [turbo-base64](https://aur.archlinux.org/packages/turbo-base64)

### Purpose:

Drop in replacement for ueberzug with several improvements and is also actively maintained.

### Benefits:

Directly quoting from the README:
> Advantages over w3mimgdisplay and ueberzug:
>* support for wayland (sway and hyprland only) and MacOS
>* no race conditions as a new window is created to display images
>* expose events will be processed, so images will be redrawn on switch workspaces
>* tmux support on X11, sway and hyprland
>* terminals without the WINDOWID environment variable are supported
>* chars are used as position - and size unit
>* No memory leak (usage of smart pointers)
>* A lot of image formats supported (through opencv and libvips).
>* GIF and animated WEBP support on X11, Sixel, Sway and hyprland
>* Fast image downscaling (through opencv and opencl)
>* Cache resized images for faster viewing

### Building:

turbo-base64 is an AUR dependency, so that must be built and installed first before ueberzugpp, otherwise requires no further intervention.

### Copyright:

[GPL3](https://github.com/jstkdng/ueberzugpp/blob/master/LICENSE)

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by federicotorrielli** [comment]
^^^ +1 for this!
