### ISSUE TITLE
[Outdated] lb32-mangohud-git

### ISSUE THREAD

**Issue by dnmodder** [chaotic-aur/packages#2588]
### Packages:

[lib32-mangohud-git](https://aur.archlinux.org/packages/lib32-mangohud-git)

### Latest chaotic version

v0.6.9.1.r78.g381c519

### Latest upstream version

v0.6.9.1.r79.g30748bd

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/lib32-mangohud-git.log

### More information

This package should be at the same version as the mangohud-git package, which is up to date.
![imagen](https://github.com/chaotic-aur/packages/assets/12377383/32d3e3ee-8b2b-4ffd-a47c-2bc3614206fe)

**Comment by xiota** [comment]
That commit was pushed earlier today.  Build scripts may not have detected the new commit so soon.

I triggered a rebuild.  Should be fixed now.

**Comment by dnmodder** [comment]
![imagen](https://github.com/chaotic-aur/packages/assets/12377383/b565a17f-eb02-4e3e-a0d4-7f02f1e5a49d)
It's outdated again.
