### ISSUE TITLE
[Bug] Rstudio: Visual editor doesn't work and there aren't Quarto options for the documents

### ISSUE THREAD

**Issue by brianmsm** [chaotic-aur/packages#2589]
### Packages:

[rstudio-desktop](https://aur.archlinux.org/packages/rstudio-desktop)

### Latest chaotic version

`2023.06.0.421-1`

### What happens?

The installation of the package goes smoothly. However there are 2 things that are not working correctly:
- There are no options to create documents or presentations in Quarto, and also not when creating projects.
- When you enter the visual editor it keeps loading infinitely and does not show anything.

### What is expected to happen?

When I install the same package from AUR, both work and/or display correctly. I leave screenshots of it working in the AUR package:
- Creating documents/presentations with Quarto and Projects:
![image](https://github.com/chaotic-aur/packages/assets/28207224/f2afe20a-c3b8-44e8-afc1-b10a149744ef)
![image](https://github.com/chaotic-aur/packages/assets/28207224/0566d278-2a3b-4073-932a-5798096cda2d)
- Visual Editor working correctly:
![image](https://github.com/chaotic-aur/packages/assets/28207224/785b1bab-8368-423c-b2e4-0d6222dd8362)

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/rstudio-desktop.log

**Comment by xiota** [comment]
Possibly... `quarto` needs to be in `makedepends` to build quarto support.  I will comment on AUR page to ask maintainer for clarification.

**Comment by xiota** [comment]
@brianmsm What package to support quarto do you have installed?

**Comment by brianmsm** [comment]
I have installed quarto-cli-bin from chaotic-aur repository

```bash
sudo pacman -Qi quarto-cli-bin
Name            : quarto-cli-bin
Version         : 1.3.361-1
Description     : An open-source scientific and technical publishing system built on Pandoc (binary from
official repo)
Architecture    : x86_64
URL             : http://quarto.org/
Licenses        : GPL
Groups          : None
Provides        : quarto
Depends On      : bash
Optional Deps   : None
Required By     : None
Optional For    : rstudio-desktop
Conflicts With  : None
Replaces        : None
Installed Size  : 298.50 MiB
Packager        : UFSCar HPC Builder <hpc.ufscar@chaotic.cx>
Build Date      : Sat 27 May 2023 12:24:36 AM -05
Install Date    : Sat 17 Jun 2023 08:07:31 PM -05
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by xiota** [comment]
Does `rstudio-desktop` (that you built locally, that works with quarto) still work when you uninstall `quarto-cli-bin`?  I'd like to know if building with quarto support turns it from an optional dependency to a required one.

From discussion with the package maintainer, it seems there have been issues with quarto for a couple years.  How "important" is quarto?  "not needed at all" - "nice to have" - "must have" - "absolutely useless without it"?

The "loading infinitely" issue would probably need to be reported upstream.

**Comment by brianmsm** [comment]
I uninstalled quarto-cli-bin and opened rstudio. It took a while, but it did open. It works, however, the options associated with Quarto no longer appear.

![image](https://github.com/chaotic-aur/packages/assets/28207224/29a95275-19c5-4170-951b-5efa2bd6ae7d)
![image](https://github.com/chaotic-aur/packages/assets/28207224/7c97cabf-cf9a-4408-ad0c-016e84c1f823)

On the second question, it is somewhere between a "nice to have" and "must have". Quarto was born to be an alternative to Rmarkdown some years ago and has been expected to mature. Although Rmarkdown is not discontinued and can still be used without needing Quarto, the trend is that new projects may start using Quarto directly instead of Rmarkdown.

About "loading infinitely", the issue is that this problem does not happen when I install the package from AUR, but it happens when I install it from chaotic-aur.

**Comment by xiota** [comment]
I don't use these packages.  Can you write some instructions to replicate the issues so I can better understand what you're describing?  Provide sample documents if needed.

**Comment by brianmsm** [comment]
Yes, of course. The error occurs either when creating or opening a Rmarkdown or Quarto file. Both formats have a mode within rstudio that allows you to have a visual aspect of what is displayed in markdown. 

Here is how it works with rstudio from AUR:
![rstudio-aur](https://github.com/chaotic-aur/packages/assets/28207224/ca19d88f-caa4-4d07-9714-1cc33f234365)

Here the operation with rstudio from Chaotic-AUR which stays loading infinitely and does not allow any further interaction:
![rstudio-chaotic-bug](https://github.com/chaotic-aur/packages/assets/28207224/a39989d2-981e-4715-af80-f0334b320a2a)

**Comment by xiota** [comment]
@brianmsm  Sorry, I put this issue off for so long.  I have rebuilt `rstudio-desktop` with `quarto-cli-bin` in makedepends.  Would you test if it works both with and without quarto installed? Thanks.

**Comment by brianmsm** [comment]
Hi @xiota.  Don't worry. Thank you very much for your time! 

I wasn't sure how to do the manual sync, but I did the download from here:  https://builds.garudalinux.org/repos/chaotic-aur/x86_64/rstudio-desktop-2023.06.2.561-1-x86_64.pkg.tar.zst

1. Installing the package with quarto already installed: It works perfectly
- I can see the quarto file creation menu
- The Visual Editor function works well 
- The visualization section works well too.

![image](https://github.com/chaotic-aur/packages/assets/28207224/9510fb00-b5b1-4001-b791-4e55225f312d)

```fish
╭─brian@brian in ~/Downloads via 📐 v4.3.1 as 🧙 took 4s
╰─λ pacman -Qi rstudio-desktop
Name            : rstudio-desktop
Version         : 2023.06.2.561-1
Description     : A powerful and productive integrated development environment (IDE) for R programming
language
Architecture    : x86_64
URL             : https://www.rstudio.com/products/rstudio/
Licenses        : AGPL3
Groups          : None
Provides        : rstudio-desktop
Depends On      : r>=3.3.0  boost-libs  qt5-sensors  qt5-svg  qt5-webengine  qt5-xmlpatterns  postgresql-libs
sqlite3  soci  clang  hunspell-en_US  mathjax2  pandoc  yaml-cpp
Optional Deps   : git: for git support [installed]
subversion: for subversion support [installed]
openssh-askpass: for a git ssh access
quarto: for Quarto projects support [installed]
Required By     : None
Optional For    : None
Conflicts With  : rstudio-desktop  rstudio-desktop-bin  rstudio-desktop-preview  rstudio-desktop-git
Replaces        : None
Installed Size  : 88.57 MiB
Packager        : Garuda Builder <team@garudalinux.org>
Build Date      : Sun 27 Aug 2023 06:50:43 PM -05
Install Date    : Mon 28 Aug 2023 01:52:14 AM -05
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

2. Installing the package without having quarto installed.
- As expected, since quarto is not installed, the quarto file creation menu does not work.
- The visual editor function works fine (it does not load anymore), both in `.rmd` and `.qmd` files.
- The visualization section when rendering with quarto does not work properly. However, I understand that this would be expected behavior since quarto is not installed.

![image](https://github.com/chaotic-aur/packages/assets/28207224/37476bfa-aa4f-402b-ad65-84572bcb10e6)

```
╭─brian@brian in ~/Downloads via 📐 v4.3.1 as 🧙 took 3s
╰─λ pacman -Qi rstudio-desktop
Name            : rstudio-desktop
Version         : 2023.06.2.561-1
Description     : A powerful and productive integrated development environment (IDE) for R programming
language
Architecture    : x86_64
URL             : https://www.rstudio.com/products/rstudio/
Licenses        : AGPL3
Groups          : None
Provides        : rstudio-desktop
Depends On      : r>=3.3.0  boost-libs  qt5-sensors  qt5-svg  qt5-webengine  qt5-xmlpatterns  postgresql-libs
sqlite3  soci  clang  hunspell-en_US  mathjax2  pandoc  yaml-cpp
Optional Deps   : git: for git support [installed]
subversion: for subversion support [installed]
openssh-askpass: for a git ssh access
quarto: for Quarto projects support
Required By     : None
Optional For    : None
Conflicts With  : rstudio-desktop  rstudio-desktop-bin  rstudio-desktop-preview  rstudio-desktop-git
Replaces        : None
Installed Size  : 88.57 MiB
Packager        : Garuda Builder <team@garudalinux.org>
Build Date      : Sun 27 Aug 2023 06:50:43 PM -05
Install Date    : Mon 28 Aug 2023 02:00:23 AM -05
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

So I think the building of the package is working perfectly!
