### ISSUE TITLE
[Request] plasma5support

### ISSUE THREAD

**Issue by pendo324** [chaotic-aur/packages#2590]
### Package:

[plasma5support](https://aur.archlinux.org/packages/plasma5support-git)

Dependencies:

- [kconfig-git](https://aur.archlinux.org/packages/kconfig-git)
- [kcoreaddons-git](https://aur.archlinux.org/packages/kcoreaddons-git)
- [ki18n-git](https://aur.archlinux.org/packages/ki18n-git)
- [kio-git](https://aur.archlinux.org/packages/kio-git)
- [kservice-git](https://aur.archlinux.org/packages/kservice-git)
- [kxmlgui-git](https://aur.archlinux.org/packages/kxmlgui-git)
- [plasma-framework-git](https://aur.archlinux.org/packages/plasma-framework-git)
- [extra-cmake-modules-git ](https://aur.archlinux.org/packages/extra-cmake-modules-git)(make)

### Purpose:

It's a new dependency of plasma-workspace that allows plasma5 apps to run on plasma6. Chaotic AUR already supports plasma-workspace via [the kde-git-meta package](https://archlinux.pkgs.org/rolling/chaotic-aur-x86_64/kde-git-meta-6-1.1-any.pkg.tar.zst.html).

### Benefits:

- Allows users to run apps made with plasma5 (...which is most non-core KDE apps right now, including most sddm themes)

### Copyright:

LGPL

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Is this @IslandC0der's domain?

**Comment by pendo324** [comment]
> Is this @IslandC0der's domain?

I think so. The main reason I noticed this (besides my plasma5 apps / SDDM theme not working) is because of [this comment](https://aur.archlinux.org/packages/plasma-workspace-git#comment-919949) on one of @IslandC0der's packages.

Seems like a relatively recent change (the plasma5support-git AUR package was only created on 2023-06-18)

**Comment by IslandC0der** [comment]
Yup! Thanks for the reminder, I've just added it :)
