### ISSUE TITLE
[Request] schedtoold

### ISSUE THREAD

**Issue by dankcuddlybear** [chaotic-aur/packages#2591]
### Package:

https://aur.archlinux.org/packages/schedtoold

No AUR dependencies

### Purpose:

Simple daemon to renice/nice and change priorities of processes while running them. Used with schedtool to set policies for real-time applications like gaming, music and video production.

### Benefits:

Schedtoold can be used to set real-time priority for games and other real-time applications to reduce latency and stuttering

### Building:

git clone https://aur.archlinux.org/schedtoold.git
cd schedtoold
makepkg -cirs

### Copyright:

GPL

### Expected Interest:

Most

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
@dankcuddlybear  There are comments on AUR indicating that this package may be broken.  Have you installed and tested it to ensure it's working the way it's supposed to?

**Comment by dankcuddlybear** [comment]
I have tested it and can confirm it is 100% working
