### ISSUE TITLE
[Rebuild] samba-support

### ISSUE THREAD

**Issue by ghost** [chaotic-aur/packages#2592]
### Packages:

[https://aur.archlinux.org/packages?O=0&K=samba-support](url)

### Latest chaotic version

1-7

### Reason for rebuild

Has the samba-support package been dropped? It's no more in the repository.

**Comment by xiota** [comment]
Custom PKGBUILD.  Looks like metapackage that installs: `avahi` `nss-mdns` `samba` `python-pysmbc`

https://github.com/chaotic-aur/packages/blob/93b5489994e480a184d93c01fee708a7470fe7c4/garuda-repo/hourly.txt#L30

**Comment by xiota** [comment]
Are packages in `garuda-repo` and `garuda-cluster` normally supposed to *not* show up in chaotic-aur?

**Comment by dr460nf1r3** [comment]
Only `garuda-repo` is a separate repo, `garuda-cluster` builds regular Chaotic-AUR packages.

**Comment by dr460nf1r3** [comment]
So, to answer this fully: this package originates from Garuda and has been moved to its own repository a while ago. Therefore its no longer present in Chaotic-AUR.
