### ISSUE TITLE
[Remove] deltachat-desktop-git

### ISSUE THREAD

**Issue by cold-nagai** [chaotic-aur/packages#2596]
### Package:

[deltachat-desktop-git](https://aur.archlinux.org/packages/deltachat-desktop-git)

### Purpose:

Delta.Chat is an E2E encrypted messaging over email.

### Benefits:

Electron 19, which is used by deltachat-desktop, has reached EOL and is no longer supported. deltachat-dekstop, claiming to be 1.38, still relies on electron19 when the upstream uses electron22 since 1.36.0. deltachat-git-bin would be much appreciated. 

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

No

### Unique request?

No

### Banned package?

No

**Comment by xiota** [comment]
Fails to build.  I don't know cause or solution.  Eventual drop seems likely.  `extra/deltachat-desktop` is available.  Metrics 4.
```
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "catalog:": catalog:
```

**Comment by Technetium1** [comment]
This is an upstream issue which is likely transient, it's caused by their current transition to a monorepo + pnpm: https://github.com/deltachat/deltachat-desktop/commit/a5c02433976909fe01a64f3049c96d0d101ae9d8 / https://github.com/deltachat/deltachat-desktop/blob/c771c5d7f875be9d2b5975ee4663ce883413fd06/package.json#L61

**Comment by dr460nf1r3** [comment]
Yeah, transitions like this can be awful. We transitioned to pnpm at work not too long ago, and also had certain issues arise from that. Might be worth reporting it upstream in this case, maybe.

**Comment by Technetium1** [comment]
The PKGBUILD still specifies npm in makedepends, which can't resolve catalogs, if it still fails after update, then it's definitely something to consider reporting upstream. Their CI is building so it should be okay.

**Comment by xiota** [comment]
Even if it's eventually fixed, is this worth keeping?  Metrics are low and `extra/deltachat-desktop` is available.

**Comment by Technetium1** [comment]
Just checked metrics, yes it's actually fine to drop this.
