### ISSUE TITLE
[Request] ArchiSteamFarm asf

### ISSUE THREAD

**Issue by bayazidbh** [chaotic-aur/packages#2599]
### Package:

[asf](https://aur.archlinux.org/packages/asf)
~~[archisteamfarm-bin](https://aur.archlinux.org/packages/archisteamfarm-bin)~~

### Purpose:

Used for idling Steam games, most useful for idling to get cards

### Benefits:

Very useful for idling to get cards, which users can then sell to get a sort of "rebate" on their purchases. Have used it for years, didn't get banned, so it is safe

 Getting it on chaotic-aur would make it easier to get as it uses .NET and can be a long process to build sometimes.

### Copyright:

[Apache License 2.0](https://github.com/JustArchiNET/ArchiSteamFarm/blob/main/LICENSE.txt)

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

[Upstream](https://github.com/JustArchiNET/ArchiSteamFarm)

**Comment by Technetium1** [comment]
I'd like to add the non-`bin` version, howver dotnet has been flagged for a while now: [dotnet-runtime](https://archlinux.org/packages/extra/x86_64/dotnet-runtime/) & [dotnet-sdk](https://archlinux.org/packages/extra/x86_64/dotnet-sdk/)
