### ISSUE TITLE
[Request] pyinstaller

### ISSUE THREAD

**Issue by ProfP30** [chaotic-aur/packages#2605]
### Package:

[pyinstaller](https://aur.archlinux.org/packages/pyinstaller)
[Source code](https://github.com/pyinstaller/pyinstaller)

### Purpose:

Compiles python source code to binary executable.
Can bundle a Python application and all its dependencies into a single package. The user can run the packaged app without installing a Python interpreter or any modules. 

### Benefits:

Compiling pyinstaller from source is very slow.
Benefit of having pyinstaller in a bin package would be awesome and save a vast amount of time (and resources).

### Copyright:

GPL2, Apache, custom:PyInstaller 

### Expected Interest:

Some

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Why do python apps need to be packaged into a single file?

How does this compare with `extra/nuitka`?

**Comment by xiota** [comment]
What are your use cases?

Why do Python packages need to be portable when you can install with `pacman` or `pip`?

Why not use `extra/nuitka`?

**Comment by xiota** [comment]
Closing because no response from OP.  Also, already added as dependency in #2638.

**Comment by Technetium1** [comment]
@xiota I've used this multiple times in place of `nuitka` & `python-cx-freeze`. They all work a bit differently, but accomplish almost the same goal. You can see more about the differences here: https://pyoxidizer.readthedocs.io/en/stable/pyoxidizer_comparisons.html
