### ISSUE TITLE
[Request] gst-plugin-gtk4

### ISSUE THREAD

**Issue by realmazharhussain** [chaotic-aur/packages#2606]
### Package:

[gst-plugin-gtk4](https://aur.archlinux.org/pkgbase/gst-plugin-gtk4)

### Purpose:

Adds GTK4 support for GStreamer

### Benefits:

This is useful for those GTK4 apps which play/manipulate media content.

### Building:

Nothing special is required. Simple `makepkg -s` will do.

### Copyright:

MPL2

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Can you list some apps that require this so I can test?

**Comment by realmazharhussain** [comment]
No, I don't think any app has been released that uses this.

But I have seen some people trying to build this plugin so that they could develop an app with this. I'm one of those people.

I have <https://gitlab.com/envision-play/envision-media-player> in the works. It depends on this plugin, this plugin is written in rust and building anything rust is a big pain in the ass because it wastes so much time, network resources and disk space everytime I need to build it.
