### ISSUE TITLE
[Request] zapret-git

### ISSUE THREAD

**Issue by REmerald** [chaotic-aur/packages#2607]
### Package:

[zapret-git](https://aur.archlinux.org/pkgbase/zapret-git)
(All packages from the pkgbase)

### Purpose:

Bypass DPI (Deep Packet Inspection) censorship (website blocks by ISP).

### Benefits:

Has a lots of options and bypass algorithms, which other such utilities lack.

### Building:

paru

### Copyright:

MIT

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Works, bypasses most blocks in my country, tested on my machine.
If someone wants to try it, make sure to configure it first.
See [readme.eng.md](https://github.com/bol-van/zapret/blob/master/docs/readme.eng.md), then [manual_setup.txt](https://github.com/bol-van/zapret/blob/master/docs/manual_setup.txt).

**Comment by xiota** [comment]
Asked maintainer via comment to improve package descriptions, but no response.

**Comment by REmerald** [comment]
@ahmubashshir

**Comment by ahmubashshir** [comment]
Yeah... XD
	- Mubashshir

**Comment by xiota** [comment]
@ahmubashshir Thank you for updating.
