### ISSUE TITLE
[Request] clipboard-sync

### ISSUE THREAD

**Issue by zany130** [chaotic-aur/packages#2608]
### Package:

[clipboard-sync](https://aur.archlinux.org/packages/clipboard-sync)

### Purpose:

runs a systemd service that sync your x11 and Wayland clipboards

### Benefits:

useful for when mixing xwayland and wayland software in your workflow. EG: remote desktop software like rustdesk

### Building:

~~doesn't seem to build in a clean chroot.~~
seems like it built fine and those errors were when installing the package which is fine?

git cloned and ran `extra-x86_64-build` in its directory and got 

```
Checking PKGBUILD
Checking clipboard-sync-0.2.0-1-x86_64.pkg.tar.zst
clipboard-sync W: Unused shared library '/usr/lib/libxcb-render.so.0' by file ('usr/bin/clipboard-sync')
clipboard-sync W: Unused shared library '/usr/lib/libxcb-shape.so.0' by file ('usr/bin/clipboard-sync')
clipboard-sync W: Unused shared library '/usr/lib/libxcb-xfixes.so.0' by file ('usr/bin/clipboard-sync')
clipboard-sync E: Dependency gcc-libs detected and not included (libraries ['usr/lib/libgcc_s.so.1'] needed in files ['usr/bin/clipboard-sync'])
clipboard-sync W: Dependency glibc detected and implicitly satisfied (libraries ['usr/lib/libc.so.6', 'usr/lib/libm.so.6', 'usr/lib/ld-linux-x86-64.so.2'] needed in files ['usr/bin/clipboard-sync'])
Checking clipboard-sync-debug-0.2.0-1-x86_64.pkg.tar.zst
==> Running checkpkg
error: target not found: clipboard-sync
==> WARNING: Skipped checkpkg due to missing repo packages
```

### Copyright:

GPL3

### Expected Interest:

Most

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
> errors were when installing the package which is fine?

Yes.  I think they're normal.

> sync your x11 and Wayland clipboards

I don't use Wayland, so don't evaluate/add packages related to it, but I'm surprised Wayland desktop environments don't already provide this functionality.

**Comment by zany130** [comment]
I did too but when using rust desk to remote to a Windows PC I couldn't copy and paste between the two when using Wayland apps.

Installing this fixed it
