### ISSUE TITLE
[Request] local

### ISSUE THREAD

**Issue by mauriciodelima21** [chaotic-aur/packages#2612]
### Package:

[local-by-flywheel-bin](https://aur.archlinux.org/packages/local-by-flywheel-bin)

### Purpose:

A very useful program for WordPress developers. I believe it will be of great value to everyone.

### Copyright:

custom:proprietary 

### Expected Interest:

Most

### Already available?

Yes

### Unique request?

No

### Banned package?

Yes

**Comment by xiota** [comment]
Please edit the request to update it:

* Title: Use the correct package name.
* Package: Fix the link.  The current link returns a 404 error.  Using the correct AUR link helps maintainers to properly evaluate the package.
* Purpose: Provide a better description of the package.  What does this package do?  How is it "useful" for WordPress developers?
* License: Provide a link to the proprietary license.

**Comment by mauriciodelima21** [comment]
Local provides useful features for WordPress developers, such as the ability to create test sites, clone existing sites, perform code debugging, modify themes and plugins, and test updates before applying them in a production environment. It also facilitates collaboration among developers, allowing you to easily share your projects with others.

https://localwp.com/

**Comment by Technetium1** [comment]
Due to the license and size, this request isn't a great fit for Chaotic, if there is increased demand in the future it can be reconsidered.
