### ISSUE TITLE
[Request] aurutils and aurum

### ISSUE THREAD

**Issue by R-a-l-f** [chaotic-aur/packages#2613]
### Package:

[aurutils](https://aur.archlinux.org/packages/aurutils)
[aurum](https://aur.archlinux.org/packages/aurum)

### Purpose:

Helper tools for the AUR with 248 votes and a high-level wrapper for aurutils with extra features.

### Benefits:

To be honest, I haven't gotten around to using it yet. Consider to take a look at the [features: local repository, local patch application, package signing, clean chroot](https://wiki.archlinux.org/title/AUR_helpers#Search_and_build)

### Building:

I build a lot of packages with either makepkg or makechrootpkg, but those packages are build with the obsolete yaourt. I'm not kidding. However, it's on my todo list to find a new way to handle the AUR, hence this request.

### Copyright:

custom:ISC 

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Please test and provide more info about viability of packages for your use case.

`aurum` looks unsuitable for general use.  The readme and man page are blank.

**Comment by Technetium1** [comment]
I use use aurutils via https://github.com/alexheretic/aurto, it's very nice. Never seen or heard of `aurum` though.
