### ISSUE TITLE
[Request] ani-cli

### ISSUE THREAD

**Issue by guiltiest-gear** [chaotic-aur/packages#2614]
### Package:

[ani-cli](https://aur.archlinux.org/packages/ani-cli)

### Purpose:

Provides a convenient command line interface to browse and watch anime

### Benefits:

Many users would prefer to use the efficiency and speed of the command line to watch anime rather than having to open up a full browser to accomplish the same task.  This version however pulls from github releases rather than the master branch.

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

I did already make an issue for a git version of this package, but I might as well cover all my bases my creating a request for the regular version as well

**Comment by xiota** [comment]
In the future, please combine requests for git/non-git versions into a single request.

Regardless, I'm not sure either package should be added because of potential issues related to copyright licensing.

**Comment by guiltiest-gear** [comment]
Fair point on both topics, closing both the issues related to ani-cli.

**Comment by Technetium1** [comment]
@xiota It's GPLv3 source: https://github.com/pystardust/ani-cli/blob/master/LICENSE. The content inside is not hosted on the application, and is thereby not of direct consequence, so this can still be added in the future if it's requested.

@guiltiest-gear the stable releases should be fine almost always, no there need to request `-git` unless you see purpose for others to also use both.

**Comment by guiltiest-gear** [comment]
@Technetium1 Personally I used to use the `-git` version on my machine due to the higher popularity in the AUR, but the normal version is effectively the same. If it's alright with you, I'd like to reopen this request.

**Comment by xiota** [comment]
> The content inside is not hosted on the application, and is thereby not of direct consequence

@Technetium1  I'm not sure and was interested in discussion about the potential issues.  The sole purpose of the program is to provide access to a site that provides access to unlicensed content.  I'm pretty sure sellers of streaming boxes have been shut down for providing access to apps that provided access to unlicensed content in similarly roundabout manners.  Chaotic is not selling streaming boxes (or anything that I'm aware of), but this seems potentially hazardous.

> I'd like to reopen this request.

@guiltiest-gear Just the normal package or both?

**Comment by guiltiest-gear** [comment]
> Just the normal package or both?

@xiota The normal package a.k.a. the non-git version. As far as I'm concerned, there's no real reason to have both included unless someone has objections or reasons to include both.

**Comment by Technetium1** [comment]
@xiota if it helps your internal analogy; Kodi still exists while the streaming box content in question doesn't (at least not as much). The apps that got in trouble were those that were providing streams from their own library on their own service and profiting from it. Ani-cli is simply indexing external content and linking off platform, like Google.

**Comment by xiota** [comment]
Large corporations have financial resources to get away with a lot of things normal people can't.  Not sure the "just linking" excuse works when using a single-purpose tool.  Becomes "conspiracy to facilitate copyright infringement".  [Surfthechannel founder gets four years prison time for piracy](https://www.cnet.com/tech/services-and-software/surfthechannel-founder-gets-four-years-prison-time-for-piracy/).

**Comment by xiota** [comment]
I've commented on the AUR page to ask maintainer to add a disclaimer on install/update, similar to:

> This program is to be used at the user's own risk, based on their government and laws.

See [disclaimer.md](https://github.com/pystardust/ani-cli/blob/master/disclaimer.md).

**Comment by xiota** [comment]
Some problems with this package:

* Not working because of `curl` update.
    * Upstream fixed couple months ago, but no new release.
* git package has issues preventing switchover.

If package isn't fixed or updated "soon", it will become a drop candidate.

**Comment by port19x** [comment]
Greetings from upstream.
@xiota regarding legalese: this is more in line with sth like yt-dlp.
A new point release is planned shortly, fixing the curl issue that has only affected windows users to our knowledge at this point.
I recommend packaging both `ani-cli` and `ani-cli-git`, as you see our cadence for release candidates is much slower, making users potentially miss out on non-critical fixes and feature enhancements

**Comment by port19x** [comment]
[v4.8](https://github.com/pystardust/ani-cli/releases/tag/v4.8) is out now, thank you for raising an issue
