### ISSUE TITLE
[Bug] swaylock-effects doesnt work when installed from chaotic aur

### ISSUE THREAD

**Issue by Felix-Kyun** [chaotic-aur/packages#2615]
### Packages:

[swaylock-effects](https://aur.archlinux.org/packages/swaylock-effects)

### Latest chaotic version

`1.6.10-1.1`

### What happens?

the following happens when i try to use swaylock
```
2023-06-28 16:51:19 - [main.c:219] Failed to daemonize
```

### What is expected to happen?

it should lock the screen as expected

### More information

Iit also doesnt work without daemon option, the one from aur works without any issues

**Comment by yum13241** [comment]
The package probably needs a rebuild on Chaotic's end.

**Comment by dr460nf1r3** [comment]
Did that, please check whether it's better now :)

**Comment by Felix-Kyun** [comment]
Thank you, Closing the issue
