### ISSUE TITLE
All ICU dependant packages

### ISSUE THREAD

**Issue by dr460nf1r3** [chaotic-aur/packages#2616]
### Packages:

https://archlinux.org/packages/core/x86_64/icu/
Got updated and needs all dependant packages to be bumped.

### More information

`firedragon`, `librewolf` and `ungoogled-chromium` were bumped by me already.

**Comment by dr460nf1r3** [comment]
@xiota and @Technetium1 if you have some spare time on your hands, that would be amazing. Simply bumping them should be sufficient.

**Comment by xiota** [comment]
Pending issues:
- [ ] freerdp-git # [aur](https://aur.archlinux.org/packages/freerdp-git) # upstream
- [ ] gimp-git # [aur](https://aur.archlinux.org/packages/gimp-git) # upstream
- [ ] quassel-core-git # pkgbase quassel, needs manual rebuild

Bumped, pending scheduled rebuild:
- chromium-wayland-vaapi
- dee
- fsearch
- fsearch-git
- libpdfium-nojs
- miktex
- mysql
- php73-intl
- podman-desktop
- tor-browser
- ungoogled-chromium

Not bumped:

- basilisk-bin
- megasync-bin
- openttd-git - 2023-06-28
- powershell-bin

**Comment by xiota** [comment]
Will have to rebump later because just noticed that new version of `core/icu` is still in testing repositories.

**Comment by dr460nf1r3** [comment]
Excellent, thanks! 🙌

**Comment by xiota** [comment]
Looks like new `core/icu` may have source-level incompatibilities, so broken package will need upstream fixes.

**Comment by dr460nf1r3** [comment]
Is there actually anything left here? Otherwise, we could close this I guess.

**Comment by xiota** [comment]
Bumped some packages that weren't rebuilt after initial bump.  Manually rebuilt `quassel` and `freerdp-git`.  Probably okay to close.  Can fix other issues as they're found.
