### ISSUE TITLE
[Request]ranger-git

### ISSUE THREAD

**Issue by izmyname** [chaotic-aur/packages#2619]
### Package:

[ranger-git](https://aur.archlinux.org/packages/ranger-git)

### Purpose:

Command-line file manager with vim-like keybindings, image, media and archieve preview support via additional plugins.

### Benefits:

It's a simple yet powerful file manager for minimalists.  

### Building:

makepkg, yay, paru

### Copyright:

GPL

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Non-git version from Arch repos has a bug that causes ranger to crash upon trashing files if trash-cli package installed and used. The git version has the bug fixed but only if  trash-cli-git used (I'm about to request that as well).

**Comment by xiota** [comment]
Can you provide instructions on how to replicate the bug?  Have you reported the issue at [bugs.archlinux.org](https://bugs.archlinux.org/)?

**Comment by izmyname** [comment]
To replicate the bug:

1. Have ranger (from Arch repo) and trash-cli or trash-cli-git installed.

2. Attempt to trash a file (especially, a big one) or non-empty directory by using ranger trash command. 

Sometimes, it works with small files.

No, I haven't reported it because the bug doesn't occur if ranger-git and trash-cli-git used.

**Comment by xiota** [comment]
I just installed `ranger` and `trash-cli`.  Deleted a file with `dD`, which entered the command `:delete`.  `ranger` did not crash, but it also did not use `trash-cli`.

**Comment by xiota** [comment]
My results:
* `ranger` + `trash-cli` ⇒ crash
* `ranger-git` + `trash-cli` ⇒ crash
* `ranger-git` + `trash-cli-git` ⇒ crash
