### ISSUE TITLE
digikam git needs git + https:// instead of git://

### ISSUE THREAD

**Issue by SolarAquarion** [chaotic-aur/packages#262]

**Comment by fabianski7** [comment]
the git repository of kde has changed to invent.kde.org. The digikam-git package still uses the old url.
The package maintainer has not responded to any requests for this change.

[chaotic's log shows this error](https://lonewolf.pedrohlc.com/chaotic-aur/makepkglogs/digikam-git.log). a manual change in pkgbuild will be required. I'm not sure if this is part of the policy of this repository
