### ISSUE TITLE
[Request] wp-desktop

### ISSUE THREAD

**Issue by mauriciodelima21** [chaotic-aur/packages#2620]
### Package:

[wp-desktop](https://aur.archlinux.org/wp-desktop)

### Purpose:

This package is a desktop version for accessing Wordpress.com. I believe many users, like myself, who use their hosting services would like to be able to enjoy direct access without having to compile through AUR as it is currently. In fact, this package was orphaned, and I took it over as the maintainer.

### Copyright:

GPL3

### Expected Interest:

Most

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Please update the request:
* Title: Use proper package name, not "packagename"
* Package: Use the AUR link, not the git link.
* Purpose: "App Wordpress Desktop" is not descriptive enough.  What exactly does this package do?
* Benefits: Why do you want this package?
* Already available? Yes – Where?

This is your second incomplete request, and you ignored requests to correct the previous one.  I understand not everyone who uses chaotic speaks English, but at least *try* to use some machine translation tool.

**Comment by mauriciodelima21** [comment]
This package is a desktop version for accessing Wordpress.com. I believe many users, like myself, who use their hosting services would like to be able to enjoy direct access without having to compile through AUR as it is currently. In fact, this package was orphaned, and I took it over as the maintainer.

**Comment by xiota** [comment]
Dropping because removed from AUR and upstream project uses Electron 26.  [`package.json`](https://github.com/Automattic/wp-calypso/blob/61ec712d83c853cc931ba925536445c79413fd39/desktop/package.json#L41)
