### ISSUE TITLE
[Rebuild] goldendict-git

### ISSUE THREAD

**Issue by GuangDai** [chaotic-aur/packages#2621]
### Packages:

[goldendict-git](https://aur.archlinux.org/packages/goldendict-git)

### Latest chaotic version

1:1.5.0.r4.g7d4c2079-1

### Reason for rebuild

Broken,

> goldendcit 
goldendict: error while loading shared libraries: libicuuc.so.72: cannot open shared object file: No such file or directory

**Comment by xiota** [comment]
Problem seems to be `qt5-webkit`, which isn't building.  AUR page has recent comments indicating the issue is being worked on upstream.

**Comment by xiota** [comment]
Consider using `goldendict-webengine-pr-git` while waiting for `qt5-webkit` to be fixed.

**Comment by GuangDai** [comment]
> Consider using `goldendict-webengine-pr-git` while waiting for `qt5-webkit` to be fixed.

OK, thanks for your help. I turn to goldendict-webengine-pr-git now

**Comment by xiota** [comment]
Looks like `goldendict-git` has been rebuilt.  Feel free to comment here if there are still issues.
