### ISSUE TITLE
[Rebuild] chromium-wayland-vaapi

### ISSUE THREAD

**Issue by ZZYSonny** [chaotic-aur/packages#2622]
### Packages:

https://aur.archlinux.org/packages/chromium-wayland-vaapi

### Latest chaotic version

114.0.5735.133-2

### Reason for rebuild

Version out of date (Latest 114.0.5735.198-2)
No longer works with latest arch, as the chaotic-prebuilt packages requires icu72

**Comment by dr460nf1r3** [comment]
I just noticed a fresh build in the build logs :)
