### ISSUE TITLE
[Request] trash-cli-git

### ISSUE THREAD

**Issue by izmyname** [chaotic-aur/packages#2623]
### Package:

[trash-cli-git](https://aur.archlinux.org/packages/trash-cli-git)

### Purpose:

Command-line utility to manage trashcan - put, restore, delete and empty.

### Benefits:

Minimalistic and easy-to-use utility to manage trashcan from a command line. 

### Building:

mkepkg, yay, paru

### Copyright:

GPL2

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Unlike non git version, this one doesn't crash if used within ranger-git.

**Comment by xiota** [comment]
If `ranger-git` works with `trash-cli`, would you still need `trash-cli-git`?  If so, can you describe new features / changes in `trash-cli-git`?
