### ISSUE TITLE
[Request] latencyflex-git

### ISSUE THREAD

**Issue by Element21** [chaotic-aur/packages#2624]
### Package:

[latencyflex-git](https://aur.archlinux.org/packages/latencyflex-git)

### Purpose:

Adding this package will enable latencyflex-wine-git to build properly as this is a dependency

### Benefits:

Read purpose

### Building:

pkgbuild seems to only use meson

### Copyright:

Apache License 2.0

### Expected Interest:

Many

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
This request is strange.  It says `latencyflex-git` is needed to build `latencyflex-wine-git`, but `latencyflex-wine-git` is built as a subpackage of `latencyflex-git`.  A description of the use case would be nice.  (Why, how, and when is this package useful?)

**Comment by xiota** [comment]
This package is currently failing to build because of missing file `vulkan/generated/vk_layer_dispatch_table.h`.  The file was previously provided by `vulkan-headers`, but no longer available because of upstream changes.

**Comment by xiota** [comment]
Dropping because upstream project is effectively abandoned.  Developer did not fix or respond to issue about the aforementioned problem.

Metrics 26.
