### ISSUE TITLE
[Rebuild] qimgv-git

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#2630]
### Packages:

[qimgv-git](http://aur.archlinux.org/packages/qimgv-git)

### Latest chaotic version

`v1.0.3.alpha.r94.ge2675f1-1`

### Reason for rebuild

`qimgv: error while loading shared libraries: libopencv_imgproc.so.407: cannot open shared object file: No such file or directory`

### Logs

[qimgv-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/qimgv-git.log)

**Comment by niobium93** [comment]
Needs to be rebuilt again.
```
qimgv: error while loading shared libraries: libopencv_imgproc.so.409: cannot open shared object file: No such file or directory
```

**Comment by xiota** [comment]
Bumped packages depending on `opencv`.  Rebuild in progress.

**Comment by xiota** [comment]
Bumped in c0fce29d6dfe8c9869d627315eeb2e6ddcce6b4a, but build servers stuck.  So may take a while.

**Comment by c02y** [comment]
Need to rebuild again:
```
extra/opencv 4.11.0-11 [installed: 4.12.0-1]
    usr/lib/libopencv_imgproc.so.411

$ /bin/ls /usr/lib/libopencv_imgproc.so*
/usr/lib/libopencv_imgproc.so  /usr/lib/libopencv_imgproc.so.412  /usr/lib/libopencv_imgproc.so.4.12.0
```
Archlinux
opencv 4.12.0-1
qimgv-git 1.0.2.r170.g34f8b43-1.4

**Comment by xiota** [comment]
Added rebuild triggers, so should rebuild automatically in future.

Servers have problems...  May be a while before rebuild reflected in repo...

Update: Rebuilt: `chaotic-aur/qimgv-git 1.0.2.r170.g34f8b43-3`
