### ISSUE TITLE
[Rebuild] nomacs

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#2631]
### Packages:

[nomacs](http://aur.archlinux.org/packages/nomacs)

### Latest chaotic version

`1:3.17.2282-2`

### Reason for rebuild

`nomacs: error while loading shared libraries: libopencv_imgproc.so.407: cannot open shared object file: No such file or directory`

### Logs

[nomacs.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/nomacs.log)

**Comment by niobium93** [comment]
Needs to be rebuilt again.
```
nomacs: error while loading shared libraries: libopencv_imgproc.so.409: cannot open shared object file: No such file or directory
```

**Comment by xiota** [comment]
Rebuilt and bumped other packages depending on `opencv`.

**Comment by xiota** [comment]
Clear your cache. `sudo pacman -Scc`

**Comment by niobium93** [comment]
Needs to be rebuilt again.

**Comment by xiota** [comment]
Servers having some problem.  Will  bump opencv-related packages after it's resolved.
