### ISSUE TITLE
[Request] apparmor-git

### ISSUE THREAD

**Issue by BL4CKH47H4CK3R** [chaotic-aur/packages#2632]
### Package:

[apparmor-git](https://aur.archlinux.org/packages/apparmor-git)

### Purpose:

Mandatory Access Control (MAC) using Linux Security Module (LSM).
Besides maintaining compatibility with [firejail-git](https://aur.archlinux.org/packages/firejail-git)

### Copyright:

GPL2, LGPL2.1

### Expected Interest:

Everyone

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
`extra/apparmor` does not work with `firejail-git`?
