### ISSUE TITLE
[Request] vulkan-tools-git

### ISSUE THREAD

**Issue by BL4CKH47H4CK3R** [chaotic-aur/packages#2633]
### Package:

[vulkan-tools-git](https://aur.archlinux.org/packages/vulkan-tools-git)

### Purpose:

Vulkan Utilities and Tools (git version)

### Benefits:

Improves compatibility for users who uses mesa-tkg-git and other git packages for graphical purposes

### Copyright:

Apache-2.0

### Expected Interest:

Everyone

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
How does this "improves compatibility"?  As far as I can tell, this just provides `vulkaninfo` and some demo programs (vkcube).  Is `vulkaninfo` from `extra/vulkan-tools` having some issue, like providing erroneous info?

**Comment by xiota** [comment]
Will close this as not planned sometime during the next few days because not getting an adequate response to my query.
