### ISSUE TITLE
[Request] lib32-vkbasalt

### ISSUE THREAD

**Issue by simons-public** [chaotic-aur/packages#2634]
### Packages:

[lib32-vkbasalt](https://aur.archlinux.org/packages/lib32-vkbasalt)

### Purpose:

A Vulkan post-processing layer. Some of the effects are CAS, FXAA, SMAA, deband.

### More information

Thanks for operating such an awesome repo!

I'm definitely using it for 32 bit games 👍

**Comment by xiota** [comment]
Is `lib32-vkbasalt` still needed / wanted?  It's not in the package lists.  Want to know if I should add it.

**Comment by simons-public** [comment]
I can't vouch for others, but I'm definitely using it for 32 bit games 👍

**Comment by xiota** [comment]
@simons-public  I'm repurposing this issue into a package request.  Will add `lib32-vkbasalt` to the package lists.  Feel free to comment here if there are any issues with the package.
