### ISSUE TITLE
[Request] element-desktop-git

### ISSUE THREAD

**Issue by nyabinary** [chaotic-aur/packages#2636]
### Package:

https://aur.archlinux.org/pkgbase/element-desktop-git

### Purpose:

Git version of the Element client.

### Benefits:

Bleeding edge Element builds

### Copyright:

Apache License 2.0

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes (the last request was closed because of being unable to build the package)

### Banned package?

No

**Comment by dr460nf1r3** [comment]
Still not fixed?
```
[2/4] Fetching packages...
error matrix-js-sdk@27.0.0: The engine "node" is incompatible with this module. Expected version ">=18.0.0". Got "16.20.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by xangelix** [comment]
Apologies for the delay! I fixed this in my private repo over a year ago,but the CI/CD failed and it never published...
It should be fixed now, but please let me know if you continue to experience issues.

**Comment by xiota** [comment]
@xangelix Fails to build.  [Log](https://builds.garudalinux.org/logs/logs.html?timestamp=1720758258765&id=element-desktop-git)

**Comment by xiota** [comment]
Planning to drop because still fails to build.

**Comment by xangelix** [comment]
> Planning to drop because still fails to build.

@xiota 

A new build dependency (`python-setuptools`) was added that should resolve the issue. Please ping me here if it doesn't.

**Comment by xiota** [comment]
@xangelix Build succeeds.  Thank you for updating.

**Comment by xiota** [comment]
@xangelix Do you know reason for error, how to fix?  Someone already mentioned in comment last month.

<details><summary>GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"</summary>

```
yarn run v1.22.22
$ yarn run build:ts && yarn run build:res && electron-builder
$ tsc
$ tsx scripts/copy-res.ts
  • electron-builder  version=26.0.16 os=6.12.33
  • artifacts will be published if draft release exists  reason=CI detected
  • loaded configuration  file=/home/builder/build/src/element-desktop/electron-builder.ts
  • writing effective config  file=dist/builder-effective-config.yaml
  • executing @electron/rebuild  electronVersion=36.5.0 arch=x64 buildFromSource=false appDir=./
  • installing native dependencies  arch=x64
  • preparing       moduleName=keytar-forked arch=x64
  • finished        moduleName=keytar-forked arch=x64
  • completed installing native dependencies
  • packaging       platform=linux arch=x64 electron=36.5.0 appOutDir=dist/linux-unpacked
  • downloading     url=https://github.com/electron/electron/releases/download/v36.5.0/electron-v36.5.0-linux-x64.zip size=112 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v36.5.0/electron-v36.5.0-linux-x64.zip duration=1.864s
(node:7639) [DEP0190] DeprecationWarning: Passing args to a child process with shell option true can lead to security vulnerabilities, as the arguments are not escaped, only concatenated.
(Use `node --trace-deprecation ...` to show where the warning was created)
  • executing @electron/fuses  electronPath=dist/linux-unpacked/element-desktop
  • building        target=tar.gz arch=x64 file=dist/element-desktop-1.11.105.tar.gz
  • building        target=deb arch=x64 file=dist/element-desktop_1.11.105_amd64.deb
  • adding autoupdate files for: deb. (Beta feature)  resourceDir=dist/linux-unpacked/resources
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86_64/fpm-1.9.3-2.3.1-linux-x86_64.7z size=5.0 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/fpm-1.9.3-2.3.1-linux-x86_64/fpm-1.9.3-2.3.1-linux-x86_64.7z duration=1.093s
  ⨯ GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
==> ERROR: A failure occurred in build().
```
</details>

**Comment by xiota** [comment]
@xangelix Found problem... electron-builder invocation needs `--publish=never` option.

yarn run build:native → yarn run hak → yarn install && yarn run build → ...

Build succeeds after replacing both yarn run build... invocations with:
```
yarn run build:ts
yarn run build:res
yarn run electron-builder --publish=never
```

**Comment by xiota** [comment]
Fixed with interfere in f796567a78ec496e61d0e4b5185fe58ee8a7d4c9.  Given package history and low usage, will drop next time it fails to build without explanation or fix within a reasonable time frame (about two weeks).  Metrics:

* element-desktop-git # 26
* element-web-git # 27

**Comment by xangelix** [comment]
I think this should be resolved now, I appreciate the PKGBUILD.append.

Apologies this went unresolved for so long, and that I don't have a well-documented place to contact/submit issue/MR fixes. This year has been full of surprises for me.

**Comment by xiota** [comment]
@xangelix Thanks for updating.  I'd assumed a ping here would be sufficient since you commented here before.

This package previously wasn't buildable from early Jun to late Aug.  It's okay if you need more time or are busy with other things, but in future, if it will take longer than about two weeks, a response would be appreciated.

Interfere removed in dd6420c8b5e78def11eb28e19c6a037e08f34280

Current metrics.

* element-desktop-git # 90
* element-web-git # 92
