### ISSUE TITLE
[Rebuild] libpdfium-nojs

### ISSUE THREAD

**Issue by ARatChicken** [chaotic-aur/packages#2640]
### Packages:

[libpdfium-nojs](https://aur.archlinux.org/packages/libpdfium-nojs)

### Latest chaotic version

`5563.r1.05a0a80e52-1`

### Reason for rebuild

Broken can be seen in logs 
``ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
``

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/libpdfium-nojs.log

### More information

i think this might be related with ICU because this is in the logs ``warning: icu-72.1-2 is up to date -- skipping``

**Comment by dr460nf1r3** [comment]
We can probably blame this on a faulty commit since this is a git package under the hood, the build error could no longer be seen when I executed a manual build.
