### ISSUE TITLE
[Outdated] lapce-git

### ISSUE THREAD

**Issue by Nyabinary** [chaotic-aur/packages#2644]
### Packages:

[lapce-git](https://aur.archlinux.org/packages/lapce-git)

### Latest chaotic version

0.2.7.r22.g664b664-1

### Latest upstream version

master(91b404fb67c19edf854cec96a21a15f607dc2ca0)

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/lapce-git.log

**Comment by dr460nf1r3** [comment]
Looks like new dependencies have been introduced:
`  error: could not find system library 'xkbcommon-x11' required by the 'glazier' crate
`

**Comment by Nyabinary** [comment]
cc: @ptr1337

**Comment by dr460nf1r3** [comment]
Mhm, fails to build even after adding `libxkbcommon-x11` as dependency..
~~~
error: failed to run custom build command for `glazier v0.7.0 (https://github.com/lapce/glazier?rev=ab692f5eb1
0e7511f2e0a6b0a86151df5ae67921#ab692f5e)`

**Comment by xiota** [comment]
Builds with the following changes:

* Add `libxkbcommon-x11` to `depends`
* Add `clang` to `makedepends`
* Add `LIBCLANG_PATH='/usr/lib'` to `build()`
* Fix spelling of `provides`

**Comment by Nyabinary** [comment]
@xiota Can you post it as a patch?

**Comment by ptr1337** [comment]
Sorry for the delay, I have fixed now the AUR package. :)
