### ISSUE TITLE
issue: ffmpeg-compat-57 needs removal

### ISSUE THREAD

**Issue by timescam** [chaotic-aur/packages#265]
ffmpeg-compat-57 rebuild needed,
the current version in repo does not work w/ spotify, I rebuild it form aur and it works again.

**Comment by xiota** [comment]
Request to remove `ffmpeg-compat-57`.

* It does not install:
    ```zsh
    $ sudo pacman -S ffmpeg-compat-57
    resolving dependencies...
    warning: cannot resolve "libvpx.so=7-64", a dependency of "ffmpeg-compat-57"
    :: The following package cannot be upgraded due to unresolvable dependencies:
          ffmpeg-compat-57
    
    :: Do you want to skip the above package for this upgrade? [y/N]
    error: failed to prepare transaction (could not satisfy dependencies)
    :: unable to satisfy dependency 'libvpx.so=7-64' required by ffmpeg-compat-57
    ```
* No package currently in the official or chaotic-aur repositories require it.  All packages requiring `libav*.so` allow up to version 64.
* `chaotic-aur/spotify` works fine without it.

**Comment by PedroHLC** [comment]
> Request to remove `ffmpeg-compat-57`.
> 
>     * It does not install:
>       ```shell
>       $ sudo pacman -S ffmpeg-compat-57
>       resolving dependencies...
>       warning: cannot resolve "libvpx.so=7-64", a dependency of "ffmpeg-compat-57"
>       :: The following package cannot be upgraded due to unresolvable dependencies:
>             ffmpeg-compat-57
>       
>       :: Do you want to skip the above package for this upgrade? [y/N]
>       error: failed to prepare transaction (could not satisfy dependencies)
>       :: unable to satisfy dependency 'libvpx.so=7-64' required by ffmpeg-compat-57
>       ```
> 
>     * No package currently in the official or chaotic-aur repositories require it.  All packages requiring `libav*.so` allow up to version 64.
> 
>     * `chaotic-aur/spotify` works fine without it.

Cc @dr460nf1r3
