### ISSUE TITLE
[Request] ueberzugpp

### ISSUE THREAD

**Issue by federicotorrielli** [chaotic-aur/packages#2651]
### Package:

[ueberzugpp](https://aur.archlinux.org/packages/ueberzugpp)

### Purpose:

Command line util which allows to display images in combination with X11 written in C++

### Benefits:

De facto replacement for ueberzug. Very important for applications like [lobster](https://aur.archlinux.org/packages/lobster-git)

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
See #2583
