### ISSUE TITLE
[Rebuild] mpv-full-git

### ISSUE THREAD

**Issue by LeeYiKyung** [chaotic-aur/packages#2652]
### Packages:

[mpv-full-git](https://aur.archlinux.org/packages/mpv-full-git)

### Latest chaotic version

0.35.1.r339.gd1d0b1a8ee-1

### Reason for rebuild

mpv: error while loading shared libraries: libplacebo.so.229: cannot open shared object file: No such file or directory

**Comment by dr460nf1r3** [comment]
Some version mismatches happening:
~~~
Run-time dependency libplacebo found: YES 5.264.1

mpv/meson.build:932:48: ERROR: Feature libplacebo-next cannot be enabled: libplacebo v5.266.0+ was not found!
~~~
Notified the AUR maintainer.

**Comment by Nyabinary** [comment]
@dr460nf1r3 maintainer seemed to push a new PKGBUILD today addressing the issue

**Comment by dr460nf1r3** [comment]
Sadly, the same issue as before :/ 
`mpv/meson.build:932:48: ERROR: Feature libplacebo-next cannot be enabled: libplacebo v5.266.0+ was not found!`

**Comment by xiota** [comment]
`libplacebo-git` not building.  Don't know what to make of the log.  
[libplacebo-git.log](https://github.com/chaotic-aur/packages/files/12137483/libplacebo-git.log)

**Comment by jkcdarunday** [comment]
libplacebo-git builds for me. It has libdovi in its dependencies which paru also builds from the AUR.

**Comment by xiota** [comment]
> It has libdovi in its dependencies

Thanks.  I overlooked the error in the log.
