### ISSUE TITLE
[Bug] wine-tkg fails again to build

### ISSUE THREAD

**Issue by raziel100** [chaotic-aur/packages#2654]
### Packages:

https://mirror.ufscar.br/chaotic-aur/chaotic-aur/x86_64/wine-tkg-fsync-git-8.11.r232.gf4a8ad89d43-327-x86_64.pkg.tar.zst
https://mirror.ufscar.br/chaotic-aur/chaotic-aur/x86_64/wine-tkg-staging-fsync-git-8.11.r10.ge57244a5-327-x86_64.pkg.tar.zst

### Latest chaotic version

8.11.r232.gf4a8ad89d43-327 | 8.11.r10.ge57244a5-327

### What happens?

wine-tkg-staging and wine-tkg-upstream both are failing building for a fell days now, but in a clean chroot using the chaotic profiles is building just fine, so is probably a problem with the builder itself, maybe some corrupted file?.

### What is expected to happen?

building successfully

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/wine-tkg-staging.log
https://builds.garudalinux.org/repos/chaotic-aur/logs/wine-tkg-upstream.log

**Comment by dr460nf1r3** [comment]
~~~
patching file dlls/msctf/msctf_internal.h
Hunk #1 FAILED at 35.
1 out of 1 hunk FAILED -- saving rejects to file dlls/msctf/msctf_internal.h.rej
~~~
Looks more like an outdated patch to me honestly 🧐

**Comment by raziel100** [comment]
> ```
> patching file dlls/msctf/msctf_internal.h
> Hunk #1 FAILED at 35.
> 1 out of 1 hunk FAILED -- saving rejects to file dlls/msctf/msctf_internal.h.rej
> ```
> 
> Looks more like an outdated patch to me honestly 🧐

it could be, but in clean chroot it compiles normaly, and i did use the same profile from chaotic-staging.cfg and it did compile just fine.

**Comment by dr460nf1r3** [comment]
These are now updated.
