### ISSUE TITLE
[Rebuild] obs-studio-tytan652

### ISSUE THREAD

**Issue by domainzero** [chaotic-aur/packages#2657]
### Packages:

[obs-studio-tytan652](https://aur.archlinux.org/packages/obs-studio-tytan652)

### Latest chaotic version

`29.1.1-1`

### Reason for rebuild

Package out of date. Latest is `29.1.3-1`

**Comment by dr460nf1r3** [comment]
`error: target not found: vlc-luajit`

**Comment by dr460nf1r3** [comment]
Mhm, added the dep, still:
`[ 39%] Linking CXX shared module decklink.so
Installing decklink to OBS rundir
[ 39%] Built target decklink
make: *** [Makefile:156: all] Error 2`
