### ISSUE TITLE
[Rebuild] ffmpeg-obs

### ISSUE THREAD

**Issue by domainzero** [chaotic-aur/packages#2658]
### Packages:

[ffmpeg-obs](https://aur.archlinux.org/packages/ffmpeg-obs)

### Latest chaotic version

`6.0.r12.ga6dc929-4`

### Reason for rebuild

Out of date. Latest is `6.0.r12.ga6dc929-5`

**Comment by dr460nf1r3** [comment]
~~~
ERROR: librist >= 0.2.7 not found using pkg-config
