### ISSUE TITLE
[Request] lsix-git

### ISSUE THREAD

**Issue by AgentPhoenix7** [chaotic-aur/packages#2659]
### Package:

[lsix-git](https://aur.archlinux.org/lsix-git.git)

### Purpose:

Like ls but for images, shows thumbnails in terminal using sixel graphics

### Copyright:

https://github.com/hackerb9/lsix

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Like ls but for images, shows thumbnails in terminal using sixel graphics

**Comment by xiota** [comment]
Please update request with following:

* Use AUR page, not the git link.
* Use the License name for standard licenses.

**Comment by xiota** [comment]
@AgentPhoenix7 Do you still want this package?  Do you plan to update the request?
