### ISSUE TITLE
[Rebuild] mcpelauncher-ui-git mcpelauncher-linux-git

### ISSUE THREAD

**Issue by REmerald** [chaotic-aur/packages#2660]
### Packages:

[mcpelauncher-ui-git](https://aur.archlinux.org/pkgbase/mcpelauncher-ui-git)
[mcpelauncher-linux-git](https://aur.archlinux.org/pkgbase/mcpelauncher-linux-git)

### Latest chaotic version

`v0.9.0.qt6.r1.ge52a436-1` `v0.9.0.qt6.r8.g27eb1b8-1`

### Reason for rebuild

Broken, requires .so file with non-existing suffix.

Rebuilding should fix the issue. See [https://github.com/minecraft-linux/mcpelauncher-ui-manifest/issues/57](https://github.com/minecraft-linux/mcpelauncher-ui-manifest/issues/57).

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/mcpelauncher-ui-git.log
https://builds.garudalinux.org/repos/chaotic-aur/logs/mcpelauncher-linux-git.log

### Builds?

Didn't try building myself.

### More information

┐(ﾟ～ﾟ)┌

**Comment by dr460nf1r3** [comment]
Looks like there are a lot of issues when attempting the rebuild ([logs](https://builds.garudalinux.org/repos/chaotic-aur/logs/mcpelauncher-ui-git.log)).
`mcpelauncher-linux-git` additionally probably needs to be updated? (`fatal: invalid reference: origin/qt6`)

**Comment by REmerald** [comment]
@Technetium1, @dr460nf1r3, @xiota, both `-ui-git` and `-linux-git` have built fine in the clean chroot:
[mcpelauncher-ui-git.log](https://github.com/chaotic-aur/packages/files/12163747/mcpelauncher-ui-git.log)
(forgot to dump the log of `-linux-git` before making it, and my terminal crashed after I tried to paste its history to vim, :disappointed:)

Also, `-ui-git` disappeared from the repo, for some reason...

Btw, maybe it'll be a good idea to add [mcpelauncher-appimage](https://aur.archlinux.org/packages/mcpelauncher-appimage), because I can use it when the git version is broken?

**Comment by Technetium1** [comment]
One of the primary issues right now seems to be getting `qt6-webengine`:
```
 qt6-webengine-6.5.2-1-x86_64 downloading...
checking keyring...
checking package integrity...
error: qt6-webengine: signature from "Antonio Rojas <arojas@archlinux.org>" is invalid
:: File /var/cache/pacman/pkg/qt6-webengine-6.5.2-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] error: failed to commit transaction (invalid or corrupted package)
```

**Comment by REmerald** [comment]
@Technetium1, is that a bug of the arch `extra` repo?`

**Comment by Technetium1** [comment]
I believe it was with the keyring. It's solved now.

**Comment by REmerald** [comment]
@Technetium1 @dr460nf1r3, `protobuf` updated recently `[2023-09-21T01:49:52+0300] [ALPM] upgraded protobuf (24.2-1 -> 24.2-2)`, so binary `mcpelauncher-ui-qt` broke again
```
mcpelauncher-ui-qt: symbol lookup error: mcpelauncher-ui-qt: undefined symbol: _ZN6google8protobuf8internal17AssignDescriptorsEPFPKNS1_15DescriptorTableEvEPN4absl12lts_202301259once_flagERKNS0_8MetadataE
```

So, I think rebuilding `mcpelauncher-ui-git` (and `mcpelauncher-linux-git` just in case) should fix it.

**Comment by Technetium1** [comment]
@dr460nf1r3 I was going to do it but lower is missing again (?!?)

**Comment by dr460nf1r3** [comment]
Hum, thats weird! It can be regenerated with `chaotic lw` btw.

Is 
```
mcpelauncher-ui-git v0.11.0.qt6.r3.ga40ddb0-1
```
the broken version or did it update in the meantime?

**Comment by REmerald** [comment]
@dr460nf1r3, `ga40ddb0` commit [is from the `qt6` branch](https://github.com/minecraft-linux/mcpelauncher-ui-manifest/commits/qt6), if I understood your question correctly.

**Comment by dr460nf1r3** [comment]
Well, what I meant is the following: if I understood it correctly, `mcpelauncher-ui-git` currently fails to open due to `protobuf` updates. Therefore my question was whether the broken package you are using has the mentioned version. In any case, I rebuilt both packages. Since those are `-git` packages you might need to reinstall the package in order to profit from it (which might also produce a signature error, just retry and it'll work).

**Comment by REmerald** [comment]
> whether the broken package you are using has the mentioned version

Yes, it has, and it worked before `protobuf` upgrade

> In any case, I rebuilt both packages.

Thanks, this fixed the issue, the launcher launches now.

> Since those are `-git` packages you might need to reinstall the package in order to profit from it

Hmm, theoretically, could we increment the last digit in the package, next time it happens? E.g. `v0.11.0.qt6.r3.ga40ddb0-2`, so that pacman would see it as an update?
It would help the people, not knowing about the issue, as well.

> which might also produce a signature error, just retry and it'll work

Yep, it did. Thanks for telling.

Anyways, everything works now, thanks a lot.

**Comment by dr460nf1r3** [comment]
> Hmm, theoretically, could we increment the last digit in the package, next time it happens? E.g. `v0.11.0.qt6.r3.ga40ddb0-2`, so that pacman would see it as an update?
> It would help the people, not knowing about the issue, as well.

We already do this for non vcs packages. It does work by increasing pkgrel by 0.1 though, which doesn't apply to vcs packages however as they set their pkgver based on pkgver() of the PKGBUILD itself.

**Comment by xiota** [comment]
> We already do this for non vcs packages. It does work by increasing pkgrel by 0.1 though, which doesn't apply to vcs packages however as they set their pkgver based on pkgver() of the PKGBUILD itself.

@dr460nf1r3   I noticed bumping works with -git packages that were recently updated and don't have any upstream commits yet.  So this suggestion for toolbox could fix bumps...  https://github.com/chaotic-aur/toolbox/issues/92

> We already do this for non vcs packages.

I'll run a search for affected -git packages to rebuild later.

**Comment by dr460nf1r3** [comment]
Yes, I thought about that too while writing the post @xiota
