### ISSUE TITLE
[Outdated] ly

### ISSUE THREAD

**Issue by REmerald** [chaotic-aur/packages#2661]
### Packages:

[ly](https://archlinux.org/packages/extra/x86_64/ly/)

### Latest chaotic version

`0.5.3-3`

### Latest upstream version

`0.6.0-1`

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/ly.log

### Builds in clean chroot?

None

### More information

The package was moved from AUR to `extra`, therefore can be removed.

**Comment by xiota** [comment]
Was removed from package lists in fe0db832bc96cb40daa6bb832e30c18e90c405af, but forgot to drop it from the database.
