### ISSUE TITLE
[Outdated] gimp-git

### ISSUE THREAD

**Issue by roland-5** [chaotic-aur/packages#2668]
### Packages:

[gimp-git](https://aur.archlinux.org/packages/gimp-git)

### Latest chaotic version

2:2.99.15.r494.5112394636-1

### Latest upstream version

gimp-git 2:2.99.16

### More information

https://www.gimp.org/news/2023/07/09/gimp-2-99-16-released/

**Comment by dr460nf1r3** [comment]
`/home/main-builder/pkgwork/PKGBUILD: line 83: ./autogen.sh: No such file or directory`
Needs interfere.

**Comment by xiota** [comment]
Should we add or switch to `gimp-develop-git`?  It also needs an interfere, but can be installed alongside `gimp`.

**Comment by dr460nf1r3** [comment]
Mhm, for me personally `gimp-git` would be sufficient, idk about other people?

**Comment by xiota** [comment]
Just added an interfere and rebuilt `gimp-git`.

**Comment by dr460nf1r3** [comment]
I saw it getting deployed, nice! :)

**Comment by roland-5** [comment]
> Mhm, for me personally `gimp-git` would be sufficient, idk about other people?

Personally, I'm totally OK with gimp-git only.
