### ISSUE TITLE
[Outdated] ledger-live

### ISSUE THREAD

**Issue by EvoXCX** [chaotic-aur/packages#2670]
### Packages:

[ledger-live](https://aur.archlinux.org/packages/ledger-live)

### Latest chaotic version

2.57.0

### Latest upstream version

2.64.2

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/ledger-live.log

**Comment by dr460nf1r3** [comment]
`https://downloads.sentry-cdn.com/sentry-cli/2.13.0/sentry-cli-Linux-x86_64` refuses connection currently, therefore the build fails.
