### ISSUE TITLE
[Remove] libvirt-xen

### ISSUE THREAD

**Issue by ahmubashshir** [chaotic-aur/packages#2672]
### Package:

[libvirt-xen](//aur.archlinux.org/pkgbase/libvirt-xen)

### Purpose:

Xen hypervisor integration with libvirt.

### Benefits:

It makes it easier to use Xen.

### Building:

makepkg or makechrootpkg 🙃 

### Copyright:

GPL3, LGPL

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
In the future, please put the package name in the title.  I've gone ahead and edited it for you.

**Comment by ahmubashshir** [comment]
Sorry, I forgot :3

**Comment by xiota** [comment]
Didn't build because of `check()` failure.  Add interfere?

**Comment by ahmubashshir** [comment]
I used aurutils to build it w/o issues as well as makechrootpkg. btw, what was the error?

**Comment by xiota** [comment]
```
Summary of Failures:

152/152 commandtest                     TIMEOUT        30.16s   killed by signal 15 SIGTERM

Ok:                 151 
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            1   
```

**Comment by xiota** [comment]
`check()` failed because of `commandtest` TIMEOUT.  Since you have built a local copy, I will tag this as waiting for upstream fix, unless another maintainer feels this is high enough priority to create an interfere.

**Comment by fwookerton** [comment]
@ahmubashshir Side question but since you compiled this package, does it work for you? For me it just coredumps, even when I run it as system service and when it is ran deliberately through the terminal
```
libvirtd: libxl_fork.c:351: sigchld_installhandler_core: La declaración `((void)"application must negotiate with libxl about SIGCHLD", !(sigchld_saved_action.sa_flags & SA_SIGINFO) && (sigchld_saved_action.sa_handler == SIG_DFL || sigchld_saved_action.sa_handler == SIG_IGN))' no se cumple.
zsh: IOT instruction  sudo libvirtd
```

**Comment by dr460nf1r3** [comment]
I was under the impression that our built tools caused the timeout and went ahead and removed it to let the build pass.

**Comment by xiota** [comment]
@ahmubashshir Someone has been having issues with the package.  Let me know if you want help trying to fix it.

**Comment by xiota** [comment]
Planning to drop because depends on `xen`, which is failing to build.  Metrics 5.
