### ISSUE TITLE
[Outdated] webstorm

### ISSUE THREAD

**Issue by balaios** [chaotic-aur/packages#2673]
### Packages:

[webstorm](https://aur.archlinux.org/packages/webstorm)

### Latest chaotic version

2023.1.3-1

### Latest upstream version

2023.2-1

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/webstorm.log

**Comment by xiota** [comment]
JetBrains [Licenses](https://sales.jetbrains.com/hc/en-gb/articles/115001015290-Where-can-I-find-the-EULA-End-User-License-Agreement-) appear to consistently disallow redistribution of their software, except for community and open-source editions.

* [TOOLBOX SUBSCRIPTION AGREEMENT FOR INDIVIDUAL CUSTOMERS](https://www.jetbrains.com/legal/docs/toolbox/license_personal/)

    > 3. GRANT OF RIGHTS
    >
    > 3.2 Unless the Subscription has expired or this Agreement is terminated in accordance with Section 12, and subject to the terms and conditions specified in this Agreement, JetBrains grants you the non-exclusive and non-transferable right to use each Product covered by the Subscription as stipulated below:
    >
    > (B) You may not:
    >
    > (ii) rent, lease, reproduce, modify, adapt, create derivative works of, distribute, sell, or transfer the Product;

*  [License Agreement for JetBrains SDK Products](https://www.jetbrains.com/legal/docs/agreements/dotnet/sdk/)

     > 5. SDK LICENSE
     >
     > 5.3 You may not modify, adapt, redistribute, decompile, reverse-engineer, disassemble, or create derivative works of (or combine with or integrate into another work) the SDK, SDK Compatible Software, or any part thereof.

**Comment by xiota** [comment]
Easier to ignore when packages are on autopilot, but when intervention is required to fix them, maybe time to consider dropping them.

These are basically misnamed binary packages.  There's little overhead for users to build them besides the download.

Building and distributing these packages takes up bandwidth and other resources.  One of the build servers has been having resource and other issues.

**Comment by balaios** [comment]
ok

**Comment by xiota** [comment]
Did you close so I wouldn't be tempted to drop it?  Don't worry.  I wouldn't touch this one unless another chaotic maintainer also thinks it should be dropped or the package maintainer goes rogue (like [this](https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=unifont&id=d8bcd61a188cfdfc232586b4343fc1dee97e03d1), where the maintainer put Russian roulette in the PKGBUILD).

**Comment by balaios** [comment]
I closed it because I agree with your point, and I wouldn't mind building the package on my own machine. The other Jetbrains packages show the same behavior. So, it would be inconvenient to do this work.
