### ISSUE TITLE
[Request] linux-binder linux-binder-headers linux-binder-docs

### ISSUE THREAD

**Issue by mdhishamsayed** [chaotic-aur/packages#2679]
### Package:

[linux-binder](https://aur.archlinux.org/packages/linux-binder)

### Purpose:

The following kernel is vanilla arch linux kernel with Binder module enabled as binder_linux-dkms package does not work.

### Benefits:

Used to run android on wayland-compatible desktops via waydroid.

### Building:

makepkg, but i don't know weather this will build or not, i did not test it.

### Copyright:

GPL2

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Dropping this package:

* `binder_linux-dkms` is available and appears to be working.
* Reduce resource usage.  Linux kernels are failing to build because of insufficient space.
* aur package is inexplicably tracking 6.5.
