### ISSUE TITLE
Request: strawberry

### ISSUE THREAD

**Issue by fabianski7** [chaotic-aur/packages#268]
> Strawberry is a music player and music collection organizer. It is a fork of Clementine released in 2018 aimed at music collectors and audiophiles. It's written in C++ using the Qt 5 toolkit.

`strawberry-full-git`
`strawberry-git`
`strawberry-lite`

**Comment by fabianski7** [comment]
thank you

**Comment by xiota** [comment]
Dropping `strawberry-full-git` because there's no longer any practical difference from `strawberry-git`.
