### ISSUE TITLE
[Outdated] mpv-full

### ISSUE THREAD

**Issue by jkcdarunday** [chaotic-aur/packages#2682]
### Packages:

[mpv-full](https://aur.archlinux.org/packages/mpv-full)

### Latest chaotic version

0.35.1-2.5

### Latest upstream version

0.36.0-1

### Logs

It seems to have attempted to build it but it fails to install a corrupt dependency package:
https://builds.garudalinux.org/repos/chaotic-aur/logs/mpv-full.log

### Builds in clean chroot?

On a clean chroot, paru was able to completly build mpv-full after building and installing the ff. AUR packages:
```
ffmpeg-git-6.1.r111232.g468615f204-1
libdovi-3.1.2-1
libplacebo-git-6.287.0rc1.57.g363cada9-1
spirv-cross-2023.05.12-1
mpv-full-0.36.0-1
```

**Comment by guiltiest-gear** [comment]
@xiota libdovi can be removed, package is now part of official extra repo: https://archlinux.org/packages/extra/x86_64/libdovi/
