### ISSUE TITLE
[Request] shell-color-scripts

### ISSUE THREAD

**Issue by guiltiest-gear** [chaotic-aur/packages#2683]
### Package:

[shell-color-scripts](https://aur.archlinux.org/packages/shell-color-scripts)

### Purpose:

A CLI tool for displaying a collection of colorscripts to the terminal.

### Benefits:

It's just a small tool to help add some life and bling to the terminal, perhaps somewhat comparable to the purpose of neofetch.

### Copyright:

MIT

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
Missing `git`, I left [a comment](https://aur.archlinux.org/packages/shell-color-scripts#comment-926928).

**Comment by xiota** [comment]
`shell-color-scripts` was a misnamed git package.  Switched to correct package.
