### ISSUE TITLE
[Request] gamejolt-client-bin

### ISSUE THREAD

**Issue by zany130** [chaotic-aur/packages#2684]
### Package:

[gamejolt-client-bin](https://aur.archlinux.org/packages/gamejolt-client-bin)

### Purpose:

Game store for some indie games

### Building:

built succsesfully with `extra-x86_64-build`

### Copyright:

MIT

### Expected Interest:

Most

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Dropping because AUR package is long out of date.  Also, binary package is using appears to be from an unofficial repo.  Metrics 4.
