### ISSUE TITLE
[Request] linux-mainline-binder

### ISSUE THREAD

**Issue by mdhishamsayed** [chaotic-aur/packages#2685]
### Package:

[linux-mainline-binder](https://aur.archlinux.org/packages/linux-mainline-binder)

### Purpose:

This is the mainline kernel with binder enabled.

### Benefits:

The linux mainline kernel does not have binder enabled by default, useful for waydroid users, so this enables it by default.

### Building:

I did not build this, my PC can't.

### Copyright:

GPL2

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Would you mind adding a description of binder to the request for people who don't know what it is.  (I have nothing to do with kernel builds.  Just think it's helpful to have better descriptions of kernel variants.)

**Comment by Technetium1** [comment]
Do we not already provide another suitable kernel that has this module?

**Comment by Edu4rdSHL** [comment]
There are zero reasons to include it, just use the `binder_linux-dkms` package which is already in our repos.
