### ISSUE TITLE
[Request] subtitlecomposer-nopocketsphinx-git

### ISSUE THREAD

**Issue by kugland** [chaotic-aur/packages#2686]
### Package:

[subtitlecomposer-nopocketsphinx-git](https://aur.archlinux.org/packages/subtitlecomposer-nopocketsphinx-git)

### Purpose:

The current packages in Chaotic AUR for both `subtitlecomposer` and `subtitlecomposer-git` are linked against an old version of `libicu`.

While trying to build it manually, I found that the it’s an upstream problem: the officially distributed sources of `subtitlecomposer` are failing to build due to a problem related to its speech recognition plugin, that depends on `pocketsphinx`. So I created an AUR package that builds the package without this plugin and without this dependency.

### Benefits:

Now there’s going to be a working version of `subtitlecomposer`.

### Building:

makepkg

### Copyright:

GPL

### Expected Interest:

Many

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Package name is unusual.  Usually `-git` goes at the end because someone might want to create a non-git version.  Since you're the maintainer, suggest you rename and open a merge request.

**Comment by kugland** [comment]
> Package name is unusual. Usually `-git` goes at the end because someone might want to create a non-git version. Since you're the maintainer, suggest you rename and open a merge request.

Hey. I just created a new package and requested the deletion of the old one.

The new one is [subtitlecomposer-nopocketsphinx-git](https://aur.archlinux.org/packages/subtitlecomposer-nopocketsphinx-git)

**Comment by xiota** [comment]
`subtitlecomposer` has been rebuilt, should work now.  `subtitlecomposer-git` build fails.

Is `subtitlecomposer-nopocketsphinx-git` intended to be a temporary substitute until `subtitlecomposer-git` works again?

**Comment by xiota** [comment]
Added interfere for `subtitlecomposer-git` to disable pocketsphinx.  I think `subtitlecomposer-nopocketsphinx-git` is not needed.

**Comment by kugland** [comment]
> Does `subtitlecomposer-nopocketsphinx-git` serve any purpose other than to get `subtitlecomposer-git` to build?

No. That was it. Thanks!
