### ISSUE TITLE
[Rebuild] kodi-nexus-git

### ISSUE THREAD

**Issue by MPSMPS** [chaotic-aur/packages#2692]
### Packages:

[kodi-nexus-git](https://aur.archlinux.org/packages/kodi-nexus-git)

### Latest chaotic version

kodi-nexus-git-r62110.c700820f09c-1

### Reason for rebuild

Broken lib depency; build against too old libfmt:
`/usr/lib/kodi/kodi.bin: error while loading shared libraries: libfmt.so.9: cannot open shared object file: No such file or directory`

### Logs

`/usr/lib/kodi/kodi.bin: error while loading shared libraries: libfmt.so.9: cannot open shared object file: No such file or directory`

### Builds?

Not tried.

**Comment by xiota** [comment]
```
==> Validating source files with b2sums...
    xbmc ... Skipped
    libdvdcss-1.4.3-Next-Nexus-Alpha2-2.tar.gz ... Passed
    libdvdnav-6.1.1-Next-Nexus-Alpha2-2.tar.gz ... Passed
    libdvdread-6.1.3-Next-Nexus-Alpha2-2.tar.gz ... Passed
    ffmpeg-4.4.1-Nexus-Alpha1.tar.gz ... Passed
    crossguid-ca1bf4b810e2d188d04cb6286f957008ee1b7681.tar.gz ... Passed
    fstrcmp-0.7.D001.tar.gz ... Passed
    flatbuffers-23.3.3.tar.gz ... Passed
    libudfread-1.1.2.tar.gz ... Passed
    cheat-sse-build.patch ... Passed
    23266.patch ... FAILED
==> ERROR: One or more files did not pass the validity check!
```

**Comment by Technetium1** [comment]
`Finished making: kodi-nexus-git r62191.34d2cacc8a7-1 (Sat 12 Aug 2023 08:38:26 AM -03)`
