### ISSUE TITLE
[Request] safing portmaster

### ISSUE THREAD

**Issue by Redo11** [chaotic-aur/packages#2695]
### Package:

[portmaster-stub-bin](https://aur.archlinux.org/pkgbase/portmaster-stub-bin)

### Purpose:

It is a free firewall, using custom kernel modules, as well as a paid VPN-type service, which is optional. 
It allows for managing network, applying connectivity rules per app and DNS blocking. It also uses secure DNS. 

### Benefits:

This is already an official binary build. It is packaged in Manjaro as well and works well. 

### Building:

I didn't build the app in clean chroot.

### Copyright:

AGPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Website: https://safing.io
The app was also featured on The Linux Experiment as a sponsorship

**Comment by xiota** [comment]
Dropping because no longer in AUR.  Also, stub package that updates outside package manager control.  Metrics 329.
