### ISSUE TITLE
[Request] spirv-headers-git

### ISSUE THREAD

**Issue by jdtatz** [chaotic-aur/packages#2698]
### Package:

[spirv-headers-git](https://aur.archlinux.org/packages/spirv-headers-git)

### Purpose:

Needed to build llvm-git, see the [build log](https://builds.garudalinux.org/repos/chaotic-aur/logs/llvm-git.log), it's specifically needed for the spirv-llvm-translator.

### Benefits:

This package is also useful for building other tools that use bleeding edge SPIR-V.

### Building:

makepkg

### Copyright:

[custom](https://github.com/KhronosGroup/SPIRV-Headers/blob/main/LICENSE)

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
@thotypous please advise

**Comment by xiota** [comment]
Adding this because... [chaotic-aur/pkgbuild-llvm-git/PKGBUILD#L13-L16](https://github.com/chaotic-aur/pkgbuild-llvm-git/blob/4731493091e431b6ae050639e4512fc1f78a3187/PKGBUILD#L13-L16).

**Comment by xiota** [comment]
`llvm-git` last successfully built earlier today.
