### ISSUE TITLE
Updating to linux 5.8.3-6-tkg-pds-zen. Error in configure.

### ISSUE THREAD

**Issue by Galcian79** [chaotic-aur/packages#270]
`==> dkms install --no-depmod -m nvidia -v 450.66 -k 5.8.3-6-tkg-pds
Error! Bad return status for module build on kernel: 5.8.3-6-tkg-pds (x86_64)
Errore nella configurazione di 
Consult /var/lib/dkms/nvidia/450.66/build/make.log for more information.
==> Warning, `dkms install --no-depmod -m nvidia -v 450.66 -k 5.8.3-6-tkg-pds' returned 10`

It worked before the update.

**Comment by Galcian79** [comment]
UPDATE: I tried to install the fsync patched kernel from [Valveaur] and both modules fails to configure as well. Only manjaro stock kernel works.
I don't know what is happening, maybe a recent change in mkninitcpio?

**Comment by PedroHLC** [comment]
Did you get any other insight on this? I can't reproduce it. Maybe is something Manjaro-specific.

**Comment by Galcian79** [comment]
Yes i found two solutions. Building the kernel from source with my gcc compiler, or you rebuild the kernel with the latest gcc version.
My gcc version is 10.1.0-2
Other workaround i found is to set env variable IGNORE_CC_MISMATCH=1, but it didn't worked or i am doing it wrong either.

**Comment by PedroHLC** [comment]
Pull gcc and gcc-libs from testing or arch's repos.
I can't break things on arch cause Manjaro keeps forking things uselessly.

Please close this issue when Manjaro move to GCC 10.2

**Comment by Galcian79** [comment]
As of today GCC has been updated to 10.2 on Manjaro Stable. Not tested because, from now on, i'll build TKG kernels from source, to avoid issues
