### ISSUE TITLE
[Request] lightly-boehs-git

### ISSUE THREAD

**Issue by throwaway69420-69420** [chaotic-aur/packages#2700]
### Package:

[lightly-boehs-git](https://aur.archlinux.org/packages/lightly-boehs-git)

Dependencies (12)

   [ breeze-icons ](https://archlinux.org/packages/?q=breeze-icons)([breeze-icons-git](https://aur.archlinux.org/packages/breeze-icons-git))
   [ frameworkintegration ](https://archlinux.org/packages/?q=frameworkintegration)([frameworkintegration-git](https://aur.archlinux.org/packages/frameworkintegration-git))
   [ hicolor-icon-theme ](https://archlinux.org/packages/?q=hicolor-icon-theme)([hicolor-icon-theme-git](https://aur.archlinux.org/packages/hicolor-icon-theme-git))
   [ kdecoration ](https://archlinux.org/packages/?q=kdecoration)([kdecoration-git](https://aur.archlinux.org/packages/kdecoration-git))
   [ kwayland ](https://archlinux.org/packages/?q=kwayland)([kwayland-git](https://aur.archlinux.org/packages/kwayland-git))
   [ cmake ](https://archlinux.org/packages/?q=cmake)([cmake-git](https://aur.archlinux.org/packages/cmake-git)) (make)
   [ extra-cmake-modules ](https://archlinux.org/packages/?q=extra-cmake-modules)([extra-cmake-modules-git](https://aur.archlinux.org/packages/extra-cmake-modules-git)) (make)
   [ git ](https://archlinux.org/packages/?q=git)([git-vfs](https://aur.archlinux.org/packages/git-vfs), [git-run-command-patch-git](https://aur.archlinux.org/packages/git-run-command-patch-git), [git-git](https://aur.archlinux.org/packages/git-git), [git-fc](https://aur.archlinux.org/packages/git-fc)) (make)
   [ kcmutils ](https://archlinux.org/packages/?q=kcmutils)([kcmutils-git](https://aur.archlinux.org/packages/kcmutils-git)) (make)
   [ kdecoration ](https://archlinux.org/packages/?q=kdecoration)([kdecoration-git](https://aur.archlinux.org/packages/kdecoration-git)) (make)
   [ qt5-declarative ](https://archlinux.org/packages/?q=qt5-declarative)([qt5-declarative-git](https://aur.archlinux.org/packages/qt5-declarative-git)) (make)
   [ qt5-x11extras ](https://archlinux.org/packages/?q=qt5-x11extras)([qt5-x11extras-git](https://aur.archlinux.org/packages/qt5-x11extras-git)) (make)

### Purpose:

Lightly is a highly customizable fork of breeze theme style that aims to be visually modern and minimalistic. It can be used to get transluency on KDE.

### Benefits:

This aur package is an updated fork of the [original repo](https://github.com/Luwx/Lightly). The [udpated fork](https://github.com/boehs/Lightly) merges the open PRs from the original repo into itself and keeps the theme updated.

### Copyright:

GPL2

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Dropped because `lightly-git` switched forks.
