### ISSUE TITLE
[Bug] armcord-git package bugged

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2702]
### Packages:

[armcord-git](https://aur.archlinux.org/packages/armcord-git)

### Latest chaotic version

r943.8e43e5a-1

### What happens?

When I use ArmCord installed by Chaotic, the screenshare does not work properly, for example I don't get either the chance to choice the entire screen.

When I compile ArmCord from source (same latest commit), it works. I discussed this with ArmCord dev and maybe the Chaotic package should be rebuilt from source. Reference: https://github.com/ArmCord/ArmCord/issues/305#issuecomment-1666519706

### What is expected to happen?

Screenshare Full Screen working as the compiled from source version.

**Comment by Technetium1** [comment]
@D3vil0p3r please try it again. Unfortunately, I was unable to get a bump to work, but it's been rebuilt.

**Comment by dr460nf1r3** [comment]
> @D3vil0p3r please try it again. Unfortunately, I was unable to get a bump to work, but it's been rebuilt.

`-git` packages ignore bumps due to setting their own pkgver at build time.

**Comment by D3vil0p3r** [comment]
> > @D3vil0p3r please try it again. Unfortunately, I was unable to get a bump to work, but it's been rebuilt.
> 
> `-git` packages ignore bumps due to setting their own pkgver at build time.

I know but I'm getting a diifferent behavior between the latest package retrieved by Chaotic AUR of  `armcord-git` related to the latest commit and the one built and compiled from source (despite they should be the same). The different behavior is on the screen share:

When the user is inside a vocal chat and run a screenshare:
* Chaotic `armcord-git`: clicking on Screenshare icon, it shows two different popup windows (instead of one):
  * one popup window related to the share of the main screen
  * the other popup window related to the share of running application windows
  ![image](https://github.com/chaotic-aur/packages/assets/83867734/bad67454-d633-4b9f-819d-668a335cc33a)

* ArmCord from source files: clicking on Screenshare icon, it shows correctly one single popup window:
  ![image](https://github.com/chaotic-aur/packages/assets/83867734/3d771353-3c09-4634-85a5-de2acdc4d830)

Despite both of the versions are built on the same commit, so I guess that the AUR package is built bad (?)

**Comment by xiota** [comment]
@D3vil0p3r Could be a missing make depend.  Are you building in clean chroot?

**Comment by D3vil0p3r** [comment]
> @D3vil0p3r Could be a missing make depend. Are you building in clean chroot?

Yes, I built in clean chroot by using source files. So I guess that the PKGBUILD of AUR package is built in a wrong manner.

The GitHub repo says to build in the [this](https://github.com/ArmCord/ArmCord#compiling) manner, but the `armcord-git` [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=armcord-git) builds the package in a different manner. I guess it could be the issue.

**Comment by Technetium1** [comment]
Yes, it's installing the same deps. If it didn't, then it shouldn't be able to compile successfully at all 😖

**Comment by D3vil0p3r** [comment]
I can try to test that PKGBUILD but by using the build commands reported in the original project page.

**Comment by xiota** [comment]
I don't know enough about this package to try to fix, but different behavior is often caused by using or building with different packages.  Scripted languages often have their own package managers, virtual environment, etc that can use different versions of packages than the system has available.

**Comment by Technetium1** [comment]
It is explicitly using the same lockfile and not updating 👀
https://classic.yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-frozen-lockfile
> Don’t generate a yarn.lock lockfile and fail if an update is needed.
If you need reproducible dependencies, which is usually the case with the continuous integration systems, you should pass `--frozen-lockfile` flag.
---
Maybe this is a sign of a missed transitive dependency being added, causing the lock to be updated even when it shouldn't. Could test with and without freezing lockfile.

**Comment by D3vil0p3r** [comment]
Thank you guys. I will test directly the PKGBUILD in clean chroot with and without `--frozen-lockfile`.

**Comment by D3vil0p3r** [comment]
According to my tests, the source of the issue in the armcord-git is that the PKGBUILD leverages on the file [armcord-launcher.sh](https://aur.archlinux.org/cgit/aur.git/tree/armcord-launcher.sh?h=armcord-git) that calls `/usr/share/armcord/app.asar`.

Instead, the original building (also performed by the PKGBUILD) generates a binary file `$pkgdir/dist/linux-unpacked/armcord` that is the one that should effectively used. So, in PKGBUILD, the line
```
install -Dm 755 "armcord-launcher.sh" "$pkgdir/usr/bin/armcord"
```
should be replaced by:
```
install -Dm 755 "$pkgname/dist/"*"-unpacked/armcord" "$pkgdir/usr/bin/armcord"
```
and probably `armcord-launcher.sh` could be deleted from the source.

**Comment by Vendicated** [comment]
this has nothing to do with the package. the `armcord` binary is nothing else except renamed electron. that's how electron apps function. the multiple screenshare popups are caused by the interaction of chromium and your desktop environment. it's on your end

**Comment by xiota** [comment]
This package is currently not working.  The problem appears to be upstream (not the AUR package).  I am dropping this package because broken builds provide users with no benefit.

**Comment by D3vil0p3r** [comment]
@xiota should we package [armcord](https://aur.archlinux.org/packages/armcord) or [armcord-bin](https://aur.archlinux.org/packages/armcord-bin)?

**Comment by xiota** [comment]
`armcord-bin` was previously rejected – #2978

`aur/armcord` currently fails to build.

**Comment by xiota** [comment]
@D3vil0p3r Please test `chaotic-aur/armcord`.  If it works without problems and you're still interested in it, you may open a new request to add it.
