### ISSUE TITLE
[Outdated]  yuzu-git & yuzu-mainline-git

### ISSUE THREAD

**Issue by Nyabinary** [chaotic-aur/packages#2703]
### Packages:

[yuzu-git](https://aur.archlinux.org/packages/yuzu-git)
[yuzu-mainline-git](https://aur.archlinux.org/packages/yuzu-mainline-git)

### Latest chaotic version

r24421.ec423c691-1 & r23744.080ff0560-1

### Latest upstream version

master

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/yuzu-git.log
https://builds.garudalinux.org/repos/chaotic-aur/logs/yuzu-mainline-git.log

**Comment by xiota** [comment]
The PKGBUILD of both packages need to be updated by their respective maintainers.

**Comment by xiota** [comment]
Maintainers MIA for about three months.  Fixed `yuzu-git` with interfere, and opened orphan request.
