### ISSUE TITLE
[Remove] telegram-tg-git

### ISSUE THREAD

**Issue by izmyname** [chaotic-aur/packages#2704]
### Package:

https://aur.archlinux.org/packages/telegram-tg-git

### Purpose:

Command-line telegram client written in ncurses

### Benefits:

It's a telegram client written in ncurses interface, easy to integrate with ranger, nnn, vim/neovim for writing long messages, also supports voice messages etc.

### License:

Unlicense

**Comment by xiota** [comment]
This package hasn't been updated in a few years.  Is there any benefit to keeping it over switching to `aur/nchat-git`?

Metrics 23.

**Comment by Technetium1** [comment]
I don't see a benefit to keeping, especially with upstream being dormant
