### ISSUE TITLE
[Request] linux-libre

### ISSUE THREAD

**Issue by edo0** [chaotic-aur/packages#2705]
### Package:

Linux-libre

https://aur.archlinux.org/packages/linux-libre

### Purpose:

I believe it would be very useful to provide a precompiled version of the Libre kernel

### Benefits:

This is a stripped down version of the Linux Kernel, devoid of all proprietary blobs but very resource-intensive to compile

### Copyright:

GPL2

### Expected Interest:

Some

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

### More information:

Available in the Aur, but not as prebuilt binaries

**Comment by Technetium1** [comment]
@dr460nf1r3 does this belong in toolbox?

**Comment by dr460nf1r3** [comment]
No, this is a regular AUR package from what I can tell, so package lists it is :)

**Comment by Technetium1** [comment]
It will be added when it's no longer outdated.

**Comment by xiota** [comment]
I'm inclined to reject this.  Building kernels is resource intensive, and those who really want to use a "libre" kernel are likely to object to using chaotic-aur at all.  Prebuilt libre kernel and other packages are available through https://www.parabola.nu/

**Comment by dr460nf1r3** [comment]
Fine by me.
