### ISSUE TITLE
[Request] zsh-vi-mode

### ISSUE THREAD

**Issue by guiltiest-gear** [chaotic-aur/packages#2706]
### Package:

[zsh-vi-mode](https://aur.archlinux.org/packages/zsh-vi-mode)

### Purpose:

This package improves the vi mode for zsh, like reducing response times, a custom exit key, text objects, and so on.

### Benefits:

The default vi mode for zsh is passable, but is lacking a lot of features and isn't the best experience overall, this package solves those problems and improves the vi mode experience for zsh.

### Copyright:

MIT

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
Currently flagged out of date, we will wait until it's not.

**Comment by guiltiest-gear** [comment]
Finally has been updated to latest version, should be good to go now
