### ISSUE TITLE
[Request] xdg-terminal-exec-git

### ISSUE THREAD

**Issue by REmerald** [chaotic-aur/packages#2707]
### Package:

[xdg-terminal-exec-git](https://aur.archlinux.org/pkgbase/xdg-terminal-exec-git)

### Purpose:

Set any default terminal you want for `Terminal=true` desktop entries.

This lets you launch e.g. `vim.desktop` on `alacritty` without any pain :smiley:.  
Without this package you can't do it so easily, because [the terminal list is hardcoded](https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gdesktopappinfo.c#L2701).

### Benefits:

Now you don't have to do e.g. `ln -s /usr/bin/alacritty /usr/local/bin/tilix`.

### Building:

paru :upside_down_face:

### Copyright:

GPL3

### Expected Interest:

Most

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Needs to be configured before it can be used (see its [README.md](https://github.com/Vladimir-csp/xdg-terminal-exec/blob/master/README.md), although it doesn't explain very clearly what exactly you need to do).

Firstly, you need to provide a list of terminals in one of the listed file locations:
`cat /etc/xdg/xdg-terminals.list`
```
Alacritty.desktop
```
And create the desktop file with a few keys in one of the listed directory locations for the each terminal. Or you can just create a link if your terminal uses `-e`:
`ls -l /usr/local/share/xdg-terminals/`
```
Alacritty.desktop -> /usr/share/applications/Alacritty.desktop
```

**Comment by xiota** [comment]
This looks interesting.  I'll take a look at it.
