### ISSUE TITLE
[Remove] ant-dracula-kde-theme-git ant-dracula-kvantum-theme-git ant-dracula-theme-git dracula-cursors-git

### ISSUE THREAD

**Issue by BL4CKH47H4CK3R** [chaotic-aur/packages#2709]
### Packages:

**Remove (Orphaned)**
[ant-dracula-kde-theme-git](https://aur.archlinux.org/packages/ant-dracula-kde-theme-git)
[ant-dracula-kvantum-theme-git](https://aur.archlinux.org/packages/ant-dracula-kvantum-theme-git)
[ant-dracula-theme-git](https://aur.archlinux.org/packages/ant-dracula-theme-git)
[dracula-cursors-git](https://aur.archlinux.org/packages/dracula-cursors-git)

**Add**
[dracula-kde-theme-git](https://aur.archlinux.org/packages/dracula-kde-theme-git)

### Latest chaotic version

`v4.0.0.r22.g954f86d`

### Latest upstream version

`r322.954f86d`

### More information

[dracula-kde-theme-git](https://aur.archlinux.org/packages/dracula-kde-theme-git) contains all the components which are offered in other multiple packages which is needed to be removed.

ant-dracula-kde-theme-git
ant-dracula-kvantum-theme-git
ant-dracula-theme-git
dracula-cursors-git

**Comment by dr460nf1r3** [comment]
Some Garuda editions possibly use this, so we need to check this first before removing it.

**Comment by BL4CKH47H4CK3R** [comment]
> Some Garuda editions possibly use this, so we need to check this first before removing it.

I tried to check all the possible components that those packages are meant to be. You are most welcome to proceed!
