### ISSUE TITLE
[issue] visual-studio-code-insiders should be built daily

### ISSUE THREAD

**Issue by timescam** [chaotic-aur/packages#271]
[visual-studio-code-insiders](https://aur.archlinux.org/packages/visual-studio-code-insiders/) should be built daily, similar to a VCS package, currently it is stuck at the july update.
As the maintainer stated on the aur page: 
> IMPORTANT: This package always installs the latest insider build (see pkgver() function), so if you want daily updates, just run "makepkg -si" everyday and it will update. I won't be updating pkgver every single day.

Thank you in advance.

**Comment by PedroHLC** [comment]
Ok, I've added it to the schedules yesterday, and it built today at `2020-08-25 06:54`
