### ISSUE TITLE
[Request] hardened_malloc

### ISSUE THREAD

**Issue by Sir-Photch** [chaotic-aur/packages#2710]
### Package:

[hardened_malloc](https://aur.archlinux.org/packages/hardened_malloc/)

### Purpose:

Hardened malloc from [GrapheneOS](https://github.com/GrapheneOS/hardened_malloc) that can be used with `LD_PRELOAD` or in `/etc/ld.so.preload`.

### Benefits:

Security benefits. See the [wiki](https://wiki.archlinux.org/title/Security#Hardened_malloc) for the respective entry.

### Building:

Build checks the signature of the dev of hardened_malloc, I am not sure if it can be kept when this is built on chaotic-aur?

### Copyright:

MIT

### Expected Interest:

Some

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Dropping because fails to build and doesn't seem inherently useful.  Metrics 12.
