### ISSUE TITLE
[Request] lazarus-beta

### ISSUE THREAD

**Issue by benjamimgois** [chaotic-aur/packages#2711]
### Package:

[lazarus-beta](https://aur.archlinux.org/pkgbase/lazarus-beta)

Dependencies:
[qt6pas](https://aur.archlinux.org/packages/qt6pas)

### Purpose:

It provides access to the latest testing release of Lazarus IDE

### Benefits:

Helps testing the latest Lazarus version before official release. Also bring early access to new features and toolkits

### Building:

 build in clean chroot

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

This package would make a lot easier to access the latest lazarus release

**Comment by FabioLolix** [comment]
Hello, would you like to edit the title to use `lazarus-beta` instead of `packagename`

btw both qt6pas and this build in clean chroot

**Comment by benjamimgois** [comment]
Sorry @FabioLolix , already fixed

**Comment by xiota** [comment]
What new features?  How frequently does this project produce releases?

**Comment by benjamimgois** [comment]
Lots of bug fixes, newer UI, support to QT6, GTK3 and IOS. There're feel "stable" releases, maybe 1 or 2 every year. But the project is very active with commits made in a daily bases.

**Comment by xiota** [comment]
This is a pkgbase with subpackage names that may conflict with future `extra/lazarus` subpackages.  I've asked the maintainer to rename them.

**Comment by Technetium1** [comment]
While we wait for the maintainer to respond, we can at least make the dependency available.

**Comment by xiota** [comment]
Also noticed that the package has inappropriate replaces (overrides `extra/lazarus`).  Have asked maintainer to remove them.

**Comment by xiota** [comment]
@benjamimgois A build of `lazarus-beta` available.  Please test and report back whether it works as expected.  Also, if possible, please test `lazarus-git`.  Thank you.

**Comment by benjamimgois** [comment]
Hi @xiota , will test as soon as i got home.

**Comment by benjamimgois** [comment]
I just tried lazarus-beta and lazarus-git. It seems there's a problem with `qt6pas`, since it's a dependency and the system  can't find the target, even if the package exist in chaotic.


`Erro: Falha ao preparar transação: alvo não encontrado: qt6pas
`

**Comment by xiota** [comment]
@benjamimgois The maintainer didn't fix all of the issues with `lazarus-beta`.  I've removed the broken builds.  Will try again when it's updated.

Is that a `pacman` error with `qt6pas`?  It is downloading and installing fine on my end.

**Comment by benjamimgois** [comment]
@xiota something was wrong in my system yesterday. I just made a new test in another machine here, it works fine indeed. Thanks a lot

**Comment by xiota** [comment]
@benjamimgois `lazarus-beta` available for testing.  It installs fine on my computer, but the program I tried building fails because of what looks like language changes in the new version.

**Comment by benjamimgois** [comment]
@xiota indeed, lazarus-beta works now. Indeed some of my projects doesn't compile yet, but it might be changes in the software itself. Thank you for your hard work on this package.

**Comment by xiota** [comment]
The -beta package isn't quite ready for full inclusion yet.  Will continue monitoring.

**Comment by xiota** [comment]
lazarus 3.0 release, including gtk3 and qt6, are now in `extra.  Is `lazarus-beta` still wanted?

**Comment by Technetium1** [comment]
If there's no explicit want, it could be dropped now.

**Comment by benjamimgois** [comment]
Well, i think it isn't necessary  until the new lazarus beta came out.

**Comment by xiota** [comment]
@benjamimgois Did `lazarus-beta` ever work for you?  When I tried building a project with `lazarus-beta` 3.0.0 it fails because of some error related to "inline" ¿functions?.  But the same project completes successfully with `extra/lazarus` 3.0.  Seems the error in `-beta` is treated as a warning?  I didn't find anything in the PKGBUILD to explain it.
