### ISSUE TITLE
[Remove] timeshift

### ISSUE THREAD

**Issue by guiltiest-gear** [chaotic-aur/packages#2713]
### Packages:

N/A*

*Package is no longer available in AUR, so I'll link the page for the official place in the extra repo

[https://archlinux.org/packages/extra/x86_64/timeshift/](https://archlinux.org/packages/extra/x86_64/timeshift/)

### Latest chaotic version

23.07.1-1

### Latest upstream version

23.07.1-2

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/timeshift.log

### More information

timeshift has been moved to the official extra repo, so there's no purpose in keeping it in this repo

**Comment by xiota** [comment]
I occasionally check for and remove packages that are no longer in the AUR.

You can request removals by commenting on an old issue related to the package, like the original request or a rebuild request.  This way people who had previously shown interest in the package can receive a notification about the change in status.

**Comment by guiltiest-gear** [comment]
@xiota Noted for future reference, thank you.
