### ISSUE TITLE
[Request] rtx

### ISSUE THREAD

**Issue by joe733** [chaotic-aur/packages#2714]
### Package:

[rtx](https://aur.archlinux.org/packages/rtx)

### Purpose:

RunTime eXecution

### Benefits:

Much faster alternative to `asdf`

### Building:

```console
$ CHROOT=$HOME/chroot
$ mkdir $CHROOT
$ mkarchroot $CHROOT/root base-devel
$ arch-nspawn $CHROOT/root pacman -Syu
```

```console
$ git clone "https://aur.archlinux.org/rtx.git"
$ cd a2ln
$ makechrootpkg -c -r $CHROOT
```

### Copyright:

MIT

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Dropping because upstream is rebranding, and this package is deprecated.
