### ISSUE TITLE
[Rebuild] alvr

### ISSUE THREAD

**Issue by un-simp** [chaotic-aur/packages#2715]
### Packages:

[ALVR](https://aur.archlinux.org/packages/alvr)

### Latest chaotic version

9.1.0.r0.g969899c7-1

### Reason for rebuild

Outdated

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/alvr.log

### Builds?

makepkg

**Comment by Technetium1** [comment]
I don't think the build failing here is our fault 😕

**Comment by xiota** [comment]
Successful rebuild.  [alvr.log](https://github.com/chaotic-aur/packages/files/13163694/alvr.log)

**Comment by Edu4rdSHL** [comment]
Yep, feel free to add it again!
