### ISSUE TITLE
[Request] radarr

### ISSUE THREAD

**Issue by segalll** [chaotic-aur/packages#2716]
### Package:

[radarr](https://aur.archlinux.org/packages/radarr)

### Purpose:

Movie download automation for usenet and torrents. Like sonarr from #1125 but for movies.

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
There is a test build of `radarr` in repository now.  Please test it to see if it works.  Also, please test `bazarr-git` and comment at #2731 whether it works.  Thank you.

**Comment by segalll** [comment]
Radarr is working great!
