### ISSUE TITLE
[Request] jellyseerr

### ISSUE THREAD

**Issue by segalll** [chaotic-aur/packages#2717]
### Package:

[jellyseerr](https://aur.archlinux.org/packages/jellyseerr)

### Purpose:

Request management and media discovery tool for the Plex/Jellyfin ecosystem

### Copyright:

MIT

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Has optdep on nonexistent package.

**Comment by segalll** [comment]
The optdep was removed.

**Comment by xiota** [comment]
@segalll I assume that is your orphan request on the package?  If there are no other issues with the package, you should cancel it because the maintainer has updated.

**Comment by segalll** [comment]
@xiota Yep, cancelling the request.

**Comment by segalll** [comment]
Sorry for the delay, request is cancelled now.

**Comment by xiota** [comment]
@segalll `jellyseerr` is built and available in the repo.  Sometimes `npm` / `nodejs` / `yarn` builds dysfunctional packages.  Please let me know whether it's working before I add it to the package lists.

**Comment by segalll** [comment]
Looks like it's working. Thanks so much!

**Comment by xiota** [comment]
Dropping because upstream rebranded to seerr.  Metrics 22.
