### ISSUE TITLE
[Request] sabnzbd

### ISSUE THREAD

**Issue by segalll** [chaotic-aur/packages#2718]
### Package:

https://aur.archlinux.org/packages/sabnzbd

Depends:
https://aur.archlinux.org/packages/python-sabctools
https://aur.archlinux.org/packages/python-sabyenc3

### Purpose:

A web-interface based binary newsgrabber with NZB file support. Useful in the servarr stack.

### Copyright:

GPL2/3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by segalll** [comment]
Is there anything that needs to be done for this?

**Comment by Technetium1** [comment]
No, just need to be less busy 😅
