### ISSUE TITLE
[Request] VMWare Horizon Client

### ISSUE THREAD

**Issue by RuthlessRuler** [chaotic-aur/packages#2719]
### Package:

[vmware-horizon-client](https://aur.archlinux.org/pkgbase/vmware-horizon-client)

### Purpose:

Helps to connect to remote Desktops available via VMWare platform.

### Copyright:

https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/docs/vmw-horizon-pricing-and-packaging-whitepaper.pdf

### Expected Interest:

Some

### Already available?

No

### Unique request?

No

### Banned package?

No

**Comment by FabioLolix** [comment]
This require vmware-keymaps https://aur.archlinux.org/packages/vmware-keymaps (real license is public domain)

vmware-horizon-client is a splitted pkgbuild and don't install any license, source archive lack any license regarding the programs

**Comment by xiota** [comment]
Dropped because deprecated after transfer of EUC from Broadcom to KKR to become an independent entity.  Metrics 172.
