### ISSUE TITLE
[Rebuild] ungoogled-chromium

### ISSUE THREAD

**Issue by HeroesLament** [chaotic-aur/packages#2720]
### Packages:

[ungoogled-chromium](https://aur.archlinux.org/packages/ungoogled-chromium)

### Latest chaotic version

115.0.5790.170-1

### Reason for rebuild

re2 package has updated the library version

```user@computer$ chromium
/usr/lib/chromium/chromium: error while loading shared libraries: libre2.so.10: cannot open shared object file: No such file or directory
```

**Comment by xiota** [comment]
I bumped this and a few other packages that depend on `re2`.  Will check in a couple days whether they build successfully.

**Comment by HeroesLament** [comment]
> I bumped this and a few other packages that depend on `re2`. Will check in a couple days whether they build successfully.

Thank you!!

**Comment by xiota** [comment]
Looks like rebuild succeeded...
```
$ pacman -Sii ungoogled-chromium | grep Date
Build Date      : Thu Aug 17 03:15:14 2023
```

[ungoogled-chromium.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/ungoogled-chromium.log) is 132MB !?
```
ungoogled-chromium.log	2023-08-17 12:00	132.2M 	File
```
