### ISSUE TITLE
[Request] scli-git

### ISSUE THREAD

**Issue by dreirund** [chaotic-aur/packages#2721]
### Package:

* [`scli-git`](https://aur.archlinux.org/packages/scli-git)
* [`signal-cli`](https://aur.archlinux.org/packages/signal-cli)
* [`libsignal-client`](https://aur.archlinux.org/packages/libsignal-client)

### Purpose:

`signal-cli` is the "de-facto" command line client to use when someone wants to register with the Signal messaging system but does not have a smartphone.

Signal is a widespread end to end encrypted messaging system.

`libsignal-client` is a dependency for `signal-cli` and many other signal clients.

`sscli-git` is a more easy to use command line client, building on top of `signal-cli`.

The dependency chain is:

`sscli-git` &rarr; `signal-cli` &rarr; `libsignal-client`.

### Benefits:

* Have a general client and needed library for the widespread Signal messaging protocol available.

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
> It is needed for many third-party signal... clients.

Examples?  Are any of them in chaotic or candidates for inclusion in chaotic?

**Comment by dreirund** [comment]
> > It is needed for many third-party signal... clients.
> 
> Examples? Are any of them in chaotic or candidates for inclusion in chaotic?

Not yet; [`signal-cli`](https://aur.archlinux.org/packages/signal-cli) is the common signal command line interface, [`scli-git`](https://aur.archlinux.org/packages/scli-git) a wrapper around `signal-cli`, that would be a subsequent request to add but can only be done after `libsignal-client` has been included, so I did not add a request for those package(s).

But if you want, enhance this package request already now by [`signal-cli`](https://aur.archlinux.org/packages/signal-cli)!

**Comment by xiota** [comment]
@dreirund  Would appreciate if you could edit this request to add `signal-cli` or whatever client you would prefer.  The dependency would tag along under the same request.  This way, we avoid adding useless packages to the repositories.

**Comment by dreirund** [comment]
> ***@Technetium1** closed this as [completed](https://github.com/chaotic-aur/packages/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/chaotic-aur/packages/commit/9a584c5522194c281d7913bd7bff2ab6ff2a1f98 1 hour ago*

:pray:

**Comment by xiota** [comment]
Planning to drop for maintenance issues.  Metrics:

2 scli-git
9 signal-cli
8 libsignal-client

**Comment by xiota** [comment]
Dropping because packages still fail to build and no response to previous comment.

* `scli-git` fails to build because `signal-cli` fails to build.
* `signal-cli` fails to build because `libsignal-client` fails to build.
* `libsignal-client` fails to build because of gradle/java problem.
