### ISSUE TITLE
[Request] cht.sh-git

### ISSUE THREAD

**Issue by guiltiest-gear** [chaotic-aur/packages#2722]
### Package:

[cht.sh-git](https://aur.archlinux.org/packages/cht.sh-git)

### Purpose:

This package is a convenient way of accessing cheat.sh, a very powerful cheat sheet for commands, especially noting the tab completion feature, instead of using `curl cht.sh`.

### Benefits:

The cht.sh client is far more user friendly and convient than just only using the curl command to access cheat.sh, especially since I use the client on a daily basis, it's just a very useful tool to have on hand.

### Copyright:

MIT

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
Upstream has been abandoned :(
