### ISSUE TITLE
[Request] packagename

### ISSUE THREAD

**Issue by bphd** [chaotic-aur/packages#2727]
### Package:

armorpaint-git, bazarr, bazarr-git, binder_linux-dkms, chromium-widevine, deezloader-remix-git, java11-openjfx, lib32-qt4, linux-binder, linux-binder-docs, mtkclient-git, obs-replay-source, pamac-all, python-fakewebcam, python-m2r2, qbittorrent-enhanced-ua, sonarrannounced-git, vala0.54, wayfarer-git, wshowkeys-git, ycmd-git, yin-yang

### Purpose:

Reduce compile time, allowing ressources to be available

### Copyright:

GPL3

### Expected Interest:

Everyone

### Already available?

Yes

### Unique request?

No

### Banned package?

No

**Comment by FabioLolix** [comment]
> chromium-widevine

unredestributable

> lib32-qt4

Deprecated, don't build

> pamac-all

need snapd which is in the rejected packages

> python2-lxml

python2 packages are rejected

```
Banned package?

No
```

```
Is this package banned?
Do not answer without checking first.
https://github.com/chaotic-aur/packages#banished-and-rejected-packages-
```

**Comment by bphd** [comment]
> > chromium-widevine
> 
> unredestributable
> 
> > lib32-qt4
> 
> Deprecated, don't build
> 
> > pamac-all
> 
> need snapd which is in the rejected packages
> 
> > python2-lxml
> 
> python2 packages are rejected
> 
> ```
> Banned package?
> 
> No
> ```
> 
> ```
> Is this package banned?
> Do not answer without checking first.
> https://github.com/chaotic-aur/packages#banished-and-rejected-packages-
> ```

pamac-all is not directly banned, it's all about deps

**Comment by FabioLolix** [comment]
> pamac-all is not directly banned, it's all about deps

From the top of the request issue


> Package:
> Link to the package base in the AUR. Include any known AUR dependencies.

**Comment by xiota** [comment]
@bphd  You are free to open legitimate issues and requests, but please stop "trolling".  Requesting that *all* packages be added (#2726) or large numbers of packages that are already in chaotic, already requested, or previously banned is unacceptable.

Each package request *must*:
* Primarily request a single package and its dependencies.  The package *must not* already be in chaotic, been previously requested, or been previously banned.
* Describe the package's purpose, primary use case.
* Be filled out as accurately as you are able.

**Comment by bphd** [comment]
> > pamac-all is not directly banned, it's all about deps
> 
> From the top of the request issue
> 
> > Package:
> > Link to the package base in the AUR. Include any known AUR dependencies.

Because it was multiple packages, I feared that pasting them all on one field will make them buggy

**Comment by bphd** [comment]
> @bphd You are free to open legitimate issues and requests, but please stop "trolling". Requesting _all_ AUR packages (#2726) or large numbers of packages that are already in chaotic, already requested, or previously banned is unacceptable.
> 
> Each package request _must_:
> 
>     * Primarily request a single package and its dependencies.  The package _must not_ already be in chaotic, been previously requested, or been previously banned.  This includes its dependencies.
> 
>     * Describe the package's purpose, primary use case.
> 
>     * Be filled out as accurately as you are able, including the title.

It's not trolling, I need those packages, you can go verify, it's packages that takes a lot of time to compile

You talk about another legitimate request to close that one that is legitimate too. It's personal attack?

The vast majority of what I've asked is okay, it's only about pamac and it's okay if it's not done, the other one still are useful. What is the problem?

I can reformulate the demand if you want, with those informations, but that will not change the need to have them, it's jsut more time consumed for the same package needs. If it's really necessary to add publicly available informations into a request that nobody will read after the decision, so will it be

**Comment by bphd** [comment]
### Package:

Real useful information

### Purpose:

duckduckgo dot com slash search package name description 

### Benefits:

duckduckgo dot com slash search package name description 

Chaotic dot cx slash about

### Building:

aur dot archlinux dot org slash package name slash pkgbuild

### Copyright:

aur dot archlinux dot org slash package name

### Expected Interest:

trends dot google dot com slash package name

### Already available?

github dot com slash chaotic aur slash package list
aur dot archlinux dot org slash package name

### Unique request?

github dot com slash chaotic aur slash issues slash search package name

### Banned package?

github dot com slash chaotic aur slash readme

### More information:

Web usage

**Comment by xiota** [comment]
> I can reformulate the demand

You may make *requests*, not demands.  This is a *privilege*, not a right.

> it's jsut more time consumed

If you are not willing to take the time to formulate proper *requests*, why should the maintainers' take the time to evaluate and add the packages?

@FabioLolix has already explained why some of the packages you requested are not appropriate.  Further, the following packages are already in chaotic: armorpaint-git, binder_linux-dkms, chromium-widevine, linux-binder, linux-binder-docs, yin-yang-git.

> publicly available informations into a request that nobody will read after the decision

The information helps maintainers evaluate packages from the initial request and when there are issues in the future.

> Package: Real useful information  
> Purpose: duckduckgo dot com slash search package name description  
> ...

Again, I urge you to create proper requests with the form filled out correctly.

**Comment by bphd** [comment]
> requests

English is not my native language. In my language both words imply the liberty of reply or not, like the request that you describe 

> willing

It's not about taking time, I'm already taking some with that topic since the beginning, it's about efficiency. If informations are publicly available, not really useful for the request and not at all after the request, it's maybe not useful to retrieve it to begin with. Maybe if you want to filter out issues, you can ask to post only after we're sure it respect the rules, or maybe make a form that open the issue only if answered right

> not appropriate

I have no problem if some package can't be or already been. I ask only for the ones that maintainer want to. I just make a list of what I believe could be useful. It's not mandatory to take them all

> helps maintainers

A script with the links I gave replaced with a $variable could do the same, maybe it's even possible to prefill the form with those links and the package name to complete the URL. the information would've even been more up to date

> create proper requests

I already said I will. I just reply globally that I don't understand all the attacks and the lack of optimization in the process. I just came here to know more about the project and to request for some packages. The discussion would have been really shorter and more efficient if you just have taken the valid packages to submission and giving the status of integration of them into the repo. Maybe with a short explanation why they can't all been took, but not much more
