### ISSUE TITLE
[Request] gnome-shell-extension-material-shell

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2728]
### Package:

[gnome-shell-extension-material-shell](https://aur.archlinux.org/packages/gnome-shell-extension-material-shell)

### Purpose:

Modern desktop interface for GNOME Shell

non-git version. git version is already packaged: https://github.com/chaotic-aur/packages/issues/463

### Benefits:

Improve your user experience and get rid of the anarchy of traditional desktop workflows. Designed to simplify navigation and reduce the need to manipulate windows in order to improve productivity. It's meant to be 100% predictable and bring the benefits of tools coveted by professionals to everyone.

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
Build fails: [gnome-shell-extension-material-shell.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/gnome-shell-extension-material-shell.log)

**Comment by D3vil0p3r** [comment]
I'm not getting any error during the build.

**Comment by Technetium1** [comment]
@D3vil0p3r is it in clean chroot by chance? Take a look at the incorrect path in my above link.

**Comment by D3vil0p3r** [comment]
> @D3vil0p3r is it in clean chroot by chance? Take a look at the incorrect path in my above link.

Yes, in clean chroot:
```
==> Extracting sources...
  -> Extracting gnome-shell-extension-material-shell-44.tar.gz with bsdtar
==> Starting build()...

added 222 packages, and audited 223 packages in 8s

30 packages are looking for funding
  run `npm fund` for details

2 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
npm notice 
npm notice New major version of npm available! 9.8.1 -> 10.0.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.0.0>
npm notice Run `npm install -g npm@10.0.0` to update!
npm notice 
rm -rf dist
mkdir dist
cp -r schemas dist
glib-compile-schemas dist/schemas/
npx sass --no-source-map src/styles/dark-theme.scss dist/style-dark-theme.css
npm notice 
npm notice New major version of npm available! 9.8.1 -> 10.0.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.0.0>
npm notice Run `npm install -g npm@10.0.0` to update!
npm notice 
npx sass --no-source-map src/styles/light-theme.scss dist/style-light-theme.css
npx sass --no-source-map src/styles/primary-theme.scss dist/style-primary-theme.css
make: git: No such file or directory
npx tsc
npx tsc scripts/transpile.ts --outDir build && node build/transpile.js
npm run rollup-extension && npm run rollup-prefs

> material-shell@1.0.0 rollup-extension
> npx rollup -c rollup.config.js -i build/extension.js  -o dist/extension.js


build/extension.js → dist/extension.js...
created dist/extension.js in 661ms

> material-shell@1.0.0 rollup-prefs
> npx rollup -c rollup.config.prefs.js -i build/prefs/prefs.js  -o dist/prefs.js

/build/gnome-shell-extension-material-shell/src/material-shell-44/build

build/prefs/prefs.js → dist/prefs.js...
created dist/prefs.js in 120ms
sed "s/{put_commit_there}//" metadata.json > dist/metadata.json
cp -r assets dist/assets
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "gnome-shell-extension-material-shell"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: gnome-shell-extension-material-shell 44-1 (Mon Sep  4 22:19:50 2023)
```

**Comment by Technetium1** [comment]
New problem:
```
Downloading: gnome-shell-extension-material-shell
Trying to make directory...
Finished preparing gnome-shell-extension-material-shell.
Starting making gnome-shell-extension-material-shell at Tue Sep  5 02:48:53 CEST 2023
Building package "gnome-shell-extension-material-shell"
execv(/home/main-builder/wizard.sh) failed: No such file or directory
```

**Comment by D3vil0p3r** [comment]
Why am I not getting that issue in clean chroot?

**Comment by dr460nf1r3** [comment]
This was related to a not created lowerdir, it's fixed now though.

**Comment by Technetium1** [comment]
It gets hung up here:
https://github.com/material-shell/material-shell/blob/89f460b3717a541082f5b87b514f7cc23e3ea170/Makefile#L23

**Comment by D3vil0p3r** [comment]
> It gets hung up here: https://github.com/material-shell/material-shell/blob/89f460b3717a541082f5b87b514f7cc23e3ea170/Makefile#L23

We need to open a PR or Issue on their side?

**Comment by Technetium1** [comment]
Maybe pkgbuild issue... @xiota thoughts?
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gnome-shell-extension-material-shell
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gnome-shell-extension-material-shell-git

**Comment by xiota** [comment]
Thought: Banish `npm` packages.

Nothing stands out to me in the PKGBUILD.  I have the same error building in clean chroot locally.  Looks like instructions are being run out of order.

In [Makefile](https://github.com/material-shell/material-shell/blob/89f460b3717a541082f5b87b514f7cc23e3ea170/Makefile), lines 22-23:
```
rm -rf dist
mkdir dist
```

And lines 7-8:
```
cp -r schemas dist
glib-compile-schemas dist/schemas/
```

But from the log, it looks like it's running 22, 7, 23, 8, ...
```
rm -rf dist
cp -r schemas dist
mkdir dist
glib-compile-schemas dist/schemas/
mkdir: cannot create directory ‘dist’: File exists
make: *** [Makefile:23: dist] Error 1
make: *** Waiting for unfinished jobs....
Error opening directory “dist/schemas/”: No such file or directory
make: *** [Makefile:8: schemas] Error 1
```

**Comment by xiota** [comment]
Adding `export MAKEFLAGS='-j1'` to `build()` allows this to build.  Is this package worth adding an interfere?

**Comment by dr460nf1r3** [comment]
If it allows building, definitely 👀

**Comment by xiota** [comment]
Putting `export MAKEFLAGS=...` in `prepare` script doesn't work.  `gnome-shell-extension-material-shell-git` has same problem; adding interfere.

**Comment by xiota** [comment]
Dropped because no longer in AUR.  Metrics 15.

**Comment by D3vil0p3r** [comment]
> Dropped because no longer in AUR.  Metrics 15.

Also its `-git` package has been dropped?

**Comment by xiota** [comment]
Both stable and git packages were removed from AUR for reason, "Upstream is EOL...  Not compatible with Gnome Shell 47+."

**Comment by D3vil0p3r** [comment]
Thank you very much @xiota
