### ISSUE TITLE
[Request] ame

### ISSUE THREAD

**Issue by mdhishamsayed** [chaotic-aur/packages#2729]
### Package:

[ame](https://aur.archlinux.org/packages/ame)

### Purpose:

Amethyst is a fast and efficient AUR helper

### Benefits:

It is a new kinda package manager and aur helper made in rust.

### Building:

no special procedures

### Copyright:

GPL3

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Dropping because not functional and fails to build.  Requires previous version of libalpm.  No upstream activity since Sep 2024.

Someone reported Crystal Linux is EOL, but I'm not able to definitively confirm status.

Metrics 11.
