### ISSUE TITLE
openmw-git doesn't work with openscenegraph-openmw-git

### ISSUE THREAD

**Issue by rtentser** [chaotic-aur/packages#273]
> openmw: error while loading shared libraries: libosg.so.161: cannot open shared object file: No such file or directory

[openscenegraph-openmw-git](https://aur.archlinux.org/packages/openscenegraph-openmw-git) is an openscenegraph version with optimizations for openmw.

openmw-git should be build with it (i guess). I've built aur package, it works.

Please add openscenegraph-openmw-git to repository and provide alternative openmw-git.

**Comment by PedroHLC** [comment]
Sorry for the late response.
I've added `openscenegraph-openmw-git`. Does it work for you?

**Comment by rtentser** [comment]
```
$ openmw
openmw: error while loading shared libraries: libosg.so.161: cannot open shared object file: No such file or directory
```

You should build `openmw-git` with `openscenegraph-openmw-git`. Or probably two of them: one with original `openscenegraph` (which is `openmw-git` now) and another with optimized one.

**Comment by rtentser** [comment]
`openscenegraph-openmw-git` works. I've built `openmw-git` with it, works fine.

**Comment by rtentser** [comment]
> openscenegraph-openmw-git

Why does it updated everyday? There is no upstream updates.

**Comment by PedroHLC** [comment]
Because package maintainer in AUR didn't followed ArchWiki guidelines and invented his own pkgver...
Please request him to change it to something like `${ver_tag}-r${commit_num}-g${commit_has}`, or follow the ArchWIki!

PS: I'll eventually do the change you requested to `openmw-git`

**Comment by mupfelofen-de** [comment]
I fixed it. Please let me know if there are any problems left.

**Comment by rtentser** [comment]
@mupfelofen-de 

```
==> Starting pkgver()...
/home/kravensky/Sources/AUR/openscenegraph-openmw-git/PKGBUILD: line 19: cd: openscenegraph-openmw-git: No such file or directory
==> ERROR: A failure occurred in pkgver().
    Aborting...
```

**Comment by rtentser** [comment]
You need to change `cd "$pkgname"` in `pkgver ()` to `cd "osg"` because repository name doesn't match package name.

**Comment by mupfelofen-de** [comment]
I changed it to ${gitname}. Sorry about that. Please try again. Unfortunately I can't test it myself.

**Comment by rtentser** [comment]
> openscenegraph-openmw-git-r3.6c2b570-1

Why it's uses pkgbuild's commit instead of upstream?

**Comment by rtentser** [comment]
I've used example from [ArchWiki](https://wiki.archlinux.org/index.php/VCS_package_guidelines#The_pkgver.28.29_function) and get `openscenegraph-openmw-git-OpenSceneGraph.3.4.1.r106.g8b07809fa-1` package. But it didn't work with ${gitname}.

**Comment by rtentser** [comment]
`git describe --long | sed 's/^OpenSceneGraph-//;s/\([^-]*-g\)/r\1/;s/-/./g'` produces `3.4.1.r106.g8b07809fa` pkgver. I think, it's perfect.

**Comment by mupfelofen-de** [comment]
Adjusted it as suggested. Please give it a try.

**Comment by rtentser** [comment]
Works fine. Thanks!

**Comment by mupfelofen-de** [comment]
I'm glad it works again. Thanks for the quick response.

**Comment by rtentser** [comment]
@PedroHLC 
Pacman still tries to update to old version number (20200908-1).

**Comment by PedroHLC** [comment]
Done
