### ISSUE TITLE
[Request] bazarr

### ISSUE THREAD

**Issue by bphd** [chaotic-aur/packages#2730]
## Package: bazarr

**Package:** [bazarr](https://aur.archlinux.org/packages/bazarr)
**Purpose:** Bazarr is a companion application to Sonarr and Radarr. It manages and downloads subtitles based on your requirements. It can be used to automatically download and manage subtitles for your TV shows and movies.
**Benefits:** This package offers seamless integration with Sonarr and Radarr, enhancing the media management experience by automating the subtitle downloading process.
**Building:** To build the bazarr package, follow these steps in a clean chroot:
```shell
git clone https://aur.archlinux.org/bazarr.git
cd bazarr
makepkg -si
```
**Copyright:** GPL3 - [GNU General Public License v3](https://www.gnu.org/licenses/gpl-3.0.en.html)
**Expected Interest:** Moderate interest, especially among users of Sonarr and Radarr.
**Already available?** Available on AUR but not on Chaotic AUR.
**Unique request?** Yes, this request is unique and not available on Chaotic AUR.
**Banned package?** Not a banned package.
**More information:** Bazarr enhances media management by automatically downloading and managing subtitles for TV shows and movies, integrating seamlessly with Sonarr and Radarr.

**Comment by xiota** [comment]
Combining with #2731.
