### ISSUE TITLE
[Request] bazarr, bazarr-git

### ISSUE THREAD

**Issue by bphd** [chaotic-aur/packages#2731]
**Package:**

[bazarr](https://aur.archlinux.org/packages/bazarr)
[bazarr-git](https://aur.archlinux.org/packages/bazarr-git)

**Purpose:**

Bazarr is a companion application to Sonarr and Radarr. It manages and downloads subtitles based on your requirements. It can be used to automatically download and manage subtitles for your TV shows and movies.

**Benefits:**

n/a

**Building:**

n/a

**Copyright:**

GPL3

**Expected Interest:**

Some

**Already available?**

No

**Unique request?**

Yes

**Banned package?**

No

**More information:**

n/a

**Comment by xiota** [comment]
In addition to https://github.com/chaotic-aur/packages/issues/2732#issuecomment-1685298000: 
1. In the future, normal and -git packages may share a request.
2. Please explain why you need *both* the normal and -git package.  Such packages normally cannot be installed simultaneously.
3. Link to standard named licenses, like GPL, is not necessary, especially if you are using a generic link, rather than the project-specific copy of the license.

**Comment by bphd** [comment]
> Please explain why you need both the normal and -git package. Such packages normally cannot be installed simultaneously.

User use both, each one choosing the one they like

> Link to standard named licenses, like GPL, is not necessary, especially if you are using a generic link, rather than the project-specific copy of the license.

It's not GPL if they have something different in their specific copy

**Comment by xiota** [comment]
> It's not GPL if they have something different in their specific copy

Right.  If that's the case, then the request form was filled out incorrectly.

**Comment by FabioLolix** [comment]
> It's not GPL if they have something different in their specific copy

They don't, it is the same copy as in the licenses package, checked with `meld`

https://github.com/morpheus65535/bazarr/blob/master/LICENSE

***

This depends on https://aur.archlinux.org/packages/python-webrtcvad-wheels, that don't install the license in the correct place; have informed the maintainer

**Comment by bphd** [comment]
> > It's not GPL if they have something different in their specific copy
> 
> Right. If that's the case, then the request form was filled out incorrectly.

And if that's not, the generic one is sufficient

**Comment by bphd** [comment]
The arr series develop, like VLC, a new major update that change a lot of things. And like VLC they are VERY lenient about adding it into main line. So the develop/git version are not just 3 patches away, it's completely different software. And when you've begun using it you just can't return, mentally like technically with files it use. So I think it deserve more than 'lowest' as it isn't just a clone of main line at all

**Comment by xiota** [comment]
> > > It's not GPL if they have something different in their specific copy
> > >
> > Right. If that's the case, then the request form was filled out incorrectly.
> >
> And if that's not, the generic one is sufficient

That is why the link for standard named licenses is *not* needed.  The name is sufficient.  If you are going to provide a link, it should be to the project-specific copy so it can be used as a reference to check the actual license of the software.

Not every maintainer uses every element of the form, but they do serve a purpose when filled out accurately.  Arguing about every detail is cumbersome and not helpful.

> So the develop/git version are not just 3 patches away, it's completely different software. And when you've begun using it you just can't return, mentally like technically with files it use.

You could list some features from the -git version that haven't made it to the normal version yet.

**Comment by bphd** [comment]
> Not every maintainer uses every element of the form, but they do serve a purpose when filled out accurately. Arguing about every detail is cumbersome and not helpful.

It's perfectly fine if not every maintainer chooses to use every element of the form, if they could, considering they're mandatory to publish. Each field, when appropriately filled out, does contribute positively. I do share your sentiment about the potential challenges and lack of productivity that can arise from debating every single detail, especially when you advise for a standard named licenses, to rather use the project-specific copy of the license

**Comment by xiota** [comment]
> especially when you advise for a standard named licenses, to rather use the project-specific copy of the license

That is not what I advised.  I have stated, "the link for standard named licenses is not needed. The name is sufficient."

I am trying to help you fill out the form so it will be more helpful to maintainers.  You still have not provided requested information.  To the extent that you are unable or unwilling to do so, your requests may not be approved.

**Comment by bphd** [comment]
> You could list some features from the -git version that haven't made it to the normal version yet.

Look changelog version 4 for example

**Comment by segalll** [comment]
This doesn't seem to be working.
```
Aug 21 23:08:04 pekin bazarr[41872]: 2023-08-21 23:08:04,605 - root                             (7f6c2808c740) :  INFO (server:67) - BAZARR
 is started and waiting for request on http://0.0.0.0:6767
Aug 21 23:08:04 pekin bazarr[41872]: Exception in thread Thread-4 (start):
Aug 21 23:08:04 pekin bazarr[41872]: Traceback (most recent call last):
Aug 21 23:08:04 pekin bazarr[41872]:   File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
Aug 21 23:08:04 pekin bazarr[41872]:     self.run()
Aug 21 23:08:04 pekin bazarr[41872]:   File "/usr/lib/python3.11/threading.py", line 975, in run
Aug 21 23:08:04 pekin bazarr[41872]:     self._target(*self._args, **self._kwargs)
Aug 21 23:08:04 pekin bazarr[41872]:   File "/usr/lib/bazarr/bazarr/app/signalr_client.py", line 125, in start
Aug 21 23:08:04 pekin bazarr[41872]:     self.connection.start()
Aug 21 23:08:04 pekin bazarr[41872]:   File "/usr/lib/bazarr/bazarr/../libs/signalrcore/hub/base_hub_connection.py", line 53, in start
Aug 21 23:08:04 pekin bazarr[41872]:     return self.transport.start()
Aug 21 23:08:04 pekin bazarr[41872]:            ^^^^^^^^^^^^^^^^^^^^^^
Aug 21 23:08:04 pekin bazarr[41872]:   File "/usr/lib/bazarr/bazarr/../libs/signalrcore/transport/websockets/websocket_transport.py", line
64, in start
Aug 21 23:08:04 pekin bazarr[41872]:     self.negotiate()
Aug 21 23:08:04 pekin bazarr[41872]:   File "/usr/lib/bazarr/bazarr/../libs/signalrcore/transport/websockets/websocket_transport.py", line
101, in negotiate
Aug 21 23:08:04 pekin bazarr[41872]:     raise HubError(response.status_code)\
Aug 21 23:08:04 pekin bazarr[41872]: signalrcore.hub.errors.HubError: 405
Aug 21 23:08:04 pekin bazarr[41872]: Exception in thread Thread-5 (start):
Aug 21 23:08:04 pekin bazarr[41872]: Traceback (most recent call last):
Aug 21 23:08:04 pekin bazarr[41872]:   File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
Aug 21 23:08:04 pekin bazarr[41872]:     self.run()
Aug 21 23:08:04 pekin bazarr[41872]:   File "/usr/lib/python3.11/threading.py", line 975, in run
Aug 21 23:08:04 pekin bazarr[41872]:     self._target(*self._args, **self._kwargs)
Aug 21 23:08:04 pekin bazarr[41872]:   File "/usr/lib/bazarr/bazarr/app/signalr_client.py", line 193, in start
Aug 21 23:08:04 pekin bazarr[41872]:     self.connection.start()
Aug 21 23:08:04 pekin bazarr[41872]:   File "/usr/lib/bazarr/bazarr/../libs/signalrcore/hub/base_hub_connection.py", line 53, in start
Aug 21 23:08:04 pekin bazarr[41872]:     return self.transport.start()
Aug 21 23:08:04 pekin bazarr[41872]:            ^^^^^^^^^^^^^^^^^^^^^^
Aug 21 23:08:04 pekin bazarr[41872]:   File "/usr/lib/bazarr/bazarr/../libs/signalrcore/transport/websockets/websocket_transport.py", line
64, in start
Aug 21 23:08:04 pekin bazarr[41872]:     self.negotiate()
Aug 21 23:08:04 pekin bazarr[41872]:   File "/usr/lib/bazarr/bazarr/../libs/signalrcore/transport/websockets/websocket_transport.py", line
101, in negotiate
Aug 21 23:08:04 pekin bazarr[41872]:     raise HubError(response.status_code)\
Aug 21 23:08:04 pekin bazarr[41872]: signalrcore.hub.errors.HubError: 405
Aug 21 23:08:07 pekin bazarr[41872]: 2023-08-21 23:08:07,893 - app.app                          (7f6b0bfff6c0) :  ERROR (app:1741) - Except
ion on /bazarr/ [GET]
Aug 21 23:08:08 pekin bazarr[41872]: 2023-08-21 23:08:08,802 - app.app                          (7f6b0b7fe6c0) :  ERROR (app:1741) - Except
ion on /bazarr/ [GET]
Aug 21 23:08:09 pekin bazarr[41872]: 2023-08-21 23:08:09,206 - app.app                          (7f6b0a7fc6c0) :  ERROR (app:1741) - Except
ion on /bazarr/ [GET]
Aug 21 23:08:09 pekin bazarr[41872]: 2023-08-21 23:08:09,635 - app.app                          (7f6b08ff96c0) :  ERROR (app:1741) - Except
ion on /bazarr/ [GET]
Aug 21 23:08:10 pekin bazarr[41872]: 2023-08-21 23:08:10,107 - app.app                          (7f6ae7fff6c0) :  ERROR (app:1741) - Except
ion on /bazarr/ [GET]
Aug 21 23:08:10 pekin bazarr[41872]: 2023-08-21 23:08:10,539 - app.app                          (7f6ae67fc6c0) :  ERROR (app:1741) - Except
ion on /bazarr/ [GET]
```

**Comment by xiota** [comment]
@segalll Thank you for the report.  Is `bazarr` of interest to you?  If so, I'll add it to the packages list.

Are you interested in leaving a bug report for the developer?  If so, I'll leave the -git package in the repository so you can do further testing.  https://github.com/morpheus65535/bazarr

**Comment by bphd** [comment]
> Is bazarr of interest

Indeed, truth seeker, the bazaar you speak of holds quite the intrigue. With its towering constellation of 2k+ stars on GitHub, a celestial testimony to its worthiness. And who can fathom the multitude of downloads it has graced upon eager seekers? Sixteen resounding votes echo in the chambers of AUR, a testament to its superiority over many others on this repository. Truly, a gem amidst the digital sands.

**Comment by dr460nf1r3** [comment]
@bphd might stop adding those comments. Last warning is given.
