### ISSUE TITLE
[Request] deezloader-remix-git

### ISSUE THREAD

**Issue by bphd** [chaotic-aur/packages#2732]
## Package: deezloader-remix-git

**Package:** [deezloader-remix-git](https://aur.archlinux.org/packages/deezloader-remix-git)
**Purpose:** Deezloader Remix is a software for downloading music from Deezer. It allows users to download high-quality music tracks from the Deezer music streaming service.
**Benefits:** Deezloader Remix provides a convenient way to acquire music from Deezer, making it accessible offline. It offers an alternative to official offline listening options.
**Building:** To build the deezloader-remix-git package, follow these steps in a clean chroot:
```shell
git clone https://aur.archlinux.org/deezloader-remix-git.git
cd deezloader-remix-git
makepkg -si
```
**Copyright:** Custom License
**Expected Interest:** Moderate interest among music enthusiasts.
**Already available?** Available on AUR but not on Chaotic AUR.
**Unique request?** Yes, this request is unique and not available on Chaotic AUR.
**Banned package?** Not a banned package.
**More information:** Deezloader Remix offers an efficient way to download high-quality music from Deezer, providing offline access and an alternative to official listening options.

**Comment by xiota** [comment]
1. Please edit the title of your requests to reflect the package names.
2. When initially submitting the requests, please edit the title and fill out the form so that the email notifications will contain the correct information.
3. Package url returns 404 error.  Package was deleted from AUR two months ago.  You may edit this request to refer to a substitute package if one exists.
4. Please provide links to custom licenses and EULAs.

**Comment by FabioLolix** [comment]
License was GPL3, the source repo have been resetted, this is likely against Deezer's terms of service

**Comment by xiota** [comment]
Links to Deezer service TOS, EULA, etc in the request would be appropriate.

**Comment by Technetium1** [comment]
Since this no longer exists on the AUR, this request cannot be completed.

**Comment by FabioLolix** [comment]
https://www.deezer.com/legal/cgu it open only in Italian for me

`Qualsiasi altro utilizzo delle Registrazioni è espressamente vietato, in particolare il download o tentativo di download, il trasferimento o tentativo di trasferimento temporaneo o definitivo sul disco rigido di un computer o su qualsiasi altro dispositivo`

Google translation
`Any other use of the Recordings is expressly prohibited, in particular the download or attempted download, the temporary or permanent transfer or attempted transfer to a computer hard drive or any other device`

Deepl translation
`Any other use of the Recordings is expressly prohibited, in particular downloading or attempted downloading, transferring or attempting to transfer temporarily or permanently to a computer hard disk or any other device`

This apply for any deezer downloader

**Comment by Technetium1** [comment]
Since it is purpose built for only downloading from the one prohibited service, I don't think we'd add it anyway. If someone needs to download from Deezer consider https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md
