### ISSUE TITLE
[Request] mtkclient-git

### ISSUE THREAD

**Issue by bphd** [chaotic-aur/packages#2736]
**Package:**

[mtkclient-git](https://aur.archlinux.org/packages/mtkclient-git)

**Purpose:**

mtkclient-git is a client for interacting with MediaTek devices, typically used for flashing firmware and managing device settings.

**Benefits:**

n/a

**Building:**

n/a

**Copyright:**

GPL3

**Expected Interest:**

Some

**Already available?**

No

**Unique request?**

Yes

**Banned package?**

No

**More information:**

None

**Comment by xiota** [comment]
@bphd  Do not open any more requests until you have fixed issues with the old requests.

**Comment by xiota** [comment]
Dropping because broken and poor maintenance.
