### ISSUE TITLE
[Request] obs-replay-source

### ISSUE THREAD

**Issue by bphd** [chaotic-aur/packages#2737]
**Package:**

[obs-replay-source](https://aur.archlinux.org/packages/obs-replay-source)

depends:
[libcaption-git](https://aur.archlinux.org/packages/libcaption-git)

**Purpose:**

obs-replay-source is a plugin for OBS Studio, a popular open-source software for live streaming and recording. This plugin allows users to replay recent segments of their stream during live broadcasts.

**Benefits:**

n/a

**Building:**

n/a

**Copyright:**

GPL2

**Expected Interest:**

Some

**Already available?**

No

**Unique request?**

Yes

**Banned package?**

No

**More information:**

None

**Comment by xiota** [comment]
Not building because cannot find `uthash.h`.  Seems to be problem with `extra/obs-studio`.  See this [comment](https://aur.archlinux.org/packages/obs-replay-source#comment-917945).

**Comment by bphd** [comment]
I'm a bit puzzled here. Could you clarify whether you're discussing issues related to the status of packages within a 10,000-package range? If these packages aren't building successfully, I'm wondering if it's more efficient to automate the retry process until they do. On the other hand, if you're only addressing packages that haven't been accepted yet, I'm curious why there's a distinction made. After all, all packages have the potential to encounter issues during their life. When a package fails to integrate smoothly, it unfairly tarnishes its reputation and consumes unnecessary effort, which doesn't differ significantly from what's already invested in packages that have been successfully integrated (except for additional compiling resources).

**Comment by xiota** [comment]
Rejecting because I'm not interested in trying to convince the maintainer to fix the package.  I'm willing to reconsider if more, different people are interested in this package.
