### ISSUE TITLE
[Request] orca-slicer

### ISSUE THREAD

**Issue by georgewoodall82** [chaotic-aur/packages#2740]
### Package:

[orca-slicer](https://aur.archlinux.org/pkgbase/orca-slicer)

### Purpose:

The best 3D printing slicer, it is used to edit, and slice 3d models so that they can print on a 3d printer. A 3d printing slicer is in most cases needed if you need to 3d print something.

### Benefits:

Builds orca slicer so that it works better on arch, as orca slicer currently just has a lazy appimage that is for ubuntu, and barely works in other distros (It wouldn't run at all for me)

### Building:

makepkg

### Copyright:

AGPL-3.0

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Have a good day

**Comment by xiota** [comment]
Fails to build.  [`orca-slicer.log`](https://builds.garudalinux.org/repos/chaotic-aur/logs/orca-slicer.log)

Also depends on [`harmonyos-sans-git`](https://aur.archlinux.org/packages/harmonyos-sans-git), but the repo isn't cloning.

**Comment by xiota** [comment]
It looks like a descendant of prusa slicer, so that might be worth trying.

**Comment by georgewoodall82** [comment]
its actually based on bambu studio, which is based on prusaslicer. I have tried both and they are good but orca slicer is the only linux program i have never been able to run on my system, even with distrobox. I have only got it to run on ubuntu.

**Comment by FabioLolix** [comment]
harmonyos-sans-git is quite a license hell, in the repo there are both an Apache2 and a custom one https://gitee.com/openharmony/resources/blob/master/LICENSE_Fonts

> 
> 2.GRANT OF LICENSE
> 
> Subject to the terms and conditions of this Agreement, Licensor hereby grant YOU a non-transferable, non-exclusive, royalty-free, revocable, worldwide copyright license to use,copy, merge, embed, bundle, redistribute and/or sell unmodified copies of HarmonyOS Sans Fonts with any software except for fonts software，subject to the  following conditions:
>
> 1)YOU shall make a prominent notice in the software to state that HarmonyOS Sans Fonts are used.
>
> 2)YOU may not make any modifications to HarmonyOS Sans Fonts or any of their individual components.
>
> 3)Neither HarmonyOS Sans Fonts nor any of their individual components may be redistributed or sold in a stand-alone base. This limitation does not apply to any work created by using HarmonyOS Sans Fonts. You can freely distribute or sell your work, such as materials, logos, application software etc. created by using HarmonyOS Sans Fonts.
>
> 4)YOU shall retain the copyright notice and this Agreement in any copies of HarmonyOS Sans Fonts.
> 
> 3.Termination
>

**Comment by xiota** [comment]
I got a modified `PKGBUILD` to build for `orca-slicer`, but it doesn't work because it tries to use files from the build path instead of their actual locations. Subsequent attempts to build failed.  Looks complicated to fix.
