### ISSUE TITLE
[Bug] When using linux-cachyos from chaotic-aur, the system refuses to start up 

### ISSUE THREAD

**Issue by Boria138** [chaotic-aur/packages#2744]
### Packages:

[linux-cachyos](https://aur.archlinux.org/packages/linux-cachyos)

### Latest chaotic version

6.4.11-1

### What happens?

When I select the cachyos kernel in GRUB, I see the vendor logo and then I get thrown back to GRUB

### What is expected to happen?

The system must start up properly 

### More information

Before writing a bug report here, I built the kernel from aur and it works fine

**Comment by dr460nf1r3** [comment]
I think that might be attributed to a kernel bug rather than the linux-cachyos (see [here](https://forum.garudalinux.org/t/dumped-into-emergency-shell-after-update-failed-to-start-switch-root-btrfs-errors/30440/3?u=dr460nf1r3) for reference).

**Comment by Boria138** [comment]
> I think that might be attributed to a kernel bug rather than the linux-cachyos (see [here](https://forum.garudalinux.org/t/dumped-into-emergency-shell-after-update-failed-to-start-switch-root-btrfs-errors/30440/3?u=dr460nf1r3) for reference).

I do not get into the crash shell, as I wrote when selecting cachyos kernel I see the logo of my motherboard, and then I return to GRUB, I also added that hand-built from aur kernel does not have such a problem it is the binary from chaotic-aur does not allow me to boot up

**Comment by dr460nf1r3** [comment]
@ptr1337 possible kernel bug?

**Comment by dr460nf1r3** [comment]
Hm, interesting.. we'd need to confirm whether it's just you or the kernel in general being broken 🤔

**Comment by ptr1337** [comment]
You can also try to install the kernel from our (CachyOS) repository and report back if its fine.

**Comment by Boria138** [comment]
> You can also try to install the kernel from our (CachyOS) repository and report back if its fine.

As I have already written the problem is in the version that lies in chaotic-aur I built the kernel myself, and also connected your repositories and everything worked fine

**Comment by Boria138** [comment]
> Version `6.4.12` is in the repo, can you give it a try please?

It's still not working

**Comment by Boria138** [comment]
Maybe CPU auto-optimization is to blame, although when I built the kernel via GitHub Actions it delivered, but maybe I just got lucky and the GitHub Actions servers have similar hardware to mine @ptr1337 Is my hypothesis correct?

**Comment by dr460nf1r3** [comment]
Interesting theory! What's the CPU you are using?

**Comment by Boria138** [comment]
> Interesting theory! What's the CPU you are using?

So it looks like my hypothesis was correct on my old laptop with i3-3217u kernel won't start but on my main pc with i3-4150 everything works perfectly fine

**Comment by Boria138** [comment]
It seems that in order for the kernel from chaotic-aur to work properly the processor should support at least x86_64v3 architecture, so on i3-3217u which supports only v2 architecture the kernel doesn't work, but the kernel itself can work on v2 architectures too I guess because your build server on v3 architecture the processor auto-optimization script has disabled support for v2 architecture so you probably need to edit pkgbuild a bit to prevent this from happening

**Comment by ptr1337** [comment]
@dr460nf1r3 

Can you also add a infere like you did with linux-cachyos-bore?
See here:
https://github.com/chaotic-aur/interfere/blob/master/linux-cachyos-bore/prepare

**Comment by Boria138** [comment]
I guess we need to add infere to all versions of the cachyos kernel since they all have CPU auto-tuning and all will not work on the v2 architecture because of this

**Comment by dr460nf1r3** [comment]
Sounds like the course of action here.

**Comment by Boria138** [comment]
> @dr460nf1r3 
> 
> Can you also add a infere like you did with linux-cachyos-bore?
> See here:
> https://github.com/chaotic-aur/interfere/blob/master/linux-cachyos-bore/prepare

I now install linux-cachyos-bore on which as I understand this fix is already there and the laptop also did not boot, or still there is still using automatic processor configuration ?

**Comment by dr460nf1r3** [comment]
It seems that the variable's name changed in the meantime: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-cachyos-bore#n285

**Comment by dr460nf1r3** [comment]
Fresh builds are currently on the way as well.

**Comment by Boria138** [comment]
> Fresh builds are currently on the way as well.

And how to find out if there are new builds with fixes for this bug, for the test ?

**Comment by dr460nf1r3** [comment]
You can simply install/update the kernel by now. It should have a pkgrel incremented by `0.1'.

**Comment by Boria138** [comment]
> You can simply install/update the kernel by now. It should have a pkgrel incremented by `0.1`.

I updated the kernel and it finally worked, you can close the error

**Comment by dr460nf1r3** [comment]
Very nice, thanks for making us aware of this issue, cheers!
