### ISSUE TITLE
[Request] poppler-qt-lcd

### ISSUE THREAD

**Issue by guiodic** [chaotic-aur/packages#2746]
### Package:

[poppler-qt-lcd](https://aur.archlinux.org/packages/poppler-qt-lcd)

### Purpose:

Poppler Qt bindings, with patches to allow subpixel rendering via Cairo

### Benefits:

Better font rendering than standard poppler in Arch repos.

### Copyright:

GPL

### Expected Interest:

Most

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
I've commented on aurweb to ask the maintainer to update provides/conflicts.  In meantime, a build is available for testing.  Please let me know if it works.  I didn't see any difference with okular on my computer.

**Comment by guiodic** [comment]
It works fine, thank you. The difference is more evident with small fonts


Il giorno dom 27 ago 2023 alle ore 01:22 xiota ***@***.***>
ha scritto:
