### ISSUE TITLE
[Request] thorium-browser-bin

### ISSUE THREAD

**Issue by alexoona** [chaotic-aur/packages#2747]
### Package:

[thorium-browser-bin](https://aur.archlinux.org/packages/thorium-browser-bin)

### Purpose:

Chromium fork for linux named after [radioactive element No. 90](https://en.wikipedia.org/wiki/Thorium). 
• Windows/MacOS/RasPi/Android/Other builds see below.
• Always built with the latest stable version of [Chromium](https://www.chromium.org/).
Intended to behave like and have the featureset of Google Chrome, with differences/patches/enhancements listed below.
• Includes [Widevine](https://www.widevine.com/), [All Codecs](https://tools.woolyss.com/html5-audio-video-tester/), Chrome Plugins, as well as thinLTO, CFlag, LDFlag, LLVM Loop, and PGO compiler optimizations. It is built with [SSE4](https://en.wikipedia.org/wiki/SSE4), [AVX](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions), and [AES](https://en.wikipedia.org/wiki/AES_instruction_set), so it won't launch on CPU's below 2nd gen Core or AMD FX, but benefits from Advanced Vector EXtensions. If your CPU lacks AVX, you can use builds from [Thorium Special](https://github.com/Alex313031/Thorium-Special).

### Benefits:

Compiler optimizations include SSE4.2, AVX, AES, and modifications to CFLAGS, LDFLAGS, thinLTO flags, import_instr_limit flags, and PGO, as well as other compiler flags.
LLVM LOOP optimizations as -mllvm flags
Learn more about these compiler optimizations and how they work [Here](https://thorium.rocks/optimizations).
UI Changes and Patches for Linux and Windows that fix bugs, enhance useability, and strengthen privacy/security.

### Copyright:

BSD 3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Please include this package in the chaotic-aur.
Thank you in advance

**Comment by xiota** [comment]
Added `thorium-browser-sse3-bin` for use on older computers lacking newer instruction sets.

The packages can be installed simultaneously, but they are ~240M to download and ~630M to install.

**Comment by xiota** [comment]
`thorium-browser-bin` is renamed on chaotic servers to `thorium-browser-avx-bin` to indicate the x86-64-v3 processor requirement and make selecting the correct package easier for users.  The launcher script has also been updated to check processor requirements and advise the user to switch packages if needed.

**Comment by xiota** [comment]
Planning to drop these packages.

* `thorium-browser-*` packages are space hogs.
* Developer has historically not kept up-to-date with upstream releases.
* Developer is making too many variations that do not follow standard x86-64 levels.
* Binary packages that are quick for users to make for themselves.
* Instruction set optimization doesn't improve browser performance.

Performance, using browserbench.org speedometer 2.1, ranked "fastest" to "slowest":

* 86.6±1.8: `extra/firefox` 121.0
* 83.8±1.0: `thorium-browser-avx-bin` 119.0.6045.214
* 83.8±1.0: `thorium-browser-sse3-bin` 119.0.6045.214
* 75.8±1.7: `thorium-browser-sse3-bin` 117.0.5938.157
* 75.4±1.0: `mercury-browser-sse3-bin` 121.0.1
* 75.2±1.3: `thorium-browser-avx-bin` 117.0.5938.157
* 74.4±1.7: `mercury-browser-avx-bin` 121.0.1
* 66.5±0.9: `mercury-browser-avx-bin` 115.4.0

Methodology:

* Install browser.
* Run with new profile.
* Disable extensions if they interfere with benchmarking.
* Run benchmark at least twice.
* Result must be within ±2.
