### ISSUE TITLE
[Request] motivewave-latest-bin

### ISSUE THREAD

**Issue by xiota** [chaotic-aur/packages#2748]
### Package:

https://aur.archlinux.org/packages/motivewave-latest-bin

### Purpose:

A Trading Platform to Fit Any Trader or Market Analyst; https://www.motivewave.com/

### Building:

clean chroot

### Copyright:

https://www.motivewave.com/support/terms_of_service.htm

> Distribution. User may not distribute registered copies of the Software to third parties.

However, no prohibition against distributing unregistered copies.

### Expected Interest:

Few; metrics currently show 2 downloads

### Already available?

Yes; creating this issue to migrate `motivewave` → `motivewave-latest-bin`.

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Switched to custom pkgbuild located at https://github.com/chaotic-aur/pkgbuild-motivewave.git

**Comment by dr460nf1r3** [comment]
Sounds great :+1:
