### ISSUE TITLE
[Rebuild] Various rebuilds due to library bumps

### ISSUE THREAD

**Issue by ocobblepot** [chaotic-aur/packages#2753]
### Packages:

strawberry-qt5 https://aur.archlinux.org/packages/strawberry-qt5

### Latest chaotic version

1.0.18-1

### Reason for rebuild

Attempting to launch the qt5 build of strawberry (strawberry-qt5 in chaotic-aur) results in the following error:
"strawberry: error while loading shared libraries: libprotobuf.so.31: cannot open shared object file: No such file or directory"

This error has occurred previously - https://github.com/chaotic-aur/packages/issues/1490

The strawberry package in the Arch Extra repo has been rebuilt due to the updated protobuf package - https://gitlab.archlinux.org/archlinux/packaging/packages/strawberry/-/commits/main

Disabling chaotic-aur in pacman.conf and then building/installing directly from the AUR (which takes ages!) results in an installation that will launch successfully.

**Comment by xiota** [comment]
Following packages likely to have the same issue.  Bumping them now.  Will check later whether they successfully rebuild.

- [ ] across
- [ ] akonadi-git
- [ ] ayatana-indicator-datetime
- [ ] clementine-git
- [ ] compiz-git
- [ ] compiz-gtk
- [ ] dogecoin-qt
- [ ] emerald-gtk3
- [ ] endeavour-git
- [ ] gazebo
- [ ] gimp-elsamuko-git
- [ ] ignition-fuel_tools-4
- [ ] ignition-msgs-5
- [ ] ignition-transport-8
- [ ] jellyfin-media-player
- [ ] kaddressbook-git
- [ ] kalendar-git
- [ ] kdepim-addons-git
- [ ] kdepim-runtime-git
- [ ] kitinerary-git
- [ ] kmail-git
- [ ] knotes-git
- [ ] korganizer-git
- [ ] lokinet
- [ ] plex-media-player
- [ ] qtscrcpy
- [ ] siril
- [ ] strawberry-qt5
- [ ] tahoma2d

**Comment by xiota** [comment]
@ocobblepot `strawberry-qt5` should be working now.  I'm leaving this issue open because I need to check back on the other affected packages.  Feel free to comment here if you find more packages with related issue.

**Comment by FabioLolix** [comment]
Tahoma2d is very likely broken, 1 issue have a workaround the other not yet reported and I'm away for a few days

**Comment by xiota** [comment]
@FabioLolix Thanks for info.  How likely do you think `tahoma2d` is to be fixed eventually (with guestimate timeframe)?  Do you think it should be a candidate to drop from chaotic because the old build no longer works and no longer possible to rebuild?

**Comment by xiota** [comment]
@alexjp FYI.  Following packages probably need to be rebuilt.

- akonadi-git
- kaddressbook-git
- kalendar-git
- kdepim-addons-git
- kdepim-runtime-git
- kitinerary-git
- kmail-git
- knotes-git
- korganizer-git

**Comment by ocobblepot** [comment]
> @ocobblepot `strawberry-qt5` should be working now. I'm leaving this issue open because I need to check back on the other affected packages. Feel free to comment here if you find more packages with related issue.

Yes, it works here now. Thank you.

**Comment by xiota** [comment]
@ocobblepot I bumped all relevant packages that are working earlier.  `strawberry-qt5` should be rebuilt by now.

**Comment by ocobblepot** [comment]
@xiota I confirm that strawberry-qt5 installs and launches OK again :+1:
