### ISSUE TITLE
[Request] ayugram-desktop-git

### ISSUE THREAD

**Issue by incycledream** [chaotic-aur/packages#2754]
### Package:

[ayugram-desktop-git](https://aur.archlinux.org/pkgbase/ayugram-desktop-git)

### Purpose:

— What does the package do?
This package is a modified Telegram Desktop client with features that safely violate Telegram's terms of service (both client and user won't be banned). It's a unique Telegram Desktop client with following features:
- Disable read packets sending
- Disable online packets sending
- Disable typing & upload packets sending
- Auto offline
- Messages history (+ deleted ones)
- View, forward and reply on deleted messages (deleted messages are stored in sqlite3 database)
- Using scheduled messages to keep offline

—  How is it used?
The same way as regular Telegram Desktop

— How is it useful?
It's useful for that people who want more freedom in Telegram Desktop, I don't know what to write here

### Benefits:

— What specific benefits does this package have over other packages? 

— What are some use cases for this package and why would a user use this package instead of another?
Other alternatives doesn't exist, If you ever need features that listed in "Purpose" section then AyuGram is for you

### Building:

Please keep in mind that I'll use this precompiled package as official Linux build of this Telegram Desktop client because nobody wants to compile and maintain it

Here's how you need to build:
https://github.com/AyuGram/AyuGramDesktop/blob/dev/docs/building-linux.md
It's not necessary to build with Docker but very recommended

This AUR package is built by different technique so it can run only on Arch Linux but I wanna to run it on other distros

### Copyright:

GPL3

### Expected Interest:

Most

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
> violate Telegram's terms of service

I'm inclined against adding this.

**Comment by dr460nf1r3** [comment]
Since we try to not violate rules, also by not including packages that aren't allowed to be shared, I have to agree 🤔
