### ISSUE TITLE
[Request] doas-sudo-shim

### ISSUE THREAD

**Issue by atouu** [chaotic-aur/packages#2757]
### Package:

[doas-sudo-shim](https://aur.archlinux.org/packages/doas-sudo-shim)

### Purpose:

Shim for the sudo command that utilizes [doas](https://www.mankier.com/1/doas).

### Benefits:

For those who doesn't want to use sudo

### Building:

makepkg -s

### Copyright:

ISC

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Another similar package called `opendoas-sudo` already exist but it's unmaintained and removed from aur and chaotic-aur database.

**Comment by xiota** [comment]
Dropped because no longer in AUR.  Metrics 97.
