### ISSUE TITLE
[Request] mcpelauncher-appimage

### ISSUE THREAD

**Issue by REmerald** [chaotic-aur/packages#2758]
### Package:

[mcpelauncher-appimage](https://aur.archlinux.org/pkgbase/mcpelauncher-appimage)

### Purpose:

Appimage version of `mcpelauncher-linux-git`+`mcpelauncher-ui-git`.

### Benefits:

This is more stable (but more outdated) version that saves the day, when the git version is broken. See [the comment](https://github.com/minecraft-linux/mcpelauncher-ui-manifest/issues/50#issuecomment-1476402814).

For me it has happened 2 times now (the first time is in the link above, and the second time was here in #2660).
The git version is good now, but in case it breaks again, this package would be useful.
Also, some ppl might prefer the stable version :man_shrugging:.

### Building:

paru :upside_down_face:

### Copyright:

GPL3

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

In case someone asks, I would not recommend replacing the git packages with this package. It's only suitable for a temporary replacement while the git version are broken.
The stable versions release once a 3 months, which is very long time to wait for a fix or new minecraft version compatibility.
Also, the appimage version had some downsides before. (Didn't test the latest version, so can't tell if they're fixed now).

Btw, it was also known as `mcbelauncher` before, and just now the old package got merged into the new `mcpelauncher-appimage`, so it's good to be added now.

**Comment by xiota** [comment]
Looks like a misnamed -bin package.

**Comment by Technetium1** [comment]
Due to the size vs its popularity, as well as the fact it's available via GitHub CDN, I don't think this is right for us to add.
