### ISSUE TITLE
[Rebuild] chromium-wayland-vaapi

### ISSUE THREAD

**Issue by PolpOnline** [chaotic-aur/packages#2759]
### Packages:

[chromium-wayland-vaapi](https://aur.archlinux.org/packages/chromium-wayland-vaapi)

### Latest chaotic version

`115.0.5790.170-2`

### Reason for rebuild

Regression regarding Wayland support, instantly crashes upon opening, see package's comments for more info

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/chromium-wayland-vaapi.log

**Comment by dr460nf1r3** [comment]
The package has been bumped and is waiting for the builder to start the routine.

**Comment by Technetium1** [comment]
Completed
