### ISSUE TITLE
Request: mergerfs & snapraid

### ISSUE THREAD

**Issue by ryester27** [chaotic-aur/packages#276]
Hello. Can you please add mergerfs and snapraid to your repo? Thank you.

https://aur.archlinux.org/packages/mergerfs/
https://aur.archlinux.org/packages/snapraid/

**Comment by PedroHLC** [comment]
Done

Please test it. And if it works as expected, feel free to close this issue.

Thanks for you contribution!

**Comment by ryester27** [comment]
Installed just fine. Thanks again!
