### ISSUE TITLE
[Request] realvnc-vnc-server-6 6.11.0-3

### ISSUE THREAD

**Issue by gpodder770** [chaotic-aur/packages#2760]
### Package:

https://aur.archlinux.org/packages/realvnc-vnc-server-6

### Purpose:

To connect to pcs for remote help like anydesk

### Benefits:

Realvnc licenses are divided among versions

### Copyright:

Not Sure
EULA (pdf): https://www.realvnc.com/en/realvnc-eula/

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
`realvnc-vnc-server` 7.5.1 and `realvnc-vnc-viewer` 7.6.0 are already in chaotic.  Why is 6.11.0 needed?

**Comment by Bhooty** [comment]
> `realvnc-vnc-server` 7.5.1 and `realvnc-vnc-viewer` 7.6.0 are already in chaotic. Why is 6.11.0 needed?

Sry sir for the mate reply
This is my another account 
This is not the viewer this is the server sir old version

**Comment by Bhooty** [comment]
> `realvnc-vnc-server` 7.5.1 and `realvnc-vnc-viewer` 7.6.0 are already in chaotic. Why is 6.11.0 needed?

The old version license doesn’t work on new version (7) of server thus I added the request sir 🥹

**Comment by xiota** [comment]
A build of `realvnc-vnc-server-6` is available for testing, pending review by other chaotic-aur maintainers.  An exact time frame for testing and review has not been established.

The purpose of test builds is to check for technical issues, such as failure to build in a clean chroot, packaging issues, and errors upon execution.  If the package is not deemed suitable for inclusion in chaotic-aur, the test build will be removed.

**Comment by xiota** [comment]
Removing package.  Also note that the aur package is currently orphaned.
