### ISSUE TITLE
[Rebuild] ueberzugpp

### ISSUE THREAD

**Issue by AlbeyAmakiir** [chaotic-aur/packages#2762]
### Packages:

[uebrezugpp](https://aur.archlinux.org/packages/ueberzugpp)

### Latest chaotic version

2.9.1-1

### Reason for rebuild

According to https://github.com/jstkdng/ueberzugpp/issues/119 a recompile is needed for it to find the recent `libspdlog.so.1.12` update instead of the outdated `libspdlog.so.1.11`.

**Comment by xiota** [comment]
Bumped and rebuilt.  `ueberzugpp` 2.9.1-1.1 now available.
