### ISSUE TITLE
[Rebuild] mcpelauncher-ui-git

### ISSUE THREAD

**Issue by Skerse** [chaotic-aur/packages#2764]
### Packages:

[mcpelauncher-ui-git](https://aur.archlinux.org/packages/mcpelauncher-ui-git)

### Latest chaotic version

v0.9.0.qt6.r5.g1664329-1

### Reason for rebuild

Broken, the package [protobuf](https://archlinux.org/packages/extra/x86_64/protobuf/) had a new update and a rebuild should use the new version and fix the issue.

### Logs

~/$ mcpelauncher-ui-qt
mcpelauncher-ui-qt: error while loading shared libraries: libprotobuf.so.23: cannot open shared object file: No such file or directory

### Builds?

Using the [pkgbuild from the AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mcpelauncher-ui-git) works!

**Comment by dr460nf1r3** [comment]
It does seem that package has been building since the issue was created:
~~~
==> Updated version: mcpelauncher-ui-git v0.11.0.qt6.r0.gb5238fb-1
==> ERROR: A package has already been built. (use -f to overwrite)
~~~
Can you confirm its fixed?

**Comment by Skerse** [comment]
Sorry for the wait, just downloaded it now and can confirm it fixed and works as intended. Thank you!

**Comment by REmerald** [comment]
@xiota The package requires rebuild again.
```
mcpelauncher-ui-qt: symbol lookup error: mcpelauncher-ui-qt: undefined symbol: _ZN6google8protobuf8internal17AssignDescriptorsEPFPKNS1_15DescriptorTableEvEPN4absl12lts_202308029once_flagERKNS0_8MetadataE
```

**Comment by Technetium1** [comment]
@REmerald reinstall: `Finished making: mcpelauncher-ui-git 0.14.1.r0.gd56d29b-1 (Fri 22 Mar 2024 04:53:49 PM CET)`

**Comment by REmerald** [comment]
@xiota @Technetium1 @dr460nf1r3 the package needs rebuild again
```
mcpelauncher-ui-qt: error while loading shared libraries: libprotobuf.so.25: cannot open shared object file: No such file or directory
```

**Comment by xiota** [comment]
Bumped packages with depends on `protobuf`.

**Comment by REmerald** [comment]
@xiota, protobuf update broke it again

**Comment by xiota** [comment]
Bumped in https://github.com/chaotic-aur/interfere/commit/ea3a7cdafe71a0067822be3a639dc2a85d236868
