### ISSUE TITLE
[Request] libresprite

### ISSUE THREAD

**Issue by yum13241** [chaotic-aur/packages#2765]
### Package:

[libresprite](https://aur.archlinux.org/pkgbase/libresprite)

### Purpose:

It's a fork from the last GPLv2 version of Aseprite, which is a paint app designed for pixel art. Since you can't distribute Aseprite, this would fill that niche.

### Benefits:

Freedom and not relying on AppImages which use an outdated version of `libfuse` (version 2).

### Copyright:

GPLv2 [only?](https://github.com/LibreSprite/LibreSprite/blob/master/LICENSE.txt)

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Why not `libresprite-git`?  Looks like last release of `libresprite` was in 2021, while the git repository has had updates over the years.

**Comment by yum13241** [comment]
I assumed they'd add the Git packages by themselves, since dr460nf1re is a big fan of `-git` packages.

**Comment by xiota** [comment]
@yum13241 As far as I know, -git packages are not automatically added without some other reason.  If the -git version is added, do you need the normal package?

Doesn't matter either way.  Both `libresprite` and `libresprite-git` currently failing to build.

**Comment by yum13241** [comment]
Log? No one can help otherwise.

**Comment by xiota** [comment]
> Log? No one can help otherwise.

Not my responsibility to fix.  Already reported with logs on the AUR pages.

**Comment by xiota** [comment]
@yum13241 Build of `libresprite` is available for testing.  Please report back whether it is working.  Thank you.

**Comment by xiota** [comment]
Switching to `libresprite-git` (fixed with intefere until upstream can be updated) because `libresprite` 1.0 was released in Nov 2021 and has severe graphical glitches.
