### ISSUE TITLE
[Request] picoscope7beta

### ISSUE THREAD

**Issue by maeknight** [chaotic-aur/packages#2766]
### Package:

[picoscope7beta](https://aur.archlinux.org/packages/picoscope7beta)

and optional driver packages with the `ps7b_` prefix.

`ps7b_libpicoipp`
`ps7b_libpicocv`
`ps7b_libpicocv`
`ps7b_libpicoipp`
`ps7b_libps2000`
`ps7b_libps2000a`
`ps7b_libps3000`
`ps7b_libps3000a`
`ps7b_libps4000`
`ps7b_libps4000a`
`ps7b_libps5000`
`ps7b_libps5000a`
`ps7b_libps6000`
`ps7b_libps6000a`

### Purpose:

linux software for using with pico technology's picoscope series of oscilloscopes.

### Copyright:

[picoscope-license.txt](https://github.com/chaotic-aur/packages/files/12484435/picoscope-license.txt)

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

i looked but was unable to find a licence or eula without running the software. considering it is useless without a picoscope i'm not sure that they care.

**Comment by xiota** [comment]
I copied the license from the deb and pasted into a txt file: [picoscope-license.txt](https://github.com/chaotic-aur/packages/files/12484435/picoscope-license.txt)

As far as I can tell, they don't prohibit distribution.  Users don't even need to own a picoscope, as long as they are working with data collected with one:

> The software in this release is for use only with Pico products or with data collected using Pico products.

**Comment by xiota** [comment]
Test packages are available.  Please test and let me know if it works before I add to package lists.

**Comment by maeknight** [comment]
i can confirm that it is working with my picoscope 2204a

![image](https://github.com/chaotic-aur/packages/assets/130556032/13ca909b-0210-4122-8790-c03f883155a0)

**Comment by xiota** [comment]
@maeknight The same maintainer has created `picoscope7` and related packages.  Are you interested in switching to the non-beta packages?

**Comment by maeknight** [comment]
yep, stable would be preferable to early access

**Comment by xiota** [comment]
@maeknight non-beta packages should be available in chaotic for testing.  Please let me know if they're working as expected.  There's no hurry, so take your time to test what you need.

**Comment by maeknight** [comment]
everything is working as expected, thank you again

**Comment by xiota** [comment]
Added non-beta packages to package list.  Will keep beta packages around for a while.
