### ISSUE TITLE
[Request] lib32-gperftools

### ISSUE THREAD

**Issue by otter501** [chaotic-aur/packages#2767]
### Package:

[lib32-gperftools](https://aur.archlinux.org/packages/lib32-gperftools)

### Purpose:

Currently there is an issue with Team Fortress 2 (and i would assume other native games) where you can't play because of the new llvm and this provides the libraries needed to make them work again.

### Benefits:

Allows for Native Linux games to work again

### Building:

makepkg

### Copyright:

BSD

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

Yes

### More information:

I understand that this is a banned package however this is also very useful at the moment, I would hope it would be added and kept in the repository until a fix has come out for these games

also this is how you would use it 
https://www.reddit.com/r/linux_gaming/comments/165pf35/tf2_borked_on_arch_heres_the_solution/

> Install lib32-gperftools from AUR
>
> Use `LD_PRELOAD=/usr/lib32/libtcmalloc.so %command%` as a launch option on Steam

**Comment by xiota** [comment]
Proprietary programs frequently break because Linux libraries are moving targets.

Why not use the Windows version with Proton?

Is there a smaller program that can be used for testing?  TF2 is 25GB.

**Comment by Technetium1** [comment]
[lib32-libunwind](https://archlinux.org/packages/multilib/x86_64/lib32-libunwind/) is out of date. When it's updated, this could be added.

@xiota Half Life 2 likely has the same issue(s), and is only ~6GB. I believe this is worth the exception to our rule, even if only due to the staggering popularity.

**Comment by xiota** [comment]
I think we don't have to wait for `extra/lib32-libunwind` to be updated.  Would just have to rebuild when it is.

I Just ran TF2 tutorial without any problems.  Without `lib32-gperftools`.

@otter501 Have you already tried this to confirm it fixes whatever the issue is?

**Comment by otter501** [comment]
yes, tf2 only works for me if i have it and "LD_PRELOAD=/usr/lib32/libtcmalloc.so %command%" in boot options, otherwise it doesn't boot, its an issue with the newest llvm

**Comment by xiota** [comment]
`lib32-gperftools` isn't building right now (Technetium1 already noticed).  So we have to wait for it to be fixed.
