### ISSUE TITLE
[Rebuild] hyprland-git

### ISSUE THREAD

**Issue by wildan-pratama** [chaotic-aur/packages#2768]
### Packages:

[hyprland-git]
https://aur.archlinux.org/packages/hyprland-git

### Latest chaotic version

0.29.0.r21.f69c5469-1

### Reason for rebuild

Hyprland freeze and crash because this issue
https://github.com/hyprwm/Hyprland/issues/3142

**Comment by xiota** [comment]
`hyprland-git` was last built yesterday.  I don't see anything in that issue that indicates rebuilding will make any difference.

**Comment by Technetium1** [comment]
This should be fixed.

**Comment by xiota** [comment]
Potentially of interest... `hyperland-stable`... #2922
