### ISSUE TITLE
Request: wsdd

### ISSUE THREAD

**Issue by ryester27** [chaotic-aur/packages#277]
Hello. Sorry for making another package request so early, but I do use this program on multiple computers in my network. Can you please add wsdd? Thanks

https://aur.archlinux.org/packages/wsdd/

**Comment by PedroHLC** [comment]
I build yesterday and forgot to update you, sorry...

Please test it, and if it works, feel free to close this issue!

Thanks for your contribution!

**Comment by ryester27** [comment]
This one working fine too. Thanks again
