### ISSUE TITLE
[Request] gpu-screen-recorder-gtk-git

### ISSUE THREAD

**Issue by liljaylj** [chaotic-aur/packages#2770]
### Package:

[gpu-screen-recorder-gtk-git](https://aur.archlinux.org/packages/gpu-screen-recorder-gtk-git)

[gpu-screen-recorder-git](https://aur.archlinux.org/packages/gpu-screen-recorder-git)

### Purpose:

This is a screen recorder that has minimal impact on system performance by recording a window using the GPU only, similar to shadowplay on windows. This is the fastest screen recording tool for Linux.

### Benefits:

This is the fastest screen recording tool for Linux.

This screen recorder can be used for recording your desktop offline, for live streaming and for nvidia shadowplay-like instant replay, where only the last few seconds are saved.

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Switched to custom -git packages because stable packages in AUR are using git versioning.

Note: Custom packages have replaces directive against stable package that will be removed eventually

Metrics:

* gpu-screen-recorder # 1727
* gpu-screen-recorder-gtk # 589
