### ISSUE TITLE
[Rebuild] dxvk-mingw-git

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#2775]
### Packages:

[dxvk-mingw-git](https://aur.archlinux.org/packages/dxvk-mingw-git)

### Latest chaotic version

`2.2.r156.g0746a3b9-1`

### Reason for rebuild

Outdated. Hasn't built for like a month. `2.3` is out now.

### Logs

[dxvk-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/dxvk-git.log)

**Comment by xiota** [comment]
Switched build servers.  Will check later if it builds.

**Comment by xiota** [comment]
Built successfully.  Please comment if there are any other issues.
