### ISSUE TITLE
[Bug] proton-ge-custom permission issue

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#2776]
### Packages:

[proton-ge-custom](https://aur.archlinux.org/packages/proton-ge-custom)

### Latest chaotic version

`2:GE.Proton8.14-2`

### What happens?

When updating from `2:GE.Proton8.13-1` to `2:GE.Proton8.14-2` pacman spammed a bunch of these warnings:
```
warning: directory permissions differ on /usr/share/steam/compatibilitytools.d/proton-ge-custom/files/
filesystem: 755  package: 777
```
Seems like a bunch of stuff was made writable by any user, which seems like a mistake.

This seems to only happen in the ChaoticAUR build.

### What is expected to happen?

Permissions should be like they were in prior versions.

### Logs

[proton-ge-custom.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/proton-ge-custom.log)

### More information

[Also see this comment.](https://aur.archlinux.org/packages/proton-ge-custom#comment-932435)

**Comment by xiota** [comment]
In the future, please just comment on the previous rebuild request, especially since you just opened it yesterday.

**Comment by niobium93** [comment]
Yesterdays request wasn't opened by me and I didn't find it since I was only searching the open issues. Sorry.

**Comment by xiota** [comment]
@niobium93 Sorry, my mistake.  I still prefer messages in old issues, if possible, to prevent proliferation of nearly identical issues.

**Comment by Technetium1** [comment]
@dr460nf1r3 related to lower recreation issue?

**Comment by xiota** [comment]
@niobium93 Package has been rebuilt.  Permissions look okay to me, based on `namcap` and `tar tvf` output.  Don't know why permissions were different in the earlier build.  Please comment if you still have issues with this package.
