### ISSUE TITLE
[Request] nix-init

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2777]
### Package:

[nix-init](https://aur.archlinux.org/packages/nix-init)

### Purpose:

Generate Nix packages from URLs with hash prefetching, dependency inference, license detection, and more

### Benefits:

Automate the creation og Nix packages in order to avoid to do it manually.

### Copyright:

MPL2

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
I need to make an issue upstream for this, there are issues with this release.

**Comment by D3vil0p3r** [comment]
> I need to make an issue upstream for this, there are issues with this release.

Ok, please link me the issue link when created.

**Comment by Technetium1** [comment]
Issue has been opened: https://github.com/nix-community/nix-init/issues/268
