### ISSUE TITLE
[Request] ffcast

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2779]
### Package:

[ffcast](https://aur.archlinux.org/packages/ffcast)

### Purpose:

Run commands on rectangular screen regions.

### Benefits:

It allows to run command on X-based environments inside rectangles (e.g. screenshots, screencast)  that allow to do common tasks.

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
Mistake in commit caused the wrong issue to be closed, it's now fixed.
