### ISSUE TITLE
request: add htop-vim-git

### ISSUE THREAD

**Issue by timescam** [chaotic-aur/packages#278]
https://aur.archlinux.org/htop-vim-git.git

thank you

**Comment by timescam** [comment]
tested, working as intended.
ty

**Comment by xiota** [comment]
@timescam Looks like `htop-vim-git` was never really added before you closed this issue.  You might have mistaken a test build or personal build for a chaotic package.  If you still need this package, please ping me and edit your original request to the follow the current request template.  In particular, I'd like to know what benefit `htop-vim-git` provides over `htop-vim`, which was recently added.
