### ISSUE TITLE
[Request] vundle

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2782]
### Package:

[vundle](https://aur.archlinux.org/packages/vundle)

### Purpose:

Plug-in manager for Vim.

### Benefits:

It allows to manage, also automaticallz, Vim plugins. Very comfortable.

### Copyright:

MIT

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by REmerald** [comment]
@Technetium1 @xiota, would it make more sense to provide [vundle-git](https://aur.archlinux.org/pkgbase/vundle-git) instead?

While both AUR packages haven't been updated for the same looong time, the versioning in the project seem to be abandoned as changes to some of the project's code itself are made after the latest release.
Plus, most importantly, the project tells to use the git version in its [quickstart](https://github.com/VundleVim/Vundle.vim#quick-start).

**Comment by Technetium1** [comment]
That's a good point. There are a lot of changes since the last release! https://github.com/VundleVim/Vundle.vim/compare/v0.10.2...master
