### ISSUE TITLE
[Request] qflipper

### ISSUE THREAD

**Issue by benoliver999** [chaotic-aur/packages#2785]
### Package:

https://aur.archlinux.org/packages/qflipper

### Purpose:

This is used to update [Flipper Zero](https://en.wikipedia.org/wiki/Flipper_Zero) firmware

> Flipper Zero is a portable Tamagotchi-like multi-functional device developed for interaction with access control systems. The device is able to read, copy, and emulate RFID and NFC tags, radio remotes, iButton, and digital access keys, along with a GPIO interface.

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
I recreated the `qflipper` package and added the maintainer of `qflipper-git` as comaintainer.

**Comment by xiota** [comment]
Dropped because moved to extra.  Metrics 210.
