### ISSUE TITLE
[Request] activitywatch-bin

### ISSUE THREAD

**Issue by crestfallnatwork** [chaotic-aur/packages#2786]
### Package:

[activitywatch-bin](https://aur.archlinux.org/packages/activitywatch-bin)

### Purpose:

Automated privacy focused time tracker written in python. Run the binary on user login, works in the background to automatically track time. 

### Benefits:

Fairly popular software, and has a polish that is difficult to find in other opensource time tracking applications. 

### Building:

makepkg

### Copyright:

MPL-2.0

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
We will review this in the future [after a new release], if it's not used by many, it may be removed due to size.

**Comment by xiota** [comment]
Last update 2024-06-10.  Metrics 178.
