### ISSUE TITLE
[Rebuild] chromium-wayland-vaapi

### ISSUE THREAD

**Issue by tankaras** [chaotic-aur/packages#2789]
### Packages:

[chromium-wayland-vaapi](https://aur.archlinux.org/packages/chromium-wayland-vaapi)

### Latest chaotic version

116.0.5845.179-1

### Reason for rebuild

Outdated

**Comment by tankaras** [comment]
Don't know why this is closed as completed when package is still outdated @dr460nf1r3

**Comment by dr460nf1r3** [comment]
Because I saw it getting deployed in the deploy logs:
~~~
> ungoogled-chromium-116.0.5845.179-1-x86_64.pkg.tar.zst
> ungoogled-chromium-116.0.5845.179-1-x86_64.pkg.tar.zst.sig

**Comment by tankaras** [comment]
You are looking at the wrong chromium. Lol.

This is the AUR for the package: https://aur.archlinux.org/packages/chromium-wayland-vaapi

**Comment by dr460nf1r3** [comment]
Oops, how embarassing 😅
