### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Rosalie241** [chaotic-aur/packages#279]
Please add the following packages:

[mingw-w64-qt5-base](https://aur.archlinux.org/packages/mingw-w64-qt5-base/)
[mingw-w64-qt5-base-static](https://aur.archlinux.org/packages/mingw-w64-qt5-base-static)

**Comment by PedroHLC** [comment]
Sorry, we're going through some technical problem and we're rebuilding all 2570 packages. This is automated but will take some time.

I'll probably just add them tomorrow :sweat_smile:

**Comment by PedroHLC** [comment]
I still haven't given up on these two, it's just there are a lot of mingw packages :smile_cat:

**Comment by PedroHLC** [comment]
Ok, solved :smile:
