### ISSUE TITLE
[Bug] Some packages are built against an outdated boost-libs ?

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#2790]
### Packages:

https://archlinux.org/packages/extra/x86_64/boost/

### Latest chaotic version

20230823-1

### What happens?

I am using Manjaro Stable and their boost-libs is at 1.83.0-2 but some chaotic-aur packages are built against the boost-libs 1.81.0 so I get this error when opening some applications:

```
~ >>> easystroke                                                               
easystroke: error while loading shared libraries: libboost_serialization.so.1.81.0: cannot open shared object file: No such file or directory

```

At least that's what I understand. The easystroke package is from the chaotic-aur.

### What is expected to happen?

To work with the latest boost.

**Comment by xiota** [comment]
Following packages are potentially affected.  Bumping.  Will check on build status later.


* [ ] `appimagelauncher`
* [ ] `calamares-git`
* [ ] `chatterino2-7tv-git`
* [ ] `citra-canary-git`
* [ ] `compiz`
* [ ] `compiz-git`
* [ ] `compiz-gtk`
* [ ] `cpod-appimage`
* [ ] `deluge-git`
* [ ] `drkonqi-git`
* [ ] `dwarfs`
* [ ] `easystroke`
* [ ] `emerald-gtk3`
* [ ] `emulationstation`
* [ ] `fastgame-git`
* [ ] `fatrat-git`
* [ ] `fldigi-git`
* [ ] `gr-foo-git`
* [ ] `gr-ieee802-11-git`
* [ ] `hal-git`
* [ ] `jmencode`
* [ ] `kaddressbook-git`
* [ ] `kdepim-addons-git`
* [ ] `kdepim-runtime-git`
* [ ] `kmail-git`
* [ ] `knotes-git`
* [ ] `korganizer-git`
* [ ] `lazarus-beta`
* [ ] `lazarus-beta-gtk3`
* [ ] `lazarus-beta-qt6`
* [ ] `libreoffice-extension-languagetool`
* [ ] `logstalgia`
* [ ] `m64py`
* [ ] `meshlab`
* [ ] `meshlab-git`
* [ ] `miktex`
* [ ] `natron-bin`
* [ ] `natron-compositor`
* [ ] `nextpnr-git`
* [ ] `odr-dabmod-git`
* [ ] `odr-dabmux-git`
* [ ] `olive-git`
* [ ] `openfx-io`
* [ ] `parlatype-libreoffice-extension`
* [ ] `qbittorrent-enhanced`
* [ ] `qbittorrent-enhanced-git`
* [ ] `qbittorrent-enhanced-qt5`
* [ ] `qbittorrent-qt5`
* [ ] `qlog-git`
* [ ] `rstudio-desktop`
* [ ] `shutter-encoder`
* [ ] `snap-pac-grub`
* [ ] `snapper-gui-git`
* [ ] `snapper-support`
* [ ] `spleeter-git`
* [ ] `stumpwm-contrib-git`
* [ ] `sunshine`
* [ ] `syncthingtray`
* [ ] `synfig-dev`
* [ ] `synfigstudio-dev`
* [ ] `themix-theme-materia-git`
* [ ] `wxformbuilder`
* [ ] `yosys-git`
* [ ] `yuzu-early-access`
* [ ] `yuzu-git`
* [ ] `zrythm`

**Comment by xiota** [comment]
@alexjp More KDE packages.  Should I just assume KDE packages aren't meant to be broken and ignore them?

* drkonqi-git
* kaddressbook-git
* kdepim-addons-git
* kdepim-runtime-git
* kmail-git
* knotes-git
* korganizer-git
