### ISSUE TITLE
[Rebuild] sddm-theme-astronaut

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2795]
### Packages:

https://aur.archlinux.org/packages/sddm-theme-astronaut

### Latest chaotic version

1.0-1

### Reason for rebuild

Missing package when running `sudo pacman -S sddm-theme-astronaut`.

**Comment by xiota** [comment]
This was dropped in bbb17bf.  KDE-git packages are currently being reorganized.

**Comment by D3vil0p3r** [comment]
After this reorganization, it will be again rebuilt? When this reorganization will be done?

**Comment by xiota** [comment]
> After this reorganization, it will be again rebuilt?

Should already be done.  If not, wait a day or so.

> When this reorganization will be done?

Don't know.  Lots of inter-related dependencies need to be sorted out.  Many packages were broken, so was decided better to start from scratch.

**Comment by xiota** [comment]
@D3vil0p3r If you're interested in the kde-git reorganization, see #2279.

**Comment by D3vil0p3r** [comment]
> @D3vil0p3r If you're interested in the kde-git reorganization, see #2279.

Thank you very much for the info ^^
