### ISSUE TITLE
[Request] goldwarden

### ISSUE THREAD

**Issue by zany130** [chaotic-aur/packages#2796]
### Package:

https://aur.archlinux.org/packages/goldwarden

### Purpose:

A feature-packed Bitwarden compatible desktop integration

### Copyright:

MIT

### Expected Interest:

Most

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by dr460nf1r3** [comment]
I didn't know about that one yet, seems to be pretty interesting!

**Comment by xiota** [comment]
Dropping because upstream development has been discontinued.  Readme states:

> Development paused indefinitely. Since goldwarden had started, most features have been upstreamed SSH Items, SSH-Agent, Memory Security, Linux Biometric Unlock and FlatHub maintenance.

Metrics 10.
