### ISSUE TITLE
Request: linux-xanmod-lts and linux-xanmod-lts-headers

### ISSUE THREAD

**Issue by OnikenX** [chaotic-aur/packages#280]
requesting the packages:

- linux-xanmod-lts
- linux-xanmod-lts-headers

and thank you very much for the repo 😍

**Comment by PedroHLC** [comment]
The server has encountered some problems during the night and we decided to wipe all packages and rebuild them all fresh.
We'll be adding new packages only after the old ones are all recompiled.
:sweat_smile:  I hope you don't mind waiting, it'll probably finish in less than 48 hs.

**Comment by OnikenX** [comment]
No hurries bro, the server is yours

I'm very thankful for having your server, I don't like to compile big packages with my weak laptop XD

**Comment by ojaksch** [comment]
I 'd also love to see linux-xanmod-lts* packages. Thanks to both of you!

**Comment by PedroHLC** [comment]
I forgot to update that I've added them!
