### ISSUE TITLE
[Request] eartag

### ISSUE THREAD

**Issue by coxackie** [chaotic-aur/packages#2803]
### Package:

https://aur.archlinux.org/packages/eartag

### Purpose:

Simple GTK4 music tag editor. Part of the GNOME Circle apps.

### Copyright:

MIT

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
Still flagged out of date

**Comment by coxackie** [comment]
yeah, the maintainer is not the most attentive. Too bad, by the way... it is as easy as just changing `pkgver=0.4.1` to `pkgver=0.5.0` in the PKGBUILD and it builds perfectly fine. Oh, well...

**Comment by xiota** [comment]
@igor-dyatlov Are you the same as the maintainer of the `aur/eartag` package?
