### ISSUE TITLE
[Request]  howdy

### ISSUE THREAD

**Issue by vixalien** [chaotic-aur/packages#2804]
### Package:

https://aur.archlinux.org/pkgbase/howdy

### Purpose:

The package allows Face ID support on linux machines

### Benefits:

It allows me to login simply using my IR Camera. It integrates (with some steps) with GNOME, KDE etc...

### Building:

makepkg

### Copyright:

MIT

### Expected Interest:

Some

### Already available?

No

### Unique request?

No

### Banned package?

No

**Comment by Technetium1** [comment]
**MUST** use `pam-python-git`

**Comment by Technetium1** [comment]
Unable to add due to `pam-python-git` failing to compile, and inability to use [`pam-python`](https://aur.archlinux.org/packages/pam-python) because of it's python2 dependency.
