### ISSUE TITLE
[Request] Add rofi-lbonn-wayland-git package

### ISSUE THREAD

**Issue by SwayKh** [chaotic-aur/packages#2805]
### Package:

https://aur.archlinux.org/packages/rofi-lbonn-wayland-git

### Purpose:

A window switcher, application launcher and dmenu replacement (fork with Wayland support)

### Benefits:

The -git version of this package seems to the added functionality for window switching

### Building:

makepkg -si ? IDK

### Copyright:

MIT

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

It seems that the `rofi-lbonn-wayland-git` package was removed in favor of `rofi-lbonn-wayland` according to #2569. However the non `-git`  package seems to break the window switching functionality of the package with is an important feature to many.

**Comment by xiota** [comment]
@SwayKh Does the stable version work now?  The git package is failing to build, and I would like to drop it.

**Comment by SwayKh** [comment]
Hi!

Yes, the rofi-wayland package in the extra repo does have the window mode working correctly. I've been using that for quite some time. So feel free to drop this.

And thanks for the awesome work you've done.

**Comment by xiota** [comment]
Feel free to comment if there is a new major bug that warrants reviving this package.
