### ISSUE TITLE
[Request] Rustrover

### ISSUE THREAD

**Issue by diniamo** [chaotic-aur/packages#2808]
### Package:

https://aur.archlinux.org/packages/rustrover

### Purpose:

The latest JetBrains IDE for Rust development.

### Benefits:

Because JetBrains products are all awesome, and in many ways, superior to other IDEs.

### Building:

[Paru](https://github.com/Morganamilo/paru) installed it without any problems.

### Copyright:

Undecided
> We are still working on licensing and pricing for RustRover. RustRover will be a commercial product sold on a subscription basis similar to that of our other IDEs, with a fair pricing structure that reflects the value it provides.

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by FabioLolix** [comment]
Typically Jetbrains programs are unredestributable, this is no different

```
(B) You may not:
(i) Rent, lease, reproduce, modify, adapt, create derivative works of, distribute, sell, or transfer the Product(s);
```

**Comment by diniamo** [comment]
That is unfortunate, but also weird because I only found Rider in the README + I can get some of them _are_ in the chaotic-aur.

Thanks anyway, closing.
