### ISSUE TITLE
[Request] toybox

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2809]
### Package:

https://aur.archlinux.org/packages/toybox

### Purpose:

Single executable that can act like many different Linux command line utilities

### Benefits:

Posix compatible like bash, except it doesn't need any changes like using the builtin set to be 100% posix compliant

### Copyright:

BSD

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Dropping because package was orphaned and adopted by a malicious account.

No compromised commits were built.

This is also of limited usefulness.  Metrics 5.
