### ISSUE TITLE
[Issue] Pacman asking for GPG keys after every reboot

### ISSUE THREAD

**Issue by rgvxsthi** [chaotic-aur/packages#281]
Hi there! Thank you for the amazing repo that is Chaotic. I've been having some trouble lately where after every pacman related command (update/upgrade), it asks me to import Pedro's PGP key. The following is what it asks me to do:
`:: Import PGP key 3056513887B78AEB, "Pedro Henrique Lara Campos <root@pedrohlc.com>"? [Y/n]`

Selecting Yes for the above leads to a missing key error:
`error: required key missing from keyring`
`error: failed to commit transaction (unexpected error)`
`Errors occurred, no packages were upgraded.`

And then I have to manually add the keys again (from Chaotic-AUR''s website):
`sudo pacman-key --keyserver hkp://keyserver.ubuntu.com -r 3056513887B78AEB 8A9E14A07010F7E3`
`sudo pacman-key --lsign-key 3056513887B78AEB`
`sudo pacman-key --lsign-key 8A9E14A07010F7E3`

I've managed to get around the issue by disabling signature check (SigLevel = Never) for Chaotic-AUR, but I'm not exactly sure what's causing the main issue. Any help would be much appreciated.

**Comment by PedroHLC** [comment]
Try the following:
```
sudo rm -rf /etc/pacman.d/gnupg
sudo pacman-key --init
sudo pacman-key --popular archlinux
```
(This will reset your pacman's keyring)

And then what you're used to:
```
sudo pacman-key --keyserver hkp://keyserver.ubuntu.com -r 3056513887B78AEB 8A9E14A07010F7E3
sudo pacman-key --lsign-key 3056513887B78AEB
sudo pacman-key --lsign-key 8A9E14A07010F7E3
```

**Comment by PedroHLC** [comment]
Closing without feedback from issuer...

Feel free to reopen if it has any extra feedback...

**Comment by rgvxsthi** [comment]
Hi Pedro, sorry for the late reply. I managed to fix the issue by installing the "chaotic-keyring" package.
