### ISSUE TITLE
[Request] php-gd

### ISSUE THREAD

**Issue by gpodder770** [chaotic-aur/packages#2810]
### Package:

https://archlinux.org/packages/extra/x86_64/php-gd/

### Purpose:

Its an extension of php
It has uses in packages in laravel
This extension should be included with the php installation in repo

### Copyright:

Not sure

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by FabioLolix** [comment]
That package is already in the Arch repo

**Comment by xiota** [comment]
```
$ pacman -Ss php-gd
extra/php-gd 8.2.10-1
    gd module for PHP
extra/php-legacy-gd 8.1.23-1
    gd module for PHP
```
