### ISSUE TITLE
[Maintenance] Rebuild packages due to abseil-cpp update

### ISSUE THREAD

**Issue by dgudim** [chaotic-aur/packages#2811]
### Packages:

https://aur.archlinux.org/packages/strawberry-qt5

### Latest chaotic version

1.0.18-1.2

### Reason for rebuild

Does not start with: ```strawberry: error while loading shared libraries: libabsl_log_internal_check_op.so.2301.0.0: cannot open shared object file: No such file or directory```

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/strawberry-qt5.log

### Builds?

Install from regular AUR works, didn't change the PKGBUILD

**Comment by FabioLolix** [comment]
btw due to `abseil-cpp` update

**Comment by xiota** [comment]
Bumped `strawberry-qt5`.  Around 470 packages are potentially affected.

**Comment by dr460nf1r3** [comment]
Nice!
