### ISSUE TITLE
[Rebuild] pdfsam

### ISSUE THREAD

**Issue by R-a-l-f** [chaotic-aur/packages#2812]
Hi,

chaotic-aur/jre 21-1 breaks chaotic-aur/pdfsam 5.1.3-1.

Please rebuild pdfsam, see https://aur.archlinux.org/packages/pdfsam#comment-935334 .

By accident I posted the issue already to the wrong place and was told to change the Java environment [1].
I'm using already different jre packages, but no package [2] seems to provide the required version 20 [3].
If users need to build their own jre20 package and their own pdfsam package containing a jre20 wrapper script [4], it doesn't make sense to provide pdfsam by chaotic-aur. However, solving the issue seems to be way easier. Rebuilding the pdfsam package seemingly solves the issue, at least it's claimed by aur comment-935334.

Regards,
Ralf

[1]
https://github.com/chaotic-aur/chaotic-aur.github.io/issues/28

[2]
~~~
$ pacman -Ss jre | grep /jre
extra/jre-openjdk 21.u35-3 [installed]
extra/jre-openjdk-headless 21.u35-3 [installed]
extra/jre11-openjdk 11.0.20.1.u1-1 [installed]
extra/jre11-openjdk-headless 11.0.20.1.u1-1 [installed]
extra/jre17-openjdk 17.0.8.1.u1-1
extra/jre17-openjdk-headless 17.0.8.1.u1-1
extra/jre8-openjdk 8.382.u05-1 [installed]
extra/jre8-openjdk-headless 8.382.u05-1 [installed]
chaotic-aur/jre 21-1 [installed: 20.0.2-1]
chaotic-aur/jre8 8u381-1
~~~

[3]
~~~
$ sudo pacman -Syu jre
[snip]
error: failed to prepare transaction (could not satisfy dependencies)
:: installing jre (21-1) breaks dependency 'java-runtime=20' required by pdfsam
~~~

[4]
https://wiki.archlinux.org/title/Java#Launching_an_application_with_the_non-default_java_version

**Comment by xiota** [comment]
In the future, please follow the issue template.

While waiting for rebuild, you can install and run with `pacman -Sd pdfsam`

**Comment by Technetium1** [comment]
@xiota understandable ✅
