### ISSUE TITLE
[Rebuild] obs-studio-git 30.0.0.beta3-1

### ISSUE THREAD

**Issue by qwerdy** [chaotic-aur/packages#2814]
### Packages:

https://aur.archlinux.org/packages/obs-studio-git

### Latest chaotic version

30.0.0.beta2

### Reason for rebuild

PKGBUILD has been updated with missing dependency https://aur.archlinux.org/cgit/aur.git/commit/?h=obs-studio-git&id=10cb93ba3e0685092e545aad8dc06c0ed4fe51f7

Unsure how all this works, but last build/log is from after PKGBUILD was updated, but still failed. https://builds.garudalinux.org/repos/chaotic-aur/logs/#obs-studio-git (2023-09-24 19:33)

### Logs

....
error: target not found: qrcodegencpp-cmake
....

**Comment by NerosTie** [comment]
`obs-studio-git` is stuck on "rc1" while "rc2" then final 30.0 has been released. I think it should be rebuild again.

**Comment by xiota** [comment]
Package has a broken`pkgver()`.  Notified maintainer via comment.  Adding interfere.

**Comment by xiota** [comment]
I see a lot of `obs-studio-*` packages.  Would someone please explain the differences among them.  If there's no significant difference, I would like to drop some.

**Comment by NerosTie** [comment]
`obs-studio-browser`, `obs-studio-rc` and `obs-studio-tytan652` are all forks maintained by tytan652 using a forked FFmpeg called `ffmpeg-obs`, hard to know the differences.

`obs-studio-git` is the git version as the one on Github. There is a major difference with the one in `extra`: you can use web docks, this function is removed from the package in `extra`

**Comment by xiota** [comment]
`git` version has been rebuilt.  Going to drop the `browser` and `rc` versions, keeping the more popular `tytan652`.

**Comment by xiota** [comment]
The forked ffmpeg-obs has a deletion request [PRQ#49388](https://lists.archlinux.org/hyperkitty/list/aur-requests@lists.archlinux.org/thread/SR7N2FSY4Q5KRICRIVALDHP6IG3YGKNE/#SR7N2FSY4Q5KRICRIVALDHP6IG3YGKNE).  Also noticed some other custom packages, like vlc-luajit.  Not thrilled about the custom packages.

@NerosTie Would you happen to know why web docks is disabled in the extra build?  Making stable builds from git packages via interfere isn't too difficult.  So may be able to provide a web-docks enabled stable build that way.  Would you be willing to test?

**Comment by NerosTie** [comment]
@xiota because there is a CEF dependency and the maintainer don't want to implement it in the [extra] build: https://bugs.archlinux.org/task/66008. 

A stable build with web docks would be nice, yes I can test if needed.

**Comment by xiota** [comment]
@NerosTie `obs-studio-stable` available for testing.  The info about custom CEF you provided was helpful.  Browser is enabled.

VLC support is disabled because want to drop depends on custom package.  Would like to also drop following dependencies, but don't know what features use them.  If I figure it out, will make another test build.

* qrcodegencpp-cmake
* libdatachannel
* libajantv2

**Comment by NerosTie** [comment]
@xiota `obs-studio-stable` works but this part is missing from the PKGBUILD/PKGINFO:

```
provides=("obs-studio=$pkgver")
conflicts=("obs-studio")
```

**Comment by xiota** [comment]
New test build.

* fixed provides/conflicts
* webrtc plugin disabled (libdatachannel)
* aja plugin disabled (libajantv2)
* browser plugin enabled (qrcodegencpp-cmake?)

**Comment by NerosTie** [comment]
It looks fine to me (with libdatachannel and libajantv2 packages removed).

It's a very nice package, it should be added to AUR as well!

**Comment by xiota** [comment]
There are already a lot of `obs-studio-*` packages on AUR.  This may be what -browser was originally meant to be.  Do you have a better name than `obs-studio-stable`?

If you want the PKGBUILD, I can link it here when I update the interferes.

**Comment by NerosTie** [comment]
About `obs-studio-browser`, from a comment of tytan652 (the maintainer): 

> This AUR package provide OBS with all the missing feature **except Twitch, Restream and YouTube integrations**.

And you package provides this. 

I think `obs-studio-stable` is the best name, because it's what is supposed to be and it's the "stable release" from the GitHub repo.

Yes I'm curious about your PKGBUILD, if you can link it.

**Comment by xiota** [comment]
Here's the PKGBUILD: [obs-studio-git/stable](https://github.com/chaotic-aur/interfere/blob/e2a9a8b8008e37c9506d59275db0cb752555c074/obs-studio-git/PKGBUILD.append).

**Comment by NerosTie** [comment]
`obs-studio-stable` should be rebuilt.

Version in chaotic-aur: 30.0.2
Version of official obs: 30.1.1 (https://github.com/obsproject/obs-studio/releases)
