### ISSUE TITLE
[Request] librepcb

### ISSUE THREAD

**Issue by bibliothec** [chaotic-aur/packages#2816]
### Package:

https://aur.archlinux.org/packages/librepcb

### Purpose:

A free EDA software to develop printed circuit boards

### Benefits:

Create electronics the easy way

### Copyright:

GPL

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
@dbrgn Getting an error on check: [librepcb.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/librepcb.log)
```
==> Starting check()...
/home/main-builder/pkgwork/PKGBUILD: line 77:  6151 Aborted                 ./tests/unittests/librepcb-unittests
==> ERROR: A failure occurred in check().
```
I left [a comment](https://aur.archlinux.org/packages/librepcb#comment-937238) to add `git` to makedepends to (maybe?) solve the version error at the start. When given `git` the result changes to: 
```
-- Found Git: /usr/bin/git (found version "2.42.0")
-- Git not found, cannot set version info
```
as well as a new failure (line increment from adding `git`):
```
/home/main-builder/pkgwork/PKGBUILD: line 78:  6162 Aborted                 ./tests/unittests/librepcb-unittests
```
I can't figure out which test is `6151` or `6162`, do you have any idea before I open an issue upstream? https://github.com/LibrePCB/LibrePCB/tree/master/tests/unittests

---

When I build locally, I get this error instead, is there any way to do the check without a display present? If not, we can interfere and skip check…
```
==> Starting check()...
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

/startdir/PKGBUILD: line 77:  6219 Aborted                 (core dumped) ./tests/unittests/librepcb-unittests
==> ERROR: A failure occurred in check().
    Aborting...
```

**Comment by dbrgn** [comment]
Not sure what this repo / project is about. Git is not a build dependency, I left a comment on the AUR page. Regarding the check errors, the check step (unit tests) requires an active X session. You could skip the check step for building though.

**Comment by Technetium1** [comment]
@dbrgn thank you very much! That answers everything I needed!

> Not sure what this repo / project is about

We build things from the AUR automatically: https://aur.chaotic.cx

**Comment by dbrgn** [comment]
> We build things from the AUR automatically: https://aur.chaotic.cx

Thanks for the link!
