### ISSUE TITLE
[Request] kwin-bismuth

### ISSUE THREAD

**Issue by bibliothec** [chaotic-aur/packages#2818]
### Package:

https://aur.archlinux.org/packages/kwin-bismuth

### Purpose:

Addon for KDE Plasma to arrange your windows automatically and switch between them using keyboard shortcuts, like tiling window managers.

### Benefits:

useful for tiling on kde plasma

### Copyright:

MIT

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Use `kwin-polonium`.  See #2587
