### ISSUE TITLE
[Request] xp-pen-tablet 

### ISSUE THREAD

**Issue by bibliothec** [chaotic-aur/packages#2819]
### Package:

https://aur.archlinux.org/packages/xp-pen-tablet

### Purpose:

XP-Pen (Official) Linux utility

### Benefits:

This is important for painter using XP Pen tablet.

### Copyright:

custom

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by FabioLolix** [comment]
The real license isn't LGPL, this isn't open at all, it has been discussed in the comments there

**Comment by bibliothec** [comment]
I modified license
