### ISSUE TITLE
VKD3D Proton Edition

### ISSUE THREAD

**Issue by IroAlexis** [chaotic-aur/packages#282]
Hello Pedro,

Can you add VKD3D Proton Edition please ?
We can see the package on [web page](http://chaotic.bangl.de/chaotic-aur/x86_64/) but pacman can't find it... :disappointed: By using `vkd3d-git`, I don't launch the dx12 games because I build my wine-tkg with the option `_use_vkd3dlib="fork"`.

May be, you no longer build this package because there is some problems with it. Is this possible ?

Thank you for your repo

**Comment by IroAlexis** [comment]
Nice, it's done and I close this issue :+1:

Thank you @PedroHLC

**Comment by PedroHLC** [comment]
:rofl: FYI this one solved automatically!

**Comment by IroAlexis** [comment]
Hmm then what caused this package update ? :thinking: It is when TkG vkd3d Git updates then there is a new build ?
