### ISSUE TITLE
[Request] pixelorama-bin

### ISSUE THREAD

**Issue by bibliothec** [chaotic-aur/packages#2822]
### Package:

https://aur.archlinux.org/packages/pixelorama-bin

### Purpose:

A free & open-source 2D sprite editor, made with the Godot Engine

### Benefits:

editor for pixel art

### Copyright:

MIT

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
```
chaotic-aur/pixelorama 0.11.2-1
    A free & open-source 2D sprite editor
chaotic-aur/pixelorama-git 2226.de7ef580-1
    A free & open-source 2D sprite editor
```

**Comment by xiota** [comment]
@bibliothec I built `pixelorama-bin` because I wanted to compare it with the other packages.  Feel free to download/install it while it's still in the repo.

**Comment by xiota** [comment]
Reopened because the previously provided packages extremely resource intensive to build and currently broken.

**Comment by xiota** [comment]
Switching to custom pixelorama package.  Metrics 130.

**Comment by novadragonDOTspace** [comment]
@xiota  Sorry to annoy here, but aur/pixelorama now uses aur/godot-export-templates-linux

**Comment by xiota** [comment]
@novadragonDOTspace Thanks for notification, but aur/pixelorama still has problems.  Commented on aurweb to notify maintainer.

Will keep custom package because runtime approach is generally better, and it updates automatically for new upstream releases.  Metrics 127.
