### ISSUE TITLE
[Request] ddcci-driver-linux-dkms

### ISSUE THREAD

**Issue by road2react** [chaotic-aur/packages#2828]
### Package:

https://aur.archlinux.org/packages/ddcci-driver-linux-dkms

### Purpose:

It provides a driver to control monitor metadata (brightness, etc) via ddcci protocol

### Copyright:

GPL2

### Expected Interest:

Some

### Already available?

No

### Unique request?

No

### Banned package?

No

**Comment by grantfanian** [comment]
This was a bit late :)
`ddcci-driver-linux-dkms`'s current latest release is broken on kernel 6.8+, DKMS compile fails.
The [fix](https://gitlab.com/ddcci-driver-linux/ddcci-driver-linux/-/merge_requests/15) has already been merged into the upstream's gitlab repository, but without bumping the version. 
[`ddcci-driver-linux-dkms-git`](https://aur.archlinux.org/packages/ddcci-driver-linux-dkms-git) was recently published to the AUR and works.

**Comment by Technetium1** [comment]
Been very busy, and I'm catching up where possible, the patience is appreciated :)
