### ISSUE TITLE
[Request] lightdm-theme-neon

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2830]
### Package:

https://aur.archlinux.org/packages/lightdm-theme-neon

### Purpose:

Modern and customizable theme for web-greeter with a nostalgic neon look. Working with nody-greeter too.

### Copyright:

GPL

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
Build fails: [lightdm-theme-neon.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/lightdm-theme-neon.log)

**Comment by D3vil0p3r** [comment]
I read the error log. How is it possible that makepkg does not extract the .tar.gz file automatically?

**Comment by xiota** [comment]
That PKGBUILD is weird.  It sets up lots of duplicate variables and reassigns them without change.  There are four different variables for the version number, and only one is used to assign to set another one.

The tarball extracts to `$pkgname-$pkgver`, but the PKGBUILD tries to use `$pkgname`, which doesn't exist.  So build fails.

There are several other issues.  Have commented to notify maintainer.

**Comment by D3vil0p3r** [comment]
Ref. https://github.com/hertg/lightdm-neon/issues/15

**Comment by D3vil0p3r** [comment]
@xiota in your opinion could have a sense to package also https://aur.archlinux.org/packages/lightdm-theme-neon-git ?

**Comment by Technetium1** [comment]
@D3vil0p3r shouldn't be a need, they're tagging releases very consistently.
