### ISSUE TITLE
[Request] xdman-beta-bin

### ISSUE THREAD

**Issue by alexoona** [chaotic-aur/packages#2831]
### Package:

https://aur.archlinux.org/packages/xdman-beta-bin

### Purpose:

Open source download accelerator and video downloader.

### Copyright:

GPL2

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by FabioLolix** [comment]
All `xdman8` pkgbuilds on AUR should be renamed to `xdman-beta` or `xdman-dev` since typically adding the number to pkgname is used for legacy version
