### ISSUE TITLE
[Request] ppsspp-git

### ISSUE THREAD

**Issue by NerosTie** [chaotic-aur/packages#2833]
### Package:

https://aur.archlinux.org/pkgbase/ppsspp-git

### Purpose:

The package of PPSSPP in the official repo is very outdated. The last version is 1.15.4 from last May. Version 1.6 is out since the beginning of September but it has not been updated in Arch. The last official version is 1.6.5 released 5 days ago.

### Benefits:

The git version of PPSSPP will provide the last updates to Arch users.

### Copyright:

GPL2

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
This package is now provided via interfere:

* Submodules can be cached, rather than redownload ~1.5GB every build attempt
* No more split packages.  No point separating assets.
