### ISSUE TITLE
[Request] godot-mono-enhanced

### ISSUE THREAD

**Issue by kraddoc** [chaotic-aur/packages#2834]
### Package:

https://aur.archlinux.org/packages/godot-mono-enhanced

### Purpose:

A FOSS game engine with C# support.

### Benefits:

This is a version of already existing godot-mono package, but with improved build files. It uses build arguments from the godot package in the main repo, ensuring similar experiences across version. More detailed description of changes can be found in [this comment](https://aur.archlinux.org/packages/godot-mono#comment-905696).

### Copyright:

MIT

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Looks like `godot-mono-enhanced` is intended to replace `godot-mono`.  From the referenced comment, I'm wondering why the new package wasn't named `godot-dotnet`.

**Comment by xiota** [comment]
Maintainer of `godot-mono-enhanced` is now comaintainer of `godot-mono`.  So switching back to `godot-mono` (#726).
