### ISSUE TITLE
[Bug] error: pop-shell-shortcuts-git: signature from "Pedro Henrique Lara Campos <root@pedrohlc.com>" is invalid

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2835]
### Packages:

https://aur.archlinux.org/packages/pop-shell-shortcuts-git

### Latest chaotic version

1:r30.52cc83f-2.3

### What happens?

When I install the package, I get the following error:
```
error: pop-shell-shortcuts-git: signature from "Pedro Henrique Lara Campos <root@pedrohlc.com>" is invalid
```
In general, if I script the installation of some Chaotic packages, is there a way to manage this kind of issue automatically by specific commands?

### What is expected to happen?

No error related to the signature.

**Comment by Technetium1** [comment]
This was solved by the next build.

**Comment by D3vil0p3r** [comment]
> This was solved by the next build.

I noted that if I change mirror, it works... So I think that some mirror didn't take the applied change.

**Comment by Technetium1** [comment]
@D3vil0p3r did you notice which mirror? Do you maybe have a new mirrorlist as a pacnew file that is unapplied?

**Comment by D3vil0p3r** [comment]
It should be this one `Server = https://cdn-mirror.chaotic.cx/$repo/$arch` because when I commented it, the issue was fixed.

**Comment by Technetium1** [comment]
@D3vil0p3r that's Cloudflare R2, you should be fine to re-enable it. A new package will invalidate the old one. We need to do some signature validation on R2 uploads in the near future, this is one of the examples why!
cc @dr460nf1r3
