### ISSUE TITLE
[Maintenance] Rebuild packages depending on dav1d

### ISSUE THREAD

**Issue by cg00001** [chaotic-aur/packages#2837]
### Packages:

kodi-git

### Latest chaotic version

`r64120.df97ff523a9-1`

### Reason for rebuild

Doesn't run.
System says libdav1d.so=7-64 , while running kodi via a terminal I get the error:
`/usr/lib/kodi/kodi.bin: error while loading shared libraries: libdav1d.so.6: cannot open shared object file: No such file or directory`

### More information

On a similar issue in the past with another library I opened an issue in xbmc, and a dev explained a binary would have to be rebuilt, since the internals were updated and manual building worked.

**Comment by xiota** [comment]
Bumping following packages with same issue:
```
chromium-wayland-vaapi
cinelerra-gg
ffmpeg-full
ffmpeg-obs
kodi-git
kodi-nexus-git
```
Let me know if there are any others.

**Comment by cg00001** [comment]
Thanks a million, kodi-git works fine -sadly I don't use the rest.
