### ISSUE TITLE
[Request] web-greeter

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2838]
### Package:

https://aur.archlinux.org/packages/web-greeter

### Purpose:

A modern, visually appealing greeter for LightDM. Similar to nody-greeter but made in Python and QT5. It is a replacement of the non-maintained Antergos web-greeter.

### Benefits:

LightDM webkit2-greeter is not longer maintained and the latest update of webkit-gtk broke it. web-greeter allows to create or use themes that are based on similar approach of webkit2 allowing users to set interactive themes in LightDM.

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Dropping because requires EOL Qt5.  In particular, qt5-webengine was dropped from extra.  Metrics 32.

Feel free to comment to request re-add if updated to Qt6, or open a new issue if there's an alternative using up-to-date libraries.
