### ISSUE TITLE
[Request] mongodb

### ISSUE THREAD

**Issue by crabvk** [chaotic-aur/packages#2840]
### Package:

https://aur.archlinux.org/packages/mongodb

Optional:
https://aur.archlinux.org/packages/mongosh # opt
... https://aur.archlinux.org/packages/libmongocrypt
https://aur.archlinux.org/packages/mongodb-tools # opt

### Purpose:

MongoDB is a popular NoSQL document database. It is used to build highly available and scalable internet applications.

### Benefits:

As [mentioned in the Arch wiki](https://wiki.archlinux.org/title/MongoDB) [mongodb-bin](https://aur.archlinux.org/packages/mongodb-bin/)'s compilation options used are unknown.

### Building:

Had built in a clean chroot with `buildpkg -r /chroot` successfully.

### Copyright:

Server Side Public License (SSPL)
https://www.mongodb.com/licensing/server-side-public-license

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
We should be sure to build optdeps for this as well

**Comment by D3vil0p3r** [comment]
What about to consider this package @xiota ? I am interested too. Thanks ^^

**Comment by dr460nf1r3** [comment]
Mongodb is a quite known database so I see no reason to not go for it. Haven't checked PKGBUILD yet tho.

**Comment by D3vil0p3r** [comment]
@dr460nf1r3 just take care about the building, give a look to the comments: https://aur.archlinux.org/packages/mongodb

**Comment by FabioLolix** [comment]
It is a burden to build, early comments from 2019

> You need to have at least ~160GB free disk space and several hours to compile source code. 

> 87GB free on disk. 16 hours of compiling and it ends due to no free space (used all 87GB).

https://aur.archlinux.org/packages/mongodb?all_reqs=1&O=130#comment-678525

https://aur.archlinux.org/packages/mongodb?all_reqs=1&O=130#comment-679272

**Comment by D3vil0p3r** [comment]
According to the latest comment of the maintainer, the building time seems to depend on RAM amount and assigned threads. Btw it is suggested to use at least 32 GB RAM.

**Comment by D3vil0p3r** [comment]
@xiota just a curiosity: which hardware did you use to compile it and how much time it required? On `/etc/makepkg.conf` did you do some changes?

**Comment by xiota** [comment]
> 87GB free on disk. 16 hours of compiling and it ends due to no free space (used all 87GB).

Might have to move to different server.  Will find out when package is next updated.

**Comment by Technetium1** [comment]
@xiota beat me to it by a few hours! If the next build fails, it can be in a daily routine with a separator.

**Comment by dr460nf1r3** [comment]
I'd prefer ufscar daily for such heavy packages. While it should be possible on the Garuda cluster in general, ufscar has dedicated nodes for the build process and doesn't share resources with other stuff.
