### ISSUE TITLE
[Remove] gnome-shell-extension-arc-menu-git

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2841]
### Package:

https://aur.archlinux.org/packages/gnome-shell-extension-arc-menu-git

### Purpose:

GNOME extension to add a menu like XFCE or standard menu.

### Benefits:

Chaotic has already a non git package. The -git package could allow to get the most updates from the project.

### Copyright:

GPL2

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
@D3vil0p3r The wording of some of your requests for -git packages looks like you want to just make them available, not actually use them.  I'd prefer no more "just make available" requests because it's extra maintenance burden.  I'd rather requests come from people who actually want to use them.

Package is missing `provides`.

**Comment by D3vil0p3r** [comment]
Thank you for the answer @xiota 
In reality, I would use it because the non -git pkg was not asked by me and I needed the -git package for the Arch environment I'm developing.

**Comment by D3vil0p3r** [comment]
> Considering dropping. Package failing to build because of bad commit. AUR maintainer ignored comment from 2023-10-10. No significant difference from stable package in `extra`. Recent releases were tagged after not many commits.

I open a orphan request.

**Comment by xiota** [comment]
To clarify, the bad commit is an upstream issue.  Ignored comment from last year was about adding `provides`.  Now `license` needs to be updated.

**Comment by D3vil0p3r** [comment]
I see the last update of the maintainer upstream was 2 hours. I remember that the upstream maintainer is very available. Can you open an issue on its gitlab repo to report the build issue about bad commit you are encountering? https://gitlab.com/arcmenu/ArcMenu/-/issues

**Comment by xiota** [comment]
@D3vil0p3r Previous maintainer disowned.  I adopted, and will update.  Will consider opening upstream issue afterward.  Can add you as comaintainer (and eventually disown) if you intended to maintain the package.

**Comment by D3vil0p3r** [comment]
Sure

**Comment by xiota** [comment]
@D3vil0p3r Added you as comaintainer.  Opened an upstream issue.  Package is updated with bad commit reverted until upstream fixes it.  You should close the orphan request.

**Comment by D3vil0p3r** [comment]
> @D3vil0p3r Added you as comaintainer. Opened an upstream issue. Package is updated. You should close the orphan request.
> 
> Update: Upstream fixed issue.

I installed the package from the latest commit but the menu does not appear on the top bar now... Not sure if there is a bug upstream. I'm using GNOME 46.

**Comment by xiota** [comment]
@D3vil0p3r Thanks for reporting/fixing/updating.  One minor point... Take a look at the end of the diff [72647ec](https://aur.archlinux.org/cgit/aur.git/commit/?h=gnome-shell-extension-arc-menu-git&id=72647ece6afc440d6385ba74625ba81d46be1aec).

It says `\ No newline at end of file`.  Unix text files are supposed to end with empty line, and missing newline has caused problems with some packages.  There's no need to change the package, but you should configure your text editor to end files with newline.

**Comment by D3vil0p3r** [comment]
Thank you for reporting it. Just to be compliant, I can fix it.

**Comment by xiota** [comment]
The newline can be added to the package the next time it needs to be updated for something else.  The main thing is to reconfigure your text editor.  It's actually surprising any editor on Linux allows to leave it out.

**Comment by xiota** [comment]
Dropping because `extra/gnome-shell-extension-arc-menu` is available.  Currently no difference between stable and git versions.  Metrics 48.
