### ISSUE TITLE
[Request] impression

### ISSUE THREAD

**Issue by vixalien** [chaotic-aur/packages#2842]
### Package:

https://aur.archlinux.org/packages/impression

### Purpose:

A straight-forward modern application to create bootable drives. It allows to flash ISO images to USB drives.

### Benefits:

- It integrates well with GNOME
- It's painfully simple and straight-forward
- Fast

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Why not use Ventoy?

**Comment by vixalien** [comment]
as far as I remember, Ventoy allows you to boot directly from an ISO which is stored on an external disk.

Impression is more of a disk-flashing tool like Rufus from Windows or balenaEtcher. The app is also part of the [GNOME Circle](https://apps.gnome.org/Impression/)

**Comment by Technetium1** [comment]
@vixalien same results are possible with Ventoy booting raw images, as well as many other features. It's worth looking more into someday: https://www.ventoy.net/en/index.html

**Comment by vixalien** [comment]
thanks!

**Comment by xiota** [comment]
> Impression is more of a disk-flashing tool

Flashing USB drives and and memory cards tends to shorten their lifespan.

**Comment by xiota** [comment]
Planning to drop for poor maintainership.  Package installs icons to location likely to conflict with other packages (`/usr/share/icons/hicolor/scalable/actions/`) and does have files conflicting with `aur/footage`.  Maintainer was notified a month ago and did not reply or fix the issue.  There is also no shortage of tools to flash USB drives.

**Comment by vixalien** [comment]
for completeness, I've notified upstream: https://gitlab.com/adhami3310/Impression/-/issues/34

**Comment by xiota** [comment]
I won't drop this right away.  It will stay if it's fixed by the time it next comes to my attention.  (Estimate about a month.)

**Comment by xiota** [comment]
New release last week appears to fix the file conflicts.
