### ISSUE TITLE
[Request] crab-hole

### ISSUE THREAD

**Issue by LuckyTurtleDev** [chaotic-aur/packages#2848]
### Package:

https://aur.archlinux.org/packages/crab-hole

### Purpose:

Crab-hole is a cross platform Pi-hole clone written in rust using [hickory-dns/trust-dns](https://github.com/hickory-dns/hickory-dns). It can be use as a network wide Ad and spy blocker or run on your local pc.

For a secure and private communication carb-hole has buildin support for doh(https), doq(quic) and dot(tls) for down- and upstreams and dnssec for upstreams.

### Building:

`makepkg -fid`

### Copyright:

AGPL

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
Neat project https://github.com/LuckyTurtleDev/crab-hole
