### ISSUE TITLE
[Request] incus

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#2852]
### Package:

[incus](https://aur.archlinux.org/packages/incus)

### Purpose:

Fork of LXD

### Benefits:

Not owned by Canonical

### Building:

Requires interfere and `cowsql-git`

### Copyright:

[Apache-2.0 license](https://github.com/lxc/incus/blob/main/COPYING)

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Requested by `ShalokShalom` on Forum

**Comment by xiota** [comment]
`cowsql-git` not needed.  It's at the same commit as `extra/cowsql`.

Seems to build without `ebtables`.  Did not test functionality (don't know how).  Might be a runtime-only dependency?

**Comment by Technetium1** [comment]
- Nice surprise, `cowsql` didn't exist until a [week after](https://gitlab.archlinux.org/archlinux/packaging/packages/cowsql/-/commit/34bb846e34a93e1d36d975a068d9959b7807e25b) creating the issue 😄
- Let's wait until the next tagged release since it's imminent https://github.com/lxc/incus/commit/0a5f3e4fd588d63c79c2a0fb3d17bf82fa4ad6aa
- `iptables`/`ebtables` _seems_ to be runtime dependency only per [results in search](https://github.com/search?q=repo%3Alxc%2Fincus%20iptables&type=code) and lack of a check in [Makefile](https://github.com/lxc/incus/blob/main/Makefile)

**Comment by xiota** [comment]
`cowsql` has no dependents other than `aur/incus`.  Could an Arch TU/PM be looking at adding it to `extra`?

**Comment by Technetium1** [comment]
@xiota It is a very strong possibility!

**Comment by xiota** [comment]
My test build (without ebtables dep) is in the repo if anyone wants to try it.

If Arch is going to add it, I hope they don't wait until moments after it's added to the chaotic package list.

**Comment by xiota** [comment]
Confirmed [`incus` is planned for eventual inclusion in `extra`](https://aur.archlinux.org/packages/incus#comment-942620).

@Technetium1 Is keeping the test build in the repo, without adding to the package lists, satisfactory?

**Comment by Technetium1** [comment]
@xiota Fantastic news! Yes, that is a valid solution. Let us leave this issue open until it shows up in extra 🥳

**Comment by xiota** [comment]
Package was deleted from AUR ([PRQ#52404](https://lists.archlinux.org/hyperkitty/list/aur-requests@lists.archlinux.org/thread/NVK7A4J4RBQA2LYQAZGJMVKS4ZRQYXW2)) and moved to [`extra-testing/incus`](https://archlinux.org/packages/extra-testing/x86_64/incus/).
