### ISSUE TITLE
[Bug] freedoom and freedm packages don't match the AUR. Seem to be dummy packages to force upgrade to the *-git versions.

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#2854]
### Packages:

[freedoom](https://aur.archlinux.org/packages/freedoom)

### Latest chaotic version

`0.12.1-5`, but AUR only has `pkgrel=4`

### What happens?

`freedoom` and `freedm` packages don't match the AUR. Seem to be dummy packages to force upgrade to the *-git versions.

### What is expected to happen?

The packages should match the AUR. It should be the stable version of `freedoom`. Failing this, the package shouldn't be in the repo at all, because it overrides locally built packages and forces users into the `*-git` variant of the packages.

### Logs

Missing. Only logs for the `freedoom-git` package exist.

**Comment by xiota** [comment]
`aur/freedoom` is currently broken.  The metapackage is intended to help users migrate to working packages.  They are planned for removal in a few weeks.  I've changed the versions to `0.0.1` so that users will be alerted to a "downgrade".

**Comment by yum13241** [comment]
OOOORRRR just make your own DOOMWADDIR.

**Comment by xiota** [comment]
`freedm` and `freedoom` metapackages no longer in repo.
