### ISSUE TITLE
[Request] swift-bin

### ISSUE THREAD

**Issue by asdfzxcvbn** [chaotic-aur/packages#2855]
### Package:

https://aur.archlinux.org/pkgbase/swift-bin

### Purpose:

compiled binary of the [swift programming language](https://github.com/apple/swift)

### Copyright:

[Apache License 2.0](https://github.com/apple/swift/blob/main/LICENSE.txt)

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Related #799

**Comment by Technetium1** [comment]
I strongly dislike that it requires older Python as optdep to enable repl. We can (and should) wait until it's updated to use a non-EOL version of Python. Until then, we provide already provide `swift-language` through the linked issue above.

**Comment by xiota** [comment]
I never succeeded in getting `swift-language` to build.

**Comment by Technetium1** [comment]
Let's see if it's possible to use a version of Python that isn't EOL. Need to look into what upstream uses & expects.

**Comment by xiota** [comment]
`swift-bin` is in the repo, but not added to lists, because I was curious.
```
Download Size   : 525.78 MiB
Installed Size  : 1843.28 MiB
```

**Comment by asdfzxcvbn** [comment]
> `swift-bin` is in the repo, but not added to lists, because I was curious. @asdfzxcvbn Feel free to install it before someone removes it.
> 
> ```
> Download Size   : 525.78 MiB
> Installed Size  : 1843.28 MiB
> ```

works, thanks

**Comment by xiota** [comment]
Decided to keep `swift-bin`.  Switching to `swift-language` doesn't make sense because swift needs swift to build.  So to bootstrap requires `swift-bin`.  Then if it breaks, `swift-bin` is needed again.  So might as well stick with `swift-bin`.
