### ISSUE TITLE
[Rebuild]  hyprland-git

### ISSUE THREAD

**Issue by romanstingler** [chaotic-aur/packages#2856]
### Packages:

https://aur.archlinux.org/packages/hyprland-git

### Latest chaotic version

0.30.0.r86.424c9a7e-1

### Reason for rebuild

Outdated

**Comment by xiota** [comment]
Commented on aur page to notify maintainer.  Rebuilding with modified PKGBUILD.
```
meson.build:2:12: ERROR: Program or command 'jq' not found or not executable
```

**Comment by xiota** [comment]
Potentially of interest... `hyperland-stable`... #2922
