### ISSUE TITLE
[Rebuild] kotatogram-desktop-beta-dynamic-bin

### ISSUE THREAD

**Issue by dreirund** [chaotic-aur/packages#2857]
### Packages:

https://aur.archlinux.org/packages/kotatogram-desktop-beta-dynamic-bin

### Latest chaotic version

1.4.9-5.2

### Reason for rebuild

It needs recompilation to be compiled against updated `abseil-cpp` version 20230802.1-1:

`kotatogram-desktop` fails with  
```
kotatogram-desktop: error while loading shared libraries: libabsl_strings.so.2301.0.0: cannot open shared object file: No such file or directory
```

Present is `/usr/lib/libabsl_strings.so.2308.0.0`.

Regards!

**Comment by xiota** [comment]
This is a bin package.  Rebuild is unlikely to do anything useful.  Comment on the AUR package page.  If the maintainer can adjust the package to resolve the issue, the update should trigger an automatic rebuild.

**Comment by xiota** [comment]
The original maintainer appears to no longer be building binaries.  Package is being retired and dropped.  Switch to `kotatogram-desktop-bin`, which uses binaries provided by the project developers.
