### ISSUE TITLE
[PSA] What to do when packages are broken because of upstream name changes?

### ISSUE THREAD

**Issue by xiota** [chaotic-aur/packages#2858]
Upstream is currently renaming packages related to KDE and Qt 5.  This will affect a lot of AUR packages.

* Before reporting the issue on GitHub, check to see if the AUR package has been updated.
   - If not and no one has commented to notify the maintainer, leave a comment on the AUR page.
* Then wait for the maintainer to update the package.
* After the AUR package is updated, wait a day or so for chaotic build servers to pick up the change.
   - If you still don't see the new package, check the [build logs](https://builds.garudalinux.org/repos/chaotic-aur/logs/) or leave a comment here.

Notes / Updates:

* Do not add comments or flag if someone else already has within the last 1-2 weeks.  Multiple comments within such a short period of time is not helpful to maintainers.
* I have left flags/comments on the affected packages in chaotic-aur that I could find.
* As of 2021-11-05, there is a dummy package `chaotic-kf5-dummy` that "provides" the missing kf5 packages.  While it will allow packages to be installed and upgraded, it does not provide any real functionality.  The *real* packages still need to be installed separately.

**Comment by xiota** [comment]
I do not plan to fix kf5-related issues via interfere until at least late Nov.  Doing so makes tracking the broken packages difficult and amounts to giving up on an upstream fix.

A potential solution is to create a dummy package that can fill the dependency gap and be used for tracking.  Thoughts? @dr460nf1r3 @Technetium1

**Comment by Technetium1** [comment]
@xiota any downsides to outweigh upsides?

**Comment by xiota** [comment]
Dummy packages would allow `pacman` to install and upgrade packages without complaining.  The programs would work as long as the real dependencies are installed.  Users can create virtual packages themselves with `pacman -S --assume-installed [package_name]`.

Some potential problems:
* Unnecessary bug reports from users confused about the purpose of the new package.
* Less obvious what's wrong with broken packages.
* Less obvious broken packages are broken.
    - Fewer reports to maintainers.
    - Less motivation for maintainers to fix packages.
* The dummy package would eventually have to be dropped.
    - The original problem would return for packages that still haven't been fixed.
    - Users would have to remove the dummy package on their own.  This happens with all dropped packages.  The only way I know of to force their remove is with `replaces` in another package.  But that just moves the problem to a different package.  Maybe could create a package `chaotic-garbage-collector` to do clean-up...  But would have similar issues as other dummy packages.
* May be other problems?

**Comment by xiota** [comment]
Not all packages need to use the new package names.  For instance, `-git` packages that have already dropped KF5 support should wait for KF6 packages to become available.  They are candidates for removal from chaotic-aur.

Here are the affected packages that I'm aware of.

* [ ] audiotube-git
* [ ] basket-git
* [ ] calamares-git
* [ ] disman-kwinft
* [ ] kcm-imchooser-frameworks
* [ ] kcm-lookandfeel-standalone-git
* [ ] kcm-polkit-kde-git
* [ ] kcm-tablet-git
* [ ] kcm-uefi
* [ ] kdenlive-stabledeps-git
* [ ] kdisplay-kwinft
* [ ] kwinft
* [ ] lightly-boehs-git
* [ ] material-kwin-decoration-git
* [ ] maui-core-git
* [ ] maui-shell-git
* [ ] mauikit-calendar-git
* [ ] nextcloud-client-git
* [ ] nx-firewall-git
* [ ] pikasso-git
* [ ] polkit-dumb-agent-git
* [ ] systray-x-git
* [ ] tokodon-git
* [ ] wrapland-kwinft

The following are also affected, but have optional KF5 dependencies.  Updating them is not urgent.

* chromium
* chromium-snapshot-bin
* chromium-wayland-vaapi
* gajim-git
* git-credential-manager-core-bin
* google-chrome
* google-chrome-beta
* google-chrome-dev
* libreoffice-dev-bin
* microsoft-edge-beta-bin
* microsoft-edge-dev-bin
* microsoft-edge-stable-bin
* nheko-git
* p7zip-gui
* qimgv-git
* snapper-gui-git
* ungoogled-chromium
* vlc
* vlc-luajit
* vlc-wayland-git
