### ISSUE TITLE
[Request] kwin-scripts-truely-maximized

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2860]
### Package:

https://aur.archlinux.org/packages/kwin-scripts-truely-maximized

### Purpose:

A Kwin script that truely maximizes your screen space by hiding the title bars of your windows when they are maximized.

### Benefits:

Very comfortable for managing windows of your KDE environment.

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
How is this any better than setting [BorderlessMaximizedWindows=true](https://wiki.archlinux.org/title/KDE#Space_efficiency)?

**Comment by D3vil0p3r** [comment]
> How is this any better than setting [BorderlessMaximizedWindows=true](https://wiki.archlinux.org/title/KDE#Space_efficiency)?

The tool on the pkg allows the user to hide the window title when maximized. It is useful when the user has a top bar, mostly when the top bar is managed by **windowtitle** applet. `BorderlessMaximizedWindows` cannot do that.

**Comment by xiota** [comment]
Hiding the titlebar of maximized windows is exactly what the `BorderlessMaximizedWindows` option does.

**Comment by D3vil0p3r** [comment]
> Hiding the titlebar of maximized windows is exactly what the `BorderlessMaximizedWindows` option does.

I tested it. It does not seem to do that.

**Comment by xiota** [comment]
@alexjp As the KDE expert... your opinion?

**Comment by D3vil0p3r** [comment]
Need to understand if `BorderlessMaximizedWindows` covers the following aspects of this kwin script:
```
Dynamically hides/shows window titles based on maximization (yes)
Automatically filters out potential breakages (e.g. GTK applications)
Configurable blacklist
Optional screen edge listener to toggle it off/on in case you need the title bar for a moment
```

**Comment by xiota** [comment]
Blacklist GTK and other apps with KWin Window Rules.

Edge listener.  No.  But you can assign a shortcut to a script to toggle on and off:
```
#!/usr/bin/env bash
if [ `kreadconfig5 --file ~/.config/kwinrc --group Windows --key BorderlessMaximizedWindows` == "true" ] ; then
  kwriteconfig5 --file ~/.config/kwinrc --group Windows --key BorderlessMaximizedWindows false
else
  kwriteconfig5 --file ~/.config/kwinrc --group Windows --key BorderlessMaximizedWindows true
fi
qdbus org.kde.KWin /KWin reconfigure
```

**Comment by D3vil0p3r** [comment]
@xiota https://github.com/fin444/truely-maximized/issues/3

**Comment by D3vil0p3r** [comment]
I'm doing some tests and I noted that if I run:
```
kwriteconfig5 --file ~/.config/kwinrc --group Windows --key BorderlessMaximizedWindows true
qdbus org.kde.KWin /KWin reconfigure
```
or I add in '~/.config/kwinrc` the content:
```
[Windows]
BorderlessMaximizedWindows=true
```
and then `qdbus org.kde.KWin /KWin reconfigure`, it works.

The problem is: when I logout and I re-login again, in `~/.config/kwinrc` I get:
```
[Windows]
BorderlessMaximizedWindows=false
```
while with the proposed package it does not occur. Not clear if it is a bug of `BorderlessMaximizedWindows`.

**Comment by alexjp** [comment]
> @alexjp As the KDE expert... your opinion?

My memory is a little vague on this one, since I ... always hide the titlebars :)

I know some window decorations have this option (hide titlebar when maximized) and I know latte-dock did this too (by setting the kwin option).

Anyway, I don't see any harm in including it (as it has other options as in the linked issue), as long as the AUR package is well mantained.

**Comment by xiota** [comment]
@D3vil0p3r You probably have some other plugin/widget/script/etc that is managing the option.

**Comment by alexjp** [comment]
Added to nightly: https://github.com/chaotic-aur/packages/commit/6ac8d67a4c5d20b63d30c69ae9fe14e998ab343f

**Comment by D3vil0p3r** [comment]
> Added to nightly: https://github.com/chaotic-aur/packages/commit/6ac8d67a4c5d20b63d30c69ae9fe14e998ab343f

What is nightly in this case?

**Comment by Technetium1** [comment]
@D3vil0p3r it's a routine that [runs nightly](https://github.com/chaotic-aur/toolbox/blob/main/services/chaotic-nightly.timer).
