### ISSUE TITLE
[Request] Lightly theme, and other 5 apps

### ISSUE THREAD

**Issue by fabianski7** [chaotic-aur/packages#287]
`lightly-git`
`lightly-qt`

**Comment by fabianski7** [comment]
taking the opportunity 🤭

`straw-viewer-git`
`snapcast`
`qmplay2-git`
`qmplay2`
`octopi-notifier-qt5`
`octopi-notifier-frameworks`

all are working. I built each one of them.

**Comment by PedroHLC** [comment]
24 days later, sorry for the delay :eyes: 
It's done!

**Comment by xiota** [comment]
Switching to `darkly-git` because development on Lightly has been stagnant and the [Bali10050](https://github.com/Bali10050/Darkly) fork is rebranding to Darkly.  Metrics:

* lightly-kf5-git # 110
* lightly-kf6-git # 82
* lightly-qt5-git # 70
* lightly-qt6-git # 93

**Comment by xiota** [comment]
darkly-git qt5 and qt6 packages have been separated.  The qt5 package will be dropped.

Metrics:

* darkly-qt5-git # 112
* darkly-qt6-git # 443
