### ISSUE TITLE
[Bug] kotatogram-dev-git: Dependency `kwayland` needs to be changed to `kwayland5`.

### ISSUE THREAD

**Issue by dreirund** [chaotic-aur/packages#2871]
### Packages:

https://aur.archlinux.org/packages/kotatogram-dev-git

### Latest chaotic version

`k1.4.9.r2.g52b300cb3-1.1`

### What happens?

[Dependencies need to be updated since packages got renamed in Arch:](https://aur.archlinux.org/packages/kotatogram-dev-git#comment-940044)

* [`kwayland` &rarr; `kwayland5`](https://aur.archlinux.org/packages/kotatogram-dev-git#comment-940044)

[Regards!](https://aur.archlinux.org/packages/kotatogram-dev-git#comment-940044)

### What is expected to happen?

Have correct dependencies

### More information

Upgrade fails with  
```
:: installing kwayland5 (5.111.0-1) breaks dependency 'kwayland' required by kotatogram-dev-git
```  
since Arch Linux previously renamed `kwayland` to `kwayland5` and now removed the `provides=(kwayland)`-entry from `kwayland5`.

**Comment by xiota** [comment]
@dreirund Please see #2858.

**Comment by dreirund** [comment]
> *@dreirund Please see #2858.*

So I am closing this as irrelevant.  
Regards and thanks!
