### ISSUE TITLE
[Request] ytdl-shim, youtube-dl-git

### ISSUE THREAD

**Issue by xiota** [chaotic-aur/packages#2874]
**Package:**

https://aur.archlinux.org/packages/ytdl-shim

¿¿¿ https://aur.archlinux.org/packages/youtube-dl-git ??? – Some programs won't work with `yt-dlp`.

**Description:**

While I would rather drop packages that depend on `youtube-dl`, several in the `extra` repository also depend on it.  So it would be beneficial to provide a replacement.

`aur/yt-dlp-drop-in` is not suitable because it is only a shell script that does not cover python imports.  The maintainers appear to be MIA.  They have not responded to any of numerous comments over the last six months.

For reference, here is a list of packages that currently depend on `youtube-dl`.  Required are bolded.  The rest are optional.

`chaotic-aur`:
* celluloid-git [#741](https://github.com/chaotic-aur/packages/issues/741)
* ~~**copypastegrab-git**~~ [#1745](https://github.com/chaotic-aur/packages/issues/1745)
* gallery-dl [828](https://github.com/chaotic-aur/packages/issues/828)
* kawaii-player [#378](https://github.com/chaotic-aur/packages/issues/378)
* lollypop-git [#562](https://github.com/chaotic-aur/packages/issues/562)
* media-downloader [1592](https://github.com/chaotic-aur/packages/issues/1592)
* mpv-full
* mpv-full-git
* mpv-vapoursynth-git [#741](https://github.com/chaotic-aur/packages/issues/741)
* ~~**persepolis-git**~~ [#2041](https://github.com/chaotic-aur/packages/issues/2041)
* pipe-viewer-git [#485](https://github.com/chaotic-aur/packages/issues/485)
* **qytdl**
* smtube [#2382](https://github.com/chaotic-aur/packages/issues/2382)
* soundux [#514](https://github.com/chaotic-aur/packages/issues/514)
* yt-dlg-git [#1538](https://github.com/chaotic-aur/packages/issues/1538)

`extra`:
* baka-mplayer
* gpodder
* lollypop
* mpv
* **persepolis**
* smplayer

**Comment by Technetium1** [comment]
@xiota Great! Yes that's plenty enough to justify, esp due to size and fast builds. I think they should be hourly.

**Comment by xiota** [comment]
Dropping qytdl because not updated for Qt6.
