### ISSUE TITLE
[Request] librealsense-legacy

### ISSUE THREAD

**Issue by alexojegu** [chaotic-aur/packages#2875]
### Package:

https://aur.archlinux.org/packages/librealsense-legacy

### Purpose:

Support Intel RealSense F200, SR300, R200, LR200 and the ZR300 cameras.

### Benefits:

Only package to full support hardware Intel RealSense F200, SR300, R200, LR200 and the ZR300 cameras.

### Copyright:

Apache

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
How is this package used?  How does it work?

The name suggests it's a library, but the aur page lists no dependents.

**Comment by alexojegu** [comment]
Honestly I've never used it. It can be used for example with [Open3D](http://www.open3d.org/docs/0.12.0/tutorial/sensor/realsense.html), but I'm looking for something easier to use. If you want, I can close the issue and reopen it when I find the right application (I'm having more trouble than I expected finding one that works on Linux)

**Comment by xiota** [comment]
Leave this open.  Maybe someone else has or finds a solution and comments.

Have you already built this yourself, or do you need a test package built?

**Comment by alexojegu** [comment]
Not yet, but I can create it myself when I get some time.

**Comment by Technetium1** [comment]
This has been lingering for a long time with no change, and it only supports cameras which will have very few users. Since this seems unlikely to change, it can be closed for now and explored again in the future if needed.
