### ISSUE TITLE
[Request] python-onnxruntime

### ISSUE THREAD

**Issue by Jcuhfehl** [chaotic-aur/packages#2876]
### Package:

https://aur.archlinux.org/packages/python-onnxruntime

### Purpose:

Used as a runtime some machine learning/llm stuff

### Copyright:

MIT

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by FabioLolix** [comment]
It have a couple of depends on AUR (nsync, python-coloredlogs) and some optdepends too (python-py3nvml, python-onnx, python-transformers)

**Comment by xiota** [comment]
> some machine learning/llm stuff

What program do you need this for?

**Comment by Technetium1** [comment]
@xiota Could be used for training, inference, and even quantization acceleration, as seen [here in 2.2](https://github.com/microsoft/onnxruntime-inference-examples/blob/main/quantization/notebooks/bert/Bert-GLUE_OnnxRuntime_quantization.ipynb). Definitely nice to provide Python bindings.

**Comment by xiota** [comment]
@Technetium1 This falls under dependency without any dependents.

There are *a lot* of python modules related to AI.  Don't really want to add *all* of them.  Someone asked that all related packages be added to an AI-related modules' optdeps.  Don't remember how many hundreds of packages that would have been.

**Comment by Technetium1** [comment]
@xiota It's used independently _or_ alongside other frameworks! It's a large project that's kept momentum for ~5 years. Check out https://onnxruntime.ai to see some of the backing forces

Even if this was just a dependency, it's one that an exception can be made for on the grounds that it's difficult to build ([pinned comment](https://aur.archlinux.org/packages/python-onnxruntime#comment-788225)). Some acceleration is included in the Pypi release, but for example, some CUDA features are [not supported unless it's built](https://onnxruntime.ai/getting-started) [this way](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-onnxruntime#n6).

Unless this ends up proving to be a **HUGE** burden, we should try to make it available

**Comment by xiota** [comment]
I don't question that someone somewhere finds it useful.  But if it's not worth the effort for OP to explain its use better than a generic one-liner, it's not worth the effort to try to build.  The more "difficult to build" a package is, the better I expect the explanation to be.

The request template clearly asks that AUR dependencies be listed, and OP didn't do that either.  There are five first-level AUR depends and three firsts-level optdeps.  While the required dependencies don't appear to have recursive dependencies, the optdeps do, and the nature of AI modules is for a lot of important functionality to be in the optdeps.

**Comment by Technetium1** [comment]
```
extra/python-onnxruntime 1.16.3-10
    Cross-platform, high performance scoring engine for ML models
extra/python-onnxruntime-opt 1.16.3-10
    Cross-platform, high performance scoring engine for ML models (with AVX2 CPU optimizations)
extra/python-onnxruntime-opt-rocm 1.16.3-10
    Cross-platform, high performance scoring engine for ML models (with ROCm and AVX2 CPU
    optimizations)
extra/python-onnxruntime-rocm 1.16.3-10
    Cross-platform, high performance scoring engine for ML models (with ROCm)
```
