### ISSUE TITLE
[Rebuild] mesa-tkg-git

### ISSUE THREAD

**Issue by EmptyVisual** [chaotic-aur/packages#2877]
### Packages:

mesa-tkg-git: https://github.com/Frogging-Family/mesa-git.git

mesa-git: https://github.com/chaotic-aur/pkgbuild-mesa-git.git
lib32-mesa-git: https://github.com/chaotic-aur/lib32-mesa-git.git

### Latest chaotic version

24.0.0_devel.179534.e95c9b0515b

### (has not been rebuilt for 5 days now) 
Last Build 2023-10-26 15:02

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/mesa-tkg-git.log

https://builds.garudalinux.org/repos/chaotic-aur/logs/mesa-git.log
https://builds.garudalinux.org/repos/chaotic-aur/logs/lib32-mesa-git.log

**Comment by dr460nf1r3** [comment]
Stalled due to DNS issues on the ufscar builder as of now.
