### ISSUE TITLE
[Request] bombono-dvd

### ISSUE THREAD

**Issue by Redcarred2** [chaotic-aur/packages#2880]
### Package:

https://aur.archlinux.org/packages/bombono-dvd

### Purpose:

DVD authoring program

### Benefits:

High recommended on linux forums
Used for DVD authoring

### Copyright:

GPL

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

Yes

**Comment by xiota** [comment]
This isn't going to work... makedepends on `scons2` which depends on `python2`.
