### ISSUE TITLE
[Request] kotatogram-desktop-git

### ISSUE THREAD

**Issue by bigdiff** [chaotic-aur/packages#2881]
### Package:

https://aur.archlinux.org/packages/kotatogram-desktop-git

### Purpose:

it is a telegram client, there were some other packages that are being discontinued in favor of the new one https://aur.archlinux.org/packages/kotatogram-desktop-git

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Most of the kotatogram-related packages were outdated or broken.  I am in the process of clearing them out.  It is taking some time, and chaotic-aur will be updated when it's done.

**Comment by xiota** [comment]
I hadn't seen that announcement.  I did try building some of the other branches that are mentioned.  None were successful.

**Comment by xiota** [comment]
Planning to drop because incompatible Qt6.8 and slow to sync with upstream Telegram.
