### ISSUE TITLE
[Rebuild] discord_arch_electron

### ISSUE THREAD

**Issue by CodeDragon5** [chaotic-aur/packages#2882]
### Packages:

https://aur.archlinux.org/packages/discord_arch_electron

### Latest chaotic version

0.0.32-1

### Reason for rebuild

Outdated in Chaotic-AUR packagelist. Latest AUR version is 0.0.33-1, and that version appears to be building correctly according to the logs.

My pacman only sees the previous version in the repo:
```
$ pacman -Si discord_arch_electron 
Repository      : chaotic-aur
Name            : discord_arch_electron
Version         : 0.0.32-1
```

And a search on pkgs.org also shows the old version in Chaotic:
https://pkgs.org/download/discord_arch_electron

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/discord_arch_electron.log

### More information

Forgive me if this is the wrong place or template for this.

**Comment by xiota** [comment]
@dr460nf1r3 ufscar-hpc issue?

`ufscar-hpc/hourly.2.txt:37:discord_arch_electron`

`discord_arch_electron.log: ==> Finished making: discord_arch_electron 0.0.33-1 (Wed 01 Nov 2023 12:04:28 AM -03)`

http://builds.garudalinux.org/repos/chaotic-aur/x86_64/#discord_arch_electron

**Comment by dr460nf1r3** [comment]
Since I didn't hear about anything being solved, it might be this one:
https://github.com/chaotic-aur/packages/issues/2877#issuecomment-1784153586

**Comment by dr460nf1r3** [comment]
Rebuilt it manually.
