### ISSUE TITLE
[Request] winbox

### ISSUE THREAD

**Issue by mauriciodelima21** [chaotic-aur/packages#2883]
### Package:

https://aur.archlinux.org/packages/winbox

### Purpose:

Winbox is a graphical user interface (GUI) tool developed by MikroTik for remotely configuring and managing MikroTik routers and networking devices. It provides a user-friendly interface, allowing network administrators to efficiently access and modify device settings. This remote management tool improves efficiency, accessibility, and security for administrators, making it a valuable asset in network management.

### Benefits:

In summary, the specific benefits of Winbox over other packages include its user-friendliness, efficiency, remote management capabilities, real-time feedback, and security features. Administrators often choose Winbox for its ease of use, making it an ideal solution for managing MikroTik devices in various use cases, from small networks to complex, remote setups.

### Building:

makepkg

### Copyright:

Custom

### Expected Interest:

Most

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

### More information:

I use this package a lot, and I struggle with the updates, or I have to install it via Snap, which doesn't make sense to me as an Arch user.

**Comment by xiota** [comment]
Looks like a windows binary run with wine.

Can you explain the versioning and updates to me?  The package is 3.40, but the website has 6.x/7.x.
