### ISSUE TITLE
[Rebuild] anki: Update build to 23.10

### ISSUE THREAD

**Issue by meliache** [chaotic-aur/packages#2884]
### Packages:

https://aur.archlinux.org/packages/anki

### Latest chaotic version

2.1.66-2

### Reason for rebuild

Anki package got updated yesterday to the 23.10 release. Maybe I'm just too impatient and it would have been rebuild automatically after a day, not sure when the rebuilds usually happen, but I decided to report that just in case.

### More information

As can be seen, Anki switched from semver to a <year>-<month> versioning scheme, not sure if that matters.

**Comment by dr460nf1r3** [comment]
Related to https://github.com/chaotic-aur/packages/issues/2877#issuecomment-1784153586. Built it manually.
