### ISSUE TITLE
[Request] bun-bin

### ISSUE THREAD

**Issue by vixalien** [chaotic-aur/packages#2885]
### Package:

https://aur.archlinux.org/packages/bun-bin

### Purpose:

Bun is a JavaScript runtime, like Node.js and Deno. It has been gaining traction recently as it's faster while maintaining (some) compatibility with Node.js

### Benefits:

I'm not sure if chaotic prefers `-bin` packages over building from source, and you may feel free to change this.

### Copyright:

GPL

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
I'm inclined to reject.

1. This is a dependency without any dependents.
2. Weird disputes that need to be resolved first.  (Orphan/Merge/Other requests.)
3. Weird packaging.  The `bun-*` packages depend on themselves/each other?

**Comment by xiota** [comment]
Closing because no response explaining use/usefulness.  If anything ever needs this, it will be added as a dependency.

**Comment by xiota** [comment]
`aur/bun` was previously added as a makedep of `museeks`.  Switched to `aur/bun-bin` for failure to build.

Metrics:

* bun # 131
