### ISSUE TITLE
[Remove] libvips-fs79527

### ISSUE THREAD

**Issue by diniamo** [chaotic-aur/packages#2886]
### Package:

https://aur.archlinux.org/packages/libvips-fs79527

### Purpose:

Image processing library

### Benefits:

I'm forced to use libvips-git, because the libvips package in the extra repository is built-in with a debug flag (this hasn't been fixed for a pretty long time), which makes insuppressible (at least in my use case) debug messages appear.

From my experience, libvips sometimes works better than opencv. (I use a program that supports both)

### Copyright:

GNU Lesser General Public License v2.1

### Expected Interest:

Half

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Relevant [FS#79527](https://bugs.archlinux.org/task/79527).  Apparently the issue may be fixed upstream with 8.15.0, which should be released "soon" because RC2 was released a couple days ago.

If there's no need for the git package after this issue is resolved, I make a test build of 8.15.0rc2 available.

**Comment by diniamo** [comment]
After the issue is resolved, I don't see why anyone would use the git package, as the developers of libvips push a lot of commits there, some potentially unstable.

I wonder about that soon that "soon" is though, the issue has been open for a very long time.

**Comment by xiota** [comment]
I've built `libvips-test-8.15.0rc2-1-x86_64.pkg.tar.zst`.  I am intentionally *not* setting the "release" flag because I want to test whether `extra/libvips` will be fixed when 8.15.0 is released.

Please let me know if it works.  If not, I will rebuild with the release flag set.

**Comment by diniamo** [comment]
It works from what I can tell.

**Comment by xiota** [comment]
I just built `libvips-fs79527 8.15.0rc2-1`.  Basically the same as the "test" package, but maybe more aesthetic not to have "test" in the name.

Will plan to remove when `extra/libvips` is upgraded to 8.15.0.

**Comment by diniamo** [comment]
Thank you!

**Comment by xiota** [comment]
@diniamo  `extra/libvips` 8.15.0-1 has been released.  Please test and let me know if it works as expected.
