### ISSUE TITLE
[Rebuild] 64gram-desktop

### ISSUE THREAD

**Issue by Sad-Soul-Eater** [chaotic-aur/packages#2888]
### Packages:

https://aur.archlinux.org/packages/64gram-desktop

### Latest chaotic version

1:1.1.1-1

### Reason for rebuild

[`protobuf`](https://archlinux.org/packages/extra/x86_64/protobuf) package was updated to `25.0-1` 

```
# telegram-desktop
telegram-desktop: error while loading shared libraries: libprotobuf-lite.so.24: cannot open shared object file: No such file or directory
```

**Comment by xiota** [comment]
I will also bump other packages that depend on `protobuf`.
