### ISSUE TITLE
[Rebuild] forkgram

### ISSUE THREAD

**Issue by Architector4** [chaotic-aur/packages#2889]
### Packages:

https://aur.archlinux.org/packages/forkgram

### Latest chaotic version

4.11.3-1

### Reason for rebuild

Needs just a simple rebuild due to update in a dependency. I'm pretty sure this doesn't need any upstream change or intervention, and a rebuild of the exact same pkgbuild will fix this, as it did many times in the past when I rebuilt it myself.

```
$ Forkgram
Forkgram: error while loading shared libraries: libprotobuf-lite.so.24: cannot open shared object file: No such file or directory
```

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/forkgram.log

### Builds?

Yes. It's a big thing that needs lots of dependencies and builds for a while though, and this time I'm too lazy to rebuild it myself lol

**Comment by xiota** [comment]
Already bumped in #2888.  Waiting for rebuild.  Will force later if needed.
