### ISSUE TITLE
Add Electron-Ozone

### ISSUE THREAD

**Issue by juxuanu** [chaotic-aur/packages#289]
AUR: [https://aur.archlinux.org/packages/electron-ozone/](https://aur.archlinux.org/packages/electron-ozone/)
PKGBUILD file: [https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=electron-ozone](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=electron-ozone)

Reasons:
* This is an extremely helpful package if you are running your desktop under Wayland, as many applications depend on this, so, having it will enable Wayland for many of them. For example, Discord bundles its own Electron version, but with the package [discord_arch_electron](https://aur.archlinux.org/packages/discord_arch_electron/) you can use your system's version.
* `electron-ozone` takes a lot of time to compile, specially in a laptop.

**Comment by PedroHLC** [comment]
:cry: I've been trying to build this package for ages.

Fellow Wayland user here...

**Comment by juxuanu** [comment]
What errors are you getting?

**Comment by PedroHLC** [comment]
I used to have compilation problems related to upstream issues, now it just won't start building cause there isn't any `gn<0.1809` in the repos :smile:

**Comment by juxuanu** [comment]
Have you tried modifying the PKGBUILD from 
```
makedepends=('git' 'gn<0.1809' 'gperf' 'harfbuzz-icu' 'java-runtime-headless'
             'jsoncpp' 'libnotify' 'lld' 'llvm' 'ninja' 'npm' 'pciutils' 'yarn'
             'python2' 'wget' 'yasm' 'python2-setuptools' 'libpipewire02' 'nodejs'
             'openh264')
to
`depends=('c-ares' 'ffmpeg' 'gtk3' 'http-parser' 'libevent' 'libxslt' 'minizip' 'nss' 'snappy')`

**Comment by PedroHLC** [comment]
Just an update,

This log is generated from the daily attempts: https://lonewolf.pedrohlc.com/chaotic-aur/makepkglogs/_daily/electron-ozone.log

**Comment by juxuanu** [comment]
@PedroHLC make it do first `pacman -U https://archive.archlinux.org/packages/g/gn/gn-0.1731.5ed3c9cc-1-x86_64.pkg.tar.zst`

Also, for more info, check https://wiki.archlinux.org/index.php/Arch_Linux_Archive#How_to_downgrade_one_package

**Comment by PedroHLC** [comment]
Nope, I can't and won't build packages with downgraded depencies. Even in a chaotic repo we have to keep some quality!

It seems like the upstream package is using this GN: https://www.archlinux.org/packages/extra/x86_64/gn-m85
AUR's package maintainer should use it too...

**Comment by juxuanu** [comment]
@PedroHLC Just as a side note, I left my pc compiling all night and I woke up with a successfully created `electron-ozone`.

**Comment by juxuanu** [comment]
https://github.com/electron/electron/pull/26022
It seems it might not be needed after all.

**Comment by PedroHLC** [comment]
Sorry, I forgot to close this one, we have it building for more than a month...
Do note that building it usually fails (like it did today): https://lonewolf.pedrohlc.com/chaotic-aur/makepkglogs/_daily/electron-ozone.log

**Comment by juxuanu** [comment]
No worries, you told me on Telegram some days ago.
Following the Electron development, I saw (and tested) that we can already use the Chromium flags to enable Wayland thanks to Ozone in their nightly build. This will probably land on version 12 iirc. We will not need this soon enough.
