### ISSUE TITLE
[Rebuild] flameshot-git

### ISSUE THREAD

**Issue by wzqj** [chaotic-aur/packages#2890]
### Packages:

https://aur.archlinux.org/pkgbase/flameshot-git

### Latest chaotic version

r1871.a447b3d6-1

### Reason for rebuild

Latest builds seem to have failed and package is outdated, missing fixes from more recent merges (especially in wayland).

Latest upstream version 12.1.0

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/flameshot-git.log

### More information

This comment from the AUR may be helpful:

https://aur.archlinux.org/packages/flameshot-git#comment-940449

> I'm also unable to get this package to build. Says I am missing kguiaddons but I checked and shouldn't the package be kguiaddons5?
> 
> EDIT: can confirm, after editing the PKGBUILD and changing kguiaddons to kguiaddons5, package builds and installs correctly.
> 
> For anyone else who wants to install, this worked for me: grab the PKGBUILD from the top right of this page under Package Actions and put it in a random, empty directory. Edit it and just add a 5 after kguiaddons. Then, in that directory run makepkg, then sudo pacman -U flameshot-git-r1938.fa29bcb4-1-x86_64.pkg.tar.zst

**Comment by xiota** [comment]
Package has many issues.  I've commented to ask maintainer to address them.

**Comment by xiota** [comment]
Added interfere and rebuilt.

**Comment by erikdubois** [comment]
It might be time to re-open...

it builds fine now

**Comment by xiota** [comment]
Although package has been updated for Qt6, it still has the same maintainer.

**Comment by erikdubois** [comment]
is the maintainer the issue...?

pkgbuild is ok
