### ISSUE TITLE
[Request] material-symbols-git

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#2893]
### Package:

https://aur.archlinux.org/pkgbase/material-symbols-git

### Purpose:

Material Design icons by Google. Used mainly on Window Managers themes to render several icon elements.

### Copyright:

Apache

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Built, but not adding to lists until `pkgver()` is fixed.

**Comment by xiota** [comment]
@D3vil0p3r While maintainers can be motivated by orphan requests, 5 days isn't really much time.  Also, most of the git changes are not to the font files themselves, but the glyph descriptions, so frequent rebuilding is pointless.

**Comment by xiota** [comment]
This package is a problem because the git repo is downloaded in `prepare()`, so not cached and redownloaded every rebuild attempt.  Even though it's sparse clone, it's still a lot to download every hour.

**Comment by D3vil0p3r** [comment]
The package has been removed? I cannot find it on Chaotic repo.

**Comment by xiota** [comment]
```
$ pacman -Ss material-symbols
chaotic-aur/ttf-material-symbols-variable-git 4.0.0.r91.ga90037f8-1
    Material Design icons by Google - variable fonts
chaotic-aur/woff2-material-symbols-variable-git 4.0.0.r91.ga90037f8-1
    Material Design icons by Google - variable fonts
```
