### ISSUE TITLE
[Rebuild] Raze

### ISSUE THREAD

**Issue by NerosTie** [chaotic-aur/packages#2898]
### Packages:

https://aur.archlinux.org/packages/raze

### Latest chaotic version

1.7.1-2

### Reason for rebuild

2 updates has been released: 1.8 then 1.8.1. It looks like Raze in [chaotic-aur] is stuck to 1.7.1.

**Comment by xiota** [comment]
Missing depends.  Rebuilt and notified aur maintainer.
