### ISSUE TITLE
[Request] omada-controller

### ISSUE THREAD

**Issue by evansan** [chaotic-aur/packages#2899]
### Package:

https://aur.archlinux.org/packages/omada-controller

### Purpose:

controller program for TP-Link Access Points

### Copyright:

custom

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
@evansan can you confirm that it works when you build it yourself?

**Comment by evansan** [comment]
I was unable to build it due to dependency error

**Comment by Technetium1** [comment]
@evansan can you please give the error?
