### ISSUE TITLE
[Request] easy-installer

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#2902]
### Package:

https://aur.archlinux.org/packages/easy-installer

### Purpose:

The Easy Installer is a desktop application which helps users install Android /e/ (https://doc.e.foundation/what-s-e) on supported devices.

### Benefits:

Considering that the /e/ OS supports over 200 devices it is worth adding this amazing package to the chaotic repo. I have used it to bring back to life my Samsung Galaxy S7 and works wonders.

### Copyright:

GPL3

### Expected Interest:

Everyone

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Package is installing files to `/usr/local` and has some other minor defects.  Maintainer was notified months ago, on 2024-03-26, but has bumped version without fixing any issues.  This package will be dropped if problems are not fixed at the next update.  Metrics 11.
