### ISSUE TITLE
[Request] footage

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#2905]
### Package:

https://aur.archlinux.org/packages/footage

Depends:
https://aur.archlinux.org/packages/gst-plugins-rs
https://aur.archlinux.org/packages/gstreamer-svt-av1
https://aur.archlinux.org/packages/vo-aacenc

### Purpose:

Trim, flip, rotate and crop individual clips. Footage is a useful tool for quickly editing short videos and screencasts. It's also capable of exporting any video into a format of your choice. 

### Benefits:

It is simply a fast way to edit a video.

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Depends `gst-plugins-rs` is flagged out of date.

Package cannot be added because has unresolved issue with conflicting files.

**Comment by xiota** [comment]
@tio-trom I have a test build in the repo.  On my computer, it doesn't do anything when I try to open a video.  Do you know what may be missing to get this working?

**Comment by Technetium1** [comment]
@xiota upstream seems to know about the problem and have a fix incoming 🤔 https://gitlab.com/adhami3310/Footage/-/issues/23#note_1717067722

**Comment by xiota** [comment]
I'm aware they're working on the file conflicts.  The issue in my last comment is a functional issue.  The program doesn't open any video in any format that I've tried.  Maybe missing a dep or makedep.

**Comment by tio-trom** [comment]
> @tio-trom I have a test build in the repo. On my computer, it doesn't do anything when I try to open a video. Do you know what may be missing to get this working?

All works great on my machine. Version 1.3.1-2. You should open it via the terminal and see if you get any output/error.

**Comment by xiota** [comment]
@tio-trom Zero output in terminal.  Do you mind providing a package list so I can look for missing depends?

**Comment by tio-trom** [comment]
Here https://paste.trom.tf/ozufefopix.sql - this is from a freshly installed TROMJaro where it works to use Footage very well.

**Comment by tio-trom** [comment]
So this package is very useful to quickly cut parts of a video, rotate, flip, convert. And it works great on my machine. What if you submit your error directly to here https://gitlab.com/adhami3310/Footage/-/issues so they can try to debug your particular issue?

**Comment by Technetium1** [comment]
@tio-trom waiting on https://gitlab.com/adhami3310/Footage/-/issues/24 + https://gitlab.com/adhami3310/Footage/-/issues/20

**Comment by xiota** [comment]
Rejecting because package has (or had) issues that weren't resolved and depends on packages with more issues (eg, missing depends) that I don't care to try to fix.

**Comment by tio-trom** [comment]
Is this comment from the maintainer relevant still https://aur.archlinux.org/packages/gst-plugin-gif#comment-961434 ?
