### ISSUE TITLE
[Request] florence

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#2906]
### Package:

https://aur.archlinux.org/packages/florence

### Purpose:

A configurable on-screen virtual keyboard

### Benefits:

Since there is a lack of such virtual keyboards on Linux I think it is worth adding it.

### Copyright:

GPL

### Expected Interest:

Most

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
I've tried multiple times over an extended period and cannot build this. If it ever gets updated and builds in a clean chroot, please feel free to request again.

**Comment by xiota** [comment]
To request again, leave comment confirming that it has been updated *and* builds in clean chroot.  However, project may be considered abandoned because it was last updated in 2014.
