### ISSUE TITLE
[Request] localsend-bin

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#2907]
### Package:

https://aur.archlinux.org/packages/localsend-bin

~~`localsend-git`~~ – currently broken
~~`localsend`~~ – permanently broken

### Purpose:

An open source cross-platform alternative to AirDrop

### Benefits:

A great and simple app for sending files and folders via a local network. You can also send text and links. It is as simple and as useful as that.

### Copyright:

MIT

### Expected Interest:

Most

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by mauriciodelima21** [comment]
This package is amazing, it can help a lot of people like me who live amidst so many quick transfers between devices. Approve it, please

**Comment by xiota** [comment]
`aur/localsend` and `aur/localsend-git` are both broken for different reasons.  Also, `aur/flutter` currently isn't working.

The pkgbuild for `aur/localsend-bin` looks basically okay, so adding it.  May eventually replace with a custom pkgbuild when flutter, or a substitute, is working.

**Comment by xiota** [comment]
Dropping because has been unbuildable after a refactor in Oct 2025.  Stable package is available, and usage of -git package is low.

Metrics:
* localsend # 713
* localsend-git # 54
