### ISSUE TITLE
[Request] mission-center

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#2908]
### Package:

https://aur.archlinux.org/packages/mission-center

### Purpose:

Monitor your CPU, Memory, Disk, Network and GPU usage

### Benefits:

Quite a neat and useful system monitor.

### Copyright:

GPL3

### Expected Interest:

Most

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Dropped because moved to extra.  Metrics 1625.
