### ISSUE TITLE
[Request] 3dslicer

### ISSUE THREAD

**Issue by amiria703** [chaotic-aur/packages#2909]
### Package:

https://aur.archlinux.org/packages/3dslicer

AUR Depends:
https://aur.archlinux.org/packages/dcmtk
https://aur.archlinux.org/packages/teem

### Purpose:

Teaching anatomy of human body to students and people.

### Copyright:

BSD

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Building this AUR package takes a lot of time and effort thus, having a prebuilt package would be so nice.

**Comment by xiota** [comment]
How much is "a lot of time"?  I tried building this and it wasn't done after some hours.  Then the build server started having problems.  There's a bin package on AUR: https://aur.archlinux.org/packages/3dslicer-bin

**Comment by xiota** [comment]
`aur/3dslicer` seems to be too resource intensive to build.  Adding it to the package lists could potentially prevent other packages from being built.  We could try providing `aur/3dslicer-bin`.

@amiria703 If I don't hear back from you "soon", I will reject this request.
