### ISSUE TITLE
[Remove] tuba

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#2911]
### Package:

https://aur.archlinux.org/packages/tuba-git + interfere

Note: `aur/tuba` is using a pkgrel format (x.y) that is incompatible with chaotic-aur.

### Purpose:

Great app for browsing the Fediverse. Maybe the best I've tested. I tested it with Mastodon and Friendica. You can pretty much have access to all of the features that Mastodon has. From creating posts and attaching media, to sorting your timeline based on groups, feed source (local or global), and more (notifications, search, hashtags, threads, direct messages, multiple accounts).

### Benefits:

This is perhaps the best way of interacting with the fediverse from a desktop app. It is also actively developed https://github.com/GeopJr/Tuba

### Copyright:

GPL3

### Expected Interest:

Most

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Rejecting because of insufficient justification for maintenance burden.

**Comment by tio-trom** [comment]
> Rejecting because of insufficient justification for maintenance burden.

Tuba is the best fediverse app I've tested so far on Linux: Posting, notifications, profiles, search, hashtags, threads, direct messages, multiple accounts & more. I tested it with Mastodon and Friendica both work very well. The app is modern and the development is very active. See https://github.com/GeopJr/Tuba

**Comment by tio-trom** [comment]
Updated the main post.

**Comment by xiota** [comment]
Nonstandard `pkgrel=0.2`.  May interact with chaotic bump system.

**Comment by xiota** [comment]
Added via `aur/tuba-git` + interfere.  The git package is convertible with autoupdate.  It will automatically rebuild when new releases are tagged.

**Comment by xiota** [comment]
The maintainer of `aur/tuba` replied to my email, indicating refusal to change to a standard `pkgrel` format.  He also states:

> I'd prefer to have my packages not in a 3rd party repo, because I will not provide any support for it. This includes dealing with possible bug reports.
 
So please avoid contacting that maintainer with any issues related to any chaotic-aur packages, especially those that are built with alternate PKGBUILD or interfere.  All of his packages currently have non-standard properties, so would also need interfere if added in the future.

Checking with chaotic-aur to determine the cause of issues is reasonable, especially for packages that are modified.  Most, including `tuba`, should have optdep on `chaotic-interfere`.
