### ISSUE TITLE
[Bug] Don't use cloudflare human verification on mirrors, no way to use under terminal

### ISSUE THREAD

**Issue by Originalimoc** [chaotic-aur/packages#2914]
### Packages:

NA

### Latest chaotic version

NA

### What happens?

error: failed retrieving file 'garuda.db' from xx-mirror.chaotic.cx : The requested URL returned error: 403
error: failed retrieving file 'chaotic-aur.db' from xx-mirror.chaotic.cx : The requested URL returned error:403

### What is expected to happen?

no error

**Comment by Originalimoc** [comment]
Cloudflare is pedantic recently and blocking a lot of endpoint

**Comment by dr460nf1r3** [comment]
Bot protection is indeed turned on. I've deployed a change - does it work now?

**Comment by Originalimoc** [comment]
still 403 :(
and browser access mirror still trigger cf human verification

**Comment by dr460nf1r3** [comment]
Which mirror is it specifically?

**Comment by Originalimoc** [comment]
All... I suppose? fr-1 de-2...On Nov 21, 2023 9:06 PM, Nico ***@***.***> wrote:
Which mirror is it specifically?

**Comment by Technetium1** [comment]
@Originalimoc Not sure if you meant to close this. It shouldn't be a continued issue at this point.

**Comment by Originalimoc** [comment]
I didn't test all the mirrors but either fr or de mirror is working so my side is good but the advice is still valid, do not limit known terminal pacman access

**Comment by Technetium1** [comment]
@Originalimoc We had no protection on R2, and any one of our mirrors using Cloudflare should have protection off/minimal and Tor access allowed. We definitely agree; that advice is valid, and we were surprised by this issue. Thank you for reporting.
