### ISSUE TITLE
[Request] mathics

### ISSUE THREAD

**Issue by coxackie** [chaotic-aur/packages#2915]
### Package:

https://aur.archlinux.org/packages/mathics

Depends:
https://aur.archlinux.org/pkgbase/simpleitk
... https://aur.archlinux.org/packages/insight-toolkit
... ... https://aur.archlinux.org/packages/gdcm # waiting fix/update

https://aur.archlinux.org/packages/python-scikit-image
... https://aur.archlinux.org/packages/python-lazy-loader
... https://aur.archlinux.org/packages/python-pyamg # (opt)
... https://aur.archlinux.org/packages/python-pywavelets # (check/opt)

https://aur.archlinux.org/packages/mathics-scanner
https://aur.archlinux.org/packages/python-palettable
https://aur.archlinux.org/packages/python-recordclass
https://aur.archlinux.org/packages/python-wordcloud

### Purpose:

This is an open-source alternative to Mathematica, used for symbolic computation, algebra, etc. Important for mathematicians, and more generally for scientists.

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by coxackie** [comment]
I realised I should also list other AUR dependencies: [mathics-scanner](https://aur.archlinux.org/packages/mathics-scanner), [python-palettable](https://aur.archlinux.org/packages/python-palettable), [python-recordclass](https://aur.archlinux.org/packages/python-recordclass), [python-scikit-image](https://aur.archlinux.org/packages/python-scikit-image). 

Unfortunately, the last one (`python-scikit-image`) has further AUR dependencies... When I have time I will try to sort them out, but not sure when this will be.

**Comment by coxackie** [comment]
Actually, paru gives me the following in the AUR, which are not in chaotic already:
```
Aur (11)                                    Old Version  New Version   Make Only
aur/mathics-scanner                                      1.3.0-1       No
aur/python-palettable                                    3.3.3-2       No
aur/python-recordclass                                   0.21-1        No
aur/python-pywavelets                                    1.4.1-1       Yes
aur/gdcm                                                 3.0.14-1      Yes
aur/insight-toolkit                                      5.3.0-2       Yes
aur/simpleitk                                            2.3.0-4       Yes
aur/python-simpleitk                                     2.3.0-4       Yes
aur/python-lazy-loader                                   0.3-1         No
aur/python-scikit-image                                  0.22.0-1      No
aur/mathics                                              6.0.3-2       No
```
However, this is not in a clean chroot... sorry...

**Comment by xiota** [comment]
@coxackie mathics is built; please test and let me know before I add to list.

**Comment by coxackie** [comment]
@xiota Whoa, that was fast... there seems to be an issue, when I run `mathics`, I get
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 631, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 875, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Pillow 10.1.0 (/usr/lib/python3.11/site-packages), Requirement.parse('pillow<10.1.0,>=8.3.2'), {'imageio'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mathics", line 33, in <module>
    sys.exit(load_entry_point('Mathics3==6.0.3', 'console_scripts', 'mathics')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/mathics", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/mathics/main.py", line 13, in <module>
    from mathics import __version__, license_string, settings, version_string
  File "/usr/lib/python3.11/site-packages/mathics/settings.py", line 7, in <module>
    import pkg_resources
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3327, in <module>
    @_call_aside
     ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3302, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3340, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 633, in _build_master
    return cls._build_from_requirements(__requires__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 646, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pkg_resources/__init__.py", line 875, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Pillow 10.1.0 (/usr/lib/python3.11/site-packages), Requirement.parse('pillow<10.1.0,>=8.3.2'), {'imageio'})
```
It looks like `python-pillow` is newer that expected from `mathics`, but I am not sure this is the only issue... should I report this to the AUR maintainer?

**Comment by xiota** [comment]
Something similar happened with Vorta.  It's a dependency check.  Problem should be reported upstream to [Mathics3/mathics-core](https://github.com/Mathics3/mathics-core/).

Try deleting `/usr/lib/python3.11/site-packages/Mathics3-6.0.3-py3.11.egg-info/requires.txt`.  If deleting the file works, you can ask the aur maintainer to delete it as a temporary measure.

**Comment by coxackie** [comment]
well, you are right, deleting the file does work. I left a message to the the AUR maintainer - we will see what he says. Many thanks!

**Comment by xiota** [comment]
@coxackie Please also open an issue in the mathics repo for the Pillow version conflict.

**Comment by coxackie** [comment]
https://github.com/Mathics3/mathics-core/issues/936

**Comment by coxackie** [comment]
@xiota I am also a bit puzzled. Look at https://github.com/Mathics3/mathics-core/issues/936#issuecomment-1822748216 - althout 6.0.4 is mentioned, I also went through the 6.0.3 release and I cannot see there an upper version requirement for pillow - just a lower version requirement. Why does the upper version constraint happen in the build?

**Comment by xiota** [comment]
Seems running `setup.py` directly generates the problem file.  Switching to PEP517 install should solve the problem.  I've posted details elsewhere.

There is a new build for you to test: mathics 6.0.3-3

**Comment by coxackie** [comment]
Everything looks good up to now. No errors thrown.

**Comment by xiota** [comment]
`mathics` was updated to PEP517 install, but maintainer introduced a new defect (missing makedepends) that could cause the package to break in the future.  New version is available in repo for use, but not adding to package lists until the defect is corrected.

**Comment by xiota** [comment]
`gdcm` is added in paused state.  I'll update if I notice any change.

**Comment by xiota** [comment]
@FabioLolix Please add me as comaintainer of `aur/gdcm` so I can update it.  Thank you.
