### ISSUE TITLE
[Request] cudatext-gtk2-bin

### ISSUE THREAD

**Issue by drdaffey** [chaotic-aur/packages#2916]
### Package:

https://aur.archlinux.org/packages/cudatext-gtk2-bin

### Purpose:

A competent Sublime Text alternative.

### Benefits:

I know of no other Sublime Text alternative that is not written in Electron and performs as well.

### Copyright:

MPL2
https://www.mozilla.org/en-US/MPL/2.0/

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Either cudatext-gtk2-bin or cudatext-qt5-bin, whichever you choose (or perhaps both).
AUR only has the -bin PKGBUILDs because compiling Lazarus software is difficult I assume.

**Comment by Technetium1** [comment]
Left comments for the maintainer [here](https://aur.archlinux.org/packages/cudatext-qt5-bin#comment-945688) and [here](https://aur.archlinux.org/packages/cudatext-gtk2-bin#comment-945687).

**Comment by Technetium1** [comment]
The maintainer seems absent and has missed multiple revisions. The source is no longer valid since they've moved to SourceForge officially. This has been flagged for more than a month as well.

**Comment by xiota** [comment]
@drdaffey Are you still interested in cudatext?  Would `-git` package be sufficient or would a stable package be needed?  (`-bin` packages were rejected for reasons previously stated.)
