### ISSUE TITLE
add keyboard-visualizer-git

### ISSUE THREAD

**Issue by fsyy** [chaotic-aur/packages#292]
please add keyboard-visualizer, as you have openrgb already packaged, this would be a nice addition.

both programs are created by the same guy:  CalcProgrammer1

openrgb + keyboard-visualizer demo: https://www.youtube.com/watch?v=Mx-YqF5S_9U&t=64s

gitlab: https://gitlab.com/CalcProgrammer1/KeyboardVisualizer
url: https://aur.archlinux.org/packages/keyboard-visualizer-git 
pkgbuild: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=keyboard-visualizer-git

**Comment by PedroHLC** [comment]
Done
