### ISSUE TITLE
[Request] hyprland-stable

### ISSUE THREAD

**Issue by REALERvolker1** [chaotic-aur/packages#2922]
### Package:

Hyprland / Xdg-desktop-portal-hyprland (release)

https://archlinux.org/packages/?name=hyprland

### Purpose:

The current release version of hyprland in the Arch repos is months out of date and lacks several useful features. The latest release version at the time of writing is `0.32.3`, whereas the current version in the Arch repos is `0.30.0`. This would be useful for people who want the latest release of the package but who would rather not have to fix their systems, switch window managers, or make new bug reports every couple of days. Personally, this is why I recently switched from Arch to Fedora.

### Benefits:

Hyprland is a tiling wayland compositor on the bleeding edge of Wayland, and has a fast development cycle. It would be great to have this package here since even if the package is eventually updated in the Arch repos, it might go without updates for several more months afterwards.

### Building:

https://aur.archlinux.org/hyprland-git.git
https://aur.archlinux.org/xdg-desktop-portal-hyprland-git.git

I assume it would be similar to the existing chaotic AUR builds of hyprland-git and xdg-desktop-portal-hyprland-git, but pulling the latest release versions instead of the git versions.

### Copyright:

BSD-3-Clause

https://github.com/hyprwm/Hyprland/blob/main/CODE_OF_CONDUCT.md

### Expected Interest:

Many

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by dr460nf1r3** [comment]
I also think that `hyprland-git` serves this purpose perfectly fine already.

**Comment by xiota** [comment]
I'm not totally against making `stable`/`git` packages via interfere, but I'd want users who are willing to test and report issues when they occur.  Otherwise, it would be wasted effort.

Will link this to previous `hyprland-git` related issues to see if there's any interest.

**Comment by REALERvolker1** [comment]
The arch ppl updated hyprland in the repos, so there's no point in this right now. Hopefully it doesn't go this long without updates again.
