### ISSUE TITLE
[Request] linwood-butterfly-bin

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#2925]
### Package:

https://aur.archlinux.org/packages/linwood-butterfly-bin

### Purpose:

Powerful, minimalistic, cross-platform, opensource note-taking app

### Copyright:

Apache, AGPL3, CC-BY-4.0 

### Expected Interest:

Half

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by dr460nf1r3** [comment]
Why would you use this instead of existing applications like Joplin and the likes?

**Comment by xiota** [comment]
Rejecting because of insufficient justification for maintenance burden.
