### ISSUE TITLE
[Request] mapeo-desktop-bin

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#2927]
### Package:

https://aur.archlinux.org/packages/mapeo-desktop-bin

### Purpose:

An offline map editing application for indigenous territory mapping in remote environments.

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by dr460nf1r3** [comment]
How are you going to utilize it?

**Comment by tio-trom** [comment]
> How are you going to utilize it?

You can find more info here https://www.digital-democracy.org/mapeo - I know you are asking me how I use every individual apps that I recommend here, but is not just me. Others use these too. I cannot always provide a detailed answer. The apps that I recommend come after months of testing them for our TROMjaro Linux, and are all trade-free. Meaning no ads, no data collection, no freemiums. And are open source.

**Comment by xiota** [comment]
Rejecting this because of insufficient justification for maintenance burden.
