### ISSUE TITLE
joplin wants to replace joplin-beta

### ISSUE THREAD

**Issue by juxuanu** [chaotic-aur/packages#293]
Having `joplin` installed and doing a `pacman -Syu` makes it want to replace the package with `joplin-beta`. Probably a PKGBUILD error.
![image](https://user-images.githubusercontent.com/24759034/95675349-d591fd00-0bb6-11eb-8237-81b1bbbaef2d.png)

**Comment by PedroHLC** [comment]
Please, request the same as Librewish did in here: https://aur.archlinux.org/packages/joplin-beta
