### ISSUE TITLE
Add pooi

### ISSUE THREAD

**Issue by tellmeY18** [chaotic-aur/packages#2931]
### Package:

https://aur.archlinux.org/packages/pooi

## Pooi - trivia on the commandline.
pooi project is a an attempt to keep the cli user more attatched to cli environment even when there is a need to perform an arbitary web search. The goal is to make pooi feature rich enough so that the user can perform as many web search functions and get the reslts in the commandline itself instead of opening up a fully featured web browser.

### Benefits:

As of now I haven't found any alternative that provides byte sized information by searching as many fields Directly from the command line. 

### Building:

makepkg

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Dropping for poor maintenance.
