### ISSUE TITLE
[Bug] pcsx2-avx-git doesn't conflict with pcsx2-git

### ISSUE THREAD

**Issue by niobium93** [chaotic-aur/packages#2934]
### Packages:

https://aur.archlinux.org/packages/pcsx2-git

### Latest chaotic version

`1.7.5236.r0.g15082d777-1`

### What happens?

When installing `pcsx2-avx-git` doesn't remove `pcsx2-git` and instead just complains about conflicting files and fails.

### What is expected to happen?

Installing `pcsx2-avx-git` should replace `pcsx2-git`.

**Comment by xiota** [comment]
Thanks for letting me know.  Both packages have been updated and rebuilt.  They may not remove each other correctly until upgraded to the fixed package first.
