### ISSUE TITLE
[Request] python-colour-science

### ISSUE THREAD

**Issue by Kibbitzer** [chaotic-aur/packages#2935]
### Package:

https://aur.archlinux.org/packages/python-colour-science

### Purpose:

Colour is an open-source [Python](https://www.python.org/) package providing a comprehensive number of algorithms and datasets for colour science.

### Benefits:

Unique package providing tools and libraries useful for the colour science field, not found on other python libraries.

### Copyright:

BSD-3-Clause

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
This package can be reconsidered for addition if there is more interest in the future. There is a PyPI wheel available, and this seems better suited to a virtual environment.
