### ISSUE TITLE
[Request] lact

### ISSUE THREAD

**Issue by coxackie** [chaotic-aur/packages#2936]
### Package:

https://aur.archlinux.org/packages/lact

### Purpose:

AMDGPU GUI Controller application. AMD only exposes CLI for controlling; this package provides a user-friendly GUI

### Copyright:

MIT

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

Yes

**Comment by xiota** [comment]
Dropped because moved to extra.  Metrics:

* lact # 1010
* lact-libadwaita # 88
