### ISSUE TITLE
kernel and kernel header mismatch (pds-cannonlake)

### ISSUE THREAD

**Issue by ysolis** [chaotic-aur/packages#294]
![image](https://user-images.githubusercontent.com/9123933/97002898-3e0aa380-1500-11eb-96aa-c0cf2c3ad280.png)

the version are missmatched for this specific kernel. I rebuilt all the other packages modeles needed by me with `dkms`

- `acpi_call-dkms`
- `bbswitch-dkms`
- `chaotic-nvidia-dkms-tkg`

and is failing because the headers come apparently from a superior version

**Comment by PedroHLC** [comment]
Solved early
