### ISSUE TITLE
[Rebuild] bluemail

### ISSUE THREAD

**Issue by mauriciodelima21** [chaotic-aur/packages#2940]
### Packages:

https://aur.archlinux.org/packages/bluemail

### Latest chaotic version

1.137.2-2

### Reason for rebuild

The package encounters an error upon opening due to an incompatibility with the GPU when installed directly from the official repositories. However, when compiled and installed from the AUR (Arch User Repository), everything works fine

### Logs

05/12/2023 13:38:02 :: Main thread initialized 
05/12/2023 13:38:02 :: Getting system flags 
05/12/2023 13:38:02 :: isLinux true 
05/12/2023 13:38:02 :: isMac false 
05/12/2023 13:38:02 :: isWindows false 
05/12/2023 13:38:02 :: isWindowsExeBuild false 
05/12/2023 13:38:02 :: isWindowsStoreBuild false 
05/12/2023 13:38:02 :: Retrieving process agrs 
05/12/2023 13:38:02 :: #0: || /opt/bluemail/bluemail || type: string -- /opt/bluemail/bluemail 
05/12/2023 13:38:02 :: Retrieving LoginItemSettings 
05/12/2023 13:38:02 :: {"openAtLogin":false,"openAsHidden":false,"restoreState":false,"wasOpenedAtLogin":false,"wasOpenedAsHidden":false} 
/bin/sh: linha 1: hostname: comando não encontrado
05/12/2023 13:38:03 :: APP child-process-gone, uptimeSeconds: 0, exitCode: 159, reason: crashed, type: GPU, serviceName: GPU, name: na 
05/12/2023 13:38:03 :: APP child-process-gone, uptimeSeconds: 0, exitCode: 159, reason: crashed, type: GPU, serviceName: GPU, name: na 
05/12/2023 13:38:03 :: APP child-process-gone, uptimeSeconds: 1, exitCode: 159, reason: crashed, type: GPU, serviceName: GPU, name: na 
05/12/2023 13:38:03 :: APP child-process-gone, uptimeSeconds: 1, exitCode: 159, reason: crashed, type: GPU, serviceName: GPU, name: na 
05/12/2023 13:38:03 :: APP child-process-gone, uptimeSeconds: 1, exitCode: 159, reason: crashed, type: GPU, serviceName: GPU, name: na 
[211247:1205/133804.057019:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (imagem do núcleo gravada)

**Comment by xiota** [comment]
Should be working now.  Comment if still having problems.
