### ISSUE TITLE
[Request] ddnet

### ISSUE THREAD

**Issue by C0D3D3V** [chaotic-aur/packages#2941]
### Package:

https://aur.archlinux.org/packages/ddnet

### Purpose:

A Teeworlds modification with a unique cooperative gameplay.

It is a very good Linux Game.

### Benefits:

Stable version is fine, ddnet-git can be instable, although we now have a pretty good CI. 

### Copyright:

custom license similar to zlib License:
https://github.com/ddnet/ddnet/blob/master/license.txt

### Expected Interest:

Some

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Package is available in repo, but not added to lists yet.  The AUR package needs to be updated.

Also, the release tags appear to all be out of tree: "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

Do you know why they aren't tagged within a branch, like master?

**Comment by C0D3D3V** [comment]
You can have a look at the PR for the 17.4 Release https://github.com/ddnet/ddnet/pull/7438

As far as I remember, the idea is to create the tag for that release that will include no more commits than needed. So most commits that move into master while the release is taking place will not be added to the tag, but imported commits like translation updates or last minute patches can be added to the tag. Thats why most tags are out of master tree.

**Comment by xiota** [comment]
It's an unusual tagging practice that's inconvenient for git packages.  I guess doesn't matter that much for stable packages.

When I see that `aur/ddnet` is updated, I'll add it to the package lists.
