### ISSUE TITLE
[Request] Swapspace

### ISSUE THREAD

**Issue by BrandowLucas** [chaotic-aur/packages#2942]
### Package:

https://aur.archlinux.org/packages/swapspace

### Purpose:

A dynamic swap manager

### Benefits:

Swapspace is a dynamic swap manager which automatically creates and activates new swap files as your memory usage goes up. Since the swaps are automatically managed by the service, you won't need to worry about using the terminal in order to create/activate new ones.

### Copyright:

GPL

### Expected Interest:

Some

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

### More information:

need the following packages to build:

autoconf automake make

**Comment by xiota** [comment]
Please provide a better description in the purpose or benefits section.  The current explanation makes this seem like an automated task killer ("never worry about memory reaching 100%"), which I'm pretty sure it's not.

Also, pasting the pkgbuild isn't necessary.  The building section is for you to note whether you have built this yourself with an aur helper, makepkg, or some other means.
