### ISSUE TITLE
[Rebuild] swayfx

### ISSUE THREAD

**Issue by jthvai** [chaotic-aur/packages#2943]
### Packages:

https://aur.archlinux.org/packages/swayfx

### Latest chaotic version

`0.3.2-1`

### Reason for rebuild

AUR package has been updated to `0.3.2-5`, and includes fixes for the recent update to `extra/wlroots` (`swayfx 0.3.2-1` cannot be installed on an up-to-date Arch Linux system).

`aur/swayfx` also includes changes in line with `extra/sway` to [address xdg-desktop-portal 1.17 requirements](https://github.com/WillPower3309/swayfx/commit/7c75b21933215348f28a2c788b174901ef13e267).

**Comment by jthvai** [comment]
Since it is built on UFSCars, could be related to #2904 (see [this comment](https://github.com/chaotic-aur/packages/issues/2904#issuecomment-1839413204)).

**Comment by xiota** [comment]
I'll manually rebuild this, but leaving issue open as reminder for someone to look at ufscar.  Maybe @PedroHLC ?
