### ISSUE TITLE
[Request] gnome-encfs-manager-bin

### ISSUE THREAD

**Issue by mdhishamsayed** [chaotic-aur/packages#2944]
### Package:

https://aur.archlinux.org/packages/gnome-encfs-manager-bin

### Purpose:

An easy to use manager and mounter for encfs stashes

### Benefits:

easy to use and not complicated.

### Copyright:

GPLV3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Should this be switched to `gnome-encfs-manager-bzr`?

**Comment by Technetium1** [comment]
@xiota Yes
