### ISSUE TITLE
[Rebuild] discord_arch_electron

### ISSUE THREAD

**Issue by jkcdarunday** [chaotic-aur/packages#2945]
### Packages:

https://aur.archlinux.org/packages/discord_arch_electron

### Latest chaotic version

0.0.35-2

### Reason for rebuild

Outdated. Latest version is 0.0.37-1.

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/discord_arch_electron.log

**Comment by Technetium1** [comment]
Looks like it will not be [orphaned](https://lists.archlinux.org/hyperkitty/list/aur-requests@lists.archlinux.org/message/DZDAJIBCJWA44CPHA4DMI6TFPVLV7XPR/) since it was updated.
