### ISSUE TITLE
[Request]  tidal-hifi-bin

### ISSUE THREAD

**Issue by evansan** [chaotic-aur/packages#2950]
### Package:

https://aur.archlinux.org/packages/tidal-hifi-bin

### Purpose:

Client for Tidal music streaming service

### Copyright:

custom:MIT

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by dr460nf1r3** [comment]
Whats your personal use for it? :)

**Comment by dr460nf1r3** [comment]
Whats your personal use for it? :)

**Comment by evansan** [comment]
it's linux client for tidal that support DRM. I personally don't need it now.

**Comment by Technetium1** [comment]
@evansan do you mean to withdraw this request then?

**Comment by evansan** [comment]
yes
