### ISSUE TITLE
[Request] compfy

### ISSUE THREAD

**Issue by Totti786** [chaotic-aur/packages#2952]
### Package:

https://aur.archlinux.org/packages/compfy

### Purpose:

A Linux Compositor for X11. Based on Picom. Providing Animations and More

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Package failing to build for over a month.  New maintainer took over, but has not updated.  Will drop if not fixed.
