### ISSUE TITLE
[Request] Insomnium

### ISSUE THREAD

**Issue by UlisesAlexanderAM** [chaotic-aur/packages#2953]
### Package:

Base:
https://aur.archlinux.org/packages/insomnium

AUR dependencies (make):
https://aur.archlinux.org/packages/nvm

### Purpose:

Is a local API testing tool. It is a forked version of Insomnia that doesn't require an account to use the full capabilities of the tool.

### Benefits:

This tool doesn't need the creation of an account, while other tools require it.
This tool works offline.

### Copyright:

MIT

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Dropping because depends on electron25.
