### ISSUE TITLE
[Rebuild] kodi-git 

### ISSUE THREAD

**Issue by cg00001** [chaotic-aur/packages#2956]
### Packages:

https://aur.archlinux.org/packages/kodi-git

### Latest chaotic version

`r64614.38b7bcef9c9-1`

### Reason for rebuild

Newest from AUR contains newer Kodi version: Kodi Omega Beta 2

### More information

![kodi-git](https://github.com/chaotic-aur/packages/assets/38960370/9fb017e5-f4f9-4bb6-b969-620f7965b25e)

**Comment by xiota** [comment]
Another ufscar issue.  Package was last rebuilt 2023-12-08.

**Comment by cg00001** [comment]
Thank you, manual rebuilt works fine.

**Comment by Technetium1** [comment]
Continued builds seem to be working fine. Please reopen in the future if needed.
