### ISSUE TITLE
[Rebuild] ppsspp-git

### ISSUE THREAD

**Issue by NerosTie** [chaotic-aur/packages#2957]
### Packages:

https://aur.archlinux.org/packages/ppsspp-git
https://aur.archlinux.org/packages/ppsspp-assets-git

### Latest chaotic version

1.16.6.r236

### Reason for rebuild

Latest chaotic version: 1.16.6.r236 (2023-10-16)
Newest version: 1.16.6-588 (2023-12-15)

https://buildbot.orphis.net/ppsspp/index.php?m=fulllist

**Comment by xiota** [comment]
I made a copy/paste error when I added the package.  However, the package is wasteful of resources because it doesn't cache git submodules.  So I'm considering switching it to an interfere.

**Comment by xiota** [comment]
Should be fixed now.  If there are any other problems with this package, please comment here or at the original request.
