### ISSUE TITLE
[Rebuild] firefox-nightly

### ISSUE THREAD

**Issue by LeoKesler** [chaotic-aur/packages#2958]
### Packages:

https://aur.archlinux.org/packages/firefox-nightly

### Latest chaotic version

+20231117.1+heb34e7add45a-1

### Reason for rebuild

Almost one month without a successful build. 

==> Retrieving sources...
  -> Updating mozilla-central hg repo...
pulling from default
abort: repository default not found
==> WARNING: Failure while updating mozilla-central hg repo

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/firefox-nightly.log

**Comment by xiota** [comment]
Firefox and Chromium both fail to build because of failed assertions that appear to be related to `icu` update.

Related #2960

**Comment by LeoKesler** [comment]
@xiota Are you sure ?  The log shows the failure happens when creating copy from mozilla-central hg repo.  There is no mention about icu . 

>   -> Creating working copy of mozilla-central hg repo...
**abort: unknown revision 'default'**
==> ERROR: Failure while creating working copy of mozilla-central hg repo
    Aborting...

**Comment by xiota** [comment]
I'm sure.  New logs overwrite old ones.  The repo sync issue from the build server.  I'll move the packages to another server.

**Comment by spupuz** [comment]
still no new build :/

**Comment by xiota** [comment]
Switched server.  Current error:
```
16:22.23   No space left on device (os error 28)
```

Planning to switch to a custom PKGBUILD that builds in one pass instead of three.

**Comment by xiota** [comment]
`firefox-nightly` should be fixed now.  Leave a comment here if there are still problems.

**Comment by xiota** [comment]
There is now a new failure during build.  `firefox-wayland-hg` has similar issues, so probably something wrong with the upstream source code.

Deleted existing `chaotic-aur/firefox-nightly` because it was built with a different PKGBUILD during testing with different depends than `aur/firefox-nightly`.  Consequently, there will be *no* `firefox-nightly` available until upstream issues are resolved.

**Comment by xiota** [comment]
@dr460nf1r3 @PedroHLC  `firefox-nightly` and `firefox-wayland-hg` are back to `No space left on device (os error 28)`.  They succeed when I run them manually.  Is there a way to increase the space available?  Would putting them in their own routine make a difference?

If they have to go back to ufscar, the cache needs to be cleared to address [an earlier problem](https://github.com/chaotic-aur/packages/issues/2958#issuecomment-1864498517), but I remember there was a problem before with clearing cache on ufscar.

**Comment by xiota** [comment]
`firefox-nightly` built successfully.  Will monitor for a few days before closing.

@PedroHLC `firefox-wayland-hg` also built successfully, but has this error at the end:
```
/home/u726578/chaotic/interfere/firefox-wayland-hg/on-success.sh: line 2: ./pkgwork/upload-symbol-archive: Permission denied
```

**Comment by xiota** [comment]
As far as I can tell, firefox-related packages are now building successfully with intermittent failures.  Cache and space issues have been resolved.  Please comment here or in another relevant firefox-related issue if there are any more problems.
