### ISSUE TITLE
[Rebuild] otpclient

### ISSUE THREAD

**Issue by meatspinner** [chaotic-aur/packages#2959]
### Packages:

https://aur.archlinux.org/packages/otpclient

### Latest chaotic version

3.2.1-3

### Reason for rebuild

OTPClient is failing to open because libcotp was updated to "3.0.0-1",

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/otpclient.log

**Comment by xiota** [comment]
To make easier to detect these types of problems, I've recommended to the maintainer to add `libcotp.so` to the provides/depends of the related pacakges.  That way, `pacman` will display an error if they are updated out of sync:
```
:: installing libcotp (3.0.0-1) breaks dependency 'libcotp.so=2-64' required by otpclient
```

Will give maintainer some time to update the packages before rebuilding.

**Comment by xiota** [comment]
I went ahead and rebuilt manually.  Build server should rebuild when maintainer updates.
