### ISSUE TITLE
Version problem with osu-lazer

### ISSUE THREAD

**Issue by IroAlexis** [chaotic-aur/packages#296]
Hi Pedro,

I install osu-lazer and when I try the multiplayer, I have an notification on the fact that I have an older version. So I tried the osu-lazer-git version and I have exactly the same problem.
I check the git repot on the project and there is an newer version but the git package use this version... So I don't understand... :disappointed:

So I report the problem to see if I'm not the only one

**Comment by PedroHLC** [comment]
They're both up-to-date. For example, the latest `osu-lazer-git` was build today:
`osu-lazer-git-2020.1031.0.r327.d66ac33032-1-x86_64.pkg.tar.zst | 2020-11-06 05:20`
From https://github.com/ppy/osu/commit/d66ac330324dbfaed52355f12a20c942d9bd3270 that was commited today, and the new commits are already queued to build...\

Check if your pacman database is up-to-date, and if the problem persists, inform me which of the repos you have first in the `[chaotic-aur]` key in `/etc/pacman.conf`

**Comment by IroAlexis** [comment]
The first is `http://chaotic.bangl.de/chaotic-aur/x86_64` and I have updated the package and same result but the applciation return now `Invalid return value 0 for stream protocol`
Now, may be, it is a bug so ?

**Comment by PedroHLC** [comment]
> The first is http://chaotic.bangl.de/chaotic-aur/x86_64
That's the problem, BangL mirrors sync isn't stable.

From the current mirrorlist (https://lonewolf.pedrohlc.com/chaotic-aur/mirrorlist) I can't guarantee synced status for BangL and Ryoichi, what I recommend is: Put the brazilian one at the top (for using its database), and use `powerpill` for downloading from all the mirrors simulteneously.

> the applciation return now Invalid return value 0 for stream protocol
That looks like an upstream issue, wait for another build or check their repo's issues.

**Comment by PedroHLC** [comment]
While I wrote that, this built:
https://lonewolf.pedrohlc.com/chaotic-aur/x86_64/osu-lazer-git-2020.1031.0.r353.84e090583d-1-x86_64.pkg.tar.zst

**Comment by IroAlexis** [comment]
Thanks ! 

> That looks like an upstream issue, wait for another build or check their repo's issues.
I'm going to test this.

**Comment by IroAlexis** [comment]
Always there. Probably an upstream issue

Thanks @PedroHLC for you help and your work :frog:
