### ISSUE TITLE
[Maintenance] Rebuild for icu library update (75)

### ISSUE THREAD

**Issue by dr460nf1r3** [chaotic-aur/packages#2960]
### Packages:

All packages dependant on libicu.

### Latest chaotic version

Multiple

### Reason for rebuild

A commonly used [shared library got updated](https://gitlab.archlinux.org/archlinux/packaging/packages/icu/-/commit/4b7ab5d0b53fb2c09f4b8877d13e8222254c8da5).

### More information

Already bumped:
- `ungoogled-chromium`

**Comment by xiota** [comment]
@PedroHLC Okay to drop `obs-streamfx`?  It needs to be bumped because of `icu`,  but doesn't build because of `ffmpeg`.  Also, reportedly doesn't work with recent obs.  `obs-streamfx-unstable` is available (#2826).

**Comment by dr460nf1r3** [comment]
> I think only 1 or 2 levels were bumped. Number of packages per level:

Should be sufficient unless we catch people's error reports because of additional breakages. 

`namcap` doesn't report `libicu` because it's in the dep tree of `base-devel`, so maintainers wouldn't be alerted to add it.

That is quite a shame since A LOT of packages are affected by this, important ones like browsers as well!

**Comment by xiota** [comment]
Some programs that were giving me icu loading errors earlier are now working without rebuild.  Why?  How?

**Comment by FGD-Garuda** [comment]
> Some programs that were giving me icu loading errors earlier are now working without rebuild. Why? How?

I can't answer that, but I believe I can confirm the same behavior on my end.
36h before writing this, I tried installing a -git package to swap from my -bin and it couldn't resolve the icu 73 deps.
FFWD 36h later I synced the mirrors but did not update system, then I just tried again to install the -git version and it worked.

App is also working, so it's more than just installing fine it runs fine too.

**Comment by xiota** [comment]
I think I figured it out.  `ldd` reports libraries recursively, so indirect depends are included.  When whatever package in the chain is updated, the error goes away.

To see direct depends only, use one of the following:
```
readelf -d /usr/bin/example | grep NEEDED
objdump -p /usr/bin/example | grep NEEDED
```

`namcap` does report `icu` depends, but the recursive, indirect errors from `ldd` were confusing me.  Also, when the library name is available, `namcap` reports it instead of the package name.  If the library name is listed in depends, `pacman` can attempt to detect issues and abort the upgrade with a message similar to:
```
:: installing icu (74.2-1) breaks dependency 'libicuuc.so=73-64' required by example
```
I had noticed `namcap` output was different, but didn't know why.  A lot of packages need to be updated.

**Comment by xiota** [comment]
This should be safe to close now.

For record, when this is needed again, first-level deps were rebuilt.  A handful of packages from other levels also needed to be rebuilt.  `-bin` packages were excluded.

**Comment by dr460nf1r3** [comment]
Very nice, thanks! 😊

**Comment by xiota** [comment]
It's that time again... icu 74 → 75...

**Comment by lesacar** [comment]
> It's that time again... icu 74 → 75...

And.... again for 75 -> 76, ungoogled-chromium-bin and sunshine are broken for me, probably every other icu dependent package.

**Comment by xiota** [comment]
Will bump in a bit...

`ungoogled-chromium-bin` would need upstream rebuild.

sunshine... rebuild may be delayed while think about whether to add as sodep...
