### ISSUE TITLE
[Request] vinegar-git

### ISSUE THREAD

**Issue by nyabinary** [chaotic-aur/packages#2961]
### Package:

[vinegar-git](https://aur.archlinux.org/packages/vinegar-git)

### Purpose:

Roblox On Linux

### Benefits:

Playing Roblox
In case a Roblox update broke Vinegar instead of waiting for a version release it can fetch the latest git and just use that which would hopefully include a fix. 

### Building:

N/A

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
There is an incorrect directory reference in [the package function](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vinegar-git#n43), they need to fix this:
[vinegar-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/vinegar-git.log)

**Comment by TheComputerGuy96** [comment]
@Technetium1 I pushed a workaround to my package so it should build now :frog:

**Comment by xiota** [comment]
Fails to build because of upstream changes.  According to [FAQ](https://vinegarhq.org/Home/rol_faq.html), Roblox has blocked WINE.  Is there any need to continue providing this?

Metrics.

* vinegar # 150
* vinegar-git # 34

**Comment by Technetium1** [comment]
I think it is probably good to keep providing this (at least in the near future), as Roblox Studio does not have the problematic Hyperion added in as of now, so it is possible to use it for development, but not for playing.

[Will Studio be affected?](https://vinegarhq.org/Home/rol_faq.html#will-studio-be-affected)

> No, Studio will continue to work. Bitdancer has confirmed that Roblox Studio will not be receiving Hyperion currently, as it’s only used for game development. Vinegar will continue to maintain Roblox Studio support.

---

Anyone who wishes to _play_ the game should investigate https://sober.vinegarhq.org
