### ISSUE TITLE
[Bug] gtk2-patched-filechooser-icon-view does not provide gtk2

### ISSUE THREAD

**Issue by BowDown097** [chaotic-aur/packages#2962]
### Packages:

https://aur.archlinux.org/packages/gtk2-patched-filechooser-icon-view

### Latest chaotic version

2.24.33-3

### What happens?

The package does not provide gtk2 whilst conflicting with gtk2, therefore it's impossible to install if you have anything that depends on gtk2.

### What is expected to happen?

The package should provide gtk2, as its gtk3 counterpart (and the AUR package itself, which is interesting) correctly does.

**Comment by xiota** [comment]
> the AUR package itself, which is interesting

Maintainer had changed `provides` without bumping `pkgrel`, so the package wasn't rebuilt with the update.

Rebuilding now.
