### ISSUE TITLE
texlab-bin [Request] 

### ISSUE THREAD

**Issue by caniko** [chaotic-aur/packages#2969]
### Package:

https://aur.archlinux.org/packages/texlab-bin

### Purpose:

LSP server for Latex

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
@caniko `extra/texlab` has `5.6.0-1`, why are the versions so far apart? What's going on here?

**Comment by xiota** [comment]
@caniko Please edit request.  Write a better description of the program under purpose.  Add explanation about `extra/texlab` being out of date since when under benefits.

**Comment by caniko** [comment]
No.

**Comment by xiota** [comment]
Request is rejected because it does not contain adequate description of the package and does not provide sufficient justification for maintenance burden.
