### ISSUE TITLE
[Bug] firefox nightly requires `nspr-hg` and `nss-hg`

### ISSUE THREAD

**Issue by ConnorJC3** [chaotic-aur/packages#2970]
### Packages:

https://aur.archlinux.org/packages/firefox-nightly

### Latest chaotic version

`123.0a1+20231222.3+h8b474eeffbe0-1`

### What happens?

Installing the chaotic version of `firefox-nightly` has an explicit dependency on `nspr-hg` and `nss-hg`:

```
$ pacman -Qi firefox-nightly
Name            : firefox-nightly
Version         : 123.0a1+20231222.3+h8b474eeffbe0-1
Description     : Standalone web browser from mozilla.org - nightly, targeting wayland and x11
Architecture    : x86_64
URL             : https://www.mozilla.org/firefox/channel/#nightly
Licenses        : GPL  LGPL  MPL
Groups          : None
Provides        : firefox-nightly
Depends On      : dbus-glib  ffmpeg  gtk3  libpulse  mime-types  nspr-hg  nss-hg  ttf-font  libvpx  libwebp  libjpeg  zlib  libevent  pipewire  libxss  libxt
Optional Deps   : hunspell-en_US: Spell checking, American English
                  libnotify: Notification integration [installed]
                  networkmanager: Location detection via available WiFi networks [installed]
                  pulseaudio: Audio support [installed]
                  speech-dispatcher: Text-to-Speech [installed]
                  xdg-desktop-portal: Screensharing with Wayland [installed]
Required By     : None
Optional For    : None
Conflicts With  : firefox-nightly
Replaces        : None
Installed Size  : 278.98 MiB
Packager        : Garuda Builder <team@garudalinux.org>
Build Date      : Fri 22 Dec 2023 04:36:40 AM EST
Install Date    : Mon 25 Dec 2023 08:55:30 PM EST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

However, the AUR package only depends on `nss`, not `nss-hg`: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=firefox-nightly#n24

### What is expected to happen?

I should be able to install `firefox-nightly` from the AUR without needing to install the latest unstable versions of `nss` and `nspr`.

### Logs

Unlikely to be relevant, but: https://builds.garudalinux.org/repos/chaotic-aur/logs/firefox-nightly.log

**Comment by xiota** [comment]
In the future search and comment on existing issues that are relevant.  `aur/firefox-nightly` is currently not building successfully.  #2958

`chaotic-aur/firefox-nightly` that you reference was built with an alternate PKGBUILD while trying to figure out why `aur/firefox-nightly` was not working.  I forgot that the depends were slightly different, and it is now deleted from the repo.

`firefox-nightly` will *not* be available until the upstream issues are resolved.

**Comment by ConnorJC3** [comment]
I saw that issue but it didn't mention the existing copy had been built with a different PKGBUILD until your comment after my issue was filed, thanks for the information.
