### ISSUE TITLE
[Request] gamescope-nvidia-git

### ISSUE THREAD

**Issue by caniko** [chaotic-aur/packages#2972]
### Package:

https://aur.archlinux.org/packages/gamescope-nvidia-git

### Purpose:

For gaming with nvidia hardware using the same environment as steam products (steam deck).

### Benefits:

[For me](https://www.reddit.com/r/hyprland/comments/13rrne7/wine_cant_set_a_the_currect_resolution_on_hyprland/); general benefits for gamescope outlined on [repo](https://github.com/ValveSoftware/gamescope)

### Copyright:

BSD

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by LukeShortCloud** [comment]
Gamescope 3.14.3 (now updated in the Arch Linux Extra repository) finally includes NVIDIA support. The `gamescope-nvidia-git` package is no longer needed.
