### ISSUE TITLE
[Bug] htop-git is built without CPU temperature support

### ISSUE THREAD

**Issue by BowDown097** [chaotic-aur/packages#2973]
### Packages:

https://aur.archlinux.org/packages/htop-git

### Latest chaotic version

3.2.2.210.g6490590d-1

### What happens?

See title.

### What is expected to happen?

CPU temperature is shown in htop, as is the case with the normal version in the Arch repos.

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/htop-git.log

### More information

I believe the build environment just needs to have lm_sensors installed. For some reason this isn't listed as an optional dependency in the AUR package either.

**Comment by Technetium1** [comment]
I left [a comment for the maintainer](https://aur.archlinux.org/packages/htop-git#comment-949870).

**Comment by Technetium1** [comment]
Fixed in https://aur.archlinux.org/cgit/aur.git/commit/?h=htop-git&id=1dd90843ef8bc62d5e024ece5cf2b4f76f7530a8
