### ISSUE TITLE
[Request] r2modman-bin

### ISSUE THREAD

**Issue by Redo11** [chaotic-aur/packages#2974]
### Package:

https://aur.archlinux.org/packages/r2modman-bin

### Purpose:

It allows you to install and manage mods for several games, like "Risk of Rain 2, Dyson Sphere Program, Valheim, GTFO, BONEWORKS" and Lethal Company

### Building:

This is a bin package

### Copyright:

MIT

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Looks like an electron app.  Electron packages tend to be large, and I would prefer that the `cp -r` be replaced with `cp --reflink=auto -r` or `mv` to reduce package time and unnecessary writes.

The package also potentially breaks a nonsense guideline that shouldn't even exist.

**Comment by xiota** [comment]
Dropping because uses EOL Electron/24.8.8.  Metrics 102.
