### ISSUE TITLE
[Request] lib32-vulkan-nouveau-git

### ISSUE THREAD

**Issue by CalcProgrammer1** [chaotic-aur/packages#2976]
### Package:

https://aur.archlinux.org/packages/lib32-vulkan-nouveau-git

### Purpose:

NVK 32-bit version.  I installed the 64-bit vulkan-nouveau-git from chaotic-aur to test the new NVK Vulkan driver and noticed a lot of games wouldn't start, but then I realized they were 32-bit games and needed the 32-bit version lib32-vulkan-nouveau-git.  I installed that one from AUR normally and the 32-bit games I tested (Skyrim original edition and Lego Star Wars Complete Collection) are working now.  It would be nice if this were also available in chaotic-aur so I don't have to manually build updates.

### Benefits:

Benefits gaming with the open source NVIDIA NVK Vulkan driver for 32-bit games (including via DXVK).

### Building:

I used yay to build this for me

### Copyright:

It is listed as "custom" on AUR but I assume it's the same as all other mesa packages

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

Yes

### More information:

It is a banned package according to lib32-* but I feel this package would be a worthy exception to this rule because game support is the primary reason 32-bit packages are still necessary and this allows a ton of 32-bit games to function.  It is not possible to "use 64 bit instead" in this case because a 32-bit driver component is needed to play 32-bit games.

If it still does not qualify due to being 32-bit feel free to close this, but I feel this is an important enough package for people wanting to test drive this new driver that it should be considered.

**Comment by xiota** [comment]
Adding this package would be reasonable given your explanation and use case, assuming no issues with it.  Were there any special build requirements that you can recall?  Approx how long did it take to compile?

Would you mind testing the games with `wine-wow64`, `wine-wow64-git`, `wine-staging-wow64`, and/or `wine-staging-wow64-git`?

**Comment by CalcProgrammer1** [comment]
It didn't take very long on my laptop (Ryzen 9 5900HX).  It looks like the build took 4 minutes according to the build log.  I've tested all the games I've tried using Steam/Proton.  There was one make dependency: lib32-rust-libs-1 which installed from the official Arch repository.  I will look into testing games with the listed wine versions.

**Comment by danayer** [comment]
I support, it would be great if this package was added, it will speed up testing of x32 applications and games, since now the absence of this package causes problems with most software. :(

**Comment by xiota** [comment]
@CalcProgrammer1 @danayer I'm waiting on feedback on whether problem games work with `wine-wow64-*`.

**Comment by danayer** [comment]
I tried to launch without lib32-vulkan-nouveau-git, wine-wow64-git, but the launch did not happen, both in zink and dxvk, it just gives errors. When I installed lib32-vulkan-nouveau-git from aur, the error disappeared and the launch started.
<details>
<summary>DXVK</summary>
0024:fixme:vulkan:wine_vkMapMemory2KHR returned mapping 0x7f61f0800000 does not fit 32-bit pointer
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_OUT_OF_HOST_MEMORY
0024:fixme:vulkan:wine_vkMapMemory2KHR returned mapping 0x7f61f1000000 does not fit 32-bit pointer
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_OUT_OF_HOST_MEMORY
0024:fixme:vulkan:wine_vkMapMemory2KHR returned mapping 0x7f61f8200000 does not fit 32-bit pointer
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_OUT_OF_HOST_MEMORY
0024:fixme:vulkan:wine_vkMapMemory2KHR returned mapping 0x7f61f8400000 does not fit 32-bit pointer
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_OUT_OF_HOST_MEMORY
0024:fixme:vulkan:wine_vkMapMemory2KHR returned mapping 0x7f61fb700000 does not fit 32-bit pointer
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_OUT_OF_HOST_MEMORY
0024:fixme:vulkan:wine_vkMapMemory2KHR returned mapping 0x7f61fd83f000 does not fit 32-bit pointer
err:   DxvkMemoryAllocator: Mapping memory failed with VK_ERROR_OUT_OF_HOST_MEMORY
</details>
<details>
<summary>ZINK</summary>
Wine Command: /usr/bin/wine /home/danayer/Games/Heroic/Prefixes/default/OVERLORD 2/drive_c/GOG Games/Overlord/Overlord.exe 
Game Log:
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0024:err:environ:init_peb starting L"C:\\GOG Games\\Overlord\\Overlord.exe" in experimental wow64 mode
0024:fixme:system:NtUserSystemParametersInfo Unimplemented action: 59 (SPI_SETSTICKYKEYS)
0024:fixme:system:NtUserSystemParametersInfo Unimplemented action: 53 (SPI_SETTOGGLEKEYS)
0024:fixme:system:NtUserSystemParametersInfo Unimplemented action: 51 (SPI_SETFILTERKEYS)
WARNING: NVK is not a conformant Vulkan implementation, testing use only.
WARNING: NVK is not a conformant Vulkan implementation, testing use only.
WARNING: NVK is not a conformant Vulkan implementation, testing use only.
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  329
  Current serial number in output stream:  330
============= End of game logs =============

</details>

**Comment by xiota** [comment]
Were the above tests with `vulkan-nouveau-git` installed?

**Comment by danayer** [comment]
Yes, from chaotic-aur, only removed `lib32-vulkan-nouveau-git` for testing

**Comment by danayer** [comment]
But everything worked, a complete reinstallation of the driver helped.
<details>
Game launched at: Fri Jan 12 2024 22:58:30 GMT+0800 (Иркутск, стандартное время)

Wine Command: /usr/bin/wine /home/danayer/Games/Heroic/Prefixes/default/OVERLORD 2/drive_c/GOG Games/Overlord/Overlord.exe 

Game Log:
002c:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
007c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0024:err:environ:init_peb starting L"C:\\GOG Games\\Overlord\\Overlord.exe" in experimental wow64 mode
0024:fixme:system:NtUserSystemParametersInfo Unimplemented action: 59 (SPI_SETSTICKYKEYS)
0024:fixme:system:NtUserSystemParametersInfo Unimplemented action: 53 (SPI_SETTOGGLEKEYS)
0024:fixme:system:NtUserSystemParametersInfo Unimplemented action: 51 (SPI_SETFILTERKEYS)
WARNING: NVK is not a conformant Vulkan implementation, testing use only.
[2024-01-12 22:58:37.533] [MANGOHUD] [error] [overlay_params.cpp:142] Unrecognized key: '=Shift_L'
[2024-01-12 22:58:37.533] [MANGOHUD] [error] [overlay_params.cpp:816] Unknown option 'refresh_rate'
[2024-01-12 22:58:37.533] [MANGOHUD] [error] [overlay_params.cpp:816] Unknown option 'io_stats'
[2024-01-12 22:58:37.533] [MANGOHUD] [error] [overlay_params.cpp:816] Unknown option 'engine'
WARNING: NVK is not a conformant Vulkan implementation, testing use only.
[2024-01-12 22:58:37.823] [MANGOHUD] [error] [overlay_params.cpp:142] Unrecognized key: '=Shift_L'
[2024-01-12 22:58:37.823] [MANGOHUD] [error] [overlay_params.cpp:816] Unknown option 'refresh_rate'
[2024-01-12 22:58:37.823] [MANGOHUD] [error] [overlay_params.cpp:816] Unknown option 'io_stats'
[2024-01-12 22:58:37.823] [MANGOHUD] [error] [overlay_params.cpp:816] Unknown option 'engine'
WARNING: NVK is not a conformant Vulkan implementation, testing use only.
[2024-01-12 22:58:38.093] [MANGOHUD] [error] [overlay_params.cpp:142] Unrecognized key: '=Shift_L'
[2024-01-12 22:58:38.093] [MANGOHUD] [error] [overlay_params.cpp:816] Unknown option 'refresh_rate'
[2024-01-12 22:58:38.093] [MANGOHUD] [error] [overlay_params.cpp:816] Unknown option 'io_stats'
[2024-01-12 22:58:38.093] [MANGOHUD] [error] [overlay_params.cpp:816] Unknown option 'engine'
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0024:fixme:d3d9:Direct3DShaderValidatorCreate9 Returning stub validator 7A7BC028.
0024:fixme:d3d9:Direct3DShaderValidatorCreate9 Returning stub validator 7A7BC028.
0024:err:d3d:wined3d_swapchain_resize_buffers Something's still holding back buffer 0 (0328C788).
0024:fixme:d3d9:Direct3DShaderValidatorCreate9 Returning stub validator 7A7BC028.
0024:fixme:d3d9:Direct3DShaderValidatorCreate9 Returning stub validator 7A7BC028.
0024:fixme:wbemprox:client_security_SetBlanket 79E01850, 01B1BF00, 10, 0, (null), 3, 3, 00000000, 0
0024:fixme:wbemprox:client_security_Release 79E01850
0024:fixme:wbemprox:enum_class_object_Next timeout not supported
0024:fixme:wbemprox:client_security_SetBlanket 79E01850, 01B1BF00, 10, 0, (null), 3, 3, 00000000, 0
0024:fixme:wbemprox:client_security_Release 79E01850
0024:fixme:d3d9:Direct3DShaderValidatorCreate9 Returning stub validator 7A7BC028.
0024:fixme:d3d9:Direct3DShaderValidatorCreate9 Returning stub validator 7A7BC028.
013c:err:ole:com_get_class_object class {8c779023-bd0e-43a0-a876-c4a54e0a7d5c} not registered
013c:err:ole:com_get_class_object no class object {8c779023-bd0e-43a0-a876-c4a54e0a7d5c} could be created for context 0x1
0118:fixme:rawinput:NtUserRegisterRawInputDevices Unhandled flags 0x230 for device 0.
0114:fixme:d3d:state_linepattern_w Setting line patterns is not supported in OpenGL core contexts.
0024:fixme:d3d9:Direct3DShaderValidatorCreate9 Returning stub validator 7A7BC028.
0024:fixme:d3d9:Direct3DShaderValidatorCreate9 Returning stub validator 7A7BC028.
0118:fixme:rawinput:NtUserRegisterRawInputDevices Unhandled flags 0x230 for device 0.
0024:fixme:d3d9:Direct3DShaderValidatorCreate9 Returning stub validator 7A7BC028.
0024:fixme:d3d9:Direct3DShaderValidatorCreate9 Returning stub validator 7A7BC028.
0024:fixme:d3d9:Direct3DShaderValidatorCreate9 Returning stub validator 7A7BC028.
0024:fixme:d3d9:Direct3DShaderValidatorCreate9 Returning stub validator 7A7BC028.
0024:fixme:d3d9:Direct3DShaderValidatorCreate9 Returning stub validator 7A7BC028.
0024:fixme:d3d9:Direct3DShaderValidatorCreate9 Returning stub validator 7A7BC028.
0024:fixme:d3d9:Direct3DShaderValidatorCreate9 Returning stub validator 7A7BC028.
0024:fixme:d3d9:Direct3DShaderValidatorCreate9 Returning stub validator 7A7BC028.
0024:fixme:d3d9:Direct3DShaderValidatorCreate9 Returning stub validator 7A7BC028.
0024:fixme:d3d9:Direct3DShaderValidatorCreate9 Returning stub validator 7A7BC028.
0024:fixme:d3d9:Direct3DShaderValidatorCreate9 Returning stub validator 7A7BC028.
0024:fixme:d3d9:Direct3DShaderValidatorCreate9 Returning stub validator 7A7BC028.
0118:fixme:rawinput:NtUserRegisterRawInputDevices Unhandled flags 0x230 for device 0.
0180:fixme:console:default_ctrl_handler Terminating process 20 on event 0
</details>
