### ISSUE TITLE
[Request] stable-diffusion-web-ui-git

### ISSUE THREAD

**Issue by caniko** [chaotic-aur/packages#2977]
### Package:

https://aur.archlinux.org/packages/stable-diffusion-web-ui-git

### Purpose:

Run stable diffusion on local hardware behind a web ui

### Benefits:

FOSAI!

### Copyright:

AGPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
Needs confirmation of deps https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/requirements_versions.txt

**Comment by caniko** [comment]
These deps are installed on non-root under home of the user.

**Comment by xiota** [comment]
Inclined to reject.  Not properly packaged.  Can't tell if it's an upstream issue.

**Comment by xiota** [comment]
@caniko Standard python packages use [PEP517](https://wiki.archlinux.org/title/Python_package_guidelines#Standards_based_(PEP_517)) install method.  Some still use older methods, but those are starting to break, so everyone should be moving to PEP517.

You noted, "These deps are installed on non-root under home of the user."  That is a clear indication of poor packaging.  Could be an upstream issue if the program can't be used any other way.

**Comment by caniko** [comment]
The issue is that the framework uses a virtual environment for the Python packages, this might make sense for other platforms. You are right that it is wrong for at least Arch.

We should definitely provide guidance, it is a large project.

**Comment by xiota** [comment]
It is poor *packaging*.  If the program cannot be used outside a virtual environment, it should be installed that way by the user, not system-wide through the package manager.

**Comment by caniko** [comment]
Well the package itself is the manager not even itself... Following this logic you could say that `pyenv` is poorly packaged.

I totally disagree with your opinion. It is unreasonable to expect this from Python packages.

You are effectively banning every package that pins versions, meaning AI applications must be installed at the non-root level.

**Comment by xiota** [comment]
Package cannot be accepted in its current state because it does not follow Arch package guidelines.  If upstream issues prevent it from being packaged properly, it should be rejected without trying to fix it.

Pinning versions is a separate issue.  If a package with pinned versions stops working, it will be dropped because it is broken, not for having pinned versions.

**Comment by Technetium1** [comment]
@xiota is correct. This is not right for us to add.
