### ISSUE TITLE
[Request] beaver-notes

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#2979]
### Package:

https://aur.archlinux.org/packages/beaver-notes-bin
https://aur.archlinux.org/packages/beaver-notes

### Purpose:

This is not only a very useful and modern looking Notes app, but it seems to be sustainable for the long run. I have personally chatted over the email with the main developer about the future of it and how can he make this sustainable. We are going to use this as our default notes app for TROMjaro and thus there is a lot of interest in keeping it going and checking to make sure the app works well. They even released a mobile notes app https://beavernotes.com/pocket and so you can have your notes on all devices.

Overall I think it is well deserving to have this one. We have already added it to our repo.

### Benefits:

I have tested so many notes applications and it is rare to find one that checks the many features that this one does. For one it is modern and supports markdown. Thus, easy to use for anyone but powerful enough for all of us. Supports copy-pasting images, table of contents, search, and dark/light modes for its theming. And a lot more.

### Copyright:

MIT

### Expected Interest:

Everyone

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by tio-trom** [comment]
I have contacted the developer however from what I understand it builds against the system's electron. On my system it was built against electron22. See https://paste.trom.tf/sixeniqiso.pl

Maybe it is this that matters https://github.com/Daniele-rolli/Beaver-Notes/blob/55baa74a7a585b3461b3bae89ac498ea10ed25dd/package.json#L44 ?

**Comment by Technetium1** [comment]
@tio-trom I had to do a search to confirm my understanding, but it appears `electron-builder` is only part of packaging specifics the OS needs, **not** building the actual application itself. This can be confirmed in your log with the line:

```
  • packaging       platform=linux arch=x64 electron=13.6.9 appOutDir=dist/linux-unpacked
```

Here's an example of how it _could_ look to force system electron, but this is maintainers job to update, and upstream's responsibility to bump:
https://github.com/yochananmarqos/pkgbuilds/blob/c7cd68878df8484d2698b32048e406144d1ff758/beaver-notes/PKGBUILD#L7-L34

**Comment by tio-trom** [comment]
> @tio-trom I had to do a search to confirm my understanding, but it appears `electron-builder` is only part of packaging specifics the OS needs, **not** building the actual application itself. This can be confirmed in your log with the line:
> 
> ```
>   • packaging       platform=linux arch=x64 electron=13.6.9 appOutDir=dist/linux-unpacked
> ```
> 
> Here's an example of how it _could_ look to force system electron, but this is maintainers job to update, and upstream's responsibility to bump: https://github.com/yochananmarqos/pkgbuilds/blob/c7cd68878df8484d2698b32048e406144d1ff758/beaver-notes/PKGBUILD#L7-L34

The developer will update to the newer electron and all of the required dependencies and will leave a comment here when he does that :)

**Comment by Daniele-rolli** [comment]
Hey there, I'm the developer of Beaver Notes. I've updated Beaver Notes from Electron 13.6.9 to 28.1.1. Thanks for pointing out the issue with the old release of Electron. The task of updating it fell a bit into my backlog, so this issue has been somewhat of a wake-up call.
