### ISSUE TITLE
[Request] tuxedo-drivers-dkms

### ISSUE THREAD

**Issue by gllmhyt** [chaotic-aur/packages#2981]
### Package:

https://aur.archlinux.org/packages/tuxedo-drivers-dkms

### Purpose:

Required dependency for tuxedo-control-center-bin

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Package is missing `conflicts` and uses `replaces`.  Packages on AUR should not use `replaces`.

**Comment by xiota** [comment]
I've edited this request to keep related packages together in package list.

**Comment by Technetium1** [comment]
This will hopefully be resolved soon: https://github.com/tuxedocomputers/tuxedo-control-center/issues/148

**Comment by xiota** [comment]
"Soon" – That issue was opened in 2021.

**Comment by malisipi** [comment]
Tuxedo control center is supporting newer Electron for awhile. And the latest version of Tuxedo control center is using [Electron 41](
https://github.com/tuxedocomputers/tuxedo-control-center/blob/aa85b059ad74bf5d8479127f4aaad2056cc46672/package.json#L110) (which is still supported, unlike the previous ones).

It would be good if you reconsider adding Tuxedo control center again.

**Comment by Technetium1** [comment]
@malisipi subscribe to #3953, it will return.
