### ISSUE TITLE
[Rebuild] tuxedo-control-center-bin

### ISSUE THREAD

**Issue by gllmhyt** [chaotic-aur/packages#2982]
### Packages:

https://aur.archlinux.org/packages/tuxedo-control-center-bin
https://aur.archlinux.org/packages/tuxedo-drivers-dkms

### Latest chaotic version

2.0.11-1

### Reason for rebuild

Build is broken since it's missing the new dependency to tuxedo-drivers-dkms instead of tuxedo-keyboard-dkms

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/tuxedo-control-center-bin.log

**Comment by xiota** [comment]
#2981
