### ISSUE TITLE
[Request] clang17, llvm17[-libs] and compiler-rt17

### ISSUE THREAD

**Issue by tiziodcaio** [chaotic-aur/packages#2983]
### Package:

https://aur.archlinux.org/packages/clang17
https://aur.archlinux.org/packages/compiler-rt17
https://aur.archlinux.org/pkgbase/llvm17

### Purpose:

Reduce builds costs

### Benefits:

It might accelerate the migration on the main arch repositories to clang17 if we had more testing

### Building:

Simple makepkg

### Copyright:

LLVM's Apache 2

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

Yes

**Comment by xiota** [comment]
Supposedly, installing `extra/pkgstats` may help Arch devs decide package priority.

At least seeing the results is interesting: [pkgstats:clang](https://pkgstats.archlinux.de/packages?query=clang)

**Comment by xiota** [comment]
`extra/clang` is now 17.0.6.
