### ISSUE TITLE
[Rebuild] stremio

### ISSUE THREAD

**Issue by drdaffey** [chaotic-aur/packages#2985]
### Packages:

https://aur.archlinux.org/packages/stremio

### Latest chaotic version

4.4.165-1

### Reason for rebuild

Need to rebuild against icu 74.2-1

"Error while starting streaming server...
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 127

/opt/stremio/node: error while loading shared libraries: libicui18n.so.73: cannot open shared object file: No such file or directory"

**Comment by Technetium1** [comment]
`Finished making: stremio 4.4.165-1.1 (Tue 09 Jan 2024 09:18:16 PM CET)`
