### ISSUE TITLE
[Request] wayland-chromium

### ISSUE THREAD

**Issue by knvzzz** [chaotic-aur/packages#2987]
### Package:

https://aur.archlinux.org/packages/wayland-chromium

### Purpose:

EGL support for chromium-wayland-vaapi

### Benefits:

VA-API in Chromium under Wayland.

### Copyright:

MIT

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
Optional dependency for #1243
