### ISSUE TITLE
[Request] openresty

### ISSUE THREAD

**Issue by cattokomo** [chaotic-aur/packages#2988]
### Package:

https://aur.archlinux.org/packages/openresty

### Purpose:

OpenResty is not provided in an updated form by any other package.

### Benefits:

Provides bindings to nginx, which are useful when hosting an API server.

### Copyright:

BSD

### Expected Interest:

Most

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Please write a better description of the package under purpose and write a use-case under benefits.
