### ISSUE TITLE
[Request] gamescope-session-git and gamescope-session-steam-git

### ISSUE THREAD

**Issue by LukeShortCloud** [chaotic-aur/packages#2989]
### Package:

https://aur.archlinux.org/packages/gamescope-session-git
https://aur.archlinux.org/packages/gamescope-session-steam-git

### Purpose:

`gamescope-session-git` allows users to create sessions that launch `gamescope` and a single command. This lowers the amount of background resources by avoiding the use of a desktop environment entirely.

Most users are interested in `gamescope-session-steam-git` which provides a session for Steam to mimic SteamOS. The session will automatically appear in the display manager.

### Benefits:

The only other alternative package is gamescope-session from the official SteamOS repositories which (1) lacks community patches that add new features and more supported devices and (2) is built against an old version of Arch Linux.

### Building:

`gamescope-session-git` is a build dependency of `gamescope-session-steam-git`.

```
$ makepkg -i gamescope-session-git
$ makepkg gamescope-session-steam-git
```

### Copyright:

MIT

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

These packages are used by at least ChimeraOS, HoloISO, and winesapOS.

**Comment by xiota** [comment]
Both packages have comments indicating users are having problems with them.  Do you know anything about them?  Do the packages need to be flagged for maintainer attention?

**Comment by LukeShortCloud** [comment]
The last time I did a build with these packages was about 1 week before the `gamescope-session-git` issue was reported. I will test them out again. `gamescope-session-git` may have a real issue. `gamescope-session-steam-git` has a comment about an old issue that has already been addressed.

**Comment by LukeShortCloud** [comment]
I updated to the latest Arch Linux and then built and installed the latest packages. They work as expected. Tested on both an AMD and Intel APU. I did not have the suggested dependencies installed on my system from one of the most recent comments on `gamescope-session-steam-git`. It seems like their issue might be specific to using `gamescope-git` (AUR) instead of `gamescope` (extras) and is unrelated to the session itself anyways.

There is some general confusion about how it actually works. The important things to note are:

- `steam` should be installed (I added a suggestion for it to be a `depends=`)
- Either (1) `steam` needs to be launched at least once from the desktop or (2) Steam client bootstrap files need to be manually downloaded and extracted before using the Gamescope session of Steam. This is a limitation of the Steam client and they cannot be distributed due to legal conerns.
- GPU support: AMD = best, Intel = okay, NVIDIA = does not work. Valve mainly tests Gamescope on AMD so this is not a huge surprise.

**Comment by xiota** [comment]
Thanks for making sure the packages are functional.

They have some defects that need to be corrected.  I've commented to notify the maintainer.

**Comment by xiota** [comment]
The maintainer has not responded to comments.  You may want to flag the package to get their attention.  If they ignore the flag long enough (6 months) someone else can take over the package and fix it.

**Comment by LukeShortCloud** [comment]
@xiota I reached out to the maintainer of the gamescope-session-steam related packages. They have now addressed all of the feedback. It was decided to not add a depends on Steam in case users wanted to try using the Steam Flatpak instead. Any chance we can get this into the Chaotic AUR soon?

**Comment by xiota** [comment]
They're added now.  Let me know if they're working.

**Comment by LukeShortCloud** [comment]
@xiota I recently tested these gamescope-session packages from the Chaotic AUR and they work great. Thank you!

**Comment by xiota** [comment]
Glad they're working well, and appreciate your patience.
