### ISSUE TITLE
[Bug] After updating the linux-xanmod package to 6.6.11, no dkms modules are built

### ISSUE THREAD

**Issue by Boria138** [chaotic-aur/packages#2991]
### Packages:

https://aur.archlinux.org/packages/linux-xanmod

### Latest chaotic version

6.6.11

### What happens?

When trying to build any dkms modules, the following error occurs 
```
==> dkms install --no-depmod broadcom-wl/6.30.223.271 -k 6.6.11-x64v-xanmod1-1
Error! Bad return status for module build on kernel: 6.6.11-x64v-xanmod1-1 (x86_64)
Consult /var/lib/dkms/broadcom-wl/6.30.223.271/build/make.log for more information
```

### What is expected to happen?

There shouldn't be any errors

### More information

When looking through the dkms logs I found that it lacked to build clang and ld.lld after installing clang and lld errors disappeared, while in the package linux-xanmod-bin everything is built and without these packages

**Comment by xiota** [comment]
> after installing clang and lld errors disappeared

To clarify, modules built successfully after `clang` and `lld` were installed?

**Comment by Boria138** [comment]
> > after installing clang and lld errors disappeared
> 
> To clarify, dkms modules built successfully after `clang` and `lld` were installed?
> 
> When I added the `v2/v3` versions, I set all the xanmod kernels to build with `clang`. I can switch `linux-xanmod` and `linux-xanmod-lts` back to `gcc` if there is some pressing reason not to use `clang`, effective with the next release. The `v2/v3` versions would continue to be built with `clang`.

Here is the dkms log without clang and lld installed

```
DKMS make.log for vboxhost-7.0.12_OSE for kernel 6.6.11-x64v-xanmod1-1 (x86_64)
Sun Jan 14 10:55:40 +06 2024
make: Entering directory '/usr/lib/modules/6.6.11-x64v-xanmod1-1/build'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: clang version 16.0.6
  You are using:           
  CC [M] /var/lib/dkms/vboxhost/7.0.12_OSE/build/vboxdrv/linux/SUPDrv-linux.o
/bin/sh: line 1: clang: command not found
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/vboxhost/7.0.12_OSE/build/vboxdrv/linux/SUPDrv-linux.o] Error 127
make[3]: *** Waiting for tasks to complete...
make[2]: *** [scripts/Makefile.build:480: /var/lib/dkms/vboxhost/7.0.12_OSE/build/vboxdrv] Error 2
make[2]: *** Waiting for tasks to be completed…
  CC [M] /var/lib/dkms/vboxhost/7.0.12_OSE/build/vboxnetflt/linux/VBoxNetFlt-linux.o
/bin/sh: line 1: clang: command not found
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/vboxhost/7.0.12_OSE/build/vboxnetflt/linux/VBoxNetFlt-linux.o] Error 127
make[3]: *** Waiting for tasks to be completed…
  CC [M]  /var/lib/dkms/vboxhost/7.0.12_OSE/build/vboxnetflt/VBoxNetFlt.o
/bin/sh: line 1: clang: command not found
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/vboxhost/7.0.12_OSE/build/vboxnetflt/VBoxNetFlt.o] Error 127
make[2]: *** [scripts/Makefile.build:480: /var/lib/dkms/vboxhost/7.0.12_OSE/build/vboxnetflt] Error 2
  CC [M] /var/lib/dkms/vboxhost/7.0.12_OSE/build/vboxnetadp/linux/VBoxNetAdp-linux.o
/bin/sh: line 1: clang: command not found
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/vboxhost/7.0.12_OSE/build/vboxnetadp/linux/VBoxNetAdp-linux.o] Error 127
make[3]: *** Waiting for tasks to be completed…
  CC [M] /var/lib/dkms/vboxhost/7.0.12_OSE/build/vboxnetadp/VBoxNetAdp.o
/bin/sh: line 1: clang: command not found
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/vboxhost/7.0.12_OSE/build/vboxnetadp/VBoxNetAdp.o] Error 127
make[2]: *** [scripts/Makefile.build:480: /var/lib/dkms/vboxhost/7.0.12_OSE/build/vboxnetadp] Error 2
make[1]: *** [/usr/lib/modules/6.6.11-x64v-xanmod1-1/build/Makefile:2068: /var/lib/dkms/vboxhost/7.0.12_OSE/build] Error 2
make: *** [Makefile:234: __sub-make] Error 2
make: Leaving directory '/usr/lib/modules/6.6.11-x64v-xanmod1-1/build'
```
As you can see the problem is that the kernel was built with clang, and I have it on my system, I suggest either adding clang and lld to the xanmod dependencies, or building the kernel with gcc

**Comment by Boria138** [comment]
I may ask a stupid question, but why was it necessary to build the kernel through clang, for building under x86_64v2 and v3 building through clang is apparently not necessary, at least I use the ALHP repository with packages built specifically for x86_64v3 and the zen kernel from there has no problems with dkms from which I concluded that it is built through gcc, I think to build the kernel you should not change the compiler at all because to build dkms you will need the same compiler that was used to build the kernel which may not be on the system, I apologize in advance if the question is really stupid, just wondering why you decided to change the compiler

**Comment by xiota** [comment]
Reason to use xanmod kernels is to improve system performance.  `clang` binaries typically outperform `gcc` binaries.  This applies to the kernel: [Squeezing More Performance Out Of The Linux Kernel With Clang + LTO](https://www.phoronix.com/review/clang-lto-kernel).

**Comment by Boria138** [comment]
> Reason to use xanmod kernels is to improve system performance.  `clang` binaries typically outperform `gcc` binaries.  This applies to the kernel: [Squeezing More Performance Out Of The Linux Kernel With Clang + LTO](https://www.phoronix.com/review/clang-lto-kernel).

Thanks for the clarification, then I guess it would be more logical not to rebuild the kernel, but just add clang and ldd to the dependencies, personally I think this bug is very critical because xanmod is the only kernel I have running on Nvidia + Plasma + Wayland, on all other kernels the system just hangs, so I would appreciate it if the bug is fixed quickly, thanks in advance

**Comment by xiota** [comment]
I'm not going to make any changes to the interferes for now.  I've asked the `linux-xanmod` maintainer to add conditional clang depends to `linux-xanmod-headers`.  Nothing stops you from installing `clang` and `lld` even if they're not listed in depends.

@Boria138 Specifically which `xanmod` kernels are you using?

**Comment by Boria138** [comment]
> I'm not going to make any changes to the interferes for now.  I've asked the `linux-xanmod` maintainer to add conditional clang depends to `linux-xanmod-headers`.  Nothing stops you from installing `clang` and `lld` even if they're not listed in depends.
> 
> @Boria138 Specifically which `xanmod` kernels are you using?

The most common linux-xanmod without v3 or v2

**Comment by xiota** [comment]
I'll change `linux-xanmod` to use `gcc`, starting with the next release.

I'll rename the v2/v3 packages to `linux-xanmod-clang-v2/3`.
