### ISSUE TITLE
[Rebuild] Linux-tkg

### ISSUE THREAD

**Issue by rejedai** [chaotic-aur/packages#2993]
### Packages:

chaotic-aur/linux-tkg-pds-generic_v3
chaotic-aur/linux-tkg-pds-generic_v3-headers

### Latest chaotic version

6.5.8-273

### Reason for rebuild

There have been kernel versions 6.6 and 6.7, this kernel has not been updated in a long time

**Comment by Technetium1** [comment]
- [linux-lts-tkg-pds.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-lts-tkg-pds.log)
- [linux-tkg-pds-generic_v3.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-tkg-pds-generic_v3.log)
- [linux-tkg-pds.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-tkg-pds.log)

**Comment by begin-theadventure** [comment]
6.6.13 	2024-01-20

**Comment by Technetium1** [comment]
Now failing for different reasons 🤔

**Comment by Technetium1** [comment]
@xiota any ideas?

**Comment by xiota** [comment]
From current log...

* `chaotic-aur/linux-tkg-pds`: succeeded, 6.7.0-273
* `chaotic-aur/linux-tkg-pds-generic_v3`: failed, out of space, garuda has only 25G available, prob have to switch server
* `chaotic-aur/linux-lts-tkg-pds`: database sync error, have to try again

I haven't figured out how [`routines-tkg.sh`](https://github.com/chaotic-aur/toolbox/blob/main/src/lib/routines-tkg.sh) works.  It may need to be updated against scheduler list in [`linux-tkg-config/prepare`](https://github.com/Frogging-Family/linux-tkg/blob/master/linux-tkg-config/prepare).

I'd also like to switch `linux-lts-tkg-*` to `linux-tkg-lts-*` so all the `linux-tkg` kernels are together in search results.  This is the pattern `linux-vfio` and `linux-xanmod` follow.

**Comment by dr460nf1r3** [comment]
The issue is also that there has been a new kernel config option which stalls the build due to not being included in the .config yet. Instead, one needs to select the option manually. We should ask for the config to be updated with the new values 🤔

**Comment by dr460nf1r3** [comment]
How are things looking these days? I noticed that the routines seem to finish successfully without additional user input. So all things *should* be up-to-date again?
