### ISSUE TITLE
[Request] add aur/cromite-bin

### ISSUE THREAD

**Issue by fahimscirex** [chaotic-aur/packages#2994]
### Package:

https://aur.archlinux.org/packages/cromite-bin

### Purpose:

It's a Chromium from based on Bromite.

### Benefits:

Privacy friendly, hardened chromium browser.

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
I'm not sure that this is a good package for us to add. It's a binary release from GitHub, which we can't really speed up more by providing. It is also at _least_ 200MB, which is rather large.

**Comment by xiota** [comment]
I agree with declining this request.  There are already too many browsers in chaotic-aur that need to be pruned.
