### ISSUE TITLE
[Request] mbpfan-git

### ISSUE THREAD

**Issue by LukeShortCloud** [chaotic-aur/packages#2998]
### Package:

https://aur.archlinux.org/packages/mbpfan-git

### Purpose:

Macs have horrible fan support. Depending on the model, I have seen the default behavior to be one of two extremes: either (1) the fan is running at 100% speed all the time which is loud and annoying or (2) the fan runs at the minimum speed causing the Mac to overheat. 

### Benefits:

Mac users can finally have a balance of fan speed and cooling performance.

### Building:

`makepkg` is all that is needed to build this package.

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

The project provides good default settings at `/etc/mbpfan.conf`. All that is needed is to enable and start the `mbpfan` service.

I noticed there is a similar (but different) project that has an AUR package that is already [provided by Chaotic AUR](https://github.com/chaotic-aur/packages/issues/604): `macfanctld`. Looking at the source code, the last update was from 11 years ago. For comparison, the `mbpfan` project last had an update from 6 months ago.

https://github.com/MikaelStrom/macfanctld
https://github.com/linux-on-mac/mbpfan

**Comment by dr460nf1r3** [comment]
Might consider exchanging packages if they provide the same functionality?

**Comment by LukeShortCloud** [comment]
Sure, that seems reasonable.

**Comment by Technetium1** [comment]
I'm inclined to keep both due to size and being unsure of functionality in regards to very old macs.
