### ISSUE TITLE
add "firefox-kde-opensuse" please

### ISSUE THREAD

**Issue by barfin** [chaotic-aur/packages#3]
https://aur.archlinux.org/packages/firefox-kde-opensuse/

**Comment by PedroHLC** [comment]
Sorry, I hadn't subscribed to this repo watch, didn't seem we had an issue already :sweat: .
I'm adding it right now, please note we already have the -bin variation.
I'll notify you when its ready!

**Comment by PedroHLC** [comment]
The build is currently broken:
https://lonewolf.pedrohlc.com/chaotic-aur/makepkglogs/_lab/firefox-kde-opensuse.log

**Comment by barfin** [comment]
> Sorry, I hadn't subscribed to this repo watch, didn't seem we had an issue already sweat .
> I'm adding it right now, please note we already have the -bin variation.
> I'll notify you when its ready!

thanks
my problem is that the -bin package doesn't update as often as the the main one

**Comment by PedroHLC** [comment]
Seems like we have this one for some time, I probably forgot to close this :sweat_smile:
