### ISSUE TITLE
[Request] tutanota-desktop

### ISSUE THREAD

**Issue by samguysu2020** [chaotic-aur/packages#3002]
### Package:

https://aur.archlinux.org/packages/tutanota-desktop

### Purpose:

Required client for popular Tutanota email

### Benefits:

Speed up installation

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
Unfortunately, this [does not bring any unique integrations](https://tuta.com/blog/desktop-clients-tutanota) as an alternative to running in any regular browser. The potential for things to go wrong when using [Electron](https://github.com/tutao/tutanota/blob/eb3c6412f4cd6fafac43be89c8fd4d502bbe72f1/package.json#L51) to view emails with active content is large, especially if the maintainer has any delay in future updates.
