### ISSUE TITLE
Libvpx bump

### ISSUE THREAD

**Issue by dr460nf1r3** [chaotic-aur/packages#3004]
### Packages:

libvpx got bumped, breaking a lot of applications like browsers or the telegram clients.

### Latest chaotic version

many

### Reason for rebuild

Broken existing applications making use of that shared lib.

**Comment by xiota** [comment]
https://github.com/chaotic-aur/interfere/commit/1c52f0644be67a5490f2850fe29a7d7d0b9a2cd2
