### ISSUE TITLE
[Bug]  soundux can't be installed/updated

### ISSUE THREAD

**Issue by otter501** [chaotic-aur/packages#3006]
### Packages:

https://aur.archlinux.org/packages/soundux

### Latest chaotic version

0.2.7-3.1

### What happens?

The package doesn't install and breaks updating unless you exclude it using yay

### What is expected to happen?

It installs

### Logs

sudo pacman -S soundux
resolving dependencies...
looking for conflicting packages...

Packages (1) soundux-0.2.7-3.1

Total Download Size:   4.09 MiB
Total Installed Size:  8.30 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 soundux-0.2.7-3.1-any.pkg.tar.zst failed to download
error: failed retrieving file 'soundux-0.2.7-3.1-any.pkg.tar.zst' from cdn-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'soundux-0.2.7-3.1-any.pkg.tar.zst' from geo-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'soundux-0.2.7-3.1-any.pkg.tar.zst' from br-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'soundux-0.2.7-3.1-any.pkg.tar.zst' from bg-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'soundux-0.2.7-3.1-any.pkg.tar.zst' from ca-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'soundux-0.2.7-3.1-any.pkg.tar.zst' from cl-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'soundux-0.2.7-3.1-any.pkg.tar.zst' from de-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'soundux-0.2.7-3.1-any.pkg.tar.zst' from de-3-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'soundux-0.2.7-3.1-any.pkg.tar.zst' from de-4-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'soundux-0.2.7-3.1-any.pkg.tar.zst' from gr-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'soundux-0.2.7-3.1-any.pkg.tar.zst' from in-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'soundux-0.2.7-3.1-any.pkg.tar.zst' from in-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'soundux-0.2.7-3.1-any.pkg.tar.zst' from in-3-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'soundux-0.2.7-3.1-any.pkg.tar.zst' from kr-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'soundux-0.2.7-3.1-any.pkg.tar.zst' from es-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'soundux-0.2.7-3.1-any.pkg.tar.zst' from es-2-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'soundux-0.2.7-3.1-any.pkg.tar.zst' from us-mi-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'soundux-0.2.7-3.1-any.pkg.tar.zst' from us-tx-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'soundux-0.2.7-3.1-any.pkg.tar.zst' from us-ut-mirror.chaotic.cx : Maximum file size exceeded
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.

**Comment by xiota** [comment]
Found bad signature and rebuilt.  Is it working now?

**Comment by otter501** [comment]
yes
