### ISSUE TITLE
[Rebuild] linux-cachyos

### ISSUE THREAD

**Issue by zany130** [chaotic-aur/packages#3007]
### Packages:

https://aur.archlinux.org/packages/linux-cachyos

### Latest chaotic version

6.7.0-3

### Reason for rebuild

Out of date

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-cachyos.log

**Comment by SolarAquarion** [comment]
The checksum could be failing or any number of issues

**Comment by xiota** [comment]
@Edu4rdSHL Any objection to moving `linux-cachyos` from CatBuilder to ufscar?

Kernels are failing to build on garuda-cluster because of "No space left on device".  Something similar may be happening on CatBuilder.

**Comment by Edu4rdSHL** [comment]
It's building fine here (I don't build on RAM and the nvmes are 2TB), the last fail was because https://github.com/chaotic-aur/packages/commit/d07b903339a16d5159b21dbe824703a90f7d1723, but feel free to move it if you want.

**Comment by xiota** [comment]
@Edu4rdSHL Thanks.  I'll leave it alone then.
