### ISSUE TITLE
[Rebuild] kodi-git doesn't open -again

### ISSUE THREAD

**Issue by cg00001** [chaotic-aur/packages#3009]
### Packages:

https://aur.archlinux.org/packages/kodi-git

### Latest chaotic version

r65211.9a87e4d657d-1

### Reason for rebuild

Kodi doesn't open:
```
~►kodi
/usr/lib/kodi/kodi.bin: error while loading shared libraries: libspdlog.so.1.12: cannot open shared object file: No such file or directory
```

Another version mismatch:
```
chaotic-aur/kodi-git r65211.9a87e4d657d-1
aur/kodi-git r65168.a4b164c00cb-1
```

**Comment by Technetium1** [comment]
The cache needed to be cleared, it's building fine now. The version will always mismatch when you do a search, as it represents the commit at the time the AUR package was last updated.
```
Finished making: kodi-git r65220.d1ba986523b-1
```
