### ISSUE TITLE
Emacs-native-comp-pgtk needs updates

### ISSUE THREAD

**Issue by yqu212** [chaotic-aur/packages#301]
Many bugs have been fixed since last build. It would be great to see the update of emacs-native-comp-pgtk to the latest version. Thanks.

**Comment by PedroHLC** [comment]
Do you mean `chaotic-aur/emacs-native-comp-git`?

**Comment by yqu212** [comment]
No. emacs-pgtk-native-comp-git-28.0.50.145939-1-x86_64.pkg.tar.zst.tar

**Comment by SolarAquarion** [comment]
it's automatically updated every day as it is a git pkg

**Comment by PedroHLC** [comment]
Yeah, but I just checked now, and this package has been rebuilt every hour, every day. But for some reason, the version comparison was stating that the latest build was older than the one in the repo, and was discarding it. So, we built and discarded this package 6*24... 144 times :sweat_smile: 

I already removed the old one and the newer one is building once again. This time it will stick, let's check in a few days if it keeps updating properly :jack_o_lantern:

**Comment by yqu212** [comment]
Thanks.

**Comment by yqu212** [comment]
Close this issue?

**Comment by PedroHLC** [comment]
Yeah, sure, thanks for the contribution!
