### ISSUE TITLE
[Rebuild] ueberzugpp

### ISSUE THREAD

**Issue by guiltiest-gear** [chaotic-aur/packages#3010]
### Packages:

https://aur.archlinux.org/packages/ueberzugpp

### Latest chaotic version

2.9.2-2

### Reason for rebuild

Package is now broken, opencv 4.9 requires package to be rebuilt against new library version

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/ueberzugpp.log

### More information

Performed a manual AUR build of ueberzugpp, proceeded to work properly, this is most likely just something that could be fixed with a rebuild

**Comment by Technetium1** [comment]
`Finished making: ueberzugpp 2.9.2-2.1 (Thu 01 Feb 2024 10:12:46 PM CET)`
