### ISSUE TITLE
[Rebuild] strawberry-qt5

### ISSUE THREAD

**Issue by dgudim** [chaotic-aur/packages#3014]
### Packages:

https://aur.archlinux.org/packages/strawberry-qt5

### Latest chaotic version

1.0.23-1

### Reason for rebuild

```
/usr/bin/strawberry-tagreader: error while loading shared libraries: libtag.so.1: cannot open shared object file: No such file or directory
```

**Comment by dr460nf1r3** [comment]
Bumped in https://github.com/chaotic-aur/interfere/commit/0d4de6c7f179e73a2f74e2138bc3c7b784109d97

**Comment by Technetium1** [comment]
Confirmed working in `1.0.23-1.2`
