### ISSUE TITLE
[Rebuild] prismlauncher

### ISSUE THREAD

**Issue by Arthurmeade12** [chaotic-aur/packages#3015]
### Packages:

https://aur.archlinux.org/packages/prismlauncher

### Latest chaotic version

8.0-1.1

### Reason for rebuild

The latest build from Chaotic-AUR will not launch due to this error: ```prismlauncher: error while loading shared libraries: libcmark.so.0.30.3: cannot open shared object file: No such file or directory```. Cmark (which Prismlauncher depends on) [has updated](https://archlinux.org/packages/extra/x86_64/cmark/) on the official Arch repos. A rebuild should fix this problem. In the future, could Prismlauncher depend on ```libcmark.so``` instead of a hardcoded version?
[Original Prismlauncher issue](https://github.com/PrismLauncher/PrismLauncher/issues/2087)
Thanks for help.

**Comment by Technetium1** [comment]
Normally the correct thing to do is have the AUR maintainer [increment PKGREL](https://wiki.archlinux.org/title/PKGBUILD#pkgrel) as they should, but they are slow, so we'll do it in the meantime. The only way I see to avoid this in the future is by having cmark [compiled and statically linked on the spot by not providing it](https://github.com/PrismLauncher/PrismLauncher/blob/5d223f6f9359c7b9017583c13c5f538032380b73/CMakeLists.txt#L505-L511), but that sucks as a solution and I don't want us to have the burden of maintaining it.

`Finished making: prismlauncher 8.0-1.2 (Sat 03 Feb 2024 07:36:23 PM CET)` and [flagged package out of date](https://aur.archlinux.org/pkgbase/prismlauncher/flag-comment).
