### ISSUE TITLE
[Request] opera browser

### ISSUE THREAD

**Issue by Dialga** [chaotic-aur/packages#3018]
### Package:

https://aur.archlinux.org/packages/opera

### Purpose:

Opera browser, one of the mainstream browsers.

### Benefits:

An alternative to chrome and firefox.

### Copyright:

custom:Opera

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Recently dropped from the extra repo.

**Comment by Dialga** [comment]
Additionally https://aur.archlinux.org/packages/opera-ffmpeg-codecs.

**Comment by xiota** [comment]
The binary attempts to modify system settings it has no business altering.  When attempting to run in a sandbox, the following errors are produced:
```
Failed to open /dev/null
Failed to open /dev/null
[2:2:0209/023946.469393:FATAL:zygote_host_impl_linux.cc(202)] Check failed: . : No such file or directory (2)
[0209/023946.471552:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/online: No such file or directory (2)
[0209/023946.479961:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2)
[0209/023946.480039:ERROR:file_io_posix.cc(145)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2)
```

**Comment by xiota** [comment]
I'm going ahead and rejecting this.  While the new aur maintainer appears off to a good start, it is still a binary package that is easy for end-users to build themselves.

All packages in chaotic-aur will be rebuilt soon (maybe by end of year).  In preparation, proprietary / binary-only packages will be reviewed and potentially dropped.  Probably only a few binary browser packages will be kept.

**Comment by erikdubois** [comment]
I noticed that the opera package is currently not being built, and I’d like to kindly ask if you would consider adding it to the build queue.

Opera still has a dedicated user base, and having it available through Chaotic-AUR would be a great convenience for those of us who rely on it for daily use.

I completely understand if there are resource or policy constraints, but I thought it was worth reaching out and asking respectfully.

Thank you for all the incredible work you do to support the community.

**Comment by xiota** [comment]
Not possible to provide this and adhere to EULA.  Even if transforming the package from `.deb` to `pkg.tar.zst` is not considered modification, moving or removing files to conform to Arch norms would.

The [EULA](https://www.opera.com/legal/eula-computers) states:

> 2. You are only granted a limited license to use the Software. Subject to the terms and conditions of this EULA, Opera hereby grants you a personal, limited, non-exclusive, non-transferable, non-sublicensable license to:
>
>    1. use the executable code version of the Software solely as installed on your personal computer; and
>    2. reproduce and distribute the Software solely as included in an application repository for a desktop open source operating system distribution PROVIDED THAT in all cases the Software is distributed:
>        1. without modification;
>        2. free of charge to end-users; and
>        3. with a copy of this EULA. Distribution for embedded open source operating systems is not permitted. For the avoidance of doubt, the Software must be distributed without modification (including as to the default search engine(s) in the Software settings), both at the time of distribution as well as after the Software is installed.
>
>        You may only use the Software as expressly authorized in this Section 2.
