### ISSUE TITLE
[Request] virtualbox-kvm

### ISSUE THREAD

**Issue by KidGrimes** [chaotic-aur/packages#3019]
### Package:

https://aur.archlinux.org/packages/virtualbox-kvm

### Purpose:

Useful for virtualization.

### Benefits:

Provides Virtualbox with KVM backend enabled.

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
If this isn't taken into extra in the reasonably near future, we may not provide the debug package going forward, as it's 4x the size.

**Comment by xiota** [comment]
`-debug` packages are being made because of recent changes to defaults in `makepkg.conf`.  I've removed them manually.  Will probably need to update toolbox.
