### ISSUE TITLE
Missing lib32-gst-plugins-bad

### ISSUE THREAD

**Issue by ObserverOfTime** [chaotic-aur/packages#302]
I'm pretty sure I installed `lib32-gst-plugins-bad` from Chaotic-AUR at first but it's not there anymore.
It depends on `lib32-chromaprint` and that depends on `lib32-ffmpeg`, both of which are also missing.
As far as I can tell, all other dependencies are available either in Chaotic-AUR or multilib.

**Comment by PedroHLC** [comment]
Done
