### ISSUE TITLE
[Remove] osu-lazer

### ISSUE THREAD

**Issue by pynappo** [chaotic-aur/packages#3020]
### Packages:

https://aur.archlinux.org/packages/osu-lazer

### Latest chaotic version

`2024.131.0-2`

### What happens?

Basically, osu-lazer got a large update and now builds from source are intentionally forbidden from submitting scores to online play. The lead dev commented on the aforementioned AUR package: 

> [ppy](https://aur.archlinux.org/account/ppy) commented on [2024-01-30 17:26 (UTC)](https://aur.archlinux.org/packages/osu-lazer#comment-954192)
> Yes, sorry but source builds will no longer submit scores. You will need to use our binaries.

### What is expected to happen?

`osu!` players are now supposed to install the AppImage manually, or use `osu-lazer-bin` from the AUR instead which uses said AppImage.

**Comment by Dwyriel** [comment]
Is it not possible to have a chaotic package that just installs the AppImage just like the AUR package?
One of the biggest reasons why I use chaotic is because it's (easily) integrated in pacman itself so whenever I update my system it'd update those AUR packages as well.

**Comment by Technetium1** [comment]
@Dwyriel that would involve the same problem of redistributing. https://github.com/Morganamilo/paru might be worth considering.
