### ISSUE TITLE
[Request] yazi-git

### ISSUE THREAD

**Issue by diniamo** [chaotic-aur/packages#3022]
### Package:

https://aur.archlinux.org/packages/yazi-git

### Purpose:

Modern terminal file manager

### Benefits:

The package in the main repositories is very outdated, but compiling a rust project takes way too long

### Copyright:

MIT

### Expected Interest:

Most

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

### More information:

Unrelated to the package, but I have a question: does the Expected Interest field refer to the group of people that use both the requested package and chaotic-aur, and will switch to the chaotic-aur package after released?

**Comment by Technetium1** [comment]
Yes, it does refer to that group.

**Comment by diniamo** [comment]
Oh right, I forgot some people were having issues with this package. I personally don't.

**Comment by xiota** [comment]
> does the Expected Interest field refer to the group of people that use both the requested package and chaotic-aur, and will switch to the chaotic-aur package after released?

Description in form is kind of vague.  I had in mind that it refers to chaotic-aur users who would be interested in using the package, whether they already build it themselves or not.

I recall seeing comments about a few packages that some chaotic-aur users said they prefer to build themselves.  Don't remember which ones or why.
