### ISSUE TITLE
[Request] mise

### ISSUE THREAD

**Issue by yozachar** [chaotic-aur/packages#3023]
### Package:

https://aur.archlinux.org/packages/mise

### Purpose:

"dev tools, env vars, task runner"

### Benefits:

Much faster alternative to [`asdf`](https://asdf-vm.com/).

### Building:

```console
$ CHROOT=$HOME/chroot
$ mkdir $CHROOT
$ mkarchroot $CHROOT/root base-devel
$ arch-nspawn $CHROOT/root pacman -Syu
```

```console
$ git clone "https://aur.archlinux.org/mise-bin.git"
$ cd mise-bin
$ makechrootpkg -c -r $CHROOT
```

### Copyright:

MIT

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Supersedes: https://github.com/chaotic-aur/packages/issues/2714

**Comment by juxuanu** [comment]
Take a while to build on my laptop. +1

**Comment by xiota** [comment]
Dropped because moved to extra.  Metrics 246.
