### ISSUE TITLE
[Request] AngryOxide

### ISSUE THREAD

**Issue by NormTurtle** [chaotic-aur/packages#3026]
### Package:

https://aur.archlinux.org/packages/angryoxide

```
but it fails to build
```

### Purpose:

A 802.11 Attack tool built in Rust! used for  wifi-pentesting!

### Benefits:

modern rust package with auto audit wifi

### Building:

make && make install

### Copyright:

GPL3

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

the build script of [aur](url)

**Comment by Technetium1** [comment]
Happy to add this when it compiles correctly

**Comment by NormTurtle** [comment]
> Happy to add this when it compiles correctly

buiild fails only for the [AUR](https://github.com/chaotic-aur/packages/issues/url) SCRIPT
but u can use this upstream git repo 
https://github.com/Ragnt/AngryOxide?tab=readme-ov-file#building-from-source

**Comment by Technetium1** [comment]
It's not our responsibility to have parity with upstream, it's the AUR maintainer's. We build only from the AUR in a clean chroot. There's not another option, unless we host our own-and that's too much time and effort. [I left a comment](https://aur.archlinux.org/packages/angryoxide#comment-957580) for the maintainer.

**Comment by NormTurtle** [comment]
build now working fine with .
please continue to add.
