### ISSUE TITLE
[Rebuild] 64gram-desktop

### ISSUE THREAD

**Issue by ahmubashshir** [chaotic-aur/packages#3028]
### Packages:

https://aur.archlinux.org/packages/64gram-desktop

### Latest chaotic version

1:1.1.13-1

### Reason for rebuild

qt6 bump

### Logs

```
Cannot mix incompatible Qt library (6.6.1) with this library (6.6.2)
zsh: IOT instruction (core dumped)  64gram-desktop
```

### Builds?

makepkg 🙃

**Comment by xiota** [comment]
Bumped.  https://github.com/chaotic-aur/interfere/commit/0cb1309fb93776dc72015b656e69b5afca17b192

**Comment by xiota** [comment]
Bumped packages depending on `lz4`: https://github.com/chaotic-aur/interfere/commit/de33a85d0a2376cbe94995a7c00d507d228c3fe1

**Comment by xiota** [comment]
Bumped in https://github.com/chaotic-aur/interfere/commit/118c5a63e875dac05a9a352e043f8ee14056c5fd

In future, please specify the exact error message and when it appears.  This is needed to determine whether a bump would even be helpful and whether other packages may be affected.

**Comment by dr460nf1r3** [comment]
Is running.
