### ISSUE TITLE
[Request] vide-bin

### ISSUE THREAD

**Issue by Glebux** [chaotic-aur/packages#3029]
### Package:

https://aur.archlinux.org/packages/vide-bin

### Purpose:

VIDE - Valve Integrated Development Environment, a toolkit containing useful tools for developing Source Engine mods 

### Copyright:

not specified

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

It has dependencies that are not included in chaotic-aur, the most beefiest one is qt4, it takes very long time to compile

**Comment by dr460nf1r3** [comment]
We dropped qt4 a while ago with all of the packages depending on it, so this is sadly not going to be added.
