### ISSUE TITLE
[request] budgie-extras-git

### ISSUE THREAD

**Issue by emanuelserpa** [chaotic-aur/packages#303]
Many things that are broken in the stable release are ok in git.

It's a pretty light wm and should be pretty fast to compile too. Budgie Desktop is relatively popular.

**Comment by PedroHLC** [comment]
Both did not compile, it seems like some dependencies are missing to build in a clean chroot.
Please submit the issues to the AUR maintainer. Then let me know when it's fixed!
Logs: https://lonewolf.pedrohlc.com/chaotic-aur/makepkglogs/_ghissues/303

**Comment by dr460nf1r3** [comment]
budgie-desktop-git compiled successfully, the other one didnt tho. 
https://bin.garudalinux.org/?c0bf3860561ed730#2DVqb7XbBDbTnZMU2mY4rDournRLrJn1Ba2VGDUapwjB

**Comment by emanuelserpa** [comment]
yeah, looks like the guy in budgie-desktop-git found my comment and fixed it.

**Comment by Bhooty** [comment]
Budgie desktop has problems with swap 
Like if u use ram almost 80% u will budgie crash and have to restart lightdm via tty 
Used to use with solus 
Thought my laptop was the problem 
After searching deep 
It seems to be a problem on their end

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.
