### ISSUE TITLE
[Bug] JamesDSP does not load when installed from the chaotic aur

### ISSUE THREAD

**Issue by zany130** [chaotic-aur/packages#3030]
### Packages:

https://aur.archlinux.org/packages/jamesdsp

### Latest chaotic version

2.7.0-1

### What happens?

program does not run when installed from the chaotic aur
```
jamesdsp
jamesdsp: symbol lookup error: jamesdsp: undefined symbol: _Zls6QDebugRK11QDockWidget, version Qt_6
```

### What is expected to happen?

program runs when installed from the chaotic aur

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/jamesdsp.log

### More information

Runs fine if installed from AUR so something is wrong with the build that's being distributed on the chaotic aur

**Comment by xiota** [comment]
Already bumped (https://github.com/chaotic-aur/interfere/commit/0cb1309fb93776dc72015b656e69b5afca17b192).  Waiting for rebuild.

**Comment by zany130** [comment]
@xiota  still does not run if installed from chaotic aur. with this error `jamesdsp: symbol lookup error: jamesdsp: undefined symbol: _Zls6QDebugRK11QDockWidget, version Qt_6`

 If I install from the aur it works fine
