### ISSUE TITLE
[Request] lemonade-git

### ISSUE THREAD

**Issue by uKaigo** [chaotic-aur/packages#3031]
### Package:

https://aur.archlinux.org/packages/lemonade-git

### Purpose:

Lemonade is a remote utility tool (copy, paste and open browser) over TCP.

### Benefits:

This is important to provide clipboard synchronization over remote sessions. neovim, for example, supports lemonade as a clipboard provider, so you can copy something on the host computer and paste it on the buffer.

You, of course, can use the cli utility without neovim, which would be the same as using other clipboard managers, like wl-clipboard.

### Building:

makepkg

### Copyright:

MIT

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
Switching to `lemonade-git` since a binary is less preferred, and it's not been updated for a while.
