### ISSUE TITLE
[Request] dpscreenocr

### ISSUE THREAD

**Issue by NormTurtle** [chaotic-aur/packages#3033]
### Package:

https://aur.archlinux.org/packages/dpscreenocr

### Purpose:

Program to recognize text on screen

### Benefits:

copy text from desktop apps/images where text is not selectable

### Building:

makepkg

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Aur is not updated and maintained anymore ! 
please update from install script from here

**Comment by Technetium1** [comment]
Please request this again if it's ever updated to Qt6. See #3157
