### ISSUE TITLE
[Rebuild] gittyup

### ISSUE THREAD

**Issue by elman22** [chaotic-aur/packages#3034]
### Packages:

https://aur.archlinux.org/packages/gittyup

### Latest chaotic version

gittyup-1.3.0-1.2

### Reason for rebuild

When starting the app, I get error `gittyup: error while loading shared libraries: libcmark.so.0.30.3: cannot open shared object file: No such file or directory`

**Comment by Technetium1** [comment]
[Bumped](https://github.com/chaotic-aur/interfere/commit/34e0a506d96093add1777f8b67ffa00167045a57#diff-acda3a66e1f15a258e2d7c66274a579f3e77ce846d9358b43f611ab39f0ae9f2R177): `Finished making: gittyup 1.3.0-1.3 (Thu 22 Feb 2024 12:49:33 AM CET)`
