### ISSUE TITLE
[Request] paru-static

### ISSUE THREAD

**Issue by LukeShortCloud** [chaotic-aur/packages#3035]
### Package:

https://aur.archlinux.org/packages/paru-static

### Purpose:

`paru-static` is a drop-in replacement for `paru` for managing AUR packages.

### Benefits:

This is a statically linked binary. Combined with `pacman-static`, these tools can help deal with a half broken upgrade (which is easy to do on Arch Linux).

### Building:

Arch Linux build dependencies = `cargo musl rustup`, AUR build dependency = `paru` (already packaged by Chaotic AUR).

```
sudo pacman -S cargo musl rustup
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -i
cd ..
git clone https://aur.archlinux.org/paru-static.git
cd paru-static
makepkg
```

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

As of today, the Chaotic AUR repository provides related packages for `paru` and `paru-git`.

**Comment by dr460nf1r3** [comment]
How exactly would `paru-static` help in this case? Since you would likely unbreak it `pacman-static` and have regular `paru` work again?

**Comment by LukeShortCloud** [comment]
My personal use-case is for my [winesapOS upgrade script](https://github.com/LukeShortCloud/winesapOS/blob/main/scripts/winesapos-upgrade.sh). It is basically an automated Arch Linux upgrade script - something I am having talks with others in the community about refactoring and making a generic and separate `archupgrade` project. Before performing a full system upgrade with Pacman, we first check for installed packages that will have major upgrade conflicts and deal with them on a one-by-one basis first. Then we perform the full system upgrade.

The vision here is to eventually upgrade the minimal amount of packages (basically `base`, `base-devel`, and all of their children dependencies)., go through fixing individual conflicts (some of them from the AUR), and then do a system upgrade with `pacman -S -u` at the end.

A problem that comes up from time-to-time is that users do not use our included upgrade script and are left with a half broken system when they upgrade since they do not know how to manually deal with these issues. Most recently, a user upgraded via Discover and a few dependencies of Pacman (archive related) were upgraded but nothing else. Those dependencies happened to affect everything else.

Perhaps I am overthinking this or simply being overly cautious.

**Comment by xiota** [comment]
`aur/paru-static` cannot be added because it currently does not build successfully.  `aur/paru` and `aur/paru-git` most likely have the same problem and need to be updated.

I'm not sure the static keyword actually does anything useful.  The package lists depends only on `git` and `pacman`.  Rust packages recompile all rust-based depends from source.

**Comment by xiota** [comment]
Tried building again.  Failed with different error:
```
error: failed to run custom build command for `alpm v2.2.2 (https://github.com/archlinux/alpm.rs?rev=8da396#8da39602)`

Caused by:
  process didn't exit successfully: `/home/main-builder/pkgwork/src/paru-2.0.1/target/release/build/alpm-6f8a529ebab994ca/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/main-builder/.cargo/git/checkouts/alpm.rs-a0070a235cf20bfa/8da3960/alpm/build.rs:25:13:
  this version of alpm.rs does not support libalpm v14.0.0 only v13.x.x is supported
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

I'm rejecting this because packages that cannot be successfully built should not be relied upon for system recovery.
