### ISSUE TITLE
[Request] Thokr

### ISSUE THREAD

**Issue by NormTurtle** [chaotic-aur/packages#3037]
### Package:

https://aur.archlinux.org/packages/thokr-git

### Purpose:

A sleek typing tui written in rust

### Benefits:

Typing test on terminal .

### Building:

makepkg

### Copyright:

GPL3

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
How useful is this program really?  What use case doesn't involve uninstalling after a few minutes of use?  Why not use any of many typing test websites?

PKGBUILD defects.

* Description not clear.  What is a "typing tui"?
* pkgver has `v` prefix that needs to be removed.
* Path variables are not guarded.
* Extraneous semicolons.
* Needs update to latest rust guidelines.

**Comment by NormTurtle** [comment]
i see package is not maintained enough.
