### ISSUE TITLE
[Request] streamlink-git / streamlink-twitch-gui-git

### ISSUE THREAD

**Issue by NegiGreenWhite** [chaotic-aur/packages#304]
streamlink-git:
https://aur.archlinux.org/packages/streamlink-git/
streamlink-twitch-gui-git:
https://aur.archlinux.org/packages/streamlink-twitch-gui-git/

Thanks!

**Comment by PedroHLC** [comment]
* `streamlink-git` compiles and it was added.
* `streamlink-twitch-gui-git`  seems like some dependencies are missing to build in a clean chroot.

Please submit the issues to the AUR maintainer. Then let me know when it's fixed!
Logs: https://lonewolf.pedrohlc.com/chaotic-aur/makepkglogs/_ghissues/304

**Comment by NegiGreenWhite** [comment]
Thanks for `streamlink-git` !

For `streamlink-twitch-gui-git`, I can't understand what is happening at all and what to submit to the AUR maintainer.
It somehow compiles in my non-chroot system, so.... just let it go.

Thanks anyway!

**Comment by PedroHLC** [comment]
The AUR maintainer fixed `streamlink-twitch-gui-git`. It's now in the server!

**Comment by NegiGreenWhite** [comment]
Wow, you are incredible!!
Thanks a lot!
