### ISSUE TITLE
[Request] Oculantej

### ISSUE THREAD

**Issue by NormTurtle** [chaotic-aur/packages#3041]
### Package:

https://aur.archlinux.org/packages/oculante

### Purpose:

A minimalistic crossplatform image viewer written in rust 

### Benefits:

A minimalistic image viewer with analysis and editing tools

### Building:

makepkg

### Copyright:

MIT

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
Package no longer exists on AUR.

**Comment by xiota** [comment]
```
$ pacman -Ss oculante
extra/oculante 0.8.22-1
    A minimalistic image viewer with analysis and editing tools
```

**Comment by NormTurtle** [comment]
@Technetium1 post is updated with new and updated link
https://archlinux.org/packages/extra/x86_64/oculante/

please open the issue

**Comment by xiota** [comment]
@NormTurtle This package is rejected because it is already included in standard Arch repos.  There is no need to provide it through chaotic-aur.
