### ISSUE TITLE
[Request] gimp-devel-noconflict

### ISSUE THREAD

**Issue by guiodic** [chaotic-aur/packages#3044]
### Package:

https://aur.archlinux.org/packages/gimp-devel-noconflict

### Purpose:

The package allows GIMP 3.0 to be installed without conflict with the stable version.

### Copyright:

GLP3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
@guiodic I'm confused, how does it help with version 3 when the current is `2.99.18-3`?

**Comment by guiodic** [comment]
> @guiodic I'm confused, how does it help with version 3 when the current is `2.99.18-3`?

version 2.99.18 is development version of Gimp 3.0.

**Comment by dr460nf1r3** [comment]
Sounds like a good solution. What files are interfering?

**Comment by xiota** [comment]
@dr460nf1r3 Sorry, missed your earlier question.  Conflicting files are... desktop file, icons, appdata.xml, man pages, symlinks/duplicates.

**Comment by dr460nf1r3** [comment]
Oh, that's quite a lot 😬
