### ISSUE TITLE
[Request] bolt-launcher

### ISSUE THREAD

**Issue by coolio321** [chaotic-aur/packages#3045]
### Package

https://aur.archlinux.org/packages/bolt-launcher

Note: gtk2, openssl-1.1 are optdeps for rs3

### Purpose

It is a linux alternative to the Jagex Launcher, allowing Linux users to play Runescape through Jagex accounts.

The alternative is using Wine, which is a far buggier and clunkier process.

### License

AGPL3

**Comment by xiota** [comment]
Dropped because depends on EOL GTK2.  Metrics 247.

**Comment by Roukoswarf** [comment]
could this be re-added? gtk2 is only an optdepend for rs3, which is a minority of users.

**Comment by xiota** [comment]
@Roukoswarf Thanks for the info.  Re-added.

Might be good if someone can test if it works with extra/gtk2-compat and let the AUR maintainer know whether the optdep can be changed.

**Comment by Roukoswarf** [comment]
Gave it a test, and sadly it crashes on `libgdk-x11-2.0.so.0`, which is not covered by gtk2-compat.
The part which seems to use the dep is the closed source rs3 client being loaded, it doesn't use it at compile time.

**Comment by xiota** [comment]
Thanks for trying.  Too bad gtk2-compat doesn't work.
