### ISSUE TITLE
[Request]  wallust-git

### ISSUE THREAD

**Issue by helixoid** [chaotic-aur/packages#3046]
### Package:

https://aur.archlinux.org/packages/wallust-git

### Purpose:

It generates colorscheme from given image just like Material-You in Android.

### Benefits:

It is a pywal replacement written in rust which makes it much faster than pywal (written in python) and has more features than pywal.

### Building:

PKGBUILD

### Copyright:

MIT

### Expected Interest:

Many

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
Codeberg is having an outage, addition is delayed.

**Comment by helixoid** [comment]
It's up
