### ISSUE TITLE
[Request] materialgram

### ISSUE THREAD

**Issue by NormTurtle** [chaotic-aur/packages#3047]
### Package:

https://aur.archlinux.org/packages/materialgram-git

### Purpose:

Unofficial desktop version of Telegram messaging app with Material Design

### Benefits:

Telegram Desktop fork with material icons and some improvements

### Building:

makepkg

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
New maintainer: https://aur.archlinux.org/cgit/aur.git/commit/?h=materialgram-git&id=d65d9a9596399a104f3610621442b701769a934d

**Comment by xiota** [comment]
New packaging looks much better than before.  Maintainer forgot to quote a variable.  Would be nice if it used git submodules, but not essential.  As far as I know, v4 build doesn't cache yet.

**Comment by xiota** [comment]
Rejecting for following reasons:

* Yet another telegram fork.  They're generally a pain to follow to ensure they continue working.
* Maintainer was notified of a defect, but pushed an update without fixing it.
