### ISSUE TITLE
[Rebuild]  Kodi-git

### ISSUE THREAD

**Issue by cg00001** [chaotic-aur/packages#3048]
### Packages:

https://aur.archlinux.org/packages/kodi-git

### Latest chaotic version

r65461.8404b9f510f-1

### Reason for rebuild

New fixes might exist on new version -eg HEVC doesn't work on previous.

**Comment by xiota** [comment]
It's already the latest commit.
```
$ pacman -Si kodi-git | grep 'Build Date'
Build Date      : Sun Mar  3 11:09:27 2024
```

**Comment by cg00001** [comment]
> pacman -Si kodi-git | grep 'Build Date'

Thank you.

**Comment by cg00001** [comment]
Sorry to bother you again, the developer of kodi-git told me what's wrong.
He decided to use gles as default instead of the working gl in his PKGBUILD, and that broke HEVC playback for me.
If you can, please see line 24 in the PKGBUILD wherein you need to define the _renderer variable to a value of either gles or gl.
Select gl instead of gles.
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kodi-git#n24

I'm building it myself, but it will take many hours.

**Comment by cg00001** [comment]
Finished building.
The way mentioned above -Kodi's default-, gl, works fine.

**Comment by xiota** [comment]
I'll add an interfere after aur maintainer responds to my comment.

**Comment by cg00001** [comment]
I noticed HEVC sources again don't work with latest kodi-git -probably something automated used gles instead of gl.
Also saw maintainer hasn't replied so that must be it.
I can live with excluding HEVC until it's fixed.

**Comment by cg00001** [comment]
@xiota today kodi-git was taken over by master -now points to Kodi 22 alpha 1, which is good for experimenting now and in the near future.
The arch maintainer told me he put Kodi 21 in: kodi-stable-git
Could we add that to Chaotic-AUR binaries
(Don't worry about gles, I use other codecs besides HEVC so it's fine.

**Comment by dr460nf1r3** [comment]
> The arch maintainer told me he put Kodi 21 in: kodi-stable-git

What is the package you would be using and why? I'm against adding packages just for the sake of adding them.

**Comment by xiota** [comment]
A problem with kodi is unusual versioning/branching/tagging practices that require manual intervention with every release. omega/21.x is at release candidate stage.  Wait for release, then `extra/kodi` will be updated.

I'm against adding prerelease packages that duplicate functionality of other packages, including those already in the extra repo, except to fix known bugs or provide specific missing features.

**Comment by cg00001** [comment]
> > The arch maintainer told me he put Kodi 21 in: kodi-stable-git
> 
> What is the package you would be using and why? I'm against adding packages just for the sake of adding them.

I usually use the next prerelease -eg 22 alpha 1-, and have a stable of previous -eg now 21 RC 2 in case 22 breaks.
So if there is an issue with multiple binaries, I'd prefer having binaries of 22 alpha 1 and later, and simply manually build 21 versions.

**Comment by cg00001** [comment]
@xiota 
I'm thinking, since Kodi stable is what other users may prefer, to have kodi-stable-git here instead of kodi-git.
People can build the Kodi "P" alpha themselves -it's too early for "P" version anyway.

**Comment by xiota** [comment]
What does `kodi-git` provide users that `extra/kodi-gles` does not?  And how is `kodi-stable-git` different from `extra/kodi-gles`?

**Comment by cg00001** [comment]
> What does `kodi-git` provide users that `extra/kodi-gles` does not? And how is `kodi-stable-git` different from `extra/kodi-gles`?

This is what I know -I'm no dev.
kodi-gles is a binary of Kodi 21 -Omega.
kodi-stable-git is build from Kodi 21 source (different dependencies).
kodi-git points to Kodi 22 -"P" version, early alpha, usually alphas are very similar to last stable with small changes, so they may be unstable.

**Comment by cg00001** [comment]
The "funny" part is, I use Flatpak Kodi 21 to avoid waiting for other versions' glitches to be fixed.

**Comment by xiota** [comment]
I had forgotten interfere is needed to fix the gl/gles issue... will add it shortly.  Will also change version to standard format (`#.r#.g#`).  Besides this, I'd prefer to leave the package alone because it's kind of complicated.

**Comment by xiota** [comment]
Added `kodi-stable-git` with similar interfere (3a992f56a993f1f5979694e4dd86fa357c3b53cb).

**Comment by cg00001** [comment]
I tried the gl version from extra along with 2 basic addons:
`kodi kodi-addon-inputstream-adaptive kodi-addon-inputstream-adaptive`
3rd party Kodi addons don't work -they didn't work either on other Kodis mentioned above, it seems the only Kodi working is from Flatpak:
https://flathub.org/apps/tv.kodi.Kodi

**Comment by xiota** [comment]
Do the git packages in the chaotic-aur repo work?  If not, maybe they should be dropped?

**Comment by cg00001** [comment]
> Do the git packages in the chaotic-aur repo work? If not, maybe they should be dropped?

That's a fair question.
Out of many 3rd party Kodi addons, one seems to work fine, several don't work in all main versions, and binaries.
I don't know if Kodi devs do this deliberately, can only wait for updates to check. That's why at first I suggested kodi-git.
So far the only working Kodi for me in Arch linux is the Flatpak binary.
Other peeps using Kodi needed to triage.

**Comment by lavish440** [comment]
Can we get a rebuild please as it is lagging behind the master ?
I'm trying to reproduce an issue but it takes a lot of time and throws some errors when trying to build on my machine.

**Comment by xiota** [comment]
Fails to build.  Flagging.
```
    pr24972.patch ... FAILED
==> ERROR: One or more files did not pass the validity check!
```

**Comment by lavish440** [comment]
> Fails to build.  Flagging.
> ```
>     pr24972.patch ... FAILED
> ==> ERROR: One or more files did not pass the validity check!
> ```

Edit the patch file and update the checksum for ffmpeg tar gz. Also update the checksum in PKGBUILD for the patch file.

**Comment by lavish440** [comment]
@xiota It looks like the PKGBUILD has been fixed.

**Comment by xiota** [comment]
```
$ pacman -Si kodi-git | grep -E '^(Repository|Name|Version|Build)'
Repository      : chaotic-aur
Name            : kodi-git
Version         : 21.1.r1535.gf9ea21c-1
Build Date      : Thu 07 Nov 2024 03:38:23 AM UTC
```

**Comment by lavish440** [comment]
> ```
> $ pacman -Si kodi-git | grep -E '^(Repository|Name|Version|Build)'
> Repository      : chaotic-aur
> Name            : kodi-git
> Version         : 21.1.r1535.gf9ea21c-1
> Build Date      : Thu 07 Nov 2024 03:38:23 AM UTC
> ```

I want to ask something. 
Is it supposed to be in-line with the git master?

**Comment by xiota** [comment]
>  Is it supposed to be in-line with the git master?

It should be, unless there is a build failure.  Some heavy packages build only once per day.  Kodi is not currently among them.

Latest commit at [github/xbmc](https://github.com/xbmc/xbmc/commits/master/) is f9ea21c, which matches the version string 21.1.r1535.g**f9ea21c**.  The version references 21.1 because 22.0 isn't in any tags yet.  It is possible to rewrite.

**Comment by xiota** [comment]
Adjusted pkgver, so more clear it's the upcoming version.
```
==> Finished making: kodi-git 22.r1477.gf9ea21c-1 (Fri Nov  8 04:29:23 2024)
```

**Comment by lavish440** [comment]
@xiota Getting this with the latest builds:
```
$ kodi
/usr/lib/kodi/kodi.bin: error while loading shared libraries: libspdlog.so.1.14: cannot open shared object file: No such file or directory
```

**Comment by xiota** [comment]
Rebuild of `kodi-git` is queued.  However, `kodi-stable-git` failed rebuild.  Looks like problem with java.

**Comment by lavish440** [comment]
Any updates?

**Comment by xiota** [comment]
Maintainer made soft of fixed one package but not the other.  Solution is unsatisfactory, so will add interfere.

**Comment by lavish440** [comment]
@xiota Seems like it broke again

```
$ pacman -Si kodi-git | grep 'Build Date'
Build Date      : Sat 15 Feb 2025 06:10:04 AM IST
````

**Comment by xiota** [comment]
Builds have been failing for a while.  Problem appears to have already been reported in comments at `aur/kodi-git`.  Someone could flag for maintainer attention.
```
    error: downloading 'https://github.com/xbmc/libdvdcss/libdvdcss-1.4.3-Next-Nexus-Alpha2-2.tar.gz' failed
```
