### ISSUE TITLE
[Request] pamac-all

### ISSUE THREAD

**Issue by pigeonskiller** [chaotic-aur/packages#3049]
### Package:

https://aur.archlinux.org/packages/pamac-all

### Purpose:

A GUI frontend for libalpm (everything in one package - snap, flatpak, appindicator, aur, appstream)

### Benefits:

Actually the most complete package manager for Arch and derivatives

### Copyright:

GPL3

### Expected Interest:

Most

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

For those who are having trouble installing this package, install libpamac-full first, before this package.

**Comment by xiota** [comment]
`pamac-all` and `libpamac-full` have already previously been rejected because they depend on `snapd`.
