### ISSUE TITLE
[Request] suyu

### ISSUE THREAD

**Issue by Ast3risk-ops** [chaotic-aur/packages#3051]
### Package:

https://aur.archlinux.org/packages/suyu-git

Also https://aur.archlinux.org/packages/suyu-dev-git + https://aur.archlinux.org/packages/suyu-dev-qt6-git

### Purpose:

Continuation of the yuzu emulator, which you guys also compiled and hosted here.

### Benefits:

Yuzu is dead, and suyu continues it.

### Building:

Basically everything from https://gitlab.com/suyu-emu/linux-package-sources/suyu-git_PKGBUILD/-/blob/master/PKGBUILD so this can be replaced with cloning that and running `makepkg -si`.

```
sudo pacman -Syu --needed base-devel boost catch2 cmake ffmpeg fmt git glslang graphviz libzip lz4 mbedtls ninja nlohmann-json openssl opus qt6 sdl2 vulkan-headers zlib zstd zip unzip
```
```
git clone https://gitlab.com/suyu-emu/suyu.git && cd suyu && git submodule init && git submodule update
```
```
export CXXFLAGS+=' -Wno-switch'
```
```
cmake -S suyu -B build -G Ninja \
    -DCMAKE_BUILD_TYPE=None \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_REPOSITORY=suyu-emu/suyu \
    -DBUILD_TAG=${_branch}-${pkgver} \
    -DENABLE_COMPATIBILITY_LIST_DOWNLOAD=ON \
    -DENABLE_QT6=OFF \
    -DENABLE_QT_TRANSLATION=ON \
    -DENABLE_SDL2=ON \
    -DENABLE_WEB_SERVICE=ON \
    -DSIRIT_USE_SYSTEM_SPIRV_HEADERS=ON \
    -DTITLE_BAR_FORMAT_IDLE="suyu | ${_branch}-${pkgver} {}" \
    -DTITLE_BAR_FORMAT_RUNNING="suyu | ${_branch}-${pkgver} | {}" \
    -DUSE_DISCORD_PRESENCE=OFF \
    -DYUZU_CHECK_SUBMODULES=OFF \
    -DYUZU_DOWNLOAD_TIME_ZONE_DATA=ON \
    -DYUZU_USE_BUNDLED_FFMPEG=OFF \
    -DYUZU_USE_BUNDLED_QT=OFF \
    -DYUZU_USE_BUNDLED_SDL2=OFF \
    -DYUZU_USE_EXTERNAL_VULKAN_HEADERS=OFF \
    -DYUZU_USE_EXTERNAL_VULKAN_UTILITY_LIBRARIES=OFF \
    -DYUZU_USE_EXTERNAL_SDL2=OFF \
    -DYUZU_USE_FASTER_LD=OFF \
    -DYUZU_USE_PRECOMPILED_HEADERS=OFF \
    -DYUZU_USE_QT_MULTIMEDIA=ON \
    -DYUZU_USE_QT_WEB_ENGINE=ON \
    -DYUZU_TESTS=OFF \
    -Wno-dev
```
```
cmake --build build
```

### Copyright:

https://gitlab.com/suyu-emu/suyu/-/blob/dev/LICENSE.txt

GPLv3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Suyu maintains multiple code mirrors, but their gitlab org is the main one: https://gitlab.com/suyu-emu

**Comment by Technetium1** [comment]
[suyu-git](https://aur.archlinux.org/packages/suyu-git) does not seem useful to add... _yet_

**Comment by xiota** [comment]
Is there any reason to keep the Qt5 version?

**Comment by Technetium1** [comment]
@xiota it will be dropped in the future, but it's still popular for now, and I'm unsure if qt6 version is working in Wayland. [Conflicts are _almost_ there](https://aur.archlinux.org/packages/suyu-dev-qt6-git#comment-962538)

**Comment by dr460nf1r3** [comment]
RIP?

https://overkill.wtf/suyu-emulator-removed-from-gitlab/

**Comment by xiota** [comment]
We shouldn't add anymore forks until some time has passed.  Maybe months to years.

**Comment by dr460nf1r3** [comment]
Yup, I had the same thoughts. Nintendo must be really salty, damn.

**Comment by xiota** [comment]
They made the fork before the funeral even started.  The outcome could have been worse.

**Comment by Technetium1** [comment]
I'm expecting that repo to be back up after a short time, as the rest of their content is still active, and releases are still available.

**Comment by Ast3risk-ops** [comment]
> RIP?
> 
> [overkill.wtf/suyu-emulator-removed-from-gitlab](https://overkill.wtf/suyu-emulator-removed-from-gitlab/)

They have their own ForgeJo instance. Their code remains.

**Comment by kiodo1981** [comment]
New App is Torzu. Please update. 10 aug 2024

**Comment by xiota** [comment]
> New App is Torzu. Please update. 10 aug 2024

Citation needed.

**Comment by kiodo1981** [comment]
https://codeberg.org/litucks/torzu/tags

**Comment by xiota** [comment]
Nothing on that page indicates any relation to suyu.

**Comment by kiodo1981** [comment]
https://codeberg.org/litucks/torzu.git
...This project incorporates several commits from the [Suyu](https://suyu.dev/) and [Sudachi](https://github.com/sudachi-emu/sudachi) forks (but cleaned up due to the typically mediocre code/commit quality from both projects) as well as changes listed in Changes.

**Comment by Ast3risk-ops** [comment]
> [codeberg.org/litucks/torzu.git](https://codeberg.org/litucks/torzu.git) ...This project incorporates several commits from the [Suyu](https://suyu.dev/) and [Sudachi](https://github.com/sudachi-emu/sudachi) forks (but cleaned up due to the typically mediocre code/commit quality from both projects) as well as changes listed in Changes.

https://git.suyu.dev/suyu/suyu has not been archived, indicating suyu is still active. Torzu is a seperate fork. Please make your own request for torzu.

**Comment by dr460nf1r3** [comment]
I'd be in favor of not adding 2 forks and instead using the one with better code quality. Little reason to have both, imo.

**Comment by Ast3risk-ops** [comment]
> I'd be in favor of not adding 2 forks and instead using the one with better code quality. Little reason to have both, imo.

Torzu is limiting public development so I'd go for suyu.


<details>
<summary>Torzu developer's statement</summary>
<blockquote>I feel like working publicly on this has taken away the fun. You may not understand, but it's quite stressful to have the public eye on a project. Keep in mind, this is just a hobby project. I feel like I always have to keep updating so I don't disappoint you. It's just not a good situation for a hobby project to be in. Turns out: running an open source project takes a lot more time than I have. And then stupid and unnecessary issues like Windows Defender flagging the emulator as malware ruin the rest. I am grateful for all your bug reports, help and support, but all that has distracted me from taking the project into the direction I would've liked.
<br><br>
Today I've accidentally locked myself out of the Tor site out of pure stupidity and one of the things I didn't make a backup of for was the key required to get the same Tor site set back up.
<br><br>
For these reasons, I have decided to limit public development. It is not all over though. My plan is to:
<br><br>
    continue the blog<br>
    move the blog into a seperate repository<br>
    keep this repository updated just enough so it stays compilable on Linux and Windows<br>
    keep the externals updated<br>
    push some bigger updates from my private upstream whenever I feel like (no promises)<br>
    NOT publish releases. If someone feels like publishing builds they should feel free to do that<br>
    NOT offer support in any way<br>
        feel free to open issues on the main repository though if you feel like an issue REALLY needs my attention<br>
    accept pull requests as long as they are of reasonable quality<br>

</blockquote>
</details>

**Comment by dr460nf1r3** [comment]
Welp, that was a plot twist I wasn't aware of.

**Comment by xiota** [comment]
Dropping because upstream development appears to be stalled and other forks are available.  Metrics 50.

**Comment by kiodo1981** [comment]
Now I use Citron [https://git.citron-emu.org/Citron/Citron](url)
