### ISSUE TITLE
[Rebuild]  cloudflared

### ISSUE THREAD

**Issue by Tronikelis** [chaotic-aur/packages#3053]
### Packages:

https://aur.archlinux.org/packages/cloudflared-bin

### Latest chaotic version

2024.1.5-1

### Reason for rebuild

Out of date package that has bugs fixed in upstream

**Comment by xiota** [comment]
cloudflared is in extra repo.

**Comment by Tronikelis** [comment]
@xiota oh my god, how did I not see that, thanks

**Comment by xiota** [comment]
It happens.  No problem.
