### ISSUE TITLE
[Request]  blink

### ISSUE THREAD

**Issue by userofryzen** [chaotic-aur/packages#3054]
### Package:

https://aur.archlinux.org/packages/blink

dependencies
icu ([icu-git](https://aur.archlinux.org/packages/icu-git)AUR)
   [ python-application](https://aur.archlinux.org/packages/python-application)AUR
   [ python-eventlib](https://aur.archlinux.org/packages/python-eventlib)AUR
   [ python-pyqt5-webkit](https://aur.archlinux.org/packages/python-pyqt5-webkit)AUR
   [ python-sipsimple](https://aur.archlinux.org/packages/python-sipsimple)AUR
   [ qt5-webkit](https://aur.archlinux.org/packages/qt5-webkit)AUR

### Purpose:

VoIP SIP. It's like linphone( that is not in the repo either) but for me linphone-desktop doesn't  work for my sip server.
The only programs that I found that work for me with my sip server are:
zoiper(closed source and paid), twinkle (a litlle bit old and with echo and bugs) and blinker( that I'm testing since a few days from flathub but i prefer to install with a repo than flatpack)

### Benefits:

almost the difference between works and doesn't work. 

I think people doesn't know this program, and I have found a few days ago after much research.

### Building:

I have not compiled yet from aur because there are a lot of aur package depending that has to be compiled and my computer is not as powerfull as I want...

### Copyright:

GNU General Public License version 3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
This depends on Qt5, and can be considered again for addition after migration to Qt6. See #3157
