### ISSUE TITLE
[Remove] niri-git

### ISSUE THREAD

**Issue by vollowx** [chaotic-aur/packages#3055]
### Package:

https://aur.archlinux.org/packages/niri-git

### Purpose:

Niri is a scrollable-tiling Wayland compositor, which aligns windows in infinity-wide dynamic workspaces.

### Benefits:

Maybe is a replacement of GNOME+PaperWM for someone?

But also is the major desktop for some including me.

### Building:

makepkg

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by vollowx** [comment]
Many thanks!

**Comment by xiota** [comment]
Is this package still needed?  `extra/niri` was created about a month after this was requested.  Metrics 55.

This package outputs errors when processed by `shfmt`.

**Comment by vollowx** [comment]
This issue is now for pre-compiled niri-git package while the niri package is the release version

**Comment by xiota** [comment]
Dropping because incompatible with new build system.  Would require rewriting as custom package.
