### ISSUE TITLE
[Request] hyprcursor-git

### ISSUE THREAD

**Issue by helixoid** [chaotic-aur/packages#3058]
### Package:

https://aur.archlinux.org/packages/hyprcursor-git

### Purpose:

It is new dependency for hyprland-git and might be the issue why hyprland-git is not being build on chaotic-aur for the past 2 days!
It is a new wayland replacement for Xcursor with support for svg cursor themes.

### Building:

makepkg

### Copyright:

BSD-3-Clause license 

### Expected Interest:

Many

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by nisby** [comment]
also hyprlang-git to build hyprcursor-git

**Comment by dr460nf1r3** [comment]
Added it in https://github.com/chaotic-aur/packages/commit/ea2d51b5845c8117af177cc6d3cbaaa2a8e400b5 as `hyprland-git` now requires it, I think adding `-git` versions is reasonable in this case as `hyprland` changes a lot.

**Comment by nisby** [comment]
> Added it in [ea2d51b](https://github.com/chaotic-aur/packages/commit/ea2d51b5845c8117af177cc6d3cbaaa2a8e400b5) as `hyprland-git` now requires it, I think adding `-git` versions is reasonable in this case as `hyprland` changes a lot.

thank you
