### ISSUE TITLE
omnisharp-roslyn

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#306]
omnisharp-roslyn
https://aur.archlinux.org/packages/omnisharp-roslyn/

Thank you for your efforts.

**Comment by PedroHLC** [comment]
Done

**Comment by ALipAkrohk** [comment]
Hello, why is this package no longer in the repository list ?! 😟

**Comment by PedroHLC** [comment]
Because of https://t.me/s/lonewolf_builder/579

**Comment by dr460nf1r3** [comment]
Well, flagged out of date since 2019..
`==> ERROR: One or more files did not pass the validity check!`

**Comment by ALipAkrohk** [comment]
> Well, flagged out of date since 2019.. Modified the PKGBUILD to skip validity so it would build successfully.

Tank
