### ISSUE TITLE
[Request] netbird-ui

### ISSUE THREAD

**Issue by artemklevtsov** [chaotic-aur/packages#3062]
### Package:

https://aur.archlinux.org/packages/netbird
https://aur.archlinux.org/packages/netbird-ui

### Purpose:

WireGuard-based mesh network.

### Benefits:

Tailscale alternative.

### Building:

makepkg. Need Go to build.

### Copyright:

BSD

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
`netbird-ui` is now a subpackage of `aur/netbird`.

Metrics:

* netbird # 432
* netbird-management # 102
* netbird-relay # 91
* netbird-signal # 96
* netbird-ui # 242
