### ISSUE TITLE
[Request] mov-cli

### ISSUE THREAD

**Issue by NormTurtle** [chaotic-aur/packages#3065]
### Package:

https://aur.archlinux.org/packages/mov-cli-git

### Purpose:

A cli tool to browse and watch movies/shows.

### Benefits:

just simple open terminal and hope on binge

### Building:

makepkg

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Inclined to reject for following reasons:

* References non-existent packages, at least one of which cannot possibly work on Arch Linux
* Content issues that have been described / discussed elsewhere

**Comment by dr460nf1r3** [comment]
Sounds reasonable to me.

**Comment by Technetium1** [comment]
First, I [flagged this dep which is outdated](https://aur.archlinux.org/packages/python-krfzf) and maintained by the old `mov-cli` maintainer. Second, there is **_not_** currently a maintainer. Unless we're adopting this, and I **really** don't think we should, then it's pending adoption. Finally, the nonexistent opt-deps are a nonissue, as they won't affect the build, but I don't appreciate that anything nonexistent is referenced, and would probably remove them via interfere if the next maintainer doesn't.

**Comment by xiota** [comment]
Was it orphaned recently?  I don't want to make interferes later when it can be avoided.  If this is worth accepting, someone related to chaotic aur should adopt it.  Can be a willing user @NormTurtle.  Otherwise, it should be cleanly rejected.

**Comment by Technetium1** [comment]
@xiota the last time the previous maintainer updated one of their remaining packages was `2023-10-23`, so I think it's been orphaned for a while.

**Comment by xiota** [comment]
The previous maintainer has a comment on the package, and I don't remember seeing it orphaned when I looked at it before.

@NormTurtle Have you built and tried using the package?  From looking at the github project, it may not be usable without extra setup.

**Comment by NormTurtle** [comment]
> Have you built and tried using the package?

i did try. its having Dependencies issue. looking for package which is not present in aur.
So im closing issue now. 
thanks for everyone looking on this issue...

____
if anyone want to use this package good workaround is just .
```python
pipx install mov-cli
```

**Comment by xiota** [comment]
Package was deleted from AUR for following reason:

> This package doesn't work because of nonexistent depends that would be complicated to add to AUR. Users are better off installing with pip to a venv.
