### ISSUE TITLE
[Request] flutter-engine

### ISSUE THREAD

**Issue by roythearsonist** [chaotic-aur/packages#3066]
### Package:

https://aur.archlinux.org/packages/flutter-engine

### Purpose:

Engine for flutter applications.

### Benefits:

This package acts as a make dependency for [another issue](https://github.com/chaotic-aur/packages/issues/2907) 

### Building:

pkgctl build

### Copyright:

BSD

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by dr460nf1r3** [comment]
In how far is this different from packages produced by this pkgbase: https://aur.archlinux.org/packages/flutter-engine-linux-google-bin ?

**Comment by xiota** [comment]
Haven't looked in detail, but there is a pinned comment saying it "... cached in the user cache directory (~/.cache/flutter-engine)..."  So unless this package is required for something, would prefer not to add it.

**Comment by roythearsonist** [comment]
> In how far is this different from packages produced by this pkgbase: https://aur.archlinux.org/pkgbase/flutter-artifacts-google-bin ?

I have no clue tbh, I just wanted to have localsend be in the chaotic aur

**Comment by xiota** [comment]
Rejecting this because packages should not be messing with user directories.

@roythearsonist In future, please comment at relevant issue so packages can be reviewed again.  #2907

**Comment by xiota** [comment]
@roythearsonist Added `localsend-bin` to chaotic aur.

**Comment by roythearsonist** [comment]
Thanks
