### ISSUE TITLE
[Rebuild] octopi, alpm_octopi_utils

### ISSUE THREAD

**Issue by EmptyVisual** [chaotic-aur/packages#3067]
### Packages:

https://aur.archlinux.org/packages/octopi
https://aur.archlinux.org/packages/alpm_octopi_utils

### Latest chaotic version

0.15.0-1

### Reason for rebuild

Pacman v6.1.0 provides libalpm.so.14, conflicting with current octopi packages requirement of libalpm.so.13 - Needs rebuild

**Comment by xiota** [comment]
AUR maintainer already bumped pkgrel.
