### ISSUE TITLE
[Request] qt5ct-kde / qt6ct-kde

### ISSUE THREAD

**Issue by kress-x** [chaotic-aur/packages#3068]
### Package:

https://aur.archlinux.org/packages/qt5ct-kde
https://aur.archlinux.org/packages/qt6ct-kde

### Purpose:

Just [qt5ct](https://archlinux.org/packages/extra/x86_64/qt5ct/) and [qt6ct](https://archlinux.org/packages/extra/x86_64/qt6ct/) with patches to support KDE color schemes.

### Benefits:

Easier time using breeze theme outside KDE.

### Building:

makepkg

### Copyright:

BSD

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Dropping qt5ct-kde because fails to build and depends on Qt5.

Metrics:

* qt5ct-kde # 23
* qt6ct-kde # 168
