### ISSUE TITLE
[Rebuild] hyprland-git

### ISSUE THREAD

**Issue by SteavenGamerYT** [chaotic-aur/packages#3069]
### Packages:

https://aur.archlinux.org/packages/hyprland-git

### Latest chaotic version

0.36.0.r83.fa886d8b-1

### Reason for rebuild

Outdated

**Comment by Ast3risk-ops** [comment]
Source AUR package is also out of date, so a rebuild won't solve anything.

**Comment by SteavenGamerYT** [comment]
> Source AUR package is also out of date, so a rebuild won't solve anything.

truns out its not its just name that is outdated

**Comment by dr460nf1r3** [comment]
It missed `hyprcursor`, which requires `hyprlang`.
