### ISSUE TITLE
[Bug] hypridle-git

### ISSUE THREAD

**Issue by SteavenGamerYT** [chaotic-aur/packages#3072]
### Packages:

https://aur.archlinux.org/packages/hypridle-git

### Latest chaotic version

0.1.1.r3.g4395339a-1

### What happens?

hypridle
hypridle: error while loading shared libraries: libhyprlang.so.1: cannot open shared object file: No such file or directory

### What is expected to happen?

work?, like just work?

### Logs

hypridle
hypridle: error while loading shared libraries: libhyprlang.so.1: cannot open shared object file: No such file or directory

**Comment by xiota** [comment]
These are the potentially affected packages.  I'll review them later.
```
hyprcursor-git
hypridle-git
hyprland-git
hyprlock-git
hyprpaper-git
xdg-desktop-portal-hyprland-git
```
