### ISSUE TITLE
[Request] ttf-readex-pro

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#3079]
### Package:

https://aur.archlinux.org/packages/ttf-readex-pro

~~lexend-fonts-git~~
~~https://aur.archlinux.org/packages/lexend-fonts-git~~

### Purpose:

Variable typeface designed to improve reading fluency

### Copyright:

OFL-1.1

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Was hard ro find specimen sheet... When finally did, looks like any other generic sans serif font.

Package doesn't follow several packaging guidelines...  including package name.

**Comment by D3vil0p3r** [comment]
We can leave a comment under AUR package page

**Comment by xiota** [comment]
No point.  Wrong name means new package is needed.  I'll take a more careful look later.  If it's worth adding, I'll make a new package or add it via interfere.

**Comment by xiota** [comment]
I'm going to create `ttf-readexpro`, which is the successor project of lexend.

**Comment by D3vil0p3r** [comment]
Thanks @xiota
