### ISSUE TITLE
[Request] advcpmv

### ISSUE THREAD

**Issue by 0xhtml** [chaotic-aur/packages#3083]
### Package:

https://aur.archlinux.org/packages/advcpmv

### Purpose:

provides cp/mv with additional features like a progress bar. Optional dependency of nnn, nnn-icons, etc.

### Benefits:

alternative jaapi-advcpmv has some minor build errors.

### Building:

Build nicely with `pkgctl build -c`

### Copyright:

unkown. PKGBUILD says GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

advcpmv has 53 votes on aur. GH https://github.com/jarun/advcpmv

**Comment by xiota** [comment]
Dropping because failing to rebuild and not worth fixing with interfere.  Metrics 31.

Note: "not worth fixing" = too difficult to fix
