### ISSUE TITLE
[Request] zed-editor-preview

### ISSUE THREAD

**Issue by PolpOnline** [chaotic-aur/packages#3086]
### Package:

https://aur.archlinux.org/packages/zed-editor-preview

### Purpose:

It's the preview version of `zed-editor`

### Benefits:

I'd like to have it in the repos to have a more updated version of what's coming. Since the "stable" one isn't even that stable

### Copyright:

AGPL, APACHE, and GPL-3.0

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
I don't see the point.  Standard releases occur every few days.

**Comment by Technetium1** [comment]
This could be worth adding **_after_** infra change.

**Comment by xiota** [comment]
Closing this to remove from active list.  If this is worth reconsidering after infra change (prob months from now), someone can leave a comment with a detailed description of why both packages are needed and how stable, prerelease, git and other packages/branches differ.
