### ISSUE TITLE
[Request] webkit2gtk-imgpaste

### ISSUE THREAD

**Issue by Rattlyy** [chaotic-aur/packages#3087]
### Package:

https://aur.archlinux.org/packages/whatsapp-for-linux

https://aur.archlinux.org/packages/webkit2gtk-imgpaste

### Purpose:

webkit2gtk-imgpaste: patch needed for raw image data pasting to work.

### Copyright:

?

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
What programs or packages use the added features?

**Comment by Rattlyy** [comment]
AUR whatsapp-on-linux

Il giorno gio 28 mar 2024 alle 20:34 xiota ***@***.***> ha
scritto:

**Comment by xiota** [comment]
@Rattlyy Do you also want `whatsapp-for-linux`, or only the alternate webkit2gtk?

**Comment by Rattlyy** [comment]
if you want you can add both ;)

Il giorno dom 31 mar 2024 alle 10:00 xiota ***@***.***> ha
scritto:

**Comment by Technetium1** [comment]
`webkit2gtk-imgpaste` is an absolute _monster_ to build.
```
real    38m34.030s
user    291m14.145s
sys     23m29.700s
```
#1386 already provided `whatsapp-for-linux`

**Comment by Rattlyy** [comment]
thank you! :)

**Comment by xiota** [comment]
I missed `whatsapp-for-linux` in my initial search...  Probably typo.

**Comment by xiota** [comment]
Considering to drop.  Fails to build, and no response from maintainer for a month. Metrics 11.

**Comment by Technetium1** [comment]
@xiota may result in cascading failures/removals as it's required by 557 packages 😬

**Comment by dr460nf1r3** [comment]
Wait, what. The paste package is required by that much packages?

**Comment by Technetium1** [comment]
`webkit2gtk-imgpaste` is required by 36 packages we provide:
```
64gram-desktop
badwolf
bookworm-git
bottles
chatgpt-desktop-bin
cinny-desktop
codelite
eclipse-java-bin
exaile
flightcore
fontfinder
forkgram
freerdp-git
gamehub
gedit-plugin-markdown_preview
gimp-git
icaclient
java-openjfx
java-openjfx-bin
komorebi
kotatogram-desktop
kotatogram-desktop-git
meteo
modrinth-app
modrinth-app-git
nasc
onedriver
pix
quickdocs
riftshare
rum
surf
surf-git
tracktion-waveform
ulauncher
whatsapp-for-linux
```

**Comment by xiota** [comment]
Use `extra/webkit2gtk`

**Comment by Technetium1** [comment]
@xiota as long as it works. The bug is still unresolved upstream, so this has reason to exist once it's updated https://bugs.webkit.org/show_bug.cgi?id=218519

**Comment by xiota** [comment]
`extra/webkit2gtk` updated to 2.44.2 in three months ago.  So the maintainer isn't keeping up (2.44.1).  While missing a minor version bump is understandable, ignoring a flag for a package that has become unbuildable with a straightforward fix is not.  I'm not interested in shadow maintaining via interfere.

**Comment by Technetium1** [comment]
@xiota to be clear, "as long as it works" is in reference to removing `webkit2gtk-imgpaste` in favor of `webkit2gtk`. I think it's reasonable to drop this until it's fixed. I also do not want to shadow maintain it.

**Comment by xiota** [comment]
Package has been updated and now builds successfully.  For record, took about 6-7 weeks since flagged.  When packages are dropped for poor maintenance, I would prefer not to add them back until there is a new maintainer or comaintainer.

**Comment by xiota** [comment]
Fails to build, again.

**Comment by xiota** [comment]
Dropping because no longer applicable to any packages.  Metrics 36.

This package patches the deprecated `webkit2gtk`.  If the `webkit2gtk-4.1` version is wanted, please open a new request.
