### ISSUE TITLE
[Request] crudini

### ISSUE THREAD

**Issue by LukeShortCloud** [chaotic-aur/packages#3089]
### Package:

https://aur.archlinux.org/packages/crudini

Depends:
https://aur.archlinux.org/packages/python-iniparse-git

### Purpose:

`crudini` is useful for administrators and automation tools for interacting with INI files such as `/etc/pacman.conf`, `/etc/default/grub`, `~/.config/legendary.ini`, etc. As the name implies, it can create, read, update, and delete (CRUD) entries in INI files.

Example usage:

```
$ sudo crudini --ini-options=nospace --set /etc/default/grub "" GRUB_TIMEOUT 10
$ crudini --get /etc/default/grub "" GRUB_TIMEOUT
10
```

### Benefits:

There are two packages on the AUR that provide this: [crudini](https://aur.archlinux.org/packages/crudini) and [python-crudini](https://aur.archlinux.org/packages/python-crudini).

The original is crudini. python-crudini was temporarily created because crudini did not update when a new release came out. It was understandable because crudini did not get a new tagged release for 2-3 years despite active development. Now that the crudini project is freqeuntly getting tagged releases again, the crudini AUR package has been staying up-to-date and the python-crudini package has seemingly been abandoned.

### Building:

`makepkg -s -i python-iniparse` is required first before building `crudini`.

### Copyright:

GPL2

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Fedora ships this package in their main repository.

**Comment by xiota** [comment]
`python-iniparse` has check failures.  Appears to be upstream issue.

**Comment by xiota** [comment]
@LukeShortCloud FYI because you are AUR maintainer.

Attempt to rebuild for Python 3.14 failed during check.
```
==> Starting check()...
Test 1 FAIL (line 36)
==> ERROR: A failure occurred in check().
```

**Comment by LukeShortCloud** [comment]
Thanks, I'll have a look.

**Comment by xiota** [comment]
Sorry, I guess false alarm?  It rebuilt successfully a moment ago.  But would still be prudent to look at the script to see what might have gone wrong.
```
==> Finished making: crudini 0.9.6-2.1 (Mon Jan 12 00:20:22 2026)
```
