### ISSUE TITLE
[request] lib32-wxgtks

### ISSUE THREAD

**Issue by Pakrohk** [chaotic-aur/packages#309]
~~lib32-wxgtk3~~
~~lib32-wxbase-light~~
~~lib32-wxcommon-light~~
~~lib32-wxgtk2-light~~
~~lib32-wxgtk3-light~~

**Comment by PedroHLC** [comment]
It'll take some time as I'm currently migrating the building cluster. But I'm sure gonna do it!

**Comment by ALipAkrohk** [comment]
> It'll take some time as I'm currently migrating the building cluster. But I'm sure gonna do it!

tanks, no problme :heart:

**Comment by PedroHLC** [comment]
So, I was looking this before adding, and `lib32-wx{base,common,gtlk2}-light` are not used by any other AUR package. `lib32-wxgtk3-light` can be used as an alternative to `lib32-wxgtk3` without `gstreamer`, and this one is used for those with pcsx2-git. But, GStreamer is pretty much in every Arch that has some Firefox installed.

So I'll just add  `lib32-wxgtk3` and ignore `lib32-*-light`.

If someone finds some other good usage for  `lib32-wxgtk{2,3}-light` feel free to reopen this issue.

**Comment by PedroHLC** [comment]
(And I forgot to say)
Thanks for the contribution, sorry for the delay, and happy 2021!

**Comment by ALipAkrohk** [comment]
> (And I forgot to say)
> Thanks for the contribution, sorry for the delay, and happy 2021!

Thank you for your attention, Happy January.

**Comment by xiota** [comment]
According to AUR page, nothing depends on `lib32-wxgtk3`.  Planning to remove it unless someone describes why it's still needed.
