### ISSUE TITLE
[Request] ripdrag, blobdrop-git

### ISSUE THREAD

**Issue by NormTurtle** [chaotic-aur/packages#3090]
### Package:

https://aur.archlinux.org/packages/ripdrag-git
https://aur.archlinux.org/packages/blobdrop-git

### Purpose:

Drag and Drop utilities

ripdrag: written in Rust and GTK4

blobdrop: Qt6

### Benefits:

replacement for [dragon](https://github.com/mwh/dragon)

### Building:

makepkg

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Goosegit11** [comment]
blobdrop is good too

**Comment by NormTurtle** [comment]
adding https://aur.archlinux.org/packages/blobdrop-git
would also be good :)

**Comment by Goosegit11** [comment]
I didn't know you could do it like that, lol
I thought it's one package per issue

**Comment by xiota** [comment]
> I didn't know you could do it like that

Normally, don't do it this way.

>  I thought it's one package per issue

Normally, it is, except for depends and stable/git packages.
