### ISSUE TITLE
[Request] livecaptions

### ISSUE THREAD

**Issue by Revival8697** [chaotic-aur/packages#3091]
### Package:

https://aur.archlinux.org/packages/livecaptions

### Purpose:

Live Captions is an application that provides live captioning.
It can be used to provide subtitles for a (English) video without one, offline.

### Benefits:

I don't think there is any other package that provide the same function.
There is no use case other than live captioning.

### Building:

makepkg

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

This is officially distributed as a [Flatpak](https://flathub.org/apps/net.sapples.LiveCaptions).

**Comment by Technetium1** [comment]
Due to the large size, existing Flatpak, and lack of popularity, it doesn't currently make sense for us to add this package.

**Comment by xiota** [comment]
Large portion of the package is the model (322M vs 0.5K).  Potentially, if package is reorganized, resource usage could be brought to acceptable levels?

However, package currently fails to build because of missing depends.  I will comment on aurweb to let maintainer know.
