### ISSUE TITLE
[Request] python-accelerate

### ISSUE THREAD

**Issue by MurasakinoNll** [chaotic-aur/packages#3092]
### Package:

https://aur.archlinux.org/packages/python-accelerate

### Purpose:

python accelerate has always been a bit funky on arch and having to build it all the time becomes a hastle

### Benefits:

useful for building llm's

### Building:

available through yay, requires alot of prereq libraries

### Copyright:

Apache

### Expected Interest:

Only me

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
This is a dep for another package that has already been requested.  #2966
