### ISSUE TITLE
[Bug] `anki` missing new dependencies from the AUR

### ISSUE THREAD

**Issue by jthvai** [chaotic-aur/packages#3096]
### Packages:

https://aur.archlinux.org/packages/anki

### Latest chaotic version

`24.04-2`

### What happens?

A new dependency on [`python-pip-system-certs`](https://aur.archlinux.org/packages/python-pip-system-certs)[^1] from the AUR was added for `anki 24.04-1` (and maintained for `-2`) that did not seem to be included in chaotic's distributed package. 

Without this dependency, `anki 24.04-2` fails to launch with the following output:

```
Traceback (most recent call last):
  File "/usr/bin/anki", line 5, in <module>
    from aqt import run
  File "/usr/lib/python3.11/site-packages/aqt/__init__.py", line 9, in <module>
    import pip_system_certs.wrapt_requests
ModuleNotFoundError: No module named 'pip_system_certs'
```

[^1]: Itself depending on [`python-git-versioner`](https://aur.archlinux.org/packages/python-git-versioner) from the AUR

### What is expected to happen?

Anki launches without error.

**Comment by xiota** [comment]
Should work now, without the extra python depends.
