### ISSUE TITLE
[Request] linux-fsync-nobara-bin

### ISSUE THREAD

**Issue by LukeShortCloud** [chaotic-aur/packages#3097]
### Package:

https://aur.archlinux.org/packages/linux-fsync-nobara-bin

### Purpose:

kernel-fsync is used by Bazzite, Nobara, and other operating systems. This kernel is geared towards gamers. Despite the somewhat misleading names, fsync is only one of many features it provides. Most notably it adds:

- Better handheld device support (ASUS ROG Ally and Lenovo Legion Go controllers have better support compared to the upstream Linux kernel)
- Steam Deck OLED support (audio, Wi-Fi, and various quirks fixed)
- ntsync for an accurate and fast implementation to replace fsync for Wine gaming
    - fsync is also provided
- AMD P-state driver for better power management
- AMD HDR support
- Support for Intel T2 Macs from >= 2016

### Benefits:

There are no other builds available on the AUR for this Linux kernel.

### Building:

`makepkg`

### Copyright:

GPL2

### Expected Interest:

Half

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Because this a binary package (a rebuild from a RPM) it makes it fast to build compared to compiling the Linux kernel from scratch.

**Comment by LukeShortCloud** [comment]
Some more information about this kernel can be found here: https://copr.fedorainfracloud.org/coprs/sentry/kernel-fsync/

**Comment by Technetium1** [comment]
After discussing this request with other staff, we've decided it's not a good match for Chaotic. There are not any features here which are not already available cachyos/tkg kernels. It's also a binary, and we prefer kernels are not. Further, our target is Arch and Arch-based distros, so it doesn't particularly fit our ethos. Thanks for requesting with appropriate information.

**Comment by LukeShortCloud** [comment]
Thanks for the transparency, I appreciate it!
