### ISSUE TITLE
[request] orchis-kde-theme-git

### ISSUE THREAD

**Issue by h0cheung** [chaotic-aur/packages#310]
A new kde plasma theme with material design.
Its matching themes are all already in chaotic-aur.
The PKGBUILD of this package is in [AUR](https://aur.archlinux.org/packages/orchis-kde-theme-git/), maintained  by me.

**Comment by PedroHLC** [comment]
It'll take some time as I'm currently migrating the building cluster. But I'm sure gonna do it!

**Comment by PedroHLC** [comment]
It seems Garuda already inserted those in the repo, feel free to reopen this issue if you want other variations. I like themes, and I'm sure to adopt those.

A suggestion is to add non -git, those are easier for chaotic and AUR helpers to find new versions/updates. Even if it's for bumping pkgver incrementally as you wish. :smile: 

Thanks for the contribution, sorry for the delay, and happy 2021!
