### ISSUE TITLE
[Request] python-yapsy

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#3102]
### Package:

https://aur.archlinux.org/packages/python-yapsy

### Purpose:

It offers a way to easily design a plugin system in Python, and motivated by the fact that many other Python plugin system are either too complicated for a basic use or depend on a lot of libraries. Yapsy only depends on Python’s standard library.

### Copyright:

BSD-2

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
What other program uses this?

**Comment by D3vil0p3r** [comment]
> What other program uses this?

It is a dependency of gradience-git , that is in Chaotic but this dependency no. Usually it is used in window managers like Hyprland.

**Comment by Technetium1** [comment]
https://github.com/chaotic-aur/packages/issues/1941 & https://github.com/chaotic-aur/packages/issues/1942 are both related, as this is a newer dependency we've missed adding!

**Comment by xiota** [comment]
For deps related to other packages, please comment on the parent package.

**Comment by xiota** [comment]
This package needs `python-zombie-imp` to function after Python 3.12 update.  Flagged aur package to notify maintainer.  However, `gradience` and `gradience-git` (#1941, #1942) still give me errors.

**Comment by xiota** [comment]
Dropping because maintainer disowned and upstream hasn't had a release since 2019.
