### ISSUE TITLE
watchman[Request] 

### ISSUE THREAD

**Issue by zany130** [chaotic-aur/packages#3104]
### Package:

https://aur.archlinux.org/packages/watchman

Depends:

https://aur.archlinux.org/packages/folly
https://aur.archlinux.org/packages/edencommon
. . . https://aur.archlinux.org/packages/fb303
. . . https://aur.archlinux.org/packages/mvfst
. . . https://aur.archlinux.org/packages/fbthrift
. . . . . . https://aur.archlinux.org/packages/fizz
. . . . . . https://aur.archlinux.org/packages/wangle

### Purpose:

watch files for modifications and perform actions when they are

### Benefits:

https://www.chezmoi.io/user-guide/advanced/use-chezmoi-with-watchman/ is one useful use case

### Copyright:

MIT

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Has a lot of dependencies.  What's the benefit over inotify?

**Comment by zany130** [comment]
Hmm, looking at Inotify, it should be possible to do something, I think? I have no idea why the Chezmoi documentation says to use Watchman....
