### ISSUE TITLE
[Request] AMDGPU PRO Vulkan/AMF

### ISSUE THREAD

**Issue by dankcuddlybear** [chaotic-aur/packages#3105]
### Package:

https://aur.archlinux.org/packages/vulkan-amdgpu-pro
https://aur.archlinux.org/packages/lib32-vulkan-amdgpu-pro
https://aur.archlinux.org/packages/amf-amdgpu-pro
https://aur.archlinux.org/packages/obs-studio-amf

### Purpose:

vulkan-amdgpu-pro, lib32-vulkan-amdgpu-pro: Proprietary Vulkan for AMD GPUs.
amf-amdgpu-pro: Hardware video encoding/decoding for AMD GPUs
amd-vulkan-prefixes: Provides vk_radv, vk_amdvlk, and vk_pro. Lets you choose between AMD Vulkan drivers.
obs-studio-amf: OBS Studio screen recording software patched for AMF support

### Benefits:

vulkan-amdgpu-pro: Offers 10-20% better performance than vulkan-radeon
amf-amdgpu-pro: Allows you to use hardware acceleration instead of CPU for video encoding/decoding. This reduces stutter when gaming and recording at the same time, and allows for much better video quality.

### Building:

makepkg -cirs

### Copyright:

custom: AMDGPU-PRO EULA
GPL2
GPL

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
`obs-studio-amf` – I'd prefer not to add another obs-studio package.

As for the `amdgpu-pro` drivers, [AMDGPUPROEULA.gz](https://github.com/chaotic-aur/packages/files/14898287/AMDGPUPROEULA.gz):

> 3. RESTRICTIONS ... You may not:
>     b. distribute ... or otherwise transfer the Software or Documentation;

**Comment by dr460nf1r3** [comment]
Yup, this pretty much makes it non-viable since we can't add it's deps.. :/

**Comment by xiota** [comment]
It's already implicit.  Can make explicit if you think it may be frequently requested in the future.

**Comment by Technetium1** [comment]
AMDGPU Pro should probably explicitly be in the list.
