### ISSUE TITLE
[Request] phonon-qt6-mpv

### ISSUE THREAD

**Issue by remonke** [chaotic-aur/packages#3106]
### Package:

https://aur.archlinux.org/packages/phonon-qt6-mpv

### Purpose:

Allows for replacing VLC with mpv for qt6-backend

### Copyright:

LGPL-2.1

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Edited to the stable version.  They're both currently at the same commit.

**Comment by xiota** [comment]
Dropped because moved to extra.  Metrics 350.
