### ISSUE TITLE
[Request] tautulli

### ISSUE THREAD

**Issue by btsands** [chaotic-aur/packages#3107]
### Package:

https://aur.archlinux.org/packages/tautulli

### Purpose:

A python based web application for monitoring, analytics and notifications for Plex Media Server

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Only available as a snap, but source code available via Github

**Comment by Technetium1** [comment]
Pending dep updates, surprised we don't already provide this!
