### ISSUE TITLE
[Request] libvirt-v2v

### ISSUE THREAD

**Issue by whoisroot** [chaotic-aur/packages#3108]
### Package:

https://aur.archlinux.org/packages/virt-v2v

### Purpose:

Convert multiple Virtual Machine guest formats to work with KVM.

### Copyright:

GPL2

### Expected Interest:

Some

### Already available?

No

### Unique request?

No

### Banned package?

No

### More information:

May have some problems with Ocaml libs at the moment, but not sure because my Arch install is super dirty and broken :stuck_out_tongue_closed_eyes:. I'm relying in Chaotic's clean build environment to solve it.

**Comment by Technetium1** [comment]
We cannot provide this due to [`nbdkit`](https://aur.archlinux.org/packages/nbdkit) not being adapted to testing (in our environment), and the fact that skipping tests would be unsafe.
