### ISSUE TITLE
[Remove] wine-stable

### ISSUE THREAD

**Issue by ghost** [chaotic-aur/packages#311]
### Package

https://aur.archlinux.org/pkgbase/wine-stable

### Purpose

Wine versions `n.m` are stable when m = 0, development when m > 0.

### License

LGPL-2.1-or-later

**Comment by PedroHLC** [comment]
Hi @barfin, it's been a long time.

I'm adding packages once again. Before adding this one, what is the difference from it and arch's community's wine?

**Comment by barfin** [comment]
> 
> 
> Hi @barfin, it's been a long time.
> 
> I'm adding packages once again. Before adding this one, what is the difference from it and arch's community's wine?

they don't have stable branch
they have only staging and development branch

**Comment by xiota** [comment]
Switching to `extra/wine` + interfere to keep package updated with current packaging standards.

**Comment by xiota** [comment]
> Is it possible to rebuild wine-stable only if there are "real" changes

The interfere bumps `pkgrel` for each Arch update to avoid missing rebuilds needed for interim changes or library updates.  However, from the update history, this does seem too frequent.  Would rate limiting rebuilds to approximately 1-2/month be sufficient?

If you know what criteria wine uses to determine when prefixes need to be updated, maybe the package could be adjusted to prevent it.

**Comment by xiota** [comment]
Rebuilds should now be rate limited to < 1/month.  https://github.com/chaotic-aur/interfere/commit/fe6093a6a4041fc1b9f77f2d85e80db95aa3bed0

**Comment by yan12125** [comment]
Well, https://github.com/chaotic-aur/interfere/commit/fe6093a6a4041fc1b9f77f2d85e80db95aa3bed0 is more like a work-around than a fix.

> Found this, but if works, would probably also prevent updates across versions.

That is like mixing DLLs from different Windows versions, which may result in unexpected breakage.

> There will be an initial pkgrel downgrade that users can either manually approve or ignore until the 10.0 series is released.

pkgrel downgrade is not good. It's confusing and users may miss important future updates.

Is it possible to define custom update conditions in chaotic-aur? In archlinuxcn, [lilac](https://github.com/archlinuxcn/lilac), the automatic builder, allows something like this: (not tested)
```yaml
update_on:
    - source: cmd
      cmd: curl "https://gitlab.archlinux.org/archlinux/packaging/packages/wine/-/raw/main/PKGBUILD" | grep -E -v '^(pkgver|pkgrel|sha512sums)=' | sha256sum
```

If hacking pkgrel is the only way, please consider using `$(((pkgrel - pkgrel % 5) / 5 + 16))` to avoid pkgrel downgrade.

**Comment by xiota** [comment]
> ... more like a work-around than a fix.

It's a workaround until a better method is found.  I'll keep thinking about it.

Users can also prevent upgrades by editing `IgnorePkg` in `pacman.conf`.

> Is it possible to...

Generating a hash that way is possible, but it cannot be saved for later comparison.

> pkgrel downgrade is not good

I'll consider revising it, but I'm not too concerned about pacman warnings.  They alert users that something has changed so they can search for the reason.

**Comment by yan12125** [comment]
Got it, thank you for considerations.

**Comment by xiota** [comment]
Interfere updated, and pkgrel advanced to 17.  https://github.com/chaotic-aur/interfere/commit/ad8380d48d4ec2f110c9ba993d4acf5633a46748

This should keep `wine-stable` up to date with `wine` packaging improvements, but likely miss rebuilds for library updates.  Manual bumps as needed should be okay.  I don't see common problem packages in the depends list.

**Comment by yan12125** [comment]
Thank you, but seems the trick is not working? [The latest wine package commit](https://gitlab.archlinux.org/archlinux/packaging/packages/wine/-/commit/2329427238fabddfeac776c534fc42a7eba6e5c4) is trivial, while wine-stable is updated again to 9.0-19.

**Comment by xiota** [comment]
The rebuild was in response to the pkgrel change.  When pkgrel is incremented, a rebuild would usually be indicated.  When reset, rebuild may not be needed.  I'll update after thinking about how to better handle this.

**Comment by yan12125** [comment]
Got it. Such rebuilds should be uncommon and are not a big issue for me.

**Comment by xiota** [comment]
Updated interfere: https://github.com/chaotic-aur/interfere/commit/0441c0fa9e645e2a355d96eca98428ed4b0a445f

Should ignore pkgrel resets now.

**Comment by yan12125** [comment]
Recently there are many pkgrel bumps:
https://github.com/chaotic-aur/packages/commits/main/wine-stable

Are those changes necessary?

**Comment by xiota** [comment]
Switching back to `aur/wine-stable` because basing on `extra/wine` didn't work as I had hoped.  Metrics 220.

**Comment by Technetium1** [comment]
Dropped because `lib32-libpcap` is now an orphan, and the package is outdated for 6 months.
