### ISSUE TITLE
[Request] kwin-effects-forceblur

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#3113]
### Package:

https://aur.archlinux.org/packages/kwin-effects-forceblur

### Purpose:

KWin Blur effect fork with window class force blur feature (Wayland & X11)

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by dr460nf1r3** [comment]
Did you verify whether this is working? Afaik it's broken in KDE 6.

**Comment by D3vil0p3r** [comment]
I am using it in KDE 5

**Comment by xiota** [comment]
How are you running Plasma 5 on Arch?

**Comment by D3vil0p3r** [comment]
I didn't still upgrade my system

**Comment by xiota** [comment]
Packages not updated for Plasma 6 were / are being dropped.  It looks like a kwin script, so takes almost no resources to build.  Prob less than a minute in a slow VM.

**Comment by D3vil0p3r** [comment]
Oh... probably it could be better to find a substitute for it. This can be a good replace in Plasma 6: https://aur.archlinux.org/packages/kwin-effects-forceblur

**Comment by xiota** [comment]
You can update your request to the new package.  But it prob won't work in your VM unless you build it yourself.

**Comment by D3vil0p3r** [comment]
I will edit this package request by requesting that linked AUR package and I will upgrade my VM to Plasma 6

**Comment by dr460nf1r3** [comment]
> I didn't still upgrade my VM system

Then how are you planning to install that package? You'll need to at least sync your mirror lists.. but I have to agree with @xiota, KDE 5 packages have no place here anymore as the Arch main repo keeps rolling.

**Comment by xiota** [comment]
I had some machines pinned to Plasma 5 using [Arch Linux Archive](https://wiki.archlinux.org/title/Arch_Linux_Archive), but the xz backdoor forced me to upgrade.  (Then I found out Arch wasn't ever really affected, but too late to go back.)

**Comment by D3vil0p3r** [comment]
> > I didn't still upgrade my VM system
> 
> Then how are you planning to install that package? You'll need to at least sync your mirror lists.. but I have to agree with @xiota, KDE 5 packages have no place here anymore as the Arch main repo keeps rolling. `kwin-effects-forceblur` however is welcome!

I agree. I need to upgrade my VM.

**Comment by ShayBox** [comment]
I use `kwin-effects-forceblur-git` because it naturally often rebuilds, non-git works, but they have to be rebuilt after every plasma update, so that's something chaotic would have to do every time plasma updates.

**Comment by dr460nf1r3** [comment]
This might be possible in infra 4.0, which is supposed to enter pilot phase soon :tm: for now we'll have to do it manually.

**Comment by xiota** [comment]
Closing because this is already in the repo and [upstream](https://github.com/taj-ny/kwin-effects-forceblur) updated for KF6.
