### ISSUE TITLE
[Request] davinci-resolve 

### ISSUE THREAD

**Issue by RashadGasimli** [chaotic-aur/packages#3114]
### Package:

https://aur.archlinux.org/packages/davinci-resolve

### Purpose:

Davinci Resolve is a proprietary video editing, color grading, color correction, visual effects, motion graphics and audio post-production application.

### Copyright:

Commercial

### Expected Interest:

Some

### Already available?

No

### Unique request?

No

### Banned package?

No

**Comment by xiota** [comment]
Rejecting for substantially same reasons package was previously dropped.  It had [numerous defects](https://github.com/chaotic-aur/packages/issues/2832#issuecomment-1745561051).  The maintainer was notified, and has so far resolved only a few of them.

More problems not previously mentioned:

* [License](https://github.com/chaotic-aur/packages/files/15050344/License.txt) implies no right to redistribute.

    > You may not ... copy the Software ...  You must not rent, lease, or sublicense your rights ... except as may be expressly permitted in this License Agreement.

* Program recently reported not working (2024-04-20 19:41); I have confirmed.
    ```
    /opt/resolve/bin/resolve: symbol lookup error: /usr/lib/libgdk_pixbuf-2.0.so.0: undefined symbol: g_task_set_static_name
    ```

* The use of `.install` file to setup `.desktop` files is questionable.

* Missing some files needed to make package useful.

**Comment by RashadGasimli** [comment]
> Rejecting for substantially same reasons package was previously dropped. It had [numerous defects](https://github.com/chaotic-aur/packages/issues/2832#issuecomment-1745561051). The maintainer was notified, and has so far resolved only a few of them.
> 
> More problems not previously mentioned:
> 
>     * [License](https://github.com/chaotic-aur/packages/files/15050344/License.txt) implies no right to redistribute.
>       > You may not ... copy the Software ...  You must not rent, lease, or sublicense your rights ... except as may be expressly permitted in this License Agreement.
> 
>     * Program recently reported not working (2024-04-20 19:41); I have confirmed.
>       ```
>       /opt/resolve/bin/resolve: symbol lookup error: /usr/lib/libgdk_pixbuf-2.0.so.0: undefined symbol: g_task_set_static_name
>       ```
> 
>     * The use of `.install` file to setup `.desktop` files is questionable.
> 
>     * Missing some files needed to make package useful.

oh okay thanks
