### ISSUE TITLE
[Request] svt-av1-psy

### ISSUE THREAD

**Issue by sommio** [chaotic-aur/packages#3116]
### Package:

https://aur.archlinux.org/packages/svt-av1-psy-git

### Purpose:

The Scalable Video Technology for AV1 (SVT-AV1 Encoder and Decoder) with perceptual enhancements for psychovisually optimal AV1 encoding

### Benefits:

The fork of svt-av1, optimized for encoder quality.

### Building:

makepkg

### Copyright:

BSD-3-Clause-Clear & BSD-2-Clause

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

I think everyone who uses `svt-av1` would be interested in it.

**Comment by xiota** [comment]
Rejecting because package has issues that have not been fixed in over six months.
