### ISSUE TITLE
[Request] sublime-music-git

### ISSUE THREAD

**Issue by make-42** [chaotic-aur/packages#3117]
### Package:

https://aur.archlinux.org/packages/sublime-music
https://aur.archlinux.org/packages/sublime-music-git

### Purpose:

This package provides a music player that also works great with Subsonic servers.

### Benefits:

There have only been slight improvements since the last release so the -git package is not that different but since there are very few updates on the git repo it would make sense to add it too since it might include features before the non -git package.

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
Is it be fine to only provide `-git`, especially due to infrequent releases? I would have created a release for this many fixes... https://github.com/sublime-music/sublime-music/compare/v0.12.0...master

**Comment by make-42** [comment]
Only having a `-git` is okay too. Thank you!

**Comment by xiota** [comment]
Flagged both packages.  Defects include:

* Deps need update, including dropping non-existent opt-deps.
* License string needs update to spdx identifier.
* `pkgver()` needs update to remove `v` prefix from version number.
* Python version shouldn't be hard-coded.

Note: Current maintainer of git package (CupricReki) has never pushed an update.  If package is not updated within a couple weeks, someone should open an orphan request.

**Comment by xiota** [comment]
@make-42 Please test whether program works as expected.

**Comment by make-42** [comment]
It does not unfortunately. I guess someone should open an orphan request yes.

**Comment by xiota** [comment]
The previous maintainer already disowned, and there is a new maintainer.  What did not work?  Error messages?

**Comment by make-42** [comment]
Since you are the new maintainer, I'll post this here. You are missing `python-pychromecast` as a dependency. Adding it to the `PKGBUILD`: 
![image](https://github.com/chaotic-aur/packages/assets/17462236/da36e058-8b8d-4b1c-a5ce-917441a94981)

Makes the error go away.

**Comment by make-42** [comment]
It's listed as an optional dependency.

**Comment by make-42** [comment]
But the program will not run without it.
![image](https://github.com/chaotic-aur/packages/assets/17462236/cbaa4a67-c960-41c8-aaf5-706b84288fa5)

**Comment by make-42** [comment]
So you'd also need to remove it from here:
![image](https://github.com/chaotic-aur/packages/assets/17462236/af290407-8a66-428d-8b36-27cc3669ddbe)

**Comment by xiota** [comment]
@make-42 Package updated.  Please test and let me know whether it's working.  I can't test myself because I don't have an account to the service and don't want to sign up for one.

In the future, the error message is enough:
```
ModuleNotFoundError: No module named 'pychromecast'
```

**Comment by make-42** [comment]
It works now. Thank you. And no it wasn't a roundabout way to ask to comaintain. I just gave the solution with the error message to save you some trouble. I'm sorry if it came across as rude.

**Comment by xiota** [comment]
It's no problem.  It took longer to read the comments and reply than to actually fix.  Most maintainers can figure it out something like this from the correct error messages.  I send detailed step-by-step instructions to maintainers who repeatedly make the same mistakes in their packages or for issues that many maintainers have made mistakes fixing.

**Comment by xiota** [comment]
Upstream project [discontinued](https://sumnerevans.com/posts/projects/sublime-music-eom/) Dec 2024.

Metrics 19.

**Comment by xiota** [comment]
Dropping because upstream discontinued and depends on `python-dataclasses-json`, which fails to build for Python 3.14.

Metrics:

* python-dataclasses-json # 53
* sublime-music-git # 19
