### ISSUE TITLE
[Request] qsv

### ISSUE THREAD

**Issue by roland-5** [chaotic-aur/packages#3119]
### Package:

https://aur.archlinux.org/packages/qsv

### Purpose:

CSV data-wrangling toolkit (fork of xsv)

### Benefits:

qsv (is a command line program for querying, indexing, slicing, analyzing, filtering, enriching, transforming, sorting, validating & joining CSV files. Commands are simple, fast & composable.

### Building:

makepkg -si

### Copyright:

Dual-licensed under MIT or the [UNLICENSE](https://unlicense.org).

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

`qsv` require [luau](https://aur.archlinux.org/packages/luau) to build.

**Comment by xiota** [comment]
Dropped because moved to extra.  Metrics 63.
