### ISSUE TITLE
[Rebuild] for python 3.12 upgrade

### ISSUE THREAD

**Issue by Totti786** [chaotic-aur/packages#3125]
### Packages:

https://aur.archlinux.org/packages/anki

### Latest chaotic version

`24.04.1-1`

### Reason for rebuild

The package needs to be rebuilt after the update to Python 3.12

### Builds?

`makepkg`

**Comment by xiota** [comment]
@Totti786 Stop opening issues for every single package that needs to be rebuilt for the same reason.

**Comment by Totti786** [comment]
@xiota Should I list all the packages that need to be rebuilt in the same request?

**Comment by xiota** [comment]
Packages are being rebuilt.  Wait a few days.
