### ISSUE TITLE
[rebuild needed] ungoogled-chromium

### ISSUE THREAD

**Issue by giovannivelludo** [chaotic-aur/packages#313]
After upgrading re2 to version 1:20201101-1, launching chromium causes the following error:
```
/usr/lib/chromium/chromium: error while loading shared libraries: libre2.so.8: cannot open shared object file: No such file or directory
```

**Comment by mads256h** [comment]
The package is gone from the repository

**Comment by PedroHLC** [comment]
Yep, we're testing the new infra (we had to migrate the build server), once it's stable, we'll rebuild it. Until then, to not keep people with outdated non-working stuff, we removed it...

**Comment by giovannivelludo** [comment]
Binaries are also available from the maintainer's repository for the time being: https://github.com/jstkdng/aur

**Comment by axzxc1236** [comment]
**Off topic** but I've been using chaotic-aur for a while and this downtime makes to realize I've been relying on chaotic-aur too much and some things have been broken **horribly**.

I was having video playback issue in Firefox until I disabled h264ify, some video are able to play but MPV is unable to play anything, until I realized ffmpeg-amd-full is broken by libilbc update.

**Comment by aspieln3r** [comment]
any updates on this?

**Comment by PedroHLC** [comment]
I think this was solved, right?

**Comment by dr460nf1r3** [comment]
Garudas builder builds it now in the morning routine and its available in the repo so this issue can be closed.
