### ISSUE TITLE
[Bug] Error downloading pm2ml

### ISSUE THREAD

**Issue by Eroldin** [chaotic-aur/packages#3132]
### Packages:

https://aur.archlinux.org/pm2ml.git

### Latest chaotic version

2021.11.20.1-14.1

### What happens?

error: failed retrieving file 'pm2ml-2021.11.20.1-14.1-any.pkg.tar.zst' from geo-mirror.chaotic.cx : Maximum file size exceeded

This happens on any mirror.

### What is expected to happen?

Should be downloading and installing without any problems.

**Comment by Technetium1** [comment]
`2021.11.20.1-14.2` is available now
