### ISSUE TITLE
[Bug] python3.12 packages miss depedency

### ISSUE THREAD

**Issue by Pingger** [chaotic-aur/packages#3133]
### Packages:

https://aur.archlinux.org/pkgbase/fvs
https://aur.archlinux.org/pkgbase/python-pathvalidate
https://aur.archlinux.org/pkgbase/rare
https://aur.archlinux.org/pkgbase/legendary
https://aur.archlinux.org/pkgbase/vkbasalt
https://aur.archlinux.org/pkgbase/vkbasalt-cli
https://aur.archlinux.org/pkgbase/patool
https://aur.archlinux.org/pkgbase/icoextract

### Latest chaotic version

fvs-0.3.4-2.2

### What happens?

Causes the python modules to not be found, as python3.12 is not yet available from the package repository and 3.11 is still in use.  

This breaks:  
- many python3 based packages from the official repositories (since they can't find their modules in the python3.11/site-packages)
- many pytohn3 based packages from the chaotic-repo (since they can't find their modules in the python3.11/site-packages)

### What is expected to happen?

The "upgrades" either not being applied, or python3.12 being installed.

Cause: dependencies not correctly declared in the chaotic-aur packages. Currently requires python instead of python >=3.12

### More information

Using Manjaro

Versions of all affected bugged packages on my system:
fvs-0.3.4-2.2  legendary-0.20.34-1.1  patool-2.2.0-1.1  python-pathvalidate-3.2.0-1.1  python-steamgriddb-1.0.5-2.1  rare-1.10.11-1.1  vkbasalt-cli-3.1.1-2.1

**Comment by xiota** [comment]
We will discuss how this problem can be prevented in the future.  However, any solution will most likely not apply to the current round of packages.

**Comment by dr460nf1r3** [comment]
This is sadly a #wontfix. Due to the nature of Manjaro repositories, we can't really do much to prevent this happening.

**Comment by ShayBox** [comment]
`obs-studio-tytan652` also needs rebuilt for python 3.12

**Comment by dr460nf1r3** [comment]
Rebuild of obs-studio-tytan652 running.

**Comment by xiota** [comment]
I guess programs that link `libpython3.so` also need to be rebuilt.
