### ISSUE TITLE
[Request] searxng-git

### ISSUE THREAD

**Issue by inetol** [chaotic-aur/packages#3135]
### Package:

https://aur.archlinux.org/packages/searxng-git

### Purpose:

SearXNG is a free internet metasearch engine which aggregates results from more than 70 search services. Users are neither tracked nor profiled.

### Benefits:

SearXNG is a fork of SearX to continue its legacy. Due to its rolling release versioning, every commit in the git `master` branch is considered *stable*.

### Building:

makepkg -sr

### Copyright:

AGPL-3.0-or-later

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Fails to build because problem with pkgver.  Metrics 137.

Has some other problems...

* Appears to hard code a random "secret key" in settings.  The key is regenerated with each rebuild.
* Installs a venv, instead of normal python module with normal python depends.

**Comment by xiota** [comment]
Adjusted pkgver with interfere, so it will at least build.  Packaging of key and venv appear to be justifiable.
