### ISSUE TITLE
[Request] apk-editor-studio

### ISSUE THREAD

**Issue by alexoona** [chaotic-aur/packages#3137]
### Package:

https://aur.archlinux.org/packages/apk-editor-studio

### Purpose:

Powerful yet easy to use APK editor for PC and Mac.

### Benefits:

Good GUI based application for editing APK files on Linux.

### Copyright:

GPL3

### Expected Interest:

Only me

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
We need to double-check the total size and compile time before accepting this

**Comment by alexoona** [comment]
Okay

**Comment by Technetium1** [comment]
Depends explicitly on Qt5: https://github.com/kefir500/apk-editor-studio/blob/063bb9564c399203839b28a7bd114ceda4bf61a7/CMakeLists.txt#L26
For the reasons outlined in #3157, it is declined to be added for now. When this dependency changes, it can be explored again!
