### ISSUE TITLE
[Rebuild] mangohud-git failling to build

### ISSUE THREAD

**Issue by raziel100** [chaotic-aur/packages#3139]
### Packages:

mangohud-git: https://aur.archlinux.org/packages/mangohud-git

### Latest chaotic version

0.7.2.rc3.r0.g046b6ce-1

### Reason for rebuild

is failling to build with the same problem of #3138 

FATAL:   Unable to build from /home/u726578/chaotic/cache/lower/20240426060348.sif: unable to open file /home/u726578/chaotic/cache/lower/20240426060348.sif: open /home/u726578/chaotic/cache/lower/20240426060348.sif: no such file or directory
cp: cannot create regular file '/scratch/chaotic/sandbox/pkgc052094c8c5/home/main-builder/wizard.sh': No such file or directory
chmod: cannot access '/scratch/chaotic/sandbox/pkgc052094c8c5/home/main-builder/wizard.sh': No such file or directory
FATAL:   could not open image /scratch/chaotic/sandbox/pkgc052094c8c5: failed to retrieve path for /scratch/chaotic/sandbox/pkgc052094c8c5: lstat /scratch/chaotic/sandbox/pkgc052094c8c5: no such file or directory

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/mangohud-git.log

### Builds?

yes, with the latest build from aur 0.7.2.rc3.r2.g0e92ec4-1

**Comment by Technetium1** [comment]
`Finished making: mangohud-git 0.7.2.rc3.r2.g0e92ec4-1 (Wed 01 May 2024 04:57:59 PM -03)`

**Comment by xiota** [comment]
@Technetium1 Packages are building, but files aren't added to repo.
