### ISSUE TITLE
[Request] Rsyslog

### ISSUE THREAD

**Issue by CuteistFox** [chaotic-aur/packages#3140]
### Package:

https://aur.archlinux.org/packages/rsyslog

### Purpose:

It is a implementation of syslog

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

[is on the wiki](https://wiki.archlinux.org/title/Rsyslog)

**Comment by xiota** [comment]
Fails to build with error:
```
configure: error: libgcrypt-config not found in PATH and pkg-config is not available. libgcrypt is missing.
```

The patch is calling AC_CHECK_PROG incorrectly.  Not worth fixing with interfere because upstream already committed fix.

Metrics 28.
