### ISSUE TITLE
[Request] zrepl-git

### ISSUE THREAD

**Issue by fmc000** [chaotic-aur/packages#3141]
### Package:

https://aur.archlinux.org/packages/zrepl-git

https://aur.archlinux.org/packages/zrepl

### Purpose:

zrepl is a one-stop, integrated solution for ZFS replication.

Main features:
    Filesystem replication
    Advanced replication features
    Automatic snapshot management
    Sophisticated Monitoring & Logging
    Maintainable implementation in Go

https://zrepl.github.io/

### Benefits:

It's a very easy and powerful implementation of snapshot/backup/remote replication of servers and workstations using ZFS. It comes with preconfigured examples that can be used almost immediately with little effort.

### Building:

Just clone it and run makepkg -si. It automatically downloads go as build requirement.

### Copyright:

MIT

https://github.com/zrepl/zrepl?tab=MIT-1-ov-file#readme

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

On the AUR there is also a pre-built -bin package.

**Comment by fmc000** [comment]
I don't think that the maintainer will ever fix the PKGBUILD. It's it possible to request to zrepl-bin package, also available in the AUR, instead?

**Comment by xiota** [comment]
Looks like there's already an interfere?

When you see packages with issues that haven't been fixed for > 2wks, flag it with detailed explanation of problem.  If maintainer unflags without fixing or complains about "abuse" of flags, open an orphan request with description of problem, how long it has been unresolved (in this case years), whether other people are affected, and that maintainer has refused to fix it.

**Comment by xiota** [comment]
Checked the package.  Commented and flagged since package appears to have been broken since Dec 2022.

**Comment by xiota** [comment]
Switching to git package.  Comment when stable package is fixed if it is still wanted.
