### ISSUE TITLE
[Request] popcorntime-bin

### ISSUE THREAD

**Issue by dandare1980** [chaotic-aur/packages#3142]
### Package:

https://aur.archlinux.org/packages/popcorntime-bin

### Purpose:

A multi-platform, free software BitTorrent client that includes an integrated media player.

### Benefits:

This is the developers recommended [AUR package](https://popcorn-time.site) that is updated faster than the [popcorntime](https://aur.archlinux.org/packages/popcorntime) package.

### Copyright:

[GPL v3 license](https://github.com/popcorn-official/popcorn-desktop/blob/development/LICENSE.txt)

### Expected Interest:

Many

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

### More information:

Suggest this replaces the current [popcorntime](https://aur.archlinux.org/packages/popcorntime) package.

**Comment by Technetium1** [comment]
Intending to this from #733 due to inactive maintainer

**Comment by xiota** [comment]
Program was recently restructured/rewritten (again?).  Given this program's troubled history, taking this opportunity to drop.  Metrics 97.
