### ISSUE TITLE
[Request] lf-git

### ISSUE THREAD

**Issue by seth0xd** [chaotic-aur/packages#3146]
### Package:

https://aur.archlinux.org/packages/lf-git

### Purpose:

A terminal file manager inspired by ranger

### Benefits:

faster and cleaner than the alternatives, and it is written is Go.

### Building:

`env CGO_ENABLED=0 go install -ldflags="-s -w" github.com/gokcehan/lf@latest`

### Copyright:

MIT

### Expected Interest:

Few

### Already available?

Yes

### Unique request?

No

### Banned package?

No

### More information:

I need this package because I don't have access to the AUR on my Artix system, I know I can just build it and all but I prefer to get it from here so I don't have to worry about updating it.

**Comment by Technetium1** [comment]
@seth0xd is it okay to instead use https://aur.archlinux.org/packages/lf-git

**Comment by xiota** [comment]
`extra/lf` is available.  No need for `-bin` or `-git` unless repo package has problems.

**Comment by seth0xd** [comment]
@xiota yeah I think you're right, it's more of an Artix problem. Thanks anyway :sparkles:

**Comment by xiota** [comment]
@seth0xd I'm not familiar with Artix.  Do they provide only a subset of Arch packages?

Would be reasonable to add `lf-git`, but would prefer to avoid duplicating the Arch repos.

**Comment by seth0xd** [comment]
I'm sure that lf ain't in Artix's repos, I have to build it from source since I don't use any AUR helper. But I understand that it might be confusing for anyone else who's not on Artix.

**Comment by xiota** [comment]
Need a "yes" or "no".  Do you want `lf-git` added to chaotic-aur?

**Comment by seth0xd** [comment]
yes

**Comment by xiota** [comment]
In case anyone is wondering, metrics 74.
