### ISSUE TITLE
[Request] feather-wallet

### ISSUE THREAD

**Issue by Maxb0tbeep** [chaotic-aur/packages#3148]
### Package:

https://aur.archlinux.org/packages/feather-wallet

### Purpose:

A monero wallet.

### Benefits:

It's better than the official wallet because it has more features and better UI

### Building:

makepkg -si

### Copyright:

BSD-3-Clause

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
This version is available in repo but I flagged it. It can be added when 2.6.7 is available

**Comment by Technetium1** [comment]
@Maxb0tbeep do you no longer want this package added?
