### ISSUE TITLE
[Rebuild] Fritzing

### ISSUE THREAD

**Issue by CheesyChocolate** [chaotic-aur/packages#3149]
### Packages:

https://aur.archlinux.org/packages/fritzing

### Latest chaotic version

1.0.2-2

### Reason for rebuild

```
Fritzing: error while loading shared libraries: libgit2.so.1.7: cannot open shared object file: No such file or directory
```

probably needs rebuild against `libgit2 1:1.8.0-2`

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/fritzing.log

**Comment by xiota** [comment]
Rebuilt fritzing.  Also, other packages that depend on libgit2 have been bumped.
