### ISSUE TITLE
[Rebuild] waybar-git

### ISSUE THREAD

**Issue by flippette** [chaotic-aur/packages#3150]
### Packages:

https://aur.archlinux.org/packages/waybar-git

### Latest chaotic version

r3346.cc084f5f-1

### Reason for rebuild

- `spdlog` unresolvable dependency
- fixes issue with `hyprland` integration

**Comment by xiota** [comment]
Package has been rebuilt, but needs `python-setuptools` added to makedeps because of Python 3.12 upgrade.
```
ModuleNotFoundError: No module named 'packaging'
```

**Comment by Technetium1** [comment]
@Alexays this has been flagged for a couple of months 👀

**Comment by Alexays** [comment]
Just added `python-setuptools`
