### ISSUE TITLE
[Rebuild] gr-lora_sdr-git

### ISSUE THREAD

**Issue by dreirund** [chaotic-aur/packages#3151]
### Packages:

https://aur.archlinux.org/packages/gr-lora_sdr-git

### Latest chaotic version

8133965-1.1

### Reason for rebuild

Linked against old version of `libgnuradio-runtime`:

In `python`, doing `import lora_sdr`:  
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.12/site-packages/lora_sdr/__init__.py", line 18, in <module>
    from .lora_sdr_python import *
ImportError: libgnuradio-runtime.so.3.10.9: cannot open shared object file: No such file or directory
```

Up to date is `/usr/lib/libgnuradio-runtime.so.3.10.10`.

**Comment by dreirund** [comment]
P.S.: The AUR package has some issues:

* Missing dependencies `python-loudify` and `python-pandas`, see [here](https://aur.archlinux.org/packages/gr-lora_sdr-git#comment-971673),
* Dependency should probably be `boost-libs` instead of `boost`,
* `pkgver()` is broken: It returns the git commit hash, see [here](https://aur.archlinux.org/packages/gr-lora_sdr-git#comment-971674) together with a solution,
* License identifier is not SPDX compliant, see [here](https://aur.archlinux.org/packages/gr-lora_sdr-git#comment-971677).

**Comment by dreirund** [comment]
[&nearr;&hairsp;Here](https://pastebin.com/raw/yA344jYR) is a `PKGBUILD` which received rework and should fix the outstanding issues.

**Comment by Technetium1** [comment]
Orphan request: https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/message/NBSS7EGBJIUKYEJWVEYCMJW5J3WPTHDZ/

**Comment by xiota** [comment]
@dreirund Are you associated with dreieck?

**Comment by dreirund** [comment]
> *@dreirund Are you associated with dreieck?*

Yes.

**Comment by xiota** [comment]
@dreirund I adopted the package and updated.  Can add you as comaintainer, but would insist pkgver follow conventional format `#.r#.g#`.

**Comment by dreirund** [comment]
> @dreirund I adopted the package and updated.  Can add you as
> comaintainer,

In that case I would step out as a maintainer.

> but would insist pkgver follow conventional format
> `#.r#.g#`.

I am totally fine with that.

Regards!

**Comment by xiota** [comment]
@dreirund Added you to some packages.  Also, I don't use epoch on AUR packages because they're build on demand.

**Comment by dreirund** [comment]
> Also, I don't use epoch on AUR packages because they're build on
> demand.

But for the packages in the AUR you still need to set `$epoch`. Since
the AUR is independently usable from `chaotic-aur`.

The version scheme change you did in `gr-lora_sdr-git` requires an
increment of `$epoch` in the AUR package, since the old version was
`8133965`, the new one is `0.5.r4.g8133965`, which is lower by version
compare logic.

So setting `epoch=1` in the AUR package actually is required.

(I have not checked the other packages.)

**Comment by xiota** [comment]
AUR is still build on demand.  AUR helper and Chaotic AUR users will receive notification and can force the update if they want.

Users unwilling to manually force the upgrade can keep the old version.  ultimately their choice.

**Comment by dreirund** [comment]
Regardless what opinions anyone has, the guidelines are clear about
that:

https://wiki.archlinux.org/title/PKGBUILD#epoch

> It is used when the version numbering scheme of a package changes (or
> is alphanumeric), breaking normal version comparison logic.

**Comment by xiota** [comment]
From your own reference:

> Warning: epoch should only be used when **absolutely required** to do so.

There is no statement *requiring* epoch to be used.  Only requirements to meet *when* it is used.

I'm not going to argue this any further with you.

**Comment by dreirund** [comment]
Will you keep it when I set `epoch=1` (i.e. "*you do not care*"), or is your policy to remove every `$epoch`-setting?

**Comment by xiota** [comment]
Please leave epoch alone.  It benefits no one, will force rebuild, and would be annoying.

Applying epoch incorrectly also causes package compatibility problems, requiring interfere to fix.  I haven't done so yet, but know of at least four packages that are affected.

**Comment by Scimmia22** [comment]
xiota, why are you always at the center of so much drama? epoch MUST be used to show that the new version is newer than the old version. This is simple an obvious. It's not specifically spelled out in the guidelines because it's so obvious.

The new version can't be older than the old version. The AUR is not special in this regard.

**Comment by dreirund** [comment]
> *This is simple an obvious. It's not specifically spelled out in the guidelines because it's so obvious.*

Where is the foundational rule that in doubt one can refer to that justifies this "it's so obvious"? Is there any protocol of Arch maintainer meetings?

If not, and if the rule applies, can a formal decision be made (or a decision be made that says that there is no such rule?)

I also do not find the guidelines "court-proof".

**Comment by Scimmia22** [comment]
Again, new version can't be older than the old version. It can't get any more obvious than that.

This crap is the reason we have warnings all over things, like bottles of bleach that have to tell you not to drink it.

**Comment by dr460nf1r3** [comment]
> @dreirund Added you to some packages.  Also, I don't use epoch on AUR packages because they're build on demand.

I'd also set epoch if we are going to alter the pkgver permanently this way, having to pacman -Suu feels clunky given we have the possibility to make it work without. I don't know any other use case of this variable 🤔

**Comment by xiota** [comment]
Epoch controls interpretation of version numbers.  Its purpose is to prevent the version change warning from being shown to users.  This is a one time warning.

But there are packages in chaotic aur that have the warning recurring.  Also, switch to v4 is going to require lots of packages to downgrade.

**Comment by Scimmia22** [comment]
That is completely and totally untrue. It doesn't prevent a warning, it prevents the package from not updating at all.

**Comment by xiota** [comment]
People who can't figure out how to upgrade a package shouldn't be using it.

**Comment by Scimmia22** [comment]
If people can't figure out how to maintain packages, maybe they shouldn't be doing that, either.

**Comment by xiota** [comment]
Again, there is no requirement to bump epoch.  There is a statement to avoid it unless absolutely necessary.  There is no absolute necessity to use epoch, so it shouldn't be used.

**Comment by Scimmia22** [comment]
There absolutely is a requirement to bump epoch. New version can't be older than the old version. Don't drink bleach. Coffee is hot.

**Comment by xiota** [comment]
Epoch is mentioned in only a few places on ArchWiki.  One of them states: "The decision to release changes should be left in the hands of Package Maintainers."  Basically, the only people who should bump epoch are the TU/PM.

**Comment by Scimmia22** [comment]
LOL, you can't be serious. The person bumping the epoch is the person maintaining the PKGBUILD, not just TU/PMs. There is way that could ever, ever be true. I can't even argue with the lack of thinking involved with that statement.

New version can't be older than the old version. A simple, obvious, irrefutable statement.
