### ISSUE TITLE
[Request] mozilla-common

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#3153]
### Package:

https://aur.archlinux.org/packages/mozilla-common

### Purpose:

Helper for forks of the Mozilla codebase which still support NPAPI

### Copyright:

GPL

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
This is very lightweight for anyone who wants it to build.  All this does it add some scripts containing:
```
MOZ_PLUGIN_PATH="/usr/lib/mozilla/plugins"
```

Also, the packages that use this require python2 to build.
