### ISSUE TITLE
[Request] libimobiledevice-git, usbmuxd-git

### ISSUE THREAD

**Issue by fmc000** [chaotic-aur/packages#3155]
### Package:

https://aur.archlinux.org/pkgbase/libimobiledevice-git
https://aur.archlinux.org/pkgbase/usbmuxd-git

Depends:
https://aur.archlinux.org/pkgbase/libusbmuxd-git
... https://aur.archlinux.org/pkgbase/libimobiledevice-glue-git
... ... https://aur.archlinux.org/pkgbase/libplist-git

### Purpose:

libimobiledevice is a cross-platform FOSS library written in C to communicate with iOS devices natively. 

### Benefits:

The -git tree implements all the fixes that are needed to insure that backup and restore operations of devices running iOS >= 14 continue to work. Archlinux provides the official released packages that are more than four years old and dont't work with the vast majority of Apple devices.

This is an example of an issue opened long ago on github (it refers to Debian but it's the same for Arch):

https://github.com/libimobiledevice/libimobiledevice/issues/1439

There are a few threads regarding this issue on bbs.archlinux.org .

### Building:

makepkg -rsi just works

### Copyright:

LGPL-2.1, GPL-2.0 licenses found

### Expected Interest:

Most

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

The website: https://libimobiledevice.org/  includes all the other software components of this project but only the four I'm requesting are needed for backup / restore operations.

**Comment by fmc000** [comment]
Another user just opened a very similar request here:

https://github.com/chaotic-aur/packages/issues/3184

**Comment by xiota** [comment]
Which of the packages is considered the "main" one?

**Comment by fmc000** [comment]
libimobiledevice-git

**Comment by xiota** [comment]
Metrics, for anyone interested.
```
libimobiledevice-git # 79
libimobiledevice-glue-git # 49
libplist-git # 49
libusbmuxd-git # 38
usbmuxd-git # 5
```
