### ISSUE TITLE
[Request] unifetch

### ISSUE THREAD

**Issue by Smart123s** [chaotic-aur/packages#3156]
### Package:

https://aur.archlinux.org/packages/unifetch

### Purpose:

Actively maintained fork of the now archived Neofetch project.

### Benefits:

btw I use Arch

### Building:

yay unifetch

### Copyright:

MIT

### Expected Interest:

Everyone

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
There are too many defunct `*fetch` apps.  Would like to drop some of them.

**Comment by Smart123s** [comment]
Ok sure, understandable. Thanks for letting me know.

**Comment by xiota** [comment]
`unifetch` was added.  I'm referring to others, like `neofetch-git`, `neofrog-git`, `freshfetch-git`, etc.
