### ISSUE TITLE
[Request] ringracers

### ISSUE THREAD

**Issue by Jujstme** [chaotic-aur/packages#3158]
### Package:

https://aur.archlinux.org/packages/ringracers

### Purpose:

Sequel to srb2kart, which is a kart game based on the doom engine.

The prequel game has been already submitted in the past to chaotic-aur and [has been accepted](https://github.com/chaotic-aur/packages/issues/2233)

### Copyright:

GPL2. License is available at: https://github.com/KartKrewDev/RingRacers/blob/master/LICENSE

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Also needs [ringracers-data](https://aur.archlinux.org/packages/ringracers-data) as a dependency in order to run.

**Comment by xiota** [comment]
How big is the sequel?  I didn't realize `srb2kart-data` was so large.
```
$ pacman -Si srb2kart-data | grep Size
Download Size   : 208.07 MiB
Installed Size  : 507.67 MiB
```

**Comment by Technetium1** [comment]
```
Download Size   : 646.69 MiB
Installed Size  : 755.47 MiB
```

**Comment by xiota** [comment]
Maybe someday... a separate spacehogs repo for games, binaries, and other packages.
