### ISSUE TITLE
[Rebuild] qt5-webkit

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#3160]
### Packages:

https://aur.archlinux.org/packages/qt5-webkit

### Latest chaotic version

latest

### Reason for rebuild

After the update of `icu` package to 75, `qt5-webkit` seems to break by the following error:
```
resolving dependencies...
warning: cannot resolve "libicuuc.so=74-64", a dependency of "qt5-webkit"
warning: cannot resolve "libicui18n.so=74-64", a dependency of "qt5-webkit"
:: The following package cannot be upgraded due to unresolvable dependencies:
      qt5-webkit

:: Do you want to skip the above package for this upgrade? [y/N]
```

**Comment by D3vil0p3r** [comment]
Probably this package will be dropped soon according to https://github.com/chaotic-aur/packages/issues/3157 but be aware about other Chaotic packages that depend on icu libraries.

**Comment by Technetium1** [comment]
Build is currently failing: [qt5-webkit.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/qt5-webkit.log)
Others report the same failure in clean chroot: https://aur.archlinux.org/packages/qt5-webkit#comment-973711

**Comment by thotypous** [comment]
Latest ICU [seems to require](https://gitlab.pyicu.org/main/pyicu/-/issues/169#note_973) `-std=c++17` but [changing](https://github.com/chaotic-aur/interfere/commit/45b1c8eeb519244d263d9829809ace8318f1f14d) from C++11 to C++17 [breaks](https://builds.garudalinux.org/repos/chaotic-aur/logs/qt5-webkit.log) some of the existing qt5-webkit code

**Comment by xiota** [comment]
Dropping `qt5-webkit` because it looks too complicated to fix.  It was deprecated years ago.  The project keeping it alive quit ~2020.

**Comment by D3vil0p3r** [comment]
Thank you @xiota in qt6 what is the package that should replace that one?

**Comment by xiota** [comment]
There's no replacement.  Upstream development on qtwebkit was deprecated years ago.  They switched to qtwebengine.

Programs that were never updated from qtwebkit have been on life support.  They're basically abandoned.  Long past time to unplug.
