### ISSUE TITLE
[Bug] qt5-webkit: missing dependencies

### ISSUE THREAD

**Issue by rssrcr** [chaotic-aur/packages#3162]
### Packages:

https://aur.archlinux.org/qt5-webkit.git

### Latest chaotic version

5.212.0alpha4

### What happens?

$ sudo pacman -Sy chaotic-aur/qt5-webkit
:: Synchronising package databases...
 core is up to date
 extra is up to date
 multilib is up to date
 chaotic-aur is up to date
resolving dependencies...
warning: cannot resolve "libicuuc.so=74-64", a dependency of "qt5-webkit"
warning: cannot resolve "libicui18n.so=74-64", a dependency of "qt5-webkit"
:: The following package cannot be upgraded due to unresolvable dependencies:
      qt5-webkit

:: Do you want to skip the above package for this upgrade? [y/N] 
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'libicuuc.so=74-64' required by qt5-webkit
:: unable to satisfy dependency 'libicui18n.so=74-64' required by qt5-webkit

### What is expected to happen?

Ordinary installation.

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/qt5-webkit.log

**Comment by dr460nf1r3** [comment]
https://github.com/chaotic-aur/packages/issues/3160
