### ISSUE TITLE
[Request] f5vpn

### ISSUE THREAD

**Issue by rssrcr** [chaotic-aur/packages#3163]
### Package:

https://aur.archlinux.org/packages/f5vpn

### Purpose:

VPN client using the Point-to-Point Protocol to connect to F5Networks BIG-IP APM

### Copyright:

Commercial

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
Related to #3157 because of Qt5

**Comment by xiota** [comment]
Depends on `qt5-webkit` ⇒ abandonware.
