### ISSUE TITLE
[Rebuild] `vkd3d-tkg-git`, `lib32-vkd3d-tkg-git` , `vkd3d-proton-tkg-git`, `lib32-vkd3d-proton-tkg-git`

### ISSUE THREAD

**Issue by dreirund** [chaotic-aur/packages#3164]
### Packages:

Is not anymore in the AUR.

### Latest chaotic version

`1.6.r86.gf9e7cb63-1` and `1.1.r4024.g0fe5a5a9-1`

### Reason for rebuild

vkd3d-git currently is at version `1.11.556.g9c83caed`.

`vkd3d-tkg-git` and `lib32-vkd3d-tkg-git` and `vkd3d-proton-tkg-git` and `lib32-vkd3d-proton-tkg-git` are lacking behind quite a lot.

**Comment by xiota** [comment]
These are custom pkgbuilds in lists.  Failing to build because of linker errors.  I'm inclined to drop tkg packages.

If `extra/vkd3d` isn't good enough, we can use either `aur/vkd3d-git` or a custom pkgbuild.

**Comment by dr460nf1r3** [comment]
> tkg packages

+1, they have been problematic since a while. I think @PedroHLC was actively fixing up the issues when they were introduced years ago, but since nobody (I guess?) here actively makes use of them anymore, constantly fixing up new errors became an annoying chore quite quickly. Tkg-kernels were already dropped due to this, therefore it makes sense to handle the other packages that way too.

**Comment by xiota** [comment]
Dropped the `tkg` packages, except `mesa-tkg-git`.  It is currently working, while `aur/mesa-git` and `aur/lib32-mesa-git` are not.

**Comment by SectionTN** [comment]
will tkg packages get back when they're fixed?

**Comment by PedroHLC** [comment]
> will tkg packages get back when they're fixed?

Not these. They were very attractive in the past with unique features/patches, but now other packages (proton-ge, linux-cachyos, AUR's vkd3d-git) have the same features and patches, pre-configured in a way where it benefits the biggest group of people out-of-the-box. TkG's packages still focus on customization (tweak them your own way while building), which is a challenge for us to redistributing pre-built packages.

Except of `mesa-tkg-git` which is still the best maintained `mesa*-git` around.

**Comment by SectionTN** [comment]
you gave me better info about it i wasn't aware of.
so i need to use `something`-git from the aur instead of tkg ones? except mesa tkg 
(i'm bad at english so if you get what i mean)

**Comment by PedroHLC** [comment]
> so i need to use `something`-git from the aur instead of tkg ones? except mesa tkg

Exactly, you'll want to replace `vkd3d{,-proton}-tkg-git` with the equivalent `vkd3d-proton-mingw-git` (also, non-proton one has no advantages over the proton one, and we don't have 32-bits DX12 games around)

**Comment by SectionTN** [comment]
thanks a lot for telling me, wish you a good day 👍🏻

**Comment by dreirund** [comment]
On Thu, 30 May 2024 05:03:05 -0700, Pedro Lara Campos
***@***.***> wrote:

> > so i need to use `something`-git from the aur instead of tkg ones?
> > except mesa tkg  
> 
> Exactly, you'll want to replace `vkd3d{,-proton}-tkg-git` with the
> equivalent `vkd3d-proton-mingw-git`

What is the use-case difference between `vkd3d-git` and
`vkd3d-proton-mingw-git`? What does the `mingw` mean?
