### ISSUE TITLE
[Rebuild] firefox-nightly firefox-wayland-hg

### ISSUE THREAD

**Issue by Weroxig** [chaotic-aur/packages#3168]
### Packages:

https://aur.archlinux.org/packages/firefox-nightly
https://aur.archlinux.org/packages/firefox-wayland-hg

### Latest chaotic version

127.0a1+20240512.21+h45d7400ce-1

### Reason for rebuild

out of date. build error

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/firefox-nightly.log
https://builds.garudalinux.org/repos/chaotic-aur/logs/firefox-wayland-hg.log

### Builds?

I haven't tried. takes too long for my system to build firefox

**Comment by xiota** [comment]
There were some problems with python and rust that I don't know how to fix.  The patch used for `extra/firefox` doesn't work with nightly code base.

**Comment by xiota** [comment]
Potentially related upstream bug: [1898479](https://bugzilla.mozilla.org/show_bug.cgi?id=1898479)

**Comment by xiota** [comment]
Firefox packages building successfully again.
```
$ pacman -Si firefox-nightly | grep Date
Build Date      : Sun 09 Jun 2024 11:50:21 AM UTC

$ pacman -Si firefox-wayland-hg | grep Date
Build Date      : Sat 08 Jun 2024 04:00:56 PM UTC
```
