### ISSUE TITLE
[Remove] duckstation-git

### ISSUE THREAD

**Issue by NerosTie** [chaotic-aur/packages#3169]
### Packages:

https://aur.archlinux.org/packages/duckstation-git

### Latest chaotic version

0.1-6759

### Reason for rebuild

No new update since 05/05.

Version in Chaotic: 0.1-6759
Version from git: 0.1-6862

**Comment by xiota** [comment]
Repurposing to remove request.  Planning to drop `duckstation-git` "soon".  The dev changed license and made clear downstream packaging is unwelcome.  While may be within rights to continue packaging, it is not worth the effort.  Users who want to continue using `duckstation-git` may build it themselves.

The stable `duckstation` package has been pinned to the last GPL commit (2024-09-01).  It will be provided for now, but may eventually also be dropped.
