### ISSUE TITLE
Anbox support for linux-tkg-*?

### ISSUE THREAD

**Issue by h0cheung** [chaotic-aur/packages#317]
I really like linux-tkg kernels, especially the pds version. However, it seems that the versions in chaotic-aur doesn't support anbox.

Is it possible to add support in this packages, or add some packages with anbox support?

By the way, is Valve Fsync supported by every version of linux-tkg in this repo?

**Comment by PedroHLC** [comment]
> Is it possible to add support in this packages, or add some packages with anbox support?

It's already there in ours 5.10 builds...

> By the way, is Valve Fsync supported by every version of linux-tkg in this repo?

It is!
