### ISSUE TITLE
[Request] proton-vpn-gtk-app

### ISSUE THREAD

**Issue by mdhishamsayed** [chaotic-aur/packages#3171]
### Package:

https://aur.archlinux.org/packages/proton-vpn-gtk-app

### Purpose:

proton vpn app maintained by the community

### Benefits:

anonymity 

### Building:

package made by amethyst aur helper, contains many aur dependencies

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
Duplicate of #3167
