### ISSUE TITLE
[Request] linux-xanmod-bore (v1,v2,v3)

### ISSUE THREAD

**Issue by mdhishamsayed** [chaotic-aur/packages#3172]
### Package:

https://aur.archlinux.org/packages/linux-xanmod-bore

### Purpose:

Linux Xanmod (Stable) with BORE CPU scheduler and tickrate customizations

### Benefits:

Fast performance

### Building:

makepkg -si

### Copyright:

GPL2

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

PLEASE USE GCC for compiling, clang causes issues..

**Comment by xiota** [comment]
What advantage would `linux-xanmod-bore` have over `linux-cachyos-bore`?

Note: `linux-xanmod-bore` is at 6.8.11.

**Comment by mdhishamsayed** [comment]
@xiota No advantage ig but xanmod kernels are different from cachyos kernels and cachyos kernels are related to only one distro while xanmod can cater multiple ones

**Comment by dr460nf1r3** [comment]
What makes it rated to one distro other than the name?

**Comment by mdhishamsayed** [comment]
@dr460nf1r3 Nothing ig..
