### ISSUE TITLE
[Request] python-librosa

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#3173]
### Package:

https://aur.archlinux.org/packages/python-librosa

### Purpose:

Python library for music and audio analysis

### Copyright:

ISC

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Inclined to reject.

* depends without dependant
* poorly maintained.  autoupdated by bot.  no one monitoring comments for issues.

**Comment by Technetium1** [comment]
Is this a dependency for something else you want?

**Comment by D3vil0p3r** [comment]
No. It is for developing deep learning based programs related to audio.

**Comment by xiota** [comment]
As long as package is in current state (no dependents, autoupdate bot, etc), I'm against adding.  (If it is, guess who gets to test, fix, and eventually drop it later.)

**Comment by Technetium1** [comment]
@D3vil0p3r after further discussing details of this package, we agreed that it doesn't belong on Chaotic. If the maintainer changes, this can be revisited.
