### ISSUE TITLE
[Request] mihomo

### ISSUE THREAD

**Issue by YuugataShinonome** [chaotic-aur/packages#3177]
### Package:

https://aur.archlinux.org/packages/mihomo

### Purpose:

it is a proxy daemon, popular in china mainland to bypass GFW

### Benefits:

the pre-build binary provided by AUR package `mihomo-bin` has some problems. I build from source by the AUR package `mihomo` and it runs well. 

### Building:

makepkg

### Copyright:

GPL3

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
@YuugataShinonome is the correct package linked? If so, the description needs fixed 👀

**Comment by YuugataShinonome** [comment]
Thanks for your response! I think it's the correct link to the AUR web page. Which part of the description should I fix?

**Comment by xiota** [comment]
Rejected because none of the descriptions for this package make any sense.
* "it is a proxy daemon, popular in china mainland to bypass GFW"
* "Mihomo Kernel by MetaCubeX, formerly known as Clash.Meta"
* "A simple Python Pydantic model for Honkai: Star Rail parsed data from the Mihomo API."

**Comment by YuugataShinonome** [comment]
@xiota Sorry for not explaining it well.
 That's the mysterious one. It involves some kind of cultural background.

To begin with, the `clash` package in official repo upstream is https://github.com/Dreamacro/clash , which is now 404 because the developer is threatened or caught by someone who don't want citizens to bypass GFW. `Clash.Meta` is close source version with more features.

After the event, team `MetaCubeX` continues to develop, and implements additional features in `Clash.Meta`. To play a joke (the name relates to some anime meme stuff) and to hide themselves from GitHub, they rename `Clash.Meta` to `mihomo`, and change their main branch to the repo as `A simple Python Pydantic model for Honkai: Star Rail parsed data from the Mihomo API.`. When go to https://github.com/MetaCubeX/mihomo and select `Meta` branch, it's the actual source code.

**Comment by Technetium1** [comment]
We've provided clash before, I didn't know it was still alive with a new name! https://github.com/chaotic-aur/packages/issues/2311 https://github.com/chaotic-aur/packages/issues/2106
Clever way to hide. Thank you for clarification.
