### ISSUE TITLE
[request] linux-next

### ISSUE THREAD

**Issue by eatmyvenom** [chaotic-aur/packages#318]
aur page
https://aur.archlinux.org/linux-next-git.git

This request also includes `linux-next-headers` 
As this is a rather large and frequently updated package, I personally believe that this could be put in with the group of packages rebuilt daily like llvm.

**Comment by PedroHLC** [comment]
Curious about this one, is it like a fluctuation btw stable and mainline? Or is it daily snapshots of the repo like firefox-nightly?

**Comment by eatmyvenom** [comment]
A new tag is created daily similar to firefox-nightly. The new tags appear to be created at 4:00 AM UTC from what I can tell.

**Comment by dr460nf1r3** [comment]
Package in repo now.

**Comment by xiota** [comment]
Dropping because:

* Linux kernels are resource intensive to build.
* I prefer to direct resources and effort into keeping other kernels working.
* `linux-mainline` release candidates should be sufficient for end-user testing.
    * git kernels are prone to bugs that can lead to data loss.
    * kernel devs should build their own branches.
