### ISSUE TITLE
[Request] phonon-qt6-gstreamer-git

### ISSUE THREAD

**Issue by fpprim** [chaotic-aur/packages#3182]
### Package:

https://aur.archlinux.org/packages/phonon-qt6-gstreamer-git

### Purpose:

Phonon GStreamer backend for Qt6

### Copyright:

LGPL

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

Yes

### More information:

[https://bbs.archlinux.org/viewtopic.php?pid=2155282](https://bbs.archlinux.org/viewtopic.php?pid=2155282)
**phonon-qt6-mpv** is already packaged, I think **phonon-qt6-gstreamer-git** should be too.

**Comment by xiota** [comment]
Added with a few caveats:

* phonon-gstreamer is deprecated, and this package uses a patch to support Qt6.  If package has significant break that isn't fixed promptly (~1 week), it will be dropped.
* Someone has reported:
    > The video preview works fine, but as a side effect, videos that you try to play by double clicking to watch in some player like MPV sometimes will not launch and report the following error message: "Invalid environment block error".
