### ISSUE TITLE
[Request] droidcam-obs-plugin

### ISSUE THREAD

**Issue by DarkXero-dev** [chaotic-aur/packages#3183]
### Package

https://aur.archlinux.org/packages/droidcam-obs-plugin

### Purpose

Plugin for DroidCam OBS.  Any Content creator using an iPhone and/or Android Phone will be able to use their device as a webcam in tandem with the companion app on the phone. 

### License

GPLV2

**Comment by Ceye4n** [comment]
also need this (but it's not available)

**Comment by Technetium1** [comment]
Needs refactored and there is currently no maintainer

**Comment by xiota** [comment]
As far as I can tell, the source replacement was done before the previous maintainer disowned.  There is a source-built package, `aur/droidcam-obs-plugin`.

**Comment by Technetium1** [comment]
Oh good, they did do the replacement first! Waiting on a maintainer then.

**Comment by xiota** [comment]
Will use source package.

**Comment by Technetium1** [comment]
Yes, tested source package, working well!
