### ISSUE TITLE
[Request] usbmuxd-git

### ISSUE THREAD

**Issue by DarkXero-dev** [chaotic-aur/packages#3184]
### Package:

https://aur.archlinux.org/packages/usbmuxd-git
https://aur.archlinux.org/packages/libusbmuxd-git

### Purpose:

A socket daemon to multiplex connections from and to iOS devices. Allows iOS devices to connect to Linux as a webcam over USB.

### Benefits:

For people like myself who own an iOS device that want to use in tandem with my previous request [**here**](https://github.com/chaotic-aur/packages/issues/3183) and OBS-Studio as a webcam. 

### Building:

makepkg -rsi

### Copyright:

 LGPL-2.1 license

### Expected Interest:

Most

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

### More information:

The non -git versions already exist on Arch only they do not work or support newer iOS versions. Hence why we need -git versions.. I tested both normal n -git since only -git works.

**Comment by fmc000** [comment]
I have opened an almost identical request here:

https://github.com/chaotic-aur/packages/issues/3155

**Comment by DarkXero-dev** [comment]
You did not mention usbmuxd in yours that's why I opened a new one.  Sorry my bad.

**Comment by xiota** [comment]
@fmc000 deja vu.

@DarkXero-dev You can always comment on closely related issues.  Depends are necessarily added when other packages are added.

**Comment by DarkXero-dev** [comment]
@xiota Ah I did not know. Next time I will ;)

**Comment by DarkXero-dev** [comment]
Why not planned ? Are you going to instead do the duplicate ?

**Comment by xiota** [comment]
@DarkXero-dev Already done. 5e48a8969edc3530a22587826d5d69a6fd1f1d48

**Comment by DarkXero-dev** [comment]
@xiota Ahhh thanks so much ;)
