### ISSUE TITLE
[Rebuild] albert

### ISSUE THREAD

**Issue by hedgehog1029** [chaotic-aur/packages#3185]
### Packages:

https://aur.archlinux.org/packages/albert

### Latest chaotic version

0.23.0-3

### Reason for rebuild

Python soname bump

### More information

Is there a tracking issue for the python soname bump? I've had a few AUR packages break, though I can't remember what they are right now...

**Comment by Technetium1** [comment]
`Finished making: albert 0.23.0-3.1 (Sat 08 Jun 2024 07:51:46 AM CEST)`

**Comment by xiota** [comment]
[Bumped](https://github.com/chaotic-aur/interfere/commit/b17ac47e6b85e910608eaac0921ac5dafdf402e3) some packages that were missed in #3125.

**Comment by FabioLolix** [comment]
> I've had a few AUR packages break, though I can't remember what they are right now...

Run `pacman -Qoq /usr/lib/python3.11/`
