### ISSUE TITLE
[Bug] ares-emu + ares-emu-git

### ISSUE THREAD

**Issue by Phantop** [chaotic-aur/packages#3187]
### Packages:

https://aur.archlinux.org/packages/ares-emu
https://aur.archlinux.org/packages/ares-emu-git

### Latest chaotic version

138-1, 138.r54.gfc7cdb57f-1

### What happens?

Loading an n64 rom causes the emulator to crash with an illegal instruction error. This does not happen with packages built on my own system.

### What is expected to happen?

The game loads without error.

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/ares-emu.log
https://builds.garudalinux.org/repos/chaotic-aur/logs/ares-emu-git.log

### More information

Guessing it's something CPU/optimization related. For reference, I'm using an Intel Core i5-1135G7 (Tiger Lake).

**Comment by xiota** [comment]
Problem at [desktop-ui/GNUmakefile#L15-L24](https://github.com/ares-emulator/ares/blob/fc7cdb57f7778e13dafdfa7b1280a6f078db41ff/desktop-ui/GNUmakefile#L15-L24)

**Comment by xiota** [comment]
@Phantop Please test `ares-emu-avx-git` (testing a potential interfere).

For N64, `extra/mupen64plus` + `chaotic-aur/rmg` performs better.

**Comment by Phantop** [comment]
`ares-emu-avx-git` works without issues!

Unlike `rmg`, `ares` offers a bunch of shader settings and I do intend to use it with other platforms, but that's for the suggestion.

**Comment by xiota** [comment]
To prevent illegal instructions, the following packages have been modified or created:

* ares-emu: targets x86-64 (sse2)
* ares-emu-git: targets x86-64 (sse2)
* ares-emu-avx-git: targets x86-64-v3 (avx/avx2)

**Comment by xiota** [comment]
This problem was probably back for about a month.  Should be fixed now.
