### ISSUE TITLE
[Request] evdi

### ISSUE THREAD

**Issue by latin-1** [chaotic-aur/packages#3188]
### Package:

https://aur.archlinux.org/packages/evdi

### Purpose:

DisplayLink

### Copyright:

GPL

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Currently only evdi-git is available in chaotic-aur.

**Comment by xiota** [comment]
What is the benefit of `evdi` over `evdi-git`?  Currently, there is only one commit difference between them.

**Comment by latin-1** [comment]
There's no particular need; I just don't want to use the -git package.
