### ISSUE TITLE
[Request] ttf-iosevka-term

### ISSUE THREAD

**Issue by latin-1** [chaotic-aur/packages#3189]
### Package:

https://aur.archlinux.org/packages/ttf-iosevka-term

### Purpose:

Iosevka, targeting terminal users.

### Copyright:

OFL

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
This font is included in `extra/ttc-iosevka`.  TTC versions of all the iosevka fonts are in the `extra` repo.  Is there any need to provide the TTF versions?

**Comment by latin-1** [comment]
Oh I did not know that. I'm still using ttf-iosevka from aur. Thank you for telling me!
