### ISSUE TITLE
[request] ffmpeg-full-git

### ISSUE THREAD

**Issue by juxuanu** [chaotic-aur/packages#319]
https://aur.archlinux.org/packages/ffmpeg-full-git/

**Comment by SolarAquarion** [comment]
No, it breaks every package that relies on ffmpeg every time there is a new
commit

**Comment by PedroHLC** [comment]
:thinking: Not sure about dropping it, I think we can have it as long as people don't expect any kind of good experience having it, not sure how to make that public...

**Comment by SolarAquarion** [comment]
if you want to build something, i would say ffmpeg-full should be good
enough
