### ISSUE TITLE
[Bug] flutter-bin

### ISSUE THREAD

**Issue by higaski** [chaotic-aur/packages#3194]
### Packages:

https://aur.archlinux.org/packages/flutter-bin

### Latest chaotic version

3.22.2-1

### What happens?

Latest update broke flutter-bin for me, reinstalling the package did not help.

```
╰─λ flutter create hello_world
Building flutter tool...
Resolving dependencies... (1.8s)
Downloading packages...
Got dependencies.
../../.cache/flutter_sdk/packages/flutter_tools/lib/src/isolated/native_assets/native_assets.dart:48:10: Error: Type 'DryRunResult' not found.
Future<DryRunResult> dryRun({
^^^^^^^^^^^^
../../.cache/flutter_sdk/packages/flutter_tools/lib/src/isolated/native_assets/native_assets.dart:127:10: Error: Type 'DryRunResult' not found.
Future<DryRunResult> dryRun({
^^^^^^^^^^^^
../../.cache/flutter_sdk/packages/flutter_tools/lib/src/isolated/native_assets/native_assets.dart:754:37: Error: Type 'DryRunResult' not found.
void ensureNativeAssetsBuildSucceed(DryRunResult result) {
^^^^^^^^^^^^
../../.cache/flutter_sdk/packages/flutter_tools/lib/src/isolated/native_assets/native_assets.dart:123:26: Error: The getter 'packagesWithNativeAssets' isn't defined for the class 'PackageLayout'.
- 'PackageLayout' is from 'package:native_assets_builder/src/package_layout/package_layout.dart' ('../../.pub-cache/hosted/pub.dev/native_assets_builder-0.7.0/lib/src/package_layout/package_layout.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'packagesWithNativeAssets'.
return packageLayout.packagesWithNativeAssets;
^^^^^^^^^^^^^^^^^^^^^^^^
../../.cache/flutter_sdk/packages/flutter_tools/lib/src/isolated/native_assets/native_assets.dart:137:25: Error: The method 'dryRun' isn't defined for the class 'NativeAssetsBuildRunner'.
- 'NativeAssetsBuildRunner' is from 'package:native_assets_builder/src/build_runner/build_runner.dart' ('../../.pub-cache/hosted/pub.dev/native_assets_builder-0.7.0/lib/src/build_runner/build_runner.dart').
Try correcting the name to the name of an existing method, or defining a method named 'dryRun'.
return _buildRunner.dryRun(
^^^^^^
../../.cache/flutter_sdk/packages/flutter_tools/lib/src/isolated/native_assets/native_assets.dart:563:9: Error: 'DryRunResult' isn't a type.
final DryRunResult dryRunResult = await buildRunner.dryRun(
^^^^^^^^^^^^
../../.cache/flutter_sdk/packages/flutter_tools/lib/src/isolated/native_assets/native_assets.dart:754:37: Error: 'DryRunResult' isn't a type.
void ensureNativeAssetsBuildSucceed(DryRunResult result) {
^^^^^^^^^^^^
../../.cache/flutter_sdk/packages/flutter_tools/lib/src/isolated/native_assets/android/native_assets.dart:53:9: Error: 'DryRunResult' isn't a type.
final DryRunResult dryRunResult = await buildRunner.dryRun(
^^^^^^^^^^^^
../../.cache/flutter_sdk/packages/flutter_tools/lib/src/isolated/native_assets/ios/native_assets.dart:51:9: Error: 'DryRunResult' isn't a type.
final DryRunResult dryRunResult = await buildRunner.dryRun(
^^^^^^^^^^^^
../../.cache/flutter_sdk/packages/flutter_tools/lib/src/isolated/native_assets/macos/native_assets.dart:55:9: Error: 'DryRunResult' isn't a type.
final DryRunResult dryRunResult = await buildRunner.dryRun(
^^^^^^^^^^^^
```

### What is expected to happen?

flutter create hello_world should create the test project without any errors

### More information

Hm, same issue after downgrading to 3.22.1-1 again.

**Comment by xiota** [comment]
Thank you for letting me know.  Looks like old caxhe needs to be cleares.  Are you using unionfs or did you add your user to flutter group?  Should work either way, but location of cache is different.  With unionfs, cache is in `~/.cache`.  If added to flutter group, package qoule probably need update.

**Comment by higaski** [comment]
Thanks for the fast reply. Creating and adding myself to the group flutterusers worked. That should be documented somewhere though.

**Comment by xiota** [comment]
@higaski Adding users to the `flutter` group is printed by pacman at install and update, but it leads to warning messages when flutter is updated.  I will update the message to mention clearing the home-directory cache.

**Comment by vacating** [comment]
what is the solution_?  i got the same error today

**Comment by vacating** [comment]
after flutter upgrade this shit load of errors wont stop 

Building flutter tool... 
Running pub upgrade... 
Resolving dependencies...
Downloading packages...
Got dependencies.
../../../../dev/src/flutter/packages/flutter_tools/lib/src/isolated/native_assets/native_assets.dart:48:10: Error: Type 'DryRunResult' not found.
  Future<DryRunResult> dryRun({
         ^^^^^^^^^^^^
../../../../dev/src/flutter/packages/flutter_tools/lib/src/isolated/native_assets/native_assets.dart:127:10: Error: Type 'DryRunResult' not found.
  Future<DryRunResult> dryRun({
         ^^^^^^^^^^^^
../../../../dev/src/flutter/packages/flutter_tools/lib/src/isolated/native_assets/native_assets.dart:754:37: Error: Type 'DryRunResult' not found.
void ensureNativeAssetsBuildSucceed(DryRunResult result) {
                                    ^^^^^^^^^^^^
../../../../dev/src/flutter/packages/flutter_tools/lib/src/isolated/native_assets/native_assets.dart:123:26: Error: The getter 'packagesWithNativeAssets' isn't defined for the class 'PackageLayout'.
 - 'PackageLayout' is from 'package:native_assets_builder/src/package_layout/package_layout.dart' ('../../Pub/Cache/hosted/pub.dev/native_assets_builder-0.7.0/lib/src/package_layout/package_layout.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'packagesWithNativeAssets'.
    return packageLayout.packagesWithNativeAssets;


and this is not being   Initialized  :     Initializing the Flutter SDK. This may take a few minutes.    which give the same erros

**Comment by xiota** [comment]
@vacating Dismounting and deleting the alternate flutter write directories may help.
```
fusermount -uq ~/.cache/flutter_sdk
rm -rf ~/.cache/{flutter_sdk,flutter_local}
```
