### ISSUE TITLE
[Rebuild] linux-xanmod-*

### ISSUE THREAD

**Issue by EvoXCX** [chaotic-aur/packages#3199]
### Packages:

https://aur.archlinux.org/packages/linux-xanmod

Missing headers in your repo, I don't remember if they are from this repo or not.

### Latest chaotic version

Stable: 6.9.3
LTS: 6.6.32

### Reason for rebuild

Broken, failed to build.

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-xanmod-clang-v3.log
https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-xanmod-clang-v2.log
https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-xanmod-lts-clang-v3.log
https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-xanmod-lts-clang-v2.log
https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-xanmod-lts.log

**Comment by xiota** [comment]
Linux kernels recently failing to build with clang, so those packages will be dropped.  The `-v3` kernels with name change should be rebuilt with `gcc` in a few days.  The `-v2` kernels will not be rebuilt because of low usage.
