### ISSUE TITLE
[Rebuild] ffmpeg-obs & obs-studio-tytan652

### ISSUE THREAD

**Issue by ShayBox** [chaotic-aur/packages#3202]
### Packages:

https://aur.archlinux.org/packages/ffmpeg-obs
https://aur.archlinux.org/packages/obs-studio-tytan652

### Latest chaotic version

6.1.1-10 & 30.1.2-4

### Reason for rebuild

Outdated
7.0.1-2 & 30.1.2-5

### More information

I can't update my system without these packages being updated.

**Comment by Technetium1** [comment]
`Finished making: ffmpeg-obs 7.0.1-2 (Sat 22 Jun 2024 06:29:46 PM CEST)`
`Finished making: obs-studio-tytan652 30.1.2-5 (Sat 22 Jun 2024 06:34:07 PM CEST)`
