### ISSUE TITLE
[Rebuild] colloid-gtk-theme-git

### ISSUE THREAD

**Issue by tio-trom** [chaotic-aur/packages#3203]
### Packages:

https://aur.archlinux.org/packages/colloid-gtk-theme-git

### Latest chaotic version

2024.06.18.r4.gdffFla7-1

### Reason for rebuild

The maintainer reverted back some stuff to make it work with the proper window buttons see https://aur.archlinux.org/cgit/aur.git/commit/?h=colloid-gtk-theme-git&id=c5a16c883951750afbe0bbaca1fed40f17f75c81 - however I am not seeing these changes being propagated to the chaotic-aur package.... Maybe a rebuild is necessary?

**Comment by tio-trom** [comment]
I have rebuilt them manually on my machine and the issue is fixed. So probably you have to rebuild them for chaotic aur.

**Comment by Technetium1** [comment]
`Finished making: colloid-gtk-theme-git 2024.06.18.r4.gdfff1a7-1.1 (Mon 24 Jun 2024 10:10:23 AM CEST)`

**Comment by tio-trom** [comment]
The package should also install the catppuccin variant - https://aur.archlinux.org/packages/colloid-gtk-theme-git

```
package_colloid-catppuccin-gtk-theme-git() {
  pkgdesc="Gtk Catppuccin theme for Linux"
  provides=("${pkgname%-git}")
  conflicts=("${pkgname%-git}")

  cd Colloid-gtk-theme
  install -d "$pkgdir/usr/share/themes"
  ./install.sh -t all --tweaks catppuccin -d "$pkgdir/usr/share/themes"
  ./install.sh -t all -s compact --tweaks catppuccin -d "$pkgdir/usr/share/themes"
}

```

It works when using the AUR package. Can you guys please check? Thanks!

**Comment by xiota** [comment]
What is the problem?
```
$ pacman -Ss colloid-catppuccin
chaotic-aur/colloid-catppuccin-gtk-theme-git 2024.06.18.r20.g8889f15-1
    Gtk Catppuccin theme for Linux
```

**Comment by tio-trom** [comment]
colloid-gtk-theme-git should install all flavors including catppuccin. From what I see it installs all but catppuccin.

**Comment by xiota** [comment]
Will trigger rebuild.  Will take a moment.  Split packages are troublesome.

**Comment by xiota** [comment]
Package has been rebuilt.  Let me know if it works as expected.  Also, in future, please provide more info so I know what to check.

**Comment by tio-trom** [comment]
Ok I just checked. Didin't seem work:

```
Installing colloid-gtk-theme-git (2024.06.18.r20.g8889f15-1.1)...

To force Libadwaita applications to use the gtk-4.0 theme,
symlink the gtk-4.0 theme to config folder
(replace Colloid-Dark with chosen theme variant):

mkdir -p ~/.config/gtk-4.0/
ln -sf /usr/share/themes/Colloid-Dark/gtk-4.0/{assets,gtk.css,gtk-dark.css} ~/.config/gtk-4.0/

Install Firefox theme - copy or symlink from /usr/share/doc/colloid-gtk-theme/firefox/:
https://github.com/vinceliuice/Colloid-gtk-theme/tree/main/src/other/firefox#installation

Installing colloid-dracula-gtk-theme-git (2024.06.18.r20.g8889f15-1.1)...

To force Libadwaita applications to use the gtk-4.0 theme,
symlink the gtk-4.0 theme to config folder
(replace Colloid-Dark with chosen theme variant):

mkdir -p ~/.config/gtk-4.0/
ln -sf /usr/share/themes/Colloid-Dark/gtk-4.0/{assets,gtk.css,gtk-dark.css} ~/.config/gtk-4.0/

Install Firefox theme - copy or symlink from /usr/share/doc/colloid-gtk-theme/firefox/:
https://github.com/vinceliuice/Colloid-gtk-theme/tree/main/src/other/firefox#installation

Installing colloid-gruvbox-gtk-theme-git (2024.06.18.r20.g8889f15-1.1)...

To force Libadwaita applications to use the gtk-4.0 theme,
symlink the gtk-4.0 theme to config folder
(replace Colloid-Dark with chosen theme variant):

mkdir -p ~/.config/gtk-4.0/
ln -sf /usr/share/themes/Colloid-Dark/gtk-4.0/{assets,gtk.css,gtk-dark.css} ~/.config/gtk-4.0/

Install Firefox theme - copy or symlink from /usr/share/doc/colloid-gtk-theme/firefox/:
https://github.com/vinceliuice/Colloid-gtk-theme/tree/main/src/other/firefox#installation

Installing colloid-nord-gtk-theme-git (2024.06.18.r20.g8889f15-1.1)...

To force Libadwaita applications to use the gtk-4.0 theme,
symlink the gtk-4.0 theme to config folder
(replace Colloid-Dark with chosen theme variant):

mkdir -p ~/.config/gtk-4.0/
ln -sf /usr/share/themes/Colloid-Dark/gtk-4.0/{assets,gtk.css,gtk-dark.css} ~/.config/gtk-4.0/

Install Firefox theme - copy or symlink from /usr/share/doc/colloid-gtk-theme/firefox/:
https://github.com/vinceliuice/Colloid-gtk-theme/tree/main/src/other/firefox#installation

Installing colloid-everforest-gtk-theme-git (2024.06.18.r20.g8889f15-1.1)...

To force Libadwaita applications to use the gtk-4.0 theme,
symlink the gtk-4.0 theme to config folder
(replace Colloid-Dark with chosen theme variant):

mkdir -p ~/.config/gtk-4.0/
ln -sf /usr/share/themes/Colloid-Dark/gtk-4.0/{assets,gtk.css,gtk-dark.css} ~/.config/gtk-4.0/

Install Firefox theme - copy or symlink from /usr/share/doc/colloid-gtk-theme/firefox/:
https://github.com/vinceliuice/Colloid-gtk-theme/tree/main/src/other/firefox#installation
```

**Comment by xiota** [comment]
Strange.  I have no idea.

**Comment by xiota** [comment]
Try packages here to see if there is any difference: http://builds.garudalinux.org/chaotic-v4/x86_64/#colloid

**Comment by tio-trom** [comment]
Builds just fine for me from AUR - see the logs https://paste.trom.tf/ebovurigeb.php - so the https://aur.archlinux.org/packages/colloid-gtk-theme-git package should build all of them.

**Comment by xiota** [comment]
The output you pasted is informational.  It is part of the package.  https://aur.archlinux.org/cgit/aur.git/tree/colloid-gtk-theme.install?h=colloid-gtk-theme-git

**Comment by tio-trom** [comment]
This is not a big deal since chaotic already has the catpouccin version somehow, but it is weird why it does not build all variants..... the PKGBUILD clearly shows that catppuccin should be installed.

> The output you pasted is informational. It is part of the package. https://aur.archlinux.org/cgit/aur.git/tree/colloid-gtk-theme.install?h=colloid-gtk-theme-git

Yes but to show you that the AUR builds all versions.

**Comment by xiota** [comment]
As far as I can tell, the variants are available: https://builds.garudalinux.org/repos/chaotic-aur/x86_64/#colloid

**Comment by tio-trom** [comment]
Yes but i anyone installs the `colloid-gtk-theme-git` from AUR they may expect for all variants to be installed. And the `catppuccin` is not. And that's a bit odd and for me it was confusing at first because I could not find that variant and I almost left  a comment on the AUR package page :P - would be cool if this would be fixed somehow. Maybe you are building from a cached pkgbuild? The catppuccin was added to the pkgfile on 2024-06-19 https://aur.archlinux.org/cgit/aur.git/log/?h=colloid-gtk-theme-git

**Comment by xiota** [comment]
The builder downloads fresh pkgbuild.  as far as i can tell, there is no.metapackage in that pkgbuild to install all the themes.

**Comment by tio-trom** [comment]
There must be something there since the original AUR package works as intended :P - no biggie, maybe someone can figure this at some point.

**Comment by Technetium1** [comment]
@tio-trom if there's different behavior here, it's almost certainly from your AUR helper. This is working as expected.

**Comment by tio-trom** [comment]
Ah yes I got totally confused. Damn sorry for that. We are working on a theme switcher based on this theme and I totally misunderstood how the Chaotic AUR builds these sort of AUR packages and how we built the theme switcher. Sorry to drag you all into this, it was my own created confusion.

**Comment by tio-trom** [comment]
Ok here's one more issue :D - I hope I am not wrong, but a few hours ago the AUR maintainer pushed a wring [commit](https://aur.archlinux.org/pkgbase/colloid-gtk-theme-git#comment-987052) and basically that deleted all non-compact colloid themes. The update went to the chaotic aur and messed up everything. He then fixed it and I see the commit should be 2024.06.18.r21.g482c350, same as your chaotic versions https://builds.garudalinux.org/chaotic-v4/x86_64/#colloid however these packages contain the same error, thus only the compact themes are present

I built the AUR package locally and it builds with all variants. Maybe you have to trigger a rebuild?

**Comment by xiota** [comment]
Bumped in https://github.com/chaotic-aur/interfere/commit/bdce3a5630646e0fc43f0bd842d6fc2920d2df58

**Comment by tio-trom** [comment]
Great! All working now. Thanks!
