### ISSUE TITLE
[Request] citra-git

### ISSUE THREAD

**Issue by jSQrD-dev** [chaotic-aur/packages#3204]
### Package:

https://aur.archlinux.org/packages/citra
https://aur.archlinux.org/packages/citra-git

### Purpose:

An experimental open-source Nintendo 3DS emulator and debugger

### Benefits:

Move from the dead repo (and packages) to an actively maintained one.
https://github.com/PabloMK7/citra

### Building:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=citra-git 
makepkg

### Copyright:

GPL-2.0  https://github.com/PabloMK7/citra?tab=GPL-2.0-1-ov-file#readme

### Expected Interest:

Many

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

### More information:

Pretty much just update citra-nightly-git, citra-canary-git to the current repo.
Don't know if this should have been a rebuild or not.

**Comment by xiota** [comment]
Will review new packages.  New issue is okay.

**Comment by xiota** [comment]
Adding `citra-git` to v3 as-is.  The old packages are also still working.

Some potential/minor issues that may warrant interfere on v4.

**Comment by xiota** [comment]
Dropping `citra-git` because deleted from AUR and upstream development discontinued.  `mandarine-git` is already in repo. Metrics:

* citra-git 86
* mandarine-git 32

**Comment by xiota** [comment]
Dropped `mandarine-git` because development stagnant.  Metrics 79.
