### ISSUE TITLE
[Bug] PCSX2-git arguments not being passed through

### ISSUE THREAD

**Issue by SeongGino** [chaotic-aur/packages#3207]
### Packages:

https://aur.archlinux.org/packages/pcsx2-git

### Latest chaotic version

1.7.5941.r0.g56f32ff

### What happens?

Launch arguments (e.g. `-help`, `-nogui`, or anything else) aren't being passed through to `/opt/pcsx2/pcsx2-qt` at all, and is launched as if no args were present.

### What is expected to happen?

Command line arguments should be respected and react accordingly.

### More information

The issue seems to be in the `/usr/bin/pcsx2` wrapper:
```
#!/usr/bin/env sh
exec /opt/pcsx2/pcsx2-qt ""
```

Adding `$@` inside the quotations resolves this problem (and is what the original AUR attached script runner does).

**Comment by xiota** [comment]
`chaotic-aur/pcsx2-git` is built from `aur/pcsx2-avx-git`.  There was a typo that has been fixed.
