### ISSUE TITLE
[Bug] python-humblewx - invalid or corrupted package (checksum)

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#3208]
### Packages:

https://aur.archlinux.org/packages/python-humblewx

### Latest chaotic version

latest

### What happens?

When the user installs the package (that is not in the pacman cache), it gets:
```
resolving dependencies...
looking for conflicting packages...

Packages (1) python-humblewx-0.2.2-1.4

Total Installed Size:  0.03 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                      [################################################] 100%
(1/1) checking package integrity                                                    [################################################] 100%
:: File /var/cache/pacman/pkg/python-humblewx-0.2.2-1.4-any.pkg.tar.zst is corrupted (invalid or corrupted package (checksum)).
Do you want to delete it? [Y/n] 
error: failed to commit transaction (invalid or corrupted package (checksum))
Errors occurred, no packages were upgraded.
```

### What is expected to happen?

Install successful.

**Comment by xiota** [comment]
I've bumped and rebuilt.  Usually when this happens, allow the prompt to delete the file and try again.  Report if there are still errors on subsequent attempts.

**Comment by Technetium1** [comment]
`pacman -Sw --debug python-humblewx` showed that the R2 was at least giving the correct file.

**Comment by D3vil0p3r** [comment]
> `pacman -Sw --debug python-humblewx` showed that the R2 was at least giving the correct file.

After @xiota intervention, it worked correctly.

**Comment by xiota** [comment]
I rebuilt because I found other files that needed to be bumped.  Now might be a good time to run `pacman -Sc`.  (double-`c` clears entire pacman cache.  single-`c` deletes unreferenced files, subject to settings in `pacman.conf`.)  Also, check `pacman -Qqm` for obsolete packages and sync configs with `.pacnew` files.
