### ISSUE TITLE
[Rebuild] gnome-shell-extension-pop-shell-git

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#3209]
### Packages:

https://aur.archlinux.org/packages/gnome-shell-extension-pop-shell-git

### Latest chaotic version

1.2.0.r301.g9a30c5b-1.1

### Reason for rebuild

The Chaotic AUR package version is old than the current one in AUR. It is needed to update it as:

1.2.0.r301.g9a30c5b-1.1 -> latest commit

in order to have the compatibility with GNOME 46.

**Comment by xiota** [comment]
Upstream dev changes default branch to track Ubuntu releases.  PKGBUILD needa workaround in `prepare()` to detect the new branch and force checkout.

Have commented on AUR page to notify maintainer.  Will wait before considering interfere.

**Comment by xiota** [comment]
Should be fixed now.

```
$ pacman -Si gnome-shell-extension-pop-shell-git | grep -E '(Repo|Name|Version|Date)'
Repository      : chaotic-aur
Name            : gnome-shell-extension-pop-shell-git
Version         : 1.2.0.r305.gcfa0c55-1
Build Date      : Sun 30 Jun 2024 07:15:44 PM UTC
```
