### ISSUE TITLE
[Rebuild] sunshine

### ISSUE THREAD

**Issue by Pyro57000** [chaotic-aur/packages#3210]
### Packages:

https://aur.archlinux.org/packages/sunshine

### Latest chaotic version

0.23.1-1.1

### Reason for rebuild

Broken, needs recompiled with Arch's new libminiupnpc.so.17 file

sunshine: error while loading shared libraries: libminiupnpc.so.17: cannot open shared object file: No such file or directory

### Logs

no logs, but the following error message

sunshine: error while loading shared libraries: libminiupnpc.so.17: cannot open shared object file: No such file or directory

### Builds?

makepkg -fsi noted from https://github.com/LizardByte/Sunshine/discussions/1676

**Comment by Technetium1** [comment]
Bumped in https://github.com/chaotic-aur/interfere/commit/c0a336c6f9ccde2a13b854d2599724155860e7f8
Build fails: [sunshine.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/sunshine.log)

**Comment by Technetium1** [comment]
Should be fixed by https://github.com/LizardByte/Sunshine/commit/a940cdb394055139ca6a964289f414da562452e3

**Comment by Technetium1** [comment]
Added the commit linked above, and it built successfully. This package probably won't update until the next version is tagged, so this is built as a one-off.
`Finished making: sunshine 0.23.1-1.2 (Tue 02 Jul 2024 09:23:07 PM CEST)`
@Pyro57000 please test and confirm functionality.

**Comment by xiota** [comment]
Maintainers won't patch even though commit was handed to them?

**Comment by Technetium1** [comment]
Last Packager:	`KuleRucket`
> [KuleRucket](https://aur.archlinux.org/account/KuleRucket) commented on [2024-07-02 14:50 (EDT)](https://aur.archlinux.org/packages/sunshine#comment-980614)
If anyone needs a pre-release fix I suggest using sunshine-git. This package only provides tagged releases.

**Comment by xiota** [comment]
One of the maintainers is the upstream dev.  He threatened to drop support for Arch rather than fix the package.

I am leaving this package in v3, but dropping it from v4 for poor maintainership.

Closing this issue because rebuild was done.
