### ISSUE TITLE
[Rebuild] Clion is 2024.1.3 when it's 2024.1.4 in AUR

### ISSUE THREAD

**Issue by kostiya** [chaotic-aur/packages#3213]
### Packages:

https://aur.archlinux.org/packages/clion

### Latest chaotic version

1:2024.1.3-1

### Reason for rebuild

Outdated.
Other Clion related packages are up to date.

### More information

For some reason Clion version up to date on the package list on the website but not in the actual chaotic repo.

**Comment by xiota** [comment]
Cannot rebuild right now.  Server has some problems.

**Comment by kostiya** [comment]
> Cannot rebuild right now. Server has some problems.

@xiota 
Hi, are there any news?
Clion repackages as expacted on my PC when Installed from AUR.

**Comment by Technetium1** [comment]
Still issues building

**Comment by dr460nf1r3** [comment]
The issue here was that seemingly all split packages were built, while clion itself didn't. Maybe an upload failure midway.
