### ISSUE TITLE
[Rebuild] ffmpeg-obs

### ISSUE THREAD

**Issue by ToastedWookiee** [chaotic-aur/packages#3216]
### Packages:

https://aur.archlinux.org/packages/ffmpeg-obs

### Latest chaotic version

7.0.1-2

### Reason for rebuild

Broken, needs to be built against current libplacebo.so.349

**Comment by xiota** [comment]
Unfortunately, the builders are down.  So cannot update anything.

**Comment by Technetium1** [comment]
Built successfully.
