### ISSUE TITLE
Let's take the chaotic even more chaotic. 20 new packages

### ISSUE THREAD

**Issue by johnZ-cyber** [chaotic-aur/packages#322]
These packages were present before the problem with the server

```
cantata-git
eqonomize-git
hlsdl
jellyfin
lightly-qt
material-kwin-decoration-git
osdlyrics-git
plasma-systemmonitor-git
pyradio-git
qownnotes
straw-viewer-git
systray-x-git
ksnip-git
konsole-git
identity
strawberry-full-git
strawberry-git
jellyfin
neochat-git
nheko-git
```

**Comment by PedroHLC** [comment]
- [ ] cantata-git
- [ ] eqonomize-git
- [ ] hlsdl
- [ ] identity
- [ ] jellyfin
- [ ] konsole-git
- [ ] ksnip-git
- [ ] lightly-qt
- [ ] material-kwin-decoration-git
- [ ] neochat-git
- [ ] nheko-git
- [ ] osdlyrics-git
- [ ] plasma-systemmonitor-git
- [ ] pyradio-git
- [ ] qownnotes
- [ ] straw-viewer-git
- [ ] strawberry-full-git
- [ ] strawberry-git
- [ ] systray-x-git

OMG, so many -git, is your system really working?
Let's see what we can do... I'll keep track of the ones added in this checklist...

**Comment by dr460nf1r3** [comment]
material-kwin-decoration-git is not compiling (still)
eqonomize-git fails without error message (A failure occurred in package().)
nheko-git misses qtkeychain-qt5 in PKGBUILD

**Comment by johnZ-cyber** [comment]
> material-kwin-decoration-git is not compiling (still)

I have contacted the package maintainer, I hope he updates the dependencies soon

> eqonomize-git fails without error message (A failure occurred in package().)

I just did the build without problems. Maybe it's also the lack of some dependency. Could you identify which one?

> nheko-git misses qtkeychain-qt5 in PKGBUILD

I've seen it reported several times in the aur. Let's wait.

Thanks!

**Comment by PedroHLC** [comment]
> I just did the build without problems. Maybe it's also the lack of some dependency. Could you identify which one?

During package:

```
Error setting permissions on /home/main-builder/pkgwork/pkg/eqonomize-git/usr/share/icons/hicolor/64x64/apps/eqonomize.png: No such file or directory
```

**Comment by PedroHLC** [comment]
```
Cannot touch /home/main-builder/pkgwork/pkg/eqonomize-git/usr/share/icons/hicolor/64x64/apps/eqonomize.png: No such file
 or directory./usr/sbin/qmake -install qinstall /home/main-builder/pkgwork/src/eqonomize/data/64/eqz-account.png /home/m
ain-builder/pkgwork/pkg/eqonomize-git/usr/share/icons/hicolor/64x64/actions/eqz-account.png
```

It's never in the same place, seems like we have  a race-condition :horse_racing: :carousel_horse:  :horse_racing:  :horse_racing:

**Comment by PedroHLC** [comment]
> > eqonomize-git fails without error message (A failure occurred in package().)
> 
> I just did the build without problems. Maybe it's also the lack of some dependency. Could you identify which one?

It was a race-condition, not sure how we'll keep updating this one... Maybe it's a good idea to open an issue in upstream's project...

**Comment by dr460nf1r3** [comment]
All fixed & available now!

**Comment by johnZ-cyber** [comment]
thank you guys
