### ISSUE TITLE
[Rebuild] obs-studio-stable

### ISSUE THREAD

**Issue by ImperatorStorm** [chaotic-aur/packages#3223]
### Packages:

`obs-studio-stable`, no AUR package exists.

### Latest chaotic version

30.1.2-1.1

### Reason for rebuild

https://github.com/obsproject/obs-studio/releases/tag/30.2.0

`0001-obs-ffmpeg-057e884.patch` seems to have broken as well.

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/obs-studio-stable.log

**Comment by xiota** [comment]
Thanks for reporting.  Package has been updated and rebuilt.

**Comment by ImperatorStorm** [comment]
Thanks!

**Comment by hirak99** [comment]
Where is the PKGBUILD for obs-studio-stable? And in general, where can I find PKGBUILD or building processes for the Chautic Aur packages?

**Comment by Technetium1** [comment]
@hirak99 in the future after moved to v4 infrastructure, you can see https://gitlab.com/chaotic-aur/pkgbuilds/-/tree/main/obs-studio-stable?ref_type=heads
