### ISSUE TITLE
[Rebuild] dolphin-emu-git

### ISSUE THREAD

**Issue by danielah05** [chaotic-aur/packages#3224]
### Packages:

https://aur.archlinux.org/packages/dolphin-emu-git

### Latest chaotic version

2407.r39.g321c464-1

### Reason for rebuild

build on chaotic-aur crashes for some reason when loading a wii game, tried reinstalling multiple times with no fix, manually compiling the aur package does not have this issue

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/dolphin-emu-git.log

### Builds?

i just used the yay aur helper

**Comment by xiota** [comment]
I'm unable to reproduce this.  What is the error message in terminal after the crash?

**Comment by danielah05** [comment]
its just giving me a "Segmentation fault (core dumped)"
im using an nvidia gtx 980 and an intel i7-3770K
the crash does not happen on the test package, however (with vulkan) i get multiple warnings and then the game does not boot. "failed to create vulkan surface" and "failed to initialize video backend", switching to something like opengl skips the vulkan error, but the video backend error still appears

**Comment by xiota** [comment]
With the opengl video backend error, does the game still run?

Please try test package again, `2407.r68.gcc3ff34-2`, built with clang and different options.  Also added a second test package `-test2-` package, built with gcc.

**Comment by danielah05** [comment]
the game does not run with the opengl error
test 1 now just crashes again with the "Segmentation fault (core dumped)" error in the terminal (also crashes when not running through terminal)
test 2 seems to work fine! it turns out running test 2 through the terminal was opening the emulator incorrectly(?) it had a regular wayland icon n stuff instead of the dolphin icon, running it through my kde program menu it runs fine and has no backend errors or anything

so it seems like test2 solves whatever the issue was

**Comment by xiota** [comment]
`dolphin-emu-git` has been rebuilt with gcc and lto disabled (corresponding with the `-test2` package).  I would also appreciate your trying the `-test3` package, built with clang and lto disabled.

**Comment by danielah05** [comment]
-test3 has the same segmentation fault error for me

**Comment by xiota** [comment]
@danielah05 Thank you for testing.  Have switched to building this package with gcc, lto off.

Last year, switched to clang, lto on because gcc, lto on was producing segfaults.  But seems some change in clang 18 produces segfaults in some packages.

**Comment by danielah05** [comment]
glad i was able to help ^^
