### ISSUE TITLE
[Rebuild] xrdp not updated to the latest AUR version

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#3226]
### Packages:

https://aur.archlinux.org/packages/xrdp

### Latest chaotic version

0.9.21.1

### Reason for rebuild

The Chaotic version of xrdp package is 0.9.21.1 while on AUR it is 0.10.0. Why was it not automatically updated?

**Comment by D3vil0p3r** [comment]
@Technetium1 @xiota the package seems still 0.9.21.1.

**Comment by xiota** [comment]
Rebuilt.

**Comment by D3vil0p3r** [comment]
> Rebuilt.

I tried now again, but it still gives me the old version. I am testing on a new environment...

**Comment by xiota** [comment]
@dr460nf1r3 Problem with mirror?

**Comment by dr460nf1r3** [comment]
> > Rebuilt.
> 
> I tried now again, but it still gives me the old version. I am testing on a new environment...

Which mirror is it you ar using?

**Comment by D3vil0p3r** [comment]
It works. Thank you for the support.
