### ISSUE TITLE
[Rebuild] localsend-git

### ISSUE THREAD

**Issue by asdfzxcvbn** [chaotic-aur/packages#3227]
### Packages:

https://aur.archlinux.org/packages/localsend-git

### Latest chaotic version

1.14.0.r89.g1095418-1

### Reason for rebuild

outdated on v1.14.0, even v1.15.0 was released like 4 days ago and v1.15.1 was released just an hour ago and no update is available

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/localsend-git.log

**Comment by Technetium1** [comment]
@xiota need to change telemetry option [here](https://github.com/chaotic-aur/interfere/blob/1c13db4afb824092b438c458bdbb3b7264da55c9/localsend-git/PKGBUILD.append#L56) to `flutter --disable-telemetry`, I think. Not sure if there is more needed.

**Comment by xiota** [comment]
Updated and rebuilt.
