### ISSUE TITLE
[Request] borg2

### ISSUE THREAD

**Issue by RubenKelevra** [chaotic-aur/packages#3228]
### Package:

https://aur.archlinux.org/packages/borg2

### Purpose:

Borg2 is the beta version of the upcoming second major release of borg.

### Benefits:

BSD While the compilation is quite quick, the extensive test-suite slows down an installation by A LOT for users wanting to test it out. On my machine a compilation and test suite run takes `11m 59s`.

While I maintain it, I don't feel comfortable skipping the test suite, as it's done for a reason and it's kinda critical that the backup tool works right.

So I was wondering if you could add it to your repo, to make it quicker for users to install it and test it out?

Thanks for considering!

### Copyright:

BSD-3-Clause

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Package should be updated to PEP517 install method.  License string should use SPDX id, (BSD-3-Clause?).

Is there a timeline for the next release?

**Comment by RubenKelevra** [comment]
> Package should be updated to PEP517 install method. License string should use SPDX id, (BSD-3-Clause?).

2.0.0b9-2 addresses this, thanks!

> Is there a timeline for the next release?

There's no timeline for a release. The idea is to make it rock solid and probably have the tools relying on Borg adapt to the new version.

Apart from that Borg 1 and 2 are incompatible. Meaning you can upgrade but you can't use them vice versa between the server side and the client side. As there are many many old versions out there in usage, the cutoff for the old Borg 1 will be quite some time.

List of versions in the wild:

https://borgbackup.readthedocs.io/en/stable/installation.html

**Comment by xiota** [comment]
[borg2.log.gz](https://github.com/user-attachments/files/16323349/borg2.log.gz)

```
=========================== short test summary info ============================
ERROR borg/testsuite/archiver/serve_cmd.py::test_with_socket - FileNotFoundEr...
ERROR borg/testsuite/archiver/serve_cmd.py::test_socket_permissions - FileNot...
==== 1509 passed, 308 skipped, 1 deselected, 2 errors in 464.58s (0:07:44) =====
```

**Comment by RubenKelevra** [comment]
Yeah looks like the PEP517 install method doesn't work. I'll investigate later

**Comment by RubenKelevra** [comment]
Those tests just fail due to access limits inside a chroot. I skip them in 2.0.0b9-3 and reported them in https://github.com/borgbackup/borg/issues/8298

**Comment by RubenKelevra** [comment]
@xiota yeah, they moved some core features out of the main package into two dependencies, and in the process a bunch of tests started failing. I spent a couple of hours looking into it but figured it's best to wait for the next release cycle to see if they fixed it upstream, as the release cycle is short.

I give it another look.

**Comment by xiota** [comment]
Dropping because not worth the effort to keep in repo.

* Package failing check.  Passing checks is important for backup tools.
* `aur/borg2` has new maintainer, but didn't adopt all the depends, so `aur/python-borgstore` is currently orphaned.
* New depends `aur/python-borghash` doesn't build in clean chroot.
* Low usage:
    * borg2 # 12
    * python-borgstore # 14
