### ISSUE TITLE
[request] chatterino2-git

### ISSUE THREAD

**Issue by bennyhillthebest** [chaotic-aur/packages#323]
AUR: https://aur.archlinux.org/packages/chatterino2-git/
GitHub: https://github.com/Chatterino/chatterino2

Thank you very much

**Comment by thotypous** [comment]
This was added to the wrong cluster. All Qt packages must be added to garuda or kitsuna until UFSCar host system is upgraded to CentOS8, see https://bbs.archlinux.org/viewtopic.php?pid=1755257#p1755257

**Comment by thotypous** [comment]
Fixed by e7e25a315cd174cb6b5b9d5103dfe1c2ea7f7a19
