### ISSUE TITLE
[Rebuild] mesa-tkg-git new dependency added, and some upcoming build flag changes in mesa 25.0

### ISSUE THREAD

**Issue by Jelgnum** [chaotic-aur/packages#3231]
### Packages:

mesa-tkg-git: https://github.com/Frogging-Family/mesa-git.git

### Latest chaotic version

24.2.0_devel.192237.52cf610975b-1

### Reason for rebuild

New dependency was added, this has been fixed in mesa-tkg-git script with https://github.com/Frogging-Family/mesa-git/pull/44
also the build flag swrast has been decomflated to llvmpipe,softpipe with this MR https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/27607 and  swrast will be removed in mesa 25.0

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/mesa-tkg-git.log

**Comment by xiota** [comment]
Rebuilt, but the PR needs to be updated.
