### ISSUE TITLE
[Request] xiccd

### ISSUE THREAD

**Issue by securerootd** [chaotic-aur/packages#3235]
### Package:

https://aur.archlinux.org/packages/xiccd

### Purpose:

Simple bridge between colord and X
This is essential for xfce color settings to work and load color profiles

### Benefits:

This is essential for xfce color settings to work and load color profiles

### Copyright:

GPLv3
https://github.com/agalakhov/xiccd/blob/master/COPYING

### Expected Interest:

Only me

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
@securerootd Please do not copy/paste all depends from the AUR page.  List *only* the AUR-based depends.
