### ISSUE TITLE
[Rebuild] protonup-qt

### ISSUE THREAD

**Issue by securerootd** [chaotic-aur/packages#3236]
### Packages:

https://aur.archlinux.org/packages/protonup-qt

### Latest chaotic version

2.9.2-1.1

### Reason for rebuild

Broken

$ -> protonup-qt
/usr/bin/python: No module named pupgui2

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/protonup-qt.log

**Comment by xiota** [comment]
@securerootd I'm unable to replicate your issue.  `pupgui2` module is part of `protonup-qt`.

**Comment by xiota** [comment]
@securerootd Closing because unable to replicate and no evidence rebuild would be helpful.  If you are still having problems, I need more info about your system, including distro, python version, and full output of error message.
