### ISSUE TITLE
[Request] linux-xanmod-edge-x64v3

### ISSUE THREAD

**Issue by securerootd** [chaotic-aur/packages#3237]
### Package:

https://aur.archlinux.org/pkgbase/linux-xanmod-edge

### Benefits:

Latest and greatest Xanmod kernel

### Copyright:

GPLv2

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Would there be any problem adding this as a v3 package only?  (See wikipedia [X86-64#Microarchitecture_levels](https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels)

**Comment by xiota** [comment]
Planning to reorganize linux-xanmod packages.

* linux-xanmod-edge-v3
* linux-xanmod-v2
* linux-xanmod-lts
* linux-xanmod-rt

May change v2/v3 suffices to something more descriptive, like x64v2/x64v3.
