### ISSUE TITLE
[Request] linux-xanmod-edge-headers

### ISSUE THREAD

**Issue by securerootd** [chaotic-aur/packages#3238]
### Package:

https://aur.archlinux.org/packages/linux-xanmod-edge-headers

Dependencies (10)

   [ pahole](https://archlinux.org/packages/?q=pahole) ([pahole-git](https://aur.archlinux.org/packages/pahole-git)AUR)
   [ bc](https://archlinux.org/packages/?q=bc) ([bc-gh](https://aur.archlinux.org/packages/bc-gh)AUR) (make)
   [ cpio](https://archlinux.org/packages/?q=cpio) ([cpio-git](https://aur.archlinux.org/packages/cpio-git)AUR) (make)
   [ gettext](https://archlinux.org/packages/?q=gettext) ([gettext-git](https://aur.archlinux.org/packages/gettext-git)AUR) (make)
   [ libelf](https://archlinux.org/packages/?q=libelf) ([elfutils-git](https://aur.archlinux.org/packages/elfutils-git)AUR) (make)
   [ pahole](https://archlinux.org/packages/?q=pahole) ([pahole-git](https://aur.archlinux.org/packages/pahole-git)AUR) (make)
   [ perl](https://archlinux.org/packages/?q=perl) ([perl-git](https://aur.archlinux.org/packages/perl-git)AUR) (make)
   [ python](https://archlinux.org/packages/?q=python) ([python37](https://aur.archlinux.org/packages/python37)AUR, [python311](https://aur.archlinux.org/packages/python311)AUR, [python310](https://aur.archlinux.org/packages/python310)AUR) (make)
   [ tar](https://archlinux.org/packages/?q=tar) ([tar-git](https://aur.archlinux.org/packages/tar-git)AUR, [busybox-coreutils](https://aur.archlinux.org/packages/busybox-coreutils)AUR) (make)
   [ xz](https://archlinux.org/packages/?q=xz) ([xz-git](https://aur.archlinux.org/packages/xz-git)AUR) (make)

### Purpose:

Headers and scripts for building modules for the Linux Xanmod - Rolling Release [EDGE] kernel

### Benefits:

Headers and scripts for building modules for the Linux Xanmod - Rolling Release [EDGE] kernel

### Copyright:

GPLv2

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Duplicate #3237
