### ISSUE TITLE
[Request] grub-hook

### ISSUE THREAD

**Issue by securerootd** [chaotic-aur/packages#3239]
### Package:

https://aur.archlinux.org/packages/grub-hook

### Purpose:

Pacman hook to update GRUB after a kernel update

### Benefits:

Pacman hook to update GRUB after a kernel update. Automatic grub update after a kernel install/remove/update

### Copyright:

GPL

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Regenerating grub config after every kernel update it not needed on Arch because the name of the image files do not change.

**Comment by xiota** [comment]
Rejecting because this is not really useful on Arch.
