### ISSUE TITLE
Request to restore auracle-git

### ISSUE THREAD

**Issue by robson-66** [chaotic-aur/packages#324]
```
alsi
auracle-git
compiz-git
crow-translate-git
dolphin-emu-git
emerald-gtk3
fsearch-git
libfido2-git
megasync-git
meteo-gtk
pa-applet-git
pacmanlogviewer-git
palemoon-bin
pamac-classic
pyradio-git
trizen-git
xfce4-panel-compiz
zsh-theme-powerlevel9k-git
```

**Comment by PedroHLC** [comment]
- [ ] alsi
- [ ] auracle-git
- [ ] compiz-git
- [ ] crow-translate-git
- [ ] dolphin-emu-git
- [ ] emerald-gtk3
- [ ] fsearch-git
- [ ] libfido2-git
- [ ] megasync-git
- [ ] meteo-gtk
- [ ] pa-applet-git
- [ ] pacmanlogviewer-git
- [ ] palemoon-bin
- [ ] pamac-classic
- [ ] pyradio-git
- [ ] trizen-git
- [ ] xfce4-panel-compiz
- [ ] zsh-theme-powerlevel9k-git


Let's see what we can do, I'll keep track of the ones added in this checklist!
Do note that non-git packages will be added first...

**Comment by robson-66** [comment]
Maybe instead of `compiz-git` you will add `compiz`.

**Comment by dr460nf1r3** [comment]
auracle-git misses pod2man dep, the rest is added :)

**Comment by robson-66** [comment]
At my place auracle-git builds without any problems.

**Comment by PedroHLC** [comment]
> At my place `auracle-git` builds without any problems.

We build at clean containers, this means that only `base-devel` is installed besides what is listed in PKGBUILD's `depends`, `makedepends` and `checkdepends`.

**Comment by xiota** [comment]
Dropped `pamac-classic` because not compatible with current libalpm.

**Comment by xiota** [comment]
Dropping `compiz-git` because no difference from `compiz`.

**Comment by xiota** [comment]
Dropping `crow-translate-git` because not yet updated for Qt6.  Metrics 34.

**Comment by xiota** [comment]
Dropping following packages because minimal difference from stable package.  Metrics:

* pacmanlogviewer-git # 11
* trizen-git # 15

**Comment by xiota** [comment]
Dropping `emerald-gtk3` because orphaned and reported to need patch to build.  Metrics 24.
