### ISSUE TITLE
[Request] pandoc-bin

### ISSUE THREAD

**Issue by coxackie** [chaotic-aur/packages#3245]
### Package:

[pandoc-bin](https://aur.archlinux.org/packages/pandoc-bin)

### Purpose:

Pandoc without the haskell dependencies of the arch package.

### Benefits:

Avoidance of haskell dependencies

### Copyright:

GPL-2.0-or-later

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

308 votes, and popularity at 2.38 at the moment of writing.

**Comment by Technetium1** [comment]
It's back. Not sure why it was dropped. I did add it before in https://github.com/chaotic-aur/packages/commit/694ced2cdd0961c000677374dcea37ee4d778dfc

**Comment by xiota** [comment]
W dropped in 50ae1fce0835d0d88baa3ac93307cde80610d385 when `pandoc` was added to `community`/`extra`.
