### ISSUE TITLE
[Bug] Missing kvantum-theme-nordic-git required by Garuda Sway

### ISSUE THREAD

**Issue by REmerald** [chaotic-aur/packages#3249]
### Packages:

https://web.archive.org/web/20231202231211/https://aur.archlinux.org/pkgbase/nordic-kde-git
https://web.archive.org/web/20240324020326/https://aur.archlinux.org/packages/kvantum-theme-nordic-git

### Latest chaotic version

`2.2.0.r115.g5c53654-1`

### What happens?

[`kvantum-theme-nordic-git` is required by the Garuda Sway Edition](https://gitlab.com/garuda-linux/tools/iso-profiles/-/blob/68012a106dd416efa6c59375d898162cc4933162/garuda/sway/Packages-Desktop#L111), but was removed in 76a14cd.

### What is expected to happen?

Probably someone needs to recreate the package. And other lost packages as well. (`plasma5-themes-nordic-git` and `sddm-theme-nordic-git`)

### Logs

Missing

### More information

[The AUR maintainer seems inactive (has a few outdated packages).](https://aur.archlinux.org/packages?K=alevalv&SeB=m)

[The last package version is up-to-date for now.](https://github.com/EliverLara/Nordic/commits/master/)

**Comment by dr460nf1r3** [comment]
I have notified the maintainer, and they have been very quick to fix it up. We now use another Kvantum theme instead: https://gitlab.com/garuda-linux/themes-and-settings/settings/garuda-sway-settings/-/commit/79c265027f25b5ad685fa72d06d39594ba300fc3
