### ISSUE TITLE
[Request] git-extras

### ISSUE THREAD

**Issue by guiltiest-gear** [chaotic-aur/packages#3250]
### Package:

https://aur.archlinux.org/packages/git-extras

### Purpose:

Provides several very useful utilities for using git, such as a REPL, counting commits, repo summaries, etc.

### Benefits:

Git users, especially those of the power variety, would find many useful tools in the package to help simplify their workflow.

### Copyright:

MIT

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by guiltiest-gear** [comment]
The package no longer seems to be present in the repos, seemingly dropped out of nowhere, which is a little odd to me. I can't seem to find any reference to its removal either, so maybe it was an accident? Thought I'd bring it up on the request issue I created.

**Comment by Technetium1** [comment]
@xiota any build issues?

**Comment by xiota** [comment]
Added in 29d2cb39b44404673759c18875a3b3c3fee74d3f.  Looks like I didn't see when this package was added, so didn't sync it with v4.
