### ISSUE TITLE
[Rebuild] cava-git

### ISSUE THREAD

**Issue by EliteAMDGamer** [chaotic-aur/packages#3251]
### Packages:

https://aur.archlinux.org/packages/cava-git

### Latest chaotic version

r955.3f6e931-1

### Reason for rebuild

installing pipewire-pulse (1:1.2.2-1) breaks dependency 'pulseaudio' required by cava-git

### More information

NoiseTorch also suffers from this same bug.

**Comment by xiota** [comment]
Bumped in https://github.com/chaotic-aur/interfere/commit/d8fb46338ace8f999ed0e0183764ef8af6b455c2
