### ISSUE TITLE
[Rebuild] prismlauncher-git

### ISSUE THREAD

**Issue by Ty3r0X** [chaotic-aur/packages#3252]
### Packages:

https://aur.archlinux.org/packages/prismlauncher-git

### Latest chaotic version

`8.0.r917.gb77dc47c6c-1`

### Reason for rebuild

Updated dynamic libs, not launching:
```
prismlauncher: error while loading shared libraries: libcmark.so.0.31.0: cannot open shared object file: No such file or directory
```
System currently has `cmark-0.31.1-1`

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/prismlauncher-git.log

**Comment by xiota** [comment]
Bumped in https://github.com/chaotic-aur/interfere/commit/293db7b8cdc6dcba54d03940e8d11bf4463b84f7
