### ISSUE TITLE
[Request] oblivion-desktop

### ISSUE THREAD

**Issue by Weirdo1312** [chaotic-aur/packages#3253]
### Package:

https://aur.archlinux.org/packages/oblivion-desktop

### Purpose:

Internet censorship circumvention tool

### Benefits:

It has a much easier time bypassing great firewall of iran than other tools

### Copyright:

Custom License
https://github.com/bepass-org/oblivion-desktop/blob/main/LICENSE.md

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Package uses `extra/electron27`.  Upstream specifies "electron": "^26.2.1".

**Comment by Pakrohk** [comment]
I think the new version has changed slightly.

**Comment by xiota** [comment]
Electron version requirement has not been changed.  Even if it were, license states, "You are prohibited from... distributing the software..."

**Comment by ircfspace** [comment]
Hi
Relevant details: https://github.com/bepass-org/oblivion-desktop/issues/563#issuecomment-2381588165

**Comment by xiota** [comment]
Upstream updated to Electron 32 and adjusted license to allow redistribution of binaries.  Now have to wait for AUR package to be updated.

**Comment by Technetium1** [comment]
Updated, needs tested https://aur.archlinux.org/cgit/aur.git/commit/?h=oblivion-desktop&id=eeda36fbe4f0a62394f5005e207b4b214c20e020

**Comment by xiota** [comment]
Packaging looks okay, and it builds.  Will not test further.  Will add shortly.

**Comment by xiota** [comment]
Fails to build.  Possibly related to npm, electron, etc version mismatch.  Will watch for a little while, but most likely will eventually drop because this type of issue frequently recurs and license doesn't allow for basic changes that would be needed to fix.  Metrics 64.

**Comment by ircfspace** [comment]
If the changes are general and do not disrupt the development process in the [main repository](https://github.com/bepass-org/oblivion-desktop), why not submit a PR to apply them?
@xiota

**Comment by xiota** [comment]
Package was updated, and now builds successfully.  Will wait until next time to drop.  Metrics 21.

> why not submit a PR to apply them?

1. I'm not going to bother with proprietary junk.  There are plenty of open-source projects I can look at.
2. To submit a PR requires cloning, *modifying*, and building.  License technically doesn't allow it.  But even if it did, see above point.
