### ISSUE TITLE
[Request] satty

### ISSUE THREAD

**Issue by Heyian** [chaotic-aur/packages#3255]
### Package:

https://aur.archlinux.org/packages/satty

### Purpose:

A screenshot annotation tool, lightweight and very function on Wayland. Still need to pipe the screenshot to it like other annotation tools.

### Benefits:

- very simple and easy to understand toolset (like Swappy)
- fullscreen annotation mode and post shot cropping (like Flameshot)
- extremely smooth rendering thanks to HW acceleration (OpenGL)
- working on wlroots based compositors (Sway, Hyprland, River, ...)
- minimal, modern looking UI, thanks to GTK and Adwaita

### Copyright:

MPL-2.0

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Maintainer is a PM, so there is a high probability it will eventually be added to the `extra` repo.

**Comment by xiota** [comment]
Eventually is now.
