### ISSUE TITLE
[Request] phantomjs-git

### ISSUE THREAD

**Issue by REmerald** [chaotic-aur/packages#3256]
### Package:

https://aur.archlinux.org/pkgbase/phantomjs-git

### Purpose:

Optional dependency of `yt-dlp`, needed for downloading some videos: `Native nsig extraction failed: Trying with PhantomJS`.

### Benefits:

Only package with a maintainer.

### Building:

mkarchroot chroot/root base-devel
makechrootpkg -c -r ~/chroot/ -I /var/cache/pacman/pkg/qt5-webkit-5.212.0alpha4-26-x86_64.pkg.tar.zst

### Copyright:

BSD

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

May also need to add `qt5-webkit`, I used the package from `archlinuxcn`.

**Comment by xiota** [comment]
Won't add because of `qt5-webkit` / Qt5.  Related #3157

**Comment by Technetium1** [comment]
Wait until upstream moves away from Phantom, it's been entirely dead for a long while https://github.com/ariya/phantomjs/issues/15344
