### ISSUE TITLE
[request] powershell

### ISSUE THREAD

**Issue by FaithLV** [chaotic-aur/packages#326]
~The current `powershell` package in repository is `7.0.3`.~
~Latest stable in AUR and upstream is `7.1.0`, would it be possible for this package to be updated?~

AUR
https://aur.archlinux.org/packages/powershell/

Upstream
https://github.com/PowerShell/PowerShell

**Comment by PedroHLC** [comment]
We haven't readded powershell yet, are you sure your mirrorlist and pacman's database are updated?

**Comment by FaithLV** [comment]
That's strange. I reinstalled my system a week ago and it's still there.
Here's my mirror list, I guess that package is still in one of those.

```
[chaotic-aur]
Server = http://chaotic.bangl.de/$repo/$arch
Server = https://chaotic.tn.dedyn.io/$arch
Server = https://builds.garudalinux.org/repos/$repo/$arch
Server = https://repo.kitsuna.net/$arch
Server = https://repo.jkanetwork.com/repo/$repo/$arch
```

**Comment by PedroHLC** [comment]
`Server = http://chaotic.bangl.de/$repo/$arch`
Is outdated (not syncing anymore), I recommend installing and using https://aur.archlinux.org/packages/chaotic-mirrorlist instead

**Comment by PedroHLC** [comment]
Closed in
https://github.com/chaotic-aur/packages/commit/4d172b24248e4d16408317d55ebe3fe439cd41dc

**Comment by xiota** [comment]
`aur/powershell` is currently failing to build and out of date.  `powershell-bin` is in chaotic aur and has more features, per the request.  Should the non-bin package be dropped?

Metrics:
* `powershell` 342
* `powershell-bin` 1035

**Comment by Technetium1** [comment]
I feel like it should be dropped in favor of `powershell-bin` as long as there is no feature parity. Their CI is gross, but it works. https://github.com/PowerShell/PowerShell/tree/master/.pipelines/templates
