### ISSUE TITLE
[Request] virtualbox-bin

### ISSUE THREAD

**Issue by Eroldin** [chaotic-aur/packages#3260]
### Package:

https://aur.archlinux.org/packages/virtualbox-bin

### Purpose:

This is one of the most used virtualization software programs in the world. 

### Benefits:

Arch Linux does provide the OSE version of this package. However, that package is known for having it's issues. The Oracle Binary file is much more stable.

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
There is no longer any separate OSE version.  Oracle binaries are built from the same sources.

What specific problems are you having with `extra/virtualbox`?

**Comment by Eroldin** [comment]
Sudden out-of-memory errors occur when starting a virtual machine when multiple machines are running. This happens even if I have more than enough free RAM available.

**Comment by xiota** [comment]
Rejecting because -bin packages are usually straightforward for users to build themselves.

I'd also recommend working with upstream to find and fix the cause.  If the problem is a packaging issue, Arch maintainers should be notified.
