### ISSUE TITLE
[Request] virtualbox-bin-guest-iso

### ISSUE THREAD

**Issue by Eroldin** [chaotic-aur/packages#3261]
### Package:

https://aur.archlinux.org/packages/virtualbox-bin-guest-iso

### Purpose:

This is the oracle binary addition for VirtualBox (requested in issue #3260)

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Package already available as `extra/virtualbox-guest-iso`
