### ISSUE TITLE
[Request] code-translucent

### ISSUE THREAD

**Issue by nautrw** [chaotic-aur/packages#3265]
### Package:

https://aur.archlinux.org/packages/code-translucent

### Purpose:

Visual Studio Code, but with patches that improve the user experience, like not needing to install Electron.

### Copyright:

MIT

### Expected Interest:

Few

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
This is probably not worth adding because the only benefit is a visual effect.  There are already too many vs-code-related packages.  Would be good to remove some.  Metrics:

* visual-studio-code-bin 12952
* vscodium 4142
* vscodium-electron 105
* vscodium-git 105
* vscodium-marketplace 113

**Comment by Technetium1** [comment]
I also agree that this wouldn't be a great addition for such a small change. This is not a lightweight package.
If any of those other packages should be dropped, it's probably `vscodium-electron`.
