### ISSUE TITLE
[Rebuild] python-syncedlyrics

### ISSUE THREAD

**Issue by CheesyChocolate** [chaotic-aur/packages#3267]
### Packages:

https://aur.archlinux.org/packages/python-syncedlyrics

### Latest chaotic version

`0.10.1-1`

### Reason for rebuild

Outdated

0.10.1-1 -> 1.0.1-1

outdated package break functionality of package `chaotic-aur/spotdl 4.2.5-6`

**Comment by Technetium1** [comment]
@xiota have I missed something obvious here??

**Comment by xiota** [comment]
Bash functions can't have empty body.  Here's a new interfere to pass check: https://github.com/chaotic-aur/interfere/commit/16bd99b3eded1bc73f31d8aee9ef164bd95166bf
```bash
if [ -n "$(declare -f check)" ]; then
  eval _orig_"$(declare -f check)"
  check() {
    _orig_check || true
  }
fi
```
