### ISSUE TITLE
[Request] clipboard-manager-git

### ISSUE THREAD

**Issue by fabianski7** [chaotic-aur/packages#3268]
### Package:

https://aur.archlinux.org/packages/clipboard-manager-git

### Purpose:

It's the only clipboard available for cosmic

### Copyright:

GPL-3.0

### Expected Interest:

Some

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
Should possibly be added to https://github.com/chaotic-aur/packages/issues/2397

**Comment by xiota** [comment]
`cosmic-session-git` already has over 20 related packages.  Might be easier to keep this separate?
