### ISSUE TITLE
[Request] envision-xr-git & wlx-overlay-s-git

### ISSUE THREAD

**Issue by ShayBox** [chaotic-aur/packages#3269]
### Package:

https://aur.archlinux.org/packages/envision-xr-git
https://aur.archlinux.org/packages/wlx-overlay-s-git

### Purpose:

These are for Linux VR, but they often get updated and take a long time to compile.

### Benefits:

This is the only option, SteamVR doesn't really work because of the lack of updates for Linux in years.

### Building:

makepkg

### Copyright:

GPL3

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

The Linux VR Adventures community would use this, re-compiling these large Rust projects is a chore.

**Comment by Technetium1** [comment]
Can you please elaborate more on the use case? [This was previously requested via Garuda Forums](https://forum.garudalinux.org/t/chaotic-aur-packages-requests-recompilation-reports/26/874?u=technetium), I asked for more information, then never got a follow-up.

I see you're also requesting https://github.com/galister/wlx-overlay-s - are there other directly related packages to be added as well?

**Comment by Technetium1** [comment]
https://lvra.gitlab.io/docs/fossvr/

**Comment by ShayBox** [comment]
You could add wivrn, monado, and open composite, but envision xr is a tool to compile and run all the needed tools and libraries in profiles, so afaik only the two packages I listed are needed.

**Comment by ShayBox** [comment]
I have a 1950x 16c 32t 4.0GHz CPU with 32GiB 3200MHz RAM and it takes 2 minutes to compile `envision-xr-git` and 5 minutes to compile `wlx-overlay-s-git` every day, combined this takes 7 minutes daily on good hardware.

**Comment by otter501** [comment]
Hello, just wanted to say that I also want the wlx-overlay-s-git package, please add

**Comment by xiota** [comment]
v4 commits: a55e9d041d9bbeb7356bb51025cfab8fcc556ea7, 83ca726a978d50e54d5d0a35dc6bcfe0ee74bf34

**Comment by xiota** [comment]
Switching `aur/wlx-overlay-s-git` to `aur/wayvr-git` because upstream rebranded.  Appears to be same AUR maintainer.  Metrics 475.
