### ISSUE TITLE
[Request] Multiple Packages

### ISSUE THREAD

**Issue by EmptyVisual** [chaotic-aur/packages#327]
ntfs3-dkms - https://aur.archlinux.org/packages/ntfs3-dkms/ (usually weekly updates - open source ntfs kernel driver which will hopefully replace the current ntfs driver in tree. developed by paragon.)
ananicy - https://aur.archlinux.org/packages/ananicy/
boston-icon-theme - http://aur.archlinux.org/packages/boston-icon-theme-git
megasync-git - http://aur.archlinux.org/packages/megasync-git
microsoft-edge-dev-bin - http://aur.archlinux.org/packages/microsoft-edge-dev-bin
nohang-git - https://aur.archlinux.org/packages/nohang-git/
timeshift-bin - http://aur.archlinux.org/packages/timeshift-bin
visual-studio-code-bin - http://aur.archlinux.org/packages/visual-studio-code-bin
xow-git - http://aur.archlinux.org/packages/xow-git
xpadneo-dkms-git - https://aur.archlinux.org/packages/xpadneo-dkms-git/

**Comment by EmptyVisual** [comment]
Hi @PedroHLC, currently still missing from what I can see,
ntfs3-dkms (really would appreciate this)
boston-icon-theme (not overly necessary)
megasync-git (please)
visual-studio-code-bin (currently we have the insiders build but need the stable build) (please)

**Comment by PedroHLC** [comment]
sorry, wrong title in the commit

**Comment by dr460nf1r3** [comment]
ntfs3-dkms will be built by the Garuda cluster, the same for visual-studio-code-bin. Both are available now :)

**Comment by xiota** [comment]
Dropping `ntfs3-dkms` because it's now included with kernel.
