### ISSUE TITLE
[Rebuild] linux-amd

### ISSUE THREAD

**Issue by scruffidog** [chaotic-aur/packages#3270]
### Packages:

https://aur.archlinux.org/packages/linux-amd

### Latest chaotic version

6.8.v.8-2

### Reason for rebuild

Outdated. 
chaotic => 6.8.v.8-2
current => 6.10.v.5-1

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-amd.log

### More information

not sure why there's a disconnect between AUR and the builds. Possible due the former orphaned status ? It has picked up a new maintainer. But it is part of the build that generates the header (linux-amd-headers), which successfully shows up with the new version with the new maintainer as well.

**Comment by xiota** [comment]
I don't know why the kernel and header packages were out of sync.  I deleted them, so they can be rebuilt tomorrow.

**Comment by xiota** [comment]
```
$ pacman -Ss linux-amd | grep -E '^\S'
chaotic-aur/linux-amd 6.10.5-1
chaotic-aur/linux-amd-headers 6.10.5-1
chaotic-aur/linux-amd-znver2 6.10.3-1
chaotic-aur/linux-amd-znver2-headers 6.10.3-1
```

**Comment by xiota** [comment]
Per comment, `linux-amd-znver3` is abnormally large.  Considering replacing `linux-amd-*` packages with interfere.
```
$ pacman -Si linux-amd-znver3
Repository      : chaotic-aur
Name            : linux-amd-znver3
Version         : 6.10.v.6-1
Description     : Linux kernel aimed at the znver3 AMD Ryzen CPU based hardware
Architecture    : x86_64
URL             : https://www.kernel.org/
Licenses        : GPL2
Groups          : None
Provides        : None
Depends On      : coreutils  linux-firmware  kmod  lzop
Optional Deps   : crda: to set the correct wireless channels of your country
Conflicts With  : None
Replaces        : None
Download Size   : 1686.71 MiB
Installed Size  : 1958.64 MiB
Packager        : UFSCar HPC Builder <hpc.ufscar@chaotic.cx>
Build Date      : Sun 25 Aug 2024 06:01:25 AM EDT
Validated By    : SHA-256 Sum
```

**Comment by xiota** [comment]
New packages are being built.  The new interferes sync with `core/linux` and allow GCC to optimize for the desired processor.  Besides standard Arch patches, no additional patches are applied.

Replaced packages:

* `linux-amd` has 19 patches.  5 appear to be from Arch.  The rest from other patch sets.
* `linux-amd-znver2` has 6 patches.  5 appear to be from Arch.  One is probably no better than setting compiler flag.
* `linux-amd-znver3` doesn't appear to apply any patches.  It instructs GCC to optimize for znver3.  Resulting package is 10x expected size.  Probably including debug info and compiling some modules into the kernel.

**Comment by xiota** [comment]
For anyone interested, adding linux-znver5, linux-x64v2, linux-x64v3, linux-x64v4.

Metrics:

* linux-cachyos # 1069
* linux-cachyos-headers # 890
* linux-cachyos-lts # 264
* linux-cachyos-lts-headers # 210
* linux-clear # 1656
* linux-clear-headers # 1595
* linux-lqx # 708
* linux-lqx-headers # 632
* linux-lts515 # 35
* linux-lts515-headers # 34
* linux-lts61 # 35
* linux-lts61-headers # 33
* linux-lts66 # 73
* linux-lts66-headers # 64
* linux-mainline # 1628
* linux-mainline-headers # 1556
* linux-mainline-x64v3 # 181
* linux-mainline-x64v3-headers # 176
* linux-nitrous # 103
* linux-nitrous-headers # 92
* linux-vfio # 63
* linux-vfio-headers # 41
* linux-vfio-lts # 50
* linux-vfio-lts-headers # 43
* linux-vfio-x64v3 # 42
* linux-vfio-x64v3-headers # 40
* linux-xanmod-edge-x64v3 # 428
* linux-xanmod-edge-x64v3-headers # 407
* linux-xanmod-lts # 176
* linux-xanmod-lts-headers # 165
* linux-xanmod-rt # 99
* linux-xanmod-rt-headers # 87
* linux-xanmod-x64v2 # 175
* linux-xanmod-x64v2-headers # 142
* linux-znver2 # 91
* linux-znver2-headers # 88
* linux-znver3 # 250
* linux-znver3-headers # 235
* linux-znver4 # 199
* linux-znver4-headers # 197
