### ISSUE TITLE
[Bug] Diodon is damaged or not valid

### ISSUE THREAD

**Issue by Raxelgrande** [chaotic-aur/packages#3272]
### Packages:

I think the diodon version from here is different than the aur one.

### Latest chaotic version

diodon-1.13.0-2.2-x86_64

### What happens?

Diodon fails to install due to the package complaining about being damaged or invalid (checksum)

### What is expected to happen?

That the program installs correctly

**Comment by Technetium1** [comment]
`Finished making: diodon 1.13.0-2.3 (Mon 19 Aug 2024 08:28:37 PM CEST)`
