### ISSUE TITLE
[Request] fooyin-git

### ISSUE THREAD

**Issue by 23365209** [chaotic-aur/packages#3276]
### Package:

https://aur.archlinux.org/packages/fooyin-git

### Purpose:

fooyin is a customizable Qt6 music player that is similar in function to foobar2000.

### Benefits:

The main developer fixes bugs and adds new features fairly frequently, so having a compiled -git version would be nice.

### Building:

Cloned the AUR repo, created a clean chroot and ran the following command inside the cloned repo:
`makechrootpkg -c -r $CHROOT`

### Copyright:

GPL-3.0

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Adding with interfere to make following changes:

* Add conflicts
* Fix pkgver
* Don't install unnecessary license file
