### ISSUE TITLE
[Request] firefox-extension-adguard

### ISSUE THREAD

**Issue by encode42** [chaotic-aur/packages#3280]
### Package:

https://aur.archlinux.org/packages/firefox-extension-adguard

### Purpose:

Provides the AdGuard ad-blocker extension for Firefox installations.

### Benefits:

Though uBlock Origin is often recommended, AdGuard is a very worthy alternative. Additionally, compared to managing extension updates through the browser, user such as myself would like to defer to the system's package manager.

### Copyright:

GPL-3.0-only

### Expected Interest:

Only me

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Inclined to reject because extensions should be managed directly through the browser.

**Comment by encode42** [comment]
The Chaotic-AUR already provides multiple Firefox extensions, though. I would agree, if these didn't already exist on Chaotic's repository. The AdGuard extension is one that is on the AUR but not built by Chaotic, while others like `firefox-extension-localcdn` and `firefox-extension-plasma-integration` are.

**Comment by xiota** [comment]
I see only those two extensions for a few different browsers.  There used to be more, but they were gradually dropped.  The last several had been deleted from AUR following poor maintenance.  The pace of web development makes them difficult to keep updated, and when outdated, they block the usual installation and update methods.
