### ISSUE TITLE
[Request] midori

### ISSUE THREAD

**Issue by dimkauzh** [chaotic-aur/packages#3281]
### Package:

https://aur.archlinux.org/packages/midori

### Purpose:

Web browser based on [Floorp](https://aur.archlinux.org/packages/floorp), with more features.

### Benefits:

I and my friends find it a small upgrade over floorp browser. Adds additional features and is a little more stable than Floorp.

### Building:

makepkg
Installs without issues using `yay`

### Copyright:

MPL-2.0

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Midori hasn't been kept up to date with Firefox/Floorp releases.

**Comment by dimkauzh** [comment]
> Midori hasn't been kept up to date with Firefox/Floorp releases.
> 
> Edit: Looks like they've been bumping versions silently.

Oh wow i didn't realise that! Just switched to Floorp. Thanks!

**Comment by xiota** [comment]
I tried building both `midori` and `midori-git`.  They need upstream updates for GCC 14.
