### ISSUE TITLE
[Request] quake3e-git

### ISSUE THREAD

**Issue by dimkauzh** [chaotic-aur/packages#3283]
### Package:

https://aur.archlinux.org/packages/quake3e-git

### Purpose:

Improved Quake III Arena Engine

### Benefits:

Up to date improved Quake III Arena Engine

### Building:

`makepkg`
Works great with `yay`

### Copyright:

GPL

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Me and my friends like to use this to play Quake3. Also till now there is no quake engine available in Chaotic-AUR.

**Comment by dimkauzh** [comment]
I rebuilt it like an hour ago, builds and works without issues

**Comment by dimkauzh** [comment]
By the way, is it maybe an idea for me to open a pull request? (Not to be greedy or anything, maybe that will be handier for you)

**Comment by Technetium1** [comment]
@dimkauzh no, it needs to be built and triaged to know which routine it belongs in. Either way, there should still be an issue so it can be tracked.

**Comment by dimkauzh** [comment]
> @dimkauzh no, it needs to be built and triaged to know which routine it belongs in. Either way, there should still be an issue so it can be tracked.

Oh ok understood. Thanks for adding this!
