### ISSUE TITLE
[Request] netflix

### ISSUE THREAD

**Issue by dimkauzh** [chaotic-aur/packages#3285]
### Package:

https://aur.archlinux.org/packages/netflix

### Purpose:

Unnofficial Netflix desktop application. A netflix electron port to desktop.

### Benefits:

There is silo-netflix on here, but I find this package a little more optimized and nicer then silo-netflix.

### Building:

`makepkg`
Works great with `yay`

### Copyright:

GPL

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Using this daily to watch netflix. Works great.

**Comment by xiota** [comment]
Package is banned.

**Comment by dimkauzh** [comment]
> Package is banned.  Uses non-standard / modified electron package.

Oh sorry didn't see that. My bad. Sorry

**Comment by xiota** [comment]
I edited the readme after you opened this issue, but ... 95c21c5c1c2b68b397fd12100090a8f0ec038deb
