### ISSUE TITLE
[Request] eyedropper

### ISSUE THREAD

**Issue by fabianski7** [chaotic-aur/packages#3288]
### Package:

https://aur.archlinux.org/packages/eyedropper

### Purpose:

It`s a color picker

### Copyright:

GPL-3.0-or-later 

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
Does this have any benefit over the flatpak? https://flathub.org/apps/details/com.github.finefindus.eyedropper
