### ISSUE TITLE
[Request] hplip-minimal

### ISSUE THREAD

**Issue by ayu2805** [chaotic-aur/packages#3289]
### Package:

https://aur.archlinux.org/packages/hplip-minimal

### Purpose:

Provides only printer drivers from HPLIP with proprietary binary plugin

### Benefits:

No need to install hplip-lite with hplip-plugin

### Copyright:

BSD, MIT, GPL-2.0, GPL-3.0, custom:HPLIP

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
@ayu2805 what is the difference between this and `hplip-lite` which we currently provide? https://github.com/chaotic-aur/packages/issues/1949

**Comment by ayu2805** [comment]
> what is the difference between this and `hplip-lite` which we currently provide? https://github.com/chaotic-aur/packages/issues/1949

@Technetium1 Well it's mainly a combination of hplip-lite and hplip-plugin. Less complication and mainly saves time(my time specifically).

**Comment by xiota** [comment]
Inclined to reject.  `hplip-minimal` is a new package and the first package from the maintainer.  At a glance, it has a couple packaging mistakes.  In particular, merely including it in the repo would break the existing `hplip` and `hplip-lite` packages.

**Comment by ayu2805** [comment]
> it has a couple packaging mistakes.

I see. Welp, actually I am the maintainer now.  The package was deleted a few years ago and I picked it up recently. Although I noticed it now and added hplip-lite as a conflict package too, I would like to know the mistakes in the package's comments.

**Comment by xiota** [comment]
I should have looked more carefully at the username...

* License strings now follow SPDX format.  https://spdx.org/licenses/
    * GPL licenses look like `GPL-2.0-only` and `GPL-3.0-or-later`
    * Custom licenses are formatted like `LicenseRef-HPLIP`
* `make` should not have `-j` options, except to concurrency bugs.  Then it's usually `-j 1`
    * Users can specify `MAKEFLAGS` in `/etc/makepkg.conf`
* `validpgpkeys` doesn't make sense when there's no signature file

On further examination, I was mistaken about the conflicts being a problem.  `hplip-lite` isn't needed in conflicts.

Does your package avoid the issue described at #2376 ?

**Comment by ayu2805** [comment]
> I should have looked more carefully at the username...
> 
> * License strings now follow SPDX format.  https://spdx.org/licenses/
>     * GPL licenses look like `GPL-2.0-only` and `GPL-3.0-or-later`
>     * Custom licenses are formatted like `LicenseRef-HPLIP`

I see, I have updated it to MIT, BSD-3-Clause, GPL-3.0-or-later, GPL-2.0-only, LicenseRef-HPLIP 

> * `make` should not have `-j` options, except to concurrency bugs.  Then it's usually `-j 1`
>     * Users can specify `MAKEFLAGS` in `/etc/makepkg.conf`

Got it, I just did that because hplip-lite also has that flag

> * `validpgpkeys` doesn't make sense when there's no signature file

I have added it now

> On further examination, I was mistaken about the conflicts being a problem.  `hplip-lite` isn't needed in conflicts.

Isn't it better to leave hplip-lite as conflict?

> Does your package avoid the issue described at #2376 ?

I have updated it and checked it. I have a printer that requires hplip-plugin and after installation of the package I didn't have to manually setup the plugins.

**Comment by xiota** [comment]
Thanks for updating the package.

I hope you checked the licenses for accuracy.  The combination of `GPL-3.0-or-later` and `GPL-2.0-only` is unusual, and I was using them only as examples.

Keeping `hplip-lite` in conflicts would be okay.  It's not necessarily better, but also not harmful.  I usually try to minimize the package lists.  It matters more for packages with longer lists.

**Comment by xiota** [comment]
Assume "only" until proven otherwise.  Usually the "or later" is in the readmy or source headers.  If you didn't see it, declare `GPL-3.0-only`.

I'm okay with adding it.  I'll go ahead and add it this weekend.  If I forget, ping me next weekend.

**Comment by ayu2805** [comment]
> Assume "only" until proven otherwise.  Usually the "or later" is in the readme or source headers.  If you didn't see it, declare `GPL-3.0-only`.

Got it, I'll do that instead. And will try to find the actual license too

> I'll add it this weekend.  If I forget, ping me next weekend.

Yeah sure.

**Comment by Technetium1** [comment]
@ayu2805 seems off without doing close inspection, you are building in clean chroot right? Can you confirm these logs are like your own? [hplip-minimal.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/hplip-minimal.log)

**Comment by ayu2805** [comment]
> @ayu2805 seems off without doing close inspection, you are building in clean chroot right? Can you confirm these logs are like your own? [hplip-minimal.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/hplip-minimal.log)

Yes indeed, also the errors from `./configure` is expected those mishaps are from HP and since it's not creating any problem I didn't choose to fix it because even the offical `hplip` from `[extra]` repo haven't fixed it.

**Comment by xiota** [comment]
`ppdc` is included in `extra/cups`.  Adding to makedeps should fix following.  (I haven't tried building this package yet.)
```
./createPPD.sh: line 84: ppdc: command not found
gzip: ppd/hpcups/*.ppd: No such file or directory
./createPPD.sh: line 90: ppdc: command not found
gzip: ppd/hpijs/*.ppd: No such file or directory
```

**Comment by ayu2805** [comment]
> `ppdc` is included in `extra/cups`.  Adding to makedeps should fix following.  (I haven't tried building this package yet.)
> ```
> ./createPPD.sh: line 84: ppdc: command not found
> gzip: ppd/hpcups/*.ppd: No such file or directory
> ./createPPD.sh: line 90: ppdc: command not found
> gzip: ppd/hpijs/*.ppd: No such file or directory
> ```

Got it, I have added it to make dependencies

**Comment by xiota** [comment]
Produces errors at start of build.  I'll look at it more later to see how important they are.
```
./configure: line 16778: test: syntax error: `-march=x86-64' unexpected
./configure: line 17939: 0: command not found
./configure: line 17944: 0: command not found
```

**Comment by ayu2805** [comment]
> Produces errors at start of build.

I thought it was harmless errors due to some syntax error from HP

**Comment by ayu2805** [comment]
@xiota Sorry for the ping but what's the current state of progress?

**Comment by xiota** [comment]
Consider applying some (if possible, all) of the patches at https://gitlab.archlinux.org/archlinux/packaging/packages/hplip

**Comment by ayu2805** [comment]
> Consider applying some (if possible, all) of the patches

Some of the patches are unnecessary here because it's related to sane i.e. scan support which I have disabled because it's a better idea to use hplip from [extra] instead of using some other packages for full feature support. Though I have added the pserror, missing drivers and include cups/ppd.h patches.

**Comment by xiota** [comment]
@ayu2805 Fails to build because missing makedep on `unzip`, but would be better to use `bsdtar`, which is what makepkg normally uses.  Alternatively, you can use `http` protocol instead of `https` to set user agent for a single file to keep it in the sources array.
```
for _key in "${!DLAGENTS[@]}" ; do
  _protocol="${DLAGENTS[$_key]%%::*}"
  if [ "$_protocol" = "http" ]; then
    DLAGENTS[$_key]="$(sed -E 's&(/bin/curl)\b&\1 -A "Mozilla/5.0 (Linux x86_64) Gecko/20100101"&g' <<< "${DLAGENTS[$_key]}")"
  fi
done
```

Also, please test packages before pushing to AUR to avoid dozens of nonfunctional commits.  If you need help, feel free to comment here.

**Comment by ayu2805** [comment]
> Alternatively, you can use `http` protocol instead of `https` to set user agent for a single file to keep it in the sources array.

@xiota I actually I want to why would I need to do that? 

Also I tried using the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hplip-plugin) from hplip-plugin that used the following snippet but it seems it's not able to download other files properly. 
```
_user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
DLAGENTS=("https::/usr/bin/curl --user-agent ${_user_agent// /\\ } -qgb '' -fLC - --retry 3 --retry-delay 3 -o %o %u")
```

**Comment by ayu2805** [comment]
> If you're not stuck on Windows permanently, it's okay to wait until you're back in a real Linux environment before updating.

Okay but as of now the PKGBUILD seems to be working but I will add a test out of your suggestion soon.

> The problem seems to be that sourceforge blocks the download when the user-agent is altered, but hp requires it to be changed.  That's why I suggest... use unaltered https for sourceforge, and alter http user-agent for hp.

I see, make sense. Thank You.
