### ISSUE TITLE
[Remove] kmscon

### ISSUE THREAD

**Issue by BPplays** [chaotic-aur/packages#3291]
### Package:

https://aur.archlinux.org/packages/kmscon

### Purpose:

it is a tty program that uses kms. it's useful for supporting custom fonts and supporting displaying unicode characters.

### Copyright:

MIT and some LGPL-2.1
https://github.com/Aetf/kmscon/?tab=License-1-ov-file#readme

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Dropped because moved to extra.

Metrics:

* kmscon # 41
* libtsm # 87
