### ISSUE TITLE
[Rebuild] dislocker

### ISSUE THREAD

**Issue by hirak99** [chaotic-aur/packages#3292]
### Packages:

https://aur.archlinux.org/packages/dislocker

### Latest chaotic version

`0.73-4`

### Reason for rebuild

The build is outdated, and the binary is linked to outdated libraries.

```sh
$ dislocker
dislocker: error while loading shared libraries: libmbedcrypto.so.14: cannot open shared object file: No such file or directory
```

Ideally pkgrel should have been increased. I dropped a note to the maintainer.

A rebuilding should be done immediately. I confirm rebuilding makes it work again.

### Builds?

No special procedure needed, just need to rebuild it.

Note that this has happened once or twice before, the dependencies get updated when the package is rebuilt. The maintainer unfortunately does not increase pkgrel. I also dropped a [note to the package to request](https://aur.archlinux.org/packages/dislocker#comment-988886) increasing pkgrel.

Steps to rebuild -

```
mkdir dislocker && cd dislocker
curl 'https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=dislocker' -o PKGBUILD
makepkg -s

# Note that it builds two packages -
# dislocker-0.7.3-4-x86_64.pkg.tar.zst and dislocker-debug-0.7.3-4-x86_64.pkg.tar.zst
# We only need the first, and do not need the debug one.
```

### More information

What is the best way to deal with situations like this in longer term, where the pkgrel does not get updated by a maintainer?

**Comment by xiota** [comment]
Bumped and rebuilt.  https://github.com/chaotic-aur/interfere/commit/fd97d0b390222cdda0935f771b000e198f1fd532
```
$ pacman -Ss dislocker
chaotic-aur/dislocker 0.7.3-4.1
    Read/write BitLocker-encrypted volumes
```
