### ISSUE TITLE
[Request] kmonad-git

### ISSUE THREAD

**Issue by hirak99** [chaotic-aur/packages#3293]
### Package:

https://aur.archlinux.org/packages/kmonad-git

### Purpose:

It is a cross platform keyboard remapping and layering software, currently supports Linux, Windows, MacOS.

For instance, it can be used to emulate the "Fn" key-like functionality, which is typically found in laptops. It can support multiple lead keys.

It has been gaining popularity steadily, from a quick Google search I found a number of articles and videos on it. All of them are positive, and it looks like many people now swear by it.

### Benefits:

The package appears to follow a very slow release schedule, almost about once in a year.

I have also requested the project owner to release a new package, which they will probably do soon: https://github.com/kmonad/kmonad/issues/879

However, given that the package release is very infrequent, unless they change the frequency it may soon become out of date again.

Also, building this locally requires installing the entire Haskell stack, which many people may not already have - or some may refrain in order to keep their distro clean of one-off build tools.

Thus adding the kmonad-git to Chaotic AUR should be very helpful.

### Building:

```sh
# The package is available in AUR: https://aur.archlinux.org/packages/kmonad-git

# Thus this works -
paru -S kmonad-git
```

### Copyright:

MIT

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

- Google: [Is kmonad useful?](https://www.google.com/search?q=is+kmonad+useful%253F)
- Reddit: [r/kmonad](https://www.reddit.com/r/Kmonad/)

**Comment by Technetium1** [comment]
Getting an uncomfortable amount of warnings. I believe the GHC + Cabal versions mismatch is to be expected and is likely OK.
Log: [kmonad-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/kmonad-git.log)
```
Stack has not been tested with GHC versions above 9.4, and using 9.6.5, this may fail
```
```
Configuring GHC ...
/home/main-builder/pkgwork/src/.stack/programs/x86_64-linux/ghc-tinfo6-9.6.5.temp/ghc-9.6.5-x86_64-unknown-linux/configure: line 6559: FP_PROG_LD_BUILD_ID: command not found
ar: conftest.a: No such file or directory
```
```
Stack has not been tested with Cabal versions above 3.8, but version 3.10.3.0 was found, this may fail
WARNING: Ignoring semigroupoids's bounds on base (>=4.3 && <4.18); using base-4.18.2.1.
Reason: trusting snapshot over cabal file dependency information.
```
And again in package function
```
Stack has not been tested with GHC versions above 9.4, and using 9.6.5, this may fail
Stack has not been tested with Cabal versions above 3.8, but version 3.10.3.0 was found, this may fail
```

@hirak99 can you confirm the package `kmonad-git 0.4.2.r87.g4c324f1-1` functions as expected?

**Comment by hirak99** [comment]
Thank you, I can confirm that the binary is working okay. This is awesome!

FYI, I flagged the build errors upstream repository, https://github.com/kmonad/kmonad/issues/881 but I don't think anything else needs to be done here yet. If the errors are unexpected, I will report it to the current package maintainer.

**Comment by Technetium1** [comment]
@hirak99 Thank you for the update, I've subscribed to notifications on the issue you created upstream
