### ISSUE TITLE
[Rebuild] aquamarine-git

### ISSUE THREAD

**Issue by Stephixus** [chaotic-aur/packages#3295]
### Packages:

http://aur.archlinux.org/packages/aquamarine-git

### Latest chaotic version

`0.3.3.r23.gdd9890d-1`

### Reason for rebuild

Outdated.
Now version 0.4.0 with many enhancements.

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/aquamarine-git.log

### More information

Many mesa dependencies proposed. :warn

**Comment by Technetium1** [comment]
Thanks, there's a new dep to be added.
