### ISSUE TITLE
[Request] shadps4-git

### ISSUE THREAD

**Issue by tulpenkiste** [chaotic-aur/packages#3297]
### Package:

https://aur.archlinux.org/packages/shadps4-git

### Purpose:

ShadPS4 is an experimental PlayStation 4 emulator written in C++.

### Benefits:

ShadPS4 is one of the fastest growing PS4 emulators, being able to get in-game on Bloodborne.

### Building:

Installed `vulkan-headers-git` and SDL3.
Then used makepkg.

### Copyright:

GPL2

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by DocMAX** [comment]
+1

**Comment by DocMAX** [comment]
:-)
