### ISSUE TITLE
[Rebuild] phpstorm and phpstorm-jre

### ISSUE THREAD

**Issue by Heyian** [chaotic-aur/packages#3298]
### Packages:

https://aur.archlinux.org/pkgbase/phpstorm

### Latest chaotic version

2024.2.0.1-1

### Reason for rebuild

Outdated, the version on the AUR is 2024.2.1-1
I know these look similar but the About of PHPStorm is telling me I have the version 2024.2.0.1 and that the update 2024.2.1 is available.

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/phpstorm.log

**Comment by xiota** [comment]
```
==> Finished making: phpstorm 2024.2.1-1 (Thu 05 Sep 2024 12:57:56 AM CEST)
```
