### ISSUE TITLE
(Re-)add some packages

### ISSUE THREAD

**Issue by Brueggus** [chaotic-aur/packages#330]
```
1password-bin
badwolf
getmail6
onedrive-abraunegg
postman-bin
pycharm-community-eap
slack-term
typora
waterfox-g3-bin
winbox64
wine-x64
```

Thanks :+1:

**Comment by dr460nf1r3** [comment]
- [ ] 1password-bin
- [ ] badwolf
- [ ] getmail6
- [ ] onedrive-abraunegg
- [ ] postman-bin
- [ ] pycharm-community-eap
- [ ] slack-term
- [ ] typora
- [ ] waterfox-g3-bin
- [ ] winbox64
- [ ] wine-x64

**Comment by xiota** [comment]
`winbox64` no longer in AUR.  Dropped along with dependency `wine-x64` in 6aa61b716ac3e83dc1748a40436059411245043e

**Comment by Brueggus** [comment]
Yep, `wine-x64` has been superseded by `wine-wow64` (see #2635)

**Comment by xiota** [comment]
Dropping `pycharm-community-eap` because of size (643.30 MiB download, 1876.46 MiB install).  `extra/pycharm-community-edition` is available.  Metrics 30.

**Comment by xiota** [comment]
Dropping `typora`.  It is trialware with restrictive [license](https://support.typora.io/License-Agreement/) disallowing distribution.  Metrics 125.
