### ISSUE TITLE
[Request] xmcl-launcher

### ISSUE THREAD

**Issue by yigitsalar** [chaotic-aur/packages#3300]
### Package:

https://aur.archlinux.org/pkgbase/xmcl-launcher

### Purpose:

X Minecraft Launcher - A modern Minecraft launcher

### Benefits:

FOSS
Unique and very customizable UI
Ability to install performance tweaks (OptiFine, etc.)/modifiable clients (Forge, Fabric, etc.) directly inside of the launcher.

### Building:

`makepkg -si`

### Copyright:

MIT

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by yigitsalar** [comment]
Thanks!

**Comment by xiota** [comment]
Planning to drop.  Fails to build, disguised -bin package, and many other packaging problems.  Metrics 65.
```
bsdtar: Error opening archive: Unrecognized archive format
```

**Comment by CrystalNetworkST** [comment]
> Planning to drop. Fails to build, disguised -bin package, and many other packaging problems. Metrics 65.
> 
> ```
> bsdtar: Error opening archive: Unrecognized archive format
> ```

Hello!!! I'm a Maintainer of xmcl-launcher on AUR, is it possible to try to build the package again?
Because at the moment in the latest version of pgkbuild it builds successfully

**Comment by xiota** [comment]
I looked at the package again.  It's still a disguised bin package.  Has incorrect source array construction for multi-architecture.  Violates source policy from AUR submission guidelines.  Has unusual checks in prepare and package.
