### ISSUE TITLE
[Bug] gconf

### ISSUE THREAD

**Issue by xiota** [chaotic-aur/packages#3306]
### Packages:

https://aur.archlinux.org/packages/gconf

### Latest chaotic version

--

### What happens?

@IslandC0der Fails to build.  Missing depends on `glib2-devel`.

I can update package if added as comaintainer.

### What is expected to happen?

Should build successfully.

### Logs

[`gconf.log.gz`](https://github.com/user-attachments/files/16921615/gconf.log.gz)

**Comment by xiota** [comment]
Planning to drop `gconf` and related packages because it is obsolete and packages/projects that still depend on it are arguably not well maintained.

**Comment by IslandC0der** [comment]
Fixed, but it is indeed obsolete

**Comment by xiota** [comment]
If dropped, the affected packages, with metrics, would be:

* gconf 459
* libgksu 238
* gksu 188

**Comment by xiota** [comment]
`gconf` no longer builds because `2to3` was removed from Python.  Planning to proceed with drop.  Updated metrics.  Inflated because of aggressive auto-bump.  Should divide by ~4.

* gconf # 2146
* libgksu # 865
* gksu # 769
