### ISSUE TITLE
[Bug] hal-emsec-git

### ISSUE THREAD

**Issue by xiota** [chaotic-aur/packages#3307]
### Packages:

https://aur.archlinux.org/packages/hal-emsec-git

### Latest chaotic version

v4.2.0.r355.g46d627b3e73-1

### What happens?

Fails to build; don't know why

### What is expected to happen?

Should build successfully

### Logs

[hal-git.log](https://github.com/user-attachments/files/16925536/hal-git.log)

### More information

@thotypous Any idea why it fails to build?

**Comment by xiota** [comment]
There are multiple problems preventing build.  I'll open a PR with upstream project in upcoming days.

Also planning to create and switch to a new package `aur/hal-emsec-git`.

**Comment by thotypous** [comment]
Wow you are a bug-fixing machine! Thanks for the effort

**Comment by dr460nf1r3** [comment]
> Wow you are a bug-fixing machine! Thanks for the effort

Definitely agree with that! 🔥

**Comment by xiota** [comment]
@thotypous How important is this package?

Package is still unbuildable, but the PR needs to be rebased.  It is currently not present in v4.  Do you have a backup for use of `hal-emsec-git` from v3?

**Comment by thotypous** [comment]
I'm currently not using it, but I plan to use it in a class that is going to happen on February 7. I will take a look at the build when I get some time to see what I can do. Thank you for your efforts!

**Comment by xiota** [comment]
@thotypous I've identified the necessary commits from the PR and have a working PKGBUILD.  Would you prefer this as a custom PKGBUILD or uploaded to AUR?  If put to AUR, can add you as comaintainer.

**Comment by thotypous** [comment]
Thank you! Please send to AUR and add me as comaintainer

**Comment by xiota** [comment]
@thotypous New package at [`aur/hal-emsec-git`](https://aur.archlinux.org/packages/hal-emsec-git).  Let me know if I added the right user name.  Will add to chaotic-aur momentarily.

**Comment by xiota** [comment]
@thotypous Since you use this for classes, should there be a stable package?

**Comment by thotypous** [comment]
> @thotypous Since you use this for classes, should there be a stable package?

Nah, if we wanted stable we would use Debian :P
