### ISSUE TITLE
[Request] SIMP

### ISSUE THREAD

**Issue by NormTurtle** [chaotic-aur/packages#3308]
### Package:

https://aur.archlinux.org/packages/simp

### Purpose:

A simple and fast image manipulation program

### Benefits:

fast minimal image edit.

### Building:

makepkg

### Copyright:

GPL

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
Hopefully maintainer adds checksums as requested. It's ok for now.
