### ISSUE TITLE
[Rebuild] mesa-tkg-git

### ISSUE THREAD

**Issue by Jelgnum** [chaotic-aur/packages#3309]
### Packages:

https://github.com/Frogging-Family/mesa-git

### Latest chaotic version

24.3.0_devel.193759.db39685e317-1

### Reason for rebuild

new dependencies and build flag updates, the package build has already been updated with the new dependencies and changes

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/mesa-tkg-git.log

**Comment by xiota** [comment]
Numerous errors, `error[E0080]: evaluation of constant value failed`.  Most likely needs to be fixed upstream.
```
FAILED: src/compiler/rust/libcompiler.rlib
rustc --target i686-unknown-linux-gnu -C linker=gcc -C link-arg=-m32 --color=always -C debug-assertions=no -C overflow-checks=no --crate-type rlib --edition=2021 -C opt-level=3 -Cforce-frame-pointers=yes --crate-name compiler --emit dep-info=src/compiler/rust/compiler.d --emit link=src/compiler/rust/libcompiler.rlib --out-dir src/compiler/rust/libcompiler.rlib.p -C metadata=56103fb@@compiler@sta src/compiler/rust/libcompiler.rlib.p/structured/lib.rs
error[E0080]: evaluation of constant value failed
   --> src/compiler/rust/libcompiler.rlib.p/structured/bindings.rs:171:26
    |
171 |     ["Size of _IO_FILE"][::std::mem::size_of::<_IO_FILE>() - 216usize];
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ attempt to compute `124_usize - 216_usize`, which would overflow
```

**Comment by Jelgnum** [comment]
there is apparently a work around for this issue https://github.com/mesonbuild/meson/issues/13591#issuecomment-2307996182

**Comment by xiota** [comment]
Thanks for finding that.  Works:
```
==> Finished making: mesa-tkg-git 24.3.0_devel.195299.0fd96dcf171-1 (Fri 20 Sep 2024 01:05:19 AM CEST)
```

Don't know whether should... wait for meson to fix, add interfere, or open issue and PR for tkg package.

**Comment by xiota** [comment]
Opened PR at `https://github.com/Frogging-Family/mesa-git/pull/50`

**Comment by dr460nf1r3** [comment]
Got merged, guess we can close it then! 🔥
