### ISSUE TITLE
[Rebuild] linux-xanmod-lts

### ISSUE THREAD

**Issue by Darian1999** [chaotic-aur/packages#3312]
### Packages:

https://aur.archlinux.org/packages/linux-xanmod-lts

### Latest chaotic version

6.6.47-1-x86_64

### Reason for rebuild

Outdated. Latest XanMod kernel LTS version in the AUR is 6.6.50-1.

**Comment by dr460nf1r3** [comment]
Is currently building.

**Comment by Darian1999** [comment]
@dr460nf1r3 Thanks, but why is it not showing on the website?

**Comment by dr460nf1r3** [comment]
Which one specifically?

**Comment by Darian1999** [comment]
@dr460nf1r3 it's linux-xanmod-lts.

**Comment by dr460nf1r3** [comment]
If you mean the build status, there is a big fat disclaimer:
> Disclaimer: the data shown here corresponds to our in-progress [infra 4.0](https://gitlab.com/chaotic-aur/pkgbuilds), NOT the live Chaotic-AUR repo.

It's done nevertheless, already:
~~~
==> Adding package './linux-xanmod-lts-6.6.50-1-x86_64.pkg.tar.zst'
  -> Computing checksums...
  -> Removing existing entry 'linux-xanmod-lts-6.6.47-1'...
  -> Creating 'desc' db entry...
  -> Creating 'files' db entry...
==> Adding package './linux-xanmod-lts-headers-6.6.50-1-x86_64.pkg.tar.zst'
  -> Computing checksums...
  -> Removing existing entry 'linux-xanmod-lts-headers-6.6.47-1'...
  -> Creating 'desc' db entry...
  -> Creating 'files' db entry...
==> Creating updated database file 'chaotic-aur.db.tar.zst'
~~~

**Comment by Darian1999** [comment]
@dr460nf1r3 Thank you, You are awesome!
