### ISSUE TITLE
[Rebuild] linux-clear

### ISSUE THREAD

**Issue by Darian1999** [chaotic-aur/packages#3313]
### Packages:

https://aur.archlinux.org/packages/linux-clear

### Latest chaotic version

6.10.6-1-x86_64

### Reason for rebuild

Outdated. Current version in the AUR is 6.10.9-1, while current version in https://aur.chaotic.cx is 6.10.6.

**Comment by Technetium1** [comment]
The routine for this was accidentally stopped, and has since been fixed. It should be available within a few hours.

**Comment by xiota** [comment]
Still hasn't been rebuilt.  Several linux kernels affected.

**Comment by Darian1999** [comment]
Now, it's updated! Yay!
