### ISSUE TITLE
[Request] cminpack

### ISSUE THREAD

**Issue by Darian1999** [chaotic-aur/packages#3320]
### Package:

https://aur.archlinux.org/packages/cminpack

### Purpose:

A C/C++ rewrite of the MINPACK software

### Benefits:

1. This Package is written in C/C++, which both are fast programming languages.

### Copyright:

BSD

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Rejected because it's a depends without any dependent and insufficient juatification for maintenance burden.

@Darian1999 Put more thought into your requests.  Describe the package *and* use case.
