### ISSUE TITLE
[Rebuild] bolt-launcher

### ISSUE THREAD

**Issue by philzin** [chaotic-aur/packages#3322]
### Packages:

https://aur.archlinux.org/packages/bolt-launcher

### Latest chaotic version

0.9.0-1.1

### Reason for rebuild

Broken after fmt 11 update.

### Builds?

 Just recompiling normally from AUR with fmt 11 installed works.

**Comment by Technetium1** [comment]
`Finished making: bolt-launcher 0.9.0-1.2 (Sat 14 Sep 2024 07:32:24 PM CEST)`
