### ISSUE TITLE
[Rebuild] dwarfs

### ISSUE THREAD

**Issue by SteavenGamerYT** [chaotic-aur/packages#3325]
### Packages:

https://aur.archlinux.org/packages/dwarfs

### Latest chaotic version

0.10.1-2

### Reason for rebuild

breaks linux kernel

### Logs

==> ERROR: binary dependency 'libfmt.so.10' not found for 'mount.dwarfs'

**Comment by xiota** [comment]
Will bump after some testing.  Pointless to bump if won't work with new fmt version.
