### ISSUE TITLE
[Rebuild] gimp-git, pkgver outdated

### ISSUE THREAD

**Issue by Covkie** [chaotic-aur/packages#3326]
### Packages:

https://aur.archlinux.org/packages/gimp-git

### Latest chaotic version

`2.99.18.r1481.ge898791-1`

### Reason for rebuild

chaoticaur builds gimp-git with pkgver 2.99.18, correct should be [2.99.19](https://gitlab.gnome.org/GNOME/gimp/-/blob/master/meson.build?ref_type=heads&blame=1#L3). 

### More information

seems the pkgver() function the chaoticaur is using is different from gimp-git's on the aur

**Comment by Technetium1** [comment]
I don't recognize this failure: [gimp-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/gimp-git.log)

**Comment by xiota** [comment]
```
error: format not a string literal and no format arguments [-Werror=format-security]
```

Means, first argument of function like `printf` should be string literal (`const char *`), not variable.  `g_warning` is a wrapper around `g_log`.  Relevant argument is `format`.
```
void g_log (
  const gchar* log_domain,
  GLogLevelFlags log_level,
  const gchar* format,
  ...
)
```

**Comment by xiota** [comment]
Closing because 2.99.18 in `pkgver` is correct, and I don't want to track this.  Upstream did not tag a new version in the git repo.  The version of -git packages for projects that use separate numbering for stable and dev isn't very meaningful.  This will rebuild when upstream has a good commit.
