### ISSUE TITLE
[Rebuild] forkgram 

### ISSUE THREAD

**Issue by cleanerspam** [chaotic-aur/packages#3327]
### Packages:

https://aur.archlinux.org/packages/forkgram 

### Latest chaotic version

5.5.31

### Reason for rebuild

libprotobuf has upgraded from version 27 to 28 and thus Forkgram is refusing to launch 

### Logs

Forkgram: error while loading shared libraries: libprotobuf-lite.so.27.3.0: cannot open shared object file: No such file or directory

### More information

Rebuilding with updated libs fixes this error

**Comment by xiota** [comment]
AUR package flagged out of date.  Automated builder might downgrade back to 5.5.3.

```
==> Finished making: forkgram 5.5.5-1 (Thu 19 Sep 2024 07:42:31 AM CEST)
```

**Comment by cleanerspam** [comment]
Its working now
