### ISSUE TITLE
[Rebuild] fluffychat

### ISSUE THREAD

**Issue by dreirund** [chaotic-aur/packages#3328]
### Packages:

https://aur.archlinux.org/packages/fluffychat

### Latest chaotic version

`1.22.1-1`

### Reason for rebuild

`fluffychat`:  
```
fluffychat: error while loading shared libraries: libjsoncpp.so.25: cannot open shared object file: No such file or directory
```

`ls  /usr/lib/libjsoncpp.so*`:  
```
/usr/lib/libjsoncpp.so  /usr/lib/libjsoncpp.so.26
```

**Comment by xiota** [comment]
Bumped packages depending on libjson.  https://github.com/chaotic-aur/interfere/commit/751b8131f6ac031cf8d781c7097f33504c6c90e6
```
==> Finished making: fluffychat 1.22.1-1.1 (Fri 20 Sep 2024 11:59:42 PM CEST)
```
