### ISSUE TITLE
[Delete] gst-plugin-gtk4

### ISSUE THREAD

**Issue by realmazharhussain** [chaotic-aur/packages#3330]
### Packages:

https://aur.archlinux.org/packages/gst-plugin-gtk4

### Reason for deletion

Adopted into base Arch & will be removed from the AUR shortly.

https://archlinux.org/packages/extra/x86_64/gst-plugin-gtk4/

### More information

There was no issue template for a deletion request. So, I'm using a rebuild template for that purpose.

> [!NOTE]
> Edited out irrelevant information after initial submission.

**Comment by xiota** [comment]
You don't have to open this type of request.  Comment on the initial request, or not.  Someone will eventually notice and remove the package.  See the commit history for examples.
