### ISSUE TITLE
[Rebuild] ffmpeg-obs

### ISSUE THREAD

**Issue by ToastedWookiee** [chaotic-aur/packages#3333]
### Packages:

https://aur.archlinux.org/packages/ffmpeg-obs

### Latest chaotic version

7.0.2-2

### Reason for rebuild

Rebuild package to update with current build for libjxl 0.11

Current chaotic-aur package is 2 versions behind the AUR at `7.0.2-4`

**Comment by xiota** [comment]
@dr460nf1r3 Please check if there are any problems with `garuda-cluster/nightly.txt` running as scheduled.

Rebuilt manually.
```
==> Finished making: ffmpeg-obs 7.0.2-4 (Tue 24 Sep 2024 12:01:49 PM CEST)
```

**Comment by xiota** [comment]
Closing because routines seem to be running.
