### ISSUE TITLE
[Rebuild] pamac-flatpak and libpamac-flatpak

### ISSUE THREAD

**Issue by code8buster** [chaotic-aur/packages#3334]
### Packages:

https://aur.archlinux.org/packages/pamac-flatpak
https://aur.archlinux.org/packages/libpamac-flatpak

Current Chaotic versions:
pamac-flatpak-11.7.1-1
libpamac-flatpak-1:11.6.4-1.1

### Latest chaotic version

1:11.6.4-1.1

### Reason for rebuild

The pacman>=7.0 versioned up libalpm from 14 to 15
According to comments on aur all thats needed is a clean rebuild

**Comment by Technetium1** [comment]
Bumped: https://github.com/chaotic-aur/interfere/commit/b7272287a2a1f2ed13da93667e2b4158793f1813
`Finished making: libpamac-flatpak 1:11.6.4-1.2 (Tue 24 Sep 2024 07:38:27 PM CEST)`
`Finished making: pamac-flatpak 11.7.1-1.1 (Tue 24 Sep 2024 07:38:31 PM CEST)`
