### ISSUE TITLE
[Rebuild] xdg-desktop-portal-hyprland-git

### ISSUE THREAD

**Issue by Stephixus** [chaotic-aur/packages#3335]
### Packages:

http://aur.archlinux.org/packages/xdg-desktop-portal-hyprland-git

### Latest chaotic version

`1.3.3.r13.ge695669f-1`

### Reason for rebuild

Outdated. Now 1.3.5.

[https://github.com/hyprwm/xdg-desktop-portal-hyprland/releases/tag/v1.3.5](https://github.com/hyprwm/xdg-desktop-portal-hyprland/releases/tag/v1.3.5)

**Comment by xiota** [comment]
@dr460nf1r3 Problem with `garuda-cluster/nightly.txt`?

Rebuilt manually.
```
==> Finished making: xdg-desktop-portal-hyprland-git 1.3.5.r1.g4adb6c4-1 (Wed 25 Sep 2024 06:01:35 PM CEST)
```

**Comment by xiota** [comment]
Closing because routine seems to be running normally.
