### ISSUE TITLE
[Request] qmapshack-git

### ISSUE THREAD

**Issue by Stephixus** [chaotic-aur/packages#3336]
### Package:

http://aur.archlinux.org/packages/qmapshack-git

### Purpose:

Consumer grade GIS software.
Use QMapShack to plan your next outdoor trip or to visualize and archive all the GPS recordings of your past exciting adventures. QMapShack is the next generation of the famous QLandkarte GT application. And of course it's even better and easier to use.

### Benefits:

Features

Maps:

    Garmin vector maps and *.jnx raster maps
    Raster maps supported by GDAL
    GEMF raster maps
    Online maps (TMS and WTMS (partially))
    Display multiple maps in one view
    Reproject maps on-the-fly to view's projection
    Digital elevation model independent from maps
    Hillshading and slope coloring

GIS Data:

    100% project oriented data handling
    Summarize project by a diary
    Support for tracks, routes, waypoints and areas
    Support of trackpoint extensions (e.g. heart rate)
    Support GPX, SLF, FIT, TCX, SMl, LOG, QLB and QMapShack's own binary format
    Simple geocache support
    Store projects in a database
    Support for multiple databases

Planning:

    Undo/redo history for all items
    Trackpoint edit mode to create/change tracks, routes or areas
    Cut/copy/combine/reverse tracks
    Various filter to enhance tracks
    Trackpoint extensions like heart rate, cadence,...
    Fine tune track statistics by activities
    Colorize track by extension or activity
    Create routes and calculate them by Routino (offline), MapQuest (online) or BRouter(online/offline)
    Use offline router to draw tracks on-the-fly.

GPS Devices:

    Support for newer Garmin devices
    Support for TwoNav devices
    Project oriented data organization on devices
    Synchronize your project with a group of devices attached

### Copyright:

License GPL3+

### Expected Interest:

Many

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

### More information:

AUR package doesn’t crash on Hyprland (Wayland) while Arch/extra package does for now (NVidia Gpu).

**Comment by Technetium1** [comment]
Noting this is qt5 and there is an active branch for 6: https://github.com/Maproom/qmapshack/tree/porting_qt6

**Comment by xiota** [comment]
If primary/only reason for request is to prevent crash, consider reporting problem to Arch.  https://archlinux.org/packages/extra/x86_64/qmapshack/
