### ISSUE TITLE
[Rebuild] rtl8821cu-morrownr-dkms-git

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#3337]
### Packages:

https://aur.archlinux.org/packages/rtl8821cu-morrownr-dkms-git

### Latest chaotic version

latest

### Reason for rebuild

I am using as first mirrors:
```
Server = http://ca.mirrors.cicku.me/archlinux/$repo/os/$arch
Server = https://mirror.qctronics.com/archlinux/$repo/os/$arch
Server = http://edgeuno-bog2.mm.fcix.net/archlinux/$repo/os/$arch
```
and I get the following error:
```
rtl8821cu-morrownr-dkms-git-5.12.0.4.188.1597dfe-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (checksum))
```

**Comment by xiota** [comment]
Signature of `rtl8821cu-morrownr-dkms-git` is okay.  Did you try again after deleting local copy?

Those mirrors are not chaotic-aur servers.  If trying again doesn't resolve issue, need to know the specific server the file is downloaded from.

**Comment by D3vil0p3r** [comment]
> Signature of `rtl8821cu-morrownr-dkms-git` is okay. Did you try again after deleting local copy?
> 
> Those mirrors are not chaotic-aur servers. If trying again doesn't resolve issue, need to know the specific server the file is downloaded from.

I'm not using a cached package. I am installing it from a new Arch-based distro installation that does not have packages cached... uhm. Once we know the specific server, what can we do?

**Comment by D3vil0p3r** [comment]
@xiota sorry... I copied ArchLinux mirrors instead of chaotic... my bad. I meant the first mirrors set on the new machine were:
```
Server = https://cdn-mirror.chaotic.cx/$repo/$arch
Server = https://geo-mirror.chaotic.cx/$repo/$arch
Server = https://de-3-mirror.chaotic.cx/$repo/$arch
Server = https://us-ut-mirror.chaotic.cx/$repo/$arch
```

**Comment by xiota** [comment]
@dr460nf1r3 I checked packages on garuda for bad signatures, but `rtl8821cu-morrownr-dkms-git` looked okay.  Maybe problem with mirror?

**Comment by dr460nf1r3** [comment]
Possible - does the issue persist?

**Comment by Technetium1** [comment]
I don't see any [active] mirrors with out of sync items.

**Comment by D3vil0p3r** [comment]
Yesterday at 17:18 (CEST) I got again that error. The Chaotic AUR mirrorlist file was:
```
Server = https://cdn-mirror.chaotic.cx/$repo/$arch
Server = https://de-3-mirror.chaotic.cx/$repo/$arch
Server = https://in-3-mirror.chaotic.cx/$repo/$arch
Server = https://kr-mirror.chaotic.cx/$repo/$arch
Server = https://us-ut-mirror.chaotic.cx/$repo/$arch
Server = https://bg-mirror.chaotic.cx/$repo/$arch
Server = https://de-4-mirror.chaotic.cx/$repo/$arch
Server = https://geo-mirror.chaotic.cx/$repo/$arch
Server = https://es-mirror.chaotic.cx/$repo/$arch
Server = https://ca-mirror.chaotic.cx/$repo/$arch
Server = https://in-2-mirror.chaotic.cx/$repo/$arch
Server = https://us-mi-mirror.chaotic.cx/$repo/$arch
Server = https://de-2-mirror.chaotic.cx/$repo/$arch
Server = https://es-2-mirror.chaotic.cx/$repo/$arch
Server = https://cl-mirror.chaotic.cx/$repo/$arch
Server = https://us-tx-mirror.chaotic.cx/$repo/$arch
Server = https://gr-mirror.chaotic.cx/$repo/$arch
Server = https://br-mirror.chaotic.cx/$repo/$arch
Server = https://in-mirror.chaotic.cx/$repo/$arch
Server = https://in-4-mirror.chaotic.cx/$repo/$arch
```

**Comment by dr460nf1r3** [comment]
Lol. The commend showed 2 times, so I went ahead and deleted one of them. Now both are gone. Wtf?

**Comment by xiota** [comment]
Deja vu... glitch in the matrix?

**Comment by xiota** [comment]
Closing because incomplete/inaccurate info, unable to reproduce, and problem was reported on v3 builders, most likely not relevant to v4.

**Comment by D3vil0p3r** [comment]
It was fixed... I think... Oh... my last comment has been deleted :o

**Comment by dr460nf1r3** [comment]
Yeah, sorry for that. No idea what happened 😅
