### ISSUE TITLE
[Request]  add persepolis-git

### ISSUE THREAD

**Issue by rubiin** [chaotic-aur/packages#3338]
### Package:

https://aur.archlinux.org/packages/persepolis-git

### Purpose:

Persepolis is a download manager written in Python

### Benefits:

Multi-segment downloading(64 connections)
Scheduling downloads
Download queuing
Download video from youtube and ...

### Building:

makepkg

### Copyright:

GPL3

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
`persepolis-git` was previously dropped for maintenance issues.  Why not wait for `extra/persepolis` to be updated, rather than re-add the git package?

**Comment by rubiin** [comment]
the updates are slow IMO so i was using the git version

**Comment by xiota** [comment]
I would rather not re-add this package because of past problems.  There are also recent comments and issues reporting incomplete or damaged downloads.

**Comment by rubiin** [comment]
Thats cool. the build doesnt take that time compared to the rust programs as its on python
