### ISSUE TITLE
[Rebuild] hyprpicker-git

### ISSUE THREAD

**Issue by Stephixus** [chaotic-aur/packages#3339]
### Packages:

https://aur.archlinux.org/packages/hyprpicker-git

### Latest chaotic version

`0.3.0.r12.38fe668-1`

### Reason for rebuild

Outdated. Now v0.4.1.
[https://github.com/hyprwm/hyprpicker/releases/tag/v0.4.1](https://github.com/hyprwm/hyprpicker/releases/tag/v0.4.1)

- fractional scaling is now supported and on by default. No more blur :)
- --version, --verbose and --quiet have been added

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/hyprpicker-git.log

### Builds?

Notes for packagers
- new deps: hyprwayland-scanner>0.4.2, hyprutils>=0.2.0
[https://github.com/hyprwm/hyprpicker/releases/tag/v0.4.0](https://github.com/hyprwm/hyprpicker/releases/tag/v0.4.0)

**Comment by xiota** [comment]
`hypr*-git` interferes need to be reviewed for depends changes.  v4 interferes should be up to date.  Will compare and sync, maybe tomorrow.

**Comment by xiota** [comment]
```
==> Finished making: hyprpicker-git 0.4.1.r1.4411a6d-1 (Tue 01 Oct 2024 10:40:15 PM CEST)
```
