### ISSUE TITLE
[Request] Freeze wine-tgk-staging-fsync-git @ 6.0rc4.r0.g350eb136-312

### ISSUE THREAD

**Issue by eNTi** [chaotic-aur/packages#334]
As reported here:
https://github.com/Frogging-Family/wine-tkg-git/issues/254
and upstream here:
https://bugs.winehq.org/show_bug.cgi?id=50448

Later versions of the package cause freezes due to a deadlock issue. Not sure how to go about this exactly but I'd suggest reverting to version 6.0rc4.r0.g350eb136-312 for the time being until this is fixed.

**Comment by mixalis1987** [comment]
Is this still an issue? We are on rc6 now and havent had issues with freezing.

**Comment by eNTi** [comment]
There's a patch upstream that ought to fix it. Unless tkg packs it in his build the freezing issue will remain until it's included into mainline or staging.

**Comment by mixalis1987** [comment]
> There's a patch upstream that ought to fix it. Unless tkg packs it in his build the freezing issue will remain until it's included into mainline or staging.

Ah i see. It probably is included in tkg builds then.
