### ISSUE TITLE
[Request] goofcord-git

### ISSUE THREAD

**Issue by olivertzeng** [chaotic-aur/packages#3341]
### Package:

None, but it's prob buildable

### Purpose:

Highly configurable and privacy minded discord client.

### Benefits:

Privacy-based Discord client. Block all trackers.

### Building:

1. Install [Node.js](https://nodejs.dev/) and [pnpm](https://pnpm.io/installation#using-npm)
1. Grab the source code from the latest release. Getting it from the main branch is not recommended for a stable experience.
1. Open a command line in the directory of the source code
  1.  Install the dependencies with pnpm install
   1. Package GoofCord with either pnpm run packageWindows, pnpm run packageLinux or pnpm run packageMac
   1. Find your freshly compiled app in the dist folder.

### Copyright:

OSL-3.0 license

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

Relative #3170

**Comment by xiota** [comment]
Can't add what doesn't exist, but some questions that should eventually be answered... What is the benefit of git over stable for this package?  What is the appeal of so many forks (discord, telegram, minecraft, etc)?

**Comment by olivertzeng** [comment]
> Can't add what doesn't exist, but some questions that should eventually be answered... What is the benefit of git over stable for this package? What is the appeal of so many forks (discord, telegram, minecraft, etc)?

This is tbh a personal preference really. I want a discord client that's lightweight, and support both shelter and equibop(a fork of vencord)

**Comment by Technetium1** [comment]
There really isn't that much tracking to be blocked. This is obviously for BBD, but it makes the point: https://github.com/zerebos/BetterDiscordAddons/blob/master/Plugins/DoNotTrack/DoNotTrack.plugin.js
Vencord (and it's forks and similars) use this by default, which does the same: https://github.com/Vendicated/Vencord/blob/main/src/plugins/_core/noTrack.ts

What else are they doing of value?

**Comment by olivertzeng** [comment]
> There really isn't that much tracking to be blocked. This is obviously for BBD, but it makes the point: https://github.com/zerebos/BetterDiscordAddons/blob/master/Plugins/DoNotTrack/DoNotTrack.plugin.js
> 
> Vencord (and it's forks and similars) use this by default, which does the same: https://github.com/Vendicated/Vencord/blob/main/src/plugins/_core/noTrack.ts
> 
> 
> 
> What else are they doing of value?

Sorry to be rude but this is just like saying why there are so many existing linux forks.
Folk, it's just personal preference and I cannot say anything else about that.

**Comment by xiota** [comment]
I would prefer to not add the git package (when/if someone creates it) because providing both stable and git packages doubles the effort required to keep them working.  There are some other factors.  Collectively, they reduce to... I'm not convinced the additional maintenance burden is justified.

**Comment by xiota** [comment]
Rejecting this request because the package doesn't exist.  Even if it did, there isn't currently sufficient benefit to make maintaining it worthwhile.  Can comment for reconsideration if both of these change.

**Comment by olivertzeng** [comment]
> Rejecting this request because the package doesn't exist. Even if it did, there isn't currently sufficient benefit to make maintaining it worthwhile. Can comment for reconsideration if both of these change.

No problem! Thanks for your response!
