### ISSUE TITLE
[Request] sdl3-git

### ISSUE THREAD

**Issue by FZXizzbKv7jg** [chaotic-aur/packages#3342]
### Package:

https://aur.archlinux.org/pkgbase/sdl3-git
https://aur.archlinux.org/pkgbase/lib32-sdl3-git

https://aur.archlinux.org/pkgbase/sdl2-compat-git
https://aur.archlinux.org/pkgbase/lib32-sdl2-compat-git

### Purpose:

Simple Directmedia Layer v3 + backward compatibility

### Benefits:

Better wayland support

### Copyright:

MIT

### Expected Interest:

Everyone

### Already available?

Yes

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Looks like there's no real 3.x release yet, so would be better to provide only -git versions with plan to drop when a release makes it into official repos.

**Comment by FZXizzbKv7jg** [comment]
https://aur.archlinux.org/packages/sdl3-git
https://aur.archlinux.org/packages/lib32-sdl3-git

**Comment by xiota** [comment]
Not adding `lib32-` packages because don't want to resolve 32-bit depends and most likely no programs need them yet.

**Comment by xiota** [comment]
Dropping because `extra/sdl3` is now available.  Metrics:

* sdl2-compat-git # 73
* sdl3-git # 757
