### ISSUE TITLE
[Rebuild] mesa-tkg-git

### ISSUE THREAD

**Issue by Jelgnum** [chaotic-aur/packages#3345]
### Packages:

https://github.com/Frogging-Family/mesa-git

### Latest chaotic version

mesa-tkg-git 24.3.0_devel.195825.023277173ce-1

### Reason for rebuild

It just hasn't been rebuilding since the 3rd of October, iirc it was rebuilding at least once a day before the 3rd. There are no errors in the logs so I'm presuming the build tool might have broke

### Logs

https://builds.garudalinux.org/repos/chaotic-aur/logs/mesa-tkg-git.log

**Comment by xiota** [comment]
The routine (v3) that builds it might have stopped working.  However, may not be worth trying to fix because planning to transition to a new build system (v4) soon.

**Comment by xiota** [comment]
```
==> Finished making: mesa-tkg-git 24.3.0_devel.196328.620739ebc49-1 (Mon 14 Oct 2024 04:29:03 PM -03)
```
