### ISSUE TITLE
[Rebuild] linux-mainline

### ISSUE THREAD

**Issue by Darian1999** [chaotic-aur/packages#3347]
### Packages:

https://aur.archlinux.org/packages/linux-mainline

### Latest chaotic version

6.12-rc1-1

### Reason for rebuild

Outdated, because the commit that was supposed to update it failed because of a broken package at build-time. (latest version in AUR is 6.12-rc2-1)

**Comment by Technetium1** [comment]
`Finished making: linux-mainline 6.12rc2-1 (Wed 09 Oct 2024 07:32:29 PM CEST)`
