### ISSUE TITLE
[Rebuild] librewolf

### ISSUE THREAD

**Issue by Ethaks** [chaotic-aur/packages#3350]
### Packages:

https://aur.archlinux.org/packages/librewolf

### Latest chaotic version

130.0.1

### Reason for rebuild

Outdated, latest version is `131.0.2-1`

### Logs

https://builds.garudalinux.org/logs/logs.html?timestamp=1728573685064&id=librewolf

**Comment by xiota** [comment]
Fails at profiling stage.
```
  Parallelism determined by memory: using 32 jobs for 32 cores based on 125.5 GiB RAM and estimated job size of 1.0 GiB
libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: DRI3: Screen seems not DRI3 capable
MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
libEGL warning: egl: failed to create dri2 screen
dbus-daemon[35077]: [session uid=1000 pid=35077] Activating service name='org.a11y.Bus' requested by ':1.1' (uid=1000 pid=35180 comm="/home/main-builder/pkgwork/src/librewolf-131.0.2-1" label="kernel")
dbus-daemon[35077]: [session uid=1000 pid=35077] Successfully activated service 'org.a11y.Bus'
[Parent 35180, Main Thread] ###!!! ABORT: file resource://gre/modules/addons/XPIProvider.sys.mjs:2653
Exiting due to channel error.
started SP3 server on port 8000
Firefox exited with code -11 during profile initialization
```

**Comment by dr460nf1r3** [comment]
> Fails at profiling stage.  Tried to fix with interfere, but still doesn't work.  https://github.com/chaotic-aur/interfere/commit/6f1fc1dd0d605a33190b466a579184346487841b
> ```
>   Parallelism determined by memory: using 32 jobs for 32 cores based on 125.5 GiB RAM and estimated job size of 1.0 GiB
> libEGL warning: DRI3: Screen seems not DRI3 capable
> libEGL warning: DRI3: Screen seems not DRI3 capable
> MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
> libEGL warning: egl: failed to create dri2 screen
> dbus-daemon[35077]: [session uid=1000 pid=35077] Activating service name='org.a11y.Bus' requested by ':1.1' (uid=1000 pid=35180 comm="/home/main-builder/pkgwork/src/librewolf-131.0.2-1" label="kernel")
> dbus-daemon[35077]: [session uid=1000 pid=35077] Successfully activated service 'org.a11y.Bus'
> [Parent 35180, Main Thread] ###!!! ABORT: file resource://gre/modules/addons/XPIProvider.sys.mjs:2653
> Exiting due to channel error.
> started SP3 server on port 8000
> Firefox exited with code -11 during profile initialization
> ```

Did it build on v4? If yes, little point in trying to fix it on v3 as it's just a few days away :)

**Comment by xiota** [comment]
Failed on v4 too.  Haven't retried after recent AUR package update, but the change was same as attempted with interfere.  Will try again later in week or weekend

**Comment by xiota** [comment]
```
pacman -Si librewolf | grep -E '^(Repository|Name|Version|Date)'
Repository      : chaotic-aur
Name            : librewolf
Version         : 132.0-1
```
