### ISSUE TITLE
[Remove] gnome-online-accounts-gtk

### ISSUE THREAD

**Issue by lumifm** [chaotic-aur/packages#3351]
### Package:

https://aur.archlinux.org/packages/gnome-online-accounts-gtk

### Purpose:

A GTK Frontend for GNOME Online Accounts

GNOME Online Accounts GTK is part of the XApp Project.

It is designed to work in all desktop environments.

### Copyright:

GPL-3.0-or-later

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Dropped because moved to extra.  Metrics 39.
