### ISSUE TITLE
[Request] input-leap

### ISSUE THREAD

**Issue by darkblaze69** [chaotic-aur/packages#3352]
### Packages:

https://aur.archlinux.org/packages/input-leap

### Latest chaotic version

 input-leap-git-3.0.2+6+gbe0974fd-1-x86_64.pkg.tar.zst 

### What happens?

Recently input-leap matured enough that they released stable versions 3.0 since 4.10.2024 https://github.com/input-leap/input-leap/releases/tag/v3.0.0

So probably there's no need to follow *-git versions and just switch to stable versions.

### What is expected to happen?

input-leap reached stable 3.0 recently.

**Comment by xiota** [comment]
@dr460nf1r3 `input-leap-git` is under your section in lists.  What would you like to do with it?

**Comment by dr460nf1r3** [comment]
Can be dropped.
