### ISSUE TITLE
[Bug] 'hyprland-git' and 'xdg-desktop-portal-hyprland-git' conflicting

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#3353]
### Packages:

https://aur.archlinux.org/packages/hyprland-git

### Latest chaotic version

latest

### What happens?

When run `sudo pacman -S hyprland-git xdg-desktop-portal-hyprland-git`, user gets:
```
error: failed to commit transaction (conflicting files)
/usr/share/xdg-desktop-portal/hyprland-portals.conf exists in both 'hyprland-git' and 'xdg-desktop-portal-hyprland-git'
```

### What is expected to happen?

No conflict.

**Comment by xiota** [comment]
Should be resolved now.
```
==> Finished making: xdg-desktop-portal-hyprland-git 1.3.6.r1.gfb9c8d66-2 (Mon 14 Oct 2024 09:29:59 PM CEST)
```
