### ISSUE TITLE
[Request] revolt-desktop-git

### ISSUE THREAD

**Issue by Pakrohk** [chaotic-aur/packages#3354]
### Package:

https://aur.archlinux.org/packages/revolt-desktop-git

### Purpose:

Open source user-first chat platform.

### Benefits:

This is an open-source alternative to Discord (in fact, the only true open-source competitor to it), so it’s essential to include it.

### Copyright:

AGLP-3.0-only

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Uses Electron 22.  Also has deprecation message in favor of migration to Tauri.

**Comment by xiota** [comment]
Rejecting because upstream project is deprecated and package is not in good state, orphaned.
