### ISSUE TITLE
[Bug] Pix doesn't start due libjxl version

### ISSUE THREAD

**Issue by ecmadrid** [chaotic-aur/packages#3355]
### Packages:

https://aur.archlinux.org/packages/pix

### Latest chaotic version

3.4.3-1

### What happens?

Pix app doesn't start because it's compiled against libjxl 0.10 but version in Arch repositories (extra) is 0.11.0-1

### What is expected to happen?

Pix  starts

**Comment by xiota** [comment]
```
==> Finished making: pix 3.4.3-1.1 (Wed 16 Oct 2024 04:56:44 PM CEST)
```
