### ISSUE TITLE
[Rebuild] hyprland-git

### ISSUE THREAD

**Issue by NoDwen** [chaotic-aur/packages#3356]
### Packages:

https://aur.archlinux.org/packages/hyprland-git

### Latest chaotic version

0.44.0.r46.0baf166d-1

### Reason for rebuild

Outdated. Builded from aur now 0.44.0.r69.6e0aadc5-1

### Logs

https://builds.garudalinux.org/logs/logs.html?timestamp=1729661855771&id=hyprland-git

### Builds?

To update, I used paru -S --overwrite "/usr/share/*" aur/hyprland-git, because I had the same issue: https://aur.archlinux.org/packages/hyprland-git#comment-994946

**Comment by asiantuntija** [comment]
Missing hyprland-protocols-git package for build dependencies. Not building atm

**Comment by xiota** [comment]
I've been waiting to rebuild for indication that the conflicting files issue is resolved.  I'll look at the hypr* packages this weekend.
