### ISSUE TITLE
[Rebuild] ttf-material-symbols-variable-git

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#3361]
### Packages:

https://aur.archlinux.org/packages/ttf-material-symbols-variable-git

### Latest chaotic version

latest

### Reason for rebuild

`ttf-material-symbols-variable-git` seems now missing from Chaotic. No GH issues related to its deletion have been found.

**Comment by D3vil0p3r** [comment]
Sorry for ping @xiota

**Comment by xiota** [comment]
I want to merge another package into this one before re-adding.  Will try to do this week or weekend.

**Comment by D3vil0p3r** [comment]
What is the package you want to merge it to?

**Comment by xiota** [comment]
Want to include the old non-variable fonts as a subpackage because they're based on the same repo.

**Comment by D3vil0p3r** [comment]
Ah ok, so the name of this package will remain the same. So currently it has been removed from Chaotic for this reason I guess
