### ISSUE TITLE
[Request] firefox-globalmenu

### ISSUE THREAD

**Issue by leap0x7b** [chaotic-aur/packages#3362]
### Package:

https://aur.archlinux.org/pkgbase/firefox-globalmenu

### Purpose:

A version of Firefox that supports Mac-like global menus

### Benefits:

Firefox by default doesn't support global menus. This package resolves that issue and makes Firefox look more native on desktop environments with support for global menus such as KDE.

### Copyright:

MPL-2.0

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by dr460nf1r3** [comment]
Didn't we have already `firefox-appmenu`.. which is entirely the same Firefox using the same patches from what I've seen?

**Comment by leap0x7b** [comment]
![image](https://github.com/user-attachments/assets/900621da-1453-4495-bc73-4d923f2d8e36)

**Comment by Technetium1** [comment]
@dr460nf1r3 👀 https://github.com/chaotic-aur/packages/commit/06083a425dae1427a1b57250d42f05f8392467df

**Comment by xiota** [comment]
Inclined to reject.  I don't want to deal with yet another fork.

**Comment by xiota** [comment]
> Was this supposed to be the replacement?

`-globalmenu` is replacement for `-appmenu`.  The appmenu version had some maintenance issues, and some people didn't realize that appmenu = global menu = dbus menu.

**Comment by xiota** [comment]
Rejecting for [aforementioned reasons](https://github.com/chaotic-aur/packages/issues/3362#issuecomment-2425021310).
