### ISSUE TITLE
[Rebuild] cpu-x

### ISSUE THREAD

**Issue by darkblaze69** [chaotic-aur/packages#3363]
### Packages:

https://aur.archlinux.org/packages/cpu-x

### Latest chaotic version

5.0.4-1

### Reason for rebuild

latest  aur version: aur/cpu-x 5.1.0-1

**Comment by xiota** [comment]
```
==> Finished making: cpu-x 5.1.0-1 (Mon Oct 21 19:24:14 2024)
```
