### ISSUE TITLE
[Rebuild] python-vlc

### ISSUE THREAD

**Issue by dreirund** [chaotic-aur/packages#3364]
### Packages:

https://aur.archlinux.org/packages/python-vlc

### Latest chaotic version

`3.0.20123-2`

### Reason for rebuild

Out of date:

AUR package is at version `3.0.21203-1`.

**Comment by xiota** [comment]
```
==> Finished making: python-vlc 3.0.21203-1 (Mon Oct 21 19:15:16 2024)
```
