### ISSUE TITLE
[Rebuild] ttf-twemoji-git

### ISSUE THREAD

**Issue by dreirund** [chaotic-aur/packages#3365]
### Packages:

https://aur.archlinux.org/packages/ttf-twemoji-git

### Latest chaotic version

`15.1.0.r5.ga6909cf-1`

### Reason for rebuild

The `-git` package is a t a new version: Running `makepkg` manually on this gives version `15.1.0.r6.g0dfa4d0-1`.

**Comment by xiota** [comment]
Fails to build.  Flagged.  However, practically, 15.1.0.r6 is just a change to readme that wouldn't affect the font files.

**Comment by xiota** [comment]
@dreirund Look at who the maintainer of that package is.  Please do not annoy maintainers with unnecessary comments notifying them of issues they are already aware of.

**Comment by xiota** [comment]
```
==> Finished making: ttf-twemoji-git 15.1.0.r6.g0dfa4d0-1 (Tue Oct 22 18:27:31 2024)
```
