### ISSUE TITLE
[Bug] plasma5-themes-sweet-full-git

### ISSUE THREAD

**Issue by Heyian** [chaotic-aur/packages#3369]
### Packages:

https://aur.archlinux.org/packages/plasma5-themes-sweet-full-git

### Latest chaotic version

r390.48a9050-1

### What happens?

Since the latest rebuild of r390, I can't install the package. I get the error: 
File /var/cache/pacman/pkg/plasma5-themes-sweet-full-git-r390.48a9050-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (checksum)).

### What is expected to happen?

Checksum pass and able to install package.

### More information

I cleared the cache beforehand to make sure I really got the new package from the Chaotic-AUR.

**Comment by dr460nf1r3** [comment]
Has been bumped, so should be working now.

**Comment by xiota** [comment]
> `File ... is corrupted (invalid or corrupted package (checksum)).`

Need to clear cache (`sudo pacman -Scc`).  Back up "important" packages first.

**Comment by Heyian** [comment]
I confirm that this has fixed the issue. Thx!
