### ISSUE TITLE
[Bug] hypridle: error while loading shared libraries

### ISSUE THREAD

**Issue by haroldojunios** [chaotic-aur/packages#3376]
### Packages:

https://aur.archlinux.org/packages/hypridle-git

### Latest chaotic version

`0.1.3.r0.g918fd78d-1`

### What happens?

The application crashes on start with the message `hypridle: error while loading shared libraries: libsdbus-c++.so.1: cannot open shared object file: No such file or directory`.

### What is expected to happen?

The application starts normally.

### More information

When built from AUR the application runs without error.

**Comment by xiota** [comment]
Should be resolved now.
```
==> Finished making: hypridle-git 0.1.4.r1.g4d2fb9e7-1 (Wed Oct 30 15:17:48 2024)
```

**Comment by haroldojunios** [comment]
Thanks, it's fixed now.
