### ISSUE TITLE
[Request] evince-no-gnome

### ISSUE THREAD

**Issue by rssrcr** [chaotic-aur/packages#3377]
### Package:

https://aur.archlinux.org/packages/evince-no-gnome

### Purpose:

The evince-no-gnome package is a variant of the Evince document viewer specifically designed to operate without any GNOME dependencies. Its primary purpose is to provide users with a lightweight option for viewing documents, particularly in environments where GNOME libraries are not desired or needed, for instance: XFCE, Mate, etc ...

### Copyright:

GPL

### Expected Interest:

Many

### Already available?

No

### Unique request?

No

### Banned package?

No

**Comment by xiota** [comment]
Rejecting because prefer not to add (near) duplicates of `extra` packages without strong use cases.  `extra/mupdf` should satisfy need for a light viewer without gnome deps.
