### ISSUE TITLE
[Rebuild] pamac-flatpak

### ISSUE THREAD

**Issue by ecmadrid** [chaotic-aur/packages#3378]
### Packages:

https://aur.archlinux.org/packages/pamac-flatpak

### Latest chaotic version

1:11.7.0-1

### What happens?

breaks with segmentation fault when select "updates". It goes till 95% and breaks with a segmentation fault. This happens to me from today, that evenenig.

### What is expected to happen?

Pamac-flatpak (pamac-manager) runs ok and updates ok.

**Comment by xiota** [comment]
Segfault caused by mismatch between libpamac and pamac.  Should be resolved now.
```
==> Finished making: pamac-flatpak 11.7.2-1 (Mon Nov  4 21:30:46 2024)
```
