### ISSUE TITLE
More missing packages

### ISSUE THREAD

**Issue by ObserverOfTime** [chaotic-aur/packages#338]
The following packages are missing since the migration:

- [x] clion
- [x] graphite-mozilla
- [x] intellij-idea-ultimate-edition
- [ ] lib32-a52dec
- [x] lib32-aom
- [x] lib32-bluez-libs
- [ ] lib32-chromaprint
- [ ] lib32-faac
- [ ] lib32-faad2
- [ ] lib32-fftw
- [ ] lib32-glslang
- [ ] lib32-gssdp
- [ ] lib32-gst-libav
- [ ] lib32-gst-plugins-bad
- [ ] lib32-gst-plugins-ugly
- [x] lib32-gupnp
- [ ] lib32-gupnp-igd
- [ ] lib32-l-smash
- [ ] lib32-lame
- [ ] lib32-libass
- [ ] lib32-libbluray
- [x] lib32-libbs2b
- [ ] lib32-libcdio
- [x] lib32-libdav1d
- [ ] lib32-libdc1394
- [ ] lib32-libdca
- [x] lib32-libde265
- [x] lib32-libdvdnav
- [x] lib32-libdvdread
- [ ] lib32-libexif
- [x] lib32-libfdk-aac
- [x] lib32-libffmpeg
- [ ] lib32-libgme
- [ ] lib32-libkate
- [ ] lib32-liblrdf
- [ ] lib32-libmms
- [ ] lib32-libmpcdec
- [ ] lib32-libmpeg2
- [ ] lib32-libnice
- [ ] lib32-libofa
- [ ] lib32-libplacebo
- [ ] lib32-libsidplay
- [x] lib32-libsrtp
- [ ] lib32-libvmaf
- [x] lib32-libwmf
- [x] lib32-lilv
- [ ] lib32-lv2
- [x] lib32-mjpegtools
- [ ] lib32-ncurses5-compat-libs
- [ ] lib32-neon
- [x] lib32-numactl
- [ ] lib32-opencore-amr
- [x] lib32-openexr
- [ ] lib32-openjpeg2
- [x] lib32-raptor
- [x] lib32-rtmpdump
- [x] lib32-sbc
- [x] lib32-serd
- [x] lib32-shaderc
- [x] lib32-sord
- [ ] lib32-spandsp
- [ ] lib32-spirv-tools
- [x] lib32-sratom
- [ ] lib32-srt
- [ ] lib32-vmaf
- [ ] lib32-webrtc-audio-processing
- [x] lib32-wildmidi
- [x] lib32-x264
- [x] lib32-x265
- [ ] lib32-xvidcore
- [x] lib32-zbar
- [ ] lib32-zvbi
- [x] neovim-nightly-git
- [x] nodejs-nativefier
- [x] pycharm-professional
- [x] syncplay
- [x] tor-browser
- [x] trackma-git
- [x] ttf-ms-fonts
- [x] waifu2x-ncnn-vulkan-git
- [x] winetricks-git
- [x] xxd-standalone

Most of them are dependencies for the gstreamer plugins.

**Comment by Bhooty** [comment]
system-config-samba 
Is also missing

**Comment by ObserverOfTime** [comment]
`waifu2x-ncnn-vulkan-git` seems to be missing still. Perhaps the build failed? :thinking:

**Comment by dr460nf1r3** [comment]
Yep, the package was indeed missing a dep but this went unnoticed when building. Thanks for bringing this to my attention 😄 
When I tried building the lib32's it failed pretty early so the rest couldnt be built either,[ log attached.](https://bin.garudalinux.org/?399b7e36e40c1ebc#FRqBCHXdA7UNuZMNbioCAEp2vKb5DsYE4DcfxL8EHRRj)

**Comment by ObserverOfTime** [comment]
Which lib is that? I'll see if I can build it locally.

**Comment by dr460nf1r3** [comment]
Thats lib32-numactl

**Comment by ObserverOfTime** [comment]
Looks like it depends on `lib32-gcc-libs` but doesn't list it.

**Comment by dr460nf1r3** [comment]
Then this needs to be adressed in the PKGBUILD as we are building in a clean chroot. Looking at the AUR page this has been requested in 2019 already. meh.

**Comment by ObserverOfTime** [comment]
I could maintain a custom PKGBUILD with the dependency until the issue is resolved if you'd like.

**Comment by dr460nf1r3** [comment]
That would for sure be a very good idea if you want the packages in the repo, go for it! :D

**Comment by ObserverOfTime** [comment]
I've published [`lib32-libnuma`](https://aur.archlinux.org/packages/lib32-libnuma) which provides `lib32-numactl`.

**Comment by mixalis1987** [comment]
Did we have expressvpn and expressvpn-gui and expressvpn-gui-gtk before?

**Comment by dr460nf1r3** [comment]
No idea, but theyre added now

**Comment by dr460nf1r3** [comment]
Libraw [broken](https://bin.garudalinux.org/?9e325e6078c34d94#GpRWPkoaTsJiU1iepWSFpoocxGZiM9spbREVZLSVifyk) too, as well as [others ](https://bin.garudalinux.org/?546695d9b6f56787#4GUgR3D5AcYc6hh1mEiuHqQqcAZHMNYKTkwLkzuMkjbD).. o_o

**Comment by ObserverOfTime** [comment]
The `lib32-libraw` build is broken. It's needed by `lib32-imagemagick`, which is a superfluous dependency of `lib32-zbar`, whose build is also broken. So, I published [`lib32-libzbar`](https://aur.archlinux.org/packages/lib32-libzbar) which fixes the build and removes the dependency.

**Comment by robbert-vdh** [comment]
[`emacs-native-comp-git`](https://aur.archlinux.org/packages/emacs-native-comp-git) is also no longer in the repo.

**Comment by ObserverOfTime** [comment]
What's holding the rest of the additions back?
If any package is still broken let me know and I'll see what I can do.

**Comment by dr460nf1r3** [comment]
This seems like a very cumbersome task so I didnt take time for it lately. Sorry 😅

**Comment by ObserverOfTime** [comment]
It looks like `lib32-zbar` and `lib32-numactl` were fixed.
You should switch back to them when you have the time.

**Comment by ukbeast** [comment]
Package `lib32-gst-libav` now requires `lib32-libffmpeg`.
https://aur.archlinux.org/packages/lib32-gst-libav/

**Comment by PedroHLC** [comment]
Note that `neovim-nightly-git` have been removed from AUR

**Comment by ObserverOfTime** [comment]
Any news on the gstreamer packages?

**Comment by PedroHLC** [comment]
> Any news on the GStreamer packages?

Those are really complicated, because of two things:
1. about their dependencies... Taking "lib32-libdav1d" as an example: you'll never find a 32bit application using that through GStreamer, not even inside Wine; and even if you find one, you'll prefer to use a native 64bit build. We would be wasting our resources (as well as the users').
2. Arch provides GStreamer and FFmpeg, while every time one of their dependencies update, they bump the pkgrel from those packages. And, we cannot do the same in Chaotic, at least not without assigning someone to take care of those packages. We would end up breaking our users' setups periodically...

I know that people are interested in those GStreamer packages now, as Proton/Wine uses those in their new mfplat implementation. What I recommend and would instantaneously adopt would be having some kind of `{,lib32-}gst-plugins-mfplat` package, with only the required codecs and dependencies (I would even accept statically built dependencies).

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.

**Comment by D3vil0p3r** [comment]
What is the difference between `tor-browser-bin` (the old `tor-browser`) of Chaotic AUR and `torbrowser-launcher` that is in Extra repo?

**Comment by xiota** [comment]
Looks like `torbrowser-launcher` downloads the Tor Browser tarball to the user's cache folder, while `tor-browser-bin` includes the tarball in the package.  They both unpack into the user home directory when run because Tor Browser needs write permissions into its program folder.  Maybe `tor-browser-bin` should be dropped?

**Comment by D3vil0p3r** [comment]
It is what I'm thinking... `torbrowser-launcher` has also the tor browser launcher settings as separated .desktop file.

**Comment by PedroHLC** [comment]
> should be dropped?

LGTM
