### ISSUE TITLE
[Request] dtrx

### ISSUE THREAD

**Issue by LukeShortCloud** [chaotic-aur/packages#3381]
### Package:

https://aur.archlinux.org/packages/dtrx

### Purpose:

`dtrx` helps take the guess work out of extracting archives. You can run `dtrx $archive` and it'll determine the format. Then it'll automatically use the correct tool(s) to extract it. This works with simple archives such as `.zip` (unzip) and even less obvious ones like `.deb` (ar)  and `.rpm` (cpio) packages.

### Benefits:

For new Linux users or even seasoned Linux users who can't be bothered to learn every single tool for the job, this helps them handle archived and/or compressed files very easily.

### Building:

`makepkg`

### Copyright:

GPL v3.0

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

### More information:

It's a small and simple package that only takes a few seconds to build and package.

**Comment by xiota** [comment]
`bsdtar` has most of the functionality and already included with Arch.

**Comment by LukeShortCloud** [comment]
`bsdtar` only works with tape archives. It errors out on anything else. However, I tested `7z` and it handled everything I threw at it: ar, cab, cpio, dmg, rar, compressed tars, and zip. I knew `7z` supported many formats and I didn't realize it was all this. Thanks for the hint! I'll go ahead and close this out.
