### ISSUE TITLE
[Request] iio-hyprland-git

### ISSUE THREAD

**Issue by Ceye4n** [chaotic-aur/packages#3388]
### Package:

https://aur.archlinux.org/packages/iio-hyprland-git

### Purpose:

A fork of okeri/iio-sway for Hyprland

Listens to iio-sensor-proxy and automatically changes Hyprland output orientation

### Benefits:

automatically rotates screen on hyprland for tablets and convertibles

### Copyright:

GPL3

### Expected Interest:

Few

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Package is very bad.  Has many problems, including `pkgbase` does not match `pkgname`.

**Comment by xiota** [comment]
Package was improved.  Added with remaining issues fixed in interfere.

**Comment by Ceye4n** [comment]
thx for the quick work, everything works, tho the AUR package turned out to be missing `jq` as dependency (will likely be listed soon)

**Comment by xiota** [comment]
Updated interfere and notified maintainer.
