### ISSUE TITLE
[Rebuild] nekoray

### ISSUE THREAD

**Issue by dreirund** [chaotic-aur/packages#3393]
### Packages:

https://aur.archlinux.org/packages/nekoray

### Latest chaotic version

`4.0.beta4-1`

### Reason for rebuild

Linked against outdated and thus non-existent `libprotobuf.so.28.2.0`:  
`nekobox`:  
```
/usr/lib/nekobox/nekobox: error while loading shared libraries: libprotobuf.so.28.2.0: cannot open shared object file: No such file or directory
```

Currently, there is `/usr/lib/libprotobuf.so.28.3.0`.

**Comment by xiota** [comment]
```
==> Finished making: nekoray 4.0.beta4-1.1 (Mon Nov 25 22:54:42 2024)
```
