### ISSUE TITLE
[Rebuild] across

### ISSUE THREAD

**Issue by dreirund** [chaotic-aur/packages#3394]
### Packages:

https://aur.archlinux.org/packages/across

### Latest chaotic version

`0.1.3-4.1`

### Reason for rebuild

`across` Is built against old and no longer existing `libspdlog`:

`across`:  
`across: error while loading shared libraries: libspdlog.so.1.14: cannot open shared object file: No such file or directory`

`/usr/lib/libspdlog.so.1.15.0` is there.

**Comment by dr460nf1r3** [comment]
Potential candidate for global bump triggers list 👀

**Comment by xiota** [comment]
```
==> Finished making: across 0.1.3-5 (Wed Nov 27 03:03:26 2024)
```
