### ISSUE TITLE
[Request] alvr-nvidia

### ISSUE THREAD

**Issue by ChrisWinters-CA** [chaotic-aur/packages#3395]
### Package:

https://aur.archlinux.org/packages/alvr-nvidia
https://aur.archlinux.org/packages/alvr-git

### Purpose:

The Chaotic AUR does already contain a binary for the alvr package, however as described in the Arch Linux section of the [ALVR Installation Guide](https://github.com/alvr-org/ALVR/wiki/Installation-guide) this package is only for users with AMD graphics cards. The alvr-nvidia package is specifically for users with Nvidia GPUs. The alvr-git package is optional as it is an unstable version build from the latest master branch, but I consider the alvr-nvidia package to be a must have since you've already accepted and built the version for AMD GPUs.

### Benefits:

This will allow users with Nvidia GPUs to play VR games on Linux

### Copyright:

MIT

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Added `alvr-nvidia`.  Not adding `-git` because there doesn't seem to be any pressing need for it.

**Comment by xiota** [comment]
Dropping because no longer in AUR.  Metrics 45.
