### ISSUE TITLE
[Request]  lightly-qt6

### ISSUE THREAD

**Issue by sintaulsiam** [chaotic-aur/packages#3396]
### Package:

https://aur.archlinux.org/packages/lightly-qt6

### Purpose:

Its one of the popular modern application style for qt or kde apps

### Benefits:

This is now the active fork of origial lightly. Development is on going and has the latest release. Its staring newly unlike the other forks. 

### Building:

makepkg -si 

### Copyright:

GPL2

### Expected Interest:

Many

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by sintaulsiam** [comment]
hello why is the request not getting any tags

**Comment by sintaulsiam** [comment]
@Technetium1

**Comment by xiota** [comment]
Someone more knowledgeable has said:

> the good package for round corners in kwin is [`kwin-effect-rounded-corners-git`] @alexjp

Also, `lightly-kf6-git` is pending switch to different fork.

**Comment by sintaulsiam** [comment]
> Someone more knowledgeable has said:
> 
> > the good package for round corners in kwin is [`kwin-effect-rounded-corners-git`] @alexjp
> 
> Also, `lightly-kf6-git` is pending switch to different fork.

What!!!

**Comment by xiota** [comment]
I thought the purpose was for rounded corners.  Either way, `lightly-git` will be updated soon.

**Comment by alexjp** [comment]
@xiota sorry, I was mistaken and confused lightly-qt6 with lightlyshaders.

it was dumb on my part :(

**Comment by xiota** [comment]
There are too many packages too keep track of.
```
$ pacman -Sql chaotic-aur | wc -l
3157
```

**Comment by sintaulsiam** [comment]
So are we getting this package or Who knows when and which fork  lighlty-git will choose.

**Comment by xiota** [comment]
If primary issue is time, lightly-git will be updated soon, most likely to the Bali10050 fork.

**Comment by sintaulsiam** [comment]
Yeah plz just check out the package I requested,  it might be based on Bali10050 :(

**Comment by sintaulsiam** [comment]
Ok guys no more need of this request. I will compile the package myself if needed they are now offering bin package for arch and I have already requested for a bin package in the aur. close this issue.

**Comment by xiota** [comment]
`lightly-git` has been updated.
