### ISSUE TITLE
[Request] cake-wallet-bin

### ISSUE THREAD

**Issue by coxde** [chaotic-aur/packages#3397]
### Package:

https://aur.archlinux.org/packages/cake-wallet-bin

### Purpose:

Cake Wallet is a noncustodial multi-currency wallet. It supports many different coins including Monero which is a privacy focused project.

### Copyright:

MIT

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by Technetium1** [comment]
I'm not sure adding this will benefit more than a couple people

**Comment by xiota** [comment]
I'd prefer not to add this.  It's a -bin package, so reasonably easy for users to install and update with an AUR helper.
