### ISSUE TITLE
[Request] numbat-git

### ISSUE THREAD

**Issue by YuugataShinonome** [chaotic-aur/packages#3401]
### Package

https://aur.archlinux.org/packages/numbat-git

### Purpose

The design of the program is really interesting and perfectly fulfills the design objective of a scientific calculator.  I major in Physics, and I find it to be a convenient tool for performing calculations in the lab. The tool has all the features I need for this specific scenario. It's offline, simple, fast, straightforward, and, most importantly, correct. The bc program is frustrating to use, and some Python packages even produce incorrect results.

### License

MIT

**Comment by xiota** [comment]
How good/useful is this really?  Python, bc, bash, etc are available on every installation and have ability to do calculations and are.

Why did I spend have to learn unit conversions in school if a program would just do it for me?  Looks like Black-Scholes equation is missing.

**Comment by Technetium1** [comment]
There is definitely little interest in something like this, but it seems useful to at least the one who requested. <3mb is reasonable.

**Comment by xiota** [comment]
The AUR package also has some minor issues / annoyances.  For instance, two copies of source are downloaded, while only one appears to be used.  Downloads have incorrect filename / extension.  Provides is set unnecessarily.  They shouln't affect building, and would be easier to overlook if the program is sufficiently useful.

So I was hoping for an answer to, 'Why not use an existing commonly available utility?'  Existing utilities have various drawbacks, and `numbat` would more useful if it addresses any of them.  However, as far as I can tell, it is yet another programming language.  From examples on the webpage, some features require typing unicode symbols.  Easiest way to look them up would be with a search engine, but many search engines support performing calculations directly.

**Comment by YuugataShinonome** [comment]
Hello, sorry for the late reply. I major in Physics, and I find it to be a convenient tool for performing calculations in the lab. The tool has all the features I need for this specific scenario. It's offline, simple, fast, straightforward, and, most importantly, correct. The bc program is frustrating to use, and some Python packages even produce incorrect results.

The design of the program is really interesting and perfectly fulfills the design objective of a scientific calculator. For example, it gives an error message when typing sin(5 Bq) because this expression is essentially meaningless in physics. Additionally, when typing (5 Bq)^2, it informs you that the dimension of the result is Time⁻², which is both insightful and heuristic.

**Comment by xiota** [comment]
@YuugataShinonome Thanks for the response.  The use case is helpful, and I've edited the request to include it.  I plan to run a test build soon and will ask the maintainer to update the package.

**Comment by xiota** [comment]
@YuugataShinonome Would the git package be satisfactory ([`aur/numbat-git`](https://aur.archlinux.org/packages/numbat-git))?  It can be added without requesting changes or adding interfere.

**Comment by xiota** [comment]
For anyone interested, `qalc` from `extra/libqalculate` may be a useful alternate.  It does not show an error for `sin(5 Bq)`, but can solve equations.
