### ISSUE TITLE
[Request] mcpelauncher-msa-ui-qt-git

### ISSUE THREAD

**Issue by yigitsalar** [chaotic-aur/packages#3403]
### Package:

[mcpelauncher-msa-ui-qt-git](https://aur.archlinux.org/packages/mcpelauncher-msa-ui-qt-git)

### Purpose:

It is an optional dependency of existing `mcpelauncher-ui-git` package. It is required for authentication for versions pre-1.16.2.

### Copyright:

[MIT, GPL-3.0-only, Unlicensed](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mcpelauncher-msa-ui-qt-git)

### Expected Interest:

Half

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by yigitsalar** [comment]
Interest might stay a little below half.

**Comment by Technetium1** [comment]
Is this _actually_ useful anymore? https://github.com/minecraft-linux/msa-manifest
> Xbox live integration of Minecraft Bedrock 1.16.20 and later is mostly handled inside the native game binary itself (official Xbox Authentication Library) and no longer requires this project.

**Comment by xiota** [comment]
I would prefer not to add because slippery slope to be flooded with requests to support old versions of stuff.

**Comment by yigitsalar** [comment]
> Is this _actually_ useful anymore? https://github.com/minecraft-linux/msa-manifest
> 
> > Xbox live integration of Minecraft Bedrock 1.16.20 and later is mostly handled inside the native game binary itself (official Xbox Authentication Library) and no longer requires this project.

It might be important for backwards compatibility

**Comment by Technetium1** [comment]
It's not right for us to add packages such as this one, which aren't actually _required_ for core functionality. I checked and Bedrock 1.16.20 is from Aug 11, 2020. That's rather far outside the window to be useful for most users.

**Comment by yigitsalar** [comment]
> It's not right for us to add packages such as this one, which aren't actually _required_ for core functionality. I checked and Bedrock 1.16.20 is from Aug 11, 2020. That's rather far outside the window to be useful for most users.

Okay, I got it.
