### ISSUE TITLE
[Rebuild] rustdesk-bin

### ISSUE THREAD

**Issue by anasgets111** [chaotic-aur/packages#3406]
### Packages:

https://aur.archlinux.org/packages/rustdesk-bin

### Latest chaotic version

1.3.3-1

### Reason for rebuild

Outdated, aur version is 1.3.5

**Comment by xiota** [comment]
```
==> Finished making: rustdesk-bin 1.3.5-1 (Sat Dec  7 16:50:22 2024)
```
