### ISSUE TITLE
[Request] docker-rootless-extras

### ISSUE THREAD

**Issue by SansSerif1** [chaotic-aur/packages#3408]
### Package

https://aur.archlinux.org/packages/docker-rootless-extras

### Purpose

This small package provides a runner needed to run Docker daemon as a non-privileged user. It provides a script at `/usr/bin/dockerd-rootless.sh` that does the job. I find this particular package useful because it installs all the dependencies, easily enables the rootless mode and I think it would be quite useful to have access to it without building it from scratch.

### License

Apache

### Submission checklist

- [X] The package is not banned.
- [X] The package is not available in Chaotic AUR or official Arch repos.
- [X] The package has not already been requested.

**Comment by xiota** [comment]
@SansSerif1 Have you tested that this package works as advertised?  Comparison with `podman-docker`?  My understanding is `podman` supports running rootless.
