### ISSUE TITLE
[Request] krename-git

### ISSUE THREAD

**Issue by ghost** [chaotic-aur/packages#3412]
### Package

https://aur.archlinux.org/packages/krename-git

### Purpose

This is a working KF6 version of KRename, not yet available on Arch repositories (that still use Qt5 version).

### License

GPL-3.0-or-later

### Submission checklist

- [X] The package is not banned.
- [X] The package is not available in Chaotic AUR or official Arch repos.
- [X] The package has not already been requested.

**Comment by wld01021993** [comment]
Should I mark this closed?

**Comment by Technetium1** [comment]
@wld01021993 it will be closed after it is added

**Comment by xiota** [comment]
Plan to remove after `extra/krename` is updated to Qt6.
