### ISSUE TITLE
[Request] python-podman-git

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#3414]
### Package

https://aur.archlinux.org/packages/python-podman-git

### Purpose

Python bindings for Podman's RESTful API

### License

Apache

### Submission checklist

- [X] The package is not banned.
- [X] The package is not available in Chaotic AUR or official Arch repos.
- [X] The package has not already been requested.

**Comment by xiota** [comment]
Will add, but this is an unused depends.  May drop if it has problems or insufficient usage.

**Comment by xiota** [comment]
For anyone interested, metrics 15.
