### ISSUE TITLE
[Request] coreutils-selinux

### ISSUE THREAD

**Issue by D3vil0p3r** [chaotic-aur/packages#3415]
### Package

https://aur.archlinux.org/packages/coreutils-selinux

### Purpose

The basic file, shell and text manipulation utilities of the GNU operating system with SELinux support

### License

GPL-3.0-or-later, GFDL-1.3-or-later

### Submission checklist

- [X] The package is not banned.
- [X] The package is not available in Chaotic AUR or official Arch repos.
- [X] The package has not already been requested.

**Comment by xiota** [comment]
@D3vil0p3r Please put all the selinux-related packages together in one request.

**Comment by D3vil0p3r** [comment]
@xiota I guess I will close all of them. I just discovered https://github.com/archlinuxhardened/selinux and the packages are already provided by a dedicated Arch selinux mirror.

**Comment by D3vil0p3r** [comment]
@xiota @Technetium1 sorry for the tag. I see that `selinux` Arch repository does not provide package `.sig` files, so the packages are not signed and it can arise security concerns. They also report on their README to use `SigLevel = Never` (that is a "paradox" to push for it in a repo of an hardening tool).

I opened an issue ticket for it, but in case they don't go for that, in your opinion should selinux AUR packages be distributed (signed) by Chaotic AUR?

**Comment by xiota** [comment]
@D3vil0p3r There are some potential issues with adding them here.  Will wait for other project to decide whether to add signatures.  Should give them at least until after the winter holidays.
