### ISSUE TITLE
[Rebuild] python packages

### ISSUE THREAD

**Issue by Totti786** [chaotic-aur/packages#3428]
### Packages

Python-related packages.

### Description

`extra/python` updated from 3.12.x to 3.13.x.

**Comment by Ast3risk-ops** [comment]
Every Python package has to be rebuilt due to the recent Python update.

**Comment by xiota** [comment]
Build servers are backlogged right now.  Will bump python packages later.

**Comment by dr460nf1r3** [comment]
Ive seen first failures due to Python versions.. looking at Firefox forks and mach.

**Comment by xiota** [comment]
> Hopefully most of the rebuilds will already be queued.

Looks like `python-*` packages weren't being bumped.  They may be on exclusion list because normally, rebuilds aren't needed except for major updates.

The browsers probably don't need rebuild, as far as python is concerned, because it's used only during build.

**Comment by drjaska** [comment]
Are all packages which have files inside `usr/lib/python3.12/site-packages/` going get rebuilt eventually as of now? Asking if "X package doesn't work" comments are needed or not.

**Comment by xiota** [comment]
Eventually all packages with files located in `/usr/lib/python3.12/site-packages/` will be rebuilt.

Some packages have python version hard coded.  AUR maintainers would need to be notified.

Some packages link the python library.  They tend to be more difficult to find.  Comment here after a few days with packages that missed being bumped.

`-bin` packages need upstream rebuild.  However, mentioning them here would make watching their progress easier.

**Comment by xiota** [comment]
Packages pending, most likely need upstream updates.

- [ ] chirp-next # python-future
- [ ] csxcad-git
- [ ] kicad-git
- [ ] libselinux # API change
- [ ] openems-git
- [ ] pjproject
- [ ] python-js2py # python 3.13 bytecode
- [ ] seafile # python-future

**Comment by xiota** [comment]
@thotypous Python modules of `csxcad-git` and `openems-git` have been disabled for now.  Will try to re-enable them in a few months.  (Ping me if they're needed and I forget.)

**Comment by xiota** [comment]
@SolarAquarion Dropped `libselinux` because other selinux related packages had already been dropped a while ago for failure to build.

**Comment by dr460nf1r3** [comment]
Great work as usual @xiota ! <3

**Comment by xiota** [comment]
Closing because relevant packages have been rebuilt.

Comment for any Python 3.12 → 3.13 related issues.
