### ISSUE TITLE
Missing in wps office

### ISSUE THREAD

**Issue by Bhooty** [chaotic-aur/packages#343]
the is required with wps office
for some reason this missed 
https://aur.archlinux.org/packages/ttf-wps-fonts
can u plz include it

**Comment by dr460nf1r3** [comment]
Added to Garuda cluster, this is in fact also needed for our setup-assistant. Thanks for the reminder!

**Comment by Bhooty** [comment]
https://aur.archlinux.org/packages/wps-office-mui-zh-cn/

This is missing 
Can u plz package this too?

**Comment by dr460nf1r3** [comment]
Done
