### ISSUE TITLE
[Rebuild] hyprland-git, aquamarine-git, hyprutils-git

### ISSUE THREAD

**Issue by os-guy** [chaotic-aur/packages#3433]
### Packages

https://aur.archlinux.org/pkgbase/hyprland-git
... https://aur.archlinux.org/pkgbase/hyprutils-git
https://aur.archlinux.org/pkgbase/aquamarine-git

### Description

I think one of theese packages has a missing library, called:
`hyprutils.so.1`
People are mentioning that it's only about Chaotic-AUR.
Especially [Vaxry](https://github.com/vaxerski) (owner, leader and developer of the hyprwm) told that it can be easily fixed by rebuilding it.

Here's a [Reddit Post Mentioning This Issue](https://www.reddit.com/r/hyprland/comments/1hksq1a/libhyprutilsso1_not_found/)
Here's the [Hyprland Issue Report](https://github.com/hyprwm/Hyprland/issues/8825)

**Comment by xiota** [comment]
Bumped and rebuilt.
