### ISSUE TITLE
[request] systemd-cron-next

### ISSUE THREAD

**Issue by ahmubashshir** [chaotic-aur/packages#345]
Please add [systemd-cron-next-git](https://aur.archlinux.org/packages/systemd-cron-next-git/)

**Comment by dr460nf1r3** [comment]
error: target not found: cargo>=0.6.0
Its also flagged out-of-date (2017-10-31)

**Comment by xiota** [comment]
Anyone know the differences, pros, and cons of `systemd-cron` vs `systemd-cron-next`?

**Comment by Technetium1** [comment]
@xiota see [this bit](https://github.com/systemd-cron/systemd-cron-next#rationale), but first notice that `systemd-cron-next` is targeting migration/compatibility for [anacron](https://man.archlinux.org/man/anacron.8.en) and others. The author prefers monolithic service management, so they made a tool that does what they want. Development looks nearly abandoned (or it's just stable now?), so continued packaging likely won't be an issue.
