### ISSUE TITLE
java-p7zip-binding

### ISSUE THREAD

**Issue by Bhooty** [chaotic-aur/packages#356]
optional requirement for filebot 
https://aur.archlinux.org/packages/java-p7zip-binding/

Windscribe VPN
https://aur.archlinux.org/packages/windscribe-cli/

Mullvad VPN
https://aur.archlinux.org/packages/mullvad-vpn/

**Comment by dr460nf1r3** [comment]
Both mullvad-vpn and windscribe-cli are added, java-p7zip fails to compile tho, log [here](https://bin.garudalinux.org/?546df1c3cf3535b1#E58NYnN4jYKY72rivMjAGjt8wTxeoetbwzN29Pr4cQfc).

**Comment by Bhooty** [comment]
thanks :D 

if it doesn't compile can u remove it from filebot as filebot asks if i want to install it as optional
its not required though :)
