### ISSUE TITLE
[request] cheese-git

### ISSUE THREAD

**Issue by juxuanu** [chaotic-aur/packages#357]
https://aur.archlinux.org/packages/cheese-git/

**Comment by dr460nf1r3** [comment]
This one doesnt build because of unknown signature
```
error: python-markdown: signature from "Eli Schwartz <eschwartz@archlinux.org>" is unknown trust
:: File /var/cache/pacman/pkg/python-markdown-3.3.3-2-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
```

**Comment by juxuanu** [comment]
It installs in my computer.

**Comment by dr460nf1r3** [comment]
Interesting. Compiling at the Garuda builder completed succesfully.

**Comment by xiota** [comment]
Dropping because `extra/cheese` is available and low usage.  Metrics 2.
