### ISSUE TITLE
package request

### ISSUE THREAD

**Issue by userofryzen** [chaotic-aur/packages#359]
Before all thanks to all.
To be short, Is it possible to have in your repo the package JRE8 from aur? 
https://aur.archlinux.org/packages/jre8/
I mean the oracle version, I need it for something from my university and icedtea and openjdk 8 can't launch it :(. 

Thanks again and regards!

**Comment by xiota** [comment]
Is this still needed?  Is jre8-openjdk still insufficient?

Metrics 527.

**Comment by userofryzen** [comment]
Remove it if you want. I'll put another issue if I discover some other
website that needs it( I needed it because my university had an old tool
for signing, but no more already )

**Comment by xiota** [comment]
Dropping because appears no longer needed.  Metrics 77.
