### ISSUE TITLE
feature request amdgpu-pro

### ISSUE THREAD

**Issue by userofryzen** [chaotic-aur/packages#360]
The amdgpu pro stack is usefull sometimes so it would be good to have it here to if it's possible. 
I mean the amdgpu pro aur packages like vulkan ones and them dependencies.

Regards again!

**Comment by dr460nf1r3** [comment]
A bit more information like links would be nice, thanks :)

**Comment by userofryzen** [comment]
> A bit more information like links would be nice, thanks :)

https://aur.archlinux.org/packages/opencl-amd/

https://aur.archlinux.org/packages/?O=0&SeB=nd&K=amdgpu-pro&outdated=&SB=n&SO=a&PP=50&do_Search=Ir

![imagen](https://user-images.githubusercontent.com/33232977/104653568-19ffce00-56bb-11eb-83a9-f4249009065a.png)
The black colour shows the packages I sometimes use, the red colour is that I think someone could need. but the most importan ones I think they are the vulkan ones beside the opencl amd other

**Comment by dr460nf1r3** [comment]
- [ ] opencl-amd
- [ ] amdgpu-pro-core-meta
- [ ] amdgpu-pro-libgl
- [ ] amf-amdgpu-pro
- [ ] lib32-amdgpu-pro-libgl
- [ ] lib32-vulkan-amdgpu-pro
- [ ] vulkan-amdgpu-pro
