### ISSUE TITLE
The KDE Git packages are still sort of broken

### ISSUE THREAD

**Issue by kode54** [chaotic-aur/packages#365]
The following issues may or may not be fixable:

`kcoreaddons-git` claims to be 5.71 something, but this appears to be a tagging issue with upstream not tagging any versions past 5.71 rc in the main branch.

`kholidays-git` claims to be fine, but the previous version claimed to be some 17.11.90 version. Apparently this is what upstream tags itself as, so whatever.

`kwindowsystem-git` claims to be version 4.100.0 something, this is also apparently what upstream tags itself as. Great.

The following packages appear to have completely disappeared from the repo, and several existing packages depend on them. They appear to be specific to Manjaro's kde unstable set, and are not in the AUR: `kactivitymanagerd-git` `kirigami2-git` `kquickcharts-git` `qqc2-desktop-style-git` `signon-kwallet-extension-git`

**Comment by dr460nf1r3** [comment]
Still working my way through all these AUR PKGBUILDs, turns out to be quite a time consuming task as many of them are broken. But we are getting there, slowly..

**Comment by dr460nf1r3** [comment]
Most of the stuff is back now & has proper versioning. If there is still something wrong let me know please! :)
