### ISSUE TITLE
lib32-libexif

### ISSUE THREAD

**Issue by Bhooty** [chaotic-aur/packages#366]
These optional packages for crossover are missing

https://aur.archlinux.org/packages/lib32-gstreamer0.10/

https://aur.archlinux.org/packages/lib32-gstreamer0.10-base/

https://aur.archlinux.org/packages/lib32-libexif/

https://aur.archlinux.org/packages/lib32-gsm/

https://aur.archlinux.org/packages/lib32-nss-mdns/

**Comment by dr460nf1r3** [comment]
- [ ] lib32-gsm
- [ ] lib32-gstreamer0.10
- [ ] lib32-gstreamer0.10-base
- [ ] lib32-libexif
- [ ] lib32-nss-mdns

**Comment by dr460nf1r3** [comment]
Both gstreamers are broken, failing to compile ([log](https://bin.garudalinux.org/?5fbcd01c1e6b04b8#BztsJ38XsftCbgjFFkwbNSpeoX8fhPduisY7fUpef96W))
The same for [libexif](https://bin.garudalinux.org/?7ca6e0a9b1e7f9a7#AmM8ARzh8HFHhpmRjZxsdNegWLA745MxYnHpJ9Mhm18B)

**Comment by Bhooty** [comment]
> Both gstreamers are broken, failing to compile ([log](https://bin.garudalinux.org/?5fbcd01c1e6b04b8#BztsJ38XsftCbgjFFkwbNSpeoX8fhPduisY7fUpef96W))
> The same for [libexif](https://bin.garudalinux.org/?7ca6e0a9b1e7f9a7#AmM8ARzh8HFHhpmRjZxsdNegWLA745MxYnHpJ9Mhm18B)

Maybe because there's already a gstreamer with a different version install 
Can u remove the gstreamer optional requirement from crossover then

**Comment by dr460nf1r3** [comment]
Well the PKGBUILD would need fixing which I cant do when adding AUR packages :)

**Comment by Bhooty** [comment]
> Well the PKGBUILD would need fixing which I cant do when adding AUR packages :)

Oww xD 
I installed via the .bin from website later 
Cause wasn't sure if crossover will break or not cause of this optional dependencies 
I think the .bin is better 
Direct install

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.

**Comment by Technetium1** [comment]
Depends on Python2 (#1958). This will be removed.

**Comment by PedroHLC** [comment]
@Technetium1 this does not make sense, this package is native.

**Comment by dr460nf1r3** [comment]
We can't have it if it depends on Python2 though. Is that what you meant?
