### ISSUE TITLE
[Request] Multiple packages

### ISSUE THREAD

**Issue by p-mng** [chaotic-aur/packages#371]
- `duf`
- `godot`
- `ly`
- `multimc5`
- `spotify-tui`
- `ttf-mac-fonts`
- `ttf-ms-fonts`
- `rocketchat-desktop`

Some of these were already included before the "purge". All of them should compile just fine.

**Comment by dr460nf1r3** [comment]
Everything but the mac fonts is available right now, that one fails to download source :)

**Comment by dr460nf1r3** [comment]
Tried it

**Comment by xiota** [comment]
Dropping `multimc5`:
* Out of date.
* Broken.
* Pinned comment on aur page: "It is illegal to redistribute any binaries created with this script because of the upstream project's licensing."
