### ISSUE TITLE
Telegram Comments Disabled?

### ISSUE THREAD

**Issue by EmptyVisual** [chaotic-aur/packages#373]
No longer able to make or view comments (even existing/previous reply comments) to the Chaotic-AUR telegram channel anymore. I'm not sure if this was intentional or switched over with their new channel 'default' policies.

If this was intentional was there a reason for it?

**Comment by PedroHLC** [comment]
It was not intentional, I've tried to set the same group as the discussion group for another channel, and that disabled it.
