### ISSUE TITLE
[request] quixel-bridge

### ISSUE THREAD

**Issue by FaithLV** [chaotic-aur/packages#374]
Could you please add my aur package `quixel-bridge` to repo? :1st_place_medal: 

AUR: https://aur.archlinux.org/packages/quixel-bridge/

**Comment by xiota** [comment]
Dropping because fails to build (hash failure).  The appimage is 414MB.  License details are unknown.

**Comment by Technetium1** [comment]
License is `Epic Content`: https://www.unrealengine.com/en-US/eula/content
