### ISSUE TITLE
[Request] WowUp Addon Manager

### ISSUE THREAD

**Issue by EmptyVisual** [chaotic-aur/packages#375]
WowUp (World of Warcraft Addon Manager) - https://aur.archlinux.org/packages/wowup

**Comment by EmptyVisual** [comment]
At the time of the request, https://www.electronjs.org/ was/is having issues and will result in a 503 error obtaining node-v11.0.2-headers.tar.gz , once that's back up again it should be fine to compile.

**Comment by dr460nf1r3** [comment]
oops, wrong issue referenced 😅
