### ISSUE TITLE
edid-decode-git

### ISSUE THREAD

**Issue by juxuanu** [chaotic-aur/packages#377]
https://aur.archlinux.org/packages/edid-decode-git/

**Comment by xiota** [comment]
Dropping because upstream repo deprecated.  Utility moved to `v4l-utils`.  Will probably be available in next release.  Metrics 615.

**Comment by xiota** [comment]
Re-added as custom package because depends of `hw-probe` and new release of `v4l-utils` is taking too long.  Will re-drop when included in `extra/v4l-utils`.
