### ISSUE TITLE
[Request] Tuxedo-tomte

### ISSUE THREAD

**Issue by nomis6432** [chaotic-aur/packages#379]
I'd like to request a few packages:
[`ckb-next`](https://aur.archlinux.org/packages/ckb-next)
[`osu-lazer`](https://aur.archlinux.org/packages/osu-lazer)
[`tuxedo-control-center`](https://aur.archlinux.org/packages/tuxedo-control-center)
[`tuxedo-keyboard`](https://aur.archlinux.org/packages/tuxedo-keyboard)
[`tuxedo-tomte`](https://aur.archlinux.org/packages/tuxedo-tomte)
Thanks for considering my request :)

**Comment by dr460nf1r3** [comment]
Well, tuxedo-tomte misses but this needs to be fixed by a version update (flagged out of date too)

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.

**Comment by xiota** [comment]
Added custom package `ckb-next-qt6-git`.

Metrics:

* ckb-next # 110

**Comment by xiota** [comment]
Dropped because `ckb-next`  moved to extra with Qt6 support.  Metrics:

* ckb-next # 156
* ckb-next-qt6-git # 36
