### ISSUE TITLE
Masterpdf Editor 5.6

### ISSUE THREAD

**Issue by Bhooty** [chaotic-aur/packages#387]
https://aur.archlinux.org/packages/masterpdfeditor-libs-included/

can u plz add this version and never update this version
I know the latest version is still on repo but this the version which can be activated offline via other way :3 
hope u will consider

**Comment by dr460nf1r3** [comment]
Due to this not being the Arch way (always latest version) we dont add this one. Version can be held back using IgnorePkg. :)

**Comment by Bhooty** [comment]
XD
Ok
Then i package it myself and keep it as backup :3
