### ISSUE TITLE
[Remove] kdisplay, theseus-ship

### ISSUE THREAD

**Issue by misyltoad** [chaotic-aur/packages#388]
### Packages

https://aur.archlinux.org/packages/disman
https://aur.archlinux.org/packages/kdisplay
https://aur.archlinux.org/packages/wrapland
https://aur.archlinux.org/packages/theseus-ship

### Purpose

I have a bunch of kwin-ft packages that used to be on here that are now non upgradable and conflict with the other normal KDE stuff when updating.

Normal kwin is basically unusable for me to work on without really bad latency and missed frames so I can't really upgrade until this is resolved or unless I take the plunge and build like all of KDE from git myself every time which would suck.

### License

LGPL-2.1-only

**Comment by Joshua-Ashton** [comment]
Nice, working here :+1:

**Comment by xiota** [comment]
This was dropped along with other KDE-git packages in #2792

**Comment by xiota** [comment]
For anyone who cares, kwinft rebranded as theseus' ship.  Packages are available for testing:
```
chaotic-aur/disman 0.601.0-0.1
chaotic-aur/kdisplay 6.1.0-1
chaotic-aur/theseus-ship 6.1.0-1
chaotic-aur/wrapland 0.601.0-0.1
```

**Comment by xiota** [comment]
Dropping because fails to build and upstream development seems to have halted around KDE 6.2 (Oct 2024).

Metrics:

* wrapland # 24
* disman # 14
* kdisplay # 7
* theseus-ship # 6
