### ISSUE TITLE
update linux-tkg-bmq

### ISSUE THREAD

**Issue by robson-66** [chaotic-aur/packages#393]
Why isn't linux-tkg-bmq updated, I'm currently running linux-tkg-bmq-sandybridge and it's still at version 5.10.7, and the current version as you know is already 5.10.11. This is Arch Linux not Debian.

**Comment by dr460nf1r3** [comment]
The kernel builder is currently offline due to some issues which means it takes more time to update everything

**Comment by PedroHLC** [comment]
You can look which kernels are currently building in https://t.me/s/chaotic_aur_deploy_log
Our threadripper is offline, while Kitsuna discusses a bug with the BCacheFS creator.

> This is Arch Linux not Debian.
Yeah, you're right. Please ask ArchLinux maintainers to build it then!

I'm doing a kind favor building all the 133 linux-tkg variations in my own 5900X. Thanks to MuQSS, that does not disturb my real work (the one that puts food on my table).
I built all the generics (non-machine-specific) and LTS ones already, now I'm building MuQSS variations, then comes BMQ, then PDS, and for last CFS...

I'll be glad if you're a little more grateful. We're here to help each other saving time, and not serve one desire...
