### ISSUE TITLE
[Request] Emacs pgtk native comp

### ISSUE THREAD

**Issue by FilipKendes** [chaotic-aur/packages#395]
I saw you have emacs-native-comp-git package, but could you add this one too?
Emacs pgtk native comp
https://aur.archlinux.org/packages/emacs-pgtk-native-comp-git/

Thank you for this repo, It helps a lot with slower laptops/PCs

**Comment by xiota** [comment]
Dropping because incompatible with new build system.  Also, maintainer recommends switching to `extra/emacs-wayland`.
