### ISSUE TITLE
[Request] p7zip-gui

### ISSUE THREAD

**Issue by MANICX100** [chaotic-aur/packages#396]
Please can you pre-build the below package integrates far nicer and with higher performance vs running the windows version of 7-zip in WINE.

https://aur.archlinux.org/packages/p7zip-gui/

**Comment by dr460nf1r3** [comment]
This wont build due to missing dependency "yasm". The AUR provided package yasm-git fails to compile with error message `"Standart (ANSI/ISO C89) header files are required"`
Is this something missing in makedepends?

**Comment by Bhooty** [comment]
i also want it :)

**Comment by dr460nf1r3** [comment]
Turns out yasm just had to be added to makedepends (even though it was already present in makedepends_x64_86)

**Comment by PedroHLC** [comment]
> Turns out yasm just had to be added to makedepends (even though it was already present in makedepends_x64_86)

Sorry, this is a flaw in chaotic's toolbox, probably very easy to fix.
