### ISSUE TITLE
System freeze when trying to minimize Plasmafox on Wayland

### ISSUE THREAD

**Issue by TheHooly** [chaotic-aur/packages#398]
My system repeatedly froze when hitting "minimize"

OS: Arch Linux
Release: 84.0.2-2 from the chaotic-aur
Kernel: 5.10.7-111-tkg-pds-zen2
Desktop: plasma-desktop 5.20.5-2 + plasma-wayland-session

Hardware:
CPU: Ryzen 7 5800X
GPU: Radeon RX 5700XT
RAM: 16GB DDR4-4000

**Comment by dr460nf1r3** [comment]
Not sure, but this probably is something to be reported at the [plasmafox repo](https://github.com/torvic9/plasmafox)

**Comment by TheHooly** [comment]
I've posted here, because their latest release on GitHub is 84.0.2-1, while the version in the repo is 84.0.2-2

**Comment by dr460nf1r3** [comment]
Closed as this is a confirmed Plasmafox bug.
