### ISSUE TITLE
[Request] ardour-git

### ISSUE THREAD

**Issue by Tremeschin** [chaotic-aur/packages#408]
It was a package I used on a daily basis from chaotic-aur _before the storm_., it's a FOSS Digital Audio Workstation.

`ardour-git` is about 600 TUs of a C++ code, compiles in about 20 minutes on entry / intermediate level Ryzen CPU so shouldn't have a big time hit on chaotic's cluster.

**Comment by xiota** [comment]
Planning to drop because:

* Fails to build.
* Devs don't use github to track issues.
    * I don't want to create a new account to report issues.
    * Search functionality isn't very good, so can't figure out whether current problem has already been reported.
* `extra/ardour` is available.

Metrics 70

**Comment by Tremeschin** [comment]
No problem!, I don't even remember requesting this (2021), and I'm not using ardour for a wihle now 🙂
