### ISSUE TITLE
[Broken Packages (?)] Various plasma-git

### ISSUE THREAD

**Issue by vickyorlo** [chaotic-aur/packages#410]
When trying to update my system with kwinft-git and other plasma-git packages installed, these errors pop up:

`error: failed to commit transaction (conflicting files)
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kwidgetsaddons-git' and 'kcoreaddons-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kwidgetsaddons-git' and 'kjobwidgets-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kwidgetsaddons-git' and 'kconfig-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kwidgetsaddons-git' and 'kcompletion-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kwidgetsaddons-git' and 'ki18n-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kwidgetsaddons-git' and 'kdbusaddons-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kwidgetsaddons-git' and 'kauth-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kwidgetsaddons-git' and 'kguiaddons-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kwidgetsaddons-git' and 'kitemviews-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kcoreaddons-git' and 'kjobwidgets-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kcoreaddons-git' and 'kconfig-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kcoreaddons-git' and 'kcompletion-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kcoreaddons-git' and 'ki18n-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kcoreaddons-git' and 'kdbusaddons-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kcoreaddons-git' and 'kauth-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kcoreaddons-git' and 'kguiaddons-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kcoreaddons-git' and 'kitemviews-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kjobwidgets-git' and 'kconfig-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kjobwidgets-git' and 'kcompletion-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kjobwidgets-git' and 'ki18n-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kjobwidgets-git' and 'kdbusaddons-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kjobwidgets-git' and 'kauth-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kjobwidgets-git' and 'kguiaddons-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kjobwidgets-git' and 'kitemviews-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kconfig-git' and 'kcompletion-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kconfig-git' and 'ki18n-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kconfig-git' and 'kdbusaddons-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kconfig-git' and 'kauth-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kconfig-git' and 'kguiaddons-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kconfig-git' and 'kitemviews-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kcompletion-git' and 'ki18n-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kcompletion-git' and 'kdbusaddons-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kcompletion-git' and 'kauth-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kcompletion-git' and 'kguiaddons-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kcompletion-git' and 'kitemviews-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'ki18n-git' and 'kdbusaddons-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'ki18n-git' and 'kauth-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'ki18n-git' and 'kguiaddons-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'ki18n-git' and 'kitemviews-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kdbusaddons-git' and 'kauth-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kdbusaddons-git' and 'kguiaddons-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kdbusaddons-git' and 'kitemviews-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kauth-git' and 'kguiaddons-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kauth-git' and 'kitemviews-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kguiaddons-git' and 'kitemviews-git'
`

This might be a problem with my installation, as the update is also trying to replace `knewstuff` with `chaotic-aur/knewstuff-git`, which sounds like something that should have happened a long time ago. Though, if I am in fact suffering of a partial upgrade, I would very much like some pointers in how to fix the system.

**Comment by IslandC0der** [comment]
I have now (hopefully) fixed this, the culprit was ` sip4`.

**Comment by vickyorlo** [comment]
Did a cache clean and re-downloaded, we're getting somewhere but a few packages still have this issue:

`/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kcoreaddons-git' and 'kjobwidgets-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kcoreaddons-git' and 'kconfig-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kcoreaddons-git' and 'kcompletion-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kjobwidgets-git' and 'kconfig-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kjobwidgets-git' and 'kcompletion-git'
/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kconfig-git' and 'kcompletion-git'
`

**Comment by IslandC0der** [comment]
It seems like `kjobwidgets-git` and `kcompletion-git` still didn't get updated, the `$pkgrel` on chaotic is still `1`, but on the AUR it's `2`. Basically, I didn't change the `$pkgver` (only the `$pkgrel`) when committing to the AUR, because there hadn't been any new commits on those KDE repos ever since. So it seems like maybe the `$pkgrel` change didn't get detected by chaotic, hence no recompiling took place.

For the other ones, running `pacman -Si chaotic-aur/{kconfig,kcoreaddons}-git`, the `$pkgver` shows as the latest (the one that supposedly fixed that issue), but the build dates are from before I uploaded that version to the AUR.
If I had to guess, I would say the `$pkgver` got updated, but the packages didn't get recompiled (`makepkg` used the previous `$srcdir`, which still contained that problematic file).

Any ideas @dr460nf1r3 and @PedroHLC?

**Comment by dr460nf1r3** [comment]
Let me try to build this manually to get logs later 👀

**Comment by vickyorlo** [comment]
Almost there: 

`/usr/lib/python3.9/site-packages/PyKF5/__init__.py exists in both 'kcoreaddons-git' and 'kconfig-git'`

Probably gonna have to be rebuilt manually too.

**Comment by dr460nf1r3** [comment]
Alright. Hope its fixed now! Also need to investige why these didnt build automatically (daily)

**Comment by vickyorlo** [comment]
Yep, now it goes through, thanks a lot! Just gonna have to deal with a bigger update than I usually do now. Closing.
