### ISSUE TITLE
unreal-engine package is broken

### ISSUE THREAD

**Issue by OnikenX** [chaotic-aur/packages#413]
happerenly it is corrupted when checking with the pgp key can you build it again?

**Comment by dr460nf1r3** [comment]
To clarify, does the issue still persist with:

> sudo pacman -Syu unreal-engine

?

**Comment by PedroHLC** [comment]
It's indeed corrupt in server-side:
```
pedrohlc@garuda-build /s/h/r/c/x86_64> gpg --verify unreal-engine-4.25.4-3-x86_64.pkg.tar.zst.sig
gpg: assuming signed data in 'unreal-engine-4.25.4-3-x86_64.pkg.tar.zst'
gpg: Signature made Sat 21 Nov 2020 04:50:30 AM UTC
gpg:                using RSA key EF925EA60F33D0CB85C44AD13056513887B78AEB
gpg: BAD signature from "Pedro Henrique Lara Campos <root@pedrohlc.com>" [unknown]
```

**Comment by PedroHLC** [comment]
Monday, when I'm home, I'll rebuild this one, as it will require me to log in to GitHub during building, and I'm without my 2FA.

**Comment by OnikenX** [comment]
I really recommend an ssh key for login, you can have 2FA and have a convenient way of longing in with the git, anyway thank you very much for the help.

**Comment by PedroHLC** [comment]
> I really recommend an ssh key for login
I do have it, all the users which can build in chaotic's infra to have it :see_no_evil:

**Comment by OnikenX** [comment]
ho yeah, sorry didn't know about it being shared  😖

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.
