### ISSUE TITLE
[Request] CassandraDB

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#415]
Cassandra : https://aur.archlinux.org/packages/cassandra/
Scylla : https://aur.archlinux.org/packages/scylla/ 
Scylla-git : https://aur.archlinux.org/packages/scylla-git/

**Comment by Technetium1** [comment]
* The source for `scylla` cannot be built with Arch's toolchain: https://aur.archlinux.org/packages/scylla#comment-876320
* `scylla` depends on python2, so it would be removed or swapped for a `-bin` version due to #1958
* `scylla-git` no longer exists

**Comment by xiota** [comment]
@dr460nf1r3  Weird problem on v4.  Looks like builds okay, but `namcap` crashes, so it doesn't upload.

**Comment by dr460nf1r3** [comment]
We should make namcap failures non-fatal. I wonder why it fails in the first place though 🤔

**Comment by xiota** [comment]
`namcap` is informational only, so okay to ignore errors.

Could be bug in python module.  Is it a pre-release / git version of namcap?  The output is very different from when I run it locally.

**Comment by dr460nf1r3** [comment]
That's what I was thinking too.

It's the "regular" namcap package from Arch repos. Do you also use [this flag](https://gitlab.com/garuda-linux/tools/chaotic-manager/-/blob/main/builder-container/build.sh?ref_type=heads#L125) to check?

**Comment by xiota** [comment]
I don't use flags.  That explains the different output.

**Comment by xiota** [comment]
The cause of the crash may be non-elf files.
```
strip: Unable to recognise the format of the input file `./usr/share/java/cassandra/sigar-bin/libsigar-ia64-hpux-11.sl'
strip: Unable to recognise the format of the input file `./usr/share/java/cassandra/sigar-bin/libsigar-ia64-linux.so'
strip: Unable to recognise the format of the input file `./usr/share/java/cassandra/sigar-bin/libsigar-ppc-linux.so'
strip: Unable to recognise the format of the input file `./usr/share/java/cassandra/sigar-bin/libsigar-ppc64-linux.so'
strip: Unable to recognise the format of the input file `./usr/share/java/cassandra/sigar-bin/libsigar-ppc64le-linux.so'
strip: Unable to recognise the format of the input file `./usr/share/java/cassandra/sigar-bin/libsigar-s390x-linux.so'
strip: Unable to recognise the format of the input file `./usr/share/java/cassandra/sigar-bin/libsigar-sparc-solaris.so'
strip: Unable to recognise the format of the input file `./usr/share/java/cassandra/sigar-bin/libsigar-sparc64-solaris.so'
```
