### ISSUE TITLE
wine-tkg-staging-fsync-git-6.1.r7.g677b445b-318 Will not show in Lutris anymore

### ISSUE THREAD

**Issue by mixalis1987** [chaotic-aur/packages#416]
Updated to the latest wine-tkg-staging and now the version will not show in Lutris. Reverted to rc6 version and it shows up again.
Did something change when building? Never had this issue before with this package. Maybe the builder can share some insite? 
Thanks.

**Comment by mixalis1987** [comment]
Compiled myself and now it shows in Lutris.

**Comment by PedroHLC** [comment]
> Compiled myself and now it shows in Lutris.
That does not solve the issue itself, so leave it open until I can ping TkG to take a look himself as we're not changing any setting related to that...

**Comment by mixalis1987** [comment]
This issue is closed because it was updated.
