### ISSUE TITLE
[request] choosenim

### ISSUE THREAD

**Issue by drygdryg** [chaotic-aur/packages#419]
https://aur.archlinux.org/packages/choosenim/
Thank you

**Comment by xiota** [comment]
Fails to build.  Problem seems to be upstream `nim`/`nimble`.  The dist module was removed, but references weren't adjusted.  (Search issues at [nim](https://github.com/nim-lang/nim) and [nimble](https://github.com/nim-lang/nimble).)
```
 Installing nimble@0.14.2
   Building nimble/nimble using c backend
/usr/lib/nim/compiler/nimblecmd.nim(18, 39) Error: cannot open file: ../dist/checksums/src/checksums/sha1
```
