### ISSUE TITLE
[request] wpspin

### ISSUE THREAD

**Issue by drygdryg** [chaotic-aur/packages#420]
https://aur.archlinux.org/packages/wpspin/

**Comment by dr460nf1r3** [comment]
Needs fixing in interfere :>

**Comment by drygdryg** [comment]
> Needs fixing in interfere :>

Fixed

**Comment by dr460nf1r3** [comment]
Nice, I just saw you are the maintainer :D Would you please add git to makedepends, thats the only thing missing. 
Available now in repo, will uncomment in the hourly list once git added.

**Comment by drygdryg** [comment]
Fixed it. Sorry for the inconvenience.

**Comment by xiota** [comment]
Dropping because no longer on AUR.  Upstream project was discontinued.  Metrics 2.
