### ISSUE TITLE
[request] unreal-engine-git

### ISSUE THREAD

**Issue by 2str8** [chaotic-aur/packages#421]
https://aur.archlinux.org/packages/unreal-engine-git
the unreal-engine package is abandoned by it's maintainer, so some guy created unreal-engine-git where package contains latest version. thanks!

**Comment by 2str8** [comment]
oh and yet i saw you deleting unreal-engine package because it's broken, so there is even better alternative than abandoned and broken one.

**Comment by PedroHLC** [comment]
As unreal-engine is a 60Gb package, I would prefer to wait for someone to orphan the stable package, otherwise, -git will take 4~5hrs to build daily in any of our clusters...

**Comment by 2str8** [comment]
Package doesn't take code from 'master' branch itself, which is always gets commits. There is a 'release' branch, same as used in `unreal-engine` package. Latest changes to that branch was a while ago, so package should update after major changes like 4.25>4.26, not after every change in code.

**Comment by PedroHLC** [comment]
Sadly the build system tries to create a file in a system directory:
```
which: no msbuild in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
Running system mono, version: 6
WARNING: Project file formats specified via the command line will be ignored when generating
         project files from the editor and other engine tools.

         Consider setting your desired IDE from the editor preferences window, or modify your
         BuildConfiguration.xml file with:

         <?xml version="1.0" encoding="utf-8" ?>
         <Configuration xmlns="https://www.unrealengine.com/BuildConfiguration">
           <ProjectFileGenerator>
             <Format>Make</Format>
           </ProjectFileGenerator>
         </Configuration>
ERROR: Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Security.SecurityException: No access to the given key ---> System.UnauthorizedAccessException: Access to the path '/etc/mono/registry/LocalMachine' is denied. ---> System.IO.IOException: Permission denied
          --- End of inner exception stack trace ---
         at System.IO.FileSystem.CreateDirectory (System.String fullPath) [0x00191] in <efe941bb62534dc3a62ceb1a818964a0>:0
         at System.IO.Directory.CreateDirectory (System.String path) [0x0002c] in <efe941bb62534dc3a62ceb1a818964a0>:0
```

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.
