### ISSUE TITLE
[Remove] arm-linux-gnueabi-binutils, arm-linux-gnueabi-gcc

### ISSUE THREAD

**Issue by lzlrd** [chaotic-aur/packages#422]
https://aur.archlinux.org/packages/arm-linux-gnueabi-binutils

https://aur.archlinux.org/packages/arm-linux-gnueabi-gcc

**Comment by xiota** [comment]
@lazerl0rd Is there still need for these packages?

As far as I can tell, `arm-linux-gnueabi-gcc` has never successfully built on chaotic servers.  Metrics for `arm-linux-gnueabi-binutils` is 9.

**Comment by dr460nf1r3** [comment]
Since we are still missing a response after almost a month, it should be fine to drop them.
