### ISSUE TITLE
[request] linux-mainline-bcachefs

### ISSUE THREAD

**Issue by juxuanu** [chaotic-aur/packages#424]
https://aur.archlinux.org/packages/linux-mainline-bcachefs/

**Comment by Pan00Pernicek** [comment]
would be very nice

**Comment by PedroHLC** [comment]
:thinking: but all of our linux-tkg are in 5.10.13 and have bcachefs enabled.
While, the linux-tkg-cfs have the same scheduler used by the vanilla linux package.

**Comment by Pan00Pernicek** [comment]
oh they have bcachefs enabled?
then this is not needed propably
