### ISSUE TITLE
[request] aarch64-linux-musl, arm-linux-gnueabihf-gcc, arm-linux-gnueabihf-binutils, arm-linux-gnueabihf-musl

### ISSUE THREAD

**Issue by drygdryg** [chaotic-aur/packages#425]
https://aur.archlinux.org/packages/aarch64-linux-musl/
https://aur.archlinux.org/packages/arm-linux-gnueabihf-gcc/
https://aur.archlinux.org/packages/arm-linux-gnueabihf-binutils/
https://aur.archlinux.org/packages/arm-linux-gnueabihf-musl/

**Comment by dr460nf1r3** [comment]
```
configure: error: 
*** These critical programs are missing or too old: GNU ld
*** Check the INSTALL file for required versions.
==> ERROR: A failure occurred in build().
    Aborting...
```
While building `arm-linux-gnueabihf-glibc-headers`, a dependency of the requested packages

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.
