### ISSUE TITLE
QOwnNotes package outdated

### ISSUE THREAD

**Issue by fabianski7** [chaotic-aur/packages#432]
The last update in the repository is on 05/01/2021 and the package version is 21.1.7-1.

Since then, QOwnNotes has been updated three times.
https://github.com/pbek/QOwnNotes/releases
21.1.8 (26-01-2021)
21.2.0 (05-02-2021)
21.2.1 (12-02-2021) - the current version, released today

On the telegram channel, the most recent log is from versions 21.1.2 and the currently available (21.1.7).
https://t.me/chaotic_aur_deploy_log/1517

I did the build from the aur package today and it doesn't seem to have any problems

**Comment by fabianski7** [comment]
https://github.com/chaotic-aur/packages/blob/main/ufscar-hpc/hourly.1.txt#L99

**Comment by dr460nf1r3** [comment]
Weird, building it manually succeeds too 🤔 
I think its due to being in ufscar routine instead of Kitsuna.

**Comment by fabianski7** [comment]
@dr460nf1r3 can you check if the same problem is happening with the material-kwin-decoration-git package? It is also outdated.

**Comment by dr460nf1r3** [comment]
This most likely was the case. UFSCar appearently cant build Qt applications, moved to Kitsuna as well 👍🏻
