### ISSUE TITLE
[Request] ddcui-git and ddcutil-git

### ISSUE THREAD

**Issue by fabianski7** [chaotic-aur/packages#433]
https://aur.archlinux.org/packages/ddcui-git/
https://aur.archlinux.org/packages/ddcutil-git/

**Comment by xiota** [comment]
@fabianski7 Do you still need `-git` versions of these packages?  `extra/ddcutil` is available, and `aur/ddcui` could be added.

**Comment by xiota** [comment]
@fabianski7 Could they be dropped entirely, or would you want `aur/ddcui` to be added?
