### ISSUE TITLE
[request] ffmpeg-full

### ISSUE THREAD

**Issue by juxuanu** [chaotic-aur/packages#435]
https://aur.archlinux.org/packages/ffmpeg-full

Non-git version

**Comment by erkexzcx** [comment]
+1

**Comment by PedroHLC** [comment]
The problem with all FFmpeg packages in AUR is that they use dynamic-linked dependencies, and they crash on any dependency API-breakage.
Unless if the AUR package maintainer promises to bump pkgrel whenever this occurs, we cannot adopt the package and leave it breaking everybody's system.

So, sorry, but we'll be denying this request.

**Comment by xiota** [comment]
@PedroHLC Based on previous comments, `ffmpeg-full` was rejected, but it's somehow in the repo, in a broken state (unsurprisingly).  Unusable because of mismatched libraries, and unable to rebuild because of some configuration or library problem.  Will watch for a little while, but probably eventually drop it.

**Comment by SolarAquarion** [comment]
fffmpeg-full needs auto rebuilds whenever a dependent library is upgraded

**Comment by dr460nf1r3** [comment]
> fffmpeg-full needs auto rebuilds whenever a dependent library is upgraded

We will likely have that in infra 4.0, but for now its not an option we have.

**Comment by xiota** [comment]
Auto rebuild alone won't fix problem because configure script is not detecting a required library.

**Comment by SolarAquarion** [comment]
also, ffmpeg will need patches occasionally.

**Comment by xiota** [comment]
Dropped for confluence of factors, technical and others.
Should not be re-added.
Metrics 412.
