### ISSUE TITLE
[request] theia-electron

### ISSUE THREAD

**Issue by coxackie** [chaotic-aur/packages#437]
here:

https://aur.archlinux.org/packages/theia-electron/

it would be awesome to include!

**Comment by coxackie** [comment]
@dr460nf1r3  many thanks for taking care of this. I am still not getting the package through the repo though. Has been 8 hours. I thought they get built hourly?

**Comment by dr460nf1r3** [comment]
Im sorry, a build error occurred 👀 dont know how to fix this one yet.. A file in sources is not recognized even though it got cloned correctly @PedroHLC

**Comment by coxackie** [comment]
hmmm... no updates here?

**Comment by dr460nf1r3** [comment]
```
==> Making package: theia-electron 1.10.0-1 (Sat 20 Feb 2021 02:30:17 AM PST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
-> Found theia-electron.sh
-> Found package.json
==> ERROR: .yarnclean was not found in the build directory and is not a URL.
```

**Comment by PedroHLC** [comment]
LOL, I'm not copying dotfilea around, this needs a fix in toolbox 👻

**Comment by PedroHLC** [comment]
First, @dr460nf1r3, I fixed this bug months ago and forgot to report it back to you :smile: 

But sadly, we're transiting to a new issues format, so I'll be closing this request.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.
