### ISSUE TITLE
[request] sourcetrail, gdb-multiarch

### ISSUE THREAD

**Issue by drygdryg** [chaotic-aur/packages#442]
https://aur.archlinux.org/packages/sourcetrail
https://aur.archlinux.org/packages/gdb-multiarch

**Comment by xiota** [comment]
sourcetrail is a drop candidate for following reasons:

* Abandoned by original developer
* New maintainer has broken build – fixable, but time consuming
* Low usage, metrics 4 (How many are my own test downloads?)

**Comment by xiota** [comment]
I managed to fix sourcetrail last week, so I suppose it stays.  Metrics 16.

However, `gdb-multiarch` fails to build.  Metrics 17.  Someone flagged 4 days ago.  However, in comments, looks like maintainer is argumentative.  Refused to fix an issue with the package for a year.  So I'm inclined to drop.  gdb for specific architectures are available and can be installed separately, as needed.

**Comment by xiota** [comment]
Dropping `gdb-multiarch` because it will soon be deleted from AUR.
