### ISSUE TITLE
TKG Kernels out of date

### ISSUE THREAD

**Issue by juxuanu** [chaotic-aur/packages#444]
TKG kernels are outdated.
Are you planning on building them or wait for 5.11?

What does this depen on?

**Comment by PedroHLC** [comment]
I think only "bcachesfs" is missing.

**Comment by robson-66** [comment]
I built myself `linux-tkg` 5.11 using `modprobed.db`, that is under my computer and it works very well. Here is the configuration: https://paste.ubuntu.com/p/4Yfzd45Vtt/

**Comment by juxuanu** [comment]
What about 5.10.17 meanwhile?

**Comment by robson-66** [comment]
Kernel 5.10 is moving to LTS.

**Comment by dr460nf1r3** [comment]
Thats a pity! 5.10 causes pretty bad graphical bugs for me which are not solved in 5.11 :(

**Comment by PedroHLC** [comment]
> That's a pity! 5.10 causes pretty bad graphical bugs for me which are not solved in 5.11 :( LTS used to solve this

We can delay our LTS in 5.4 as long as TkG keeps supporting it.

> What about 5.10.17 meanwhile?

Sadly, we are with one less server until UFSCar finishes upgrading RHEL7->8. With that, there aren't enough slots right now for building 5.10.17 -- But I'll build at least the generics one and AMD's Zen1/2 architecture.

**Comment by juxuanu** [comment]
@PedroHLC maybe it's ok to build only the generic ones while you wait for more servers.

**Comment by juxuanu** [comment]
@PedroHLC The LTS ones are also quite out of date: Arch's linux-lts is at 5.10.19-1 while linux-lts-tkg-* are at 5.4.100

**Comment by PedroHLC** [comment]
some people warned us that they have some bugs with 5.10 and not with 5.4, so we're gonna keep 5.4 as LTS for some time (the EOL for 5.4 is still very far)

**Comment by juxuanu** [comment]
Well, it's inconvenient nonetheless because the default compression for the initramfs has changed on Arch. Now 5.4 produces a kernel panic.

Your point is understandable, tho.

**Comment by dr460nf1r3** [comment]
Im one of the guys who have issues with kernel versions > 5.9, really bad visual glitches 😅

**Comment by robson-66** [comment]
@juxuanu
To make older kernels boot without problems you need to edit the `etc/mkinitcpio.conf` file like this 
```
# COMPRESSION
# Use this to compress the initramfs image. By default, zstd compression
# is used. Use 'cat' to create an uncompressed image.
#COMPRESSION="zstd"
#COMPRESSION="gzip"
#COMPRESSION="bzip2"
#COMPRESSION="lzma"
COMPRESSION="xz"
#COMPRESSION="lzop"
#COMPRESSION="lz4"
```
And of course at the end you have to run this command 
`mkinitcpio -P`

**Comment by juxuanu** [comment]
@robson-66 Thanks for your info, although I am aware of this (since I had to deal with the .pacnew). I just wanted to point out, as written, the inconvenience, mostly for people not so knowledgeable about this stuff. New installs will have the default compression and, if they go with an LTS TkG kernel, they will face kernel panics which are not very descriptive of the matter.

**Comment by robson-66** [comment]
although I am aware of this (since I had to deal with the .pacnew).
Personally, when a `pacnew` file appears I remove the `.pacnew` suffix after reviewing it to see what new changes have been made, after deleting the old file of course.

**Comment by PedroHLC** [comment]
Thanks to @lordkitsuna, it's not out-of-date anymore!
