### ISSUE TITLE
[request] kwin with full-screen unredirection patch

### ISSUE THREAD

**Issue by TheLich132** [chaotic-aur/packages#445]
Someone made a patch using kwin-lowlatency code for a vanilla kwin that enables full-screen unredirection: 
[https://gist.github.com/Sporif/7f18d95dd89af8ec386dd1fbbe11bf67](https://gist.github.com/Sporif/7f18d95dd89af8ec386dd1fbbe11bf67)
I have build it and so far it works great and full-screen unredirection works as intended.

Would love to see that in chaotic-aur since kwin build time is quiet long on my PC.

**Comment by dr460nf1r3** [comment]
Got a PKGBUILD for this one?

**Comment by TheLich132** [comment]
Unfortunately not. I can try to make one, but I don't know if it will be any good, because I have never done this.

**Comment by TheLich132** [comment]
I think everything should works correctly, at least it works great for me. Fell free to change anything you would like in the PKGBUILD (like pkgname or anything). Thanks!

[PKGBUILD.txt](https://github.com/chaotic-aur/packages/files/6010288/PKGBUILD.txt)

**Comment by dr460nf1r3** [comment]
Nice work. Available as kwin-fs-redir (cant have another kwin in repo)
