### ISSUE TITLE
[request] spot-client

### ISSUE THREAD

**Issue by coxackie** [chaotic-aur/packages#447]
New spotify client:
https://aur.archlinux.org/packages/spot-client/

**Comment by xiota** [comment]
Dropped `spot-client-git` because development branch is broken, master branch is stuck at 0.3.3.r0, while stable package is at 0.4.0.

**Comment by xiota** [comment]
Dropping because upstream has an unmaintained notice in the readme since Aug 2025.  Prior commit was Nov 2024.

Metrics 17.
