### ISSUE TITLE
request ytfzf-git

### ISSUE THREAD

**Issue by robson-66** [chaotic-aur/packages#448]
https://aur.archlinux.org/packages/ytfzf-git/

**Comment by westofer** [comment]
thanks :D

**Comment by westofer** [comment]
@dr460nf1r3 `ytfzf-git` doesn't exist anymore for some reason. only `ytfzf` exists.  https://aur.archlinux.org/packages/ytfzf/

**Comment by dr460nf1r3** [comment]
Mhm, weird. Anyway, fixed.

**Comment by xiota** [comment]
Dropping because `extra/ytfzf` is available and low usage.  There is only one commit difference between stable and git.  Metrics 3.
