### ISSUE TITLE
[request] add woeusb & woeusb-gui

### ISSUE THREAD

**Issue by 2str8** [chaotic-aur/packages#454]
useful utility to create windows images. woeusb is the latest version, woeusb-gui is depricated gui one. both works fine, so add all of them pls :). 
https://aur.archlinux.org/packages/woeusb/
https://aur.archlinux.org/packages/woeusb-gui/

**Comment by PedroHLC** [comment]
@dr460nf1r3 will handle it

But hey, I recommend you this project instead: https://www.ventoy.net

**Comment by 2str8** [comment]
Thanks for telling me about ventoy! much appreciated! :)
