### ISSUE TITLE
[request] librewolf-dev-wayland

### ISSUE THREAD

**Issue by vnepogodin** [chaotic-aur/packages#456]
https://aur.archlinux.org/packages/librewolf-dev-wayland/

**Comment by dr460nf1r3** [comment]
We decided to not add this right now as we already have a lot of different Firefox versions in repo right now and not enough processing power for more of them :/

**Comment by PedroHLC** [comment]
+1 to @dr460nf1r3 comment, plus we do have `librewolf-wayland-hg` which is the same as a nightly and should include features from `-dev`.

**Comment by vnepogodin** [comment]
> +1 to @dr460nf1r3 comment, plus we do have `librewolf-wayland-hg` which is the same as a nightly and should include features from `-dev`.

`librewolf-wayland-hg` - release build🙃
