### ISSUE TITLE
[Request] emacs-git

### ISSUE THREAD

**Issue by innerout** [chaotic-aur/packages#462]
Hello,
Since chaotic repository already provides emacs packages with native compilation support, it should also provide the [emacs-git](https://aur.archlinux.org/packages/emacs-git/) package, which does not include native compilation. There are times that native-compilation causes bugs, and you are forced to revert to vanilla Emacs.

**Comment by xiota** [comment]
Dropping for poor maintainership.

**Comment by deadcombo** [comment]
What's the issue? If you don't mind.

**Comment by xiota** [comment]
Package is broken, and maintainer has a history of malicious behavior with other packages after being notified that they're broken.  This package will not be be considered to be re-added unless it has a different maintainer or the package is forked.
