### ISSUE TITLE
 [Request] Gnome Material Shell

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#463]
Link : https://aur.archlinux.org/packages/gnome-shell-extension-material-shell-git/

**Comment by ALipAkrohk** [comment]
Why did you close issue?!
Please see this [link](https://material-shell.com/)

**Comment by dr460nf1r3** [comment]
Added it yesterday
![Screenshot_9](https://user-images.githubusercontent.com/12834713/109636756-dfa3a080-7b43-11eb-9e03-869b3ff5f522.png)

**Comment by xiota** [comment]
Dropped because no longer in AUR.  Metrics 11.
