### ISSUE TITLE
Multiple package request

### ISSUE THREAD

**Issue by Edu4rdSHL** [chaotic-aur/packages#469]
Hello, I would love to have the following packages in the repo:

1. [adwaita-qt](https://aur.archlinux.org/packages/adwaita-qt)
2. [lbry-app-bin](https://aur.archlinux.org/packages/lbry-app-bin/)
3. [gajim-git](https://aur.archlinux.org/packages/gajim-git/)
4. [python-nbxmpp-git](https://aur.archlinux.org/packages/python-nbxmpp-git/)
5. [spotify-tray-git](https://aur.archlinux.org/packages/spotify-tray-git/)
6. [vala-panel-appmenu-registrar-git](https://aur.archlinux.org/packages/vala-panel-appmenu-registrar-git/)

Thank you!

**Comment by ALipAkrohk** [comment]
lbry-app-bin (outofdate: 2021/06/26) : https://aur.archlinux.org/packages/lbry-desktop-bin/
lbry-desktop-bin (NewPkg: 2021-06-28) : https://aur.archlinux.org/packages/lbry-desktop-bin/

**Comment by xiota** [comment]
For anyone wondering, `lbry-desktop-bin` uses Electron 17.2.0.
