### ISSUE TITLE
[request] distrho-ports-lv2-git distrho-ports-vst-git

### ISSUE THREAD

**Issue by Tremeschin** [chaotic-aur/packages#470]
We now have [Vitalium synth](https://mastodon.falktx.com/@falktx/105820343678750210) port and it takes quite some RAM to build on 4+ compile threads, also will be progressively updated for a while in the next days, weeks until it gets better Linux support.

The other (`ports-vst`) is because they replace regular `distrho-ports` and I (might) do use some plugins outside the main ones on `ports-lv2`, just in case.

**Comment by dr460nf1r3** [comment]
```
Cloning into 'distrho-extra-lv2'...
done.
==> Starting prepare()...
/home/main-builder/pkgwork/PKGBUILD: line 29: scripts/premake-update.sh: No such file or directory
```

**Comment by Tremeschin** [comment]
Yea just saw this, forget extra-lv2-git looks like not much people use it
