### ISSUE TITLE
Multiple

### ISSUE THREAD

**Issue by Bhooty** [chaotic-aur/packages#471]
https://aur.archlinux.org/packages/filebot/

https://aur.archlinux.org/packages/masterpdfeditor-libs-included/

https://aur.archlinux.org/packages/jellyfin/

https://aur.archlinux.org/packages/sendanywhere/

https://aur.archlinux.org/packages/nitroshare 

https://aur.archlinux.org/packages/feem/

**Comment by dr460nf1r3** [comment]
sendanywhere requires electron8 which is not available appearently

**Comment by Bhooty** [comment]
> sendanywhere requires electron8 which is not available appearently

Oww 
Then can u do the feem then 
Kind of same app but from different developer

**Comment by dr460nf1r3** [comment]
Theyre all up except for the one requiring electron8

**Comment by Bhooty** [comment]
Thanks a lot 🥺

**Comment by xiota** [comment]
Dropping feem because unmaintained and metrics show zero usage.
