### ISSUE TITLE
Multiple packages

### ISSUE THREAD

**Issue by p-mng** [chaotic-aur/packages#473]
- `apostrophe`: markdown editor
- `aic94xx-firmware`: probably one of the most-installed AUR packages
- `dmenu-height`: dmenu with an official patch applied
- `makemkv`: DVD and BR ripping/backup tool
- `j4-dmenu-desktop`: view .desktop entries in dmenu
- `farbfeld`: easy to parse image format

All packages have at least some votes on the AUR and I use all of them so they should build just fine. Thanks in advance, love your project :)

**Comment by xiota** [comment]
Dropping farbfeld because maintainer non-responsive.  Also, while interesting, non-standard image formats are not particularly useful.

**Comment by xiota** [comment]
Dropped makemkv because failure to build.  Upstream website and sources are now gone.

Also: Depends on EOL Qt5.  Demoware requiring periodic key refresh.

Metrics 132.

**Comment by drjaska** [comment]
Please consider adding back makemkv or mention valid alternatives to which users should migrate to. It is AFAIK the only good tool for digitalising Blu-Ray and DVD discs.

- AUR has patches for ffmpeg-9 compatibility and users report that the AUR package works again
- The upstream websites and sources have returned (again after another absence period of the creator :/ )
- EOL Qt5 is a legit downside
- It is fully operational shareware and not some limited demoware once given a bought license key or given a demo key which is valid for a time period which can be spoofed easily with faketime or any other method of changing system time, there isn't a network requirement.
