### ISSUE TITLE
powershell not being updated

### ISSUE THREAD

**Issue by Brueggus** [chaotic-aur/packages#476]
Hi,
the following packages have been updated in AUR recently but the current versions did not yet arrive in the chaotic repos:

- powershell
- optimus-manager
- optimus-manager-qt

Could you have a quick look?

**Comment by PedroHLC** [comment]
Nothing much to do, UFSCar's server is currently being migrated to RHEL8, and Kitsuna was stricken by another bcachefs bug.
We're just temporarily without building servers...

**Comment by Brueggus** [comment]
Ouch :( 
Thanks for the quick response!

**Comment by Brueggus** [comment]
Sorry for being a bit picky here... both `powershell` and `phpstorm-eap` are in `kitsuna-cluster/hourly.txt`. The latter has been added few hours ago and is already available in the repo.

`powershell` was updated to 7.1.2 in AUR on 2021-02-15 but (as far as I can see) chaotic ships 7.1.1.

Are you sure that "UFSCar's server is currently being migrated to RHEL8, and Kitsuna was stricken by another bcachefs bug." is causing this?

**Comment by dr460nf1r3** [comment]
I had a look and the package didnt compile as dotnet dependencies were missing (which are also on the hourly list just above powershell). No idea what was going on there :/
