### ISSUE TITLE
[Request] matrix-mirage and subliminal-git

### ISSUE THREAD

**Issue by BachoSeven** [chaotic-aur/packages#478]
- [matrix-mirage](https://aur.archlinux.org/packages/matrix-mirage/): my favourite desktop Matrix client, 8 AUR votes
- [subliminal-git](https://aur.archlinux.org/packages/subliminal-git/): subtitles downloader, `-git` version because the non-git package is unmaintained, 31 AUR votes

**Comment by dr460nf1r3** [comment]
Sadly both of them have dependencies which do not compile successfully, see the commit for which ones. Does that work on your setup?

**Comment by BachoSeven** [comment]
Well yesterday I compiled both of them succesfully; now I tried installing `python-bulk` by itself and it also fails :/ I will report it to the maintainer and hopefully get it working.
Instead, I could compile `python-simpleaudio` correctly. Could you share the failure log?

**Comment by dr460nf1r3** [comment]
I have submitted the log on the respective AUR page already. Then we got both maintainers notified, thats great :)

**Comment by BachoSeven** [comment]
Sorry for the delay, now I reported it also for `python-bulk`, it's simly a makedepends on `python-pip` missing I think. As soon as that's also resolved I'll post it here so you can try compiling again

**Comment by dr460nf1r3** [comment]
If its a makedepend missing we can easily patch this up, let me have a look..

**Comment by BachoSeven** [comment]
The reason why I didn't realise it yesterday is that `subliminal-git` pulls so many python dependencies, that one of them has jsut got to pull down `python-pip` with it, and so there was no error with `python-bulk`... lol

**Comment by dr460nf1r3** [comment]
Got it all fixed, nice work! :)

**Comment by BachoSeven** [comment]
Thank you!

**Comment by BachoSeven** [comment]
@dr460nf1r3 the maintainer for `python-bulk` responded, so now it should also be fixed downstream fwiw.

**Comment by xiota** [comment]
Dropping `matrix-mirage-git` because [upstream project is dead](https://github.com/mirukana/mirage/issues?q=is%3Aissue+ded).
