### ISSUE TITLE
request: fluffychat

### ISSUE THREAD

**Issue by Joshix-1** [chaotic-aur/packages#480]
https://aur.archlinux.org/packages/fluffychat/

**Comment by dr460nf1r3** [comment]
Guess it would have been to nice if it just worked after fixing makedepends :D 
Seems like it succeeded, but not at the same time, logs [here](https://bin.garudalinux.org/?bfebd492cc53fd29#qyJxLLCpZQpUGCPTBrDzcsmNk8o2zr2Py6fCNqsHudU) @PedroHLC

**Comment by xiota** [comment]
[Build log](https://builds.garudalinux.org/repos/chaotic-aur/logs/fluffychat.log) has some error related to `/opt/flutter` permissions.
```
==> Starting prepare()...
fatal: detected dubious ownership in repository at '/opt/flutter'
To add an exception for this directory, call:

	git config --global --add safe.directory /opt/flutter
rm: cannot remove '/opt/flutter/version': Permission denied
==> ERROR: A failure occurred in prepare().
    Aborting...
```

The directory is owned by a group `flutterusers`:
```
$ ls -lad flutter
drwxrwxr-x 10 root flutterusers 4096 2023-04-06 22:12:47 flutter
```

The [aur page](https://aur.archlinux.org/packages/fluffychat) has a comment, stating:

> I was able to build the package. The problem lies with flutter and not with this package. Just fix the ownership of flutter.
>
>     sudo chown -R $USER:flutterusers /opt/flutter/

Does this need to be fixed with an interfere?

**Comment by dr460nf1r3** [comment]
Yes, this is correct. `nyrna` could be taken as working example: https://github.com/chaotic-aur/interfere/blob/master/nyrna/prepare

**Comment by Technetium1** [comment]
Success!

**Comment by xiota** [comment]
Autoupdating custom package in [interfere](https://github.com/chaotic-aur/interfere/tree/master/fluffychat).
