### ISSUE TITLE
Multiple package request

### ISSUE THREAD

**Issue by Edu4rdSHL** [chaotic-aur/packages#486]
Hello hello, would love to see these packages.

- [mkosi-git](https://aur.archlinux.org/packages/mkosi-git)
- [dnf](https://aur.archlinux.org/packages/dnf/)
- [yum](https://aur.archlinux.org/packages/yum)

Thank you in advance <3

**Comment by Technetium1** [comment]
This depends on python2, so it will be removed. See #1958
