### ISSUE TITLE
request: davinci-resolve-studio

### ISSUE THREAD

**Issue by paperbenni** [chaotic-aur/packages#488]
https://aur.archlinux.org/packages/davinci-resolve-studio

**Comment by ShayBox** [comment]
`davinci-resolve-studio` in chaotic is out of date, and this really don't need to be a package, it's a bin package.

**Comment by xiota** [comment]
Dropping this package because of intensive resource usage and numerous problems with the PKGBUILD that prevent it from building.  See https://github.com/chaotic-aur/packages/issues/2832#issuecomment-1745561051

**Comment by xiota** [comment]
Dropped because of intensive resource usage and numerous problems that prevent it from building.  See https://github.com/chaotic-aur/packages/issues/2832#issuecomment-1745561051
