### ISSUE TITLE
[Request] Pamac-all and Snapd

### ISSUE THREAD

**Issue by maydayv7** [chaotic-aur/packages#491]
I request the [Pamac-all](https://aur.archlinux.org/packages/pamac-all/) package to be added. It depends on [snapd](https://aur.archlinux.org/packages/snapd/) and [snapd-glib](https://aur.archlinux.org/packages/snapd-glib/) from the AUR.

**Comment by dr460nf1r3** [comment]
We removed this about a month back for some reasons, it doesnt really fit in. Almost everything which can be installed via Snap can be found at the AUR so there is no need for Snaps. Start embracing the Arch way 😌

**Comment by PedroHLC** [comment]
There are only two packages I recall saying "no" to add it here, both are too chaotic, even for us, and you got the achievement of putting them in the same issue.

About Snap, you can try searching the same app in AUR, or extract it and use it, make your own PKGBUILD. Either one of these will get you an app much more integrated with your system, will not f*ck your devices boot time, and will be easier to maintain. If you want to sandbox it, take a look at https://wiki.archlinux.org/index.php/security#Sandboxing_applications

**Comment by maydayv7** [comment]
Actually, I only wanted pamac-all as I wanted to manage my flatpak apps, but it depends on snapd.
As for the flatpak app, it isn't on the AUR, so a request to include it on chaotic is not possible.

**Comment by PedroHLC** [comment]
> As for the flatpak app, it isn't on the AUR, so a request to include it on chaotic is impossible.
 
 If the PKGBUILD exists elsewhere, we might be interested in you submitting it to AUR and would love to help you with it.
 If it does not, then it's a little more complicated. But we wouldn't mind helping too. We can't adopt the maintenance of it ourselves.
