### ISSUE TITLE
[Request] xfce4-panel-profiles

### ISSUE THREAD

**Issue by maydayv7** [chaotic-aur/packages#492]
Link: https://aur.archlinux.org/packages/xfce4-panel-profiles/
This app should have been included in the xfce4 group.

EDIT: I'll request it's inclusion in the official Arch repos

**Comment by PedroHLC** [comment]
Ok, if needed before that, feel free to reopen this issue.

**Comment by maydayv7** [comment]
Yes, I would really appreciate it if it was made available on chaotic.
Also, can it somehow be made part of the xfce4/xfce4-goodies metapackage?

**Comment by dr460nf1r3** [comment]
Yep, we can add this via interfere (did this)
