### ISSUE TITLE
[Request] "spotify-snap" to replace regular "spotify" package

### ISSUE THREAD

**Issue by ThePoorPilot** [chaotic-aur/packages#493]
https://aur.archlinux.org/packages/spotify-snap/

This package builds spotify from the snap-based package instead of the debian package. Unfortunately, spotify has stopped updating the debian package(not updated since September 2020) and only release updates to the snap package(or the flatpak, which is based on the snap).

When the spotify-snap AUR package is built it remains compatible with the original spotify package.
As such, the "spotify" package could be replaced with the "spotify-snap" package seamlessly(while keeping the same name).

If this package was only added as "spotify-snap" with the old "spotify" package stilll being in the repository/AUR, it would probably be confusing to users. It would be best to just replace the "spotify" package, because the snap package actually gets updates. Arch is all about keeping your software as up to date as possible! :)

See the forum post I made about this topic here:
https://forum.garudalinux.org/t/unofficial-up-to-date-spotify-package-that-could-be-installed-with-pacman-based-upon-flatpak/5424/

**Comment by dr460nf1r3** [comment]
So there are some modifications in place:
spotify-snap is renamed to spotify to make it less confusing for endusers. 
As followup, spotify-dev is replaced by spotify-edge-snap using replaces=().
