### ISSUE TITLE
[request] deemix + AUR dependencies

### ISSUE THREAD

**Issue by svdmxyz** [chaotic-aur/packages#494]
Could deemix and it's 2 dependencies that are in the AUR please be added? I would really appreciate it! (Compiling only takes a couple of seconds for each package)

https://aur.archlinux.org/packages/deemix/
https://aur.archlinux.org/packages/python-deezer-py/
https://aur.archlinux.org/packages/python-spotipy/

**Comment by PedroHLC** [comment]
Sorry, a "deezer downloader", that would bring us trouble. So I'll be against "deemix".
But those deps are just development libraries and can be used for legal stuff. So, I'll add them.

**Comment by svdmxyz** [comment]
That's understandable, thanks anyway!
