### ISSUE TITLE
request: xen, xen-docs

### ISSUE THREAD

**Issue by ahmubashshir** [chaotic-aur/packages#496]
https://aur.archlinux.org/pkgbase/xen/

**Comment by dr460nf1r3** [comment]
Mhm, Im afraid this wont be able to build at all currently - Compilation fails due to a flag which is incompatible with the latest binutils (read about it on the AUR page). Afaik we dont have the possibility to use the not latest packages.
`the flag is on: src/xen-4.14.1/tools/qemu-xen-build/config-host.mak changing LDFLAGS_NOPIE=-no-pie to LDFLAGS_NOPIE= will also fix the issue.` 
If you provide a PKGBUILD which patches this file there might be a possibility to add this nevertheless :)

**Comment by ahmubashshir** [comment]
Applying no-pie-binutils.patch will fix the error.
* [no-pie-binutils.patch.gz](https://github.com/chaotic-aur/packages/files/6137204/no-pie-binutils.patch.gz)
* [PKGBUILD.patch.gz](https://github.com/chaotic-aur/packages/files/6137207/PKGBUILD.patch.gz)


```diff
# no-pie-binutils.patch
--- a/tools/qemu-xen/configure	2020-10-16 16:53:28.000000000 +0600
+++ b/tools/qemu-xen/configure	2021-03-14 15:42:17.839118054 +0600
@@ -2116,7 +2116,7 @@
 # Check we support --no-pie first; we will need this for building ROMs.
 if compile_prog "-Werror -fno-pie" "-no-pie"; then
   CFLAGS_NOPIE="-fno-pie"
-  LDFLAGS_NOPIE="-no-pie"
+  LDFLAGS_NOPIE=""
 fi
 
 if test "$static" = "yes"; then

# ----------------------------------------------------------------------------------

# PKGBUILD.patch
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -44,6 +44,7 @@ source=(
 	"xen-intel-ucode.hook"
 	"xen-amd-ucode.hook"
 	"xen_4.14.1_fixes.patch"
+	"no-pie-binutils.patch"
 )
 
 
@@ -73,6 +74,7 @@ sha512sums=(
 	'7a832de9b35f4b77ee80d33310b23886f4d48d1d42c3d6ef6f8e2b428bec7332a285336864b61cfa01d9a14c2023674015beb7527bd5849b069f2be88e6500cd'
 	'99921b94a29fa7988c7fb5c17da8e598e777c972d6cae8c8643c991e5ff911a25525345ea8913945313d5c49fecf9da8cc3b83d47ab03928341e917b304370a9'
 	'75c0f3a30c726484b1701ba369ae84e9d4362367a843c5e962945192156b9f15a17b92f9fbf50395e22edc6159e8ceb30d751a7b09944bf5a1a37d0a98c82583'
+	'd7be5643aa86ecbfac12324cd21126183ca8c010f3fb650fed11f049920ccd2569b5166a9b104bb59c54a9def718bc8c41e92fc2cb65c242284222a0b12ebc91'
 )
 
 
@@ -125,6 +127,7 @@ prepare() {
 
 	# mostly from: https://github.com/olafhering/xen/commit/1a1d86fef44444e8e265fd8bc687f8238a0d1615
 	patch -p1 < ../xen_4.14.1_fixes.patch
+	patch -p1 < ../no-pie-binutils.patch
 
 	if [ "${_build_stubdom}" == "true" ]; then

```

**Comment by xiota** [comment]
Planning to drop because fails to build.  Package looks somewhat complicated, so not interested in trying to fix.  Comments on AUR page indicates `xen`  may eventually be added to `extra`.  Metrics 12.
