### ISSUE TITLE
request: thonny, thonny-git, & mu-editor

### ISSUE THREAD

**Issue by ShayBox** [chaotic-aur/packages#497]
https://aur.archlinux.org/packages/thonny/
https://aur.archlinux.org/packages/thonny-git/
https://aur.archlinux.org/packages/mu-editor/

**Comment by xiota** [comment]
Dropping...

* `thonny-git` – Orphaned package that appears to have been unmaintained for years.  No clear benefit over stable package.
* `mu-editor` – Disguised bin package.

Metrics ...

* thonny # 129
* thonny-git # 16
* mu-editor # 8
