### ISSUE TITLE
KDE git packages in the main repository

### ISSUE THREAD

**Issue by sxe** [chaotic-aur/packages#501]
Hi there, 
first of all thanks for providing us with all the packages. I am a long time user of chaotic-aur and really appreciate all the effort you guys put into this!

That being said, since a couple of weeks now I am unable to use chaotic-aur cause the KDE git package are in the same repository than all the other package. I simple don't want KDE git, I am mainly interested in the kernels and nvidia packages (and a couple smaller ones).  

Is there any way to block KDE packages all together? Blocking the group "kf5-git" in pacman.conf for example doesn't work. Maybe an extra repository for KDE git would be a good idea? I would assume I am not the only one with this problem.

Hope this is the right place to ask this. 

Cheers

**Comment by PedroHLC** [comment]
:thinking: But those packages shouldn't touch your system in any way if you don't install them manually. I mean, they shouldn't be offering to install when you do a `pacman -S dolphin kwin`, for example. They are there, but you shouldn't be able to see them except when doing a search (`pacman -Ss`), or explicitly installing them.

**Comment by dr460nf1r3** [comment]
:>

**Comment by PedroHLC** [comment]
>  I would assume I am not the only one with this problem.

Could it be that you put `[chaotic-aur]` before the official repos (core, community, extra) in your `pacman.conf`? It should be placed AFTER them...

**Comment by sxe** [comment]
Yeah well that's what I expected but that's not what's happening. When ever I do a "sudo pacman -Syu"  I get this:

` ~ $  sudo pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 chaotic-aur is up to date
:: Starting full system upgrade...
warning: birdtray-git: local (1.4.r11.g116c855-1) is newer than chaotic-aur (v1.9.0.r73.g045d4fc-1)
resolving dependencies...
looking for conflicting packages...
:: plasma-framework-git and plasma-framework are in conflict. Remove plasma-framework? [y/N] `

The chaotic-aur entry is at the very end of my pacman.conf. No idea why this is happening.

**Comment by PedroHLC** [comment]
I just tried installing `plasma-framework` here, and it doesn't ask for a replacement with `-git`.
Could it be that some other `-git` package that you have installed, now depends on `plasma-framework-git`?

**Comment by sxe** [comment]
Dang you were right, thanks!
I had `kscreenlocker-git` installed for some reason. I replace it with `kscreenlocker` and now it works. 
I am sorry for having wasted your time. 

Have a good day guys.
