### ISSUE TITLE
lightcord-bin doesnt got updated

### ISSUE THREAD

**Issue by LeSnake04** [chaotic-aur/packages#503]
Because bad version naming by the maintainer, lightcord-bin doesn't got updated (The version name change is considered a downgrade by pacman). I waited several days

aur/lightcord-bin 0.1.5-1 (+7 1.69) (Installed)
    A simple - customizable - Discord Client
chaotic-aur/lightcord-bin dev-4 (117.5 MiB 261.7 MiB) (Installed: 0.1.5-1)
    A simple - customizable - Discord Client

**Comment by dr460nf1r3** [comment]
Turns out you found a package which wasnt in the package list! Anyway, its updated now :)
