### ISSUE TITLE
[Request] ffmpeg-headless

### ISSUE THREAD

**Issue by lazerl0rd** [chaotic-aur/packages#506]
https://aur.archlinux.org/packages/ffmpeg-headless

**Comment by PedroHLC** [comment]
The problem with all FFmpeg packages in AUR is that they use dynamic-linked dependencies, and they crash on any dependency API-breakage.
Unless if the AUR package maintainer promises to bump pkgrel whenever this occurs, we cannot adopt the package and leave it breaking everybody's system.

So, sorry, but we'll be denying this request.

**Comment by lazerl0rd** [comment]
> The problem with all FFmpeg packages in AUR is that they use dynamic-linked dependencies, and they crash on any dependency API-breakage.
> Unless if the AUR package maintainer promises to bump pkgrel whenever this occurs, we cannot adopt the package and leave it breaking everybody's system.
> 
> So, sorry, but we'll be denying this request.

That's all good, thanks for the heads up.
