### ISSUE TITLE
[Replacement] zestginx

### ISSUE THREAD

**Issue by lazerl0rd** [chaotic-aur/packages#507]
https://aur.archlinux.org/packages/zestginx

--\-

I'd like to replace `nginx-zest-git` with `zestginx` which, on the advice of Petro, should be done by adding `zestginx` then removing `nginx-zest-git`. The reason provided to upstream is as follows:

_Zestginx is now a formal project, and I would like to drop the old, messy, package (which also is on epoch 4, lol) for the clean, maintainable new package which's name will be shared across packages for other distros._

**Comment by dr460nf1r3** [comment]
This one doesnt compile cleanly, logs [here](https://bin.garudalinux.org/?3e7f33d9acbb818b#MSazLxuqctpAGGAD1HDcAcgJBaBeAHfAamykMkt5X1B)

**Comment by xiota** [comment]
Not building: [log](https://builds.garudalinux.org/repos/chaotic-aur/logs/zestginx.log).
```
error: rustup could not choose a version of cargo to run, because one wasn't specified explicitly, and no default is configured.
help: run 'rustup default stable' to download the latest stable release of Rust and set it as your default toolchain.
```

I've added a comment on the AUR page to notify the maintainer.

**Comment by xiota** [comment]
Over two years is long enough to wait for a fix.
