### ISSUE TITLE
Providing more μarchitecture-optimized packges

### ISSUE THREAD

**Issue by juxuanu** [chaotic-aur/packages#515]
Since you are providing all TkG's kernels with their microarchitecture variations, what about providing also other packages that could really use those optimizations, such as having SSE4.1/4.2, AVX/2, etc.

One that comes to mind is mesa-tkg-git, which could be provided optimized, providing packages such as mesa-tkg-{$microarch}-git.

**Comment by PedroHLC** [comment]
I'm actually considering dropping all those μarchitecture and move to ‘x86-64’. ‘x86-64-v2’, ‘x86-64-v3’, and ‘x86-64-v4’ repo-wide.

**Comment by juxuanu** [comment]
Following ArchLinux's recent decision to provide x86-64 and x86-64-v3 simultaniously, this would seem like a nice time to make a change in the direction you mention.

**Comment by PedroHLC** [comment]
We got [a patch](https://github.com/Frogging-Family/linux-tkg/pull/211) that supports it, now we someone to add them to the [supported vector](https://github.com/Frogging-Family/linux-tkg/blob/251ea4d098d59d6f3a2cb25629a6403759fa79ca/linux-tkg-config/prepare#L667).
