### ISSUE TITLE
[REQUEST] audiotube-git

### ISSUE THREAD

**Issue by fabianski7** [chaotic-aur/packages#516]
https://aur.archlinux.org/packages/audiotube-git/

**Comment by xiota** [comment]
Dropping this because maintainer isn't updating for KF5-package name change.

**Comment by xiota** [comment]
`aur/audiotube-git` has been updated.  Should it be added back or is `extra/audiotube` sufficient?

**Comment by Technetium1** [comment]
@xiota wouldn't hurt to have it back
