### ISSUE TITLE
Missing Linux-TKG packages

### ISSUE THREAD

**Issue by Dartegnian** [chaotic-aur/packages#517]
I've just finished a scheduled system update when I noticed something in the output of `paru`:

> :: Packages not in the AUR: linux-tkg-pds-zen  linux-tkg-pds-zen-headers

I went on to check two Chaotic AUR mirrors <sup>[[1]](https://chaotic.dedyn.io/chaotic-aur/x86_64/) [[2]](https://chaotic-in.dr460nf1r3.me/repos/chaotic-aur/x86_64/)</sup> and found that some of the Linux-TKG packages, including packages for specific micro-architectures and CPU schedulers, were gone.

All that's left now is a TKG package with the MuQSS scheduler. Were the others removed?

**Comment by PedroHLC** [comment]
> All that's left now is a TKG package with the MuQSS scheduler. 

Oh, thanks, I lost one.

> Were the others removed?

Yep, in 5.11.8 I've enabled winesync without knowing them all would have a file conflict. When I noticed it, all variations had already been built.

I'll build them all as soon as some building server becomes available. (See https://t.me/chaotic_aur/603)

**Comment by Gitorian** [comment]
Any updates on this issue?

> -> Missing AUR Packages:  chaotic-nvidia-dkms-tkg  chaotic-nvidia-settings-tkg  chaotic-nvidia-utils-tkg  lib32-chaotic-nvidia-utils-tkg  linux-tkg-pds-ivybridge  linux-tkg-pds-ivybridge-headers

**Comment by PedroHLC** [comment]
We don't have our own nvidia packages anymore. No maintainer is using NVIDIA and because of that it really became complicated to maintain.

PDS packages were dropped as they are no longer significant after Project C.

**Comment by NerosTie** [comment]
> PDS packages were dropped as they are no longer significant after Project C.

What is it?

**Comment by Gitorian** [comment]
> > PDS packages were dropped as they are no longer significant after Project C.
> 
> What is it?

https://gitlab.com/alfredchen/projectc






> We don't have our own nvidia packages anymore. No maintainer is using NVIDIA and because of that it really became complicated to maintain.
> 
> PDS packages were dropped as they are no longer significant after Project C.
But Project C PKGBUILDs aren't in the chaotic-aur, right? Are there plans to add these PKGBUILDs after the server migration is completed?

**Comment by PedroHLC** [comment]
> But Project C PKGBUILDs aren't in the chaotic-aur, right? Are there plans to add these PKGBUILDs after the server migration is completed?

Current linux-tkg-bmq, and old linux-tkg-pds are from project c.

**Comment by Gitorian** [comment]
> > But Project C PKGBUILDs aren't in the chaotic-aur, right? Are there plans to add these PKGBUILDs after the server migration is completed?
> 
> Current linux-tkg-bmq, and old linux-tkg-pds are from project c.

I'm confused
 
> PDS packages were dropped as they are no longer significant after Project C.

I'm confused. Is the PDS cpu scheduler included or not?
If the current PKGBUILD "linux-tkg-bmq" is from Project C, it also has to include the **P**riority and **D**eadline based **S**kiplist multiple queue cpu scheduler, right? After all Project C provides BMQ and PDS-mq in one single patch set.

**Comment by PedroHLC** [comment]
Project C is a remake of both PDS & BMQ for sharing the same codebase. In other words, project C is a merge+remake of them.

>  it also has to include the Priority and Deadline-based Skiplist multiple queue CPU scheduler, right?
No. Project C adds a "selection" in the building step, where you select either BMQ or PDS.

PDS is no longer interesting because, after Project C, BMQ started outperforming it in gaming.
That's why TkG sometimes rebases the old (before-ProjectC) PDS, renaming it to UPDS, but even he already lost interest in it.
