### ISSUE TITLE
switch back to `spotify`

### ISSUE THREAD

**Issue by BachoSeven** [chaotic-aur/packages#522]
Spotify had not been updating their .deb for a while, but in the last week they released them and they're up to date with the `-snap` packages. So I suggest to switch back to the `spotify` package, or at least add it back since because there's no need to have spotify-snap and spotify-edge-snap when there's a gpg-signed tarball instead.

https://aur.archlinux.org/pkgbase/spotify/

**Comment by dr460nf1r3** [comment]
The question is, will they keep updating the .deb? 
If they wont do for a long (like last time) it might not be worth switching once again

**Comment by ThePoorPilot** [comment]
It seems like they have continue to release updates, at least so far. However, it did take them about 11 hours after the snap 1.1.55.498 release to get the regular Debian package up. It may be worth sticking with spotify-snap assuming CReimer keeps it maintained and those few hours are important.

On a different note, the current "spotify" package based on spotify-snap is out of date. Something about the configuration of it must be broken as it is currently on 1.1.46.916

**Comment by dr460nf1r3** [comment]
Alright, added it to Garudas routine as Kitsuna vm is offline still. (and its updated) :)
