### ISSUE TITLE
[Request] Discord-ptb

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#523]
Aur: https://aur.archlinux.org/packages/discord-ptb/

**Comment by PedroHLC** [comment]
Isn't that ancient? 0.0.23 where canary is 0.0.119

**Comment by ALipAkrohk** [comment]
> Isn't that ancient? 0.0.23 where canary is 0.0.119

I use discord-ptb because it strongly uses more efficient hardware resources.

**Comment by PedroHLC** [comment]
From their wiki:
> The Public Test Build is the beta version of the Discord Client and the middle ground between the Stable and Canary clients.

> I use discord-ptb because it strongly uses more efficient hardware resources.

Unless you're enabling/disabling hardware acceleration, you're just having a placebo.
Whatever improvements it has, is also in -canary, which the AUR package is heavily maintained compared to PTB.

And watch out. For some reason, the PTB maintainer decided to add "SUID" to the sandbox, which's dangerous.

**Comment by ALipAkrohk** [comment]
> From their wiki:
> 
> > The Public Test Build is the beta version of the Discord Client and the middle ground between the Stable and Canary clients.
> 
> > I use discord-ptb because it strongly uses more efficient hardware resources.
> 
> Unless you're enabling/disabling hardware acceleration, you're just having a placebo.
> Whatever improvements it has, is also in -canary, which the AUR package is heavily maintained compared to PTB.
> 
> And watch out. For some reason, the PTB maintainer decided to add "SUID" to the sandbox, which's dangerous.

I installed the canary version. 
**Discord-Canary** : In practice it was no different from the web version (WPA) and was very limited.
**Discord-PTB** :  Not only did it have normal discord features, but it was also recognized by betterDiscord, I was also very impressed by the speed and use of the hardware, It was like a better rewrite than Discord in C++.
SUID, I will definitely check it out, thanks for the notification.

**Comment by PedroHLC** [comment]
Again, PTB is the middle btw stable and canary. There is no magic in there that is not in canary. Besides, it uses Discord's electron, not the one from the system (built specifically for arch setups.) 

I'll leave this open for others to argue.

**Comment by ALipAkrohk** [comment]
> Again, PTB is the middle btw stable and canary. There is no magic in there that is not in canary. Only that, it uses Discord's electron, not the one from the system (built specifically for arch setups.)
> 
> I'll leave this open for others to argue.

I am using [BetterDiscordcli](https://aur.archlinux.org/packages/betterdiscordctl-git/) and I feel that Discord-Canary  is not compatible with it, because after installing betterDiscord the Canary settings change to the web version and the software asks me to download and install the original version.

**Comment by rashedheydari2001** [comment]
i create account for this project pakroh so how can i help

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.
