### ISSUE TITLE
[Request] Bibata Cursors

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#524]
bibata cursor theme : https://aur.archlinux.org/packages/bibata-cursor-theme/
bibata cursor translucent : https://aur.archlinux.org/packages/bibata-cursor-translucent/
bibata extra cursor : https://aur.archlinux.org/packages/bibata-extra-cursor-theme/
bibata rainbow cursor : https://aur.archlinux.org/packages/bibata-rainbow-cursor-theme/

**Comment by tio-trom** [comment]
Error in the build, dependency it seems `python-clickgen>=2.0.0` https://builds.garudalinux.org/repos/chaotic-aur/logs/filtered/dep-not-in-repo/bibata-cursor-theme.log

**Comment by dr460nf1r3** [comment]
https://github.com/chaotic-aur/packages/issues/2086

**Comment by Technetium1** [comment]
I left [a comment](https://aur.archlinux.org/packages/bibata-cursor-theme#comment-888605) on `bibata-cursor-theme`

**Comment by tio-trom** [comment]
I see they are not happy about the solution https://aur.archlinux.org/packages/bibata-cursor-theme#comment-888608 :D - perhaps they need more context.

**Comment by Technetium1** [comment]
[I replied back](https://aur.archlinux.org/packages/bibata-cursor-theme#comment-888644).

**Comment by tio-trom** [comment]
Now that https://github.com/chaotic-aur/packages/issues/2112 is added to the repo can you please try and rebuild this?

**Comment by Technetium1** [comment]
@tio-trom last one is done now :)
`Finished making: bibata-cursor-theme 2.0.2-2.1 (Fri 18 Nov 2022 05:21:23 AM CET)`

**Comment by tio-trom** [comment]
Awesome! Thank you!
