### ISSUE TITLE
[Request] Mingw-W64

### ISSUE THREAD

**Issue by deikatsuo** [chaotic-aur/packages#531]
Please add this package
```bash
mingw-w64-gcc mingw-w64-freetype2-bootstrap mingw-w64-cairo-bootstrap mingw-w64-harfbuzz mingw-w64-pango mingw-w64-poppler mingw-w64-gtk3
```

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.

**Comment by deikatsuo** [comment]
> Sorry, this issue does not follow our new template.
> 
> Please, either:
> 
>     1. open a new issue;
> 
>     2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.

Ah, sorry. Actually I have found a repository for mingw
