### ISSUE TITLE
[new pkg] Godot Engine

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#538]
Beta & Rc Versions : https://aur.archlinux.org/packages/godot-beta-bin/
Godot Mono : https://aur.archlinux.org/packages/godot-mono-bin/
Godot Dev V4 & Git Versions: https://aur.archlinux.org/packages/godot-git/

**Comment by dr460nf1r3** [comment]
-bin variants added, left out -git for now as it seems to have really long compile time.

**Comment by xiota** [comment]
Fails to build because of upnp update last month.  Someone already reported upstream.  Will wait a little longer for fix before dropping.  Metrics 46.

**Comment by FabioLolix** [comment]
> Fails to build because of upnp update last month

godot-git is not affected by https://github.com/godotengine/godot/issues/93907 because it build its bundled miniupnp and not using the system one

That can be bypassed with https://aur.archlinux.org/cgit/aur.git/commit/?h=godot-mono-git&id=1ff79740ecb3771d726d71ce9678c2a490266564

**Comment by xiota** [comment]
Problem was out of date custom pkgbuild.  Switching back to aur package.
