### ISSUE TITLE
Manjaro libs issue

### ISSUE THREAD

**Issue by kronos2411** [chaotic-aur/packages#540]
Hello guys. I`m using Manjaro and there diffrenet libs verions compared Arch. So i cannot install some packages, i build this packages from AUR and then when i`am update, pamac tries to install version from Chaotic. How i can ignore Chaotic version but installing updates from AUR?

**Comment by ahmubashshir** [comment]
just use `yay -Syua`

**Comment by PedroHLC** [comment]
```
> How i can ignore Chaotic version but installing updates from AUR?
```

Add it to IgnorePkgs and, when you need to update them, update with `paru -S aur/somepkg` or `yay -S aur/somepkg`
