### ISSUE TITLE
[new-pkg] nginx mainline modules

### ISSUE THREAD

**Issue by ahmubashshir** [chaotic-aur/packages#541]
Please add these:
```
nginx-mainline-mod-brotli
nginx-mainline-mod-dav-ext
nginx-mainline-mod-echo
nginx-mainline-mod-fancyindex
nginx-mainline-mod-headers-more
nginx-mainline-mod-lua
nginx-mainline-mod-njs
nginx-mainline-mod-ndk
nginx-mainline-mod-auth_pam
```

**Comment by xiota** [comment]
@ahmubashshir `nginx-mainline-mod-lua` fails to build.  You are the AUR maintainer and were notified via comment a month ago.  These packages have low usage and will be dropped if not fixed "soon".  Metrics:

* nginx-mainline-mod-auth_pam # 2
* nginx-mainline-mod-brotli # 2
* nginx-mainline-mod-dav-ext # 13
* nginx-mainline-mod-echo # 2
* nginx-mainline-mod-fancyindex # 5
* nginx-mainline-mod-headers-more # 2
* nginx-mainline-mod-lua # 3
* nginx-mainline-mod-ndk # 3
* nginx-mainline-mod-njs # 7
