### ISSUE TITLE
Remove grouping from all packages

### ISSUE THREAD

**Issue by PedroHLC** [chaotic-aur/packages#542]
- What happens?

  There are a lot of VCS packages being suggested in Xorg, Gnome, and KDE groups.

- What is expected to happen?

   We don't want to add those to any stable group.

**Comment by IslandC0der** [comment]
So far, what I've done is add a `-git` suffix to the original group name (`plasma-git`, `kde-applications-git`, etc). That way, we still have groups, but there's no conflicts.
We can have our cake and eat it too :)

**Comment by PedroHLC** [comment]
I don't recall why I didn't close this issue yet, is as simple as adding `sed -i'' 's/^groups=.*$//g' PKGBUILD` in https://github.com/chaotic-aur/toolbox/blob/main/src/lib/interfere.sh#interfere-generic

**Comment by PedroHLC** [comment]
@IslandC0der, I could remove all groups, except the ones ending in "-git", would that be good for you?

**Comment by IslandC0der** [comment]
@PedroHLC yeah, sounds good! Or we could add `-git` to every group (I wouldn't mind making that happen), whichever you think is better :)

**Comment by PedroHLC** [comment]
I need some magic "sed", capable of doing that, right now I'm just removing all groups :+1:

**Comment by IslandC0der** [comment]
@PedroHLC how about this: `sed '/^groups=(/s/ /-git /g;/^groups=(/s/)/-git)/'` 👀

**Comment by PedroHLC** [comment]
> @PedroHLC how about this: `sed '/^groups=(/s/ /-git /g;/^groups=(/s/)/-git)/'` eyes

That doubles "-git" in the ones that already ends in it :smile:

**Comment by IslandC0der** [comment]
@PedroHLC  there: `sed '/^groups=(/s/ /-git /g;/^groups=(/s/)/-git)/;/^groups=(/s/-git-git/-git/g'` 😂

**Comment by PedroHLC** [comment]
LOOKS AWESOME, ADDING IT!

**Comment by PedroHLC** [comment]
BUT WAIT, IS THAT REALLY DESIRED? I think we should "Just keep the -git" ones...

**Comment by IslandC0der** [comment]
Personally, I don't think we should remove the other groups, because we're basically just removing functionality; adding the `-git` suffix or a `chaotic-` prefix would fix all the issues people were having, while still keeping the groups functionality.
Between those two, I think I'd favor `-git`, since we try to stick as closely as possible to the AUR PKGBUILDs, and it wouldn't make sense to add `chaotic-` to the ones being distributed on the AUR.
What do you think?

**Comment by PedroHLC** [comment]
:thinking: I think we should add "-git" only to the packages ending in "-git", otherwise, remove them all...

**Comment by IslandC0der** [comment]
Ohhh okay, I see what you mean; yeah I agree, it doesn't make sense to add non `-git` packages to `-git` groups.
So is the group conflict problem also happening with non VCS packages?

**Comment by dr460nf1r3** [comment]
> BUT WAIT, is that really desired? I think we should "Just keep the -git" ones...
> **EDIT1**: Or keep the "-git", and prefix any other with "chaotic-"...
> **EDIT2**: I wonder if that will affect garuda somehow...

We dont use groups to install packages, metapkgs are used for that purpose so it should not cause issues I guess 👀

**Comment by PedroHLC** [comment]
>  So is the group conflict problem also happening with non VCS packages?

We don't keep track of them, it all started with a -bzr package: https://github.com/chaotic-aur/packages/issues/16

**Comment by maydayv7** [comment]
Yep, definitely is a problem while installing Arch with chaotic repos enabled, best solution would be to create -git and non -git groups

**Comment by maydayv7** [comment]
Or, users can install using pacman -S extra/group_name

**Comment by VexfulNiko** [comment]
Should this be closed yet?

**Comment by dr460nf1r3** [comment]
Yup! 
https://github.com/chaotic-aur/toolbox/blob/main/src/lib/interfere.sh#L84
