### ISSUE TITLE
[Request] Protonmail-bridge

### ISSUE THREAD

**Issue by federicotorrielli** [chaotic-aur/packages#547]
AUR: https://aur.archlinux.org/packages/protonmail-bridge/

Also, can you close the other requests that are fullfilled? It's a bit confusing to only add a label and leave them there.

**Comment by dr460nf1r3** [comment]
Im sure you read the pinned issue, its explained there.

**Comment by federicotorrielli** [comment]
@dr460nf1r3 yes, can I help with my computer? I have a 5800X Ryzen CPU.

**Comment by dr460nf1r3** [comment]
I somehow missed this, sorry. Thanks for the kind offer, we cant really compile on random machines due to safety reasons though.  Anyway, the package is added now. :)
