### ISSUE TITLE
chaotic-key keyring and gpg keys disappear after reboot

### ISSUE THREAD

**Issue by AnirudhChandupatla** [chaotic-aur/packages#548]
I followed the setup from https://aur.chaotic.cx/, for the first time it worked fine. after reboot I get "signature from "Pedro Henrique Lara Campos <root@pedrohlc.com>" is unknown trust" this message while installing anything from chaotic AUR. when I checked the list of keys with "gpg --homedir /etc/pacman.d/gnupg --list-keys" chaotic keys are missing in here. 

when I do "sudo pacman-key --populate chaotic" keys are appened but again after reboot they disappear.

**Comment by PedroHLC** [comment]
Is that a pure-ArchLinux, Garuda, Manjaro, Arco, Endeavour or anything else??

**Comment by AnirudhChandupatla** [comment]
pure ArchLinux

**Comment by PedroHLC** [comment]
That's something that needs deep investigation. It's not a common thing for the system to be recreating Pacman's keyring on every boot. There must be some package's hook or Systemd's unit file triggering this.
I don't see any advantage in that behavior so if you want to disable it feel free. But, I'm also interested in knowing what it is, so please let me know when you find it.

**Comment by dr460nf1r3** [comment]
As no further feedback has been given Im closing this issue. Feel free to reopen if the issue occurs again.
