### ISSUE TITLE
[new pkg] LeftWM

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#555]
AUR : [Git](https://aur.archlinux.org/packages/leftwm-git/), [Stable](https://aur.archlinux.org/packages/leftwm/), [Themes](https://aur.archlinux.org/packages/leftwm-theme-git/)
Git Repo : https://github.com/leftwm/leftwm

**Comment by xiota** [comment]
`leftwm-theme-git` fails to build.  No response since 2024-04-01.  Metrics 7.

Haven't decided whether to interfere or drop.  No stable variant.

There are also `leftwm-config` packages to consider adding.

**Comment by xiota** [comment]
`leftwm-git` and `leftwm-theme-git` appear to have been fixed Aug 2024.  However, `leftwm` now fails to build (same reason) and out of date (late Oct 2024).  Usage of all packages is low.

* `leftwm` 6
* `leftwm-nonsystemd` 3
* `leftwm-git` 11
* `leftwm-nonsystemd-git` 5
* `leftwm-theme-git` 6
