### ISSUE TITLE
[REQUEST] ion-git

### ISSUE THREAD

**Issue by RohitSingh107** [chaotic-aur/packages#560]
Git: https://gitlab.redox-os.org/redox-os/ion
aur: https://aur.archlinux.org/ion-git.git

**Comment by xiota** [comment]
Dropping this package.  Metric 3.  Package cannot be rebuilt and signature error prevents install without rebuilding.

Package maintainer has identified as an upstream issue.  I don't want to make another account for a custom gitlab server, so not going to bother reporting it.

If someone wants this added back, (1) report the issue upstream, (2) comment here after it's fixed.  Also, (3) include a few sentences to explain what this package is and how it's useful.
