### ISSUE TITLE
[Request] bforartists-git

### ISSUE THREAD

**Issue by data-man** [chaotic-aur/packages#563]
Links:
AUR: https://aur.archlinux.org/packages/bforartists-git
git: https://github.com/Bforartists/Bforartists

**Comment by dr460nf1r3** [comment]
[bforartists-git.log](https://github.com/chaotic-aur/packages/files/6487852/bforartists-git.log)
Complaining about Python 3.9+ being required when its clearly installed @PedroHLC

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.
