### ISSUE TITLE
[Request] Telephant : Mastodon Clint

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#567]
Aur : https://aur.archlinux.org/packages/telephant-git/
Git : https://github.com/muesli/telephant

**Comment by dr460nf1r3** [comment]
Fails to compile currently, maintainer is notified :>

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.
