### ISSUE TITLE
[Request] Phoenicis PlayOnLinux 

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#570]
Github : https://github.com/PhoenicisOrg/phoenicis
Aur : https://aur.archlinux.org/packages/phoenicis-playonlinux/

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.

**Comment by xiota** [comment]
Dropping because fails to build.  Maintainer ignoring comments for over a year.  Metrics 30.
