### ISSUE TITLE
Wish list for packages in chaotic aur

### ISSUE THREAD

**Issue by caniko** [chaotic-aur/packages#571]
Currently in AUR, but not in chaotic-aur:
- [zeal-git](https://aur.archlinux.org/packages/zeal-git/) and [zeal](https://aur.archlinux.org/packages/zeal/)
- [meshlab](https://aur.archlinux.org/packages/meshlab/) and [meshlab-git](https://aur.archlinux.org/packages/meshlab-git/)
- [fiji](https://aur.archlinux.org/packages/fiji-bin/)
- [authy](https://aur.archlinux.org/packages/authy/)

Packages that aren't in either AUR or chaotic-aur:
- [miniconda](https://docs.conda.io/en/latest/miniconda.html)
- [FEniCS](https://fenicsproject.org/download/)

Note that it is possible to install miniconda through pyenv, I just thought it was natural seeing that `anaconda` is in chaotic-aur.

**Comment by dr460nf1r3** [comment]
If you want to have the last two added you should look into providing a PKGBUILD :)

**Comment by caniko** [comment]
> If you want to have the last two added you should look into providing a PKGBUILD :)

Understood, I don't have time for that I am afraid. Moreover, `dolfin` is the backend of fenics, and it has an [AUR repository](https://aur.archlinux.org/packages/python-dolfin/).

**Comment by dr460nf1r3** [comment]
So all the packages available in AUR have been built now, wanna leave this issue open or closed? Is `dolfin` needed? I saw the PKGBUILD needs patching as its broken in its current state :)

**Comment by caniko** [comment]
All good, thank you!

**Comment by xiota** [comment]
Dropped `meshlab` and `meshlab-git` from the package lists because they're not building.  Left the packages in the repository because the existing builds run, but with errors about missing plugins.

**Comment by xiota** [comment]
Dropping `zeal-git` because `extra/zeal` is available and low usage.  Metrics 2.
