### ISSUE TITLE
[Question] Plasma-git or Plasma stable 

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#572]
Hi, my question is why when I use chaotic-aur, it installs the git version of the plasma desktop ?!
Normally there should be a choice between the git and stable versions.
Or at least the right to choose repo at the time of installation.
**I hope you understand what I mean by this question, my English is a little weak**

**Comment by dr460nf1r3** [comment]
This should not happen at all, do you install using a metapackage? It might need #542

**Comment by IslandC0der** [comment]
Hi, you might have installed something that  depends on `plasma-desktop-git`. Could you please provide the output of `pacman -Qi plasma-desktop-git`?

**Comment by ALipAkrohk** [comment]
> This should not happen at all, do you install using a metapackage? It might need #542

I feel this is due to the user-manager package.

> Hi, you might have installed something that depends on `plasma-desktop-git`. (#501)
> Could you please provide the output of `pacman -Qi plasma-desktop-git`?

I have now removed the plasma from the system and am using Leftwm.
