### ISSUE TITLE
Remove this `*-bin` packages

### ISSUE THREAD

**Issue by RustemB** [chaotic-aur/packages#574]
Reason: their non `*-bin` versions already in `community` repo
```
aspnet-runtime-bin
aspnet-targeting-pack-bin
dotnet-host
dotnet-runtime
dotnet-sdk
dotnet-targeting-pack
netstandard-targeting-pack
```
Reason why we can't remove it right now: some packages requires `*-bin` versions even if it's not in `chaotic`'s repo :D (e.g. `ryujinx-git`)

**Comment by dr460nf1r3** [comment]
We can replace depends of those packages using interfere. Which ones are affected?
