### ISSUE TITLE
modprobe-db

### ISSUE THREAD

**Issue by robson-66** [chaotic-aur/packages#580]
Why when updating the system `sudo pacman -Syu` does it pop up this prompt whether to replace `modprobe-db` with `modprobe-db-git`?
https://i.postimg.cc/CKYjygZj/Przechwycenie-obrazu-ekranu-2021-05-01-15-52-42.png

**Comment by dr460nf1r3** [comment]
Added this just 1 hour ago, seems like replaces() needs to be removed from the PKGBUILD. Thanks for reporting!
