### ISSUE TITLE
[Request] python-qiskit

### ISSUE THREAD

**Issue by coxackie** [chaotic-aur/packages#581]
Please add python-qiskit, which is [here](https://aur.archlinux.org/packages/python-qiskit/), which should include all the python-qiskit "sub-packages". There are too many build packages, and it would be great to have these pre-built.

 Many, many thanks.

**Comment by dr460nf1r3** [comment]
That were quite a lot of dependencies 😆

**Comment by coxackie** [comment]
you guys are epic!

**Comment by coxackie** [comment]
hmmm, I no longer can find `python-qiskit` in the repo. Was it removed? Could you check, and if this is the case, please re-add it?

**Comment by Technetium1** [comment]
Related to #2086

**Comment by Technetium1** [comment]
Optional deps coming once we get `python-qiskit` building. For now, we are waiting on `python-retworkx` which is [out of date](https://aur.archlinux.org/pkgbase/python-retworkx/flag-comment)… [python-retworkx.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/python-retworkx.log)

**Comment by dr460nf1r3** [comment]
Update '23: `python-retworkx` is still broken.

**Comment by coxackie** [comment]
So, the thing is that the only package needing `python-retworkx` is [python-qiskit-aqua](https://aur.archlinux.org/packages/python-qiskit-aqua), which has been deprecated long time ago, so should most probably be dropped. For example, the `python-qiskit` AUR meta-package does not require it.

 Could we then please then move towards this direction?

**Comment by coxackie** [comment]
@dr460nf1r3 just pinging to see if anything can be done - please see previous comment.

**Comment by Technetium1** [comment]
@coxackie I checked all the dependencies, and they're still up to date. However, `python-retworkx` is still flagged out of date and using the old version. There's also an important update from https://github.com/Qiskit/rustworkx: 
> The `retworkx` project has been renamed to `rustworkx`. The use of the `retworkx` package will still work for the time being but starting in the 1.0.0 release `retworkx` will no longer be supported

**Comment by coxackie** [comment]
@Technetium1 I should have been more precise, please see my [previous comment](https://github.com/chaotic-aur/packages/issues/581#issuecomment-1435722896), where I mention that "the only package needing python-retworkx is [python-qiskit-aqua](https://aur.archlinux.org/packages/python-qiskit-aqua), which has been deprecated long time ago, so should most probably be dropped. For example, the `python-qiskit` AUR meta-package does not require it." Maybe one can just drop `python-qiskit-aqua` for the time being, and only build what is needed [here](https://aur.archlinux.org/packages/python-qiskit). What do you think?

**Comment by Technetium1** [comment]
@coxackie I'm confused since we do not try to build the deprecated [python-qiskit-aqua](https://aur.archlinux.org/packages/python-qiskit-aqua) for a long time. Maybe your search showing that package was before this commit? https://github.com/chaotic-aur/packages/commit/e097180b8e00ddb4e724eede954033d34cf93014

**Comment by coxackie** [comment]
@Technetium1 I am also confused, because if I visit the [AUR page](https://aur.archlinux.org/packages/python-qiskit) of the `python-qiskit` meta-package there is no mention of `python-retworkx`. Are you sure this is a required dependency? It does not appear to be. Have you tried to build the package without it?

**Comment by Technetium1** [comment]
@coxackie Oh! It is dep for [python-qiskit-terra](https://aur.archlinux.org/packages/python-qiskit-terra)

**Comment by coxackie** [comment]
The dependency I can see [here](https://aur.archlinux.org/packages/python-qiskit-terra?all_deps=1#pkgdeps) is for [python-rustworkx](https://aur.archlinux.org/packages/python-rustworkx), which is replacing `python-retworkx`.

**Comment by Technetium1** [comment]
Turns out I misread `rustworkx` as `retworkx`!
```
$ aur depends --pkgbase python-qiskit
python-qiskit   python-qiskit-terra
python-qiskit-aer       python-qiskit-terra
python-qiskit-ibmq-provider     python-qiskit-terra
python-qiskit-aer       openblas-lapack
python-qiskit   python-qiskit
python-qiskit-terra     python-rustworkx
python-qiskit-aer       muparserx
python-qiskit-terra     python-tweedledum
python-qiskit   python-qiskit-ibmq-provider
python-qiskit   python-qiskit-aer
```

**Comment by Technetium1** [comment]
Success!

**Comment by xiota** [comment]
`python-qiskit-aer` is failing to build because of missing depends.  It's an optdep of `python-qiskit`.  The other qiskit-related optdeps aren't in the repo.  Adding them all looks quite troublesome, and I would prefer to drop them.  Using them in a venv might be easier.  What is the benefit of using them from a repo?

Metrics:

* muparserx # 4
* python-qiskit-aer # 7
* python-qiskit # 18
* python-rustworkx # 22
