### ISSUE TITLE
Garuda Wayfire Installed on Asus Laptop... Cannot adjust Screen resolution within OS

### ISSUE THREAD

**Issue by bptknx** [chaotic-aur/packages#582]
I have Garuda Linux Wayfire installed on an Asus laptop with Invidia Geforce GTX 950m video. Cannot adjust screen resolution within OS. Will try adjusting Grub.cfm file to adjust boot resolution. However I am new to Linux and not familiar with Grub command line syntax. Any help would be appreciated. Thanks

**Comment by dr460nf1r3** [comment]
This is the wrong place to request help for Garuda. Instead please use the [official forum](https://forum.garudalinux.org), this repo is used for package requests / issues with packages.
