### ISSUE TITLE
Can you add some packages

### ISSUE THREAD

**Issue by ahmed-tasaly** [chaotic-aur/packages#584]
### Can you add these packages?
**vboot** & **hfsprogs** & **geekbench** &  **Phoronix-test-suite** & **Radeon-profile**

**Comment by dr460nf1r3** [comment]
Would you be so kind to provide the exact AUR page links? There is no `vboot`, only `vboot-utils` for example.

**Comment by ahmed-tasaly** [comment]
> Would you be so kind to provide the exact AUR page links? There is no `vboot`, only `vboot-utils` for example.

yes, I meant vboot-utils but forget on writing.

and the links : 
**vboot-utils** https://aur.archlinux.org/packages/vboot-utils/
**hfs-progs** https://aur.archlinux.org/packages/hfsprogs/
**geekbench** https://aur.archlinux.org/packages/geekbench/
**phoronix-test-suite** https://aur.archlinux.org/packages/phoronix-test-suite/
**Radeon-profile-git** https://aur.archlinux.org/packages/radeon-profile-git/
and
**megatools** https://aur.archlinux.org/packages/megatools/

I **am not** a professional Linux user
If you found better sources then use them,
and 
**I would like to thank you for all of your effort**

_Note:_
I am neither the owner nor the packager nor the submitter of these packages
I am only a user

**Comment by dr460nf1r3** [comment]
No problem, just gotta know the package names. You are welcome :)

**Comment by xiota** [comment]
Dropping geekbench because it is a disguised bin.  Program is proprietary.  It was recently orphaned and picked up by a new maintainer.  Metrics 132.

**Comment by xiota** [comment]
Dropping vboot-utils because it is orphaned, flagged for over a year.  Metrics 20.

**Comment by xiota** [comment]
Dropping radeon-profile-git.  Previous comaintainer stated that program is not functional.  Last upstream commit was Feb 2022 and not updated for Qt6.  Metrics 87.
