### ISSUE TITLE
Please can you add Linux Mint artwork

### ISSUE THREAD

**Issue by blank-space-maker** [chaotic-aur/packages#590]
Hello, please could you add mint-y-icons, mint-x-icons, mint-themes, mint-sounds and mint-backgrounds from AUR. Thanks

**Comment by dr460nf1r3** [comment]
Is this still required? Mint-artworks now pulls tons of different packages, which is why would like to drop it.

**Comment by blank-space-maker** [comment]
hello, you can drop mint-backgrounds and thanks for all the work you do.
