### ISSUE TITLE
Please add Linux Mint Xapps and Pamac-all

### ISSUE THREAD

**Issue by blank-space-maker** [chaotic-aur/packages#593]
Please can you add xplayer, pix, mintlocale, xfce4-docklike-plugin, gigolo, ttf-vista-fonts, ttf-symbola and pamac-all from the AUR. Thanks

**Comment by dr460nf1r3** [comment]
Pamac-all depends on snapd, which we dropped in the past and decided to not add again. So this request will be denied, the rest will be added :)

**Comment by dr460nf1r3** [comment]
The source of ttf-vista-fonts apparently doesn't exist anymore (cant be fetched).

**Comment by PedroHLC** [comment]
> The source of ttf-vista-fonts apparently doesn't exist anymore (cant be fetched).

It never was, you need a real Windows Vista to get that file...

**Comment by xiota** [comment]
Dropping `gigolo` because fails to build and maintainer hasn't responded to either comment or flag.

**Comment by FabioLolix** [comment]
Btw `gigolo` is in Extra-testing https://archlinux.org/packages/extra-testing/x86_64/gigolo/ since yesterday

**Comment by xiota** [comment]
Dropping xplayer because depends on clutter, which was discontinued in 2022.

Metrics:

* xplayer # 21
* mintlocale # 188
