### ISSUE TITLE
[Request] vital-synth

### ISSUE THREAD

**Issue by SameExpert** [chaotic-aur/packages#599]
Please add [vital-synth](https://aur.archlinux.org/packages/vital-synth/)

**Comment by xiota** [comment]
Dropping because requires manual download of deb package and user input in `prepare()` function.  Metrics 54.

See https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/thread/VT4KQOIDW4F7XZYZ2EA3FZVQGEK7VHT6/
