### ISSUE TITLE
[Request] Pantheon-mail

### ISSUE THREAD

**Issue by maydayv7** [chaotic-aur/packages#601]
Link: https://aur.archlinux.org/packages/pantheon-mail/
Also, can it please be added to the `pantheon` group

**Comment by dr460nf1r3** [comment]
Did you actually install this before? There is a dependency, `libgsignon-glib` which doesnt exist in both Arch repos/AUR.

**Comment by maydayv7** [comment]
It actually requires [libsignon-glib](https://archlinux.org/packages/extra/x86_64/libsignon-glib/), but I don't know how to change that on the AUR's PKGBUILD

**Comment by dr460nf1r3** [comment]
Oh, in that case thats easy to fix using our interfere repo :)

**Comment by maydayv7** [comment]
Thanks a lot
Anyways, submitting a request

**Comment by dr460nf1r3** [comment]
Even though the depends are fixed now the package still fails to compile, looks like a source code error to me.  Maybe the logs help? 
[pantheon-mail.log](https://github.com/chaotic-aur/packages/files/6464695/pantheon-mail.log)

**Comment by maydayv7** [comment]
Okay, will reopen this issue once I track down the problem. Thanks a lot.
