### ISSUE TITLE
[Request] Please add xfce4-dockbarx-plugin, macfanctld, gromit-mpx, kazam and artha from AUR

### ISSUE THREAD

**Issue by blank-space-maker** [chaotic-aur/packages#604]
Hello, please can you add xfce4-dockbarx-plugin, macfanctld, gromit-mpx, kazam and artha from the AUR.

xfce4-dockbarx-plugin: https://aur.archlinux.org/packages/xfce4-dockbarx-plugin/
macfanctld: https://aur.archlinux.org/packages/macfanctld/
gromit-mpx: https://aur.archlinux.org/packages/gromit-mpx/
kazam: https://aur.archlinux.org/packages/kazam/
artha: https://aur.archlinux.org/packages/artha/

Thanks for all the hard work and have a great weekend

**Comment by xiota** [comment]
`artha` fails to build. Will drop if not fixed.  Metrics 6.
