### ISSUE TITLE
DKMS modules cannot install on linux-tkg-* 5.12.4 due to invalid kernel configurations

### ISSUE THREAD

**Issue by heavysink** [chaotic-aur/packages#609]
Hi,

It seems that linux-tkg-* 5.12.4 is broken because no dkms module can install with them. The logs:

 ERROR: Kernel configuration is invalid.
           include/generated/autoconf.h or include/config/auto.conf are missing.
           Run 'make oldconfig && make prepare' on kernel src to fix it.

**Comment by PedroHLC** [comment]
Indeed they seem broken, I've removed them and pinged @Tk-Glitch to take a look

**Comment by PedroHLC** [comment]
Just tested in my system, and with `5.12.4-157` we have DKMS working again.
It looks like this https://github.com/Frogging-Family/linux-tkg/commit/5c0f3f72e33098b6c2867aa23c02c1ea91f8738c fixed it.

**NOTE**: It will take some time for the server to rebuild all the kernels variations...
