### ISSUE TITLE
[Request] tok-git

### ISSUE THREAD

**Issue by fabianski7** [chaotic-aur/packages#614]
https://aur.archlinux.org/packages/tok-git/

the libtd-git dependency takes a long time to compile. At least on my i7-6700 pc

**Comment by dr460nf1r3** [comment]
libtd-git is added, tok-git fails to compile though. 
[tok-git.log](https://github.com/chaotic-aur/packages/files/6496439/tok-git.log)

**Comment by fabianski7** [comment]
it's woking now

**Comment by fabianski7** [comment]
Broken again. Sorry.
The pkgbuild needs to be updated to build with qbs. I will follow the progress
