### ISSUE TITLE
[Request] Trello

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#615]
https://aur.archlinux.org/packages/trello/

https://aur.archlinux.org/packages/trello-bin/

https://aur.archlinux.org/packages/trello-cli/

https://aur.archlinux.org/packages/trello-git/

https://aur.archlinux.org/packages/silo-trello/

**Comment by xiota** [comment]
Note: `trello` uses electron17.

**Comment by xiota** [comment]
Dropping `silo-trello` because `silos` has maintenance issues.
