### ISSUE TITLE
[Request] `Brave`

### ISSUE THREAD

**Issue by PolpOnline** [chaotic-aur/packages#616]
https://aur.archlinux.org/packages/brave/

**Comment by coxackie** [comment]
Sorry to necrocomment here, but brave does not appear to being built anymore, although there were many effort to finally make it build in a clean chroot. Could it please be ckecked?

**Comment by Technetium1** [comment]
@dr460nf1r3 any idea where it went? I can't find it now, or when it was removed?

**Comment by dr460nf1r3** [comment]
Iirc either there were issues building in the past or the release was lagging way behind 🤔

**Comment by coxackie** [comment]
Indeed there were issues in the past, but they should have been resolved now. Could you please maybe give it another go as a package now?

**Comment by Technetium1** [comment]
@coxackie failing on 2 builders as follows: [brave.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/brave.log)
```
Cloning into bare repository '/home/main-builder/pkgsrc/chromium'...
error: RPC failed; curl 18 Transferred a partial file
error: 28 bytes of body are still expected
fatal: the remote end hung up unexpectedly
==> ERROR: Failure while downloading chromium git repo
```

**Comment by coxackie** [comment]
oh, well, so much for the claims that it now builds ok then. Maybe this is not a big deal - supposedly it should move to official repos soon as the brave team sorts out some stuff, so you could just let this go.

**Comment by Technetium1** [comment]
Here's the related post for getting Brave into community. Looks like we probably won't have to wait much longer. 
https://community.brave.com/t/does-brave-allow-the-distribution-of-self-compiled-or-distro-compiled-binaries/457833/21
