### ISSUE TITLE
[Request] element-desktop-git

### ISSUE THREAD

**Issue by caniko** [chaotic-aur/packages#618]
https://aur.archlinux.org/packages/element-desktop-git

**Comment by dr460nf1r3** [comment]
This package is currently unmaintained and needs a fix

**Comment by caniko** [comment]
I thought the recent updates to downstream projects fixed it? You get errors during build?

**Comment by dr460nf1r3** [comment]
```
error electron-builder@22.11.4: The engine "node" is incompatible with this module. Expected version ">=14.17.0". Got "10.24.0"
error Found incompatible module.                                               
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
Getting this error, even though the fix taken from the comment section has been applied
