### ISSUE TITLE
[Request] intel-media-driver-git and ffmpeg-git

### ISSUE THREAD

**Issue by Hou-dev** [chaotic-aur/packages#623]
https://aur.archlinux.org/packages/intel-media-driver-git
https://aur.archlinux.org/packages/ffmpeg-git/

Allows for hardware accelerated video decode on popular video sites on Intel iGPUs

**Comment by dr460nf1r3** [comment]
[intel-media-driver-git.log](https://github.com/chaotic-aur/packages/files/6542256/intel-media-driver-git.log)
Intel-media-driver-git fails to compile, dependencies & the other package have been added though.

**Comment by xiota** [comment]
Both packages currently failing to build for different reasons.  Metrics unavailable.

Planning to drop because the use case "hardware accelerated video decode ... on Intel iGPUs" should be covered by the `extra` packages.  Also, `ffmpeg-git` is sporadically incompatible with `ffmpeg`.
