### ISSUE TITLE
[request] OpenRA Medieval Warfare

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#632]
aur : https://aur.archlinux.org/packages/openra-mw-git/

**Comment by dr460nf1r3** [comment]
Did this ever install cleanly for you before? Seems like package() is broken. 
```
==> Entering fakeroot environment...
==> Starting package()...
cp: cannot stat 'engine/GeoLite2-Country.mmdb.gz': No such file or directory
cp: cannot stat 'engine/OpenRA.Game.exe': No such file or directory
cp: cannot stat 'engine/OpenRA.Platforms.Default.dll': No such file or directory
cp: cannot stat 'engine/OpenRA.Server.exe': No such file or directory
cp: cannot stat 'engine/OpenRA.Utility.exe': No such file or directory
```

**Comment by ALipAkrohk** [comment]
Hi yes I have this problem too, but the reason for introducing the game to you was that your team has a garuda linux gaming distribution development.

**Comment by dr460nf1r3** [comment]
Alright, thanks. I have notified the AUR maintainer, hopefully he will fit it. :)

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.
