### ISSUE TITLE
issue adding chaotic-mirrorlist

### ISSUE THREAD

**Issue by NovaMoon** [chaotic-aur/packages#634]
I tried following the setup from the website 
after creating the missing directory i tried to install it with ` pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-'{keyring,mirrorlist}'.pkg.tar.zst' ` but it get the following error.

[root@u ~]#  pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-'{keyring,mirrorlist}'.pkg.tar.zst' 
warning: database file for 'chaotic-aur' does not exist (use '-Sy' to download)
loading packages...
warning: chaotic-keyring-20210406-1 is up to date -- reinstalling
warning: chaotic-mirrorlist-20210516-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (2) chaotic-keyring-20210406-1  chaotic-mirrorlist-20210516-1

Total Installed Size:  0.01 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] y
(2/2) checking keys in keyring                                                                          [#############################################################] 100%
(2/2) checking package integrity                                                                        [#############################################################] 100%
(2/2) loading package files                                                                             [#############################################################] 100%
(2/2) checking for file conflicts                                                                       [#############################################################] 100%
(2/2) checking available disk space                                                                     [#############################################################] 100%
:: Processing package changes...
(1/2) reinstalling chaotic-keyring                                                                      [#############################################################] 100%
==> Appending keys from chaotic.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key 3FFA0B5E092ED4095E26F69B8ADB4AEC585061CF...
  -> Locally signing key 1949E60D299007430C94DC0657F3D9CC660431DD...
  -> Locally signing key EF925EA60F33D0CB85C44AD13056513887B78AEB...
==> Importing owner trust values...
==> Updating trust database...
gpg: next trustdb check due at 2021-08-02
==> Updating trust database...
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 786C63F330D7CB92: no user ID for key signature packet of class 10
gpg: key 1EB2638FF56C0C53: no user ID for key signature packet of class 10
gpg: key 1EB2638FF56C0C53: no user ID for key signature packet of class 10
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   9  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   9  signed:  83  trust: 1-, 0q, 0n, 8m, 0f, 0u
gpg: depth: 2  valid:  77  signed:  24  trust: 77-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2021-08-02
(2/2) reinstalling chaotic-mirrorlist                                                                   [#############################################################] 100%
error: extract: not overwriting dir with file /etc/pacman.d/chaotic-mirrorlist
error: problem occurred while upgrading chaotic-mirrorlist
error: could not commit transaction
error: failed to commit transaction (transaction aborted)
Errors occurred, no packages were upgraded.

**Comment by dr460nf1r3** [comment]
You already created a chaotic-mirrorlist manually perhaps? Try overwriting it with --overwrite "*"

**Comment by NovaMoon** [comment]
i only created the dir "/etc/pacman.d/chaotic-mirrorlist" and nothing more.
done the --overwrite option but the error persists

[root@u ~]#  pacman -U --overwrite 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-'{keyring,mirrorlist}'.pkg.tar.zst' 
warning: database file for 'chaotic-aur' does not exist (use '-Sy' to download)
loading packages...
warning: chaotic-mirrorlist-20210516-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) chaotic-mirrorlist-20210516-1

Total Installed Size:  0.00 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                          [#############################################################] 100%
(1/1) checking package integrity                                                                        [#############################################################] 100%
(1/1) loading package files                                                                             [#############################################################] 100%
(1/1) checking for file conflicts                                                                       [#############################################################] 100%
(1/1) checking available disk space                                                                     [#############################################################] 100%
:: Processing package changes...
(1/1) reinstalling chaotic-mirrorlist                                                                   [#############################################################] 100%
error: extract: not overwriting dir with file /etc/pacman.d/chaotic-mirrorlist
error: problem occurred while upgrading chaotic-mirrorlist
error: could not commit transaction
error: failed to commit transaction (transaction aborted)
Errors occurred, no packages were upgraded.

**Comment by NovaMoon** [comment]
i found the mistake.
i added

[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist

before i did the first 3 commands. works now

**Comment by dr460nf1r3** [comment]
Nice to see you solved it. :)
