### ISSUE TITLE
[Request] `olive-git`

### ISSUE THREAD

**Issue by blackcat-917** [chaotic-aur/packages#635]
- Link to the package(s) in AUR: [aur.archlinux.org/packages/olive-git](https://aur.archlinux.org/packages/olive-git)

- Utility this package has for you:

  This package could be useful for testing new olive features, as the stable version is from April 2019.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [x] YES
  - [ ] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES (GPL-3.0 licensed)
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by dr460nf1r3** [comment]
A dependency, openimagio-git fails to compile due to unknown reasons currently.

**Comment by blackcat-917** [comment]
Now it builds! 🎉

**Comment by dr460nf1r3** [comment]
Sadly no, 
`=> Checking buildtime dependencies...
chmod: changing permissions of '/home/main-builder/pkgwork/src'
: Operation not permitted

==> ERROR: An unknown error has occurred. Exiting...`

I looked at the PKGBUILD but couldnt find something special 👀

**Comment by blackcat-917** [comment]
Strange, in my machine it does (I've just installed the package).
![image](https://user-images.githubusercontent.com/53786619/120838573-3e741e00-c568-11eb-9940-66f0fd04c684.png)

**Comment by dr460nf1r3** [comment]
Yes, checked that too. Seems toolbox related, maybe @PedroHLC can have a look :)

**Comment by PedroHLC** [comment]
> Yes, checked that too. Seems toolbox related, maybe @PedroHLC can have a look :)

I have absolutely no clue on how it could fail while "Checking buildtime dependencies" in a clean build.

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.

**Comment by blackcat-917** [comment]
Sorry for the late response, can you reopen this issue since I can't?
