### ISSUE TITLE
[Request] Pikaur

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#636]
AUR : https://aur.archlinux.org/packages/pikaur-git/

**Comment by ALipAkrohk** [comment]
error: pyalpm: signature from "Jelle van der Waa <jelle@vdwaa.nl>" is invalid
:: File /var/cache/pacman/pkg/pyalpm-0.10.3-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).

**Comment by dr460nf1r3** [comment]
`pyalpm` is an [Arch Linux package](https://archlinux.org/packages/extra/x86_64/pyalpm/) so not an issue on our end, probably the download just corrupted 🤔
