### ISSUE TITLE
[Request] firefox kde opensuse

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#637]
AUR : https://aur.archlinux.org/packages/firefox-kde-opensuse/
Bin : https://aur.archlinux.org/packages/firefox-kde-opensuse-bin/

**Comment by dr460nf1r3** [comment]
Added the -bin variant for now, apart from that we have already enough Firefox forks compiled from source :)

**Comment by ALipAkrohk** [comment]
aur: https://aur.archlinux.org/packages/firefox-kde-opensuse-bin/ [outofdate: 2021/06/10]
NewPkg **aur** : https://aur.archlinux.org/packages/firefox-kde-opensuse-rpm/ [Last Updated : 2021/07/23]
