### ISSUE TITLE
[package request] fractal-next

### ISSUE THREAD

**Issue by juxuanu** [chaotic-aur/packages#641]
https://aur.archlinux.org/packages/fractal-next/

Hopefully no more dependency issues

**Comment by xiota** [comment]
Considering dropping this.  Package needs updates, but maintainer nonresponsive to comments.  Can update interfere, but may not be worthwhile.  Metrics 21.

`extra/fractal` available.  Last updated May 2024.

**Comment by xiota** [comment]
Dropping because still fails to build.  Metrics 2.
