### ISSUE TITLE
mesa-git update failing

### ISSUE THREAD

**Issue by tankaras** [chaotic-aur/packages#648]
Proceed with installation? [Y/n] y
:: Retrieving packages...
 mesa-git-1:21.2.0_devel.140557.db83dc619c9-1-x86_64.pkg.tar.zst failed to download
 Total (1/3)                75.7 MiB  2039 KiB/s 00:38 [----------------------------] 100%
error: failed retrieving file 'mesa-git-1:21.2.0_devel.140557.db83dc619c9-1-x86_64.pkg.tar.zst' from random-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'mesa-git-1:21.2.0_devel.140557.db83dc619c9-1-x86_64.pkg.tar.zst' from us-tx-mirror.chaotic.cx : Maximum file size exceeded
error: failed retrieving file 'mesa-git-1:21.2.0_devel.140557.db83dc619c9-1-x86_64.pkg.tar.zst' from us-wa-mirror.chaotic.cx : The requested URL returned error: 404
error: failed retrieving file 'mesa-git-1:21.2.0_devel.140557.db83dc619c9-1-x86_64.pkg.tar.zst' from us-ut-mirror.chaotic.cx : HTTP server doesn't seem to support byte ranges. Cannot resume.
error: failed retrieving file 'mesa-git-1:21.2.0_devel.140557.db83dc619c9-1-x86_64.pkg.tar.zst' from us-ca-mirror.chaotic.cx : expected download size exceeded
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.

**Comment by PedroHLC** [comment]
Hey, the upload btw server was broken, I fixed them with https://github.com/chaotic-aur/toolbox/pull/19 and rebuild mesa-git.
Please try again. :smile: 

(Sorry for the inconvenience)
