### ISSUE TITLE
[Request] LinuxXanmod LTS

### ISSUE THREAD

**Issue by ALipAkrohk** [chaotic-aur/packages#655]
Aur : https://aur.archlinux.org/packages/linux-xanmod-lts/

**Comment by ALipAkrohk** [comment]
![image](https://user-images.githubusercontent.com/27810360/121857863-4885e180-cd0b-11eb-87cd-f119d5ba2c3c.png)
You have not loaded this package in the tank yet ?

**Comment by dr460nf1r3** [comment]
Sorry for the late answer, we will add this once another builder is back.
