### ISSUE TITLE
[Request] Unreal Engine

### ISSUE THREAD

**Issue by caniko** [chaotic-aur/packages#661]
[Info](https://wiki.archlinux.org/title/Unreal_Engine_4#Installing_from_the_AUR) on how to do it from the Arch wiki

Would be nice if we could have the latest UE5 early access in addition to the standard UE4. The PKGBUILD would have to configured.

**Comment by dr460nf1r3** [comment]
We have this requested in #413 & #421 already however Unreal Engine is a really big package which needs at least 80GB free space on mirrors iirc so we need to make sure every mirror has this amount of space before trying to add it :)

**Comment by caniko** [comment]
I saw those packages, moreover, I didn't think that the AUR package was broken. And this isn't `unreal-engine-git`, but `unreal-engine`.

**Comment by caniko** [comment]
> make sure every mirror has this amount of space before trying to add it :)

I see, thank you. +1 from me to add the package to the repo.

**Comment by caniko** [comment]
Oh no, is this what you are talking about? From EULA:
>The Product may not contain any Paid Content Distributed in uncooked source format or any Engine Tools.

Definition of "Engine Tools":
>“Engine Tools” means (a) editors and other tools included in the Engine Code; (b) any code and modules in either the Developer or Editor folders, including in object code format, whether statically or dynamically linked; and (c) other software that may be used to develop standalone products based on the Licensed Technology.

I [tweeted](https://twitter.com/canhtart/status/1403105767411027970) Tim Sweeney, fingers crossed.

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.
