### ISSUE TITLE
pyidm to FireDM

### ISSUE THREAD

**Issue by ahmed-tasaly** [chaotic-aur/packages#663]
### Hello
**PyIDM** has been renamed to **FireDM**  in 2021.2.9 release
and it had many updates since then.

Thanks in advance

**_Links_** 

_https://github.com/firedm/FireDM_
_https://aur.archlinux.org/packages/firedm/_
_https://aur.archlinux.org/packages/pyidm/_      ---->> (Removed)

**Comment by PedroHLC** [comment]
And it now requires `youtube-dlp` instead of `youtube-dlc`.
