### ISSUE TITLE
Incorrect signature 

### ISSUE THREAD

**Issue by robson-66** [chaotic-aur/packages#664]
I don't know if it's the fault of the new `pacman`, but every now and then during an update it pops up info about invalid PGP keys, such as. `dolphin-emu-git` 
https://i.postimg.cc/qMsHx26K/Przechwycenie-obrazu-ekranu-2021-06-10-15-58-04.png

**Comment by PedroHLC** [comment]
You're right, something is borked with it. I'll take a look and close the issue once fixed.

PS: When sending us logs/screenshot, please export/run it with `LANG=en_US.UTF-8`.

**Comment by robson-66** [comment]
I updated `dolphin-emu-git` by downloading it from the `chaotic-aur` server with the `pacman -U` command, and this time the update went through without a problem.

**Comment by PedroHLC** [comment]
Thanks for the alert and testing.
