### ISSUE TITLE
[Request] Ledger-live

### ISSUE THREAD

**Issue by caniko** [chaotic-aur/packages#668]
[haguichi](http://aur.archlinux.org/packages/haguichi) and [ledger-live](http://aur.archlinux.org/packages/ledger-live)

**Comment by dr460nf1r3** [comment]
Probably yet another makedepend missing (had to add git already), so can't compile leder-live 🙄 
https://builds.garudalinux.org/repos/chaotic-aur/logs/ledger-live.log

**Comment by caniko** [comment]
Does ledger live work now

**Comment by dr460nf1r3** [comment]
Well, still the same issue as before sadly. Appearently no fix could be provided by the maintainer. I could offer to add `ledger-live-bin` instead :)

**Comment by caniko** [comment]
The url that was faulty on your last build seems to work just fine for me. Could you try again?

**Comment by dr460nf1r3** [comment]
Even though no more URL issues come up we still have the compilation error. Log URL is still the one posted above.

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.

**Comment by xiota** [comment]
Dropping ledger-live because depends on EOL Electron 32.  Metrics 108.
