### ISSUE TITLE
Pamac-aur

### ISSUE THREAD

**Issue by robson-66** [chaotic-aur/packages#669]
When installing `pamac-aur` I get this error `libalpm12: /usr/lib/libalpm.so.12 is in the file system`
Is really `libalpm12` needed as a dependency, because PKGBUILD with AUR does not have it.

**Comment by dr460nf1r3** [comment]
Its not needed anymore since a few hours, Pamac got updated and works without workaround now. Also, I just removed libalpm12 from the repo for this reason.

**Comment by robson-66** [comment]
Then in that case you need to rebuild `pamac-aur`.

**Comment by dr460nf1r3** [comment]
I found the culprit 😅 will do so asap! :) 
https://github.com/chaotic-aur/interfere/blob/master/pamac-aur/PKGBUILD.append
