### ISSUE TITLE
[Request] tokodon-git

### ISSUE THREAD

**Issue by SameExpert** [chaotic-aur/packages#671]
Please add [tokodon-git](https://aur.archlinux.org/packages/tokodon-git/)

**Comment by dr460nf1r3** [comment]
There are some makedepends missing it seems, I have notified the maintainer as just dropping them in didnt help :)

**Comment by SameExpert** [comment]
I could build it successfully (in KDE Dr460nized) :thinking:
All the make dependencies are in Arch repositories (extra). Maybe you have skipped dependency check while building?

**Comment by dr460nf1r3** [comment]
We build in clean chroots which means packages which are present on your installation due to being pulled in by other packages might be missing in the actual PKGBUILD. This happens a lot actually 😅 
Need to figure out which ones are missing 🤔

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.
