### ISSUE TITLE
[request] multimc5

### ISSUE THREAD

**Issue by creeper123123321** [chaotic-aur/packages#673]
https://aur.archlinux.org/packages/multimc5/

**Comment by xiota** [comment]
Note: `multimc5` dropped because:
* Out of date.
* Broken.
* Pinned comment on aur page, "It is illegal to redistribute any binaries created with this script because of the upstream project's licensing."  (Related to `multimc-git` ban?)

**Comment by Technetium1** [comment]
Oof... This was supposed to have been dropped already...

**Comment by dr460nf1r3** [comment]
Please also add to banned packages in this case 😄
