### ISSUE TITLE
Error on installing VS Code 1.57

### ISSUE THREAD

**Issue by uroybd** [chaotic-aur/packages#674]
Hi,
I'm facing a problem updating VS Code to 1.57.

Here's the relevant log:
```
Download of visual-studio-code-bin (1.57.0-1) started
Download of visual-studio-code-bin (1.57.0-1) finished
Checking keyring...
Checking integrity...
Error: visual-studio-code-bin: signature from "Nico Jensch <dr460nf1r3@garudalinux.org>" is unknown trust
```

I'm in Manjaro Linux Gnome Edition.

**Comment by uroybd** [comment]
Re-adding the repository solved the problem.

**Comment by dr460nf1r3** [comment]
Nice to see that you solved already :) pls note that some applications might not work on Manjaro due to being compiled against different library version.
