### ISSUE TITLE
dotnet-sdk-bin, dropbox, google-chrome, libadwaita, teams are out of date

### ISSUE THREAD

**Issue by dodgypast** [chaotic-aur/packages#679]
![image](https://user-images.githubusercontent.com/24266439/121863982-99ef9a00-cd26-11eb-8da0-42edae07fffa.png)

**Comment by PedroHLC** [comment]
@dr460nf1r3 they're all in dragon-cluster's nightly. Are you sure that routine is working at all?

**Comment by dr460nf1r3** [comment]
Its not updating for the same reason as the morning routine. I ran the routine manually to not have it killed so everything is updated now.

**Comment by dr460nf1r3** [comment]
Btw, dotnet-sdk-bin is no longer needed as its in community - I removed it. If there is some package requiring the -bin let me know so we can drop the correct one into interfere :)
