### ISSUE TITLE
gpg errors on chaotic-aur   

### ISSUE THREAD

**Issue by Area51Kacz** [chaotic-aur/packages#681]
I've the chaotic-aur repo
And it went .... crazy

I've updated as usual (pacman -Syyu)  and i got this message

error: brave-nightly-bin: signature from "Nico Jensch dr460nf1r3@garudalinux.org" is unknown trust
:: File /var/cache/pacman/pkg/brave-nightly-bin-1.27.62-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: firefox-esr-bin: signature from "Nico Jensch dr460nf1r3@garudalinux.org" is unknown trust
:: File /var/cache/pacman/pkg/firefox-esr-bin-78.11.0-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: google-chrome: signature from "Nico Jensch dr460nf1r3@garudalinux.org" is unknown trust
:: File /var/cache/pacman/pkg/google-chrome-91.0.4472.101-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).

How could i update these chaotic-aur packages?

**Comment by robson-66** [comment]
I suggest you go to `/var/cache/pacman/pkg` and install the package with `pacman -U google-chrome-91.0.4472.101-1-x86_64.pkg.tar.zst`.

**Comment by dr460nf1r3** [comment]
Did you install the Chaotic keyring properly?

**Comment by mixalis1987** [comment]
I have the same problem and I also have the keyring. I have google-chrome and Brave-bin installed and it happens on those two.

**Comment by dr460nf1r3** [comment]
Just rebuilt the mentioned packages, please let me know if that fixes your issue 😊

**Comment by mixalis1987** [comment]
> Just rebuilt the mentioned packages, please let me know if that fixes your issue 😊

That didn't work.

`error: brave-bin: signature from "Nico Jensch <dr460nf1r3@garudalinux.org>" is unknown trust
:: File /var/cache/pacman/pkg/brave-bin-1:1.25.72-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: google-chrome: signature from "Nico Jensch <dr460nf1r3@garudalinux.org>" is unknown trust
:: File /var/cache/pacman/pkg/google-chrome-91.0.4472.106-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.`

**Comment by mixalis1987** [comment]
I just installed on EndeavourOS on my VM and the install was fine. But on my main OS Manjaro it doesnt work. Its confusing.

**Comment by mixalis1987** [comment]
Ok so, I reinstalled the keyring and mirrorlist becasue I couldnt think of anything else and the install now works for me again.

**Comment by dr460nf1r3** [comment]
Oh that kind of explains it - Manjaro uses a so called "pacman-init" service which populates the keyring during every boot. Works for Manjaro & Arch keyrings but Chaotic-AUR is sadly not included. Make sure to mask the service to not run into issues again! :)

**Comment by PedroHLC** [comment]
@mixalis1987 We've now made an announcement of it, that should help you to prevent this from happening in the future: https://t.me/chaotic_aur/618

**Comment by mixalis1987** [comment]
@Pedro Henrique Lara Campos ***@***.***>

That's great. 👍I was just about to ask if that will break any of Manjaro
keyring stuff. But the announcement said no. So all good :)

**Comment by Area51Kacz** [comment]
@PedroHLC i've done it  and im still having issues

**Comment by Area51Kacz** [comment]
it worked now (reinstall chaotic-aur AND  disable  manjaro pacman-service)

**Comment by PedroHLC** [comment]
@Area51Kacz keep me in contact in case it happens again...
Also, let me know what you update and if possible logs from pamac/pacman and journal from that service.
Thank you!

**Comment by joe733** [comment]
Facing a similar issue:

```bash
~ took 3s 
➜ sudo pacman -Sy tela-circle-icon-theme-git  
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 chaotic-aur is up to date
 andontie-aur is up to date
 archlinuxcn is up to date
resolving dependencies...
looking for conflicting packages...

Packages (1) tela-circle-icon-theme-git-2022.02.08.r20.g5809e613-1

Total Download Size:    76.19 MiB
Total Installed Size:  224.51 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 tela-circle-icon-theme-git-2022.02.08.r20.g5809...    76.2 MiB  3.75 MiB/s 00:20 [##############################################] 100%
(1/1) checking keys in keyring                                                    [##############################################] 100%
(1/1) checking package integrity                                                  [##############################################] 100%
error: tela-circle-icon-theme-git: signature from "Nico Jensch (Chaotic-AUR) <dr460nf1r3@garudalinux.org>" is invalid
:: File /var/cache/pacman/pkg/tela-circle-icon-theme-git-2022.02.08.r20.g5809e613-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 

```

does not happen with other packages..

**Comment by dr460nf1r3** [comment]
This will eventually be fixed soonish, a full rebuild is currently in progress. Once you notice updates coming in and the issue is still happening, please open a new issue and we will sort this asap :)
