### ISSUE TITLE
[Request] Add youtube-music-bin & ytmdesktop

### ISSUE THREAD

**Issue by TheDudeThatCode** [chaotic-aur/packages#686]
Please add these packages as youtube-bin is also available in chaotic-aur: -

- https://aur.archlinux.org/packages/youtube-music-bin/
- https://aur.archlinux.org/packages/ytmdesktop/

**Comment by Technetium1** [comment]
ytmdesktop depends on python2, so it will be removed, youtube-music-bin stays.

**Comment by xiota** [comment]
The -git variant is failing to build because Electron 35 isn't in Arch repos yet.  Metrics for anyone interested:

* youtube-music-git # 415
* youtube-music-bin # 998

**Comment by xiota** [comment]
Switching youtube-music-git to custom package because of build failures related to Electron version mismatch.

https://github.com/th-ch/youtube-music/commit/0108e3f603e9edb2e244925739e0b291538d2393

Metrics:

* youtube-music-bin # 857
* youtube-music-git # 76

**Comment by xiota** [comment]
Dropping because upstream project appears to be having some difficulties.

Metrics:

* youtube-music-bin # 1937
* youtube-music-git # 359
