### ISSUE TITLE
emacs-native-comp-git absoulte?

### ISSUE THREAD

**Issue by Flinner** [chaotic-aur/packages#687]
native comp branch has been  [merged](https://git.savannah.gnu.org/gitweb/?p=emacs.git;a=commit;h=289000eee729689b0cf362a21baa40ac7f9506f6)

[reddit post](https://www.reddit.com/r/emacs/comments/myej3z/the_nativecompilation_branch_was_just_merged_into/)

will both `emacs-native-comp-git` and `emacs-pgtk-native-comp-git ` be removed?

**Comment by PedroHLC** [comment]
This should be discussed here: https://aur.archlinux.org/packages/emacs-native-comp-git/#comment-813032
As we're only building the AUR's PKGBUILD, we'll replicate the decisions made there...

**Comment by Flinner** [comment]
thanks for the fast reply.
