### ISSUE TITLE
[Issue] joplin-desktop is outdated

### ISSUE THREAD

**Issue by rkunschke** [chaotic-aur/packages#695]
Joplin desktop is outdated. 
I recently build it via AUR in version 2.0.10-1 The new build joplin-2.0.11-1 failed in AUR too. I will report there too.
https://aur.archlinux.org/pkgbase/joplin/#news

**Comment by PedroHLC** [comment]
@dr460nf1r3 `sed -i'' 's/joplin-desktop/joplin' dragon-cluster/nightly.txt`
Looks like the pkgbase was renamed.

**Comment by dr460nf1r3** [comment]
Changed.

**Comment by rkunschke** [comment]
Thank you :)
