### ISSUE TITLE
[Request] yuzu-git

### ISSUE THREAD

**Issue by NerosTie** [chaotic-aur/packages#698]
`yuzu-git` is more stable than `yuzu-mainline-git` (stable vs beta, more or less), that's why I think it could be a good addition.

GIT: https://github.com/yuzu-emu/yuzu

AUR: https://aur.archlinux.org/packages/yuzu-git/

**Comment by dr460nf1r3** [comment]
The actual AUR PKGBUILD is still broken, a fixed version has been created by another AUR user which we will use as source to build from until the package has been fixed. 
https://gitlab.com/tallero/yuzu-git-aur.git
