### ISSUE TITLE
[Request] tutanota-desktop

### ISSUE THREAD

**Issue by svdm-artix** [chaotic-aur/packages#702]
I would appreciate it if tutanota could be added. 

https://aur.archlinux.org/packages/tutanota-desktop

They're just out of beta and the app is great!

**Comment by svdm-artix** [comment]
If this isn't possible the https://aur.archlinux.org/packages/tutanota-desktop-bin version would be okay/appreciated!

**Comment by dr460nf1r3** [comment]
The non -bin version sadly [fails to compile ](https://builds.garudalinux.org/repos/chaotic-aur/logs/tutanota-desktop.log) so the -bin version has been added :)
