### ISSUE TITLE
emacs-git replaces chaotic-aur/emacs-pgtk-native-comp-git?

### ISSUE THREAD

**Issue by drishal** [chaotic-aur/packages#705]
There is some weird issue, on upgrading today, I get the issue `:: Replace emacs-git with chaotic-aur/emacs-pgtk-native-comp-git? [Y/n] `, some conflict in packages?

**Comment by dr460nf1r3** [comment]
Well, I looked at the PKGBUILD - in there we have `replaces=('emacs26-git' 'emacs27-git' 'emacs-git' 'emacs-seq')` which kind of explains it. We can remove that part so the prompt does not appear again :)

**Comment by dr460nf1r3** [comment]
That should do the trick :) https://github.com/chaotic-aur/interfere/commit/e27e4d879d7f50bbb203e3cec8a36ab623971754
