### ISSUE TITLE
Issues when installing package groups?

### ISSUE THREAD

**Issue by drishal** [chaotic-aur/packages#706]
when  I am installing some popular package groups like `gnome` or `kde-applications` I get some weird conflict issues due to which either the installation of packages fails, or gets replaced by a `-git` version which could be potentially buggy
For eg when I do `sudo pacman -S gnome` it fails with `gdm-plymouth and gdm-prime are in conflict`. Maybe either resolve these conflicts by removing the conflicting packages or renaming those groups to something like `gnome-chaotic` or `kde-chaotic`

**Comment by dr460nf1r3** [comment]
Related to #542

**Comment by PedroHLC** [comment]
Closing this, duplicate of #542
