### ISSUE TITLE
Package request Emacs-ng 

### ISSUE THREAD

**Issue by drishal** [chaotic-aur/packages#708]
can we please have Emacs-ng and a  more up-to-date version of  emacs-ng-git?  compiling rust and webrender on a laptop is NOT fun
https://aur.archlinux.org/packages/emacs-ng/
https://aur.archlinux.org/packages/emacs-ng-git/
https://github.com/emacs-ng/emacs-ng

**Comment by xiota** [comment]
Dropping.  Both packages were paused about a year ago in 90c1e3da8d28555db2705e5a748c40f63f60e558 for failure to build.  Confirmed they are still both unbuildable.  `aur/emacs-ng` is unmaintained.  Upstream repo has no new commits for four months.  Metrics:

* `emacs-ng` 19
* `emacs-ng-git` 6
