### ISSUE TITLE
[Request] power-profiles-daemon

### ISSUE THREAD

**Issue by maydayv7** [chaotic-aur/packages#710]
Link: https://aur.archlinux.org/packages/power-profiles-daemon/
Can it also be added to the gnome group

**Comment by dr460nf1r3** [comment]
What is the reason for having it added to the GNOME group?

**Comment by maydayv7** [comment]
This is because it appears in gnome-control-center:
![Screenshot from 2021-06-28 16-04-06](https://user-images.githubusercontent.com/73811274/123622931-7f3f1a00-d82a-11eb-8a77-d64eade714e2.png)

**Comment by dr460nf1r3** [comment]
Sounds like a valid reason to me. Done 😁

**Comment by maydayv7** [comment]
Thx ;)
