### ISSUE TITLE
[Request] FFmpeg stuff for Yandex.Browser Beta

### ISSUE THREAD

**Issue by Scorpi-ON** [chaotic-aur/packages#719]
I would be glad to see these packages in `chaotic-aur` repos:
- [yandex-browser-ffmpeg-codecs-opera](http://aur.archlinux.org/packages/yandex-browser-ffmpeg-codecs-opera)
- [opera-beta-ffmpeg-codecs](http://aur.archlinux.org/packages/opera-beta-ffmpeg-codecs)

It takes too much time and power to compile them directly from AUR. ☹️

**Comment by xiota** [comment]
Dropping opera-beta-ffmpeg-codecs because AUR package is orphaned and no other package uses it.  Metrics 51.
