### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by Bhooty** [chaotic-aur/packages#724]
https://aur.archlinux.org/packages/orchis-theme-git/

https://aur.archlinux.org/packages/plata-theme/

https://aur.archlinux.org/packages/qogir-gtk-theme/

https://aur.archlinux.org/packages/materia-theme-git/

**Comment by joe733** [comment]
Orchis theme is missing

```shell
~ 
➜ sudo pacman -Syu                
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 chaotic-aur is up to date
 andontie-aur is up to date
 archlinuxcn is up to date
:: Starting full system upgrade...
warning: webcamoid: local (9.0.0-2) is newer than chaotic-aur (9.0.0-1)
 there is nothing to do

~ took 4s 
➜ sudo pacman -Ss orchis-theme-git

~ 
➜ 
```

**Comment by dr460nf1r3** [comment]
It was possibly on the Garuda builders list until I removed it when cleaning up the repo. I noticed you opened an issue for it, which is great :)
