### ISSUE TITLE
[Request] godot-mono

### ISSUE THREAD

**Issue by Krutonium** [chaotic-aur/packages#726]
- Link to the package(s) in AUR: [godot-mono](https://aur.archlinux.org/packages/godot-mono/)

- Utility this package has for you: Game Development

 It's for developing games, specifically using C#.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO (but also yes, because it makes it easy to test said games on Linux)

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [x] YES (but apparently it requires X)
  - [ ] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by dr460nf1r3** [comment]
This does not compile cleanly, notified the maintainer as well but its appearently not a packaging issue. Maybe @PedroHLC can have a look :)

**Comment by Krutonium** [comment]
They've replied on the AUR.

**Comment by PedroHLC** [comment]
I left a comment about how can they fix it, if they don't apply we have our methods, but let's see if they do it first:
https://aur.archlinux.org/packages/godot-mono/#comment-817364

One thing that could help is suggesting a working patch of the PKGBUILD. Sadly I'm without free time :crying_cat_face:

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.

**Comment by Krutonium** [comment]
I mean, that's hardly fair - Surely you can grandfather old requests that are in progress without making it a hassle?

**Comment by Krutonium** [comment]
Also we can't re-open issues. That's a you thing.

**Comment by dr460nf1r3** [comment]
No need to feel attacked. I'm going to reopen the issue for you, no problem.

**Comment by PedroHLC** [comment]
> I mean, that's hardly fair - Surely you can grandfather old requests that are in progress without making it a hassle?

:sweat_smile: Sorry, there were some suspicious actions going on, and we decided to complicate a few things so that we could audit what was human and what was not.

No disrespect was intended. I'm really sorry for any fuss this may have caused.

> Also we can't re-open issues. That's a you thing.

Yeah, I should have tested this before.

**Comment by PedroHLC** [comment]
@dr460nf1r3 doesn't look like this package will receive the headless build in AUR, I think we should take the interfere approach...

**Comment by Krutonium** [comment]
Understood! Thanks for hosting this regardless :)
