### ISSUE TITLE
yaru group not updating in chaotic?

### ISSUE THREAD

**Issue by coxackie** [chaotic-aur/packages#727]
All the components of the `yaru` group have been updated on 2021-07-08 to 21.10.1-1 in AUR, but the version here is still stuck at 21.04.1-5. Is there any problem in building them?

FYI, the packages of the group are:
```
yaru-unity-theme
yaru-sound-theme
yaru-session
yaru-metacity-theme
yaru-icon-theme
yaru-gtksourceview-theme
yaru-gtk-theme
yaru-gnome-shell-theme
```

Many thanks!

**Comment by dr460nf1r3** [comment]
No idea why it didnt update as the package is clearly on the building list & a manual rebuild worked 🤔 anyway its up to date now :)

**Comment by coxackie** [comment]
not sure if this was fixed after all, since the `yaru` packages have been updated again in the AUR yesterday, but this update is not reflected in `chaotic`.

**Comment by dr460nf1r3** [comment]
Weird! Actually this should've been fixed here https://github.com/chaotic-aur/packages/commit/cf03c3777bd22baee8a3e5292ac2f0da51510672, definitely gotta monitor if it gets stuck with the next update again 🤔
