### ISSUE TITLE
[Request] mips64-elf-gcc, mips64-elf-newlib

### ISSUE THREAD

**Issue by TheEssem** [chaotic-aur/packages#732]
`mips64-elf-binutils` is already in the repo (as per #680), so it should make sense to add the rest of the build packages especially since it could help certain development areas (e.g. N64 homebrew) and building GCC with newlib support can be tedious.

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.
