### ISSUE TITLE
[Request] webbrowser

### ISSUE THREAD

**Issue by svdm-artix** [chaotic-aur/packages#737]
Could https://aur.archlinux.org/packages/webbrowser-git/ be added as well if possible? Thanks!

**Comment by dr460nf1r3** [comment]
> Just so everyone is aware, there is a bug preventing it from being built. Once this is resolved the package will be updated.

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.
