### ISSUE TITLE
[Request] tealdeer, qtile-git, river-git, spacefm-git, foot, pywayland, pywlroots

### ISSUE THREAD

**Issue by RohitSingh107** [chaotic-aur/packages#743]
https://aur.archlinux.org/tealdeer.git

http://aur.archlinux.org/packages/qtile-git

http://aur.archlinux.org/packages/river-git

http://aur.archlinux.org/packages/spacefm-git

http://aur.archlinux.org/packages/foot

http://aur.archlinux.org/packages/pywayland

http://aur.archlinux.org/packages/pywlroots

THANKS :)

**Comment by RohitSingh107** [comment]
Irony! pywayland and pywlroots just today got added to official arch community repo. So these can be removed from chaotic because both are same packages in chaotic and community repo, resources should not be wasted :)

**Comment by dr460nf1r3** [comment]
This is irony indeed, solved :D

**Comment by RohitSingh107** [comment]
Hello friend, again tealdeer too just got added to Arch community repo so it can be removed from chaotic, resources should not ne wasted 😃

**Comment by dr460nf1r3** [comment]
You were ahead of the time 😜

**Comment by xiota** [comment]
Dropping `spacefm-git`.  Failed to build because of gcc14 changes.  Upstream was discontinued 2018.  Metrics 31.
