### ISSUE TITLE
[Bug] ananicy-cpp outdated since several days.

### ISSUE THREAD

**Issue by aviallon** [chaotic-aur/packages#760]
In AUR, `ananicy-cpp` is at version `0.7.2`.
In chaotic, it is still at `0.5.3` however.

A lot of features and bugfixes have been added since then, and according to the repo, it is supposed to be checked hourly (?)

Thanks for your work btw.

**Comment by dr460nf1r3** [comment]
There happens to be an issue during linking, have a look at the [logs](https://builds.garudalinux.org/repos/chaotic-aur/logs/ananicy-cpp.log) :)

**Comment by aviallon** [comment]
> There happens to be an issue during linking, have a look at the [logs](https://builds.garudalinux.org/repos/chaotic-aur/logs/ananicy-cpp.log) :)

Thanks! I have found and fixed the issue (a dependency problem…), caused by spdlog not keeping up with fmtlib…

**Comment by dr460nf1r3** [comment]
Very nice, it compiled successfully now 😁

**Comment by aviallon** [comment]
PS: the same issues happened with `ananicy-cpp-git`.

**Comment by dr460nf1r3** [comment]
I know, rebuilt this one with the other one already 😋

**Comment by aviallon** [comment]
Very nice! Also, thanks for making me discover this: https://github.com/aviallon/aviallon  
Very useful.

**Comment by dr460nf1r3** [comment]
Hehe, discovered by someone else on GitHub as well. A nice hidden feature of GitHub 😬
