### ISSUE TITLE
[Request] GNOME Performance Packages

### ISSUE THREAD

**Issue by maydayv7** [chaotic-aur/packages#763]
[mutter-performance](https://aur.archlinux.org/packages/mutter-performance)
[gnome-shell-performance](https://aur.archlinux.org/packages/gnome-shell-performance/)

**Comment by xiota** [comment]
Dropping gnome-shell-performance because no difference from `extra/gnome-shell`.  Also flagged for nearly two months and has new maintainer who hasn't pushed any changes.  Metrics 1279.
