### ISSUE TITLE
[Request] Add sublime-text-4 & sublime-text-3

### ISSUE THREAD

**Issue by TheDudeThatCode** [chaotic-aur/packages#769]
Please add these packages in chaotic-aur: -

- https://aur.archlinux.org/packages/sublime-text-4/
- https://aur.archlinux.org/packages/sublime-text-3/

**Comment by xiota** [comment]
Dropping `sublime-text-3` because it's no longer supported by the developer.  (Licenses are for three years.  Last build was Oct 2019.)

Metrics:

* sublime-text-3 # 33
* sublime-text-4 # 659
