### ISSUE TITLE
[request] chatterino2-7tv-git

### ISSUE THREAD

**Issue by bennyhillthebest** [chaotic-aur/packages#770]
AUR: https://aur.archlinux.org/packages/chatterino2-7tv-git/
GitHub: https://github.com/SevenTV/chatterino7

Thanks a lot!!!

**Comment by bennyhillthebest** [comment]
can the package be updated? right now it is at release 3277, while the latest is 3358. Thank you very much!

**Comment by dr460nf1r3** [comment]
The name in the list was missing a "2" in it's pkgname, a typo I made when adding it 😅 will be corrected later so it'll build hourly as expected :)
