### ISSUE TITLE
[request] scilab

### ISSUE THREAD

**Issue by bennyhillthebest** [chaotic-aur/packages#771]
AUR: https://aur.archlinux.org/packages/scilab/
Original source: https://www.scilab.org/
GitHub: https://github.com/bartoszek/AUR-scilab

Thank you very much!

**Comment by dr460nf1r3** [comment]
One last dependency is missing an update, `apache-lucene`.

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.

**Comment by xiota** [comment]
Dropping this because it's been broken for years.  `scilab-bin` (#2821) is available.
