### ISSUE TITLE
[Request] Tootle

### ISSUE THREAD

**Issue by maydayv7** [chaotic-aur/packages#781]
Link: http://aur.archlinux.org/packages/tootle

**Comment by dr460nf1r3** [comment]
@PedroHLC this could be problematic? 
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tootle#n49

**Comment by PedroHLC** [comment]
> @PedroHLC this could be problematic?
> https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=tootle#n49

No, it's safe.

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.
