### ISSUE TITLE
Openvpn3 for using .ovpn

### ISSUE THREAD

**Issue by Bhooty** [chaotic-aur/packages#782]
http://aur.archlinux.org/packages/openvpn3

**Comment by Bhooty** [comment]
@dr460nf1r3 sir any update? :3

**Comment by dr460nf1r3** [comment]
I'm very busy these days, not sure if you saw the amount of open issues we got right now 🤔

**Comment by Bhooty** [comment]
> 
> 
> I'm very busy these days, not sure if you saw the amount of open issues we got right now 🤔

i replied thinking it had dependency which were not available :3

**Comment by xiota** [comment]
Can someone explain the benefit of `openvpn3` over the default `openvpn` package that is already in the Arch repositories?  The package isn't building, and it looks like there are a lot of upstream issues.  Wondering if it should just be dropped.

**Comment by dr460nf1r3** [comment]
I think at this time we did not have `openssl3` in the Arch repos, now we do so I'm also wondering what benefit it brings.

**Comment by xiota** [comment]
@danayer Please open a new request because author of this one is now ghost.
