### ISSUE TITLE
tuner

### ISSUE THREAD

**Issue by pixtolero** [chaotic-aur/packages#786]
https://aur.archlinux.org/packages/tuner

**Comment by xiota** [comment]
Reports on AUR page indicate `tuner` is not producing sound.  Same issue with `tuner-git`.

**Comment by xiota** [comment]
Just tested.  Need to install `gst-libav` to play AAC stations.

**Comment by xiota** [comment]
Dropping because flagged couple months without maintainer response.  Upstream has closed codeberg repo in favor of github.  Metrics 56.
