### ISSUE TITLE
[Request] kicad-nightly, kicad-library-nightly, kicad-library-3d-nightly

### ISSUE THREAD

**Issue by perigoso** [chaotic-aur/packages#787]
https://aur.archlinux.org/packages/kicad-nightly/
https://aur.archlinux.org/packages/kicad-library-nightly/
https://aur.archlinux.org/packages/kicad-library-3d-nightly/

warning: kicad-library-3d-nightly is rather big, could be skipped for that reason

**Comment by dr460nf1r3** [comment]
This does not compile in our clean chroot, maybe the maintainer is able to provide a fix :)

**Comment by perigoso** [comment]
do you have an output of the issue?

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.
