### ISSUE TITLE
[Request] linux-g14 and linux-zen-g14

### ISSUE THREAD

**Issue by k-amin07** [chaotic-aur/packages#792]
Hi, please add the Asus Zephyrus G14 specific kernels linux-g14 and linux-zen-g14 to chaotic-aur. Thanks!

https://aur.archlinux.org/packages/linux-zen-g14

https://aur.archlinux.org/packages/linux-zen-g14-headers

**Comment by PedroHLC** [comment]
@dr460nf1r3 I think you added the non -zen ones...

**Comment by k-amin07** [comment]
Hi, thanks for adding the linux-g14. Could you please add the linux-zen-g14 also?

**Comment by dr460nf1r3** [comment]
Are really both of them needed or does the linux-zen one suffice?
