### ISSUE TITLE
[Bug] ananicy-cpp-git fails because repo URL changed

### ISSUE THREAD

**Issue by aviallon** [chaotic-aur/packages#797]
See the end of https://builds.garudalinux.org/repos/chaotic-aur/logs/ananicy-cpp-git.log:
```
==> ERROR: /home/main-builder/pkgsrc/ananicy-cpp is not a clone of https://gitlab.com/ananicy-cpp/ananicy-cpp.git
    Aborting...
```

@dr460nf1r3 I updated the URL in the AUR package because the older one (aviallon/ananicy-cpp) was still being used.

**Comment by dr460nf1r3** [comment]
Yeah, that happens when git sources aren't the same. Cleared the dir & rebuild the package. 😁
