### ISSUE TITLE
[Remove] silos

### ISSUE THREAD

**Issue by svdm-artix** [chaotic-aur/packages#798]
https://aur.archlinux.org/packages/silos/
https://aur.archlinux.org/packages/silo-netflix/
https://aur.archlinux.org/packages/silo-primevideo/

Thanks!

**Comment by xiota** [comment]
Noticed these while looking at packages for v4 transition.  I'm generally suspicious of these types of packages (unofficial apps for paid services), and would prefer to drop on principle.

Maintainer is upstream developer.  Main `silos` package has some minor issues.

Metrics:

* silos 110
* silo-netflix 40
* silo-trello 4
* silo-primevideo 25

**Comment by Technetium1** [comment]
If there are problems to be resolved, then they should be reported. If they do not get fixed at that point, it would seem reasonable to drop. I don't have any particularly strong feelings either way about this package.

**Comment by xiota** [comment]
Dropping packages related to `silos` because of maintenance issues.  Also, trademark and other issues.

If only there were an app that allowed users to visit any site they wanted...

Metrics (down 47% from previous):

* silos 61
* silo-netflix 19
* silo-trello 4
* silo-primevideo 10
