### ISSUE TITLE
[Request] swift-language-git

### ISSUE THREAD

**Issue by Elara6331** [chaotic-aur/packages#799]
- Link to the package(s) in AUR: https://aur.archlinux.org/packages/swift-language-git

- Utility this package has for you:

  This package contains the swift programming language.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [X] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [X] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [X] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [X] NO

- Does the package's license allows us to redistribute it?:

  - [X] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [X] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [X] YES

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.

**Comment by Arsen6331** [comment]
I have edited my post to use the new template, but I am unable to reopen the issue.

**Comment by PedroHLC** [comment]
@dr460nf1r3 do you recall what was the bug here? If it's something toolbox-side, please assign the issue to me.

**Comment by dr460nf1r3** [comment]
`-- Install configuration: "Release" CMake Error at cmake_install.cmake:46 (file): file cannot create directory: /home/main-builder/pkgwork/pkg/swift-language-git/usr/lib/swift-git/bin. Maybe need administrative privileges. Call Stack (most recent call first): /home/main-builder/pkgwork/src/build/buildbot_linux/llvm-linux-x86_64/tools/cmake_install.cmake:66 (include) /home/main-builder/pkgwork/src/build/buildbot_linux/llvm-linux-x86_64/cmake_install.cmake:77 (include) `

Does not seem like a toolbox issue to me 🤔

**Comment by PedroHLC** [comment]
> `-- Install configuration: "Release" CMake Error at cmake_install.cmake:46 (file): file cannot create directory: /home/main-builder/pkgwork/pkg/swift-language-git/usr/lib/swift-git/bin. Maybe need administrative privileges. Call Stack (most recent call first): /home/main-builder/pkgwork/src/build/buildbot_linux/llvm-linux-x86_64/tools/cmake_install.cmake:66 (include) /home/main-builder/pkgwork/src/build/buildbot_linux/llvm-linux-x86_64/cmake_install.cmake:77 (include) `
> 
> Does not seem like a toolbox issue to me thinking

The package is trying to write the files to `"$pkgdir"` during `build()`...

**Comment by spacecowgirl314** [comment]
I was just going to make my own issue. However, I'd like the stable version swift-language. I'd really appreciate this in chaotic-aur.

**Comment by PedroHLC** [comment]
> I was just going to make my own issue. However, I'd like the stable version swift-language. I'd really appreciate this in chaotic-aur.

Hi @spacecowgirl314, both the packages have the same issue. This line:
```bash
python swift/utils/build-script --preset=buildbot_linux,no_test install_destdir="$pkgdir"
```
Is building swift and moving the files to `$pkgdir` -- Arch disallows writing to `$pkgdir` outside the `package()` function. That's a security measure.

Because of that, we cannot add those PKGBUILDs. But, if you or @Arsen6331 or anyone else decides to host a proper PKGBUILD (doing build in `build()`, and packaging in `package()`), we'll be glad to include it.

**Comment by spacecowgirl314** [comment]
I've left a comment on the AUR package for the maintainer. Hopefully they're able to fix it and we can revisit this issue.

**Comment by soloturn** [comment]
@PedroHLC @spacecowgirl314 can you please add a link where you saw that one shoudl not write into $pkgdir?

swif-language-git builds now outside and moves the stuff into pkgdir:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=swift-language-git#n129

**Comment by jonathonf** [comment]
From https://man.archlinux.org/man/PKGBUILD.5,

> **package() Function**
> The package() function is used to install files into the directory that will become the root directory of the built package and is run after all the optional functions listed below. The packaging stage is run using fakeroot to ensure correct file permissions in the resulting package. All other functions will be run as the user calling makepkg.

So, packaging should be done in the package() function to ensure permissions are correct.

Plus,

> **pkgdir**
> This contains the directory where makepkg bundles the installed package. This directory will become the root directory of your built package. This variable should only be used in the package() function.

**Comment by SolarAquarion** [comment]
@soloturn looking at the fedora rpm and nix files, they create a .tar.gz and then install that via the package function of the respective repositories

**Comment by soloturn** [comment]
adjusted the PKGBUILD, hope its fine now.

**Comment by Technetium1** [comment]
@soloturn build still fails: https://builds.garudalinux.org/repos/chaotic-aur/logs/swift-language-git.log

**Comment by xiota** [comment]
Closed this too early.  Build still fails.  [swift-language-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/swift-language-git.log)

Some issue cloning the apple/swift and apple/llvm-project repositories with `git clone --mirror`.  `git clone` and `git clone --bare` work as expected.  Doesn't affect forks.

Anyone know how to ask github to look at the problem?

**Comment by Technetium1** [comment]
@xiota Yes! We'll probably wait a little while since we're on free tier. Be **very** specific: https://support.github.com/contact?tags=rr-general-technical

**Comment by xiota** [comment]
@Technetium1 Thanks.  I'll wait a week or so... Then send you a draft for review before submitting anything...

**Comment by Technetium1** [comment]
@xiota No need to wait, I mean to say their responses sometimes take a long time. Feel free to Telegram it!

**Comment by xiota** [comment]
`swift-language-git` appears to have never successfully built, even though the aur package is actively maintained (last updated 2023-09-03).  Adding `swift-language` to see if it builds.  If not, will probably drop this.

**Comment by xiota** [comment]
Rejecting this because `swift-lanuage-git` has never successfully built since it was requested and added to the package lists.  `swift-language` has the same maintainer and similar issues.   These currently include: Broken patches that maintainer has not updated despite multiple requests from different people.  Incorrectly preparing submodules.

**Comment by xiota** [comment]
I was added as comaintainer of `aur/swift-language` and recently figured out how to fix it.  It is very difficult to build because it depends on itself to compile.  To bootstrap requires `swift-bin`.  Then if it breaks, `swift-bin` is again needed to fix.  So why not stick with `swift-bin` (#2855)?
