### ISSUE TITLE
[Request]fzf-tab-git

### ISSUE THREAD

**Issue by brendenhoffman** [chaotic-aur/packages#803]
https://aur.archlinux.org/packages/fzf-tab-git/
Descprition: Replace zsh's default completion selection menu with fzf (git version)

I recently submitted this package to the aur. I think its good to go, but you might give it a good look over before its put it in this repo.

**Comment by dr460nf1r3** [comment]
```
  ln -s "fzf-tab.zsh" \
    "${pkgdir}/usr/share/zsh/plugins/${pkgname}/fzf-tab.plugin.zsh"
```
Why exactly do you symlink the $srcdir with $pkgdir?

**Comment by brendenhoffman** [comment]
Oops. I did not notice it was going from $srcdir to $pkgdir. I can fix that. I am a little conflicted on how to handle that file, it's for oh my zsh, and it's included in the git repo, but I linked it in case it was deemed unnecessary.
