### ISSUE TITLE
amule-git

### ISSUE THREAD

**Issue by heroku-miraheze** [chaotic-aur/packages#809]
https://aur.archlinux.org/packages/amule-git/

**Comment by dr460nf1r3** [comment]
Broken as well,

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.
