### ISSUE TITLE
amule-adnza

### ISSUE THREAD

**Issue by heroku-miraheze** [chaotic-aur/packages#810]
https://aur.archlinux.org/packages/amule-adnza/

**Comment by dr460nf1r3** [comment]
This package depends on a nonexistent wxgtk package, another package which provides this is also broken and hasn't seen an update since 2016

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.
