### ISSUE TITLE
[Remove] gnome-terminal-git, gnome-contacts-git, gnome-calendar-git

### ISSUE THREAD

**Issue by svdm-artix** [chaotic-aur/packages#811]
~~gnome-terminal-git~~
~~gnome-contacts-git~~
~~gnome-calendar-git~~

**Comment by dr460nf1r3** [comment]
`Gnome-terminal-git` is broken, in need of an update..

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.

**Comment by xiota** [comment]
`gnome-terminal-git` was already effectively dropped a couple years ago 3af0e9fdad151f6fd5a8e5fd2a85f6af15e00234.  Since it is *still* broken, I plan to drop it for good, along with its dependencies.  Anyone who still wants this package may open a new request after it has been fixed.

**Comment by xiota** [comment]
`gnome-calendar-git` is also broken.  Will notify maintainer via comment on AUR page.
