### ISSUE TITLE
[Request] firefox-appmenu

### ISSUE THREAD

**Issue by maydayv7** [chaotic-aur/packages#816]
Link: https://aur.archlinux.org/packages/firefox-appmenu  
The `firefox-kde-opensuse` package in the repos is very often outdated (even right now), and this version is well-maintained and up to date, so if this package is added, the other can be removed.

**Comment by dr460nf1r3** [comment]
The KDE build is not only about the appmenu but the KDE integration. It's PKGBUILD is broken currently, waiting for a fix..

**Comment by maydayv7** [comment]
Yes, also KDE integration, but it contains extensive patches, and this package may also be used in XFCE for the vala-appmenu plugin.
Otherwise, it's fine, I'll close the request

**Comment by maydayv7** [comment]
Also, this package is independent of the other, it contains normal firefox along with the Ubuntu appmenu patch

**Comment by dr460nf1r3** [comment]
Would you be fine with the -bin version as well? 
We did have the package in repo some time ago but dropped it because other packages provided the appmenu patch as well 🤔

**Comment by maydayv7** [comment]
Yes, any version is fine

**Comment by dr460nf1r3** [comment]
Sure thing then :D
