### ISSUE TITLE
goodvibes-git

### ISSUE THREAD

**Issue by heroku-miraheze** [chaotic-aur/packages#820]
https://aur.archlinux.org/packages/goodvibes-git/

**Comment by tio-trom** [comment]
I can't find this one in your repo anymore

**Comment by dr460nf1r3** [comment]
https://github.com/chaotic-aur/packages/issues/2086

**Comment by tio-trom** [comment]
> This seems to require an older `libsoup` than we can provide. thinking

What about https://aur.archlinux.org/packages/goodvibes ?

**Comment by Technetium1** [comment]
`goodvibes` requires the same thing.

**Comment by tio-trom** [comment]
> `goodvibes` requires the same thing.

Ah I see....

**Comment by Technetium1** [comment]
Marking relation to non-git version: #819
