### ISSUE TITLE
bootstrap-dht-git

### ISSUE THREAD

**Issue by heroku-miraheze** [chaotic-aur/packages#823]
https://aur.archlinux.org/packages/bootstrap-dht-git/

**Comment by heroku-miraheze** [comment]
Why pkg broken???

**Comment by dr460nf1r3** [comment]
https://builds.garudalinux.org/repos/chaotic-aur/logs/bootstrap-dht-git.log

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.
