### ISSUE TITLE
App Request

### ISSUE THREAD

**Issue by linux6os** [chaotic-aur/packages#824]
Pamac-All - https://aur.archlinux.org/packages/pamac-all
(And Its Dependenices)
Lightly-Qt - https://aur.archlinux.org/packages/lightly-qt/
Snapd - https://aur.archlinux.org/packages/snapd/
(and its dependencies)
Neofetch - https://github.com/linux6os/apps/raw/master/x86_64/neofetch-git-7.1.0.r137.g05dbc61d-1-any.pkg.tar.zst
(with Aravalli logo)

**Comment by dr460nf1r3** [comment]
We sadly can't add anything depending on snapd as written in the README of this repo already. 
As for the neofetch, we already have a version of that in the repo. The rest:
```
chaotic-aur/lightly-qt 0.4.1-1
A modern style for qt applications
```
