### ISSUE TITLE
[Remove] mysql57

### ISSUE THREAD

**Issue by heroku-miraheze** [chaotic-aur/packages#825]
https://aur.archlinux.org/packages/mysql57/

**Comment by xiota** [comment]
Can someone explain the need for `mysql57`?  It is currently not building because of `openssl` issues.  `mysql` (8.0.x) is in chaotic, and `mariadb` (10.11.x) is in extra.

**Comment by dr460nf1r3** [comment]
Given this was requested without justification and in 2021, it would be reasonable to drop it imo.
