### ISSUE TITLE
cpod

### ISSUE THREAD

**Issue by LeSnake04** [chaotic-aur/packages#829]
please add https://aur.archlinux.org/packages/cpod

**Comment by LeSnake04** [comment]
I am curious: why arent you adding the package directly anymore ?

(I am not mad, just woundering what changed)

**Comment by dr460nf1r3** [comment]
Its easier to add a label using a mobile than actually building/sending stuff to git 😁

**Comment by dr460nf1r3** [comment]
The dependency `electron2` sadly doesn't compile cleanly, the AUR page has multiple reports on that as well - no fix since the creation of the package itself in 2020.

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.
