### ISSUE TITLE
The Aseprite packages are violating the Aseprite license

### ISSUE THREAD

**Issue by netthier** [chaotic-aur/packages#835]
Hey, it seems like you're redistributing binaries of Aseprite (#495) which is explicitly prohibited since v1.1.8 due to a new license.

From https://www.aseprite.org/faq/#can-i-redistribute-aseprite:
>  Can I redistribute Aseprite?
No. From August 2016 you cannot redistribute compiled versions of Aseprite. We have replaced the General Public License (GPLv2) with the new Aseprite EULA. The only way to redistribute Aseprite is with an special educational license.
Anyway this does not restrict most users: You can still compile the source code, and use the program to create your assets for commercial games. You can also make contributions to Aseprite or modify its source code for your personal purposes.

Affected packages are aseprite and aseprite-git

I'm not in any way, shape, or form affiliated with Aseprite, so this is not a legal request of any kind.

**Comment by dr460nf1r3** [comment]
Alright, thanks for the heads up!
