### ISSUE TITLE
trafficserver

### ISSUE THREAD

**Issue by heroku-miraheze** [chaotic-aur/packages#837]
https://aur.archlinux.org/packages/trafficserver/

**Comment by dr460nf1r3** [comment]
Appearently requires an existing `trafficserver` group to compile which does not exist in our clean chroot.

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.
