### ISSUE TITLE
biglybt-extreme-mod

### ISSUE THREAD

**Issue by heroku-miraheze** [chaotic-aur/packages#840]
https://aur.archlinux.org/packages/biglybt-extreme-mod/

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.

**Comment by xiota** [comment]
Dropping because absentee maintainer.  Flagged out of date over two years.  Metrics 7.
