### ISSUE TITLE
[Request] gnome-text-editor-git

### ISSUE THREAD

**Issue by IroAlexis** [chaotic-aur/packages#842]
- Link to the package(s) in AUR: [gnome-text-editor-git](https://aur.archlinux.org/packages/gnome-text-editor-git)

- Utility this package has for you:

It allows me to test the application progress that will replace Gedit. It seems that it contains Builder features that Gedit doen't have. 

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [x] YES
  - [ ] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO (I couldn't test because I don't have glib 2.69 package but it is maybe a problem for you)

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by PedroHLC** [comment]
Sorry, this issue does not follow our new template.

Please, either:
1. open a new issue;
2. edit the first post to include [this template](https://github.com/chaotic-aur/packages/blob/main/.github/ISSUE_TEMPLATE.md) and then re-open this issue.

**Comment by IroAlexis** [comment]
Oh sorry and my bad, I didn't see that we had to follow an issue template. I'm going to look at this ! Thanks

**Comment by PedroHLC** [comment]
> Oh sorry and my bad, I didn't see that we had to follow an issue template. I'm going to look at this ! Thanks

don't worry, that's new
