### ISSUE TITLE
[Issue] yuzu-git requires fmt

### ISSUE THREAD

**Issue by Krutonium** [chaotic-aur/packages#845]
As the title says, Yuzu needs fmt installed as a regular dependency, and not a makedepend, unlike what the pkgbuild seems to imply (https://gitlab.com/tallero/yuzu-git-aur/-/blob/master/PKGBUILD#L30)

**Comment by dr460nf1r3** [comment]
Should be fixed with this :) Please also notify the maintainer so everyone benefits from this. 
https://github.com/chaotic-aur/interfere/commit/21a0887113fe678eb090e483aaf5ef55f7df23f3
