### ISSUE TITLE
[Request] cpod

### ISSUE THREAD

**Issue by LeSnake04** [chaotic-aur/packages#870]
- Link to the package(s) in AUR:

~~cpod~~
~~cpod-appimage~~
https://aur.archlinux.org/packages/cpod-git

- Utility this package has for you:
It's a good open-source podcast manager

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [x] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO (electron2 missing reported by you in #829)

- Does the package's license allows us to redistribute it?:

  - [X] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES  (this is an contionuation of #829)

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

- Have you tested if the latest version of the package builds in a clean chroot?:

  - [ ] YES
  - [ ] NO

**Comment by PedroHLC** [comment]
Thanks for re-opening the issue, and sorry for the trouble!

**Comment by LeSnake04** [comment]
I made a package named [cpod-appimage](https://aur.archlinux.org/packages/cpod-appimage/). Maybe add it insstead since its working

**Comment by dr460nf1r3** [comment]
Sure thing! :)

**Comment by tio-trom** [comment]
How about add the git package too https://aur.archlinux.org/packages/cpod-git?

**Comment by xiota** [comment]
The `git` package exports `NVM_DIR` to `$HOME/.nvm`.  Where does that go on the build server?  Is it a persistent or transient location?

**Comment by xiota** [comment]
Planning to drop...

* Uses Electron 2
* Upstream development discontinued
* Available on flathub: https://flathub.org/apps/com.github.z.Cumulonimbus

**Comment by LeSnake04** [comment]
Makes sense. Last time I used it was kinda buggy anyway so I switched to kasts. And if people still wanna use it they can still compile it or use the appimage/flatpak

**Comment by dr460nf1r3** [comment]
> * Uses Electron 2

What the ...

**Comment by tio-trom** [comment]
> Planning to drop...
> 
>     * Uses Electron 2
> 
>     * Upstream development discontinued
> 
>     * Available on flathub: https://flathub.org/apps/com.github.z.Cumulonimbus

Makes sense.
