### ISSUE TITLE
[pkg request] linux-vfio-lts

### ISSUE THREAD

**Issue by JuniorJPDJ** [chaotic-aur/packages#873]
## 👶 For requesting new packages

- Link to the package(s) in AUR: [linux-vfio-lts](https://aur.archlinux.org/packages/linux-vfio-lts/)

- Utility this package has for you:

  It's fallback when linux-vfio fails somehow. It's used as kernel in hypervisor for GPU (and other PCI) passthrough machines.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by xiota** [comment]
@JuniorJPDJ Do you still use the `linux-vfio` and `linux-vfio-lts` packages?

**Comment by JuniorJPDJ** [comment]
Yes, why?

**Comment by xiota** [comment]
The AUR packages were unmaintained for a long while.  I adopted and updated them.  Want to know if the patches are still working.

For Linux 6.8, the patches are causing a linker error, so hold off updating to any VFIO kernel 6.8.  Hoping to figure out how to fix by 6.8.1.

**Comment by JuniorJPDJ** [comment]
Sure, I'll boot the gaming PC to test. Thanks for the info :D

**Comment by xiota** [comment]
>  boots up my VM with GPU and USB controller passthrough (this one needs ACS patch)

That is interesting... I recall disabling the patches while trying to figure out reason for link failures.  Maybe ACS patch is no longer needed?  Would you mind trying another 6.8 kernel, like linux-mainline?
