### ISSUE TITLE
[outdated] linux-vfio

### ISSUE THREAD

**Issue by JuniorJPDJ** [chaotic-aur/packages#874]
## 👴 For reporting outdated packages

- Link to latest build: [linux-vfio.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/linux-vfio.log)

- Package name: `linux-vfio`

- Latest build: `5.12.15.arch1-2`

- Latest version available: `5.13.9.arch1-2`

- Have you tested if the latest version of the package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

Last build log is from 2021-07-13 09:24, when package got updates at least few times in this time. Are autoupdates enabled and working?

**Comment by PedroHLC** [comment]
>  Are autoupdates enabled and working?

Yeah, the package is taking more than the time limit (4 hours) to finish building...
I'll add `-j $(nproc)` that's missing.

**Comment by PedroHLC** [comment]
I'm testing it right now, would be easier if this package used tarballs instead of fetching git, github can be slow when fetching a 30Gb repository...

**Comment by PedroHLC** [comment]
Ok, @JuniorJPDJ please test it, and if it works, feel free to close this issue.

**Comment by JuniorJPDJ** [comment]
Thanks ;)
