### ISSUE TITLE
[Request] xfce-theme-manager

### ISSUE THREAD

**Issue by MANICX100** [chaotic-aur/packages#876]
- Link to the package(s) in AUR: [https://aur.archlinux.org/packages/xfce-theme-manager/](https://aur.archlinux.org/packages/xfce-theme-manager/)

- Utility this package has for you: Quickly download and use XFCE/GNOME GTK themes without moving files around.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by xiota** [comment]
Dropped because depends on EOL GTK2.  Metrics 34.
