### ISSUE TITLE
[Request] targetcli-fb

### ISSUE THREAD

**Issue by JuniorJPDJ** [chaotic-aur/packages#877]
### Packages

https://aur.archlinux.org/packages/targetcli-fb

Depends:
https://aur.archlinux.org/packages/python-rtslib-fb

### Purpose

It allows me to setup iSCSI target and manage block devices for VMs using vhost SCSI controller (the lowest penalty on IO)

### License

Apache-2.0

**Comment by xiota** [comment]
@JuniorJPDJ Do you still use this package?

**Comment by Technetium1** [comment]
Just flagged out of date as well: https://aur.archlinux.org/pkgbase/targetcli-fb/flag-comment

**Comment by Technetium1** [comment]
Maintainer still hasn't touched the package since I flagged it. This won't be added if it isn't updated.

**Comment by xiota** [comment]
Maintainer updated in June (5 months after release).  I had wanted to know whether this package is still useful.  Since it is, will close this.  However, package is not up to current packaging standards, so it may be dropped if it breaks.

**Comment by xiota** [comment]
Dropping because AUR package is orphaned.  Metrics 4.

**Comment by antermin** [comment]
Since mid-June 2025, @johnlane (`starfry` on AUR) has become the maintainer of the AUR package.

Can you please consider re-adding this package?
