### ISSUE TITLE
[Request] obs-hevc-vaapi-git

### ISSUE THREAD

**Issue by ArinL** [chaotic-aur/packages#879]
## 👶 For requesting new packages

- Link to the package(s) in AUR: https://aur.archlinux.org/packages/obs-hevc-vaapi-git/

- Utility this package has for you:

  It's OBS Studio but with HEVC VAAPI support built in, particularly in my case I'll be able to record using my 6700 XT's  H265 hardware encoder, which is superior to AMD's H264 encover.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [x] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [x] YES
  - [ ] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by dr460nf1r3** [comment]
The package builds but crashes whenever settings are trying to be opened. I provided logs at its AUR page.
