### ISSUE TITLE
[Request] bcachefs-tools-git

### ISSUE THREAD

**Issue by Architector4** [chaotic-aur/packages#883]
Note:

- We will delete issues not following this template!
- You can add new information besides the ones required here.
- You can delete the subsections that are not related to your issue.

## 👶 For requesting new packages

- Link to the package(s) in AUR: https://aur.archlinux.org/packages/bcachefs-tools-git/

- Utility this package has for you:

Create and perform operations on bcachefs filesystems. This would also be supplementary to linux-tkg-* packages already in this repo, which also feature bcachefs patches.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [x] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [x] YES
  - [ ] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by xiota** [comment]
Dropping because `extra/bcachefs-tools` is available and low usage. Metrics 4.

Last release was last month.  Tagged releases are reasonably frequent, about 1-3 months.
