### ISSUE TITLE
[Request] ttf-twemoji, ttf-twemoji-git

### ISSUE THREAD

**Issue by memreyagci** [chaotic-aur/packages#885]
### Package:

https://aur.archlinux.org/packages/ttf-twemoji
https://aur.archlinux.org/packages/ttf-twemoji-git

### Purpose:

It's an emoji package of Twitter emojis.

### Benefits:

They are needed to view emojis because most window managers don't come with one.

### Building:

clean chroot

### Copyright:

MIT, CC-BY-4.0

### Expected Interest:

Some

### Already available?

No

### Unique request?

Yes

### Banned package?

No

**Comment by xiota** [comment]
Switched to `ttf-twemoji-git` for following reasons:

* `aur/ttf-twemoji`, `aur/ttf-twemoji-color`, and `aur/ttf-twemoji-color-git` all do not follow package guidelines.  (Different for each one.)
* Twemoji 15.x releases are not available elsewhere.  Is this a Chaotic AUR exclusive?

**Comment by temeraire-cx** [comment]
Thanks for the request. Some parts of the issue need attention:

- **Title**: The title must be `[Request] package_name`, `[Rebuild] package_name` or `[Issue] package_name`.

Please fix the sections above. The issue closes automatically in one week without an answer.
