### ISSUE TITLE
[Request] obs-studio-browser

### ISSUE THREAD

**Issue by dankcatlord** [chaotic-aur/packages#886]
## 👶 For requesting new packages

- Link to the package(s) in AUR:

  [obs-studio-browser](https://aur.archlinux.org/packages/obs-studio-browser)

- Utility this package has for you:

  This package provides OBS Studio with the browser source and docks which aren't available in the [obs-studio](https://archlinux.org/packages/?q=obs-studio) package. They allow users to add things such as chat windows to their streams.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [x] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by xiota** [comment]
Dropping this because duplicates functionality of `obs-studio-tytan652` (same maintainer)
