### ISSUE TITLE
[Remove] ocs-url

### ISSUE THREAD

**Issue by MANICX100** [chaotic-aur/packages#887]
- Link to the package(s) in AUR: [https://aur.archlinux.org/packages/ocs-url](https://aur.archlinux.org/packages/ocs-url)

- Utility this package has for you: Install GTK theme files without command line or pling store app.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by xiota** [comment]
Dropped because depends on EOL Qt5.  Last upstream commit was in 2019.  Comment on aurweb indicates this isn't actually useful anymore.  Metrics 56.

**Comment by Technetium1** [comment]
It is some form of useful, but Qt5 is a problem. https://forum.garudalinux.org/t/chaotic-aur-packages-requests-recompilation-reports/26/1223

**Comment by temeraire-cx** [comment]
This request was not created with an issue template. Please resubmit it with the request or rebuild template.
