### ISSUE TITLE
[Request] sardi-icons

### ISSUE THREAD

**Issue by ghost** [chaotic-aur/packages#890]
## 👶 For requesting new packages

- Link to the package(s) in AUR: https://aur.archlinux.org/packages/sardi-icons/

- Utility this package has for you:

yet another good icon theme for linux desktops

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [x] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES
  - [ ] 
- Have you tested if the latest version of the package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

**Comment by tio-trom** [comment]
Cannot find this package in your repo anymore.

**Comment by dr460nf1r3** [comment]
https://github.com/chaotic-aur/packages/issues/2086

**Comment by Technetium1** [comment]
Done
