### ISSUE TITLE
godot-git is outdated

### ISSUE THREAD

**Issue by caniko** [chaotic-aur/packages#897]
godot-git is no longer on [AUR](https://aur.archlinux.org/packages/godot-git/). I found by encountering [this error](https://github.com/godotengine/godot/issues/50969) while using the live version on chaotic-aur.

Is it possible to re-upload the AUR package, and update it to the most recent version? The PKGBUILD should be present in the mirrors.

[List](https://aur.archlinux.org/packages/?O=0&K=godot) of all godot packages on AUR.

**Comment by dr460nf1r3** [comment]
I can't find information about why this package was removed from AUR in the maillists, its still available for cloning though if you have an AUR account: `ssh://aur@aur.archlinux.org/godot-git.git`
If you want to maintain the package, that's fine. I'm not really interested in maintaining it myself though.

**Comment by dr460nf1r3** [comment]
Aaaand its back in Chaotic-AUR too :D
