### ISSUE TITLE
[Request] stacer-bin

### ISSUE THREAD

**Issue by Smart123s** [chaotic-aur/packages#898]
## 👶 For requesting new packages

- Link to the package(s) in AUR: https://aur.archlinux.org/packages/stacer-bin/

- Utility this package has for you:

  It's a cool resource monitoring tool for Linux.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [x] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by dr460nf1r3** [comment]
Why `stacer-bin` instead of `stacer`? Both seem equally up to date 🤔

**Comment by Smart123s** [comment]
I have switched to chaotic-aur today, and I have used the -bin package, because it was faster to install. Didn't even thought about checking non -bin packages. I will do it in the future.

**Comment by dr460nf1r3** [comment]
`stacer` is already present in the repo, please use that one.
