### ISSUE TITLE
[Remove] vimiv-qt, vimiv-qt-git

### ISSUE THREAD

**Issue by WitherCubes** [chaotic-aur/packages#913]
## 👶 For requesting new packages

- Link to the package(s) in AUR: [vimiv-qt](https://aur.archlinux.org/packages/vimiv-qt), [vimiv-qt-git](https://aur.archlinux.org/packages/vimiv-qt-git)

- Utility this package has for you:
An image viewer with vim-like keybindings

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [x] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [x] YES
  - [ ] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by xiota** [comment]
Dropped because fails to build with Python 3.14 and still depends on EOL Qt5.

Metrics:

* vimiv-qt # 9
* vimiv-qt-git # 5
