### ISSUE TITLE
[Issue] joplin-desktop is out of date

### ISSUE THREAD

**Issue by toddzilla57** [chaotic-aur/packages#914]
## 👴 For reporting outdated packages

- Link to latest build ([find it here](https://github.com/laurent22/joplin/archive/refs/tags/v2.3.5.tar.gz)):

- Package name: `joplin-desktop`

- Latest build: `v2.3.5`

- Latest version available: `v2.2.7`

- Have you tested if the latest version of the package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

I was able to select the [AUR build](https://aur.archlinux.org/packages/joplin-desktop/) through Pamac and install it that way. Built successfully

**Comment by PedroHLC** [comment]
Funny we have joplin ok, but not joplin-desktop.

**Comment by PedroHLC** [comment]
```
╰─λ pacman -Ss joplin
chaotic-aur/joplin 2.3.5-1
    A note taking and to-do application with synchronization capabilities - CLI App
chaotic-aur/joplin-desktop 2.3.5-1
    A note taking and to-do application with synchronization capabilities - Desktop
```

Looks good to me, may take some time to update in the CDN mirror...

**Comment by toddzilla57** [comment]
Thanks! That was fast! Upgraded on my laptop using chaotic repo. Mirror is updated. Thanks again!
