### ISSUE TITLE
[Bug] Cryptomator chaotic package has additional dependencies

### ISSUE THREAD

**Issue by Smart123s** [chaotic-aur/packages#919]
## 🐛 For reporting bugs

- What happens?

  The [Cryptomator package on Chaotic](https://archlinux.pkgs.org/rolling/chaotic-aur-x86_64/cryptomator-1.5.15-2-x86_64.pkg.tar.zst.html) depends on `zulu-16-bin` which is not provided by the Chaotic repository.

- What is expected to happen?

  The [AUR verison of Cryptomator](https://aur.archlinux.org/packages/cryptomator) does not depend on `zulu-16-bin`, so the Chaotic version should also install without it.

- If possible, please attach logs.

```
$ sudo pacman -S cryptomator
resolving dependencies...
warning: cannot resolve "zulu-16-bin", a dependency of "cryptomator"
:: The following package cannot be upgraded due to unresolvable dependencies:
      cryptomator

:: Do you want to skip the above package for this upgrade? [y/N] y
looking for conflicting packages...
 there is nothing to do
```

**Comment by dr460nf1r3** [comment]
Should be fixed, if it works please close the issue :)
`Depends On      : fuse2  java-environment=16  alsa-lib  hicolor-icon-theme  libxtst  libnet  libxrender`
