### ISSUE TITLE
[Request] amdvlk-2021q2.5, lib32-amdvlk-2021q2.5

### ISSUE THREAD

**Issue by watton** [chaotic-aur/packages#923]
- Link to the package(s) in AUR: [amdvlk-2021q2.5](https://aur.archlinux.org/packages/amdvlk-2021q2.5/), [lib32-amdvlk-2021q2.5](https://aur.archlinux.org/packages/lib32-amdvlk-2021q2.5/)

- Utility this package has for you:

  AMD dropped support for Pre-Polaris and Pre-Raven asics and advised to use 2021.Q2.5 or older release.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [X] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [X] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [X] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [X] NO

- Does the package's license allows us to redistribute it?:

  - [X] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [X] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [X] YES

**Comment by PedroHLC** [comment]
Instead, I prefer adding "amdvlk-git", what do you think? Would this cover for you until `2021q3` gets released?

**Comment by watton** [comment]
2021.Q2.5 was the last version with support for Pre-Polaris and Pre-Raven GPUs, so subsequent releases or "amdvlk-git" wouldn't help.
