### ISSUE TITLE
Failed retrieving file 'chaotic-aur.db.sig'

### ISSUE THREAD

**Issue by fred-sheehan** [chaotic-aur/packages#926]
## 🐛 For reporting bugs

- What happens?

> failed retrieving file 'chaotic-aur.db.sig' from ftp.belnet.be : The requested URL returned error: 404
> 
> The repository does exist on the server, and have installed, and re-installed all as per this page;
https://aur.chaotic.cx/

**Comment by dr460nf1r3** [comment]
Uhm, any details?

**Comment by fred-sheehan** [comment]
failed retrieving file 'chaotic-aur.db.sig' from ftp.belnet.be : The requested URL returned error: 404

The repository does exist on the server, and have installed, and re-installed all as per this page;
https://aur.chaotic.cx/

**Comment by fred-sheehan** [comment]
Sorry, new to github..

**Comment by dr460nf1r3** [comment]
You are redirected to this mirror by our geo-mirror, for now you can comment it in `/etc/pacman.d/chaotic-mirrorlist` and choose another mirror close to you to have it working. 
Need to have a look at whats going on with this one.

**Comment by PedroHLC** [comment]
@fred-sheehan But, @dr460nf1r3 , we don't serve database's signed

**Comment by PedroHLC** [comment]
@fred-sheehan We will need some more information: your `pacman.conf`, `chaotic-mirrorlist`, pacman version, and if you are using pure ArchLinux or some fork distro (e.g: Manjaro, Artix)

**Comment by carbon-ui** [comment]
@PedroHLC sir belnet servers are down i think

**Comment by PedroHLC** [comment]
> @PedroHLC sir belnet servers are down i think

I forgot to reply to this yesterday, but nope, they are/were not.

Here you can see a graph of their HTTP status: https://status.chaotic.cx/
And here you can see the timestamp of their last sync: https://status.chaotic.cx/mirrors

Also, this is not related to this issue, next time open a new one :smile_cat:

**Comment by PedroHLC** [comment]
Closing this without feedback from fred in 8 days...
