### ISSUE TITLE
[Outdated] rpcs3-git

### ISSUE THREAD

**Issue by NerosTie** [chaotic-aur/packages#929]
rpcs3-git has not been updated in a while.

![Screenshot_20210909_172210](https://user-images.githubusercontent.com/4572452/132714644-91d2da34-8ea6-4d45-8b88-a8df60b142c9.png)

Even on AUR the version is newer (0.0.18.12703.06f733a7f-1).
## 👴 For reporting outdated packages

- (If available) Link to latest build ([find it here](https://builds.garudalinux.org/repos/chaotic-aur/logs/)): [rpcs3-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/rpcs3-git.log)

- Package name: `rpcs3-git`

- Latest build: `0.0.17.12654.c62deeefd-1`

- Latest version available: `0.0.18.12703.06f733a7f-1` (AUR) or `0.0.18-12727` (Git)

- Have you tested if the latest version of the package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

**Comment by dr460nf1r3** [comment]
No, I'm taking care of it like that as well. Thanks!

**Comment by xiota** [comment]
`ffmpeg` has been updated to version 6.0.  While updating, I saw the messages:
```
:: installing ffmpeg (2:6.0-3) breaks dependency 'libavcodec.so=59-64' required by rpcs3-git
:: installing ffmpeg (2:6.0-3) breaks dependency 'libavutil.so=57-64' required by rpcs3-git
:: installing ffmpeg (2:6.0-3) breaks dependency 'libswscale.so=6-64' required by rpcs3-git
```

I did not see any specific version numbers in the `rpcs3-git` PKGBUILD, so maybe it just needs a rebuild?  Similarly for some other packages that depend on `ffmpeg`?
