### ISSUE TITLE
[Request] surfn-icons-git

### ISSUE THREAD

**Issue by carbon-ui** [chaotic-aur/packages#930]
## 👶 For requesting new packages

- Link to the package(s) in AUR: [https://aur.archlinux.org/packages/surfn-icons-git]

- Utility this package has for you:
Icon Theme Good For MATE & XFCE4 Desktop

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by AvinashReddy3108** [comment]
@carbon-ui Uhh, I'm 100% sure this package exists in ArcoLinux repos.

**Comment by PedroHLC** [comment]
@AvinashReddy3108 
Sorry, why does it matters if it's in ArcoLinux's repos when the op opened the issue in chaotic-aur?

**Comment by AvinashReddy3108** [comment]
@PedroHLC Just saying, OP can have the package from there until it's part of this repo.
