### ISSUE TITLE
[Request] `rocm-opencl-runtime`

### ISSUE THREAD

**Issue by PolpOnline** [chaotic-aur/packages#931]
## 👶 Request of a new package

- Link to the package(s) in AUR: aur.archlinux.org/packages/rocm-opencl-runtime/

- Utility this package has for you:

  Use ROCm

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

- Does the package's license allows us to redistribute it?:

  - [ ] YES
  - [x] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by BrainwreckedTech** [comment]
I'd just like to comment in favor of adding this package if possible.

`rocm-opencl-runtime` covers GCN2 AMD GPUs whereas `opencl-amd` and `opencl-mesa` only goes back to GCN3.  This package has a rather long dependency chain to build on your own.  On top of that, the computers that you'd find GCN2 cards in still are typically not the ones you want to be stuck compiling such a package on.

The license for this package is MIT according to the AUR.

**Comment by Technetium1** [comment]
Added to Community
