### ISSUE TITLE
[Request] kicad-git

### ISSUE THREAD

**Issue by diggit** [chaotic-aur/packages#949]
- Link to the package(s) in AUR: [kicad-nightly](https://aur.archlinux.org/packages/kicad-git/)

- Utility this package has for you:
Up to date (git) kicad with all features that are not yet in stable release. Sometimes, there can be even more than a year between releases.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by diggit** [comment]
Thank you for accepting this package request!
I am not sure how often it's built, but usually once a day is enough.

**Comment by dr460nf1r3** [comment]
You are welcome. I put it to build hourly, if daily would be enough we could move it there as well though. :)

**Comment by diggit** [comment]
IMO hourly builds sound like a waste of resources. There is ususally around 20 commits per day, in kicad repo. Well, it's up to you :)

**Comment by xiota** [comment]
Dropping because this package uses a lot of resources to build and frequently fails.  What makes it intolerable is upstream auto-closes issues by bot.  Metrics 43.

Use `extra/kicad`.  Most recent stable release three weeks ago.  Time between releases appears to be a few months.

**Comment by diggit** [comment]
That is unfortunate. Kicad has stable release approximately once per year. Those in between are only bugfix releases for the stable (no new features).

You could say something similar about freecad #774 . It also uses a lot of resources (I assune) and fails often...

**Comment by Technetium1** [comment]
Freecad does not fail often, and rarely requires intervention https://github.com/chaotic-aur/interfere/commits/master/freecad-git

**Comment by xiota** [comment]
A kicad dev manually re-opened the issue and fixed it.  But still annoying that they even have a bot that auto-closes valid issues.  The commit in question even failed check-in.  Will consider re-adding if I think of a way to make an interfere to skip commits that fail check-in.

**Comment by xiota** [comment]
Closing because `kicad-git` has already been added back to repo.

**Comment by ninetailedtori** [comment]
We have kicad-git back, but could we get prebuilt compressed packages for the kicad-git libraries as well?
https://aur.archlinux.org/packages/kicad-library-nightly
https://aur.archlinux.org/packages/kicad-library-3d-nightly

**Comment by xiota** [comment]
I had forgotten about the request for libraries... how long do they take to build and how big are they?

Update on kicad-git... no problems on builder side since making rebuilds contingent on successful upstream check-in.  Last successful rebuild earlier today.  Metrics 70.
