### ISSUE TITLE
google-chrome, spotify, microsoft-edge-{beta-dev} redistribution permissions?

### ISSUE THREAD

**Issue by fabiscafe** [chaotic-aur/packages#952]
## 🐛 For reporting bugs

chaotic aur distributes google-chrome microsoft-edge-{beta,dev} and spotify who are prohibited to redistribute by 3rd party without granted rights to do so. I couldnt find any text for permission

The terms are here:
* microsoft-edge: https://docs.microsoft.com/en-us/legal/microsoft-edge/microsoft-edge-devtools-license-terms; inside Edge  edge://terms, right before the download at https://www.microsoftedgeinsider.com/en-us/download/?platform=linux-deb
* Spotify: https://www.spotify.com/us/legal/end-user-agreement/
* Google Chrome: https://policies.google.com/terms#toc-software, Inside Chrome about Google Chrome:
```
Google Chrome and Chrome OS Additional Terms of Service
Last modified: 01 January, 2021

By using Chrome or Chrome OS, you agree to the Google Terms of Service located at https://policies.google.com/terms and these Google Chrome and Chrome OS Additional Terms of Service.
...
```

### What is expected to happen?

A permission-to-redistribute-text should be visible somewhere, if not available those packages should be dropped.

**Comment by juxuanu** [comment]
About Spotify:
Flathub redistributes the snap of Spotify: https://github.com/flathub/com.spotify.Client/blob/8b1304407df83ed959131956903541974504fe60/com.spotify.Client.json#L258
If they do, why wouldn't they in Chaotic?

**Comment by BrainwreckedTech** [comment]
May want to point out the individual clauses that you believe are being violated, so the devs don't have to wade through oceans of text.

Microsoft Edge:

> 3. SCOPE OF LICENSE. The software is licensed, not sold. Microsoft reserves all other rights. Unless applicable law gives you more rights despite this limitation, you will not (and have no right to):
> ...
> e. share, publish, distribute, or lend the software, provide the software as a stand-alone hosted solution for others to use, or transfer the software or this agreement to any third-party.

**Comment by BrainwreckedTech** [comment]
Google:

You may not copy, modify, distribute, sell, or lease any part of our services or software. Also, you may not reverse engineer or attempt to extract any of our source code unless you have our written permission or applicable law lets you do so.

**Comment by BrainwreckedTech** [comment]
I can't find anything in the Spotify link concerning software distribution.  The distribution covered in the ToS concerns IP rights of the conent distributed by Spotify, not the software itself.
