### ISSUE TITLE
[Request] autokey-{common,gtk,qt}

### ISSUE THREAD

**Issue by BrainwreckedTech** [chaotic-aur/packages#953]
## 👶 For requesting new packages

- Link to the package(s) in AUR:

  [autokey-common](https://aur.archlinux.org/packages/autokey-common/)
  [autokey-gtk](https://aur.archlinux.org/packages/autokey-gtk/)
  [autokey-qt](https://aur.archlinux.org/packages/autokey-qt/)
  
- Utility this package has for you:

  Extremely useful hotkey program.  My main personal use is to trigger common symbols not found on the US keyboard layout.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [x] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES - GPL3
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

![Screenshot_20210922_083331](https://user-images.githubusercontent.com/3752022/134344214-0ff48b23-8147-4a38-a12b-86a25762af02.png)

**Comment by tio-trom** [comment]
I see this package was removed. I tested it from AUR and it works quite well. It is also quite a unique package allowing you to bind keys to scripts and what not. I see it is not updated in 9 months - is this the reason why it was removed https://github.com/autokey/autokey/issues ?

**Comment by xiota** [comment]
The package was broken and needed to be rebuilt.  It will be back eventually.
