### ISSUE TITLE
[Request] mysql

### ISSUE THREAD

**Issue by SunnyRaj84348** [chaotic-aur/packages#957]
## 👶 For requesting new packages

- Link to the package(s) in AUR: [mysql](https://aur.archlinux.org/packages/mysql)

- Utility this package has for you:

  MySQL Community Edition is Open Source Relational Database Management System.
  I use MySQL for my personal projects due to its performance and resource friendly nature.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [x] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by dr460nf1r3** [comment]
There are weird things [going on here](https://builds.garudalinux.org/repos/chaotic-aur/logs/mysql.log), happening on different machines.

**Comment by dr460nf1r3** [comment]
Oh it actually builds now? 🤯

**Comment by Technetium1** [comment]
Sure does!!! :smiley:
