### ISSUE TITLE
[Request] dot-bin

### ISSUE THREAD

**Issue by wouu** [chaotic-aur/packages#959]
## 👶 For requesting new packages

- Link to the package(s) in AUR: [dot-bin](https://aur.archlinux.org/packages/dot-bin)

- Utility this package has for you:

  it's a browser based on firefox that claims to be privacy-oriented, ad-blocking, and easily customisable.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [X] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [X] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [X] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [X] NO

- Does the package's license allows us to redistribute it?:

  - [X] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [X] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [X] YES

**Comment by dr460nf1r3** [comment]
Do you think its worth adding the package? The binary is completely outdated and it doesn't seem like it will be updated any time soon. I'm following the development myself :)

**Comment by wouu** [comment]
> Do you think its worth adding the package? The binary is completely outdated and it doesn't seem like it will be updated any time soon. I'm following the development myself :)

if `dot-bin` is outdated, then would it be viable to add [`dot-git`](https://aur.archlinux.org/packages/dot-git) instead? i attempted to compile it in a clean chroot, but i got some errors relating to not setting a git email (i'll try to get the full error message and send it in a minute). however because i'm crap at building packages, and git in general, it could just be my fault for not specifying some required options or something. if this is an error on my behalf, and not to do with the aur package itself, then would you or somebody else mind verifying that there are no other errors during the compilation? thanks in advance

**Comment by dr460nf1r3** [comment]
There is an issue about bringing builds back https://github.com/dothq/browser/issues/610
I'm assuming the -bin can be updated after that is completed first. The -git version PKGBUILD is outdated and tries to build from FF 87 while the current is 89 appearently so its not exactly useful as well :/

**Comment by Technetium1** [comment]
There's a [planned name change](https://aur.archlinux.org/packages/dot-bin#comment-833068):
> I'm working towards a name change. The planned new name is "dot-browser". I'll push a new package soon and submit a request for this one to be merged into the new one.

That was 2021-10-26 and there have been no comments from the maintainer since...

**Comment by dr460nf1r3** [comment]
Actually, there has been very little activity at the projects git repository as well. It seems rather abandoned to me 🤔
