### ISSUE TITLE
[Request] Nash

### ISSUE THREAD

**Issue by MohammadHisham** [chaotic-aur/packages#963]
## 👶 For requesting new packages

- Link to the package(s) in AUR: [https://aur.archlinux.org/packages/nash-git/]

- Utility this package has for you:

A system shell that attempts to be more safe and give more power to user.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by MohammadHisham** [comment]
@dr460nf1r3 due to a recent change in pkgbuild that bug has happened

**Comment by dr460nf1r3** [comment]
Recent? It was last updated in 2018 👀

**Comment by MohammadHisham** [comment]
@dr460nf1r3 this package does not satisfy the AUR rules and will be removed by some days
its just a waste of space
