### ISSUE TITLE
 [Request] pcsx2-git

### ISSUE THREAD

**Issue by Noobao** [chaotic-aur/packages#964]
### Packages

Custom package:
https://github.com/chaotic-aur/packages/tree/main/pcsx2-git

Reference:
https://aur.archlinux.org/packages/pcsx2
https://aur.archlinux.org/packages/pcsx2-git

### Purpose

Emulating ps2 games.

### License

GPL-3.0-only, LGPL-3.0-only

**Comment by dr460nf1r3** [comment]
Fails to build currently.

**Comment by xiota** [comment]
Because of some past dependency issues, `aur/pcsx2-avx-git` + interfere is used to build `chaotic-aur/pcsx2-git`.

Although issues should now be resolved, the interfere has been retained because the -avx- package is easier to update.  This may or may not change with new build system.
