### ISSUE TITLE
where do i find .zst packages ??

### ISSUE THREAD

**Issue by D0nnieD4rk0** [chaotic-aur/packages#965]
i thought id find them here because i dont want an extra repo just 1 or 2 packages from it

**Comment by dr460nf1r3** [comment]
Have a look at the mirrorlist at aur.chaotic.cx, packages are distributed there.

**Comment by PedroHLC** [comment]
https://aur.chaotic.cx/mirrorlist.txt

Replace `$repo` with `chaotic-aur`, and `$arch` with `x86-64`, like: http://cdn-mirror.chaotic.cx/chaotic-aur/x86_64
