### ISSUE TITLE
Clementine-git Installs But Will Not Run

### ISSUE THREAD

**Issue by Kandelai** [chaotic-aur/packages#967]
- Link to the package(s) in AUR: [put link here](https://example.com)

https://archlinux.pkgs.org/rolling/chaotic-aur-x86_64/clementine-git-1.4.0rc1.r442.g78d4c4f3f.0.g78d4c4f3f-1-x86_64.pkg.tar.zst.html

- Utility this package has for you:

 Music App

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [x ] YES
  - [ ] No, but yes for a great amount.
  - [ ] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [x ] YES
  - [ ] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

It is already in chaotic-aur

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x ] NO

- Does the package's license allows us to redistribute it?:

  - [ x] YES
  - [ ] No clue.
  - [ ] No, but the author doesn't really care, it's just for bureaucracy.

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x ] YES

## 👴 For reporting outdated packages

- (If available) Link to latest build ([find it here](https://builds.garudalinux.org/repos/chaotic-aur/logs/)): [some-package.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/some-package.log)

- Package name: `some-package`

- Latest build: `v0.0.0.r0.gc0ffec0ffe`

- Latest version available: `v1.0.0.r100.gdeadbeef`

- Have you tested if the latest version of the package builds in a clean chroot?:

  - [ ] YES
  - [ ] NO

## 🐛 For reporting bugs

- What happens?
- 
The application installs but will not run. I ran it through terminal and it produced the following error;

'clementine: error while loading shared libraries: libprotobuf.so.23: cannot open shared object file: No such file or directory'

I then uninstalled it and installed the same version from the community repo and it worked/opened, and ran, so the issue is with the application in Chaotic-aur.

- What is expected to happen?

  The application to open and play music.

- If possible, please attach logs.

Don't have logs but here is my system info;
Operating System: Garuda Linux
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.14.8-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 6 × Intel® Core™ i5-9600K CPU @ 3.70GHz
Memory: 15.5 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2

- Depending on how critical is making this information available, please send it to [critical at chaotic dot cx](mailto:critical@chaotic.cx)

- Describe it briefly: Include the attacking vector, the possible outcomes and, if possible, solutions.

**Comment by dr460nf1r3** [comment]
Got any useful logs when starting the application via terminal?
