### ISSUE TITLE
[Request] gdm-tools-git & gdm-settings-git

### ISSUE THREAD

**Issue by realmazharhussain** [chaotic-aur/packages#970]
## 👶 Requesting new package

- Link to the package in AUR: [gdm-tools-git](https://aur.archlinux.org/gdm-tools-git.git) & [gdm-settings-git](https://aur.archlinux.org/gdm-settings-git.git)

- Utility this package has for me:

  - Change theme and background image/color of GDM (GNOME's Login/Display Manager
  - Extract the default GNOME-Shell theme and apply user-defined CSS to it
  - Apply current GNOME settings to GDM.

- Do you consider this package(s) to be useful for **every** chaotic user?:

  - [ ] YES
  - [ ] No, but yes for a great amount.
  - [x] No, but yes for a few.
  - [ ] No, it's useful only for me.

- Do you consider this package(s) to be useful for feature testing/preview (e.g: mesa-aco, wine-wayland)?:

  - [ ] YES
  - [x] NO

- Are you sure we don't have this package already (test with `pacman -Ss <pkgname>`)?:

  - [x] YES

- Have you tested if this package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

- Does the package's license allows us to redistribute it?:

  - [x] YES
  - [ ] NO

- Have you searched the [issues](https://github.com/chaotic-aur/packages/issues) to ensure this request is new (not duplicated)?:

  - [x] YES

- Have you read the [README](https://github.com/chaotic-aur/packages#banished-and-rejected-packages) to ensure this package is not banned?:

  - [x] YES

**Comment by j1cs** [comment]
@dr460nf1r3 @realmazharhussain 
can we update this? now is called [gdm-setings](https://github.com/realmazharhussain/gdm-settings)

**Comment by realmazharhussain** [comment]
[gdm-tools](https://github.com/realmazharhussain/gdm-tools] and [gdm-settings](https://github.com/realmazharhussain/gdm-settings] are two different projects.

**Comment by xiota** [comment]
Dropping `gdm-tools-git` because it runs `install.sh` script that attempts to run `sudo` and `pacman -S`.  Package fails to build successfully because `pacman` command fails or times out from lack of user input.

Will not re-add package unless call to non-standard install script is removed, as calls to custom scripts can mask poor packaging practices.
