### ISSUE TITLE
`nicotine-plus-git` is outdated

### ISSUE THREAD

**Issue by BachoSeven** [chaotic-aur/packages#981]
## 👴 For reporting outdated packages

- There seems to be nothing here: [nicotine-plus-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/nicotine-plus-git.log)

- Package name: `nicotine-plus-git`

- Have you tested if the latest version of the package builds in a clean chroot?:

  - [x] YES
  - [ ] NO

## 🐛 For reporting bugs

- What happens?

  The package hasn't been updated since the 2nd of September

- What is expected to happen?

  The package should be built in garuda-cluster/hourly

**Comment by dr460nf1r3** [comment]
Its really a weird thing. I rebuilt it manually again, gotta try moving it in another routine.
