### ISSUE TITLE
[Outdated] guiscrcpy-git

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/packages#996]
## 👴 For reporting outdated packages

- Link to latest build [here](https://builds.garudalinux.org/repos/chaotic-aur/logs/guiscrcpy-git.log)

- Package name: `guiscrcpy-git`

- Latest build: `4.11.0.r1265.gffc2243-1`

- Latest version available: `4.10.0.r1242.gdd301d0-1`

- Have you tested if the latest version of the package builds in a clean chroot?:

  - [ ] YES
  - [x] NO

**Comment by Technetium1** [comment]
@dr460nf1r3 It's dependency may also need to be rebuilt, as `python-pynput` is `1.7.3-5` in Chaotic-AUR, but `1.7.4-1` is available. https://github.com/chaotic-aur/packages/blob/2cebcaa50722ade62816860bb63df5ac5db0a7ec/dragon-cluster/hourly.txt#L69

**Comment by xiota** [comment]
Dropping because depends on broken package (`pyside2`) that I'm not interested in fixing.
